### ISSUE TITLE
FLUX Fill example not working due to Not Found for url: https://huggingface.co/black-forest-labs/FLUX.1-Fill-dev/resolve/main/model_index.json

### ISSUE THREAD

**Issue by petergerten** [huggingface/diffusers#10010]
### Describe the bug

FLUX Fill is example not working due to Not Found for url: https://huggingface.co/black-forest-labs/FLUX.1-Fill-dev/resolve/main/model_index.json

### Reproduction

Execute the FLUX Fill example according to doc.

### System Info

diffusers main

**Comment by a-r-r-o-w** [comment]
The Diffusers weights PR have not yet been merged into the repo. It should be usable after merged, but for now you need to specify revision="refs/pr/4" in from_pretrained.

**Comment by petergerten** [comment]
solved via syntax in https://github.com/huggingface/diffusers/pull/9985
(add ' revision="refs/pr/4"')
