### ISSUE TITLE
Add Support for Lightricks/LTX-Video Model and Video Generation Features (text2video, image2video, video2video) in Diffusers with Sequential CPU Offload Compatibility

### ISSUE THREAD

**Issue by BasimBashir** [huggingface/diffusers#10034]
**Is your feature request related to a problem? Please describe.**
Currently, the Diffusers library does not provide native support for advanced video generation tasks such as text-to-video (text2video), image-to-video (image2video), or video-to-video (video2video) generation for lighttricks/LTX-Video model. With the growing demand for generative AI in video content creation, incorporating these features would significantly enhance the utility of the library for researchers and developers.

Additionally, the current implementation of video generation models, such as [Lightricks/LTX-Video](https://huggingface.co/Lightricks/LTX-Video), does not support sequential_cpu_offload. This feature is essential for users with low VRAM devices as it allows efficient memory management by offloading parts of the model to the CPU, enabling smoother generation processes on limited hardware.

**Describe the solution you'd like.**
Integrate support for video generation tasks into the Diffusers library by utilizing models like the one provided by [Lightricks/LTX-Video](https://huggingface.co/Lightricks/LTX-Video). This could include:

- Text-to-video generation capabilities.
- Image-to-video transformations.
- Video-to-video editing and generation.

Additionally, ensure compatibility with sequential_cpu_offload to make these features accessible to users with low VRAM devices. This would help democratize access to video generation tasks and expand the potential user base.

**Describe alternatives you've considered.**
1. Using separate video generation libraries, but this creates fragmentation and complicates workflows.
2. Adapting text-to-image models for video generation with additional scripting, but this is resource-intensive and not optimized for video-specific tasks.
3. Manually managing memory usage for low VRAM devices, which is cumbersome and error-prone compared to utilizing sequential_cpu_offload.

**Additional context.**
The [Lightricks/LTX-Video](https://huggingface.co/Lightricks/LTX-Video) model on Hugging Face appears to provide state-of-the-art capabilities for these tasks. Incorporating such advanced models into Diffusers would streamline workflows for users requiring video generation features. Adding compatibility with sequential_cpu_offload would further enhance usability on low-resource devices, ensuring smoother performance and broader accessibility.

This feature would position Diffusers as a leader in both image and video generative tasks, enhancing its appeal in the broader AI community.

**Comment by sayakpaul** [comment]
This time we got a bit ahead of time all hail to @a-r-r-o-w  ;) 
https://github.com/huggingface/diffusers/pull/10021

**Comment by sayakpaul** [comment]
Closing this to track in https://github.com/huggingface/diffusers/issues/9995.
