### ISSUE TITLE
Forgot to pass the output sample size in AttnUpBlock2D() in unet_2d_blocks.py

### ISSUE THREAD

**Issue by xyliu6666** [huggingface/diffusers#10039]
### Describe the bug

Hi, I found that the parameter upsample_size was not passed into the upsampler in AttnUpBlock2D() in unet_2d_blocks.py [Line: 2386]. This can result in mismatched dimensions when processing images using AttnUpBlock2D(). This does not seem to have been corrected in the latest GitHub version [v0.31.0]. Thanks!

### Reproduction

see description

### System Info

Diffusers [v0.31.0]

**Comment by sayakpaul** [comment]
Could you provide an example of how it can lead to an error? 

Cc: @yiyixuxu

**Comment by yiyixuxu** [comment]
closing now due to inactivity 
let us know if you're able to provide more info and we will reopen!
