### ISSUE TITLE
Cannot import MochiPipeline

### ISSUE THREAD

**Issue by justahumanb** [huggingface/diffusers#10049]
### Describe the bug

Can't import mochi in colab. When trying have a following error:

ImportError                               Traceback (most recent call last)
[<ipython-input-5-6aeec58dc926>](https://localhost:8080/#) in <cell line: 2>()
      1 import torch
----> 2 from diffusers import MochiPipeline
      3 from diffusers.utils import export_to_video
      4 
      5 pipe = MochiPipeline.from_pretrained("genmo/mochi-1-preview", torch_dtype=torch.bfloat16)

ImportError: cannot import name 'MochiPipeline' from 'diffusers' (/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py)

### Reproduction

!pip install diffusers accelerate transformers
import torch
!pip install -U compel

import torch
from diffusers import MochiPipeline

### System Info

🤗 Diffusers version: 0.31.0
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Running on Google Colab?: Yes
- Python version: 3.10.12
- PyTorch version (GPU?): 2.5.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.5 (gpu)
- Jax version: 0.4.33
- JaxLib version: 0.4.33
- Huggingface_hub version: 0.26.2
- Transformers version: 4.46.2
- Accelerate version: 1.1.1
- PEFT version: 0.13.2
- Bitsandbytes version: not installed
- Safetensors version: 0.4.5
- xFormers version: not installed
- Accelerator: Tesla T4, 15360 MiB
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

 @DN6 @a-r-r-o-w

**Comment by a-r-r-o-w** [comment]
`pip install git+https://github.com/huggingface/diffusers`

Could you try the above? This is a version difference since there hasn't been a diffusers release with Mochi yet. Also make sure to restart your colab env after above command
