### ISSUE TITLE
Token Issue with FluxTransformer2DModel.from_single_file Method

### ISSUE THREAD

**Issue by CyberVy** [huggingface/diffusers#10057]
### Describe the bug

When I use the FluxTransformer2DModel.from_single_file method, the provided token seems to be invalid, and I am unable to download files that require token verification, such as the official Flux model files.

However, I can confirm that the token is valid because when using FluxPipeline.from_single_file to load the official Flux model, all files can be downloaded successfully without any issues.

### Reproduction

```python
from diffusers import FluxTransformer2DModel
FluxTransformer2DModel.from_single_file(“A Local File Path”,token=...)
```
It does not work, and raise an error in the log below.
```python
from diffusers import FluxTransformer2DModel
FluxTransformer2DModel.from_single_file(“A HF URL”,token=...)
```
It works too.
So I think **the problem only exists when a local file path is passed to this method.
When a HF url is passed to it, it works.**
```python
from diffusers import FluxPipeline
FluxPipeline.from_single_file("black-forest-labs/FLUX.1-dev",token=...)
```
It works.

### Logs

```shell
...
HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/transformer/config.json
...
OSError: black-forest-labs/FLUX.1-dev is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `token` or log in with `huggingface-cli login`.
```

### System Info

   - 🤗 Diffusers version: 0.31.0
   - Platform: Linux-6.6.56+-x86_64-with-glibc2.35
   -   Running on Google Colab?: No
   - Python version: 3.10.14
   - PyTorch version (GPU?): 2.4.0 (True)
   - Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
   - Jax version: 0.4.26
   - JaxLib version: 0.4.26.dev20240620
   -  Huggingface_hub version: 0.25.1
   - Transformers version: 4.45.1
   - Accelerate version: 0.34.2
   - PEFT version: 0.13.2
   - Bitsandbytes version: not installed
   - Safetensors version: 0.4.5
   - xFormers version: not installed
   - Accelerator: Tesla T4, 15360 MiB
   - Tesla T4, 15360 MiB
   - Using GPU in script?: No
   - Using distributed or parallel set-up in script?: No

### Who can help?

@DN6 @sayakpaul

**Comment by asomoza** [comment]
I tried with this code:

```python
from diffusers import FluxTransformer2DModel


FluxTransformer2DModel.from_single_file(
    "https://huggingface.co/black-forest-labs/FLUX.1-dev/flux1-dev.safetensors",
    token="hf_XXX",
)
```

With a valid token and it worked without a problem, I can only guess that your problem is still the problem but it's weird that it works with the pipeline and not the transformer model.

You didn't post the diffusers version, are you using the latest one?

**Comment by sayakpaul** [comment]
> it's weird that it works with the pipeline and not the transformer model.

In your code example, you used the model class, though and you said it worked?

**Comment by asomoza** [comment]
yeah, I just loaded it like OP was doing it, didn't do anything else since the issue was supposed to be the access token, is that your question?

**Comment by CyberVy** [comment]
> I tried with this code:
> 
> ```python
> from diffusers import FluxTransformer2DModel
> 
> 
> FluxTransformer2DModel.from_single_file(
>     "https://huggingface.co/black-forest-labs/FLUX.1-dev/flux1-dev.safetensors",
>     token="hf_XXX",
> )
> ```
> 
> With a valid token and it worked without a problem, I can only guess that your problem is still the problem but it's weird that it works with the pipeline and not the transformer model.
> 
> You didn't post the diffusers version, are you using the latest one?

Yes, it's the latest 0.31.0.
Copied from Kaggle console, there is some bug to copy information from kaggle console, so I missed some information.
Sorry for that.
Here is the complete env information.

- 🤗 Diffusers version: 0.31.0
- Platform: Linux-6.6.56+-x86_64-with-glibc2.35
- Running on Google Colab?: No
- Python version: 3.10.14
- PyTorch version (GPU?): 2.4.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26.dev20240620
- Huggingface_hub version: 0.25.1
- Transformers version: 4.45.1
- Accelerate version: 0.34.2
- PEFT version: 0.13.2
- Bitsandbytes version: not installed
- Safetensors version: 0.4.5
- xFormers version: not installed
- Accelerator: Tesla T4, 15360 MiB
Tesla T4, 15360 MiB
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by CyberVy** [comment]
> I tried with this code:
> 
> ```python
> from diffusers import FluxTransformer2DModel
> 
> 
> FluxTransformer2DModel.from_single_file(
>     "https://huggingface.co/black-forest-labs/FLUX.1-dev/flux1-dev.safetensors",
>     token="hf_XXX",
> )
> ```
> 
> With a valid token and it worked without a problem, I can only guess that your problem is still the problem but it's weird that it works with the pipeline and not the transformer model.
> 
> You didn't post the diffusers version, are you using the latest one?

Also, I've try again, you code works.
And I updated the issue with more detailed triggering conditions in the reproduction code.
Thanks for your help.

**Comment by DN6** [comment]
Thanks for flagging @CyberVy. Opened a PR to fix
https://github.com/huggingface/diffusers/pull/10082

When we try to auto fetch the configs needed to load the Flux model we weren't passing in the token. My guess is that you don't have the Flux configs in your HF Cache. 

You can work around it by either setting the `HF_TOKEN` enviroment variable with your token or running `huggingface-cli login` and setting your token that way.

**Comment by yiyixuxu** [comment]
closing as fixed here https://github.com/huggingface/diffusers/pull/10082
let us know if you still have issues and we will reopen!

**Comment by KMiNT21** [comment]
I encountered this issue a long time ago, and now I’ve run into it again.
Can’t the from_single_file() function load a file locally without requiring an internet connection?
Why can’t I pass the config to it somehow? Why does it absolutely need a connection to HF?
