### ISSUE TITLE
syntax error on ctx

### ISSUE THREAD

**Issue by Clement-Lelievre** [huggingface/diffusers#10052]
### Describe the bug

Across [several files](https://github.com/search?q=repo%3Ahuggingface%2Fdiffusers%20CTX&type=code), a bool statement is wrongly constructed IMO

One example: https://github.com/huggingface/diffusers/blob/c96bfa5c80eca798d555a79a491043c311d0f608/scripts/convert_sd3_to_diffusers.py#L14 => instead of checking for truthiness of the function object `is_accelerate_available` itself, it should check for the truthiness of its return value I believe. So parentheses are needed, to call this function.

Proposed fix: 
```python
CTX = init_empty_weights if is_accelerate_available() else nullcontext 
```

### Reproduction

see https://github.com/huggingface/diffusers/blob/c96bfa5c80eca798d555a79a491043c311d0f608/scripts/convert_sd3_to_diffusers.py#L14

### System Info

not relevant

### Who can help?

@yiyixuxu @say

**Comment by sayakpaul** [comment]
@Clement-Lelievre you're right, would you be able to open a PR?

**Comment by Clement-Lelievre** [comment]
will do early next week

**Comment by Clement-Lelievre** [comment]
> @Clement-Lelievre you're right, would you be able to open a PR?

will do early next week
