### ISSUE TITLE
 Missing Section in Optimization Docs

### ISSUE THREAD

**Issue by ParagEkbote** [huggingface/diffusers#10097]
### Describe the bug

There is a missing section in the Optimization section of the diffuser docs.  Its location being here in the ReadMe:

![image](https://github.com/user-attachments/assets/e1d6832d-f248-454b-8c37-92dbbbd897a9)

Web link for the main version: https://huggingface.co/docs/diffusers/main/en/optimization/opt_overview

![image](https://github.com/user-attachments/assets/f1e13bbe-ea7c-4595-a9a6-72ac4f6fa2fd)

After viewing the docs on the stable version, the described methods are already present. They only need to be added with the overview and structured properly.

Web link for stable version: https://huggingface.co/docs/diffusers/optimization/fp16

![image](https://github.com/user-attachments/assets/cb88bedf-34e0-46fa-a08c-55f8b26f4621)

I'd love to resolve it to make the docs more robust and open a PR for the same.

### Reproduction

NA

### Logs

NA

### System Info

NA

### Who can help?

@stevhliu @sayakpaul

**Comment by sayakpaul** [comment]
Thanks for spotting! Feel free to open on a PR if you'd like.

**Comment by stevhliu** [comment]
Good catch! The `opt_overview.md` doc shouldn't exist since its been removed, so its curious that you can still link to it! Anyways, I think if you update the optimization link on `README.md` to point to https://huggingface.co/docs/diffusers/optimization/fp16 that should be fine.
