### ISSUE TITLE
When using load_lora_weights, it prompts that object has no attribute

### ISSUE THREAD

**Issue by Purhythm** [huggingface/diffusers#10154]
### Describe the bug

When following the tutorial in version V0.31.0, specifically the section "Load LoRAs for inference," using the original code :
```
from diffusers import DiffusionPipeline
import torch
pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = DiffusionPipeline.from_pretrained(pipe_id, torch_dtype=torch.float16).to("cuda")
```
results in the following error:
_AttributeError: module 'diffusers' has no attribute 'StableDiffusionXLPipeline'_

Then, I modified the pipeline version I was using as Code 2,
```
from diffusers import DiffusionPipeline
import torch
pipe_id = "stabilityai/stable-diffusion-2-1"
pipe = DiffusionPipeline.from_pretrained(pipe_id, torch_dtype=torch.float16).to("cuda")
pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors", adapter_name="toy")
```
 and the following error occurred:
AttributeError: 'StableDiffusionPipeline' object has no attribute 'load_lora_weights'

The first issue occurred because I followed the diffusers source code directly, so I believe this might be a bug. I'm a newcomer in this field, and if my reasoning is incorrect, I hope you can understand. I would appreciate your help in resolving this.

### Reproduction

1. Code1：
```
from diffusers import DiffusionPipeline
import torch
pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = DiffusionPipeline.from_pretrained(pipe_id, torch_dtype=torch.float16).to("cuda")
```

2. Code2：

```
from diffusers import DiffusionPipeline
import torch
pipe_id = "stabilityai/stable-diffusion-2-1"
pipe = DiffusionPipeline.from_pretrained(pipe_id, torch_dtype=torch.float16).to("cuda")
pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors", adapter_name="toy")
```

### System Info

- `diffusers` version: 0.11.1
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.8.20
- PyTorch version (GPU?): 2.4.1+cu124 (True)
- Huggingface_hub version: 0.25.2
- Transformers version: 4.46.3
- Using GPU in script?: yep，i use " .to("cuda") "
- Using distributed or parallel set-up in script?: I think no

**Comment by hlky** [comment]
> diffusers version: 0.11.1

Try `pip install -U diffusers`

**Comment by edkamesh** [comment]
upgrade diffusers and peft library to the latest version using `pip install -U diffusers peft -q`

**Comment by Purhythm** [comment]
> > diffusers version: 0.11.1
> 
> Try `pip install -U diffusers`

it work, thanks.

**Comment by Purhythm** [comment]
> upgrade diffusers and peft library to the latest version using `pip install -U diffusers peft -q`

thanks
