### ISSUE TITLE
SDXL Pipelines slow loading and inference

### ISSUE THREAD

**Issue by okaris** [huggingface/diffusers#10150]
### Describe the bug

Cached model + lora takes >40 seconds to load and >8 minutes to run a simple image to image task at 1024x1024 

### Reproduction

```
import os
import torch
from PIL import Image
from diffusers import StableDiffusionXLImg2ImgPipeline
from diffusers.schedulers import DPMSolverMultistepScheduler


os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"


base = 'stabilityai/stable-diffusion-xl-base-1.0'
redmond = "artificialguybr/3DRedmond-V1"

base_pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(base, variant="fp16", torch_dtype=torch.float16)
base_pipe.load_lora_weights(redmond)
base_pipe = base_pipe.to('cuda')

base_pipe.scheduler = DPMSolverMultistepScheduler.from_config(
    base_pipe.scheduler.config, 
    use_karras_sigmas=True, 
    algorithm_type="sde-dpmsolver++", 
    final_sigmas_type="zero"
)

image = Image.open("dragon.png")
image = image.resize((1024, 1024))

prompt = "3D Render Style, 3DRenderAF, white background"
image = base_pipe(
    prompt=prompt,
    image=image,
    strength=0.75,
    num_inference_steps=30,
    guidance_scale=4.0,
    output_type="pil",
    width=1024,
    height=1024,
).images[0]
```

### System Info

- 🤗 Diffusers version: 0.31.0
- Platform: Linux-5.15.0-117-generic-x86_64-with-glibc2.35
- Running on Google Colab?: No
- Python version: 3.10.12
- PyTorch version (GPU?): 2.5.1+cu124 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.25.1
- Transformers version: 4.47.0
- Accelerate version: 1.2.0
- PEFT version: 0.14.0
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA H100 80GB HBM3, 81559 MiB
NVIDIA H100 80GB HBM3, 81559 MiB
NVIDIA H100 80GB HBM3, 81559 MiB
NVIDIA H100 80GB HBM3, 81559 MiB
NVIDIA H100 80GB HBM3, 81559 MiB
NVIDIA H100 80GB HBM3, 81559 MiB
NVIDIA H100 80GB HBM3, 81559 MiB
NVIDIA H100 80GB HBM3, 81559 MiB
- Using GPU in script?: Yes

### Who can help?

 @yiyixuxu @sayakpaul @DN6

**Comment by okaris** [comment]
<img width="444" alt="Screenshot 2024-12-09 at 09 07 44" src="https://github.com/user-attachments/assets/e42237f6-516c-4b94-a39a-415080ee8123">
<img width="885" alt="Screenshot 2024-12-09 at 09 08 00" src="https://github.com/user-attachments/assets/7575d885-73fe-47ac-967e-e2b3417880f0">
<img width="622" alt="Screenshot 2024-12-09 at 09 07 25" src="https://github.com/user-attachments/assets/5b81730c-2419-4f7a-a49f-1a51cfe9573a">

**Comment by hlky** [comment]
Can you check usage with `nvidia-smi` or `nvtop` during the generation?

**Comment by hlky** [comment]
`load_image` applies `.convert("RGB")` by default.

The issue with RGBA images being used as latent comes from here:

https://github.com/huggingface/diffusers/blob/6131a93b969f87d171148bd367fd9990d5a49b6b/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py#L712-L713

`VaeImageProcessor` supports `do_convert_rgb` but it's only used in some pipelines, seems we should be using that in most (all?) pipelines.

https://github.com/huggingface/diffusers/blob/6131a93b969f87d171148bd367fd9990d5a49b6b/src/diffusers/pipelines/controlnet/pipeline_controlnet.py#L250

**Comment by hlky** [comment]
As for loading, can you try moving pipe to cuda before loading lora?

**Comment by okaris** [comment]
Thanks, @hlky. The input image/latent issue was indeed due to passing a 4-channel image; converting it to RGB resolved the problem.

Regarding the slow loading issue, it turned out to be unrelated to diffusers. The root cause was likely an infection by the Kinsing malware, a cryptocurrency miner that possibly entered through an unsecured Redis instance in a Docker container. The malware was consuming extensive CPU resources, significantly impacting performance. I’m leaving this information here just in case it helps anyone else in the future.
