### ISSUE TITLE
an error that config.json is not found.

### ISSUE THREAD

**Issue by Zarato2122** [huggingface/diffusers#10169]
### Describe the bug

Whether it is local download and upload or download model from Hugging face official website, after running on the jupter notebook, it shows an error that config.json is not found.

After checking, the locally downloaded file is exactly the same as the official website, but it still reports an error. After changing from Hugging face to download, there is no improvement, and the same error is reported.

### Reproduction

OSError: Error no file named config.json found in directory .......

### System Info

- 🤗 Diffusers version: 0.32.0.dev0
- Platform: Linux-5.4.0-198-generic-x86_64-with-glibc2.17
- Running on Google Colab?: No
- Python version: 3.8.20
- PyTorch version (GPU?): 2.4.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.26.3
- Transformers version: 4.46.3
- Accelerate version: 1.0.1
- PEFT version: 0.7.0
- Bitsandbytes version: not installed
- Safetensors version: 0.4.5
- xFormers version: not installed
- Accelerator: NVIDIA RTX A6000, 49140 MiB
NVIDIA RTX A6000, 49140 MiB
NVIDIA RTX A6000, 49140 MiB
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by hlky** [comment]
Hi @Zarato2122! Can you share the code you're using?

**Comment by Zarato2122** [comment]
Sure.You can check out my code here: [Gist Link](https://gist.github.com/Zarato2122/1acd6b3b3a79cc08c1b663ead4e8bd90)

**Comment by Zarato2122** [comment]
**OSError: Error no file named config.json found in directory /data/ziqiang/czc/diffusers/examples/dreambooth/model.

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.

{'clip_sample_range', 'rescale_betas_zero_snr', 'dynamic_thresholding_ratio', 'thresholding', 'variance_type'} was not found in config. Values will be initialized to default values.**

When I try to run the model, I get the error message above. However, as I mentioned earlier, I checked the downloaded model folder and found that each subfolder does indeed contain the downloaded config.json file. Even without using the local model, if I download it directly from Hugging Face, I still get the same error (missing the config.json file).

My code is mainly based on lora-sdxl. I only modified some necessary parameters in the parse-args function within the lora-sdxl code. Does the model folder need to have a single overarching config.json file? This is really confusing to me.

**Comment by hlky** [comment]
Hi @Zarato2122. You're using `/data/ziqiang/czc/diffusers/examples/dreambooth/model` for both `pretrained_model_name_or_path` and `pretrained_vae_model_name_or_path`, when `pretrained_vae_model_name_or_path` is not `None` it is expected to be the *full* path to the VAE because `subfolder` is not used. Try changing the default back to `None` or pass the full path to VAE including the subfolder. Note that the main use of `pretrained_vae_model_name_or_path` with XL is to use `madebyollin/sdxl-vae-fp16-fix` to enable VAE to run in fp16.

**Comment by Zarato2122** [comment]
Hi @hlky,

Thank you for your suggestion! The problem has been solved.
