### ISSUE TITLE
Raise an error when `len(gligen_images )` is not equal to `len(gligen_phrases)` in `StableDiffusionGLIGENTextImagePipeline`

### ISSUE THREAD

**Issue by abcdefg133hi** [huggingface/diffusers#10172]
To whom it may concern,

I found that when using `StableDiffusionGLIGENTextImagePipeline`, there is no error raised when `len(gligen_images )` is not equal to `len(gligen_phrases)`. And when I dig into the source code, it seems that these two features are zipped together in a for loop during the preprocessing. I guess this will cause the longer one to be clipped unintentionally. (If my understanding is wrong, feel free to correct me.) Is there any possibility to raise an error or at least warning? Thanks in advance.

Source Code: https://github.com/huggingface/diffusers/blob/v0.31.0/src/diffusers/pipelines/stable_diffusion_gligen/pipeline_stable_diffusion_gligen_text_image.py#L689

**Comment by hlky** [comment]
Hi @abcdefg133hi. Thanks for finding this. Your understanding is correct, the longer of `gligen_phrases` and `gligen_images` will be clipped:

```python
for phrase, image in zip(["text", "text1", "text2"], ["image", "image1"]):
    print(phrase, image)
text image
text1 image1
```

We should add this to `check_inputs` and raise an error when `len(gligen_images) != len(gligen_phrases)`. Note that `Copied from` will need to be removed.
https://github.com/huggingface/diffusers/blob/c9e4fab42ca481fe8e0d2456b54ec900fb57730d/src/diffusers/pipelines/stable_diffusion_gligen/pipeline_stable_diffusion_gligen_text_image.py#L450

Would you like to submit a PR?
