### ISSUE TITLE
(Re)implement model cards for the training examples

### ISSUE THREAD

**Issue by anton-l** [huggingface/diffusers#1021]
#748 didn't account for `diffusers.hub_utils.create_model_card()` (called by `hub_utils.push_to_hub()` which was replaced by `repo.push_to_hub()`) that was responsible for creating model cards like https://huggingface.co/anton-l/ddpm-ema-flowers-64 , so now they come out empty.

But since the model card generation logic is now available in `huggingface_hub`, we can start implementing it across all of the the training scripts (not just the unconditional example).

**Comment by patrickvonplaten** [comment]
Agree

**Comment by sayakpaul** [comment]
This has been implemented for most widely used examples.
