### ISSUE TITLE
HunyuanVideoPipeline not support enable_sequential_cpu_offload()？

### ISSUE THREAD

**Issue by zhaoyun0071** [huggingface/diffusers#10239]
### Describe the bug

when use **pipe.enable_sequential_cpu_offload()** for purpose of low vram.

but get error below and  got the black video

```
diffusers\image_processor.py:147: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")
```

_the similar issue：https://github.com/huggingface/diffusers/pull/10136#issuecomment-2545653366_

### Reproduction

```
import torch
from diffusers import HunyuanVideoPipeline, HunyuanVideoTransformer3DModel
from diffusers.utils import export_to_video

model_id = "tencent/HunyuanVideo"
transformer = HunyuanVideoTransformer3DModel.from_pretrained(
    model_id, subfolder="transformer", torch_dtype=torch.bfloat16
)
pipe = HunyuanVideoPipeline.from_pretrained(model_id, transformer=transformer, torch_dtype=torch.float16)
pipe.vae.enable_tiling()
pipe.enable_sequential_cpu_offload()

output = pipe(
    prompt="A cat walks on the grass, realistic",
    height=320,
    width=512,
    num_frames=61,
    num_inference_steps=30,
).frames[0]
export_to_video(output, "output.mp4", fps=15)
```

### System Info

windows 11 
RTX3090
diffusers 0.32.0.dev 5fb3a985173efaae7ff381b9040c386751d643da
torch 2.2.2 cu118

### Who can help?

@DN6 @a-r-r-o-w

**Comment by hlky** [comment]
Could you try with latest PyTorch version? Also what's the driver version from `nvidia-smi`?

**Comment by DN6** [comment]
@zhaoyun0071 Could you also try setting the dtype to `torch.bfloat16` in the Pipeline? It is currently set to `torch.float16` while the transformer is in `torch.bfloat16`

**Comment by zhaoyun0071** [comment]
> @zhaoyun0071 Could you also try setting the dtype to `torch.bfloat16` in the Pipeline? It is currently set to `torch.float16` while the transformer is in `torch.bfloat16`. It could be causing NaNs when decoding latents.

https://github.com/huggingface/diffusers/blob/7667cfcb41dfeb8f217e4314dcf2d561b8ca41d2/docs/source/en/api/pipelines/hunyuan_video.md

```
Recommendations for inference:

Both text encoders should be in torch.float16.
Transformer should be in torch.bfloat16.
VAE should be in torch.float16.
num_frames should be of the form 4 * k + 1, for example 49 or 129.
```

**Comment by SHYuanBest** [comment]
i upgrade the `torch`, and fix the warming

**Comment by zhaoyun0071** [comment]
> i upgrade the `torch`, and fix the warming

solved black video problem？

**Comment by SHYuanBest** [comment]
> > > > i upgrade the `torch`, and fix the warming
> > > 
> > > 
> > > solved black video problem？
> > 
> > 
> > yes, with torch==2.5.1 and without change the default dtype
> > output.mp4
> 
> can you try my code?
> 
> ```
> 
> import torch
> from diffusers import HunyuanVideoPipeline, HunyuanVideoTransformer3DModel
> from diffusers.utils import export_to_video
> 
> model_id = "tencent/HunyuanVideo"
> transformer = HunyuanVideoTransformer3DModel.from_pretrained(
>     model_id, subfolder="transformer", torch_dtype=torch.bfloat16
> )
> pipe = HunyuanVideoPipeline.from_pretrained(model_id, transformer=transformer, torch_dtype=torch.float16)
> pipe.vae.enable_tiling()
> pipe.enable_sequential_cpu_offload()
> 
> output = pipe(
>     prompt="A cat walks on the grass, realistic",
>     height=320,
>     width=512,
>     num_frames=61,
>     num_inference_steps=30,
> ).frames[0]
> export_to_video(output, "output.mp4", fps=15)
> ```


https://github.com/user-attachments/assets/90aa6332-d0ca-47dd-8ee4-cc5209360484

**Comment by zhaoyun0071** [comment]
> > > > > i upgrade the `torch`, and fix the warming
> > > > 
> > > > 
> > > > solved black video problem？
> > > 
> > > 
> > > yes, with torch==2.5.1 and without change the default dtype
> > > output.mp4
> > 
> > 
> > can you try my code?
> > ```
> > 
> > import torch
> > from diffusers import HunyuanVideoPipeline, HunyuanVideoTransformer3DModel
> > from diffusers.utils import export_to_video
> > 
> > model_id = "tencent/HunyuanVideo"
> > transformer = HunyuanVideoTransformer3DModel.from_pretrained(
> >     model_id, subfolder="transformer", torch_dtype=torch.bfloat16
> > )
> > pipe = HunyuanVideoPipeline.from_pretrained(model_id, transformer=transformer, torch_dtype=torch.float16)
> > pipe.vae.enable_tiling()
> > pipe.enable_sequential_cpu_offload()
> > 
> > output = pipe(
> >     prompt="A cat walks on the grass, realistic",
> >     height=320,
> >     width=512,
> >     num_frames=61,
> >     num_inference_steps=30,
> > ).frames[0]
> > export_to_video(output, "output.mp4", fps=15)
> > ```
> 
>  output.mp4

many thanks

**Comment by a-r-r-o-w** [comment]
Awesome, glad to see it was resolved. Marking this as closed. Just to summarize, it was a problem with torch version and not something to do with `enable_sequential_cpu_offload`

**Comment by hlky** [comment]
@SahilCarterr add `revision='refs/pr/18'` to `from_pretrained` until weights are merged.
