### ISSUE TITLE
[Community Pipeline] Mix Prompting pipeline?

### ISSUE THREAD

**Issue by daspartho** [huggingface/diffusers#1029]
## Idea
I've been playing with this concept of mixed embeddings. The premise is simple: the pipeline takes a list of prompts and generates images based on a mix of embeddings of the prompts. It produces some interesting mixed-up outcomes.

## Example
Prompt 1: `a mountain, cinematic angle, studio Ghibli, cinematic lighting, detailed oil painting, hyperrealistic, 8k`
Prompt 2: `A long and winding beach, tropical, bright, simple, by Studio Ghibli and Greg Rutkowski, artstation`

#### Prompt 1 only
![mountain64](https://user-images.githubusercontent.com/59410571/198332098-694290de-1e64-4776-ac93-851e00c4d0bf.jpg)

#### Prompt 2 only
![beach64](https://user-images.githubusercontent.com/59410571/198332142-9b11615c-f661-4521-babb-fb75f3203c1d.jpg)

#### Prompt 1 + Prompt 2
![mix64](https://user-images.githubusercontent.com/59410571/198332159-22b393af-02b6-4de7-949d-c90c7a99b938.jpg)

## Implementation
I've put up a working implementation for this [here](https://github.com/daspartho/fastai-part2/blob/main/mixprompt.ipynb). I could open up a PR for a community pipeline for this if that's something folks would like to be added. #841

**Comment by Randolph-zeng** [comment]
There is a ICLR 2022 paper "PROMPT-TO-PROMPT IMAGE EDITING WITH CROSS-ATTENTION CONTROL" that does similar but more things into the pipeline. There are also open sourced code in the web, would be interesting to add them to Diffusers too  @patrickvonplaten  https://github.com/google/prompt-to-prompt

**Comment by patrickvonplaten** [comment]
Hey @Randolph-zeng, we are working on enabling exactly this use case: https://github.com/huggingface/diffusers/pull/1639
