### ISSUE TITLE
Add Stable Diffusion Telephone to community pipelines 

### ISSUE THREAD

**Issue by MarkRich** [huggingface/diffusers#1037]
Context: https://twitter.com/jayelmnop/status/1585695941788856320 

**Is your feature request related to a problem? Please describe.**
The problem is that we don't have this awesome little pipeline! 

**Describe the solution you'd like**
We add it to community pipelines per https://github.com/huggingface/diffusers/issues/841 

I'd love to take a crack at this! Can probably work on it starting Sunday or Monday! 

See example: https://twitter.com/i/status/1585695941788856320 

cc @patil-suraj  or @patrickvonplaten  if you disagree / think this isn't useful / part of scope.

**Comment by patil-suraj** [comment]
Hey @MarkRich , this would be a very cool addition, feel free to work on it, happy to help :)

**Comment by WASasquatch** [comment]
This is pretty cool, but I would think the CLIP Interrogator isn't powerful enough, or optimized enough. It often trips out, and provides rubbish prompts for real images, let alone diffusions. I have it as part of Easy Diffusion, and I really just stopped using it cause of the frequency of error.
