### ISSUE TITLE
custom pipelines and from_pretrained

### ISSUE THREAD

**Issue by WASasquatch** [huggingface/diffusers#1046]
**What API design would you like to have changed or added to the library? Why?**

custom pipelines is available through the master `from_pretrained()` method, but do not work for other pipelines. It would be beneficial if you could load custom features into any pipeline, such as the much needed and missing functionality of img2img and inpainting for custom pipelines. 

**What use case would this enable or better enable? Can you give us a code example?**

It wouldn't make custom pipelines a novelty, but a functioning part of diffusers that could be used in production services, and production workflows. 

Currently if you tried to load custom pipes with say `StableDiffusionImg2ImgPipeline()` you will get errors about `cache_download` and also `Could not locate the pipeline.py inside clip_guided_diffusion.` (or whatever community pipe)

It would be cool, still, if custom pipes were just plugins. So you could do something like `custom_pipelines = ['clip_guided_diffusion', 'weighted_stable_diffusion', 'etc']` sort of deal to add multiple features.

**Comment by WASasquatch** [comment]
I have been trying to get clip guidance into img2img and inpaint for weeks now, to no avail, and it's getting super frustrating.

**Comment by patrickvonplaten** [comment]
Thanks for the issue. I think it'll be quite difficult, technically, trying to ensure that one can load multiple custom pipelines into one given that they all define their own `step` function and also rely on different weights, e.g. clip guided diffusion relies on more weight parameters than stable diffusion text2image. The best I can think of at the moment is doing something like:

```python
from diffusers import DiffusionPipeline

stable_diffusion = DiffusionPipeline.from_pretrained(model_id)
clip_guided = DiffusionPipeline.from_pretrained(model_id, custom="clip_guided_diffusion", **stable_diffusion.components)  # this won't allocate new memory
```

In the long run we should maybe really try to have a better compatibility with AUTOMATIC1111 which is really nice (see PR/issue here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/2577)

**Comment by WASasquatch** [comment]
And don't you think that may have been a short sight in "community" development and usage through the API? It seems more intuitive for custom pipelines to be modules to a stable Diffusion pipeline. Which ever you have active by name, eg `lpw_stable_diffusion` would have a "`step_extension`" that is hooked into a main step function, like a override. That way you don't have to share components or configs, but just declare the pipe type.
