### ISSUE TITLE
[Community] train example of sde_ve and karras_ve

### ISSUE THREAD

**Issue by vsfh** [huggingface/diffusers#1054]
Great project!

I notice I cannot find the train example of sde_ve and karras_ve whose schedulers and pipeline has been implemented in this repo. You know its loss and set of sigma is tricky so I hope I can get your official implement.

Thanks.

**Comment by natolambert** [comment]
Hi @vsfh yeah you are right that this is not filly supported yet. It would be a great issue for a community member to verify. We definitely have some checks when developing it that it matches up, but I don't think any of the core maintainers have done any deep testing.

**Comment by patrickvonplaten** [comment]
This would definitely be a nice addition to `diffusers` :-) Will mark this as a community issue / good first issue
