### ISSUE TITLE
Failed to load safety-checker on scripts/convert_original_stable_diffusion_to_diffusers.py

### ISSUE THREAD

**Issue by AkiKagura** [huggingface/diffusers#1060]
### Describe the bug

Trying to change my ckpt model into diffusers model but failed for lacking the cache of safety-checker

### Reproduction

Clone the code of diffusers from GitHub, then get into directory of diffusers and execute the following command:
`python3 scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path /Users/hime/Downloads/mkmkgen.ckpt --dump_path  /Users/hime/Downloads/mkmkgen`

Then I get error messages like following. Also, my cache folder /`Users/hime/.cache/huggingface/hub/models--CompVis--stable-diffusion-safety-checker` is empty. Is there any solution to get inner contents of `.cache/huggingface/hub/models--CompVis--stable-diffusion-safety-checker` directory?

### Logs

```shell
--2022-10-30 10:52:43--  https://raw.githubusercontent.com/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (Operation timed out)。
重试中。

--2022-10-30 10:55:44--  (尝试次数： 2)  https://raw.githubusercontent.com/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：1873 (1.8K) [text/plain]
正在保存至: “v1-inference.yaml.1”

v1-inference.yaml.1 100%[===================>]   1.83K  --.-KB/s  用时 0s      

2022-10-30 10:55:52 (10.3 MB/s) - 已保存 “v1-inference.yaml.1” [1873/1873])

Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPTextModel: ['vision_model.encoder.layers.12.self_attn.out_proj.bias', 
...
Traceback (most recent call last):
  File "/Users/hime/gitProject/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 721, in <module>
    safety_checker = StableDiffusionSafetyChecker.from_pretrained("CompVis/stable-diffusion-safety-checker")
  File "/Users/hime/miniforge3/envs/diffusers/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1964, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/Users/hime/miniforge3/envs/diffusers/lib/python3.10/site-packages/transformers/configuration_utils.py", line 531, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/hime/miniforge3/envs/diffusers/lib/python3.10/site-packages/transformers/configuration_utils.py", line 558, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/hime/miniforge3/envs/diffusers/lib/python3.10/site-packages/transformers/configuration_utils.py", line 613, in _get_config_dict
    resolved_config_file = cached_file(
  File "/Users/hime/miniforge3/envs/diffusers/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/Users/hime/miniforge3/envs/diffusers/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1136, in hf_hub_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hime/.cache/huggingface/hub/models--CompVis--stable-diffusion-safety-checker/refs/main'
```

### System Info

source code of diffusers
History for [diffusers](https://github.com/huggingface/diffusers/commits/main)/[scripts](https://github.com/huggingface/diffusers/commits/main/scripts)/convert_original_stable_diffusion_to_diffusers.py
Commits on Oct 26, 2022

Running on Mac M1

**Comment by AkiKagura** [comment]
Also, that is the result when I haven't change any code besides at convert_original_stable_diffusion_to_diffusers.py line673:`checkpoint = torch.load(args.checkpoint_path)`->`checkpoint = torch.load(args.checkpoint_path, map_location='cpu')` for CUDA is not supported on Mac

**Comment by patrickvonplaten** [comment]
Hey @AkiKagura, 

Could you upload your checkpoint `/Users/hime/Downloads/mkmkgen.ckpt` somewhere on the Hub: https://huggingface.co/ so that I can reproduce the error? :-) Thank you!

**Comment by AkiKagura** [comment]
> Hey @AkiKagura,
> 
> Could you upload your checkpoint `/Users/hime/Downloads/mkmkgen.ckpt` somewhere on the Hub: https://huggingface.co/ so that I can reproduce the error? :-) Thank you!

Yes! there is.
https://huggingface.co/AkiKagura/mkgen-diffusion/tree/main/mkgen.ckpt

Thank you so much😊

**Comment by patrickvonplaten** [comment]
Hey @AkiKagura, 
I don't seem to be able to access https://huggingface.co/AkiKagura/mkgen-diffusion/tree/main/mkgen.ckpt I'm afraid

**Comment by AkiKagura** [comment]
So sorry! @patrickvonplaten 
https://huggingface.co/AkiKagura/mkgen-diffusion/tree/main/ ,this site is correct, and the mkgen.ckpt file in it is that model.

**Comment by patrickvonplaten** [comment]
IT seems like you have managed to upload a diffusers model no? I can see that the diffusers folder structure is present :-)

**Comment by AkiKagura** [comment]
> IT seems like you have managed to upload a diffusers model no? I can see that the diffusers folder structure is present :-)

Actually, they are two models trained in different ways that is … I am still having this problem🥲
