### ISSUE TITLE
Update Textual Inversion example instruction to Stable Diffusion v1.5

### ISSUE THREAD

**Issue by gau-nernst** [huggingface/diffusers#1061]
### Describe the bug

Currently the Textual Inversion example uses Stable Diffusion v1.5 in the command, but the instructions say Stable Diffusion v1.4

https://github.com/huggingface/diffusers/blob/95414bd6bf9bb34a312a7c55f10ba9b379f33890/examples/textual_inversion/README.md?plain=1#L32

https://github.com/huggingface/diffusers/blob/95414bd6bf9bb34a312a7c55f10ba9b379f33890/examples/textual_inversion/README.md?plain=1#L51-L66

The instruction should be updated and link to https://huggingface.co/runwayml/stable-diffusion-v1-5 instead.

### System Info

NA

**Comment by patrickvonplaten** [comment]
cc @patil-suraj

**Comment by patil-suraj** [comment]
fixed in #1103
