### ISSUE TITLE
[Dreambooth] can't repeate paper results

### ISSUE THREAD

**Issue by orydatadudes** [huggingface/diffusers#1062]
thank you for you great work
Using dog images (Dog toy example data ) I am trying to reconstruct the results showed in the paper
what i did?
follow the following instructors i fine tuned stable-diffusion-v1-5 using 120 others dogs images (randomly chosen from Stanford Dogs Dataset ), i also fine tuned the text model:

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --train_text_encoder \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of sks dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --use_8bit_adam
  --gradient_checkpointing \
  --learning_rate=2e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=800

when i want to generate a photo of a sleeping/swimming/in a bucket i am getting one of the source images:

![A photo of sks dog swimming](https://user-images.githubusercontent.com/64726228/198868174-54d98e93-a2c2-4599-9048-1b0840556280.png)

from diffusers import StableDiffusionPipeline
import torch

model_id =  "examples/dreambooth/dog" #"runwayml/stable-diffusion-v1-5"  #"CompVis/stable-diffusion-v1-4"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")

prompt = "A photo of sks dog sleeping"
image = pipe(prompt, num_inference_steps=50, guidance_scale=7.5).images[0]

image.save(prompt + ".png")

is some else succeed in getting better results? what goes wrong ?
thanks

**Comment by patrickvonplaten** [comment]
Hey @orydatadudes, 

Note that the official weights and code of dreambooth: https://dreambooth.github.io/ has never really been open-sourced. So we cannot expect to be able to reproduce 1-to-1 the same results as in the paper. The best article we have for dreambooth at the moment can be found here: https://github.com/huggingface/blog/pull/603 (it'll soon be available here: https://huggingface.co/blog/stable_diffusion_dreambooth_training )

**Comment by Revist** [comment]
Same here, I checked and when you want to generate "a bucket" it works fine, results for "a dog" are somewhat strange (i get some strange colors)
<img width="515" alt="Screenshot 2022-11-04 at 12 40 17" src="https://user-images.githubusercontent.com/26026957/199964211-952d3fd9-5117-4369-87fc-27a83a3d02a0.png">

**Comment by Revist** [comment]
Here the guy claims to have reproduced the results:
https://github.com/XavierXiao/Dreambooth-Stable-Diffusion

**Comment by patil-suraj** [comment]
As Patrick said, the original code and model on which dream booth was trained in the paper are not available. So it might not be possible to get exact reproducible results. 

If you are getting the same results as your input image, that likely means it's overfitting, so we could try different things here
- reduce the number of steps or LR
- use prior preservation 
- train the text encoder

Also note that to get the best possible results it's important to carefully pick the hyper parameters, we did many experiments and wrote a blog about it please take a look at it https://huggingface.co/blog/dreambooth

Thank you !

**Comment by Revist** [comment]
@patil-suraj Thank you

**Comment by MeixiChenTracy** [comment]
> Here the guy claims to have reproduced the results:
> https://github.com/XavierXiao/Dreambooth-Stable-Diffusion
@Revist 
Hi, I'm pretty new to this so I might ask stupid questions, please forgive me: 

I tried both implementations, and found this guy's implementation working far more stable than the implementation here, i.e. no annoying parameter tuning. Do you know why there's a difference like this?

Is it probably because he starts with a set of hyperparameters that already works generally well, so when I copy his script it just works? If so may I ask where can I find a set of parameters that works for the sks dog or the sks toy sample? I've struggled days to get this correct 😭😭😭

Many thanks

**Comment by patrickvonplaten** [comment]
Hey @Revist,

Note that the dreambooth script is just an example - we cannot make sure it works perfectly well for every use case. The purpose of this example script is to teach / show the community how to do fine-tune the model with dreambooth - it is up to you to decide on your hyper-parameters (which BTW also depend always on your use case). There is no way we can provide "universally correct" hyper-parameters.
