### ISSUE TITLE
LMSDiscreteScheduler.add_noise() returns error

### ISSUE THREAD

**Issue by vtushevskiy** [huggingface/diffusers#1064]
### Describe the bug

WHen I try to run the code:
```
        timesteps = torch.tensor([num_inference_steps - start_step]*batch_size, dtype=torch.long, device=device)
        noise = torch.randn(latents.shape, generator=generator, device=device)
        latents = scheduler.add_noise(latents, noise, timesteps).to(device)
```
I have error:
```
    latents = scheduler.add_noise(latents, noise, timesteps)
  File "/home/vlad/notebook/diffusersCustom/lib/python3.8/site-packages/diffusers/schedulers/scheduling_lms_discrete.py", line 270, in add_noise
    step_indices = [(schedule_timesteps == t).nonzero().item() for t in timesteps]
  File "/home/vlad/notebook/diffusersCustom/lib/python3.8/site-packages/diffusers/schedulers/scheduling_lms_discrete.py", line 270, in <listcomp>
    step_indices = [(schedule_timesteps == t).nonzero().item() for t in timesteps]
ValueError: only one element tensors can be converted to Python scalars
```
What may be the reason?

### System Info

- `diffusers` version: 0.6.0
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Huggingface_hub version: 0.10.0
- Transformers version: 4.23.1

**Comment by patrickvonplaten** [comment]
cc @anton-l could you take a look here?

**Comment by anton-l** [comment]
@vtushevskiy could you post a reproducible code snippet please? Looks like you have duplicate timesteps in the scheduler, but I can't say for sure without an example :)

**Comment by vtushevskiy** [comment]
Can't reproduce. Now error doesn't appear

**Comment by htoyryla** [comment]
I have been struggling with the same error in my custom pipeline. Found out that it was because I was passing the timesteps index instead of the actual timesteps.

This gives the error (where t_index is an integer index into scheduler.timesteps):

```
latents_ = scheduler.add_noise(orig_latents, noise, torch.tensor([t_index]))
```

This works:

```
latents_ = scheduler.add_noise(orig_latents, noise, torch.tensor([scheduler.timesteps[t_index]]))
```

diffusers 0.6.0
python 3.9.12
transformers  4.21.0
pytorch  1.11.0  py3.9_cuda11.3_cudnn8.2.0_0  
Ubuntu 20.04 5.15.0-52-generic

**Comment by htoyryla** [comment]
Now I see it. This line https://github.com/huggingface/diffusers/blob/ad9d7ce4763f8fb2a9e620bff017830c26086c36/src/diffusers/schedulers/scheduling_lms_discrete.py#L255 converts the timesteps into Float, so that the branch handling the int/index case is not run.
