### ISSUE TITLE
HuggingFaceDocBuilderDev makes documents for PR in forks

### ISSUE THREAD

**Issue by shirayu** [huggingface/diffusers#1066]
### Describe the bug

HuggingFaceDocBuilderDev makes documents for PR in forks like this https://github.com/shirayu/diffusers/pull/1
The URL is ``https://moon-ci-docs.huggingface.co/docs/diffusers/pr_1/en/index``.

### Reproduction

See https://github.com/shirayu/diffusers/pull/1

### System Info

None

**Comment by shirayu** [comment]
Hi, @patrickvonplaten , @sgugger 

I would like to know what happens if more than one person creates a PR with the same number.
If a PR with a certain number already exists in the doc, will it be overwritten if another person creates a PR with the same number in a different repository?

**Comment by sgugger** [comment]
Probably yes

**Comment by shirayu** [comment]
OK. If so, they can be overwritten by others unintentionally.
Anyway I got it.
Thank you.
