### ISSUE TITLE
[Feature request] Tensor to Image post-processing integrated with the library 

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#107]
For the image diffusers, the outputs are tensors that need to be pre-processed to become useful as images. Different models and schedulers may require different post-processing for the images that the user may not be aware about.

For that, the API for pipelines could have a `output_type` option that the user could choose between the output formats such as `pil`, `numpy`, `tensor`, [analogous to the Gradio `type` on the gr.Image component](https://gradio.app/docs/#image)

This could enable for the following use-case:
```
image = ldm_pipeline([prompt], generator=generator, num_inference_steps=steps, guidance_scale=guidance_scale, output_type="pil")
```
Where the output is already a PIL image (if the output is only one image), or a PIL array (if the output are multiple images)

(Also when the library is expanded to more modalities, the final output modality could follow the same logic)

**Comment by anton-l** [comment]
Added in https://github.com/huggingface/diffusers/pull/111
