### ISSUE TITLE
How to save jax models

### ISSUE THREAD

**Issue by dingjingzhen** [huggingface/diffusers#1074]
I use a model trained by pytorch, how can I convert it to jax for inference

**Comment by natolambert** [comment]
Hi @dingjingzhen, I have an idea but am not 100% sure. This seems like a functionality not directly supported by the library. What has been done in the past is to utilize scripts and utils (that are present in the library [here](https://github.com/huggingface/diffusers/blob/0902449ef82d8f1700643ae65b20316519ac20ec/src/diffusers/modeling_flax_pytorch_utils.py)) to save a new jax-version of the model.

If I recall correctly, jax models will often need a different pipeline / scheduler to get even more speed ups?

**Comment by camenduru** [comment]
https://github.com/huggingface/diffusers/issues/1015#issuecomment-1297504201

**Comment by pcuenca** [comment]
Exactly, thanks @camenduru!

In addition, @dingjingzhen, you can use a PyTorch model by using the `from_pt` argument when you load the pipeline, as @camenduru shows here in the first line of his snippet: https://github.com/huggingface/diffusers/issues/1015#issuecomment-1297752984

This will convert the weights on the fly. Then you can save them in Flax format if you need to (second line of the snippet), or convert them every time you use the model, depending on your use case.

Please, let us know if that helps :)

**Comment by dingjingzhen** [comment]
@pcuenca Thank you for the great work that has solved my problem

**Comment by pcuenca** [comment]
Awesome! Glad to know :)
