### ISSUE TITLE
Using jax inference

### ISSUE THREAD

**Issue by dingjingzhen** [huggingface/diffusers#1075]
How to generate multiple images with a single prompt when I use jax to accelerate txt2img

**Comment by patrickvonplaten** [comment]
Hey for now you could simply duplicate your prompt:

```python
prompt = "A cinematic film still of Morgan Freeman starring as Jimi Hendrix, portrait, 40mm lens, shallow depth of field, close up, split lighting, cinematic"
images_per_prompt = 2

prompt = [prompt] * images_per_prompt * jax.device_count()
prompt_ids = pipeline.prepare_inputs(prompt)
prompt_ids.shape
```

For more information you could maybe have a look at the blog post :-) 
https://huggingface.co/blog/stable_diffusion_jax

**Comment by pcuenca** [comment]
Closing for now, feel free to reopen if needed.
