### ISSUE TITLE
about stable-diffusion-v1-5

### ISSUE THREAD

**Issue by zcswdt** [huggingface/diffusers#1076]
### Model/Pipeline/Scheduler description

How to download model stable-diffusion-v1-5 to the local disk

![image](https://user-images.githubusercontent.com/43515926/198968357-f705264c-b039-4d4b-bd88-66eb2097174b.png)

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by natolambert** [comment]
Hi @zcswdt -- you need to get the model directly from the hub (https://huggingface.co/runwayml/stable-diffusion-v1-5). This involves making an account, accepting the conditions / license, and then downloading directly or using the git interface.

**Comment by averad** [comment]
@zcswdt

**Downloading stable-diffusion-v1-5 and stable-diffusion-inpainting to local disk:**
You will need to go to: https://huggingface.co/runwayml/stable-diffusion-v1-5 and https://huggingface.co/runwayml/stable-diffusion-inpainting. Review and accept the usage/download agreements before completing the following steps.

stable-diffusion-v1-5 uses 5.10 GB
stable-diffusion-inpainting uses 5.10 GB
If your model folders are larger, open stable-diffusion-v1-5 and stable-diffusion-inpainting and delete the .git folders

```
git clone https://huggingface.co/runwayml/stable-diffusion-v1-5 --branch main --single-branch stable-diffusion-v1-5
git clone https://huggingface.co/runwayml/stable-diffusion-inpainting --branch main --single-branch stable-diffusion-inpainting
```

Enter in your HuggingFace credentials and the download will start. Once complete, you are ready to start using Stable Diffusion.

Note: You can change the --branch [option] to fp16, bf16, flax or onnx depending on your needs
