### ISSUE TITLE
How to run dreambooth accelerate from python file

### ISSUE THREAD

**Issue by adhikjoshi** [huggingface/diffusers#1080]
### Describe the bug

I tried to finetune model, works fine.

Now i want to make a python script which accepts parameters from Flask and start training,

What i found is that, i have to pass all parameters as command like

`accelerate launch --config_file=$ACCELERATE_CONFIG train_dreambooth.py \`

But i want to access this as python function, where i can pass parameters to function and start training,

I didn't find any docs for this in accelerate or diffusers.

Is there anything like 

```
from accelerate import Accelerator
accelerator = Accelerator()
accelerator.launch('train_dreambooth', .....)
```

I want start training from python file instead of through a command, so i can use it through Flask API.

### System Info

accelerate==0.12.0

**Comment by patrickvonplaten** [comment]
cc @patil-suraj could you take a look here?

**Comment by patil-suraj** [comment]
You could use the `notebook_launcher` function for this , https://huggingface.co/docs/accelerate/v0.11.0/en/launcher#accelerate.notebook_launcher, for example import the `main` function from the script and launch it using the `notebook_launcher`
