### ISSUE TITLE
[Feature Request] Documentation around multiple pipelines reusing model weights

### ISSUE THREAD

**Issue by theahura** [huggingface/diffusers#1084]
**Is your feature request related to a problem? Please describe.**
If I have a StableDiffusionPipeline, a StableDiffusionImg2ImgPipeline, and a StableDiffusionInpaintPipeline, these will all load separate weights to the GPU even though they are all using the same model. This makes creating applications that use the full breadth of SD difficult to create.

**Describe the solution you'd like**
It seems like it _is_ possible to reuse weights, according to https://discuss.huggingface.co/t/access-clip-from-stablediffusionpipeline-and-use-the-same-models-for-multiple-pipelines/24813. However, this is not at all clear from the API docs and it's also unclear whether we need to do things like route to cuda multiple times.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by patrickvonplaten** [comment]
Hey @theahura,

That's a good point - we should definitely add this somewhere to the docs. Where do you think would be the best place to discover it for newcomers? Somewhere under `"using-diffusers"` ? here: https://huggingface.co/docs/diffusers/main/en/using-diffusers/

**Comment by theahura** [comment]
I personally was looking in the README, and I think it's basically one paragraph. It would fit right below the section where you describe the different pipelines (e.g. img2img, inpaint):
```
It's possible to reuse weights between pipelines. For example, if you wanted to use StableDiffusion and StableDiffusionImg2Img, you could initialize the weights for the first and apply them to the latter:

SD = diffusers.StableDiffusionPipeline('url', ...params...)
SD_IMG2IMG = diffusers.StableDiffusionPipelineImg2Img('url', unet=SD.unet, scheduler=SD.scheduler, token_extractor=SD.token_extractor, ...)

SD_PIPE = SD.to("cuda")
SD_IMG2IMG_PIPE = SD_IMG2IMG.to("cuda")

Now you can call both pipelines and they will reuse the weights.
```

**Comment by theahura** [comment]
I _believe_ these weights can also be reused in community pipelines? but not 100% sure

**Comment by patrickvonplaten** [comment]
Cool! Would you like to open a PR to add it to the docs? :-)

**Comment by theahura** [comment]
Sure thing, see: https://github.com/huggingface/diffusers/compare/main...theahura:diffusers:patch-1

**Comment by WASasquatch** [comment]
https://huggingface.co/docs/diffusers/main/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.components

**Comment by patrickvonplaten** [comment]
Good catch @WASasquatch - thanks :-) Here a PR to fix it: https://github.com/huggingface/diffusers/pull/1329
