### ISSUE TITLE
Explore potential speed benefits from implementing kernl (Up to 12X faster GPU inference)

### ISSUE THREAD

**Issue by 0xdevalias** [huggingface/diffusers#1094]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Explore whether implementing kernl would provide speedups for Stable Diffusion.

- https://github.com/ELS-RD/kernl
  - > Kernl lets you run PyTorch transformer models several times faster on GPU with a single line of code, and is designed to be easily hackable.
- https://www.reddit.com/r/MachineLearning/comments/ydqmjp/p_up_to_12x_faster_gpu_inference_on_bert_t5_and/
  - > Up to 12X faster GPU inference on Bert, T5 and other transformers with OpenAI Triton kernels

**Describe alternatives you've considered**
- That kernl won't be useful in this repo, or that existing optimisations already do things as well as it could (or better).

**Additional context**

- Crossposted on:
  - https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4096
  - https://github.com/ELS-RD/kernl/issues/141

**Comment by patrickvonplaten** [comment]
Very interesting! cc @NouamaneTazi @Narsil @patil-suraj here

**Comment by patrickvonplaten** [comment]
I'm not sure the diffusers team has time for this, but we'd definitely be interested in exploring this option, but we'd need some benchmark numbers :-)

**Comment by Narsil** [comment]
@OlivierDehaene Played with it and saw same or even slightly worse performance on some hardware.

Not to diminish the acomplishments of `kernl`, I am a big fan of putting kernel writing in the hands of users, and being able to tinker with it. 
I am just saying running some benchmarks would be necessary. It would be awesome if we manage to expose a simple script.

**Comment by OlivierDehaene** [comment]
I played a bit with their Linear, LayerNorm and FlashAttention implementations with our optimized BLOOM deployement: 
- I didn't see gains with their Linaer and LayerNorm but maybe I did something wrong I didn't have the time to investigate more.
- Flash Attention is awesome as always and their implementation adds support for arbitrary masks not just causal masks which is great :)

**Comment by patil-suraj** [comment]
Interesting, as said by other would be cool to see some benchmarks. Also flash attention is now supported through `xformers` cf #532

**Comment by 0xdevalias** [comment]
I've also heard DeepSpeed MII be talked about when it comes to speed improvements of things. Unsure whether there are any things that can be understood/taken from that to improve things here:

> This PR for DeepSpeed MII is a nice tutorial for SD using DeepSpeed MII and lays out some of the optimizations they do,
> 
> https://github.com/microsoft/DeepSpeed-MII/pull/90
> 
> https://github.com/microsoft/DeepSpeed-MII/blob/7ce86af278bc4da1479c17309d87539ccf78f994/examples/benchmark/txt2img/README.md
> 
> _Originally posted by @Thomas-MMJ in https://github.com/huggingface/diffusers/issues/532#issuecomment-1303759989_

**Comment by Thomas-MMJ** [comment]
Here is what the krnl dev, said in response to a question someone in the reddit thread asked if they would be of benefit for accelerating yolov5,

>> Can I also use this project to improve inference time of projects like yolov5, etc.?

> Right now the kernels cover linear layer, attention, and layer norm / rms norm. So the effect would be limited outside a transformer or assimilated. However we will increase the number of kernels, but convolution is not right now our priority

**Comment by Thomas-MMJ** [comment]
Note that there are triton implementations of convolution here,

https://github.com/pytorch/pytorch/tree/c7c09722ad5ee25c5891f863e5bbd1575ad77970/torch/_inductor/triton_ops
