### ISSUE TITLE
Dreambooth and DeepSpeedCPUAdam

### ISSUE THREAD

**Issue by zetyquickly** [huggingface/diffusers#1097]
Hello,

I was playing with a Dreambooth example and noticed a mention that about deepspeed optimizer

> ```deepspeed.ops.adam.DeepSpeedCPUAdam``` gives a substantial speedup

Whenever I change `torch.optim.AdamW` to `deepspeed.ops.adam.DeepSpeedCPUAdam` explicitly it actually gives a speedup. 

I am wondering whether it's possible to perform this switch using `accelerate launch train_dreambooth.py` parameters or set up? Or there's no such API, and this was mentioned for information purposes

Link to the quoted text: https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README.md

**Comment by patrickvonplaten** [comment]
Think we could allow to do this easier from the dreambooth training script - what do you think @patil-suraj ? :-)

**Comment by patil-suraj** [comment]
It's not possible to switch optimizer with accelerate API. Also, the `deepspeed` support is very experimental so I would suggest the users to  just modify the script for advanced `deepspeed` use-cases.
