### ISSUE TITLE
No class name for dreambooth

### ISSUE THREAD

**Issue by Li-En-Good** [huggingface/diffusers#1099]
### Describe the bug

It might come from the latest update?

Traceback (most recent call last):
  File "/dreambooth/infer.py", line 5, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
  File "/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 452, in from_pretrained
    if class_name.startswith("Flax"):
AttributeError: 'NoneType' object has no attribute 'startswith'

### System Info

- `diffusers` version: 0.6.0
- Platform: Linux-3.10.0-1160.53.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.10.6
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0
- Using GPU in script?:  yes
- Using distributed or parallel set-up in script?: no

**Comment by Li-En-Good** [comment]
downgraded and still wouldn't work

**Comment by pcuenca** [comment]
Hi @Li-En-Good, thanks for opening this issue! Can you please provide a reproducibility snippet? In particular, what is `model_id`? Are you downloading the model from Hugging Face Hub, or is it a directory in your computer?

Thanks a lot!

**Comment by Li-En-Good** [comment]
Hi @pcuenca! It is a directory from my computer.

I am doing the same thing as provided here: 
https://github.com/huggingface/diffusers/tree/main/examples/dreambooth#inference

`from diffusers import StableDiffusionPipeline`
`import torch`
`model_id = "path-to-your-trained-model"`
`pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")`
`prompt = "A photo of sks dog in a bucket"`
`image = pipe(prompt, num_inference_steps=50, guidance_scale=7.5).images[0]`
`image.save("dog-bucket.png")`

**Comment by pcuenca** [comment]
Hi @Li-En-Good, sorry for being so slow to answer here. I have two suspicions here:

- Are you using a diffusers-style repo (a folder with several components inside) and not a single-file checkpoint?
- If you are using a diffusers repo, maybe there's a missing component inside?

It'd be really helpful if you could look inside the contents of your model directory. You can do it from a Linux terminal by issuing the following command:

```bash
$ tree <path-to-your-trained-model>
```

This is the output of the previous command for a Dreambooth model I trained in my local system:

```
├── feature_extractor
│   └── preprocessor_config.json
├── logs
│   └── dreambooth
│       ├── 1665440798.804341
│       │   └── events.out.tfevents.1665440798.deep-hack.2498761.1
│       └── events.out.tfevents.1665440798.deep-hack.2498761.0
├── model_index.json
├── safety_checker
│   ├── config.json
│   └── pytorch_model.bin
├── scheduler
│   └── scheduler_config.json
├── text_encoder
│   ├── config.json
│   └── pytorch_model.bin
├── tokenizer
│   ├── merges.txt
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   └── vocab.json
├── unet
│   ├── config.json
│   └── diffusion_pytorch_model.bin
└── vae
    ├── config.json
    └── diffusion_pytorch_model.bin
```
