### ISSUE TITLE
Pros and cons of the configuration setup

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/diffusers#11]
Could you mention the reasons why you opted for a configuration setup that is different from transformers'?

From a previous conversation I remember it was in order to not repeat twice the arguments, however when looking at schedulers it seems like it is still the case:

https://github.com/huggingface/diffusers/blob/850d43450f2154d586c1cb226ca17ec53765e2a2/src/diffusers/schedulers/scheduling_ddpm.py#L23-L45

From a quick read through the file, I don't understand why I have to register something, and what exactly I need to register. Some values are directly set as attribute below the `register`, while others are passed to the `register` method, which seems to act as an `__init__` method with required arguments.

Is it in order to isolate a `dict_to_save` that will serialize only the kwargs passed to the `register` method? Wouldn't it be simpler with an `__init__` method in the `ConfigMixin` instead?

-> Or is it a choice so as to not have a configuration object that you move around everywhere, instead choosing to have it as a mixin for both schedulers and pipelines?

**Comment by patrickvonplaten** [comment]
Closing this issue for now as it was discussed quite extensively offline
