### ISSUE TITLE
A checkpoint trained only on non-copyrighted images.

### ISSUE THREAD

**Issue by MatthewWaller** [huggingface/diffusers#1111]
**Is your feature request related to a problem? Please describe.**
I would like to be able to respect the copyright of artists whose work was used to train the model.

**Describe the solution you'd like**
I'm not sure if this is exactly the place, but if possible, I would like a checkpoint that is trained only on non-copyrighted images. I think this might be the only solution 😔

**Describe alternatives you've considered**
I've thought of giving part of the proceeds of my application of Stable Diffusion to artists in some manner, and I've thought of setting thresholds for how likely a work belongs to an artist, and I've thought of limiting artist names in the text prompt, but nothing would work as cleanly as a checkpoint without copyrighted images.

**Comment by keturn** [comment]
huggingface _hosts_ a lot of models (some of which are diffusion models), but as far as I know they haven't much been in the business of training them. This would be more a project of [Stability.ai](https://stability.ai) or [Runway ML](https://research.runwayml.com/) or perhaps [EleutherAI](https://www.eleuther.ai/) or the forthcoming Stability Conglomerate Foundation thing we've heard rumors of.

**Comment by MatthewWaller** [comment]
Good point. This probably isn’t the forum for this.
