### ISSUE TITLE
[Community] Add aspect ratio bucketing

### ISSUE THREAD

**Issue by Inkorak** [huggingface/diffusers#1112]
Add the possibility of finetuning SD and dreambooth using [aspect ratio bucketing](https://github.com/NovelAI/novelai-aspect-ratio-bucketing).  Instead of using crops, training with aspect ratio bucketing can greatly improve the quality of outputs. NovelAI has released this method under MIT license, so adding it should not be a problem.

**Comment by patrickvonplaten** [comment]
Cool! I'm not sure I'll have time for this anytime soon, but let's see if the community is interested or maybe @patil-suraj ?

**Comment by patil-suraj** [comment]
Cool, won't really have time for this, but if someone is interested in contributing I would be happy to help :)

**Comment by sinanhlvc** [comment]
This is something that I have seen that improves the results and tediousness of preparing datasets and cropping out valuable parts of images. Is this still something that could be considered?

**Comment by patrickvonplaten** [comment]
Hey @sinanhlvc, 

Could you please open a new issue/feature request here?
