### ISSUE TITLE
[Community] Attention Slice/Flash Attention for JAX implementation of unet_2d_condition

### ISSUE THREAD

**Issue by Lime-Cakes** [huggingface/diffusers#1139]
**Is your feature request related to a problem? Please describe.**
Currently, the base pytorch implementation of unet_2d_condition have attention slice feature and can be enabled/set through set_attention_slice. However, JAX's implementation doesn't have this feature. Attention slicing allows saving a lot of vram when running. Alternatively, options like flash attention would save even more.

**Describe the solution you'd like**
If possible, I think we could consider using flash attention for JAX. There is already a flash attention implementation at https://github.com/lucidrains/flash-attention-jax with a MIT license, which can be added as an optional dependency (off by default), so it won't force pytorch users to install. Having set_attention_slice would be great as well, giving people more options.

**Additional context**
I have no yet tested the flash attention JAX code. It's possible the implementation doesn't actually offer much speed up/ram saving on TPU.

**Comment by patrickvonplaten** [comment]
Very interesting! Will mark this as a community feature as I don't think we'll find the bandwidth anytime soon to solve this community feature

**Comment by Lime-Cakes** [comment]
I ran some test and realize flash attention didn't offer any speed up or better memory usage. The opposite happened actually. Seemed like flash attention caused OOM while default doesn't. I believe it's because JAX optimizes the default attention better. 

Closing this issue now. If someone discovered a better, more efficient attention on jax, either open another issue or reopen this one.

**Comment by pcuenca** [comment]
That's has been my experience too @Lime-Cakes, the compiler is usually awesome! Thanks for trying!
