### ISSUE TITLE
Higher level pipeline

### ISSUE THREAD

**Issue by osanseviero** [huggingface/diffusers#114]
Just as in `transformers`, I was wondering if we have any plans for a general `pipeline` function that could use the different pipelines under the hood.

**Comment by patrickvonplaten** [comment]
We already have `DiffusionPipeline` - you should be able to load all models via this class, *e.g.*:

```python
from diffusers import DiffusionPipeline

model_id = "google/ddpm-ema-celebahq-256"

# load model and scheduler
ddpm = DiffusionPipeline.from_pretrained(model_id) 
```
