### ISSUE TITLE
[Flax] 🚨 0.7.0 not working 🚨

### ISSUE THREAD

**Issue by camenduru** [huggingface/diffusers#1145]
### Describe the bug

![Screenshot 2022-11-05 083749-x](https://user-images.githubusercontent.com/54370274/200104662-894bbbce-b435-48fc-af87-b539595fc898.jpg)

### System Info

TPU v3-8

**Comment by camenduru** [comment]
I am still testing...

**Comment by camenduru** [comment]
`0.7.0 🦆 💀  😢 `

![Screenshot 2022-11-05 092325](https://user-images.githubusercontent.com/54370274/200106625-49093699-8181-4648-97eb-1100cb33547e.jpg)

**Comment by camenduru** [comment]
Maybe related 17 hours ago [Jaxlib release v0.3.24](https://github.com/google/jax/releases/tag/jaxlib-v0.3.24) also this new version using more memory 😭

**Comment by patrickvonplaten** [comment]
Thanks for notifying us here so quickly! I'm not on my computer at the moment - but will try to fix it by tonight! 

Could you double check at which commit of main results start to become incorrect? 
I suspect that we messed up something between 0.6.0 and 0.7.0 here - also @pcuenca @patil-suraj here

**Comment by camenduru** [comment]
accelerate sus

**Comment by pcuenca** [comment]
Thanks @camenduru! I'm not at my computer either, but will look into it later today.

**Comment by camenduru** [comment]
🚓🚔🚨 https://github.com/huggingface/diffusers/commit/0b61cea347e9b464fb03506cb78a49d38e1c74ee 🚨🚔🚓

**Comment by pcuenca** [comment]
Thanks, @camenduru, fix incoming!

**Comment by pcuenca** [comment]
@camenduru We have a fix candidate. We'll probably merge it soon, but meanwhile if you want to give it a go, you can install diffusers from the PR branch like this:

```bash
pip install https://github.com/huggingface/diffusers.git@fix-flax-time-embeddings
```

If you do test it, we'd appreciate if you'd let us know how it goes :)

**Comment by patrickvonplaten** [comment]
Hey @camenduru,

Thanks a mille for spotting the bug. We've just pushed a patch release that should fix your bug in https://github.com/huggingface/diffusers/releases/tag/v0.7.2 

Could you just try to run:

```
pip install --upgrade diffusers
```

and try your code example again? It should work now I think

**Comment by camenduru** [comment]
thanks @pcuenca and @patrickvonplaten ♥ it is working 🎉
