### ISSUE TITLE
encrypted neural networks? 

### ISSUE THREAD

**Issue by batrlatom** [huggingface/diffusers#1146]
### Model/Pipeline/Scheduler description

Hi,
there is influx of profile pics apps and many will come in the near future. I think that user privacy should be main concern for such apps. Some services are just deleting model after the train, others leave it on the server.I am thinking ... is there any reliable way to protect the network from theft and stealibg user's identity? Is encryption of the model good enough solution in terms of user usability vs privacy? Would be useful to have such encryption implemented directly to the pipeline?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by batrlatom** [comment]
Yes, it is related to dreambooth. And the problem could be that if you have a service with a bunch of models, somebody hacks you and leaks all models online. I am thinking if such developers can somehow protect user's privacy for example by encrypting the model and then asking user for a password for each generation. I know that it is not so much related to the SD, it's not a pipeline or so. But maybe I am just asking for some tips and best practices, if there are any.

**Comment by patrickvonplaten** [comment]
Ok I see, I guess yes you could encrypt neural networks, but that's probably very costly if you have to decrypt the model for every forward pass
