### ISSUE TITLE
DPM-Solver++

### ISSUE THREAD

**Issue by dblunk88** [huggingface/diffusers#1148]
**Describe the solution you'd like**
A new Sampler based on the paper: https://arxiv.org/abs/2206.00927

"DPM-Solver (and the improved version DPM-Solver++) is a fast dedicated high-order solver for diffusion ODEs with the convergence order guarantee. DPM-Solver is suitable for both discrete-time and continuous-time diffusion models without any further training. Experimental results show that DPM-Solver can generate high-quality samples in only 10 to 20 function evaluations on various datasets."

Example 1: https://github.com/LuChengTHU/dpm-solver
Example 2: https://github.com/crowsonkb/k-diffusion/commit/2d2240ba480d4b6096497252d164bb06345fe61a

**Comment by jenkspt** [comment]
Looks like the DPM-Solver author is already on it: #1101

**Comment by dblunk88** [comment]
> Looks like the DPM-Solver author is already on it: #1101

whoops! Didn't see that. Closing this since it's a duplciate
