### ISSUE TITLE
Training doesnt work

### ISSUE THREAD

**Issue by renzixilef** [huggingface/diffusers#1156]
Hi,

im having problems with executing the training file. My bug report says: 

The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `12` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
usage: train_dreambooth.py [-h] --pretrained_model_name_or_path PRETRAINED_MODEL_NAME_OR_PATH [--pretrained_vae_name_or_path PRETRAINED_VAE_NAME_OR_PATH]
                           [--revision REVISION] [--tokenizer_name TOKENIZER_NAME] [--instance_data_dir INSTANCE_DATA_DIR]
                           [--class_data_dir CLASS_DATA_DIR] [--instance_prompt INSTANCE_PROMPT] [--class_prompt CLASS_PROMPT]
                           [--save_sample_prompt SAVE_SAMPLE_PROMPT] [--save_sample_negative_prompt SAVE_SAMPLE_NEGATIVE_PROMPT]
                           [--n_save_sample N_SAVE_SAMPLE] [--save_guidance_scale SAVE_GUIDANCE_SCALE] [--save_infer_steps SAVE_INFER_STEPS]
                           [--pad_tokens] [--with_prior_preservation] [--prior_loss_weight PRIOR_LOSS_WEIGHT] [--num_class_images NUM_CLASS_IMAGES]
                           [--output_dir OUTPUT_DIR] [--seed SEED] [--resolution RESOLUTION] [--center_crop] [--train_text_encoder]
                           [--train_batch_size TRAIN_BATCH_SIZE] [--sample_batch_size SAMPLE_BATCH_SIZE] [--num_train_epochs NUM_TRAIN_EPOCHS]
                           [--max_train_steps MAX_TRAIN_STEPS] [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS] [--gradient_checkpointing]
                           [--learning_rate LEARNING_RATE] [--scale_lr] [--lr_scheduler LR_SCHEDULER] [--lr_warmup_steps LR_WARMUP_STEPS]
                           [--use_8bit_adam] [--adam_beta1 ADAM_BETA1] [--adam_beta2 ADAM_BETA2] [--adam_weight_decay ADAM_WEIGHT_DECAY]
                           [--adam_epsilon ADAM_EPSILON] [--max_grad_norm MAX_GRAD_NORM] [--push_to_hub] [--hub_token HUB_TOKEN]
                           [--hub_model_id HUB_MODEL_ID] [--logging_dir LOGGING_DIR] [--log_interval LOG_INTERVAL] [--save_interval SAVE_INTERVAL]
                           [--save_min_steps SAVE_MIN_STEPS] [--mixed_precision {no,fp16,bf16}] [--not_cache_latents] [--local_rank LOCAL_RANK]
                           [--concepts_list CONCEPTS_LIST]
train_dreambooth.py: error: unrecognized arguments: --use_auth_token
Traceback (most recent call last):
  File "/home/leoai/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/leoai/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/leoai/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/leoai/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/leoai/anaconda3/envs/diffusers/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--use_auth_token', '--instance_data_dir=training', '--class_data_dir=classes', '--output_dir=output', '--instance_prompt=Leo Weber', '--class_prompt=person', '--seed=3434554', '--resolution=512', '--center_crop', '--train_batch_size=1', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=100', '--sample_batch_size=4', '--max_train_steps=800']' returned non-zero exit status 2.

What can i do?

**Comment by camenduru** [comment]
>train_dreambooth.py: error: unrecognized arguments: --use_auth_token

@renzixilef try without '--use_auth_token'

**Comment by renzixilef** [comment]
Its still not working. Now i get this bug report:

The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `12` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/home/leoai/github/diffusers/examples/dreambooth/train_dreambooth.py", line 812, in <module>
    main(args)
  File "/home/leoai/github/diffusers/examples/dreambooth/train_dreambooth.py", line 489, in main
    tokenizer = CLIPTokenizer.from_pretrained(
  File "/home/leoai/anaconda3/envs/diffusers/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1761, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'CompVis/stable-diffusion-v1-4'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'CompVis/stable-diffusion-v1-4' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback (most recent call last):
  File "/home/leoai/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/leoai/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/leoai/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
(diffusers) leoai@Felix:~/github/diffusers/examples/dreambooth$
ple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/leoai/anaconda3/envs/diffusers/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=training', '--class_data_dir=classes', '--output_dir=output', '--instance_prompt=Leo Weber', '--class_prompt=person', '--seed=3434554', '--resolution=512', '--center_crop', '--train_batch_size=1', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=100', '--sample_batch_size=4', '--max_train_steps=800']' returned non-zero exit status 1.

**Comment by patrickvonplaten** [comment]
Hey @renzixilef, 

Could you provide us with a reproducible code snippet? Also BTW it's really helpful to format code with markdown using 

Normal text here

\`\`\`
Code here
\`\`\`

Normal text here

In then looks as follows:

```
Traceback (most recent call last):
File "/home/leoai/github/diffusers/examples/dreambooth/train_dreambooth.py", line 812, in
main(args)
File "/home/leoai/github/diffusers/examples/dreambooth/train_dreambooth.py", line 489, in main
tokenizer = CLIPTokenizer.from_pretrained(
File "/home/leoai/anaconda3/envs/diffusers/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1761, in from_pretrained
raise EnvironmentError(
OSError: Can't load tokenizer for 'CompVis/stable-diffusion-v1-4'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'CompVis/stable-diffusion-v1-4' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback (most recent call last):
File "/home/leoai/anaconda3/envs/diffusers/bin/accelerate", line 8, in
sys.exit(main())
File "/home/leoai/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
args.func(args)
File "/home/leoai/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
simple_launcher(args)
(diffusers) leoai@Felix:~/github/diffusers/examples/dreambooth$
ple_launcher
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/leoai/anaconda3/envs/diffusers/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=training', '--class_data_dir=classes', '--output_dir=output', '--instance_prompt=Leo Weber', '--class_prompt=person', '--seed=3434554', '--resolution=512', '--center_crop', '--train_batch_size=1', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=100', '--sample_batch_size=4', '--max_train_steps=800']' returned non-zero exit status 1.
```

which is much more readable

**Comment by renzixilef** [comment]
Hi @patrickvonplaten,

thanks for your tips, i am new to this platform so this is really helpful. 
Since my last post i already made it work properly. I am not completely sure what the problem was, but I think xformers was not installed corretly. Not sure if this can cause this issue tho. I'vecompletely reset my Linux Distro and tried it from scratch so it could be some kind of other mistake I made.

Anyway, thanks for your help.
