### ISSUE TITLE
Stitching images & Generating larger images

### ISSUE THREAD

**Issue by elricwan** [huggingface/diffusers#1159]
**Is your feature request related to a problem? Please describe.**
For diversity diffusion model applications, include Conditional image generation & Image in-painting & Stitching images & Generating larger images, would you mind providing some examples for training or inference?

Thank you!

**Comment by patrickvonplaten** [comment]
Hey @elricwan,

Sorry I don't understand the feature request here a 100%. Could you clarify a bit what exactly you wish to see and in what form (doc page, code example, ...)

**Comment by elricwan** [comment]
Hi Patrick, thanks for the quick response. I am looking for the code example. And the detailed descriptions for those application are from here:
https://blog.ml6.eu/potential-applications-of-discrete-diffusion-models-e185276cf9af

Thank you!

**Comment by patrickvonplaten** [comment]
Hey @elricwan,

Sorry we don't have the model that is featured in the blog you linked above yet.

**Comment by elricwan** [comment]
Thanks
