### ISSUE TITLE
the pytest test_local_custom_pipeline hangs/freezes the testing - have to ctrl-c 

### ISSUE THREAD

**Issue by Thomas-MMJ** [huggingface/diffusers#1160]
### Describe the bug

running 

`pytest -v -k "not test_local_custom_pipeline" tests/test_pipelines.py`

the hanging test is skipped, and all of the other tests either pass or are skipped due to slowness

`pytest -v tests/test_pipelines.py`

hangs on test_local_custom_pipeline, and I have to ctrl-c

### Reproduction

Run,

`pytest -v tests/test_pipelines.py::CustomPipelineTests::test_local_custom_pipeline`

It hangs till I do ctrl-c  (allowed to go for 1/2 hour)

### System Info

- `diffusers` version: 0.8.0.dev0
- Platform: Linux-5.15.68.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
- Python version: 3.9.13
- PyTorch version (GPU?): 1.12.1 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.21.2
- Using GPU in script?: unsure?
- Using distributed or parallel set-up in script?: no?

**Comment by patrickvonplaten** [comment]
Interesting! I'm not able to reproduce it sadly - I'm wondering what the issue could be here. I tried on:

```
- `diffusers` version: 0.8.0.dev0
- Platform: Linux-5.18.10-76051810-generic-x86_64-with-glibc2.34
- Python version: 3.9.7
- PyTorch version (GPU?): 1.11.0+cpu (False)
- Huggingface_hub version: 0.11.0.dev0
- Transformers version: 4.25.0.dev0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```


@anton-l any luck reproducing this issue maybe?

**Comment by Thomas-MMJ** [comment]
I'll close this for now, my environment may be subtly borked

**Comment by Thomas-MMJ** [comment]
So instead of running it as a test, I ran it as regular code,

it is infinite looping in a while loop, when doing

`local_custom_pipeline_path = get_tests_dir("fixtures/custom_pipeline")
`
in the while loop of

```
def get_tests_dir(append_path=None):
    """
    Args:
        append_path: optional path to append to the tests dir path
    Return:
        The full path to the `tests` dir, so that the tests can be invoked from anywhere. Optionally `append_path` is
        joined after the `tests` dir the former is provided.
    """
    # this function caller's __file__
    caller__file__ = inspect.stack()[1][1]
    tests_dir = os.path.abspath(os.path.dirname(caller__file__))

    while not tests_dir.endswith("tests"):
        tests_dir = os.path.dirname(tests_dir)

    if append_path:
        return os.path.join(tests_dir, append_path)
    else:
        return tests_dir
```

**Comment by Thomas-MMJ** [comment]
If I cd to tests and run it, it works just fine, it is when ran from ./diffusers that it infinite loops.

**Comment by Thomas-MMJ** [comment]
closing - fresh checkout and it works, so perhaps a bad cached
