### ISSUE TITLE
Convert Flax trained model to PyTorch

### ISSUE THREAD

**Issue by jorahn** [huggingface/diffusers#1161]
**Is your feature request related to a problem? Please describe.**
I'm using the new Flax pipeline for dreambooth training and want to be able to use the trained model on systems that don't run jax.

**Describe the solution you'd like**
Add from_flax parameter to PyTorch model.from_pretrained() functions like Flax models have from_pt parameters in .from_pretrained() to enable cross-compatibility. Probably [here](https://github.com/huggingface/diffusers/blob/main/src/diffusers/modeling_flax_pytorch_utils.py) or [here](https://github.com/huggingface/diffusers/blob/main/src/diffusers/modeling_utils.py).

**Describe alternatives you've considered**
A script to convert Flax msgpack to Diffusers and Flax msgpack to SD Checkpoint (i.e. /scripts directory).

**Additional context**
See [here](https://github.com/huggingface/transformers/blob/49b77b89ea1e89a9940f2b84da1bcc0696ecb07a/src/transformers/modeling_utils.py#L1723) for the implementation of this feature in transformers.

**Comment by camenduru** [comment]
Good idea 🤩 maybe like this: https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_flax_pytorch_utils.py#L242-L352

**Comment by jorahn** [comment]
Thanks, I'll give it a try

**Comment by patrickvonplaten** [comment]
Let me know how it goes @jorahn - curious to hear if it works :-)

**Comment by camenduru** [comment]
+1 curious

**Comment by jorahn** [comment]
Ok, so I have a lokal version, that works for this:

```python
from diffusers import FlaxStableDiffusionPipeline, StableDiffusionPipeline
from diffusers import AutoencoderKL, UNet2DConditionModel
import jax.numpy as jnp

pipe, params = FlaxStableDiffusionPipeline.from_pretrained('CompVis/stable-diffusion-v1-4', revision='bf16', dtype=jnp.bfloat16)
pipe.save_pretrained('output-flax', params)

vae = AutoencoderKL.from_pretrained('output-flax/vae', from_flax=True)
unet = UNet2DConditionModel.from_pretrained('output-flax/unet', from_flax=True)
```
The pipeline doesn't work yet:
```python
pipe2 = StableDiffusionPipeline.from_pretrained('output-flax', from_flax=True)
```
This leads to `OSError: Error no file named diffusion_pytorch_model.bin found in directory output-flax/unet.`. I'll try to put this into a PR so you can take a look at it and maybe help to figure out what's missing.

**Comment by patrickvonplaten** [comment]
Will try to help with the PR!

**Comment by pcuenca** [comment]
Actually superseded by #1241.

**Comment by camenduru** [comment]
![download](https://user-images.githubusercontent.com/54370274/209425812-46208883-5fd5-4055-8f84-75cb50e1af8c.png)

**Comment by patrickvonplaten** [comment]
Closing this PR as one can simply convert the model by loading it into PyTorch now:

```python
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("./flax_stable_diffusion", from_flax=True)
```
