### ISSUE TITLE
prompt endoftext bug - results with prompt > max-length are way better then prompt with length <= max-length

### ISSUE THREAD

**Issue by petekay** [huggingface/diffusers#1165]
### Describe the bug

Hi I trained a personal model (key: `smnb`, class: `person`) with dreambooth, and i found, that I can't replicate the results with automatic1111 on the one side and huggingface/transformers + notebook on the other side.

the fascinating thing is, that if I use exactly max_words + 1, then my prompt is shortened with the word but also with the endoftext-token, and this creates fantastic results.

```
scheduler = DDIMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", clip_sample=False, set_alpha_to_one=False)
safety_checker = None

pipe = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=torch.float16, revision="fp16", scheduler=scheduler, safety_checker = safety_checker).to("cuda")
g_cuda = None

# %%
#@title Run for generating images.
g_cuda = torch.Generator(device='cuda')
seed = 1117437330 #@param {type:"number"}
g_cuda.manual_seed(seed)

prompt = "Ultrawide realistic photo of a smnb person viking men, leading a battle, battle-scarred mind-blowing details, ethereal, ominous, scarred, highly detailed, viking attire, cinematic, 16k, 1080s, smooth, sharp focus, by stanley artgermm, tom bagshaw, greg rutkowski, vincent di fate, carne griffiths, ayami kojima, trending on deviantart, hyper detailed, full of color, digital art, vibrant colors, smooth gradients, high contrast, depth of field, shot on canon camera" #@param {type:"string"}
negative_prompt = "" #@param {type:"string"}
num_samples = 1 #@param {type:"number"}
guidance_scale = 10 #@param {type:"number"}
num_inference_steps = 50 #@param {type:"number"}
height = 512 #@param {type:"number"}
width = 512 #@param {type:"number"}

with autocast("cuda"), torch.inference_mode():
    images = pipe(
        prompt,
        height=height,
        width=width,
        negative_prompt=negative_prompt,
        num_images_per_prompt=num_samples,
        num_inference_steps=num_inference_steps,
        guidance_scale=guidance_scale,
        generator=g_cuda
    ).images

for img in images:
    display(img)
```

this runs fine, and produces this image:
![grafik](https://user-images.githubusercontent.com/17798967/200195466-a215862a-c86a-476a-b8c6-2e2e88bb31ca.png)

but if I add a comma to the prompt and rerun the code (of couse with same seed), I get this error but a very nice picture:

so the exact prompt is:
prompt = "Ultrawide realistic photo of a smnb person viking men, leading a battle, battle-scarred mind-blowing details, ethereal, ominous, scarred, highly detailed, viking attire, cinematic, 16k, 1080s, smooth, sharp focus, by stanley artgermm, tom bagshaw, greg rutkowski, vincent di fate, carne griffiths, ayami kojima, trending on deviantart, hyper detailed, full of color, digital art, vibrant colors, smooth gradients, high contrast, depth of field, shot on canon camera,"

--> ("," is the last character)

```
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['<|endoftext|>']
```
![grafik](https://user-images.githubusercontent.com/17798967/200195534-f92a7503-29aa-4679-b137-29a74feeff07.png)

(it's even so similar to the real person, that I hide the eyes here :) )

if you think, this is by accident, let's compare another seed:
seed = 1117437320
prompt with comma (and endoftext cutoff?)
![grafik](https://user-images.githubusercontent.com/17798967/200195646-2cba0c08-57c2-4a1f-9bb0-76957b926e7d.png)

without comma (no cut-off, prompt length = ok):
![grafik](https://user-images.githubusercontent.com/17798967/200195691-f07e2129-079b-4fd4-9266-5741da23d9f6.png)

seed 1117437334:
with comma prompt:
![grafik](https://user-images.githubusercontent.com/17798967/200196312-90d59d3b-dfa7-4bc1-8227-2bba3ece81e7.png)

without comma (no cut-off, prompt length = ok):
![grafik](https://user-images.githubusercontent.com/17798967/200196317-30a64537-c58c-48c3-8f1f-05392b875cb9.png)

this goes on and on, of course this is not because of the "," itself, but I think that the forward-step is better if the endoftext prompt is cut-off, can someone prove these results with other trained models?

i compared the prompts with 20 different seeds, of course this is not a very big "study", but in my case:
6-7 results from 20 in the with-comma-edition were really good and you can with high similarity to the original picture/person.

in the non-comma-edition, I would say that none of the 20 pictures looked like the original.

maybe related issues:
https://github.com/facebookresearch/SLIP/issues/18

related code:
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L278

### Reproduction

1. Train `keyword person` model with dreambooth
2. create images with maximal prompt length + 1 sign (",")
3. compare it to prompt up to max length or less.

You can also add additional clips, which also get cut-off:

I added` ",a,b,c"`
`prompt = "[identical from above] carne griffiths,a,b,c"`
which resulted in this message (and again the great output/pictures):
`The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['a, b, c <|endoftext|>']`

In any case, this is not the same like putting the prompt to:
`prompt = "[identical from above] carne griffiths"`
which most people would assume, but the prompt-cutoff cuts the flagword "endoftext" off (I assume).

I replicated in locally with these packages in windows + conda, but I get also replicate it exactly on google colab.
Perfect replication is just for me possible, because I have my trained model, but if this is a bug, you could replicate it, with some real person pictures like I did.

### System Info

important package list:

diffusers==0.6.0
torch==1.12.1
torch-fidelity==0.3.0
torchaudio==0.12.1
torchmetrics==0.6.0
torchvision==0.13.1
transformers==4.18.0

python==3.8.10

**Comment by averad** [comment]
I noticed this today and can confirm prompts with <|endoftext|> removed have better results than prompts that include <|endoftext|> in the 20 or so tests I completed.

**Comment by averad** [comment]
# Cat Tests
I completed some tests using seed '168895681900500' and prompt cat or cat<|endoftext|> or cat,

## Findings:
- <|endoftext|> has no weight in sequences up to 77 tokens (See Test_1 - Test_3)
- When <|endoftext|> is truncated from the end of of a 77 token prompt the resulting image changes (See Test_4 - Test_5)

### Test_1: Cat
```
11062022-160057 - Model: ./models/sd-onnx-v1-5
11062022-160057 - Prompt: cat
11062022-160057 - Neg_Prompt: 
11062022-160057 - Inference Steps: 50 Guidance Scale: 7.5 Width: 512 Height: 512
11062022-160057 - Seed: 168895681900500
```
![11062022-160057](https://user-images.githubusercontent.com/640619/200203901-89b7eca3-cea7-4019-92c5-7e56a8074323.png)

### Test_2: cat<|endoftext|>
```
11062022-160345 - Model: ./models/sd-onnx-v1-5
11062022-160345 - Prompt: cat<|endoftext|>
11062022-160345 - Neg_Prompt: 
11062022-160345 - Inference Steps: 50 Guidance Scale: 7.5 Width: 512 Height: 512
11062022-160345 - Seed: 168895681900500
```
![11062022-160345](https://user-images.githubusercontent.com/640619/200203997-1e38a670-1e1a-42ec-a0d4-c49656725a35.png)

### Test_3: cat<|endoftext|>...repeat to max CLIP allowed amount
* The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['<|endoftext|>']
```
11062022-160632 - Model: ./models/sd-onnx-v1-5
11062022-160632 - Prompt: cat<|endoftext|>....<|endoftext|>
11062022-160632 - Neg_Prompt: 
11062022-160632 - Inference Steps: 50 Guidance Scale: 7.5 Width: 512 Height: 512
11062022-160632 - Seed: 168895681900500
```
![11062022-160632](https://user-images.githubusercontent.com/640619/200204110-8d979761-d9b4-4726-806d-2fc7be34f38f.png)

### Test_4: cat,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```
11062022-161757 - Model: ./models/sd-onnx-v1-5
11062022-161757 - Prompt: cat,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
11062022-161757 - Neg_Prompt: 
11062022-161757 - Inference Steps: 50 Guidance Scale: 7.5 Width: 512 Height: 512
11062022-161757 - Seed: 168895681900500
```
![11062022-161757](https://user-images.githubusercontent.com/640619/200204629-b70fb7e2-7fb7-463b-aef5-9a0f1cdfd6a5.png)

### Test_5: cat,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 
* The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['<|endoftext|>']
```
11062022-161602 - Model: ./models/sd-onnx-v1-5
11062022-161602 - Prompt: cat,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
11062022-161602 - Neg_Prompt: 
11062022-161602 - Inference Steps: 50 Guidance Scale: 7.5 Width: 512 Height: 512
11062022-161602 - Seed: 168895681900500 - Gen Time: 99.70440316200256s
```
![11062022-161602](https://user-images.githubusercontent.com/640619/200204224-fe1161ac-3bed-4f5e-89f5-3d9766287ded.png)

**Comment by patrickvonplaten** [comment]
1.) Very good find the cut-off indeed does not behave as it should! 
We should always add a EOS to the end. Will open a PR to fix this!

2.) Interesting, not sure if this mean we should change anything
