### ISSUE TITLE
[TPU] Textual Inversion Training hangs when saving model

### ISSUE THREAD

**Issue by dhruvrnaik** [huggingface/diffusers#1166]
### Describe the bug

I am running the `textual_inversion.py` on a v3-8 TPU VM, and the script hangs at the model saving (save_progress) step. 
Any clue why that may be happening?

### System Info

TPU VM - tpu-vm-pt-1.10
- `diffusers` version: 0.7.1
- Platform: Linux-5.11.0-1021-gcp-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.10.0+cu102 (False)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0

**Comment by camenduru** [comment]
hi @dhruvrnaik, 
- please use diffusers>=0.7.2 `pip install -U diffusers`
- if it is possible always use tpu-vm-base then install pytorch (1.13.0) without cuda support 
- jax 0.3.24 has some memory issue please use jax[tpu]==0.3.23
- `pip install -U "jax[tpu]==0.3.23" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html `

maybe that helps 👀

**Comment by dhruvrnaik** [comment]
@camenduru I tried all of the above but still facing the same issue. Might move on to using flax for this if it continues to cause issues.

**Comment by patrickvonplaten** [comment]
It seems like you're using TPU/XLA with PyTorch - we haven't tested Pytorch/XLA extensively yet sadly and I'm not sure if we'll find time for this anytime soon. 

I think what's happening here though is that the model tries to save the same weights to the same file location simultaniously on all 8 devices. 

IMO you will have to add functionality similar to the one here for PyTorch/XLA: https://github.com/huggingface/transformers/blob/67b37891335262bbbb501b0b53418aafd43a04d7/src/transformers/modeling_utils.py#L1562

**Comment by dhruvrnaik** [comment]
I have tried using `accelerator.save` (https://github.com/huggingface/accelerate/blob/main/src/accelerate/utils/other.py) and it's equivalent - `xm.save` which are supposed to only save the model on the rank=0 device.

It was easier to just shift to using the flax script @camenduru created.
