### ISSUE TITLE
What is "class images" mean for dreambooth training?

### ISSUE THREAD

**Issue by universewill** [huggingface/diffusers#1168]
What is "class images" mean for dreambooth training? 
If instance images meaning the subject i want to train on ， what does "class images" mean?

**Comment by Lewington-pitsos** [comment]
It depends on what interface you are using to run dreambooth. 

That said when I read [https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb#scrollTo=jjcSXTp-u-Eg](this dreambooth colab) it has a variable called `num_class_images` which refers to the number of class images that will be created. 

For instance, if you are training on a photo of your dog then that particular dog is your instance, and it will have the "class" of "dog". Dreambooth will use the images you gave it of your dog to train, but it will also generate a lot of other "class images" (i.e. images of dogs generally) to help it train better.  

You will usually get a faster response to questions like this on the dreambooth discord: https://discord.gg/GvckSgAv5x github issues are usually for more technical questions. 

(Someone with clout: I would recommend closing this)

**Comment by universewill** [comment]
> It depends on what interface you are using to run dreambooth.
> 
> That said when I read [this dreambooth colab](https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb#scrollTo=jjcSXTp-u-Eg) it has a variable called `num_class_images` which refers to the number of class images that will be created.
> 
> For instance, if you are training on a photo of your dog then that particular dog is your instance, and it will have the "class" of "dog". Dreambooth will use the images you gave it of your dog to train, but it will also generate a lot of other "class images" (i.e. images of dogs generally) to help it train better.
> 
> You will usually get a faster response to questions like this on the dreambooth discord: https://discord.gg/GvckSgAv5x github issues are usually for more technical questions.
> 
> (Someone with clout: I would recommend closing this)

Thanks for your reply.

So i only need to config the "num_class_images" parameter and the training process will generate the so called "class images" by itself? No need for me to provide "dog" class images if i want to train on my dog instance images?

Do i get this right?

**Comment by Lewington-pitsos** [comment]
that's correct, unless you are using a very rare training process the class images will be generated for you. Again in future discord is a much better place to ask these questions, and if you could close this issue that would be mad cool!
