### ISSUE TITLE
AdamW degrades word embeddings in textual inversion training

### ISSUE THREAD

**Issue by hadaev8** [huggingface/diffusers#1176]
### Describe the bug

Text embeddings intended to be frozen/unchanged, but it doesn't happen.
First embedding trains against real embeddings, but as training go on, word embeddings decays to zero.

### Reproduction

Not sure if really a bug.

### System Info

Example on colab.
Code here too.

**Comment by patrickvonplaten** [comment]
cc @patil-suraj

**Comment by hadaev8** [comment]
@duongna21 
Im sure fixed it in my codebase by using adam.
Not ideal way to fix it, if you want weight decay, easier to apply it manually on new embedding.

**Comment by patrickvonplaten** [comment]
Gently ping here again @patil-suraj :-)

**Comment by hadaev8** [comment]
Bump

**Comment by patrickvonplaten** [comment]
Hey @hadaev8,

Could you check whether this is fixed by: https://github.com/huggingface/diffusers/pull/1665

**Comment by hadaev8** [comment]
Well I guess so, while I would prefer direct reducing affected embs
