### ISSUE TITLE
Download stable_diffusion on aws

### ISSUE THREAD

**Issue by hamzafar** [huggingface/diffusers#1199]
### Describe the bug

Hi,

I want to run stable diffusion model on aws. and I am downloading model on aws with following code:
`git lfs install`
`git clone https://huggingface.co/runwayml/stable-diffusion-v1-5`

However during downloading 'stable-diffusion-v1-5' the downloading interrupts and gives following error:
`Errors logged to /home/ubuntu/stable-diffusion-v1-4/.git/lfs/objects/logs/20221108T184944.168420745.log`

During installation of git lfs, I also got following error:

`Error: Failed to call git rev-parse --git-dir --show-toplevel: "fatal: not a git repository (or any of the parent directories): .git\n"
Git LFS initialized.`

Any advice to download model on the aws, will be highly appreciated :)

### Reproduction

`git lfs install`
`git clone https://huggingface.co/runwayml/stable-diffusion-v1-5`

on aws

### System Info

I am using aws server. And access aws server with putty from my windows machine.

**Comment by hamzafar** [comment]
Hi,
I am trying to use model from the machine. something like this:
`StableDiffusionPipeline.from_pretrained(
"/home/ubuntu/stable-diffusion-v1-5",
)`

**Comment by pcuenca** [comment]
Hi @hamzafar!

You need to:
- Accept the license for the model you are trying to download. Please, go to the [model page](https://huggingface.co/runwayml/stable-diffusion-v1-5), read the terms and click "accept" if you agree.
- Be logged in before downloading. To do that, I think the easiest would be to run the following commands:

```bash
pip install huggingface_hub
huggingface-cli login
git config --global credential.helper store
```

After that, git clone should work. Please, let us know how it goes.

**Comment by hamzafar** [comment]
Hi @pcuenca,

Would this also work if I accept the license from my laptop chrome. And run logging in commands on AWS machine through putty and then do git clone on AWS server?

Looking forward hearing from you.

**Comment by pcuenca** [comment]
Yes, you only need to accept the license once and you can do it in your laptop. But you have to be logged in in the machine where you'll download the weights.

**Comment by pcuenca** [comment]
Closing for now, please reopen if necessary :)
