### ISSUE TITLE
Obtaining the image iterations before final image has been generated StableDiffusionPipeline.pretrained() 

### ISSUE THREAD

**Issue by MonkeeMan1** [huggingface/diffusers#1202]
Hey all. I am currently using the StableDiffusionPipeline to generate AI images with a discord bot which I use with my friends. I was wondering if it was possible to get a preview of the image being generated before it is finished?

For example, if an image takes 20 seconds to generate, since it is using diffusion it starts off blury and gradually gets better and better. What I want is to save the image on each iteration (or every few seconds) and see how it progresses. How would I be able to do this?

```python
class ImageGenerator:
    def __init__(self, socket_listener, pretty_logger, prisma):
        self.model = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", revision="fp16", torch_dtype=torch.float16, use_auth_token=os.environ.get("HF_AUTH_TOKEN"))
        self.model = self.model.to("cuda")

    async def generate_image(self, data):
        start_time = time.time()
        with autocast("cuda"):
            image = self.model(data.description, height=self.default_height, width=self.default_width,
                               num_inference_steps=self.default_inference_steps, guidance_scale=self.default_guidance_scale)
            image.save(...)
```

The code I have currently is this, however it only returns the image when it is completely done. I have tried to look into how the image is generated inside of the StableDiffusionPipeline but I cannot find anywhere where the image is generated. If anybody could provide any pointers/tips on where I can begin that would be very helpful.

**Comment by htoyryla** [comment]
I am not using the standard pipelines, but in my own code I have started to store intermediate (denoised) results and I often find that the final one is not the best, as during the final steps the image may develop too details, even cluttered sometimes. 

Here's roughly what I do to get a gradually evolving estimate of the final image. 

```
        sigma = scheduler.sigmas[i]

        ....

        if opt.saveiters:
           # estimate final image from current state
           los = latents - sigma * noise_pred                         
          # get an image from the latents
          lats_ = 1 / 0.18215 * los.detach()   
         ...
```

**Comment by ajundo** [comment]
A modified pipeline with callback function `callback(i, t, latents, noise_pred)` is enough. you also need to calculate the predicted x_0 by yourself like above, or use this detailed code if you are confused with the coefficients and variables.
```
# 
def callback(step, timestep, latents, noise):   
    alpha_t = torch.sqrt(pipe.scheduler.alphas_cumprod)
    sigma_t = torch.sqrt(1 - pipe.scheduler.alphas_cumprod)
    a_t, s_t = alpha_t[timestep], sigma_t[timestep]
    latents = (latents - s_t * noise) / a_t
    latents = 1 / 0.18215 * latents
    image = pipe.vae.decode(latents).sample
    image = (image / 2 + 0.5).clamp(0, 1) 
    image = image.cpu().permute(0, 2, 3, 1).numpy() 
    images = pipe.numpy_to_pil(image)
```
Hope it helps.
