### ISSUE TITLE
converting SD model to onnx

### ISSUE THREAD

**Issue by harishprabhala** [huggingface/diffusers#1205]
### Describe the bug

Hi - I am trying to convert stable-diffusion-v1.4 to onnx using the below code.

python convert_stable_diffusion_checkpoint_to_onnx.py --model_path="CompVis/stable-diffusion-v1-4" --output_path="./stable_diffusion_onnx" --fp16="True"

The output I am getting is a model.onnx (430MB) and weights.pb (1.6GB) file. I am looking to get a proper unet.onnx file with the converted onnx weights (1.6GB). 

Can you please help.

### System Info

Diffusers==0.6.0
Python 3.8

**Comment by patrickvonplaten** [comment]
Gently pinging @anton-l here

**Comment by anton-l** [comment]
Hi @harishprabhala! Due to a protobuf size limitation in ONNX, there's currently no way to export 2GB+ of weights into a single `.onnx` file. You can still load the UNet with `onnxruntime` just fine, just make sure to keep `model.onnx` and `weights.pb` in the same directory :)
