### ISSUE TITLE
Community Integration: Making AIGC cheaper, faster, and more efficient.

### ISSUE THREAD

**Issue by binmakeswell** [huggingface/diffusers#1212]
**Is your feature request related to a problem? Please describe.**
AIGC has recently risen to be one of the hottest topics in AI. Unfortunately, large hardware requirements and training costs are still a severe impediment to the rapid growth of the AIGC industry. The Stable Diffusion v1 version of the model requires 150,000 A100 GPU Hours for a single training session.

**Describe the solution you'd like**
We are happy to share a fantastic solution where **the costs of training AIGC models such as stable diffusion can be 7 times cheaper**!

[Colossal-AI](https://github.com/hpcaitech/ColossalAI) release a complete open-source Stable Diffusion pretraining and fine-tuning solution with the pretraining cost reduced by 6.5 times, and the hardware cost of fine-tuning by 7 times. An RTX 2070/3050 PC is good enough to accomplish the fine-tuning task flow, allowing AIGC models such as Stable Diffusion to be available to a wider community. 

Open-source code：https://github.com/hpcaitech/ColossalAI/tree/main/examples/images/diffusion

**Additional context**
More details can be found on the [blog](https://medium.com/@yangyou_berkeley/diffusion-pretraining-and-hardware-fine-tuning-can-be-almost-7x-cheaper-85e970fe207b). We believe the democratization of AIGC models is also very helpful for Hugging Face members. We would appreciate it if we could build the integration with you to benefit both of our users and we are willing to provide help you need in this cooperation for free.

Thank you very much.

Best regards,
Yongbin Li, HPC-AI Tech

**Comment by patrickvonplaten** [comment]
Hey @binmakeswell,

This sounds great - I think we'd be very interested in having a better integration here! Also cc @patil-suraj @thomwolf

**Comment by patil-suraj** [comment]
This is very cool @binmakeswell ! Would be very happy to integrate diffusers in colossalAI examples!

**Comment by binmakeswell** [comment]
Thanks for your enthusiastic response and we look forward to working together!

How do you expect it to be carried out?
Take our collaboration with [Lightning](https://github.com/Lightning-AI/lightning) for example, we communicated in slack for details, provided [documentation](https://pytorch-lightning.readthedocs.io/en/latest/advanced/model_parallel.html#colossal-ai) and eventually did a [joint release](https://lightning.ai/pages/community/lightning-releases/lightning-1-8-release/).

**Comment by 0xdevalias** [comment]
Would love to see a simple integration between diffusers and ColossalAI!

Here's a collection of related issues I found/opened on various StableDiffusion / Dreambooth related projects about this:

- https://github.com/hpcaitech/ColossalAI/issues/1935
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4606
- https://github.com/d8ahazard/sd_dreambooth_extension/issues/174
- https://github.com/TheLastBen/fast-stable-diffusion/issues/493
- https://github.com/ShivamShrirao/diffusers/issues/129

**Comment by patrickvonplaten** [comment]
Hey @binmakeswell,

Should we jump on a call to discuss? :-) I think we've reached out via email

**Comment by binmakeswell** [comment]
> Hey @binmakeswell,
> 
> Should we jump on a call to discuss? :-) I think we've reached out via email

Sure. @patrickvonplaten I just emailed(ybl@hpcaitech.com) you our available hours. Looking forward to our meeting and cooperation :-)

**Comment by 0xdevalias** [comment]
Hopefully not stale.

**Comment by binmakeswell** [comment]
We are working in process for this integration : )

**Comment by haofanwang** [comment]
Any update? It would be very great to fasten training process.

**Comment by Fazziekey** [comment]
> Any update @binmakeswell ? It would be very great to fasten training process.
> 
> I found [train_dreambooth.py](https://github.com/hpcaitech/ColossalAI/blob/a9b27b9265c31175192643e3974187e5ea112c1d/examples/images/dreambooth/train_dreambooth.py) and [train_dreambooth_colossalai.py](https://github.com/hpcaitech/ColossalAI/blob/a9b27b9265c31175192643e3974187e5ea112c1d/examples/images/dreambooth/train_dreambooth_colossalai.py) that are based on diffusers.

Thank you for your interest and contribution to colossalai, we have merged into the hugging face diffuser library.
https://github.com/huggingface/diffusers/tree/main/examples/research_projects/colossalai

**Comment by Kuri-su** [comment]
Is there any process?

**Comment by Sniper199999** [comment]
> It's merged to `diffusers` :-) See: https://github.com/huggingface/diffusers/tree/main/examples/research_projects/colossalai

so does that mean that integration with Automatic1111 is around the corner?

**Comment by 0xdevalias** [comment]
@Sniper199999 Last I paid attention, automatic1111 isn't based on diffusers at all, so unless that has changed since I last looked, short answer is "no, probably not"

**Comment by patrickvonplaten** [comment]
Actually we'd really like to integrate `diffusers` into A1111, but it seems quite complicated. Note sure if anybody has a clear plan of action. Also related: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/2577

Should we try to create a module plug-in?
