### ISSUE TITLE
Improve Dreambooth example documentation

### ISSUE THREAD

**Issue by exo-pla-net** [huggingface/diffusers#1228]
The current [Dreambooth example](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth) is difficult to follow.

We're told to:

> Initialize an Accelerate environment with:
accelerate config

However, "accelerate config" asks utterly baffling questions (to a neophyte), like 
> "Do you want to use DeepSpeed?", 

or 
>"Do you wish to use FP16 or BF16 (mixed precision)? [NO/fp16/bf16]"

Darned if I know! I'm here to *learn* from this example. As such, the example should at the very least give opinionated statements: "Unless you know what you're doing, choose fp16," or it should explain the benefits/drawbacks of the various options.

**Comment by patrickvonplaten** [comment]
cc @patil-suraj

**Comment by muellerzr** [comment]
@patrickvonplaten I can probably assist on this, as this is a fair point as more libraries start using Accelerate that we should template's how to quickly write configs for users to use that are relevant to them. One option is we have a `write_basic_config` function in accelerate that creates a config file based on all the GPUs available and let's you set the mixed precision mode: https://huggingface.co/docs/accelerate/v0.14.0/en/package_reference/utilities#accelerate.utils.write_basic_config

So e.g. a better option may be to direct the user to perform:

```python
from accelerate.utils import write_basic_config
write_basic_config(mixed_precision="no")
```
We can also experiment with adding a command of something like `accelerate config basic`. Which from your perspective is easier on you @exo-pla-net? Likely the CLI option I imagine? 😃

**Comment by exo-pla-net** [comment]
Speaking on behalf of all grug-brained developers, I'd indeed be eminently happy with the CLI option @muellerzr 🧠

More broadly, deep-diving into things like mixed-precision is probably only appropriate after a user is confident and comfortable with basic Dreamboothing.

My *dream* tutorial would be a Colab notebook, with all the settings and non-obvious lines of code commented on. I could then quickly google and tinker my way into competence, starting with the strong foundation of fully functional code.

**Comment by muellerzr** [comment]
In that case, you can definitely go ahead with the above method I think and you'll be fine for now in a Colab notebook, and the CLI option will come quite soon!

**Comment by patil-suraj** [comment]
Thanks for the issue, will add some basic config options in the doc :) 

> My dream tutorial would be a Colab notebook, with all the settings and non-obvious lines of code commented on. I could then quickly google and tinker my way into competence, starting with the strong foundation of fully functional code.

Here you go!
https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_dreambooth_training.ipynb

**Comment by exo-pla-net** [comment]
Wonderful, @patil-suraj -- this will confidently get me started. Making my humble dreams come true. Thanks!

**Comment by 0xdevalias** [comment]
> as this is a fair point as more libraries start using Accelerate that we should template's how to quickly write configs for users to use that are relevant to them. One option is we have a `write_basic_config` function in accelerate that creates a config file based on all the GPUs available and let's you set the mixed precision mode: [huggingface.co/docs/accelerate/v0.14.0/en/package_reference/utilities#accelerate.utils.write_basic_config](https://huggingface.co/docs/accelerate/v0.14.0/en/package_reference/utilities#accelerate.utils.write_basic_config)

While it's not the 'proper solution for this issue I raised on accelerate, it will certainly help me to have a programmatic solution, given the current CLI doesn't really allow configuration to be done in a non-interactive way (eg. in a jupyter notebook)

- https://github.com/huggingface/accelerate/issues/822

**Comment by patrickvonplaten** [comment]
@patil-suraj should we maybe also update the diffusers examples?

**Comment by muellerzr** [comment]
BTW, on the current dev version of Accelerate (so on version 0.15.0 onward once released) there will be an `accelerate config default` command which will write a default config based on your system through the cli (and only accepts very few parameters, including fp16)

**Comment by patrickvonplaten** [comment]
> 

Cool @patil-suraj could you please integrate / update this?

**Comment by williamberman** [comment]
Added docs for the `write_basic_config` version here https://github.com/huggingface/diffusers/pull/1513. Will wait until accelerate release with `accelerate config default` to version bump and add to docs.

**Comment by williamberman** [comment]
Merged in some additional docs about the default accelerator config here: https://github.com/huggingface/diffusers/pull/1564

@exo-pla-net I'm going to resolve this issue but feel free to re-open if there are still clarity issues around the accelerator config. Thank you so much for the issue!
