### ISSUE TITLE
Add an "About" to the repo

### ISSUE THREAD

**Issue by feconroses** [huggingface/diffusers#123]
It would be nice to add an about section to this repo: 
![Screen Shot 2022-07-21 at 12 50 12 PM](https://user-images.githubusercontent.com/10597153/180258092-e8a06766-63db-4fec-9f06-f8ef4adb365d.png)

**Comment by osanseviero** [comment]
WDYT about

> :hugs:  Diffusers: Modular toolbox for diffusion models for different modalities

?

**Comment by feconroses** [comment]
LGTM!

**Comment by patrickvonplaten** [comment]
Good point - added a description!
