### ISSUE TITLE
Accept License while downloading as a y/n option in cmd terminal

### ISSUE THREAD

**Issue by ghpkishore** [huggingface/diffusers#1239]
**Is your feature request related to a problem? Please describe.**
When I wanted to "git clone https://huggingface.co/runwayml/stable-diffusion-v1-5", it failed cause I hadn't accepted the permission in HF for the repo. 

**Describe the solution you'd like**
Instead of asking me to go to the web to accept it, wouldn't it be simpler to have to accept license in the cmd itself. This way, anyone, irrespective of whether they have HF account or not would be able to use it. This is similar to how conda asks you to accept license when you install it in a new AWS Linux instance.

This is also good from a standpoint on standardising license acceptance. For every model, if I had to go to a particular page and accept conditions, it might become difficult.

**Describe alternatives you've considered**
None.

**Additional context**
Simplifies downloading of models and puts all action in cmd instead of having to create account and search for the right repo to accept license.

**Comment by patrickvonplaten** [comment]
Interesting, I think this is actually not a very bad idea - @Wauplin maybe do you think this could make sense?

**Comment by julien-c** [comment]
this would be in `huggingface_hub` only (not through git) because there's no way to hook that into git command-line (AFAIK)

So not sure it would solve your use case @ghpkishore?

**Comment by Wauplin** [comment]
Agree with @julien-c that such a method would be integrated in the `huggingface_hub` library. We could have a `accept_terms` method to display the relevant information and prompt for relevant details.

> This way, anyone, irrespective of whether they have HF account or not would be able to use it. 

Currently the goal of a gated repo is also to share your contact information with the owner of the model: "_This repository is publicly accessible, but you have to accept the conditions to access its files and content. By agreeing you accept to share your contact information (email and username) with the repository authors._" 
So in any case a user would have to be logged in to accept to the terms of a repo. The other solution is to completely remove the gate from [runwayml/stable-diffusion-v1-5](https://huggingface.co/runwayml/stable-diffusion-v1-5) but that's a company decision, not a technical problem to tackle.

**Comment by ghpkishore** [comment]
@julien-c yes, a solution where cmd interface for accepting terms is good enough. I understand the need for prior account setup to share info to model owners.  Will close this issue.
