### ISSUE TITLE
[Documentation request] How to create a dataset for training

### ISSUE THREAD

**Issue by StoneCypher** [huggingface/diffusers#124]
You do say [how to train a new model from a dataset](https://github.com/huggingface/diffusers/tree/main/examples).  You don't say how to create a dataset.

Is it just a directory of images?  Do they need to be sized somehow?  Is there a subdirectory tree?  Are there text files containing metadata?

**Comment by patrickvonplaten** [comment]
Hey @StoneCypher,

That's a very good question and quite important indeed! I'll do my best to answer it here, but @anton-l might have a better answer. 

So in short the google colab shows you how to train a simple unconditional diffusion model on any image datasets. All you need are actually images and that's it! 

The training script is written in a way that expects you to use the [Datasets library](https://huggingface.co/docs/datasets/index) for your vision data. More specifically, the script expects that one key of your dataset is called `image` as can be seen here: https://github.com/huggingface/diffusers/blob/1a84bd2a0f7e2add890ba4bfc6e4ba83d9ed2972/examples/train_unconditional.py#L81 (note how the `image` key is called). This means your dataset should have an image key. 

Now there are two options:

- Either you can use a pre-existing dataset that has images, *e.g.*:
    - https://huggingface.co/datasets/cifar10 (here you could just rename `img` to `image` to make it work. There are many other image datasets on the Hub or
    - You can create your own image dataset as is explained here: https://huggingface.co/docs/datasets/image_process#image-datasets

**Comment by patrickvonplaten** [comment]
@anton-l we should also try to make the training colab / script a bit easier to adapt to other datasets (with clear comments on how to do so)

**Comment by patrickvonplaten** [comment]
Let's maybe take the Transformers notebook as an example here: https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_glue_no_trainer.py#L53

**Comment by patrickvonplaten** [comment]
@StoneCypher Let me know if you have more in-detail questions! Happy to help

**Comment by StoneCypher** [comment]
@patrickvonplaten - Thank you.

[PR to obviate](https://github.com/huggingface/diffusers/pull/127).
