### ISSUE TITLE
Safe Latent Diffusion

### ISSUE THREAD

**Issue by manuelbrack** [huggingface/diffusers#1242]
### Model/Pipeline/Scheduler description

We have just released a [paper](https://arxiv.org/abs/2211.05105) introducing Safe Latent Diffusion (SLD) for text2image diffusion models. 
SLD mitigates the well known issue that models like Stable Diffusion that are trained on unfiltered, web-crawled datasets tend to suffer from inappropriate degeneration. For instance SD may _unexpectedly_ generate nudity, violence, images depicting self-harm, or otherwise offensive content. 
SLD suppresses the vast majority of such content and is very sophisticated in that it offers hyper parameters to target exactly what content you want to suppress, to what extent, and in which stage of the diffusion process. Therefore, the overall image image composition and intent of the image remains the same with just the unwanted content being removed/replaced.

Additionally, SLD also improves perceived image quality and image-text-alignment as user studies on DrawBench show.

I believe an SLD pipeline would be a great contribution to the diffusers library. 

## Example

Below one of the rather benign examples. SLD also suppresses far more problematic content, that I'd rather not display here:
![github_grid_2_scaled](https://user-images.githubusercontent.com/26039108/201054451-a94d093f-6f65-4c11-8382-e70b4a03d006.png)
Top is SD v1.5 and below are the same images with SLD enabled. 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

**Implementation:**
https://github.com/ml-research/safe-latent-diffusion

**Weights:**
Compatible with Stable Diffusion checkpoints. e.g.:
https://huggingface.co/CompVis/stable-diffusion-v1-4
https://huggingface.co/runwayml/stable-diffusion-v1-5

**Authors**
@manuelbrack, @PatrickSchrML

**Paper**
https://arxiv.org/abs/2211.05105

**Comment by patrickvonplaten** [comment]
Hey @manuelbrack, 

This is a super cool contribution - amazing to see that you found a strong practical solution to this extremely difficult problem! 
We'd love to include your work natively in `diffusers` - I think it should be as simple as adding a `pipeline_stable_diffusion_safe` to 
https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines

You could essentially in a first pass just copy-paste this pipeline there: https://github.com/ml-research/safe-latent-diffusion/blob/fa32cbdbe2f48ae0af3e10855ea044550e2d5052/src/sld/sld_pipeline.py#L25 and then we could take it from a PR to get the pipeline to be merged?

**Comment by manuelbrack** [comment]
Hi

**Comment by manuelbrack** [comment]
Hi @patrickvonplaten 

Thanks for the quick response and nice feedback. Your suggestion sounds great, I will make a PR to add ```pipeline_stable_diffusion_safe``` to https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines. 

In a first step this will ofc only include the PyTorch implementation and no dedicated pipelines for onnx or flax, but I guess we can add this from the initial PR.

**Comment by patrickvonplaten** [comment]
PR has been merged - closing :-)
