### ISSUE TITLE
How to - Image2Image with (Image + Text) Guided!

### ISSUE THREAD

**Issue by innat** [huggingface/diffusers#1254]
I've an **image with target object**. And I like to generate new image with **text-guided background** with the **target object** in a natural view.  In short

- An image with target object (i.e. car).
- Complex backgrouond removed by **Model A**.
- Then pass it to **Model B** with **text / prompt**.
- Generate **new images <ins>with different poses</ins> of the target object** with **new background** defined by **prompt**.

Here, I'm looking for **Model B**.  Can it be achieved with diffusers? Any pointer?

**Comment by patrickvonplaten** [comment]
Interesting! Maybe this could work: https://github.com/huggingface/diffusers/issues/1305 -> we should have it somewhat soon :-)

**Comment by innat** [comment]
Wow, you're right. Though the pose of the target object is fixed but this is pretty close. 

https://arxiv.org/pdf/2211.07825.pdf

![image](https://user-images.githubusercontent.com/17668390/202321890-977a384f-9451-4780-a1f3-30959485d8d2.png)

**Comment by innat** [comment]
Still open for any suggestion and recommendation. 
( no github-action bot please, 🔕 )

**Comment by patrickvonplaten** [comment]
BTW, Stable Diffusion Depth Estimation should work quite well for this: https://huggingface.co/stabilityai/stable-diffusion-2-depth

**Comment by innat** [comment]
@patrickvonplaten 
https://twitter.com/matthieurouif/status/1589539286814461953

**Comment by patrickvonplaten** [comment]
This would make a nice pipeline here as well :-)

**Comment by innat** [comment]
@patrickvonplaten Could you please open it?

**Comment by innat** [comment]
Candidates: https://huggingface.co/docs/diffusers/using-diffusers/controlling_generation

**Comment by innat** [comment]
Probably this can be gained from recent strategies, i.e. controlnet.

**Comment by innat** [comment]
CC @patrickvonplaten 

Subject-driven Text-to-Image Generation via Apprenticeship Learning
https://arxiv.org/abs/2304.00186#

![image](https://user-images.githubusercontent.com/17668390/229868991-ea91e9b3-f0ef-4926-9b1b-6e711c7d5ca6.png)
