### ISSUE TITLE
Standardize on `init_image` for img2img, inpaint, and others

### ISSUE THREAD

**Issue by fboulnois** [huggingface/diffusers#1257]
**What API design would you like to have changed or added to the library? Why?**

[img2img](https://github.com/huggingface/diffusers/blob/3d98dc763a645423f992b3546c4d9cdd97eb9d04/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L312) currently uses the `init_image` parameter, whereas  [inpaint](https://github.com/huggingface/diffusers/blob/3d98dc763a645423f992b3546c4d9cdd97eb9d04/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py#L312) uses the `image` parameter.

**What use case would this enable or better enable? Can you give us a code example?**

I have some code that dynamically switches between `StableDiffusionPipeline`, `StableDiffusionImg2ImgPipeline`, and `StableDiffusionInpaintPipeline` based on whether an image and mask are provided, and standardizing on `init_image` would simplify the pipeline call (instead of checking beforehand / supplying unused parameters):

```sh
pipeline(prompt, init_image=image, ...)
```

**Comment by patrickvonplaten** [comment]
fair point! Would be ok with just using `image=...` everywhere. What do you think @pcuenca , @patil-suraj @anton-l ?

**Comment by pcuenca** [comment]
I agree, it's a good point and I'd rather standardize on `image` rather than `init_image`. @fboulnois would you like to open a PR with that? It's totally cool if you don't have time though :)
