### ISSUE TITLE
train a diffusion model on rectangle images

### ISSUE THREAD

**Issue by Fairywang9** [huggingface/diffusers#1262]
### Describe the bug

How to train the pictures with Rectangle ,I tried 128*128, and it is fine,but 128*256 input then there are error of tuple size, does anyone know how to solve it?
I just use the diffusers_training_example on colab
![image](https://user-images.githubusercontent.com/56218499/201465424-9bbbbec7-12be-46f0-8350-cd37dedfbb99.png)

What I change:
1. 
@dataclass
class TrainingConfig:
    # image_size = 128  # the generated image resolution
    image_size_h = 128  # my change
    image_size_w = 256  # my change

2. 
preprocess = transforms.Compose(
    [
        transforms.Resize((config.image_size_h, config.image_size_w)),
        transforms.RandomHorizontalFlip(),

3. 
model = UNet2DModel(
    sample_size=(config.image_size_h,config.image_size_w)

Here is the error
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-4f9138074009> in <module>
      2 args = (config, model, noise_scheduler, optimizer, train_dataloader, lr_scheduler)
      3 
----> 4 notebook_launcher(train_loop, args, num_processes=1)

4 frames
/usr/local/lib/python3.7/dist-packages/diffusers/pipelines/ddpm/pipeline_ddpm.py in __call__(self, batch_size, generator, output_type, return_dict, **kwargs)
     69         image = torch.randn(
     70             (batch_size, self.unet.in_channels, self.unet.sample_size_w, self.unet.sample_size_h),
---> 71             generator=generator,
     72         )
     73         image = image.to(self.device)

TypeError: randn(): argument 'size' must be tuple of ints, but found element of type tuple at pos 3

### System Info

the example on colab

**Comment by jenkspt** [comment]
This is the culprit: https://github.com/huggingface/diffusers/blob/c9b34637039b8b7374ae15c70aa93289bc5b6ccd/src/diffusers/pipelines/ddpm/pipeline_ddpm.py#L97-L103

Given that the `UNet2DModel` docstring says that `sample_size` can be a tuple  
https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d.py#L46

I can open a pull request to fix this.
