### ISSUE TITLE
Why is noise scheduler in train_dreambooth.py hard coded to "CompVis/stable-diffusion-v1-4" ? 

### ISSUE THREAD

**Issue by sausax** [huggingface/diffusers#1264]
I noticed that the noise scheduler in the train_dreambooth.py is hardcoded to "CompVis/stable-diffusion-v1-4" here
https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py#L475

The script also takes a command line parameter for pretrained_model https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py#L32

Is it required for the noise scheduler to be of SD v1.4 or can we use the pretrained_model provided in the command line ? 
I want to try the script with v1.5 but not sure if I need to replace the noise scheduler also ?

**Comment by patrickvonplaten** [comment]
That's a very good question - it's actually a bug! Thanks for spotting it :-) 
Here the PR that should solve it: https://github.com/huggingface/diffusers/pull/1322
