### ISSUE TITLE
Schedulers do not work well for text-guided image-to-image generation

### ISSUE THREAD

**Issue by buttercutter** [huggingface/diffusers#1267]
For https://lablab.ai/t/stable-diffusion-img2img , it seems that only [LMSDiscreteScheduler](https://huggingface.co/docs/diffusers/api/schedulers#diffusers.LMSDiscreteScheduler) works well in [generating different variations of the pictures sketches](https://colab.research.google.com/drive/1LMDWu5TUUGjjTnis7wkYP1TY77DxaRa7#scrollTo=0O0Iy1zK0q-8&line=4&uniqifier=1), that is my observation so far

Besides, it seems that both `RePaintScheduler` and `KarrasVeScheduler` are not fully supported yet, at least inside the colab ipynb notebook ?   Please advise

Relevant issue at https://github.com/CompVis/stable-diffusion/issues/178

**Comment by patrickvonplaten** [comment]
Hey @buttercutter,

Note that both repaint and karras_ve are not compatible with stable diffusion. 

Would these docs maybe help: https://huggingface.co/docs/diffusers/main/en/using-diffusers/schedulers ?

**Comment by buttercutter** [comment]
@patrickvonplaten these 2 schedulers are listed in the huggingface link you just sent above. So, why are they not supported in stable diffusion ? I am not confused here.

**Comment by patrickvonplaten** [comment]
@buttercutter neither `RePaintScheduler` nor `KarrasVeScheduler` is stated on the doc page: https://huggingface.co/docs/diffusers/main/en/using-diffusers/schedulers -> note that you can always check all compatible schedulers with:
```python
pipeline.scheduler.compatibles
```

as explained here: 
https://huggingface.co/docs/diffusers/main/en/using-diffusers/schedulers#changing-the-scheduler
