### ISSUE TITLE
  --mixed_precision="fp16"  works only with accellerate config

### ISSUE THREAD

**Issue by spuliz** [huggingface/diffusers#1272]
### Describe the bug

when setting the parameters   --mixed_precision="fp16"  the system prompts the message "--mixed_precision is set to its default value to no" despite of declaring the parameters. The message disappear if I launch accelerate config and set mixed precision from there.

### System Info

Tesla T4, 15109 MiB, 15109 MiB - Colab Notebook.

**Comment by patrickvonplaten** [comment]
Hey @spuliz, 

Could you please provide a reproducible code snippet or command that we can run? 

Thank you!

**Comment by spuliz** [comment]
Hey @patrickvonplaten 

This happens when I launch Dreambooth from Google Colab. 

export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="path-to-instance-images"
export OUTPUT_DIR="path-to-save-model"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --mixed_precision= fp16
  --max_train_steps=400
  
  Notice message warning that mixed precision wasn't setup.

**Comment by patrickvonplaten** [comment]
cc @patil-suraj here

**Comment by patil-suraj** [comment]
@spuliz The warning can be ignored safely. For ease of use, we pass that argument directly when initializing the `Accelerator` object. cf https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py#L334

The launch command gives that warning, because the default value is `no`, but we later override it, so this can be ignored.

**Comment by patil-suraj** [comment]
Also, the argument `--mixed_precision` should actually be passed to `accelerate launch` instead of the script, but we will have to keep the current way as lots of users are already using it. cc @patrickvonplaten
