### ISSUE TITLE
During inpainting, scaling latent before concat break some schedulers.

### ISSUE THREAD

**Issue by BurguerJohn** [huggingface/diffusers#1276]
### Describe the bug

In pipeline_stable_diffusion_inpaint.py there is this two lines:
```
latent_model_input = torch.cat([latent_model_input, mask, masked_image_latents], dim=1)
latent_model_input = self.scheduler.scale_model_input(latent_model_input, t)
```
It seen to break some schedulers, setting scale first should fix it:

```
latent_model_input = self.scheduler.scale_model_input(latent_model_input, t)
latent_model_input = torch.cat([latent_model_input, mask, masked_image_latents], dim=1)
```

### System Info

Windows

**Comment by patrickvonplaten** [comment]
I think you're very right here! That's a great catch :-) 
Thanks to you inpaint should now work for all schedulers :heart: 

https://github.com/huggingface/diffusers/pull/1331
