### ISSUE TITLE
Update UNet1D Tests to not use Mish

### ISSUE THREAD

**Issue by natolambert** [huggingface/diffusers#1287]
**Is your feature request related to a problem? Please describe.**
Currently the `UNet1DTests` heavily rely on mish because they were based on a re-implementation of a model. This is not needed generally, so it would be good to add another 1d model just for tests so we can delete a lot of the tests that look like this.

```
    @unittest.skipIf(torch_device == "mps", "mish op not supported in MPS")
    def test_determinism(self):
        super().test_determinism()
```

**Comment by thehimalayanleo** [comment]
Hi @natolambert, wondering if I could take up this issue. And do we essentially want _some_ 1D model that can run without requiring mish? Thanks!

**Comment by natolambert** [comment]
Yeah @thehimalayanleo that's exactly right. It's preferable that it has an application, but not needed.

The RL tests can stay as is, it's just that a lot of the `UNet1D` tests were added in the RL PR, so there can be some quality of life improvements there 🤗.

**Comment by KE7** [comment]
The activation function as well should be an optional param until Mish is supported on M1. I am unable to run training even with MPS fallback enabled

**Comment by SauravMaheshkar** [comment]
@natolambert could you please explain how to fix this. This might seem stupid but doesn't simply changing the activation to `swish` in `prepare_init_args_and_inputs_for_common` solve the problem (and updating the `OutValueFunctionBlock` to not have `mish`)?

Ref: #3994
