### ISSUE TITLE
Unable to run multiple prompts in stable diffusion fast jax.ipynb

### ISSUE THREAD

**Issue by G-force78** [huggingface/diffusers#1295]
### Describe the bug

Adding multiple prompt lines as described in the blog https://huggingface.co/blog/stable_diffusion_jax

prompt_ids = pipeline.prepare_inputs(prompts)
prompt_ids = shard(prompt_ids)
images = pipeline(prompt_ids, p_params, rng, jit=True).images
images = images.reshape((images.shape[0], ) + images.shape[-3:])
images = pipeline.numpy_to_pil(images)
image_grid(images, 2, 4)

results in an error message

ValueError                                Traceback (most recent call last)
[<ipython-input-30-562eb5ffece2>](https://localhost:8080/#) in <module>
     25 num_samples = jax.device_count()
     26 prompt = num_samples * [prompt]
---> 27 prompt_ids = pipeline.prepare_inputs(prompt)
     28 prompt_ids = shard(prompt_ids)
     29 images = pipeline(prompt_ids, p_params, prng_seed, num_inference_steps, jit=True).images

### Reproduction

Use this modified cell

#@title Set and go!
#@markdown First run takes ~50s as it compiles stuff. Then, it should take around ~8s per prompt!
prompts = [
    "highly detailed photography, Danny Devito as Frodo, ((sharp focus)), photo by Annie Leibovitz, intricate, natural lighting, high quality, 4k, cover photo" 
 "digital painting of Jessica Alba as black widow",
  "HAL-9000 in the style of Van Gogh",
    "Times Square under water, with fish and a dolphin swimming around",
    "Ancient Roman fresco showing a man working on his laptop",
    "Close-up photograph of young black woman against urban background, high quality, bokeh",
    "Armchair in the shape of an avocado",
    "Clown astronaut in space, with Earth in the background",  
] 
num_inference_steps = 50 #@param {type:"integer"}
seed = -1 #@param {type:"integer"}
#@markdown `-1` will set a random seed. You can replace that to any integer for reproducible results

if(seed == -1):
  import random
  random_int = random.randint(0, 2147483647)
  real_seed = random_int
else:
  real_seed = seed
prng_seed = jax.random.PRNGKey(real_seed)
prng_seed = jax.random.split(prng_seed, jax.device_count())
num_samples = jax.device_count()
prompt = num_samples * [prompt]
prompt_ids = pipeline.prepare_inputs(prompt)
prompt_ids = shard(prompt_ids)
images = pipeline(prompt_ids, p_params, prng_seed, num_inference_steps, jit=True).images
images_pil = pipeline.numpy_to_pil(np.asarray(images.reshape((num_samples,) + images.shape[-3:])))
if(seed == -1):
  print(f"Seed used {real_seed}")
image_grid(images_pil, 2, 4)

### System Info

chex-0.1.5 commonmark-0.9.1 diffusers-0.7.2 flax-0.6.2 ftfy-6.1.1 optax-0.1.3 rich-12.6.0 tensorstore-0.1.28 tokenizers-0.13.2 transformers-4.24.0

**Comment by pcuenca** [comment]
Hi @G-force78, there are two small errors in your modified code:

- The first prompt is missing a comma in the array. Therefore `prompts` is not an array with 8 items as intended.
- When you prepare the inputs, you need to do it on your array:

```
# prompt_ids = pipeline.prepare_inputs(prompt)
prompt_ids = pipeline.prepare_inputs(prompts)   # Note: prompts instead of prompt
```

Hope that helps!
