### ISSUE TITLE
Paella

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#1296]
### Model/Pipeline/Scheduler description

Fast Text-Conditional Discrete Denoising on Vector-Quantized Latent Spaces 

abs: https://arxiv.org/abs/2211.07292
github: https://github.com/dome272/Paella 

t2i model requiring less than 10 steps to sample high-fidelity images 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/dome272/Paella/issues/2

Anybody in the community interested in adding the model ?

**Comment by nandwalritik** [comment]
Hi @patrickvonplaten Can I take this up if no one is working on it?

**Comment by aengusng8** [comment]
Hi, @patrickvonplaten I will take Paella up. Should this pipeline be a community pipeline or a native one?

**Comment by patrickvonplaten** [comment]
Oh that's awesome @aengusng8 - would you like to open a PR for it? :-) 

Yes exactly, Paella should go into the native diffusion pipelines as it's an official model with paper and official release etc..

**Comment by aengusng8** [comment]
@patrickvonplaten I will open a PR next few days.

**Comment by pcuenca** [comment]
Superseded by #3134.
