### ISSUE TITLE
Common API

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/diffusers#13]
How much of a common API do you expect there to be across different objects? For example, the `unet.py` file contains a `Trainer`, while other models seem to only rely on their `forward` method, but they have different APIs and signatures.

Same with pipelines, for example with the `BDDM` pipeline having the following arguments for it's `__call__` method: `mel_spectrogram, generator, torch_device=None`, while the `DDIM` pipeline has `batch_size=1, generator=None, torch_device=None, eta=0.0, num_inference_steps=50`.

Do we expect all of these models, pipelines, schedulers to have a common API at the end? Is that even possible with diffusers?

It seems like *most* arguments are similar, but with a few specificities for models, pipelines and schedulers. That's where having a configuration system would arguably work quite well as it would show very visibly what each of them has in terms of arguments for customization.

This reminds me a bit of the `do_lower_case` problem we have in `transformers`: some tokenizers have it, some don't, but users don't necessarily understand that and try to use it for all tokenizers.

**Comment by kashif** [comment]
One thing that is sometimes missing with the `models`'s `forward` is the notion of a `context` or `conditioning`... typically for the image gen. there is no conditioning, however for other modalities conditioning might be needed so if we can also add that in the  `forward` and by default make it none, it will be helpful!

**Comment by patil-suraj** [comment]
Thanks @kashif . I think this is exactly what @anton-l  proposed with task/modality specific sub-classes.

**Comment by patrickvonplaten** [comment]
@anton-l RE: 

> the UNet variations can definitely be consolidated into one. However, I'm in favor of keeping modality-specific subclasses, similar to ...ForTaskName in tranformers. See, for example, GLIDETextToImageUNetModel and GLIDESuperResUNetModel [here](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_glide.py#L644), where we have different forwards depending on how the model is conditioned.

Haven't looked too much into the models yet, but do we really need them to be modality specific? E.g. couldn't a vision unet also work on a spectrogram image? Think I'd be at the moment more in favor of naming the modules in `src/diffusers/models` after their input / output format and model type - e.g. unet_2d.py, unet_3d.py. In the case of glide, could that maybe mean that we have a `unet_conditional_2d.py` and a `unnet_upsample.py` module? I'm a bit worried that if we add `For<TaskName>` or `For<Modality>` too early and then find out later that those models work for other modalities it'll be a bit difficult to refactor them later on. Note here the target group is also more experienced users so they might not need the "guidance" of a modality specific name.

However, for the pipelines I'd be very much in favor of quickly making the distinction between modalities as the pipelines should 1-to-1 reflect architectures proposed in papers. Here the target group is less experienced users which just want to run the model as presented in a paper. 

What do you think @patil-suraj @anton-l ?

**Comment by patrickvonplaten** [comment]
Not super excited about early-on introducing a pipeline config, but happy to brainstorm about it (don't know much about majestic yet :-))

**Comment by patrickvonplaten** [comment]
Also closing as the API is now finalized and explain on the main README: https://github.com/huggingface/diffusers
