### ISSUE TITLE
Examples contain hardcoded model names

### ISSUE THREAD

**Issue by allo-** [huggingface/diffusers#1300]
### Describe the bug

Commit [c18941b](https://github.com/huggingface/diffusers/commit/c18941b01ad0ea6b07d020f353d81153c632a374) introduced hardcoded model names in the example scripts. Most of them should probably be replaced by `args.pretrained_model_name_or_path`.

### Reproduction

Run one of the scripts with a model in a local folder and the commandline option `--pretrained_model_name_or_path model_folder`.
The script nevertheless tries to download stable diffusion and either downloads an unnecessary model or fails because of a missing huggingface token.

### System Info

Version: [4625f04](https://github.com/huggingface/diffusers/commit/4625f04bc04bed43c1ba9b821149af121b5965ea)

**Comment by patrickvonplaten** [comment]
Hey @allo-,

You are very right! Would you like to open a PR to change it ? :-) Otherwise happy to do it !

**Comment by allo-** [comment]
I don't think I can test all places from the commit.
In the other PR, the test suite seems to fail as well in code unrelated to my changes. At least I've got quite a few bot mails about it.

How is the test coverage for the places changed in this commit (and maybe the previous ones. I had a look at the history of textual_inversion to find when it changed)?

**Comment by patrickvonplaten** [comment]
Here we go: https://github.com/huggingface/diffusers/pull/1778 -> won't have time to do the same changes for Flax though.
