### ISSUE TITLE
How to train text guided image to image stable diffusion?

### ISSUE THREAD

**Issue by StrugglingForBetter** [huggingface/diffusers#1304]
This repository has https://github.com/huggingface/diffusers/tree/main/examples/text_to_image to do text to image training method? How to do image to image finetuning or training with text guided? Is there any example?

**Comment by patrickvonplaten** [comment]
Hey @StrugglingForBetter,

We haven't found time to add a image-to-image fine-tuning example. Feel free to give it a try yourself - we'd love to host a image-to-image fine-tuning example :-)
