### ISSUE TITLE
Direct Inversion: Optimization-Free Text-Driven Real Image Editing with Diffusion Models

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#1305]
### Model/Pipeline/Scheduler description

https://arxiv.org/abs/2211.07825

Could be cool to try to build a pipeline with this :-) 

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

Will weights, code be open-sourced cc @adham-elarabawy maybe? :-)

**Comment by adham-elarabawy** [comment]
Yes. Releasing diffusers-integrated codebase for the paper later this week.
