### ISSUE TITLE
ImportError: cannot import name 'PIL_INTERPOLATION' from 'diffusers.utils'

### ISSUE THREAD

**Issue by Pirog17000** [huggingface/diffusers#1315]
### Describe the bug

Hour ago been able to generate images. Now, I see this string in log.

### Reproduction

Basically, try to generate an image, like, NOW

### Logs

```shell
.cache\huggingface\modules\diffusers_modules\git\lpw_stable_d │
│ iffusion.py:15 in <module>                                                  │
│                                                                             │
│     12 from diffusers.pipelines.stable_diffusion import StableDiffusionPipe │
│     13 from diffusers.pipelines.stable_diffusion.safety_checker import Stab │
│     14 from diffusers.schedulers import DDIMScheduler, LMSDiscreteScheduler │
│ >   15 from diffusers.utils import PIL_INTERPOLATION, deprecate, is_acceler │
│     16 from transformers import CLIPFeatureExtractor, CLIPTextModel, CLIPTo │
│     17                                                                      │
│     18                                                                      │

\lib\site-packages\diffusers\utils\__init__.py
```
```


### System Info

Diffusers: 0.7.2
Windows 10

**Comment by hardik-a-joshi** [comment]
getting same error

**Comment by plambe** [comment]
Me too, in a google colab notebook that worked 24 hours ago

**Comment by patrickvonplaten** [comment]
Sorry that's on me! Fixing with @pcuenca now

**Comment by patrickvonplaten** [comment]
Reverting the change now for all community pipelines sorry!

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/pull/1317

**Comment by pcuenca** [comment]
Should be fixed now, can you please try again @Pirog17000, @stevenhales, @hardik-a-joshi, @plambe?

Sorry about that!

**Comment by adhikjoshi** [comment]
Everyone who had issue, reinstall new diffusers

pip install git+https://github.com/HuggingFace/diffusers.git

It will fix error,

**Comment by plambe** [comment]
It is fixed and thanks for the rapid reaction!

**Comment by pcuenca** [comment]
> Everyone who had issue, reinstall new diffusers

Actually, that should no longer be necessary after the fix in #1317 was merged. Can anyone please confirm that it works again?

**Comment by pcuenca** [comment]
@plambe awesome, thanks a lot!

**Comment by adhikjoshi** [comment]
works well, that was fast, really appreciate it.
