### ISSUE TITLE
Right set of UNet hyperparameters when training DDPM

### ISSUE THREAD

**Issue by leopoldmaillard** [huggingface/diffusers#1318]
Hi there !
I am currently training a DDPM model on a custom image dataset following the cool [unconditional_image_generation](https://github.com/huggingface/diffusers/blob/main/examples/unconditional_image_generation/train_unconditional.py) example script.

Since I don't have the compute to perform comprehensive hyperparameter tuning of my architecture, I was wondering if there are any common intuitions when designing the `UNet` denoiser : **width/length of the residual blocks, number and positions of the attention blocks, etc. with respect to the number of samples in the training set as well as their resolution**.

If anyone has a wide experience in training DMs, it would be super cool to share insights here or in a dedicated blog post such as the one [discussing the hyperparameters choice when training Dreambooth](https://huggingface.co/blog/dreambooth).

Thank you ! 🤗

**Comment by patrickvonplaten** [comment]
Maybe cc @anton-l ?

**Comment by leopoldmaillard** [comment]
I guess this problem will be further addressed in the upcoming unit 2 _Fine-Tuning and Guidance_ of the [HF Diffusion Course](https://github.com/huggingface/diffusion-models-class) !

Also, @lewtun mentioned "When dealing with higher-resolution inputs you may want to use more down and up-blocks, and keep the attention layers only at the lowest resolution (bottom) layers to reduce memory usage." in the course's introductory notebook.

**Comment by patrickvonplaten** [comment]
cc @anton-l again here

**Comment by leopoldmaillard** [comment]
Hello @anton-l, thank you for your insight ! 

I also found out that Dhariwal & Nichol discussed hyperparameters tuning of DDPM in their paper _Diffusion Models Beat GANs on Image Synthesis_.

Will close this for now !
