### ISSUE TITLE
[Community Pipeline] RePaint + Stable Diffusion

### ISSUE THREAD

**Issue by anton-l** [huggingface/diffusers#1333]
## Intro

Community Pipelines are introduced in `diffusers==0.4.0` with the idea of allowing the community to quickly add, integrate, and share their custom pipelines on top of `diffusers`. 

You can find a guide about Community Pipelines [here](https://github.com/huggingface/diffusers/issues/841). You can also find all the community examples under [`examples/community/`](https://github.com/huggingface/diffusers/tree/main/examples/community). If you have questions about the Community Pipelines feature, please head to the [parent issue](https://github.com/huggingface/diffusers/issues/841).

## Idea: Combining RePaint with Stable Diffusion

The idea of this pipeline is to improve upon the [legacy stable diffusion inpainting pipeline](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py) by making use of the [RePaint approach](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/repaint/pipeline_repaint.py)

At the moment the `RePaint` pipeline only works for image diffusion, as opposed to latent diffusion (as in Stable Diffision). But making the RePaint scheduler work with latent diffusion would be a great way to improve unsupervised inpainting results!

Resources:

* Legacy unsupervised inpainting pipeline: https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py
* RePaint pipeline that doesn't support latent diffusion: https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/repaint/pipeline_repaint.py
* Original RePaint project page and paper: https://github.com/andreas128/RePaint/

**Comment by nathanielherman** [comment]
Ooh I actually implemented this today https://github.com/huggingface/diffusers/pull/1341/files!

**Comment by Randolph-zeng** [comment]
And a minimum code snippet to reproduce the repaint stuff is here, might need only 1~2 minutes to set up this experiment.
Note _repaint_ddim_scheduler_ and _sd_repaint_pipeline_ are the two files I copied from the PR. You only need to change the relative import to the correct diffusers lib import to make following code snippet to work ( which should only takes you at most 2 minutes to create such local files). A quick note is that there are two small bugs I mentioned above, please check my comments in the PR to fix those two lines 
```
import PIL
import requests
from io import BytesIO
from schedulers.repaint_ddim_scheduler import RePaintScheduler
from pipelines.sd_repaint_pipeline import StableDiffusionRepaintPipeline

def download_image(url):
    response = requests.get(url)
    return PIL.Image.open(BytesIO(response.content)).convert("RGB")

img_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo.png"
mask_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo_mask.png"

init_image = download_image(img_url).resize((512, 512))
mask_image = download_image(mask_url).resize((512, 512))

pipe = StableDiffusionRepaintPipeline.from_pretrained('/cognitive_comp/common_data/stable-diffusion-v1-5').to(7)
pipe.scheduler = RePaintScheduler.from_config(pipe.scheduler.config)
prompt = "a bright lamp, high resolution, highly detailed, placed on a park bench"
outpiant_res = pipe(init_image=init_image,
    mask_image=mask_image,
    prompt=prompt,
    num_inference_steps=100,
    guidance_scale=2.5,
    jump_length=1,
    jump_n_sample=2)
outpiant_res.images[0]
```
