### ISSUE TITLE
multiple gpu parallel for train dreambooth without cuda out memory

### ISSUE THREAD

**Issue by loboere** [huggingface/diffusers#1340]
I have 2 gpus and I would like to use both to train dreambooth without cuda out memory

They say that I should use nn.DataParallel , but I don't know where to put it

**Comment by averad** [comment]
@loboere are you referring to this pytorch [documentation](https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html) 

```
if torch.cuda.device_count() > 1:
  print("Let's use", torch.cuda.device_count(), "GPUs!")
  # dim = 0 [30, xxx] -> [10, ...], [10, ...], [10, ...] on 3 GPUs
  model = nn.DataParallel(model)

model.to(device)
```

**Comment by camenduru** [comment]
I am also curious 🤔
@loboere please try https://github.com/huggingface/accelerate
```
pip install accelerate
accelerate config
```

**Comment by patrickvonplaten** [comment]
I strongly advise against using `nn.DataParallel`, even PyTorch doesn't recommend it using anymore. Instead one should use https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html#torch.nn.parallel.DistributedDataParallel instead
