### ISSUE TITLE
Offline training

### ISSUE THREAD

**Issue by Bayern4ever-dot** [huggingface/diffusers#1342]
I would like to the train diffusion model offline, can I download the pre-training model from the website in advance?

**Comment by pcuenca** [comment]
Absolutely! The easiest way, I think, would be to follow these instructions: https://github.com/huggingface/diffusers/blob/main/README.md#running-the-model-locally

You can pass your local folder to any of the training scripts in our examples folder.

**Comment by Bayern4ever-dot** [comment]
> 

I got it,thanks~

**Comment by aaaleeexTLC** [comment]
Hi guys, I'm also trying to run this locally, were you able to do it?

How is it done? I saw this on documentation:
------------------------------- 
you need to download the weights first
Then load the saved weights into the pipeline:
pipeline = DiffusionPipeline.from_pretrained("./stable-diffusion-v1-5")

Now you can run the pipeline as you would in the section above.
------------------------------- 

I tried setting an environment variable with 

export pipeline = DiffusionPipeline.from_pretrained("./my_local_model.ckpt")

But it didn't work

**Comment by LT1st** [comment]
> 绝对地！我认为最简单的方法是遵循以下说明：https://github.com/huggingface/diffusers/blob/main/README.md#running-the-model-locally
> 
> 您可以将本地文件夹传递到示例文件夹中的任何训练脚本。

Cannot find this link

**Comment by asomoza** [comment]
that's because that answer was posted in Nov 19, 2002. If you still want to find that (don't really know why), this is the permalink:

https://github.com/huggingface/diffusers/tree/v0.7.2?tab=readme-ov-file#running-the-model-locally

Right now, you can just download the model and use the local filepath to train/inference.
