### ISSUE TITLE
train dreambooth with runway inpainting model

### ISSUE THREAD

**Issue by loboere** [huggingface/diffusers#1345]
Does anyone know a way to train dream booth with runway inpainting?

**Comment by thedarkzeno** [comment]
I have a PR with the code, you can test it if you want: https://github.com/huggingface/diffusers/pull/1091

**Comment by pcuenca** [comment]
The PR was merged.

**Comment by Efrat-Taig** [comment]
I trained dreambooth with inpainting.  you can contact me for details https://www.linkedin.com/in/efrattaig/

**Comment by loboere** [comment]
can someone add the inpainting option in the dreambooth colab here
https://github.com/huggingface/diffusers/blob/acd317810bc138b3a78fa30e1b3da1006c1d60ad/docs/source/training/overview.mdx

https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_dreambooth_training.ipynb

**Comment by gabguerin** [comment]
Did you train it on colab ? I get OutOfMemory errors when I try it

**Comment by kunalgoyal9** [comment]
> I trained dreambooth with inpainting. you can contact me for details [linkedin.com/in/efrattaig](https://www.linkedin.com/in/efrattaig/)

Hi @Efrat-Taig I have sent you a mail, if you can please check it out.
Thanks
