### ISSUE TITLE
how to combine train_unconditional.py with LDMPipline

### ISSUE THREAD

**Issue by panenyaun** [huggingface/diffusers#1353]
### Describe the bug

how to combine train_unconditional.py with LDMPipline

### System Info

diffuser=0.6.0
python=3.8.12
pycharm

**Comment by patrickvonplaten** [comment]
Hey @panenyaun, 

Note that `train_unconditional.py` is a simple example how to train a diffusion model from scratch. The idea is not to create an all-encompassing example to train/fine-tune all diffusion models. However we would be happy to add a new example script for `train_unconditional_latent.py` if you're interested!
