### ISSUE TITLE
img2img results in noisy image with low num_inference_steps

### ISSUE THREAD

**Issue by jonasdoevenspeck** [huggingface/diffusers#1368]
I'm trying to make a video with the `StableDiffusionImg2ImgPipeline` but am encountering some unexpected behavior.
I generate the first frame by using the `StableDiffusionPipeline` with relatively many steps (e.g. 100). This frame is then slightly warped (e.g. rotation, translation, zoom). Next I feed the frame to `StableDiffusionImg2ImgPipeline` to slightly refine the warped image. The translated image will have empty sides now (black pixels) which I expect to be made coherent. 

However, when using a small `num_inference_steps`, the image becomes very noisy. Using more `num_inference_steps` results in a completely different image. I realize I can use the `strength` to module this behavior but since it is essentially the same as changing `num_inference_steps`, it doesn't help.

I realize that inpainting could help but this only works for translate and rotate since for zoom there are no black pixels (mask).

Is there any setting for which this video generation would be smooth? Or is the `StableDiffusionImg2ImgPipeline` just not suited for this application/task?

**Comment by jonasdoevenspeck** [comment]
@pedrogengo yes.
I first generate the following image with `StableDiffusionPipeline` (prompt is something with 'chess')
![000001](https://user-images.githubusercontent.com/28825134/203647521-eedc936d-ecb5-462c-8c13-a36adf03e5f7.png)
This image is then slightly zoomed (5% only) and fed into the `StableDiffusionImg2ImgPipeline` with the same prompt used the generate the initial image, `num_inference_steps = 2` and `strength=1`.
The output is as follows:
![000002](https://user-images.githubusercontent.com/28825134/203647796-b2cb2720-e5e0-491f-9b71-d8eb557d9e6a.png)

**Comment by patrickvonplaten** [comment]
Can only second @pedrogengo here, the `strength` parameter is way too strong

**Comment by jonasdoevenspeck** [comment]
Thanks for the tips @pedrogengo and @patrickvonplaten. I tried your suggestion (but with `num_inference_steps = 100` and `strength = 0.1` and indeed it looks better for the first step now:
![000003](https://user-images.githubusercontent.com/28825134/204895851-58574b66-2a24-42b9-b0ad-d78d5421955a.png)

However when zooming in further, the image becomes blurry again:
![000009](https://user-images.githubusercontent.com/28825134/204896000-6c8ea64b-be2a-43e6-b8da-3f1873b88b20.png)

I tried with many different combinations of  `num_inference_steps` and `strength` but I can't manage to get a good result. My goal is to make a video with smooth transitions between frames and with:
1) zoom, translation, rotation between frames.
2) new features emerging in the image 

To give you an idea I made such a video already with VQGAN-CLIP: https://www.youtube.com/watch?v=T_bii9VLDk0
I was hoping to get better looking visuals with Stable-Diffusion. However, is it possible that the way stable diffusion works, it is not possible to make such videos?

**Comment by jonasdoevenspeck** [comment]
@patrickvonplaten and @pedrogengo are you aware of any examples (code and video) that succesfully have used the img2img-pipeline to generate videos?

**Comment by patrickvonplaten** [comment]
That's a good question! @jonasdoevenspeck,

I'm sure someone in our discord would know :-) Would you like to join the discord: https://discord.gg/G7tWnz98XR and maybe ask there under "discussions" for diffusion models? I'm sure someone has some good leads.
