### ISSUE TITLE
ImportError: cannot import name 'CLIPVisionModelWithProjection' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)

### ISSUE THREAD

**Issue by BlackDeveloping** [huggingface/diffusers#1377]
### Describe the bug

ImportError: cannot import name 'CLIPVisionModelWithProjection' from 'transformers' (/usr/local/lib/python3.9/dist-packages/transformers/__init__.py)
1 hour ago it worked nice. 

### System Info

last, all, all

**Comment by aablsk** [comment]
Seeing the same issue. I suspect it's related to the new 0.8.0 release?

**Comment by Mistobaan** [comment]
seeing this too. Installing the version of transformers from github seems to work but definitely diffusers will need a new release:

```pip install git+https://github.com/huggingface/transformers.git```

**Comment by aablsk** [comment]
Can confirm that downgrading to 0.7.2 fixes the issue as well.

**Comment by pcuenca** [comment]
Thanks for reporting this! We are working on it, meanwhile please install `transformers` from github as @Mistobaan suggested above.

`pip install git+https://github.com/huggingface/transformers.git`

**Comment by plambe** [comment]
I have the same issue; installing transformers from git works for me too

**Comment by patrickvonplaten** [comment]
Sorry about this! We working on a fix asap - we'll do a patch release in 30min

**Comment by anton-l** [comment]
Fixed in a patch release `0.8.1`: https://github.com/huggingface/diffusers/releases/tag/v0.8.1
:warning: Please upgrade with `pip install --upgrade diffusers` or `pip install diffusers==0.8.1`
