### ISSUE TITLE
Repeated operation in Transformer2DModel

### ISSUE THREAD

**Issue by Warvito** [huggingface/diffusers#1379]
It looks like Norm operation is repeated in the Transformer2DModel.forward method in lines:

https://github.com/huggingface/diffusers/blob/f07a16e09bb5b1cf4fa2306bfa4ea791f24fa968/src/diffusers/models/attention.py#L203

and

https://github.com/huggingface/diffusers/blob/f07a16e09bb5b1cf4fa2306bfa4ea791f24fa968/src/diffusers/models/attention.py#L210

**Comment by Warvito** [comment]
Fixed in #1381

**Comment by patrickvonplaten** [comment]
Thanks for the issue @Warvito !
