### ISSUE TITLE
ImportError:  LDMTextToImagePipeline requires the transformers library but it was not found in your environment.

### ISSUE THREAD

**Issue by skuma307** [huggingface/diffusers#138]
Hi, Thanks for a fantastic model but when I am installing it on Colab, It throws the below error.

`ImportError: 
LDMTextToImagePipeline requires the transformers library but it was not found in your environment. You can install it with pip.`

I have installed it via `!pip install diffusers transformers` and I am able to import both the libraries successfully.

Can anyone help me fix the issue?

**Comment by anton-l** [comment]
Hi @skuma307! Could you try hitting "Restart runtime" in the colab, and re-running `!pip install diffusers transformers` before any imports?
