### ISSUE TITLE
Shouldn't PNDMScheduler have an add_noise() method, too?

### ISSUE THREAD

**Issue by Quasimondo** [huggingface/diffusers#139]
Maybe a naive question, but I was following the tutorial notebooks and was testing to exchange schedulers and noticed that it was missing there but is present in both DDIM and DDPM.

**Comment by natolambert** [comment]
Hi Quasimondo, I think this is down to the differences between the algorithms. Here are the papers for [DDPM](https://proceedings.neurips.cc/paper/2020/file/4c5bcfec8584af0d967f1ab10179ca4b-Paper.pdf) and [PNDM](https://arxiv.org/pdf/2202.09778.pdf) (you can also find the corresponding code in the top of our files).

I think the TLDR is that DDPM is sampling from a distribution of epsilons, while PNDM directly predicts the epsilon / sample. You can see this in how PDNM does not have a variance schedule in the form of `alpha` or `beta`.

Feel free to re-open if you have a more specific pointer than I do! I'm learning these things on the way.
