### ISSUE TITLE
Create Colab Notebook for training script

### ISSUE THREAD

**Issue by mrm8488** [huggingface/diffusers#14]
I have seen in the TO-DO list that you think to create a Colab to train the DM in examples folder.
I can do it!

**Comment by anton-l** [comment]
That would be awesome, @mrm8488!
Feel free to open a draft PR in https://github.com/huggingface/notebooks (under a new directory `/diffusers/`) and ping me in the collab channel on Slack if you have any questions :)

**Comment by patrickvonplaten** [comment]
We now have two notebooks here: https://github.com/huggingface/notebooks/tree/main/diffusers

**Comment by patrickvonplaten** [comment]
We'd be more than happy for more colabs :-)

**Comment by mrm8488** [comment]
> We'd be more than happy for more colabs :-)

I will open a PR with another notebook
