### ISSUE TITLE
StableDiffusionSafetyChecker's non-voided images are not the same as without safety checker

### ISSUE THREAD

**Issue by regisss** [huggingface/diffusers#1403]
### Describe the bug

For a given pipeline, the non-voided images returned by the safety checker are different from the images we get with the same pipeline without safety checker.

It seems to come from the initialization of the `CLIPVisionModel` inside the `__init__` of `StableDiffusionSafetyChecker`. More specifically, this line in Transformers with `torch.randn` seems to be the culprit: https://github.com/huggingface/transformers/blob/afce73bd9d891b55dcb8d4d875d17718ffa01ff0/src/transformers/models/clip/modeling_clip.py#L178

### Reproduction

To reproduce this issue, please run the following code snippet twice: once as it is and once commenting the line `safety_checker=None`.

```python
from diffusers import StableDiffusionPipeline
from diffusers.training_utils import enable_full_determinism


enable_full_determinism(27)

generator = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    safety_checker=None,
)

outputs = generator(
    ["An image of a squirrel in Picasso style"],
    num_images_per_prompt=1,
    height=256,
    width=256,
)

for i, image in enumerate(outputs.images):
    image.save(f"image_{i+1}.png")
```

### System Info

GPU = V100
CUDA = 11.6
torch = 1.13.0/1.11.0
diffusers = main/0.8.1/0.7.2
transformers = 4.24.0

**Comment by regisss** [comment]
Edited the first post with hints about what may cause this issue.

**Comment by patrickvonplaten** [comment]
Hey @regisss,

Actually this is expected since the random generator is forwarded when loading / initializing the model. The function:
`enable_full_determinism` should always be run **after** `from_pretrained` -> then the outputs should match.

**Comment by regisss** [comment]
Thanks for the explanation @patrickvonplaten, it indeed solves this issue :slightly_smiling_face:
