### ISSUE TITLE
😱 PR #1395 causes ValueError expected 'feature_extractor' in Onnx Pipeline with SD 2.0 Models

### ISSUE THREAD

**Issue by averad** [huggingface/diffusers#1407]
### Describe the bug

@patrickvonplaten 

#1395 optional "feature_extractor" is not so optional. Issue when loading SD 2.0 Models as they contain:

```
  "feature_extractor": [
    null,
    null
  ],
```

### Reproduction

Install [Diffusers ](https://github.com/huggingface/diffusers/tree/cbfed0c25606a70b5c4faf819575b46267434847) from PR #1395 
Convert stable-diffusion-2-base to Onnx

```
from diffusers import OnnxStableDiffusionPipeline
height=512
width=512
num_inference_steps=50
guidance_scale=7.5
prompt = "a photo of an astronaut riding a horse on mars"
negative_prompt="bad hands, blurry"
pipe = OnnxStableDiffusionPipeline.from_pretrained("./stable-diffusion-2-base_onnx", provider="DmlExecutionProvider", safety_checker=None)
image = pipe(prompt, height, width, num_inference_steps, guidance_scale, negative_prompt).images[0] 
image.save("astronaut_rides_horse.png")
```

### Logs

```shell
Traceback (most recent call last):
pipe = OnnxStableDiffusionPipeline.from_pretrained(
  File "\lib\site-packages\diffusers\pipeline_utils.py", line 672, in from_pretrained
    raise ValueError(
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_onnx_stable_diffusion.OnnxStableDiffusionPipeline'> expected {'feature_extractor', 'safety_checker', 'text_encoder', 'vae_encoder', 'unet', 'vae_decoder', 'tokenizer', 'scheduler'}, but only {'safety_checker', 'text_encoder', 'vae_encoder', 'unet', 'vae_decoder', 'tokenizer', 'scheduler'} were passed.
```

### System Info
- `diffusers` version:[ 0.9.0.dev0](https://github.com/huggingface/diffusers/tree/cbfed0c25606a70b5c4faf819575b46267434847) PR #1395
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.0+cpu (False)
- Huggingface_hub version: 0.11.0
- Transformers version: 4.25.0.dev0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
Thanks a lot for the ping @averad - @anton-l if you have a minute could you check?

**Comment by anton-l** [comment]
Adapted and reverted some of the changes from the linked PR: #1416
Thank you for reporting @averad!
