### ISSUE TITLE
Running difussers with GPU

### ISSUE THREAD

**Issue by jfdelgad** [huggingface/diffusers#143]
Running the example codes i see that the CPU and not the GPU is used, is there a way to use GPU instead

**Comment by natolambert** [comment]
Can you be more specific? This was not the intent.

Are you looking at this [file](https://github.com/huggingface/diffusers/blob/main/examples/train_unconditional.py) or something different?

**Comment by jfdelgad** [comment]
Thanks for your reply. I just installed the repo and run the example in the read me. This was ran using the CPU although there is a cuda card present. Is there a documentation page for the repo?

```
# !pip install diffusers transformers
from diffusers import DiffusionPipeline

model_id = "CompVis/ldm-text2im-large-256"

# load model and scheduler
ldm = DiffusionPipeline.from_pretrained(model_id)

# run pipeline in inference (sample random noise and denoise)
prompt = "A painting of a squirrel eating a burger"
images = ldm([prompt], num_inference_steps=50, eta=0.3, guidance_scale=6)["sample"]

# save images
for idx, image in enumerate(images):
    image.save(f"squirrel-{idx}.png")
```

**Comment by anton-l** [comment]
Hi @jfdelgad! You can set the pipeline's `torch_device` explicitly like so:
```python
images = ldm([prompt], num_inference_steps=50, eta=0.3, guidance_scale=6, torch_device="cuda")["sample"]
```

The docs for `diffusers` are still in progress, but they will be out in the next couple of weeks :)

**Comment by jfdelgad** [comment]
The issue seems to have been on my machine, it works well now.
