### ISSUE TITLE
AttributeError: 'OnnxRuntimeModel' object has no attribute 'config'

### ISSUE THREAD

**Issue by john1089** [huggingface/diffusers#1433]
when i am trying to run stable-diffusion with onnx,there is a problem.it is like this:
Traceback (most recent call last):
  File "\txt2img.py", line 8, in <module>
    pipe = OnnxStableDiffusionPipeline.from_pretrained("./libs/stable_diffusion_onnx", provider="CPUExecutionProvider", safety_checker=None)
  File "\venv\lib\site-packages\diffusers\pipeline_utils.py", line 677, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 102, in __init__
    is_unet_version_less_0_9_0 = hasattr(unet.config, "_diffusers_version") and version.parse(
AttributeError: 'OnnxRuntimeModel' object has no attribute 'config'
my system is windows10.
so how can i fix this?

**Comment by john1089** [comment]
put txt2img.py down here:
```python
from diffusers import OnnxStableDiffusionPipeline
height=512
width=512
num_inference_steps=50
guidance_scale=7.5
prompt = "a photo of an astronaut riding a horse on mars"
negative_prompt="bad hands, blurry"
pipe = OnnxStableDiffusionPipeline.from_pretrained("./libs/stable_diffusion_onnx", provider="CPUExecutionProvider", safety_checker=None)
image = pipe(prompt, height, width, num_inference_steps, guidance_scale, negative_prompt).images[0] 
image.save("astronaut_rides_horse.png")
```

**Comment by averad** [comment]
Where did you download stable_diffusion_onnx from or what steps did you follow to download the stable_diffusion_onnx folder?

**Comment by john1089** [comment]
i downloaded it from huggingface:
`git clone https://huggingface.co/runwayml/stable-diffusion-v1-5 --branch onnx --single-branch stable_diffusion_onnx`

**Comment by averad** [comment]
Are you using diffusers 0.9.0?

**Comment by john1089** [comment]
yes

**Comment by john1089** [comment]
ok,it was fixed

**Comment by JiaojiaoYe1994** [comment]
> put txt2img.py down here:
> 
> ```python
> from diffusers import OnnxStableDiffusionPipeline
> height=512
> width=512
> num_inference_steps=50
> guidance_scale=7.5
> prompt = "a photo of an astronaut riding a horse on mars"
> negative_prompt="bad hands, blurry"
> pipe = OnnxStableDiffusionPipeline.from_pretrained("./libs/stable_diffusion_onnx", provider="CPUExecutionProvider", safety_checker=None)
> image = pipe(prompt, height, width, num_inference_steps, guidance_scale, negative_prompt).images[0] 
> image.save("astronaut_rides_horse.png")
> ```

Hi John, I also tried to inference on text-to-image task using `OnnxStableDiffusionPipeline`. However, when I used ONNXRuntime model, I can not inference pipeline on GPU. Have you ever tried this on GPU?
