### ISSUE TITLE
when using diffusers and transformer: module transformers has no attribute FeatureExtractionMixin

### ISSUE THREAD

**Issue by TheOneTrueGuy** [huggingface/diffusers#1439]
### Describe the bug

I'm trying to use diffusers alongside another package, CLIP Interrogator. When I install the dependencies for CLIP Interrogator my diffuser code goes kerplooie! and throws this error: module transformers has no attribute FeatureExtractionMixin

### Reproduction

a notebook with the code to replicate this behavior is here: https://colab.research.google.com/drive/1W3NS1_dMhlZNYLybjLMRr-l9G3TdxN9L?usp=sharing
![error_clip_diffusers_11_26_2022](https://user-images.githubusercontent.com/3240071/204119582-d461465d-7a93-4dcf-881f-26532b88cacc.PNG)

### System Info

running on a google colab

**Comment by kashif** [comment]
Thank you for the report! I believe it is the `BLIP` requirement of Clip Interrogator that pins transformers to an older version from last December and thus can you kindly try to upgrade transformers and try?

**Comment by TheOneTrueGuy** [comment]
I changed the transformer install to the most recent version and still get the same result.

**Comment by TheOneTrueGuy** [comment]
swapped the transformer install so it followed the BLIP install and that changed the error. Now it's doing this:
![errors2](https://user-images.githubusercontent.com/3240071/204154790-c70206d3-f4e5-45d4-b6ac-c3c666647edd.PNG)
I'll see if the maker of CLIP Interrogator responds this time...

**Comment by patrickvonplaten** [comment]
Hey @TheOneTrueGuy,

Sorry could you give me access to the colab or even better just copy-paste your code snippet here?

**Comment by TheOneTrueGuy** [comment]
No, sorry to you, Patrick. We got it fixed yesterday afternoon and I just didn't have time to report here. I restricted that version after I posted a version to my github account that works. Still a little dicey and I'd prefer a version that works with the later version of diffusers and CLIP but it works for now,. Please check it out, it makes some trippy animations: https://github.com/TheOneTrueGuy/DigitalDayDream

**Comment by patrickvonplaten** [comment]
Cool!

**Comment by TheOneTrueGuy** [comment]
yes, I'm having a huge fun time. I've spun off another version that transforms videos instead of feedback-looping the init frame. Gotta say it's fire. It's in the same repo if you have 10 minutes to try it.
![Xfer_short60a_2fps](https://user-images.githubusercontent.com/3240071/205417056-c0ea4289-7156-4454-a96c-0304a33a4bac.gif)
