### ISSUE TITLE
TensorFlow and Flax/Jax

### ISSUE THREAD

**Issue by will-rice** [huggingface/diffusers#144]
Will this library be similar to transformers and include TensorFlow and Flax implementations at some point?

**Comment by natolambert** [comment]
Yes that is on the longer-term road map. Moderate term we want to make the schedulers interface well with `numpy` (which then lets one use their own non-torch models), but making the models all independent is more substantial of an undertaking.

We would happily provide feedback if you want to open a PR!

**Comment by patrickvonplaten** [comment]
We're currently adding JAX with see https://github.com/huggingface/diffusers/issues/475 . We don't plan on adding TF in anytime soon.
