### ISSUE TITLE
Delete Cached Model

### ISSUE THREAD

**Issue by adhikjoshi** [huggingface/diffusers#1440]
### Describe the bug

Hi have been using diffusers, it works fine. after 10-20 model loading using

`from_pretrained("CompVis/stable-diffusion-v1-4"`

`from_pretrained("hakurei/waifu-diffusion"`
.
and tens of more,

what i found is saved model cache is building up, how can i remove a specific pre-trained model from disk? or all of cached models?

### System Info

diffusers 8.0

**Comment by patrickvonplaten** [comment]
Good question! 

1. By default the models are cached under:
`"./.cache/huggingface/hub/"` 
There the models cache directories are called according to their repo ids e.g. "models--CompVis--stable-diffusion-v1-4"
=> so to delete one model cache you can just delete the whole directory:
```
rm -rf .cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/
```

2. You can also define the cache_dir yourself to have better control over it:
```python
pipe = DiffusionPipeline.from_pretrained(..., cache_dir="your/cache/dir")
```

3. Finally, we're also working on a PR that lets you return the cached path when downloading the model which should be helpful!:
https://github.com/huggingface/diffusers/pull/1450
