### ISSUE TITLE
ImportError: cannot import name 'StableDiffusionSafetyChecker' 

### ISSUE THREAD

**Issue by liu6381810** [huggingface/diffusers#1444]
### Describe the bug

`ImportError: cannot import name 'StableDiffusionSafetyChecker' from 'diffusers.pipelines.stable_diffusion' (/home/tiger/anaconda3/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/__init__.py)`

### System Info

diffusers=0.9.0 python=3.9

**Comment by patrickvonplaten** [comment]
Do you have `transformers` installed? Please attach a full list of your installed versions here.

The following works for me:

```python
from diffusers.pipelines.stable_diffusion import StableDiffusionSafetyChecker
```
