### ISSUE TITLE
[Announcement] Stable Diffusion v1-4/v1-5 have lifted gated access! => No need to be logged into hf.co anymore!

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#1447]
https://huggingface.co/CompVis/stable-diffusion-v1-4
https://huggingface.co/CompVis/stable-diffusion-v1-3
https://huggingface.co/CompVis/stable-diffusion-v1-2
https://huggingface.co/CompVis/stable-diffusion-v1-1

are all no longer gated!

This means you don't have to be logged in to download the model. Just doing:

```python
from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
```

Will now always download the `"CompVis/stable-diffusion-v1-4"` no matter if you're logged in or not.

**Update**

https://huggingface.co/runwayml/stable-diffusion-v1-5 is no longer gated either.

**Comment by 88stacks** [comment]
nice, was this broken partially today, all my code that was normally working all of a sudden died on not being able to download CompVis/stable-diffusion-v1-4

**Comment by patrickvonplaten** [comment]
> today

The Hub might have been down

**Comment by Yesdazero** [comment]
![Screenshot_20230310-012812](https://user-images.githubusercontent.com/127429385/224104350-b5c83223-48ca-41cf-8ed7-ba7af11758c9.png)

**Comment by Yesdazero** [comment]
![Screenshot_20230310-012442](https://user-images.githubusercontent.com/127429385/224104596-c186d23e-38eb-405b-87ff-4028f5cd11cc.png)
