### ISSUE TITLE
Wishlist: example for training a superresolution pipeline

### ISSUE THREAD

**Issue by Quasimondo** [huggingface/diffusers#146]

**Comment by rashmimarganiatgithub** [comment]
I can do this if no one has taken this up yet.

**Comment by rashmimarganiatgithub** [comment]
@patrickvonplaten  here I found some pretrained weights: [link](https://github.com/krasserm/super-resolution).

**Comment by pcuenca** [comment]
Hi @rashmimarganiatgithub, thanks for the pointer! However, I think those methods are not using diffusion techniques. For the diffusers repo we would be interested to showcase super-resolution models based on diffusion, such as the upscaling steps performed in [Imagen](https://www.assemblyai.com/blog/how-imagen-actually-works/), for instance. Would you agree with that @patrickvonplaten?

**Comment by rashmimarganiatgithub** [comment]
@pcuenca, Please check the updated links, I was still updating the link. In the updated link under [pretrained-ldms](https://github.com/CompVis/latent-diffusion#pretrained-ldms) you can find the weight for super-resolution contributed by open image community

**Comment by patrickvonplaten** [comment]
True - thanks for the pointer @rashmimarganiatgithub,

There is indeed one super-resolution checkpoint under: https://ommer-lab.com/files/latent-diffusion/sr_bsr.zip 
=> do we know if it's a good one?

**Comment by rashmimarganiatgithub** [comment]
@patrickvonplaten, I didn't test it yet. These weights are from models trained on Openimages datast with 600 categories so I assume it is good.

**Comment by patrickvonplaten** [comment]
Cool - thanks for letting me know! Also cc @patil-suraj @anton-l FYI in you think it could make sense to test it out

**Comment by ElliotQi** [comment]
How is it going? I'm also interested in this!

**Comment by renhaa** [comment]
I am also very interested!

**Comment by patil-suraj** [comment]
Will test out the model, and comment here, thanks a lot for sharing this!

Also, if anyone is interested feel free to open a PR to add this, more than happy to help.

**Comment by patil-suraj** [comment]
Thanks to @duongna21 the latent diffusion super resolution model is now available in `diffusers` 

```python
from diffusers import LDMSuperResolutionPipeline
from PIL import Image

pipe = LDMSuperResolutionPipeline.from_pretrained('CompVis/ldm-super-resolution-4x-openimages')
pipe.to('cuda')

img = Image.open('low_resolution.jpg')
super_img = pipe(img, num_inference_steps=100, eta=1)
super_img['images'][0]
```

**Comment by theahura** [comment]
Thanks a ton! Out of curiosity, is there info on the required GPU size to run this for different resolutions?

**Comment by patil-suraj** [comment]
Haven't tried this extensively, but on a 16GB GPU I was able to do `128x128` -> `1024x1024`
