### ISSUE TITLE
Autoencoder scale values in config

### ISSUE THREAD

**Issue by samedii** [huggingface/diffusers#1460]
**What API design would you like to have changed or added to the library? Why?**

Would be nice to have some way of getting the appropriate scale value for the VAE like saving it in the config. It is now hardcoded in the pipelines.

I am referring to these two:
```
1 / 0.08333
1 / 0.18215
```

**What use case would this enable or better enable? Can you give us a code example?**

We could avoid hard coding this piece of information "everywhere" with something like

```
vae.latent_scale  # 1 / 0.18215
```

**Comment by patrickvonplaten** [comment]
Actually related to this: https://github.com/huggingface/diffusers/issues/732

**Comment by samedii** [comment]
`scale_value` sounds okay to my ears. I could change the code to handle this and make a PR but I'm afraid it would break all the pretrained checkpoints on huggingface that do not have this value in their configs.

Do you have any ideas for how to handle that?

Dispatch based on number of blocks if it's missing...

**Comment by patrickvonplaten** [comment]
Hey @samedii, 

It shouldn't break any checkpoints on the Hub if we set the right default :-)

**Comment by samedii** [comment]
There are two defaults now though. Upscaling uses `0.08333`

**Comment by samedii** [comment]
Looks like @williamberman has solved it but without a default value. 

Maybe I'm missing something and there is a nice solution. Do we have any other information available than what's in "vae.config"?

```
{
  "_class_name": "AutoencoderKL",
  "_diffusers_version": "0.9.0.dev0",
  "_name_or_path": "hf-models/stable-diffusion-x4-upscaler/vae",
  "act_fn": "silu",
  "block_out_channels": [
    128,
    256,
    512
  ],
  "down_block_types": [
    "DownEncoderBlock2D",
    "DownEncoderBlock2D",
    "DownEncoderBlock2D"
  ],
  "in_channels": 3,
  "latent_channels": 4,
  "layers_per_block": 2,
  "norm_num_groups": 32,
  "out_channels": 3,
  "sample_size": 256,
  "up_block_types": [
    "UpDecoderBlock2D",
    "UpDecoderBlock2D",
    "UpDecoderBlock2D"
  ]
}
```

Otherwise we basically have to select the default value based on matching against the config. E.g. the upscaler vae uses one less block.

**Comment by patrickvonplaten** [comment]
But I think that's what we want right -> retrieve value from the config. cc @williamberman

**Comment by williamberman** [comment]
I'm going to close this issue as a dup of https://github.com/huggingface/diffusers/issues/726 and also note that @patil-suraj is almost done with a PR fixing here https://github.com/huggingface/diffusers/pull/1860 !

fyi @samedii :)
