### ISSUE TITLE
StableDiffusionInpaintPipeline - unassigned variable bug when inferencing with multiple images and masks

### ISSUE THREAD

**Issue by zxydi1992** [huggingface/diffusers#1462]
### Describe the bug

The `StableDiffusionInpaintPipeline` seems to support `torch.Tensor` as inputs. However, the code contains a bug that made the inference fail. 

The bug is located at line 654 and line 675 in [pipeline_stable_diffusion_inpaint.py](https://github.com/huggingface/diffusers/blob/v0.9.0/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py)

Error message:

>   Traceback (most recent call last):
>     File "/opt/conda/envs/diffusers/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>       fn(i, \*args)
>     File "/home/XXXXX/sd_inpaint.py", line 142, in main
>       inpainted = pipe(prompt=[prompt] * len(images), image=images,  mask_image=masks).images
>     File "/opt/conda/envs/diffusers/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>       return func(\*args, \*\*kwargs)
>     File "/opt/conda/envs/diffusers/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 629, in __call__
>       mask,
>   UnboundLocalError: local variable 'mask' referenced before assignment

Reasoning: In line 654, the code does not define 'mask' variable if the input type is not `torch.Tensor`; while at line 675, `mask` is used in the arguments to the function call.
  
Besides, line 678 should change to `num_images_per_prompt`, because mask is already in batch form, the piece `mask = mask.repeat(batch_size, 1, 1, 1)` in line 538 would make the output mask longer than we need in the first axis.

Suggest fix: since `prepare_mask_and_masked_image` function already supports `torch.Tensor` as inputs, we can remove the if statement in line 654.

### System Info

diffusers==0.8.1
python=3.8.5

**Comment by patrickvonplaten** [comment]
Hey @zxydi1992,

Could you please provide a reproducible code snippet? 
E.g. one where you import `StableDiffusionInpaintPipeline` and then run it in inference?

**Comment by kampta** [comment]
I got the same error. Here is a minimal reproducible example

```
import torch
from diffusers import StableDiffusionInpaintPipeline

inpaint = StableDiffusionInpaintPipeline.from_pretrained(
            "runwayml/stable-diffusion-inpainting",
        ).to("cuda")
mask = torch.ones(512, 512, 1, device='cuda')
image = torch.zeros(512, 512, 3, device='cuda')
image = inpaint(prompt='A cat', image=image, mask_image=mask)
```

**Comment by patrickvonplaten** [comment]
Hey @kampta,

Thanks for the repro: 

It should be fixed with https://github.com/huggingface/diffusers/pull/1527

Note that you need to pass mask and image in the following format though:
[batch_size, num_channels, width, length]

You example should therefore look as follows and should work once #1527 is merged:
```python
import torch
from diffusers import StableDiffusionInpaintPipeline

inpaint = StableDiffusionInpaintPipeline.from_pretrained(
            "runwayml/stable-diffusion-inpainting",
        ).to("cuda")
mask = torch.ones(1, 1, 512, 512, device='cuda')
image = torch.zeros(1, 3, 512, 512, device='cuda')
image = inpaint(prompt='A cat', image=image, mask_image=mask)
```

**Comment by kampta** [comment]
Thanks
