### ISSUE TITLE
Is it possible to use VersatileDiffusion for Seq2Seq generation training?

### ISSUE THREAD

**Issue by HZQ950419** [huggingface/diffusers#1464]
Hi,

Thanks for the amazing project for diffusion models! I'm interested in Seq2Seq generation with diffusion models. Thus is it possible to use VersatileDiffusion model for Seq2Seq generation training? Or are you planning to add text-to-text generation pipeline in Diffusers?

Thanks!

**Comment by patrickvonplaten** [comment]
Hey @HZQ950419,

We sadly haven't found the time yet to add text-to-text for versatile diffusion. If you want to give it a try adding it that'd be amazing :-)
