### ISSUE TITLE
what's the paper of conditional unet ?

### ISSUE THREAD

**Issue by taki0112** [huggingface/diffusers#148]
Hello.

Can you tell me the paper name in [condional_unet architecture](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_condition.py) ? 

I wonder what paper this model structure is based on. 
What paper is this model used in?

**Comment by anton-l** [comment]
Hi @taki0112! Our UNet is based on several implementations listed in the [Credits](https://github.com/huggingface/diffusers#credits). It's highly configurable in order to reproduce and port all kinds of previously published UNets from that list to a single codebase.

**Comment by taki0112** [comment]
@anton-l Thank you for the comments!
