### ISSUE TITLE
`deprecate` should point to the usage of the deprecated thing

### ISSUE THREAD

**Issue by keturn** [huggingface/diffusers#1480]
This warning message:
> /opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/diffusers/utils/deprecation_utils.py:35: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_lms_discrete.LMSDiscreteScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
>  warnings.warn(warning + message, FutureWarning)

does not tell me anything about where the offending usage of `from_config` is taking place.

It should probably be using the `stacklevel` argument to [`warn`](https://docs.python.org/3.9/library/warnings.html?highlight=stacklevel#warnings.warn) so it doesn't just point to a line in your `deprecate` function all the time.

**Comment by patrickvonplaten** [comment]
Yes, 100% agree. Thanks for the issue. Opening a PR
