### ISSUE TITLE
question on set_timesteps 

### ISSUE THREAD

**Issue by naoto0804** [huggingface/diffusers#1491]
Thank you for releasing a wonderful repository! Let me ask a newbie question.

**What API design would you like to have changed or added to the library? Why?**
`diffusers.DDPMScheduler.set_timesteps`

**What use case would this enable or better enable? Can you give us a code example?**
I guess `diffusers.DDPMScheduler.set_timesteps` is for faster sampling.
However, `diffusers.DDPMScheduler.step` seems to sample x_{t-1} given x_{t}, according to [here](https://github.com/huggingface/diffusers/blob/v0.9.0/src/diffusers/schedulers/scheduling_ddpm.py#L271-L272). Is there any official way to sample x_{t-a} given x_{t} (a > 1) easily other than manually unrolling the step function?

**Comment by patrickvonplaten** [comment]
Thanks for the nice words. Sorry I don't fully understand the issue here :sweat_smile: - could maybe leave some pseudo-code to explain? Thanks!
