### ISSUE TITLE
Cannot import name 'init_git_repo' from 'diffusers.hub_utils'

### ISSUE THREAD

**Issue by FogoVoar** [huggingface/diffusers#1495]
### Describe the bug

To be honest I'm not sure if this is a bug, but since it started happening all of a sudden in the last few hours I'm going to assume it is.
I'm using a Colab setup with Dreambooth to fine tune Stable Diffusion 1.4, the error happens when executing the cell that tries to import the 'init_git_repo' from 'diffusers.hub_utils'.

### Reproduction

The issue can be reproduced by running the first 3 cells of [this notebook](https://github.com/PsorTheDoctor/artificial-intelligence/blob/master/modern_approach/text_to_image/dreambooth.ipynb).

### Logs

```shell
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-6dd94e0be846> in <module>
     14 from accelerate.utils import set_seed
     15 from diffusers import AutoencoderKL, DDPMScheduler, PNDMScheduler, StableDiffusionPipeline, UNet2DConditionModel
---> 16 from diffusers.hub_utils import init_git_repo, push_to_hub
     17 from diffusers.optimization import get_scheduler
     18 from diffusers.pipelines.stable_diffusion import StableDiffusionSafetyChecker

ImportError: cannot import name 'init_git_repo' from 'diffusers.hub_utils' (/usr/local/lib/python3.7/dist-packages/diffusers/hub_utils.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

### System Info

![image](https://user-images.githubusercontent.com/112202663/204880973-a5e2004f-aa42-42f3-96ff-5b74ec217b1c.png)
(I would copy and paste the plain text here but ctrl+c doesn't work in google colab's terminal and the context menu has no option to copy)

**Comment by FogoVoar** [comment]
For now I've been able to bypass the problem by commenting the highlighted line out (surprisingly).
But I'll leave the issue open in case someone else doesn't have the same luck.

**Comment by WASasquatch** [comment]
> ![image](https://user-images.githubusercontent.com/112202663/204880973-a5e2004f-aa42-42f3-96ff-5b74ec217b1c.png) (I would copy and paste the plain text here but ctrl+c doesn't work in google colab's terminal and the context menu has no option to copy)

Next time, run it from a throw-away cell `!diffusers-cli env`

**Comment by patrickvonplaten** [comment]
Hey @FogoVoar,

Thanks for the bug report. This should be solved by now cc @anton-l no?

**Comment by Ayo-faks** [comment]
i still experience the same issue
