### ISSUE TITLE
Reading model from a local file

### ISSUE THREAD

**Issue by prp-e** [huggingface/diffusers#150]
Greetings. 

Consider I have a `model.ckpt` file, and it's trained and saved on my local computer. It's not hosted on huggingface and let's consider it's a little bit confidential and cannot be hosted anywhere. How can I feed it into `from_pretrained()` function?

**Comment by anton-l** [comment]
Hi @prp-e! You can load a local model using `from_pretrained("local/path")` if it was previously saved there with `model.save_pretrained("local/path")`.

**Comment by prp-e** [comment]
Great. I was curious if it is possible to use [multimodalart/majesty-diffusion](https://github.com/multimodalart/majesty-diffusion) with diffusers. I guess it's not possible yet.

**Comment by anton-l** [comment]
Not yet, but community model contributions are very much welcome! 🤗  cc @apolinario

**Comment by patrickvonplaten** [comment]
Could we open a new issue about adding "majesty-diffusion" to not loose track here. Closing this one as "Reading model from a local file" was answered above.
