### ISSUE TITLE
[Discussion]Any practice for deploying model inferences provided by diffusers into a web service?

### ISSUE THREAD

**Issue by VXenomac** [huggingface/diffusers#1502]
I'm trying deploying model inferences provided by diffusers into a web service.
I'm planning to use [fastapi](https://github.com/tiangolo/fastapi) or [BentoML](https://github.com/bentoml/BentoML) to build, but haven't found anything that works with diffusers directly.
I would greatly appreciate if you have good advice or practice to share.

**Comment by patrickvonplaten** [comment]
I don't really know, but sounds like a great question! Also note we have a very active discord channel for these kinds of questions: https://discord.gg/G7tWnz98XR
