### ISSUE TITLE
Use consistent random number generation across hardware

### ISSUE THREAD

**Issue by antoche** [huggingface/diffusers#1514]
**Is your feature request related to a problem? Please describe.**

`pytorch.randn` is not consistent across hardware devices (See https://github.com/pytorch/pytorch/issues/84234).

`diffusers` calls `torch.randn` on the device computation is run on (typically 'cuda'). As a result, results produced with the exact same parameters will differ across machines.

**Describe the solution you'd like**

Until the issue is resolved in pytorch itself, `diffusers` should use a deterministic RNG so results can be consistent across hardware.

One possible workaround is to keep using `torch.rng` while enforcing generation to happen on the cpu, which currently seems consistent no matter the hardware.

Here is an example solution:

```
def randn(size, generator=None, device=None, **kwargs):
    """
    Wrapper around torch.randn providing proper reproducibility.

    Generation is done on the given generator's device, then moved to the
    given ``device``.

    Args:
        size: tensor size
        generator (torch.Generator): RNG generator
        device (torch.device): Target device for the resulting tensor
    """
    # FIXME: generator RNG device is ignored and needs to be passed to torch.randn (torch issue #62451)
    rng_device = generator.device if generator is not None else device
    image = torch.randn(size, generator=generator, device=rng_device, **kwargs)
    image = image.to(device=device)
    return image


def randn_like(tensor, generator=None, **kwargs):
    return randn(tensor.shape, layout=tensor.layout, generator=generator, device=tensor.device, **kwargs)
```

Calling these functions instead of the `torch` ones, with a generator whose device is `cpu`, gives deterministic results and still allows for the rest of the computations to run on cuda.

This would also simplify and speed up all the tests, which can simply use `cpu`-bound generators and leave `device` to be `cuda` even for those relying on RNG.

**Describe alternatives you've considered**

It's also possisble to switch to `numpy`'s RNG, which is deterministic. The above solution is more `torch`-native.

**Comment by patrickvonplaten** [comment]
@patil-suraj @anton-l @pcuenca @williamberman curious to hear your opinion here.

**Comment by antoche** [comment]
Agree that this may be a performance concern for some. 

With the proposal I suggested, no change in the interface or new function is needed. Users get deterministic results by passing a generator using device="cpu", and more performant, less deterministic results (i.e, current behaviour) by passing a generator using device="cuda" (which I believe is the default).

Note that this also addresses an issue in pytorch where the generator's device is sometimes ignored (https://github.com/pytorch/pytorch/issues/62451)

**Comment by pcuenca** [comment]
Sorry for the delay in reacting to this.

I agree that random number generation is a mess and it's worthwhile taking a closer look. In addition, we have ugly workarounds for platform-specific bugs, such as `mps`.

I think many users won't care about reproducibility. The opt-in mechanism to use a `cpu`-backed Generator looks a bit obscure to me, but it may be enough for those who do. So, two main options here:

- Adopt this solution as is, and create a documentation page about how to achieve reproducible results.
- Create a helper as Patrick suggested. I'd call it something like `enable_reproducibility()`, as `set_deterministic()` sounds to me like "always produce the same results given the same inputs".

Since reproducibility is more of an advanced feature, I think it would suffice to use the first approach for now.

In any case (whether we add a helper or not), I'm in favor of adopting the proposed functions and use them throughout the code base. We could take advantage of them in our tests, and they could absorb the workarounds for `mps` too.

**Comment by williamberman** [comment]
Agreed reproducibility is really nice. Just for my own context, outside of our test suite, what's the general use case for reproducibility? In my limited experience so far most of the diffusion model codebases I've worked on have just used the standard torch rng functionality.

**Comment by antoche** [comment]
Reproducibility/determinism is not just a "nice thing, it's vitally important for multiple reasons:
- For research, if results are not reproducible, then other researchers cannot compare their results against previous work. Reproducibility is a cornerstone of the scientific process.
- For contributors, if tests aren't reproducible on their machines, then it is a major hindrance in contributing to a project. If the tests don't even pass on a contributor's machine without any changes, they don't know what their changes might be breaking.
- For production software, reproducibility is a requirement. If a developer writes software relying on a library that is not deterministic, they can't make any guarantees that their software will be reliable, and they can't write reliable tests for their own code. 
- For users, reproducibility is an important feature. The same inputs ought to result in the same results, so users can explore and refine their work, build on other users' inputs, as well as recover it if the outputs have been lost.

**Comment by patrickvonplaten** [comment]
@antoche this issue should now be solved. See guide here: https://huggingface.co/docs/diffusers/using-diffusers/reproducibility

**Comment by antoche** [comment]
That's great, thanks a lot for this!

One thing I've noticed while working on this issue is that there are quite a few random functions being used throughout the codebase and its dependencies, so I ended up with the following approach in the meantime.

I wrote this methods which provides a patch of any random function ensuring that function runs generation on the generator's device:

```python
def _patch_rand(randfn):
    """
    Returns a deterministic version of the given random function.

    Args:
        randfn (function): Function to wrap.
    Returns:
        function: A function wrapping the input random function and enforcing RNG to happen
            on the ``generator``'s device no matter what the target ``device`` is.
    """

    def new_rand(*args, generator=None, device=None, **kwargs):
        """
        Wrapper around any torch random function providing proper reproducibility.

        Generation is done on the given generator's device, then moved to the
        given ``device``.

        Args:
            size: tensor size
            generator (torch.Generator): RNG generator
            device (torch.device): Target device for the resulting tensor
        """
        if generator is None:
            raise ValueError(f"No generator passed to {randfn.__module__}.{randfn.__name__}, result will be non-deterministic!")
        # FIXME: generator RNG device is ignored and needs to be passed to torch.randn (torch issue #62451)
        rng_device = generator.device if generator is not None else device
        result = randfn(*args, generator=generator, device=rng_device, **kwargs)
        result = result.to(device=device)
        return result

    return new_rand
```

I call it for all these torch random number generating functions:
```python

_functions_to_patch = (
    "bernoulli",
    "multinomial",
    "normal",
    "poisson",
    "rand",
    "rand_like",
    "randint",
    "randint_like",
    "randn",
    "randn_like",
    "randperm",
)
```

And finally I have a context manager which replaces all the `torch` functions with the patched ones, so the default behaviour is unchanged and caller can choose to use the patched pathway using the decorator, e.g.

```python
with random.patch():
   # Patched random functions will be used here
   pipeline = ...
   result = pipeline(...)
# Original functions will be used here
```

This has the benefit of capturing more RNG functions and not having to replace every call site by a different function, as well as capturing RNG uses within dependencies themselves, and flagging RNG uses where no generator is passed at all. The downside is that it's up to the user to opt-in (which may be an upside for some) rather than being automatically more deterministic.

The in-place `Tensor` RNG methods like `Tensor.normal_` are not addressed either.

This might or might not be an approach you want to adopt, just showing this here as something you might consider an improvement (I find it serves my needs fairly well).

**Comment by patil-suraj** [comment]
cc @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @antoche,

Thanks for the write-up, I'm sure that this is very useful to the community! I think it's a bit overkill for `diffusers` because all random functions we're using during inference are random normal function that we've now wrapped into a `randn_tensor` function
