### ISSUE TITLE
UNet2DConditionModel: TypeError: forward() got an unexpected keyword argument 'encoder_hidden_states'

### ISSUE THREAD

**Issue by rousseau** [huggingface/diffusers#1522]
### Describe the bug

Hi everyone,

I try to use the UNet2DConditionModel with images as conditional input (for super-resolution purpose) in a Pytorch Lightning code. However, when I call the unet.forward function, this error message appears:
TypeError: forward() got an unexpected keyword argument ‘encoder_hidden_states’

I don’t understand the reason since this ‘encoder_hidden_states’ argument is required when calling the forward function of unet.

Thanks in advance for any help.

### Reproduction

import torch
from torch import nn
from torchvision import datasets
import torchvision.transforms as transforms

transform = transforms.ToTensor()

train_data = datasets.MNIST(root = 'data', train = True, download = True, transform = transform)
test_data = datasets.MNIST(root = 'data', train = False, download = True, transform = transform)

#normalize between -1,1
norm = transforms.Lambda(lambda t: (t/255.0 * 2) - 1)

pad = transforms.Pad(2)
train_data= torch.unsqueeze(norm(pad(train_data.data)), dim=1)
test_data= torch.unsqueeze(norm(pad(test_data.data)), dim=1)
 
device = torch.device("cpu") if not torch.cuda.is_available() else torch.device("cuda:0")

#%%

from diffusers import UNet2DConditionModel

unet = UNet2DConditionModel(
    sample_size=32,  # the target image resolution
    in_channels=1,  # the number of input channels, 3 for RGB images
    out_channels=1,  # the number of output channels
    layers_per_block=2,  # how many ResNet layers to use per UNet block
    block_out_channels=(16, 32, 64, 128),  # the number of output channes for each UNet block
    norm_num_groups = 16,
    down_block_types=( 
        "DownBlock2D",  # a regular ResNet downsampling block
        "AttnDownBlock2D",  # a ResNet downsampling block with spatial self-attention
        "DownBlock2D", 
        "DownBlock2D",
    ), 
    up_block_types=(
        "UpBlock2D",  # a regular ResNet upsampling block
        "AttnUpBlock2D",  # a ResNet upsampling block with spatial self-attention
        "UpBlock2D", 
        "UpBlock2D",  
      ),
)

from diffusers import DDPMScheduler, DDIMScheduler, DPMSolverMultistepScheduler, PNDMScheduler
n_timesteps = 1000
noise_scheduler = DDPMScheduler(num_train_timesteps=n_timesteps)

#%%

import pytorch_lightning as pl
import torch.nn.functional as F

class DiffusionModel(pl.LightningModule):
    def __init__(self, unet, scheduler):
        super().__init__()
        
        self.unet = unet
        self.scheduler = scheduler

        self.img_size = 32
        self.LR_size = 8
        self.interp = transforms.InterpolationMode.NEAREST

    def training_step(self, batch, batch_idx):
        clean_images = batch
        
        #LR image simulation
        LR_images = nn.UpsamplingNearest2d(size = dm.img_size)(nn.AvgPool2d(kernel_size=int(dm.img_size/dm.LR_size))(clean_images))

        # Sample noise to add to the images
        noise = torch.randn(clean_images.shape).to(self.device)
        bs = clean_images.shape[0]
        
        # Sample a random timestep for each image
        timesteps = torch.randint(0, self.scheduler.num_train_timesteps, (bs,), device=self.device).long()

        # Add noise to the clean images according to the noise magnitude at each timestep
        # (this is the forward diffusion process)
        noisy_images = self.scheduler.add_noise(clean_images, noise, timesteps)
   
        noise_pred = self.unet(sample = noisy_images, timestep=timesteps, encoder_hidden_states=LR_images, return_dict=False)[0]    

        loss = F.mse_loss(noise_pred, noise)

        self.log("train/loss", loss)
        return loss

    @torch.no_grad()
    def sample(self, batch):
        batch_size = batch.shape[0]
        image_shape = (batch_size, self.unet.in_channels, self.unet.sample_size, self.unet.sample_size)
        image = torch.randn(image_shape, generator=None, device=device)

        self.unet.to(device)
        batch = batch.to(device)
        timesteps = self.scheduler.timesteps.to(device) 
        
        for t in timesteps:
            # 1. predict noise model_output
            model_output = self.unet(sample=image, timestep=t, encoder_hidden_states=batch).sample

            # 2. compute previous image: x_t -> x_t-1
            image = self.scheduler.step(model_output, t, image).prev_sample 

        image = (image / 2 + 0.5).clamp(0, 1)
        image = image.cpu().numpy()  

        batch.detach()
        timesteps.detach()

        return image

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-4)
        return optimizer  

dm = DiffusionModel(unet=unet, scheduler=noise_scheduler) 

#%%

batch_size = 512
trainloader = torch.utils.data.DataLoader(train_data, batch_size=batch_size)

max_epoch = 50
trainer = pl.Trainer(
    max_epochs=max_epoch, 
    log_every_n_steps=10, 
    gpus=1, 
    auto_select_gpus=True,
)
trainer.fit(dm, trainloader)

### System Info

pytorch                   1.12.1
pytorch-lightning     1.7.2
huggingface-hub    0.11.1
diffusers                 0.9.0

**Comment by patrickvonplaten** [comment]
Hey @rousseau,

Thanks for reporting the error here. I cannot run your code snippet because it says:
```
IndentationError: expected an indented block
```

Could you maybe try to provide a short, consise code snippet that reproduces the error without any other code that is not necessary? Or alternatively provide a google colab?

**Comment by rousseau** [comment]
Please find a link to a colab notebook :
https://colab.research.google.com/drive/1E6oSbI1l7PnQrq87phvS2gr8AGJ-X4ew?usp=sharing

**Comment by patrickvonplaten** [comment]
Note that we don't official support PyTorch Lightning in the library and I suspect the bug to come from there. Could you maybe try to single out the responsible code for the bug - if it's not related to PyTorch lightning it would be much easier to solve from our side :-)

**Comment by rousseau** [comment]
It does not seem to be related to Lightning. 

Below a minimal code producing the same error:

`from diffusers import UNet2DConditionModel

unet = UNet2DConditionModel(
    sample_size=32,  # the target image resolution
    in_channels=1,  # the number of input channels, 3 for RGB images
    out_channels=1,  # the number of output channels
    layers_per_block=2,  # how many ResNet layers to use per UNet block
    block_out_channels=(16, 32, 64, 128),  # the number of output channes for each UNet block
    norm_num_groups = 16,
    down_block_types=( 
        "DownBlock2D",  # a regular ResNet downsampling block
        "AttnDownBlock2D",  # a ResNet downsampling block with spatial self-attention
        "DownBlock2D", 
        "DownBlock2D",
    ), 
    up_block_types=(
        "UpBlock2D",  # a regular ResNet upsampling block
        "AttnUpBlock2D",  # a ResNet upsampling block with spatial self-attention
        "UpBlock2D", 
        "UpBlock2D",  
      ),
)

from diffusers import DDPMScheduler
n_timesteps = 1000
noise_scheduler = DDPMScheduler(num_train_timesteps=n_timesteps) 

import torch

bs = 16
shape = (bs,1,32,32)
images = torch.randn(shape)
timesteps = torch.randint(0, noise_scheduler.num_train_timesteps, (bs,))

pred = unet(sample = images, timestep=timesteps, encoder_hidden_states=images, return_dict=False)[0]    
`

**Comment by pcuenca** [comment]
The problem seems to be [here](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_condition.py#LL335).

`UNet2DConditionModel` sends the `encoder_hidden_states` intended for cross-conditioning based on whether the module has an `attentions` property or not. `AttnDownBlock2D` has `attentions`, but doesn't do cross-attention and does not accept `encoder_hidden_states` in its forward call: https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_blocks.py#L495

@patrickvonplaten how do you think we should address this?

**Comment by rousseau** [comment]
Ok. Thanks @pcuenca . I understand the issue.

**Comment by rousseau** [comment]
@pcuenca In the colab notebook, I change "AttnDownBlock2D" to "CrossAttnDownBlock2D".

However, there is another issue (which might be related to a mis-understanding from me).
In the doc, encoder_hidden_states (torch.FloatTensor) — (batch, channel, height, width) encoder hidden states.
So in the minimal code, encoder_hidden_states=batch (batch of images).
But it raises the following issue : 
<img width="975" alt="image" src="https://user-images.githubusercontent.com/398895/205439439-dc1551af-a72e-48be-94b2-3a377091a544.png">

I guess the format (shape) is not correct but it is consistent with the doc.

**Comment by patrickvonplaten** [comment]
@pcuenca ah yeah the check is not ideal at the moment. We should probably rather add a `has_cross_attention` property to the block and then check this instead of "has attention blocks" - feel free to open a PR for this :-) 

@rousseau, good catch, this is indeed a bug in the docs, fixing it!

**Comment by pcuenca** [comment]
Fixed (#1554, #1560).
