### ISSUE TITLE
examples/textual_inversion.py Poor quality training outcome with SD2.0

### ISSUE THREAD

**Issue by zagglez** [huggingface/diffusers#1524]
### Describe the bug

examples/textual_inversion.py Latest commit [6c56f05](https://github.com/huggingface/diffusers/commit/6c56f05097f7d3c561f02dc1c27e3dd7e9f88ce1)

This commit trains against SD1.5 well.

It does train SD2.0 but NOT well.  Perhaps it is not using SD2.0's OpenCLIP, still using SD1.x CLIP?

### Reproduction

Train against 2.0-base.  Inference with fp16 - trained object rarely appears in output and if it does, very unconvincing.

Train against 1.5.  Inference with fp16 - trained object always appears and is well synthesised.

### Logs

```shell
n/a  - training completes properly - the problem is the quality of the training.
```

### System Info

 `diffusers` version: 0.9.0
- Platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.10
- Python version: 3.8.13
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.24.0

**Comment by patrickvonplaten** [comment]
Hey @zagglez,

Could you please provide a reproducible code snippet? For more information on how to do so, you can also check: https://huggingface.co/course/chapter8/5?fw=pt
