### ISSUE TITLE
`VQDiffusionPipeline` missing `learned_classifier_free_sampling_embeddings`

### ISSUE THREAD

**Issue by xenova** [huggingface/diffusers#1530]
### Describe the bug

When trying to load a pretrained `VQDiffusionPipeline`, it says that `learned_classifier_free_sampling_embeddings` is not passed. I also looked at the cache directory, and the corresponding folder is also missing (https://huggingface.co/microsoft/vq-diffusion-ithq/tree/main/learned_classifier_free_sampling_embeddings)

### Reproduction

```python
import torch
from diffusers import VQDiffusionPipeline

pipeline = VQDiffusionPipeline.from_pretrained("microsoft/vq-diffusion-ithq", torch_dtype=torch.float16, revision="fp16")
pipeline = pipeline.to("cuda")

image = pipeline("teddy bear playing in the pool").images[0]

# save image
image.save("./teddy_bear.png")
```

Note: this is the example from https://github.com/microsoft/VQ-Diffusion#integration-with--diffusers-library

### Logs

```shell
Fetching 12 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 11907.18it/s]
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
Traceback (most recent call last):
  File "convert/script.py", line 4, in <module>
    pipeline = VQDiffusionPipeline.from_pretrained(
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\lib\site-packages\diffusers\pipeline_utils.py", line 674, in from_pretrained
    raise ValueError(
ValueError: Pipeline <class 'diffusers.pipelines.vq_diffusion.pipeline_vq_diffusion.VQDiffusionPipeline'> expected {'vqvae', 'tokenizer', 'scheduler', 'text_encoder', 'transformer', 'learned_classifier_free_sampling_embeddings'}, but only {'transformer', 'vqvae', 'scheduler', 'tokenizer', 'text_encoder'} were passed.
```

### System Info

```sh
- `diffusers` version: 0.9.0
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.8.3
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
```

**Comment by patrickvonplaten** [comment]
Hey @xenova,

Thanks a lot for the issue. At the moment VQDiffusionPipeline has not enough usage that would deserve a lot of attention IMO. 
We are only a few maintainers of this library and sadly won't have the time to look into it. 

That being said, if you're interesting in adding such a feature, we would be more than happy to help you out :-)

**Comment by patrickvonplaten** [comment]
FYI cc @williamberman

**Comment by williamberman** [comment]
Hey @xenova this is because we forgot to upload fp16 weights after we updated the model with classifier free sampling 🤕. I'll get on uploading the updated fp16 weights but in the meantime fp32 should work, sorry about that!

```
import torch
from diffusers import VQDiffusionPipeline

pipeline = VQDiffusionPipeline.from_pretrained("microsoft/vq-diffusion-ithq")
pipeline = pipeline.to("cuda")

image = pipeline("teddy bear playing in the pool").images[0]

# save image
image.save("./teddy_bear.png")
```

**Comment by xenova** [comment]
Thanks for the responses!

>  At the moment VQDiffusionPipeline has not enough usage that would deserve a lot of attention IMO

100% agree - the actual reason I was trying to load it was for the VQVAE itself. This is because I wanted a pretrained `VQModel` for super resolution with latent diffusion (https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion_superresolution.py). I tried using stable diffusion's `AutoEncoderKL`, but it didn't work - which I assume is due spatial alignment of the latent space (Unless I am making some mistake).

> I'll get on uploading the updated fp16 weights but in the meantime fp32 should work

Great!
