### ISSUE TITLE
Image Variation Pipeline

### ISSUE THREAD

**Issue by misbahsy** [huggingface/diffusers#1535]
### Describe the bug

Image variation pipeline is giving me the following error:

` File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py", line 401, in __call__
    image_embeddings = self._encode_image(image, device, num_images_per_prompt, do_classifier_free_guidance)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_image_variation.py", line 208, in _encode_image
    dtype = next(self.image_encoder.parameters()).dtype
TypeError: parameters() missing 1 required positional argument: 'self'
`
Seems to be a bug, let me know if it is something I am missing.

### Reproduction

```python

repo_id = "stabilityai/stable-diffusion-2-base"
scheduler = EulerDiscreteScheduler.from_pretrained(repo_id, subfolder="scheduler")
model = StableDiffusionImageVariationPipeline.from_pretrained(repo_id, torch_dtype=torch.float16,safety_checker=None, revision="fp16",image_encoder=CLIPVisionModelWithProjection, scheduler=scheduler,use_auth_token=HF_AUTH_TOKEN).to("cuda")
generator = torch.Generator("cuda")
with autocast("cuda"):
    images = model(image=image,height=height,width=width,num_inference_steps=num_inference_steps,guidance_scale=guidance_scale,num_images_per_prompt=num_images_per_prompt,generator=generator).images

    

### Logs

_No response_

### System Info

It's an ubuntu env with the latest diffusers from github.

**Comment by patrickvonplaten** [comment]
@misbahsy could you please run:

```
diffusers-cli env
```
and post the version output here?

**Comment by misbahsy** [comment]
@patrickvonplaten It gives me the following:
`diffusers-cli: command not found`

Don't think the cli is available for me? Is there a specific installation for it?

**Comment by rskvazh** [comment]
I think yours "stabilityai/stable-diffusion-2-base" probably can not condition on image embeddings, only text? You need `repo_id = "lambdalabs/sd-image-variations-diffusers"`

**Comment by patrickvonplaten** [comment]
@misbahsy,

you need to install diffusers as follows:

```
git clone https://github.com/huggingface/transformers
cd transformers
pip install -e .
```

This will automatically install `diffusers-cli `
