### ISSUE TITLE
Apple MPS and KDPM2AncestralDiscreteScheduler & KDPM2DiscreteScheduler

### ISSUE THREAD

**Issue by FahimF** [huggingface/diffusers#1537]
### Describe the bug

The above two schedulers have issues when running under Apple MPS. It looks as if `float64` to `float32` conversion is not handled correctly for MPS for either of these. See attached screenshots for errors. 
![CleanShot 2022-12-04 at 08 32 41@2x](https://user-images.githubusercontent.com/181110/205475110-a09e93f2-bd89-46ff-b43f-6ebd094942b8.jpg)
![CleanShot 2022-12-04 at 08 36 25@2x](https://user-images.githubusercontent.com/181110/205475115-823ce109-9e0e-47a6-b6fe-70c778218325.jpg)

### Reproduction

Simply use the KDPM2AncestralDiscreteScheduler or the KDPM2DiscreteScheduler with Stable Diffusion v2 base model. This is how I tested.

### Logs

```shell
Logs shown in screenshots attached above.
```

### System Info

- `diffusers` version: 0.10.0.dev0
- Platform: macOS-13.1-arm64-arm-64bit
- Python version: 3.9.13
- PyTorch version (GPU?): 1.14.0.dev20221124 (False)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0
- Using GPU in script?: Using MPS
- Using distributed or parallel set-up in script?: No

**Comment by patrickvonplaten** [comment]
Thanks for opening cc @pcuenca here maybe

**Comment by patrickvonplaten** [comment]
@pcuenca should we maybe open this one up for the community if you're busy? :-)

**Comment by keturn** [comment]
still exists in 0.12.1, stalebot.
