### ISSUE TITLE
Conversion Script Type Int Incorrect

### ISSUE THREAD

**Issue by dnwalkup** [huggingface/diffusers#1539]
### Describe the bug

In https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py

The argument --prediction_type is incorrectly defined as INT when the helper is guiding to pass type STRING. 

### Reproduction

Any attempt to use the script to convert diffusers when using --prediction_type as directed (e.g. --prediction_type='epsilon') will result in an error.

### Logs

```shell
error: argument --prediction_type: invalid int value: 'epsilon'
```

### System Info

- `diffusers` version: 0.9.0
- Platform: Linux-5.15.65+-x86_64-with-debian-bullseye-sid
- Python version: 3.7.12
- PyTorch version (GPU?): 1.12.0+cu113 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.22.1
- Using GPU in script?: P100
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
Fixed here: https://github.com/huggingface/diffusers/commit/922d56a19c9977cc96f379464a3f0afaad1dd579 - thanks @dnwalkup !
