### ISSUE TITLE
Error with StableDiffusionPipeline from diffusers

### ISSUE THREAD

**Issue by alielfilali01** [huggingface/diffusers#1542]
here is the version i'm using 
![image](https://user-images.githubusercontent.com/58257628/205493592-2b4753ee-1cea-4d07-b9f4-b390b5bb638c.png)
the code cell with the problem 
![image](https://user-images.githubusercontent.com/58257628/205493627-132870d2-18ee-441a-9746-caf415fdbbd0.png)
and here is the error message 
![image](https://user-images.githubusercontent.com/58257628/205493653-2bcfae0c-0423-4bd3-9beb-8d4d9939d636.png)

i'm pretty sure the code line is  correct so what might be the problem ?

**Comment by adhikjoshi** [comment]
Update version, it's too old.

**Comment by alielfilali01** [comment]
> Update version, it's too old.

Yes thank you, it worked when i specified the version 0.9.0 but it didn't work with just 
pip install --upgrade diffusers[torch]
