### ISSUE TITLE
AttributeError: 'DDPMScheduler' object has no attribute 'get_velocity' (using stable-diffusion-2)

### ISSUE THREAD

**Issue by Dr-Noob** [huggingface/diffusers#1544]
### Describe the bug

Running `examples/dreambooth/train_dreambooth.py` fails:

```
[noob@server dreambooth]$ ./train.sh 
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Steps:   0%|                                                                                                                                              | 0/800 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_dreambooth.py", line 716, in <module>
    main(args)
  File "train_dreambooth.py", line 641, in main
    target = noise_scheduler.get_velocity(latents, noise, timesteps)
AttributeError: 'DDPMScheduler' object has no attribute 'get_velocity'
```

### Reproduction

I just followed the [README.md](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README.md), more precisely, I tried [Training on a 16 GB GPU](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README.md#training-on-a-16gb-gpu). First I downloaded the stable-diffusion-2 repo with:

```
[noob@server diffusers]$ git clone https://huggingface.co/stabilityai/stable-diffusion-2
```

Then, I did:

```
[noob@server diffusers]$ cd examples/dreambooth/
[noob@server dreambooth]$ 
python3.7 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
pip install bitsandbytes
accelerate config

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks dog" \
  --resolution=768 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=2 --gradient_checkpointing \
  --use_8bit_adam \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=800
```

with:

```
[noob@server dreambooth]$ cat requirements.txt 
diffusers>==0.5.0
accelerate
torchvision
transformers>=4.22.1
ftfy
tensorboard
modelcards
```

Seems like the error is caused by `prediction_type` in `scheduler_config.json`:

```
[noob@server dreambooth]$ cat ../../stable-diffusion-2/scheduler/scheduler_config.json 
{
  "_class_name": "DDIMScheduler",
  "_diffusers_version": "0.8.0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "clip_sample": false,
  "num_train_timesteps": 1000,
  "prediction_type": "v_prediction",
  "set_alpha_to_one": false,
  "skip_prk_steps": true,
  "steps_offset": 1,
  "trained_betas": null
}
```

I saw `"_diffusers_version": "0.8.0"` here so tried changing requirements and use >=0.8.0 rather than >=0.5.0, but still no luck.

### System Info

- `diffusers` version: 0.9.0
- Platform: Linux-4.18.0-348.7.1.el8_5.x86_64-x86_64-with-centos-8.5.2111
- Python version: 3.7.9
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: Yes, RTX 3090
- Using distributed or parallel set-up in script?: No

**Comment by emlazzarin** [comment]
+1 also have this issue.

**Comment by patrickvonplaten** [comment]
It's indeed in master: https://github.com/huggingface/diffusers/blob/9a52e33eb65bc580e3257ce504372a67b16fb8df/src/diffusers/schedulers/scheduling_ddpm.py#L352

**Comment by emlazzarin** [comment]
Uninstalling and then force installing from master on the Github repo solved this for me.

**Comment by dnwalkup** [comment]
+1 for the issue and the solve by pip installing via this repo.

Let's get pypi up-to-date.

**Comment by Takyon236** [comment]
Just had the same error
