### ISSUE TITLE
Generating artifacts when changing the schedulers to DDIM and DDPM

### ISSUE THREAD

**Issue by abassino** [huggingface/diffusers#1545]
Hello. I have tried to change and test different schedulers after loading the model as described in the following page: https://huggingface.co/docs/diffusers/using-diffusers/schedulers
Though the DMP and PNDM give acceptable results, there are some issues with the DDIM and DDPM schedulers as shown in the results below. For example, the DDIM scheduler is set as follow: `scheduler = DDIMScheduler.from_config(scheduler.config)` and the model inputs are as follow:
prompt: "A photograph of an astronaut riding a horse on Mars, high resolution, high definition.",
width": 512,
height: 512,
seed: 0,
num_inference_steps: 40,
guidance_scale: 12

In addition, using different seeds also give similar results. Below are the results:
For DDIM:
![ddim](https://user-images.githubusercontent.com/10333061/205576773-4a4604c3-63a1-48d5-8add-2233a58e81c3.jpg)

For DDPM:
![ddpm](https://user-images.githubusercontent.com/10333061/205576930-1dc9c2e4-05ca-49cf-8461-0fb0898fc7c4.jpg)

For DMP:
![dpm](https://user-images.githubusercontent.com/10333061/205576972-8b827b5d-24d4-43d8-bf10-167af98d680e.jpg)

For PNDM
![pndm](https://user-images.githubusercontent.com/10333061/205576998-d79e20bf-9f9a-4eca-abd9-dc33b6301950.jpg)

So I am wondering what might be the potential cause of the problem with the DDIM and DDPM schedulers as shown in the results. And in case it is because  of how the scheduler are set, what would be the alternative way of doing that so that they give consistent results. 
Other information include:
Model version: runwayml/stable-diffusion-v1-5
Diffusers version: 0.9.0

Thank you in advance!

**Comment by patrickvonplaten** [comment]
Hey @abassino,

Can you please add a reproducible code snippet? Otherwise we cannot really help here

**Comment by abassino** [comment]
Thank you @averad  and @patrickvonplaten for the follow-up. After further investigation it seems that the issue was caused by an outdated version of the SD 1.5 model i was using. Redownloading the model and retrying it solved the issue, especially for the DDIM scheduler. Now the result looks as follow:
![now_0](https://user-images.githubusercontent.com/10333061/207383777-d5b7cbbf-9461-41f3-88c2-041fb08ca1d0.jpg)

For the DDPM scheduler, i also confirm what @averad said about increasing the number of steps. However, in my case, i had to push it to the steps value to 1000 before obtaining acceptable results.

**DDPM with steps=200**
![ddpm_steps_200](https://user-images.githubusercontent.com/10333061/207384129-c9f346d8-4f6d-4122-b0e7-d774cdd8a3f6.jpg)

**DDPM with steps=500**
![ddpm_steps_500](https://user-images.githubusercontent.com/10333061/207384241-833e617b-e059-4dad-8f56-3c83e6a1eece.jpg)

**DDPM with steps =1000**
![ddpm_steps_1000](https://user-images.githubusercontent.com/10333061/207384450-cdbe3a3a-52a2-4aca-a6f6-1af2e1fde51a.jpg)

So i will close this issue now, unless @patrickvonplaten you still would like me to provide you some code snippet.
