### ISSUE TITLE
`stable_diffusion_mega` pipeline doesn't work for img2img and inpainting

### ISSUE THREAD

**Issue by juno-hwang** [huggingface/diffusers#1572]
### Describe the bug

Hello, I runed the sample code of [stable-diffusion-mega](https://github.com/huggingface/diffusers/tree/main/examples/community#stable-diffusion-mega) and there's a mismatch between parameter names of new and legacy pipelines.
It seems that Mega pipeline uses `image` for `img2img` and `inpaint`, but the legacy pipeline uses `init_image`.

### Reproduction
```python
from diffusers import DiffusionPipeline
import PIL
import requests
from io import BytesIO
import torch

def download_image(url):
    response = requests.get(url)
    return PIL.Image.open(BytesIO(response.content)).convert("RGB")

pipe = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", custom_pipeline="stable_diffusion_mega", torch_dtype=torch.float16, revision="fp16")
pipe.to("cuda")
pipe.enable_attention_slicing()

init_image = download_image("https://raw.githubusercontent.com/CompVis/stable-diffusion/main/assets/stable-samples/img2img/sketch-mountains-input.jpg")
prompt = "A fantasy landscape, trending on artstation"
images = pipe.img2img(prompt=prompt, image=init_image, strength=0.75, guidance_scale=7.5).images
```
### Logs

```shell
Traceback (most recent call last):
  File "D:\StableDiffusion\test.py", line 18, in <module>
    images = pipe.img2img(prompt=prompt, image=init_image, strength=0.75, guidance_scale=7.5).images
  File "C:\Users\*\anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\wnsdh/.cache\huggingface\modules\diffusers_modules\git\stable_diffusion_mega.py", line 177, in img2img
    return StableDiffusionImg2ImgPipeline(**self.components)(
  File "C:\Users\wnsdh*anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: __call__() missing 1 required positional argument: 'init_image'
```

### System Info

- `diffusers` version: 0.9.0
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: RTX 3090
- Using distributed or parallel set-up in script?: No

**Comment by christinalc** [comment]
hi, i changed 'git+https://github.com/huggingface/diffusers' to this `git+https://github.com/huggingface/diffusers.git` in my requirements file, but i am still getting this error `TypeError: __call__() missing 1 required positional argument: 'init_image'`

i am using gradio and HF spaces, is there something i am doing wrong?

**Comment by christinalc** [comment]
thanks for the reply! sorry i'm new to this - i'm hosting it on hugging face spaces so i haven't done any installation. this is my repo: https://huggingface.co/spaces/christinac/text-decorator/tree/main and the `git+https://github.com/huggingface/diffusers.git` is in the requirements.txt file

**Comment by christinalc** [comment]
@pedrogengo thank you so much!!
