### ISSUE TITLE
Textual inversion prompt tokenization is buggy

### ISSUE THREAD

**Issue by askerlee** [huggingface/diffusers#1580]
### Describe the bug

https://github.com/huggingface/diffusers/blob/02d83c9ff1b93f2c6f9c94f9369b3e4bc1ba8ce7/examples/textual_inversion/textual_inversion.py#L423

In the line above, the placeholder prompt (a string) is passed to `tokenizer.convert_tokens_to_ids()`. However, args.placeholder_token hasn't been tokenized yet. The correct use is:
    `placeholder_token_id = tokenizer.convert_tokens_to_ids(tokenizer.tokenize(args.placeholder_token))`
or simply
    `placeholder_token_id = tokenizer(args.placeholder_token)["input_ids"]`
(They are not equivalent though; tokenizer() seems to contain two more token IDs - maybe `start` and `end` tokens?)

I have the feeling that there could probably be other prompt preprocessing bugs lurking in the code. 

### Reproduction

    (Pdb) tokenizer.convert_tokens_to_ids("skrr")
    49407
    (Pdb) tokenizer.convert_tokens_to_ids("abcd")
    49407
    (Pdb) tokenizer.convert_tokens_to_ids(tokenizer.tokenize("skrr"))
    [909, 9126]
    (Pdb) tokenizer("skrr")['input_ids']
    [49406, 909, 9126, 49407]

On `skrr` and `abcd` the same token ID `49407` (`start` of a string?) is returned , which is apparently wrong.

### System Info

Diffusers '0.10.0.dev0'
transformers '4.25.1'
Ubuntu Linux 20.04.5.

**Comment by JunnYu** [comment]
49407 is [UNK] token.
![image](https://user-images.githubusercontent.com/50394665/206361619-19d7401a-3ed0-4508-b9d9-a8195069c662.png)
if we add_tokens and then that's correct.
```python
num_added_tokens = tokenizer.add_tokens('skrr')
tokenizer.convert_tokens_to_ids("skrr")
```
![image](https://user-images.githubusercontent.com/50394665/206361785-fc7171b8-d4b8-48c1-9f00-a7b60088463b.png)

**Comment by askerlee** [comment]
I see. Thanks @JunnYu for the clarification. Now the issue is, during inference, will the token be mapped to UNKNOWN as well? I guess not, as the tokenization is handled by the standard pipeline of diffusers? 

Actually when I used textual inversion in diffuses, I got very bad images compared to the original repo. Not sure if it's due to this (potential) inconsistency.

**Comment by patrickvonplaten** [comment]
We now have a fix for the weight decay problem, very sorry that it took forever.
