### ISSUE TITLE
Runtime error in image2image addnoise

### ISSUE THREAD

**Issue by TheOneTrueGuy** [huggingface/diffusers#1600]
### Describe the bug

Starting this morning a scheduler in the image2image pipeline  began to throw an error in addnoise.

I should add that this code was working fine yesterday and is entirely unaltered and that other, also previously working unaltered image2image projects all repeat the same error.

It is on line 254 of scheduling_pndm.py and says:
indices should be either on cpu or on the same device as the indexed tensor (cpu)

![error_12_7_2022](https://user-images.githubusercontent.com/3240071/206336661-863b38d8-1c37-49c7-acde-706bbc8fed7b.PNG)

Thanks for your attention :)

### Reproduction

the code for this error can be found in my repo, https://github.com/TheOneTrueGuy/DigitalDayDream
under ClipLoop.ipynb 

### System Info

running under Linux in a Google colab server, probably ubuntu

**Comment by averad** [comment]
@TheOneTrueGuy is the issue specific to ```diffusers==0.2.4```?

**Comment by TheOneTrueGuy** [comment]
I can't tell for sure because attempting to use 0.3.0 sets off an entirely different string of errors. 
![0 3 0error2_12_7_2022](https://user-images.githubusercontent.com/3240071/206358104-45f61dab-aa68-4953-a34e-3b4e3dfea1e8.PNG)

**Comment by TheOneTrueGuy** [comment]
Wil Bown did it and is easy fix for anyone else who runs into this. In image_to_image.py:

line 84: init_latents = self.vae.encode(init_image.to(self.device)).latent_dist.sample()

line 155: image = self.vae.decode(latents).sample
works for moving from 0.2.4 to 0.3.0 but DOES NOT solve the original problem in 0.2.4 but I just need A working version not particularly THAT working version.

Thanks everybody for the help & thanks Wil Bown especially :)
