### ISSUE TITLE
lpw_stable_diffusion.py broken when using diffusers==0.9.0

### ISSUE THREAD

**Issue by kovtcharov** [huggingface/diffusers#1604]
### Describe the bug

When initializing a diffusers pipeline, the following error occurs. Possibly related to the following [updates ](https://github.com/huggingface/diffusers/pull/1570/files)recently? 
```
  File ".cache/huggingface/modules/diffusers_modules/git/lpw_stable_diffusion.py", line 755, in __call__
    num_warmup_steps = len(timesteps) - num_inference_steps * self.scheduler.order
AttributeError: 'EulerAncestralDiscreteScheduler' object has no attribute 'order'
```

### Reproduction

Simply initializing pipeline with any scheduler (even default scheduler) seems to generate the above error.

### System Info

- `diffusers` version: 0.9.0
- Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
- Python version: 3.9.15
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: parallel

**Comment by kovtcharov** [comment]
I tried to reproduce the error in a [colab](https://colab.research.google.com/drive/11wv2bl_IeqL7tkXIG4z29Em0oIK-51fa?usp=sharing), but ran into a different issue/error related to the SafetyChecker:
```
[~/.cache/huggingface/modules/diffusers_modules/git/lpw_stable_diffusion.py](https://localhost:8080/#) in <module>
      9 from diffusers import SchedulerMixin, StableDiffusionPipeline
     10 from diffusers.models import AutoencoderKL, UNet2DConditionModel
---> 11 from diffusers.pipelines.stable_diffusion import StableDiffusionPipelineOutput, StableDiffusionSafetyChecker
     12 from diffusers.utils import PIL_INTERPOLATION, deprecate, logging
     13 from transformers import CLIPFeatureExtractor, CLIPTextModel, CLIPTokenizer

ImportError: cannot import name 'StableDiffusionSafetyChecker' from 'diffusers.pipelines.stable_diffusion' (/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/stable_diffusion/__init__.py)
```

**Comment by kovtcharov** [comment]
@patrickvonplaten, would you like me to create a new bug report related to the bug above for diffusers v0.10.0?

**Comment by kovtcharov** [comment]
Updated [script ](https://colab.research.google.com/drive/11wv2bl_IeqL7tkXIG4z29Em0oIK-51fa?usp=sharing)here to reproduce the original bug using diffusers v0.9.0. You should still be able to reproduce the second bug listed above by uncommenting the second line below:
```
!pip install --upgrade diffusers[torch]==0.9.0 transformers scipy
# !pip install --upgrade diffusers[torch]==0.10.0 transformers scipy
```

**Comment by WASasquatch** [comment]
further shenanigans with v0.8.0: https://github.com/huggingface/diffusers/issues/1616****

**Comment by patrickvonplaten** [comment]
This should be resolved now no?
