### ISSUE TITLE
train_dreambooth.py: error: the following arguments are required:

### ISSUE THREAD

**Issue by mcventur** [huggingface/diffusers#1617]
I'm trying to fit train SD 1.5 with DreamBooth with prior preservation following the  steps from [https://github.com/huggingface/diffusers/tree/main/examples/dreambooth]

But i'm receiving an error:
`train_dreambooth.py: error: the following arguments are required: --pretrained_model_name_or_path, --instance_data_dir, --instance_prompt
    Traceback (most recent call last):
    File "/home/myuser/miniconda3/envs/dbooth/bin/accelerate", line 10, in <module>
    sys.exit(main())
    File "/home/myuser/miniconda3/envs/dbooth/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
    File "/home/myuser/miniconda3/envs/dbooth/lib/python3.7/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
    File "/home/myuser/miniconda3/envs/dbooth/lib/python3.7/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
    subprocess.CalledProcessError: Command '['/home/myuser/miniconda3/envs/dbooth/bin/python3.7', 'train_dreambooth.py']' returned non-zero exit status 2.`

This is my script.sh for make the training:

```
#!/bin/bash
    export MODEL_NAME="v1-5-pruned.ckpt"
    export INSTANCE_DIR="retocadas"
    export CLASS_DIR="person_ddim"
    export OUTPUT_DIR="salida"
    
    accelerate launch train_dreambooth.py \
    --pretrained_model_name_or_path=$MODEL_NAME \
    --instance_data_dir=$INSTANCE_DIR \
    --class_data_dir=$CLASS_DIR \
    --output_dir=$OUTPUT_DIR \
    --with_prior_preservation --prior_loss_weight=1.0 \
    --instance_prompt="AnUniqueExample" \
    --class_prompt="person" \
    --resolution=512 \
    --train_batch_size=1 \
    --gradient_accumulation_steps=2 --gradient_checkpointing \
    --use_8bit_adam \
    --learning_rate=5e-6 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=0 \
    --num_class_images=200 \
    --max_train_steps=800
```
    

All files and paths indicated in the header are on the same path as the .sh file.
Someone can help me to find the problem?

**Comment by averad** [comment]
What happens if you put ./ infront of your files/directories? 

```
#!/bin/bash
    export MODEL_NAME="./v1-5-pruned.ckpt"
    export INSTANCE_DIR="./retocadas"
    export CLASS_DIR="person_ddim"
    export OUTPUT_DIR="./salida"
    
    accelerate launch train_dreambooth.py \
    --pretrained_model_name_or_path=$MODEL_NAME \
    --instance_data_dir=$INSTANCE_DIR \
    --class_data_dir=$CLASS_DIR \
    --output_dir=$OUTPUT_DIR \
    --with_prior_preservation --prior_loss_weight=1.0 \
    --instance_prompt="AnUniqueExample" \
    --class_prompt="person" \
    --resolution=512 \
    --train_batch_size=1 \
    --gradient_accumulation_steps=2 --gradient_checkpointing \
    --use_8bit_adam \
    --learning_rate=5e-6 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=0 \
    --num_class_images=200 \
    --max_train_steps=800
```

**Comment by mcventur** [comment]
There is no changes. I obtain the same result. It's like the train_dreambooth wasn't receiving my arguments...

**Comment by mcventur** [comment]
Debugging, printing args in accelerate launch.py, i've seen 
training_script_args=[]
I'm losing my arguments in anywhere...

**Comment by averad** [comment]
Latest version of diffusers? `diffusers-cli env`

**Comment by mcventur** [comment]
- `diffusers` version: 0.10.0.dev0
- Platform: Linux-4.14.0-115.el7a.0.1.ppc64le-ppc64le-with-centos-7.6.1810-AltArch
- Python version: 3.7.12
- PyTorch version (GPU?): 1.12.1 (False)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.24.0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

and huggingface-cli env:

- huggingface_hub version: 0.11.1
- Platform: Linux-4.14.0-115.el7a.0.1.ppc64le-ppc64le-with-centos-7.6.1810-AltArch
- Python version: 3.7.12
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/myuser/.huggingface/token
- Has saved token ?: True
- Who am I ?: <myuser>
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 1.12.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A

**Comment by mcventur** [comment]
As you can see, i'm trying to make the fit training in a ppc64 machine. I haved to install many dependencies manually with conda, and some with pip.

**Comment by patrickvonplaten** [comment]
Hey @mcventur,

Note that:

```
#!/bin/bash
    export MODEL_NAME="v1-5-pruned.ckpt"
    export INSTANCE_DIR="retocadas"
    export CLASS_DIR="person_ddim"
    export OUTPUT_DIR="salida"
    
    accelerate launch train_dreambooth.py \
    --pretrained_model_name_or_path=$MODEL_NAME \
    --instance_data_dir=$INSTANCE_DIR \
    --class_data_dir=$CLASS_DIR \
    --output_dir=$OUTPUT_DIR \
    --with_prior_preservation --prior_loss_weight=1.0 \
    --instance_prompt="AnUniqueExample" \
    --class_prompt="person" \
    --resolution=512 \
    --train_batch_size=1 \
    --gradient_accumulation_steps=2 --gradient_checkpointing \
    --use_8bit_adam \
    --learning_rate=5e-6 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=0 \
    --num_class_images=200 \
    --max_train_steps=800
```

is probably not the correct syntax for `diffusers` since we don't allow passing checkpoints of the format .ckpt . I'm not able to run your code snippet above.

**Comment by mcventur** [comment]
Thanks patric. Really i've tested first with 
`export MODEL_NAME="CompVis/stable-diffusion-v1-4"`
but with same result. 

I think i've found the solution: i've edited the script with nano. It's possible it added any /r not desired on the code, that could break the code. Editing it with VS Code solve the problem. 

Now i've fighting with other problems, but this is another history.

Thanks to all!
