### ISSUE TITLE
[Tests] Inconsistent outputs for common fast tests on MPS

### ISSUE THREAD

**Issue by anton-l** [huggingface/diffusers#1630]
There are three (so far) pipelines that don't produce the same outputs between two consecutive runs on MPS, despite having a warmup step in the common fast tests:

https://github.com/huggingface/diffusers/blob/cd91fc06fe9513864fca6a57953ca85a7ae7836e/tests/test_pipelines_common.py#L67-L73

Needs further investigation to avoid skipping these tests

**Comment by patrickvonplaten** [comment]
Interesting! Thanks for flagging this here! I think especially `StableDiffusionImg2ImgPipeline` should give identical results. I wonder whether this is because of the stochastic sampling operation when encoding the image for img2img

**Comment by patrickvonplaten** [comment]
I think currently we cannot do much as this seems to be a problem in native PyTorch/MPS no @pcuenca ?
