### ISSUE TITLE
[Tests] Non-deterministic depth estimator in `StableDiffusiondepth2imgPipelineFastTests`

### ISSUE THREAD

**Issue by anton-l** [huggingface/diffusers#1631]
`DPTForDepthEstimation` might be causing less reproducible results between two consecutive runs than other transformers models, which motivated overriding the tolerances of common fast tests, e.g. `3e-5` here:

https://github.com/huggingface/diffusers/blob/cd91fc06fe9513864fca6a57953ca85a7ae7836e/tests/pipelines/stable_diffusion_2/test_stable_diffusion_depth.py#L155-L174

Needs further investigation, the common fast tests should ideally be applicable to all pipelines.

**Comment by patrickvonplaten** [comment]
I noticed this too, I noticed however that the results stay within a `1e-4` range which is good enough IMO. Should be fixed by: https://github.com/huggingface/diffusers/pull/1669
