### ISSUE TITLE
Support optionally using karras sigmas in the k_diffusion wrapper pipeline

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#1633]
**Is your feature request related to a problem? Please describe.**
K-Diffusion enables users to generate sigmas with `k_diffusion.sampling.get_sigmas_karras`. `diffusers` currently do not support using those to generate the sigmas with its [k_diffusion wrapper](https://github.com/huggingface/diffusers/blob/main/examples/community/sd_text2img_k_diffusion.py) 

**Describe the solution you'd like**
Enable users to optionally generate karras sigmas similarly to how AUTO1111 does it https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/44c46f0ed395967cd3830dd481a2db759fda5b3b/modules/sd_samplers.py#L453

**Comment by patrickvonplaten** [comment]
I  will try to allocate some time in the next weeks to look into it (can't promise to get it done soon though). Just wondering: do we have some results/benchmarks to know whether karras sigmas work better ?

**Comment by apolinario** [comment]
I don't think they necessarily work better.

They just works differently and the community enjoys having the possibility of having this variations for artistic purposes when using tools that support it such as AUTO1111 and any other based on k_diffusion so I think it would be great for diffusers to also enable such variations. But I can say it works _better_ (some people believe so subjectively)

**Comment by patrickvonplaten** [comment]
In case one is interested in taking a look? @williamberman @yiyixuxu @pcuenca @patil-suraj

**Comment by patrickvonplaten** [comment]
Here a solution that should work well: https://github.com/huggingface/diffusers/issues/1887#issuecomment-1399263545 . Hope to soon find time to implement it :-)

**Comment by ym-ctw** [comment]
> 



> 这里有一个应该运行良好的解决方案：[#1887（评论）](https://github.com/huggingface/diffusers/issues/1887#issuecomment-1399263545)。希望尽快找到时间来实施它:-)

Did you add the karras sigmas to diffusers's scheduler? I want to use DPM++ 2M karras but I only find DPMSolver multi-step.

**Comment by patrickvonplaten** [comment]
Not yet @ym-ctw - we'd be more than happy to review a PR though :-)

**Comment by ym-ctw** [comment]
> Not yet @ym-ctw - we'd be more than happy to review a PR though :-)

Thanks, I really hope you could add karras especially in DPM++ series soon. Because now much more new model are using 'DPM++ 2M karras' to get much better results than 'eular a' or others schedulers, most of these models are from 'civitai.com.' 
Hope you could keep an emphasis on it, Thanks for your effort.

**Comment by sayakpaul** [comment]
I feel we have had a nice overhaul in schedulers to harmonize features from the k-diffusion repo. So, closing this.
