### ISSUE TITLE
[MPS] Some of the `DPTForDepthEstimation` ops are not supported on MPS

### ISSUE THREAD

**Issue by anton-l** [huggingface/diffusers#1634]
To reproduce, remove the mps skips in `StableDiffusiondepth2imgPipelineFastTests`:

https://github.com/huggingface/diffusers/blob/cd91fc06fe9513864fca6a57953ca85a7ae7836e/tests/pipelines/stable_diffusion_2/test_stable_diffusion_depth.py#L154

This is probably solvable on the `transformers` side, but opening an issue here too to keep track of the testing :)

**Comment by patrickvonplaten** [comment]
This would be nice to fix indeed!

**Comment by pcuenca** [comment]
Thanks @anton-l, I'll take a look :)

**Comment by patrickvonplaten** [comment]
Gently reminder @pcuenca :-)
