### ISSUE TITLE
Dynamic thresholding

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#1636]
Could be important for increased quality or robustness to "fried" areas.

**Comment by williamberman** [comment]
Yep, think this is good now

**Comment by alexblattner** [comment]
All this is great, but could we have an example? I don't see mimic scale anywhere....

I'm using this as reference: https://sd.mcmonkey.org/dynthresh/

**Comment by williamberman** [comment]
@alexblattner I'm not familiar with mimic scale, could you provide a reference?

**Comment by alexblattner** [comment]
@williamberman the link I provided

**Comment by williamberman** [comment]
That link just lists it as a toggle, doesn't tell me anything about it :)
