### ISSUE TITLE
Should we open Github Discussions?

### ISSUE THREAD

**Issue by camenduru** [huggingface/diffusers#1646]
Is it possible to enable github discussions then people can ask questions and also we can move some issues to discussions if it is a question.

**Comment by camenduru** [comment]
like this one https://github.com/huggingface/diffusers/issues/1647 should go to discussions

**Comment by patrickvonplaten** [comment]
For now we will not open GitHub discussions as we would like to centralize everything on the issues - we sadly don't have the time at the moment to monitor multiple different forums. I'm very open to the idea in general though, maybe in a couple of months we could start with discussions.
