### ISSUE TITLE
[Question] How can I use color correction .pt in diffusers

### ISSUE THREAD

**Issue by camenduru** [huggingface/diffusers#1647]
https://huggingface.co/Linaqruf/anything-v3.0/blob/main/Anything-V3.0.vae.pt 
this is for color correction how can I use this with diffusers

**Comment by apolinario** [comment]
Hi @camenduru , that 'color correction .pt' is the anythingV3.0 VAE. VAE is the variational auto-encoder that encodes/decodes images for models like Stable Diffusion 

While it would be possible to convert that pt to the diffusers format, there's no specific VAE-only conversion script, so you would need to adapt the existing script a little bit. 

However, you can already use the anything-v3.0 VAE in any other model with diffusers, in the following way:
```py
from diffusers.models import AutoencoderKL
from diffusers import StableDiffusionPipeline
model = "CompVis/stable-diffusion-v1-4" #Replace this to any model you would like to use this VAE with
vae = AutoencoderKL.from_pretrained("Linaqruf/anything-v3.0", subfolder="vae")
pipe = StableDiffusionPipeline.from_pretrained(model, vae=vae)
```

**Comment by camenduru** [comment]
I did it 🎉 
![7558571514354788](https://user-images.githubusercontent.com/54370274/209511820-ae99e8a3-bdeb-4d86-86e3-533d3f62ae13.gif)

**Comment by patrickvonplaten** [comment]
Wuhuu super cool! Would you like to maybe add a conversion script to `diffusers` for this? :-)

**Comment by camenduru** [comment]
if someone here for how to please check `swap ckpt vae` inside https://huggingface.co/spaces/camenduru/converter

**Comment by camenduru** [comment]
If someone is here for information on how to please check the `swap ckpt vae` inside https://huggingface.co/spaces/camenduru/converter
