### ISSUE TITLE
May I ask what the T_max parameter means and what is its default value?

### ISSUE THREAD

**Issue by nikoharo** [huggingface/diffusers#1650]
![t_max](https://user-images.githubusercontent.com/96216203/206861858-18cb00b5-6e5e-4f89-b05e-5f3867b7cc6e.png)

**Comment by camenduru** [comment]
maybe this code different from https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py

**Comment by patrickvonplaten** [comment]
Hey @camenduru,

It should be defined here :

https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.CosineAnnealingLR.html#cosineannealinglr
