### ISSUE TITLE
[Trivial Fix] Flag use_ema in train_unconditional.py should not have default value

### ISSUE THREAD

**Issue by Nelorth** [huggingface/diffusers#1654]
## Problem
The definition of the flag `use_ema` wrongly includes a default value of `True`:
https://github.com/huggingface/diffusers/blob/fc94c60c8373862c509e388f3f4065d98cedf589/examples/unconditional_image_generation/train_unconditional.py#L156-L161
Hence, when the flag is not passed via CLI, **it is still evaluated as true**.

## Fix
To fix this bug, simply remove `default=True` from the flag definition.

**Comment by patrickvonplaten** [comment]
Agree actually, we should probably rename this to `--use_no_ema`? 

cc @anton-l
