### ISSUE TITLE
StableDiffusionImageVariationPipeline not initializing 

### ISSUE THREAD

**Issue by artyemk** [huggingface/diffusers#1655]
### Describe the bug

When I try to initialize pipe I get this error:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/lambdalabs/sd-image-variations-diffusers/resolve/v2.0/model_index.json`

There is a problem with lambdalabs repo, please check. This issue can also be found here - https://github.com/LambdaLabsML/lambda-diffusers/issues/16

### Reproduction

Code to reproduce bug (from https://github.com/LambdaLabsML/lambda-diffusers):

```
from diffusers import StableDiffusionImageVariationPipeline
from PIL import Image

device = "cuda:0"
sd_pipe = StableDiffusionImageVariationPipeline.from_pretrained(
  "lambdalabs/sd-image-variations-diffusers",
  revision="v2.0",
  )
```

### Logs

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipeline_utils.py", line 454, in from_pretrained
    config_dict = cls.load_config(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 348, in load_config
    raise EnvironmentError(
OSError: v2.0 is not a valid git identifier (branch name, tag name or commit id) that exists for this model name. Check the model page at 'https://huggingface.co/lambdalabs/sd-image-variations-diffusers' for available revisions.
```

### System Info

- `diffusers` version: 0.10.0.dev0
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.13.0+cu116 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by WASasquatch** [comment]
> revision="v2.0"

is not a valid revision. This is for the model floating point type, example `fp16`.

**Comment by averad** [comment]
WASasquatch is correct. Here is some more information incase you run into issues.

To correct the issue you need to: 
1. Go to the model's hugging face page. 
- https://huggingface.co/lambdalabs/sd-image-variations-diffusers/tree/main
2. Click on "Files and Versions" 
![1](https://user-images.githubusercontent.com/640619/206927815-0ff1c7f2-ba4e-4006-8bf0-613be65f993d.png)

3. Click on "main" to see the drop down of available "revisions"


v2.0 is not a listed "revision" for that model, I believe you would want to pull/download the main "revision"

Corrected Script Example:
```
from diffusers import StableDiffusionImageVariationPipeline
from PIL import Image

device = "cuda:0"
sd_pipe = StableDiffusionImageVariationPipeline.from_pretrained(
  "lambdalabs/sd-image-variations-diffusers",
  revision="main",
  )
```
