### ISSUE TITLE
Images are the wrong size (256px for stable diffusion 1.5) after using ckpt to diffusers script

### ISSUE THREAD

**Issue by JohnnyRacer** [huggingface/diffusers#1672]
### Describe the bug

Hello, I was testing [the conversion script for ckpts to diffusers](https://raw.githubusercontent.com/huggingface/diffusers/039958eae55ff0700cfb42a7e72739575ab341f1/scripts/convert_original_stable_diffusion_to_diffusers.py), when I realized all the images that generated by the converted models are only 256x256 and of very low quality. I used the following commands to convert the ckpt :
```
python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ./models/sd-v1-5_pruned_ema.ckpt  --original_config_file ./stable-diffusion/configs/stable-diffusion/v1-inference.yaml  --dump_path sd-v1-5-diffusers
```
And loaded the checkpoint using the folder's path with StableDiffusionPipeline like so:
```python
from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler

pipe = StableDiffusionPipeline.from_pretrained("./sd-v1-5-diffusers", torch_dtype=torch.float16, safety_checker=None).to("cuda")

prompt ="a lion roaring"
torch.manual_seed(0)
image = pipe(prompt, num_inference_steps=50, guidance_scale=7).images[0]
image
```
The end result is not so nice ... Where both the resolution is capped at 256x256 and the content is not what was prompted.
![image](https://user-images.githubusercontent.com/77214388/207144788-cf45f7e8-4f8e-49c6-8ebd-8157506fa0c2.png)

The ckpt model was download from HF's `runwayml/stable-diffusion-v1-5` repo, the hash was verified and works well with Automatic1111's webui repo. Any help would be much appreciated.

### Reproduction

```
wget https://raw.githubusercontent.com/huggingface/diffusers/039958eae55ff0700cfb42a7e72739575ab341f1/scripts/convert_original_stable_diffusion_to_diffusers.py
python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ./models/sd-v1-5_pruned_ema.ckpt  --original_config_file ./stable-diffusion/configs/stable-diffusion/v1-inference.yaml  --dump_path sd-v1-5-diffusers
```

```python
from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler

pipe = StableDiffusionPipeline.from_pretrained("./sd-v1-5-diffusers", torch_dtype=torch.float16, safety_checker=None).to("cuda")

prompt ="a lion roaring"
torch.manual_seed(0)
image = pipe(prompt, num_inference_steps=50, guidance_scale=7).images[0]
image
```

### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.10.2
- Platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.17
- Python version: 3.8.15
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?:  No

**Comment by patrickvonplaten** [comment]
Thanks for the repro @JohnnyRacer ! Checking now :-)

**Comment by JohnnyRacer** [comment]
@patrickvonplaten  I tried to use the latest conversion script and that seemed to solve the problem. Do you want to still look into the problem or should I close the issue?

**Comment by patrickvonplaten** [comment]
Ah I'm sorry that I didn't manage to follow up here. All good then, if it's solved for you :-)
