### ISSUE TITLE
[Custom Models] Can't load dreambooth models with new scheduling config method and DPMSolver

### ISSUE THREAD

**Issue by WASasquatch** [huggingface/diffusers#1674]
### Describe the bug

I can't load DPMSolver, for example, with the new method to define schedulers from config, cause apparently, most these dreambooth models don't have a config for the schedulers. What do we do in this instance then? 

```OSError: nitrosocke/redshift-diffusion does not appear to have a file named scheduler_config.json.```

### Reproduction

Load DPMSolver with Dreambooth model like `nitrosocke/redshift-diffusion` and pass the `pipe.scheduler.config` to it.

### Logs

```shell
~\AppData\Roaming\Python\Python39\site-packages\diffusers\configuration_utils.py in from_config(cls, config, return_unused_kwargs, **kwargs)
    194                 )
    195             deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
--> 196             config, kwargs = cls.load_config(pretrained_model_name_or_path=config, return_unused_kwargs=True, **kwargs)
    197 
    198         init_dict, unused_kwargs, hidden_dict = cls.extract_init_dict(config, **kwargs)

~\AppData\Roaming\Python\Python39\site-packages\diffusers\configuration_utils.py in load_config(cls, pretrained_model_name_or_path, return_unused_kwargs, **kwargs)
    352                 )
    353             except EntryNotFoundError:
--> 354                 raise EnvironmentError(
    355                     f"{pretrained_model_name_or_path} does not appear to have a file named {cls.config_name}."
    356                 )

OSError: nitrosocke/redshift-diffusion does not appear to have a file named scheduler_config.json.
```

### System Info

`diffusers-cli env` doesn't seem to work when installed with Conda (this is a fresh install of diffusers as of this morning with conda install method)

```
diffusers-cli is not recognized as an internal or external command,
operable program or batch file.
```

Guess that's yet another bug.

**Comment by averad** [comment]
@WASasquatch what is your suggested code change to correct the reported issue?

**Comment by WASasquatch** [comment]
> @WASasquatch what would you suggest 🤗 change to correct the reported issue? Were you able to hack together a workaround?

DPMSolver worked giving it a config dictionary like the old methods we used to work, but that would mean maintaining both old schedulers setup, and new, and determining where to apply.

**Comment by averad** [comment]
@WASasquatch thanks for the info, appreciate it

**Comment by patrickvonplaten** [comment]
@WASasquatch could you please provide a reproducible code snippet?

**Comment by anton-l** [comment]
@WASasquatch the `Scheduler.from_config(pipe.scheduler.config)` method was introduced in v0.8.0 and has been used in release notes for every new scheduler since: https://github.com/huggingface/diffusers/releases/tag/v0.8.0
This is also reflected in the quicktour docs: https://huggingface.co/docs/diffusers/v0.10.2/en/quicktour
And in the scheduler docs: https://huggingface.co/docs/diffusers/v0.10.2/en/using-diffusers/schedulers#changing-the-scheduler

The API works as expected in the latest version:
```python
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler

pipe = StableDiffusionPipeline.from_pretrained("nitrosocke/redshift-diffusion")
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
```

And the original API is also still supported for backward compatibility:
```python
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler

pipe = StableDiffusionPipeline.from_pretrained("nitrosocke/redshift-diffusion")
pipe.scheduler = DPMSolverMultistepScheduler.from_config("nitrosocke/redshift-diffusion", subfolder="scheduler")
```

You might be missing the `subfolder="scheduler"` argument if you're using the old API, judging by the error message.

**Comment by anton-l** [comment]
> diffusers-cli env doesn't seem to work when installed with Conda

pinging our conda contributor @sugatoray for a way to enable CLI commands in conda packages :)

**Comment by WASasquatch** [comment]
> @WASasquatch to give a bit of context on the change: The `Scheduler.from_config(pipe.scheduler.config)` method was introduced in v0.8.0 and has been used in release notes for every new scheduler since: https://github.com/huggingface/diffusers/releases/tag/v0.8.0 This is also reflected in the quicktour docs: https://huggingface.co/docs/diffusers/v0.10.2/en/quicktour And in the scheduler docs: https://huggingface.co/docs/diffusers/v0.10.2/en/using-diffusers/schedulers#changing-the-scheduler
> 
> The API works as expected in the latest version:
> 
> ```python
> from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler
> 
> pipe = StableDiffusionPipeline.from_pretrained("nitrosocke/redshift-diffusion")
> pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
> ```
> 
> And the original API is also still supported for backward compatibility:
> 
> ```python
> from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler
> 
> pipe = StableDiffusionPipeline.from_pretrained("nitrosocke/redshift-diffusion")
> pipe.scheduler = DPMSolverMultistepScheduler.from_config("nitrosocke/redshift-diffusion", subfolder="scheduler")
> ```
> 
> You might be missing the `subfolder="scheduler"` argument if you're using the old API, judging by the error message.

That would make sense, though wasn't required before it seems, as since 0.8 I had been using them all without subfolder, and even was using DPMSolver with DPMSolver++ algorithm. The last couple weeks due to all the errors I have been using bleeding edge to get on top of errors to migrate to other services in a more stable fashion instead of killing it for users when I am not around or what not. 

But I decided to jump ship for AUTOMATIC's and pretty satisfied with performance and features, if not for the WebUI mess (seems to be a quirky system from time to time).
