### ISSUE TITLE
convert_original_stable_diffusion_to_diffusers.py error state dict

### ISSUE THREAD

**Issue by elen07zz** [huggingface/diffusers#1675]
convert_original_stable_diffusion_to_diffusers.py

Im trying to convert some ckpt to diffusers but im getting this error:

Traceback (most recent call last):
  File "H:\stable\convert_original_stable_diffusion_to_diffusers.py", line 864, in <module>
    checkpoint = checkpoint["state_dict"]
KeyError: 'state_dict'

**Comment by SpandexWizard** [comment]
what would that mean? 'reproducible code snippet'....  i have the same issue. merged two models using the automatic 1111 webui and now i want to convert the merged model to diffusers. BOTH models have previously been converted to diffuers seperately, but when i try to convert the merged model i get both the 'global_step' and the 'state_dict' errors (the global step error can be bypassed by using the latest conversion script).  i'm not exactly sure what you'd want to know. the script is called using 'python scriptname --checkpoint_path="location" --dump_path="location"', and it's the script right off the repository.

**Comment by geocine** [comment]
I also experience this. I will report back once I find solution. I want to share the model to reproduce the issue but its NSFW so I will leave it to someone to share their models.

**Comment by geocine** [comment]
@patrickvonplaten 

I saw someone found a solution here. This worked on my end.
https://gist.github.com/sftblw/1586a5b0d962e606ac5e89754fdd24cd
