### ISSUE TITLE
It is not possible to disable telemetry

### ISSUE THREAD

**Issue by w4ffl35** [huggingface/diffusers#1685]
### Describe the bug

Although the DISABLE_TELEMETRY and HF_HUB_OFFLINE env variables exist, setting them doesn't actually seem to disable telemetry.

https://github.com/huggingface/diffusers/blob/main/src/diffusers/hub_utils.py#L87

Pass is used, and /api/telemetry is prepended to the huggingface endpoint.

### Reproduction

- set DISABLE_TELEMETRY to True
- run stablediffusion from pretrained
- see `/api/telemetry/diffusers_from_pretrained` in the requests made to huggingface

### System Info

main branch

**Comment by anton-l** [comment]
Thank you for the fix in https://github.com/huggingface/diffusers/pull/1686 @w4ffl35! This was a serious oversight on our side, very sorry for mixing up the return there! :pray:

**Comment by w4ffl35** [comment]
Glad to help.

Will you accept a PR that changes TELEMETRY to an opt-in value or must it remain opt-out?

**Comment by patrickvonplaten** [comment]
@w4ffl35,

We've fully removed TELEMETRY now. So if you load checkpoints locally, nothing is sent.
