### ISSUE TITLE
`seed` missing from `StableDiffusionPipeline()` v2*?

### ISSUE THREAD

**Issue by BFauber** [huggingface/diffusers#1689]
It appears that the `seed` argument is missing from v2* of `StableDiffusionPipeline()`.

https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L397

If this is correct, I recommend editing the `generator: Optional[torch.Generator] = None` to include the option of a user-defined seed, such as `generator: Optional[torch.Generator().manual_seed(seed)] = None`, where the `seed` value is a separate argument for the `StableDiffusionPipeline()` `__call__()` and `seed: int = None` is the default. This change will enable the reproducible generation of outputs from the same input parameters.

https://pytorch.org/docs/stable/generated/torch.Generator.html

Thanks!

**Comment by BFauber** [comment]
Thanks @mlmcgoogan for the quick feedback. 

I appreciate the ability to feed the `pipe()` user-defined latents. Conversely, setting the `seed` value in the SD v1* prompt was quite straightforward. 

Why is the current `getLatents()` approach in place vs `seed` with SD v2*? 

Thanks!

**Comment by averad** [comment]
Try:

```
generator = torch.Generator(device="cuda").manual_seed(8)
image = pipeline(prompt, generator=generator).images[0]
```

https://huggingface.co/docs/diffusers/main/en/using-diffusers/schedulers#access-the-scheduler

**Comment by BFauber** [comment]
Thanks @mlmcgoogan and @averad for these suggestions!

**Comment by patrickvonplaten** [comment]
Also linking this doc page on generating the same output batched vs. non-batched with a reproducible seed: https://huggingface.co/docs/diffusers/using-diffusers/reusing_seeds
