### ISSUE TITLE
Training dreambooth on multiple GPUs with deepspeed

### ISSUE THREAD

**Issue by hamzafar** [huggingface/diffusers#1695]
### Describe the bug

Hi,

I am distributing dream booth training on 8 Tesla V100 (16GB) GPUs using deep speed.

I have configured accelerate as below(output of default_config.yaml):
`command_file: null
commands: null
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: null
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
mixed_precision: fp16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false
`

I am running train_dreambooth.py script as below:
`accelerate launch train_dreambooth.py --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" --instance_data_dir="/home/ubuntu/shoes" --output_dir="/home/ubuntu/sd_dreamboth" --instance_prompt="[v] shoes" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=2e-6 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=600`

I can observe the GPUs memory consumption just after executing the above script, but the training stops immediately. and I got follwoing error:

`
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torch/utils/cpp_extension.py", line 1818, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

RuntimeError: Error building extension 'utils'

ImportError: /home/ubuntu/.cache/torch_extensions/py38_cu118/utils/utils.so: cannot open shared object file: No such file or directory

ImportError: /home/ubuntu/.cache/torch_extensions/py38_cu118/utils/utils.so: cannot open shared object file: No such file or directory ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 110404) of binary: /usr/bin/python3

`

Kindly recommend me know, If I am configuring accelerate correctly?

![image](https://user-images.githubusercontent.com/6842017/207429378-b23d77b0-86dd-412d-a586-c87ba0f72f1f.png)

### Reproduction

accelerate launch train_dreambooth.py --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" --instance_data_dir="/home/ubuntu/shoes" --output_dir="/home/ubuntu/sd_dreamboth" --instance_prompt="[v] shoes" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=2e-6 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=600

### System Info

https://cloud.lambdalabs.com/instances: gpu_8x_v100

**Comment by hamzafar** [comment]
Yes, dreambooth is running without deepspeed.

**Comment by patil-suraj** [comment]
From the stack trace, it looks like deepspeed is not installed correctly, Could you try re-installing it ? Also, note that deepspeed support is experimental, I would recommend using `xformers` for memory-efficient training.

**Comment by hamzafar** [comment]
Thank you for the recommendation. I will try using `xformers`. Previously, I was using deepspeed for model parallelism. Can you provide some guidance on how to accomplish this task?

**Comment by hamzafar** [comment]
Hi @williamberman thank you for the recommendation. I will check into logs and open the issue with deepspeed.

Actually, I was asking assistance related to model parallelism.
