### ISSUE TITLE
Getting an error with pipeline_onnx_stable_diffusion_img2img.py AttributeError: 'Tensor' object has no attribute 'astype'. Did you mean: 'dtype'?

### ISSUE THREAD

**Issue by Justanetizen** [huggingface/diffusers#1709]
### Describe the bug

I'm getting an error when trying to use onnx img2img pipeline

Changing line 353 from image = image.astype(latents_dtype) to image = np.array(image).astype(latents_dtype) fixes this for me and seems to work but not sure if this is correct?

### Reproduction

from PIL import Image
from diffusers import OnnxStableDiffusionImg2ImgPipeline

init_image = Image.open('./img.png')

init_image = init_image.resize((512, 512), resample=Image.Resampling.LANCZOS)

pipe = OnnxStableDiffusionImg2ImgPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype="auto", safety_checker=None, requires_safety_checker=False, provider="DmlExecutionProvider")

prompt = "A fantasy landscape, trending on artstation"

images = pipe(prompt=prompt, image=init_image, strength=0.75, num_inference_steps=20, guidance_scale=7.5, negative_prompt="", num_images_per_prompt=1).images

images[0].save("./fantasy_landscape.png")

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Justanetizen\Documents\stuff\Coding\onnx stable diffusion\example.py", line 16, in <module>
    images = pipe(prompt=prompt, image=init_image, strength=0.75, num_inference_steps=20, guidance_scale=7.5, negative_prompt="", num_images_per_prompt=1).images
  File "C:\Users\Justanetizen\Documents\stuff\Coding\onnx stable diffusion\sd_env\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion_img2img.py", line 353, in __call__
    image = image.astype(latents_dtype)
AttributeError: 'Tensor' object has no attribute 'astype'. Did you mean: 'dtype'?
```

### System Info

- `diffusers` version: 0.11.0.dev0
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.6
- PyTorch version (GPU?): 1.13.0+cpu (False)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.26.0.dev0
- Using GPU in script?: Yes, using AMD Radeon RX 6600 using DmlExecutionProvider
- Using distributed or parallel set-up in script?: Don't know what this means, refer to reproduction script above

**Comment by averad** [comment]
@anton-l just want to put this on your radar.

Verified the reported issue.

**Comment by anton-l** [comment]
Thanks for flagging this @Justanetizen @averad !
The issue should be fixed with https://github.com/huggingface/diffusers/pull/1727

**Comment by Justanetizen** [comment]
Have pulled latest main branch and it is now working as expected, thank you!
