### ISSUE TITLE
Errors: Converting inpainting diffusers to OG stable diffusion

### ISSUE THREAD

**Issue by BenjaminIrwin** [huggingface/diffusers#1726]
Am I right in saying the diffusers to OG stable diffusion script (link below), shouldn't work for a non-standard architectures? 

I've finetuned an inpainting model from Runway's SD 1.5 Inpainting checkpoint. It has 9 input channels instead of 5. I created a .ckpt file from this finetuned model with the script below, but it's crashing Automatic111's repo when I run it.

https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion.py

**Comment by patrickvonplaten** [comment]
Hey @BenjaminIrwin,

We don't actively maintain the diffusers to OG stable diffusion script. Maybe someone from the community can help here though :-)

**Comment by zaryabmakram** [comment]
Hi @BenjaminIrwin, 

I would really love to have a detailed guide on how you were able to finetune the Runway's SD 1.5 Inpainting checkpoint on a custom dataset. It would be great if you could describe to me your process on how I can do the same on my own dataset.
