### ISSUE TITLE
[Community Pipeline] Superresolution with Transformers

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#1732]
:hugs: Transformers now also includes an image super resolution/restoration model: Swin2SR (based on Swinv2) :fire: 
models on the hub: https://huggingface.co/caidas
docs: https://huggingface.co/docs/transformers/main/en/model_doc/swin2sr

We could combine this very nicely with `diffusers` to build some cool community pipelines.

cc @NielsRogge

**Comment by julien-c** [comment]
could fit well inside this task type: https://huggingface.co/tasks/image-to-image

**Comment by Raman-Kumar** [comment]
Hi, @patrickvonplaten 
can I contribute to this?
I have previously contributed to PyTorch for new apple GPU operations (350+ lines of C++, Objective C, and Python)

**Comment by patrickvonplaten** [comment]
Hey @Raman-Kumar,

Yes please feel free to take this feature request :-)
