### ISSUE TITLE
train_dreambooth_flax not found gpu error 

### ISSUE THREAD

**Issue by rahilparsana** [huggingface/diffusers#1738]
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.) , i have the server with gpu its A100 80gb

**Comment by pcuenca** [comment]
Hi @rahilparsana, please make sure you follow the JAX installation instructions for CUDA: https://github.com/google/jax#pip-installation-gpu-cuda
