### ISSUE TITLE
list of prompts with same content leads to different inference speed

### ISSUE THREAD

**Issue by chesha1** [huggingface/diffusers#1742]
### Describe the bug

There are two cases:
1.
```
prompt_1 = "green grass"
prompt_2 = "apple tree"
prompt = [prompt_1, prompt_2]
```
2.
```
prompt = "green grass, apple tree"
```
Parameter *prompt* of pipe object can receive string or list of string. However, if I pass list of string into pipe, inference speed will decrease strongly. In the above cases, prompts are theoretically same, but the speed of case1 is half of that of case2.  
Is that a bug or a feature? If it is a feature, length of prompt is limited to 77 tokens due to CLIP. How to have longer prompt?

### Reproduction

```
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
pipe = pipe.to(device)


prompt_1 = "green grass"
prompt_2 = "apple tree"
prompt = [prompt_1, prompt_2]
num_inference_steps = 100
height = 512
width = 512
num_images_per_prompt = 3
guidance_scale = 7.5

PipelineOut = pipe(prompt, num_inference_steps=num_inference_steps, guidance_scale=guidance_scale, height=height, width=width, num_images_per_prompt=num_images_per_prompt)

### Logs

_No response_

### System Info

- `diffusers` version: 0.11.0.dev0
- Platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.31
- Python version: 3.9.13
- PyTorch version (GPU?): 1.12.0+cu116 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by averad** [comment]
https://huggingface.co/docs/diffusers/main/en/using-diffusers/custom_pipeline_examples#long-prompt-weighting-stable-diffusion

**Comment by pcuenca** [comment]
Hi @chesha1!

Please, note that the semantics are very different. When you use a list of prompts, then the pipeline generates _one image per prompt_. If you use a single string with the two prompts concatenated, then the pipeline generates only one image for that concatenated prompt. In your example, as you are using a list of 2 prompts and 3 images per prompt, you should receive a total of 6 images: 3 would be the result for the first prompt ("green grass") and 3 would be generated for the second ("apple tree"). The two prompts are not combined in any way, it's exactly the same as if you called the pipeline twice, each time with a prompt.

If you are interested in dealing with long prompts instead, then you can refer to the link pointed out by @averad.

I hope that helps :)
