### ISSUE TITLE
Getting a command not found error when trying to use script

### ISSUE THREAD

**Issue by killamonis** [huggingface/diffusers#1747]
Cloned the repo and tried using the convert_original_stable diffusion_to_diffusers.py to convert my .ckpt file and I'm getting a 
`sudo: ./scripts/convert_original_stable_diffusion_to_diffusers.py: command not found` error. Any idea what I can do to utilize the script?

Command I'm running 
`./scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path=*path* --scheduler_type=ddim --dump_path=*path*`

**Comment by averad** [comment]
`python ./scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path=*path* --scheduler_type=ddim --dump_path=*path*`
