### ISSUE TITLE
attention.py test can force you to uninstall xformer

### ISSUE THREAD

**Issue by BurguerJohn** [huggingface/diffusers#1773]
### Describe the bug

https://github.com/huggingface/diffusers/blob/9f8c915a756cf937a428186a2af8cc56f029f689/src/diffusers/models/attention.py#L305
https://github.com/huggingface/diffusers/blob/9f8c915a756cf937a428186a2af8cc56f029f689/src/diffusers/models/attention.py#L468

I have users that have xformer pre-compiled, but it not always work on their local computer. I do my own tests before calling set_use_memory_efficient_attention_xformers, but this will crash the application even if I'm turning the xformer to Off.

It's still a strange test to have hidden inside the model, this should be tested on a outside script, I think. Even so, even if tested in here, it should at least print a warning, not crash the application.

### Reproduction

Pre-compile or install a xformers binary that don't work on your computer, it will aways throw a Exception, even if you are setting xformers = Off

This tests should be on another layer of the script or at least just do that tests if xformers = On

### System Info

Windows

**Comment by kig** [comment]
Thanks for noticing this, I've got a fix brewing in #1776
