### ISSUE TITLE
Can the progress bar from pipe be suppressed ? 

### ISSUE THREAD

**Issue by Trisanu-007** [huggingface/diffusers#1786]
Hi, 
When we pass a prompt to the pip (from for eg: pipe = StableDiffusionPipeline.from_pretrained("./stable-diffusion-v1-5")), it displays an output in this case, with a progress bar. Is it possible to get an output without the progress bar, or to somehow disable it?

Thanks in advance!

**Comment by averad** [comment]
I haven't tested this but couldn't you use https://docs.python.org/3/library/contextlib.html or something similar to redirect the output 

```
import contextlib

with contextlib.redirect_stdout(None):
    Something
```

**Comment by averad** [comment]
[#172](https://github.com/huggingface/diffusers/issues/172)

**Comment by Trisanu-007** [comment]
Thank you very very much ! This solves my issue !

**Comment by Hzzone** [comment]
pipeline.set_progress_bar_config(disable=True)
