### ISSUE TITLE
getattr(): attribute name must be string

### ISSUE THREAD

**Issue by TheOneTrueGuy** [huggingface/diffusers#1801]
### Describe the bug

started throwing this error:
getattr(): attribute name must be string

![12_21_2022_diffuser_error](https://user-images.githubusercontent.com/3240071/209004339-00b0ee5d-3502-4f54-96b4-8d3a884bf714.PNG)

### Reproduction

code to reproduce error: ClipLoop.ipynb found in this repo: https://github.com/TheOneTrueGuy/DigitalDayDream

### Logs

```shell
sorry, no logs
```

### System Info

Google Colab, Linux

**Comment by TheOneTrueGuy** [comment]
the code where this happens has been running perfectly and looks perfectly unremarkable:
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    revision="fp16", 
    torch_dtype=torch.float16,
    use_auth_token=True
).to(device)
pipe.safety_checker = FakeSafety()

**Comment by TheOneTrueGuy** [comment]
upgraded to version 0.8.0 as per here: https://huggingface.co/CompVis/stable-diffusion-v1-4/discussions/158
now getting: 'PNDMScheduler' object has no attribute 'set_format' error instead.

Terribly frustrating all this old boys.

![12_21_2022_diffuser_error2](https://user-images.githubusercontent.com/3240071/209042253-16b4b9a8-029f-4974-977b-406a360a8b63.PNG)

**Comment by TheOneTrueGuy** [comment]
added: !pip install --upgrade diffusers transformers scipy 
to my steup/install as per: https://huggingface.co/CompVis/stable-diffusion-v1-4
and now I'm getting:  name 'init_empty_weights' is not defined

![12_21_2022_diffuser_error3](https://user-images.githubusercontent.com/3240071/209045404-dc6f9dad-015d-4e84-b37c-358b7eae5a01.PNG)

**Comment by ishwar00** [comment]
> upgraded to version 0.8.0 as per here: https://huggingface.co/CompVis/stable-diffusion-v1-4/discussions/158 now getting: 'PNDMScheduler' object has no attribute 'set_format' error instead.
> 
> Terribly frustrating all this old boys.
> 
> ![12_21_2022_diffuser_error2](https://user-images.githubusercontent.com/3240071/209042253-16b4b9a8-029f-4974-977b-406a360a8b63.PNG)

Did you try restarting the runtime after upgrading?

**Comment by TheOneTrueGuy** [comment]
> > upgraded to version 0.8.0 as per here: https://huggingface.co/CompVis/stable-diffusion-v1-4/discussions/158 now getting: 'PNDMScheduler' object has no attribute 'set_format' error instead.
> > Terribly frustrating all this old boys.
> > ![12_21_2022_diffuser_error2](https://user-images.githubusercontent.com/3240071/209042253-16b4b9a8-029f-4974-977b-406a360a8b63.PNG)
> 
> Did you try restarting the runtime after upgrading?

Yes, each of these is a fresh restart in a new google colab instance. I've gotten the same range of errors in a half-dozen different diffusers based programs I've written. The only version that doesn't throw these sorts of errors is the most basic text-to-image pipeline. Any sort of image-to-image or even the deforum notebook is giving me a similar complex of errors. 

All of them worked last week but after a short break I came back and none of them are working except text-to-image.

**Comment by pengbo807** [comment]
I ran into the same issue today, is there a solution yet?

**Comment by TheOneTrueGuy** [comment]
Nope, I'm still getting "NameError: name 'init_empty_weights' is not defined" with diffusers 0.11.0 from the upgrade.

Nothing at all has changed in my code, this has to be upstream of me, or upstream of diffusers.

 "You raised my hopes and dashed them quite expertly, sir. Bravo!" ―Tinny Tim. Futurama

This error is back now tho:
https://user-images.githubusercontent.com/3240071/209045404-dc6f9dad-015d-4e84-b37c-358b7eae5a01.PNG

**Comment by TheOneTrueGuy** [comment]
Ran the latest code example from here:
https://github.com/huggingface/diffusers#image-to-image-text-guided-generation-with-stable-diffusion
and it obviates the issue. Clear changes in the syntax, tsk-tsk. Not very backwards compatible.
Closing the issue while I burrow through changing all my code (12 notebooks!) to the new form.

**Comment by TheOneTrueGuy** [comment]
> 

Switched to a different module removed the problem, thanks anyways :)
