### ISSUE TITLE
Add Scalable Diffusion Pipline

### ISSUE THREAD

**Issue by MichaelFan01** [huggingface/diffusers#1805]
### Model/Pipeline/Scheduler description

Scalable Diffusion train latent diffusion models, replacing the commonly-used U-Net backbone with a transformer that operates on latent patches. We analyze the scalability of our Diffusion Transformers (DiTs) through the lens of forward pass complexity as measured by Gflops. We find that DiTs with higher Gflops---through increased transformer depth/width or increased number of input tokens---consistently have lower FID. In addition to good scalability properties, our DiT-XL/2 models outperform all prior diffusion models on the class-conditional ImageNet 512×512 and 256×256 benchmarks, achieving a state-of-the-art FID of 2.27 on the latter.

### Open source status

- [X] The model implementation is available
- [x] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://www.wpeebles.com/DiT
https://github.com/facebookresearch/DiT

**Comment by patrickvonplaten** [comment]
I think @kashif is already on to something exciting here: https://github.com/huggingface/diffusers/pull/1806
