### ISSUE TITLE
`from_pretrained` downloads `*.bin` and `*.safetensors` weights if both are present in the repo

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#1811]
### Describe the bug

If both `*.bin` and `*.safetensors` weights exist in a repository both are downloaded even thought only the `*.safetensors` version are used, doubling the disk size & time to download models. 

As we load `*.safetensors` by default, we should only download them.

### Reproduction

```py
import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1", torch_dtype=torch.float16)
```

### System Info

diffusers==0.11.1

**Comment by camenduru** [comment]
https://github.com/huggingface/diffusers/blob/9be94d9c6659f7a0a804874f445291e3a84d61d4/src/diffusers/modeling_utils.py#L569
https://github.com/huggingface/diffusers/blob/9be94d9c6659f7a0a804874f445291e3a84d61d4/src/diffusers/modeling_utils.py#L802

**Comment by camenduru** [comment]
also diffusers generating new snapshot again and again snapshots pointing to same thing but idk is this a bug?

![Screenshot 2022-12-26 042323](https://user-images.githubusercontent.com/54370274/209488086-6f27febd-a611-4135-8cfe-765d0acc6085.jpg)

**Comment by julien-c** [comment]
@camenduru do you use Developer mode on Windows? If yes, those snapshots would be symlink'ed to the actual files (i.E. not duplicated on disk space)

**Comment by camenduru** [comment]
Hi @julien-c 👋 yes snapshots pointing to same thing it is not a bug but I think this is a bug 🐜

![Screenshot 2022-12-26 085357](https://user-images.githubusercontent.com/54370274/209542517-9ce28615-0164-4fe2-bd52-a0de6324eba9.jpg)

**Comment by pcuenca** [comment]
@apolinario I'm not able to reproduce this using diffusers @ `main`. If I delete my cache directory and then load the stable diffusion pipeline for model `stabilityai/stable-diffusion-2-1`, this is what ends up being downloaded:

```
pedro@deep-hack:diffusers$ tree models--stabilityai--stable-diffusion-2-1/
models--stabilityai--stable-diffusion-2-1/
├── blobs
│   ├── 1238522277c48923ff2751e238f2742c562e45643f3d50cc93d163cb30638b0c
│   ├── 469be27c5c010538f845f518c4f5e8574c78f7c8
│   ├── 5294955ff7801083f720b34b55d0f1f51313c5c5
│   ├── 536b82b4e3c62c4898b4ac8725bc514f2a98f5de
│   ├── 76e821f1b6f0a9709293c3b6b51ed90980b3166b
│   ├── 9b1458658e8651398962171a8c5c56c5c0bd5aea
│   ├── 9c60528fdcb99a7caf834426a94ea13c56cf422b
│   ├── a1d993488569e928462932c8c38a0760b874d166399b14414135bd9c42df5815
│   ├── ae0c5be6f35217e51c4c000fd325d8de0294e99c
│   ├── cce6febb0b6d876ee5eb24af35e27e764eb4f9b1d0b7c026c8c3333d4cfc916c
│   ├── cefd6c7732bbda467ed1ec3e33cfa332a5fe32cf
│   ├── f4fe219b936c0e171504b4bba0c33c7bef6ea211
│   └── f97af6a6a8235236b1346312f328569ce2d70f81
├── refs
│   └── main
└── snapshots
    └── 36a01dc742066de2e8c91e7cf0b8f6b53ef53da1
        ├── feature_extractor
        │   └── preprocessor_config.json -> ../../../blobs/5294955ff7801083f720b34b55d0f1f51313c5c5
        ├── model_index.json -> ../../blobs/cefd6c7732bbda467ed1ec3e33cfa332a5fe32cf
        ├── scheduler
        │   └── scheduler_config.json -> ../../../blobs/536b82b4e3c62c4898b4ac8725bc514f2a98f5de
        ├── text_encoder
        │   ├── config.json -> ../../../blobs/9c60528fdcb99a7caf834426a94ea13c56cf422b
        │   └── model.safetensors -> ../../../blobs/cce6febb0b6d876ee5eb24af35e27e764eb4f9b1d0b7c026c8c3333d4cfc916c
        ├── tokenizer
        │   ├── merges.txt -> ../../../blobs/76e821f1b6f0a9709293c3b6b51ed90980b3166b
        │   ├── special_tokens_map.json -> ../../../blobs/ae0c5be6f35217e51c4c000fd325d8de0294e99c
        │   ├── tokenizer_config.json -> ../../../blobs/f4fe219b936c0e171504b4bba0c33c7bef6ea211
        │   └── vocab.json -> ../../../blobs/469be27c5c010538f845f518c4f5e8574c78f7c8
        ├── unet
        │   ├── config.json -> ../../../blobs/9b1458658e8651398962171a8c5c56c5c0bd5aea
        │   └── diffusion_pytorch_model.safetensors -> ../../../blobs/1238522277c48923ff2751e238f2742c562e45643f3d50cc93d163cb30638b0c
        └── vae
            ├── config.json -> ../../../blobs/f97af6a6a8235236b1346312f328569ce2d70f81
            └── diffusion_pytorch_model.safetensors -> ../../../blobs/a1d993488569e928462932c8c38a0760b874d166399b14414135bd9c42df5815

10 directories, 27 files
```

**Comment by pcuenca** [comment]
Ok, I've been able to reproduce it when a repo contains safetensors versions of just some files, but not all. This is the case for @camenduru's example.
