### ISSUE TITLE
Paint By Example Fine-tuning

### ISSUE THREAD

**Issue by kukeshajanth** [huggingface/diffusers#1812]
Is it possible to have a diffuser training implementation of paint by example pipeline? Should unlock, image conditioning for inpainting. Looking forward to contributing.

**Comment by patrickvonplaten** [comment]
Hey @kukeshajanth,

Feel free to open a PR to contribute such a training script. I'd suggest maybe to put it under: https://github.com/huggingface/diffusers/tree/main/examples/research_projects

in this case? :-)
