### ISSUE TITLE
train_text_to_image.py --resume_from_checkpoint logic is broken.

### ISSUE THREAD

**Issue by iuliaturc** [huggingface/diffusers#1813]
### Describe the bug

Problem 1
---
An attempt to resume from a checkpoint *and* push the result to the hub fails:
```
accelerate train_text_to_image.py \
...
--resume_from_checkpoint="latest" \
--push_to_hub \
--hub_model_id="myusername/mymodel"
```
Error message:
```
OSError: Tried to clone a repository in a non-empty folder that isn't a git repository. If you really want to do this, do it manually.
```
- IIUC, the script attempts to clone the repo inside the `args.output_dir`, which is not empty (since I'm resuming from an existing checkpoint in `args.output_dir`).
- Currently, the `output_dir` and resume directory are assumed to be the same ([relevant line](https://github.com/huggingface/diffusers/blob/8aa4372aea5bff1f64777a1c5f4fd502f1f9248e/examples/text_to_image/train_text_to_image.py#L602)).
- The solution could be to de-couple the two. Then, I could specify `--resume_from_checkpoint=/path/to/my/checkpoint-XXX` and `--output_dir=/new/path`, so that `--output_dir` is empty and can be cloned into.

Problem 2
---
The calculation of the resume step [here](https://github.com/huggingface/diffusers/blob/8aa4372aea5bff1f64777a1c5f4fd502f1f9248e/examples/text_to_image/train_text_to_image.py#L605) seems wrong:
```
resume_global_step = global_step * args.gradient_accumulation_steps
first_epoch = resume_global_step // num_update_steps_per_epoch
```
I don't think the multiplication by `args.gradient_accumulation_steps` is needed.

Concretely, when I resume from `checkpoint-14500` and set `--max_train_steps=15000`, no additional training is happening. Removing that multiplication solves the problem.

### Reproduction

See above.

### Logs

```shell
See above.
```

### System Info

Irrelevant.

**Comment by pcuenca** [comment]
Thanks @iuliaturc, I'll take a look. Another solution (for the first point) would be to _not_ use git clone, but that could be harder than decoupling the paths, as you suggested. Or detecting that the git checkout exists, copying @anton-l in case he has opinions here :)

**Comment by merfnad** [comment]
Just wanted to add that I found the same issue as problem 2 above, and the same solution fixes the issue. The global step number from the checkpoint already corresponds to target number of steps, no scaling by gradient accumulation steps is needed.

**Comment by pcuenca** [comment]
You are right @merfnad. Perhaps you or @iuliaturc would like to open a PR for that second issue while we find some time to resolve the first one?

**Comment by pcuenca** [comment]
The second issue was resolved but not sure about the first, taking a look.
