### ISSUE TITLE
support for change CLIP model.

### ISSUE THREAD

**Issue by CrazyBoyM** [huggingface/diffusers#1814]
I have tried changing the default CLIP model to chinese clip model, code like this:
```
import torch
from diffusers import StableDiffusionPipeline
from transformers import ChineseCLIPTextModel

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipe.text_encoder = ChineseCLIPTextModel.from_pretrained("OFA-Sys/chinese-clip-vit-large-patch16")
pipe = pipe.to("cuda")

prompt = "漂亮女孩，蓝色眼睛，金色头发"
image = pipe(prompt).images[0]  
```
but it can not work correctly, can you give me some suggestions?

**Comment by patrickvonplaten** [comment]
Hey @CrazyBoyM,

Note that Stable Diffusion has been trained to only use the English CLIP model. If you're looking for a Chinese/Multi-lingual model, could you please check: 
- https://huggingface.co/BAAI/AltDiffusion-m9

:-)
