### ISSUE TITLE
`--extract_ema` has no effect when converting .ckpt to diffusers

### ISSUE THREAD

**Issue by feffy380** [huggingface/diffusers#1818]
There's a bug in `scripts/convert_original_stable_diffusion_to_diffusers.py` that causes the `--extract_ema` flag to have no effect, so it always uses the non-EMA weights. I converted the sd-v1-4 ckpt to diffusers format both with and without the flag. `diff` reports both directories are identical.

```
$ diff -s sd14-ema sd14-non_ema
Common subdirectories: sd14-ema/feature_extractor and sd14-non_ema/feature_extractor
Files sd14-ema/model_index.json and sd14-non_ema/model_index.json are identical
Common subdirectories: sd14-ema/safety_checker and sd14-non_ema/safety_checker
Common subdirectories: sd14-ema/scheduler and sd14-non_ema/scheduler
Common subdirectories: sd14-ema/text_encoder and sd14-non_ema/text_encoder
Common subdirectories: sd14-ema/tokenizer and sd14-non_ema/tokenizer
Common subdirectories: sd14-ema/unet and sd14-non_ema/unet
Common subdirectories: sd14-ema/vae and sd14-non_ema/vae
```

The problem appears to be this snippet here, where the non-EMA weights are unconditionally copied to `unet_state_dict`, overwriting the EMA weights written by the preceding block of code.

https://github.com/huggingface/diffusers/blob/9be94d9c6659f7a0a804874f445291e3a84d61d4/scripts/convert_original_stable_diffusion_to_diffusers.py#L335-L337

**Comment by patrickvonplaten** [comment]
Hey @feffy380,

Could you link to the checkpoint you are trying to convert? Note that `--extract_ema` only works/make sense if the checkpoint has both EMA and non-EMA weights.

**Comment by feffy380** [comment]
This was with the Stable Diffusion v1.4 full-ema checkpoint from https://huggingface.co/CompVis/stable-diffusion-v-1-4-original

**Comment by patrickvonplaten** [comment]
Hey @feffy380,

Thanks a lot for the issue, you're 100% right. This was actually a nasty silent bug and thanks to you it's corrected now - thanks a mille :heart: 

I hope not too many community members have the incorrect checkpoint now :fearful: 

The PR #1937 should fix it :-)

**Comment by patrickvonplaten** [comment]
Issue should be fixed along-side some other issues. BTW, here is now a nice space to automatically convert checkpoints: https://huggingface.co/spaces/diffusers/sd-to-diffusers/discussions/1
