### ISSUE TITLE
image sources for training examples for validation/comparison (data provided)

### ISSUE THREAD

**Issue by Thomas-MMJ** [huggingface/diffusers#1819]
Below I've attached a list of image sources used for the Dreambooth and Textual Inversion paper, I've also included images provided by Joe Penna to be used for comparing training on a person (Joe Penna has given permission for his images to be used for this purpose). 

I'd like to have this added to the examples folder.  This will allow people to be certain that their local setup is working before trying to train on a custom image.  It will also be useful for researchers to compare new techniques.

[image_sources_for_training_examples.txt](https://github.com/huggingface/diffusers/files/10297569/image_sources_for_training_examples.txt)

**Comment by Thomas-MMJ** [comment]
We should likely also have a standardized captions for the images, and standardized regularization images (also with captions).

**Comment by patrickvonplaten** [comment]
Hey @Thomas-MMJ,

Should we maybe make this a dataset on the Hub? https://huggingface.co/new-dataset
Also, what exactly is the idea here? To train the model or the images linked in your text dataset and then expect a certain output? How exactly were you imagining such a test? :-)
