### ISSUE TITLE
accelerator.save_state() get stuck When training with Multi-GPUs

### ISSUE THREAD

**Issue by StrugglingForBetter** [huggingface/diffusers#1820]
### Describe the bug

accelerator.save_state() get stuck When training with Multi-GPUs. 
but it works well when training with a single GPU, how to solve this problem?

### Reproduction

                    if accelerator.is_main_process:
                        save_path = os.path.join(args.ckpt_path, f"checkpoint-{global_step}")
                        
                        accelerator.save_state(save_path)
                        logger.info(f"Saved state to {save_path}")

### System Info

ubuntu 20.04

**Comment by patrickvonplaten** [comment]
Hey @StrugglingForBetter, 

Could you please add a reproducible code snippet? 

Also cc @patil-suraj @pcuenca here

**Comment by patil-suraj** [comment]
Hey @StrugglingForBetter , I think it's likely because if `deepspeed`, I've verified that saving works on multi-gpu, won't be able to look into deepspeed issue soon, but I will recommend using `xformers` for memory efficient training. It should help fit the training in 24GB.

**Comment by StrugglingForBetter** [comment]
> 

Hi, @patil-suraj . Thanks for your suggestion. Can you give me a more detailed info about how to use xformers? Is there any link or detailed tuturials, or any examples? Thanks!

**Comment by patil-suraj** [comment]
Sure, first you'll need to install `xformers`,  for this:

- either try this https://huggingface.co/docs/diffusers/optimization/xformers; this is the simplest way but is experimental
- if this doesn't work, you'll need to build it from source, for that, see https://github.com/facebookresearch/xformers#installing-xformers

Once you have `xformers` installed, pass `--enable_xformers_memory_efficient_attention` to the script, it should reduce memory usage quite significantly.

**Comment by patil-suraj** [comment]
No I haven't tried `deepspeed`, I meant saving works on multi-gpu without deepspeed, so this issue is likely because of deepspeed.

**Comment by StrugglingForBetter** [comment]
> Sure, first you'll need to install `xformers`, for this:
> 
> * either try this https://huggingface.co/docs/diffusers/optimization/xformers; this is the simplest way but is experimental
> * if this doesn't work, you'll need to build it from source, for that, see https://github.com/facebookresearch/xformers#installing-xformers
> 
> Once you have `xformers` installed, pass `--enable_xformers_memory_efficient_attention` to the script, it should reduce memory usage quite significantly.

I tried 2 ways you mentioned but all failed. 
If I use this way: https://huggingface.co/docs/diffusers/optimization/xformers
it will report :
Requirement already satisfied: pyre-extensions==0.0.23 in /home/hello/anaconda3/lib/python3.8/site-packages (from formers==0.0.15.dev376) (0.0.23)
ERROR: Could not find a version that satisfies the requirement torch==1.13 (from formers) (from versions: none)
ERROR: No matching distribution found for torch==1.13

but my pytorch version is 1.13.1 + cu117

Is there a pytorch version 1.13?? I know there is a version named 1.13.0

**Comment by better629** [comment]
@StrugglingForBetter Do u solve the problem, I have the same prolem https://github.com/huggingface/diffusers/issues/2606
