### ISSUE TITLE
Comments swapped in Stable Diffusion depth2img

### ISSUE THREAD

**Issue by neverix** [huggingface/diffusers#1823]
### Describe the bug

In [pipeline_stable_diffusion_depth2img.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py), lines 541 and 531 have swapped labels in the comments.

### Reproduction

 -, mistake in the code

### System Info

N/A

**Comment by patrickvonplaten** [comment]
Hey @neverix, 

Thanks a lot for the issue!
Would you like to open a PR to fix it? :-)

**Comment by neverix** [comment]
Sure #1903
