### ISSUE TITLE
Stable Diffusion Img2Img with a mask

### ISSUE THREAD

**Issue by Mwni** [huggingface/diffusers#1825]
The masking on inpainting mode works perfect. However, the issue is, that you always need a dedicated inpainting checkpoint for inpainting. This checkpoint must have a denoiser with (9, W, H) input shape instead of (5, W, H). 

For many custom models such a checkpoint does not exist. Other repositories like [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) support this; If the checkpoint is not inpainting compatible, it falls back to regular img2img, yet still applies the mask in the sampling process.

Is this possible with the current code base?

**Comment by patrickvonplaten** [comment]
Hey @Mwni,

Yes this is very much possible with this class: https://github.com/huggingface/diffusers/blob/1bf4f0da7e76ebe6a31e0d596f61f11652210f99/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py#L68 - it can load any SD checkpoint. 

Also these docs here might help:
- https://github.com/huggingface/diffusers/tree/main/examples/community#stable-diffusion-mega
- https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion#how-to-convert-all-use-cases-with-multiple-or-single-pipeline

**Comment by patrickvonplaten** [comment]
Let me know if this has helped/worked :-)

**Comment by Mwni** [comment]
Yes. Thanks.

**Comment by djibvongenf** [comment]
hi, is there a possiblity to work with multimask?

let's say i have a 3d image with 4 material
blue = concrete
red = glass
green = wood
yellow = aluminium

Mask generated through my 3d software to be more precised

Or for each material i can add a alpha channel (mask) which mean i can use 4 different mask (bw) with a specific text prompt

thanks

**Comment by homedesignsai** [comment]
@patrickvonplaten 
I want to use this Img2img model (https://civitai.com/models/139562?modelVersionId=344487) for inpainting task as per above solution I have try this code but it gives me an error

`from diffusers import DiffusionPipeline
import PIL
import requests
from io import BytesIO
import torch


def download_image(url):
    response = requests.get(url)
    return PIL.Image.open(BytesIO(response.content)).convert("RGB")


pipe = DiffusionPipeline.from_single_file(
    "/workspace/stable-diffusion-xl-inpainting/checkpoints/realvisxlv4.safetensors",
    torch_dtype=torch.float16,
).to("cuda")
pipe.enable_attention_slicing()

### Inpainting

img_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo.png"
mask_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo_mask.png"
init_image = download_image(img_url).resize((512, 512))
mask_image = download_image(mask_url).resize((512, 512))

prompt = "a cat sitting on a bench"
images = pipe.inpaint(
    prompt=prompt, image=init_image, mask_image=mask_image, strength=0.75
).images`

This error I am getting "AttributeError: type object 'DiffusionPipeline' has no attribute 'from_single_file'"

Please let me know if I am doing something wrong

**Comment by Tokir-Vora** [comment]
@patrickvonplaten 

I want to use this Img2img model (https://civitai.com/models/139562?modelVersionId=344487) for inpainting task as per above solution I have try this code but it gives me an error

```
from diffusers import DiffusionPipeline
import PIL
import requests
from io import BytesIO
import torch


def download_image(url):
    response = requests.get(url)
    return PIL.Image.open(BytesIO(response.content)).convert("RGB")


pipe = DiffusionPipeline.from_single_file(
    "/workspace/stable-diffusion-xl-inpainting/checkpoints/realvisxlv4.safetensors",
    torch_dtype=torch.float16,
).to("cuda")
pipe.enable_attention_slicing()

### Inpainting

img_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo.png"
mask_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo_mask.png"
init_image = download_image(img_url).resize((512, 512))
mask_image = download_image(mask_url).resize((512, 512))

prompt = "a cat sitting on a bench"
images = pipe.inpaint(
    prompt=prompt, image=init_image, mask_image=mask_image, strength=0.75
).images
```

This error I am getting "**AttributeError: type object 'DiffusionPipeline' has no attribute 'from_single_file'**"

Please let me know if I am doing something wrong
