### ISSUE TITLE
Best way to work around xformers backwards K limit on sm80/86/89 devices

### ISSUE THREAD

**Issue by hafriedlander** [huggingface/diffusers#1829]
XFormers currently can't run backwards on many Sm80/86/89 devices. It runs fine at any size on A100s, but on other devices in the class (including common ones like 3080, 3090, 4090) it only works backwards when dim_heads <= 64.

This is a pretty narrow use case (most people don't run backwards as standard inference doesn't need it, and SD2 and greater have dim_heads <= 64 for all layers), and kind of working around a bug in xformers, so I'm not sure if there should be a specific API to support working around this issue.

If this is appropriate to include in DIffusers, any preference on an API? (My naive though is to add a `max_dim_head` argument to `set_use_memory_efficient_attention_xformers`). I'm happy to do a PR if an API is agreed.

**Comment by hafriedlander** [comment]
Here's some logic I wrote that detects the issue (for Diffusers 0.10.x) - https://github.com/cloneofsimo/lora/blob/bc497114969a629c0cf909c0a5837d1dacb6909f/lora_diffusion/xformers_utils.py

It's similar to the test in https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/cross_attention.py#L120 but deliberately runs backwards, and checks per dimhead.

Any opinion on whether this should be in Diffusers @patil-suraj  or @patrickvonplaten ?

**Comment by patil-suraj** [comment]
As you said, it's a narrow use case, so I'm not sure if we should handle this in diffusers. I think it's okay to let it fail explicitly during backward if it not working. Maybe open an issue in `xformers` to see if they have any plans for this.

**Comment by hafriedlander** [comment]
There is already an issue https://github.com/facebookresearch/xformers/issues/563 - TLDR; they aren't planning on fixing it any time soon.

The downside is that Dreambooth and other training will fail on SD1.5 based models with xformers on, in a way that isn't well documented or communicated.

It's relatively easy to detect the error, and you already have a "does xformers work reliably" test in unet. My personal vote would be that the training scripts at least should have a test & warning if user tries to enable xformers when it won't work.

**Comment by qslug** [comment]
This is (at least partly) fixed now as part of https://github.com/facebookresearch/xformers/commit/615175f6082afcb91e72bf277ea9d3c722cc4a11.

**Comment by litaotju** [comment]
It's a known issue of xformers library on 30x GPUs, try install the dev version of the xformers. 
This works on my 3060.
```
pip install xformers==0.0.17.dev466
```

See https://github.com/facebookresearch/xformers/issues/631
