### ISSUE TITLE
Adding image logging to textual_inversion script

### ISSUE THREAD

**Issue by isamu-isozaki** [huggingface/diffusers#1837]
**Is your feature request related to a problem? Please describe.**
Currently, the textual inversion script just runs the full course without any logging of images and no way for the users to see what kind of images it will produce.

**Describe the solution you'd like**
At every --log_frequency steps, make images log to wandb/local dir. I have done this in a personal project and it's nice to see how the model is learning.

**Describe alternatives you've considered**
Make a pipeline that just logs to a local directory as log_{global_step}.jpg.

I can do this pr too since it's a simple copy paste

**Comment by patrickvonplaten** [comment]
@patil-suraj @williamberman can you take a look here?

**Comment by patil-suraj** [comment]
#2009 should fix this

**Comment by isamu-isozaki** [comment]
Merged
