### ISSUE TITLE
Training multiple faces concepts with single model 

### ISSUE THREAD

**Issue by Abhi001vj** [huggingface/diffusers#1843]
Hi I tried to train diffusion model on multiple concepts with code from this repo. My idea was to create a script that takes in  a directory full of labeled images like actors' names or character names. Then I run this script on a video to create directories full of frames where the actor/ character appears. Now I can use this data to train multiple concepts at once and create new scenes from the video. Eg if I extract characters from the movie Terminator and Predator after training I can create new scenes like predator and terminator facing each other, but instead of two different models I can do this with a single model. When I tried to do this I got very blurred-out results with a lot of artifacts. Is there a recommended number of steps for training multiple concepts at once?  Please share your experience if you have tried to train multiple concepts at the same time. Thank you

**Comment by patrickvonplaten** [comment]
Do you use DreamBooth?
