### ISSUE TITLE
Post choosing accerlate config-- Which type of machine are you using-- What do I choose?

### ISSUE THREAD

**Issue by Jcdude105** [huggingface/diffusers#1847]
> Please select a choice using the arrow or number keys, and selecting with enter
  No distributed trainingg
  multi-CPU
 * multi-GPU
  TPU
  MPS       

I have a normal computer, an rtx 2060 and a normal cpu, core i-5 11400F, and I have no idea what TPU and MPS stands for, but from google searches both seem like old technology and I don't have multiple Cpu's or gpus so Idk which to choose. Can anyone help?

**Comment by Abhinay1997** [comment]
Can you provide context where you're seeing this ? If you can provide a code snippet, even better.

TPU is used only for Google TPU hardware (supported on Google Colab).
MPS is used for Apple ARM processors ( M1, M2, M1 Pro , M1 Ultra etc) on the new macbooks.

So you should be choosing either CUDA ( Nvidia GPU's ) or CPU. Try ```no distributed training``` first and check if your GPU is being used. Let us know how it goes.

**Comment by Abhinay1997** [comment]
You can:-
1. Choose ```no distributed training``` for this question.
2. In the next step, you'll be prompted with:- ```Do you want to run your training on CPU only (even if a GPU is available)? [yes/NO]```: Choose NO
3. After a few more questions you get ```What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:``` Mention your GPU id here if you see it.

**Comment by Jcdude105** [comment]
> 

That was helpful and worked so thank you! By the way, these settings can be changed by just running "accerlate config" again right?

**Comment by Abhinay1997** [comment]
Yes. You should be able to rerun accelerate config and change them again.
