### ISSUE TITLE
Can't paste or even type my token for logging into huggingface from the commandline?

### ISSUE THREAD

**Issue by Jcdude105** [huggingface/diffusers#1853]
Hi, for context, I'm trying to follow this [guide](https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth) in order to make dreambooth require less vram since I only have an rtx 2060 6gb and I got stuck following the guide. I used to use gitbash for my commands before I switched to windows command because I couldn't select the machine for accerlating the enviorment but that's besides the point. 

From the windows commandline, when I type or paste "huggingface-cli login", a "token:" appears to enter the token but I cannot type, let alone paste after I type "huggingface-cli login" and hit enter. When I tried the same command from git bash, entering "huggingface-cli login" doesn't do anything and instead makes the line go down, similar to how pressing enter makes the line go down in microsoft word. 

How do I fix this? I'm new to anything coding related so I don't know where to even start to fix this.

**Comment by Abhinay1997** [comment]
As a workaround ,can you set your token in the environment variable so you can skip calling huggingface-cli login ?

Try this in your cli:
```set HUGGING_FACE_HUB_TOKEN=your_token_here```

OR

You can also set the token at the top in the python script that requires your token as follows:-
```
from huggingface_hub.hf_api import HfFolder
HfFolder.save_token('your_token_here')
```

**Comment by patrickvonplaten** [comment]
Actually I don't think you need to login in anymore to have access to any model. They are all free to download now. 
Otherwise could you maybe post the issue on: https://github.com/huggingface/huggingface_hub
