### ISSUE TITLE
Custom pipeline as attribute

### ISSUE THREAD

**Issue by adhikjoshi** [huggingface/diffusers#1854]
Right now we need to load custom pipelines as parameter in DiffusionPipeline 

`pipe = DiffusionPipeline.from_pretrained(model_id, custom_pipeline="lpw_stable_diffusion", revision="fp16", torch_dtype=torch.float16)`

But, can we pass custom_pipeline as attribute? this will allow changing pipelines easily without loading model

```
pipe = DiffusionPipeline.from_pretrained(model_id, revision="fp16", torch_dtype=torch.float16)
pipe.custom_pipeline("lpw_stable_diffusion")
```

**Comment by patrickvonplaten** [comment]
Interesting idea! Not a big fan of such magic functions (like `pipe.custom_pipeline("lpw_stable_diffusion")` would silently convert `pipe` into another class.

But maybe we could do something like:

```py
from diffusers.utils import load_custom_pipeline_classes

pipe = DiffusionPipeline.from_pretrained(model_id, revision="fp16", torch_dtype=torch.float16)
lpw_cls = load_custom_pipeline_classes("lpw_stable_diffusion")

pipe = lpw_cls(**pipe.components)
```

**Comment by adhikjoshi** [comment]
> Interesting idea! Not a big fan of such magic functions (like `pipe.custom_pipeline("lpw_stable_diffusion")` would silently convert `pipe` into another class.
> 
> But maybe we could do something like:
> 
> ```py
> from diffusers.utils import load_custom_pipeline_classes
> 
> pipe = DiffusionPipeline.from_pretrained(model_id, revision="fp16", torch_dtype=torch.float16)
> lpw_cls = load_custom_pipeline_classes("lpw_stable_diffusion")
> 
> pipe = lpw_cls(**pipe.components)
> ```
> 
> 
> 

This is even better, can swap pipelines easily.

**Comment by patrickvonplaten** [comment]
Can @anton-l @patil-suraj @pcuenca what do you think about the idea? If you're ok with it, I could open a PR for it :-)

**Comment by patil-suraj** [comment]
Good idea, but we could also do this no?

```python
pipe = DiffusionPipeline.from_pretrained(model_id, revision="fp16", torch_dtype=torch.float16)
lpw = DiffusionPipeline.from_pretrained(model_id, custom_pipeline="lpw_stable_diffusion",  **pipe.component)
```

Maybe we should just document it better.
