### ISSUE TITLE
Should I do 'accelerator.prepare()' again after 'accelerator.unwrap_model()' ?

### ISSUE THREAD

**Issue by DtYXs** [huggingface/diffusers#1855]
For multi-gpu training:
`model = accelerator.prepare(model)`
I want to save ckpt during training. Then I do this:
`model = accelerator.unwrap_model(model)`
`pipeline = Pipeline(model=model)`
`pipeline.save_pretrained(...)`
And I want to continue training. Should I do `model = accelerator.prepare(model)` again after saving?

**Comment by patrickvonplaten** [comment]
cc @patil-suraj @pcuenca

**Comment by patil-suraj** [comment]
@DtYXs checkpointing is now added to all scripts, for example, #1668.

And to answer your question, you should not assign unwrapped `model` to `model`; instead, we could directly pass `accelerator.unwrap_model(model)` to `pipeline` or use a different variable name.
