### ISSUE TITLE
UnCLIP Pipeline is currently poorly tested

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#1857]
### Describe the bug

The UnCLIP pipeline, like any new pipeline in `src/pipelines` should depend on the tester mixin: https://github.com/huggingface/diffusers/blob/debc74f442dc74210528eb6d8a4d1f7f27fa18c3/tests/test_pipelines_common.py#L35 just like Stable Diffusion does: https://github.com/huggingface/diffusers/blob/debc74f442dc74210528eb6d8a4d1f7f27fa18c3/tests/pipelines/stable_diffusion/test_stable_diffusion.py#L47 so that we can be sure that batched inference etc... works well.

This is currently not the case:
- https://github.com/huggingface/diffusers/blob/debc74f442dc74210528eb6d8a4d1f7f27fa18c3/tests/pipelines/unclip/test_unclip_image_variation.py#L41
- https://github.com/huggingface/diffusers/blob/debc74f442dc74210528eb6d8a4d1f7f27fa18c3/tests/pipelines/unclip/test_unclip.py#L32

@williamberman could you take care of this? :-) 

### Reproduction

Batched inference tests etc... are currently not run.

### System Info

Current "main" of diffusers.

**Comment by williamberman** [comment]
Ah thanks for catching! Will add

**Comment by williamberman** [comment]
Resolving issue as https://github.com/huggingface/diffusers/pull/1908 was merged :)
