### ISSUE TITLE
Stable Diffusion 2.x -- Wrong CLIP layer is being used for conditioning?

### ISSUE THREAD

**Issue by jorgemcgomes** [huggingface/diffusers#1863]
### Describe the bug

Looking at the ["official" SD implementation](https://github.com/Stability-AI/stablediffusion), we can see in the end of the inference config file the following lines:

https://github.com/Stability-AI/stablediffusion/blob/d55bcd4d31d0316fcbdf552f2fd2628fdc812500/configs/stable-diffusion/v2-inference.yaml#L63-L67
```
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"
```

Following the implementation in https://github.com/Stability-AI/stablediffusion/blob/main/ldm/modules/encoders/modules.py , we can see that this config means that conditioning is not done on the last CLIP layer, but on the penultimate CLIP layer. This is not unheard of, Novel.ai reported doing something similar https://blog.novelai.net/novelai-improvements-on-stable-diffusion-e10d38db82ac

This seems to be different from what is being done in the diffusers pipeline, where the last_hidden_state is used for conditioning.

https://github.com/huggingface/diffusers/blob/ab0e92fdc8b42e1739840d10bb0b1dc7edaf2ff3/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L265-L269

Has the diffusers implementation been tested against the StabilityAI implementation? A difference like this would most likely impact the generation quality, although it wouldn't really break it, so it could go unnoticed. 

If this is indeed an issue, all pipelines and stable diffusion trainers (for both torch and Jax) would have to be fixed.

### System Info

0.12.0 dev

## Examples

Some comparisons for the prompts "art, low-poly fire-spitting dragon", "art, high-quality photo of a dog", "icon, casual, racing, grey, subway surfer", "art, hypercasual, squid game on a snowy mountain". The results are definitely different, not destructively different though. But I would guess that this affects some prompts more than others.

### Current implementation: `final_layer_norm(last_hidden_state)`

![image](https://user-images.githubusercontent.com/3987574/210015057-f191b42d-52df-4cb9-af85-6af9da6033df.png)
![image](https://user-images.githubusercontent.com/3987574/210015139-1dad78a5-36fc-4450-b1fc-2059c4d7115e.png)
![image](https://user-images.githubusercontent.com/3987574/210015175-65f531bc-838a-4042-bf05-1efe2e186dac.png)
![image](https://user-images.githubusercontent.com/3987574/210015192-7e51ab37-f3c0-4fc1-87e7-2e96697b3f59.png)

### Changing to `final_layer_norm(hidden_state[-2])`

![image](https://user-images.githubusercontent.com/3987574/210015073-050eecd4-50f2-422a-8cd4-3f853410c0fc.png)
![image](https://user-images.githubusercontent.com/3987574/210015145-97c0e2e9-f493-4133-82a1-69c016c810a4.png)
![image](https://user-images.githubusercontent.com/3987574/210015178-5c3d3855-a00d-44b3-b031-4e6c0f53db30.png)
![image](https://user-images.githubusercontent.com/3987574/210015200-0aa3d73c-d978-49a3-85ff-c7c3279b69bc.png)

**Comment by hafriedlander** [comment]
Not a bug - when converting from ckpt, they just drop the final layer from the model which has the same effect.

https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py#L755

https://huggingface.co/stabilityai/stable-diffusion-2-1-base/blob/main/text_encoder/config.json#L19

**Comment by keturn** [comment]
related: #1721

**Comment by hafriedlander** [comment]
BTW, if you _do_ want to use a lower layer, you can wrap it in something like https://github.com/hafriedlander/stable-diffusion-grpcserver/blob/dev/sdgrpcserver/pipeline/text_embedding/text_encoder_alt_layer.py

**Comment by jorgemcgomes** [comment]
> Not a bug - when converting from ckpt, they just drop the final layer from the model which has the same effect.
> 
> https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py#L755
> 
> https://huggingface.co/stabilityai/stable-diffusion-2-1-base/blob/main/text_encoder/config.json#L19

I see, that makes a lot of sense.

Glad this wasn't an issue after all!

**Comment by patrickvonplaten** [comment]
Also answered in-detail here: https://github.com/huggingface/diffusers/issues/1721#issuecomment-1372737379
