### ISSUE TITLE
Tried converting a diffuser to onnx, AMD GPU?

### ISSUE THREAD

**Issue by DOUBLEXX666** [huggingface/diffusers#1881]
![Screenshot 2023-01-01 125044](https://user-images.githubusercontent.com/66040365/210184270-615ffaf0-12eb-4306-b92f-debcc003d51c.png)

**Comment by patrickvonplaten** [comment]
Hey @DOUBLEXX666,

Could you please provide your diffusers version (run `diffusers-cli env`) 

And also a reproducible code snippet which can be copy pasted to reproduce your error
