### ISSUE TITLE
generation of multi person in one image is bad. 

### ISSUE THREAD

**Issue by tengshaofeng** [huggingface/diffusers#1899]
I train two person at the same time. one is 'a sks woman', the other is 'a zwx man'.
It is ok when using single person, for instance 'a sks woman'.   But when I want to create photo of couple, using prompt 'a sks woman and a zwx man', it came bad generation, most time only one person is just so so, the other one is always bad. It seems that when put them together, two person will both be affected.
Why? How can I solve that?

**Comment by patrickvonplaten** [comment]
Interesting! I haven't had much experience with this yet.

**Comment by tengshaofeng** [comment]
> 

ok, Thanks for your reply.
