### ISSUE TITLE
Load Automatic1111 trained embeddings file to HF

### ISSUE THREAD

**Issue by kamalkraj** [huggingface/diffusers#1904]
Is it possible to load the Automatic1111 trained embeddings file to HF diffusers? 

For example: https://huggingface.co/joachimsallstrom/Double-Exposure-Embedding

@patil-suraj @patrickvonplaten @anton-l

**Comment by patrickvonplaten** [comment]
Hmm not sure, are the trained embedding files coming from textual inversion? cc @patil-suraj

**Comment by harishprabhala** [comment]
Yes I believe these are trained on Textual Inversions in automatic1111 webui

**Comment by kamalkraj** [comment]
> Hmm not sure, are the trained embedding files coming from textual inversion? cc @patil-suraj

Yes. 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Textual-Inversion

**Comment by camenduru** [comment]
I wrote a script back then but I didn't find sorry if I find I will share but simple, first `flat` then convert like this

diffusers embed 
`{'<midjourney-style>': tensor([-5.9785e-02, -3.8523e-02,`

auto embed
`{'string_to_token': {'*': 265}, 'string_to_param': {'*': tensor([[ 0.1605,  0.7939,  0.1157,`

you need just remove ` 'string_to_token': {'*': 265}, 'string_to_param': {'*` part and add ` {'<midjourney-style>': `

**Comment by kamalkraj** [comment]
Hi @camenduru ,

How exactly can we load this when no.of vectors learned per token is greater than 1?
for reference - https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Textual-Inversion#creating-an-embedding

cc @patrickvonplaten @patil-suraj @anton-l

**Comment by camenduru** [comment]
Please look how auto loads both and maybe you can reverse it without converting https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/7ec275fae799f19cdb1756412ae75ca6bfe251cd/modules/textual_inversion/textual_inversion.py#L163

**Comment by patrickvonplaten** [comment]
cc @patil-suraj here

**Comment by patrickvonplaten** [comment]
@kamalkraj how exactly can you load the embedding weights: https://huggingface.co/joachimsallstrom/Double-Exposure-Embedding/blob/main/dblx.pt into PyTorch? The following doesn't work for me:

```python
import torch

embeds = torch.load("./dblx.pt")
```

when having downloaded `"./dblk.pt"` from: https://huggingface.co/joachimsallstrom/Double-Exposure-Embedding/blob/main/dblx.pt

**Comment by kamalkraj** [comment]
> @kamalkraj how exactly can you load the embedding weights: https://huggingface.co/joachimsallstrom/Double-Exposure-Embedding/blob/main/dblx.pt into PyTorch? The following doesn't work for me:
> 
> ```python
> import torch
> 
> embeds = torch.load("./dblx.pt")
> ```
> 
> when having downloaded `"./dblk.pt"` from: https://huggingface.co/joachimsallstrom/Double-Exposure-Embedding/blob/main/dblx.pt

```python
!wget https://huggingface.co/joachimsallstrom/Double-Exposure-Embedding/resolve/main/dblx.pt

import torch

embedding = torch.load("dblx.pt",map_location=torch.device('cpu'))
```

@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Also related: https://github.com/huggingface/diffusers/issues/1985

**Comment by camenduru** [comment]
@kamalkraj @patrickvonplaten I found it I already added here memory lost 😋 

https://github.com/camenduru/notebooks/blob/main/camenduru's_webui_to_diffusers_embeddings.ipynb

**Comment by functorism** [comment]
@camenduru Wouldn't one need to add all tokens and use them together to achieve the full effect for some of these embeddings?

For every vector add a new token `<style-n>` (or similar), and when prompting use `my prompt, by <style-1><style-2><style-n>...`?

In the case of `dblx.pt` there would be 8.

But I feel like I'm missing something, because how it usually seems to work is that these embeddings are loaded and then only one style word is actually used, like `a profile photo of a woman and a city, photo by dblx` from the `dblx` example.

**Comment by camenduru** [comment]
@functorism I don't want to say something incorrect I believe all your questions in this video thanks to Jonathan Whitaker ❤
https://youtu.be/0_BBRNYInx8?t=523

also if you want merge embeddings please check 
https://github.com/CodeExplode/stable-diffusion-webui-embedding-editor
https://github.com/tkalayci71/embedding-inspector

**Comment by kamalkraj** [comment]
solved - https://colab.research.google.com/drive/1Oou-wjDbMZsxOKOnc7EF5DbOcMgXAUR4?usp=sharing
successfully reproducing the results of the readme of https://huggingface.co/joachimsallstrom/Double-Exposure-Embedding

@functorism, you are correct. 

@camenduru thank you so much for making colab T4 xformers binary 

cc @patrickvonplaten @patil-suraj

**Comment by camenduru** [comment]
@kamalkraj wow super cool thanks ♥️

**Comment by functorism** [comment]
Thanks @kamalkraj and @camenduru, I was able to reproduce the example picture for dblx with the aforementioned technique of adding tokens for each vector. Example notebook here: https://gist.github.com/functorism/d7821fa065760b5f584d800b893380ac

**Comment by patil-suraj** [comment]
Thanks a lot @kamalkraj @functorism 

so the idea is to just use multiple tokens when you multiple TI embeddings ? I just checked the original TI repo and it seems to be doing something different cf https://github.com/rinongal/textual_inversion/blob/main/ldm/modules/embedding_manager.py#L119

Does anyone here know how it's done auto1111?
