### ISSUE TITLE
Add additional integration testing around training scripts i.e. dreambooth

### ISSUE THREAD

**Issue by williamberman** [huggingface/diffusers#1917]
**Is your feature request related to a problem? Please describe.**
We have some integration tests for testing training scripts. These were added pre-dreambooth, so we could add some more!

Existing tests: https://github.com/huggingface/diffusers/blob/main/examples/test_examples.py 
CI Call: https://github.com/huggingface/diffusers/blob/19a0ce4a47cf083223a249f7f5d14e9a097f65e6/.github/workflows/push_tests.yml#L145 

**Describe the solution you'd like**
- [x] Collect list of example scripts that could use more testing
- [ ] Determine common flag combinations worth adding tests for
- [x] How e2e do we want to test? Is it worth doing full training runs and adding to nightly? -> we do cpu tests on merge

Status of tested scripts
- [ ] train_dreambooth_flax.py
- [ ] train_dreambooth_lora.py
- [x] train_dreambooth.py
- [ ] train_text_to_image_flax.py
- [ ] train_text_to_image_lora.py
- [x] train_text_to_image.py
- [ ] textual_inversion_flax.py
- [x] textual_inversion.py
- [x] train_unconditional.py

**Comment by williamberman** [comment]
cc @anton-l

**Comment by patrickvonplaten** [comment]
Partly solved by: https://github.com/huggingface/diffusers/pull/2289

**Comment by williamberman** [comment]
> Partly solved by: #2289

Nice! Updated PR description with list of scripts already tested and to note that we don't need full training runs on nightly :)
