### ISSUE TITLE
diffusers_training_example.ipynb uses `init_git_repo` which is not defined

### ISSUE THREAD

**Issue by murphyk** [huggingface/diffusers#1922]
### Describe the bug

https://colab.sandbox.google.com/github/huggingface/notebooks/blob/main/diffusers/training_example.ipynb#scrollTo=b11ba8b7-eb8f-4e8e-88ae-6e4a2b68433e
contains the line 
```
from diffusers.hub_utils import init_git_repo, push_to_hub
```
which fails ('init_git_repo` not defined). 

[Also, `config.push_to_hub` should probably be set to False by default]

### Reproduction

Just run https://colab.sandbox.google.com/github/huggingface/notebooks/blob/main/diffusers/training_example.ipynb#scrollTo=b11ba8b7-eb8f-4e8e-88ae-6e4a2b68433e

### System Info

- `diffusers` version: 0.10.2
- Platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.31
- Python version: 3.9.13
- PyTorch version (GPU?): 1.12.0+cu116 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.20.1
- Using GPU in script?: P6000
- Using distributed or parallel set-up in script?: no

**Comment by anton-l** [comment]
Hi @murphyk! This is now fixed in the updated training notebook :) (https://github.com/huggingface/notebooks/pull/298)
