### ISSUE TITLE
Converting SafeTensor files to diffusers

### ISSUE THREAD

**Issue by dblunk88** [huggingface/diffusers#1928]
There's a way to convert ckpt files to diffusers, but do not seem to see a way to do so for SafeTensor files.

Additionally, is there a way to run just the SafeTensor files by itself? If it needs additional files, maybe we could introduce a way to apply some default files off of them. I am assuming that most current models are based off of SD 1.4 or SD 1.5, and we could either set a flag or automate to transfer over those settings by default.

If there is a way to run SafeTensors directly, then it probably needs some documentation (was not able to find any)

**Comment by camenduru** [comment]
Maybe this helps https://huggingface.co/spaces/camenduru/converter

**Comment by dblunk88** [comment]
> Maybe this helps https://huggingface.co/spaces/camenduru/converter

It does! Although kind of a roundabout way.
safetensor to ckpt to diffusers
would be great to have just a safetensor to diffusers

Although for the time being, I'll use this. Thanks for the link <3

**Comment by camenduru** [comment]
I think this can do safetensors to diffusers https://huggingface.co/spaces/safetensors/convert

**Comment by patrickvonplaten** [comment]
@dblunk88 ,

Could you check this: https://huggingface.co/spaces/diffusers/sd-to-diffusers/discussions/1#63bd7b07bb80ec4ef148ea6b

Also here a PR to try it natively with `diffusers`: https://github.com/huggingface/diffusers/pull/1989

@dblunk88 could you check if this works?

**Comment by dblunk88** [comment]
> @dblunk88 ,
> 
> Could you check this: https://huggingface.co/spaces/diffusers/sd-to-diffusers/discussions/1#63bd7b07bb80ec4ef148ea6b
> 
> Also here a PR to try it natively with `diffusers`: #1989
> 
> @dblunk88 could you check if this works?

Have yet to check it, let me take a look tomorrow 🙂 thanks for the PR
