### ISSUE TITLE
CLIP Guided Image2Image

### ISSUE THREAD

**Issue by dblunk88** [huggingface/diffusers#1929]
The CLIP guided text2img is pretty good. Would be nice to be able to use it for img2img

**Comment by akshay-babbar** [comment]
Hi @patrickvonplaten , since it will be my first issue ever, i will be happy to take this up if someone can guide me.
Can this be assigned to me?

**Comment by patrickvonplaten** [comment]
Hey @akshay-babbar,

sure would you like to open a PR for it?

**Comment by akshay-babbar** [comment]
Yes @patrickvonplaten i would like to, but from the above , it is not clear to me what needs to be done exactly? Can you explain?

**Comment by patrickvonplaten** [comment]
Hey @akshay-babbar,

The goal here is to make a community pipeline (see: https://github.com/huggingface/diffusers/issues/841) 
that does img2img and is guided by CLIP, so quite similar to: https://github.com/huggingface/diffusers/blob/main/examples/community/clip_guided_stable_diffusion.py

**Comment by akshay-babbar** [comment]
Sure @patrickvonplaten , will be a good learning for me, can you assign this to me?

**Comment by patil-suraj** [comment]
Hey @akshay-babbar thanks, just assigned it to you, let me know if you need any help :)

**Comment by akshay-babbar** [comment]
Thanks @patil-suraj

**Comment by yixuanren** [comment]
Hi may I ask any update here?

**Comment by nipunjindal** [comment]
Hello @patrickvonplaten,

I'd like to take it up and raise a PR.
Before moving ahead can you clarify my understanding, I'd have a add another pipeline in the community (as suggested in #841) with additional CLIP guidance? 
For the Img2Img pipeline, do I inherit from https://github.com/huggingface/diffusers/blob/v0.14.0/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L93 or should I duplicate the code and mark duplicate as I read on other threads.

Would love to get clarification to enable faster convergence.

**Comment by akshay-babbar** [comment]
Hey @patil-suraj, Sorry but I was/am keeping busy, so could not get back to this. So for now please feel free to assign this issue to someone else.
Thanks.

**Comment by nipunjindal** [comment]
Hello @patil-suraj @patrickvonplaten,

Here is the PR(https://github.com/huggingface/diffusers/pull/2723) for CLIP guidance for Img2Img pipeline. Let me know your thoughts.

**Comment by nipunjindal** [comment]
Hello @patil-suraj @patrickvonplaten,

Sorry for the ping, were you able to take a look at the PR and would you have some initial comments?

**Comment by patrickvonplaten** [comment]
Merged! Well done, looks great!

**Comment by dblunk88** [comment]
wohoo! Awesome work! Thank you for the awesome feature
