### ISSUE TITLE
Fix PNDMScheduler docstring 

### ISSUE THREAD

**Issue by Warvito** [huggingface/diffusers#1933]
In the PNDM docstring it is saying that the `prediction_type` argument could be `epsilon` , `sample` or `v_prediction`.

https://github.com/huggingface/diffusers/blob/247b5feea125c6933384c59dcfd6d286c71dd8ba/src/diffusers/schedulers/scheduling_pndm.py#L87

But in the step method, it raises an error if we use `sample`

https://github.com/huggingface/diffusers/blob/247b5feea125c6933384c59dcfd6d286c71dd8ba/src/diffusers/schedulers/scheduling_pndm.py#L376

and says that it can only use epsilon or v_prediction

https://github.com/huggingface/diffusers/blob/247b5feea125c6933384c59dcfd6d286c71dd8ba/src/diffusers/schedulers/scheduling_pndm.py#L380

Consider remove the `sample` mention in the class docstring

**Comment by patrickvonplaten** [comment]
Hey @Warvito,

Thanks for the issue, you're 100% correct. Would you mind opening an issue for it? :-)
