### ISSUE TITLE
Unable to load custom pipeline for UnCLIP pipeline

### ISSUE THREAD

**Issue by ethansmith2000** [huggingface/diffusers#1941]
### Describe the bug

had been frequently using a custom pipeline for Karlo that now fails to load as of yesterday. 

using:   pipe = UnCLIPPipeline.from_pretrained("kakaobrain/karlo-v1-alpha",custom_pipeline="./karlo")

which gives

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py in hf_raise_for_status(response, endpoint_name)
    238     try:
--> 239         response.raise_for_status()
    240     except HTTPError as e:

~/.local/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
   1020         if http_error_msg:
-> 1021             raise HTTPError(http_error_msg, response=self)
   1022 

HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/kakaobrain/karlo-v1-alpha/resolve/main/diffusion_pytorch_model.bin

The above exception was the direct cause of the following exception:

EntryNotFoundError                        Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/diffusers/modeling_utils.py in _get_model_file(cls, pretrained_model_name_or_path, weights_name, subfolder, cache_dir, force_download, proxies, resume_download, local_files_only, use_auth_token, user_agent, revision)
    599                 # Load from URL or cache if already cached
--> 600                 model_file = hf_hub_download(
    601                     pretrained_model_name_or_path,

~/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py in _inner_fn(*args, **kwargs)
    123 
--> 124         return fn(*args, **kwargs)
    125 

~/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py in hf_hub_download(repo_id, filename, subfolder, repo_type, revision, library_name, library_version, cache_dir, user_agent, force_download, force_filename, proxies, etag_timeout, resume_download, token, local_files_only, legacy_cache_layout)
   1066             try:
-> 1067                 metadata = get_hf_file_metadata(
   1068                     url=url,

~/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py in _inner_fn(*args, **kwargs)
    123 
--> 124         return fn(*args, **kwargs)
    125 

~/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py in get_hf_file_metadata(url, token, proxies, timeout)
   1375     )
-> 1376     hf_raise_for_status(r)
   1377 

~/.local/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py in hf_raise_for_status(response, endpoint_name)
    256             )
--> 257             raise EntryNotFoundError(message, response) from e
    258 

EntryNotFoundError: 404 Client Error. (Request ID: Root=1-63b88711-2bc2320b527fa70524f93aa8)

Entry Not Found for url: https://huggingface.co/kakaobrain/karlo-v1-alpha/resolve/main/diffusion_pytorch_model.bin.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-6-ad11e6990790> in <module>
----> 1 pipe = UnCLIPPipeline.from_pretrained("kakaobrain/karlo-v1-alpha",custom_pipeline="./karlo")
      2 pipe.to("cuda")
      3 pipe.clip_model = transformers.CLIPVisionModelWithProjection.from_pretrained("openai/clip-vit-large-patch14").to("cuda")
      4 pipe.feature_extractor = transformers.CLIPFeatureExtractor.from_pretrained("openai/clip-vit-large-patch14")

~/.local/lib/python3.8/site-packages/diffusers/pipeline_utils.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    727 
    728         # 5. Instantiate the pipeline
--> 729         model = pipeline_class(**init_kwargs)
    730 
    731         if return_cached_folder:

~/.cache/huggingface/modules/diffusers_modules/local/pipeline.py in __init__(self, prior, decoder, text_encoder, tokenizer, text_proj, super_res_first, super_res_last, prior_scheduler, decoder_scheduler, super_res_scheduler, clip_model, img_feature_extractor)
    251         )
    252 
--> 253         self.text_proj = UnCLIPTextProjModel.from_pretrained("kakaobrain/karlo-v1-alpha")
    254 
    255     def prepare_latents(self, shape, dtype, device, generator, latents, scheduler):

~/.local/lib/python3.8/site-packages/diffusers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    450                 pass
    451         if model_file is None:
--> 452             model_file = cls._get_model_file(
    453                 pretrained_model_name_or_path,
    454                 weights_name=WEIGHTS_NAME,

~/.local/lib/python3.8/site-packages/diffusers/modeling_utils.py in _get_model_file(cls, pretrained_model_name_or_path, weights_name, subfolder, cache_dir, force_download, proxies, resume_download, local_files_only, use_auth_token, user_agent, revision)
    627                 )
    628             except EntryNotFoundError:
--> 629                 raise EnvironmentError(
    630                     f"{pretrained_model_name_or_path} does not appear to have a file named {weights_name}."
    631                 )

OSError: kakaobrain/karlo-v1-alpha does not appear to have a file named diffusion_pytorch_model.bin.

However, I am still able to load the original pipeline with just:
pipe = UnCLIPPipeline.from_pretrained("kakaobrain/karlo-v1-alpha")

it appears to be treating the load from HF differently 

### Reproduction

see above

### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.11.1
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.9.15
- PyTorch version (GPU?): 1.13.1 (True)
- Huggingface_hub version: 0.11.0
- Transformers version: 4.26.0.dev0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

Additionally on cloud GPU

--------------------------------------------------------------------------
WARNING: No preset parameters were found for the device that Open MPI
detected:

  Local host:            132-145-140-55
  Device name:           mlx5_0
  Device vendor ID:      0x02c9
  Device vendor part ID: 4126

Default device parameters will be used, which may result in lower
performance.  You can edit any of the files specified by the
btl_openib_device_param_files MCA parameter to set values for your
device.

NOTE: You can turn off this warning by setting the MCA parameter
      btl_openib_warn_no_device_params_found to 0.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           132-145-140-55
  Local device:         mlx5_0
  Local port:           1
  CPCs attempted:       udcm
--------------------------------------------------------------------------
/home/ubuntu/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.11.1
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.12.1 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
Hey @ethansmith2000,

Note that community pipelines should **not** be loaded as follows:

```python
pipe = UnCLIPPipeline.from_pretrained("kakaobrain/karlo-v1-alpha",custom_pipeline="./karlo")
```

but rather:

```python
pipe = DiffusionPipeline.from_pretrained("kakaobrain/karlo-v1-alpha",custom_pipeline="./karlo")
```

See maybe here: https://github.com/huggingface/diffusers/issues/841 for more information.

**Comment by ethansmith2000** [comment]
Thank you for your help Patrick!
