### ISSUE TITLE
Errors while trying to train a custom model using the tutorial within the diffusers>examples>dreambooth

### ISSUE THREAD

**Issue by tushar-31093** [huggingface/diffusers#1949]
### Describe the bug

![image](https://user-images.githubusercontent.com/40886260/211196455-01599b94-b3b3-42e6-ad5a-01e48a9cd048.png)
![image](https://user-images.githubusercontent.com/40886260/211196661-673a5bc1-9363-48a1-813a-ff49950a73e6.png)

NameError: name 'str2 optimizer 8bit blockwise' is not defined

Literally followed the steps one after the other

### Reproduction

Just follow the same steps but for the server  use AWS EC2 g4dn.2xlarge instance with Ubuntu 20.*

### System Info

- `diffusers` version: 0.12.0.dev0
- Platform: Linux-5.15.0-1022-aws-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 0.15.0
- Accelerate version: not installed - It is installed. Attached an image below
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

![image](https://user-images.githubusercontent.com/40886260/211196714-b95da0e4-3110-4f4e-9e8f-52d652f1a078.png)

**Comment by patrickvonplaten** [comment]
Hey @tushar-31093,

This seems to be a bug with bitsandbytes and your specific hardware. Could you maybe file an issue there: https://github.com/facebookresearch/bitsandbytes?
