### ISSUE TITLE
stable diffusion inference

### ISSUE THREAD

**Issue by westnight** [huggingface/diffusers#1952]
Here is the command when testing the stable diffusion inference:
python3 scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms --config configs/Inference/v2-inference.yaml --ckpt 768-v-ema.ckpt
768-v-ema.ckpt is downloaded from https://huggingface.co/stabilityai/stable-diffusion-2/tree/main
but the output image is not good, like
![image](https://user-images.githubusercontent.com/32773215/211267204-1a806d35-44da-4ffe-b295-eefe8eb1a93d.png)

can anyone please figure out what's wrong?

**Comment by patrickvonplaten** [comment]
Hey @westnight,

I think this is the wrong repo. You can find the correct repo to post this issue here: https://github.com/CompVis/stable-diffusion
