### ISSUE TITLE
Custom pipelines are downloaded even though present locally

### ISSUE THREAD

**Issue by chris-aeviator** [huggingface/diffusers#1955]
### Describe the bug

When adding a custom pipeline to the `examples/community` folder and installing my local diffusers via `pip3 install -e .` diffusers still tries to download the pipeline from HF hub.

### Reproduction

see above

### System Info

diffusers@aba2a65d6ab47c0d1c12fa47e9b238c1d3e34512
python 3.9

**Comment by patrickvonplaten** [comment]
Sorry I don't fully understand the problem here? Could you add a reproducible code snippet?

**Comment by chris-aeviator** [comment]
> Community pipelines are summarized in the [community examples folder](https://github.com/huggingface/diffusers/tree/main/examples/community)
> …
> Here the custom_pipeline argument should consist simply of the filename of the community pipeline excluding the .py suffix, 

I expected the custom_pipeline argument to behave like a lookup for file in the community/examples folder.

No access to the machine currently, roughly:

``
cp examples/community/img2img_inpainting.py examples/community/my_custom_img2img_inpainting.py

## in diffusers
[…]custom_pipeline='my_custom_img2img_inpainting'

`

I've seen now you can reference a local pipeline with an absolute path
