### ISSUE TITLE
colossalai error

### ISSUE THREAD

**Issue by huanzhizun** [huggingface/diffusers#1961]
### Describe the bug

OSError: stable-diffusion-v1-5 does not appear to have a file named tokenizer/config.json. Checkout 

### Reproduction

export MODEL_NAME="stable-diffusion-v1-5"
export INSTANCE_DIR="img"
export OUTPUT_DIR="idp-ysl"

torchrun --nproc_per_node 2 train_dreambooth_colossalai.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=400 \
  --placement="cuda"
~                       

### System Info

- `diffusers` version: 0.7.2
- Platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by haofanwang** [comment]
It seems to not be a problem of ColossalAI.

1. Try transformers==4.25.1
2. Can stable-diffusion-v1-5 be successfully loaded in terminal directly? It is also possible the model is not rightly downloaded to cache because of network connection.
