### ISSUE TITLE
Latent unconditionnal generation

### ISSUE THREAD

**Issue by Kageyoshi317** [huggingface/diffusers#1963]
Hi,
in "https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py" a VQVAE is used so that diffusion is performed on a lower dimensional latent space. I'd like to generate my own data however I found no script to train a personal VQVAE and it is not straightforward to train one because of the backward pass.
Is there a vqvae training script?
Thanks !

**Comment by patrickvonplaten** [comment]
We currently do not have training code for a VAE in `diffusers`. You could have a look at: https://github.com/CompVis/taming-transformers
