### ISSUE TITLE
Support plan for Pytorch 2.0

### ISSUE THREAD

**Issue by haofanwang** [huggingface/diffusers#1964]
**Is your feature request related to a problem? Please describe.**
Although the stable version of Pytorch 2.0 has not been released yet, its new features do improve efficiency with only small modification on training code. Surely, I notice that some functions are re-named in the newer Pytorch.

**Describe the solution you'd like**
Support for Pytorch 2.0 for better computational efficiency. I'm interesting in how `torch.compile` jointly work with diffusers framework. Is it on your development plan?

**Comment by patrickvonplaten** [comment]
Hey @haofanwang,

Good question! We're planning on having full support for `torch.compile` in diffusers and are actively working on getting inference and training scripts to work correctly. 

cc @patil-suraj who is taking the lead here.

**Comment by patrickvonplaten** [comment]
See: https://github.com/huggingface/diffusers/pull/2303
