### ISSUE TITLE
Resnet - Delete dead code

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#197]
There is a lot of dead
code in the file: https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/resnet.py which should be cleaned up, namely:

- Pretty much all code after: https://github.com/huggingface/diffusers/blob/80e0c8ba9ebd7b3ddd82f3e443715d4e7f08f2bb/src/diffusers/models/resnet.py#L389
- All `set_weights` functions

Someone keen on taking this? @anton-l maybe?

**Comment by ydshieh** [comment]
I can take it as a first step, but wondering where do these `set_weight` come from? Copied from the official implementation?

**Comment by patrickvonplaten** [comment]
the `set_weight` come purely from me - I used it to convert checkpoitns on the fly, but we don't need them anymore at all
