### ISSUE TITLE
transformers looking for an incorrect file OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named tokenizer/config.json.

### ISSUE THREAD

**Issue by vmajor** [huggingface/diffusers#1976]
### Describe the bug

transformers 4.24.0 is insisting on trying to find `OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named tokenizer/config.json.`

However this will never happen because the config file is actually `tokenizer_config.json`

### Reproduction

Attempt to run:

`export MODEL_NAME=runwayml/stable-diffusion-v1-5`
 `accelerate launch train_dreambooth.py --pretrained_model_name_or_path=$MODEL_NAME ` 

### System Info

- `diffusers` version: 0.11.1
- Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.0 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.24.0
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by haofanwang** [comment]
Could you try `transformers>=4.25.1`?

**Comment by vmajor** [comment]
OK that changed the error. It also transpires that I pip had installed 4.25.1 but conda installed 4.24.0 so I had two versions installed. I had to uninstall both for the 4.25.1 to be summoned.

Now I have another error and again it seems unusual:

`TypeError: get_scheduler() got an unexpected keyword argument 'num_cycles'`

**Comment by patrickvonplaten** [comment]
@vmajor could you please see: https://github.com/huggingface/diffusers/issues/1817
