### ISSUE TITLE
JAX Attention Refactoring?

### ISSUE THREAD

**Issue by Lime-Cakes** [huggingface/diffusers#1992]
At the moment, pytorch version of most attention had been refactored to use attention processor (except a few being deprecated). Is there plans to do the same for flax version? 

Since AttentionBlock is deprecated, should the same be done to its flax counterpart? 
https://github.com/huggingface/diffusers/blob/9b37ed33b5fa09e594b38e4e6f7477beff3bd66a/src/diffusers/models/attention.py#L32
https://github.com/huggingface/diffusers/blob/9b37ed33b5fa09e594b38e4e6f7477beff3bd66a/src/diffusers/models/attention_flax.py#L19

**Comment by patrickvonplaten** [comment]
cc @pcuenca @patil-suraj 

Are we're using `FlaxAttentionBock` anywhere? Why did we copy it - I think it's not used in Stable Diffusion

**Comment by patil-suraj** [comment]
@patrickvonplaten Yes, it's used for Stabel Diffusion, cf https://github.com/huggingface/diffusers/blob/8a3f0c1f7178f4a3d5a5b21ae8c2906f473e240d/src/diffusers/models/attention_flax.py#L121

**Comment by patil-suraj** [comment]
@pcuenca, would you like to take this one? happy to take it if you are busy?

**Comment by pcuenca** [comment]
@patil-suraj sure, I can take a look tomorrow

**Comment by Lime-Cakes** [comment]
Any update? We should at least put a deprecation warning on FlaxAttentionBlock, right?

**Comment by pcuenca** [comment]
I'm taking a look today. Sorry for being so slow!
