### ISSUE TITLE
[Test] Test the resnet class

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#200]
We should write tests for the resnet class: https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/resnet.py

**Comment by ydshieh** [comment]
@patrickvonplaten Do you have any thought on what the test should look like. It contains building blocks, unlike what we have in `transformers` (where we test the tope level **models**). 

I guess we can test what have been imported in other model files that are used as models in diffusion process.

**Comment by patrickvonplaten** [comment]
IMO, lots of shape tests and some hardcoded integration tests with random weights for the different configurations. 

Maybe @anton-l and @patil-suraj have some nice ideas here as well :-)

**Comment by patrickvonplaten** [comment]
ping again to @anton-l and @patil-suraj here

**Comment by patil-suraj** [comment]
We should at least have following tests IMO

- check if it takes expected input and output shape is also as expected.

Integration test for different configurations, listing out the important ones
- `conv_shortcut`
- `up` and `down`
- `use_nin_shortcut`
- `kernel`

**Comment by patrickvonplaten** [comment]
Not super urgent IMO - but let's not forget. Assigning @anton-l here (hope that's ok - no need to do it asap, but it'd be nice to do it eventually).

Will also be very helpful to compare JAX against PyTorch

**Comment by hchings** [comment]
Hi @patrickvonplaten, I went ahead and added tests for the resnet class for key configs @patil-suraj mentioned.
I haven't added tests for comparing against JAX but happy to do that. Should I add it to the same file or any cleaner way to do this? We might also want a separate `test_layer_utils_flax.py` for `resnet_flax.py`.

**Comment by patil-suraj** [comment]
Awesome @hchings , will take a look at the PR.

**Comment by patil-suraj** [comment]
I think it's okay to not have flax tests at the moment. wdyt @patrickvonplaten ?

**Comment by patrickvonplaten** [comment]
Yes think it's totally fine to not have flax tests yet

**Comment by sayakpaul** [comment]
https://github.com/huggingface/diffusers/pull/1850 is merged so closing this.
