### ISSUE TITLE
[Tests] Test attention class

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#201]
Test attention class: https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention.py

We should test this class well

**Comment by rashmimarganiatgithub** [comment]
@patrickvonplaten , And this also please assign to me?

**Comment by patrickvonplaten** [comment]
Sure :-) Feel free to open a PR for it and others that are interested can directly jump in

**Comment by sidthekidder** [comment]
I started a PR for this issue. Hope @rashmimarganiatgithub doesn't mind me jumping in, I was looking for an easier testing issue!

**Comment by rashmimarganiatgithub** [comment]
@sidthekidder , Please go ahead. I will take other issues.

**Comment by sayakpaul** [comment]
Closing because of https://github.com/huggingface/diffusers/pull/368
