### ISSUE TITLE
How to do fp16 finetuning for dreambooth inpainting?

### ISSUE THREAD

**Issue by shileims** [huggingface/diffusers#2018]
Hi @thedarkzeno and @patil-suraj 
     Thanks for your excellent work on dream booth inpainting.
     My question is that how to perform fp16 dreambooth inpainting fine-tuning?

**Comment by patil-suraj** [comment]
Hey @shileims you can configure accelerate to use mixed precision, use `accelerate config` and it'll ask you bunch of question when it asks about mixed precision, choose `fp16`. Or you could also just pass `--mixed_precision="fp16"` as an argument to the script.

**Comment by AmericanPresidentJimmyCarter** [comment]
As far as I can tell, there is no code in this repo to train an inpainting/outpainting model like the RunwayML model.

**Comment by AmericanPresidentJimmyCarter** [comment]
Update: there is a training script for inpainting here based off of the ones from diffusers

https://github.com/devilismyfriend/StableTuner/blob/main/scripts/trainer.py

**Comment by patil-suraj** [comment]
thank you for sharing!
