### ISSUE TITLE
[Test] Add tests for unet_blocks file

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#202]
https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_blocks.py needs tests

**Comment by John-Poulos** [comment]
Hello, I am a comp sci student and would like to assist, can you give me more information about what tests you are looking for? The link for the testing documentation in the contributing.md is returning a 404 error: https://huggingface.co/docs/diffusers/testing
Thanks in advance!

**Comment by patrickvonplaten** [comment]
Ah yeah we don't have testing docs yet :-/ In short we would just need some test similar to what we've done here: https://github.com/huggingface/diffusers/blob/main/tests/test_layers_utils.py but for all unet blocks. I think in a first step we should:

- Create a general `UNetBlockTesterMixin` in its own file, called `test_unet_blocks.py`
- Test just for shape and output correctness, so maybe you could create a `Class UNetBlockTesterMixin` in the same spirit as: https://github.com/huggingface/diffusers/blob/07f8ebd543fa36b2ec5bfcc80d56eadb308b47f5/tests/test_modeling_common.py#L27 and then we create a bunch of test classes in `test_unet_blocks.py` that inherit from this class

Also cc @anton-l

**Comment by hchings** [comment]
Hi @patrickvonplaten  (and cc @anton-l) - I've added a PR for 2D Unet blocks with a few questions. 
Please take a look, thanks!

**Comment by hchings** [comment]
Hi @patrickvonplaten ^ Can I get some feedback from you for https://github.com/huggingface/diffusers/pull/1945 so I can wrap this PR up?  Thanks~

**Comment by patrickvonplaten** [comment]
Hey @hchings, 

Sure! I left some comments on #1945 :-)

**Comment by sayakpaul** [comment]
Closing because of https://github.com/huggingface/diffusers/pull/1945
