### ISSUE TITLE
choice of prior preservation images when training a style with dreambooth 

### ISSUE THREAD

**Issue by chesha1** [huggingface/diffusers#2023]
When using dreambooth, it is recommended that offering more regularization images to reduce overfitting and language drift. If you want to train a object, for example, a certain type of dog, you will easily find many images of dogs to be treated as prior preservation images.
However, if you want to train a style, how can you find a large class containing the style wanted? It is hard to say one style belongs to what another style. If there definely exists a large class, those two classes are so different that model is hard to learn semantic information from them.
Are there any techniques about choosing prior preservation images?

**Comment by patrickvonplaten** [comment]
cc @patil-suraj

**Comment by patil-suraj** [comment]
Hey @chesha1 , prior preservation acts as a regularizer during training, so if the images of the same class are unavailable, we can use images closer to the concept we want to train. For example, for style training, we could generate images using existing styles and use those for prior preservation. Even if those doesn't belong to our style it should still work. There is a dataset [here](https://huggingface.co/datasets/ProGamerGov/StableDiffusion-v1-5-Regularization-Images) which provides prior images for different concepts, and a lot of users have trained style models using such prior images and it seems to work really well.

**Comment by chesha1** [comment]
> Hey @chesha1 , prior preservation acts as a regularizer during training, so if the images of the same class are unavailable, we can use images closer to the concept we want to train. For example, for style training, we could generate images using existing styles and use those for prior preservation. Even if those doesn't belong to our style it should still work. There is a dataset [here](https://huggingface.co/datasets/ProGamerGov/StableDiffusion-v1-5-Regularization-Images) which provides prior images for different concepts, and a lot of users have trained style models using such prior images and it seems to work really well.

Thanks for reply.
