### ISSUE TITLE
Textual Inversion Training notebook: "The file has been corrupted or is not a valid notebook file."

### ISSUE THREAD

**Issue by CptanPanic** [huggingface/diffusers#2024]
### Describe the bug

I try to open the training notebook on linked at https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/README.md colab to https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_textual_inversion_training.ipynb
 

```
SyntaxError: JSON.parse: unexpected character at line 41 column 7 of the JSON data
Fb@https://ssl.gstatic.com/colaboratory-static/common/7e353f7d5d304439541daef59a502dce/external_polymer_binary.js:90:515
qK@https://ssl.gstatic.com/colaboratory-static/common/7e353f7d5d304439541daef59a502dce/external_polymer_binary.js:2476:164
nK/<@https://ssl.gstatic.com/colaboratory-static/common/7e353f7d5d304439541daef59a502dce/external_polymer_binary.js:2459:505
Aa@https://ssl.gstatic.com/colaboratory-static/common/7e353f7d5d304439541daef59a502dce/external_polymer_binary.js:21:57
ya.prototype.next_@https://ssl.gstatic.com/colaboratory-static/common/7e353f7d5d304439541daef59a502dce/external_polymer_binary.js:19:195
Ca/this.next@https://ssl.gstatic.com/colaboratory-static/common/7e353f7d5d304439541daef59a502dce/external_polymer_binary.js:22:47
b@https://ssl.gstatic.com/colaboratory-static/common/7e353f7d5d304439541daef59a502dce/external_polymer_binary.js:22:307
```

### Reproduction

just opening it

### System Info

google colab

**Comment by pcuenca** [comment]
Hi @CptanPanic! The training notebook loads for me using the following URL (which I took from the README):
https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/training_example.ipynb

Are you using a different notebook?

**Comment by ForceConstant** [comment]
@pcuenca ok yes that one works. The one I was trying, and seems to be linked around the internet, is the "colab" link in https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/README.md which goes to https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_textual_inversion_training.ipynb

**Comment by CptanPanic** [comment]
Yes sorry I wasn't clear, but I was talking about the textual inversion colab. I didn't realize there were different notebooks in this repo.

**Comment by pcuenca** [comment]
Fixed, can you please try again?

**Comment by CptanPanic** [comment]
yes works. Thanks.
