### ISSUE TITLE
Write a doc for centralizing our LoRA efforts

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#2028]
Currently, we have incoming support for LoRA to fine-tune with [DreamBooth](https://github.com/huggingface/diffusers/pull/1884) and [Text2Image](https://github.com/huggingface/diffusers/pull/2002). 

These things enable the community to run fine-tuning on consumer GPUs which is a big enabling factor for many use cases. 

So with that, I think it's important to put together a doc highlighting these efforts. This doc could live under https://github.com/huggingface/diffusers/tree/main/docs/source/en/training (as suggested by @patil-suraj). 

I will start working on this doc next week. If anyone has any suggestions, feel free to comment. Opening this issue thread so that things don't get slipped through the cracks.

**Comment by brucethemoose** [comment]
While its for a completely different implementation, I noticed some helpful bits in this: https://rentry.org/lora_train

For instance:
- A note that network_dim has a significant influence on model quality
- A simple image showing the directory structure for training data: https://i.imgur.io/zpbs8FB_d.webp?maxwidth=640&shape=thumb&fidelity=medium
- A minimal vram consumption example config.
- Sane recommendations for number of epochs, LR and such.

**Comment by sayakpaul** [comment]
Thanks so much for the suggestions! I will definitely keep all these in mind :)
