### ISSUE TITLE
Add noise interpolation and text intertpolation scripts to examples

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#205]
Noise and text embedding interpolation scripts like @karpathy's [stable-diffusion-walk](https://gist.github.com/karpathy/00103b0037c5aaea32fe1da1af553355) are very nice to make artistic designs / videos and are relatively easy to add. We could add them under https://github.com/huggingface/diffusers/tree/main/examples to make it more available to the community

**Comment by danielpatrickhug** [comment]
Hi @patrickvonplaten, I've been working and modifying a copy of this script every day for the past 3 weeks. I would be happy to help add it! would you like a colab notebook with added video creation from generated frames? "Dream Seam" or as the exact .py file from Karpathy's repo?

**Comment by patrickvonplaten** [comment]
Very cool! Should we make it a community notebook (and add it under https://github.com/huggingface/diffusers/tree/main/examples/community - it'd be the first one :partying_face: )

**Comment by danielpatrickhug** [comment]
Sure! I'll make a pull request to add the notebook to the community folder. The notebook is completely self-contained and should operate on the free version of google Colab - I've only tested it twice on the free version. I'll do my best to keep it up to date as the diffusers library updates.

**Comment by sayakpaul** [comment]
Closong because of https://github.com/huggingface/diffusers/pull/518.
