### ISSUE TITLE
Add some documentation to the StableDiffusionImg2Img Pipeline tensor input format

### ISSUE THREAD

**Issue by brucethemoose** [huggingface/diffusers#2061]
So I was trying to feed the stablediffusionimg2imgpipeline with a video frame turned into torch tensor instead of a PIL image as is typical, and I was... struggling with garbled output, until I *eventually* found this bit in the code:
 https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L86

I think the docs should mention the raw input image tensor should be in the [-1.0:1.0] range, which isn't typical when (for instance) dumping floating point frames from numpy or vapoursynth.

Just a tiny thing. But maybe it will save someone else the trouble.

**Comment by patrickvonplaten** [comment]
+1 on this one. Think we should definitely improve the documentation and the robustness of all models that accept images. 

In short, pipelines that accept images should:
- Be allowed to accept images in multiple formats (PIL, numpy, torch.Tensor)
- Be tested that all inputs give the same results
- We should probably think about a feature extractor class that centralizes all the logic. Don't think we need to make it depend on a config yet, but adding a new class for it would make a lot of sense. 

cc @patil-suraj @williamberman

**Comment by patrickvonplaten** [comment]
We should solve this very soon, this is an important issue. This issue describes in more detail how to solve it: https://github.com/huggingface/diffusers/issues/2304

I will make this a priority for me next week.

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu here as it's related to #2304

**Comment by patrickvonplaten** [comment]
Assigning @yiyixuxu here instead of me

**Comment by sayakpaul** [comment]
I think this has been addressed now. 

Cc: @stevhliu to confirm if this is the case.

**Comment by pcuenca** [comment]
The expected range is indeed `[0, 1]`, this was standardized a while ago. The VAE works in the `[-1, 1]` range, but the conversion is performed [here](https://github.com/huggingface/diffusers/blob/069186fac510d6f6f88a5e435523b235c823a8a0/src/diffusers/image_processor.py#L703). Passing images in the `[-1, 1]` range would also work, but it's deprecated now.
