### ISSUE TITLE
How to create videos with Stable Diffusion with high temporal cohesion?

### ISSUE THREAD

**Issue by pauldog** [huggingface/diffusers#2063]
I've been trying to work out how this is done?

https://www.youtube.com/watch?v=StpTUnYbxBg
https://www.youtube.com/watch?v=7ieodV1cvag

I can slowly change the latent space random noise to get slightly different images with a few jumps.
But I don't understand how this guy does the transformations as well such as rotations and zooms of the image.
How does he get such temporal cohesion between frames?
(Ignoring the fact that there is some extra video frame interpolation going on here.)
You can't do a transformation on Gaussian noise as far as I'm aware / except for a simple translation.
But if you take an image and noise it up and then put it through the SD process again, you don't often end up with quite similar images, especially with guidance set high.

Can this be done in standard Stable Diffusion or is he using some special image-->image version perhaps.

I am trying to work out the algorithms involved.

**Comment by patrickvonplaten** [comment]
Good question @pauldog.

Maybe some helpful links: 
https://github.com/nateraw/stable-diffusion-videos

or feel free to ask question in the diffusers discord as well:
https://discord.gg/G7tWnz98XR
