### ISSUE TITLE
Are all models fully versioned and deterministic? 

### ISSUE THREAD

**Issue by arpowers** [huggingface/diffusers#2082]
Hello everyone,

I wanted to ask about some issues that have been popping up in libraries that use diffusers as a dependency. Specifically, there have been some unexpected changes to the output (check out this video: https://www.youtube.com/watch?v=usgqmQ0Mq7g) and I've also encountered similar problems when using a separate script. The common thread seems to be diffusers, but I haven't been able to figure out the root cause.

I was wondering if diffusers is fully deterministic in terms of version number. Many calls to from_pretrained don't seem to have version information, so I'm assuming they just pull the latest version. Is it possible that unexpected changes could be coming from untracked changes to models in these cases?

Would it make sense to always require a version number when making calls to diffusers to avoid these issues?

**Comment by patrickvonplaten** [comment]
Hey @arpowers,

`diffusers` is supposed to be fully deterministic when loading models. Model weights & configs might change, but we never change them in breaking ways. 
If you want to be 100% sure that nothing can change, we recommend to use a versioned `diffusers` + use `revision="889b629140e71758e1e0006e355c331a5744b4bf"` (or another commit hash, e.g. see: https://huggingface.co/runwayml/stable-diffusion-v1-5/commits/main) 

```python
pipe = DiffusionPipeline.from_pretrained(..., revision=...)
```
