### ISSUE TITLE
Image-to-Image Diffusion Models

### ISSUE THREAD

**Issue by JunMa11** [huggingface/diffusers#2093]
Dear all,

Thanks for the awesome work!

Is there any tutorial about how to train Image-to-Image Diffusion Models (without text guidance)? E.g. palette https://iterative-refinement.github.io/palette/

**Comment by patrickvonplaten** [comment]
I don't know of any at the moment sadly - maybe you can try asking in our discord? :-) 
https://discord.gg/G7tWnz98XR

**Comment by JunMa11** [comment]
Thank you:)
