### ISSUE TITLE
Call to Torch.randn throws: "randn() received an invalid combination of arguments"

### ISSUE THREAD

**Issue by NicholasKao1029** [huggingface/diffusers#2098]
### Describe the bug

When calling the `__call__` method of the stable diffusion pipeline, with a list of generators. (works without list of generators)

An internal call in the diffusers package to torch.randn throws an exception regarding in compatible function stubs. 

I followed these docs 
https://huggingface.co/docs/diffusers/using-diffusers/reusing_seeds

I see this 
https://github.com/huggingface/diffusers/issues/2083
But am wondering what the consequences of upgrading to a dev branch is (currently asking modal team if this is possible)

### Reproduction

First time doing this let me know what is wrong

I am doing this on the modal.com platform 
```
volume = modal.SharedVolume().persist("vol-name")
image = (
    modal.Image.debian_slim()
    .pip_install(
        "accelerate",
        "colorgram.py",
        'diffusers~=0.11.0',
        "ftfy",
        "torch",
        "torchvision",
        "transformers",
        "scipy",
        "safetensors",
        "triton"
    )
    .pip_install("xformers", pre=True)
    .run_function(load_model)
)
stub = modal.Stub(name="service-name", image=image)
```

The setup works fine, but when actually calling the pipeline
```
        request_obj = {
            "prompt":prompts,
            "height":height,
            "width":width,
            "num_inference_steps":steps,
            "guidance_scale":cfg_scale,
            "negative_prompt": negative_prompts,
            "eta":eta,
            "generator":generator_list_from_seeds(all_seeds)
        }

        with torch.inference_mode():
            with torch.autocast("cuda"):
                # call to model here
                images = self.pipe (
                    **request_obj
                ).images
```

From my tests this only happens when I give a list of generators. to try reproduce the seed

### Logs

```shell
colorgram.py-1.2.0-py2.py3-none-any.whl 
diffusers-0.11.1-py3-none-any.whl 
ftfy-6.1.1-py3-none-any.whl 
torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl 
torchvision-0.14.1-cp310-cp310-manylinux1_x86_64.whl 
```
snippet from the docker install, inside of a serverless container on modal.com

And then the error that occurs
```
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 537, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
  File "/usr/local/lib/python3.10/site-packages/diffusers/schedulers/scheduling_euler_discrete.py", line 227, in step
    noise = torch.randn(model_output.shape, dtype=model_output.dtype, device=device, generator=generator).to(
TypeError: randn() received an invalid combination of arguments - got (torch.Size, generator=list, device=torch.device, dtype=torch.dtype), but expected one of:

 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```
```


### System Info

- Platform: Linux-5.13.0-1029-aws-x86_64-with-glibc2.31
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.1+cu117 (False)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.26.0
- Using GPU in script?: Don't think so
- Using distributed or parallel set-up in script?: Do not know

sorry if there are instructions on how I can check the last 2 points let me know

**Comment by patrickvonplaten** [comment]
Hey @NicholasKao1029,

Could you post a **fully reproducible** code snippet? 

I don't think this:

```python
volume = modal.SharedVolume().persist("vol-name")
image = (
    modal.Image.debian_slim()
    .pip_install(
        "accelerate",
        "colorgram.py",
        'diffusers~=0.11.0',
        "ftfy",
        "torch",
        "torchvision",
        "transformers",
        "scipy",
        "safetensors",
        "triton"
    )
    .pip_install("xformers", pre=True)
    .run_function(load_model)
)
stub = modal.Stub(name="service-name", image=image)
```

Is related to `diffusers` at all?

**Comment by NicholasKao1029** [comment]
Yeah thats for the service I'm using, meant it as a reference to packages I'm installing but it can be ignored 

```
import torch
from diffusers import StableDiffusionPipeline
from diffusers.models import AutoencoderKL
import time
import random

def load_sd_model():

    # huggingface id
    model_id = "runwayml/stable-diffusion-v1-5"
    load_start_time = time.time()
    vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse")
    pipe = StableDiffusionPipeline.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        custom_pipeline="lpw_stable_diffusion", # long and attention prompts
        vae=vae,
    )

    def null_safety(images, **kwargs):
        return images, False

    pipe.safety_checker = null_safety

    return pipe

def get_generator_from_seed(seed: int):
    seed = int(seed)
    return torch.Generator(device="cuda").manual_seed(seed)

def generator_list_from_seeds(seeds: list[int]):
    return [get_generator_from_seed(seed) for seed in seeds]

if __name__ == "__main__":
    # This is a test to see if the model loads
    # without errors.
    pipe = load_sd_model()
    batch_size = 2
    request_obj = {
        "prompt":["dog"] * batch_size,
        "height": 512,
        "width": 512,
        "num_inference_steps":1,
        "guidance_scale":7.5,
        "negative_prompt": [""] * batch_size,
        "eta":1,
        "generator":generator_list_from_seeds([i for i in range(batch_size)])
    }

    with torch.inference_mode():
        with torch.autocast("cuda"):
            # call to model here
            images = pipe (
                **request_obj
            ).images

            for i in range(batch_size):
                with open(f't_{i}.png', 'wb') as file:
                    file.write(images[i])

```

let me know if this is good

**Comment by patrickvonplaten** [comment]
Can't run the code as it gives: 

```
    def generator_list_from_seeds(seeds: list[int]):
TypeError: 'type' object is not subscriptable
```

**Comment by NicholasKao1029** [comment]
sorry are you having a problem with the `generator_list_from_seeds` function seems as it seems to output a list of generators for me
`[<torch._C.Generator object at 0x000001F120CFF0F0>, <torch._C.Generator object at 0x000001F120E83650>]`

**Comment by mustang651** [comment]
I have similar problem with my simple setup:
`pipe = DiffusionPipeline.from_pretrained(model_id, custom_pipeline="lpw_stable_diffusion", torch_dtype=torch.float16)
pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)
pipe.vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse", torch_dtype=torch.float16).to(device)
pipe=pipe.to(device)

def get_inputs(batch_size=1):
    generator = [torch.Generator(device).manual_seed(i) for i in range(batch_size)]
    prompts = batch_size * [prompt]
    inputs = {"prompt": prompts, "generator": generator, "width": width, "height": height, "num_inference_steps": steps}
    seeds = [gen.seed() for gen in generator]
    return inputs, seeds

inputs, seeds = get_inputs(number_images)

images = pipe(**inputs).images`

It runs well without custom_pipeline="lpw_stable_diffusion" but gives me an error with it. What am I doing wrong?
The error:
`Token indices sequence length is longer than the specified maximum sequence length for this model (92 > 77). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "D:\somedir\txt2img\StableDiffusion.py", line 64, in <module>
    images = pipe(**inputs).images
             ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.cache\huggingface\modules\diffusers_modules\git\lpw_stable_diffusion.py", line 807, in __call__
    latents, init_latents_orig, noise = self.prepare_latents(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.cache\huggingface\modules\diffusers_modules\git\lpw_stable_diffusion.py", line 640, in prepare_latents
    latents = torch.randn(shape, generator=generator, device=device, dtype=dtype)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: randn() received an invalid combination of arguments - got (tuple, generator=list, dtype=torch.dtype, device=torch.device), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)`
