### ISSUE TITLE
How can I use `*.safetensors` modles in `diffusers` library?

### ISSUE THREAD

**Issue by Yiximail** [huggingface/diffusers#2105]
I found a really great model a few days ago. Then I wanted to use it on a pure API server (without webui or other Gradio interface)
Here is the model's path in huggingface: [WarriorMama777/OrangeMixs](https://huggingface.co/WarriorMama777/OrangeMixs)

And I mainly refer to these two demos:
[conditional_image_generation](https://huggingface.co/docs/diffusers/v0.11.0/en/using-diffusers/conditional_image_generation)
[stable-diffusion-v1-5](https://huggingface.co/runwayml/stable-diffusion-v1-5)

``` python
from diffusers import DiffusionPipeline
# I also tried it in StableDiffusionPipeline

pipe  = DiffusionPipeline.from_pretrained("WarriorMama777/OrangeMixs")
pipe = pipe.to("cuda")
```
Got an error below.
```
OSError: /root/.cache/huggingface/diffusers/models--WarriorMama777--OrangeMixs/snapshots/641d5be1a5f89a040e58f769cac02b328a277467 does not appear to have a file named config.json. Checkout 'https://huggingface.co//root/.cache/huggingface/diffusers/models--WarriorMama777--OrangeMixs/snapshots/641d5be1a5f89a040e58f769cac02b328a277467/None' for available files.
```

Then I tried to download the model first and then load the model path directly.
According to this [`documentation`](https://huggingface.co/docs/diffusers/v0.11.0/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.from_pretrained), `from_pretrained` should be able to accept the model path.
``` python
from diffusers import DiffusionPipeline
pipe = DiffusionPipeline.from_pretrained("/content/AbyssOrangeMix2_nsfw.safetensors")
```
Error again.
```
OSError: It looks like the config file at '/content/AbyssOrangeMix2_nsfw.safetensors' is not a valid JSON file.
```

After comparing [`runwayml/stable-diffusion-v1-5`](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main) with [`WarriorMama777/OrangeMixs`](https://huggingface.co/WarriorMama777/OrangeMixs/tree/main).
I found that there are multiple folders in the root of stable-diffusion-v1-5: `unet`, `vae`, `tokenizer`...
After reviewing many tutorials and documents, I think these are probably what `diffusers` load, not `*.ckpt` or `*.safetensors`.

Then I looked up how to convert them. And I found `diffusers` has a script.
[convert_original_stable_diffusion_to_diffusers](https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py)

``` python
!git clone https://github.com/huggingface/diffusers.git

!python /content/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py \
 --checkpoint_path /content/AbyssOrangeMix2_nsfw.safetensors \
 --from_safetensors --dump_path /content/model
```
```
Traceback (most recent call last):
  File "/content/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 19, in <module>
    from diffusers.pipelines.stable_diffusion.convert_from_ckpt import load_pipeline_from_original_stable_diffusion_ckpt
ModuleNotFoundError: No module named 'diffusers.pipelines.stable_diffusion.convert_from_ckpt'
```

Here is my test colab notebook: [colab](https://colab.research.google.com/drive/1q0iTdK91ARHchw7YxygvRoa0Q_9J5xnM?usp=sharing)

I am not familiar with python and may ask some basic questions. I have been trying to solve it for the past two days but I still haven't found a solution, so I apologize for any uncomfortable. I would greatly appreciate your help.

**Comment by patrickvonplaten** [comment]
Hey @Yiximail,

Yeah the models of this repo are not at all in the correct format, converted all of them here: https://huggingface.co/OrangeMix

Note that if you'd like to save those under the safetensors format, you can just load and save them, e.g.

```python
from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("OrangeMix/AbyssOrangeMix2")
pipeline.save_pretrained("local_path", safe_serialization=True)
```

cc @Narsil we should maybe add a doc for safetensors :-)

**Comment by Narsil** [comment]
On it: https://github.com/huggingface/diffusers/pull/2122 :)

**Comment by Yiximail** [comment]
Thank you for explaining to me, and the conversion of the model.
