### ISSUE TITLE
Does img2img and txt2img shares same weights of textual encoder?

### ISSUE THREAD

**Issue by YJ-142150** [huggingface/diffusers#2108]
Hi, thanks for your great work.
Does text guided img2img and txt2img shares same textual encoder for conditioning?
I trained stable diffusion on dream booth which fine-tunes txt2img. Does the fine-tune affect text guided img2img's weight, too?

**Comment by patrickvonplaten** [comment]
Hey @YJ-142150,

Every checkpoint that works with txt2img sholud work with img2img . Dreambooth fine-tuning should not affect img2mg's capabilities, it should just change them in the same way Dreambooth changes txt2img from the base to the new model. Hope this makes sense

**Comment by YJ-142150** [comment]
Thanks for answering the question!
