### ISSUE TITLE
Why is there a `permute(2, 0, 1)` in textual_inversion example

### ISSUE THREAD

**Issue by taoisu** [huggingface/diffusers#2115]
Hi @patil-suraj, thanks for the example on textual inversion!

While I was looking at the code, I struggle to understand this line:

```python
example["pixel_values"] = torch.from_numpy(image).permute(2, 0, 1)
```
in textual_inversion.py

The image is already in RGB format, this permute effectively convert the format into BRG format, I'm wondering is this by design?

**Comment by taoisu** [comment]
https://github.com/huggingface/diffusers/blob/946d1cb200a875f694818be37c9c9f7547e9db45/examples/textual_inversion/textual_inversion.py#L422

**Comment by patil-suraj** [comment]
The permute is for to convert the image to `channels_first` first format. `PIL` uses images in channels last format, so when converting the images to pytorch we need to do a permute to bring the channel dim to first dim.

**Comment by taoisu** [comment]
Got it. Thanks for the explanation!
