### ISSUE TITLE
How can I change alpha of LoRA?

### ISSUE THREAD

**Issue by hysts** [huggingface/diffusers#2117]
I'm not that familiar with the implementation detail of LoRA and wondering how I can change alpha in inference time.
I found a field scale here:
https://github.com/huggingface/diffusers/blob/085613733791b4d67be058edcd0bd23da5c3f57c/src/diffusers/models/cross_attention.py#L260
so I though I can change it by implementing something like `tune_lora_scale`  in the original implementation:
https://github.com/cloneofsimo/lora/blob/e19f6ae22c3fa4d6da252c5b7443fc0942088cd7/lora_diffusion/lora.py#L597-L600
but actually it doesn't seem to be used:
https://github.com/huggingface/diffusers/blob/085613733791b4d67be058edcd0bd23da5c3f57c/src/diffusers/models/cross_attention.py#L285
It looks like scale has to be passed as an argument to this module, but how can I do that?

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/pull/2129 should solve it :-)

**Comment by hysts** [comment]
@patrickvonplaten Thank you for the answer and PR!
