### ISSUE TITLE
VRAM usage of inference

### ISSUE THREAD

**Issue by chesha1** [huggingface/diffusers#2133]
What factors influence the VRAM usage? 
I used to thnk it is in linear with the number of pixels of the generated images. But when the image size grows, VRAW usage grows faster. It seems that space complexity is not just O(n). (Supposing that n is the number of pixels of the generated images).

Resolution       VRAM
512 * 512         6.1
768 * 768         12.2
1152 * 1152     43.2

**Comment by patrickvonplaten** [comment]
Hey @chesha1,

Usually the bottleneck of Stable Diffusion is the cross attention layer: https://github.com/huggingface/diffusers/blob/69caa9647201b08119288ab1df6574552635b37e/src/diffusers/models/cross_attention.py#L211

Note that in the cross attention layer we compute the matrix QK^T where as K are the project text embeddings and Q is the flattened pixel sequence which is of length `width x height` as seen here: https://github.com/huggingface/diffusers/blob/69caa9647201b08119288ab1df6574552635b37e/src/diffusers/models/transformer_2d.py#L256

This means the complexity becomes 77 (seq len of text embeddings) * (image_width) * (image_height) which is essentially O(n2)

**Comment by chesha1** [comment]
> Hey @chesha1,
> 
> Usually the bottleneck of Stable Diffusion is the cross attention layer:
> 
> https://github.com/huggingface/diffusers/blob/69caa9647201b08119288ab1df6574552635b37e/src/diffusers/models/cross_attention.py#L211
> 
> Note that in the cross attention layer we compute the matrix QK^T where as K are the project text embeddings and Q is the flattened pixel sequence which is of length `width x height` as seen here:
> 
> https://github.com/huggingface/diffusers/blob/69caa9647201b08119288ab1df6574552635b37e/src/diffusers/models/transformer_2d.py#L256
> 
> This means the complexity becomes 77 (seq len of text embeddings) * (image_width) * (image_height) which is essentially O(n2)

Thanks for your reply.
