### ISSUE TITLE
How to synthesize the files trained by ‘train_dreambooth_lora.py’ into ckpt files?

### ISSUE THREAD

**Issue by kkiqq22** [huggingface/diffusers#2145]
Hello, admirable developer
I used the ‘train_dreambooth_lora.py’ method to train and got the ‘. bin’ file. I need to convert it to ckpt for use in webui,How to convert the bin file to the ckpt file

**Comment by kkiqq22** [comment]
hello?

**Comment by patrickvonplaten** [comment]
Hey @kkiqq22,

Sorry could you post this question on https://github.com/AUTOMATIC1111/stable-diffusion-webui as it refers to this framework? :-)

Otherwise maybe the community has found a nice way to convert it

**Comment by kkiqq22** [comment]
Yes, this is the framework. The files trained with lora are always wrong.
The size of the model file trained by some LORA frameworks is 288mb. Why is the LORA file trained by diffusers only 2-6mb?
ps:288mb ckpt webui is work,2-6mb ckpt webui is not work
