### ISSUE TITLE
[Community Pipeline] Support a texture painting workflow

### ISSUE THREAD

**Issue by Dekker3D** [huggingface/diffusers#2149]
**Is your feature request related to a problem? Please describe.**
The current texture projection setup simply replaces the material on selected faces with a new one, which makes it hard to blend between two textures or only apply specific features of a new texture to an existing one.

**Describe the solution you'd like**
Offer an alternative workflow, probably under a checkbox named "texture painting workflow", where the add-on stores newly generated textures (more than one, possibly, under some sort of selection menu) and slots them into a new "image texture" node in the existing material. It only needs a UV map input pointing at your projected UVs, but if you also add a Principled BSDF and output node, you can easily toggle between a preview of this texture and the original output.

Then, in Texture Painting mode, select the clone brush tool and tell it to paint on the existing texture, using the newly added texture as a source texture. This should set up the user to quickly start painting this new texture onto the existing one. This would be extremely useful for tricky models where you need to add texture bits from various angles, so you need rapid iteration.

**Describe alternatives you've considered**
I'm currently doing all this manually. It's slow, but it works.

**Additional context**
This should probably be read in the context of #2150, which is the other half of my current workflow.

**Comment by patrickvonplaten** [comment]
Should we maybe create a community pipeline for this as explained here: https://github.com/huggingface/diffusers/issues/841 ? :-)

**Comment by Dekker3D** [comment]
Oh man, sorry! I meant to submit this issue on https://github.com/carson-katri/dream-textures

**Comment by patrickvonplaten** [comment]
No worries :-)
