### ISSUE TITLE
Make texture projection work with img2img models

### ISSUE THREAD

**Issue by Dekker3D** [huggingface/diffusers#2150]
**Is your feature request related to a problem? Please describe.**
Right now, texture projection only works with depth2img models.

**Describe the solution you'd like**
An img2img model can do some pretty decent work for texture projection, if you give it an input image with unshaded basic textures... if no such textures are available, a cavity map or ambient occlusion texture will work well if you bump up the denoising strength a fair bit.

**Describe alternatives you've considered**
I'm currently doing this manually in Auto1111.

**Additional context**
This should probably be read in the context of #2149, which is the other half of my current workflow.

**Comment by patrickvonplaten** [comment]
Hey @Dekker3D, can you code up an example that explains your workflow maybe? :-)

**Comment by Dekker3D** [comment]
Sorry! This issue was meant for https://github.com/carson-katri/dream-textures, I messed up.
