### ISSUE TITLE
AutoEncoderKL

### ISSUE THREAD

**Issue by Kageyoshi317** [huggingface/diffusers#2152]
Hello,
AutoencoderKL.latent_channels is 4 by default, how does one interpret 4 channels ? How was this choice motivated? I know we are talking about a low meaningful latent space but I'm trying to understand a bit more about it. Also, are there pre-trained 1 or 3 channel AutoEncoderKL's? 
Thanks in advance

**Comment by patrickvonplaten** [comment]
Hey @Kageyoshi317,

Could you maybe have a look at the original Taming-Transformer paper: https://compvis.github.io/taming-transformers/ this should explain it :-)
