### ISSUE TITLE
RuntimeWarning: invalid value encountered in cast

### ISSUE THREAD

**Issue by cmmalana** [huggingface/diffusers#2153]
Newbie here. I am interested in stable diffusion and wanted to practice and see how it performs. I came across https://github.com/huggingface/diffusers/tree/main#new--stable-diffusion-is-now-fully-compatible-with-diffusers which I followed the code:
```
import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", revision="fp16", torch_dtype=torch.float16, safety_checker=None)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]

image.save("astronaut_rides_horse.png")
```
My issue is I am having this error in terminal and the file "astronaut_rides_horse.png" is only a black image:
Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py:818: RuntimeWarning: invalid value encountered in cast
images = (images * 255).round().astype("uint8")

**Comment by pcuenca** [comment]
Hi @cmmalana! That same code works for me. Would you mind running `diffusers-cli env` and pasting the output from the command? Also, please let us know the GPU you are using. Thank you!

**Comment by cmmalana** [comment]
Hello @pcuenca! I am using a GTX 1660 and here is the output!
- `diffusers` version: 0.12.1
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.9
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Huggingface_hub version: 0.12.0
- Transformers version: 0.15.0
- Accelerate version: not installed
- xFormers version: not installed

**Comment by pcuenca** [comment]
Hi @cmmalana! Unfortunately, I've seen a few reports about people having trouble with the GTX 1660 when using `float16` weights. This appears to be an nVidia issue, see for example this PyTorch thread for more details: https://github.com/pytorch/pytorch/issues/58123

Until the problem is resolved, you might be successful using `float32` instead of `float16`, but then you'll need to save some memory because 6 GB of VRAM won't be enough to run Stable Diffusion with default settings.

First, I'd recommend you use sequential CPU offloading, which only copies the active model to GPU memory (instead of moving them all at once). You'd do it like this:

```Python
import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", safety_checker=None)
# pipe = pipe.to("cuda")
pipe.enable_sequential_cpu_offload()

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]

image.save("astronaut_rides_horse.png")
```

**IMPORTANT**: in this configuration you don't have to move the pipeline to `cuda`.

If this still runs out of memory, then you can enable attention slicing, like this:

```Python
import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", safety_checker=None)
# pipe = pipe.to("cuda")
pipe.enable_sequential_cpu_offload()
pipe.enable_attention_slicing("max")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]

image.save("astronaut_rides_horse.png")
```

(If that works, then you can try to skip the `"max"` argument and see if it still does).

Note that inference will be slower when using `float32`, but at least I think you should be able to generate images this way. Please, do let us know if that works!

**Comment by cmmalana** [comment]
Hello again @pcuenca I wanna say thank you since I have now been able to generate an image even without the help of attention slicing. Again, thank you so much!

**Comment by mohammadmi19** [comment]
Where is the file location that’s need to be changed?

**Comment by pcuenca** [comment]
Hi @mohammadmi19. These instructions are appropriate for the `diffusers` library, and meant to be used with Python code. If you are using a web UI, then you'd need to ask the authors of that UI as it's unrelated to diffusers. Sorry about that, but we can't help with software we don't know :)

**Comment by mohammadmi19** [comment]
I’m using the local file if that’s what u mean…

**Comment by liuxz-cs** [comment]
> diffusers-cli env

Hello, I have meet the same problem when run my code in V100, and the diffusers-cli results are as follows, how to solve this problem?

```
Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.14.0
- Platform: Linux-4.14.0_1-0-0-32-x86_64-with-glibc2.10
- Python version: 3.8.0
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.27.3
- Accelerate version: 0.18.0
- xFormers version: 0.0.17+5eb0dbf.d20230829
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

**Comment by liuxz-cs** [comment]
> Hi @cmmalana! Unfortunately, I've seen a few reports about people having trouble with the GTX 1660 when using `float16` weights. This appears to be an nVidia issue, see for example this PyTorch thread for more details: [pytorch/pytorch#58123](https://github.com/pytorch/pytorch/issues/58123)
> 
> Until the problem is resolved, you might be successful using `float32` instead of `float16`, but then you'll need to save some memory because 6 GB of VRAM won't be enough to run Stable Diffusion with default settings.
> 
> First, I'd recommend you use sequential CPU offloading, which only copies the active model to GPU memory (instead of moving them all at once). You'd do it like this:
> 
> ```python
> import torch
> from diffusers import StableDiffusionPipeline
> 
> pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", safety_checker=None)
> # pipe = pipe.to("cuda")
> pipe.enable_sequential_cpu_offload()
> 
> prompt = "a photo of an astronaut riding a horse on mars"
> image = pipe(prompt).images[0]
> 
> image.save("astronaut_rides_horse.png")
> ```
> 
> **IMPORTANT**: in this configuration you don't have to move the pipeline to `cuda`.
> 
> If this still runs out of memory, then you can enable attention slicing, like this:
> 
> ```python
> import torch
> from diffusers import StableDiffusionPipeline
> 
> pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", safety_checker=None)
> # pipe = pipe.to("cuda")
> pipe.enable_sequential_cpu_offload()
> pipe.enable_attention_slicing("max")
> 
> prompt = "a photo of an astronaut riding a horse on mars"
> image = pipe(prompt).images[0]
> 
> image.save("astronaut_rides_horse.png")
> ```
> 
> (If that works, then you can try to skip the `"max"` argument and see if it still does).
> 
> Note that inference will be slower when using `float32`, but at least I think you should be able to generate images this way. Please, do let us know if that works!

Hello, I have meet the same problem when run my code in V100, and the diffusers-cli results are as follows, how to solve this problem?

```
Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.14.0
- Platform: Linux-4.14.0_1-0-0-32-x86_64-with-glibc2.10
- Python version: 3.8.0
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.27.3
- Accelerate version: 0.18.0
- xFormers version: 0.0.17+5eb0dbf.d20230829
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

**Comment by pcuenca** [comment]
Hello @liuxz-cs, can you please post a short code snippet that reproduces the issue?

**Comment by liuxz-cs** [comment]
> Hello @liuxz-cs, can you please post a short code snippet that reproduces the issue?

We define a new class that inherits from `diffusers.pipeline_utils import DiffusionPipeline`, and call its functions after initialization with the trained model parameters with:

```
video_controlnet_pipe = NewDiffusionPipeline.from_pretrained(
    net_path,
    torch_dtype = torch.float16
).to("cuda")
```

The error information is  `pipelines\pipeline_utils.py:818: RuntimeWarning: invalid value encountered in cast
images = (images * 255).round().astype("uint8")`

**Comment by liuxz-cs** [comment]
> Hello @liuxz-cs, can you please post a short code snippet that reproduces the issue?

We define a new class that inherits from diffusers.pipeline_utils import DiffusionPipeline, and call its functions after initialization with the trained model parameters with:

```
pipe = NewDiffusionPipeline.from_pretrained(
    net_path,
    torch_dtype = torch.float16
).to("cuda")
```

The error information is `pipelines\pipeline_utils.py:818: RuntimeWarning: invalid value encountered in cast images = (images * 255).round().astype("uint8")`

**Comment by pcuenca** [comment]
This seems an unrelated issue, I would recommend you open a new one. But please, note that we won't be able to reproduce or understand the issue with the snippet you posted, as it contains code that we can't see or test. I'd suggest you try to isolate the problem using just diffusers code.

**Comment by CTimmerman** [comment]
`torch_dtype=torch.float32` works but is slower. https://github.com/huggingface/diffusers/issues/6815#issuecomment-1925810346
