### ISSUE TITLE
clip_sample argument is unused  during the initialisation of DDPMScheduler (scheduling_ddpm.py)

### ISSUE THREAD

**Issue by KnHuq** [huggingface/diffusers#2159]
### Describe the bug

File location: https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py

* During the initialisation of DDPMScheduler, clip_sample argument is taken however, it is not being used in any place. Even if we set the clip_sample to False, it still clips the samples in the step method.

### Reproduction

Just investigate the code of DDPMScheduler.

`class DDPMScheduler(SchedulerMixin, ConfigMixin):
    """
    Denoising diffusion probabilistic models (DDPMs) explores the connections between denoising score matching and
    Langevin dynamics sampling.
    [`~ConfigMixin`] takes care of storing all config attributes that are passed in the scheduler's `__init__`
    function, such as `num_train_timesteps`. They can be accessed via `scheduler.config.num_train_timesteps`.
    [`SchedulerMixin`] provides general loading and saving functionality via the [`SchedulerMixin.save_pretrained`] and
    [`~SchedulerMixin.from_pretrained`] functions.
    For more details, see the original paper: https://arxiv.org/abs/2006.11239
    Args:
        num_train_timesteps (`int`): number of diffusion steps used to train the model.
        beta_start (`float`): the starting `beta` value of inference.
        beta_end (`float`): the final `beta` value.
        beta_schedule (`str`):
            the beta schedule, a mapping from a beta range to a sequence of betas for stepping the model. Choose from
            `linear`, `scaled_linear`, or `squaredcos_cap_v2`.
        trained_betas (`np.ndarray`, optional):
            option to pass an array of betas directly to the constructor to bypass `beta_start`, `beta_end` etc.
        variance_type (`str`):
            options to clip the variance used when adding noise to the denoised sample. Choose from `fixed_small`,
            `fixed_small_log`, `fixed_large`, `fixed_large_log`, `learned` or `learned_range`.
        clip_sample (`bool`, default `True`):
            option to clip predicted sample between -1 and 1 for numerical stability.
        prediction_type (`str`, default `epsilon`, optional):
            prediction type of the scheduler function, one of `epsilon` (predicting the noise of the diffusion
            process), `sample` (directly predicting the noisy sample`) or `v_prediction` (see section 2.4
            https://imagen.research.google/video/paper.pdf)
    """

    _compatibles = [e.name for e in KarrasDiffusionSchedulers]
    order = 1

    @register_to_config
    def __init__(
        self,
        num_train_timesteps: int = 1000,
        beta_start: float = 0.0001,
        beta_end: float = 0.02,
        beta_schedule: str = "linear",
        trained_betas: Optional[Union[np.ndarray, List[float]]] = None,
        variance_type: str = "fixed_small",
        clip_sample: bool = True,
        prediction_type: str = "epsilon",
    ):`

### System Info

latest one

**Comment by patrickvonplaten** [comment]
Hey @KnHuq,

Note that `clip_sample` is used here: https://github.com/huggingface/diffusers/blob/7d96b38b70407ec69816e71cdcfc4e0b41e26768/src/diffusers/schedulers/scheduling_ddpm.py#L286 

Every __init__ that is decorated with `register_to_config`: https://github.com/huggingface/diffusers/blob/7d96b38b70407ec69816e71cdcfc4e0b41e26768/src/diffusers/schedulers/scheduling_ddpm.py#L111 automatically save the attribute under `self.config`
