### ISSUE TITLE
Porting `img2img.py` from SD into the diffusers library

### ISSUE THREAD

**Issue by atarashansky** [huggingface/diffusers#216]
The [image-to-image script](https://github.com/CompVis/stable-diffusion/blob/main/scripts/img2img.py) in stable-diffusion is a very nice tool for modifying images.

Their implementation seems relatively straightforward, though they have only implemented it for the DDIM scheduler. I took a crack at porting it over into the diffusers library but have not quite been able to replicate the behavior (long story short, the image is failing to crystallize at strengths < 0.8). I'm planning to keep beating my head against it, and hopefully have a PR soon, but figured I'd ask if there were any plans on your side to add similar functionality. If said functionality already exists, please point me in the right direction :)

Thanks!

**Comment by anton-l** [comment]
Thank you for exploring @atarashansky! We'll try to implement an img2img pipeline in the next couple of days, happy to compare notes!

**Comment by atarashansky** [comment]
**Does the diffusers library currently support "forward" diffusion?**

I started from scratch and got image-to-image translation to work in the following test case:
 - Imagine I wanted to use a stable diffusion output as the initial image. The output was generated from `prompt=A`
 - The target image has `prompt=B`
 - Let `strength` be in the range `[0,num_inference_steps]`. `strength=0` means the initial image has no influence. `strength=num_inference_steps` means the output will just be the initial image.
Scheme:
1.  Run denoising with `prompt=A` for `strength` steps
2. Run denoising with `prompt=B` for the remaining `num_inference_steps-strength` steps.

What about the more general use case where the initial image can be anything?
The scheme I want:
1. Diffuse the starting image for `num_inference_steps-strength` steps **<< is this feasible?**
2. Run denoising with `prompt=B` for the  subsequent  `num_inference_steps-strength` steps

I had previously tried:
1. Add noise level corresponding to step=strength to the encoded starting image
2. Run denoising with `prompt=B` for the subsequent `num_inference_steps-strength` steps
But the above is what I initially reported as having trouble with.

**Comment by unography** [comment]
@anton-l is a training pipeline planned as well for img2img? And apart from stable diffusion, is it possible to add img2img training for current ddpm models? like the superresolution examples in the original repo?

**Comment by NielsRogge** [comment]
This seems available now here: https://github.com/huggingface/diffusers/tree/main/examples/inference#image-to-image-text-guided-generation-with-stable-diffusion

cc @patil-suraj

**Comment by NielsRogge** [comment]
This seems now available here: https://github.com/huggingface/diffusers/tree/main/examples/inference#image-to-image-text-guided-generation-with-stable-diffusion

cc @patil-suraj

**Comment by anton-l** [comment]
Correct, the `img2img` pipeline is now available via `examples`! 
https://github.com/huggingface/diffusers/tree/main/examples/inference#image-to-image-text-guided-generation-with-stable-diffusion
