### ISSUE TITLE
LoRA training on an inpainting model.

### ISSUE THREAD

**Issue by vitalyshalumov** [huggingface/diffusers#2161]
### Describe the bug

I want to train using lora+dreambooth to add a concept to an inpainting model and then use the in-painting pipeline for inference.
The train_dreambooth_lora.py gives the following error:

RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[1, 4, 64, 64] to have 9 channels, but got 4 channels instead

Obviously this is due to the added input channels of the in-painting model.
how can I update the script train_dreambooth_lora.py to use it on models such as 
stabilityai/stable-diffusion-2-inpainting
runwayml/stable-diffusion-inpainting

alternatively, maybe the way to go is first use lora+dreambooth on vanila SD (train_dreambooth_lora.py), then train an in-painting model (can you please provide a reference?) and only then use inference?

Thank you!

### Reproduction

accelerate launch train_dreambooth_lora.py   --pretrained_model_name_or_path=$MODEL_NAME    --instance_data_dir=$INSTANCE_DIR   --output_dir=$OUTPUT_DIR   --instance_prompt="a photo of sns dog"   --resolution=512   --train_batch_size=1   --gradient_accumulation_steps=1   --checkpointing_steps=100   --learning_rate=1e-4   --report_to="wandb"   --lr_scheduler="constant"   --lr_warmup_steps=0   --max_train_steps=500   --validation_prompt="priest with sns dog, national geographic, portrait, photo, photography"   --validation_epochs=50   --seed="0"

### Logs

```shell
File "train_dreambooth_lora.py", line 1016, in <module>
    main(args)
  File "train_dreambooth_lora.py", line 873, in main
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File ".../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../diffusers/src/diffusers/models/unet_2d_condition.py", line 482, in forward
    sample = self.conv_in(sample)
  File ".../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File ".../lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[1, 4, 64, 64] to have 9 channels, but got 4 channels instead
```

### System Info

- `diffusers` version: 0.13.0.dev0
- Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 0.12.0
- Accelerate version: not installed
- xFormers version: 0.0.16rc425
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by krahnikblis** [comment]
interested in this topic, following and looking forward to the response re: training.

in my own work on this, i've analyzed the inpainting Unet weights, the only difference in structure is the first convolutional layer. so, if you already have LoRA weights, you can technically use them as-is on the Inpaint model, since they don't affect the convolutional layer. however, in the docs about how inpainting model was trained, it branched from SD 1.2, so if you trained LoRAs against say 1.5, you might need to grab the difference between 1.5 and 1.2, to add in with your existing LoRAs... i did this via getting a LoRA extraction of that difference... not sure how big the training difference is between the 2 models, so the attentions might not be "all you need" hehe... haven't tested the results yet, been dealing with other bugs from latest release.

**Comment by patrickvonplaten** [comment]
Hey @vitalyshalumov,

Good question! It should be more or less the same as the inpainting training script here: https://github.com/huggingface/diffusers/blob/60d915fbed5665534aa52bb98ef4444eac46715c/examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py#L732

Would you maybe be willing to add a training script to https://github.com/huggingface/diffusers/tree/main/examples/research_projects/dreambooth_inpaint ? I think the community would really like this :-) 

Maybe also cc @thedarkzeno and @patil-suraj here :-)

**Comment by patil-suraj** [comment]
Would be nice have such a script, 

the lora logic can pretty much be copied from https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py

and using this and the inpainting script , we could add a new script 

`examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint_lora.py`.

Happy to help with this :)

**Comment by thedarkzeno** [comment]
Nice, I think it should be easy, will take a look at it later today

**Comment by thedarkzeno** [comment]
Just created a PR here: https://github.com/huggingface/diffusers/pull/2205
