### ISSUE TITLE
Add an example on pivotal tuning

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#2162]
Pivotal tuning: https://arxiv.org/abs/2106.05744

Reference implementation: https://github.com/cloneofsimo/lora

**Comment by sayakpaul** [comment]
Up.

**Comment by dioscuroi** [comment]
👍

**Comment by sayakpaul** [comment]
Will be picked up.

**Comment by abcamiletto** [comment]
Up! This would be very cool. Is the plan to replicate [this](https://github.com/cloneofsimo/lora/blob/master/training_scripts/run_lorpt.sh)?

**Comment by sayakpaul** [comment]
Sorry, currently, we're a bit short-stuffed at the moment. If you want to pick it up, we're more than happy to help out :)
