### ISSUE TITLE
Im using jupyter notebook and every time it stacks ckpt file but I don't know where it is

### ISSUE THREAD

**Issue by jakeyahn** [huggingface/diffusers#2167]
every time I try using diffusers, it downloads all .bin files and ckpt files but it piles up somewhere in the server.

i thought it got piled up in anaconda3/env but it wasn't. 

where would it downloads the files be? my server its full of memory:(

![image](https://user-images.githubusercontent.com/82705312/215630356-d552d30c-1cb2-4755-8bcb-cdf30ed4c179.png)

**Comment by patrickvonplaten** [comment]
Sorry I don't fully understand the issue. Downloaded models are usually cached under `~.cache/...`

**Comment by jakeyahn** [comment]
thanks that solved my issue!
