### ISSUE TITLE
Textual inversion logging doesn't see placeholder tokens

### ISSUE THREAD

**Issue by isamu-isozaki** [huggingface/diffusers#2182]
### Describe the bug

Currently, the textual inversion script sets up pipelines as
```
pipeline = DiffusionPipeline.from_pretrained(
    args.pretrained_model_name_or_path,
    text_encoder=accelerator.unwrap_model(text_encoder),
    revision=args.revision,
)
```
without the tokenizer. So when I was training on the placeholder token <frida> for my dog, I kept getting pictures like this who is a famous woman called frida
![media_images_validation_6_96276b2fa8da68d8252b](https://user-images.githubusercontent.com/23430101/215855769-70b8f041-f09e-4dca-89a3-36d66ff82556.png)

I'll make a pr to fix this and post it here. 

### Reproduction

Just run textual inversion script in examples with any concept with <frida> placeholder token

### System Info

Any env.

**Comment by isamu-isozaki** [comment]
FIxed in pr

**Comment by patrickvonplaten** [comment]
Ah very good catch! Thanks for opening an issue :-)

**Comment by isamu-isozaki** [comment]
@patrickvonplaten Np! And closing since it's fixed
