### ISSUE TITLE
config files missed for training naive text-to-image model

### ISSUE THREAD

**Issue by JunMa11** [huggingface/diffusers#2185]
### Describe the bug

I used the following command to train a naive text-to-image model and the training process goes well. 

Here are files in the model folder

```bash
pytorch_model.bin  optimizer.bin        scaler.pt
random_states_0.pkl  scheduler.bin

```

However, during inference, it raises errors on missing config files.

> OSError: Error no file named model_index.json found in directory path_to/text2Euro-naive/checkpoint-4000.

I manually download `model_index.json` from https://huggingface.co/stabilityai/stable-diffusion-2-1/blob/main/model_index.json and put it into the model folder. 

A new error occurred:

> Error no file named scheduler_config.json found in directory path_to/text2Euro-naive/checkpoint-4000.

How can I find these missed files for model inference?

 

### Reproduction

```bash
export MODEL_NAME="stabilityai/stable-diffusion-2-1-base"
export TRAIN_DIR="./data/train"
export OUTPUT_DIR="./text2Euro-naive"

accelerate launch --mixed_precision="fp16"  train_naive_T2I.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --train_data_dir=$TRAIN_DIR \
  --output_dir=$OUTPUT_DIR \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --max_train_steps=30000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \

```

Inference 

```bash
from diffusers import StableDiffusionPipeline
import torch

model_path = "path_to/text2Euro-naive/checkpoint-4000"
pipe = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=torch.float16)
pipe.to("cuda")
```

### Logs

```shell
OSError: Error no file named model_index.json found in directory path_to/text2Euro-naive/checkpoint-4000.

> Error no file named scheduler_config.json found in directory path_to/text2Euro-naive/checkpoint-4000.
```

### System Info

- `diffusers` version: 0.10.2
- Platform: Linux-5.13.0-39-generic-x86_64-with-glibc2.31
- Python version: 3.9.15
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
Hey @JunMa11,

Thanks for the bug - you're raised a very good point here and we have actually an open PR to fix it here: https://github.com/huggingface/diffusers/pull/2048#discussion_r1091957011 . I hope it gets merged soon :-)

**Comment by orionw** [comment]
I have the same issue, has this been resolved?  Thanks

**Comment by shellin-star** [comment]
I met the same issue, how to solve this problem?

**Comment by patrickvonplaten** [comment]
Could you open a new issue with a reproducible code snippet please? :-)
