### ISSUE TITLE
How to change default Adam optimizer to special version of Adam deepspeed.ops.adam.DeepSpeedCPUAdam?

### ISSUE THREAD

**Issue by runner22k** [huggingface/diffusers#2186]
I am having a 8GB VRAM GPU. I am using ShivamShrirao's diffuser to train. On his page, It is said that "Changing the default Adam optimizer to DeepSpeed's special version of Adam deepspeed.ops.adam.DeepSpeedCPUAdam gives a substantial speedup"

How to do that? and where can we get CUDA toolchain with the same version as pytorch?
My pytorch version is 1.12.1

**Comment by patil-suraj** [comment]
To use `CPUAdam` you will just have to replace the optimizer here https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py#L665 with `deepspeed.ops.adam.DeepSpeedCPUAdam`

Each pytorch version comes with a cuda version, check what cuda version it  is, you can type `pip show torch` and then it'll print something  like `torch 1.12.1+cu113` with the cuda version at the end, then you'll just have to install that specific cuda version toolchain.

If you use/like `conda`, the that would be easiest option https://towardsdatascience.com/managing-cuda-dependencies-with-conda-89c5d817e7e1

**Comment by runner22k** [comment]
> 

@patil-suraj Thanks for the reply, I am not a programmer. Can you suggest which line needs to be changed?
