### ISSUE TITLE
train_dreambooth_lora.py doesn't have --dataset_name  and --caption_column arguments

### ISSUE THREAD

**Issue by Pirog17000** [huggingface/diffusers#2192]
So I'm trying to give it a try launching locally with an provided example from the announcements page:

```
accelerate launch --mixed_precision="fp16" train_text_to_image_lora.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$DATASET_NAME --caption_column="text" \
  --resolution=512 --random_flip \
  --train_batch_size=1 \
  --num_train_epochs=100 --checkpointing_steps=5000 \
  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --seed=42 \
  --output_dir="sd-pokemon-model-lora" \
  --validation_prompt="cute dragon creature" --report_to="wandb"
  ```

turning it into a function like this:
```
def lora_train():
    print("TRAINING LORA!!!")
    time.sleep(2)

    args_list = [
        '--pretrained_model_name_or_path=' + MODELT_NAME,
        '--class_data_dir=' + CAPTIONS_DIR,
        '--num_class_images=' + str(amount_of_images),
        '--instance_data_dir=' + IMAGES_DIR,
        "--seed=23123",
        '--instance_prompt=' + instance_prompt,
        '--validation_prompt=' + validation_prompt,
        '--validation_epochs=' + str(render_every_epoch),
        '--output_dir=' + lora_output_folder,
        '--resolution=' + str(Resolution),
        '--checkpointing_steps=' + str(checkpoint_every),
        '--num_train_epochs=' + str(train_epochs),
        # Point to checkpoint name, not 'True' or 'False'
        '--learning_rate=' + str(lora_learning_rate),
        '--allow_tf32',
        '--enable_xformers_memory_efficient_attention',
    ]

    command = ["accelerate", "launch", lora_script_path, *args_list]
    subprocess.run(command)
```

I have prepared a proper captions - every caption in txt file with the same name as an image, put it into CAPTIONS_DIR, additionally grabbed all the text from every of them and put in jsonl file, as written on this page: https://huggingface.co/docs/datasets/v2.4.0/en/image_load#imagefolder-with-metadata

putting jsonl file in IMAGES_DIR is breaking the training process.
it's confusing, what should be the name of captions file, where it should be placed, how do I tell the column name without an argument, there's no such argument in use inside train_dreambooth_lora.py.

help!

**Comment by patil-suraj** [comment]
Hi @Pirog17000 !

`train_dreambooth_lora` does not accept a caption+image datset, it just needs a path of the directory containing your images. Note that, dreambooth (with or without lora) is different from text_to_image, dreambooth does not need text captions.

You can find specific instructions for text_to_image and dreambooth here 

text_to_image: https://github.com/huggingface/diffusers/tree/main/examples/text_to_image#training-with-lora
dreambooth: https://github.com/huggingface/diffusers/tree/main/examples/dreambooth#training-with-low-rank-adaptation-of-large-language-models-lora
