### ISSUE TITLE
Tune A Video

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#2195]
### Model/Pipeline/Scheduler description

Tune a video's idea is to leverages Stable Diffusion to create short videos.

Code and weights are available here and already in the diffusers format:
https://github.com/showlab/Tune-A-Video

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

cc @bryandlee

**Comment by sayakpaul** [comment]
Closing this issue in favor of https://github.com/huggingface/diffusers/issues/2432. @Abhinay1997 is already working on https://github.com/huggingface/diffusers/pull/2455.
