### ISSUE TITLE
Is Openvino pipeline support in progress ?

### ISSUE THREAD

**Issue by lalith-mcw** [huggingface/diffusers#2202]
### Model/Pipeline/Scheduler description

1. Planning to support **Openvino pipeline** with converted **IR models** from stable-diffusion with model optimizer. Is the development for same in-progress ?

2. And also currently there is support only for **CPUExecutionProvide**r and there is no support to use **Openvino ExecutionProvider** to run ONNX models with the pipeline. Which takes advantage of the system and has better utilization of the resources with efficient inferencing.

Support for the same also yet to be added 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by patrickvonplaten** [comment]
Hey @lalith-mcw ,

We currently don't have the bandwith to maintain open vino in `diffusers`. Think it should rather go directly into a library like optimum: https://github.com/huggingface/optimum

cc @echarlaix @mfuntowicz @anton-l

**Comment by echarlaix** [comment]
Hi @lalith-mcw,

We plan to integrate the export of stable diffusion models to the OpenVINO IR along with pipelines allowing inference using OpenVINO Runtime to `optimum`, you can see the progress in [#122](https://github.com/huggingface/optimum-intel/pull/122).

**Comment by lalith-mcw** [comment]
> Hi @lalith-mcw,
> 
> We plan to integrate the export of stable diffusion models to the OpenVINO IR along with pipelines allowing inference using OpenVINO Runtime to `optimum`, you can see the progress in [#122](https://github.com/huggingface/optimum-intel/pull/122).

Yeah thanks will check that out

**Comment by lalith-mcw** [comment]
Any updates on running onnx models with onnxruntime using openvino-execution provider ?

@patrickvonplaten @echarlaix

**Comment by geekinglcq** [comment]
> Any updates on running onnx models with onnxruntime using openvino-execution provider ?
> 
> @patrickvonplaten @echarlaix
Hi, we just release a version of OpenVINO pipeline here:  
https://github.com/OFA-Sys/diffusion-deploy

**Comment by echarlaix** [comment]
> Any updates on running onnx models with onnxruntime using openvino-execution provider ?

Concerning the ONNX Runtime OpenVINO Execution Provider, better to follow the updates on [microsoft/onnxruntime#13973](https://github.com/microsoft/onnxruntime/issues/13973) directly.

Thanks for sharing [@geekinglcq](https://github.com/geekinglcq) ! We plan to integrate the stable diffusion pipeline supporting both OpenVINO and ONNX Runtime to `optimum`, and to add the OpenVINO export and loading logic to `optimum-intel`, will link the PRs to this issue when ready

**Comment by sayakpaul** [comment]
[ONNX Runtime](https://huggingface.co/docs/optimum/onnxruntime/usage_guides/models#export-and-inference-of-stable-diffusion-models)
[OpenVINO](https://huggingface.co/docs/optimum/intel/inference#export-and-inference-of-stable-diffusion-models)
