### ISSUE TITLE
Why $MODEL_NAME is downloaded to my Home directory instead of dreambooth directory?

### ISSUE THREAD

**Issue by runner22k** [huggingface/diffusers#2203]
### System Info

```Shell
- `Accelerate` version: 0.16.0
- Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.31
- Python version: 3.10.9
- Numpy version: 1.23.5
- PyTorch version (GPU?): 1.12.1 (True)
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: DEEPSPEED
	- mixed_precision: fp16
	- use_cpu: False
	- dynamo_backend: NO
	- num_processes: 1
	- machine_rank: 0
	- num_machines: 1
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- deepspeed_config: {'gradient_accumulation_steps': 1, 'gradient_clipping': 1.0, 'offload_optimizer_device': 'cpu', 'offload_param_device': 'cpu', 'zero3_init_flag': False, 'zero_stage': 2}
	- fsdp_config: {}
	- megatron_lm_config: {}
	- downcast_bf16: no
```

### Information

- [X] The official example scripts
- [x] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [x] My own task or dataset (give details below)

### Reproduction

I am trying to train a model using Shivam Shrirao dreambooth. I gave "$MODEL_NAME=darkstorm2150/Protogen_v2.2_Official_Release". When I run the script, Protogen model is getting downloaded into my home directory ($HOME/.cache/huggingface) instead of the dreambooth location in a different partition with a lot of free space. Please check my launch.sh bash script below. 

```
export MODEL_NAME="darkstorm2150/Protogen_v2.2_Official_Release"
export INSTANCE_DIR="./test/training"
export CLASS_DIR="./test/man"
export OUTPUT_DIR="./test/trained"

accelerate launch --mixed_precision="fp16" train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a portrait of sks man" \
  --class_prompt="a portrait of man" \
  --seed=3434554 \
  --save_interval=400 \
  --resolution=512 \
  --train_batch_size=1 \
  --sample_batch_size=1 \
  --gradient_accumulation_steps=1 --gradient_checkpointing \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=800 \
  --save_sample_prompt="a masterpiece photo of sks man, 4k, dlsr, canon, nikon"
```

### Expected behavior

I expected the model to be downloaded to the current working directory, instead of Home directory. Current directory is on a different drive with lot of free space, just mounted to "AI" directory. That is `"AI/github/diffusers/examples/dreambooth/"
`

Please suggest a solution to change the default download location for the models, which are being directly downloaded from hugging face website by the script.

**Comment by patrickvonplaten** [comment]
Hey @runner22k,

> I am trying to train a model using Shivam Shrirao dreambooth.

Note that we don't maintain: https://github.com/ShivamShrirao/diffusers

Could you please open the issue there? It's a fork of `diffusers` I believe

**Comment by runner22k** [comment]
> Hey @runner22k,
> 
> > I am trying to train a model using Shivam Shrirao dreambooth.
> 
> Note that we don't maintain: https://github.com/ShivamShrirao/diffusers
> 
> Could you please open the issue there? It's a fork of `diffusers` I believe

Sure thankyou :)
