### ISSUE TITLE
Add safety check usage in the readme

### ISSUE THREAD

**Issue by dblunk88** [huggingface/diffusers#221]
It seems like a safety check is now required for stable diffusion. Could update the readme with a proper example on how to establish the pipeline? The current example is now outdated

**Comment by anton-l** [comment]
Hi @dblunk88! The current `main` branch is not compatible with the checkpoint yet, as the final safety weights will only be released in a couple of days. Please install the latest PyPi release instead until then:
`pip install diffusers transformers`

**Comment by anton-l** [comment]
The latest release and checkpoints are fully in sync now! 🎉
