### ISSUE TITLE
Allow for LoRA to train the text encoder as well

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#2210]
**Is your feature request related to a problem? Please describe.**
The current LoRA training code only trains the unet

**Describe the solution you'd like**
Also train the text encoder, this is already possible with the non-LoRA Dreambooth, also popular diffusers based implementations of LoRA such as `cloneofsimo/lora` [also allow for text encoder LoRA](https://github.com/cloneofsimo/lora/blob/master/training_scripts/train_lora_dreambooth.py)

**Additional context**
There's a [very nice analysis](https://github.com/cloneofsimo/lora/discussions/37) about how training the text-encoder LoRA can affect the generation, seems to overall bring better quality.

**Comment by yuananf** [comment]
There is already a PR for this, #2141

**Comment by apolinario** [comment]
Thanks for flagging. I missed it!
