### ISSUE TITLE
how to fine-tune the stable diffusion super resolution model

### ISSUE THREAD

**Issue by liushanyuan18** [huggingface/diffusers#2219]
Thank you for you amazing work!
Could you please tell me how to finetune the stable diffusion super resolution model ? I don't know how to do that

**Comment by patrickvonplaten** [comment]
Very good question! We currently don't have a training example pipeline for this sadly.
Maybe you can also try asking on discord:
https://discord.gg/G7tWnz98XR

**Comment by R2Bb1T** [comment]
@liushanyuan18 hello, did you solve the problem? I've been working on the same thing recently.
