### ISSUE TITLE
Multiple GPU train dreambooth problems？

### ISSUE THREAD

**Issue by wen020** [huggingface/diffusers#2220]
**what happend？**
I used **a gpu A100** to train stable diffution(https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py), and change the train_batch_size from 1 to 2, 4.
The following is the experimental data：
GPU.             batch size.             train cost time.                         gpu memory
1\*A100：     1                   10 minute 40 second             17G
1\*A100：     2                   16 minute 40 second             22G
1\*A100：     4                   30 minute40 second             35G
**I don't understand why the train cost time increases with the batch size increases？**

Then I used **two gpu A100** to train stable diffution(https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py), and change the train_batch_size from 1 to 2, accelerate split_batches=True.
The following is the experimental data：
GPU.       batch size.     train cost time.                         gpu memory
2\*A100：1                   10 minute 40 second             22G
2\*A100：2                   16 minute 40 second             27G
**I don't understand is this time and gpu memory consumption normal？**

And following is my environment configuration:
torch                          1.13.1+cu116
transformers                   4.26.0
diffusers                      0.13.0.dev0
**accelerate config**
-----------------------------------------------------------------------------------------------In which compute environment are you running?
This machine                                                                                   
-----------------------------------------------------------------------------------------------Which type of machine are you using?                                                           
multi-GPU                                                                                      
How many different machines will you use (use more than 1 for multi-node training)? [1]:       
Do you wish to optimize your script with torch dynamo?[yes/NO]:NO                              
Do you want to use DeepSpeed? [yes/NO]: NO                                                     
Do you want to use FullyShardedDataParallel? [yes/NO]: NO                                      
Do you want to use Megatron-LM ? [yes/NO]: NO                                                  
How many GPU(s) should be used for distributed training? [1]:2
What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:
-----------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
fp16                                                                                           
accelerate configuration saved at /root/.cache/huggingface/accelerate/default_config.yaml

**Comment by patil-suraj** [comment]
I would need a few more deatils to understand this better. Could you also post the command that you used? And are you using xformers ?
