### ISSUE TITLE
Using safety checker outside of stable diffusion pipeline

### ISSUE THREAD

**Issue by preethiseshadri518** [huggingface/diffusers#2225]
I am interested in flagging images I am analyzing as safe/unsafe and know that stable diffusion uses a safety checker. Is it possible to use this safety checker in isolation (i.e. without using it in the stable diffusion pipeline)? If so, I would really appreciate any examples or suggestions on how to do so! Here is what I am referring to: https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/safety_checker.py

I also noticed that you have code to create a custom inference pipeline, as you show in this blog: https://huggingface.co/blog/stable_diffusion. However, you don't use the safety checker after using the vae to decode the latents into the generated image. Shouldn't that be done afterwards, or is the check being done implicitly somewhere in the pipeline?

```
with torch.no_grad():
    image = vae.decode(latents).sample
```

**Comment by patrickvonplaten** [comment]
Here is an example of how to use it: 
https://github.com/CompVis/stable-diffusion/blob/21f890f9da3cfbeaba8e2ac3c425ee9e998d5229/scripts/txt2img.py#L29

**Comment by preethiseshadri518** [comment]
Thank you! This is helpful.
