### ISSUE TITLE
Pipe doesnt get loaded into GPU StableDiffusionPipeline.from_pretrained

### ISSUE THREAD

**Issue by PGTBoos** [huggingface/diffusers#2228]
### Describe the bug

My system nvidea 3080 ti (12 Gig) win 11 cuda 12 (even with the toolkit), with WSL2 ubuntu   
Pytorch works fine with cuda in my other jupyterlab experiments.  
I can login to huginglab, (i see in debug console), and have tried various models.
I tried with autocast and without, the fan's of the card spin up a few seconds and then slow down again.   
It seems getpretrained doesnt work (so it never gets .to("cuda")    
I show the code partial difusers and transformers are the latest versions.   
In jupyterlab it just hangs, i even extended timeouts in jupyterlab (10 minutes) but no effect.   
I just get fetched 15 files 100%green bar message and then nothing ever happens after.   
No errors in the console, or in the notebook , or in the debug output.
I don't now how to enable more debugging or where to look to fix this please help.

~~~Python
import os
from PIL import Image, ImageDraw
from IPython.display import HTML
from base64 import b64encode
import torch
from torch.nn import functional as F
from diffusers import StableDiffusionPipeline, AutoencoderKL
from diffusers import UNet2DConditionModel, PNDMScheduler, LMSDiscreteScheduler
from diffusers.schedulers.scheduling_ddim import DDIMScheduler
from transformers import CLIPTextModel, CLIPTokenizer
from tqdm.auto import tqdm
from huggingface_hub import notebook_login
notebook_login()

from torch.cuda.amp import autocast   #https://www.reddit.com/r/StableDiffusion/comments/x79mfm/cannot_import_name_autocast_from_torch/
from PIL import Image
torch.cuda.empty_cache() #just to be sure
#model = "runwayml/stable-diffusion-v1-5"
model = "CompVis/stable-diffusion-v1-4"
token="hf_xxxx-mytoken-xxxxx"
pipe = StableDiffusionPipeline.from_pretrained(model, torch_dtype=torch.float16, use_auth_token= token).to("cuda")
prompt = "White sphynx cat, is going fishing"

# Found docs suggested this to get around a bug
#with autocast(True):
#    _ = pipe(prompt, num_inference_steps=1)

with autocast(True):
    image = pipe(prompt).images[0]
image.show()
~~~

### Reproduction

pipe = StableDiffusionPipeline.from_pretrained(model, torch_dtype=torch.float16, use_auth_token= token)

### Logs

```shell
I have none no errors are shownin debug of jupyterlab or in the output or in the console.
```

### System Info

- `diffusers` version: 0.12.1
- Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.10.6
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.12.0
- Transformers version: 0.15.0
- Accelerate version: not installed
- xFormers version: not installed
- Using GPU in script?: <yes>
- Using distributed or parallel set-up in script?: <no>

**Comment by patrickvonplaten** [comment]
Hey @PGTBoos,

Note that we strongly recommend against using `with torch.autocast` for inference. See: https://github.com/huggingface/diffusers/pull/2021

**Comment by PGTBoos** [comment]
well, I tried without it too, and it's not to the point where it hangs, I was under the false impression then that it worked maybe better as I thought the GPU fan spinning a few seconds more, but it wasn't crashing there. It never got that far.
