### ISSUE TITLE
Issues in Textual_Inversion example (Validation code and Gradient accumulation)

### ISSUE THREAD

**Issue by yxding95** [huggingface/diffusers#2233]
Hi,

I'm glad that you build this amazing project! 
But there seems some issues in the Textual_Inversion example (https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion.py):

1. The validation pipeline forget to replace the tokenizer at Line783 (https://github.com/huggingface/diffusers/blob/a87e87fcbe8fa999dcaa5f681f1df86beeadf68f/examples/textual_inversion/textual_inversion.py#L783-L787)
2. I'm not very familiar with the Accelerator, but is there forget to apply the Gradient Accumulation in the training part? (I'm not sure whether it is automatically processed by Accelerator) From Line743 to Line747 (https://github.com/huggingface/diffusers/blob/a87e87fcbe8fa999dcaa5f681f1df86beeadf68f/examples/textual_inversion/textual_inversion.py#L743-L747)

Thanks for your awesome project again!

**Comment by patrickvonplaten** [comment]
Think the tokenizer part is fixed here: 
https://github.com/huggingface/diffusers/commit/d46d78c5846f88552abdfdd67dd6e704c0c47a60

Regarding the gradient accumulation, this is handled automatically in `accelerate` no? cc @patil-suraj

**Comment by patil-suraj** [comment]
Yes, gradient accumulation is handled automatically in `accelerate`, you can refer to the docs for more details https://huggingface.co/docs/accelerate/usage_guides/gradient_accumulation#letting-accelerate-handle-gradient-accumulation
