### ISSUE TITLE
Some code are missing

### ISSUE THREAD

**Issue by pokameng** [huggingface/diffusers#2242]
I don't find the Training was done using a [modified version of the original Stable Diffusion training code](https://huggingface.co/lambdalabs/sd-image-variations-diffusers/blob/main/(https://github.com/justinpinkney/stable-diffusion).
 Something is empty.

Can you reload this code?
Thanks!!!
![image](https://user-images.githubusercontent.com/47957015/216762529-4ec55b89-9a54-4c3e-860b-208fa7124c8d.png)

@patrickvonplaten 
@kashif @natolambert

**Comment by averad** [comment]
Submitted a request to update the hyperlink:

https://huggingface.co/lambdalabs/sd-image-variations-diffusers/discussions/17

Workaround is to use:

https://github.com/justinpinkney/stable-diffusion

Note: 

This is not an issue with Huggingface/Diffusers but with a specific Model Card on HuggingFace.co

Issue like this should be handled on HuggingFace.co using the Community Tabs on the Model having an issue or containing an error.

**Comment by williamberman** [comment]
thanks @averad !
