### ISSUE TITLE
Does LoRa affect memory usage and run-time during inference?

### ISSUE THREAD

**Issue by FBehrad** [huggingface/diffusers#2247]
Hello,
I fine-tuned the Stable Diffusion using LoRa. Although the fine-tuning became much faster and required less memory, the inference was heavily affected. Now, inference has become very slow and needs more memory. 
Is this normal?

**Comment by jorgemcgomes** [comment]
Were you using xformers? There is currently an API issue, where if you enable LoRA, xformers is disable, see #2124

**Comment by patrickvonplaten** [comment]
@bddppq has a great solution in #2286 - we should be able to merge this soon :-)

**Comment by FBehrad** [comment]
> @bddppq has a great solution in #2286 - we should be able to merge this soon :-)

Thank you. The provided solution worked for me.
