### ISSUE TITLE
Use KerasCV fine-tuned checkpoints in Diffusers 🧨 

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#2253]
You can now fine-tune Stable Diffusion (v1) models and use them in Diffusers as standard `StableDiffusionPipeline`s. Check out the following document to learn more!

[Using KerasCV Stable Diffusion Checkpoints in Diffusers](https://huggingface.co/docs/diffusers/main/en/using-diffusers/kerascv)

**Comment by patrickvonplaten** [comment]
Think we can close this :-)
