### ISSUE TITLE
unconditional_image_generation/train_unconditional.py incompatibile with ONNXRuntime

### ISSUE THREAD

**Issue by prathikr** [huggingface/diffusers#2265]
### Describe the bug

I am testing compatibility of ONNXRuntime with the diffusers unet and am running into an issue with a post-processing step in the train_unconditional.py example script.

In previous discussions, we discovered an issue where ONNXRuntime expects a plain numpy array as output of the forward pass instead of a dictionary. I was able to resolve this issue by using `return_dict=False` parameter and adjust the way the forward pass of the model is called during training from `model(noisy_images, timesteps).sample` to `model(noisy_images, timesteps, return_dict=False)[0]` in the training example script.

However, a new post-processing step was added in the training pipeline where a DDPMPipeline is used to perform inference using an ONNXRuntime trained model. This is causing the error described below. What is the guidance to circumvent this issue as ONNXRuntime inference uses a different API than training?

### Reproduction

accelerate launch examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py --dataset_name huggan/flowers-102-categories --output_dir ./outputs/ --overwrite_output_dir --ddpm_num_steps 100 --train_batch_size 16 --mixed_precision no

### Logs

```shell
Traceback (most recent call last):
  File "train_unconditional.py", line 569, in <module>
    main(args)
  File "train_unconditional.py", line 544, in main
    images = pipeline(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/prathikrao/diffusers/src/diffusers/pipelines/ddpm/pipeline_ddpm.py", line 70, in __call__
    if isinstance(self.unet.sample_size, int):
  File "/home/prathikrao/.local/lib/python3.8/site-packages/onnxruntime/training/ortmodule/ortmodule.py", line 281, in __getattr__
    return getattr(self.module, name)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'sample_size'
```

### System Info

- `diffusers` version: 0.13.0.dev0
- Platform: Linux-5.0.0-1032-azure-x86_64-with-glibc2.17
- Python version: 3.8.16
- PyTorch version (GPU?): 1.13.1 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: not installed
- Accelerate version: 0.16.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: distributed

**Comment by prathikr** [comment]
@patrickvonplaten @anton-l could you please take a look or assign someone? Thank you

**Comment by patrickvonplaten** [comment]
Hey @prathikr, 

I don't think the https://github.com/huggingface/diffusers/blob/main/examples/unconditional_image_generation/train_unconditional.py script is supposed to work with ONNX. The script is supposed to be an easy example of how to train an unconditional image generation model.

**Comment by prathikr** [comment]
Hi @patrickvonplaten, I've already added the ONNX version under research_projects and am maintaining it myself. The core issue is that DDPMPipeline breaks when given an ORTModule object for inference. I'm curious why is there an inferencing section in a training script?

**Comment by patrickvonplaten** [comment]
cc @anton-l @echarlaix maybe

**Comment by patrickvonplaten** [comment]
Gently pinging @anton-l and @echarlaix here again :-)
