### ISSUE TITLE
colossalai problem

### ISSUE THREAD

**Issue by wen020** [huggingface/diffusers#2268]
**What happend？**
I used colossalai to train stable diffution (https://github.com/huggingface/diffusers/blob/main/examples/research_projects/colossalai/train_dreambooth_colossalai.py)  to train dreambooth and found to be slower than train_dreambooth.py (https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py)

The following is the experimental data：
train_dreambooth_colossalai.py
GPU.         batch size.      train cost time.               gpu memory
2\*A100： 1                      8 minute 40 second       17G\*2

train_dreambooth.py
GPU.        batch size.      train cost time.                gpu memory
1\*A100： 1                      5 minute 7 second          22G
**I don't understand why train_dreambooth_colossalai.py is slower than train_dreambooth.py？**

**Reproduction**
run train_dreambooth_colossalai.py in
torchrun --nproc_per_node 2 train_dreambooth_colossalai.py
--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4
--instance_data_dir=./training_images
--class_data_dir=./class_images
--output_dir=./trained_models
--with_prior_preservation --prior_loss_weight=1.0
--instance_prompt="coachchristo person"
--class_prompt="person"
--resolution=512
--train_batch_size=1
--learning_rate=5e-6
--lr_scheduler="constant"
--lr_warmup_steps=0
--max_train_steps=1000
--placement="cuda"

And following is my environment configuration:
colossalai 0.2.0+torch1.13cu11.6
torch 1.13.1
diffusers 0.12.1
GPU 2*A100

run train_dreambooth.py in
torch 1.13.1
diffusers 0.12.1
GPU 1*A100

**Comment by patrickvonplaten** [comment]
Gently pinging @Fazziekey here :-)

**Comment by Fazziekey** [comment]
colossal AI use cpu offload, which will offload Mem fro GPU to cpu to reduce the memory cost, it is a better sulotion for the user who don't have A100
