### ISSUE TITLE
Script for converting stable diffusion to stable diffusion inpainting.

### ISSUE THREAD

**Issue by theja-vanka** [huggingface/diffusers#2280]
I have been trying to fine tune stable diffusion and convert that into inpainting model and resume training from there. Any script for model surgery / conversion pipeline would be great.

**Comment by patrickvonplaten** [comment]
Hey @theja-vanka can you try to use this code snippet: https://github.com/huggingface/diffusers/issues/1619 ? :-) This should work

**Comment by satwiksunnam19** [comment]
Hello @theja-vanka @patrickvonplaten I have followed the conversion part of UNET but after that how to proceed further, any help in the direction is appreciated.
