### ISSUE TITLE
stable diffusion machine memory leak

### ISSUE THREAD

**Issue by wen020** [huggingface/diffusers#2284]
I have encountered a memory leak problem, we need to store and switch the model of stable diffusion in memory, but when we convert the model in memory to gpu, the memory is not reclaimed, and at the same time, when the model in memory is deleted, the memory also not recycled.
Therefore, what should I do to reclaim the machine memory occupied by the stable diffusion model.

code：
![51739229-1161-4286-9FEB-728C4EA7E976.png](https://s3.amazonaws.com/moonup/production/uploads/1673944537468-6377272a0c233a6c5ec9d40b.png)

runing log：
![FF8085CC-A11A-48C3-94ED-1F5BE84AF27A.png](https://s3.amazonaws.com/moonup/production/uploads/1673944582546-6377272a0c233a6c5ec9d40b.png)

**Comment by patrickvonplaten** [comment]
Hey @wen020,

Would you like to open a PR to fix the memory leak? :-)

**Comment by wen020** [comment]
@patrickvonplaten I have no idea about this problem.Can you give me some suggestions？And do you have a plan to solve this problem？

**Comment by patrickvonplaten** [comment]
Those issue could maybe help:

https://github.com/huggingface/diffusers/issues/1905
https://github.com/huggingface/diffusers/issues/2053

**Comment by rgdcardoso** [comment]
@wen020 @patrickvonplaten experiencing exactly the same issue. Creating a pipeline allocates memory that is not deallocated when the pipeline goes out of scope or is forcefully removed. `torch.cuda.clean_cache` or `gc.collect` are unable to clean up 2GB's per pipeline that end up leaking.
