### ISSUE TITLE
ImportError: cannot import name 'StableDiffusionVideoInpaintPipeline' from 'diffusers'

### ISSUE THREAD

**Issue by reillydonovan** [huggingface/diffusers#2294]
### Describe the bug

I installed diffusers using pip install --upgrade diffusers[torch] and got returned the following error.  

ImportError: cannot import name 'StableDiffusionVideoInpaintPipeline' from 'diffusers'

I get the same return when installing with conda.
Any idea how to rememdy this issue?

### Reproduction

pip install --upgrade diffusers[torch]

conda install -c conda-forge diffusers

both return the same error.

### System Info

- `diffusers` version: 0.12.1
- Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.31
- Python version: 3.11.0
- PyTorch version (GPU?): 1.13.1.post200 (True)
- Huggingface_hub version: 0.12.0
- Transformers version: 0.16.0
- Accelerate version: not installed
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
Hey @reillydonovan, I don't think `StableDiffusionVideoInpaintPipeline` is (yet) part of `diffusers`. Can you add a link where you saw the pipeline?
