### ISSUE TITLE
enable_xformers_memory_efficient_attention not work in T4 GPU for stable-diffusion-v1-5

### ISSUE THREAD

**Issue by tianleiwu** [huggingface/diffusers#2296]
### Describe the bug

Use enable_xformers_memory_efficient_attention get the following error in T4 GPU:
```
ValueError: Operator `memory_efficient_attention` does not support inputs:
     query       : shape=(16, 256, 1, 160) (torch.float16)
     key         : shape=(16, 256, 1, 160) (torch.float16)
     value       : shape=(16, 256, 1, 160) (torch.float16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 128
```

### Reproduction

I used the example code:
```
    import torch
    from diffusers import DiffusionPipeline
    from xformers.ops import MemoryEfficientAttentionFlashAttentionOp
    pipe = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to("cuda")
    pipe.enable_xformers_memory_efficient_attention(attention_op=MemoryEfficientAttentionFlashAttentionOp)
    pipe.vae.enable_xformers_memory_efficient_attention(attention_op=None)
    pipe.unet.to(memory_format=torch.channels_last)
    pipe("test prompts", 512, 512, 50)
```

My environment is python 3.10 in Ubuntu 20.04 with the following package versions:
```
diffusers==0.12.1 (also tested code built from main branch)
transformers==4.26.0
numpy==1.24.1
accelerate==0.15.0
torch==1.13.1+cu117
xformers=0.0.16       (also tested 0.0.17.dev444)
```

I guess probably it need GPU compute capacity 80 or later. If that is the case, need update the document.

### System Info

- `diffusers` version: 0.13.0.dev0
- Platform: Linux-5.15.0-1031-azure-x86_64-with-glibc2.31
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.26.0
- Accelerate version: 0.15.0
- xFormers version: 0.0.16+6f3c20f.d20230208
- Using GPU in script?: T4 GPU
- Using distributed or parallel set-up in script?: No

**Comment by pcuenca** [comment]
Hi @tianleiwu! Thanks for the report. I'm not sure about the requirements of `xFormers` and what features work on what devices. [Their documentation](https://github.com/facebookresearch/xformers#install-troubleshooting) mentions a `TORCH_CUDA_ARCH_LIST` build variable that could help. Did you try to contact them for clarification?

**Comment by tianleiwu** [comment]
I tried diffuers 0.13.0 and build xformers from source, and xformers is now working.
