### ISSUE TITLE
fast-stable-diffusion fine-tuned checkpoints in Diffusers

### ISSUE THREAD

**Issue by kimtaehyeong** [huggingface/diffusers#2299]
### Describe the bug

Hello, 
I wanted to bring up the dreambooth model through the following command.
```
pipe = StableDiffusionPipeline.from_pretrained("./test.ckpt")
```

Valid Error "model_index.json"

The address of the model I learned is fast-dreamboot and I used it at the following address.
"https://github.com/TheLastBen/fast-stable-diffusion"

Is there a way to use the model using Stable Diffusion Pipeline?

Thanks.

### Reproduction

pipe = StableDiffusionPipeline.from_pretrained("./test.ckpt")

### System Info

- `diffusers` version: 0.10.2
- Platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
You first need to convert the checkpoints from the `.ckpt` format to `diffusers` format :-) 
See script here: https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py

**Comment by kimtaehyeong** [comment]
@patrickvonplaten Thank you so much!!
