### ISSUE TITLE
Is there support to convert the `bf16` models from `flax` to `onnx`

### ISSUE THREAD

**Issue by lalith-mcw** [huggingface/diffusers#2300]
Currently the `bf-16` models in https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/bf16/unet & https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/bf16 are all flax models

**Comment by patrickvonplaten** [comment]
You will have to first convert flax to pytorch and then pytorch to onnx I think

**Comment by lalith-mcw** [comment]
@patrickvonplaten thanks for your response, is there any converter for the same ?
Couldn't find within `diffusers/scripts` ?

**Comment by lalith-mcw** [comment]
Will check this and post if there are any https://github.com/huggingface/diffusers/issues/1161#issuecomment-1399582865

**Comment by lalith-mcw** [comment]
`Found ``bfloat16`` weights in Flax model. Casting all ``bfloat16`` weights to ``float32`` before loading those in PyTorch model.`

I do want to load the model in torch `in` bf16 format and save the same ?
Any reasons bf16 models only moved to flax ?

And also the loading ended up in the following error:
`AttributeError: module transformers has no attribute FlaxStableDiffusionSafetyChecker`

In windows[cpu] also there is no jaxlib support

**Comment by patrickvonplaten** [comment]
There is no reason really that the weights exists only for Flax in BF16. We can def also upload them for PyTorch in bfloat16. Maybe the easiest here is actually to just do:

```python
from diffusers import DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.bfloat16)
# convert to ONNX
```

**Comment by patrickvonplaten** [comment]
cc @williamberman

**Comment by lalith-mcw** [comment]
But the safety checker failed with conversion for onnx 
![image](https://user-images.githubusercontent.com/84698958/218516355-e46c4470-c1d9-463e-8cb8-d035cc8b9bfc.png)
