### ISSUE TITLE
Question about alpha in imagic_stable_diffusion

### ISSUE THREAD

**Issue by cyysc1998** [huggingface/diffusers#2301]
Hi, thanks for the excellent work. I have a question about alpha in [imagic](https://github.com/huggingface/diffusers/blob/a7ca03aa85f94574f06576d2155b3ec061fe8d63/examples/community/imagic_stable_diffusion.py#L399). In imgaic paper, the interpolation ratio between $e_{tgt}$ and $e_{opt}$ is (0, 1). However, the ratio is set 1.2 default in [imagic](https://github.com/huggingface/diffusers/blob/a7ca03aa85f94574f06576d2155b3ec061fe8d63/examples/community/imagic_stable_diffusion.py#L399). Is there a deviation in my understanding?
![image](https://user-images.githubusercontent.com/35159700/217782920-f6d02fce-62c3-4e2c-a60c-4a55d1fd182a.png)
![image](https://user-images.githubusercontent.com/35159700/217783051-36a49551-20a0-4ce3-a2f3-ad02308c1062.png)

**Comment by THE-WORLD0** [comment]
I also tried to reproduce the result of this paper, but I found the text embedding optimization seems not to converge, can I have the chance to contact you？

**Comment by cyysc1998** [comment]
Maybe this is the reason for this problem.
![image](https://user-images.githubusercontent.com/35159700/218080655-e844a195-e822-4953-9b7e-0eeb8a107ac0.png)

**Comment by cyysc1998** [comment]
> I also tried to reproduce the result of this paper, but I found the text embedding optimization seems not to converge, can I have the chance to contact you？

You can email me to csun1998f@outlook.com

**Comment by THE-WORLD0** [comment]
@cyysc1998 I have sent an email to you, have you received it? Looking forward to your reply.
