### ISSUE TITLE
StableDiffusion pipelines - negative prompt

### ISSUE THREAD

**Issue by kdziedzic66** [huggingface/diffusers#2307]
Hi,

Maybe I misunderstand something but in most of the stable diffusion pipelines after we embed negative prompt - there is a concatenation of `negative_prompt_embedding` with `prompt_embedding`:

`prompt_embeds = torch.cat([negative_prompt_embeds, prompt_embeds])`

Shouldn't it be rather something like:

`prompt_embeds = torch.cat([-negative_prompt_embeds, prompt_embeds])`

Doesn't it rather reinforce the influence of negative words on the generation ?

**Comment by averad** [comment]
@kdziedzic66 when you applied the change to your code, what differences did you notice in your image generation?

**Comment by kdziedzic66** [comment]
just noticed it - i'm still testing

**Comment by kdziedzic66** [comment]
ok - now i see, the negative sign is applied later in unet inference
