### ISSUE TITLE
LDM Inpainting, LaMA cleaner

### ISSUE THREAD

**Issue by polavishnu4444** [huggingface/diffusers#2310]
### Model/Pipeline/Scheduler description

Hi,
Looking to see if we have any inputs on getting the LDM with inpaint, as that is advanced today with cleaning of image given a mask kind of. Similar to LaMA, ZITS etc.

It would be also great if we could get LaMA, ZITS etc pipelines as well.

### Open source status

- [x] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/CompVis/latent-diffusion/blob/main/scripts/inpaint.py

**Comment by polavishnu4444** [comment]
@patrickvonplaten - Any plan for this?

**Comment by patrickvonplaten** [comment]
I won't have time to look into this sadly. I'm also unsure how much such a model would be used by the community.
