### ISSUE TITLE
Text to Image Finetune Save EMA hook throws error

### ISSUE THREAD

**Issue by samar-khanna** [huggingface/diffusers#2312]
### Describe the bug

I think this commit `f5ccffecf7c9c7b08c39043d1c9528be2c5cfecc` on Feb 7 2023 has introduced a bug where in this function:
```        def save_model_hook(models, weights, output_dir):
            if args.use_ema:
                ema_unet.save_pretrained(os.path.join(output_dir, "unet_ema"))

            for i, model in enumerate(models):
                model.save_pretrained(os.path.join(output_dir, "unet"))

                # make sure to pop weight so that corresponding model is not saved again
                weights.pop()
```
the line `ema_unet.save_pretrained(..)` throws the error:
```ValueError: `save_pretrained` can only be used if `model_cls` was defined at __init__.```

I believe a fix could be to allow the `EMAModel.from_pretrained(..)` method to accept a `subfolder` argument, and then to initialise it like so:
```ema_unet = EMAModel.from_pretrained(args.pretrained_model_name_or_path, UNet2DConditionModel, subfolder="unet")```

### Reproduction

```        def save_model_hook(models, weights, output_dir):
            if args.use_ema:
                ema_unet.save_pretrained(os.path.join(output_dir, "unet_ema"))

            for i, model in enumerate(models):
                model.save_pretrained(os.path.join(output_dir, "unet"))

                # make sure to pop weight so that corresponding model is not saved again
                weights.pop()
```

### System Info

- `diffusers` version: 0.13.0.dev0
- Platform: Linux-5.15.0-1023-aws-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): not installed (NA)
- Huggingface_hub version: 0.12.0
- Transformers version: not installed
- Accelerate version: 0.16.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

**Comment by baeseongsu** [comment]
I also had the same issue. 
To fix it, I temporarily added `model_cls` and `model_config` when defining the `EMAModel`.

```python
# Create EMA for the unet.
if args.use_ema:
    ema_unet = UNet2DConditionModel.from_pretrained(
        args.pretrained_model_name_or_path, 
        subfolder="unet", 
        revision=args.revision
   )
   # update the following code line.
    ema_unet = EMAModel(
        parameters=ema_unet.parameters(), 
        model_cls=UNet2DConditionModel, 
        model_config=ema_unet.config
    )
```

**Comment by trouble-maker007** [comment]
@baeseongsu thanks for share, I also had the same issue

**Comment by patrickvonplaten** [comment]
cc @williamberman

**Comment by williamberman** [comment]
Thanks for the report! Can confirm the error, will have a code change up soon with some tests to catch it :)
