### ISSUE TITLE
Typo in load_pipeline_from_original_stable_diffusion_ckpt() method

### ISSUE THREAD

**Issue by p1atdev** [huggingface/diffusers#2319]
### Describe the bug

Currently it works fine, but I think `inferenc.yaml` should be `inference.yaml`.

https://github.com/huggingface/diffusers/blob/1e7f96544203724652707dc93a7671c90efd3eeb/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L870-L894

### System Info

- `diffusers` version: 0.13.0.dev0
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.9.15
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.26.0
- Accelerate version: 0.16.0
- xFormers version: not installed
- Using GPU in script?: RTX 3070 Ti
- Using distributed or parallel set-up in script?:

**Comment by patrickvonplaten** [comment]
Thanks for opening a PR!
