### ISSUE TITLE
Dreambooth Training not reading instance data

### ISSUE THREAD

**Issue by asahi0130** [huggingface/diffusers#2324]
I am trying to run the Dreambooth Training on my local device from the line command.

However, this gave me a hard time due to the trained weights not generating images like the instance data (pictures of my face). I was trying to troubleshoot this and figured out that the generated images (from the trained weights) are the same no matter what instance data I put. This means that the program is not correctly reading my instance data.
(I tried to use different instance data but it generated the same sample data images)

I tried the same command on Google collab and it worked perfectly fine.

Summary:

Dreambooth training on the local device (line command) not reading the instance data images.

Any help would be appreciated.

Thank you

### Reproduction

1. Download this github repo.
2. Put instance images into ./examples/dreambooth/ALface
3. Change instance_data_dir to the above directory (./ALface) in the script (launch.sh)
4. Check the sample images after the script runs.

### System Info

Platform: Ubuntu 22.04
Python Version: Python 3.10.6
Diffusers: 0.13.0.dev0

**EDIT:**
Additional Info:

The command I run:
`python3 train_dreambooth.py --pretrained_model_name_or_path runwayml/stable-diffusion-v1-5  --instance_data_dir ./ALface --instance_prompt "ALface" --class_prompt "person" --class_data_dir ~/Desktop/classData --output_dir ./ckpt --max_train_steps 800 --learning_rate 1e-6 --mixed_precision fp16 --use_8bit_adam --lr_warmup_steps 0 --lr_scheduler constant --resolution 512 --train_batch_size 1 --gradient_accumulation_steps 1 --gradient_checkpointing --train_text_encoder  --num_class_images 50 --with_prior_preservation --prior_loss_weight 1.0 --sample_batch_size 4`

Things tried:
- Without "use_8bit_adam"
- Made sure the instance_data_dir and _class_data_dir was correct
- Tried increasing train steps
- Tried without train_text_encoder

- Using different versions of dependencies (copied from google colab)

Prompt when generating image: "Photo of ALface person"

Google Colab Result:
![202311](https://user-images.githubusercontent.com/106039754/218528186-66737e96-9eca-4fa0-babf-9bb1b4773c00.png)

Local result:
![2](https://user-images.githubusercontent.com/106039754/218528292-7aedfe58-1bc4-4787-97bb-38e67f418c45.png)
![1](https://user-images.githubusercontent.com/106039754/218528304-2ee7024a-06a2-4f93-a363-358d76cd5697.png)

**Comment by patrickvonplaten** [comment]
@williamberman could you have a look here?

**Comment by williamberman** [comment]
Hey @asahi0130 are you using the latest version of the script from diffusers main? The script should be throwing an error because you're passing --revision=fp16. On the latest version of the script, when we load a unet with non fp32 datatypes.

**Comment by asahi0130** [comment]
> Hey @asahi0130 are you using the latest version of the script from diffusers main? The script should be throwing an error because you're passing --revision=fp16. On the latest version of the script, when we load a unet with non fp32 datatypes.

I’m sorry, the command I am passing above was one of the command I tried when trouble shooting. It still produced the same result without this argument. I’m sorry, I will edit the above command.

**Comment by asahi0130** [comment]
I founed a fix:

Updating xformers to:
xformers 0.0.17.dev442

Worked for me.

**Comment by williamberman** [comment]
Thanks for debugging @asahi0130! We have docs for issues with that xformers version here https://huggingface.co/docs/diffusers/main/en/optimization/xformers . I added a warning message to the training scripts to hopefully make it easier to debug in the future :)

**Comment by rajbala** [comment]
Would one only see this issue of not reading instance data if trying to use xformers during training?

**Comment by williamberman** [comment]
@rajbala in all likelihood, yes. If you have other issues with the training scripts, could you open a separate issue?
