### ISSUE TITLE
[Pipelines] On adding Pix2Pix Zero

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#2328]
[Pix2Pix Zero](https://pix2pixzero.github.io/) presents a wonderful idea for editing the objects in a generated image with finer controls. Some really amazing results:

![image](https://user-images.githubusercontent.com/22957388/218379221-d6b29314-e473-4940-8c41-5d63e5907cba.png)

![image](https://user-images.githubusercontent.com/22957388/218379236-629793e8-3d69-44e9-9865-533522ff0197.png)

The code for Pix2Pix Zero is available here: https://github.com/pix2pixzero/pix2pix-zero. 

IIUC, to add this pipeline to `diffusers` we need the following primary things:

* Changes to cross attention so that the attention weights are [book-kept](https://github.com/pix2pixzero/pix2pix-zero/blob/25b885767bf81fc8bd9e7aa7a2a095ecbebab9db/src/utils/cross_attention.py#L20). 
* The DDIM inversion scheduler (especially if we wanted to condition the pipeline on a real input image).
* Potentially, an inversion pipeline that gives us the inverted noise from the starting image.
* A pipeline that takes in the inverted latent (or some randomly sampled noise if we're not using a real input image) and gives us the edited image back by actually applying the methodology proposed in Pix2Pix Zero. 

I guess it's best to add the following things separately:

* DDIM inversion scheduler
* DDIM inversion pipeline 
* Editing pipeline (including changes to attention)

WDYT? @patrickvonplaten @patil-suraj

**Comment by patrickvonplaten** [comment]
- I don't think we have to change the cross attention, instead we just create a pipeline specific attention processor class inside the pipeline that has a attribute `self.probs` that can be set.
- Yes sounds good to me to create a DDIM inversion scheduler. 
- I would put everything that's needed for editing in one pipeline, no need to create multiple pipelines. 

This pipeline is probably quite similar in its general idea to:
- https://github.com/huggingface/diffusers/pull/2275

**Comment by patil-suraj** [comment]
Thanks a lot for the issue!

- Same comment as Patrick's for the attention weights
- Is the scheduler significantly different from the `DDIMScheduler` ? If there is an example available, could you point to it ?
- Inversiona and editing pipeline can go under same directory.

**Comment by sayakpaul** [comment]
Thanks for your inputs @patrickvonplaten @patil-suraj!

> Is the scheduler significantly different from the DDIMScheduler ? If there is an example available, could you point to it ?

This is [where](https://github.com/pix2pixzero/pix2pix-zero/blob/main/src/utils/scheduler.py) the inversion scheduler is implemented.

**Comment by sayakpaul** [comment]
I would prefer to add `inverse_step()`. This is much more complete IMO.

**Comment by williamberman** [comment]
+1 if it's just the inverse of the actual step I would add it to the existing scheduler

**Comment by sayakpaul** [comment]
We have Pix2Pix Zero in diffusers already. 

https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/pix2pix_zero
