### ISSUE TITLE
When I want to run the inference after training dreambooth, I report an error

### ISSUE THREAD

**Issue by 1235555555shan** [huggingface/diffusers#2332]
### Model/Pipeline/Scheduler description

pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda:3")

prompt = "A photo of a beautiful Asian sks girl"
image = pipe(prompt, num_inference_steps=50, guidance_scale=7.5).images[0]

image.save("dog-bucket.png")

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

![image](https://user-images.githubusercontent.com/85985529/218440478-fde9087a-b13a-4a1d-8a43-5ae1922e0397.png)

**Comment by patrickvonplaten** [comment]
cc @williamberman

**Comment by williamberman** [comment]
@1235555555shan  We actually already have docs for this here https://huggingface.co/docs/diffusers/main/en/training/dreambooth#performing-inference-using-a-saved-checkpoint :)

They were in the README but I'm going to also add them to the cli help message

**Comment by williamberman** [comment]
@1235555555shan I'm going to close the issue given we merged the test and better docs. Feel free to re-open if I missed something or it's not clear. Thanks for the issue report!
