### ISSUE TITLE
callback_steps is typed as Optional[int] but has a default value

### ISSUE THREAD

**Issue by williamberman** [huggingface/diffusers#2343]
In pipelines, we pass both a callback and a callback_steps. callback_steps is always set and has a default value of 1. callback is optional. We always type callback_steps incorrectly as Optional[int] instead of just int. We should update the type signatures of callback_steps.

https://github.com/huggingface/diffusers/pull/2297#discussion_r1101984092

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/pull/2357
