### ISSUE TITLE
Documentation for `KarrasDiffusionSchedulers`

### ISSUE THREAD

**Issue by williamberman** [huggingface/diffusers#2348]
I assume there's a general classification for the types of schedulers that can be added to this type. It would be helpful to add a quick blurb about why certain schedulers qualify as `KarrasDiffusionSchedulers`

**Comment by williamberman** [comment]
@kashif I see you named the type, could you advise here?

**Comment by kashif** [comment]
ok let me check! I can do this issue if its ok?

**Comment by williamberman** [comment]
Yep sure thing :)
