### ISSUE TITLE
OnnxStableDiffusionInpaintPipeline lacks denoise support

### ISSUE THREAD

**Issue by xzuyn** [huggingface/diffusers#2353]
`OnnxStableDiffusionInpaintPipelineLegacy` has support for denoise strength, but `OnnxStableDiffusionInpaintPipeline` does not.

**Comment by patrickvonplaten** [comment]
Hey @xzuyn,

We currently sadly don't have time to add more features to the ONNX pipelines

**Comment by xzuyn** [comment]
dang, ok.
