### ISSUE TITLE
Is there a training script for instruct pix2pix ?

### ISSUE THREAD

**Issue by tengshaofeng** [huggingface/diffusers#2360]
Thanks for your great job. I found a test script for instruct pix2pix , but I cannot find the traning one. Where can I find it. Or do you plan to give that? thank you.

**Comment by patrickvonplaten** [comment]
cc @sayakpaul :-)

**Comment by sayakpaul** [comment]
It's within our plans. Soon :)

**Comment by tengshaofeng** [comment]
> 

Nice. Thank you for your reply.
