### ISSUE TITLE
Text_to_Image finetuning script crashes when trying to save checkpoints

### ISSUE THREAD

**Issue by gianlucaasti** [huggingface/diffusers#2361]
### Describe the bug

Hello everyone,
I want to signal a problem I have found while fine tuning a text_to_image model.
I am a newbie so I might be missing something big.
I have also found a possible workaround to solve it.
I am currently using the guide at this link:

https://huggingface.co/docs/diffusers/training/text2image

to train this specific model:

https://huggingface.co/stabilityai/stable-diffusion-2-1-base

The log shows this error: 

  File "/users/myuser/.local/lib/python3.8/site-packages/diffusers/training_utils.py", line 144, in save_pretrained
    raise ValueError("`save_pretrained` can only be used if `model_cls` was defined at __init__.")
ValueError: `save_pretrained` can only be used if `model_cls` was defined at __init__.
Steps:   3%|▎         | 500/15000 [12:04<5:50:18,  1.45s/it, lr=1e-5, step_loss=0.0391]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24721) of binary: /opt/conda/anaconda3/bin/python3.8

As you can see after 500 steps the model is supposed to save a checkpoint but while it's doing that, it crashes.

I have currently found a workaround:
I haven't figured out the reason why it's showing this error yet, but it seems related to the version of the accelerate library.
If you have accelerate=0.16, downgrading it to accelerate 0.15 will solve this issue.

I hope this might help other people

### Reproduction

accelerate launch /users/myuser/data/ldm/Diffusers/examples/text_to_image/train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$TRAIN_DIR \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --mixed_precision="fp16" \
  --max_train_steps=15000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir=${OUTPUT_DIR}

### Logs

```shell
accelerator.save_state(save_path)
  File "/users/myuser/.local/lib/python3.8/site-packages/accelerate/accelerator.py", line 2026, in save_state
    hook(self._models, weights, output_dir)
  File "/users/myuser/data/ldm/Diffusers/examples/text_to_image/train_text_to_image.py", line 416, in save_model_hook
    ema_unet.save_pretrained(os.path.join(output_dir, "unet_ema"))
  File "/users/myuser/.local/lib/python3.8/site-packages/diffusers/training_utils.py", line 144, in save_pretrained
    raise ValueError("`save_pretrained` can only be used if `model_cls` was defined at __init__.")
Steps:   3%|▎         | 500/15000 [12:04<5:50:18,  1.45s/it, lr=1e-5, step_loss=0.0391]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24721) of binary: /opt/conda/anaconda3/bin/python3.8
```

### System Info

- `diffusers` version: 0.13.0.dev0
- Platform: Linux-4.19.0-17-amd64-x86_64-with-glibc2.10
- Python version: 3.8.12
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.12.0
- Transformers version: 4.26.1
- Accelerate version: 0.16.0
- xFormers version: not installed
- Using GPU in script?: 1 GPU
- Using distributed or parallel set-up in script?: no

- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_name: None
        - tpu_zone: None
        - command_file: None
        - commands: None

**Comment by baeseongsu** [comment]
Please refer to https://github.com/huggingface/diffusers/issues/2312 and https://github.com/huggingface/diffusers/pull/2341

**Comment by patrickvonplaten** [comment]
Sorry for this! Should work now :-)

**Comment by gianlucaasti** [comment]
Dear Patrick and Baeseongsu,
thank you for your help and for linking the other threads, I didn't see them when I opened the bug.
I think we can close the bug :)
