### ISSUE TITLE
How could I convert a LoRA .safetensors or .ckpt file into the format that diffusers can process?

### ISSUE THREAD

**Issue by garyhxfang** [huggingface/diffusers#2363]
### Describe the bug

I got some LoRA model in .safetensors format, and tried to convert in to the format that can be used in diffusers.
But nowhere I can find any document or scripts to achieve that.
So I try to convert the file with the [convert_original_stable_diffusion_to_diffusers.py](https://github.com/huggingface/diffusers/blob/a7ca03aa85f94574f06576d2155b3ec061fe8d63/scripts/convert_original_stable_diffusion_to_diffusers.py) scripts, but it didn't work.
Could somebody provide a guideline or script about how should I covert the LoRAs? 

### Reproduction

python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path /xxx/yyy/zzz.safetensors  --scheduler_type euler-ancestral  --dump_path /aaa/bbb/ccc --from_safetensors

and i got the following error

───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /root/imagine/notebook/convert.py:105 in <module>                            │
│                                                                              │
│   102 │   parser.add_argument("--device", type=str, help="Device to use (e.g │
│   103 │   args = parser.parse_args()                                         │
│   104 │                                                                      │
│ ❱ 105 │   pipe = load_pipeline_from_original_stable_diffusion_ckpt(          │
│   106 │   │   checkpoint_path=args.checkpoint_path,                          │
│   107 │   │   original_config_file=args.original_config_file,                │
│   108 │   │   image_size=args.image_size,                                    │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/diffusers/pipelines/stable_diff │
│ usion/convert_from_ckpt.py:945 in                                            │
│ load_pipeline_from_original_stable_diffusion_ckpt                            │
│                                                                              │
│    942 │   unet_config["upcast_attention"] = upcast_attention                │
│    943 │   unet = UNet2DConditionModel(**unet_config)                        │
│    944 │                                                                     │
│ ❱  945 │   converted_unet_checkpoint = convert_ldm_unet_checkpoint(          │
│    946 │   │   checkpoint, unet_config, path=checkpoint_path, extract_ema=ex │
│    947 │   )                                                                 │
│    948                                                                       │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/diffusers/pipelines/stable_diff │
│ usion/convert_from_ckpt.py:335 in convert_ldm_unet_checkpoint                │
│                                                                              │
│    332 │                                                                     │
│    333 │   new_checkpoint = {}                                               │
│    334 │                                                                     │
│ ❱  335 │   new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dic │
│    336 │   new_checkpoint["time_embedding.linear_1.bias"] = unet_state_dict[ │
│    337 │   new_checkpoint["time_embedding.linear_2.weight"] = unet_state_dic │
│    338 │   new_checkpoint["time_embedding.linear_2.bias"] = unet_state_dict[ │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'time_embed.0.weight'

### System Info

diffusers 0.11.0 python3.8

**Comment by jndietz** [comment]
I would pull down `main` locally, and run `pip install -e .` inside that directory.  That will give you the latest pre-released version of `diffusers`.  Upgrading both `diffusers` and `transformers` resolved some issues for me in regards to going from safetensors/ckpt -> diffusers in the last day.

**Comment by garyhxfang** [comment]
@jndietz Thanks, but do you know is [convert_original_stable_diffusion_to_diffusers.py](https://github.com/huggingface/diffusers/blob/a7ca03aa85f94574f06576d2155b3ec061fe8d63/scripts/convert_original_stable_diffusion_to_diffusers.py) this script the correct way to convert the LoRA file from *.safetensors to diffusers format?

**Comment by jndietz** [comment]
@garyhxfang Based on this:

https://huggingface.co/spaces/diffusers/sd-to-diffusers/blob/main/app.py

It seems like, yes, that would be the correct script.  However, since this is a LoRA, I'm not sure if that is the correct approach.  Are LoRAs merged with a checkpoint the same as a LoRA on its own?  I'm not sure.  It's worth a shot.  You'll have to provide something for `--original_config_file`, which perhaps the original SD 1.5 yaml will work?  All hypothetical - it's worth trying.

**Comment by jndietz** [comment]
I just tried to do this with a LoRA that was downloaded from civitai.  I wasn't sure what to provide for the `original_config_file` because those never come with one, but here is my output:

```
(ldm) ubuntu@ip-172-31-6-102:/dietz-scripts$ ./hf-convert-ckpt-to-diffusers.sh /models/some_civitai_lora.safetensors /stable-diffusion-webui/models/Stable-diffusion/stable-diffusion-v1-5/v1-inference.yaml /output/test
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 125, in <module>
    pipe = load_pipeline_from_original_stable_diffusion_ckpt(
  File "/diffusers/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 976, in load_pipeline_from_original_stable_diffusion_ckpt
    checkpoint = torch.load(checkpoint_path, map_location=device)
  File "/home/ubuntu/miniconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/miniconda3/envs/ldm/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xb9'.

```

**Comment by garyhxfang** [comment]
@jndietz  Thanks, let me have a try again.

**Comment by garyhxfang** [comment]
Still cannot convert the safetensors LoRA file, can @patrickvonplaten  have a check on this issue?
As LoRA model become more and more popular recently, more over, the communities get used to share LoRA file in safetensors or ckpt format, I think it's quite important that we have an convenient approach/script to convert the LoRA file to something diffusers can process.

Also I found that we don't have solution on convert/load the textual inverse embedding in .pt format, I spent all they searching for the solution but doesn't find any approach.

**Comment by patrickvonplaten** [comment]
Hey @garyhxfang ,


Note that the conversion script you used won't work as it expects a full model checkpoint. Could you upload your LoRA embeddings somewhere so that we could write a new conversion script? 

How did you get the LoRA checkpoints for this? Which notebook did you use for training?

**Comment by garyhxfang** [comment]
Thanks a lot for your response! @patrickvonplaten 

I download the LoRA file from civitai.com, you can also have a check on the website, it is one of the most important websites/communities that people share their stable diffusion and LoRA models. I think many of them train the LoRA model with AUTOMATIC111/stable-diffusion-webui.

The LoRA model I would like to convert are
https://civitai.com/models/7448/korean-doll-likeness
and
https://civitai.com/models/7716/taiwan-doll-likeness
I also upload it to hf 
https://huggingface.co/garyfang/LoRA_Collection/tree/main

Since many many popular LoRA models are shared in .safetensors format, and the end users love LoRA very much as it really perform very well in generating great images, it's quite important for us developers that diffusers could have a generic approach/script to convert the .safetensors LoRA models into the format can be loaded by diffusers. So that developers using diffusers could make use of these great models already in the communities to build better models or applications. 
Currently the next release of my application really need these LoRAs to be embedded to the model, it will be so great if we could get support from your side to achieve that.

Thanks very much.

**Comment by patrickvonplaten** [comment]
BTW this seems related: https://github.com/huggingface/diffusers/issues/2326

**Comment by dkackman** [comment]
> it's quite important for us developers that diffusers could have a generic approach/script to convert the .safetensors LoRA models > into the format can be loaded by diffusers.

Better yet, support `.safetensors` LoRA models directly

**Comment by Skquark** [comment]
I ran into this too trying to load or convert LatentLabs360 safetensors LoRA file so I can use it with the new Panorama pipeline, but no matter what I tried in the convert script or loading pretrained, I couldn't get it to work.  Model is here https://civitai.com/models/10753/latentlabs360 if anyone wants to try...

**Comment by sunhaha123** [comment]
> I ran into this too trying to load or convert LatentLabs360 safetensors LoRA file so I can use it with the new Panorama pipeline, but no matter what I tried in the convert script or loading pretrained, I couldn't get it to work. Model is here https://civitai.com/models/10753/latentlabs360 if anyone wants to try... I now see that convert_lora_safetensor_to_diffusers.py is being worked on, so I guess I can wait for that to get merged.

look this:  https://github.com/kohya-ss/sd-scripts/blob/main/networks/merge_lora_old.py

**Comment by khimaros** [comment]
this script may be useful in the meantime: https://github.com/huggingface/diffusers/blob/75501a37157da4968291a7929bb8cb374eb57f22/scripts/convert_lora_safetensor_to_diffusers.py

**Comment by ProGamerGov** [comment]
So it it currently possible to train a LoRA model for SD 2.1 and then convert it to a safetensor or ckpt/pt?


I see this PR added a safetensor to diffusers script, but what about the reverse? https://github.com/huggingface/diffusers/pull/2403

**Comment by Micheal-Liuu** [comment]
@jndietz @garyhxfang Hi, I am a real novice for coding and AIGC, and all I know about Python is its basic syntax. I can't understant what is "pull down `main` ".  Can you tell me how to fix this problem in more concrete way, or it's an unresolvable problem that we can't convert lora model through this way.  Thank you so much! I will try other models other than lora before recieving your anwser.

**Comment by patrickvonplaten** [comment]
Hey @garyhxfang, 

We just added a `from_ckpt` loading function which should help: https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline.from_ckpt

**Comment by innat-asj** [comment]
quick summarize

- `.safetensor` to `.bin` -> https://github.com/huggingface/diffusers/issues/2829#issuecomment-1510160066
    - `pipeline.unet.load_attn_procs("pt_state_dict.bin")`
    - `pipeline.unet.load_attn_procs("pt_state_dict.safetensors")`
- `.bin` to `.safetensor` -> https://github.com/huggingface/diffusers/issues/2866#issuecomment-149559946
- [`from_ckpt`](https://github.com/huggingface/diffusers/blob/7e6886f5e93ca9bb1e6d4beece46fe1e43b819c2/src/diffusers/loaders.py#L1060) -> supports `.safetensor` , `.ckpt` (full model with/without lora)

cc. @sayakpaul

**Comment by athenawisdoms** [comment]
When I try `pt_state_dict = safetensors.torch.load_file(model_filepath, device="cpu")` I get the error 

> AttributeError: module 'safetensors' has no attribute 'torch'

I'm currently using `git+https://github.com/ShivamShrirao/diffusers.git@2933b6b20b77c07ca7f8d7248cf9fc1ab2668bfc`. Is there a quick way to add this functionality into my current environment?

**Comment by sayakpaul** [comment]
Could you update safetensors to the latest stable version and retry?

**Comment by athenawisdoms** [comment]
@sayakpaul Getting the same error with the latest safetensors stable v0.3.0...

```
$ pip freeze | egrep 'safetensors|diffusers|torch'
diffusers==0.15.1
safetensors==0.3.0
torch==2.0.0
torchvision==0.15.1
```

Alternatively is there a huggingspace space that can perform this conversion to a .bin file?

**Comment by innat-asj** [comment]
actions-github

**Comment by patrickvonplaten** [comment]
Gentle ping here @sayakpaul - this is also related to the other LoRA issues no? E.g.: https://github.com/huggingface/diffusers/issues/2326#issuecomment-1532171432

**Comment by sayakpaul** [comment]
Maybe the https://github.com/huggingface/diffusers/pull/3490 PR will fix this. Will see. CC: @garyhxfang @athenawisdoms

**Comment by liuchangzong** [comment]
Maybe you can try this:
[convert_lora_safetensor_to_diffusers.py(https://github.com/huggingface/diffusers/blob/main/scripts/convert_lora_safetensor_to_diffusers.py)
Acutal I am confused about how to convert custom_models.safetensors to  diffusers

**Comment by sayakpaul** [comment]
Gentle ping in the issue to see if this is still an issue given all the above discussions considered.

**Comment by the-APM** [comment]
can someone summerize and point to the real solution (if implemented yet) as a bookend to the discussion?

**Comment by sayakpaul** [comment]
See if this section of the documentation helps:
https://huggingface.co/docs/diffusers/main/en/training/lora#supporting-different-lora-checkpoints-from-diffusers

**Comment by HG2407** [comment]
How fascinating! This is my first time seeing a new feature being requested and it being added, from start to finish. Wow !
