### ISSUE TITLE
Add support for converting inpainting,instruct-pix2pix,etc models

### ISSUE THREAD

**Issue by reimager** [huggingface/diffusers#2379]
The conversion scripts can convert ckpt and safetensors models to diffusers format, but it does not work for inpainting or instruct-pix2pix models:

Example: Using this safetensors file: https://huggingface.co/stabilityai/stable-diffusion-2-inpainting/blob/main/512-inpainting-ema.safetensors

`python3 convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ~/512-inpainting-ema.safetensors --from_safetensors --dump_path ~/512-inpainting-ema`

Results in an error: 

`
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
	size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
`

Similar for instruct-pix2pix (except different size obv)

`
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
	size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
`

If I'm missing something obvious, my apologies.

**Comment by patrickvonplaten** [comment]
Hey @reimager,

Thanks for the issue and very sorry to answer so late. Could you try to add the line: 
```
--num_in_channels 8
```

to the conversion script, this should make it work, I believe :-) See:
https://github.com/huggingface/diffusers/blob/f7278638e48d4a2e6c619d08078a3a622e4db438/scripts/convert_original_stable_diffusion_to_diffusers.py#L36

**Comment by reimager** [comment]
@patrickvonplaten You are correct - its even in the help. My apologies!

**Comment by patrickvonplaten** [comment]
All good - always good to ask so that the next reader has a reference :-)

**Comment by satwiksunnam19** [comment]
I have an issue with converting inpainting ckpt to diffusers format and I'm attaching a relative image which is causing error , can anyone help with the potential solution  
![image](https://user-images.githubusercontent.com/83942187/231502309-0a9b57d8-b3f8-4272-b8e1-aff3f631a3ea.png)
