### ISSUE TITLE
How to remove Logs，

### ISSUE THREAD

**Issue by zhanghongyong123456** [huggingface/diffusers#2394]
I want to use pyinstaller to package as exe without cmd command line
![image](https://user-images.githubusercontent.com/48466610/219591814-fd79322c-a459-48be-a5d9-00eedca5d134.png)

**Comment by sayakpaul** [comment]
Thanks for reporting.

@patrickvonplaten @williamberman WDYT? Seems like https://github.com/huggingface/transformers/issues/21506#issuecomment-1430722571 proposes a fix.

**Comment by patrickvonplaten** [comment]
Hmm, maybe can we just disable the logger for diffusers globally? Shouldn't this work? 
See docs here: https://huggingface.co/docs/diffusers/api/logging

**Comment by sayakpaul** [comment]
Hi @zhanghongyong123456. Were you able to disable logging with https://github.com/huggingface/diffusers/issues/2394#issuecomment-1455906251 ? If so, do you mind closing the issue? If not, please let us know.
