### ISSUE TITLE
pre-trained stable diffusion model taking 4min to generate an image 

### ISSUE THREAD

**Issue by HEGADE** [huggingface/diffusers#2411]
hi , I'm trying to generate an image from a prompt using the Stable-Diffusion-v1-5 model,and I'm using NVidia GeForce GTX 1650 , to create an image it's taking 4 min, is it normal? or I did something wrong?, how can I improve the performance

**Comment by haofanwang** [comment]
(1) make sure you do put your model on GPU correctly
(2) use float16

**Comment by HEGADE** [comment]
Okay tq

**Comment by sayakpaul** [comment]
@haofanwang thanks for sharing your thoughts. 

@HEGADE could you close the issue if https://github.com/huggingface/diffusers/issues/2411#issuecomment-1435512428 resolved your problem?

**Comment by HEGADE** [comment]
issues  resolved thank you for the support
