### ISSUE TITLE
"NameError: name 'transformers' is not defined" when i load model from hub

### ISSUE THREAD

**Issue by WiNE-iNEFF** [huggingface/diffusers#2414]
### Describe the bug

An error occurs when trying to load any model from the hub:
```
[/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/pipeline_utils.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    826 
    827                 is_diffusers_model = issubclass(class_obj, diffusers.ModelMixin)
--> 828                 transformers_version = version.parse(version.parse(transformers.__version__).base_version)
    829                 is_transformers_model = (
    830                     is_transformers_available()

NameError: name 'transformers' is not defined
```
How to solve this problem?

### Reproduction

```
!pip install -qq diffusers datasets

image_pipe = DDPMPipeline.from_pretrained("google/ddpm-cifar10-32").to(device);
```

### System Info

Google Colab,
diffusers in /usr/local/lib/python3.8/dist-packages (0.13.0)
datasets in /usr/local/lib/python3.8/dist-packages (2.9.0)

**Comment by haofanwang** [comment]
it seems that you have not installed transformer.

**Comment by WiNE-iNEFF** [comment]
> it seems that you have not installed transformers. I have made to PR to fix this typo.
> 
> `pip install transformers `

already tried, it was 0 sense

**Comment by haofanwang** [comment]
Cannot reproduce your problem after install transformers. Could you import transformers successfully?
