### ISSUE TITLE
Is it good to train on 512x512, inference on 512x768?

### ISSUE THREAD

**Issue by tengshaofeng** [huggingface/diffusers#2429]
Thank you for your great job. It is really useful for me. I want to inference with resolution of 512x768. I know I could do that with the model trained on 512x512. But to get the best performance on both 512x512 and 512x768, should I trained on 512x512 or 512x768 or 768x768. I'd appreciate your advise.

**Comment by sayakpaul** [comment]
In our experiments, if there is a resolution discrepancy, then the performance usually degrades quite a bit i.e., if you fine-tune on a custom dataset with a different resolution, then the quality of the generated images might not be on par. Usually, the number of training images seen during fine-tuning dictates this performance. 

If an upscaled resolution is a requirement for you, would mind trying out the latent upscaler model we recently introduced? You can find an application of it in this Space: https://huggingface.co/spaces/huggingface-projects/stable-diffusion-latent-upscaler/blob/main/app.py. 

Cc: @yiyixuxu

**Comment by tengshaofeng** [comment]
@sayakpaul ,thanks so much for your reply. So if I want to finetune the sd-1.5 with 200k images, and most of the image is resolution of 512x768. In accordance with what you said, to get the best performance on 512x768, maybe training on 512x768 is better? BTW, thanks for your  latent upscaler model, I will try it later.

**Comment by sayakpaul** [comment]
Yes, sure, worth giving it a try but I just wanted to share our experience to make you aware of the poor results that might arise :)

**Comment by tengshaofeng** [comment]
@sayakpaul 
![image](https://user-images.githubusercontent.com/9246739/220049034-091814fb-50c7-434e-b685-d1863ff90d71.png)
![image](https://user-images.githubusercontent.com/9246739/220049043-243eb388-1d8d-4409-97df-b48336e17a2b.png)
I try the app of upscaler, it is not good yet, maybe worse than real-esrgan. Did the result I show is right? prompt="(portrait:1.0),face in the center, Mage godess with white hair and mage god with black hair, pale skin, fantasy, in love, couple, hug each other,  sharp focus, intricate, elegant, illustration, ambient lighting, art by stefanie law, qistina khalidah, tranding on artstation, art by luis royo higly detailed studio lighting"

**Comment by sayakpaul** [comment]
It's happening probably because of the discrepancy between the training data. So, I guess your best bet for now is to fine-tune the model or use something like [MultiDiffusion](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/panorama). Cc: @omerbt

**Comment by tengshaofeng** [comment]
@sayakpaul Thanks so much.

**Comment by omerbt** [comment]
Hi! indeed as @sayakpaul mentioned, even though StabelDiffusion can technically process higher resolution images, we observed that many times it produces poor quality outputs (it is out-of-distribution w.r.t its training data).[MultiDiffusion](https://multidiffusion.github.io/) tackles this and allows to generate high-quality images at arbitrary aspect ratio. See [this documentaion](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/panorama) for how to use it through diffusers.

**Comment by tengshaofeng** [comment]
@omerbt @patrickvonplaten thanks for your reply,guys. I learned so much. Thanks again.
