### ISSUE TITLE
A bug in multiple gpu training

### ISSUE THREAD

**Issue by kangxi1818** [huggingface/diffusers#2435]
### Describe the bug

when train this code with multiple gpu
![截屏2023-02-20 下午9 37 27](https://user-images.githubusercontent.com/117744200/220123319-7c056709-84db-4b2f-b047-2b79dcfa0dbb.png)
I got a bug like this
![截屏2023-02-20 下午9 38 48](https://user-images.githubusercontent.com/117744200/220123555-923071d6-984e-4841-871b-87bd29a4fe9a.png)

### Reproduction

I just mutify this code
![截屏2023-02-20 下午9 40 14](https://user-images.githubusercontent.com/117744200/220123841-99f30993-f6f8-442d-a318-e7388dcef691.png)
change num_processes=1 to num_processes=2
before this bug another bug is like that 
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
I change the 'fork' to 'spawn' like that
![截屏2023-02-17 下午4 37 21](https://user-images.githubusercontent.com/117744200/220125213-6ebdbae8-0e09-48d9-ba27-0c0917825dc1.png)

### System Info

![截屏2023-02-20 下午9 50 21](https://user-images.githubusercontent.com/117744200/220125890-1a46d6ee-14c1-47d9-841c-00e9294a0d28.png)
![截屏2023-02-20 下午9 50 39](https://user-images.githubusercontent.com/117744200/220125902-038be528-15c3-4934-b3ae-a151932835ef.png)
platform in jupyter notebook

**Comment by patrickvonplaten** [comment]
Hey @kangxi1818,

I don't think it's possible to run training code on multi-process on a google colab as a google colab only always has 1 GPU.
