### ISSUE TITLE
About the fourier time embedding type

### ISSUE THREAD

**Issue by WHan-alter** [huggingface/diffusers#2438]
Dear Develops,

I noticed that in 
 https://github.com/huggingface/diffusers/blob/17ecf72d4472f5dc11e7c86841c95898f6edbc0b/src/diffusers/models/unet_2d.py#L307-#L309, you scaled the samples with the timestep when the time embedding type is fourier. But you did not apply such normalization for the unet2d_condition and unet1d model. What are the differences between the scaled and the original sample? Yang Song's ScoreSDE has similar functions (they used the marginal prob std to normalize the model output). But I still need to get your idea regarding this.

Best,
Wenkai

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @WHan-alter,

Yes exactly the only reason we do this for the Unet2D model is because Yang Song's ScoreSDE does it.

**Comment by sayakpaul** [comment]
@WHan-alter could we close this issue if https://github.com/huggingface/diffusers/issues/2438#issuecomment-1456100320 makes sense?

**Comment by WHan-alter** [comment]
Thank you very much for your response! It resolves my concern.
