### ISSUE TITLE
Add information for contributors on how to apply code formatter

### ISSUE THREAD

**Issue by hysts** [huggingface/diffusers#244]
**Is your feature request related to a problem? Please describe.**

I don't know how we are supposed to apply code formatters. I found settings for `black`, `isort` and `flake8` in `pyproject.toml` and `setup.cfg`, but it doesn't seem to be used. When I apply `isort` to the `main` branch, it changes codes. I think code formatters are not applied properly.

**Describe the solution you'd like**

It'd be nice if there's information for contributors like this one: https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md
Also, I'd like to suggest using [`pre-commit`](https://pre-commit.com/).

**Comment by anton-l** [comment]
Hi @hysts, we're working on a `CONTRIBUTING.md` guide at the moment, but until then you can apply the style changes by running `make style` from the repo's root, and `make quality` for other checks.

**Comment by hysts** [comment]
Hi, @anton-l 
I see. Thanks.
BTW, I just noticed that the `scripts` directory is not included in `check_dirs`, but is this intended? I'm wondering why it's excluded.
https://github.com/huggingface/diffusers/blob/47893164ab569ff5f6bd142896195051f9ffb200/Makefile#L6

**Comment by anton-l** [comment]
@hysts the `scripts` folder was intended for quick experiments and debugging scripts at first, but I think we can add it too at this point. I'll open a quick PR for that :)
