### ISSUE TITLE
[SD2.1] - Input shapes for unet model

### ISSUE THREAD

**Issue by lalith-mcw** [huggingface/diffusers#2443]
Trying to run via Openvino IR - inferencing a pixelated image currently 

Input Nodes for SD2.1:
sample - [2,4,64,64],timestep [-1] and encoder_hidden_states [2,77,1024]

Still I do get the inferenced image as 512x512 since vae_decoder takes latents input of shape 512x512 and that results in a pixelated image. What are the shapes used for the above three nodes for proper inferencing
![image.png](https://s3.amazonaws.com/moonup/production/uploads/1676897046949-63a031c0f3334a6553d2e01a.png)

Input Nodes for SD1.4:
sample - [2,4,64,64],timestep [-1] and encoder_hidden_states [2,77,768] 

With these inputs the output was proper for SD1.4 models also tried using the `DPMSolverMultistepScheduler` for SD2.1 still the output is the same.

Saw somewhere the encoder_hidden_states blob shape was updated ? What are the right dimensions to be used ?

**Comment by sayakpaul** [comment]
As you can see [here](https://huggingface.co/stabilityai/stable-diffusion-2-1/blob/main/text_encoder/config.json#L11) that the encoder hidden state dimension for SD v2.1 is 1024 whereas for SD v1.4 it is 768 (see [here](https://huggingface.co/CompVis/stable-diffusion-v1-4/blob/main/text_encoder/config.json#L11)).   

These dimensions are not meant to be changed.

**Comment by lalith-mcw** [comment]
@sayakpaul used the same only. Mentioned it wrongly as SD2.1 which has 768

**Comment by lalith-mcw** [comment]
@tianleiwu any thoughts on this ?

**Comment by sayakpaul** [comment]
Could this be surfacing from the IR engine you are using? Does the same pipeline produce same results if run on, say, Colab?

**Comment by lalith-mcw** [comment]
Checking in local only as of now

**Comment by tianleiwu** [comment]
@lalith-mcw, input and output shapes of 2.1 unet ONNX model:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/30328909/222092665-c29be07a-0012-4c7c-9abe-48ff24159791.png">

**Comment by patrickvonplaten** [comment]
Maybe also cc @echarlaix FYI

**Comment by sayakpaul** [comment]
Hi folks!

@echarlaix recently added support for OpenVINO-optimized inference for StableDiffusion from `optimum`:

https://huggingface.co/docs/optimum/intel/inference#export-and-inference-of-stable-diffusion-models
