### ISSUE TITLE
train_dreambooth_inpaint.py throwing "returned non-zero exit status 1" error

### ISSUE THREAD

**Issue by lakshman111** [huggingface/diffusers#2444]
### Describe the bug

@thedarkzeno @patil-suraj 

I've been running train_dreambooth_inpaint.py from https://github.com/huggingface/diffusers/tree/main/examples/research_projects/dreambooth_inpaint for the last few days with the same environment configurations.  Today I ran it again and got:

Traceback (most recent call last):
  File "train_dreambooth_inpaint.py", line 825, in <module>
    main()
  File "train_dreambooth_inpaint.py", line 421, in main
    accelerator = Accelerator(
TypeError: __init__() got an unexpected keyword argument 'accelerator_project_config'
Traceback (most recent call last):
  File "/usr/local/envs/laksh/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/envs/laksh/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/envs/laksh/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/usr/local/envs/laksh/lib/python3.8/site-packages/accelerate/commands/launch.py", line 552, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/envs/laksh/bin/python', 'train_dreambooth_inpaint.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-inpainting', '--instance_data_dir=/workspace/diffusers/examples/research_projects/dreambooth_inpaint/modern_512_images', '--output_dir=/workspace/diffusers/examples/research_projects/dreambooth_inpaint/modern_512_400steps_model', '--instance_prompt=a photo of mmodern furniture', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=400']' returned non-zero exit status 1.

### Reproduction

1. SSH into GPU
2. Create a conda environment: conda create -n YOUR_ENV_NAME python=3.8
3. Activate the session: source activate YOUR_ENV_NAME
4. CD into https://github.com/huggingface/diffusers/tree/main/examples/research_projects/dreambooth_inpaint
5. pip install -r requirements.txt
6. pip install git+https://github.com/huggingface/diffusers
7. Run the first code snippet with custom inputs (my code is below)

`export MODEL_NAME="runwayml/stable-diffusion-inpainting"
export INSTANCE_DIR="/workspace/diffusers/examples/research_projects/dreambooth_inpaint/modern_512_images"
export OUTPUT_DIR="/workspace/diffusers/examples/research_projects/dreambooth_inpaint/modern_512_400steps_model"

accelerate launch train_dreambooth_inpaint.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of mmodern furniture" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=400`

### System Info

- `diffusers` version: 0.14.0.dev0
- Platform: Linux-5.15.0-47-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.12.1
- Transformers version: 4.26.1
- Accelerate version: 0.16.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by lakshman111** [comment]
Solved!  I changed "accelerator_project_config" to "project_config" and it worked.  Looks like the variable Accelerate is looking for is "project_config": https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py

Didn't get around to submitting a PR yet.  I've never submitted one, so need to still read through the guidelines on how to do that.

**Comment by sayakpaul** [comment]
Thanks and glad that it got resolved!

**Comment by kadirnar** [comment]
> Solved! I changed "accelerator_project_config" to "project_config" and it worked. Looks like the variable Accelerate is looking for is "project_config": https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py
> 
> Didn't get around to submitting a PR yet. I've never submitted one, so need to still read through the guidelines on how to do that.

Thank you. This error should be fixed immediately.  @thedarkzeno @patil-suraj

**Comment by sayakpaul** [comment]
@lakshman111 could we close this issue?

**Comment by kadirnar** [comment]
> @lakshman111bu konuyu kapatabilir miyiz?

No. The error still persists. It needs to be fixed. If you want, I can do it.

**Comment by patrickvonplaten** [comment]
> > @lakshman111bu konuyu kapatabilir miyiz?
> 
> No. The error still persists. It needs to be fixed. If you want, I can do it.

That'd be very nice!
