### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by qwapilot** [huggingface/diffusers#2453]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sayakpaul** [comment]
We have dedicated doc here:  https://huggingface.co/docs/diffusers/main/en/conceptual/contribution

**Comment by patrickvonplaten** [comment]
Hey @qwapilot, I'm also working on a more extensive guide for exactly this question! Should be merged in like 2 weeks :-) 
https://github.com/huggingface/diffusers/pull/2043
