### ISSUE TITLE
img2img style transfer

### ISSUE THREAD

**Issue by Jason-kid** [huggingface/diffusers#2457]
For style transfer using the img2img function, does the input image need to be resized?
For example, using sd-2-1-base, any image size input will always produce completely unusable results.
Have any suggestions? Thanks

**Comment by sayakpaul** [comment]
Is it always the case for different checkpoints? I have not tried performing style transfer with that pipeline so tagging @yiyixuxu @patil-suraj to check if they have any suggestions. 

Also, if you could provide some code snippet that we could use to try this out, that would be great!

**Comment by XiangZhu0718** [comment]
> 
yes, any image size (less than 512) may roduce completely unusable results.
should i resize to 512* 512 as the original sd-2-1-base output ?

class inference_img2img():
    def __init__(self,model_id):
        scheduler = LMSDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
        pipe = StableDiffusionImg2ImgPipeline.from_pretrained(model_id, 
                                                              scheduler=scheduler, 
                                                              torch_dtype=torch.float16)
        self.pipe = pipe.to("cuda")
        
    def infer(self, img2img_opt):
        generator = torch.Generator(device="cuda").manual_seed(img2img_opt.seed)
        response = requests.get(img2img_opt.url)
        init_image = Image.open(BytesIO(response.content)).convert("RGB")
        output = self.pipe(prompt=img2img_opt.prompt,
                           guidance_scale=img2img_opt.guidance_scale,
                           num_inference_steps=img2img_opt.num_inference_steps,
                           generator=generator, 
                           image=init_image, 
                           strength=img2img_opt.strength)
        image = output.images[0]
        hasNSFW = output.nsfw_content_detected
        name = img2img_opt.prompt[:32] + '.png'
        path = os.path.join('outputs/img2img-samples', name)
        image.save(path)
        return path, name, hasNSFW

    model_id = "./stable-diffusion-2-1-base"
    opt = img2img_parser()
    instance = inference_img2img(model_id)
    instance.infer(opt)

**Comment by yiyixuxu** [comment]
Thanks for reporting the issue! 🤗

Could you provide a reproducible example?  - the code example you provided is not self-contained and relies on external data and variables, so it is hard for us to understand what's wrong

**Comment by XiangZhu0718** [comment]
> Thanks for reporting the issue! 🤗
> 
> Could you provide a reproducible example? - the code example you provided is not self-contained and relies on external data and variables, so it is hard for us to understand what's wrong

model_id_or_path = "./stable-diffusion-2-1-base"
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(model_id_or_path, torch_dtype=torch.float16)
pipe = pipe.to("cuda")
url = "a Personal Photo"
response = requests.get(url)
init_image = Image.open(BytesIO(response.content)).convert("RGB")
prompt = "A photo of person, anime style"
images = pipe(prompt=prompt, image=init_image, strength=0.5, guidance_scale=7.5, num_inference_steps=50).images
