### ISSUE TITLE
Code quality check fails even after running 'make style' and 'make quality'.

### ISSUE THREAD

**Issue by lukovnikov** [huggingface/diffusers#2460]
I was making a PR and ran `make style`and `make quality`, resolved all issues but CI still tells me something is wrong with the new script I'm trying to contribute.

**Comment by haofanwang** [comment]
I have the same issue. It seems to be problematic of CI, so don't worry.

**Comment by sayakpaul** [comment]
Sorry it seems to be problematic. 

Could you please ensure the virtual environment you're using to run `make style` and `make quality` has the updated Python dependencies?
