### ISSUE TITLE
Stable diffusion finetuning support for IterableDataset

### ISSUE THREAD

**Issue by samar-khanna** [huggingface/diffusers#2462]
**Is your feature request related to a problem? Please describe.**

For `examples/text_to_image/train_text_to_image.py`, I am trying to load a `webdataset` which is an `IterableDataset` that doesn't have the `__len__` property. While I can hack around the code to make it work, it would be very useful to have support for these types of datasets.

**Describe the solution you'd like**

Support for `IterableDataset` or `webdataset` in the finetuning script.

**Describe alternatives you've considered**

**Additional context**

**Comment by sayakpaul** [comment]
Hi!

While I agree that this support would be nice but our example scripts are meant to be easy-to-follow along and focus on the task at hand. We strive to do that being as minimal as possible but without missing out on the important implementation details. 

So, we don't anticipate integrating the `webdataset` support for the time being.
