### ISSUE TITLE
[Examples] `checkpoints_total_limit` seems to be not limiting

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#2466]
### Describe the bug

We introduced `checkpoints_total_limit` in the examples in https://github.com/huggingface/diffusers/pull/2374. 

Setting it, however, doesn't limit the number of checkpoints being preserved. Is that expected? 

### Reproduction

```bash
accelerate launch examples/text_to_image/train_text_to_image.py \
    --pretrained_model_name_or_path hf-internal-testing/tiny-stable-diffusion-pipe \
    --dataset_name hf-internal-testing/dummy_image_text_data \
    --resolution 64 \
    --center_crop \
    --random_flip \
    --train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --max_train_steps 8 \
    --learning_rate 5.0e-04 \
    --scale_lr \
    --lr_scheduler constant \
    --lr_warmup_steps 0 \
    --output_dir "temp_dir" \
    --checkpointing_steps=2 \
    --checkpoints_total_limit=3 \
    --seed=0
```

### System Info

```
- `diffusers` version: 0.14.0.dev0
- Platform: Linux-4.19.0-23-cloud-amd64-x86_64-with-glibc2.10
- Python version: 3.8.15
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.26.1
- Accelerate version: 0.16.0
- xFormers version: 0.0.16rc424
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
```

**Comment by sayakpaul** [comment]
Cc: @williamberman

**Comment by xiankgx** [comment]
Hi, I'm experiencing this bug too on 0.14.0.dev0. How can I fix it?

**Comment by williamberman** [comment]
hm interesting, afaik that's the accelerate api

**Comment by xiankgx** [comment]
The instantiating of the `ProjectConfiguration `is missing the parameter `automatic_checkpoint_naming `.
https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py#L346

![image](https://user-images.githubusercontent.com/4113258/222111673-aaf0adc7-3941-435b-a203-d6c2c60ddef0.png)

**Comment by sayakpaul** [comment]
I don't think that should influence the checkpoint limiting behavior, though.

**Comment by Ttl** [comment]
`automatic_checkpoint_naming` should be set for `total_limit` to have an effect: https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L2107-L2122

**Comment by pcuenca** [comment]
Very interesting, @Ttl, thanks a lot for digging into this! Would you like to submit a PR? @williamberman @sayakpaul I think it's ok to have accelerate use the naming, isn't it?

**Comment by williamberman** [comment]
Ok so it would make sense that accelerate would have to handle the naming convention or do some internal metadata tracking to know the order that checkpoints were saved. 

The **diffusers scripts and accelerate handle naming conventions of checkpoint files differently**. We save files **suffixed with the global step**. Accelerate saves files **suffixed with an internal counter** of the number of times accelerate has had save_state called.

Luckily, the **accelerate convention will still let us know latest checkpoint** for when we want to resume from latest (Ideally we shouldn't have to rely on the naming convention for this but this isn't bad imo). 

However, we still **use the suffix on the filename to determine the global step** to resume training at. Relying on the naming convention of the filename isn't ideal for storing the training step. I think we should **explicitly save the global step as metadata in the checkpoint directory with a save_model_hook** and also **let accelerate handle the checkpoint filenaming**.

**Comment by williamberman** [comment]
We should use the https://huggingface.co/docs/accelerate/v0.16.0/en/package_reference/accelerator#accelerate.Accelerator.register_for_checkpointing on a general training state object for any general training data that should be saved when we checkpoint

**Comment by sayakpaul** [comment]
> We should use the https://huggingface.co/docs/accelerate/v0.16.0/en/package_reference/accelerator#accelerate.Accelerator.register_for_checkpointing on a general training state object for any general training data that should be saved when we checkpoint

I think we only need to do it for things that we don't pass to `prepare()`. EMA'd objects are a good example of that. 

The `transformers` training scripts (that don't leverage `Trainer`) also does this:

https://github.com/huggingface/transformers/blob/b90fbc7e0ba41dfd6b343e7e2274443f19087f36/examples/pytorch/language-modeling/run_mlm_no_trainer.py#L696

Given this is an important feature, I suggest let's go with 

> also let accelerate handle the checkpoint filenaming.

and do any refactoring that is needed which I think will be simple enough. Does it make sense to also implement test cases for the checkpointing limit?

**Comment by Ttl** [comment]
It's important to note that this functionality only works correctly in accelerate version 0.17 and later. https://github.com/huggingface/accelerate/issues/1163

**Comment by williamberman** [comment]
Ok yes let's refactor to support the checkpoint limit. I don't think we should add test cases as it's something accelerate themselves should be testing. I think this ended up being a "bug" because I used the api wrong :grin:

**Comment by patrickvonplaten** [comment]
Can we try to fix this, @williamberman or @sayakpaul do you have some time?

**Comment by williamberman** [comment]
taking a look

**Comment by eliphatfs** [comment]
After some digging up I found that the limit seems to be only on when auto naming is enabled (not tested, but judging from source code). Most (if not all) diffusers official training examples are *NOT* using auto naming in accelerator.
I think accelerator may well track all `save_states` calls during training.
