### ISSUE TITLE
[ONNX] Is it possible to load LORAs to be used in the ONNX pipelines?

### ISSUE THREAD

**Issue by GreenLandisaLie** [huggingface/diffusers#2493]
A while ago I've asked about Textual Inversion embeddings and the answer was basically 'no'. There was a way around it but it wasn't an actual solution. However this was some time ago and things might have changed. 
So, is it possible now? And if so is there any documentation on this matter I can read?
Sorry this is not an actual issue.

**Comment by GBalogo** [comment]
AFAIK, nothing has changed in that you'd have to write your own code to "load" LoRAs into an ONNX pipeline, and that would be a massive headache prone to breaking, even to support exclusively the default diffusers style LoRAs. There are "solutions" to convert LoRAs from other formats to diffusers format, then inject into a model _before_ converting to ONNX, but most people would give up before figuring it out, I'd think.

**Comment by GreenLandisaLie** [comment]
> There are "solutions" to convert LoRAs from other formats to diffusers format, then inject into a model before converting to ONNX

Yap, that's excatly what I had to do with Textual Inversion embeddings. It worked but the resulting models would have uneven layer sizes and if I tried to convert an 'injected' model back to .ckpt and use it to merge with other models it would fail. Plus, embeddings should really only be loaded on demand - specially LORAs.
With LORAs people adjust their overall weights in accordance to their needs - something that would be impossible with that approach so that wouldn't do.

**Comment by ssube** [comment]
This is possible, but only if the ONNX model's nodes and initializers have their original names. Running some of the ORT optimization scripts will rename them and makes it very difficult to line things up. I have some notes on the nodes, names, etc in https://github.com/ssube/onnx-web/issues/213
