### ISSUE TITLE
MPS: StableDiffusionUpscalePipeline produces a black image

### ISSUE THREAD

**Issue by Radagaisus** [huggingface/diffusers#2495]
### Describe the bug

Running the `StableDiffusionUpscalePipeline` on MPS produces a black (or sometimes gray) upscaled image.

### Reproduction

```python
from diffusers import StableDiffusionUpscalePipeline
from PIL import Image

# Name of the upscaling model to use
model_id = 'stabilityai/stable-diffusion-x4-upscaler'

# Load the pretrained upscaling model
pipeline = StableDiffusionUpscalePipeline.from_pretrained(model_id)

# Use MPS architecture
pipeline = pipeline.to('mps')

# Open the low-resolution image that will be upscaled
low_res_image = Image.open('outputs/references/tests/low-res-cat.png') 

# Upscale the image
upscaled_image = pipeline(
	# The prompt used for generating the image
	prompt='a white cat',
	# Negative prompt to guide the image generation away from
	negative_prompt='',
	image=low_res_image,
	# The number of denoising steps. More denoising steps usually lead to a higher
	# quality image at the expense of slower inference.
	num_inference_steps=5,
	# Higher guidance scale encourages to generate images that are closely linked
	# to the text prompt, usually at the expense of lower image quality.
	guidance_scale=7.5,
).images[0]

# Save the upscaled image
upscaled_image.save('outputs/upscaled_cat.png')
```

Adding a warmup step doesn’t appear to help:

```python
# First-time quick warmup pass to circumvent a first-time inference issue on MPS
_ = pipeline('warmup pass prompt', low_res_image, num_inference_steps=1)
```

### System Info

- `diffusers` version: 0.13.1
- Platform: macOS-13.2.1-arm64-arm-64bit
- Python version: 3.10.9
- PyTorch version (GPU?): 1.13.1 (False)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.26.1
- Accelerate version: 0.12.0
- xFormers version: 0.0.17.dev451
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by patrickvonplaten** [comment]
cc @pcuenca here

**Comment by pcuenca** [comment]
This is resolved in the latest nightly of the upcoming PyTorch 2.0. Probably related: https://github.com/pytorch/pytorch/pull/94963

Unfortunately I don't think we can do much in diffusers to make it work with the current version of PyTorch.

**Comment by innat** [comment]
@Radagaisus 
try `safety_checker=None` in the pipe.
