### ISSUE TITLE
Support batches in noise scheduler

### ISSUE THREAD

**Issue by jaketae** [huggingface/diffusers#25]
Firstly, kudos to the HF team for building this awesome library!

I would like to propose some modifications to the DDPM noise scheduler (and potentially other schedulers) to support batching. Based on [`training_ddpm.py`](https://github.com/huggingface/diffusers/blob/main/examples/train_ddpm.py), it appears that the DDPM noise scheduler does not batch forward diffusion steps:

https://github.com/huggingface/diffusers/blob/694ad9849bd26f7baa9044f49395a2b90be49f68/examples/train_ddpm.py#L78-L81

Supporting batches should be possible in theory by crudely modifying `DDPMScheduler.get_alpha_prod` to something like

```python
def get_alpha_prod(self, time_steps):
        mask = (time_steps < 0).float().numpy()
        return torch.from_numpy(self.one * mask + self.alphas_cumprod[time_steps] * (1 - mask))
```

The referenced line in the training example script would now be reduced to

```python
#  noises = torch.randn(clean_images.shape).to(clean_images.device)
# timesteps = torch.randint(0, noise_scheduler.timesteps, (16, 1, 1, 1)).long()
noise_images = noise_scheduler.forward_step(clean_images, noises, timesteps)
```

Is there a particular reason why we should avoid batching the forward process? Curious to hear your thoughts!

**Comment by patrickvonplaten** [comment]
Very much agree! @anton-l is working on this right now I think :-)

**Comment by anton-l** [comment]
Yep, much cleaner now :) https://github.com/huggingface/diffusers/commit/848c86ca0a2e321cda294c3cd3e8a3572281c2f3
