### ISSUE TITLE
First-time "warmup" pass for Apple Silicon (M1/M2)

### ISSUE THREAD

**Issue by rupeshs** [huggingface/diffusers#2505]
As per the document "warm-up" pass is required for Apple silicon inference. Is this really needed in the diffuser 0.13.1?

**Comment by pcuenca** [comment]
I tested three weeks ago and the problem was still happening to me: https://github.com/huggingface/diffusers/issues/372#issuecomment-1418886886

**Comment by rupeshs** [comment]
@pcuenca I was working on my new app DiffusionMagic - Simple to use Stable Diffusion workflow using diffusers. https://github.com/rupeshs/diffusionmagic

**Comment by pcuenca** [comment]
@rupeshs looks cool! Did you try `mps` without the forward pass?

**Comment by rupeshs** [comment]
@pcuenca  Thank you, sadly I don't have a Mac machine.

**Comment by pcuenca** [comment]
Cool, thanks. Closing this issue for now, then.
