### ISSUE TITLE
Standardizing batching logic for pipelines which take both images and text prompts

### ISSUE THREAD

**Issue by williamberman** [huggingface/diffusers#2510]
In the stable unclip img2img pipeline, I follow the standard batching logic for the prompts. If a single image is passed, I duplicate batch_size * num_images_per_prompt times. If multiple images are passed, I only support the same number of prompts and images passed, so I duplicate each image num_images_per_prompt times.

In the stable diffusion img2img pipeline, the inputted images are regardless extended to the length batch_size * num_images_per_prompt however, this is deprecated, and the future expected behavior is that the user should always pass batch_size * num_images_per_prompt images.

I'm in general in favor of standardizing on the stable unclip batching behavior. I think always supporting a single image being passed regardless of the number of prompts and num_images_per_prompt is flexible and intuitive (at least to me, it would be the default behavior I would expect). I think requiring the user pass more images than prompts might be a bit confusing.

I see in the case of stable diffusion img2img this poses some potential issues because when you pass a list of generators, you have to pass batch_size * num_images_per_prompt as the generators are used for each independent latent noise. I haven't thought super hard on if there's a way around this.

**Comment by sayakpaul** [comment]
> I'm in general in favor of standardizing on the stable unclip batching behavior. I think always supporting a single image being passed regardless of the number of prompts and num_images_per_prompt is flexible and intuitive (at least to me, it would be the default behavior I would expect). I think requiring the user pass more images than prompts might be a bit confusing.

I am in favor of that too. Passing more images could be a confusing default behaviour indeed.

> I see in the case of stable diffusion img2img this poses some potential issues because when you pass a list of generators, you have to pass batch_size * num_images_per_prompt as the generators are used for each independent latent noise. I haven't thought super hard on if there's a way around this.

That complicates the UX in my opinion and not super intuitive. I think to prevent that case we could just raise meaningful error messages so that the users have enough guidance to resolve it.

**Comment by patrickvonplaten** [comment]
Would also be in favor of for now not complicating things too much. I'd even say that if the user passes len(images) != len(prompt) we always raise for now. We can always adapt later.
