### ISSUE TITLE
Is there exists a method to use unet.set_attn_processor from a config file with its network definitions ?

### ISSUE THREAD

**Issue by svjack** [huggingface/diffusers#2513]
Huggingface transformers use auto_map in config file to allow users define their own network(by script) 
and load them by Huggingface's interface. Because models such as "ControlNet" or "ControlLoRA" and many so on are an edit version by change their attention block of Unet.
Load from config and use "unet.set_attn_processor" auto construct the network to make this edit activate may make the 
diffuser project more compatible with many downstream works easily.
Can this feature be supported in the future ?

**Comment by patrickvonplaten** [comment]
Hey @svjack,

What would be the big advantage of adding it to the config? We could add it, but it'd require significant changes to the UI
