### ISSUE TITLE
Initialisation of models takes long time

### ISSUE THREAD

**Issue by nicollegah** [huggingface/diffusers#2525]
Hey,

I am running a web service based on Stable Diffusion. Somehow, when i launch a new instance, initialisation of stable diffusion takes about 15 minutes. For me this is critical, as I am offering 5 different models and thus start-up time becomes significant.

Basically i am running:     
```
pipe = StableDiffusionPipeline.from_pretrained(model, 
                                                    torch_dtype=torch.float16, safety_checker=None)
```
and it is stuck here
<img width="978" alt="image" src="https://user-images.githubusercontent.com/55440280/222155181-4574717e-3f25-46c9-a680-65c41a6d0aa7.png">

Once the script ran once, the startup time is on the order of minutes and acceptable. It feels like it needs to compile something on first run or so.

Any ideas what I can improve to decrease the time? 
diffusers==0.13.1
xformers==0.0.16
transformers==4.26.1
torch==1.13.1
accelerate==0.15.0
CUDA 11.7

Thanks!

**Comment by mikegarts** [comment]
@nicollegah Maybe you can cache the large model files locally to avoid the download on startup?

**Comment by nicollegah** [comment]
How would I do that? Just to be clear, it is not downloading the actual model at this step (as far as I'm aware of). I made an image of the instance with downloaded model files and if I make new instances of that image, this happens. It is not showing to download the multi gb files. I saw that when creating the image but here it is not the case. I am not sure what it is "fetching" here and what the step afterwards is that takes so long.

**Comment by mikegarts** [comment]
@nicollegah Does this also happen when you are providing a path to a directory containing model's files as mentioned here (I am not sure what does the variable model holds in your example)?
https://huggingface.co/docs/diffusers/main/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.from_pretrained

**Comment by nicollegah** [comment]
@mikegarts Wow, you just alleviated a major source of trouble for me. That's it. Startup is so much faster now. Thanks a lot for all your work, diffusers is really such a cool library.
