### ISSUE TITLE
Saving error finetuning stable diffusion LoRA

### ISSUE THREAD

**Issue by sr5434** [huggingface/diffusers#2548]
### Describe the bug

After the stable diffusion model is fully trained, an error occurs:
```
Traceback (most recent call last):
  File "train_text_to_image_lora.py", line 872, in <module>
    main()
  File "train_text_to_image_lora.py", line 825, in main
    unet.save_attn_procs(args.output_dir)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/loaders.py", line 273, in save_attn_procs
    weights_no_suffix = weights_name.replace(".bin", "")
AttributeError: 'NoneType' object has no attribute 'replace'
```
After this error occurs, the weights for the model aren't saved.

### Reproduction

I ran the below command in Google Colab:
```
accelerate launch train_text_to_image_lora.py --mixed_precision="fp16" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --dataset_name="Norod78/microsoft-fluentui-emoji-512-whitebg" --caption_column="text" --resolution=512 --train_batch_size=2 --num_train_epochs=1 --output_dir="./sd-model-finetuned-lora" --max_train_steps=1000 --checkpointing_steps=500 --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 --seed=42
```

### Logs

```shell
Traceback (most recent call last):
  File "train_text_to_image_lora.py", line 872, in <module>
    main()
  File "train_text_to_image_lora.py", line 825, in main
    unet.save_attn_procs(args.output_dir)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/loaders.py", line 273, in save_attn_procs
    weights_no_suffix = weights_name.replace(".bin", "")
AttributeError: 'NoneType' object has no attribute 'replace'
```

### System Info

Google colab running the latest version of diffusers.

Is this a bug, or is there something I have to do on my end to fix this?

**Comment by StarWorkXc** [comment]
I have a same issue...
How to fix it, plz?

**Comment by wangjuns** [comment]
Me too.
It's seem that move below code upper then clean up code will fix bug.

```
 if weights_name is None:
            if safe_serialization:
                weights_name = LORA_WEIGHT_NAME_SAFE
            else:
                weights_name = LORA_WEIGHT_NAME
```

**Comment by sr5434** [comment]
Thank you, that seems to have fixed the problem.

**Comment by douo** [comment]
> pipeline.unet.load_attn_procs(args.output_dir, weights_name='xyz.bin')

It seem to be `weight_name`([ref](https://github.com/huggingface/diffusers/blob/main/src/diffusers/loaders.py#L144)) not `weghts_name`.

**Comment by sr5434** [comment]
@wangjuns you should consider opening a PR with those changes.

**Comment by sr5434** [comment]
The error also occurs when loading weights:
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-417d63d04d54>](https://localhost:8080/#) in <module>
      4 model_path = "/content/sd-model-finetuned-lora/pytorch_lora_weights.bin"
      5 pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
----> 6 pipe.unet.load_attn_procs(model_path)
      7 pipe.to("cuda")
      8 

[/usr/local/lib/python3.9/dist-packages/diffusers/loaders.py](https://localhost:8080/#) in load_attn_procs(self, pretrained_model_name_or_path_or_dict, **kwargs)
    151         model_file = None
    152         if not isinstance(pretrained_model_name_or_path_or_dict, dict):
--> 153             if (is_safetensors_available() and weight_name is None) or weight_name.endswith(".safetensors"):
    154                 if weight_name is None:
    155                     weight_name = LORA_WEIGHT_NAME_SAFE

AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by patrickvonplaten** [comment]
Looks like we need to fix something here! @sr5434 could you maybe add a link to the trained LoRA checkpoints ? Also cc @sayakpaul could you maybe try to have a look into this? :-)

**Comment by sayakpaul** [comment]
This is related to https://github.com/huggingface/diffusers/issues/2616.

@wfng92 proposed a nice suggestion here: https://github.com/huggingface/diffusers/issues/2616#issuecomment-1466106107.

The easiest workaround for now seems to be  https://github.com/huggingface/diffusers/issues/2616#issuecomment-1462099156.

**Comment by patrickvonplaten** [comment]
Does this fix the problem: https://github.com/huggingface/diffusers/pull/2655/files

**Comment by sr5434** [comment]
@sayakpaul I tried the work around, but now the error occurs at load time. @patrickvonplaten I will send the LoRA weights as soon as I can.

**Comment by 0xhelloweb3** [comment]
@patrickvonplaten  
```
!pip install git+https://github.com/huggingface/diffusers@correct_lora_saving_loading
!accelerate launch --mixed_precision="fp16" train_text_to_image_lora.py \
  --pretrained_model_name_or_path="Linaqruf/anything-v3.0" \
  --dataset_name="ethers/azuki-datasets" --caption_column="text" \
  --resolution=512 --random_flip \
  --train_batch_size=1 \
  --max_train_steps=1 \
  --checkpointing_steps=1000 \
  --validation_epochs=100 \
  --num_validation_images=0 \
  --output_dir="/content/drive/MyDrive/differ-out" \
  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --seed=42 \
  --max_train_samples=10
```
An error is still reported when the training result is saved in colab.
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/7252280/224860238-b06c5952-4a1d-4671-a14c-6e69d9ca6014.png">

**Comment by 0xhelloweb3** [comment]
@patrickvonplaten here is my colab code, [colab](https://colab.research.google.com/drive/1Z-Xt8c4Wjk5d3ft5VoC0P-J0y0427i4z?usp=sharing)
you can use for testing

**Comment by sayakpaul** [comment]
@0xhelloweb3 might have been an improper dependency resolution problem in your Colab. 

Mine worked fine: https://colab.research.google.com/gist/sayakpaul/a6640268902e3e75aef58b5c9f06f042/scratchpad.ipynb

**Comment by 0xhelloweb3** [comment]
> @0xhelloweb3 might have been an improper dependency resolution problem in your Colab.
> 
> Mine worked fine: https://colab.research.google.com/gist/sayakpaul/a6640268902e3e75aef58b5c9f06f042/scratchpad.ipynb

Thx, he problem has been solved and it works normally

**Comment by sayakpaul** [comment]
@sr5434 could you check if https://github.com/huggingface/diffusers/pull/2655 solves your issue and close this issue accordingly?

**Comment by sr5434** [comment]
Yes, #2655 fixes the issue. Thank you @patrickvonplaten for creating the PR.
