### ISSUE TITLE
StableDiffusionPipeline requires unreleased accelerate version (0.17.0)

### ISSUE THREAD

**Issue by ernesto-elsaesser** [huggingface/diffusers#2554]
### Describe the bug

`StableDiffusionPipeline.enable_model_cpu_offload()` requires accelerate **0.17.0**:

https://github.com/huggingface/diffusers/blob/2ea1da89ab42bde69caad909048925ca99873400/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L237-L240

However, right now, the latest release is **0.16.0** (see https://github.com/huggingface/accelerate/releases)

### Reproduction

```python
!pip install --upgrade accelerate

from diffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
pipe.enable_model_cpu_offload()
```

### Logs

```shell
>>> pipe.enable_model_cpu_offload()

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
----> pipe.enable_model_cpu_offload()

File ~/anaconda3/envs/torch-sd/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py:240, in StableDiffusionPipeline.enable_model_cpu_offload(self, gpu_id)
    238     from accelerate import cpu_offload_with_hook
    239 else:
--> 240     raise ImportError("`enable_model_offload` requires `accelerate v0.17.0` or higher.")
    242 device = torch.device(f"cuda:{gpu_id}")
    244 if self.device.type != "cpu":

ImportError: `enable_model_offload` requires `accelerate v0.17.0` or higher.

--

$ pip install accelerate==0.17.0

ERROR: Could not find a version that satisfies the requirement accelerate==0.17.0 (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.15.0, 0.16.0)
ERROR: No matching distribution found for accelerate==0.17.0
```

### System Info

- `diffusers` version: 0.14.0
- Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.9.16
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.12.1
- Transformers version: 4.26.1
- Accelerate version: 0.16.0
- xFormers version: 0.0.16

**Comment by patrickvonplaten** [comment]
Thanks for the well-written issue 
Yes accelerate 0.17.0 is indeed not released yet, could you try installing it from main?

```
pip install git+https://github.com/huggingface/accelerate.git
```

As explained here: https://huggingface.co/lllyasviel/sd-controlnet-canny#example

**Comment by luludus** [comment]
> ### Describe the bug
> `StableDiffusionPipeline.enable_model_cpu_offload()` requires accelerate **0.17.0**:
> 
> https://github.com/huggingface/diffusers/blob/2ea1da89ab42bde69caad909048925ca99873400/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L237-L240
> 
> However, right now, the latest release is **0.16.0** (see https://github.com/huggingface/accelerate/releases)
> 
> ### Reproduction
> ```python
> !pip install --upgrade accelerate
> 
> from diffusers import StableDiffusionPipeline
> pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
> pipe.enable_model_cpu_offload()
> ```
> 
> ### Logs
> ```shell
> >>> pipe.enable_model_cpu_offload()
> 
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> ----> pipe.enable_model_cpu_offload()
> 
> File ~/anaconda3/envs/torch-sd/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py:240, in StableDiffusionPipeline.enable_model_cpu_offload(self, gpu_id)
>     238     from accelerate import cpu_offload_with_hook
>     239 else:
> --> 240     raise ImportError("`enable_model_offload` requires `accelerate v0.17.0` or higher.")
>     242 device = torch.device(f"cuda:{gpu_id}")
>     244 if self.device.type != "cpu":
> 
> ImportError: `enable_model_offload` requires `accelerate v0.17.0` or higher.
> 
> --
> 
> $ pip install accelerate==0.17.0
> 
> ERROR: Could not find a version that satisfies the requirement accelerate==0.17.0 (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.15.0, 0.16.0)
> ERROR: No matching distribution found for accelerate==0.17.0
> ```
> 
> ### System Info
> * `diffusers` version: 0.14.0
> * Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
> * Python version: 3.9.16
> * PyTorch version (GPU?): 1.13.1+cu117 (True)
> * Huggingface_hub version: 0.12.1
> * Transformers version: 4.26.1
> * Accelerate version: 0.16.0
> * xFormers version: 0.0.16

You can delete the：pipe.enable_model_cpu_offload()
and just use pipe.to("cuda")
but the gpu memory cannot be managed well

**Comment by ernesto-elsaesser** [comment]
@patrickvonplaten thank you for your reply. Installing from `main` did work, and in the meantime **0.17.0** has been released anyways. 👍

Maybe it's worth mentioning this solution in the official docs, in places like the green box in [Model offloading for fast inference and memory savings](https://huggingface.co/docs/diffusers/optimization/fp16#model-offloading-for-fast-inference-and-memory-savings), for when you guys ever out-ship the other teams again 🙂

**Comment by franciskip** [comment]
> ### Describe the bug
> `StableDiffusionPipeline.enable_model_cpu_offload()` requires accelerate **0.17.0**:
> 
> https://github.com/huggingface/diffusers/blob/2ea1da89ab42bde69caad909048925ca99873400/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L237-L240
> 
> However, right now, the latest release is **0.16.0** (see https://github.com/huggingface/accelerate/releases)
> 
> ### Reproduction
> ```python
> !pip install --upgrade accelerate
> 
> from diffusers import StableDiffusionPipeline
> pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
> pipe.enable_model_cpu_offload()
> ```
> 
> ### Logs
> ```shell
> >>> pipe.enable_model_cpu_offload()
> 
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> ----> pipe.enable_model_cpu_offload()
> 
> File ~/anaconda3/envs/torch-sd/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py:240, in StableDiffusionPipeline.enable_model_cpu_offload(self, gpu_id)
>     238     from accelerate import cpu_offload_with_hook
>     239 else:
> --> 240     raise ImportError("`enable_model_offload` requires `accelerate v0.17.0` or higher.")
>     242 device = torch.device(f"cuda:{gpu_id}")
>     244 if self.device.type != "cpu":
> 
> ImportError: `enable_model_offload` requires `accelerate v0.17.0` or higher.
> 
> --
> 
> $ pip install accelerate==0.17.0
> 
> ERROR: Could not find a version that satisfies the requirement accelerate==0.17.0 (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.15.0, 0.16.0)
> ERROR: No matching distribution found for accelerate==0.17.0
> ```
> 
> ### System Info
> * `diffusers` version: 0.14.0
> * Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
> * Python version: 3.9.16
> * PyTorch version (GPU?): 1.13.1+cu117 (True)
> * Huggingface_hub version: 0.12.1
> * Transformers version: 4.26.1
> * Accelerate version: 0.16.0
> * xFormers version: 0.0.16

Consider downgrading the PyTorch to 1.13.1 version should work  !pip install torch==1.13.1 you may as well use !pip install accelerate -U
