### ISSUE TITLE
Unclear workflow for Textual Inversion

### ISSUE THREAD

**Issue by init27** [huggingface/diffusers#2564]
Hi All! 
First of all, thank you so much for the amazing work with `diffusers`. I have literally been able to pickup Stable Diffusion and grasp different concepts to a great extent in under a week thanks to it! 

## Cannot load in custom Textual Inversion models

I've been unable to make `diffusers` work with Textual Inversion models from the community. I have tried following the [examples from the docs](https://huggingface.co/docs/diffusers/v0.14.0/en/training/text_inversion#textual-inversion) as well as some other examples in the repos

My simple requirement would be to able to load in a custom `negative embedding` for example: [nfixer](https://civitai.com/models/13515/nfixer-for-illuminati-diffusion-v11) and make it work! 

Could you please point me to a better resource or if I'm missing something obvious? 

Thanks again for all the amazing work! 🤗

### Reproduction

- Download [nfixer](https://civitai.com/models/13515/nfixer-for-illuminati-diffusion-v11) text embedding
- Download [illuminati model](https://civitai.com/models/11193/illuminati-diffusion-v11) although any `.ckpt` would be okay
- Run the `convert_from_stable_diffusion_to_diffusers.py` script from the examples folder (I had to comment out some code-to make it work)
- Try to read in `nfixer` and pass as a `negative embed` to the `StableDiffusionPipeline` based on the [reference](https://huggingface.co/docs/diffusers/v0.14.0/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline)

### System Info

- `diffusers 0.12.1`

**Comment by patrickvonplaten** [comment]
Hey @init27,

Thanks for opening this issue! We're a bit under water at the moment and sadly haven't found time yet for: https://github.com/huggingface/diffusers/pull/2009 

Which should enable this use case! I try to allocate time for textual inversion this or next week (:crossed_fingers: )

**Comment by init27** [comment]
Thank you very much for the reply and all your amazing work! 

I'll close this issue and keep an eye out on #2009! 🙏
