### ISSUE TITLE
ImportError: cannot import name 'ProjectConfiguration' from 'accelerate.utils' 

### ISSUE THREAD

**Issue by bluusun** [huggingface/diffusers#2571]
### Describe the bug

Train Dreambooth fails after upgrade with ImportError: cannot import name 'ProjectConfiguration' from 'accelerate.utils' 

### Reproduction

Latest version

git clone https://github.com/huggingface/diffusers
cd diffusers
pip install -e .

### Logs

```shell
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "train_dreambooth.py", line 34, in <module>
    from accelerate.utils import ProjectConfiguration, set_seed
ImportError: cannot import name 'ProjectConfiguration' from 'accelerate.utils' (/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/utils/__init__.py)
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=/home/ubuntu/t', '--instance_data_dir=/home/ubuntu/', '--class_data_dir=/home/ubuntu/work/input_images/regularization_images/person/', '--output_dir=/home/ubuntu/.cache/', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of asdf person', '--class_prompt=a photo of person', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=800']' returned non-zero exit status 1.
```

### System Info

absl-py                  1.3.0            
accelerate               0.12.0           
addict                   2.4.0            
aiohttp                  3.8.3            
aiosignal                1.3.1            
altair                   4.2.0            
antlr4-python3-runtime   4.8              
anyio                    3.6.2            
appdirs                  1.4.4            
async-timeout            4.0.2            
attrs                    19.3.0           
audioread                3.0.0            
Automat                  0.8.0            
awscli                   1.27.22          
basicsr                  1.4.2            
beautifulsoup4           4.11.1           
bitsandbytes             0.35.4           
blessings                1.6              
blinker                  1.4              
botocore                 1.29.22          
cachetools               5.2.0            
certifi                  2019.11.28       
cffi                     1.15.1           
chardet                  3.0.4            
charset-normalizer       2.1.1            
Click                    7.0              
click-help-colors        0.9.1            
click-shell              2.1              
cloud-init               22.4.2           
cmake                    3.25.0           
colorama                 0.4.3            
coloredlogs              15.0.1           
command-not-found        0.3              
configobj                5.0.6            
constantly               15.1.0           
contourpy                1.0.6            
cryptography             2.8              
cycler                   0.11.0           
datasets                 2.9.0            
dbus-python              1.2.16           
decorator                5.1.1            
dill                     0.3.6            
distro                   1.4.0            
distro-info              0.23ubuntu1      
docker-pycreds           0.4.0            
docutils                 0.16             
ec2-hibinit-agent        1.0.0            
einops                   0.3.0            
entrypoints              0.3              
facexlib                 0.2.5            
fairscale                0.4.12           
fastapi                  0.88.0           
ffmpeg                   1.4              
ffmpy                    0.3.0            
filelock                 3.8.2            
filterpy                 1.4.5            
flatbuffers              22.11.23         
fonttools                4.38.0           
frozenlist               1.3.3            
fsspec                   2022.11.0        
ftfy                     6.1.1            
future                   0.18.2           
gdown                    4.6.0            
gfpgan                   1.3.8            
gitdb                    4.0.10           
GitPython                3.1.30           
google-auth              2.15.0           
google-auth-oauthlib     0.4.6            
gpustat                  0.6.0            
gradio                   3.13.2           
grpcio                   1.51.1           
h11                      0.14.0           
hibagent                 1.0.1            
httpcore                 0.16.2           
httplib2                 0.14.0           
httpx                    0.23.1           
huggingface-hub          0.11.1           
humanfriendly            10.0             
hyperlink                19.0.0           
idna                     2.8              
imageio                  2.9.0            
imaginAIry               11.0.0           
importlib-metadata       6.0.0            
incremental              16.10.1          
inflect                  6.0.2            
install                  1.3.5            
invisible-watermark      0.1.5            
Jinja2                   2.10.1           
jmespath                 1.0.1            
joblib                   1.2.0            
jsonpatch                1.22             
jsonpointer              2.0              
jsonschema               3.2.0            
keyring                  18.0.1           
kiwisolver               1.4.4            
kornia                   0.6.0            
language-selector        0.1              
launchpadlib             1.10.13          
lazr.restfulclient       0.14.2           
lazr.uri                 1.0.3            
librosa                  0.9.2            
lightning-utilities      0.6.0.post0      
linkify-it-py            1.0.3            
llvmlite                 0.31.0           
lmdb                     1.3.0            
Markdown                 3.4.1            
markdown-it-py           2.1.0            
MarkupSafe               2.1.2            
matplotlib               3.6.2            
mdit-py-plugins          0.3.3            
mdurl                    0.1.2            
mega.py                  1.0.8            
more-itertools           4.2.0            
mpmath                   1.2.1            
multidict                6.0.3            
multiprocess             0.70.14          
mypy-extensions          0.4.3            
mysql-connector-python   8.0.32           
natsort                  8.2.0            
netifaces                0.10.4           
networkx                 2.8.8            
numba                    0.48.0           
numpy                    1.24.2           
nvidia-cublas-cu11       11.10.3.66       
nvidia-cuda-nvrtc-cu11   11.7.99          
nvidia-cuda-runtime-cu11 11.7.99          
nvidia-cudnn-cu11        8.5.0.96         
nvidia-ml-py3            7.352.0          
oauthlib                 3.1.0            
omegaconf                2.1.1            
onnx                     1.12.0           
onnxruntime              1.13.1           
open-clip-torch          2.7.0            
opencv-python            4.6.0.66         
orjson                   3.8.3            
packaging                21.3             
pandas                   1.5.3            
pathlib                  1.0.1            
pathtools                0.1.2            
pexpect                  4.6.0            
Pillow                   9.3.0            
pip                      20.0.2           
pooch                    1.6.0            
progressbar              2.5              
protobuf                 3.20.3           
psutil                   5.5.1            
pyarrow                  11.0.0           
pyasn1                   0.4.2            
pyasn1-modules           0.2.1            
pycparser                2.21             
pycryptodome             3.16.0           
pydantic                 1.10.2           
pyDeprecate              0.3.1            
pydub                    0.25.1           
PyGObject                3.36.0           
PyHamcrest               1.9.0            
PyJWT                    1.7.1            
pymacaroons              0.13.0           
PyNaCl                   1.3.0            
pyOpenSSL                19.0.0           
pyparsing                3.0.9            
pyre-extensions          0.0.23           
pyrsistent               0.15.5           
pyserial                 3.4              
PySocks                  1.7.1            
python-apt               2.0.1            
python-dateutil          2.8.2            
python-debian            0.1.36ubuntu1    
python-magic             0.4.16           
python-multipart         0.0.5            
pytorch-lightning        1.9.1            
pytz                     2022.6           
PyWavelets               1.4.1            
PyYAML                   6.0              
random-user-agent        1.0.1            
realesrgan               0.3.0            
regex                    2022.10.31       
requests                 2.28.2           
requests-oauthlib        1.3.1            
requests-unixsocket      0.2.0            
resampy                  0.4.2            
responses                0.18.0           
rfc3986                  1.5.0            
rotary-embedding-torch   0.2.1            
rsa                      4.7.2            
s3cmd                    2.0.2            
s3transfer               0.6.0            
safetensors              0.2.8            
scikit-image             0.19.3           
scikit-learn             1.2.0            
scipy                    1.9.3            
SecretStorage            2.3.1            
sentry-sdk               1.15.0           
service-identity         18.1.0           
setproctitle             1.3.2            
setuptools               45.2.0           
simplejson               3.16.0           
six                      1.14.0           
smmap                    5.0.0            
sniffio                  1.3.0            
sos                      4.4              
soundfile                0.11.0           
soupsieve                2.3.2.post1      
ssh-import-id            5.10             
starlette                0.22.0           
sympy                    1.11.1           
systemd-python           234              
tb-nightly               2.12.0a20221205  
tenacity                 5.1.5            
tensorboard              2.12.0           
tensorboard-data-server  0.7.0            
tensorboard-plugin-wit   1.8.1            
threadpoolctl            3.1.0            
tifffile                 2022.10.10       
timm                     0.6.12           
tokenizers               0.12.1           
toolz                    0.12.0           
torch                    1.13.1           
torchaudio               0.13.1           
torchdiffeq              0.2.3            
torchmetrics             0.11.1           
torchvision              0.14.0           
TorToiSe                 2.4.2            
tqdm                     4.64.1           
transformers             4.26.1           
triton                   2.0.0.dev20221202
Twisted                  18.9.0           
typing-extensions        4.4.0            
typing-inspect           0.8.0            
ubuntu-advantage-tools   8001             
uc-micro-py              1.0.1            
ufw                      0.36             
unattended-upgrades      0.1              
Unidecode                1.3.6            
urllib3                  1.26.14          
uvicorn                  0.20.0           
wadllib                  1.3.3            
wandb                    0.13.10          
wcwidth                  0.2.5            
websockets               10.4             
Werkzeug                 2.2.2            
wheel                    0.34.2           
xformers                 0.0.16           
xxhash                   3.2.0            
yapf                     0.32.0           
yarl                     1.8.2            
zipp                     1.0.0            
zope.interface           4.7.1

**Comment by bluusun** [comment]
Sorry duplicate. Accelerate v0.16.0 should be in requirements.txt

**Comment by patrickvonplaten** [comment]
cc @williamberman could you check here?

**Comment by better629** [comment]
use accelerate==0.16.0

**Comment by williamberman** [comment]
Sorry about this! Added a min version to accelerate here: https://github.com/huggingface/diffusers/pull/3042

**Comment by williamberman** [comment]
requirements files now updated :)
