### ISSUE TITLE
Precommit hooks for contributors

### ISSUE THREAD

**Issue by vvvm23** [huggingface/diffusers#2573]
**Is your feature request related to a problem? Please describe.**
Not really a problem but just a quality of life suggestion.

I noticed PR #2524 which simply updated copyrights. It got me thinking that this could be quite easily automated to trigger for every new file added in commits using git pre-commit hooks. I asked on the discord and there was some agreement, so I thought I'd open an issue here.

The same goes for line ending checks, running `make clean` and `make quality`, and other code quality related things.

**Describe the solution you'd like**
Add some pre-commit hooks for contributors to automate some code quality processes, as suggested above.

**Describe alternatives you've considered**
Checking all files in a large repo could be quite slow. It could be replaced with checks and auto-formatting before merging into the main branch, or limiting it to only files edited in the commit.

**Additional context**
Of course, if this goes against the design philosophy of diffusers, feel free to close. This is just a quality of life suggestion that I've had a lot of success with in other projects.

**Comment by patrickvonplaten** [comment]
Heey @vvvm23, 

I really like pre-commit hooks as well the problem though is that they can sometimes really slow you down. E.g. `make style` usually has to be run only once in the end of a long streak of commits.

**Comment by vvvm23** [comment]
Hi Patrick,

Yeah that makes sense. I personally feel the slow down is worth it, but I can see merit for not having them too.

I'll close this, but feel free to reopen if you wish. 🤗
