### ISSUE TITLE
Installing diffusers in editable mode does not work

### ISSUE THREAD

**Issue by generatorman** [huggingface/diffusers#2578]
### Describe the bug

I'm trying to install diffusers in editable mode in a Colab/Kaggle notebook, following https://huggingface.co/docs/diffusers/installation . It installs successfully, but then I cannot import the package unless I use import src.diffusers .

Only advise I could find on this was to add the package directory to PYTHONPATH using sys.path.append(). Well, path.append() does not work at all to update the PYTHONPATH. I found another way of actually changing PYTHONPATH, but that doesn't help - I still get an error of ImportError: cannot import name 'StableDiffusionPipeline' from 'diffusers' (unknown location) .

### Reproduction

`!pip install torch
!pip install accelerate
!git clone https://github.com/huggingface/diffusers

%cd diffusers
!git checkout v0.14.0
!pip install -e ".[torch]"

import os, sys
print(os.getcwd())

sys.path.append(os.getcwd())
!echo $PYTHONPATH

os.environ['PYTHONPATH'] = os.getcwd() + ':' + os.environ.get('PYTHONPATH', '')
%cd src
os.environ['PYTHONPATH'] = os.getcwd() + ':' + os.environ.get('PYTHONPATH', '')
%cd diffusers
os.environ['PYTHONPATH'] = os.getcwd() + ':' + os.environ.get('PYTHONPATH', '')
!echo $PYTHONPATH

%cd ../../..

!pip install transformers scipy ftfy

#%cd diffusers

import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)`

### Logs

```shell
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_27/636070101.py in <module>
----> 1 from diffusers import StableDiffusionPipeline
      2 pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)

ImportError: cannot import name 'StableDiffusionPipeline' from 'diffusers' (unknown location)
```

### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.13.0.dev0
- Platform: Linux-5.15.65+-x86_64-with-debian-bullseye-sid
- Python version: 3.7.12
- PyTorch version (GPU?): 1.13.0+cpu (False)
- Huggingface_hub version: 0.12.1
- Transformers version: 4.26.1
- Accelerate version: 0.12.0
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by patrickvonplaten** [comment]
I don't fully understand why you have `diffusers==0.13.0` installed when you install from 0.14.0 git? 

Maybe you have to uninstall `diffusers` before installing in editable mode? 

Can you try running:

```
pip uninstall diffusers
```

and try again?
