### ISSUE TITLE
possible xFormers bug or misuse

### ISSUE THREAD

**Issue by Infrared1029** [huggingface/diffusers#2579]
### Describe the bug

providing a mask seems to produce weird errors unless, that's not how a mask is supposed to be passed?

### Reproduction

```python
from diffusers.models.cross_attention import XFormersCrossAttnProcessor, CrossAttention

hidden_states = torch.randn(32, 30, 16).cuda()
attn_mask = torch.zeros((32, 30, 30)).bool().cuda()
xf(CrossAttention(16, dim_head=16, heads=1).cuda(), hidden_states, attention_mask=attn_mask)
```

### Logs

```shell
`RuntimeError: Expected attn_bias.stride(1) == 0 to be true, but got false.`
```

### System Info

- `diffusers` version: 0.14.0
- Platform: Linux-5.4.0-1103-azure-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Huggingface_hub version: 0.12.1
- Transformers version: not installed
- Accelerate version: 0.16.0
- xFormers version: 0.0.16
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by patrickvonplaten** [comment]
cc @patil-suraj @pcuenca here

**Comment by Infrared1029** [comment]
I opened a similiar issue in xFormer's repo, can be helpful https://github.com/facebookresearch/xformers/issues/683
