### ISSUE TITLE
How to use schedulers in numpy mode?

### ISSUE THREAD

**Issue by brappier** [huggingface/diffusers#2580]
Initially you used to have a tensor format = numpy. 
but now it looks like it only supports pytorch. why??

How to use it for numpy?

**Comment by patrickvonplaten** [comment]
Because all models are only available in PyTorch - what is the use case of using the schedulers in numpy only?

**Comment by brappier** [comment]
pytorch is a big dependency. if we want to run it with onnx, we should be allowed to just do stuff with numpy

**Comment by patrickvonplaten** [comment]
I see! Think currently it's too much work to decouple torch from onnx sadly :-/

**Comment by tianleiwu** [comment]
For onnx, it is feasible to implement scheduler as onnx operator to avoid dependency on PyTorch (or even numpy).

**Comment by brappier** [comment]
yeah, but the whole point of a package like diffusers is so that we dont have to implement schedulers ourselves.
is there any other package for all the state-of-the-art schedulers implemented?
