### ISSUE TITLE
DDIM timesteps function.

### ISSUE THREAD

**Issue by GLivshits** [huggingface/diffusers#2585]
### Describe the bug

DDIM scheduler uses wrong timesteps for sampling.
For example, given 50 steps and 1 steps offset gives timesteps [981, 961, ..., 1].
However, start of the diffusion process should be at timestep 999.
The same issue appears in [Stabilityai/Stab](https://github.com/Stability-AI/stablediffusion)

### Reproduction

Create the pipeline and establish scheduler:
import diffusers
model = diffusers.StableDiffusionPipeline.from_pretrained('stabilityai/stable-diffusion-2-1-base')
model.scheduler = diffusers.DDIMScheduler.from_config(model.scheduler.config, steps_offset=0)

Then call model.scheduler.set_timesteps(50)
Expected output: [999, 979, 958, 938, 917, 897, 877, 856, 836, 816, 795, 775, 754,
                               734, 714, 693, 673, 652, 632, 612, 591, 571, 550, 530, 510, 489,
                               469, 449, 428, 408, 387, 367, 347, 326, 306, 285, 265, 245, 224,
                               204, 183, 163, 143, 122, 102,  82,  61,  41,  20,   0]
Actual output: [980, 960, 940, 920, 900, 880, 860, 840, 820, 800, 780, 760, 740, 720,
                          700, 680, 660, 640, 620, 600, 580, 560, 540, 520, 500, 480, 460, 440,
                          420, 400, 380, 360, 340, 320, 300, 280, 260, 240, 220, 200, 180, 160,
                          140, 120, 100,  80,  60,  40,  20,   0]

Moreover, with 21 steps problem is much more pronounced:
Expected output: [999, 949, 899, 849, 799, 749, 699, 649, 599, 549, 500, 450, 400,
                               350, 300, 250, 200, 150, 100,  50,   0]
Actual output: [940, 893, 846, 799, 752, 705, 658, 611, 564, 517, 470, 423, 376, 329,
                          282, 235, 188, 141,  94,  47,   0]

### System Info

diffusers==0.14.0

Proposed solution:
Replace the following rows (https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddim.py, 203-210):
                  self.num_inference_steps = num_inference_steps
                  step_ratio = self.config.num_train_timesteps // self.num_inference_steps
                  # creates integer timesteps by multiplying by ratio
                  # casting to int to avoid issues when num_inference_step is power of 3
                  timesteps = (np.arange(0, num_inference_steps) * step_ratio).round()[::-1].copy().astype(np.int64)
                  self.timesteps = torch.from_numpy(timesteps).to(device)
                  self.timesteps += self.config.steps_offset

with following:
                  self.num_inference_steps = num_inference_steps
                  max_timestep = self.config['num_train_timesteps']-1
                  # creates integer timesteps by multiplying by ratio
                  # casting to int to avoid issues when num_inference_step is power of 3
                  timesteps = (np.linspace(self.config.steps_offset, max_timestep, self.num_inference_steps) ).round()[::-1].copy().astype(np.int64)
                  self.timesteps = torch.from_numpy(timesteps).to(device)

In such a way it will produce evenly distributed timesteps + interpret steps_offset as an offset from the ending of diffusion process (since model performs worse at small timesteps).

**Comment by patrickvonplaten** [comment]
Hey @GLivshits, 

Why should the start be at 999? Note that we've double checked our implementation with the original implementation here: https://github.com/ermongroup/ddim and we're getting the same results.

**Comment by PeterL1n** [comment]
Indeed this seems like a bug.

But the fix is not simply changing `timesteps`. You also need to change the calculation for `prev_timestep` in `step()` method.

**Comment by ernestchu** [comment]
Current implementation of DDIM is a little tricky. It sacrifices the first denoising step `x_T -> x_{T-s}` for the final denoising step `x_1 -> x_0`. The intuition is that human perception cannot distinguish **100% noise and 80% noise** 👀. But we can definitely tell the difference between **5% noise and clean image**. Let's use a simple 3-step DDIM example to illustrate my point:
```
Expected DDIM implementation
  ______   ______   ______ 
 /      \ /      \ /      \
|________|________|________|
0       T/3     2T/3       T

Current DDIM implementation
  _  _____  _____
 / \/     \/     \
|__|_____|________|________|
0  1    T/3     2T/3  ==   T
```
Both implementation follows the DDIM paper, since its formulation does not enforce a common step size. DDIM just says we can jump from one timestep to a way smaller one. However, current implementation has a strong assumption in this example: `x_{2T/3} == x_{T}`. Based on 👀, the assumption is acceptable and the sampling quality is fairly good!

So, should we follow the current implementation or the other one? I think it should be a great topic to discuss with 🤗 Diffusers team.

**Comment by williamberman** [comment]
Hey @GLivshits thanks for the issue :) 

Yes you are correct that in the case where the initial timestep is not the max amount of noise, technically yes there should be less noise in the initial latents. In image variation pipelines where we add some noise to an initial image, we do this correctly. 

However, in the case where there's no initial image to noise, yes we would technically always have to have our initial denoising step occur at the max amount of noise.

However, what happens here is that for all subsequent noising steps, the scheduler will add the correct amount of noise to the predicted initial image so in practice this has very little effect. 

Similar to what patrick said, our goal is actually not to be mathematically accurate but to match the implementations as they're released! So yes stable diffusion has this issue which means we should as well :)

**Comment by PeterL1n** [comment]
We published a paper on this issue: https://arxiv.org/abs/2305.08891
The current DDIM sample steps are flawed and can create actual problems.

**Comment by williamberman** [comment]
super neat @PeterL1n will take a look :)

**Comment by GLivshits** [comment]
Just in order to justify my doubts:
https://arxiv.org/pdf/2305.08891.pdf

Actually same applies to training. For example, try to noise a picture with white background with forward diffusion training till last timestep, and then denoise it with model. You will get an image with white background. This is because last timestep std is not exactly one (it is 0.9977), and SNR level is not zero (4.6819e-03).

For sampling, starting with timestep < 999 (whis is our case) produces even more pronounced effect - this means, that we started with zeros-latent, resulting in medium brightness.

**Comment by TheOnlyHolyMoly** [comment]
> https://arxiv.org/abs/2305.08891

@PeterL1n Loved your paper, read it right after it was released but then could not find it again until I saw this disucssion here. Is the fixed repo published anywhere? I would like to create a PR for https://github.com/vladmandic/automatic
Do you think the issue will affect other timestep based samplers possibly? The results were impressive!
