### ISSUE TITLE
Documentation contains non-existing load_image in diffusers.utils

### ISSUE THREAD

**Issue by belyak** [huggingface/diffusers#2596]
### Describe the bug

The documentation contains the code which doesn't work.

https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/controlnet

### Reproduction

from diffusers.utils import load_image

### Logs

```shell
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-35a619c14d56> in <module>
----> 1 from diffusers.utils import load_image

ImportError: cannot import name 'load_image' from 'diffusers.utils' (/home/andy/.local/lib/python3.10/site-packages/diffusers/utils/__init__.py)
```

### System Info

diffusers==0.14.0, linux x86-64, python 3.10.6

**Comment by patrickvonplaten** [comment]
Hmmm, weird I can run the following code snippet:

```py
from diffusers.utils import load_image
```

Are you sure your system info is correct? The error message states Python 3.10 but in the system info you state python 3.6?

**Comment by belyak** [comment]
yes

**Comment by patrickvonplaten** [comment]
Interesting! Hmm not really sure what's going on then. Could you maybe just try to use the above command then? There seems to be something weird going on with the internal import
