### ISSUE TITLE
Dreambooth multi-subjects training makes the results quality worse

### ISSUE THREAD

**Issue by qq110146** [huggingface/diffusers#2599]
### Overview
**I finetuned from stable diffusion v1.5 with dreambooth method, it worked fine when I trained single subject: car/dog. But the results quality decreased when I trained both categories at the same time with script: [train_multi_subject_dreambooth.py](https://github.com/huggingface/diffusers/blob/main/examples/research_projects/multi_subject_dreambooth/train_multi_subject_dreambooth.py)**

### Details
**Dataset**

>**Car** 
 ![l52ZopPQw6PDncKglZ2TrpGcmJ7A](https://user-images.githubusercontent.com/46549740/223613518-309f584c-e3e8-4e2f-bfe0-a3d14a1f9778.jpg)
> ![l52ZopPQw6SX0ZOgl52TrpGcmJ7A](https://user-images.githubusercontent.com/46549740/223613531-a3416cd3-7f11-46d9-a9c9-cfea96731c15.jpg)

>  **Dog**
> ![p1-512](https://user-images.githubusercontent.com/46549740/223613927-67a71f63-46ed-492d-9e4e-d4cedd3d0f58.png)
> ![p2-512](https://user-images.githubusercontent.com/46549740/223613937-72aab37e-3e84-43bc-a001-7641da70703b.png)
> ![p3-512](https://user-images.githubusercontent.com/46549740/223613946-721c5399-48f5-4bf7-a32d-82c612a7f47d.png)

**1.Single-subject experiment**
```
--Dog
export MODEL_NAME="/home/mobile360/data/lucien/model/diffusers/stable-diffusion-v1-5"
export INSTANCE_DIR="/home/mobile360/data/lucien/data/task/diffusion-multi/instance/dog3"
export CLASS_DIR="/home/mobile360/data/lucien/data/task/diffusion-multi/class/photo-of-dog"
export OUTPUT_DIR="/home/mobile360/data/lucien/data/task/diffusion-multi/ckpt/output-RPQS-dog-v5"
accelerate launch --mixed_precision="fp16" train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of RPQS dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --sample_batch_size=8 \
  --gradient_accumulation_steps=2 --gradient_checkpointing \
  --use_8bit_adam \
  --learning_rate=2e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=400 \
  --checkpointing_steps=600 \
  --max_train_steps=600

--Car
export MODEL_NAME="/home/mobile360/data/lucien/model/diffusers/stable-diffusion-v1-5"
export INSTANCE_DIR="/home/mobile360/data/lucien/data/task/diffusion-multi/instance/car2"
export CLASS_DIR="/home/mobile360/data/lucien/data/task/diffusion-multi/class/photo-of-car"
export OUTPUT_DIR="/home/mobile360/data/lucien/data/task/diffusion-multi/ckpt/output-TKIB-car-v1"
accelerate launch --mixed_precision="fp16" train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of TKIB car" \
  --class_prompt="a photo of car" \
  --resolution=512 \
  --train_batch_size=1 \
  --sample_batch_size=8 \
  --gradient_accumulation_steps=2 --gradient_checkpointing \
  --use_8bit_adam \
  --learning_rate=2e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=400 \
  --checkpointing_steps=600 \
  --max_train_steps=600

```
**Results** - fine
A photo of RPQS dog
![image](https://user-images.githubusercontent.com/46549740/223615236-838ddbeb-4eff-42b7-a35f-94a19c6877bd.png)
A photo of red TKIB car
![image](https://user-images.githubusercontent.com/46549740/223616246-d76327c3-4a38-4dde-885b-1ea441b1ddd4.png)

**2.Multi-subjects experiment**

```
export MODEL_NAME="/home/mobile360/data/lucien/model/diffusers/stable-diffusion-v1-5"
export OUTPUT_DIR="/home/mobile360/data/lucien/data/task/diffusion-multi/ckpt/output-multi-v16"
# Subject 1
export INSTANCE_DIR_1="/home/mobile360/data/lucien/data/task/diffusion-multi/instance/dog4"
export INSTANCE_PROMPT_1="a photo of RPQS dog"
export CLASS_DIR_1="/home/mobile360/data/lucien/data/task/diffusion-multi/class/photo-of-dog/"
export CLASS_PROMPT_1="a photo of dog"
# Subject 2
export INSTANCE_DIR_2="/home/mobile360/data/lucien/data/task/diffusion-multi/instance/car2"
export INSTANCE_PROMPT_2="A photo of TKIB car"
export CLASS_DIR_2="/home/mobile360/data/lucien/data/task/diffusion-multi/class/photo-of-car"
export CLASS_PROMPT_2="A photo of car"

accelerate launch train_multi_subject_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir="$INSTANCE_DIR_1,$INSTANCE_DIR_2" \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="$INSTANCE_PROMPT_1,$INSTANCE_PROMPT_2" \
  --with_prior_preservation \
  --prior_loss_weight=1.0 \
  --class_data_dir="$CLASS_DIR_1,$CLASS_DIR_2" \
  --class_prompt="$CLASS_PROMPT_1,$CLASS_PROMPT_2"\
  --num_class_images=400 \
  --resolution=512 \
  --train_batch_size=1 \
  --sample_batch_size=8 \
  --gradient_checkpointing \
  --use_8bit_adam \
  --learning_rate=1e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --checkpointing_steps=800 \
  --max_train_steps=800
```
**Results** - bad
A photo of RPQS dog
![image](https://user-images.githubusercontent.com/46549740/223617632-b915809c-400d-4cbb-b0de-fa2148a2f78e.png)
A photo of red TKIB car
![image](https://user-images.githubusercontent.com/46549740/223618330-fccf6190-f8e9-450b-a383-08d54d284cc7.png)
A TKIB car with a RPQS dog
![image](https://user-images.githubusercontent.com/46549740/223618505-56a3a2fd-c4ff-4b62-9b43-4710bf83c296.png)

**The results of multi-subjects experiment get worse quality and seem to be fake images.**

### 3. In my experiment, what might be the reason for the bad results?  Is this result due to SR not being finetuned?

**Comment by qq110146** [comment]
Hi @patrickvonplaten  can someone help with this issue? Thanks!

**Comment by patrickvonplaten** [comment]
Hey @qq110146,

I think dreambooth has initially been proposed only on single subject. Could you maybe try to use the forum with your very nice description to look for help: https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63

**Comment by qq110146** [comment]
> Hey @qq110146,
> 
> I think dreambooth has initially been proposed only on single subject. Could you maybe try to use the forum with your very nice description to look for help: https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63

Okay, I will ask for help there. Thank you very much!
