### ISSUE TITLE
MLP in the diffusers library

### ISSUE THREAD

**Issue by yass43** [huggingface/diffusers#2607]
Hello,
I'm currently dealing with very small size images, (1,8,8) for example, and would like to train a latent denoising model using an MLP or a ResMLP instead of a UNet2DModel, are there any available implementations for such a task? Do you suggest another architecture?
Thanks

**Comment by patrickvonplaten** [comment]
Hey @yass43, 

Could you try to use the forum for such questions instead: https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63 ? 

We try to keep GitHub for issues mostly
