### ISSUE TITLE
Cannot change pre-trained-model download directory

### ISSUE THREAD

**Issue by xingzhehe** [huggingface/diffusers#2614]
### Describe the bug

I tried the very first example **Text-to-Image generation with Stable Diffusion**. 

I have set every single variable I can find on Internet to the current path, but it keeps downloading model to `~/.cache`. I have very limited home space, so it keeps telling me no space on the disk.

### Reproduction

import torch
from diffusers import StableDiffusionPipeline
import os

os.environ['TORCH_HOME'] = os.path.abspath(os.getcwd())
os.environ['HF_HOME'] = os.path.abspath(os.getcwd())
os.environ['XDG_CACHE_HOME'] = os.path.abspath(os.getcwd())
os.environ['HUGGINGFACE_HUB_CACHE'] = os.path.abspath(os.getcwd())
os.environ['TRANSFORMERS_CACHE'] = os.path.abspath(os.getcwd())

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]

### System Info

I am using ubuntu 20.04, and the latest diffuser.

**Comment by stevhliu** [comment]
You can see the `cache_dir` [parameter](https://huggingface.co/docs/diffusers/main/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.from_pretrained.cache_dir) from the `main` version of the docs :)

**Comment by xingzhehe** [comment]
> 

After I set cache_dir=".", it seems not to be able to find some config file:

Traceback (most recent call last):
  File "XXXXXX/test_diffuser.py", line 13, in <module>
    pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16, cache_dir='.')
  File "XXXXXX/anaconda3/envs/xxxx/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 589, in from_pretrained
    config_dict = cls.load_config(
  File "XXXXXX/anaconda3/envs/xxxx/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 380, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "XXXXXX/anaconda3/envs/xxxx/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 479, in _dict_from_json_file
    with open(json_file, "r", encoding="utf-8") as reader:
FileNotFoundError: [Errno 2] No such file or directory: './models--runwayml--stable-diffusion-v1-5/snapshots/39593d5650112b4cc580433f6b0435385882d819/model_index.json'

**Comment by patrickvonplaten** [comment]
Hmm that's weird what happens if you set `cache_dir="./temp"` as a test?

**Comment by xingzhehe** [comment]
> Hmm that's weird what happens if you set `cache_dir="./temp"` as a test?

It gives the same error.

**Comment by wrk226** [comment]
I encountered a similar situation and solved my problem by using symbolic links.
For example, assume you want to move the cache files to `/home/temp` folder，you may try:
`
mv ~/.cache/huggingface /home/temp/
ln -s  /home/temp/huggingface ~/.cache/huggingface
`
Hope it helps.

**Comment by xingzhehe** [comment]
> I encountered a similar situation and solved my problem by using symbolic link. For example, assume you want to move the cache files to `/home/temp` folder，you can do:
> 
> ```
> mv ~/.cache/huggingface /home/temp/
> ln -s /home/temp/huggingface ~/.cache/huggingface
> ```
> 
> Hope it helps.

Yes it helps! Thank you so much! But I really think this is a bug and should be fixed.

**Comment by patrickvonplaten** [comment]
Hmm I really cannot reproduce this - @Wauplin do you have an idea maybe what could be going on here? 

Also @xingzhehe, could you please post what error message you get when doing:

```py
import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16, cache_dir="./cache_dir")
```

**Comment by Wauplin** [comment]
Hi @xingzhehe, I made a patch release to fix this (see [release notes](https://github.com/huggingface/huggingface_hub/releases/tag/v0.13.2)).
So if you upgrade `huggingface_hub` to version 0.13.2, it should be your issue. You must delete the corrupted cache folder before. Please let me know if you have any related issue.

**Comment by xingzhehe** [comment]
> Hi @xingzhehe, I made a patch release to fix this (see [release notes](https://github.com/huggingface/huggingface_hub/releases/tag/v0.13.2)). So if you upgrade `huggingface_hub` to version 0.13.2, it should be your issue. You must delete the corrupted cache folder before. Please let me know if you have any related issue.

Thanks! The issue has been fixed!

**Comment by SuperBruceJia** [comment]
Please simply use
```shell
# Export the TRANSFORMERS_CACHE, HF_HOME, and HF_DATASETS_CACHE paths
export TRANSFORMERS_CACHE=/projectnb/pnn/.cache
export HF_HOME=/projectnb/pnn/.cache
export HF_DATASETS_CACHE=/projectnb/pnn/.cache
```

or

```python
import os

os.environ['TRANSFORMERS_CACHE'] = "/projectnb/pnn/.cache"
os.environ['HF_HOME'] = "/projectnb/pnn/.cache"
os.environ['HF_DATASETS_CACHE'] = "/projectnb/pnn/.cache"
```
