### ISSUE TITLE
torch.FloatTensor as image input for StableDiffusionControlNetPipeline

### ISSUE THREAD

**Issue by jingyangcarl** [huggingface/diffusers#2618]
### Describe the bug

I get "tuple index out of range" when using torch.FloatTensor as input

### Reproduction

```
output = pipe(
                [p + ', best quality, extremely detailed'],
                image=torch.FloatTensor(depth_cut),
                negative_prompt=['longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality'],
                generator=generator,
                num_inference_steps=20,
            )
```

### System Info

- `diffusers` version: 0.14.0
- Platform: Linux-5.4.0-139-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.12.1
- Transformers version: 4.26.0
- Accelerate version: 0.17.0.dev0
- xFormers version: 0.0.16

**Comment by patrickvonplaten** [comment]
Good point! This should be solved with https://github.com/huggingface/diffusers/pull/2617
