### ISSUE TITLE
Add support for external latent specification

### ISSUE THREAD

**Issue by gordicaleksa** [huggingface/diffusers#262]
https://colab.research.google.com/github/pcuenca/diffusers-examples/blob/main/notebooks/stable-diffusion-seeds.ipynb <- this notebook (linked in the README) makes it seem as if we can specify the latent externally, but looking at the code that doesn't seem to work.

Here is a [proposed tweak](https://gist.github.com/karpathy/00103b0037c5aaea32fe1da1af553355?permalink_comment_id=4281835#gistcomment-4281835) (comment on karpathy's gist, some asserts are needed)

**Comment by pcuenca** [comment]
Hi Aleksa, thanks for writing!

That notebook relies on PR #247, which was recently merged. It should work with the `main` branch of diffusers, but not yet with the latest PyPi version (0.2.4). Could you please try with `main` instead? If it still doesn't work, please do let us know! :)

Thanks again!

**Comment by gordicaleksa** [comment]
Hi Pedro!

Thanks for the quick reply! 

Ah, ok, I'm on the older version apparently recommended for stable diffusion (`0.2.4`) so I missed this one! LGTM!
