### ISSUE TITLE
Adding cosine with decay

### ISSUE THREAD

**Issue by isamu-isozaki** [huggingface/diffusers#2628]
**Is your feature request related to a problem? Please describe.**
Hi! We wanted to add cosine with decay optimizer to diffusers since in training muse and other experiments, it's very valuable.

**Describe the solution you'd like**
I'll make a pr.

**Comment by isamu-isozaki** [comment]
Sorry, need double checking but this might already be implemented.

**Comment by pcuenca** [comment]
Hi @isamu-isozaki! For reference, there are a couple of cosine schedules currently implemented:

https://github.com/huggingface/diffusers/blob/main/src/diffusers/optimization.py#L109
https://github.com/huggingface/diffusers/blob/main/src/diffusers/optimization.py#L143

**Comment by isamu-isozaki** [comment]
@pcuenca Thank you! Let me confirm

**Comment by isamu-isozaki** [comment]
Ah, yup as far as I can see, I think cosine with decay is just implemented as cosine in diffusers. But I am by no means an expert here so feel free to reopen if I'm wrong!
