### ISSUE TITLE
`DDIMScheduler` does not work unless `set_timesteps` is used

### ISSUE THREAD

**Issue by samedii** [huggingface/diffusers#263]
### Describe the bug

Need to set number of inference steps since "None" is default. Expected to have a default value.

Adding a very simple PR.

### Reproduction

```
    scheduler = DDIMScheduler(
        beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear"
    )
    # skipping this step will cause an exception later
    # scheduler.set_timesteps(1000)
    pipeline = StableDiffusionPipeline.from_pretrained(
        model_name,
        scheduler=scheduler,
        use_auth_token=True,
    ).to(device)
```

### Logs

```shell
>       prev_timestep = timestep - self.config.num_train_timesteps // self.num_inference_steps
E       TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'
```

### System Info

```shell
diffusers v0.2.4
python 3.8.8
```

**Comment by pcuenca** [comment]
Sorry, I responding to your PR before I saw this issue. @anton-l what do you think?

**Comment by natolambert** [comment]
If I recall correctly all of the schedulers are not designed to run without calling `set_timesteps()` because of the heavy dependence of inference on `num_inference_timesteps` and how the timesteps match with the inference loop.

**Comment by patrickvonplaten** [comment]
@samedii, actually quick question: How to do you exactly get the above error? 
The stable diffusion pipeline should always correctly set the number of timesteps, see: https://github.com/huggingface/diffusers/blob/efa773afd2a99f6041043298d9f3e8bcdaa325c7/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L121

How exactly do you get the error:
```
>       prev_timestep = timestep - self.config.num_train_timesteps // self.num_inference_steps
E       TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'
```

If you do: 

```python
    scheduler = DDIMScheduler(
        beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear"
    )
    # skipping this step will cause an exception later
    # scheduler.set_timesteps(1000)
    pipeline = StableDiffusionPipeline.from_pretrained(
        model_name,
        scheduler=scheduler,
        use_auth_token=True,
    ).to(device)
   pipeline("an image of a planet")
```

it should work correctly

**Comment by samedii** [comment]
> @samedii, actually quick question: How to do you exactly get the above error?
> ...

Sorry I answered in the PR. I built my own pipeline using your components.

**Comment by samedii** [comment]
Sorry forgot to close
