### ISSUE TITLE
which scheduler is  "DPM++ 2s a Karras" and "DPM++ 2M Karras" ?

### ISSUE THREAD

**Issue by ym-ctw** [huggingface/diffusers#2635]
### Model/Pipeline/Scheduler description

I used scheduler 【DPM ++ 2s a Karras】 and 【DPM++ 2M Karras】before in sd-webui, and I know these two scheduler has better performance. 
And I found that diffusers has single/multi-DPM solver , but I don't know which  is DPM ++ 2s a Karras or DPM++ 2M Karras.
Could you please tell me about that? thanks!

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by ClashSAN** [comment]
You have DPMSolverMultistepScheduler which by default is DPM++ 2M I think. 

it was added here: https://github.com/huggingface/diffusers/pull/1132

DPM++ 2M Karras 
2 = 2nd order
M = multistep
a = ancestral
Karras = special noise

**Comment by ym-ctw** [comment]
> 

Thanks for your detailed reply! I will try it later!

**Comment by ym-ctw** [comment]
> You have DPMSolverMultistepScheduler which by default is DPM++ 2M I think.
> 
> it was added here: #1132
> 
> DPM++ 2M Karras 2 = 2nd order M = multistep a = ancestral Karras = special noise

Thanks for your detailed reply! I will try it later!

**Comment by CrazyBoyM** [comment]
so when "DPM++ 2M Karras" equal to DPMSolverMultistepScheduler, which scheduler is "DPM++ 2s a Karras"?

**Comment by AdamMayor2018** [comment]
> so when "DPM++ 2M Karras" equal to DPMSolverMultistepScheduler, which scheduler is "DPM++ 2s a Karras"?

Do u have a clue now?

**Comment by CrazyBoyM** [comment]
maybe&nbsp;we&nbsp;should&nbsp;write&nbsp;it&nbsp;by&nbsp;add&nbsp;noise&nbsp;per&nbsp;step&nbsp;


---Original---
From: ***@***.***&gt;
Date: Thu, Jul 6, 2023 14:23 PM
To: ***@***.***&gt;;
Cc: &quot;Ke ***@***.******@***.***&gt;;
Subject: Re: [huggingface/diffusers] which scheduler is  &quot;DPM++ 2s a Karras&quot;and &quot;DPM++ 2M Karras&quot; ? (Issue #2635)




  
so when "DPM++ 2M Karras" equal to DPMSolverMultistepScheduler, which scheduler is "DPM++ 2s a Karras"?
  
Do u have a clue now?
 
&mdash;

**Comment by patrickvonplaten** [comment]
DPM++ 2M Karras => `DPMSolverMultistepScheduler.from_config(..., use_karras=True)`
DPM ++ 2M a Karras == =>  `DPMSolverMultistepScheduler.from_config(..., use_karras=True, algorithm_type="sde-dpmsolver++")`

I'd say

**Comment by bruce2233** [comment]
Thanks

**Comment by saeedkhanehgir** [comment]
@patrickvonplaten 

Thanks for sharing these notes.

In this [link](https://civitai.com/articles/1501/best-sampler-for-sdxl) , I read the best sampler for SDXL is DPM++ 2SA Karras , I want to know How can I implement this sampler with diffusers, Can you help me? 

thanks
