### ISSUE TITLE
tiled VAE fails with IndexError

### ISSUE THREAD

**Issue by keturn** [huggingface/diffusers#2646]
### Describe the bug

decoding with `enable_vae_tiling` fails with the Stable Diffusion 2.1 model on certain sizes, throwing an IndexError.

### Reproduction

```py
import diffusers, torch
pipeline = diffusers.StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1", torch_dtype=torch.float16, revision="fp16").to("cuda")
pipeline.enable_xformers_memory_efficient_attention()
pipeline.enable_vae_tiling()

t0 = torch.zeros((1, 4, 20, 24))

with torch.inference_mode():
    decoded = pipeline.decode_latents(t)
```

### Logs

```shell
IndexError: index 128 is out of bounds for dimension 2 with size 128
```

### System Info

- `diffusers` version: 0.14.0
- Platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.26.1
- Accelerate version: 0.16.0
- xFormers version: 0.0.16
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by sayakpaul** [comment]
Ccing @kig

**Comment by kig** [comment]
Thanks for the bug report!

I couldn't repro your test case with, is there something I'm missing?

```python
import diffusers, torch

with torch.inference_mode():
    pipeline = diffusers.StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1").to("cuda")
    pipeline.enable_xformers_memory_efficient_attention()
    pipeline.enable_vae_tiling()

    t = torch.zeros((1, 4, 20, 24)).to("cuda")

    decoded = pipeline.decode_latents(t)
```

**Comment by kig** [comment]
Okay, tried doing an exhaustive test on the {1..120 x 1..120} permutations and it did run into an error at (1, 4, 73, 97) input dimensions.

A fix is to modify the blend_h and blend_v functions in autoencoder_kl.py to:

```python
    def blend_v(self, a, b, blend_extent):
        for y in range(min(a.shape[2], b.shape[2], blend_extent)):
            b[:, :, y, :] = a[:, :, -blend_extent + y, :] * (1 - y / blend_extent) + b[:, :, y, :] * (y / blend_extent)
        return b

    def blend_h(self, a, b, blend_extent):
        for x in range(min(a.shape[3], b.shape[3], blend_extent)):
            b[:, :, :, x] = a[:, :, :, -blend_extent + x] * (1 - x / blend_extent) + b[:, :, :, x] * (x / blend_extent)
        return b
```

Here's the exhaustive test in case it's useful:

```python
import diffusers, torch

with torch.inference_mode(), torch.autocast("cuda"):
    pipeline = diffusers.StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1", torch_dtype=torch.float16, revision="fp16").to("cuda")
    pipeline.enable_xformers_memory_efficient_attention()
    pipeline.enable_vae_tiling()

    for i in range(1, 120):
      for j in range(1, 120):
        print(f"{i} x {j}")

        t = torch.zeros((1, 4, i, j)).to("cuda")

        decoded = pipeline.decode_latents(t)
```

**Comment by patrickvonplaten** [comment]
Thanks a lot for testing all this @kig - would you maybe like to open a PR to fix it?

**Comment by kig** [comment]
> Thanks a lot for testing all this @kig - would you maybe like to open a PR to fix it?

@patrickvonplaten Hey sure, I created #2660 with the above fix and tests for the failing sizes.
