### ISSUE TITLE
Model fails to load if StableDiffusionSafetyChecker safetensors are present

### ISSUE THREAD

**Issue by antoche** [huggingface/diffusers#2663]
### Describe the bug

This used to work fine a day ago:

```python
from diffusers import StableDiffusionPipeline
p = StableDiffusionPipeline.from_pretrained("prompthero/openjourney")
```

Now it fails with the following exception:

```python
NotImplementedError: Make sure `_init_weights` is implemented for <class 
 'diffusers.pipelines.stable_diffusion.safety_checker.StableDiffusionSafetyChecker'>
```

It seems due to the latest commit in that model's repo, from 12h ago, which adds safetensors for some of the models. Loading the previous revision works fine:

```python
p = StableDiffusionPipeline.from_pretrained("prompthero/openjourney", revision="1d4118b1339734ddba018e29ccf0545cbd59e252")
```

### Reproduction

See above

### System Info

- `diffusers` version: 0.13.1
- Platform: Linux-4.14.240
- Python version: 3.9.10
- PyTorch version (GPU?): 1.12.0a0+git664058f (True)
- Huggingface_hub version: 0.13.1
- Transformers version: 4.26.0
- Accelerate version: 0.13.1
- xFormers version: 0.0.14.dev

**Comment by patrickvonplaten** [comment]
Thanks a lot for the issue, I cannot really reproduce this sadly, but I got a warning with the safety checker as well. Could you maybe check if this new commit solves the issue: https://huggingface.co/prompthero/openjourney/discussions/63 ? 

E.g. could you just run the same command again?

**Comment by antoche** [comment]
The latest revision works now. I can still reproduce the problem by loading the problematic model revision:

```python
p = StableDiffusionPipeline.from_pretrained("prompthero/openjourney", revision="f8d948566c2a933d7d1bb4b6ae0f6fb53c53f99c")
```

If this an issue with the model, then I guess it's not a problem, but the error message could probably be improved, as it seems to indicate a bug in the code itself.

**Comment by patrickvonplaten** [comment]
Think it was a problem with the safety checker model weights

**Comment by antoche** [comment]
Is there a way the error message could have been made clearer? The `NotImplementedError` exception really makes it look like it's a bug in the code rather than an issue with the hub model.

**Comment by patrickvonplaten** [comment]
@antoche that's a very good point! The error message was indeed very bad here and it would make a lot of sense to improve it! We'd be more than happy about a PR here :-)

**Comment by WASasquatch** [comment]
I am getting this error with the latest code example for LCM (which is recent)

```
 raise NotImplementedError(f"Make sure `_init_weights` is implemented for {self.__class__}")
NotImplementedError: Make sure `_init_weights` is implemented for <class 'diffusers.pipelines.stable_diffusion.safety_checker.StableDiffusionSafetyChecker'>
```

https://github.com/luosiallen/latent-consistency-model#usage

Is it related?

**Comment by patrickvonplaten** [comment]
Hmm I'm not able to reproduce this error see: https://colab.research.google.com/drive/1gTXpp-d4OuCKhLRAjZn11a7P9Ihq0XH9?usp=sharing

Could you maybe add a reproducible code snippet?
