### ISSUE TITLE
Timestep embedding in UNet1DModel and UNet1DConditionModel

### ISSUE THREAD

**Issue by yujianll** [huggingface/diffusers#2664]
**Is your feature request related to a problem? Please describe.**
It seems the UNet1DModel does not support the timestep embedding as UNet2DModel. For example, [this function](https://github.com/huggingface/diffusers/blob/f20c8f5a1aba27f5972cad50516f18ba516e4d9e/src/diffusers/models/unet_1d_blocks.py#L499) does not consider the input `temb`. I wonder is there any plan for adding this, or am I missing something?
Also, there seems to be no implementation for UNet1DConditionModel. Would it be possible to add it in the future?

**Describe the solution you'd like**
Support timestep embedding as UNet2DModel.

**Comment by patrickvonplaten** [comment]
Hey @yujianll,

The reason this function doesn't have time embeddings is probably simply because the model using the corresponding block doesn't need to have time embeddings passed (maybe because it's already been concatenated before.)

**Comment by patrickvonplaten** [comment]
Not yet :-)
