### ISSUE TITLE
Textual Inversion training colab: ValueError: You have to specify the number of GPUs you would like to use, add `num_processes=...` to your call.

### ISSUE THREAD

**Issue by KaiyueSun98** [huggingface/diffusers#2675]
│ in <module>:2                                                                                    │
│                                                                                                  │
│   1 import accelerate                                                                            │
│ ❱ 2 accelerate.notebook_launcher(training_function, args=(text_encoder, vae, unet))              │
│   3                                                                                              │
│   4 for param in itertools.chain(unet.parameters(), text_encoder.parameters()):                  │
│   5   if param.grad is not None:                                                                 │
│                                                                                                  │
│ /home/kaiyuesun/anaconda3/envs/ldm/lib/python3.8/site-packages/accelerate/launchers.py:106 in    │
│ notebook_launcher                                                                                │
│                                                                                                  │
│   103 │   │   function(*args)                                                                    │
│   104 │   else:                                                                                  │
│   105 │   │   if num_processes is None:                                                          │
│ ❱ 106 │   │   │   raise ValueError(                                                              │
│   107 │   │   │   │   "You have to specify the number of GPUs you would like to use, add `num_   │
│   108 │   │   │   )                                                                              │
│   109                                                                                            │
╰─────────────────────────────────────────────────────────────────────────────────
ValueError: You have to specify the number of GPUs you would like to use, add `num_processes=...` to your call.

Does anyone know how to solve this issue about accelerator?

**Comment by patrickvonplaten** [comment]
Hey @KaiyueSun98, 

Could you try to link a reproducible code snippet or a link to the colab?

**Comment by KaiyueSun98** [comment]
Hi @patrickvonplaten ,

Thanks for your reply. I have managed to solve this problem.

The link to the colab is: [sd_textual_inversion_training.ipynb](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_textual_inversion_training.ipynb)
The code snippet with error is located here: [Training function](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_textual_inversion_training.ipynb#scrollTo=jXi0NdsyBA4S&line=4&uniqifier=1)
I was getting this error:
```                                                                                         
 ❱ 3 accelerate.notebook_launcher(training_function, args=(text_encoder, vae, unet))                         
   4                                                                                              
                                                                                                  
 /home/kaiyuesun/anaconda3/envs/ldm/lib/python3.8/site-packages/accelerate/launchers.py:106 in    
 notebook_launcher                                                                                
                                                                                                  
   103 │   │   function(*args)                                                                    
   104 │   else:                                                                                  
   105 │   │   if num_processes is None:                                                          
 ❱ 106 │   │   │   raise ValueError(                                                              
   107 │   │   │   │   "You have to specify the number of GPUs you would like to use, add `num_   
   108 │   │   │   )                                                                              
   109   
 ```
By specifying the num_processes `notebook_launcher(training_function, args=(text_encoder, vae, unet),num_processes=1)` in this way, the problem would be solved.

Thanks
