### ISSUE TITLE
"What Schedulers are supported on diffusers? I found some in the webUI that I couldn't find on diffusers, such as "DPM++ 2M Karras" and "DPM++ SDE Karras". Does anyone know their names on diffusers?"

### ISSUE THREAD

**Issue by XXXKAY** [huggingface/diffusers#2676]
### Model/Pipeline/Scheduler description

"What Schedulers are supported on diffusers? I found some in the webUI that I couldn't find on diffusers, such as "DPM++ 2M Karras" and "DPM++ SDE Karras". Does anyone know their names on diffusers?"

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by patrickvonplaten** [comment]
Hey @XXXKAY,

`"DPM++ 2M Karras"` corresponds to: https://huggingface.co/docs/diffusers/api/schedulers/multistep_dpm_solver
"DPM++ SDE Karras" is not yet supported see: https://github.com/huggingface/diffusers/issues/2064

**Comment by XXXKAY** [comment]
Thank you for your reply, and I am looking forward to "DPM++ SDE Karras".

**Comment by zetyquickly** [comment]
Seems like https://huggingface.co/docs/diffusers/api/schedulers/multistep_dpm_solver does correspond only to `DPM++ 2M`. `DPM++ 2M Karras` is not there yet. Am I correct, @patrickvonplaten ?

**Comment by zetyquickly** [comment]
Not very different. If compare A1111 webui with diffusers side by side. The results of `DPM++ 2M Karras (webui)` will be different from `DPM++ 2M (diffusers)`. At the same time `DPM++ 2M (webui)` will be almost identical with `DPM++ 2M (diffusers)`. 

In a message above there's three images with [examples](https://github.com/huggingface/diffusers/issues/2676#issuecomment-1476444796)

Mine are `DPM++ 2M (diffusers)` vs `DPM++ 2M (webui)`:
![diffusers](https://user-images.githubusercontent.com/25350960/227285675-7d9828ef-d734-4057-aa64-2d179301305a.png)
![webui](https://user-images.githubusercontent.com/25350960/227285688-fa2842b5-a8ae-439f-9f1b-dd0beb90ea6e.png)

And `DPM++ 2M Karras (webui)`
![webui_karras](https://user-images.githubusercontent.com/25350960/227285755-f6f8b2c4-16cc-41d8-a242-3f446ced7038.png)

From the perspective of quality it's arguably different, but from perspective of the highest reproducibility. It would be great to understand how to recreate `DPM++ 2M Karras (webui)` in `diffusers`

**Comment by patrickvonplaten** [comment]
Interesting thanks for the comparison here. For reproducibability I think we need to work on this issue: https://github.com/huggingface/diffusers/issues/1633 

I currently don't find the time to work on it, but would be very happy to guide someone in case @zetyquickly you'd be interested :-)

**Comment by FurkanGozukara** [comment]
What is equivalent of DPM++ 2M SDE Karras
