### ISSUE TITLE
How to use attend-and-excite pipeline with inpainting or depth pipelines?

### ISSUE THREAD

**Issue by himmetozcan** [huggingface/diffusers#2679]
If I am not mistaken attend-and-excite pipeline is using text2img model. Is it possible to use it with "runwayml/stable-diffusion-inpainting" or "stabilityai/stable-diffusion-2-depth" pipelines? Thanks.

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu

**Comment by yiyixuxu** [comment]
Hi @himmetozcan 

I think you would need to create a custom pipeline with the attend-and-excite process added to it 
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_attend_and_excite.py#L887

happy to help if you decide to give it a try 🤗

**Comment by himmetozcan** [comment]
Hi again. I have implemented it for the [depth pipeline](https://github1s.com/huggingface/diffusers/blob/HEAD/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_depth2img.py). However, the result of the modified (attend-and-excite process added) and unmodified (original depth pipeline) pipelines are almost the same.

Perhaps, the depth input in u-net is becoming too dominant in terms of conditioning the output, much more than what attend and excite process is doing, and that is why we are not seeing any important change in the output, what do you think?

Below are my `input image`, `result of depth2img attend-excite`, `result of depth2img-regular`, and the `difference image` respectively. Used same seeds. 

I have also checked the loss value at each step and it is not decreasing (around 0.98).
 
`Prompt = "a blue cat wearing a crown"`

(image url = "https://cdn.britannica.com/86/166986-050-4CEFE5DE/cute-kitten-and-puppy-outdoors-in-grass.jpg")
![image](https://user-images.githubusercontent.com/44242024/226172052-3be9b8c2-3100-411b-9c5a-78fa52e12a27.png)

![image](https://user-images.githubusercontent.com/44242024/226172294-e630d310-2657-4782-8ec1-aa7bdcb6fb9d.png)
![image](https://user-images.githubusercontent.com/44242024/226172310-cb625f2d-4b39-4bc8-ace0-84dd4c4f8e73.png)
![image](https://user-images.githubusercontent.com/44242024/226172536-fccf834b-df07-4f65-849a-a6fafd618efd.png)

**Comment by Pie31415** [comment]
Hello, if this task isn't already taken/completed do you mind if I give it a shot?

**Comment by himmetozcan** [comment]
Yes ofcourse

Andy ***@***.***>, 19 Mar 2023 Paz, 22:35 tarihinde şunu
yazdı:

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu here

**Comment by yiyixuxu** [comment]
@himmetozcan what results do you expect to see?
it seems to me that stable diffusion was able to correctly place the crown onto the blue cat without the help from attend-and-excite
