### ISSUE TITLE
the FID for the Stable Diffusion

### ISSUE THREAD

**Issue by jiayisunx** [huggingface/diffusers#2681]
In the NVIDIA paper "eDiff-I: Text-to-Image Diffusion Models with an Ensemble of Expert Denoisers", it said the zero-shot FID for the stable diffusion on the COCO2014 validation set can be 8.59:
![image](https://user-images.githubusercontent.com/50946601/225237742-23883700-df0b-476d-bb0c-ea1035b40296.png)
 And I see a chart of FID vs CLIP scores in https://huggingface.co/runwayml/stable-diffusion-v1-5, but no specific number:
![image](https://user-images.githubusercontent.com/50946601/225239104-3a81b778-f583-4876-94b8-5dc973f9d60f.png)

Can you tell me the official FID score for the stable-diffusion?

**Comment by patrickvonplaten** [comment]
To be honest, I also don't really know here - gently pinging the original author @pesser

**Comment by jiayisunx** [comment]
Or would it be possible to share the specific scores from the chart of FID vs CLIP scores I mentioned above, and I would really appreciate it if you can share the code to reproduce the scores. Thanks!

**Comment by ntajbakhsh** [comment]
The numbers you read from the graph are based on a 10k validation set, and I think the numbers in the table are based on a 30k set. In general, the larger the validation set, the smaller the FIDs. In the graph below, we have generated the plot for HF-SD 1.5 using a 30k set. As you can see, the lowest FID is close to what you see in the table. In case, you are curious, the other curve, labeled as NeMo-SD, is our re-implementation of SD, which we release along with a convergence recipe as a part of Nvidia's NeMo Multimodal.
![image](https://user-images.githubusercontent.com/12647849/234698791-121f3f98-eff0-4569-8a7c-95ed25f07ec1.png)

**Comment by jiayisunx** [comment]
Hi @ntajbakhsh, thank you for your reply! Can you please share the script to reproduce the scores?

**Comment by prachi-mcw** [comment]
how you @ntajbakhsh how you calculated the clip score , i am getting clip scores like 33.567 something , not as low as marked in graph plotted  above
