### ISSUE TITLE
Samplers & Documentation

### ISSUE THREAD

**Issue by dblunk88** [huggingface/diffusers#271]
I am confused about how to properly implement the various samplers with the StableDiffusionPipeline. The default values output garbage. The only preset I could find is for LMS. It would be helpful to have documentation on-hand with how to properly implement them. 

Additionally, more options would also be nice, specifically the ones used by k-diffusion: https://github.com/crowsonkb/k-diffusion/blob/master/k_diffusion/sampling.py

**Comment by patrickvonplaten** [comment]
That's great feedback @dblunk88 ! 
We're working on docs and should have that ready in ~2 weeks. Regarding the various samplers we should indeed write this down a bit better - opening a PR for this :-)

**Comment by dblunk88** [comment]
> That's great feedback @dblunk88 ! We're working on docs and should have that ready in ~2 weeks. Regarding the various samplers we should indeed write this down a bit better - opening a PR for this :-)

Much appreciated! If it helps: DDIM seems to work only if clip_sample=False

**Comment by patrickvonplaten** [comment]
Here a summary of how to use the different samplers:

## Examples:

### Text-to-Image with default PLMS scheduler

```python
# make sure you're logged in with `huggingface-cli login`
from torch import autocast
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", use_auth_token=True)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
with autocast("cuda"):
    image = pipe(prompt)["sample"][0]  
    
image.save("astronaut_rides_horse.png")
```

### Text-to-Image with DDIM scheduler

```python
# make sure you're logged in with `huggingface-cli login`
from torch import autocast
from diffusers import StableDiffusionPipeline, DDIMScheduler

scheduler = DDIMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", clip_sample=False, set_alpha_to_one=False)

pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4", 
    scheduler=scheduler,
    use_auth_token=True
).to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
with autocast("cuda"):
    image = pipe(prompt)["sample"][0]  
    
image.save("astronaut_rides_horse.png")
```

### Text-to-Image with K-LMS scheduler

```python
# make sure you're logged in with `huggingface-cli login`
from torch import autocast
from diffusers import StableDiffusionPipeline, LMSDiscreteScheduler

lms = LMSDiscreteScheduler(
    beta_start=0.00085, 
    beta_end=0.012, 
    beta_schedule="scaled_linear"
)

pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4", 
    scheduler=lms,
    use_auth_token=True
).to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
with autocast("cuda"):
    image = pipe(prompt)["sample"][0]  
    
image.save("astronaut_rides_horse.png")

**Comment by patrickvonplaten** [comment]
@dblunk88 what other schedulers/samplers from the k-diffusion GitHub were you thinking of?

**Comment by dblunk88** [comment]
> @dblunk88 what other schedulers/samplers from the k-diffusion GitHub were you thinking of?

If I had to single out one, I'd say Euler would be nice to have.

Realistically speaking though, it would be nice to have the entire library of https://github.com/crowsonkb/k-diffusion/blob/master/k_diffusion/sampling.py . It's just more options since each sampler has it's up & downsides.

**Comment by dblunk88** [comment]
Segregated this into #277
