### ISSUE TITLE
Support K-LMS for inpainting

### ISSUE THREAD

**Issue by Inkorak** [huggingface/diffusers#272]
You have added K-LMS support to [image_to_image.py](https://github.com/huggingface/diffusers/blob/main/examples/inference/image_to_image.py), can you add it to [inpainting.py](https://github.com/huggingface/diffusers/blob/main/examples/inference/inpainting.py)?

**Comment by patrickvonplaten** [comment]
cc @anton-l here :-)

**Comment by patrickvonplaten** [comment]
cc @anton-l
