### ISSUE TITLE
what's the difference between 'train_text_to_image_lora.py' and 'train_dreambooth_lora.py' ?

### ISSUE THREAD

**Issue by anonymoussss** [huggingface/diffusers#2720]
what's the difference between examples/text_to_image/train_text_to_image_lora.py and examples/dreambooth/train_dreambooth_lora.py ?

**Comment by sayakpaul** [comment]
Conceptually, there are very few differences.

In DreamBooth, we generally use prior preservation. In the vanilla text to image fine-tuning, we don't do that. 

DreamBooth requires a significantly smaller dataset, but that is not the case for the vanilla text to image fine-tuning. 

I am closing the issue for now, feel free to re-open.

**Comment by edwardelric1202** [comment]
> 

How many images are enough for vanilla text to image fine-tuning? I tried dozens of images, but seems not perform good.

**Comment by sayakpaul** [comment]
It really depends on the variety involved in the images in terms of subjects, compositions, concepts, etc.  

So, if you're looking for having more control over the generated outputs, you might want to take a look at this document (slightly outdated, will update soon): https://huggingface.co/docs/diffusers/main/en/using-diffusers/controlling_generation

**Comment by edwardelric1202** [comment]
> 

many thanks, I'll check it out.

**Comment by noanti** [comment]
@sayakpaul  So if I disable `with_prior_preservation` parameter in `train_dreambooth_lora.py`, it basically should be same with `train_text_to_image_lora.py`, right?
