### ISSUE TITLE
Error when loading models with cache_dir set

### ISSUE THREAD

**Issue by Skquark** [huggingface/diffusers#2729]
I'm suddenly having a problem when I set cache_dir=path in .from_pretrained and can't get around it.  It used to work fine a few days ago, and it works when cache_dir=None, but now when I have it pointing to my Google Drive on Colab, I'm getting this message:
```
  File "<ipython-input-7-cc85556e36ff>", line 8965, in get_lpw_pipe
    pipe = DiffusionPipeline.from_pretrained(model_path, custom_pipeline="AlanB/lpw_stable_diffusion_mod", cache_dir=prefs['cache_dir'] if bool(prefs['cache_dir']) else None, torch_dtype=torch.float16, safety_checker=None if prefs['disable_nsfw_filter'] else StableDiffusionSafetyChecker.from_pretrained("CompVis/stable-diffusion-safety-checker").to(torch_device), requires_safety_checker=not prefs['disable_nsfw_filter'])
  File "/usr/local/lib/python3.9/dist-packages/diffusers/pipelines/pipeline_utils.py", line 764, in from_pretrained
    cached_folder = cls.download(
  File "/usr/local/lib/python3.9/dist-packages/diffusers/pipelines/pipeline_utils.py", line 1093, in download
    config_file = hf_hub_download(
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/file_download.py", line 1256, in hf_hub_download
    _create_symlink(blob_path, pointer_path, new_blob=False)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/file_download.py", line 857, in _create_symlink
    os.symlink(abs_src, abs_dst)
OSError: [Errno 95] Operation not supported: '/content/drive/MyDrive/AI/Stable_Diffusion/models/models--prompthero--openjourney/blobs/ec7e89e526405bf51ca1f538c8d48e76fd3e8f27' -> '/content/drive/MyDrive/AI/Stable_Diffusion/models/models--prompthero--openjourney/snapshots/bf2f700a1623c5d0de5197ae6267e96db9bea998/model_index.json'
```
It happens with all models I try to load, and I can't track it down to any recent changes.  Maybe it's from the huggingface_hub repo, I don't know, everything is up to date and looks normal in the code.  Couldn't find any issues posted about "Errno 95" but hoping it's an easy fix.  Thanks..

**Comment by Skquark** [comment]
Looks like it's related to an update in huggingface_hub from 3 days ago regarding relative symlinks in cache in this commit: https://github.com/huggingface/huggingface_hub/commit/cdaa4107909861e16a37546624942636b3cf242a
They modified those exact lines in file_download, but still don't know what the fix would be.  I'm using an absolute path in cache_dir.  Any clues?

**Comment by Skquark** [comment]
No problem, sounds like a pain. As a note, I was getting this error on Colab running Linux, though it'd probably have an error on Windows too..

**Comment by Wauplin** [comment]
Hmm ok. Could you share the script you are using please?

**Comment by Wauplin** [comment]
@Skquark asking because I didn't have a problem when running a basic `diffusers` example in a google colab (using `huggingface_hub=0.13.2` and running on a free GPU):

```py
from diffusers import StableDiffusionPipeline
import torch
model_id = "prompthero/openjourney"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")
prompt = "retro serie of different cars with different colors and shapes, mdjrny-v4 style"
image = pipe(prompt).images[0]
```

Here is my example google colab: https://colab.research.google.com/drive/1n3HphUN4LjRqnlOfQLWWZ67TEudLm73X

(BTW I'm reverting back to relative symlinks in https://github.com/huggingface/huggingface_hub/pull/1399 - will do a patch release soon)

**Comment by Skquark** [comment]
Alright, tried again with the latest huggingface_hub and we can once again load from cache_dir without error.  Looks like that hotfix did the trick.  I haven't tested it on a Windows local run (my GPU not good enough), but hopefully works there too.  Thank you so much, think we can consider this particular issue resolved...

**Comment by sayakpaul** [comment]
Closing it then. Feel free to re-open in case of problems.

**Comment by Wauplin** [comment]
Good, thanks for the feedback @Skquark and glad it worked!
We had users facing the same issue on Windows and it works for them as well so we are good as well on this topic.

Have fun with `diffusers` now! :)
