### ISSUE TITLE
CLIP Guidance support for DPMSolverMultistepScheduler

### ISSUE THREAD

**Issue by yuvalkirstain** [huggingface/diffusers#2737]
**Is your feature request related to a problem? Please describe.**
Hi, CLIP guidance can be very useful. I saw that there is a [community pipeline](https://github.com/huggingface/diffusers/blob/main/examples/community/clip_guided_stable_diffusion.py) but it only supports specific schedulers. Specifically, it does not support DPMSolverMultistepScheduler, which is very popular today.

**Describe the solution you'd like**
I would love for huggingface to upgrade this pipeline, and make it support DPMSolverMultistepScheduler.

**Comment by nipunjindal** [comment]
@patrickvonplaten @patil-suraj I can take dig at it while I am already at CLIP guidance for now. Would that be ok and worth it?

**Comment by sayakpaul** [comment]
Sure. Please feel free to rework the community pipeline to add support. 

Thanks for willingness.
