### ISSUE TITLE
How to use "learned_embeds.bin" files?

### ISSUE THREAD

**Issue by yanzengatsmu** [huggingface/diffusers#2743]
I finetuend on textual inversion and got "learned_embeds.bin" files. I did not save checkpoints. Can I use these learned embedding files to test the model in specific training steps?

**Comment by sayakpaul** [comment]
I think you should be able to. The reason why you didn't get any other checkpoint files is because text encoder doesn't touch anything other than the embedding layer of the text encoder.

**Comment by yanzengatsmu** [comment]
> 

Thank you so much for your reply. How can I specify the learned embedding file I want to load? Is there any function or do I need to manually load the embedding like this? `token_embeds[placeholder_token_id] = load_embeds(learned_embeds.bin)[placeholder_token_id]`

**Comment by sayakpaul** [comment]
Ah got it! I think we are indeed missing that functionality. #2009 is on the way to fix it. 

@patrickvonplaten cc.
