### ISSUE TITLE
MultiControlNet failed to execute 

### ISSUE THREAD

**Issue by waquey** [huggingface/diffusers#2744]
Dear great author, 

I've tried to apply multi-controlnet 
While executing the code 
" 
pipe = StableDiffusionControlNetPipeline.from_pretrained(
        "example/a-sd15-variant-model", torch_dtype=torch.float16,
        controlnet=control_net_lists,
    ).to("cuda")
"

It will return the error as following  

_requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/example/a-sd15-variant-model/resolve/main/model_index.json_

However, I've tried to git clone the file and type in account and password, it shows the file does not exist.  
Can anyone help? Thanks

**Comment by sayakpaul** [comment]
You're passing a wrong checkpoint as https://huggingface.co/example/a-sd15-variant-model doesn't exist. If you change it to `runwayml/stable-diffusion-v1-5` it should work.

**Comment by waquey** [comment]
> You're passing a wrong checkpoint as https://huggingface.co/example/a-sd15-variant-model doesn't exist. If you change it to `runwayml/stable-diffusion-v1-5` it should work.

Thanks a lot! It works now

**Comment by sayakpaul** [comment]
Closing the issue for now. Feel free to re-open.
