### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by standardAI** [huggingface/diffusers#2747]
On this page, "https://huggingface.co/docs/diffusers/main/en/optimization/torch2.0", it says "... as the stable version is yet to be released.".

**Comment by sayakpaul** [comment]
Thanks for pointing it out. I think, in general, the [Torch 2.0 doc](https://github.com/huggingface/diffusers/blob/main/docs/source/en/optimization/torch2.0.mdx) needs some modifications. 

@pcuenca, could you maybe address it?

**Comment by pcuenca** [comment]
I just merged #2764 to update the PyTorch 2 docs. @standardAI thanks a lot, and feel free to open a new issue if you see other problems :)
