### ISSUE TITLE
How about add face-landmarks at the control-net support?

### ISSUE THREAD

**Issue by circuluspibo** [huggingface/diffusers#2750]
https://huggingface.co/georgefen/Face-Landmark-ControlNet

I found new trial of controlnet though face-landmark.
It's useful for changing or  modifying the face using diffusers.
Could you support this at the next release?

**Comment by sayakpaul** [comment]
Hi. For this to work, I think we only need to have the `controlnet` model parameters converted from the above checkpoints such that it's compatible with the `StableDiffusionControlNetPipeline` ([docs](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/controlnet)). 

You can refer to the following that performs this conversion (i.e., from the original ControlNet conditioning checkpoints to what's expected in Diffusers):

https://github.com/huggingface/diffusers/blob/73bdad08a1fae592c73e211b55b83745c487b5ea/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L957

Cc: @williamberman

**Comment by patrickvonplaten** [comment]
Also cc @apolinario , I think you've been working on similar things no? and cc @pcuenca

**Comment by piEsposito** [comment]
I needed that, so I performed the conversion: https://huggingface.co/piEsposito/face-landmark-controlnet-from-georgefen-diffusers

**Comment by innat-asj** [comment]
With **mediapipe** https://huggingface.co/CrucibleAI/ControlNetMediaPipeFace - supports both sd 1.5 and 2.1.

![image](https://user-images.githubusercontent.com/81627860/233142253-92d5d30a-b2d2-4f2f-8915-0c46d1e90a09.png)
