### ISSUE TITLE
Virus dected in Latent Upscaler

### ISSUE THREAD

**Issue by brurpo** [huggingface/diffusers#2754]
Hi there, suddenly my latent upscaler stopped working in my gui, then I realyzed that the pytorch bin file was missing.
When I tried to download from here, chrome accused a virus in the file. Then I checked windows defender and saw that the file was missing because windows defender detected it as a virus and deleted it.
I think this is probably a false positive, right? But both chrome and windows defender detected it. I allowed the 'threat' and everything seems to be fine. Is there something we can do?

**Comment by sayakpaul** [comment]
Interesting. Maybe it flagged as it's a `bin` file?

**Comment by patrickvonplaten** [comment]
Can you send some links @brurpo ?

**Comment by brurpo** [comment]
Hi there, sure!
it was downloaded from here:
https://huggingface.co/stabilityai/sd-x2-latent-upscaler/blob/main/vae/diffusion_pytorch_model.bin

These are from windows defender
![image](https://user-images.githubusercontent.com/24902022/226683933-13d198cb-ab18-47a3-81c5-e5db34c665a2.png)
![image](https://user-images.githubusercontent.com/24902022/226684076-f660c15c-9342-4c61-aa76-200565dc47d5.png)

**Comment by patrickvonplaten** [comment]
uff wow - that's weird :sweat_smile: 

It should be better when using the just merged safetensors checkpoint though no? https://huggingface.co/stabilityai/sd-x2-latent-upscaler/discussions/5 

cc @Narsil
