### ISSUE TITLE
How to convert LoRA trained by diffusers to work on stable-diffusion-webui?

### ISSUE THREAD

**Issue by zhaoyuzhi** [huggingface/diffusers#2765]

**Comment by patrickvonplaten** [comment]
Might also be a good question for https://github.com/AUTOMATIC1111/stable-diffusion-webui maybe?

**Comment by A-cunminF** [comment]
Maybe you need this: https://github.com/A-cunminF/diffusers_utils/blob/main/convert_diffusers_lora_bin_to_webui.py

Useage:

```
python convert_lora_bin_to_webui.py --lora_bin_path=/PATH/TO/pytorch_lora_weights.bin --output_path=/PATH/TO/pytorch_lora_weights.safetensors
```

If your LoRA is not bin but safetensors, you can convert it to bin first by code below:

```python
from diffusers import DiffusionPipeline, DPMSolverMultistepScheduler
import torch

repo_id = "YOUR BASE MODEL PATH"
generator = DiffusionPipeline.from_pretrained(
    repo_id,
    torch_dtype=torch.float16,
    safety_checker=None
)
generator.unet.load_attn_procs("./lora_weights.safetensors")
generator.unet.save_attn_procs('./')
```

**Comment by JIAOJIAYUASD** [comment]
How to convert a loha or lokr safetensor trained from diffusers to webui format? [qustion](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/15661)
