### ISSUE TITLE
The `train_controlnet.py` script prevents valid local datasets from being used

### ISSUE THREAD

**Issue by jfischoff** [huggingface/diffusers#2772]
### Describe the bug

The `train_controlnet.py` script has a `--train_data_dir` flag for training with local datasets. However, using it seems impossible. This is because the code works by assuming the data is in the `imagefolder` format, which AFAICT tell from all the examples, expects a single image, but the controlnet data requires two images, one for the vanilla SD training and one for the controlnet training. 

It is possible that there is a way to format the directories so it can be used with the `imagefolder` format and two images, but I was unable to figure that out (happy to be wrong here).

To get the code working for local datasets (like the fusing/fill50k example dataset), I modified the code to not assume the data is in the `imagefolder` format and then it can work with a setup .py file.  

### Reproduction

call `train_controlnet.py` with the "--train_data_dir" flag

### System Info

- `diffusers` version: 0.15.0.dev0
- Platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
- Python version: 3.9.13
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.13.2
- Transformers version: 4.26.1
- Accelerate version: 0.17.1
- xFormers version: 0.0.16
- Using GPU in script?: NVidia RTX 3090 Ti
- Using distributed or parallel set-up in script?: nope

**Comment by patrickvonplaten** [comment]
cc @pcuenca @williamberman @yiyixuxu - can someone have a look here?

**Comment by WaltBao** [comment]
same problem

**Comment by patrickvonplaten** [comment]
Reping @williamberman @yiyixuxu here

**Comment by yiyixuxu** [comment]
Thanks for the issue! 
@jfischoff @WaltBao I think you are right - I will update the script

**Comment by williamberman** [comment]
Sorry for the delay here, thanks for the report @jfischoff and thanks for the fix @yiyixuxu  :)

**Comment by Tord-Zhang** [comment]
@jfischoff would you please share the setup.py? I am totally confused about how to format the directories. Thanks a lot.

**Comment by yiyixuxu** [comment]
@Tord-Zhang we have an example here (data.py) https://github.com/huggingface/community-events/tree/main/jax-controlnet-sprint/dataset_tools
