### ISSUE TITLE
Dreambooth train on 8GB should fix DeepSpeed==0.8.2 otherwise raise ZeRORuntimeException

### ISSUE THREAD

**Issue by polym** [huggingface/diffusers#2776]
### Describe the bug

I followed the instructions to [train the model on a 8GB gpu](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth#training-on-a-8-gb-gpu), installed DeepSpeed `pip3 install DeepSpeed`,  run `accelerate launch`, and then got ZeRORuntimeException which suggest to set <"zero_force_ds_cpu_optimizer": false in deepspeed config file. I tried to add it to .cache/huggingface/accelerate/default_config.yaml but make no sense. I searched the codes in [DeepSpeed](https://github.com/microsoft/DeepSpeed), ZeRORuntimeException was introduced by [this commit](https://github.com/microsoft/DeepSpeed/commit/457850dc5ad72960f0e8a8f1597914d682a7792c) in version 0.8.3. Therefore, I reinstall DeepSpeed with version 0.8.2, the problem was fixed. Is there any better approach to fix it?

### Reproduction

1. pip install -r requirements.txt
2. pip install DeepSpeed
3. accelerate config enable DeepSpeed
4. accelerate launch

### Logs

```shell
raise ZeRORuntimeException(msg)
deepspeed.runtime.zero.utils.ZeRORuntimeException: You are using ZeRO-Offload with a client provided optimizer (<class 'torch.optim.adamw.AdamW'>) which in most cases will yield poor performance. Please either use deepspeed.ops.adam.DeepSpeedCPUAdam or se
t an optimizer in your ds-config (https://www.deepspeed.ai/docs/config-json/#optimizer-parameters). If you really want to use a custom optimizer w. ZeRO-Offload and understand the performance impacts you can also set <"zero_force_ds_cpu_optimizer": false>
 in your configuration file.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2497) of binary:
```

### System Info

- `diffusers` version: 0.15.0.dev0
- Platform: Linux-5.3.0-46-generic-x86_64-with-glibc2.27
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.13.3
- Transformers version: 4.27.2
- Accelerate version: 0.17.1
- xFormers version: 0.0.16
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by hurun** [comment]
meet the same issue.
anyone can fixed?

**Comment by patrickvonplaten** [comment]
Good catch! @williamberman @sayakpaul @patil-suraj any chance you can look into this? I would honestly just pin deepspeed to 0.8.2 for now wdyt?

**Comment by zixiliuUSC** [comment]
do you have any update now? I try to run Alpaca's training script with deepspeed and meet the same error. See this issue https://github.com/tatsu-lab/stanford_alpaca/issues/93. My running script is below:
```
HOST_NUM=1
HOST_GPU_NUM=1
TJ_INSTANCE_ID="llama13b"
CHIEF_IP="localhost:29400"

torchrun \
    --nnodes=$HOST_NUM \
    --nproc_per_node=$HOST_GPU_NUM \
    --rdzv_id=$TJ_INSTANCE_ID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$CHIEF_IP \
    --master_port=12345 \
main.py \
    --model_name_or_path llama_13B_hf \
    --data_path ./alpaca_data.json \
    --bf16 True \
    --output_dir llama_13B_output \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --deepspeed ZeRO3.json
#--gradient_accumulation_steps 8 \
#    --fsdp "full_shard auto_wrap" \
    # --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
```

**Comment by sayakpaul** [comment]
Pinning sounds like the best solution to me. I would defer this to @williamberman.

**Comment by zixiliuUSC** [comment]
hey, I think the error comes from `get_optimizer_cls_and_kwargs` function in trainer. Try to add `deepspeed.ops.adam.DeepSpeedCPUAdam` cls in the if-else would be OK, correct?
```
    @staticmethod
    def get_optimizer_cls_and_kwargs(args: TrainingArguments) -> Tuple[Any, Any]:
        """
        Returns the optimizer class and optimizer parameters based on the training arguments.

        Args:
            args (`transformers.training_args.TrainingArguments`):
                The training arguments for the training session.

        """

        # parse args.optim_args
        optim_args = {}
        if args.optim_args:
            for mapping in args.optim_args.replace(" ", "").split(","):
                key, value = mapping.split("=")
                optim_args[key] = value

        optimizer_kwargs = {"lr": args.learning_rate}

        adam_kwargs = {
            "betas": (args.adam_beta1, args.adam_beta2),
            "eps": args.adam_epsilon,
        }
        if args.optim == OptimizerNames.ADAFACTOR:
            optimizer_cls = Adafactor
            optimizer_kwargs.update({"scale_parameter": False, "relative_step": False})
        elif args.optim == OptimizerNames.ADAMW_HF:
            from .optimization import AdamW

            optimizer_cls = AdamW
            optimizer_kwargs.update(adam_kwargs)
        elif args.optim == OptimizerNames.ADAMW_TORCH:
            from torch.optim import AdamW

            optimizer_cls = AdamW
            optimizer_kwargs.update(adam_kwargs)
        elif args.optim == OptimizerNames.ADAMW_TORCH_XLA:
            try:
                from torch_xla.amp.syncfree import AdamW

                optimizer_cls = AdamW
                optimizer_kwargs.update(adam_kwargs)
            except ImportError:
                raise ValueError("Trainer failed to import syncfree AdamW from torch_xla.")
        elif args.optim == OptimizerNames.ADAMW_APEX_FUSED:
            try:
                from apex.optimizers import FusedAdam

                optimizer_cls = FusedAdam
                optimizer_kwargs.update(adam_kwargs)
            except ImportError:
                raise ValueError("Trainer tried to instantiate apex FusedAdam but apex is not installed!")
        elif args.optim == OptimizerNames.ADAMW_BNB:
            try:
                from bitsandbytes.optim import Adam8bit

                optimizer_cls = Adam8bit
                optimizer_kwargs.update(adam_kwargs)
            except ImportError:
                raise ValueError("Trainer tried to instantiate bnb Adam8bit but bnb is not installed!")
        elif args.optim == OptimizerNames.ADAMW_ANYPRECISION:
            try:
                from torchdistx.optimizers import AnyPrecisionAdamW

                optimizer_cls = AnyPrecisionAdamW
                optimizer_kwargs.update(adam_kwargs)

                # TODO Change dtypes back to M=FP32, Var = BF16, Kahan = False once they can be cast together in torchdistx.
                optimizer_kwargs.update(
                    {
                        "use_kahan_summation": strtobool(optim_args.get("use_kahan_summation", "False")),
                        "momentum_dtype": getattr(torch, optim_args.get("momentum_dtype", "float32")),
                        "variance_dtype": getattr(torch, optim_args.get("variance_dtype", "float32")),
                        "compensation_buffer_dtype": getattr(
                            torch, optim_args.get("compensation_buffer_dtype", "bfloat16")
                        ),
                    }
                )
            except ImportError:
                raise ValueError("Please install https://github.com/pytorch/torchdistx")
        elif args.optim == OptimizerNames.SGD:
            optimizer_cls = torch.optim.SGD
        elif args.optim == OptimizerNames.ADAGRAD:
            optimizer_cls = torch.optim.Adagrad
        else:
            raise ValueError(f"Trainer cannot instantiate unsupported optimizer: {args.optim}")
        return optimizer_cls, optimizer_kwargs
```

**Comment by patrickvonplaten** [comment]
> do you have any update now? I try to run Alpaca's training script with deepspeed and meet the same error. See this issue [tatsu-lab/stanford_alpaca#93](https://github.com/tatsu-lab/stanford_alpaca/issues/93). My running script is below:
> 
> ```
> HOST_NUM=1
> HOST_GPU_NUM=1
> TJ_INSTANCE_ID="llama13b"
> CHIEF_IP="localhost:29400"
> 
> torchrun \
>     --nnodes=$HOST_NUM \
>     --nproc_per_node=$HOST_GPU_NUM \
>     --rdzv_id=$TJ_INSTANCE_ID \
>     --rdzv_backend=c10d \
>     --rdzv_endpoint=$CHIEF_IP \
>     --master_port=12345 \
> main.py \
>     --model_name_or_path llama_13B_hf \
>     --data_path ./alpaca_data.json \
>     --bf16 True \
>     --output_dir llama_13B_output \
>     --num_train_epochs 3 \
>     --per_device_train_batch_size 4 \
>     --per_device_eval_batch_size 4 \
>     --evaluation_strategy "no" \
>     --save_strategy "steps" \
>     --save_steps 2000 \
>     --save_total_limit 1 \
>     --learning_rate 2e-5 \
>     --weight_decay 0. \
>     --warmup_ratio 0.03 \
>     --lr_scheduler_type "cosine" \
>     --logging_steps 1 \
>     --tf32 True \
>     --deepspeed ZeRO3.json
> #--gradient_accumulation_steps 8 \
> #    --fsdp "full_shard auto_wrap" \
>     # --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
> ```

Small note here though that this repo doesn't really deal with Llama or alpaca - should we maybe post this somewhere else instead?

**Comment by Trangle** [comment]
您好，邮件已收到。

**Comment by insist93** [comment]
meet the same issue.
anyone can fixed?

**Comment by SefaZeng** [comment]
Any updates?
