### ISSUE TITLE
Create a img2img (+ inpainting) controlnet pipeline

### ISSUE THREAD

**Issue by tiimgreen** [huggingface/diffusers#2783]
**Is your feature request related to a problem? Please describe.**
In auto1111 I can use img2img with inpainting in combination with controlnet canny edge detection to generate a new image.

With current tools in diffusers it appears I can't do that. I can only do text2img with controlnet

**Describe the solution you'd like**
A new pipeline `StableDiffusionImg2ImgControlNetPipeline` or something similar which will allow img2img with inpainting and controlnet

**Describe alternatives you've considered**
Tried with auto1111 and works perfectly but can't use diffusers library for it

**Comment by yiyixuxu** [comment]
Hi @tiimgreen 

we have a community pipeline here 
https://github.com/huggingface/diffusers/pull/2561

YiYi

**Comment by patrickvonplaten** [comment]
Think we should move them to source cc @yiyixuxu @williamberman

**Comment by kadirnar** [comment]
@patrickvonplaten ,

Can we do Inpaint using Image2Image(openjourney, anythingv4...) models?

**Comment by patrickvonplaten** [comment]
One can do controlnet img2img & inpaint with the pipelines here: https://github.com/huggingface/diffusers/pull/3533
