### ISSUE TITLE
Clarity embedding work 

### ISSUE THREAD

**Issue by NicholasKao1029** [huggingface/diffusers#2798]
Looking at this colab for loading embedding it uses the `.bin` 
https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_conceptualizer_inference.ipynb#scrollTo=bJx50Ta37392

There is a conversion script for sd -> diffusers

I was wondering does this also apply to `.pt` files for embeddings and if so, can the instructions be made clear

**Comment by sayakpaul** [comment]
Ccing @apolinario

**Comment by NicholasKao1029** [comment]
Hello is there an update to this

**Comment by patrickvonplaten** [comment]
I think this should be solved by: https://github.com/huggingface/diffusers/pull/2009 will try to get this PR merged asap

**Comment by NicholasKao1029** [comment]
y'all killing it
