### ISSUE TITLE
"DPMSolverMultistepScheduler "Is not" dpm++ 2M K ", "DPMSolverMultistepScheduler" = "dpm++ 2 m" Karras doesn't seem to be effective

### ISSUE THREAD

**Issue by XXXKAY** [huggingface/diffusers#2801]
Dear developers, first of all thank you for your pay, after I a lot of testing I found "DPMSolverMultistepScheduler
"Is not" dpm++ 2M K ",
"DPMSolverMultistepScheduler" = "dpm++ 2 m" Karras doesn't seem to be effective, it is very influence some model generated effect, can tell me the way to solve this problem?
This problem is greatly magnified on the orange model

**Comment by sayakpaul** [comment]
Hi!

Could you provide some results along with code snippets to demonstrate the problem in more details?

**Comment by XXXKAY** [comment]
Here are some comparison charts

**Comment by XXXKAY** [comment]
Here are some comparison charts(by AbyssOrangeMix3 model)：
![k15](https://user-images.githubusercontent.com/119796959/227448648-7d6bb68d-f3c5-4067-9650-b696d8cc59da.png)
webui,"dpm++ 2m k","15step" 

![15](https://user-images.githubusercontent.com/119796959/227448847-b4b6e8a1-cf55-486d-bc25-ee07f03f1299.png)
webui,"dpm++ 2m", "15step"

![DPMSolverMultistepScheduler15](https://user-images.githubusercontent.com/119796959/227449071-6b25864b-930e-4cd4-8a48-0cd54b42e90e.jpg)
diffusers "DPMSolverMultistepScheduler","15step"

![DPMSolverMultistepScheduler20](https://user-images.githubusercontent.com/119796959/227449200-19f7402c-c4fe-4f60-aa5e-60c61ed1d097.jpg)
diffusers "DPMSolverMultistepScheduler","20step"

![k20](https://user-images.githubusercontent.com/119796959/227449382-c343d2ac-209e-4e6b-b679-d46c7b71f810.png)
webui,"dpm++ 2m k","20step" 

![20](https://user-images.githubusercontent.com/119796959/227449484-14689d35-fbb7-4685-8448-726648aaa277.png)
webui,"dpm++ 2m ","20step"

**Comment by XXXKAY** [comment]
> Here are some comparison charts(by AbyssOrangeMix3 model)： ![k15](https://user-images.githubusercontent.com/119796959/227448648-7d6bb68d-f3c5-4067-9650-b696d8cc59da.png) webui,"dpm++ 2m k","15step"
> 
> ![15](https://user-images.githubusercontent.com/119796959/227448847-b4b6e8a1-cf55-486d-bc25-ee07f03f1299.png) webui,"dpm++ 2m", "15step"
> 
> ![DPMSolverMultistepScheduler15](https://user-images.githubusercontent.com/119796959/227449071-6b25864b-930e-4cd4-8a48-0cd54b42e90e.jpg) diffusers "DPMSolverMultistepScheduler","15step"
> 
> ![DPMSolverMultistepScheduler20](https://user-images.githubusercontent.com/119796959/227449200-19f7402c-c4fe-4f60-aa5e-60c61ed1d097.jpg) diffusers "DPMSolverMultistepScheduler","20step"
> 
> ![k20](https://user-images.githubusercontent.com/119796959/227449382-c343d2ac-209e-4e6b-b679-d46c7b71f810.png) webui,"dpm++ 2m k","20step"
> 
> ![20](https://user-images.githubusercontent.com/119796959/227449484-14689d35-fbb7-4685-8448-726648aaa277.png) webui,"dpm++ 2m ","20step"

@sayakpaul

**Comment by sayakpaul** [comment]
@XXXKAY this is NFSW content, so I am deleting the comments for the benefit of the community. Could you please use another checkpoint with the `safety_checker` turned on?

**Comment by XXXKAY** [comment]
Sorry I went back to the example,

This is generated using the webUI:
![15K](https://user-images.githubusercontent.com/119796959/227457658-be5fb10a-0787-4a88-807a-4fc951289c8a.png)
dpm++ 2m k.      15setp



![15](https://user-images.githubusercontent.com/119796959/227457792-728a8a8d-2c75-4d33-86b9-3fe16ae049fe.png)
dpm++ 2m .      15setp



This is generated using the diffusers:

![DPMSolverMultistepScheduler15](https://user-images.githubusercontent.com/119796959/227457915-d9057e09-e9df-4840-9696-f6a46fba3a47.jpg)
DPMSolverMultistepScheduler.      15setp

![DPMSolverMultistepScheduler20](https://user-images.githubusercontent.com/119796959/227458020-2532b7a9-47fb-49b8-b092-338765045529.jpg)
DPMSolverMultistepScheduler.      20setp


The model I use is: AbyssOrangeMix3 (AOM3)

**Comment by XXXKAY** [comment]
> Sorry I went back to the example,
> 
> This is generated using the webUI: ![15K](https://user-images.githubusercontent.com/119796959/227457658-be5fb10a-0787-4a88-807a-4fc951289c8a.png) dpm++ 2m k. 15setp
> 
> ![15](https://user-images.githubusercontent.com/119796959/227457792-728a8a8d-2c75-4d33-86b9-3fe16ae049fe.png) dpm++ 2m . 15setp
> 
> This is generated using the diffusers:
> 
> ![DPMSolverMultistepScheduler15](https://user-images.githubusercontent.com/119796959/227457915-d9057e09-e9df-4840-9696-f6a46fba3a47.jpg) DPMSolverMultistepScheduler. 15setp
> 
> ![DPMSolverMultistepScheduler20](https://user-images.githubusercontent.com/119796959/227458020-2532b7a9-47fb-49b8-b092-338765045529.jpg) DPMSolverMultistepScheduler. 20setp
> 
> The model I use is: AbyssOrangeMix3 (AOM3)

@sayakpaul

**Comment by sayakpaul** [comment]
Could you ensure this behavior repeats for a couple of different seeds?

**Comment by XXXKAY** [comment]
> Could you ensure this behavior repeats for a couple of different seeds?
I can ensure that the results obtained with different seed is such a bad result, I think "DPMSolverMultistepScheduler" missing "Karras", this problem will be very serious on some model，such like: "AbyssOrangeMix3","ChilloutMix"

**Comment by sayakpaul** [comment]
So, this seems to be a problem only for particular types of models if I understand correctly. 

> I think "DPMSolverMultistepScheduler" missing "Karras"

Could you elaborate what do you mean by this?

**Comment by XXXKAY** [comment]
> So, this seems to be a problem only for particular types of models if I understand correctly.
> 
> > I think "DPMSolverMultistepScheduler" missing "Karras"
> 
> Could you elaborate what do you mean by this?

As I said the title of （" DPMSolverMultistepScheduler" Is not "dpm++ 2 m K", "DPMSolverMultistepScheduler" = "dpm++ 2 m"）
