### ISSUE TITLE
How to prune diffusers model?

### ISSUE THREAD

**Issue by adhikjoshi** [huggingface/diffusers#2802]
Pruning .ckpt is available, but is there script to prune diffusers?

**Comment by sayakpaul** [comment]
Hi,

Could you elaborate a bit more on what exactly you are looking for? 

You can load the individual sub-networks of a `diffusers` pipeline like so:

```py
from diffusers import UNet2DConditionModel

model_id = "runwayml/stable-diffusion-v1-5"
unet = UNet2DConditionModel.from_pretrained(model_id, subfolder="unet")
```

And then maybe you could do the pruning? Would this work?

**Comment by adhikjoshi** [comment]
There are script to prune .ckpt models, like below

https://github.com/prettydeep/Dreambooth-SD-ckpt-pruning

This is used to prune 8GB of .ckpt into 3GB models and faster inference.

I was wondering if we can do it with diffusers models?

I am doing 

convert diffusers -> .ckpt -> prune it -> convert pruned .ckpt into diffusers

**Comment by sayakpaul** [comment]
@echarlaix
