### ISSUE TITLE
printing pipeline doesn't take customized ones into account

### ISSUE THREAD

**Issue by moono** [huggingface/diffusers#2806]
### Describe the bug

I want to print current pipeline status as stated here [Diffusers doc](https://huggingface.co/docs/diffusers/using-diffusers/loading) `How does loading work?` section using `print(pipe)`.

It prints ok when default config is used, but if I change (customize) pipeline, it still prints same(default) configuration.

Is it intentional? or bug?

### Reproduction

```python
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler

# default settings
print("default setting")
repo_id = "CompVis/stable-diffusion-v1-4"
pipe = StableDiffusionPipeline.from_pretrained(repo_id)
print(pipe)

# let's change scheduler
print()
print("custom setting")
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
print(pipe)
```

### Logs

```shell
default setting
StableDiffusionPipeline {
  "_class_name": "StableDiffusionPipeline",
  "_diffusers_version": "0.14.0",
  "feature_extractor": [
    "transformers",
    "CLIPFeatureExtractor"
  ],
  "requires_safety_checker": true,
  "safety_checker": [
    "stable_diffusion",
    "StableDiffusionSafetyChecker"
  ],
  "scheduler": [
    "diffusers",
    "PNDMScheduler"
  ],
  "text_encoder": [
    "transformers",
    "CLIPTextModel"
  ],
  "tokenizer": [
    "transformers",
    "CLIPTokenizer"
  ],
  "unet": [
    "diffusers",
    "UNet2DConditionModel"
  ],
  "vae": [
    "diffusers",
    "AutoencoderKL"
  ]
}


custom setting
StableDiffusionPipeline {
  "_class_name": "StableDiffusionPipeline",
  "_diffusers_version": "0.14.0",
  "feature_extractor": [
    "transformers",
    "CLIPFeatureExtractor"
  ],
  "requires_safety_checker": true,
  "safety_checker": [
    "stable_diffusion",
    "StableDiffusionSafetyChecker"
  ],
  "scheduler": [
    "diffusers",
    "PNDMScheduler"
  ],
  "text_encoder": [
    "transformers",
    "CLIPTextModel"
  ],
  "tokenizer": [
    "transformers",
    "CLIPTokenizer"
  ],
  "unet": [
    "diffusers",
    "UNet2DConditionModel"
  ],
  "vae": [
    "diffusers",
    "AutoencoderKL"
  ]
}
```

### System Info

- `diffusers` version: 0.14.0
- Platform: Linux-5.4.0-144-generic-x86_64-with-glibc2.27
- Python version: 3.9.16
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.13.2
- Transformers version: 4.26.1
- Accelerate version: 0.18.0.dev0
- xFormers version: 0.0.16
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
Hey @moono,

Great catch! This looks like a bug indeed. PR on its way: https://github.com/huggingface/diffusers/pull/2849

Seems like a couple more things need to be fixed actually, good that we spotted this here :-)

**Comment by moono** [comment]
Thank you @patrickvonplaten for taking time to look into this. 
I'll close this issue since you've submitted the related PR.
