### ISSUE TITLE
Optimize model loading by natively using Accelerate, please.

### ISSUE THREAD

**Issue by piEsposito** [huggingface/diffusers#281]
**Is your feature request related to a problem? Please describe.**
Loading pretrained models, for example `UNet2DConditionModel` peaks at 8GB when loading a pretrained one, while it takes a lot less memory when it is fully loaded to the GPU. That is happens likely because there are some redundancies between loaded weights and the model.

When we start it with empty weights and load them using accelerate, it peaks on 4.91GB, which lets us deploy Diffusers in servers that have a lot less RAM and thus are cheaper.

**Describe the solution you'd like**
It would be great if Diffusers natively supported loading models from pretrained using `accelerate.init_empty_weights` and `accelerate.accelerate.load_checkpoint_and_dispatch`, so it has lower memory footprint.

**Describe alternatives you've considered**
- Loading the models with accelerate myself, but that requires model surgery and a lot of coding, which makes me prone to mistakes
- Do what accelerate does by hand

**Additional context**
Using accelerate to natively load models would also reduce the RAM memory footprint when loading pipelines composed of more than one model, by already allocating them on the proper device and thus enabling us to deploy diffusers on cheaper servers.

**Comment by anton-l** [comment]
Hey @piEsposito, happy to look into that in the coming week! If you have a code snippet that works for you, feel free to include it here as a reference :hugs: 

@muellerzr @patrickvonplaten wdyt? We can either do this, or bring the low-RAM loading code from transformers

**Comment by muellerzr** [comment]
cc @sgugger so it's on your radar since next week I'll be out for a bit :)

**Comment by patrickvonplaten** [comment]
Happy to include `accelerate`! Maybe we can follow the same logic we have in `transformers` with `device_map="auto"` :-) And definitely +1 to make use of torch's meta device to half the peak required memory usage!

**Comment by piEsposito** [comment]
Now this is great news, you just made my life a lot easier. Anyway I can help?

**Comment by patrickvonplaten** [comment]
@piEsposito - if you want you could give it a try to add `accelerate` and `torch`'s `meta` device logic to: https://github.com/huggingface/diffusers/blob/9b704f768880c732503fe46800986c6998ca205d/src/diffusers/modeling_utils.py#L203 more or less in the same spirit as it's done in `transformers`: https://github.com/huggingface/transformers/blob/65fb71bc762c46bb067306c1fd083b1cba87a095/src/transformers/modeling_utils.py#L1610

Happy to guide you through a PR!

**Comment by patrickvonplaten** [comment]
Thanks a lot for opening the PR! Think @patil-suraj wanted to guide you here a bit :-)

**Comment by piEsposito** [comment]
@patrickvonplaten it is just a draft to see if the direction is right. It will of course be improved to production level code with guidance from you folks. Thanks :D

**Comment by patil-suraj** [comment]
Hey @piEsposito ! Looking through the PR and will get back to you soon about this.

**Comment by piEsposito** [comment]
@patil-suraj I saw that when we pass the `low_cpu_mem_usage` and `device_map` to the Pipeline abstraction, it will break on stable diffusion when loading the Safety Checker. Should we add an exception for that and let safety checker be loaded in full?

**Comment by patrickvonplaten** [comment]
Hey @piEsposito,

Do we need both arguments here? Could we maybe just add `device_map` for now ?

**Comment by piEsposito** [comment]
@patrickvonplaten `device_map` would automatically imply that `low_cpu_mem_usage` is `True`, and `low_cpu_mem_usage` needs a device map, we can stick to `device_map` only. 

I can update the PR branch asap if you think that makes sense.

**Comment by patrickvonplaten** [comment]
@patil-suraj btw if you're very busy - happy to take this one!

**Comment by piEsposito** [comment]
@patrickvonplaten just did it. If the direction I'm going is right I can make the Pipeline abstractions pass it too and then create the proper tests and work on code quality.

**Comment by patrickvonplaten** [comment]
Perfect - reviewing today!
