### ISSUE TITLE
Deepspeed or FSDP cannot be used for fine-tuning two models together such as text encoder and unet

### ISSUE THREAD

**Issue by liuyugeng** [huggingface/diffusers#2816]
Can you add some features when finetuning the whole diffusion model, not only unet?
I read the Dreambooth code and copy the some code such as ```train_text_encoder``` to ```diffusers/examples/text_to_image/train_text_to_image.py```, but it still doesn't work for Deepspeed or FSDP.
I am trying to fine-tune the text encoder and unet, but deepspeed didn't support it since the code is
``` 
for obj in result:
            if isinstance(obj, torch.nn.Module):
                model = obj
            elif isinstance(obj, (torch.optim.Optimizer, DummyOptim)):
                optimizer = obj
            elif (isinstance(obj, (LRScheduler, DummyScheduler))) or (
                type(obj).__name__ in deepspeed.runtime.lr_schedules.VALID_LR_SCHEDULES
            ):
                scheduler = obj
```
If I have two models, the for loop will ignore the first one.
Also, FSDP didn't support it, even though it can be used for two models, but the two models have different config files.
Thus, could you add some script about how to fine-tune the two models together?

**Comment by sayakpaul** [comment]
@williamberman

**Comment by patrickvonplaten** [comment]
We haven't looked too much into Deepspeed or FSDP yet to be honest
