### ISSUE TITLE
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /huggingface/diffusers/main/examples/community/lpw_stable_diffusion.py

### ISSUE THREAD

**Issue by Pirog17000** [huggingface/diffusers#2819]
### Describe the bug

![image](https://user-images.githubusercontent.com/3022852/227634681-1f522131-f921-4fb5-a2b4-781f8dd0a43b.png)

SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max
retries exceeded with url:
/huggingface/diffusers/main/examples/community/lpw_stable_diffusion.py (Caused
by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: certificate has expired (_ssl.c:997)')))

### Reproduction

Try to run with lpw pipeline
(how do we make it run locally, and why it keeps checking it online without any updates from the administrator?)

### Logs

```shell
SSLError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max
retries exceeded with url:
/huggingface/diffusers/main/examples/community/lpw_stable_diffusion.py (Caused
by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: certificate has expired (_ssl.c:997)')))
```

### System Info

- `diffusers` version: 0.15.0.dev0
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.9
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.13.2
- Transformers version: 4.27.0.dev0
- Accelerate version: 0.17.0.dev0
- xFormers version: 0.0.17+57edbb7.d20230228

**Comment by erikbern** [comment]
This was due to Github's certificate expiring but appears to have been fixed now

https://news.ycombinator.com/item?id=35295216

**Comment by patrickvonplaten** [comment]
Thanks for helping out here @erikbern ! @Pirog17000 can you confirm?

**Comment by patrickvonplaten** [comment]
You can just pass the file path to `custom_pipeline=...` see [here](https://huggingface.co/docs/diffusers/api/diffusion_pipeline#diffusers.DiffusionPipeline.from_pretrained.custom_pipeline)
