### ISSUE TITLE
inpainting doesn't work with CPU

### ISSUE THREAD

**Issue by krrishdholakia** [huggingface/diffusers#282]
### Describe the bug

<img width="895" alt="Screen Shot 2022-08-30 at 3 59 50 PM" src="https://user-images.githubusercontent.com/17561003/187558163-fe0198c5-a09f-44b2-ba5c-182d5c66131e.png">
Using the inpainting example but trying to run it on the cpu instead of gpu (since i'm trying to push to hf space). 

Hitting this runtime error: 
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.HalfTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

### Reproduction

Try and run pipeline in cpu

### System Info

```shell
using google colab
```

**Comment by krrishdholakia** [comment]
cc: @patil-suraj

**Comment by krrishdholakia** [comment]
https://colab.research.google.com/github/patil-suraj/Notebooks/blob/master/in_painting_with_stable_diffusion_using_diffusers.ipynb

**Comment by krrishdholakia** [comment]
tried using the updated pipeline - `StableDiffusionInpaintPipeline`
<img width="1539" alt="Screen Shot 2022-08-30 at 5 59 48 PM" src="https://user-images.githubusercontent.com/17561003/187569943-5fe40268-e325-451f-bb11-241efefbaa85.png">


but it doesn't seem to have been uploaded yet

**Comment by patrickvonplaten** [comment]
@krrishdholakia does it still not work on CPU? cc'ing our in-painting authors here: @patil-suraj and @anton-l

**Comment by patrickvonplaten** [comment]
@patil-suraj could you take a look here?

**Comment by patil-suraj** [comment]
Hey @krrishdholakia , sorry to come to this only now. The pipeline should work on CPU, I suspect that you are setting the `torch_dtype=torch.float16` , which won't  on CPU as it does as fp16 is not supported on CPU, please pass `torch_dtype=torch.float32` to make sure it works on CPU.
