### ISSUE TITLE
Any chance someone is working on multi controlnet for img2img

### ISSUE THREAD

**Issue by romanfurman6** [huggingface/diffusers#2820]
Any chance someone is working on StableDiffusionControlNetImg2ImgPipeline to support multiple controlnet?

**Comment by mikegarts** [comment]
Hi @romanfurman6, I might give it a try next week but can't promise anything :)

**Comment by romanfurman6** [comment]
haha thank you @mikegarts 🙌🏻  I saw @takuma104 was working on something similar https://github.com/huggingface/diffusers/pull/2627

**Comment by mikegarts** [comment]
@romanfurman6, indeed @takuma104 added the support to provide multiple controlnet conditions at StableDiffusionControlNetPipeline.

Some time ago I added the StableDiffusionControlNetImg2ImgPipeline community pipeline (img2img+controlnet, based on what takuma did), but it supports only single controlnet conditioning.
I think it wouldn't be too hard to add support for img2img+multiple controlnets (worst thing in a separate pipeline if the change is breaking).

**Comment by mikegarts** [comment]
Hi @romanfurman6 - this one seems to do the trick :)
https://github.com/huggingface/diffusers/pull/2833

**Comment by romanfurman6** [comment]
Perfect, thank you @mikegarts 🙌🏻
