### ISSUE TITLE
Dreambooth won't start: [00:51:51] WARNING  The following values were not passed to        

### ISSUE THREAD

**Issue by Leomn1234** [huggingface/diffusers#2821]
### Describe the bug

Getting this whenever I run train_dreambooth.py on Colab but it won't get passed it, it seems to freeze up and just run and not do anything with this warning and the cursor keeps blinking, until you stop the cell, then it just stops immediately when you try to run it after that. It has always worked before, and no changes on my end. Think it might be an issue with accelerate. Have no other info.

### Reproduction

[00:51:51] WARNING  The following values were not passed to        

### Logs

```shell
[00:51:51] WARNING  The following values were not passed to
```

### System Info

colab notebook

**Comment by Glatzenhopper** [comment]
i have the same problem :(

**Comment by ThunderMonique** [comment]
Same since yesterday:.(

**Comment by CyberPhonkMusic** [comment]
the same problem here, until yesterday I was getting

**Comment by lepascal** [comment]
Me too …

**Comment by jmaccall316** [comment]
Please if anyone knows how to fix it even manually. Tried to install a few different versions of things but very hard to diagnose when there is no display.

**Comment by CyberPhonkMusic** [comment]
I waited for him to do the process even with this message, and it worked,

**Comment by semosem** [comment]
I closed the warning and it continued..

**Comment by Usaka** [comment]
@CyberPhonkMusic i waited to finish process but don't does nothing, the output console is empty, i run the script on Colab

i was follow tutorial publish 3 may and i search all libs worn to that date, but i received same error

**Comment by jmaccall316** [comment]
Yeah, I don't know. Is it just the display or something on Google's end? Hopefully it gets resolved.

**Comment by jmaccall316** [comment]
Issue has been proven tied to accelerate launch.

Credit [hntrssthmpsn](https://github.com/hntrssthmpsn) for a quick solution: https://github.com/ShivamShrirao/diffusers/issues/222#issuecomment-1483978585

!accelerate launch train_dreambooth.py

to:

!/usr/bin/python3 train_dreambooth.py

**Comment by Usaka** [comment]
@jmaccall316  excelent, thks so much, use !/usr/bin/python3 train_dreambooth.py work to me

**Comment by patrickvonplaten** [comment]
This seems to be a problem with `accelerate` then ?

**Comment by iamyukihiro** [comment]
Me too

**Comment by patrickvonplaten** [comment]
Hmm I'm not able to reproduce this issue: https://colab.research.google.com/drive/1TbCPyRMqKa6wht1tDt_9v-aUbKTQt_44?usp=sharing

Can someone upload a reproducible colab?

**Comment by muellerzr** [comment]
Hi all, any chance you could tell us: is this on a single GPU or TPU in Colab when we are trying to run it?

**Comment by jmaccall316** [comment]
> Hmm I'm not able to reproduce this issue: https://colab.research.google.com/drive/1TbCPyRMqKa6wht1tDt_9v-aUbKTQt_44?usp=sharing
> 
> Can someone upload a reproducible colab?

Issue was first encountered on the ShivamShrirao [colab](https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb#scrollTo=jjcSXTp-u-Eg&line=1&uniqifier=1) using his diffusers fork.

He's had to temporarily change !accelerate launch to !python3. Some things tried: installing HF diffusers directly instead of his fork, using HF repo train_dreambooth.py instead of his, but still no success. The bug is what you see in the image, no display and very finicky. The warning is all that comes, nothing ever follows. !python3 does work.
![accelerate](https://user-images.githubusercontent.com/120006038/228337543-a37a5474-e064-471f-9045-54b621d4b4f0.png)

**Comment by jmaccall316** [comment]
Okay, I think I figured it out. The fork colab seems to run when you add a cell with: 

```
from accelerate.utils import write_basic_config

write_basic_config()
```

I assume this is either a new import or something that has become more important than it used to be. Always worked without until recently.

**Comment by muellerzr** [comment]
Awesome. For now let's use that as the solution and then next week I'll try to figure out what the regression was. @jmaccall316 is this using the CPU, GPU, or TPU in colab?

**Comment by jmaccall316** [comment]
I use Premium GPU on colab for training.

**Comment by GeneralAwareness** [comment]
> Okay, I think I figured it out. The fork colab seems to run !accelerate launch when you add a cell with:
> 
> ```
> from accelerate.utils import write_basic_config
> 
> write_basic_config()
> ```
> 
> I assume this is either a new import or something that has become required. Always worked without until recently.

When you say cell are you talking about a cell in the notebook?  My accelerate launch is in a python script not in a notebook and it is doing the exact same thing until I added this.  How very strange.  Now I have another program that did not do this but it used .toml files instead so I suspect it has to do with a VERY long command line.

**Comment by GeneralAwareness** [comment]
Woke up this morning and even with the change I did, trained as well, it no longer works. WARNING  The following values were not passed to ...

**Comment by mauricio-repetto** [comment]
Hi I'm having the same issue using the official scripts from HF

> ```
> from accelerate.utils import write_basic_config
> 
> write_basic_config()
> ```

After executing the above and then the accelerate command made possible to get outpus from the colab cell.

**Comment by GeneralAwareness** [comment]
> Was there any fix for this found?

Yes, there is and it involves no longer sending the commands on the command line and instead using a config file (in its format it knows how to read) instead.
