### ISSUE TITLE
Can i make image&text to video with modelscope video model?

### ISSUE THREAD

**Issue by tonymacx86PRO** [huggingface/diffusers#2830]
### Open source status

- [ ] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by tonymacx86PRO** [comment]
I making a modelscope video cli wrapper and i need more pipelines to have different modes of operating with it for example: text to video(the existing one), video to video, image to video... (Not implemented ones), can anyone pls implement this pipelines? It will be useful, thanks everyone if added the pipelines

**Comment by sayakpaul** [comment]
Those are incoming. Currently, we support https://huggingface.co/docs/diffusers/main/en/api/pipelines/text_to_video.

Tune a Video (https://github.com/huggingface/diffusers/pull/2455) is also incoming. Feel free to open issues separately for requesting new pipelines (single issue for a single pipeline, ideally) as it's easier to keep track of them that way.

I am closing this issues for now.
