### ISSUE TITLE
can you support controlnet_pipeline don't use control   , and it looks like sample stable diffusion ? 

### ISSUE THREAD

**Issue by kelisiya** [huggingface/diffusers#2838]
**Is your feature request related to a problem? Please describe.**
I want to try a better way to assemble controlnet, when I try not to add control in the contronet pipeline, I will encounter an error
**Describe the solution you'd like**
I want the contronetpipeline to degenerate into a normal sd when the control is not loaded

**Describe alternatives you've considered**

**Additional context**

**Comment by sayakpaul** [comment]
You could just use `StableDiffusionPipeline` in that case, no?

```from diffusers import StableDiffusionPipeline
import torch 

model_id = "runwayml/stable-diffusion-v1-5"
prompt = "a photo of an astronaut riding a horse on mars"

pipeline = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipeline = pipeline.to("cuda")
image = pipeline(prompt).images[0]
```

Or am I missing out on something?
