### ISSUE TITLE
Can we modify the network architecture?

### ISSUE THREAD

**Issue by xingzhehe** [huggingface/diffusers#2848]
The inner code base seems to be quite complicated. I was wondering is there any easy way to modify part of the network architecture? For example, like in the Paint By Example, https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/paint_by_example/pipeline_paint_by_example.py, they add more channels in the first layer of unet while keeping all other weights same as Stable Diffusion. 

For example, if I would like to train Paint By Example on my own dataset, but I don't know how to initialize the model like that in the paper. It is just an example, and what I am planning is slightly different. I could understand if you want to keep this library for inference only. I am just asking if there exists or it is planed? Otherwise, would you suggest to use their own repo (and others like that) to do the training I am talking about?

**Comment by patrickvonplaten** [comment]
Sorry I don't fully understand, you can modify pretty much everything of the unet, see all the init args of:
- https://github.com/huggingface/diffusers/blob/920a15cf70c9c540bdc56fcfd52f7e8f2c02e33a/src/diffusers/models/unet_2d_condition.py#L117
- https://github.com/huggingface/diffusers/blob/920a15cf70c9c540bdc56fcfd52f7e8f2c02e33a/src/diffusers/models/unet_2d.py#L82

**Comment by xingzhehe** [comment]
Thanks for the reference. Actually I was thinking of creating different condition injection methods to modify the feature map. I just realized that I need to modify this file. Thanks!
