### ISSUE TITLE
Extremely slow loading of model

### ISSUE THREAD

**Issue by laxuscullen** [huggingface/diffusers#2852]
Hi guys. 

Cuda 12.0. 
Memory: 16GB, Tesla T4. nproc output: 4

I am using local files only = True, I am pointing the from_pretrained to the /cache_folder/snapshot/234xxx88378
First request to initialize the models takes 40s for stable diffusion 1.5 I have seen people get around 3s, how is that even achievable? 
I have tried using device_map = auto, it makes no difference. 

All requests after model is in memory is around 4s for 30 steps. Can this be improved as well?

```python
self.text2img_pipeline, self.cache_folder = DiffusionPipeline.from_pretrained(
          self.model, # this is the cache folder path
          torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
          cache_dir="models",
          local_files_only=True,
          # device_map="auto",
          return_cached_folder = True,
 )
self.text2img_pipeline.to(DEVICE)
self.text2img_pipeline.safety_checker = None
self.compatible_schedulers = {
          scheduler.__name__: scheduler for scheduler in self.text2img_pipeline.scheduler.compatibles
}
self.text2img_pipeline.enable_xformers_memory_efficient_attention()
```

I am sorry if I missed out on something, please let me know.

**Comment by patrickvonplaten** [comment]
Hey @laxuscullen,

Loading should indeed take only 3 seconds here. 

Do you have `accelerate` installed? Could you maybe copy-paste the output you get from `diffusers-cli env` i.e. the versions of:
- `torch`
- `safetensors`
- `accelerate`
- `transformers`
- `diffusers`

**Comment by laxuscullen** [comment]
I checked and accelerate is installed. 0.15.0

> diffusers-cli env

- `diffusers` version: 0.14.0
- Platform: Linux-5.15.0-1031-aws-x86_64-with-glibc2.31
- Python version: 3.9.5
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Accelerate version: 0.15.0
- xFormers version: 0.0.16rc425
- Using GPU in script?: Not sure?
- Using distributed or parallel set-up in script?: Not sure

Sorry I am not sure what the last two points mean? I am indeed using CUDA as the device if thats what the 2nd last is referring to.
Thank you so much for your reply! I really really appreciate the help

**Comment by laxuscullen** [comment]
@patrickvonplaten sorry about the ping but any help would be appreciated

**Comment by laxuscullen** [comment]
@patrickvonplaten sorry for the ping but could I possibly get some help regarding this? it is quite urgent that we fix this issue

**Comment by laxuscullen** [comment]
I noticed my hugging face hub version was old. I upgrade it to 0.13.3 and the issue still remains. I don't even know what's wrong. Its still taking ~40s to load each model. Local files is true and I am loading everything from the cache directory snapshots/commit/.

**Comment by laxuscullen** [comment]
@patrickvonplaten sorry for the ping but could I possibly get some help regarding this? it is quite urgent that we fix this issue

**Comment by patrickvonplaten** [comment]
Can you also update `accelerate` to the newest version?

Also can you maybe attach a google colab that shows that loading the model takes 40seconsd?

**Comment by laxuscullen** [comment]
> Can you also update `accelerate` to the newest version?
> 
> Also can you maybe attach a google colab that shows that loading the model takes 40seconsd?

Thank you for that suggestion!! Updating to the latest version definitely helped speed things up. I have updated both accelerate and transformers. The time for loading a model is now 8-9 seconds. Image loading time with 30 steps is 4 seconds. Still, this is nowhere close to 3s. I am using aws server with tesla t4.

**Comment by Bastaff** [comment]
If this is running on a server, are you by any chance swapping between different pipes because I'm running into the same issue which is not present when running inference on the same pipeline two times in a row.

**Comment by laxuscullen** [comment]
> If this is running on a server, are you by any chance swapping between different pipes because I'm running into the same issue which is not present when running inference on the same pipeline two times in a row.

This slow loading time is only during the setup. I make an object of the class which on call creates the model and then it stays in the memory. This happens for all the different models I have. After that it uses the pre loaded model. I do not think there is any swapping between different pipes?

**Comment by Bastaff** [comment]
> > If this is running on a server, are you by any chance swapping between different pipes because I'm running into the same issue which is not present when running inference on the same pipeline two times in a row.
> 
> This slow loading time is only during the setup. I make an object of the class which on call creates the model and then it stays in the memory. This happens for all the different models I have. After that it uses the pre loaded model. I do not think there is any swapping between different pipes?

Does the slow startup happen when doing inference 2-3 times in a row using the same pipe?

**Comment by laxuscullen** [comment]
> > > If this is running on a server, are you by any chance swapping between different pipes because I'm running into the same issue which is not present when running inference on the same pipeline two times in a row.
> > 
> > 
> > This slow loading time is only during the setup. I make an object of the class which on call creates the model and then it stays in the memory. This happens for all the different models I have. After that it uses the pre loaded model. I do not think there is any swapping between different pipes?
> 
> Does the slow startup happen when doing inference 2-3 times in a row using the same pipe?

After the initial load time of the models, it is 4s to generate an image. It does not take more than 4 after the initial load of the model in memory.

**Comment by laxuscullen** [comment]
> Can you also update `accelerate` to the newest version?
> 
> Also can you maybe attach a google colab that shows that loading the model takes 40seconsd?

Hello, unfortunately nothing has changed. It was 8s for sometime and now after a restart it is back to 40s. I don't know why. 

- `diffusers` version: 0.14.0
- Platform: Linux-5.15.0-1031-aws-x86_64-with-glibc2.31
- Python version: 3.9.5
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.13.3
- Transformers version: 4.25.1
- Accelerate version: 0.18.0
- xFormers version: 0.0.16rc425

```python
self.text2img_pipeline, self.cache_folder = DiffusionPipeline.from_pretrained(
          self.model, # this is the cache folder path
          torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
          cache_dir="models",
          local_files_only=True,
          return_cached_folder = True,
 )
self.text2img_pipeline.to(DEVICE)
self.text2img_pipeline.safety_checker = None
self.compatible_schedulers = {
          scheduler.__name__: scheduler for scheduler in self.text2img_pipeline.scheduler.compatibles
}
self.text2img_pipeline.enable_xformers_memory_efficient_attention()```

EulerAncestralDiscreteScheduler, guidance scale = 7

**Comment by laxuscullen** [comment]
Its faster when I use uvicorn but in prod when I am using gunicorn it increases the model loading time. Stable diffusion 1.5 and inkpunk models take 40s to load in both, openjourney v4 loads bit faster. If this is of any help. Again, this is very weird and is not accurate. Sometimes it will take 8s to load openjourney in either and sometimes not. I have no clue as to why.

**Comment by laxuscullen** [comment]
@patrickvonplaten any help is appreciated please I am losing my mind here with this

**Comment by pcuenca** [comment]
> Its faster when I use uvicorn but in prod when I am using gunicorn it increases the model loading time. 

This information is new to me. Could you please measure the time it takes for the model to load without any http or api server involved? 

One easy way would be to save the code snippet you posted before to a python file and then running "time script.py".

**Comment by laxuscullen** [comment]
> > Its faster when I use uvicorn but in prod when I am using gunicorn it increases the model loading time.
> 
> This information is new to me. Could you please measure the time it takes for the model to load without any http or api server involved?
> 
> One easy way would be to save the code snippet you posted before to a python file and then running "time script.py".
> 
> Update: I used this script:
> 
> ```python
> import time
> import torch
> from diffusers import DiffusionPipeline
> 
> begin = time.time()
> pipe, folder = DiffusionPipeline.from_pretrained(
>         "runwayml/stable-diffusion-v1-5",
>         cache_dir="models",
>         torch_dtype=torch.float16,
>         safety_checker=None,
>         local_files_only=True,
>         return_cached_folder=True,
> )
> print(f"Load             : {time.time()-begin}")
> pipe.to("cuda")
> print(f"Load+cuda        : {time.time()-begin}")
> pipe.enable_xformers_memory_efficient_attention()
> print(f"Load+cuda+xfomers: {time.time()-begin}")
> ```
> 
> And these are the timings I got:
> 
> ```shell
> Load             : 2.51175856590271
> Load+cuda        : 4.171940803527832
> Load+cuda+xfomers: 4.19656777381897
> ```

ncalls | tottime | percall | cumtime | percall | filename:lineno(function)
2122 | 34.056 | 0.016 | 34.084 | 0.016 | /home/api/venv/lib/python3.9/site-packages/torch/serialization.py:1076(load_tensor)
9162 | 4.047 | 0.000 | 4.074 | 0.000 | {method 'to' of 'torch._C._TensorBase' objects}
2 | 0.108 | 0.054 | 0.108 | 0.054 | {built-in method gc.collect}

Attaching the csv (as a zip) as well:
[log_response.zip](https://github.com/huggingface/diffusers/files/11176326/log_response.zip)

I will try to do your script in a while and let you know how it works without using a http server. In the meantime, hopefully the above stats help! I appreciate your time and support ^^

**Comment by laxuscullen** [comment]
> 

Hello. Here's the result. Turns out it has nothing to do with http server. I have also upgraded to diffusers 0.15.0 and no difference.

I ran the script multiple times one after the other. Note the difference in times. 

# stable-diffusion-v1-5
```
python3 test.py 
Load             : 37.65210032463074
Load+Scheduler             : 37.65352749824524
Load+cuda        : 39.83027672767639
Load+cuda+xfomers: 39.86527943611145
--
python3 test.py 
Load             : 29.48639154434204
Load+Scheduler             : 29.487765789031982
Load+cuda        : 31.56245470046997
Load+cuda+xfomers: 31.597569227218628
--
python3 test.py 
Load             : 14.872646808624268
Load+Scheduler             : 14.873899459838867
Load+cuda        : 16.910045385360718
Load+cuda+xfomers: 16.945375442504883
--
python3 test.py 
Load             : 4.720951557159424
Load+Scheduler             : 4.7223615646362305
Load+cuda        : 6.655545234680176
Load+cuda+xfomers: 6.690539360046387
--
python3 test.py 
Load             : 16.77522921562195
Load+Scheduler             : 16.777154445648193
Load+cuda        : 18.800325632095337
Load+cuda+xfomers: 18.835001945495605
```

# openjourney-v4
```
python3 test.py 
Load             : 41.533220291137695
Load+Scheduler             : 41.53461766242981
Load+cuda        : 45.762211084365845
Load+cuda+xfomers: 45.797624588012695
--
python3 test.py 
Load             : 40.2455267906189
Load+Scheduler             : 40.24745297431946
Load+cuda        : 42.353947162628174
Load+cuda+xfomers: 42.39437198638916
--
python3 test.py 
Load             : 11.931086301803589
Load+Scheduler             : 11.938352108001709
Load+cuda        : 14.180178880691528
Load+cuda+xfomers: 14.218569278717041
--
python3 test.py 
Load             : 14.353259086608887
Load+Scheduler             : 14.354692935943604
Load+cuda        : 16.43486976623535
Load+cuda+xfomers: 16.494126319885254
--
python3 test.py 
Load             : 6.459465980529785
Load+Scheduler             : 6.4656641483306885
Load+cuda        : 8.728263854980469
Load+cuda+xfomers: 8.765289783477783
--
python3 test.py 
Load             : 4.5192039012908936
Load+Scheduler             : 4.520668983459473
Load+cuda        : 6.41217041015625
Load+cuda+xfomers: 6.447228193283081
```

So what even is happening here?

Code used:
```python
from diffusers import (
    StableDiffusionPipeline, DPMSolverMultistepScheduler
)
import torch, time
begin = time.time()
pipe = StableDiffusionPipeline.from_pretrained(
    "models/models--runwayml--stable-diffusion-v1-5/snapshots/39593d5650112b4cc580433f6b0435385882d819",
    torch_dtype=torch.float16,
    cache_dir="models/",
    local_files_only=True,
)
print(f"Load             : {time.time()-begin}")
temp = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
print(f"Load+Scheduler             : {time.time()-begin}")
pipe.to("cuda")
print(f"Load+cuda        : {time.time()-begin}")
pipe.enable_xformers_memory_efficient_attention()
print(f"Load+cuda+xfomers: {time.time()-begin}")

```

**Comment by pcuenca** [comment]
Interesting, not sure what could be the reason for so much variation. It looks like most time is spent in PyTorch's `load_tensor`, could you please try to install `safetensors` to bypass that loading mechanism? You'll need to delete or put aside the cached `models` folder and download the weights once so the safetensors files are selected. Load times are about _halved_ for me when I use `safetensors`, curious to see if they are more stable in your case.

Also, for the sake of testing I'd maybe temporarily disable the safety checker to see if it has any impact on variability.

Finally, I understand you are running this on an AWS instance. What type of disk drive are you using to store the models?

**Comment by laxuscullen** [comment]
> 

Hello. Shifting to safetensors seriously affected the load time to:
For open journery v4:
17s, 16s (5sec for image generation)

For stable 1.5:
13s, 27s, 11s, 7s, (including 5sec)

Safety checker has been none since the start. Sorry for the late reply, could not get the time to work on the project.

Disk info:
nvme0n1     259:0    0   200G  0 disk 
└─nvme0n1p1 259:1    0   200G  0 part /
nvme1n1     259:2    0 116.4G  0 disk 

Running the script using safetensors:
```
python3 test.py 
Load             : 7.183128595352173
Load+Scheduler             : 7.1858251094818115
Load+cuda        : 10.776149272918701
Load+cuda+xfomers: 10.81068229675293

python3 test.py 
Load             : 3.832073926925659
Load+Scheduler             : 3.833575963973999
Load+cuda        : 6.012383699417114
Load+cuda+xfomers: 6.046616315841675

python3 test.py 
Load             : 2.091398239135742
Load+Scheduler             : 2.092985153198242
Load+cuda        : 4.10987401008606
Load+cuda+xfomers: 4.144474744796753

python3 test.py 
Load             : 2.0898549556732178
Load+Scheduler             : 2.0914087295532227
Load+cuda        : 4.375207185745239
Load+cuda+xfomers: 4.409597873687744
```

**Comment by JeffreyBWang** [comment]
Hey man, any update here? I'm facing the same problem :(

**Comment by laxuscullen** [comment]
@pcuenca

**Comment by laxuscullen** [comment]
> Hey man, any update here? I'm facing the same problem :(

You should mention the details he’s asked me so that it can help to notice the issue!

**Comment by aycaecemgul** [comment]
[laxuscullen](https://github.com/laxuscullen) did you fix this issue? I am having a similar problem where loading local model files takes around 2 mins.

**Comment by laxuscullen** [comment]
> [laxuscullen](https://github.com/laxuscullen) did you fix this issue? I am having a similar problem where loading local model files takes around 2 mins.
@aycaecemgul 
Nope. They don’t care to help. Even had tagged the guy back then and then just gave up.

**Comment by asomoza** [comment]
This is a very old issue, the versions of the issue were:

 ```
diffusers version: 0.14.0
Python version: 3.9.5
PyTorch version (GPU?): 1.13.1+cu117 (True)
Huggingface_hub version: 0.11.1
Transformers version: 4.25.1
Accelerate version: 0.15.0
```

If you're having the same problem with the up to date libraries I can help you, but you'll need to post a minimal reproducible code with the error.

**Comment by aycaecemgul** [comment]
Thank you [asomoza](https://github.com/asomoza), I have a quick question that might resolve my problem. Do you think using a hdd instead of ssd storage might affect the init time?

**Comment by asomoza** [comment]
yes by a lot, HDDs are really slow if you compare them to a mid range SSD. 

I have an HDD and if I load the models from it (SDXL), it takes a really long time. I also have a mid range SSD that has 550MB/s and even with it, you notice the difference. My main SSD is a Samsung 980 PRO with 7,000 MB/s and it loads the models in a couple of seconds.

**Comment by aycaecemgul** [comment]
thanks [asomoza](https://github.com/asomoza), this was my problem! converting to ssd fixed the issue.
