### ISSUE TITLE
Contributing Doc Missing PR Checklist

### ISSUE THREAD

**Issue by dg845** [huggingface/diffusers#2854]
In the [`CONTRIBUTING.md` doc](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md), in the ["How to open a PR" section](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md#how-to-open-a-pr), number 6, it says:

> Once you are satisfied (**and the checklist below is happy too**), go to the webpage of your fork on GitHub. Click on 'Pull request' to send your changes to the project maintainers for review.

However, there is no checklist below (I believe the checklist existed in earlier versions of the document). Is this an oversight?

**Comment by patrickvonplaten** [comment]
Great catch! Will adapt the contribution checklist. https://github.com/huggingface/diffusers/pull/2873
