### ISSUE TITLE
[ControlNet] Support multi-batch multi-controlnet

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#2855]
Currently, we don't support passing multiple batches for multiple ControlNets. Elaborate discussions on this are [here](https://github.com/huggingface/diffusers/issues/2704). 

We recently merged https://github.com/huggingface/diffusers/pull/2804 in order to make out users better aware of what is currently supported so that they are not confused about the error messages. 

@patrickvonplaten has proposed a short design of how multiple batches when using multiple ControlNets can be handled: https://github.com/huggingface/diffusers/pull/2804#issuecomment-1485582104.

This is issue is for keeping track of this feature and for discussing relevant design candidates to accommodate the change.

**Comment by CesarERamosMedina** [comment]
Hi hi! Was this ever resolved @sayakpaul ?
