### ISSUE TITLE
Any plan to support UniDiffuser?

### ISSUE THREAD

**Issue by nemonameless** [huggingface/diffusers#2857]
Any plan to support UniDiffuser?  https://github.com/thu-ml/unidiffuser
versatile diffusion(VD) maybe won't satisfy for multimodal

**Comment by patrickvonplaten** [comment]
Looks like a cool model, won't have much time to look into it I'm afraid but happy to guide someone if the community wants to pick it up

**Comment by dg845** [comment]
I would be interested in taking a stab at this :)

**Comment by nemonameless** [comment]
> I would be interested in taking a stab at this :)

looking forward to your work , it may take several days? a bit complicated

**Comment by dg845** [comment]
I've opened a very preliminary PR at #2963. I've also left a comment with some questions regarding the implementing the pipeline on the PR, let me know if that would be better moved somewhere else (such as this issue).

**Comment by sayakpaul** [comment]
UniDiffusers is in so, can be closed.
