### ISSUE TITLE
[LoRA] Better conversion of LoRA weights from `.bin` to `.safetensors`

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#2866]
Context: https://github.com/huggingface/diffusers/issues/2829#issuecomment-1485334706.

Currently, we have a [script](https://github.com/huggingface/diffusers/blob/1d7b4b60b7b7e19a0347da5a04ec76c045d8dbf0/scripts/convert_lora_safetensor_to_diffusers.py#L125) that allows us to convert LoRA weights from PyTorch to Safetensors but it outputs the whole pipeline instead of just the LoRA weights. 

Ideally, we should just output the LoRA weights in `safetensors`.  

Cc: @patrickvonplaten @Narsil

**Comment by pure-rgb** [comment]
What are the benefit over pytorch weight to safetensors? Why this attempt (motivation)?

**Comment by pure-rgb** [comment]
@patrickvonplaten Sorry for the confusion, my bad. I needed to see [this](https://github.com/huggingface/safetensors#yet-another-format-). Nevermind.

**Comment by patriciogonzalezvivo** [comment]
Hi! I tried this but the resulting `.safetensors` tile don't seems to work on Automatic1111. Any idea why? The meta data is nothing like the `.safetensors` generated by https://github.com/kohya-ss/ training script. Any pointer on what to do?
