### ISSUE TITLE
[Community effort] Type Hints

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#287]
**Is your feature request related to a problem? Please describe.**

Many important functions and classes are missing type hints

**Describe the solution you'd like**

It would be great if the following functions could have better type hints to understand what input is expected.

## Models

1. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/unet_2d.py#L14
2. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/unet_2d_condition.py#L14
3. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/vae.py#L394
4. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/vae.py#L443
5. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/vae.py#L432
6. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/vae.py#L438
7. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/vae.py#L328
8. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/vae.py#L370
9. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/vae.py#L375
10. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/vae.py#L385
11. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/models/vae.py#L296

## Schedulers

12. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_ddim.py#L53
13. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_ddim.py#L103
14. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_ddim.py#L179
15. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_ddpm.py#L52
16. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_ddpm.py#L90
17. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_ddpm.py#L182
18. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_karras_ve.py#L36
19. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_karras_ve.py#L71
20. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_karras_ve.py#L82
21. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_lms_discrete.py#L28
22. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_lms_discrete.py#L82
23. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_lms_discrete.py#L126
24. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_pndm.py#L52
25. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_pndm.py#L100
26. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_pndm.py#L263
27. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_sde_ve.py#L40
28. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_sde_ve.py#L62
29. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/schedulers/scheduling_sde_ve.py#L72

## Pipelines

30. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/ddim/pipeline_ddim.py#L31
31. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/ddpm/pipeline_ddpm.py#L31
32. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py#L19
33. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py#L10
34. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/latent_diffusion_uncond/pipeline_latent_diffusion_uncond.py#L16
35. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/pndm/pipeline_pndm.py#L31
36. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/pndm/pipeline_pndm.py#L25
37. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/score_sde_ve/pipeline_score_sde_ve.py#L10
38. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/score_sde_ve/pipeline_score_sde_ve.py#L15
39. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/stochatic_karras_ve/pipeline_stochastic_karras_ve.py#L24
40. - [x] https://github.com/huggingface/diffusers/blob/7e1b202d5ebf36475a8b7031ce3035af12883003/src/diffusers/pipelines/stochatic_karras_ve/pipeline_stochastic_karras_ve.py#L30

**Comment by patrickvonplaten** [comment]
Lots of beginner good first issues here for a first contribution. The way it works is easy! Pick some numbers by posting them here as a message here, open a PR to add type hints, ping @anton-l @patil-suraj @pcuenca or @patrickvonplaten on the PR to merge it and we'll tick your numbers of :-) 

Example:

I'm taking numbers **39.** and **40.** and will attach a PR below

**Comment by leszekhanusz** [comment]
Maybe that would also be a good idea to make a GitHub action to check that `mypy` is happy in all the PRs.

**Comment by patrickvonplaten** [comment]
Usually we're happy with just `black`, `isort` and `flake8` - are there any advantages of `mypy` over `flake8` ? `mypy` is a bit too restrictive to me personally

**Comment by patrickvonplaten** [comment]
What do you think here @anton-l @patil-suraj @pcuenca - note that we don't have it in Transformers and might require some more setting up . Not sure if it's worth it from my point of view, but happy to go for it if others think it's a good idea.

Also cc @LysandreJik @sgugger would love to hear your opinion on mypy: http://www.mypy-lang.org/

**Comment by sgugger** [comment]
I do have some opinions on mypy ;-) It usually ends up requiring the maintainer to write some horrible type hints that no one reading it will understand.

IMO you should focus on having type hints which make your code better documented and are readable and understandable, but enabling `mypy` is a step ahead as it will send errors if you use one function with a type that doesn't strictly match the type hint (and Python is dynamically typed so this tends to happen a lot for good reasons. For instance in Transformers, we had some issues `AutoModel`).

**Comment by santiviquez** [comment]
Hey, if there is no problem. I'm taking numbers **37.** and **38.** and will attach a PR below.

**Comment by daspartho** [comment]
I'll be taking numbers 35. and 36. and will attach a PR below.

**Comment by sidthekidder** [comment]
Hi! I'll take numbers 1 and 2, attaching a PR below.

**Comment by daspartho** [comment]
I'll work on numbers 24, 25, and 26. and will attach a PR below.

**Comment by santiviquez** [comment]
I'll take **12**, **13** and **14** and will attach a PR below

**Comment by daspartho** [comment]
I'll work on 3, 4, 7, 10, and 11 and will attach a PR below

**Comment by sidthekidder** [comment]
I'll pick up 30, 31 and 32, attaching a PR below

**Comment by shepherd1530** [comment]
Hello,

I will be taking 5, 6. Will attach a PR.

**Comment by daspartho** [comment]
I'll work on 15, 16, and 17 and will attach a PR below.

**Comment by santiviquez** [comment]
I'll take 21, 22 and 23 and will attach a PR below

**Comment by jcmc00** [comment]
I'll take 28, 29 and 30 and will attach a PR

**Comment by daspartho** [comment]
I'll take on 8 and will attach a PR

**Comment by patrickvonplaten** [comment]
Amazing work everyone here - we can close this issue :partying_face: Our IDEs should be happy now
