### ISSUE TITLE
Output type "latent" not correctly handled for the Stable Diffusion Inpainting pipeline

### ISSUE THREAD

**Issue by abdellah-lamrani-alaoui** [huggingface/diffusers#2871]
### Describe the bug

The behavior of the option `output_type = "latent"` is not the same for the inpainting and the txt2image pipeline.

**Inpainting pipeline:**

If `output_type = "latent"`, the value returned is the decoded image (**`latents`** should be returned in this case):
[link to file](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py)
```
# 11. Post-processing
image = self.decode_latents(latents)

# 12. Run safety checker
image, has_nsfw_concept = self.run_safety_checker(image, device, prompt_embeds.dtype)

# 13. Convert to PIL
if output_type == "pil":
    image = self.numpy_to_pil(image)

# Offload last model to CPU
if hasattr(self, "final_offload_hook") and self.final_offload_hook is not None:
    self.final_offload_hook.offload()

if not return_dict:
    return (image, has_nsfw_concept)

return StableDiffusionPipelineOutput(images=image, nsfw_content_detected=has_nsfw_concept)
```

**Text2Image pipeline:**

Here when `output_type == "latent"` is chosen, the `latents` value is returned:

[link to file](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py)
```
if output_type == "latent":
    image = latents
    has_nsfw_concept = None
elif output_type == "pil":
    # 8. Post-processing
    image = self.decode_latents(latents)

    # 9. Run safety checker
    image, has_nsfw_concept = self.run_safety_checker(image, device, prompt_embeds.dtype)

    # 10. Convert to PIL
    image = self.numpy_to_pil(image)
else:
    # 8. Post-processing
    image = self.decode_latents(latents)

    # 9. Run safety checker
    image, has_nsfw_concept = self.run_safety_checker(image, device, prompt_embeds.dtype)

```

=> I can try opening a PR for this :)

### Reproduction

Not relevant here

### System Info

Not relevant here

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu can you take a look here?

**Comment by pdoane** [comment]
I ran into this as well when reviewing the latent upscaler.  Some other notes:

- Documentation doesn't list 'latent' as a valid option for output_type
- StableDiffusionImg2ImgPipeline also does not handle the output_type correctly
- StableDiffusionLatentUpscalePipeline doesn't support prompt embeds so I suspect it does not interpret the prompt in the same way

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu here again :-)

**Comment by yiyixuxu** [comment]
Hi @abdellah-lamrani-alaoui 
currently, only text2img and img2img support latent output here, but we are working on a unified API `VAEImageProcessor` to handle all the preprocessing and postprocessing of image inputs/outputs 

img2img pipeline already implemented with this https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L733

and relevant PR here:
https://github.com/huggingface/diffusers/pull/2617 

@patrickvonplaten  sorry you have to pin me again😅, will try to get the PR out today!

**Comment by pdoane** [comment]
img2img behavior is broken, note the following sequence:

```
        if output_type == "latent":
            image = latents
            has_nsfw_concept = None

        image = self.decode_latents(latents)
```

Always decodes the latents for the returned image.

**Comment by yiyixuxu** [comment]
@pdoane ah you're right - will fix it. Thanks!

**Comment by patrickvonplaten** [comment]
@yiyixuxu let's maybe fix this in a quick short PR :-)
