### ISSUE TITLE
Image to Video Pipeline

### ISSUE THREAD

**Issue by tonymacx86PRO** [huggingface/diffusers#2883]
### Model/Pipeline/Scheduler description

How will this new pipeline work
You give a image and using the denoising strength adds noise to first frame and adding it to temporal memory
Output: Making from first image makes a sequence frame that represents a animation or video from the first frame
This very cool addition to text to video pipeline

If you have denoising strength of 0 u don't change the first frame and add it to temporal memory
if you have 1 it will completely change the first frame and add it to temporal memory

### Open source status

- [ ] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by a-r-r-o-w** [comment]
Marking as closed due to really old issue + plenty of image-to-video models supported now :)
