### ISSUE TITLE
How to implement `cross_attention_kwargs` in `StableDiffusionImg2ImgPipeline`?

### ISSUE THREAD

**Issue by youyuge34** [huggingface/diffusers#2884]
How to implement `cross_attention_kwargs`  in `StableDiffusionImg2ImgPipeline`?

I want to use lora weight with parameter `cross_attention_kwargs` in Img2img pipeline, but the `cross_attention_kwargs` has not implemented in `StableDiffusionImg2ImgPipeline`. Is there another way to get the same effect? 

The error message is :
```
stable_diffusion/pipeline_stable_diffusion_img2img.py 
line 642 got an unexpected keyword argument `cross_attention_kwargs`
```

**Comment by nipunjindal** [comment]
That sounds right, I can add that. Thanks for the bug.
