### ISSUE TITLE
Issues loading LoRA weights

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#2885]
Reported here by https://discuss.huggingface.co/u/dkackman: https://discuss.huggingface.co/t/does-load-attn-procs-work-with-safetensors/34827. See also proposed patch by user https://discuss.huggingface.co/u/slavakurilyak.

**Comment by patrickvonplaten** [comment]
cc @sayakpaul here

**Comment by sayakpaul** [comment]
@patrickvonplaten the solution proposed [here](https://discuss.huggingface.co/t/does-load-attn-procs-work-with-safetensors/34827/2?u=sayakpaul) checks if the LoRA concerned keys are present before the [state dict iteration](https://github.com/huggingface/diffusers/blob/0df4ad541f317a6c4d4f4dc6bd4a3e0324a5658d/src/diffusers/loaders.py#L223). Could you take a look at that and accordingly we could check with [slavakurilyak](https://discuss.huggingface.co/u/slavakurilyak) to see if they would be interested in a contribution.

**Comment by LIngerwsk** [comment]
Thank! Does the new_load_attn_procs work in the Diffusers with 0.14.0 version? 
Or the load_attn_procs works with safetensors now?
