### ISSUE TITLE
Tweaking and training a diffusers architecture from scratch

### ISSUE THREAD

**Issue by ysig** [huggingface/diffusers#2890]
Hi,

Training a diffusion model from scratch may be desirable especially if parts of the architecture are meant to be tweaked.
Although there is (training)[https://huggingface.co/docs/diffusers/training/text2image] it is not clear:

1.  How one can do multi-gpu/multi-node training
2. Whether and how you can modify parts of an existing architecture to something else, while still being part of the diffusers framework.

Is this currently supported?

Best,
ysig

PS: This expresses a general concern I always had with `huggingface's` design approach (for example even early on with distilGPT) where it seemed that the motive was to make people have an inference script to use out of the box (which was amazing!), but actually training and even tweaking the architecture became much-much more complicated.

**Comment by patrickvonplaten** [comment]
Hey @ysig:

1.) You can run all example scripts on multi-node by correctly configuring accelerate for multi-gpu. See https://github.com/huggingface/diffusers/tree/main/examples/text_to_image#running-locally-with-pytorch . When doing `accelerate config` you are asked about your set-up and then everything should work out of the box when launching with accelerate launch

2.) Sure you can modify all kinds of things of the unet, see config here: https://github.com/huggingface/diffusers/blob/e1144ac20c4c96f09f1c1e203715969bf80feb65/src/diffusers/models/unet_2d_condition.py#L117
