### ISSUE TITLE
UNet3DConditionModel not using Condition

### ISSUE THREAD

**Issue by Reichenbachian** [huggingface/diffusers#2895]
### Describe the bug

I could be entirely lost here, but it seems `UNet3DConditionModel` doesn't properly use `class_labels`. In fact, it doesn't use it at all. It seems odd to me that a "ConditionModel" doesn't use its condition.

### Reproduction

Doesn't need reproduction. The variable is unused in the source. 

### Logs

```shell
Not relevant
```

### System Info

Not relevant

**Comment by patrickvonplaten** [comment]
The condition refers more to the `encoder_hidden_states` here. We just added this class for: https://huggingface.co/damo-vilab/text-to-video-ms-1.7b and we don't need class_labels support yet
