### ISSUE TITLE
Is it possible to run text2video-zero with less than 15GB GPU?

### ISSUE THREAD

**Issue by camenduru** [huggingface/diffusers#2898]
### Describe the bug

Hi 👋 everybody, I have a question is it possible to use `xformers` with `text2video-zero`

when I add `self.pipe.enable_xformers_memory_efficient_attention()` I am getting a temporal consistency problem

| with xformers | without xformers (needs more than 20GB vram)
| --- | --- | 
![image_5](https://user-images.githubusercontent.com/54370274/228700990-f1c76506-027c-4ede-bdd1-685069724547.gif) | ![image (6)](https://user-images.githubusercontent.com/54370274/228700984-46ac3613-a53a-46d2-a3f1-122b5550fbee.gif)

code is here https://gitlab.com/camenduru/text2-video-zero/-/blob/dev/model.py

### Reproduction

🧬

### System Info

🥔

**Comment by patrickvonplaten** [comment]
That's very interesting! Did you train text2video-zero? Or does it just use pretrained checkpoints? 

The other possibility to reduce memory would be to make use of attention slicing: https://huggingface.co/docs/diffusers/api/diffusion_pipeline#diffusers.DiffusionPipeline.enable_attention_slicing

**Comment by camenduru** [comment]
oops maybe this is not `text2video-zero` but it is inside the demo `Pose Conditional` https://huggingface.co/spaces/PAIR/Text2Video-Zero

only with `self.pipe.enable_attention_slicing()` also not working 😭

![image (9)](https://user-images.githubusercontent.com/54370274/229153210-dc2db68e-0767-46d1-a386-8016a0c355f5.gif)

model: https://huggingface.co/plasmo/woolitize-768sd1-5/tree/main
controlnet model: https://huggingface.co/lllyasviel/sd-controlnet-openpose/tree/main

this is the colab you can test https://github.com/camenduru/text2video-zero-colab

how can I reduce the size of the model

https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main
![Screenshot 2023-03-31 174934](https://user-images.githubusercontent.com/54370274/229155420-5c17a81b-25b4-4b6b-949d-79897e5fbcbc.png)

https://huggingface.co/lllyasviel/sd-controlnet-openpose/tree/main
![Screenshot 2023-03-31 175049](https://user-images.githubusercontent.com/54370274/229155437-f46d26db-09e0-4df5-8311-b4fe25af29ee.png)

**Comment by sayakpaul** [comment]
Did get you. 

https://github.com/huggingface/diffusers/issues/2898#issuecomment-1502853740 already has with and without `xformers`.

**Comment by sayakpaul** [comment]
Could you try it out from [here](https://huggingface.co/docs/diffusers/main/en/api/pipelines/text_to_video_zero#texttovideo-with-pose-control)?

**Comment by camenduru** [comment]
woohoo 🥳 now it is working with `enable_attention_slicing()` thanks ❤

![download](https://user-images.githubusercontent.com/54370274/231108285-b57cae49-fc76-44a1-884f-9d04e5fc7ffe.gif)

**Comment by camenduru** [comment]
Unfortunately, this has not been solved. It just looks like it has been solved 😭 There is still a temporal consistency problem, even with the latest code.

**Comment by camenduru** [comment]
`enable_attention_slicing()` and `enable_xformers_memory_efficient_attention()` causing the problem

**Comment by camenduru** [comment]
without `enable_attention_slicing()` and `enable_xformers_memory_efficient_attention()` 
https://github.com/Picsart-AI-Research/Text2Video-Zero#text-to-video-1

**Comment by sayakpaul** [comment]
I will let @19and99 comment on it.

**Comment by camenduru** [comment]
please fork https://github.com/Picsart-AI-Research/Text2Video-Zero and add `self.pipe.enable_attention_slicing()` or `enable_xformers_memory_efficient_attention()` here https://github.com/Picsart-AI-Research/Text2Video-Zero/blob/44b1639baed624800cb9dce43a29e2549024bc76/model.py#L261-L288

```py
%cd /content
!git clone  https://github.com/your_username/Text2Video-Zero
!pip install -q gradio==3.23.0 decord==0.6.0 diffusers==0.14.0 accelerate==0.17.0 safetensors==0.2.7 einops==0.6.0 transformers==4.26.0
!pip install -q torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 torchtext==0.14.1 torchdata==0.5.1 --extra-index-url https://download.pytorch.org/whl/cu116 -U
!pip install -q xformers==0.0.16 triton==2.0.0 -U
!pip install -q kornia==0.6 tomesd basicsr==1.4.2 timm==0.6.12
%cd /content/Text2Video-Zero
!python app.py --public_access
```

**Comment by camenduru** [comment]
You have already replicated the problem at  at https://github.com/huggingface/diffusers/issues/2898#issuecomment-1502853740

**Comment by camenduru** [comment]
we are getting slideshow with xformers 😐 https://github.com/huggingface/diffusers/issues/2898#issue-1646956317

**Comment by sayakpaul** [comment]
I will let @19and99 comment further.

**Comment by 19and99** [comment]
Thanks for the report @camenduru, @sayakpaul, @patrickvonplaten.
We are using a custom attention processor, while `pipe.enable_xformers_memory_efficient_attention()` resets all the attention processers to  `XFormersAttnProcessor`, causing the consistency issue.

**Comment by evancasey** [comment]
Sorry if I'm missing something here but isn't a lot of the consistency stuff not enabled in this implementation when you use the controlnet text-to-video code explained in the docs?

The `TextToVideoZeroPipeline` does the latent warping and cross frame attention, but the controlnet text-to-video is only doing cross frame attention.

So it would not be expected to have full consistency as compared to the vanilla `TextToVideoZeroPipeline` example

**Comment by camenduru** [comment]
thanks @19and99 ❤ is it possible to reduce the model size? https://github.com/huggingface/diffusers/issues/2898#issuecomment-1492084722

**Comment by sayakpaul** [comment]
> We are using a custom attention processor, while pipe.enable_xformers_memory_efficient_attention() resets all the attention processers to XFormersAttnProcessor, causing the consistency issue.

Thanks for this hint, @19and99!

> is it possible to reduce the model size?

@camenduru, I think for that we need to implement a corresponding xFormers attention processor. Ccing @patrickvonplaten in case he has any other suggestions.

**Comment by camenduru** [comment]
Hi @sayakpaul 👋 if someone has time yes it will be super cool 🔥 to implement `xformers` attention processor or `attention_slicing` attention processor 

is it possible to reduce the model size?

is `convert_original_controlnet_to_diffusers.py` converting to fp32 or fp16 is it possible like `--half ` `pipe.to(torch_dtype=torch.float16)`
![image](https://user-images.githubusercontent.com/54370274/231654970-775c0cf4-94bd-44fd-afa4-80c914fe9372.png)
![image](https://user-images.githubusercontent.com/54370274/231655003-4d4c0cf1-4637-4623-a7ee-3a1dce970a5a.png)

and what is this https://github.com/huggingface/diffusers/blob/46c52f9b9607e6ecb29c782c052aea313e6487b7/scripts/convert_original_controlnet_to_diffusers.py#L29

I tried this but I don't understand the `--original_config_file` 😐 please help
```py
!pip install -q git+https://github.com/huggingface/diffusers transformers omegaconf
!git clone https://github.com/huggingface/diffusers
!wget https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_openpose.pth
!wget https://huggingface.co/lllyasviel/sd-controlnet-openpose/raw/main/config.json ?????
!python /content/diffusers/scripts/convert_original_controlnet_to_diffusers.py --checkpoint_path /content/control_sd15_openpose.pth --dump_path /content/cnet --original_config_file /content/config.json
```

**Comment by sayakpaul** [comment]
Regarding 

https://github.com/huggingface/diffusers/blob/46c52f9b9607e6ecb29c782c052aea313e6487b7/scripts/convert_original_controlnet_to_diffusers.py#L29

It's used to convert the original ControlNet parameters to the one we have in `diffusers`. For the config file, @williamberman can provide more details. 

Reducing the size of `diffusion_pytorch_model.bin` should be possible, pinging @patrickvonplaten for that.

Also, since the questions you're asking are not related to xFormers, we'd appreciate it if you could open a separate thread.

**Comment by camenduru** [comment]
In this thread, everything is connected to each other. In my opinion, we should continue here.

**Comment by sayakpaul** [comment]
The easiest options are attention slicing or xformers attention processor. These need to be implemented. 

Second option would be to run the pipeline in half precision which can be done by specifying the `torch_dtype` argument of the pipeline to `torch.float16`. For running on a 15GB card, one will likely need to couple half-precision and / or attention slicing, xFormers attention processing.

**Comment by camenduru** [comment]
update solved: `--original_config_file` https://raw.githubusercontent.com/Mikubill/sd-webui-controlnet/main/models/cldm_v15.yaml also `news` https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main thanks to lllyasviel ❤

**Comment by camenduru** [comment]
I converted to `diffusion_pytorch_model.bin` 🥳 is it possible to convent to `fp16` then `save` like `controlnet.to(torch_dtype=torch.float16)`

![Screenshot 2023-04-13 110803](https://user-images.githubusercontent.com/54370274/231695878-aa656a91-3d2c-49b9-883e-3dee9344303f.png)
