### ISSUE TITLE
Training examples missing

### ISSUE THREAD

**Issue by henrydylan** [huggingface/diffusers#290]
Hello, in the Readme file you mentioned that the training examples can be found in `examples/training` directory, but it seems that it is not there. Maybe because it is under developing but I am really looking forward to see it. Big hug to this love community! :)

**Comment by patrickvonplaten** [comment]
Thanks for the ping - updating the README as this folder doesn't exist anymore :sweat_smile:

**Comment by patrickvonplaten** [comment]
Should be solved here: https://github.com/huggingface/diffusers/blob/main/README.md :slightly_smiling_face:
