### ISSUE TITLE
AudioLDM Pipeline doesn't run: AttributeError: 'NoneType' object has no attribute 'scheduler'

### ISSUE THREAD

**Issue by Pirog17000** [huggingface/diffusers#2904]
### Describe the bug

Downloaded weights from "cvssp/audioldm" to local folder,
running an example from docs (trying), receiving AttributeError: NoneType after initializing of the pipeline

### Reproduction
```
from diffusers import AudioLDMPipeline, DPMSolverMultistepScheduler
import torch
import sys
import scipy

modelpath = "A:\SD_Models\custom_models/audio-ldm/"
pipeline = AudioLDMPipeline.from_pretrained(modelpath, torch_dtype=torch.float16)  # To use locally-downloaded weights
# pipeline = AudioLDMPipeline.from_pretrained("cvssp/audioldm", torch_dtype=torch.float16)  # If weights are not downloaded
pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config)

print(type(pipeline))
if type(pipeline)!=None:
    pipeline = pipeline.to("cuda")
else:
    sys.exit(f"Pipe is {type(pipeline)}")

prompt = "Techno music with a strong, upbeat tempo and high melodic riffs"
audio = pipeline(prompt, num_inference_steps=10, audio_length_in_s=5.0).audios[0]

# save the audio sample as a .wav file
scipy.io.wavfile.write("techno.wav", rate=16000, data=audio)
```
### Logs

```shell
│    5                                                                        │
│    6 modelpath = "A:\SD_Models\custom_models/audio-ldm/"                    │
│    7 pipeline = AudioLDMPipeline.from_pretrained(modelpath, torch_dtype=tor │
│ >  8 pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline. │
│    9 print(type(pipeline))                                                  │
│   10 if type(pipeline)!='NoneType':                                         │
│   11 │   pipeline = pipeline.to("cuda")                                     │
└─────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'NoneType' object has no attribute 'scheduler'
```

### System Info

- `diffusers` version: 0.15.0.dev0                          
- Platform: Windows-10-10.0.19045-SP0                       
- Python version: 3.10.9                                    
- PyTorch version (GPU?): 1.13.1+cu117 (True)               
- Huggingface_hub version: 0.13.2                           
- Transformers version: 4.27.0.dev0
- Accelerate version: 0.17.0.dev0
- xFormers version: 0.0.17+57edbb7.d20230228

**Comment by patrickvonplaten** [comment]
Hey @Pirog17000, 

I cannot reproduce this error. Can you maybe attached a google-colab that shows your error?

**Comment by kinoc** [comment]
I was getting AudioLDM Pipeline == 'NoneType' errors, until I created a fresh new virtual environment from scratch and installed from there. I had originally cloned from an stable diffusion based environment to start out and apparently it was masking the new code. Or so I guess. I was able to get the demo code to produce the techno wav after the fresh install.

**Comment by Pirog17000** [comment]
weird. I completely reinstalled recently diffusers but it didn't help 🤔  and yeah, I'm not using venv to run diffusers

**Comment by devxpy** [comment]
Updating transfomers to the latest version fixed this for me -

```
pip install 'transformers ~= 4.28.1'
```
