### ISSUE TITLE
Add Karras Sigmas to all schedulers

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#2905]
**Is your feature request related to a problem? Please describe.**

As stated in multiple issue:
- https://github.com/huggingface/diffusers/issues/1887
- https://github.com/huggingface/diffusers/issues/2801
- https://github.com/huggingface/diffusers/issues/2676

**Describe the solution you'd like**

It would be nice to be able to do:

```py
scheduler = DPMSolverMultistepScheduler(use_karras_sigmas=True)
```
and 
```py
scheduler = DPMSolverMultistepScheduler.from_config(scheduler.config, use_karras_sigmas=True)
```

**Describe alternatives you've considered**
No alternative possible

**Additional context**
We have a nice PR: https://github.com/huggingface/diffusers/pull/2874 that solves this for the Karras stable diffusion pipeline, but it would be nice to have this for all native diffusion schedulers as well. 

https://github.com/huggingface/diffusers/pull/2874 can be very nicely used for integration testing.

Also cc @sayakpaul @takuma104

**Comment by Pie31415** [comment]
Seems fun. Currently working on the LoRA tests PR but I'd like to take a crack at this if it's not urgent.

**Comment by sayakpaul** [comment]
Seems like a requested feature. I will try to allocate some time next week. @patrickvonplaten, anything you have in mind regarding the design I should know? I think we should consider separate PRs for separate schedulers to help with the reviews and also to keep the PRs disentangled. 

@Pie31415 thanks so much for being willing to help! We deeply appreciate it. Let's see how we want to tackle this and based on that we can circle back :)

**Comment by Pie31415** [comment]
Looking forward to it!

**Comment by sayakpaul** [comment]
https://github.com/huggingface/diffusers/pull/2956 could be a good reference PR to add `use_karras_sigmas` to the rest of the schedulers. Let's continue the discussion there.

**Comment by sayakpaul** [comment]
Related PR: https://github.com/huggingface/diffusers/pull/3001

**Comment by sayakpaul** [comment]
I think we have added support for Karras sigmas for all the most popular schedulers now. So, I think it's okay to close this issue.
