### ISSUE TITLE
Optimizer selection

### ISSUE THREAD

**Issue by jmaccall316** [huggingface/diffusers#2946]
I'm wondering if it's possible to integrate the [Lion optimizer](https://github.com/lucidrains/lion-pytorch) in train_dreambooth.py in place of AdamW if we choose, like optimizer args. I know this would conflict with people who have low VRAM and use 8bit-Adam. So Just a store_true option maybe. 

I'm going to have a look at it later but might be above my limited abilities, if anyone knows how to do it please let me know. Would like to see more control over which optimizer is used, we could all gain from more user end testing and experimenting with key setting like these. I have tried the different Adam versions, currently I use RAdam which is easy to use since it has pretty much the same structure as AdamW.

**Comment by jmaccall316** [comment]
> Hi.
> 
> Our training examples are meant to be easy to customize. We provide reasonable defaults and leave the rest to the users to control. If there's sufficient interest from the community in using Lion, then we might consider adding its support.

That seems fair. The scripts are all pretty customizable, I wouldn't want to make anything more difficult, I've just heard of it recently and seen it implemented in a couple of places elsewhere. Just kind of think the optimizer can be a pretty important customization.  I hope in the future we can put  in a selection, like a handful of optimizers to choose from the same as you can choose between schedulers, etc.  Like Adam, SGD, Lion, etc. And supporting docs. Certainly only if people are interested.

Thanks for all the work you guys put in here making this stuff work for us.

**Comment by sayakpaul** [comment]
Thanks for understanding, we deeply appreciate it. 

I am closing this issue for now but as mentioned in https://github.com/huggingface/diffusers/issues/2946#issuecomment-1495450982, we might revisit it given the interest from the community.
