### ISSUE TITLE
Having "ImportError:"

### ISSUE THREAD

**Issue by AhmedUZaki** [huggingface/diffusers#295]
I got this error 
'''
ImportError: cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_'
'''
after installing diffusers, PyTorch, and transformers.

**Comment by anton-l** [comment]
Hey @AhmedUZaki! This looks like a broken environment issue due to either pip, conda or both. 

Try reinstalling everything in a clean environment:
```
pip uninstall -y diffusers torch transformers
pip install diffusers torch transformers
```

**Comment by AhmedUZaki** [comment]
Thansk
