### ISSUE TITLE
Why img2img as a separate pipeline?

### ISSUE THREAD

**Issue by oxysoft** [huggingface/diffusers#2950]
**What API design would you like to have changed or added to the library? Why?**

I find it strange that img2img is a separate pipeline from `StableDiffusionPipeline`. The problem is that I have very limited VRAM (6GB) and I can't afford to load two separate pipelines for both txt2img and img2img. In general it seems like a strange API design to me, and many of the functionalities are clearly copy-pasted into the img2img pipeline.

**What use case would this enable or better enable? Can you give us a code example?**

Ideally it should both be the same pipeline, and we can simply omit or pass the image parameter depending on what we want.

**Comment by sayakpaul** [comment]
I think we have to promote the idea of a clear separation of concerns. 

We [support](https://huggingface.co/docs/diffusers/main/en/optimization/opt_overview) a couple of memory optimization techniques. I encourage you to check those out to see if that helps.

**Comment by cmdr2** [comment]
@oxysoft A workaround that works for me:
```py
from diffusers import StableDiffusionPipeline, StableDiffusionImg2ImgPipeline

pipe_txt2img = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)
pipe_img2img = StableDiffusionImg2ImgPipeline(
        vae=pipe_txt2img.vae,
        text_encoder=pipe_txt2img.text_encoder,
        tokenizer=pipe_txt2img.tokenizer,
        unet=pipe_txt2img.unet,
        scheduler=pipe_txt2img.scheduler,
        safety_checker=None,
        feature_extractor=None,
        requires_safety_checker=False,
)
```

This doesn't result in double the memory, the second pipeline is just a thin wrapper that barely consumes any memory. You can use the same technique for the Inpainting pipeline as well.

**Comment by oxysoft** [comment]
> @oxysoft A workaround that works for me:
> 
> ```python
> from diffusers import StableDiffusionPipeline, StableDiffusionImg2ImgPipeline
> 
> pipe_txt2img = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)
> pipe_img2img = StableDiffusionImg2ImgPipeline(
>         vae=pipe_txt2img.vae,
>         text_encoder=pipe_txt2img.text_encoder,
>         tokenizer=pipe_txt2img.tokenizer,
>         unet=pipe_txt2img.unet,
>         scheduler=pipe_txt2img.scheduler,
>         safety_checker=None,
>         feature_extractor=None,
>         requires_safety_checker=False,
> )
> ```
> 
> This doesn't result in double the memory, the second pipeline is just a thin wrapper that barely consumes any memory. You can use the same technique for the Inpainting pipeline as well.

Excellent!! I didn't know I could directly set each module that way and share them from an existing pipeline.

> I think we have to promote the idea of a clear separation of concerns.
> 
> We [support](https://huggingface.co/docs/diffusers/main/en/optimization/opt_overview) a couple of memory optimization techniques. I encourage you to check those out to see if that helps.

In all applications today, we are concerned about both txt2img and img2img and so for these requirements they are nearly the same concerns and the library is over-separating them.

However as @cmdr2 has shown the pipeline objects are merely holding references to other things and presenting an interface. The use case presented here should be a page in the docs, most people are gonna want to mix all these features without throwing away performance!

**Comment by sayakpaul** [comment]
Regarding using separate components for a pipeline, here are some official docs that might useful:

* https://huggingface.co/docs/diffusers/main/en/using-diffusers/write_own_pipeline
* https://huggingface.co/docs/diffusers/main/en/using-diffusers/loading#swap-components-in-a-pipeline

In the second guide, maybe explicitly showing how to separately load `unet`, `text_encoder`, etc. in a pipeline would be useful. Cc: @patrickvonplaten @stevhliu

**Comment by stevhliu** [comment]
Thanks for the feedback! 

What do you think about adding this to the [Reuse components across pipelines](https://huggingface.co/docs/diffusers/main/en/using-diffusers/loading#reuse-components-across-pipelines) section to show that you can reuse the same/or just some of the components in a different pipeline?

**Comment by sayakpaul** [comment]
Sounds good to me. Would you mind opening a PR?

**Comment by detkov** [comment]
For those who also read the thread and have the question "What `dtype` will be used inside the wrapped pipeline" here is the answer: all the data transfers (`device`, `dtype`) are included in the `__call__` function and depend on the corresponding `device` and `dtype` of the components, like `unet` or `text_encoder` and so on.

So there's nothing to worry about, it just works!

**Comment by zishengwu** [comment]
Bravo!! You save my life, i even spend a few hours to combine t2i and i2i into one module... 😭
