### ISSUE TITLE
Is there a straightforward way to initialize the DDPMpipeline with an openai pretrained model ?

### ISSUE THREAD

**Issue by hamadichihaoui** [huggingface/diffusers#2965]
Hi,

I want to use the following imagenet DDPM pretrained model from the openai repo https://openaipublic.blob.core.windows.net/diffusion/jul-2021/256x256_diffusion_uncond.pt.

I wonder if there is a straightforward way to initialize the DDPMpipeline using the pretrained model?

Thanks.

**Comment by patrickvonplaten** [comment]
Hey @hamadichihaoui,

We haven't added any openai model yet

**Comment by YuxinWenRick** [comment]
Hi @patrickvonplaten,

Are there any ImageNet pre-trained diffusion models on Diffuser? I couldn't find one on the [website](https://huggingface.co/models?library=diffusers&sort=downloads&search=imagenet).

Thanks.

**Comment by patrickvonplaten** [comment]
DiT was trained on ImageNet :-) https://huggingface.co/facebook/DiT-XL-2-512
