### ISSUE TITLE
The adjustment assigned to 0.01 in the loop and never re-assigned to 0

### ISSUE THREAD

**Issue by zetyquickly** [huggingface/diffusers#2972]
https://github.com/huggingface/diffusers/blob/0c63c3839a8dbaf336f640db3ddc8462d4f6711a/src/diffusers/pipelines/stable_diffusion/safety_checker.py#L73

**Comment by patrickvonplaten** [comment]
Good catch! Mind opening a PR here to fix it? :-)

**Comment by zetyquickly** [comment]
can do. @patrickvonplaten does the special care also missing, what is expected to happen with prompts similar to special care tokens?

**Comment by patrickvonplaten** [comment]
Sorry what do you mean by "special care"?

**Comment by patrickvonplaten** [comment]
Hmmm to be honest, I don't really know. cc @patil-suraj do you remember how special tokens are supposed to be dealt with?
