### ISSUE TITLE
Kandinsky 2.0 and 2.1 support

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [huggingface/diffusers#2975]
Another VQGAN based model, but with multi-lingual support and an UNCLIP style prior that allows image variations and image mixing.

https://github.com/ai-forever/Kandinsky-2

The FID is reportedly good (8.21) and since it's token based things like inpainting/outpainting are easy.

Unfortunately it is Russian state sponsored and no safetensors version of the weights currently exists.

**Comment by NotNANtoN** [comment]
I'm very curious about this as well! To be honest, Kandinsky 2.0 support would not even be necessary as it is vastly inferior to 2.1.

**Comment by patrickvonplaten** [comment]
Related: https://github.com/huggingface/diffusers/issues/2985

Agree with @NotNANtoN ! Think going for 2.1 directly makes sense here :-) 

> Unfortunately it is Russian state sponsored and no safetensors version of the weights currently exists.
Think we can assume good faith here from the authors
