### ISSUE TITLE
Is it possible to inference using multiple GPUs?

### ISSUE THREAD

**Issue by DevJunghun** [huggingface/diffusers#2977]
Hi, Thanks for sharing this library for using stable diffusion.
There is one questions I want to ask.

Like title, Is it possible to inference using multiple GPUs? If possible, how?
do you share doc about inference using multiple GPUs?

```
OS: Linux Ubuntu 20.04
GPU: RTX 4090 (24GB) * n
RAM: 72GB
Python: 3.9.16
```

assume i have two stable diffusion models (model 1, model 2)
ex) GPU 1 - using model 1, GPU 2 - using model 2

or

assume i have two request, i want to process both request parallel (prompt 1, prompt 2)
ex) GPU 1 - processing prompt 1, GPU 2 - processing prompt 2

I think.. this question can be solved by using thread and two pipes like below.. right?

```
p_01 = StableDiffusionPipeline.from_pretrained(model_01).to("cuda:0")  
p_02 = StableDiffusionPipeline.from_pretrained(model_02).to("cuda:1")  

Thread(target=generate_pipe01, args=(prompt, negative_prompt)).start()  
Thread(target=generate_pipe02, args=(prompt, negative_prompt)).start()
```

I'll be waiting for your good opinions. Thank you.

**Comment by patrickvonplaten** [comment]
Hey @DevJunghun,

here what I would recommend.

1.) Create a python file `run_distributed.py` that works in distributed mode. Note that we set the world_size here to 2 assuming that you want to run your code in parallel over 2 GPUs.

```py
#!/usr/bin/env python3
import torch
import torch.distributed as dist
import torch.multiprocessing as mp

from diffusers import DiffusionPipeline

sd = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)


def run_inference(rank, world_size):
    # create default process group
    dist.init_process_group("gloo", rank=rank, world_size=world_size)

    # move to rank
    sd.to(rank)

    if torch.distributed.get_rank() == 0:
        prompt = "a dog"
    elif torch.distributed.get_rank() == 1:
        prompt = "a cat"

    image = sd(prompt).images[0]
    image.save(f"./{'_'.join(prompt)}.png")


def main():
    world_size = 2
    mp.spawn(
        run_inference,
        args=(world_size,),
        nprocs=world_size,
        join=True
    )


if __name__ == "__main__":
    main()
```

2. Having defined the script you can start it by just running:
```
torchrun run_distributed.py
```

**Comment by patrickvonplaten** [comment]
Note that when using PyTorch's distributed data loaders you have much more control over what data goes to which GPU: 
https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html

**Comment by patrickvonplaten** [comment]
@sayakpaul @williamberman @pcuenca - it might be worth actually creating a quick doc page for this

**Comment by DevJunghun** [comment]
@patrickvonplaten Thanks for your kindness! Have a nice day :)

**Comment by sayakpaul** [comment]
Reopening this issue to keep a better track of the doc @patrickvonplaten mentioned in https://github.com/huggingface/diffusers/issues/2977#issuecomment-1498832883. 

@muellerzr do you have any recommendations for this? Anything, in particular, we need to know for the `accelerate` side to run distributed inference? Any relevant pointers would be very useful for us to ensure the doc we're putting together sheds light into the best practices :)

**Comment by muellerzr** [comment]
@sayakpaul using `accelerate launch` removes any spawn requirements etc that @patrickvonplaten shows, you can use `accelerator.process_index` (or the new `PartialState().process_index`, which is better for this stuff) to specify what GPU something should be run on. And in regards to `.to(rank)` you can use `state.device`

So in full as code:

```bash
accelerate launch file.py
```

```python
#!/usr/bin/env python3
from accelerate import PartialState
from diffusers import DiffusionPipeline

sd = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)


def run_inference():
    # Initialize the distributed environment
    state = PartialState()

    # move to rank
    sd.to(state.device)

    if state.process_index == 0:
        prompt = "a dog"
    elif state.process_index == 1:
        prompt = "a cat"

    image = sd(prompt).images[0]
    image.save(f"./{'_'.join(prompt)}.png")


def main():
    run_inference()


if __name__ == "__main__":
    main()

**Comment by chikiuso** [comment]
is there any way I could inference with multi gpu on one single image with text prompt? thanks

**Comment by sayakpaul** [comment]
@chikiuso could you describe your use case?

**Comment by sayakpaul** [comment]
Still not clear to me. 

Are you trying to generate four images for a given (single in this case) prompt?

**Comment by chikiuso** [comment]
Hi @sayakpaul Sorry for my bad English, I am trying to generate one single image with one single prompt at the same time. thanks.

**Comment by sayakpaul** [comment]
No problem. I am just trying to understand better to get your issue resolved. 

> I am trying to generate one single image with one single prompt at the same time. thanks.

Then, doesn't https://github.com/huggingface/diffusers/issues/2977#issuecomment-1500345083 work?

**Comment by pcuenca** [comment]
> No problem. I am just trying to understand better to get your issue resolved.
> 
> > I am trying to generate one single image with one single prompt at the same time. thanks.
> 
> Then, doesn't [#2977 (comment)](https://github.com/huggingface/diffusers/issues/2977#issuecomment-1500345083) work?

@sayakpaul I think they want to generate a single image across 4 different GPUs. I don't think that's possible, as the process is iterative in nature.

**Comment by zetyquickly** [comment]
@pcuenca can one parallel such iterative process MPI method, breaking one image to several workers?

**Comment by pcuenca** [comment]
@zetyquickly I don't know how to do it, unfortunately. Happy to listen to suggestions from developers in the community.

**Comment by zetyquickly** [comment]
got it

**Comment by Enderfga** [comment]
I need to use 4 GPUs to infer during the traversal of dataloader, and then use the generated images for subsequent processing. In other words, I cannot use accelerate launch to call a single py file. Do you have any suggestions on how to solve this? @muellerzr @patrickvonplaten

**Comment by laelhalawani** [comment]
Stable Diffusion XL seems to be using something parallel to MoE. Maybe MoE based architectures can be offloaded to multiple GPUs more effectively?
