### ISSUE TITLE
PNDM bug

### ISSUE THREAD

**Issue by dblunk88** [huggingface/diffusers#298]
### Describe the bug

A PNDM bug got introduced in commit b64c5227595f5eed10f6ff3ac7953de0bb07ab2d. I get IndexErrors and a highly increased step count

### Reproduction

pipe.scheduler = PNDMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", num_train_timesteps=1000)

### System Info

```shell
newest diffusers, python 3.7.x
```

**Comment by WASasquatch** [comment]
Confirmed on my own fork.

**Comment by anton-l** [comment]
Confirmed locally, @patrickvonplaten is working a fix right now! 🙌

**Comment by patrickvonplaten** [comment]
Sorry about this - should be fixed in 10min :pray:

**Comment by patrickvonplaten** [comment]
Thanks a mille for reporting @dblunk88 !
