### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)

### ISSUE THREAD

**Issue by pure-rgb** [huggingface/diffusers#2995]
### Describe the bug

With controlnet pipeline, if `'runwayml/stable-diffusion-v1-5'` is used, it works but with `'stabilityai/stable-diffusion-2-1'`, it doesn't. It looks like controlnet weight for sd 2 for `lllyasviel/sd-controlnet-canny` doesn't exist. Is there any support?

### Reproduction

```
canny = ControlNetModel.from_pretrained('lllyasviel/sd-controlnet-canny', torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    'stabilityai/stable-diffusion-2-1',
    torch_dtype=torch.float16,
    safety_checker = None,
    controlnet=canny,
)
pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)
pipe = pipe.to('cuda')

canny_cond = load_image(
    'https://huggingface.co/takuma104/controlnet_dev/resolve/main/gen_compare/control_images/converted/control_vermeer_canny.png'
)
```
```
image = pipe(prompt="masterpiece, best quality",
    num_inference_steps=30, guidance_scale=7.5,
    generator=torch.manual_seed(0), width=512, height=512, 
    image=canny_cond).images[0]
image
```

### Logs

```shell
RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)
```
```


### System Info

diffusers.__version__
'0.15.0'

**Comment by patrickvonplaten** [comment]
Hey @pure-rgb, 

Note that the official canny controlnet was trained on the v1-5 checkpoint. Could you try to use a 2.1 controlnet instead such as this one: https://huggingface.co/thibaud/controlnet-sd21-canny-diffusers

**Comment by pure-rgb** [comment]
@patrickvonplaten 
Thanks for informing. I checked the referred checkpoint. The outcoem doesn't look great same as SD 1.5. Is it expected?

**Comment by DrDavidS** [comment]
`lllyasviel/sd-controlnet-canny` only support SD1.5 and you are using SD2.1 now.

In detail, the text embedding dim of SD1.5 tokens are 768 but in SD2.1 they have are 1024.That's why you see:
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)`

Just use a control net  model that support SD2.1:  https://huggingface.co/thibaud/controlnet-sd21-canny-diffusers

**Comment by SalernoNicola** [comment]
this commands work for me:
pip install -q -U git+https://github.com/huggingface/peft.git

**Comment by TomYule** [comment]
我也遇到这个问题 下载对应的sd21 controlnet 模型即可 地址 
https://huggingface.co/thibaud/controlnet-sd21/tree/main
