### ISSUE TITLE
[Examples] Test and update READMEs on multi-GPU support

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#2997]
We keep getting issues where community members want to know how to do multi-GPU training with our training examples. An example: https://github.com/huggingface/diffusers/issues/2981.

I think we should test the following examples on a priority (as for others, multi-GPU is probably overkill) and ensure their respective READMEs have a short section on multi-GPU support (as suggested by @patrickvonplaten [here](https://github.com/huggingface/diffusers/issues/2981#issuecomment-1499031803)):

* Text-to-image
* ControlNet
* InstructPix2Pix (being introduced [here](https://github.com/huggingface/diffusers/pull/2978))

DreamBooth and Textual Inversion won't probably benefit from multi-GPU setup that much, so okay for me to not focus on them at the moment. 

I will test text-to-image as well as InstructPix2Pix. @williamberman or @yiyixuxu could do it for ControlNet?

**Comment by pure-rgb** [comment]
multi-GPU, does it refer to data parallel or model parallel, or both?

**Comment by sayakpaul** [comment]
DDP.

**Comment by williamberman** [comment]
Yeah would be fun!
