### ISSUE TITLE
[Docs] Distributed inference with multiple GPUs 

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#3010]
Originally posted by @patrickvonplaten in https://github.com/huggingface/diffusers/issues/2977#issuecomment-1498832883

**Comment by patrickvonplaten** [comment]
cc @stevhliu any chance that you have some time to add this to the docs maybe? :sweat_smile:

**Comment by stevhliu** [comment]
Absolutely, I'd be happy to! 😄
