### ISSUE TITLE
Replacing text encoder

### ISSUE THREAD

**Issue by leabrix** [huggingface/diffusers#3013]
Hello, I would like to replace the text encoder with a custom one for some experiments. In this case it would be ("cambridgeltl/SapBERT-from-PubMedBERT-fulltext"). 
How would i go about that when I want to use StableDiffusionPipeline and not LDMTextToImagePipeline or AltDiffusionPipeline?

I tried initializing them using the CLIPTextModel.from_pretrained but that does not work for me. 
What do i miss here?

**Comment by patrickvonplaten** [comment]
Hey @leabrix, 

Note that https://huggingface.co/cambridgeltl/SapBERT-from-PubMedBERT-fulltext is not a CLIPTextEncoderModel but a BertModel . Therefore you would have to load the model with `BertModel.from_pretrained("cambridgeltl/SapBERT-from-PubMedBERT-fulltext")` instead

**Comment by leabrix** [comment]
I also tried to use `BertModel` but this did not work for me. 

I can build the `StableDiffusionPipeline` but when generating images it says:

`RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

**Comment by leabrix** [comment]
I replicated this in google Colab. 

```
!pip install transformers diffusers huggingface_hub

from transformers import CLIPTextModel, CLIPTokenizer, BertTokenizer, BertModel
import torch

text_encoder = BertModel.from_pretrained("cambridgeltl/SapBERT-from-PubMedBERT-fulltext")

# tokenizer = BertTokenizer.from_pretrained("cambridgeltl/SapBERT-from-PubMedBERT-fulltext")

from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler

pipeline = StableDiffusionPipeline.from_pretrained(f"runwayml/stable-diffusion-v1-5")
pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config)
pipeline.text_encoder = text_encoder
# pipeline.tokenizer = tokenizer
pipeline.to("cuda")

images = pipeline(
    prompt="Prompt",
    height=512,
    width=512,
    num_inference_steps=25,
    guidance_scale=4,
    negative_prompt=None,
    num_images_per_prompt=1,
).images
```

Running this code the first time results in the following error:
```
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)
```

Running the image generation again results in 
```
RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
```

**Comment by patrickvonplaten** [comment]
Hey @leabrix,

What happens when you run the code on CPU? This is probably an index error under the hood which you can uncover when using CPU :-)
