### ISSUE TITLE
Convert ControlNet trained with diffusers into original CompVis format used in WebUI

### ISSUE THREAD

**Issue by huanngzh** [huggingface/diffusers#3015]
Hi, I have followed [blog/train-your-controlnet](https://huggingface.co/blog/train-your-controlnet) and got my own ControlNet model in diffusers format. Now I want to convert that into `.pth` format which can be used in [sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet). Anyone helps?

There are conversion scripts that converts between CompVis ckpt and diffusers available, but models including ControlNet may not come out.

**Comment by takuma104** [comment]
Hi @huanngzh , It seems that there is currently no script in `scripts/` to convert from the Diffusers format of ControlNet to the format used in `sd-webui-controlnet`. I tried writing one based on `scripts/convert_diffusers_to_original_stable_diffusion.py`. Could you give it a try?

https://gist.github.com/takuma104/4adfb3d968d80bea1d18a30c06439242

I made sure that the file format is compatible with the format produced after processing with [extract_controlnet.py](https://github.com/Mikubill/sd-webui-controlnet/blob/main/extract_controlnet.py).

Usage:
```sh
python convert_diffusers_controlnet_to_original_controlnet.py --model_path a_diffusers_controlnet_model_folder/ --checkpoint_path converted_file.pth
```

**Comment by huanngzh** [comment]
Hi @takuma104, I have already written a script to solve the problem myself. Thank you very much for your help. I compared my script with yours and try yours again. It works well.

**Comment by huimlight** [comment]
@huanngzh @takuma104 Hello, we use ControNet of differs code to train model, check point contain xx.bin and xx.json. How to convert json file to yaml file？ Thanks！

**Comment by takuma104** [comment]
@huimlight I believe you can convert the ControlNet checkpoint of Diffusers with the script [in this comment](https://github.com/huggingface/diffusers/issues/3015#issuecomment-1500917937). You'll need the yaml file that was used with the base model during training, please use the yaml file [from here](https://github.com/lllyasviel/ControlNet/tree/main/models). If the base model is SD1.x, you can use `cldm_v15.yaml`, and if it's SD2.x, you can use `cldm_v21.yaml`. For use with A1111 and the like, you can simply rename the yaml file used in the conversion to the same name as the checkpoint file after conversion.
