### ISSUE TITLE
[Latent Upscaling] Restore noise

### ISSUE THREAD

**Issue by chillpixelgames** [huggingface/diffusers#3018]
**What API design would you like to have changed or added to the library? Why?**

The `StableDiffusionLatentUpscalePipeline` should have the `noise_level` parameter reinstated. It was removed based on the false assumption that noise is undesirable. The author of the original commit said that:

> this step [noise] theoretically can make the model work better on out-of-distribution inputs, but mostly just seems to make it match the input less, so it's turned off by default.

It is desirable for the input to undergo some changes to enhance the output quality. Additionally, the diffuser's API ought to offer developers complete control. It is impossible to anticipate all potential scenarios, hence all features should be made accessible.

**What use case would this enable or better enable? Can you give us a code example?**

This feature is crucial in obtaining superior outcomes from the latent upscaler, and its significance is highlighted by its inclusion as a prominent setting on AUTOMATIC1111's home screen. The setting is labeled as "Denoising strength" and is enabled by default to introduce noise. It is accessible by clicking on "High res fix," which I believe employs `stabilityai/sd-x2-latent-upscaler`.

The introduction of noise enables the latent upscaler to incorporate additional details that it would have otherwise overlooked.

By way of illustration, in the image below, the inclusion of noise has not only upscaled it but also considerably augmented its quality. I find that the girl's teeth, hair, and eyes are particularly prominent.

![image (4)](https://user-images.githubusercontent.com/124188297/230706158-b7ab99c3-1bf8-4f2f-ae9d-759310e241dd.png)

![webui (2)](https://user-images.githubusercontent.com/124188297/230705789-0ff5e972-724f-4bbf-9f3e-414e698892f9.png)

**Comment by chillpixelgames** [comment]
@patrickvonplaten @pcuenca #2298

**Comment by patrickvonplaten** [comment]
I think it was never working in the first place as the noise level is never used in this PR: https://github.com/huggingface/diffusers/pull/2298/files 

So let's maybe see this issue as a feature request to add noise as an input to the latent upscaler. @yiyixuxu mind taking a look here?

**Comment by yiyixuxu** [comment]
yea sure

cc @williamberman here I think the private repo he is working on should be implementing this feature? (just based on the paper)

**Comment by yiyixuxu** [comment]
Hi @chillpixelgames:

Thanks for this issue!

I'm not familiar with AUTOMATIC1111, so I'm not sure if it's using the same model. If you have time, you can play with the original latent-upscale model here in this notebook. I think the `noise_level_aug` is the option you are looking for. We didn't implement it because the author explicitly said in her experiments she found the this option makes the result worse. Let me know if it's not the case (I will test it out myself too) 

https://colab.research.google.com/drive/1o1qYJcFeywzCIdkfKJy7cTpgZTCM2EI4

**Comment by williamberman** [comment]
@yiyixuxu I don't think we actually had to make any changes to that pipeline in that PR :)

**Comment by alexblattner** [comment]
@yiyixuxu hi, I don't mind helping out. In fact, I need to have the upscale option work for me too. I am lacking a bit of understanding on the procedure. But if you explain it to me, I'll help out.
