### ISSUE TITLE
[Examples] ControlNet (PyTorch) - custom resolution?

### ISSUE THREAD

**Issue by alelordelo** [huggingface/diffusers#3029]
On the tutorial example bellow by @pcuenca:
https://github.com/huggingface/diffusers/tree/main/examples/controlnet
https://huggingface.co/blog/train-your-controlnet

Is it possible to train with a custom resolution dataset, ex 1024 x 768?
I tried something like this, but didn't work:

accelerate launch train_controlnet.py \
 --pretrained_model_name_or_path=$MODEL_DIR \
 --output_dir=$OUTPUT_DIR \
 --dataset_name=fusing/fill50k \
 **--resolution=1024x768 \**
 --learning_rate=1e-5 \
 --validation_image "./conditioning_image_1.png" "./conditioning_image_2.png" \
 --validation_prompt "red circle with blue background" "cyan circle with brown floral background" \
 --train_batch_size=4
 
 
thanks!

**Comment by pcuenca** [comment]
Hi @alelordelo, the current version of the training script only deals with square images, so a single number is expected for the `resolution` argument. It wouldn't be hard to extend it to support different width and height, but I haven't trained any models with rectangular sizes and don't know if there are any limitations.

In order for you to test while we evaluate this change, I'd recommend you hardcode your desired dimensions here: https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py#L609, using something like:

```
            transforms.Resize((768,1024), interpolation=transforms.InterpolationMode.BILINEAR),
```

Note that the height precedes the width when using `Resize`.

Would it be possible for you to test that and see if the model trains?

Also copying @williamberman and @sayakpaul in case they have additional insight.
