### ISSUE TITLE
StableDiffusionControlNetImg2ImgPipeline' has no  attribute 'from_pretrained'

### ISSUE THREAD

**Issue by Pirog17000** [huggingface/diffusers#3032]
### Describe the bug

https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_controlnet_img2img.py
unable to launch this pipeline anyhow.
any tips?

### Reproduction

Running an example from the file itself:
```py
import numpy as np
import torch
from PIL import Image
from diffusers import ControlNetModel, UniPCMultistepScheduler
from diffusers.utils import load_image
input_image = load_image("https://hf.co/datasets/huggingface/documentation-images/resolve/main/diffusers/input_image_vermeer.png")
controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny", torch_dtype=torch.float16)
pipe_controlnet = StableDiffusionControlNetImg2ImgPipeline.from_pretrained(
                "runwayml/stable-diffusion-v1-5",
                controlnet=controlnet,
                safety_checker=None,
                torch_dtype=torch.float16
                )
pipe_controlnet.scheduler = UniPCMultistepScheduler.from_config(pipe_controlnet.scheduler.config)
pipe_controlnet.enable_xformers_memory_efficient_attention()
pipe_controlnet.enable_model_cpu_offload()
        # using image with edges for our canny controlnet
control_image = load_image(
            "https://hf.co/datasets/huggingface/documentation-images/resolve/main/diffusers/vermeer_canny_edged.png")
result_img = pipe_controlnet(controlnet_conditioning_image=control_image,
                        image=input_image,
                        prompt="an android robot, cyberpank, digitl art masterpiece",
                        num_inference_steps=20).images[0]
result_img.show()
```

### System Info

- `diffusers` version: 0.15.0.dev0
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.9
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.13.2
- Transformers version: 4.27.0.dev0
- Accelerate version: 0.17.0.dev0
- xFormers version: 0.0.17+57edbb7.d20230228

**Comment by mikegarts** [comment]
Hi @Pirog17000 

Here's an example how you can use the pipeline with one
https://colab.research.google.com/drive/1CfJO2rNKDPMJeLrTXVi7e03-QE0VruwE?usp=sharing
or multiple controlnets:
https://colab.research.google.com/drive/1e-yLAoLFUlGBSQqcGGHaMjiaOOdTlw3L?usp=sharing

Hope that helps :)

**Comment by zengjie617789** [comment]
update the version of diffusers
