### ISSUE TITLE
how to use two placeholder_tokens in textual_inversion?

### ISSUE THREAD

**Issue by yuxu915** [huggingface/diffusers#3035]
I separately trained two image sets with two placeholder_tokens, using <*dog> and <@cat>, I'd like to ask how to merge these placeholder_tokens together and generate an image such as "a <*dog> playing with a <@cat>"

**Comment by patrickvonplaten** [comment]
Hey @yuxu915, 

You can simply load two textual inversion vectors with: https://huggingface.co/docs/diffusers/main/en/api/loaders#diffusers.TextualInversionLoaderMixin.load_textual_inversion

**Comment by yuxu915** [comment]
> 

really thanks for your reply, but it seems the placeholder_tokens doesn't learn the concept(the customized dog),the training script is as follows:

```
export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export DATA_DIR="/diffusers/examples/image_instance/dog_1"
export OUTPUT_DIR="/diffusers/examples/textual_inversion/models/textual_inversion_<*_dog>_dog_500iter"

CUDA_VISIBLE_DEVICES=5 accelerate launch textual_inversion.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$DATA_DIR \
  --learnable_property="object" \
  --placeholder_token="<*_dog>" \
  --initializer_token="dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --max_train_steps=500 \
  --learning_rate=5.0e-04 \
  --scale_lr \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --output_dir=$OUTPUT_DIR
```


and the inference script is as follows:

```
from diffusers import StableDiffusionPipeline
import torch

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")

pipe.load_textual_inversion("/diffusers/examples/textual_inversion/models/textual_inversion_<*_dog>_dog_500iter")

prompt = "A <*_dog> dog"

image = pipe(prompt, num_inference_steps=50).images[0]
image.save("A <*_dog> dog.png")
```

**Comment by yuxu915** [comment]
@patrickvonplaten really thanks for your advice! I use codes like follows:
```
from diffusers import StableDiffusionPipeline
import torch

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")

pipe.load_textual_inversion("/diffusers/examples/textual_inversion/models/textual_inversion_<*_dog>_dog")
pipe.load_textual_inversion("/diffusers/examples/textual_inversion/models/textual_inversion_<cat-toy>_toy")

prompt = "A <*_dog> dog"

image = pipe(prompt, num_inference_steps=50).images[0]
image.save("A <*_dog> dog.png")
```
here, <*_dog> and <cat-toy> are two placehoders that indicate the customized dog and toy.
If I use prompt "A <*_dog> dog" or "A <cat-toy> toy", it will separately generate the dog and toy successfully,results are as follows. Hwever, if I use prompt"A <*_dog> dog and a <cat-toy> toy", the results are not satisfied, as follows:
![A_ cat-toy](https://user-images.githubusercontent.com/94051337/231961994-c5c622f0-464f-4a60-a321-fbbbb48ea835.png)
<img width="385" alt="A_ *_dog _dog_and_ cat-toy" src="https://user-images.githubusercontent.com/94051337/231962300-a32bdbcc-67f0-47f6-b1d0-bcfbb93fe512.png">
<img width="786" alt="A_ sks-dog" src="https://user-images.githubusercontent.com/94051337/231962599-2e3787ed-6f02-4218-bd29-05afe800bd75.png">

**Comment by patrickvonplaten** [comment]
Hey @yuxu915 could you upload the two textual inversion vectors to the Hub so that we can debug it? :- )

**Comment by yuxu915** [comment]
@patrickvonplaten hi, thanks for you reply! 
The vector of dog is 
[learned_embeds.bin.zip](https://github.com/huggingface/diffusers/files/11287091/learned_embeds.bin.zip)

The vector of toy is 
[learned_embeds_cat.bin.zip](https://github.com/huggingface/diffusers/files/11287124/learned_embeds_cat.bin.zip)

If I generate image with prompt such as "a <dog> play with<toy>", the results will be a dog in toy style, not a dog and a toy.

**Comment by patrickvonplaten** [comment]
Ok, I can reproduce and you seem to use the learned embeddings perfectly fine. I think the problem here is just that the textual inversion embeddings don't seem to be compatible with each other since they haven't been trained together. I'm not sure how to fix this without retraining tbh
