### ISSUE TITLE
[ControlNet] How to reproduce cartoon to realistic photo

### ISSUE THREAD

**Issue by zechenghe** [huggingface/diffusers#3036]
How can I reproduce the ControlNet cartoon-> realistic photo example? Since both the content and color are preserved, I do not think the control signal is canny/HED/hough/depth/sketch/pose/norm etc?
https://github.com/huggingface/diffusers/releases
![image](https://user-images.githubusercontent.com/24302931/230841831-eac77d5f-002f-40e8-9bb6-20025b9db488.png)

**Comment by innat-asj** [comment]
Didn't find this figure in original paper if its officially claims.
cc. @takuma104 san.

**Comment by innat-asj** [comment]
Cool. It would be great to reproduce those steps with diffusers and add it as [example](https://github.com/huggingface/diffusers/tree/main/examples).

**Comment by innat-asj** [comment]
stale.

**Comment by innat-asj** [comment]
stale.

**Comment by innat-asj** [comment]
stale.

**Comment by patrickvonplaten** [comment]
Hey @innat-asj,

I sadly won't have the time trying to reproduce it - it's much trickier than I thought. But the workflow should be as follows: https://colab.research.google.com/drive/1OZohZY6b-Jx2Q4YUkzxUFefHN961R1aa?usp=sharing

Note that you probably have to do multiple rounds of image-to-image and controlnet to get it working

**Comment by patrickvonplaten** [comment]
Hope that helps!
