### ISSUE TITLE
Add ODISE

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/diffusers#3043]
### Model/Pipeline/Scheduler description

Add ODISE, a model capable of zero-shot text-based image segmentation.

Supports text prompts out of the box, unlike Segment Anything. The model is based on the features of the frozen U-Net of Stable Diffusion

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/NVlabs/ODISE

Demo: https://huggingface.co/spaces/xvjiarui/ODISE

**Comment by sayakpaul** [comment]
Amazing paper <3 

We need to first discuss the design to best support such important use cases (another example is [here](https://diffusion-classifier.github.io/)). We currently have a couple of other things going on and we're a bit understuffed at the moment to discuss the API design right away. 

That said, I suggest we do a soft integration: have the project contributed to https://github.com/huggingface/diffusers/tree/main/examples/community.

**Comment by xvjiarui** [comment]
Thank you @NielsRogge and @sayakpaul !

The soft integration makes perfect sense to me. I will try to start work on it later this week.
