### ISSUE TITLE
conditional Unet1D

### ISSUE THREAD

**Issue by lucala** [huggingface/diffusers#3044]
**Is your feature request related to a problem? Please describe.**
I would like to work on text conditioned diffusion of 1d signals. There exists a variety of building blocks for conditional Unet2D but not for Unet1D.

**Describe the solution you'd like**
Support for conditional Unet1D (unet_1d_condition.py and respective conditional building blocks)

**Describe alternatives you've considered**
Other repo's, but they do not offer the amazing ecosystem Huggingface has.

**Comment by shivammehta25** [comment]
Hi, I would like this feature as well, even I would also like to help out to put it into the library, my use case is speech synthesis, it would be helpful to synthesise audio representations conditioned on text input.

**Comment by sayakpaul** [comment]
We have an [AudioDiffusionPipeline](https://huggingface.co/docs/diffusers/main/en/api/pipelines/audio_diffusion#diffusers.AudioDiffusionPipeline) that leverages the [`UNet2DConditionModel`](https://huggingface.co/docs/diffusers/main/en/api/models#diffusers.UNet2DConditionModel). Could that be repurposed for your use-case? I am no expert in the domain, though. So, tagging @sanchit-gandhi.

**Comment by shivammehta25** [comment]
Treating the mel spectrogram as images might not be the best inductive bias that we would want in audio synthesis there is no temporal relation in the frequency domain i.e. on the y-axis, so just for experimentation purposes, it would be nice to try it with a 1D model.

**Comment by lucala** [comment]
Yes, AudioDiffusionPipeline works on 2D spectrograms, which can also work but in my case I'm trying to experiment on raw 1D audio signals. This approach has been shown to work in [Dance Diffusion](https://huggingface.co/docs/diffusers/api/pipelines/dance_diffusion) but it only exists for the unconditional case.

**Comment by sanchit-gandhi** [comment]
Cool discussion, sorry to not have replied earlier!  I definitely agree that working directly in the audio domain is better than log-mel space (e.g. NaturalSpeech2 > DiffGAN-TTS)

I think if there's a new pipeline/model that we want to add to diffusers that leverages a 1-d conditional UNet model it'd make sense to add the class. I'm not sure how useful a standalone 1-d conditional UNet model would be though?

**Comment by shivammehta25** [comment]
I feel it will be useful for research purposes, having stronger conditioning by cross-attention would definitely perform better than concatenating channels initially (because that is what I am doing right now).

**Comment by leng-yue** [comment]
One potential application of audio is utilizing the UNet1D conditional model to forecast pitches based on midi notes and phones. This approach can prove beneficial in developing pitch prediction models.

**Comment by sayakpaul** [comment]
I think for now, we will just keep the UNet1D model as is and later we can revisit any modification if there's any model/pipeline that would benefit from it. This is in line with what we have been doing for some of our recent stuff such as ControlNet, T2I adapter (being worked on here: https://github.com/huggingface/diffusers/pull/2555).

**Comment by patrickvonplaten** [comment]
I don't think there is a need for the conditional UNet1D

**Comment by jxmorris12** [comment]
If anyone has a conditional 1D implementation, please share it here!

**Comment by frankcholula** [comment]
[diffusion policy](https://diffusion-policy.cs.columbia.edu/) uses a version borrowed from [diffusion planning](https://diffusion-planning.github.io/) which I find quite useful for modeling robot trajectories.
here's the [code](https://github.com/frankcholula/diffusion_policy/blob/main/diffusion_policy/model/diffusion/conditional_unet1d.py).

**Comment by enatrage** [comment]
just checking in, has anyone found a conditional 1D implementation?

**Comment by shivammehta25** [comment]
I ended up writing one here: https://github.com/shivammehta25/Matcha-TTS/blob/main/matcha/models/components/decoder.py#L200

**Comment by enatrage** [comment]
> I ended up writing one here: https://github.com/shivammehta25/Matcha-TTS/blob/main/matcha/models/components/decoder.py#L200

much appreciated!
