### ISSUE TITLE
What does "encoder_hidden_states" used for in DiT examples?

### ISSUE THREAD

**Issue by JincanDeng** [huggingface/diffusers#3050]

**Comment by sayakpaul** [comment]
@kashif

**Comment by kashif** [comment]
If i remember @JincanDeng the `encoder_hidden_states` is not used:

https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/dit/pipeline_dit.py#L158

only the class label is used to condition the denoising of the VAE latent.
