### ISSUE TITLE
👾 8-bit model converter

### ISSUE THREAD

**Issue by camenduru** [huggingface/diffusers#3051]
We start putting multiple models in a vram at the same time like this issue https://github.com/huggingface/diffusers/issues/2898 😐 If it is possible we need 8-bit model converter

like this for diffusers
4 bits quantization of [LLaMA](https://arxiv.org/abs/2302.13971) using [GPTQ](https://arxiv.org/abs/2210.17323)
https://github.com/qwopqwop200/GPTQ-for-LLaMa

**Comment by sayakpaul** [comment]
Cc @echarlaix from the `optimum` team regarding the possibility of this feature. 

@camenduru, thanks for reporting. If it happens, it will most likely happen from `optimum`. Hence, I cc'd Ella above.

**Comment by sayakpaul** [comment]
Can we please close this issue? It's probably a better feature request for the optimum team.

**Comment by camenduru** [comment]
ok

**Comment by echarlaix** [comment]
Hi @camenduru,

You can use the [`ORTQuantizer`](https://huggingface.co/docs/optimum/main/en/onnxruntime/usage_guides/quantization#quantize-seq2seq-models) to apply int8 quantization on different subcomponent of your ONNX model. Feel free to open an issue on [`optimum`](https://github.com/huggingface/optimum) in case you encounter any difficulties
