### ISSUE TITLE
control for versatile diffusion

### ISSUE THREAD

**Issue by pribadihcr** [huggingface/diffusers#3052]
Hi, in original repo https://github.com/SHI-Labs/Versatile-Diffusion there is fidelity level and focus level to control the generated image variation. In diffusers pipeline, is there a similar parameter for that?. Thanks

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @pribadihcr, 

I think we have not added this yet cc @anton-l . I don't think I'll find time to add this sadly
