### ISSUE TITLE
Trying to load my Lora but it doesn't work for some reason

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#3059]
```
import os

files = os.listdir('.')

for file in files:
    print(file)
if 'mngstle.safetensors' in files:
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(333)
    pipe.unet.load_attn_procs('mngstle.safetensors').to(device)
    # Use the loaded UNet module here
else:
    print('mngstle.safetensors file not found in current directory.')
```

.config
mngstle.safetensors
sample_data
333

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <cell line: 7>:10                                                                             │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/diffusers/loaders.py:208 in load_attn_procs               │
│                                                                                                  │
│   205 │   │   │   │   │   subfolder=subfolder,                                                   │
│   206 │   │   │   │   │   user_agent=user_agent,                                                 │
│   207 │   │   │   │   )                                                                          │
│ ❱ 208 │   │   │   │   state_dict = torch.load(model_file, map_location="cpu")                    │
│   209 │   │   else:                                                                              │
│   210 │   │   │   state_dict = pretrained_model_name_or_path_or_dict                             │
│   211                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/serialization.py:815 in load                        │
│                                                                                                  │
│    812 │   │   │   │   return _legacy_load(opened_file, map_location, _weights_only_unpickler,   │
│    813 │   │   │   except RuntimeError as e:                                                     │
│    814 │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None           │
│ ❱  815 │   │   return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args  │
│    816                                                                                           │
│    817                                                                                           │
│    818 # Register pickling support for layout instances such as                                  │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/serialization.py:1033 in _legacy_load               │
│                                                                                                  │
│   1030 │   │   │   f"Received object of type \"{type(f)}\". Please update to Python 3.8.2 or ne  │
│   1031 │   │   │   "functionality.")                                                             │
│   1032 │                                                                                         │
│ ❱ 1033 │   magic_number = pickle_module.load(f, **pickle_load_args)                              │
│   1034 │   if magic_number != MAGIC_NUMBER:                                                      │
│   1035 │   │   raise RuntimeError("Invalid magic number; corrupt file?")                         │
│   1036 │   protocol_version = pickle_module.load(f, **pickle_load_args)                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnpicklingError: invalid load key, '_'.

**Comment by patrickvonplaten** [comment]
Hey @alexblattner, 

I cannot reproduce your codesnippet:

```py
import os

files = os.listdir('.')

for file in files:
print(file)
if 'mngstle.safetensors' in files:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(333)
pipe.unet.load_attn_procs('mngstle.safetensors').to(device)
# Use the loaded UNet module here
else:
print('mngstle.safetensors file not found in current directory.')
```

as it gives me:
```
IndentationError: expected an indented block after 'for' statement on line 5
```

Please make sure to add a reproducible code snippet - thanks!

**Comment by alexblattner** [comment]
> Hey @alexblattner,
> 
> I cannot reproduce your codesnippet:
> 
> ```python
> import os
> 
> files = os.listdir('.')
> 
> for file in files:
> print(file)
> if 'mngstle.safetensors' in files:
> device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
> print(333)
> pipe.unet.load_attn_procs('mngstle.safetensors').to(device)
> # Use the loaded UNet module here
> else:
> print('mngstle.safetensors file not found in current directory.')
> ```
> 
> as it gives me:
> 
> ```
> IndentationError: expected an indented block after 'for' statement on line 5
> ```
> 
> Please make sure to add a reproducible code snippet - thanks!

I edited it, now it's like the OG

**Comment by patrickvonplaten** [comment]
Hey @alexblattner, 

I don't have access to: `'mngstle.safetensors'` could you upload it to the Hub: http://hf.co/ ?

**Comment by alexblattner** [comment]
I just used this code and solved it:

```
import torch
from safetensors.torch import load_file
from collections import defaultdict
def load_lora_weights(pipeline, checkpoint_path, multiplier, device, dtype):
    LORA_PREFIX_UNET = "lora_unet"
    LORA_PREFIX_TEXT_ENCODER = "lora_te"
    # load LoRA weight from .safetensors
    if isinstance(checkpoint_path, str):

        state_dict = load_file(checkpoint_path, device=device)

        updates = defaultdict(dict)
        for key, value in state_dict.items():
            # it is suggested to print out the key, it usually will be something like below
            # "lora_te_text_model_encoder_layers_0_self_attn_k_proj.lora_down.weight"

            layer, elem = key.split('.', 1)
            updates[layer][elem] = value

        # directly update weight in diffusers model
        for layer, elems in updates.items():

            if "text" in layer:
                layer_infos = layer.split(LORA_PREFIX_TEXT_ENCODER + "_")[-1].split("_")
                curr_layer = pipeline.text_encoder
            else:
                layer_infos = layer.split(LORA_PREFIX_UNET + "_")[-1].split("_")
                curr_layer = pipeline.unet

            # find the target layer
            temp_name = layer_infos.pop(0)
            while len(layer_infos) > -1:
                try:
                    curr_layer = curr_layer.__getattr__(temp_name)
                    if len(layer_infos) > 0:
                        temp_name = layer_infos.pop(0)
                    elif len(layer_infos) == 0:
                        break
                except Exception:
                    if len(temp_name) > 0:
                        temp_name += "_" + layer_infos.pop(0)
                    else:
                        temp_name = layer_infos.pop(0)

            # get elements for this layer
            weight_up = elems['lora_up.weight'].to(dtype)
            weight_down = elems['lora_down.weight'].to(dtype)
            alpha = elems['alpha']
            if alpha:
                alpha = alpha.item() / weight_up.shape[1]
            else:
                alpha = 1.0

            # update weight
            if len(weight_up.shape) == 4:
                curr_layer.weight.data += multiplier * alpha * torch.mm(weight_up.squeeze(3).squeeze(2), weight_down.squeeze(3).squeeze(2)).unsqueeze(2).unsqueeze(3)
            else:
                curr_layer.weight.data += multiplier * alpha * torch.mm(weight_up, weight_down)
    else:
        for ckptpath in checkpoint_path:
            state_dict = load_file(ckptpath, device=device)

            updates = defaultdict(dict)
            for key, value in state_dict.items():
                # it is suggested to print out the key, it usually will be something like below
                # "lora_te_text_model_encoder_layers_0_self_attn_k_proj.lora_down.weight"

                layer, elem = key.split('.', 1)
                updates[layer][elem] = value

            # directly update weight in diffusers model
            for layer, elems in updates.items():

                if "text" in layer:
                    layer_infos = layer.split(LORA_PREFIX_TEXT_ENCODER + "_")[-1].split("_")
                    curr_layer = pipeline.text_encoder
                else:
                    layer_infos = layer.split(LORA_PREFIX_UNET + "_")[-1].split("_")
                    curr_layer = pipeline.unet

                # find the target layer
                temp_name = layer_infos.pop(0)
                while len(layer_infos) > -1:
                    try:
                        curr_layer = curr_layer.__getattr__(temp_name)
                        if len(layer_infos) > 0:
                            temp_name = layer_infos.pop(0)
                        elif len(layer_infos) == 0:
                            break
                    except Exception:
                        if len(temp_name) > 0:
                            temp_name += "_" + layer_infos.pop(0)
                        else:
                            temp_name = layer_infos.pop(0)

                # get elements for this layer
                weight_up = elems['lora_up.weight'].to(dtype)
                weight_down = elems['lora_down.weight'].to(dtype)
                alpha = elems['alpha']
                if alpha:
                    alpha = alpha.item() / weight_up.shape[1]
                else:
                    alpha = 1.0

                # update weight
                if len(weight_up.shape) == 4:
                    curr_layer.weight.data += multiplier * alpha * torch.mm(weight_up.squeeze(3).squeeze(2), weight_down.squeeze(3).squeeze(2)).unsqueeze(2).unsqueeze(3)
                else:
                    curr_layer.weight.data += multiplier * alpha * torch.mm(weight_up, weight_down)
    return pipeline
import Loras #file containing the function
controlnet = ControlNetModel.from_pretrained("lllyasviel/control_v11p_sd15_openpose", torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
  "runwayml/stable-diffusion-v1-5",controlnet=controlnet, torch_dtype=torch.float16,safety_checker=None, requires_safety_checker=False,
).to("cuda")
pipe=Loras.load_lora_weights(pipe, ['galgadot.safetensors','mngstle.safetensors'],1.0,'cuda',torch.float16)
```
