### ISSUE TITLE
Is this docstring of `encoder_hidden_states` argument in `Transformer2DModel` correct?

### ISSUE THREAD

**Issue by off99555** [huggingface/diffusers#3062]
https://github.com/huggingface/diffusers/blob/e607a582cfaa7dfaf7913fc3bb54c35eceee583c/src/diffusers/models/transformer_2d.py#L228-L230

The shape is `(batch_size, seq_length, embedding_dim)`, isn't it? Also it's supposed to be float tensor. Or maybe it supports both long and float?

**Comment by patrickvonplaten** [comment]
You're right it should be a float tensor and the shape should be `(batch_size, seq_length, embedding_dim)` - mind opening a PR here? :-)

**Comment by off99555** [comment]
Sure. Done it.
