### ISSUE TITLE
Textual Inversion Colab is non-functional

### ISSUE THREAD

**Issue by whatlurks** [huggingface/diffusers#3081]
### Describe the bug

The "Create our Training Data" cell fails every time

### Reproduction

https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_textual_inversion_training.ipynb

### Logs

```shell
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <cell line: 1>:4                                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1614 in __getattr__            │
│                                                                                                  │
│   1611 │   │   │   modules = self.__dict__['_modules']                                           │
│   1612 │   │   │   if name in modules:                                                           │
│   1613 │   │   │   │   return modules[name]                                                      │
│ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1615 │   │   │   type(self).__name__, name))                                                   │
│   1616 │                                                                                         │
│   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'AutoencoderKL' object has no attribute 'sample_size'
```

### System Info

Colab

**Comment by n-dijkstra-enjins** [comment]
I have the same issue (up until the day before yesterday it worked just fine)

**Comment by n-dijkstra-enjins** [comment]
Update: it seems to be an issue with the latest development version of the `diffusers` package. For me it worked to replace the line `!pip install -U -qq diffusers==0.14.0` with `!pip install -U -qq diffusers==0.14.0` (for some reason, I couldn't get v0.15.0 to work either, but that might've been a mistake on my side).

**Comment by whatlurks** [comment]
> Update: it seems to be an issue with the latest development version of the `diffusers` package. For me it worked to replace the line `!pip install -U -qq git+https://github.com/huggingface/diffusers.git` with `!pip install -U -qq diffusers==0.14.0` (for some reason, I couldn't get v0.15.0 to work either, but that might've been a mistake on my side).

Can confirm replacing this in the first cell worked for me as well! Thank you for the temporary fix!! Issue definitely still exists with the live build, but this helped a lot for the meantime.

**Comment by antonnes** [comment]
Experiencing this issue. Changing that particular line didn't solve the problem for me.

**Comment by remorses** [comment]
Might need to replace sample_size with config.sample_size

**Comment by sayakpaul** [comment]
The Colab might have been outdated. 

Could you follow [this tutorial](https://github.com/huggingface/diffusers/tree/main/examples/textual_inversion) instead? 

PR to fix the notebook is also very welcome :)

**Comment by AdityaRajSingh** [comment]
@sayakpaul I tried using the above tutorial as suggested by you. 
[Colab for training](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_textual_inversion_training.ipynb) 
And still facing the same error. Your help would be appreciated 🙏
Thanks

**Comment by sayakpaul** [comment]
https://github.com/huggingface/diffusers/tree/main/examples/textual_inversion is actually a bit different from the notebook in the sense that the notebook may not have latest updates. 

So, I suggest trying out the training script and let us know if there are any issue.
