### ISSUE TITLE
PFGM++

### ISSUE THREAD

**Issue by Newbeeer** [huggingface/diffusers#3082]
### Model/Pipeline/Scheduler description

The PFGM++ (https://github.com/Newbeeer/pfgmpp) is a new type of generative models subsuming PFGM / diffusion models. It's more robust than diffusion models, easier to train than PFGM, and achieve SOTA on several standard conditional/unconditional image generation benchmarks. Below is a list of more detailed improvements:

*Improvements over [PFGM](https://github.com/Newbeeer/Poisson_flow) / Diffusion Models:*

- No longer require the large batch training target in *PFGM*, thus enable **flexible conditional generation and more efficient training!**
- More general $D \in \mathbb{R}^+$ dimensional augmented variable. **PFGM++ subsumes PFGM and Diffusion Models**: *PFGM* correspond to $D=1$ and *Diffusion Models* correspond to $D\to \infty$.
- Smaller $D$ **more robust** than *Diffusion Models* ( $D\to \infty$ ). Existence of **sweet spot** $D^*$ in the middle of $(1,\infty)$!
- Enable the **adjustment for model robustness and rigidity**, by tuning $D$!
- Enable **direct transfer of well-tuned hyperparameters** from any existing *Diffusion Models* ( $D\to \infty$ )

Please let me know if you would like the PFGM++ pipeline added to this repository. I would be happy to take some time to make it happen. :)

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/Newbeeer/Poisson_flow

https://github.com/Newbeeer/pfgmpp

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten

**Comment by sayakpaul** [comment]
Didn't garner enough interest. So, will close.
