### ISSUE TITLE
Text to audio with default code produces an unplayable file

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#3091]
### Describe the bug

Great with the new Text to audio feature. However, when I use the default script, the resulting file doesn't contain any audio, there are no errors printed in the console: 

The file properties looks ok:
![image](https://user-images.githubusercontent.com/1322593/231726379-5d14fbee-2b80-49f0-925c-6685505df2a5.png)

However, VLC can't ID the codec:
![image](https://user-images.githubusercontent.com/1322593/231726505-6a99a748-fca6-46c7-b67b-8d42c13bdd42.png)

Here's the file:
[Techno music with a strong_ upbeat tempo and high melodic riffs.zip](https://github.com/huggingface/diffusers/files/11220883/Techno.music.with.a.strong_.upbeat.tempo.and.high.melodic.riffs.zip)

### Reproduction

Just run the default script and check the resulting file. 

### Logs

```shell
No info in logs.
```

### System Info

Diffusers 0.15
PyTorch 2.0.0
Win 11

**Comment by patrickvonplaten** [comment]
Hey @tin2tin,

Sorry could you copy-paste the exact command you ran? I'm not 100% sure what model and what code you used? I assume it's https://huggingface.co/cvssp/audioldm

**Comment by tin2tin** [comment]
It's the code from here: https://github.com/huggingface/diffusers/releases/tag/v0.15.0

```
from diffusers import AudioLDMPipeline
import torch

repo_id = "cvssp/audioldm"
pipe = AudioLDMPipeline.from_pretrained(repo_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "Techno music with a strong, upbeat tempo and high melodic riffs"
audio = pipe(prompt, num_inference_steps=10, audio_length_in_s=5.0).audios[0]

import scipy

scipy.io.wavfile.write("techno.wav", rate=16000, data=audio)
```

**Comment by tin2tin** [comment]
@sanchit-gandhi Could you check if this is working for you and if there is some error on my end?

**Comment by heury** [comment]
I got a same error. Could you guide me on how to resolve it?

**Comment by devxpy** [comment]
> It's the code from here: [`v0.15.0` (release)](https://github.com/huggingface/diffusers/releases/tag/v0.15.0)
> 
> ```
> from diffusers import AudioLDMPipeline
> import torch
> 
> repo_id = "cvssp/audioldm"
> pipe = AudioLDMPipeline.from_pretrained(repo_id, torch_dtype=torch.float16)
> pipe = pipe.to("cuda")
> 
> prompt = "Techno music with a strong, upbeat tempo and high melodic riffs"
> audio = pipe(prompt, num_inference_steps=10, audio_length_in_s=5.0).audios[0]
> 
> import scipy
> 
> scipy.io.wavfile.write("techno.wav", rate=16000, data=audio)
> ```

Remove the `torch_dtype=torch.float16` param, and it seems to work

**Comment by tin2tin** [comment]
@devxpy Yes, you're right. That solves the problem. So, the documentation needs to be updated.
