### ISSUE TITLE
Is it possible to modify the noise directly?

### ISSUE THREAD

**Issue by oxysoft** [huggingface/diffusers#3093]
**Is your feature request related to a problem? Please describe.**
I want to do seed interpolation animation.

**Describe the solution you'd like**
We can already specify the seed as a 'generator', the next step would be to pass the noise directly instead. Then I can generate two noise tensors and interpolate them with a method of my choice.

**Describe alternatives you've considered**

**Additional context**

**Comment by oxysoft** [comment]
I think we can do it by passing a `latents` parameter when calling the pipe!

https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L535

**Comment by sayakpaul** [comment]
Yeah that is exactly correct. 

Closing this, feel free to re-open.
