### ISSUE TITLE
How to use multiple GPUs?

### ISSUE THREAD

**Issue by richardrl** [huggingface/diffusers#31]
The example script shows how to use torch distributed to launch across multiple machines.

What about using multiple GPUs? Does huggingface automatically use up all GPUs on the current machine? How do we control how much it uses?

**Comment by richardrl** [comment]
This command failed:

```
python3 -m torch.distributed.launch --nproc_per_node 10 train_unconditional.py  --dataset="cifar10"  --resolution=32  --output_dir="cifar10-ddpm"  --batch_size=64  --num_epochs=100 --gradient_accumulation_steps=1 --lr=1e-4  --warmup_steps=50
0 --mixed_precision=no
```

`    model, optimizer, train_dataloader, lr_scheduler                                                                                                                                                                                                                                                  [191/481]
  File "/usr/local/lib/python3.6/dist-packages/accelerate/accelerator.py", line 442, in prepare                                                                                                                                                                                                                
    result = tuple(self._prepare_one(obj, first_pass=True) for obj in args)                                                                                                                                                                                                                                    
  File "/usr/local/lib/python3.6/dist-packages/accelerate/accelerator.py", line 442, in <genexpr>                                                                                                                                                                                                              
    result = tuple(self._prepare_one(obj, first_pass=True) for obj in args)                                                                                                                                                                                                                                    
  File "/usr/local/lib/python3.6/dist-packages/accelerate/accelerator.py", line 338, in _prepare_one                                                                                                                                                                                                           
    return self.prepare_model(obj)                                                                                                                                                                                                                                                                             
  File "/usr/local/lib/python3.6/dist-packages/accelerate/accelerator.py", line 466, in prepare_model                                                                                                                                                                                                          
    model, device_ids=[self.local_process_index], output_device=self.local_process_index, **kwargs                                                                                                                                                                                                             
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 496, in __init__                                                                                                                                                                                                        
    dist._verify_model_across_ranks(self.process_group, parameters)                                                                                                                                                                                                                                            
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8                                                                                                                                                                                      
ncclSystemError: System call (socket, malloc, munmap, etc) failed.                                                                                                                                                                                                                                             
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 573) of binary: /usr/bin/python3                                                                                                                                                                                  
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed                                                                                                                                                                                                                 
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group                                                                                                                                                                                    
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group                                                                                                                                                                                                                                
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group                              `

**Comment by patil-suraj** [comment]
Hi @richardrl,

The command should work for multiple GPUs. To control the number of GPUs used, modify the `--nproc_per_node` argument. This needs to be less or equal to the number of GPUs you have.

**Comment by richardrl** [comment]
@patil-suraj I found the problem, need to set CUDA_VISIBLE_DEVICES to restrict to free memory GPUs

**Comment by CrazyBoyM** [comment]
does this method also support for txt2img pipe() to auto use multiple GPUs to have a faster speed? Such as a RTX2080 8g and a 3090 24g.

**Comment by patil-suraj** [comment]
@CrazyBoyM This is for training, but it's possible to use text2image pipelines with multiple GPUs for data parallel  inference. 
@pcuenca should maybe write a doc for how to use the pipeline with multi-GPUs for inference, few other users have also asked this questions on different platforms.

**Comment by MeixiChenTracy** [comment]
> @CrazyBoyM This is for training, but it's possible to use text2image pipelines with multiple GPUs for data parallel inference.
> @pcuenca should maybe write a doc for how to use the pipeline with multi-GPUs for inference, few other users have also asked this questions on different platforms.

@patil-suraj Hi, I wonder where can I find this doc for how to use the pipeline with multi-GPUs for inference? Thank you so much!
