### ISSUE TITLE
`set_attn_processor` to AttnProcessor2_0 on CPU.

### ISSUE THREAD

**Issue by pashu123** [huggingface/diffusers#3100]
Currently, setting the Attention Processor to `AttnProcessor2_0` doesn't use the torch.nn.functional.scaled_dot_product_attention op.
I tried running the  `torch.nn.functional.scaled_dot_product_attention` on the CPU for fp32 tensor and it worked.

```
pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1", torch_dtype=torch.float32)
pipe.unet.set_attn_processor(AttnProcessor2_0())
```

**Comment by sayakpaul** [comment]
Cc: @pcuenca

**Comment by patrickvonplaten** [comment]
@pashu123, I don't really understand the issue. Using `AttnProcessor2_0` always uses `torch.nn.functional.scaled_dot_product_attention` I think

**Comment by pashu123** [comment]
> @pashu123, I don't really understand the issue. Using `AttnProcessor2_0` always uses `torch.nn.functional.scaled_dot_product_attention` I think

Running it on cpu as well? I have tested it on cuda - it works fine, but on cpu it’s not generating scaled dot product op.

**Comment by pashu123** [comment]
> > @pashu123, I don't really understand the issue. Using `AttnProcessor2_0` always uses `torch.nn.functional.scaled_dot_product_attention` I think
> 
> Running it on cpu as well? I have tested it on cuda - it works fine, but on cpu it’s not generating the scaled dot product op.

Any views @patrickvonplaten ?

**Comment by patrickvonplaten** [comment]
Hey @pashu123, 

SDPA attention is **not** more efficient on CPU, it's made for GPU
