### ISSUE TITLE
Inpainting height and width

### ISSUE THREAD

**Issue by Amazingldl** [huggingface/diffusers#3103]
```
import PIL
import requests
import torch
from io import BytesIO

from diffusers import StableDiffusionInpaintPipeline


def download_image(url):
    response = requests.get(url)
    return PIL.Image.open(BytesIO(response.content)).convert("RGB")


img_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo.png"
mask_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo_mask.png"

init_image = download_image(img_url)
mask_image = download_image(mask_url)

pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting", torch_dtype=torch.float16,
)
pipe = pipe.to("cuda")

prompt = "Face of a yellow cat, high resolution, sitting on a park bench"
image = pipe(prompt=prompt, image=init_image, mask_image=mask_image, height=1024, width=1024).images[0]
```

I got this error:
```
│ D:\App\miniconda\envs\aigc\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stabl │
│ e_diffusion_inpaint.py:871 in __call__                                                           │
│                                                                                                  │
│   868 │   │   │   │                                                                              │
│   869 │   │   │   │   # concat latents, mask, masked_image_latents in the channel dimension      │
│   870 │   │   │   │   latent_model_input = self.scheduler.scale_model_input(latent_model_input   │
│ ❱ 871 │   │   │   │   latent_model_input = torch.cat([latent_model_input, mask, masked_image_l   │
│   872 │   │   │   │                                                                              │
│   873 │   │   │   │   # predict the noise residual                                               │
│   874 │   │   │   │   noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=prom   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 128 but got size 64 for tensor number 2
in the list.
```

If I set the height=520, width=520, I got this error:
```
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 65 but got size 64 for tensor number 2 in
the list.
```

Can I customize the height and width of the output image? If so, what are the requirements for height and width?
Thanks for your helps!

**Comment by Madot10** [comment]
Hi @Amazingldl, 
Something I've noticed using stable diffusion the last couple of months is about the input image height and width must be a **multiple of 64** (and the same applies to the output image)

**Comment by sayakpaul** [comment]
What happens when you do 512x512?

**Comment by Amazingldl** [comment]
Do you mean this?
image = pipe(prompt=prompt, image=init_image, mask_image=mask_image, height=512, width=512).images[0]
It works, but why can't set height=1024 and width=1024, what is wrong with this size?
> What happens when you do 512x512?

**Comment by Amazingldl** [comment]
Thank you all for your reply.

**Comment by rupertmenneer** [comment]
Hey everyone! I don't think the way image resolutions are handled is super clear way in the inpainting pipeline (and perhaps others).

The current code allows you pass in an image of incorrect resolution into the inpainting pipeline and then will throw a tensor mismatch error. Additionally, there are two input parameters: height and width - however there is no check to see whether the image actually matches the passed height/width nor does the pipeline resize the image w.r.t these inputs. I propose the following changes which I am happy to put into a PR:

- [ ] If height/width left are None, and the image isn’t 512*512 then warn users they have passed in an input image that is not the expected size and automatically resize it. Perhaps reject it if isn’t square aspect ratio.
- [ ] If the height/width have been passed as an input parameter then resize the input image accordingly. I feel like there is no point having the height/width parameters if the input image isn’t modified to match them.
- [ ] Improved documentation on the model card w.r.t input resolutions.

N.b. to clarify input sizes must already be a multiple of 8 - this is expected due the U-net multiplier/AE. This check already exists in the code that the passed height/width are a mult of 8, the pipeline works just fine on any mult of 8.

However it should also be stated that the inpainting model (and presumably the base model as well) is quite sensitive to resolution/scales. I have produced some results below inpainting on the same image at 32, 64, 128, 256, 512, 1024. As you can see results below 512 degrade significantly. This makes sense given the fact the model uses a vector quantised auto encoder and has learned to produce results at a specific scale and resolution, it is quite clear in the paper/model card they trained the model on 512 images.  I am not sure if there is anything we can do to really address this, but might make sense to make this clear to people passing in images above/below the recommended size(s). Perhaps we could add this to the model card or documentation?

Happy to write a PR for this if there is any agreement on the above?

![image](https://user-images.githubusercontent.com/71332436/235195702-09fa5cd7-c0b2-4adb-8e4e-18f25a126977.png)

**Comment by sayakpaul** [comment]
CC: @patrickvonplaten @williamberman

**Comment by williamberman** [comment]
Yes, the initial issue was probably due to one of the model inputs (latents?) being created according to the passed height and width parameters which were different dimensions from one of (or both) the resized mask and/or the encoded masked image. 

Once there are multiple picture inputs (in this case, latents, mask, and the original image), keeping track of the right dimensions for all of them can get a bit wonky :).

I think in this case, the solution might just be re-sizing the input image before it is masked and encoded. We similarly did this in the controlnet pipeline here https://github.com/huggingface/diffusers/blob/5c7a35a25915f29aa79e5b69d831fd0f7d7d8d41/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py#L672-L696

@rupertmenneer lots of interesting points on the aspect ratio side! I'm not super familiar with the affect of aspect ratio on model quality in this case but it seems outside the scope of this issue. It's probably just a small fix with resizing the masked image before its encoded. If you want to propose aspect ratio based pipeline changes might be worth a separate issue :)

**Comment by patrickvonplaten** [comment]
BTW `diffusers` code only requires height and width to be a multiple of 8, not 64 :-) See: https://github.com/huggingface/diffusers/pull/505

**Comment by Amazingldl** [comment]
solved by https://github.com/huggingface/diffusers/pull/3322
thanks [rupertmenneer](https://github.com/rupertmenneer)
