### ISSUE TITLE
controlnet inpaint with multiple conditions

### ISSUE THREAD

**Issue by timegate** [huggingface/diffusers#3104]
I tried to mimic the pull request https://github.com/huggingface/diffusers/pull/2833 to use multiple conditions on controlnet inpaint (https://github.com/timegate/diffusers, https://github.com/huggingface/diffusers/commit/aab478100fce9fea6103f192a21065df11ffa0ed),

but it (seg + depth) showed worse results than just one condition (either seg or depth)
Is there anybody working on this?

*one result using both conditions
![image](https://user-images.githubusercontent.com/16134605/231956738-efda88b5-33c4-4625-a079-7b4179751fa4.png)

*same result with one condition 
![image](https://user-images.githubusercontent.com/16134605/231957124-8d6da00e-5312-40f5-93cc-6751d1c2b7f4.png)

**Comment by timegate** [comment]
I succeed to get reasonable results by giving full-region conditions to depth map and seg map. But it is still interesting that one condition works better when using the masked version of the depth map or seg map.

![grid](https://user-images.githubusercontent.com/16134605/232358337-3fe4a37f-5985-42b7-bd7d-36021e7ad418.png)
![result](https://user-images.githubusercontent.com/16134605/232358341-b173ac3f-9f35-4de5-ba60-3095bc868206.png)

**Comment by alexblattner** [comment]
@timegate do you happen to know how to make multicontrolnet work with paint with words? I'd like my openpose characters to be the correct ones and not have them switch around. Your work is really cool btw

**Comment by timegate** [comment]
> @timegate do you happen to know how to make multicontrolnet work with paint with words? I'd like my openpose characters to be the correct ones and not have them switch around. Your work is really cool btw

I'm sorry but I can't be sure as I haven't looked at the code (paint with words), but I'm guessing it'll probably work in a similar context to this commit. I'll take a look if I have some time to do it. Thanks so much.

**Comment by timegate** [comment]
I close this issue as the pull request is done, and I will open another issue again if there are any additional updates / issues. Thanks for reviewing again :)
