### ISSUE TITLE
Generate small images with StableDiffusion, 128x128 possibly, and leave it to me to upscale later.

### ISSUE THREAD

**Issue by MatthewWaller** [huggingface/diffusers#3109]
**Is your feature request related to a problem? Please describe.**
The images are often too large to run quickly. And the memory profile too large.

**Describe the solution you'd like**
I would like to be able to generate an image that is 128x128, and decide later if I want to upscale.

**Describe alternatives you've considered**
I've tried a variety of performance enhancements to save memory and time. They have not been effective

**Additional context**
If this is something I could do by fine-tuning on 128x128 images, I could consider that. Thanks!

**Comment by MatthewWaller** [comment]
I noticed here, for instance, that a person fine-tuned on 256x256.

https://huggingface.co/justinpinkney/miniSD

Would it be possible to fine tune to 128x128, or would there be significant adjustments to make?

**Comment by jing-yu-lim** [comment]
> I noticed here, for instance, that a person fine-tuned on 256x256.
> 
> https://huggingface.co/justinpinkney/miniSD
> 
> Would it be possible to fine tune to 128x128, or would there be significant adjustments to make?

Hi, I would like to request for the same as well, or even 64x64 works. Thank you.
