### ISSUE TITLE
Save base model in ControlNet training scripts when saving trained model or pushing to hub

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#3115]
This came up in the PR to provide ControlNet support to Apple's `ml-stable-diffusion`: https://github.com/apple/ml-stable-diffusion/pull/153. I've also seen people training ControlNet models for Stable Diffusion v2 and v2.1, so it could be useful to save this as a metadata field for users of the trained models.

This would be similar to the `base_model` recently added to the textual inversion training script: https://github.com/huggingface/notebooks/commit/944dc4b45cc15303ae08bad7745a0b9d03ef5bef, but could maybe go inside the `config.json` of the saved model.

@williamberman @sayakpaul @yiyixuxu @patrickvonplaten do you think this could be useful? If so, I can submit a PR for both the PyTorch and the Flax training scripts.

**Comment by sayakpaul** [comment]
I think it would make sense to add that to the YAML metadata like we do in the DreamBooth training as well:

https://github.com/huggingface/diffusers/blob/ca783a0f1f4ce8b0a16e6b96a8890edc47489e3a/examples/dreambooth/train_dreambooth_lora.py#L70

**Comment by patrickvonplaten** [comment]
We could definitely add such a flag to the training script @pcuenca - I'd say be default we only save controlnet, but having an option to save the whole model along-side makes a lot of sense!

**Comment by pcuenca** [comment]
Thanks, @sayakpaul and @patrickvonplaten, I'll prepare a PR then! I thought we just needed the metadata info, didn't think about saving the whole model to the same repo.

Actually the metadata field already appears in some models, for example here: https://huggingface.co/lllyasviel/control_v11f1p_sd15_depth/blob/main/README.md?code=true#L3, but couldn't find it being automatically added in either the training or conversion scripts.

**Comment by atiorh** [comment]
Thank you all! We currently assume a `runwayml/stable-diffusion-v1-5` base model and [warn the users](https://github.com/apple/ml-stable-diffusion/blob/main/python_coreml_stable_diffusion/torch2coreml.py#L956) who attempt to export ControlNet models to Core ML using another model version. I will update the behavior once the base model attribute is made available in the model metadata.

**Comment by pcuenca** [comment]
Closing as fixed by #3229.
