### ISSUE TITLE
how to access progressbar?

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#3117]
hello, I would like to yield the current progress of the pipe but there's no way to access the printed progressbar. How can I give live updates on the progress in my fastapi app

**Comment by nipunjindal** [comment]
To access the progress and report back in the REST API, please pass in a callback function in the pipeline. The usage of these variables is as follows:

```
            callback (`Callable`, *optional*):
                A function that will be called every `callback_steps` steps during inference. The function will be
                called with the following arguments: `callback(step: int, timestep: int, latents: torch.FloatTensor)`.
            callback_steps (`int`, *optional*, defaults to 1):
                The frequency at which the `callback` function will be called. If not specified, the callback will be
                called at every step.
```

```
import torch
from diffusers import EulerDiscreteScheduler, StableDiffusionPipeline

seed = 33

pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4", requires_safety_checker=False
)
pipe = pipe.to("mps")
pipe.scheduler = EulerDiscreteScheduler.from_config(
    pipe.scheduler.config, use_karras_sigmas=True
)

prompt = "an astronaut riding a horse on mars"


def progress(step, timestep, latents):
    print(step, timestep, latents[0][0][0][0])


generator = torch.Generator(device="mps").manual_seed(seed)
image = pipe(
    prompt,
    generator=generator,
    num_inference_steps=20,
    callback=progress,
    callback_steps=1,
).images[0]

display(image)
```

Hope this helps.

**Comment by alexblattner** [comment]
it does! thank you! what does latents[0][0][0][0] do though?

**Comment by nipunjindal** [comment]
I simply printed an element of the latent that we are reverse diffusing. If you would like to visualize the intermediate steps, you can convert it to a PIL image.

**Comment by alexblattner** [comment]
I see, thank you!

**Comment by sayakpaul** [comment]
Thanks for your help @nipunjindal! Closing the issue, feel free to re-open.

**Comment by nirajbawa** [comment]
> To access the progress and report back in the REST API, please pass in a callback function in the pipeline. The usage of these variables is as follows:
> 
> ```
>             callback (`Callable`, *optional*):
>                 A function that will be called every `callback_steps` steps during inference. The function will be
>                 called with the following arguments: `callback(step: int, timestep: int, latents: torch.FloatTensor)`.
>             callback_steps (`int`, *optional*, defaults to 1):
>                 The frequency at which the `callback` function will be called. If not specified, the callback will be
>                 called at every step.
> ```
> 
> ```
> import torch
> from diffusers import EulerDiscreteScheduler, StableDiffusionPipeline
> 
> seed = 33
> 
> pipe = StableDiffusionPipeline.from_pretrained(
>     "CompVis/stable-diffusion-v1-4", requires_safety_checker=False
> )
> pipe = pipe.to("mps")
> pipe.scheduler = EulerDiscreteScheduler.from_config(
>     pipe.scheduler.config, use_karras_sigmas=True
> )
> 
> prompt = "an astronaut riding a horse on mars"
> 
> 
> def progress(step, timestep, latents):
>     print(step, timestep, latents[0][0][0][0])
> 
> 
> generator = torch.Generator(device="mps").manual_seed(seed)
> image = pipe(
>     prompt,
>     generator=generator,
>     num_inference_steps=20,
>     callback=progress,
>     callback_steps=1,
> ).images[0]
> 
> display(image)
> ```
> 
> Hope this helps.
what is timestep argument please explain  it

**Comment by nickyreinert** [comment]
FYI: callback is deprecated, this would be the correct implementation right now, example:


```
    image = pipeline(
        prompt=prompt,
        negative_prompt=negative_prompt,
        generator=generator,
        num_inference_steps=inference_steps, 
        callback_on_step_end=return_progress,
        guidance_scale=guidance_scale).images[0]

```
```
    def return_progress(pipe, step_index, timestep, callback_kwargs):

        [...]


```

ref https://huggingface.co/docs/diffusers/v0.27.2/en/using-diffusers/callback
