### ISSUE TITLE
How to use safetensors file for image generation?

### ISSUE THREAD

**Issue by DevJunghun** [huggingface/diffusers#3139]
Hi, Thanks for sharing this library for using stable diffusion.
There is one questions I want to ask.

I want to use safetensors file. (like civitai checkpoint, LoRA..)
do you share doc about using safetensors file?

1. how to convert safetensors file? (like [this](https://civitai.com/models/4823/deliberate))
2. I think for using LoRA, I can use [convert_lora_safetensor_to_diffusers.py](https://github.com/huggingface/diffusers/blob/main/scripts/convert_lora_safetensor_to_diffusers.py), is this right?
3. If my thought is right, Can i use this model like below code? (dump_path = test)
```python
pipe = StableDiffusionPipeline.from_pretrained(test, torch_dtype=torch.float16)
```

I'll be waiting for your good opinions. Thank you.

**Comment by caojiachen1** [comment]
You can use the official script convert_original_stable_diffusion_to_diffusers.py to convert the safetensor checkpoints  downloaded from civitai.com to diffuser type models,and you can use it like the code 
`pipe = StableDiffusionPipeline.from_pretrained(model_path , torch_dtype=torch.float16).to('cuda')`
which the model_path means the path of your converted model.This works for me.
Also I found `use_safetensors (bool, optional ) — If set to True, the pipeline will be loaded from safetensors weights. If set to None (the default). The pipeline will load using safetensors if the safetensors weights are available and if safetensors is installed. If the to False the pipeline will not use safetensors. ` in the stablediffusionpipeline official documentation.It seems that i can use the code 
`pipe = StableDiffusionPipeline.from_pretrained(SAFETENSORS_PATH , torch_dtype = torch.float16 , use_safetensors = True).to('cuda')` to load the safetensor model,but actually it didn't work which i am also confused.
I didn't try using the LoRA model so i don't know if your code works well.I have heard that diffuser cannot officially support loading lora only models currently which i don't know if it is true.

**Comment by DevJunghun** [comment]
@caojiachen1 Thank you for your reply!

**Comment by underscore-en** [comment]
The convertion script throws when I updated to 16, it worked when it was in 14.

**Comment by liuchangzong** [comment]
I have used from_ckpt to load .safetensors file according to [this](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline.from_ckpt), but I got failed. Is there anybody get the same situation??

**Comment by patrickvonplaten** [comment]
@underscore-en, can you please open a new issue with a reproducible code snippet? Otherwise it's impossible to help here
