### ISSUE TITLE
ImportError: cannot import name 'StableDiffusionControlNetPipeline'

### ISSUE THREAD

**Issue by JiaojiaoYe1994** [huggingface/diffusers#3140]
### Describe the bug

I try to generate text-to-image using ControlNet described in documentation [here](https://huggingface.co/docs/diffusers/v0.15.0/en/api/pipelines/stable_diffusion/controlnet), But  got import error  when try to import StableDiffusionControlNetPipeline. Could anyone help me out? Thank you!

### Reproduction

from diffusers import StableDiffusionControlNetPipeline                                      

### Logs

```shell
ImportError: cannot import name 'StableDiffusionControlNetPipeline' from 'diffusers' 
(/usr/local/lib/python3.8/dist-packages/diffusers/__init__.py)
```

### System Info

- `diffusers` version: 0.14.0
- Platform: Linux-5.3.0-28-generic-x86_64-with-glibc2.27
- Python version: 3.8.16
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.13.3
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: not installed

**Comment by outrun32** [comment]
Try reinstalling installing the new version of diffusers
'pip install diffusers==0.15.0`

**Comment by JiaojiaoYe1994** [comment]
It works, thanks

**Comment by FrenchMajesty** [comment]
Was this packaged removed from `0.17.0` ? Today I got the same error and I am now downgrading.

**Comment by patrickvonplaten** [comment]
No `StableDiffusionControlNetPipeline` was not removed. Doing:

```py
from diffusers import StableDiffusionControlNetPipeline
```
works just as expected when I try it

**Comment by FrenchMajesty** [comment]
I am following this Colab Notebook:
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/vertex_endpoints/torchserve/dreambooth_stablediffusion.ipynb

If you modify the file that is written for `handler.py` to include this
import line at the top, the model will fail at the last step and if you
investigate the logs it will say that import is broken. But if it's not the
diffusers package, then what could it be?

**Comment by sFinOe** [comment]
> ```python
> StableDiffusionControlNetPipeline
> ```

can you please update it on the diffusers docs?
