### ISSUE TITLE
Safety checker outside pipeline

### ISSUE THREAD

**Issue by adhikjoshi** [huggingface/diffusers#3142]
### Describe the bug

Safety checker works well like this,

```
pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5",torch_dtype=torch.float16).to("cuda")
prompt = 'close-up photo of a knot in a rope'
result =  pipe(prompt=[prompt).images
```

I want to take advantage of function "run_safety_checker" after image generation, as **i want to blur image instead of having black image.**

here is my code,

```
pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5",torch_dtype=torch.float16).to("cuda")
prompt = 'close-up photo of a knot in a rope'
result =  pipe(prompt)
image, has_nsfw_concept = pipe.run_safety_checker(result)
```

Any way to use safety_checker outside pipeline? or have option of receiving NSFW image as option, like ["StableDiffusionPipelineSafe"](https://huggingface.co/docs/diffusers/v0.15.0/en/api/pipelines/stable_diffusion_safe#safe-stable-diffusion)

### Reproduction

diffusers=0.15.0

### System Info

diffusers=0.15.0

**Comment by patrickvonplaten** [comment]
Hey @adhikjoshi note that the safety checker is just a `transformers` model component which you can load as follows:

```py
from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker

safety_checker = StableDiffusionSafetyChecker.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="safety_checker")
```
