### ISSUE TITLE
Promoting community ControlNet pipelines

### ISSUE THREAD

**Issue by pdoane** [huggingface/diffusers#3148]
**What API design would you like to have changed or added to the library? Why?**

Recently the txt2img ControlNet equivalent has been made standard, but the remaining variants are community supported.  Given how useful ControlNet is, I think it makes sense for the whole group to be promoted.

**What use case would this enable or better enable? Can you give us a code example?**

We have seen some feature divergence recently, e.g. Guidance Start/End is in the community img2img pipeline, and Guess Mode is in the standard txt2img pipeline.  These features are common to all ControlNet implementations.

**Comment by patrickvonplaten** [comment]
I don't fully understand the feature request here. What exactly are you asking for?

**Comment by alexblattner** [comment]
@patrickvonplaten this: https://github.com/cloneofsimo/paint-with-words-sd with multicontrolnet. the idea is to have prompts specific to specific areas like that you could convey to the AI which specific object or person is where while using controlnet that usually works with a single non specific object or person.

Is that clearer?

**Comment by pdoane** [comment]
What I'm suggesting is to move `stable_diffusion_controlnet_img2img.py` from community to supported pipelines.  Possibly also the inpaint pipelines but I could see waiting for how ControlNet 1.1 inpainting works out.  My guess is that divergence has increased with ControlNet txt2img being migrated as a standard pipeline but the others.  In the mean time, I've switched to making my own hybrid pipeline that combines all the features together.

I think @alexblattner is asking for something unrelated to the issue, I assume this: https://github.com/cloneofsimo/paint-with-words-sd

**Comment by alexblattner** [comment]
@pdoane I apologize "What API design would you like to have changed or **added to the library?**" I focused on that and got confused, my bad

**Comment by patrickvonplaten** [comment]
> What I'm suggesting is to move `stable_diffusion_controlnet_img2img.py` from community to supported pipelines. Possibly also the inpaint pipelines but I could see waiting for how ControlNet 1.1 inpainting works out. My guess is that divergence has increased with ControlNet txt2img being migrated as a standard pipeline but not the others. In the mean time, I've switched to making my own hybrid pipeline that combines all the features together.
> 
> I think @alexblattner is asking for something unrelated to the issue, I assume this: https://github.com/cloneofsimo/paint-with-words-sd

I agree I think we could move all the community controlnet pipelines to source pipelines cc @williamberman (@pdoane would you like to open a PR)
