### ISSUE TITLE
Diffusers 0.14.0 Produces Non-Deterministic Images

### ISSUE THREAD

**Issue by eolszewski** [huggingface/diffusers#3149]
### Describe the bug

In diffusers 0.14.0, when I generate two images with the same set of parameters, they look exactly the same to the naked eye, however, their bytes are different. I am working on a feature where I was planning on using the sha256 of each images' bytes to serve as a unique identifier, hence I came upon this bug. 

I only tested this in 0.11.1 and 0.14.0 where it worked fine in the former but precipitated this discrepancy in the latter.

### Reproduction

https://colab.research.google.com/drive/1nMLAKmC8ZpFN38WlzCxkEqe5art8_4Wa?usp=sharing

OR

```
import io
import torch
import hashlib
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)  

def bytes_from_image(image):
    buffer = io.BytesIO()
    image.save(buffer, format='JPEG')
    return buffer.getvalue()

prompt = "a photograph of an astronaut riding a horse"
image_one = pipe(prompt, generator=torch.Generator('cuda').manual_seed(42)).images[0]
image_two = pipe(prompt, generator=torch.Generator('cuda').manual_seed(42)).images[0]

image_one_hash = (hashlib.sha256(bytes_from_image(image_one)).hexdigest())
image_two_hash = (hashlib.sha256(bytes_from_image(image_two)).hexdigest())

print(image_one_hash)
print(image_two_hash)
print(image_one_hash == image_two_hash)
```

### System Info

diffusers==0.14.0

**Comment by nipunjindal** [comment]
@patrickvonplaten 's response on this [issue](https://github.com/huggingface/diffusers/issues/3061) will help you.

**Comment by eolszewski** [comment]
You are right. Thank you!
