### ISSUE TITLE
Cannot load a pretrained CLIPTextModel while using SD2.1

### ISSUE THREAD

**Issue by DrDavidS** [huggingface/diffusers#3150]
I'm tring to write a stable-diffusion pipeline on my own, and I read some tutorials about it, such as https://huggingface.co/blog/stable_diffusion

This tutorials is based on "CompVis/stable-diffusion-v1-4" and I tried it on colab, it works well.

But when I tried to change the model to "stabilityai/stable-diffusion-2-1-base",  the CLIPTextModel downloaded from hub

```python
tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14")
text_encoder = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14")
```

is still for SD1.4 with hidden_size 768, but SD2.1 requires a hidden_size 1024, doesn't match.

Also I tried 
```python
CLIPTextModel.from_pretrained("stabilityai/stable-diffusion-2-1-base")
``` 

It raise "stabilityai/stable-diffusion-2-1-base does not appear to have a file named config.json."

I dont't know how to load the correct CLIPTextModel for SD2.1, and I don't wanna use `StableDiffusionPipeline` for now.

Can you help me solve this problem?
Thanks a lot.

**Comment by takuma104** [comment]
Hi @DrDavidS , Indeed, this is quite difficult to find it. The correct answer can be found here (it's a part of ckpt conversion script): https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L839. I believe you can use these two in combination.

```py
text_model = CLIPTextModel.from_pretrained("stabilityai/stable-diffusion-2", subfolder="text_encoder")
tokenizer = CLIPTokenizer.from_pretrained("stabilityai/stable-diffusion-2", subfolder="tokenizer")
```

**Comment by DrDavidS** [comment]
> Hi @DrDavidS , Simply specifying the `subfolder` should be sufficient.
> 
> ```python
> text_model = CLIPTextModel.from_pretrained("stabilityai/stable-diffusion-2-1-base", subfolder="text_encoder")
> tokenizer = CLIPTokenizer.from_pretrained("stabilityai/stable-diffusion-2-1-base", subfolder="tokenizer")
> ```

Thanks a lot, I didn't expect it such easy!
