### ISSUE TITLE
What is the format of the training data

### ISSUE THREAD

**Issue by WGS-note** [huggingface/diffusers#3151]
Hello，I'm training Lora, but I don't know what the data format looks like,

The error is as follows:

 --caption_column' value 'text' needs to be one of: image

What is the data format?

**Comment by sayakpaul** [comment]
The dataset needs to be in the format of image-caption pairs. 

For [this dataset](https://huggingface.co/datasets/lambdalabs/pokemon-blip-captions),  `text` is the caption column. While launching the script, you can specify the image column and caption column for your dataset.

**Comment by anonymoussss** [comment]
Write a metadata.json file according to this format：https://huggingface.co/docs/datasets/v2.4.0/en/image_load#imagefolder-with-metadata
