### ISSUE TITLE
cannot import name '_pywrap_analyzer_wrapper' from  'tensorflow.lite.python.analyzer_wrapper'

### ISSUE THREAD

**Issue by tensor-song** [huggingface/diffusers#3152]
### Describe the bug

RuntimeError: Failed to import transformers.models.clip.image_processing_clip 
because of the following error (look up to see its traceback):
cannot import name '_pywrap_analyzer_wrapper' from 
'tensorflow.lite.python.analyzer_wrapper' (unknown location)

### Reproduction

RuntimeError: Failed to import transformers.models.clip.image_processing_clip 
because of the following error (look up to see its traceback):
cannot import name '_pywrap_analyzer_wrapper' from 
'tensorflow.lite.python.analyzer_wrapper' (unknown location)

### System Info

win10

**Comment by sayakpaul** [comment]
This seems like an installation problem. Have tried seeing if you can import other models from `transformers`?
