### ISSUE TITLE
How can I get seeds to reproduce images after use num_images_per_prompt > 1?

### ISSUE THREAD

**Issue by bubooK90** [huggingface/diffusers#3158]
when I set num_images_per_prompt to 4 and provide a seed for generator, I got 4 different images, of course I can reproduce first image by the seed I provided before. But how can I reproduce the other 3 images?

there is my sketch:

`
pipeline = StableDiffusionPipeline.from_pretrained(repo_id, custom_pipeline="AlanB/lpw_stable_diffusion_mod", vae=vae, torch_dtype=torch.float16).to("cuda")

...

if request['seed'] == -1:
      request['seed'] = random.randint(0, 9007199254740991)
      
    gen = torch.Generator("cuda").manual_seed(request['seed'])

    images = pipeline(
        prompt = request['prompt'],
        negative_prompt = request['negative'],
        width = int(request['width']/8)*8,
        height = int(request['height']/8)*8,
        generator = gen,
        num_inference_steps = request['steps'],
        guidance_scale = request['scale'],
        num_images_per_prompt = request['noi']
    ).images
`

Thanks a lot!

**Comment by myndxero** [comment]
Images in a batch are your base seed +1, so 4 images seed 0, seed +1, seed +2, seed+3. I use webui, not familiar with CLI at all, but hoping this helps.

**Comment by yiyixuxu** [comment]
you can pass a list of seeds match `num_images_per_prompt`

see https://huggingface.co/docs/diffusers/using-diffusers/reusing_seeds

**Comment by bubooK90** [comment]
> Images in a batch are your base seed +1, so 4 images seed 0, seed +1, seed +2, seed+3. I use webui, not familiar with CLI at all, but hoping this helps.

Thanks but it seems diffusers does not like this

**Comment by bubooK90** [comment]
> you can pass a list of seeds match `num_images_per_prompt`
> 
> see https://huggingface.co/docs/diffusers/using-diffusers/reusing_seeds

It works now! I tried before and got a error of generator list. And I saw a issue which said generator list is not support, I also ask the same question under the issue. But after that, I cannot find that issue anymore :-). Maybe it's a dream.

**Comment by bubooK90** [comment]
> > you can pass a list of seeds match `num_images_per_prompt`
> > see https://huggingface.co/docs/diffusers/using-diffusers/reusing_seeds
> 
> It works now! I tried before and got a error of generator list. And I saw a issue which said generator list is not support, I also ask the same question under the issue. But after that, I cannot find that issue anymore :-). Maybe it's a dream.

I know what happened before, I define the pipeline as below: 

`pipeline = StableDiffusionPipeline.from_pretrained(repo_id, custom_pipeline="AlanB/lpw_stable_diffusion_mod", vae=vae, torch_dtype=torch.float16).to("cuda")`

which add a custom_pipeline: AlanB/lpw_stable_diffusion_mod, then generator list cannot works. Remove the custom_pipeline everything works fine
