### ISSUE TITLE
Expected 'learned_classifier_free_sampling_embeddings' but not passed

### ISSUE THREAD

**Issue by jamarju-fp** [huggingface/diffusers#3162]
### Describe the bug

Hello.

The following snippet causes this error:

```
ValueError: Pipeline <class 'diffusers.pipelines.vq_diffusion.pipeline_vq_diffusion.VQDiffusionPipeline'> expected {'text_encoder', 'transformer', 'scheduler', 'vqvae', 'tokenizer', 'learned_classifier_free_sampling_embeddings'}, but only {'text_encoder', 'transformer', 'scheduler', 'vqvae', 'tokenizer'} were passed.
```

Which was likely introduced by: https://github.com/huggingface/diffusers/commit/f1fcfdeec5ae98b30b0939baf9e64f47c813da99

### Reproduction

```python
from diffusers import VQDiffusionPipeline
pipeline = VQDiffusionPipeline.from_pretrained("microsoft/vq-diffusion-ithq", torch_dtype=torch.float16, revision="fp16")
```

### System Info

`diffusers.__version__ = 0.15.1`

**Comment by yiyixuxu** [comment]
cc @williamberman

**Comment by init-22** [comment]
@jamarju-fp goto pipeline_vq_diffusion.py, find the class VQDiffusionPipeline and in  the __init__ method change 

learned_classifier_free_sampling_embeddings: LearnedClassifierFreeSamplingEmbeddings 

to 

learned_classifier_free_sampling_embeddings: Optional[LearnedClassifierFreeSamplingEmbeddings] = LearnedClassifierFreeSamplingEmbeddings

I didnt get the error after this, I am new to this repo so didnt test it, (dont know how to test this pipeline) but I think this should work @yiyixuxu  @williamberman

**Comment by patrickvonplaten** [comment]
Gently ping again @williamberman here

**Comment by williamberman** [comment]
ah yes we never uploaded the learned classifier embedding to the fp16 variant

**Comment by init-22** [comment]
@williamberman so you are suggesting not to pass fp16 in this case? Is there any other modifications/checks that you think should be added internally in the pipeline to solve it or atleast to make the error more clear?
