### ISSUE TITLE
diffusers result is different from webui

### ISSUE THREAD

**Issue by dingjingzhen** [huggingface/diffusers#3164]
The same prompt input effect is much worse than webui, I think it is the problem of text encoder, especially when the prompt is longer, is there a plan to do this?

**Comment by nipunjindal** [comment]
Hello @dingjingzhen,

Can you share more details on pipeline, scheduler, prompt, arguments with screenshots to compare against?

**Comment by CrazyBoyM** [comment]
same issues.I think it is caused by the different of text encoder weights.

**Comment by patrickvonplaten** [comment]
It would be great to see an example so that we can debug @dingjingzhen :-)
