### ISSUE TITLE
LPW prompt for controlnet.

### ISSUE THREAD

**Issue by aravind-h-v** [huggingface/diffusers#3171]
**Is your feature request related to a problem? Please describe.**
Currently, controlnet pipelines donot support community pipelines, I was hoping this feature can be implemented ? I really liked the LPW feature from the community pipeline and have hacked up a solution following it:

https://github.com/aravind-h-v/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py

Is it possible to get a more elegant and official implementation of this feature (and possibly other community pipelines)?

**Describe the solution you'd like**
Implement community pipelines in controlnet SD pipelines

**Describe alternatives you've considered**
Manually copy code from LPW pipeline into controlnet pipeline

**Additional context**

**Comment by patrickvonplaten** [comment]
Note that we don't actively maintain the LPW pipeline. You can instead make use of the compel library: https://huggingface.co/docs/diffusers/using-diffusers/weighted_prompts

**Comment by aravind-h-v** [comment]
Thanks for pointing this out!

**Comment by aravind-h-v** [comment]
Got this figured out, thanks.
