### ISSUE TITLE
TensorRT demo error

### ISSUE THREAD

**Issue by gaoxiao** [huggingface/diffusers#3176]
### Describe the bug

TensorRT demo error:
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/1241824/233465104-501d0b4c-035f-4742-9249-a97ee01833fe.png">

### Reproduction

Demo code for TensorRT:
https://github.com/huggingface/diffusers/blob/main/examples/community/README.md#tensorrt-text2image-stable-diffusion-pipeline

### System Info

Python: 3.10.9
diffusers: 0.16.0.dev0
TensorRT: 8.5.3.1

**Comment by sayakpaul** [comment]
Related to https://github.com/huggingface/diffusers/issues/3181.
