### ISSUE TITLE
Missing docs about how to fine-tune models

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#3190]
### Describe the bug

Currently there are no docs about how to adapt existing models for fine-tuning. E.g. fine-tuning a text-to-image model for inpainting or other tasks. 

It's actually quite easy to initialize a unet from pretrained weights while having a different archicture for some part of the model as shown here: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 

We should put this in the docs, ideally creating a whole "How to adapt a model" doc page

### Reproduction

We've now had 4,5 issues about it

### System Info

Not needed

**Comment by stevhliu** [comment]
Happy to take this on! :)

**Comment by sayakpaul** [comment]
@stevhliu please loop me in if you need any help or need to discuss anything :)
