### ISSUE TITLE
Dreambooth + Lora is broken

### ISSUE THREAD

**Issue by tcapelle** [huggingface/diffusers#3191]
### Describe the bug

The loading of the LoRA weights is not working anymore. Reverting to previous commit fixes the issue:
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/18441985/233715934-7eb0c9e5-af23-423e-9ac9-7fa5794cdc85.png">

https://wandb.ai/capecape/dreambooth-lora/reports/Dreambooth-LoRA-issues--Vmlldzo0MTQwODI0

I think this is related to how the LoRA weights are applied.

### Reproduction

https://wandb.ai/capecape/dreambooth-lora/reports/Dreambooth-LoRA-issues--Vmlldzo0MTQwODI0

### System Info

- `diffusers` version: 0.16.0.dev0
- Platform: Linux-5.15.0-1032-gcp-x86_64-with-glibc2.31
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.1 (True)
- Huggingface_hub version: 0.13.4
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: 0.0.18
- Using GPU in script?: V100
- Using distributed or parallel set-up in script?: Noe

**Comment by tcapelle** [comment]
cc. @patrickvonplaten

**Comment by sayakpaul** [comment]
Currently being worked on here: https://github.com/huggingface/diffusers/pull/3180 

Thanks for reporting and for your patience :)

**Comment by patrickvonplaten** [comment]
@tcapelle #3180 has been merged, can you try again?

**Comment by tcapelle** [comment]
<img width="1423" alt="Screenshot 2023-04-28 at 15 05 14" src="https://user-images.githubusercontent.com/18441985/235155448-25ff4d9d-7f70-404d-9ef3-7881211d09fe.png">
Everything looks awesome, thanks @patrickvonplaten and @sayakpaul =)
