### ISSUE TITLE
reuse pipline instance for later inference

### ISSUE THREAD

**Issue by junjiexv** [huggingface/diffusers#3192]
when i reuse the same stable-diffision text-to-image instance after pipe() called, it throws not all data in same device execption.
does it request a newly created pipeline, when calling pipe()?

**Comment by sayakpaul** [comment]
Could you maybe provide a code snippet for us to understand this better?

**Comment by junjiexv** [comment]
thanks for your response! here is the error:
![image](https://user-images.githubusercontent.com/24380723/234193832-c8ca5f94-9288-4dc2-90de-24e59bb70851.png) @sayakpaul

**Comment by junjiexv** [comment]
is relative to these options ?
pipe.enable_model_cpu_offload()
pipe.enable_xformers_memory_efficient_attention()

**Comment by junjiexv** [comment]
i finger it out. i calls following methods multiple times for the same pipeline instance:
  @@pipe.enable_model_cpu_offload()
pipe.enable_xformers_memory_efficient_attention()

thank you! @sayakpaul
