### ISSUE TITLE
I can't load safetensors model

### ISSUE THREAD

**Issue by Amazingldl** [huggingface/diffusers#3196]
The code is:
```
from diffusers import ControlNetModel
control1 = ControlNetModel.from_pretrained("./model/ControlNet/sd-controlnet-canny")
control2 = ControlNetModel.from_pretrained("./model/ControlNet/sd-controlnet-seg")
```

The models are local:
![image](https://user-images.githubusercontent.com/54729177/233782038-2cb21093-b505-4163-b705-6714497f675a.png)
One is .bin model, the other is .safetensors.

I got this error:
`OSError: Error no file named diffusion_pytorch_model.bin found in directory ./model/ControlNet/sd-controlnet-seg.`
![image](https://user-images.githubusercontent.com/54729177/233782270-91d6c4e6-72ef-4b7f-ad58-2c646c9b1d70.png)

I can load bin model successfully but failed to load safetensors.

and my version of diffusers is 0.16.0.dev0

Any help is appreciated!

**Comment by sayakpaul** [comment]
Do you have `safetensors` installed in your environment? 

https://github.com/huggingface/diffusers/blob/c5933c9c89c9c23c5f7f0fcd532d9a7043d879b8/src/diffusers/models/modeling_utils.py#L437

**Comment by Amazingldl** [comment]
> Do you have `safetensors` installed in your environment?
> 
> https://github.com/huggingface/diffusers/blob/c5933c9c89c9c23c5f7f0fcd532d9a7043d879b8/src/diffusers/models/modeling_utils.py#L437

I'm gonna cry because I'm so stupid~
Thank you, you are my hero~
