### ISSUE TITLE
Notes2Audio

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#320]
### Model/Pipeline/Scheduler description

https://github.com/magenta/music-spectrogram-diffusion

Very cool model that can transform notes to music. 
**Note**: Requires translating the code from Flax to PyTorch.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

cc @cghawthorne 

Also this might be interesting for @ArthurZucker . Happy to help here!

**Comment by nandwalritik** [comment]
Hi @patrickvonplaten I would like to take this up.

**Comment by patrickvonplaten** [comment]
Hey @nandwalritik,

I think @kashif and @ArthurZucker are already working on it here: https://github.com/huggingface/diffusers/pull/544 :-) 

But if you would like to help, you could review the PR a bit or you @kashif and @nandwalritik maybe you could chat a bit

**Comment by kashif** [comment]
awesome @nandwalritik please send me an email kashif.rasul@gmail.com and I can show you what i did till now! Happy to pair up then!

**Comment by nandwalritik** [comment]
Yeah sure.
