### ISSUE TITLE
google colab tracebacks become un-useable after installing

### ISSUE THREAD

**Issue by fractaldna22** [huggingface/diffusers#3205]
after pip install diffusers, the traceback format is swapped with a multi colored comic sans ms style font without hyperlink pointers to the exception line, with nothing but the line number where an exception occured or .py files with the exception are no longe clickable from within the exception traceback. I think it is replacing the traceback system with something "pretty", but it is not pretty, its un-usable, ugly, has nothing to do with diffusers, and I beg someone to please be having the same issue so it can be identified and turned off.

Example of original, good traceback
![image](https://user-images.githubusercontent.com/37323518/233866589-f80aac17-aaa3-4735-9716-3e3ccb3a9555.png)

example of the traceback after installing and importing diffusers
![image](https://user-images.githubusercontent.com/37323518/233866625-0213ce7d-cb46-4634-a1c1-4ea88b2c1441.png)

**Comment by fractaldna22** [comment]
And none of those wacky, underlined, aqua texts are not clickable. nothing is clickable after importing diffusers within the cell outputs. It makes it Impossible to fix sources of exceptions within a reasonable amount of time

**Comment by patrickvonplaten** [comment]
I don't know how to help here. What exactly would you like to change in diffusers?

**Comment by fractaldna22** [comment]
sorry. it turns out i was wrong and it wasnt diffusers, but actually from
pytorch lightning which diffusers was importing. even something as small as
"from pytorch_lightning import seed_all" will replace every exception in
the notebook with a new handler that no longer conveys the location of the
exception.  They patch their tacky crap over the original handler in
ipython or sys..   my suggestion would be to not import pytorch_lightning
in so many modules so i can remove it from my life xD  but its not
diffusers fault .  this is the normal traceback when lightning is not
imported

[image: image.png]

after its imported, all tracebacks become this
[image: image.png]

note: in the original default tracebacks, ./path/module.py  is a clickable
hyperlink, and theres always a link that takes you to the error.  in the
replaced tracebacks after pytorch_lightning is imported - those are gone
for the rest of the kernel session and all it tells you is the line
number.  it no longer underlines the error in the code either, so if you
forget the line you have to scroll back down to look at it again. thousands
of lines, thousands of hour of not running the model but just trying to
hunt down errors after this regime gets imposed

**Comment by fractaldna22** [comment]
Update 
It turns out it IS diffusers. Diffusers installs the so-called "rich" formatting module that includes the rainbow tracebacks which do not include useful tracebacks.  It sets the default system tracebacks to rich.traceback, and moreover, diffusers refuses to import pipelines or models unless rich is installed. 
Why? What functionality does rich offers that you would  default to that? Why does , or would, anyone prefer rich?  Why does it require rich to import a model that should not even be changing the tracebacks as thats completely unrelated and unnecessary to the functions of  the model?   

Please change diffusers to not default to Rich and modify the notebook system to default to rich tracebacks.

**Comment by fractaldna22** [comment]
As you can see, Diffusers will not import AudioLMPipeline, or any other pipeline, without rich installed. 

Fortunately, since rich is not installed. I am able to actually read and understand this error BECAUSE rich isnt installed. Had rich been installed, I would not be able to interpret the origin of the error and be left in the dark and annoyed that Im bombarded with unintelligible rainbow rich text with no relevant information or links to jump to the modules in question.   The problem is, Diffusers requires rich, and I Require that Diffusers NOT require rich. Please.

```python
--------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-11-32271255bc11>](https://localhost:8080/#) in <cell line: 11>()
      9 os.environ['USE_TORCH_EXTENSIONS'] = accelerator.device.type
     10 
---> 11 from diffusers import AudioLDMPipeline
     12 
     13 from share_btn import community_icon_html, loading_icon_html, share_js

5 frames
[/usr/local/lib/python3.10/dist-packages/flax/linen/summary.py](https://localhost:8080/#) in <module>
     25 import jax
     26 import jax.numpy as jnp
---> 27 import rich.console
     28 import rich.table
     29 import rich.text

ModuleNotFoundError: No module named 'rich'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by fractaldna22** [comment]
Update: It seems like uninstalling Flax allows rich to be uninstalled without causing an error in Diffusers. 
But the issue remains that this was not the default and the steps to get proper tracebacks are not obvious, i've been trying to figure this out for MONTHS.
