### ISSUE TITLE
pipe.unet.load_attn_procs not working in diffusers` version: 0.16.0

### ISSUE THREAD

**Issue by sing817** [huggingface/diffusers#3221]
### Describe the bug

I use unet.load_attn_procs but not working after update diffusers project.

what is load_lora_weights?
what is the difference between new and old lora format?
How can I know it is new or old?

### Reproduction

When 
```python
pipe.load_lora_weights("./testlora/pytorch_lora_weights.bin")
``` 
or 
```python
pipe.unet.load_attn_procs("./testlora/pytorch_lora_weights.bin")
``` 
get

```shell
    KeyError: 'down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor'
``` 
``
When
```python
pipe.load_attn_procs("./testlora/pytorch_lora_weights.bin")
``` 
it can run but not loading any lora weights.

### System Info

- `diffusers` version: 0.16.0.dev0
- Platform: Linux-5.4.0-144-generic-x86_64-with-glibc2.27
- Python version: 3.10.11
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.13.4
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: 0.0.18
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
Could you install `diffusers` (`pip install git+https://github.com/huggingface/diffusers`) from the source and retry this? https://github.com/huggingface/diffusers/pull/3180 should have fixed this.

**Comment by webliupeng** [comment]
> Could you install `diffusers` (`pip install git+https://github.com/huggingface/diffusers`) from the source and retry this? #3180 should have fixed this.

I had the same error. I run this in latest version diffusers

**Comment by sayakpaul** [comment]
Could you post a reproducible code snippet? And also which Diffusers version are you using?

**Comment by webliupeng** [comment]
> Could you post a reproducible code snippet? And also which Diffusers version are you using?

@sayakpaul could you have a look this issue #3284 , I change some code which mentioned in #3284 , and then I can run trainning lora until steps finished(I mean this progress display 500/500) , finally I got this same error``` KeyError: 'down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor'
```

**Comment by sayakpaul** [comment]
We need to be able to reproduce this issue. 

I did the following tests on my end. First, I installed `diffusers` from source: `pip -U install git+https://github.com/huggingface/diffusers`. 

Then I ran inference with three checkpoints:

* [patrickvonplaten/lora_dreambooth_dog_example](https://huggingface.co/patrickvonplaten/lora_dreambooth_dog_example): This one DOESN'T have the latest LoRA serialization format. 
* [sayakpaul/dog-test-lora](https://huggingface.co/sayakpaul/dog-test-lora): This one HAS the latest LoRA serialization format but only UNet.
* [sayakpaul/dreambooth-text-encoder-test](https://huggingface.co/sayakpaul/dreambooth-text-encoder-test): This one HAS the latest LoRA serialization format as well text encoder LoRA parameters. 

I used the following code to test inference WITHOUT any failures:

```python
from huggingface_hub.repocard import RepoCard
from diffusers import StableDiffusionPipeline
import torch 

# any of the above checkpoints should work here
lora_model_id = "sayakpaul/dreambooth-text-encoder-test" 
card = RepoCard.load(lora_model_id)
base_model_id = card.data.to_dict()["base_model"]

pipe = StableDiffusionPipeline.from_pretrained(base_model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")
pipe.load_lora_weights(lora_model_id)
image = pipe("A picture of a sks dog in a bucket", num_inference_steps=25).images[0]
```

Anything I am missing out on? 

I have also created this PR to clear some ambiguity around loading method for LoRA: https://github.com/huggingface/diffusers/pull/3299
