### ISSUE TITLE
no " pytorch_custom_diffusion_weights.bin" after training in custom_diffusion.

### ISSUE THREAD

**Issue by yuxu915** [huggingface/diffusers#3222]
### Describe the bug

"Error no file named pytorch_custom_diffusion_weights.bin found in directory xxx"
after training, I get these files:
<img width="195" alt="image" src="https://user-images.githubusercontent.com/94051337/234231865-fe46ec9e-f962-418d-a79e-73c7a1e7b528.png">
which one should I load fot inference?

### Reproduction

train and infer code as same as source code.

### System Info

- `diffusers` version: 0.15.0.dev0
- Platform: Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.13.3
- Transformers version: 4.28.0.dev0
- Accelerate version: 0.16.0
- xFormers version: 0.0.18
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by yiyixuxu** [comment]
Looks like the folder contains an intermediate checkpoint at 250 
if you let the training finish, you should find a `pytorch_custom_diffusion_weights.bin` in your directory

**Comment by yuxu915** [comment]
@yiyixuxu hi, thanks for your reply, 
I got a `pytorch_lora_weights.bin` rather than `pytorch_custom_diffusion_weights.bin` after training. Training step is setting to 100.
Below is the training log returned from the terminal:


04/26/2023 02:16:41 - INFO - __main__ - ***** Running training *****
04/26/2023 02:16:41 - INFO - __main__ -   Num examples = 120
04/26/2023 02:16:41 - INFO - __main__ -   Num batches each epoch = 60
04/26/2023 02:16:41 - INFO - __main__ -   Num Epochs = 2
04/26/2023 02:16:41 - INFO - __main__ -   Instantaneous batch size per device = 2
04/26/2023 02:16:41 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 2
04/26/2023 02:16:41 - INFO - __main__ -   Gradient Accumulation steps = 1
04/26/2023 02:16:41 - INFO - __main__ -   Total optimization steps = 100
Steps: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:03<00:00,  1.63it/s, loss=0.817, lr=4e-5]Model weights saved in ./model_output/single_cat_test/pytorch_lora_weights.bin
04/26/2023 02:17:45 - INFO - __main__ - Saving embeddings
{'requires_safety_checker'} was not found in config. Values will be initialized to default values.
{'upcast_attention', 'mid_block_type', 'conv_in_kernel', 'num_class_embeds', 'class_embed_type', 'timestep_post_act', 'time_embedding_type', 'only_cross_attention', 'resnet_time_scale_shift', 'conv_out_kernel', 'projection_class_embeddings_input_dim', 'use_linear_projection', 'time_cond_proj_dim', 'class_embeddings_concat', 'dual_cross_attention'} was not found in config. Values will be initialized to default values.
{'norm_num_groups'} was not found in config. Values will be initialized to default values.
{'prediction_type'} was not found in config. Values will be initialized to default values.
/data/diffusers_new/diffusers/transformers/src/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
{'lower_order_final', 'dynamic_thresholding_ratio', 'solver_type', 'algorithm_type', 'sample_max_value', 'solver_order', 'thresholding'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "train_custom_diffusion.py", line 1289, in <module>
    main(args)
  File "train_custom_diffusion.py", line 1242, in main
    pipeline.unet.load_attn_procs(args.output_dir, weight_name="pytorch_custom_diffusion_weights.bin")
  File "/data/diffusers_new/diffusers/src/diffusers/loaders.py", line 195, in load_attn_procs
    model_file = _get_model_file(
  File "/data/diffusers_new/diffusers/src/diffusers/utils/hub_utils.py", line 272, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named pytorch_custom_diffusion_weights.bin found in directory ./model_output/single_cat_test.
Steps: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:14<00:00,  1.34it/s, loss=0.817, lr=4e-5]
Traceback (most recent call last):
  File "/data/anaconda3/envs/diffusers_new/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data/anaconda3/envs/diffusers_new/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/data/anaconda3/envs/diffusers_new/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/data/anaconda3/envs/diffusers_new/lib/python3.8/site-packages/accelerate/commands/launch.py", line 552, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/data/anaconda3/envs/diffusers_new/bin/python', 'train_custom_diffusion.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=/data/datasets/image_instance/cat', '--output_dir=./model_output/single_cat_test', '--class_data_dir=/data/datasets/img_class/cat/cat', '--with_prior_preservation', '--prior_loss_weight=1.0', '--class_prompt=cat', '--num_class_images=120', '--instance_prompt=photo of a <new1> cat', '--resolution=512', '--train_batch_size=2', '--learning_rate=1e-5', '--lr_warmup_steps=0', '--max_train_steps=100', '--scale_lr', '--hflip', '--modifier_token', '<new1>']' returned non-zero exit status 1.

**Comment by sayakpaul** [comment]
As mentioned in the other thread, maybe your local clone is outdated as this clearly should not be the case:

https://github.com/huggingface/diffusers/blob/256e6960cbe8a6379ee396ca6317503a991b9bbe/src/diffusers/loaders.py#L348-L351

And then:

https://github.com/huggingface/diffusers/blob/256e6960cbe8a6379ee396ca6317503a991b9bbe/examples/custom_diffusion/train_custom_diffusion.py#L1230

**Comment by daeunni** [comment]
@yuxu915 Hi, did u succeed in the inference with them except `pytorch_custom_diffusion_weights.bin` file? How did u address this issue?
