### ISSUE TITLE
[instructpixel2pixel]RuntimeError: For now only a certain number of K values are supported. Let us know if you hit this and we will fix it

### ISSUE THREAD

**Issue by lsabrinax** [huggingface/diffusers#3228]
### Describe the bug

RuntimeError: For now only a certain number of K values are supported. Let us know if you hit this and we will fix it

### Reproduction

accelerate launch --mixed_precision="fp16" train_instruct_pix2pix.py \
    --pretrained_model_name_or_path=$MODEL_NAME \
    --dataset_name=$DATASET_ID \
    --enable_xformers_memory_efficient_attention \
    --resolution=256 --random_flip \
    --train_batch_size=4 --gradient_accumulation_steps=4 --gradient_checkpointing \
    --max_train_steps=15000 \
    --checkpointing_steps=5000 --checkpoints_total_limit=1 \
    --learning_rate=5e-05 --max_grad_norm=1 --lr_warmup_steps=0 \
    --conditioning_dropout_prob=0.05 \
    --mixed_precision=fp16 \
    --seed=42 

### System Info

- `diffusers` version: 0.16.0.dev0
- Platform: Linux-4.14.0_1-0-0-47-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.10
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Huggingface_hub version: 0.13.4
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: 0.0.12
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by sayakpaul** [comment]
What is your error? I followed the official docs and I couldn't reproduce it. Could you try to help us reproduce it?
