### ISSUE TITLE
How to user safetensors file in pipe

### ISSUE THREAD

**Issue by VmFree** [huggingface/diffusers#3232]
Hi, I'm looking for an example to directly use safetensors file (e.g. v1-5-pruned.safetensors) in pipe such as 
```
DiffusionPipeline.from_pretrained("E:\\aimodels\\v1-5-pruned.safetensors", use_safetensors=True)
```

but what I can find is something like 
```
DiffusionPipeline.from_pretrained(pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5")
```
for parameter pretrained_model_name_or_path, API say:
```
pretrained_model_name_or_path (str or os.PathLike, optional) — Can be either:
           A string, the repo id of a pretrained pipeline hosted inside a model repo on https://huggingface.co/ Valid repo ids have to be located under a user or organization name, like CompVis/ldm-text2im-large-256.
            A path to a directory containing pipeline weights saved using [save_pretrained()] ./my_pipeline_directory/.
```

I don't know why it should be a *directory*, and can't be a .safetensors file?

any example or explain will be great helpful, thank you!

**Comment by alexblattner** [comment]
@VmFree I am having the same issue. Apparently you're supposed to use from_ckpt, but I didn't understand how to use it for controlnet.... at least you can just enjoy this solution for now: https://github.com/huggingface/diffusers/issues/3204#issuecomment-1521462853

**Comment by sayakpaul** [comment]
If you have `safetensors` installed by default it should load the safetensor variant of the checkpoint by default actually. 

> DiffusionPipeline.from_pretrained(pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5")

You're supposed to pass a path that contains the checkpoints and not the weight names to the `pretrained_model_name_or_path` argument.

**Comment by cmawhorter** [comment]
FWIW -- you need a directory with all those subdirectories (vae, unet, text_encoder, etc.), and then in _those_ directories the model is stored in the format safetensors. e.g. text_encoder/model.safetensors

the safetensors file from HF can contain all those other bits folded into the file. or not. so, you need to run it through something that converts it to that expected directory structure.

in my case i was trying to use a checkpoint converted by invokeai to test out TI, and couldn't figure out why it wasn't working. turns out in my case, i'm dumb and just needed to do `pip install safetensors` in the examples/textual_inversion directory like literally everything told me to do.

**Comment by sayakpaul** [comment]
Just trying to understand this better. Is the issue stemming from the fact it's not explicitly clear what folder structure to expect when running the examples? 

Cc: @yiyixuxu @stevhliu

**Comment by cmawhorter** [comment]
speaking for myself, it was confusing that "models" are being distributed as a single file with the safetensors extension and seem to be packaged archives, when in reality safetensors is just a container and nothing more. 

some of the tools out there accept those single files and hide all the complexity of working with them, which kept me from understanding what's going on behind-the-scenes. (and cemented the idea in my brain that they're archives)

reading through the script to convert to diffusers here and looking through how a safetensors file is handled by other tools finally got me over the hump.

**Comment by sayakpaul** [comment]
@VmFree let us know if the comments above resolve your problem.
