### ISSUE TITLE
Can't run StableDiffusionKDiffusionPipeline

### ISSUE THREAD

**Issue by sanbuphy** [huggingface/diffusers#3250]
### Describe the bug

I would like to use StableDiffusionKDiffusionPipeline, but when I run it directly, an error occurs with the message "AttributeError: 'StableDiffusionKDiffusionPipeline' object has no attribute 'sampler'".

### Reproduction

```python
from diffusers import StableDiffusionKDiffusionPipeline
import time

pipeline = StableDiffusionKDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
pipeline.to("cuda")
images = pipeline("woman,cute,headshot",num_inference_steps=20).images[0]
images.save(f"mytest-{time.time()}.jpg")

```

### Logs

```shell
AttributeError: 'StableDiffusionKDiffusionPipeline' object has no attribute 'sampler'
```
![image](https://user-images.githubusercontent.com/96160062/234740716-6294e046-0d70-421d-b32e-d9bb6efbfc73.png)

### System Info

- `diffusers` version: 0.16.0.dev0
- Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.13.4
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by yiyixuxu** [comment]
@sanbuphy 

you need to call 
`pipeline..set_scheduler("...")`

maybe we should add a docstring example here 

YiYi

**Comment by sanbuphy** [comment]
> @sanbuphy
> 
> you need to call `pipeline.set_scheduler("...")`
> 
> maybe we should add a docstring example here
> 
> YiYi

Thank you very much. it works well.

yes, i think we need a example. I try to find something tips in docs but i don't git it. and we should use the attr like `sample_euler` while the other people  don't know.
