### ISSUE TITLE
Why webui and diffuser chose the same prompt and sampler but cannot get the same results?

### ISSUE THREAD

**Issue by sanbuphy** [huggingface/diffusers#3253]
Hello, I would like to ask why the WebUI of Auto111 and all Diffusers on github  cannot get the same results? I want to know the reason, thank you very much.

**Comment by nipunjindal** [comment]
Happy to debug these issues. To make this actionable, please share a diffusers code to repro v/s kdkiffusion pipeline.

**Comment by sanbuphy** [comment]
> Happy to debug these issues. To make this actionable, please share diffusers code to repro v/s kdkiffusion pipeline.

I use this code in diffuser:
```python
from diffusers import StableDiffusionKDiffusionPipeline
import time
import torch

pipeline = StableDiffusionKDiffusionPipeline.from_pretrained("v1-5-pruned", torch_dtype=torch.float16)
pipeline.to("cuda")

pipeline.set_scheduler("sample_euler")
generator = torch.manual_seed(1234)
images = pipeline("cat",num_inference_steps=20,generator= generator).images[0]
images.save(f"mytest-{time.time()}.jpg")
```

and i use the same param in auto111webui:
![image](https://user-images.githubusercontent.com/96160062/234771357-89dc6fdc-d9d0-4233-9d55-d258140ee6b4.png)

but i can't get the same result

**Comment by alexblattner** [comment]
@sanbuphy that's because they use compel (not the same as what A1111 uses). here's something relevant: https://github.com/damian0815/compel/issues/16

I know it sucks that it is that way, but that's how it is sadly... Hopefully the diffusers team does what A111 did

**Comment by sanbuphy** [comment]
> @sanbuphy that's because they use compel (not the same as what A1111 uses). here's something relevant: [damian0815/compel#16](https://github.com/damian0815/compel/issues/16)
> 
> I know it sucks that it is that way, but that's how it is sadly... Hopefully the diffusers team does what A111 did

Thank you ! cheems.
I haven't even used complex prompts yet. Just using the simplest prompt like 'cat' already makes a big difference in the results, and I don't even have any negative prompts.

**Comment by nipunjindal** [comment]
I don't have A1111 setup, however, StableDiffusionPipeline v/s StableDiffusionKDiffusionPipeline is exactly same for me, which makes me believe there some believe there are some differences in A111.

![Screenshot 2023-04-27 at 2 09 02 PM](https://user-images.githubusercontent.com/6430864/234807713-9a66eaca-ae88-475b-8eac-bb5d2cbdab48.png)
![Screenshot 2023-04-27 at 2 09 11 PM](https://user-images.githubusercontent.com/6430864/234807779-17403d5d-147c-4fa5-abee-c13fae9ace1a.png)

**Comment by sanbuphy** [comment]
> I don't have A1111 setup, however, StableDiffusionPipeline v/s StableDiffusionKDiffusionPipeline is exactly same for me, which makes me believe there are some differences in A111.
> 
> ![Screenshot 2023-04-27 at 2 09 02 PM](https://user-images.githubusercontent.com/6430864/234807713-9a66eaca-ae88-475b-8eac-bb5d2cbdab48.png) ![Screenshot 2023-04-27 at 2 09 11 PM](https://user-images.githubusercontent.com/6430864/234807779-17403d5d-147c-4fa5-abee-c13fae9ace1a.png)

Hi!  Please trust me, they will be very different. You can deploy and test locally to see.

https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by takuma104** [comment]
Hi @sanbuphy , In the `generator` argument, we specify the method for generating random numbers used in latent or euler sampling. If you specify it with `torch.manual_seed()`, it will be generated on the CPU. This is the cause of significant differences in the generated images, as it is assumed to be generated on the GPU (cuda) in A1111. By doing as follows, I believe almost the same images will be generated.

```py
generator = torch.Generator(device='cuda').manual_seed(1234)
```

Also, the default value of guidance_scale in Diffusers is 7.5. In contrast, according to the screenshot of A1111, the scale is set to 7.0, which also results in a slight difference.

**Comment by sanbuphy** [comment]
> Hi @sanbuphy , In the `generator` argument, we specify the method for generating random numbers used in latent and euler sampler. If you specify it with `torch.manual_seed()`, it will be generated on the CPU. This is the cause of significant differences in the generated images, as it is assumed to be generated on the GPU (cuda) in A1111. By doing as follows, I believe almost the same images will be generated.
> 
> ```python
> generator = torch.Generator(device='cuda').manual_seed(1234)
> ```
> 
> Also, the default value of `guidance_scale` in Diffusers is `7.5`. In contrast, according to the screenshot of A1111, the `CFG scale` is set to `7.0`, which also results in a slight difference.

Thank you soooooooooooooo much  !!!!!!!! you are my hero!!!!!!!!!!!!!!!!!!!!!!!!!! Can I buy you a cup of coffee? XD

**Comment by takuma104** [comment]
@noskill I believe using `StableDiffusionKDiffusionPipeline` and `lpw_stable_diffusion` at the same time is not compatible. I wrote before about making the A1111 style prompt available for any pipeline, so feel free to use it. I think you can use it by replacing the `StableDiffusionPipeline` part in this example with `StableDiffusionKDiffusionPipeline`.

https://gist.github.com/takuma104/43552b8ec70b63323c57dc9c6fcb9b90

**Comment by thenol** [comment]
> Hi @sanbuphy , In the `generator` argument, we specify the method for generating random numbers used in latent and euler sampler. If you specify it with `torch.manual_seed()`, it will be generated on the CPU. This is the cause of significant differences in the generated images, as it is assumed to be generated on the GPU (cuda) in A1111. By doing as follows, I believe almost the same images will be generated.
> 
> ```python
> generator = torch.Generator(device='cuda').manual_seed(1234)
> ```
> 
> Also, the default value of `guidance_scale` in Diffusers is `7.5`. In contrast, according to the screenshot of A1111, the `CFG scale` is set to `7.0`, which also results in a slight difference.

i run across the same problems although i do like this

**Comment by lionel3** [comment]
I have done many comparisions. The main reason may be the difference of prompt embeddings between webui and diffusers. Check this code https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb for more details.
<img width="786" alt="1040025030sldn0gv3000oipilo" src="https://github.com/huggingface/diffusers/assets/16537531/76395f09-0f8f-453e-90ab-140ed48d7793">

**Comment by lionel3** [comment]
I have done many comparisions. The main reason may be the difference of prompt embeddings between webui and diffusers. Check this code https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb for more details.
<img width="786" alt="1040025030sldn0gv3000oipilo" src="https://github.com/huggingface/diffusers/assets/16537531/76395f09-0f8f-453e-90ab-140ed48d7793">
