### ISSUE TITLE
Conversion of Inpainting CKPT to Diffusers format Results an error 

### ISSUE THREAD

**Issue by satwiksunnam19** [huggingface/diffusers#3254]
Hello @patrickvonplaten, I have been trying to use this https://www.reddit.com/r/StableDiffusion/comments/11bdzsc/how_to_convert_inpanting_ckpt_model_to_diffusers/  methodology proposed here, I have experimented with two models and results in the same error
1. I have used the runwayml stable diffusion inpainting ckpt to convert that to diffusers format, which results in this error 
![image](https://user-images.githubusercontent.com/83942187/234769239-05ff787d-1276-42bc-b1c1-471a6b7c181f.png)
2. I have used a custom inpainting ckpt, which I have used the checkpoint merger from automaticUi, and results in me the same error as above.

Can you say what's the problem causing things in the conversion part and please lemme know ASAP?
Thank You in Advance and Regards,
Satwik Sunnam.

**Comment by sayakpaul** [comment]
Could you post some reproducible snippets so that we can try to identify the bug?

**Comment by satwiksunnam19** [comment]
Hey @sayakpaul this is the code snippet that reproduces the error
Step 1 : https://raw.githubusercontent.com/huggingface/diffusers/8f21a9f0e29cc5e3d139095785d52ff474ebda0e/scripts/convert_original_stable_diffusion_to_diffusers.py, from here you'll get an python file.
Step 2: 
https://raw.githubusercontent.com/runwayml/stable-diffusion/main/configs/stable-diffusion/v1-inpainting-inference.yaml Yaml File 
Step 3: 
!python /content/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path=/root/.cache/huggingface/hub/models--runwayml--stable-diffusion-inpainting/snapshots/caac1048f28756b68042add4670bec6f4ae314f8/sd-v1-5-inpainting.ckpt --scheduler_type=ddim --dump_path=W:/.cache/huggingface/hub/models--runwayml--stable-diffusion-inpainting --original_config_file=v1_inpainting_inference.yaml

Put the corresponding file paths in the above mentioned script and this will gives an error.

**Comment by sayakpaul** [comment]
Thanks. One more question:

`sd-v1-5-inpainting.ckpt` -- where is this coming from?

**Comment by satwiksunnam19** [comment]
you can download that using this codding snippet

! pip install huggingface_hub
from huggingface_hub import hf_hub_download
downloaded_model_path = hf_hub_download(repo_id="runwayml/stable-diffusion-inpainting",
                                                          filename="sd-v1-5-inpainting.ckpt",
                                                         )
print(downloaded_model_path)

set the checkpoint_path= download_model_path

**Comment by sayakpaul** [comment]
Okay thanks! I think we have the means to reproduce this. Now, I would like to ping @patrickvonplaten to know if we support converting inpainting pipelines as I don't have a good handle on this yet.

**Comment by satwiksunnam19** [comment]
Let's see 👀 and find a solution for this

**Comment by patrickvonplaten** [comment]
You can convert an inpainting checkpoint with: https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py and setting https://github.com/huggingface/diffusers/blob/6290668254f421496c968e39d7de4e07e6bc394d/scripts/convert_original_stable_diffusion_to_diffusers.py#L38 to:
```
--num_in_channels 9
```

**Comment by satwiksunnam19** [comment]
same error is reproducing after changing that too @sayakpaul @patrickvonplaten

**Comment by satwiksunnam19** [comment]
@patrickvonplaten the error is solved by correctly mentioning the yaml file 
Thanks

**Comment by sayakpaul** [comment]
Closing this then :) Feel free to re-open.

**Comment by patrickvonplaten** [comment]
Hey @satwiksunnam19,

Could you upload your inpainting CKPT format file to the Hub? I can help you convert it. 

Note that:

> S 2: Convert the model to inpainting model using the A+B-C using automatic 1111 as discussed in this thread (https://www.reddit.com/r/StableDiffusion/comments/zyi24j/how_to_turn_any_model_into_an_inpainting_model/) try to run the model in the automatic 1111 and see the outputs.

is not an official doc / step as advertised by the `diffusers` library. We cannot be aware support all kinds of specific conversions of models. Make the forum: https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63 might actually be a better place for such specific questions

**Comment by satwiksunnam19** [comment]
I'll upload that, but as of now we need a transparent method to convert the inpainting ckpt to the diffusers format,is there any parameters that can be useful in the conversion script to do the good diffusers model.

I'll upload the model in the next 30 minutes and ping you here.

**Comment by satwiksunnam19** [comment]
https://drive.google.com/file/d/10UwWjVhQTS3Gzshmof3W87_AuYSjMfss/view?usp=share_link This is the inpainting ckpt of the model and due to internet issues i'm not able to upload to the hub, please do me know any further steps to be done @patrickvonplaten 

Thanks,
SS

**Comment by patrickvonplaten** [comment]
Hey @satwiksunnam19 could you please upload it to the Hub, I'm having a hard time working on G-Drive
