### ISSUE TITLE
convert_lora_safetensor_to_diffusers OSError: No such device (os error 19)

### ISSUE THREAD

**Issue by sing817** [huggingface/diffusers#3258]
```shell
python scripts/convert_lora_safetensor_to_diffusers.py \
--base_model_path=stabilityai/stable-diffusion-2-1-base \
--checkpoint_path="my_lora_output_pytorch_lora_weights_file" \
--dump_path="./testoutput" \

``` 
get:

File "conda/envs/diffusers/lib/python3.10/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
OSError: No such device (os error 19)

why?

**Comment by sing817** [comment]
--device cpu or--device cuda or --device cuda:0 problem still

**Comment by sayakpaul** [comment]
I would like to try to reproduce this. Could you maybe help with a Colab that reproduces the error?

**Comment by sing817** [comment]
> 
#state_dict = load_file(checkpoint_path)

state_dict = torch.load(checkpoint_path)

and get this:
AttributeError: 'UNet2DConditionModel' object has no attribute 'unet'

**Comment by sing817** [comment]
> 我想嘗試重現這一點。您能否幫助重現錯誤的 Colab？

  warnings.warn(
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /media/mdai/Data_House_3/projects/diffusers/lora_save/convert_lora_safetensor_to_diffusers.py:12 │
│ 6 in <module>                                                                                    │
│                                                                                                  │
│   123 │   lora_prefix_text_encoder = args.lora_prefix_text_encoder                               │
│   124 │   alpha = args.alpha                                                                     │
│   125 │                                                                                          │
│ ❱ 126 │   pipe = convert(base_model_path, checkpoint_path, lora_prefix_unet, lora_prefix_text_   │
│   127 │                                                                                          │
│   128 │   pipe = pipe.to(args.device)                                                            │
│   129 │   pipe.save_pretrained(args.dump_path, safe_serialization=args.to_safetensors)           │
│                                                                                                  │
│ /media/mdai/Data_House_3/projects/diffusers/lora_save/convert_lora_safetensor_to_diffusers.py:32 │
│ in convert                                                                                       │
│                                                                                                  │
│    29 │                                                                                          │
│    30 │                                                                                          │
│    31 │   # load LoRA weight from .safetensors                                                   │
│ ❱  32 │   state_dict = load_file(checkpoint_path)                                                │
│    33 │                                                                                          │
│    34 │   visited = []                                                                           │
│    35                                                                                            │
│                                                                                                  │
│ /media/mdai/Data_House_3/conda/envs/diffusers/lib/python3.10/site-packages/safetensors/torch.py: │
│ 259 in load_file                                                                                 │
│                                                                                                  │
│   256 │   ```                                                                                    │
│   257 │   """                                                                                    │
│   258 │   result = {}                                                                            │
│ ❱ 259 │   with safe_open(filename, framework="pt", device=device) as f:                          │
│   260 │   │   for k in f.keys():                                                                 │
│   261 │   │   │   result[k] = f.get_tensor(k)                                                    │
│   262 │   return result                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by sayakpaul** [comment]
What is your `checkpoint_path`? It doesn't seem like the complete snippet to me.

**Comment by fangcao1314** [comment]
最后解决了吗

**Comment by yzeng58** [comment]
Same here

**Comment by zhangxs131** [comment]
怎么解，是环境哪里的问题吗，卸载了几个重装还是，

**Comment by YoucanBaby** [comment]
same question

**Comment by lonngxiang** [comment]
same

**Comment by asomoza** [comment]
For everyone that keeps adding the "same" comment here (don't really know what the other language says). 

This is an old issue and a lot has changed from then, specially with LoRAs. 

Also the main reason this wasn't answered was because the person that asked the initial question didn't provide any useful information, the device error it's almost always associated to a bad environment because PyTorch couldn't find a device to use. So probably it was fixed with a reinstall.

So instead of adding the "same", if you want a solution, it would be better if you open a new issue with the details we need:

- minimal code to reproduce.
- trace of the error.
- details on your environment.

Until someone does this, you can keep posting the "same"  and we won't be able to help.

**Comment by lonngxiang** [comment]
> For everyone that keeps adding the "same" comment here (don't really know what the other language says).
> 
> This is an old issue and a lot has changed from then, specially with LoRAs.
> 
> Also the main reason this wasn't answered was because the person that asked the initial question didn't provide any useful information, the device error it's almost always associated to a bad environment because PyTorch couldn't find a device to use. So probably it was fixed with a reinstall.
> 
> So instead of adding the "same", if you want a solution, it would be better if you open a new issue with the details we need:
> 
> * minimal code to reproduce.
> * trace of the error.
> * details on your environment.
> 
> Until someone does this, you can keep posting the "same" and we won't be able to help.

torch                     2.3.1   
safetensors 0.4.3

**Comment by asomoza** [comment]
Maybe there's a language barrier here, but I repeat what we need to be able to help.

Open a new issue with the details we need:

- minimal code to reproduce.
- trace of the error.
- details on your environment.

**Comment by lonngxiang** [comment]
My error is mainly the model address is wrong

**Comment by asomoza** [comment]
I don't think I understand what you mean with that. The literal meaning of that is that you're using a wrong path and the obvious fix to that is that yo use the correct one.

**Comment by lonngxiang** [comment]
> I don't think I understand what you mean with that. The literal meaning of that is that you're using a wrong path and the obvious fix to that is that yo use the correct one.

That's right. That's what caused my mistake

**Comment by lonngxiang** [comment]
You may not notice, the model download saved the same name folder, resulting in an error

**Comment by asomoza** [comment]
oh ok, so I can assume you fixed your problem.

**Comment by jiahuanluo** [comment]
Maybe the same problem[here](https://github.com/huggingface/transformers/issues/25179)
