### ISSUE TITLE
Revisit Conversion Space

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#3261]
- [ ] No way to specify a model if the user does not have any models in their account: https://huggingface.co/spaces/diffusers/sd-to-diffusers/discussions/7#644a3407f3ff2cb84eb4147d
- [ ] Make it compatible with 2.1 (not base) models.
- [ ] Make it clearer how users can specify arbitrary models (hard to see "Other" when the user has many unrelated models in their account).
- [ ] Maybe try to make it simpler?

**Comment by patrickvonplaten** [comment]
I just updated the whole space: https://huggingface.co/spaces/diffusers/sd-to-diffusers
and tested it on the following repos:

- https://huggingface.co/patrickvonplaten/v1-5
- https://huggingface.co/patrickvonplaten/v2-1
- https://huggingface.co/patrickvonplaten/v2-1-base
- https://huggingface.co/patrickvonplaten/v2-0

I don't think it works for controlnet models yet, but we could easily leverage: https://github.com/huggingface/diffusers/blob/eade4308dabc7f7ba75eab508d386b66b3764513/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L1331

Feel free to adapt for ControlNet @pcuenca :-)

**Comment by pcuenca** [comment]
@patrickvonplaten made a PR to the Space in case you or @williamberman would like to take a quick look (I haven't converted many controlnet models). Otherwise I'll just merge in the morning.
