### ISSUE TITLE
DeepFloyd/IF-I-XL-v1.0 404 error

### ISSUE THREAD

**Issue by rupeshs** [huggingface/diffusers#3263]
https://huggingface.co/DeepFloyd/IF-I-XL-v1.0
![image](https://user-images.githubusercontent.com/3255994/234880480-af92946b-2e74-4fdb-8ea8-237cd14f2bac.png)

**Comment by apolinario** [comment]
The weights have not been released yet. When deepfloyd releases it, they should live on this URL

**Comment by williamberman** [comment]
+1 to what poli said! Appreciate your patience :)
