### ISSUE TITLE
Is there any way to enhance the prompt  rules for Diffuser?

### ISSUE THREAD

**Issue by sanbuphy** [huggingface/diffusers#3269]
Hi, I was wondering if there is a way to improve the prompt rules for Diffuser in order to generate embedding vectors similar to those of A111 web UI?

**Comment by sayakpaul** [comment]
Could you maybe give a more elaborate example of what you're trying to achieve?

We have a section on better prompt engineering in our docs that might be useful here: 
https://huggingface.co/docs/diffusers/stable_diffusion#better-prompt-engineering

**Comment by sanbuphy** [comment]
> Could you maybe give a more elaborate example of what you're trying to achieve?
> 
> We have a section on better prompt engineering in our docs that might be useful here: https://huggingface.co/docs/diffusers/stable_diffusion#better-prompt-engineering

Hi!  I want something like this: 
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/examples/community#automatic1111-webui-stable-diffusion

**Comment by sayakpaul** [comment]
Do you mean prompt weighting? 

If so, we have a doc here: https://huggingface.co/docs/diffusers/main/en/using-diffusers/weighted_prompts

But not sure if that is what you're looking for.

**Comment by sanbuphy** [comment]
> Do you mean prompt weighting?
> 
> If so, we have a doc here: https://huggingface.co/docs/diffusers/main/en/using-diffusers/weighted_prompts
> 
> But not sure if that is what you're looking for.

Yes, I have seen that before. However, it is not consistent with the results from the web UI. I am looking for a way to make them consistent, by using the prompt weighting method available in the web UI

**Comment by takuma104** [comment]
Hi @sanbuphy , I think using the Community's LPW Pipeline https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py would be the quickest way to adopt the A1111 compatible prompt format.

I personally created this code by copying the old A1111 code, and it can be used with such as ControlNet and other pipelines as well. Please feel free to use it if you'd like.
https://gist.github.com/takuma104/43552b8ec70b63323c57dc9c6fcb9b90

**Comment by sanbuphy** [comment]
> Hi @sanbuphy , I think using the Community's LPW Pipeline https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py would be the quickest way to adopt the A1111 compatible prompt format.
> 
> I personally created the following code by copying the old A1111 code, and it can be used with such as ControlNet and other pipelines as well. Please feel free to use it if you'd like. https://gist.github.com/takuma104/43552b8ec70b63323c57dc9c6fcb9b90

Thank you very much for your help! I will try to come to a conclusion.
