### ISSUE TITLE
Is there a way to run train_text_to_image.py with training text_encoder?

### ISSUE THREAD

**Issue by DogsHeadZ** [huggingface/diffusers#3270]

**Comment by DogsHeadZ** [comment]
For finetuning, will results be better with training traing text_encoder ?

**Comment by sayakpaul** [comment]
You can refer to this script that shows how to additionally fine-tune the text encoder: https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py

**Comment by sayakpaul** [comment]
Closing this issue since we want to keep the `train_text_to_image.py` as is for now and let the users customize them as per their needs (that being one of the [goals of our training scripts](https://huggingface.co/docs/diffusers/training/overview)).
