### ISSUE TITLE
Deepfloyd aspect ratios

### ISSUE THREAD

**Issue by dblunk88** [huggingface/diffusers#3291]
**Is your feature request related to a problem? Please describe.**
I saw that the pre-release cherry picks had various aspect ratios. As far as I know, the current implementation only has a standard aspect ratio

**Describe the solution you'd like**
The ability to specify resolutions for both stage 1 and 2

**Comment by dblunk88** [comment]
Disregard, I found it :D

**Comment by dblunk88** [comment]
nevermind. height & width works for stage 1, but not stage 2

**Comment by AmericanPresidentJimmyCarter** [comment]
Dup of https://github.com/huggingface/diffusers/issues/3289

**Comment by stpg06** [comment]
I tried to do it Stage 1 only with no safety checker or watermarker and when I specified my usual 512 square resolution the images were not generating properly, just noisy gradients. When I remove the height and width the image outputs correctly  but it's tiny. This is not optimal though I can see the premise. There's just not enough space to generate a good image with such small dimensions,  while the upscaler works it is a little ambitious, kind of an overkill with such a small pic to start with. Did somebody say they were able to get better resolution without the upscaler? If so, I would like to know  what needs to be done to accomplish that.

**Comment by AmericanPresidentJimmyCarter** [comment]
> I tried to do it Stage 1 only with no safety checker or watermarker and when I specified my usual 512 square resolution the images were not generating properly, just noisy gradients. When I remove the height and width the image outputs correctly but it's tiny. This is not optimal though I can see the premise. There's just not enough space to generate a good image with such small dimensions, while the upscaler works it is a little ambitious, kind of an overkill with such a small pic to start with. Did somebody say they were able to get better resolution without the upscaler? If so, I would like to know what needs to be done to accomplish that.

The first UNet model is trained in 64x64, it is not meant to be used without an upscaler.

See the documentation: https://huggingface.co/docs/diffusers/api/pipelines/if

**Comment by johnowhitaker** [comment]
Stage 1 accepts width and heigh arguments - for eg, I may want to do width=96 to get a landscape image (height=64). 
Stage 2 doesn't let you do different aspect ratios though - the width and height are set to the default (https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/deepfloyd_if/pipeline_if_superresolution.py#LL809C9-L810C45) and can't be changed without editing the code.

**Comment by stpg06** [comment]
> > I tried to do it Stage 1 only with no safety checker or watermarker and when I specified my usual 512 square resolution the images were not generating properly, just noisy gradients. When I remove the height and width the image outputs correctly but it's tiny. This is not optimal though I can see the premise. There's just not enough space to generate a good image with such small dimensions, while the upscaler works it is a little ambitious, kind of an overkill with such a small pic to start with. Did somebody say they were able to get better resolution without the upscaler? If so, I would like to know what needs to be done to accomplish that.
> 
> The first UNet model is trained in 64x64, it is not meant to be used without an upscaler.
> 
> See the documentation: https://huggingface.co/docs/diffusers/api/pipelines/if

Yeah I get the part, but with Stable Diffusion you are always able to generate an image well above 512 even on V1 and base models trained on that size. So if I am correct , the XL version model can go to 256? I only tried "IF-I-L-v1.0" since I figured XL wouldn't work on colab without using premium GPU. The model will prob be better for me if I can dreambooth it so as to train it on my own images scaled to that size.  The model is great for photorealism and certain things but most of my images are impressionistic, I find the style has good vectors, but when I upscale those, it doesn't always output too well.

**Comment by StanleyPain** [comment]
> I tried to do it Stage 1 only with no safety checker or watermarker and when I specified my usual 512 square resolution the images were not generating properly, just noisy gradients. When I remove the height and width the image outputs correctly but it's tiny. This is not optimal though I can see the premise. There's just not enough space to generate a good image with such small dimensions, while the upscaler works it is a little ambitious, kind of an overkill with such a small pic to start with. Did somebody say they were able to get better resolution without the upscaler? If so, I would like to know what needs to be done to accomplish that.

How did you remove the safety checker? I've been trying to figure that out for a bit.

**Comment by AmericanPresidentJimmyCarter** [comment]
> How did you remove the safety checker? I've been trying to figure that out for a bit.

```py
        stage_1 = IFPipeline.from_pretrained(
            "DeepFloyd/IF-I-XL-v1.0",
        ).to('cpu')
        stage_1.enable_model_cpu_offload()
        stage_1.safety_checker = dummy_checker
        stage_1.watermarker = None
```
