### ISSUE TITLE
Adding input pertubation

### ISSUE THREAD

**Issue by isamu-isozaki** [huggingface/diffusers#3293]
Input perturbation is a very simple change proposed [here](https://arxiv.org/abs/2301.11706) where we add noise during training to make the trainer robust to the error accumulation during inference. This got state-of-the-art on the celeb dataset as can be seen [here](https://paperswithcode.com/sota/image-generation-on-celeba-64x64)

I made a pr [here](https://github.com/huggingface/diffusers/pull/3292)

**Comment by xiaohu2015** [comment]
@isamu-isozaki Do this trick related to noise offset?

**Comment by isamu-isozaki** [comment]
@isamu-isozaki Good question! And very similar implementation but the idea/what they do is very different.

Noise offset adds another normal distribution to reduce the low-frequency noise to make stable diffusion able to generate images that it originally can't. Implementation-wise this is
```
noise += args.noise_offset * torch.randn(
    (latents.shape[0], latents.shape[1], 1, 1), device=latents.device
)
....
noisy_latents = noise_scheduler.add_noise(latents, noise, timesteps)
....
loss = F.mse_loss(model_pred.float(), noise.float(), reduction="mean")
```


For input perturbation, the idea is to make the model's training robust to an error during inference(some random noise at x_t). To do this we do
```
new_noise = noise + args.input_pretubation*torch.randn_like(noise)
...
noisy_latents = noise_scheduler.add_noise(latents, new_noise, timesteps)
...
loss = F.mse_loss(model_pred.float(), noise.float(), reduction="mean")
```
so, in input perturbation, the objective is to ignore the new noise added while for offset noise, it's included for more info.

Let me know if that makes sense!

**Comment by xiaohu2015** [comment]
@isamu-isozaki another work is https://arxiv.org/abs/2305.08891

**Comment by isamu-isozaki** [comment]
@xiaohu2015 ohh I was planning to read that paper. Thanks for the send!

**Comment by isamu-isozaki** [comment]
Closing since merged
