### ISSUE TITLE
[FR] Multiclass Finetuning with Dreambooth 

### ISSUE THREAD

**Issue by mauricio-repetto** [huggingface/diffusers#3309]
**Is your feature request related to a problem? Please describe.**

Hi! first of all thanks for such a great tool and all your hard work. Well at this moment I'm working with a partner @fededemo on a thesis related to data augmentation using synthetic images with generative models. We were fintuning things with dreambooth using some scripts from [this repo](https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth) which allows us to finetune two classes simultaneously by using a parameter call concept_list I would like if possilbe to add this kind of capabilty to the official scripts.

The concept list work this way 
concepts_list = [
    {
        "instance_prompt":      "photo of zwx dog",
        "class_prompt":         "photo of a dog",
        "instance_data_dir":    "/content/data/zwx",
        "class_data_dir":       "/content/data/dog"
    },
     {
        "instance_prompt":      "photo of ukj person",
         "class_prompt":         "photo of a person",
         "instance_data_dir":    "/content/data/ukj",
        "class_data_dir":       "/content/data/person"
     }
] 

NOTE: In particular something that this script didn't take into account was to also consider  `sample_batch_size` and `save_sample_prompt` within this dictionary for the additional classes since eventually someone would want to save different prompts and number of images for each class.

**Describe the solution you'd like**

We would like to see the above implemented, why? well we would like to see if the DM is capable of give better attention to the differences between objects by finetuning at the same time two different concepts that belong to the same class, for instance _an image of a **pneumonia** xray_ and _an image of a **penoumoconiosis** xray_

**Describe alternatives you've considered**

Use the alternative scripts that we have being using so far, with the drawback that there aren't official scripts :'(

**Additional context**

-

**Comment by patrickvonplaten** [comment]
Could we maybe move this into the `research_projects` folder: https://github.com/huggingface/diffusers/tree/main/examples/research_projects and be maintained by you? :-)

**Comment by mauricio-repetto** [comment]
Hi @patrickvonplaten I can only promess that I'll try :-) Thanks in advance for always replying back

**Comment by mauricio-repetto** [comment]
Hello @patrickvonplaten, we spent some time on this and finally we have implemented it in the following pr: https://github.com/huggingface/diffusers/pull/3807
