### ISSUE TITLE
How can i delete lastest output from pipe command?

### ISSUE THREAD

**Issue by Mudereded401** [huggingface/diffusers#3324]
Hello! I'm writing a program in Colab to use SD without any webui. I have most of it done but i want to delete lastest output made from "pipe(prompt, etc)", It exactly shows a progress bar that i can't handle like a normal Widget from Ipywidgets (I mean, replacing that progress bar instead of generating another one below)

![image](https://user-images.githubusercontent.com/65833857/235903933-8e3f8ba2-af94-449e-a2e9-3c863ef2e7fa.png)

  I would like to know if there's any way to take control of that widget or just deleting it to show a new pipe() progress bar above it.

  The only solution i have done is clearing everything with clear_output(), but it flicks when re-drawing everything with Ipywidgets

**Comment by mimhle** [comment]
You can turn off the progress bar by calling: `pipe.set_progress_bar_config(disable=True) `
