### ISSUE TITLE
Could we make `BaseOutput` picklable?

### ISSUE THREAD

**Issue by larme** [huggingface/diffusers#3327]
Currently we can pickle but cannot recover from the pickled bytes:

```
In [40]: bs =pickle.dumps(output)

In [41]: pickle.loads(bs)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: IFPipelineOutput.__init__() missing 3 required positional arguments: 'images', 'nsfw_detected', and 'watermark_detected'
```

The motive is that we want to pass outputs of pipelines between processes or even machines. We can use `to_tuple` but user will need to know the order of different outputs' keys to use the returned tuples.

System Info

- diffusers version: 0.16.1
- Platform: debian 11
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0 (True)
- Using distributed or parallel set-up in script?: True

**Comment by patrickvonplaten** [comment]
What is the use case here exactly ? Can you just use tuples  by adding `return_dict=False` to the forward pass of IF?

**Comment by larme** [comment]
Hi @patrickvonplaten , I’m improving support of diffusers in BentoML. We need to pickle the `BaseOutput` so that we can pass the output around machines on a network using [runner architecture](https://docs.bentoml.org/en/latest/concepts/runner.html). A practical usage examples is that we can distribute each stage of IF’s pipeline to its own pods/machines and scale them independetly (for example more pods for stage1 pipeline because it take more time to inference).

We want our integration works for every pipeline that is a subclass of `diffusers.DiffusionPipeline`, so we cannot pass `return_dict=False` because not every pipeline implement this argument.

**Comment by patrickvonplaten** [comment]
I see! IMO we should try to add `return_dict=False` to all missing pipelines as a first fix. Otherwise, any idea on how we could make `BaseOutput` picklable?

**Comment by baijumeswani** [comment]
Can something like this be done? https://github.com/huggingface/transformers/pull/8989

The problem is that the `BaseOutput` is not copyable (mostly because of this problem: https://github.com/python/cpython/issues/105736).

Probably the easiest fix is to make the dataclass members not required while constructing the class. This should make the class copyable at least.
