### ISSUE TITLE
Can inpaint load t2i's models? Or do I have to load a specific inpaint model

### ISSUE THREAD

**Issue by dingjingzhen** [huggingface/diffusers#3329]
Can inpaint load t2i's models? Or do I have to load a specific inpaint model

**Comment by alexblattner** [comment]
yes you do. I have an alternative that doesn't need it though (it is less precise, but it works) that I am working on right now. Would you like to use it?

**Comment by joeyism** [comment]
Hi @alexblattner that's something that i'd be interested in. Can you share that please?

**Comment by alexblattner** [comment]
sure @joeyism it isn't in the community pipelines, it's custom made so there might be issues. Also, it can be further modified for applying masks just like in inpainting.

here's the pipeline: 
[Pipeline.txt](https://github.com/huggingface/diffusers/files/11405672/Pipeline.txt)

here's how you use it:
pipe = LatentCouplesPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16,safety_checker=None,requires_safety_checker=False)
pipe = pipe.to("cuda")
compel_proc = Compel(tokenizer=pipe.tokenizer, text_encoder=pipe.text_encoder)
prompt=["a beautiful park", "a dog++ in a beautiful park","a cat+ playing with a (ball)1.5 in a beautiful park"]
negative_prompt=["(low quality, worst quality)1.4", "(low quality, worst quality)1.4","(low quality, worst quality)1.4"]
promptE=[]
for i in prompt:
    promptE.append(compel_proc(i))
negative_promptE=[]
for i in negative_prompt:
    negative_promptE.append(compel_proc(i))
generator = torch.manual_seed(1)
pos=["0:0-512:512","80:80-256:512","296:80-512:512"] //those are in pixels x1:y1-x2:y2 is the format. These are assuming the pic is 512px
mix_val=[0.1, 0.9, 0.9]
image = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    pos=pos,
    mix_val=mix_val,
    num_inference_steps=20,
    generator=generator,
).images[0]


let me know if you have issues with the pipeline
