### ISSUE TITLE
canot import StableDiffusionSafetyChecker from diffusers.pipelines.stable_diffusion 

### ISSUE THREAD

**Issue by saladinlorenz** [huggingface/diffusers#3332]
### Describe the bug

  File "D:\generate\fonc\tammy\tammy-main\tammy-main\tammy\stable_diffusion.py", line 15, in <module>
    from diffusers.pipelines.stable_diffusion import StableDiffusionSafetyChecker
ImportError: cannot import name 'StableDiffusionSafetyChecker' from 'diffusers.pipelines.stable_diffusion' (C:\Users\salad\Downloads\diffusers-main\diffusers-main\src\diffusers\pipelines\stable_diffusion\__init__.py)

### Reproduction

import os
import subprocess
from typing import List, Optional, Union

import numpy as np
import torch
from diffusers import (
    AutoencoderKL,
    PNDMScheduler,
    StableDiffusionImg2ImgPipeline,
    StableDiffusionPipeline,
    UNet2DConditionModel,
)
from diffusers.pipeline_utils import DiffusionPipeline
from diffusers.pipelines.stable_diffusion import StableDiffusionSafetyChecker

from PIL import Image
from transformers import CLIPFeatureExtractor, CLIPTextModel, CLIPTokenizer

from tammy.utils import download_from_google_drive

### System Info

# packages in environment at C:\Users\salad\anaconda3\envs\tammy:
#
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
accelerate                0.18.0                   pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cachetools                5.3.0                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.15.1           py39h0878f49_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
clip-by-openai            1.1                      pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cryptography              3.4.8            py39h7bc7c5c_1    conda-forge
cudatoolkit               11.0.221             h74a9793_0
diffusers                 0.16.1             pyhd8ed1ab_0    conda-forge
filelock                  3.12.0             pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               ha860e81_0
fsspec                    2023.4.0           pyh1a96a4e_0    conda-forge
ftfy                      6.1.1                    pypi_0    pypi
google-auth               2.17.3                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.54.0                   pypi_0    pypi
huggingface_hub           0.14.1             pyhd8ed1ab_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
intel-openmp              2023.1.0         h59b6b97_46319
jpeg                      9b                   hb83a4c4_2
lerc                      3.0                  hd77b12b_0
libdeflate                1.17                 h2bbff1b_0
libpng                    1.6.39               h8cc25b3_0
libtiff                   4.5.0                h8a3f274_0
libuv                     1.44.2               h2bbff1b_0
libwebp                   1.2.4                h2bbff1b_0
libwebp-base              1.2.4                h2bbff1b_1
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
mkl                       2023.1.0         h8bd8f75_46356
mkl-service               2.4.0            py39h2bbff1b_1
mkl_fft                   1.3.6            py39hf11a4ad_1
mkl_random                1.2.2            py39hf11a4ad_1
ninja                     1.10.2               haa95532_5
ninja-base                1.10.2               h6d14046_5
numpy                     1.24.3           py39h79a8e48_1
numpy-base                1.24.3           py39h8a87ada_1
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pillow                    9.3.0            py39hdc2b20a_1
pip                       23.0.1           py39haa95532_0
protobuf                  4.22.4                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.16               h6244533_2
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.7.1           py3.9_cuda110_cudnn8_0    pytorch
pyyaml                    6.0              py39hb82d6ee_4    conda-forge
regex                     2023.5.5                 pypi_0    pypi
requests                  2.30.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
setuptools                66.0.0           py39haa95532_0
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.41.2               h2bbff1b_0
tbb                       2021.8.0             h59b6b97_0
tensorboard               2.12.3                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
torchvision               0.8.2                py39_cu110    pytorch
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typing-extensions         4.5.0            py39haa95532_0
typing_extensions         4.5.0            py39haa95532_0
tzdata                    2023c                h04d1e81_0
urllib3                   2.0.2                    pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.6                    pypi_0    pypi
werkzeug                  2.3.3                    pypi_0    pypi
wheel                     0.38.4           py39haa95532_0
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xz                        5.4.2                h8cc25b3_0
yaml                      0.2.5                h8ffe710_2    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0

**Comment by stevhliu** [comment]
Hi, can you try:

```py
from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker
```

**Comment by stevhliu** [comment]
Thanks, would you like to open a PR on the model card and modify the [How to Get Started with the Model](https://huggingface.co/CompVis/stable-diffusion-safety-checker#how-to-get-started-with-the-model) section with the correct code?

**Comment by woctezuma** [comment]
Done! https://huggingface.co/CompVis/stable-diffusion-safety-checker/discussions/45
