### ISSUE TITLE
Importing diffusers takes >10 seconds

### ISSUE THREAD

**Issue by Anirudh-Scale** [huggingface/diffusers#3338]
### Describe the bug

Importing the `diffusers` package takes a long time in a Docker container (~13-15s). I've provided the Dockerfile, the test script I used to measure the import time, the corresponding output from the script, as well as exact package versions. 

### Reproduction

Dockerfile:
```
FROM nvcr.io/nvidia/pytorch:22.08-py3

ARG CUDA_VERSION=11.7
ARG TORCH_CUDA_ARCH_LIST=8.0
ARG PYTHON_VERSION=3.8.13

RUN apt-get -yq update && apt-get install -y \
  dumb-init \
  libcurl4-openssl-dev \
  libssl-dev \
  python3-dev \
  gcc \
  libsm6 \
  libxrender-dev \
  libxext6 \
  && rm -rf /var/lib/apt/lists/*

##
## Environment variables
##
ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true

RUN --mount=type=secret,id=codeartifact-pip-conf,target=/opt/conda/pip.conf pip install diffusers boto3 transformers safetensors accelerate
```

After building and exec'ing into the Docker container (via `/bin/bash`), I run the following script:

```
import time

start_import_time = time.time()
import diffusers
print(f"Importing took {time.time() - start_import_time}s")
```

This gives the output: 
```
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Importing took 13.357857942581177s
```

### System Info

Output of `diffusers-cli env`:

- `diffusers` version: 0.16.1
- Platform: Linux-5.4.0-1101-aws-x86_64-with-glibc2.10
- Python version: 3.8.13
- PyTorch version (GPU?): 1.13.0a0+d321be6 (False)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
Hey @Anirudh-Scale, 

Thanks for the issue! It's true that importing all of `diffusers` has gotten a bit slow. 
We really don't recommend to run:
```py
import diffusers
```

But to instead do

```py
from diffusers import DiffusionPipeline
``` 
(which takes 0.0005 seconds)

We could speed up the overall import though by making everything lazy as is done in `transformers`: https://github.com/huggingface/transformers/blob/312b104ff65514736c0475814fec19e47425b0b5/src/transformers/__init__.py#L50

I'd say that this is not needed yet, but I think we could consider it soon (@sayakpaul )

**Comment by harish-kamath** [comment]
This does not work for me. Running on `diffusers==0.16.1`, , I get the following:

`start = time.time(); from diffusers import DiffusionPipeline; print(f"{time.time()-start:.3f}s")`
Returns
`8.261s`

**Comment by harish-kamath** [comment]
Bump on this @sayakpaul. Still seems to take forever, even with specific imports.

**Comment by patrickvonplaten** [comment]
Turning this into an enhancement. We could add lazy import logic to `diffusers` -> this would def speed up overall imports by quite a bit

**Comment by chuck-ma** [comment]
Any progress here ?

**Comment by sayakpaul** [comment]
We landed lazy imports many months back. It should have improved a bit.
