### ISSUE TITLE
Support for 'scale' parameter when xformers is used for lora models

### ISSUE THREAD

**Issue by abhijitpal1247** [huggingface/diffusers#3348]
### Describe the bug

Facing the following error while using xformers attention in case of a lora model and making use of the inference parameter cross_attention_kwargs = {'scale':0.5}. `TypeError: XFormersAttnProcessor.__call__() got an unexpected keyword argument 'scale'`

### Reproduction

pipe is an instance of StableDiffusionPipeline class 
pipe.to(device)
pipe.load_attn_procs(lora_path)
pipe.enable_xformers_memory_efficient_attention()
image = pipe(prompt=prompt, cross_attention_kwargs={"scale":0.5}).images[0]

### Logs

```shell
TypeError: XFormersAttnProcessor.__call__() got an unexpected keyword argument 'scale'
```

### System Info

- `diffusers` version: 0.16.1
- Platform: Linux-4.14.301-224.520.amzn2.x86_64-x86_64-with-glibc2.26
- Python version: 3.10.9
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.27.3
- Accelerate version: 0.18.0
- xFormers version: 0.0.17rc481
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
Hey @abhijitpal1247,

Could you please provide a fully reproducible code snippet? I cannot run:

```py
pipe.to(device)
pipe.load_attn_procs(lora_path)
pipe.enable_xformers_memory_efficient_attention()
image = pipe(prompt=prompt, cross_attention_kwargs={"scale":0.5}).images[0]
```

Sadly

**Comment by abhijitpal1247** [comment]
@patrickvonplaten 
Here lora_weights_path can be replaced with any finetuned lora weights. Please let mw know if anything else is required

```
pipe = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
pipe.to(torch.device("cuda"), torch.float16)
pipe.load_attn_procs(lora_weights_path)
pipe.enable_xformers_memory_efficient_attention()
image = pipe(prompt="A Happy Child", cross_attention_kwargs={"scale":0.5}).images[0]
```

**Comment by pcuenca** [comment]
Hi @abhijitpal1247, I believe the ultimate problem is that LoRA is incompatible with xFormers because both implement their own custom attention processors, and only one of them can be active at a single time.

`scale` is a parameter understood by the LoRA processor, but the xFormers one does not know how to deal with it. When you enable xFormers after loading lora, you are effectively disabling LoRA if I understand it right.

**Comment by abhijitpal1247** [comment]
@pcuenca in v0.13.1 it was possible to do so..
Also we have a class LoRAXFormersCrossAttnProcessor, which had support for scale parameter in v0.13.1

**Comment by pcuenca** [comment]
Hi @abhijitpal1247, you are right, sorry for the confusion.

However, I could run the following code successfully in both diffusers `0.13.1` and the current `main` branch:

```Python
import torch
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler
from huggingface_hub import model_info

# LoRA weights ~3 MB
model_path = "pcuenq/pokemon-lora"

info = model_info(model_path)
model_base = info.cardData["base_model"]
pipe = StableDiffusionPipeline.from_pretrained(model_base, torch_dtype=torch.float16)
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)

pipe.unet.load_attn_procs(model_path)
pipe.enable_xformers_memory_efficient_attention()

pipe.to("cuda")

image = pipe("Green pokemon with menacing face", cross_attention_kwargs={"scale":0.5}, num_inference_steps=25).images[0]
image.save("green_pokemon.png")
```

The following snippet (similar to yours) also works in `main` and `0.16.1`:

```Python
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
pipe.to(torch.device("cuda"), torch.float16)
pipe.load_lora_weights("pcuenq/pokemon-lora")
pipe.enable_xformers_memory_efficient_attention()
image = pipe(prompt="Blue pokemon looking happy", cross_attention_kwargs={"scale":0.5}).images[0]
image.save("blue_pokemon.png")
```

Is it not working in your case?

**Comment by pcuenca** [comment]
@patrickvonplaten Not sure what's the failing use case, it seems to be working for me when using the previous snippets:

```
type(next(iter(pipe.unet.attn_processors.values())))
<class 'diffusers.models.attention_processor.LoRAXFormersAttnProcessor'>
```

**Comment by abhijitpal1247** [comment]
@pcuenca Sorry, for not realizing it earlier, I have made a very silly mistake..
I have used `pipe.load_attn_procs(lora_weights_path)` instead of `pipe.unet.load_attn_procs(lora_weights_path)`. With this change the code snippet is working.

**Comment by sayakpaul** [comment]
You should be able to also use :) 

```py
pipe.load_lora_weights(lora_weights_path)
```

**Comment by pcuenca** [comment]
Thanks @abhijitpal1247, and sorry for my confusion when first going through this issue!

I'd maybe recommend you use the new API: `pipe.load_lora_weights` :)
