### ISSUE TITLE
How to apply multi-vector textureal inversion embeds

### ISSUE THREAD

**Issue by haowang1013** [huggingface/diffusers#3352]
### Describe the bug

When using the official textural inversion [training script](https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion.py) with multi-vector, the output of the training is in the form of
```
{
 placeholder_token: learned_embeds
}
```
`learned_embeds` is a [collection](https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion.py#L159C4-L167) of the embeds for both the placeholder token and the additional tokens created by the training script.

When loading `learned_embeds` into the text encoded it cannot be loaded directly as the shape doesn't match. The way I see it only the following could work:
1. Only load learned_embeds[0], which defeats the purpose of multi-vector training in the first place.
2. Reconstruct the additional tokens as placeholder_token_{N} and apply the embeds accordingly.
3. Apply the average of `learned_embeds` for the placeholderr token.

It seems like option 2 is the most logical one as that's how the model works during the training. If this is the intended usage then why not save the additional tokens in the state dict as well?

Thanks

### Reproduction

N/A

### System Info

diffusers 0.16.1

**Comment by patrickvonplaten** [comment]
Hey @haowang1013,

Thanks for the issue. We want to make sure that the serialization format for textual inversion always stays the same no matter whether it's multi or single vector. If we save `<*>` do we really need to save `<*>_1` and `<*>_2` as well ? What would be the advantage of doing so?

**Comment by haowang1013** [comment]
> 

Hi,

IMO, as it stands now the format is already **not** backward compatible. For instance my code (which is adapted) from [stable_conceptualizer_inference.ipynb](https://github.com/huggingface/notebooks/blob/main/diffusers/stable_conceptualizer_inference.ipynb) expects the state dict to be { [token]: [embeds] }, not { token: [embeds] } and it always picks the first token and applies the corresponding embeds.

Saving embeds per token is actually backward compatible because these old code can continue to only care about the first token in the list (which is the "main" placeholder token), and adapts to multi-vector later.

The core of the problem is that there's no way to apply the multi-vector embeds to the same token in the text encoder. If you ask the user to reconstruct the additional tokens then they suddenly need to care about how it's constructed in the training script:
```
for i in range(1, args.num_vectors):
    additional_tokens.append(f"{args.placeholder_token}_{i}")
```

IMO, this is fragile and unnecessary.

**Comment by haowang1013** [comment]
BTW I found some relevant code in [load_textual_inversion](https://github.com/huggingface/diffusers/blob/main/src/diffusers/loaders.py#L650-L665), if the user is expected to call this function as opposed to implement his own loading logic then I guess the problem as not as bad. In that case the notebook probably needs updating to reflect the latest best practice.

**Comment by patrickvonplaten** [comment]
We should indeed update the textual inversion google colab, thanks for the heads-up!

**Comment by haowang1013** [comment]
Thanks for the update, will close this now :)
