### ISSUE TITLE
How to remove lora after loading it?

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#3358]
The title pretty much. I am trying to load and unload inside the denoising loop to apply the loras to specific parts of the image only

**Comment by pcuenca** [comment]
Hi @alexblattner, you could try `pipe.unet.set_default_attn_processor()`, would that work for your use case?

**Comment by alexblattner** [comment]
I'll try that, but I need to fix a lot of other bugs first. thanks @pcuenca

**Comment by pcuenca** [comment]
Sure :) In that case I'll be closing this issue, feel free to reopen if needed when you try it out :)

**Comment by alexblattner** [comment]
hello @pcuenca , thanks for doing your best to help. I decided going for an implementation that uses this: https://gist.github.com/takuma104/e38d683d72b1e448b8d9b3835f7cfa44 instead
