### ISSUE TITLE
scheduler leaky abstractions in pipelines

### ISSUE THREAD

**Issue by keturn** [huggingface/diffusers#336]
Excited by the opportunities that Stable Diffusion has made for use with consumer hardware, I've started working with the code. I was looking to get an idea of what I'd need to do for something like #277 and studying the StableDiffusionPipeline class.

I'm concerned by the use of ` isinstance(self.scheduler, LMSDiscreteScheduler)`. If you can't implement a new Scheduler without meddling with the internal implementation of the Pipeline, that points to some breakdown in the API design. We don't want growing `if isintance` trees that grow with each New Scheduler PR.

It also introduces an ordering dependency between components that weren't otherwise entangled: https://github.com/huggingface/diffusers/blob/e49dd03d2de347caf5f18d04657500412f57103b/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L120-L124

It wasn't obvious to me at first glance, but `scheduler.set_timesteps` modifies `scheduler.sigmas`. So now when working with that code we have to remember that we have to do that scheduler initialization _before_ we finish preparing the initial latents, whereas those were independent operations before.

Another worrying comment is this: https://github.com/huggingface/diffusers/blob/e49dd03d2de347caf5f18d04657500412f57103b/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L126-L130

If "not all schedulers share the same signature," it's much harder to make and use Schedulers.  

## Suggestions

LMSDiscreteScheduler's `step` function seems to want the step number instead of the time. Options:

1. Change the signature of `Scheduler.step` to always include the index as well as the time. (It's readily available and cheap to have on the stack.)
2. Since LMS is linear (right there in the name!), could it take the usual `timestep` value and easily convert it back to its index value?

For DDIMScheduler's extra `eta` parameter:

The `**kwargs` on `StableDiffusionPipeline.__call__` seems to be unused, and `eta` seems to be passed straight through to `scheduler.step` with no other interaction. We could take `eta` out of the formal parameter list and rename `kwargs` to `extra_step_kwargs`.

I haven't yet looked at other uses of Scheduler outside of this one pipeline, but those are my initial thoughts.

**Comment by patrickvonplaten** [comment]
Hey @keturn, that's indeed a somewhat messy API - we've already talked a bit about it with @anton-l and @patil-suraj. We would also like to change/adapt it, but it's actually quite tricky to bring all the schedulers into one design.

 Thanks for bringing this to everybody's attention here. Would love to openly discuss how we can improve the design!

**Comment by patrickvonplaten** [comment]
100% agree on that we somewhat badly entangle `sigmas` and `timesteps` here - we should definitely change this! 
Maybe `sigmas` shouldn't be accessible at all if some function hasn't been called yet

**Comment by patrickvonplaten** [comment]
Also like the idea of passing the `**kwargs` through to `scheduler.step(...)`!

**Comment by keturn** [comment]
When I originally looked at this, I was under the impression that there were some differences between whether sigmas or timesteps were computed up front and where some multiplication happened, but I figured that was solvable with a little algebra and a little refactoring without changing the overall design too much.

But when [hlky got me looking at why _some_ samplers weren't behaving](https://discord.com/channels/879548962464493619/1020832171352658061/1020869069806764112) as well as others, I realized there's a bigger difference between the design of Katherine's sampler functions and diffusers' Scheduler.step method: Samplers may use the model more than once per timestep.

The operation is very similar to that of guidance functions: Much like the current StableDiffusionPipeline offers an option to run two sets of data through the UNet to [perform classifier-free guidance](https://github.com/huggingface/diffusers/blob/429dace10a356a776f935fc11e16d5b321b496f3/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L252-L253), the higher order functions featured in _Elucidating_ and _DPM-Solver_ (`sample_heun` and `sample_dpm` in k_diffusers) use the model to make multiple predictions and combine them for a better result.

I expect we'll see a plethora of other guidance functions that rely on combining the results of multiple predictions, such as [Composable Diffusion](https://energy-based-model.github.io/Compositional-Visual-Generation-with-Composable-Diffusion-Models/).

…

Them's the findings. My thoughts about what to do about it are all tangled up with this project's philosophy of Pipelines being _single purpose_ and having some sort of pristine _original implementation_ that shall be preserved.

Reading that again, I see that schedulers _are_ intended to be building blocks, and that reassures me that we can come up with something we can build applications on. 😊

**Comment by patrickvonplaten** [comment]
Thanks a lot for the input here. We're thinking about a nice design with @anton-l and will share very soon!

**Comment by garrett361** [comment]
@keturn I'm curious about the link you shared: [hlky got me looking at why some samplers weren't behaving](https://discord.com/channels/879548962464493619/1020832171352658061/1020869069806764112)

However, when I try to follow it, I'm met with an error message from Discord: `You find yourself in a strange place. You don't have access to any text channels, or there are none in this server`.  Could you give more detailed instructions for how to see that conversation?
