### ISSUE TITLE
`LoRALinearLayer` stops autocast from working

### ISSUE THREAD

**Issue by Teoge** [huggingface/diffusers#3366]
### Describe the bug

I encountered an issue while finetuning a UNet2DConditionModel and attempting to use lora, resulting in a significant decrease in speed, around 2.6 times slower than the original processing time per step.
Upon investigation, I discovered that this slowdown was caused by the xformers library running on fp32 instead of fp16.
The reason behind xformers utilizing fp32 is due to the LoRALinearLayer manually converting the output type to match the input type, which in my case is fp32 because I have fixed text embeddings loaded from disk.

Here is the specific code snippet: https://github.com/huggingface/diffusers/blob/v0.14.0/src/diffusers/models/cross_attention.py#L346

Although I can manually convert the text embeddings to fp16 to bypass this issue, I believe this is not an ideal solution.
Could you please clarify the rationale behind manually converting the output type to match the input type?
Is there a specific reason why this conversion cannot be left to Automatic Mixed Precision (AMP) to handle the operation?

### Reproduction

-

### System Info

- `diffusers` version: 0.14.0
- Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.27
- Python version: 3.9.16
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Huggingface_hub version: 0.12.0
- Transformers version: 4.26.1
- Accelerate version: 0.18.0
- xFormers version: 0.0.18+da27862.d20230423
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by patrickvonplaten** [comment]
Hey @Teoge, 

We quite strongly discourage from running code **for inference** in autocast. Can you just run in normal FP16? 

For more info see:
- https://huggingface.co/docs/diffusers/v0.16.0/en/optimization/fp16#half-precision-weights
- https://github.com/huggingface/diffusers/issues/2568

**Comment by Teoge** [comment]
Thank you for your response. I appreciate the explanation provided. However, I would like to seek clarification on a couple of points.

1. While I understand the recommendation to run the inference code using FP16 precision, I want to clarify that I am currently training a UNet model. Based on your explanation, it is suggested to train the UNet model using full FP32 precision. However, I have found this approach to be too slow for my requirements, and I have observed a significant performance improvement by utilizing AMP during training. Although your reasoning is valid, I believe it may not be the most efficient choice for training.

2. Additionally, I have noticed that in the example scripts train_text_to_image.py and train_dreambooth.py, autocast is still employed in the training loop. This occurs because the model's forward function is wrapped in an autocast during the `model = accelerator.prepare(model)` step when the `--mixed_precision` option is utilized. Please correct me if my understanding is incorrect.
https://github.com/huggingface/accelerate/blob/v0.18.0/src/accelerate/accelerator.py#L1235

Thank you for your assistance.
