### ISSUE TITLE
Exception: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by jelling** [huggingface/diffusers#3367]
### Describe the bug

There may be multiple reasons for the `Exception: Error while deserializing header: HeaderTooLarge` error message when loading a LoRA, but one of them is caused by passing in `/pytorch_lora_weights.bin` instead of just the root directory.

Suggestion: add a check to make certain the user only passes in a directory OR drop the filename part. Also, the LoRA docs currently do not show a full path example which is probably why I hit this. 

### Reproduction

Example: 
```
  # Add LoRA
  bad_path = "/some_lora_dir/pytorch_lora_weights.bin"
  pipe.load_lora_weights(lora_path) #  Error while deserializing header: HeaderTooLarge
  lora_path = = "/some_lora_dir" 
  pipe.load_lora_weights(good_path) # works fine
```

### System Info

Doesn't matter

**Comment by patrickvonplaten** [comment]
Agree a better error message would be nice here! @sayakpaul do you have time to look into this maybe?

**Comment by sayakpaul** [comment]
Is it not clear from the docstring? 

https://huggingface.co/docs/diffusers/main/en/api/loaders#diffusers.loaders.LoraLoaderMixin.load_lora_weights

> Also, the LoRA docs currently do not show a full path example which is probably why I hit this.

What is a full path?

**Comment by sayakpaul** [comment]
Thanks @jelling. 

I opened a PR to clarify that: https://github.com/huggingface/diffusers/pull/3397.

**Comment by Mineyme** [comment]
I also have the similar issue when I run my comfyUI On the cloud。I cannot find any file about lora ,except  /notebooks/ComfyUI/models/loras. can anyone tell me how to resolve it, I'm not a developer ,  detail as soon as possible ,thank you very much

![image](https://github.com/huggingface/diffusers/assets/108466614/43e17440-4d5f-4983-a035-f381d4104c75)
