### ISSUE TITLE
Diffusers Controlnet pipeline with textual inversion tokens

### ISSUE THREAD

**Issue by bertChristiaens1** [huggingface/diffusers#3371]
I was wondering whether Textual Inversion tokens are already supported for Diffusers Controlnet pipelines?
Would this be a lot of changes to the original (Multi)controlnet pipeline?
I'm also wondering whether it's easy to load multiple Textual Inversion concepts for a Diffusers pipeline.

If this is not yet possible and seems feasable to implement, I might make some time to program a community pipeline for this!

Additional questions:
Why is the img2img and inpainting pipeline only a community pipeline? What does need to happen to integrate it in the Diffusers source code?
Is there a big benefit of Dreambooth over Textual Inversion? For now, Textual Inversion seems easier to integrate with external models such as ControlNet, since they use the StableDiffusion v15 base model, while Dreambooth appears to change the SDv15 weights.

**Comment by bertChristiaens1** [comment]
Thanks for the response, it's very useful! I also just discovered the `pipe.load_textual_inversion()` which makes it easy to load in new concepts.

And okay so Dreambooth is much better! But if I want to use MultiControlnet with existing trained controlnet checkpoints (e.g scribble+segmentation), I suppose it won't work that well with a trained Dreambooth checkpoint? I would like to learn multiple concepts (5-10) and combine it with Controlnets to add as much control possible.

**Comment by alexblattner** [comment]
>I also just discovered the pipe.load_textual_inversion() which makes it easy to load in new concepts.

that works but weighted prompts won't work

>And okay so Dreambooth is much better!

depends on what you're trying to do

>But if I want to use MultiControlnet with existing trained controlnet checkpoints (e.g scribble+segmentation), I suppose it won't work that well with a trained Dreambooth checkpoint

it will work on a dreambooth checkpoint.

>I would like to learn multiple concepts (5-10)

then loras or TIs would be better

>combine it with Controlnets to add as much control possible.

use the controlnet pipeline then

**Comment by ChristiaensBert** [comment]
Thanks very much @alexblattner!
Just to understand one more time, Dreambooth finetunes the model (Text Encoder+Unet) so modifies the internal weights. And Controlnet is trained on the original SD1.5 checkpoint. However, using a ControlNet model together with a finetuned Dreambooth model will still work even though the Controlnet model is not specifically trained for this new Dreambooth checkpoint?

And is it then possible to train 10 new concepts with Dreambooth and use them together? Or will this corrupt the original information in the model even more?

**Comment by alexblattner** [comment]
>using a ControlNet model together with a finetuned Dreambooth model will still work even though the Controlnet model is not specifically trained for this new Dreambooth checkpoint

yes

>And is it then possible to train 10 new concepts with Dreambooth and use them together

not sure. Someone who specializes in training could answer better, but theoretically yes and no. it could learn a few concepts, but it does forget stuff while training. the question is when and why. unsure, but someone who plays a lot with this can tell you more than anyone here.

>Or will this corrupt the original information in the model even more

when you train it corrupts the original model no matter what. the question is if you like the corruption or not. dreambooth checkpoints are better used for general things and styles. Specific concepts are better used with loras and TIs but TIs are worse at conveying concepts than loras
