### ISSUE TITLE
[feat] raise exceptions on all network errors

### ISSUE THREAD

**Issue by psychedelicious** [huggingface/diffusers#3372]
*This is not a bug report - please do not ask for updates on a HF outage here. This is a feature request for the `diffusers` library to change how to handles 50X network issues.*

*The May 9 HF outage is a known issue. Suggest checking Twitter for status updates https://twitter.com/huggingface or visit HF's discord*

**Is your feature request related to a problem? Please describe.**
There was a minor outage today in which calls to `from_pretrained()` resulted in 504 and 502 errors. 

Instead of raising an exception, a message was logged. 

Though the message was helpful, because it did not raise an exception, it was difficult to handle programmatically.

**Describe the solution you'd like**
All network errors raise exceptions.

**Describe alternatives you've considered**
I don't think there really is any.

**Comment by patrickvonplaten** [comment]
Hey @psychedelicious,

Very sorry for this outage - it's due to a HF Hub outage: https://status.huggingface.co/
We're working hard at resolving this.

**Comment by alexblattner** [comment]
@patrickvonplaten good luck on resolving it. Is there a way to use controlnet with only the safetensors and stable diffusion 1.5 without using the auto download or downloading the entire repo?

**Comment by psychedelicious** [comment]
No worries re: the outage - it happens!

Hoping we can get exceptions raised on all network errors so that consumers of `diffusers` can handle the situation gracefully.

**Comment by ASH1998** [comment]
Why are my local models not working, I have stored them in my cache dir, why do i need to connect to hub when i have the resources in local. This needs to be changed.

**Comment by psychedelicious** [comment]
@Noyii @ASH1998 @evancasey 
This is not a bug report - this is a feature request for the `diffusers` library.

The outage is a known issue. Suggest checking Twitter for status updates: https://twitter.com/huggingface

**Comment by aycaecemgul** [comment]
I can download models with git lfs, but it's a pain in the butt, it takes too long since there is a different versions of weights.
For example i do not need .ckpt or .safetensors version of the same model but i have to wait for it since it downloads the whole repo.
(Also before i found i can download models with git lfs, i tried _snapshot_download_ and _hf_hub_download functions to download specific files but examples and documentation is not clear and i couldn't make them work.)

tl,dr: there needs to be a clear and efficient way to download models without using _from_pretrained_.

**Comment by alexblattner** [comment]
@aycaecemgul agreed, it's a bad implementation philosophy regardless to be dependent on a server. Why can't diffusers just allow to use a ckpt/safetensors file and be done with it?

**Comment by patrickvonplaten** [comment]
Very sorry for the problems that were created two yesterday! It's the first time something similar happened in years. 

BTW you can always run everything locally by defining `local_files_only=True`.

**Nevertheless**, we should have better code that detects if the Hub is down and catches a `huggingface_hub.utils._errors.HfHubHTTPError` error. 

@Wauplin any idea how we could gracefully throw error messages or automatically switch to `local_files_only=True` when the Hub is down?

**Comment by Wauplin** [comment]
@patrickvonplaten If I remember correctly the first thing `diffusers` do when instantiating a pipeline is downloading the config file + make a call to `huggingface_hub.model_info()` to list the files in the repo. What I would do is to make this `model_info` call first. If it fails with a HTTPError, print a warning to the user + default back to "local_files_only=True" (either the user has no internet or the Hub is down).

So [in this file](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/pipeline_utils.py#L1207) I would rewrite the logic to:

```py
        if not local_files_only:
            try:
                info = model_info(
                    pretrained_model_name,
                    use_auth_token=use_auth_token,
                    revision=revision,
                )
            except RepoNotFoundError, EntryNotFoundError:
                raise # maybe still raise if Hub is up but repo/file do not exist ?
            except HTTPError as e:
                warnings.warn(f"Couldn't connect to the Hub: {e}. Will try to load from local cache.")
                local_files_only = True 

        if not local_files_only:
            config_file = hf_hub_download(
                pretrained_model_name,
                cls.config_name,
                cache_dir=cache_dir,
                revision=revision,
                proxies=proxies,
                force_download=force_download,
                resume_download=resume_download,
                use_auth_token=use_auth_token,
            )
           (...) # same logic afterwards
```

**Warning:** I did not try it myself. The snippet above is just there to give an idea.
