### ISSUE TITLE
Make diffusers independent from server

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#3375]
Hello diffusers team, we appreciate the libraries and your dedication. We understand that you are doing your best with the server issue, but it makes no sense why we need a server to run things locally.

Maybe try to allow better ways to use models that don't involve downloading an entire repository with files we don't need or download through the server over and over again?

**Comment by pcuenca** [comment]
You can always use `local_files_only=True` if you have the pipeline cached:

```Python
pipe = DiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", local_files_only=True, torch_dtype=torch.float16, revision="fp16")
```

(If the pipeline is cached and `local_files_only` is not specified, there's a single HTTP connection to verify whether the model configuration changed).

**Comment by alexblattner** [comment]
@pcuenca it is a good first step in the right direction. thank you!

**Comment by eeyrw** [comment]
But I have a question that my server can not access HF, but I can access by another PC. So how can I download the cache directory like "models--stabilityai--stable-diffusion-2-1" which keep version information?

**Comment by pcuenca** [comment]
You can create a Python script to to run `DiffusionPipeline.from_pretrained()` in that PC, but am not sure it'll work as the API services are down. Is the model not cached in your server?

**Comment by eeyrw** [comment]
> You can create a Python script to to run `DiffusionPipeline.from_pretrained()` in that PC, but am not sure it'll work as the API services are down. Is the model not cached in your server?

I notice there are two directory format "from_pretrained" accepted, one is the cached format which is mentioned above, the other is "raw" model files directory with no version control ( no blobs, snapshots ... ). So you mean even I prepare the cached format directory for the server with no ability to access HF, "from_pretrained" method will still try to access HF to ensure whether the current version is newest. The only way to ensure offline "from_pretrained" working is to specify the "raw" model files directory from snapshots of cached format.

Do I understand behaviour of "from_pretrained" correctly?

**Comment by patrickvonplaten** [comment]
Linked to: https://github.com/huggingface/diffusers/issues/3372

**Comment by patrickvonplaten** [comment]
I think a couple of issues are thrown together here - could we maybe open a new issue thread for different things? :-)
