### ISSUE TITLE
[Question] About SNR weighting optimization during diffusion training

### ISSUE THREAD

**Issue by haowang1013** [huggingface/diffusers#3377]
Hi,

Currently SNR weighting is only implemented for full text to image fine-tuning (in [train_text_to_image.py](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py#L838C26-L850)). I wonder if it makes sense to implement that optimization for other fine-tuning strategies (such as textural inversion, dreambooth, loras)?

Thanks

**Comment by haowang1013** [comment]
I also wonder if it makes sense to support the [use_ema](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py#L282) flag for other fine-tuning strategies for the similar reason.

**Comment by patrickvonplaten** [comment]
Gently pinging @sayakpaul here

**Comment by sayakpaul** [comment]
EMA is a memory-heavy affair, so, I guess it's fine that we do it only for a single example. That effectively stands as a reference for the community in case they want to use that in the other training scripts. 

I think same applies to MinSNR as well. 

But if you find that MinSNR substantially helped with quality and/or performance for the other training examples (even one), happy to welcome a PR :) 

I hope this makes sense.

**Comment by haowang1013** [comment]
> EMA is a memory-heavy affair, so, I guess it's fine that we do it only for a single example. That effectively stands as a reference for the community in case they want to use that in the other training scripts.
> 
> I think same applies to MinSNR as well.
> 
> But if you find that MinSNR substantially helped with quality and/or performance for the other training examples (even one), happy to welcome a PR :)
> 
> I hope this makes sense.

It does and I'll play with it and report back, thanks :)
