### ISSUE TITLE
[Tests] Add tests for LMS Discrete

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#338]
Similar to other tests we should add tests for the LMS Discrete Scheduler in https://github.com/huggingface/diffusers/blob/main/tests/test_scheduler.py

**Comment by patrickvonplaten** [comment]
cc @anton-l

**Comment by sidthekidder** [comment]
Btw, the cmd: `pytest tests/test_scheduler.py` fails on my system (macOS 11.2.3, Python 3.8.2, Apple clang version 12.0.5) with the error:

```
FAILED tests/test_scheduler.py::ScoreSdeVeSchedulerTest::test_full_loop_no_noise - AssertionError: assert 2048.0 < 0.01

>       assert abs(result_sum.item() - 14379591680.0) < 1e-2
E       AssertionError: assert 2048.0 < 0.01
E        +  where 2048.0 = abs((14379589632.0 - 14379591680.0))
E        +    where 14379589632.0 = <built-in method item of Tensor object at 0x15f7f0cc0>()
E        +      where <built-in method item of Tensor object at 0x15f7f0cc0> = tensor(1.4380e+10).item

tests/test_scheduler.py:800: AssertionError
```

**Comment by patrickvonplaten** [comment]
> Btw, the cmd: `pytest tests/test_scheduler.py` fails on my system (macOS 11.2.3, Python 3.8.2, Apple clang version 12.0.5) with the error:
> 
> ```
> FAILED tests/test_scheduler.py::ScoreSdeVeSchedulerTest::test_full_loop_no_noise - AssertionError: assert 2048.0 < 0.01
> 
> >       assert abs(result_sum.item() - 14379591680.0) < 1e-2
> E       AssertionError: assert 2048.0 < 0.01
> E        +  where 2048.0 = abs((14379589632.0 - 14379591680.0))
> E        +    where 14379589632.0 = <built-in method item of Tensor object at 0x15f7f0cc0>()
> E        +      where <built-in method item of Tensor object at 0x15f7f0cc0> = tensor(1.4380e+10).item
> 
> tests/test_scheduler.py:800: AssertionError
> ```

Yes for us as well @sidthekidder - we're looking into fixing this one in https://github.com/huggingface/diffusers/pull/268

**Comment by sidthekidder** [comment]
Added some code for the LMS Discrete scheduler similar to the DDIM scheduler test. Though I still haven't understood some parts of this scheduler, so the `test_full_loop_no_noise` [is failing](https://github.com/huggingface/diffusers/runs/8289643421?check_suite_focus=true) and I'm not sure how to fix it. The value of the [residual var here](https://github.com/huggingface/diffusers/pull/467/files#diff-7cab305a6a78540131fcce1fafb912ccf6b52aa50b4a0a2b794aea71004d5a95R875) seems to be a nan matrix, leading to the final `sample` output being nan as well. I don't understand how the `dummy_model` [fn here](https://github.com/huggingface/diffusers/pull/467/files#diff-7cab305a6a78540131fcce1fafb912ccf6b52aa50b4a0a2b794aea71004d5a95R870) mocks a real model as well, what does the value being returned mean.
In general, I couldn't find more details of a "LMS discrete scheduler" online, so not sure how to better understand the `test_full_loop_no_noise` function - would appreciate any tips or help! @patrickvonplaten @patil-suraj

**Comment by patrickvonplaten** [comment]
@anton-l can you help here?

**Comment by anton-l** [comment]
Hi @sidthekidder, checking your PR, will comment there soon! :hugs:
