### ISSUE TITLE
Discoloured output in StableDiffusionInpaintPipeline batch inference + possible docs error

### ISSUE THREAD

**Issue by BenjaminIrwin** [huggingface/diffusers#3381]
### Describe the bug

When I do batch inference using the StableDiffusionInpaintPipeline (inputting the images/masks as multidimensional tensors), I get discolored/pale output and the inpainted area seems to bear little relation to the inputted mask. Example:

Input image:
<img src="https://github.com/huggingface/diffusers/assets/59652119/6e0f3b2f-5e28-4e7a-9c71-fe70e8d234c3" width="200">

Input mask:
<img src="https://github.com/huggingface/diffusers/assets/59652119/a07a1de8-1be3-4db4-ab1a-018ddc0098c0" width="200">

Output images:
<img src="https://github.com/huggingface/diffusers/assets/59652119/b16df771-4c09-4a52-b810-eb832eb5b696" width="200">
<img src="https://github.com/huggingface/diffusers/assets/59652119/e4152b01-70bd-4aa6-9ebc-19bc0f4f6417" width="200">
<img src="https://github.com/huggingface/diffusers/assets/59652119/dfa30c49-7bce-43cb-b059-bf0ae7a206af" width="200">

And here's an output example from when I perform single image inference (using PIL image and PIL mask as input):

<img src="https://github.com/huggingface/diffusers/assets/59652119/e87fadd8-a05e-40f9-b709-a366b8bf4361" width="200">

As you can see there is no discoloration/paleness in this latter example. Am I missing something obvious in my code? If not it feels like something is happening in the StableDiffusionInpaintPipeline __call__ function, prior to the forward pass, which is causing this distortion?

Also heads up, I think there may be a mistake in the docs (https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/inpaint#diffusers.StableDiffusionInpaintPipeline.__call__.mask_image). It says 'expected shape [of the mask input tensor] would be (B, H, W, 1)', but the script rejects tensors in that shape. What worked for me for both image and mask tensors was (B, 1, H, W).

### Reproduction

```py
import torch
import torchvision
from PIL import Image
from diffusers import StableDiffusionInpaintPipeline
from diffusers.utils import PIL_INTERPOLATION

from constants import hf_token

batch_size = 3
prompt = 'A woman walking'

image_transforms = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
])

def preprocess(images, width=512, height=512):
    image_tensors = []
    for image in images:
        image = image.resize((width, height), resample=PIL_INTERPOLATION["lanczos"])
        image = image_transforms(image)
        image_tensors.append(image)
    return torch.stack(image_tensors)

model = StableDiffusionInpaintPipeline.from_pretrained("runwayml/stable-diffusion-inpainting", torch_dtype=torch.float16,
                                                               use_auth_token=hf_token,safety_checker=None)
model = model.to("cuda")
model.enable_attention_slicing()

mask = Image.open('mask.png').convert('L')
masks = [mask] * batch_size
init_images = [Image.open('image.png').convert('RGB')] * batch_size

input_masks = preprocess(masks)
input_images = preprocess(init_images)

prompts = [prompt] * batch_size

output_images = model(image=input_images, mask_image=input_masks, prompt=prompts, guidance_scale=7, num_inference_steps=25).images

for idx, output_image in enumerate(output_images):
    output_image.save('image_out_{}.png'.format(idx))

```

### System Info

- `diffusers` version: 0.16.1
- Platform: Linux-5.10.173-154.642.amzn2.x86_64-x86_64-with-glibc2.26
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.28.1
- Accelerate version: 0.19.0
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by patrickvonplaten** [comment]
Hey @BenjaminIrwin, 

Please make sure to not use torchvision or other custom image transformation functions to pre-process the image. When using just `diffusers` functions everything works just fine. The following worked for me without problems:

```py
from diffusers.utils import load_image

mask = load_image("https://user-images.githubusercontent.com/59652119/237332764-a07a1de8-1be3-4db4-ab1a-018ddc0098c0.png")
image = load_image("https://user-images.githubusercontent.com/59652119/237332730-6e0f3b2f-5e28-4e7a-9c71-fe70e8d234c3.png")

from diffusers import StableDiffusionInpaintPipeline
import torch

model = StableDiffusionInpaintPipeline.from_pretrained("runwayml/stable-diffusion-inpainting", torch_dtype=torch.float16)
model = model.to("cuda")
model.enable_attention_slicing()

batch_size = 3
prompt = 'A woman walking'

masks = [mask] * batch_size
images = [image] * batch_size

prompts = [prompt] * batch_size

output_images = model(image=images, mask_image=masks, prompt=prompts, guidance_scale=7, num_inference_steps=25).images

for output_image in output_images:
    display(output_image)
```

See colab here: https://drive.google.com/file/d/1IbzObg7h95lZuGmKoORTaaldOnYK2le9/view?usp=sharing

**Comment by BenjaminIrwin** [comment]
Thank you very much Patrick! Heads up this code snippet isn't working on 0.16.1. I get the following error:

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 57 for tensor number 2 in the list.

It is working on the dev version you use in the colab though.

**Comment by patrickvonplaten** [comment]
Ah yeah you're totally right! Seems like @yiyixuxu your VAE processing PR has fixed it :-)
