### ISSUE TITLE
DeepFloyd-IF in JAX

### ISSUE THREAD

**Issue by yuvalkirstain** [huggingface/diffusers#3385]
### Model/Pipeline/Scheduler description

The new [DeepFloyd-IF model](https://huggingface.co/DeepFloyd/IF-I-XL-v1.0) looks really good! Hope to see it implemented in Jax to run on TPUs :)

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://huggingface.co/DeepFloyd/IF-I-XL-v1.0

**Comment by yiyixuxu** [comment]
@sayakpaul 😁

**Comment by patrickvonplaten** [comment]
@yuvalkirstain would you be interested in giving this a try? We could give you access to a TPU for it :-)

**Comment by yuvalkirstain** [comment]
@patrickvonplaten not sure if I will have time to do it, but if I do I will definitely add a PR.

**Comment by fkunn1326** [comment]
@patrickvonplaten Hi, I am trying [deepfloyd if on tpu](https://github.com/fkunn1326/diffusers/tree/if-flax)  but I don't have access to tpu.
Can you give me access to the tpu?
