### ISSUE TITLE
[Tests] Add Tests for Karras VE

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#339]
Similar to other tests we should add tests for the Karras VE Scheduler in https://github.com/huggingface/diffusers/blob/main/tests/test_scheduler.py

**Comment by shraddhafalane** [comment]
Would like to work on it.

**Comment by rashmimarganiatgithub** [comment]
@sidthekidder, this is similar to [Tests] Add tests for LMS Discrete #338. I hope you don't mind testing both the issue at the same and merging them into one PR?

**Comment by sidthekidder** [comment]
@rashmimarganiatgithub I'm starting LMS discrete first, since that one could take a while both at the same time might be tough! Let me see how it goes.

**Comment by patrickvonplaten** [comment]
Usually it's good to make one PR per issue! We try our PRs to be laser-focused for an issue only, so I think it would be good to keep the PRs separated to begin with :-)

**Comment by patrickvonplaten** [comment]
@anton-l any updates here?
