### ISSUE TITLE
How can I convert A111 .safetensors format lora to .bin format lora?

### ISSUE THREAD

**Issue by sanbuphy** [huggingface/diffusers#3393]
Due to current issues loading A111 safetensors, https://github.com/huggingface/diffusers/issues/3064
I want to load it at runtime by converting it to the bin format. I used the script (https://github.com/haofanwang/Lora-for-Diffusers) but found that it could not fully convert the weights to bin format, resulting in a final bin file that is half the size of the original safetensor file.

**Comment by patrickvonplaten** [comment]
cc @sayakpaul as well think this a duplicate of a bunch of other issues now
