### ISSUE TITLE
Make Loras also modify text embeddings

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#3396]
Apparently, A1111 also makes Loras modify the embeddings as you can see in the example here: https://civitai.com/models/8252/gal-gadotlora the trigger word is gldot which isn't part of the general training data of SD1.5. Also, @takuma104 confirmed that to be the case. Now, I'll be completely honest. I have no idea what's the idea behind loras and how they're implemented beyond the fact that they modify the model. so, how does one update the embeddings from loras?

**Comment by patrickvonplaten** [comment]
Sorry I don't fully follow here :sweat_smile: . By modifying "the embeddings" do you mean the text embeddings? Maybe the checkpoint has textual inversion and lora in one? 

Also cc @sayakpaul just FYI

**Comment by takuma104** [comment]
@alexblattner I took a look at the gal-gadotlora file using [this script](https://gist.github.com/takuma104/de3045680f9647209303695b0d959cb5) and it includes LoRA for the text_encoder as well. From my understanding, the tokenizer properly tokenizes any unknown word, and then the LoRA part of the text_encoder learns from it, turning it into a trigger word.

**Comment by alexblattner** [comment]
@takuma104 thanks, I think that the fact that I was not using a checkpoint made it seem so bad that I didn't realize that the Lora was applied

**Comment by jfischoff** [comment]
Hi all, trying to understand if the latest PR that was merged for loading loras also supports these trigger words.
