### ISSUE TITLE
ControlNet v1.1.150 works worse than previous version makes blurry images

### ISSUE THREAD

**Issue by i4imaru** [huggingface/diffusers#3407]
after update  automatic1111 started to generate blurry images maybe someone knows what to do in this case, before images was sharper and more contrast, even if the input is low quality, but right now doesn't matter how much quality is your inout image the result is blurry and with low details

**Comment by patrickvonplaten** [comment]
Hey @i4imaru!

`diffusers` != A1111, please open an issue on automatic1111: https://github.com/AUTOMATIC1111/stable-diffusion-webui
