### ISSUE TITLE
[Tests] Training DreamBooth with LoRA with text encoder enabled

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#3411]
From [this](https://github.com/huggingface/diffusers/actions/runs/4955396756/jobs/8864770968?pr=3370) CI run:

```bash
E           AttributeError: 'UNet2DConditionModel' object has no attribute 'text_model'
```

But this only seems to be an issue when `accelerate` is built from source. If we install the latest stable version of `accelerate`, it goes away. 

## To reproduce

```bash
from accelerate.utils import write_basic_config

write_basic_config(save_location="default_config.yml")
```

And then:

```bash
accelerate launch --config_file default_config.yml examples/dreambooth/train_dreambooth_lora.py \
    --pretrained_model_name_or_path hf-internal-testing/tiny-stable-diffusion-pipe \
    --instance_data_dir docs/source/en/imgs \
    --instance_prompt photo \
    --resolution 64 \
    --train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --max_train_steps 2 \
    --learning_rate 5.0e-04 \
    --scale_lr \
    --lr_scheduler constant \
    --lr_warmup_steps 0 \
    --train_text_encoder \
    --output_dir .
```

Make sure `accelerate` is installed from source and you're on a CPU. 

@patrickvonplaten @williamberman

**Comment by sayakpaul** [comment]
I was investigating this. 

To provide more context, here's what I get when I print the keys of the state_dict of `unet_lora_layers` (here):

https://github.com/huggingface/diffusers/blob/3a237f4fa25dd5a3f354428f0e2e869d08089dc7/examples/dreambooth/train_dreambooth_lora.py#L836

```bash
down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor.to_q_lora.down.weight
down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor.to_q_lora.up.weight
down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor.to_k_lora.down.weight
down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor.to_k_lora.up.weight
down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor.to_v_lora.down.weight
down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor.to_v_lora.up.weight
down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor.to_out_lora.down.weight
down_blocks.1.attentions.0.transformer_blocks.0.attn1.processor.to_out_lora.up.weight
...
```

However, after we "prepare" the parameters and other things with `accelerate`, when I peak into the keys of the SAME state dict, I get:

```bash
text_model.encoder.layers.0.self_attn.k_proj.to_q_lora.down.weight
text_model.encoder.layers.0.self_attn.k_proj.to_q_lora.up.weight
text_model.encoder.layers.0.self_attn.k_proj.to_k_lora.down.weight
text_model.encoder.layers.0.self_attn.k_proj.to_k_lora.up.weight
text_model.encoder.layers.0.self_attn.k_proj.to_v_lora.down.weight
text_model.encoder.layers.0.self_attn.k_proj.to_v_lora.up.weight
text_model.encoder.layers.0.self_attn.k_proj.to_out_lora.down.weight
text_model.encoder.layers.0.self_attn.k_proj.to_out_lora.up.weight
text_model.encoder.layers.0.self_attn.v_proj.to_q_lora.down.weight
text_model.encoder.layers.0.self_attn.v_proj.to_q_lora.up.weight
text_model.encoder.layers.0.self_attn.v_proj.to_k_lora.down.weight
...
```

I can confirm that the save and load hooks don't have any effect on this as I verified that this issue persists when we remove the hooks:

https://github.com/huggingface/diffusers/blob/3a237f4fa25dd5a3f354428f0e2e869d08089dc7/examples/dreambooth/train_dreambooth_lora.py#L914-#L915

Cc: @muellerzr if you have any insights on this.

**Comment by patrickvonplaten** [comment]
I can reproduce. The interesting part is that it works on `accelerate==0.19.0` but fails when using `accelerate` source. 

Here ho to reproduce very easily @muellerzr:

# 1. Git clone diffusers and cd

```
git clone https://github.com/huggingface/diffusers.git && cd diffusers
```

# 2. Install accelerate with latest pypi
```
pip install accelerate --upgrade # 0.19.0
```

# 3. Save accelerate config in `diffusers` dir:
```
{
  "compute_environment": "LOCAL_MACHINE",
  "distributed_type": "NO",
  "downcast_bf16": false,
  "machine_rank": 0,
  "main_training_function": "main",
  "mixed_precision": "no",
  "num_machines": 1,
  "num_processes": 1,
  "rdzv_backend": "static",
  "same_network": false,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": true
}
```

4. Run @sayakpaul script:
```
accelerate launch --config_file default_config.yml examples/dreambooth/train_dreambooth_lora.py \
    --pretrained_model_name_or_path hf-internal-testing/tiny-stable-diffusion-pipe \
    --instance_data_dir docs/source/en/imgs \
    --instance_prompt photo \
    --resolution 64 \
    --train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --max_train_steps 2 \
    --learning_rate 5.0e-04 \
    --scale_lr \
    --lr_scheduler constant \
    --lr_warmup_steps 0 \
    --train_text_encoder \
    --output_dir .
```

=> Note that this works! Now updating `accelerate` to source gives a failure. Can you look into this?

**Comment by muellerzr** [comment]
How long ago did it start failing? (E.g. did it work 2 days ago and not yesterday?)

**Comment by sayakpaul** [comment]
Yesterday it was fine. Started failing from today

**Comment by muellerzr** [comment]
As mentioned in [here](https://github.com/huggingface/accelerate/issues/1420), this stems from a recent integration on main. For now please build via pypi and we'll look into it as soon as we can. Sorry!

**Comment by muellerzr** [comment]
@sayakpaul can you verify installing from main again fixed all issues? Should be good now :)

**Comment by sayakpaul** [comment]
For now, we have pinned the last version of accelerate in our Docker containers. But will update in the coming days. 

Thank you, Zach!

**Comment by sayakpaul** [comment]
Closing it's now solved.
