### ISSUE TITLE
Stuck at launch of code for creation of model

### ISSUE THREAD

**Issue by anthonysom** [huggingface/diffusers#3423]
Hi all,

I'm stuck when trying to run the code to create the model. it renders the below:

2023-05-11 10:07:31.040186: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py:258: FutureWarning: logging_dir is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use project_dir instead.
warnings.warn(
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/train_dreambooth.py:869 in │
│ │
│ 866 │
│ 867 if name == "main": │
│ 868 │ args = parse_args() │
│ ❱ 869 │ main(args) │
│ 870 │
│ │
│ /content/train_dreambooth.py:460 in main │
│ │
│ 457 │ │ │ } │
│ 458 │ │ ] │
│ 459 │ else: │
│ ❱ 460 │ │ with open(args.concepts_list, "r") as f: │
│ 461 │ │ │ args.concepts_list = json.load(f) │
│ 462 │ │
│ 463 │ if args.with_prior_preservation: │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 'concepts_list.json'

Can anyone help to fix this issue plz?
Thanks

**Comment by stpg06** [comment]
You prob have the the argument --concepts_list="concepts_list.json" in your run code 
`!wget -q https://github.com/ShivamShrirao/diffusers/raw/main/examples/dreambooth/concepts_list.json` and edit the prompts and paths to match your dataset.

As an alternative, you would remove the argument altogether, but with this option you must specify --instance_prompt="", class_prompt="", instance_data_dir="" and class_data_dir="" - with concepts_list.json you don't need these options as they are specified in the file. 

concepts_list in mainly used when you want to train multiple concepts. but works the same if you only specify one.

**Comment by anthonysom** [comment]
Hi and many thanks for taking the time to guide me through finding a solution.

So I have the code below:

!python3 train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --pretrained_vae_name_or_path="stabilityai/sd-vae-ft-mse" \
  --output_dir=$OUTPUT_DIR \
  --revision="fp16" \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --seed=1337 \
  --resolution=512 \
  --train_batch_size=1 \
  --train_text_encoder \
  --mixed_precision="fp16" \
  --use_8bit_adam \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=12 \
  --sample_batch_size=4 \
  --max_train_steps=1000 \
  --save_interval=1000 \
  --save_sample_prompt="photo of atypidi person" \
  --concepts_list="concepts_list.json"

So I understand, based on what you wrote, that my problem originates from the line
`  --concepts_list="concepts_list.json"`

- What I do not undertand is what I shoud do with the first option where you mention the below:
`!wget -q https://github.com/ShivamShrirao/diffusers/raw/main/examples/dreambooth/concepts_list.json` Where do you get this line from? And what do you mean when you say I must edit the prompts and paths to match my dataset?

- The second option would be to delete `  --concepts_list="concepts_list.json"` and replace it with
--instance_prompt=""
--class_prompt=""
--instance_data_dir=""
--class_data_dir=""
But then, as you mentioned, I would have to specify these? WHat if they are already specified ?

I have them specified as below:
concepts_list = [
    {
        "instance_prompt":      "photo of atypidi person",
        "class_prompt":         "photo of a person",
        "instance_data_dir":    "/content/data/atypidi",
        "class_data_dir":       "/content/data/person"
    },
#     {
#         "instance_prompt":      "photo of ukj person",
#         "class_prompt":         "photo of a person",
#         "instance_data_dir":    "/content/data/ukj",
#         "class_data_dir":       "/content/data/person"
#     }
]

# `class_data_dir` contains regularization images
import json
import os
for c in concepts_list:
    os.makedirs(c["instance_data_dir"], exist_ok=True)

with open("concepts_list.json", "w") as f:
    json.dump(concepts_list, f, indent=4)

**Comment by sayakpaul** [comment]
Hi, 

We don't support `concepts_list.json` as a part of the training script. I would suggest opening this issue in https://github.com/ShivamShrirao/diffusers. 

Since this is something we don't support from the training script (we don't plan to as well), I am closing this issue.
