### ISSUE TITLE
makeavid-sd-jax

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#3427]
### Model/Pipeline/Scheduler description

New text2video project:
https://huggingface.co/spaces/TempoFunk/makeavid-sd-jax
https://github.com/lopho/makeavid-sd-tpu

### Open source status

- [x] The model implementation is available
- [x] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by patrickvonplaten** [comment]
It'd be amazing if we could convert this to PyTorch and add here :heart_eyes:

**Comment by sayakpaul** [comment]
Here's the PyTorch implementation: https://github.com/lopho/makeavid-sd-tpu/tree/main/makeavid_sd/torch_impl

Cc: @lopho.
