### ISSUE TITLE
An unexpected result when I try to change the StableDiffusionImg2ImgPipeline

### ISSUE THREAD

**Issue by LeoooooMM** [huggingface/diffusers#3428]
### Describe the bug

I'm not sure I could call it a bug.
The difference is a modification based on the example using StableDiffusionImg2ImgPipeline

`pipe.unet      = UNet2DConditionModel.from_config(pipe.unet.config).to(device)`

But the two pieces of code give very different results, especially if I insert the above code(use pipe.net = ...), the pipeline gives a result that looks like Gaussian noise. I don't really understand why there is such a difference

Besides, I have a small question about whether a diffusion model like controlnet, which operates on the latent space, has a resolution requirement for the training dataset. I understand that the fill50k given in the example gives data in 512×512. If I want to fine-tune with custom dataset(256×256 for example), do I need to wirte my own Data preprocessing functions, or I just need to modify the resolution parameter in train_control.py?

### Reproduction

```
import torch
from PIL import Image
from diffusers import StableDiffusionImg2ImgPipeline,UNet2DConditionModel,DDIMScheduler


device = "cuda"
pipe = StableDiffusionImg2ImgPipeline.from_pretrained("runwayml/stable-diffusion-v1-5",safety_checker=None).to(device)

init_image = Image.open("image.jpg").convert("RGB")
init_image.thumbnail((256,256))
prompt = "John French Sloan / Cornelia Street / New Realism / cityscape / 1920"

pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)
#pipe.unet      = UNet2DConditionModel.from_config(pipe.unet.config).to(device) # the difference
generator = torch.Generator(device="cuda").manual_seed(0)

images = pipe(prompt=prompt, image=init_image, strength=0.75,guidance_scale=7.5,generator=generator).images[0]
images.save("pre.png")


```
this is source image
![image](https://github.com/huggingface/diffusers/assets/88709183/fc88e328-bd7c-43ca-8468-14b63a22f883)
these are 2 results with and without the pipe.unet sentence
![pre (1)](https://github.com/huggingface/diffusers/assets/88709183/5bd2660e-a795-4ec8-915e-79ea89709376)
![pre](https://github.com/huggingface/diffusers/assets/88709183/6c20482d-8876-4cb7-8566-a6ab825d255a)

### System Info

this is system info
- `diffusers` version: 0.17.0.dev0
- Platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.35
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.13.4
- Transformers version: 4.27.4
- Accelerate version: 0.17.1
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by alexblattner** [comment]
I don't what changes you made, but it's clear that the denoising process is not happening

**Comment by LeoooooMM** [comment]
> I don't what changes you made, but it's clear that the denoising process is not happening

I also think the denosing process is not happening but I dont know why. 
I use the almost the same two programs above except this sentence below
`#pipe.unet      = UNet2DConditionModel.from_config(pipe.unet.config).to(device) # the difference`

**Comment by patrickvonplaten** [comment]
Hey @LeoooooMM,

By doing:

```py
pipe.unet  = UNet2DConditionModel.from_config(pipe.unet.config).to(device)
```

you are randomely initializing the model, so essentially you wipe out all the pretrained weights for random ones. 
Please use `UNet2DConditionModel.from_pretrained(...)` here instead.
