### ISSUE TITLE
training dreambooth with 4 gb vram

### ISSUE THREAD

**Issue by pure-rgb** [huggingface/diffusers#3452]
### Describe the bug

I tried to run dreambooth with my 4 gb gpu and I couldn't make it run. I used all the optimization techniques but still it couldn't run. I tired both dreambooth and lora

### Reproduction

Code 

https://github.com/huggingface/diffusers/tree/main/examples/dreambooth

### System Info

cpu: core i9
ram: 16 gb
gpu: 1050 Ti (4GB)

**Comment by patrickvonplaten** [comment]
I don't think it's possible to run it with just 4GB of RAM, you'll need at least 8GB I think

**Comment by pure-rgb** [comment]
okay. then, would it be possible to run at least 6 gb? pls see here https://github.com/huggingface/diffusers/pull/2918#issuecomment-1550267591
