### ISSUE TITLE
ClipGuidedDiffusion lacks prompt latents and negative latents, making it impossible to use with lpw

### ISSUE THREAD

**Issue by Pirog17000** [huggingface/diffusers#3456]
As follows from the title:  ClipGuidedDiffusion pipeline lacks latents inputs, so it is not possible at the moment to get the long prompt, convert it with LPW pipeline and put latents into clip-guided pipeline.

**Describe the solution you'd like**
• add support of latents for this pipeline
• make prompt an optional argument

**Comment by patrickvonplaten** [comment]
cc @patil-suraj 

Note that we recommend using compel instead of LPW as stated here: https://huggingface.co/docs/diffusers/using-diffusers/weighted_prompts

**Comment by Pirog17000** [comment]
while using lpw or compel, both outputs embeds, which are not possible to use after weightening (also would be great to have both working and compatible)
