### ISSUE TITLE
Unable to find a version that satisfies the requirement huggingface-hub to install diffusers

### ISSUE THREAD

**Issue by rashmimarganiatgithub** [huggingface/diffusers#347]
### Describe the bug

while trying to setup development environment by using  command(pip install -e ".[dev]") within diffusers cloned repro folder
I am getting ERROR: Could not find a version that satisfies the requirement huggingface-hub<1.0,>=0.8.1 

I have tried downgrading default huggingface_hub = 0.4.1 to 0.0.19 to 0.1.0
but no use, I am not able to install the diffusers . what is the correct version of huggingface_hub which needs to be installed

### Reproduction

**Follow CONTRIBUTING.md file steps**

Follow these steps to start contributing ([supported Python versions](https://github.com/huggingface/diffusers/blob/main/setup.py#L426)):

1. Fork the [repository](https://github.com/huggingface/diffusers) by
   clicking on the 'Fork' button on the repository's page. This creates a copy of the code
   under your GitHub user account.

2. Clone your fork to your local disk, and add the base repository as a remote:

   ```bash
   $ git clone git@github.com:<your Github handle>/diffusers.git
   $ cd diffusers
   $ git remote add upstream https://github.com/huggingface/diffusers.git
   ```

3. Create a new branch to hold your development changes:

   ```bash
   $ git checkout -b a-descriptive-name-for-my-changes
   ```

   **Do not** work on the `main` branch.

4. Set up a development environment by running the following command in a virtual environment:

   ```bash
   $ pip install -e ".[dev]"
   ```

   (If diffusers was already installed in the virtual environment, remove
   it with `pip uninstall diffusers` before reinstalling it in editable
   mode with the `-e` flag.)

### System Info

```shell
ERROR: Could not find a version that satisfies the requirement huggingface-hub<1.0,>=0.8.1 (from diffusers[dev]) (from versions: 0.0.1, 0.0.2, 0.0.3rc1, 0.0.3rc2, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.4.0)
```

**Comment by rashmimarganiatgithub** [comment]
@patrickvonplaten , what is correct version of huggingface_hub for installing diffusers while setting up development environment with command: pip install -e ".[dev]"

**Comment by patrickvonplaten** [comment]
Hey @rashmimarganiatgithub, 

Could you try again with: https://github.com/huggingface/diffusers/pull/348 :-) The newest version of `huggingface_hub` (`huggingface_hub==0.9.1`: https://github.com/huggingface/huggingface_hub/releases/tag/v0.9.1) is the correct one :-)

**Comment by rashmimarganiatgithub** [comment]
Hey @patrickvonplaten ,

 Tried with 0.9.1 version, but still same issue.
python -m pip install huggingface_hub==0.9.1
ERROR: Could not find a version that satisfies the requirement huggingface_hub==0.9.1 (from versions: 0.0.1, 0.0.2, 0.0.3rc1, 0.0.3rc2, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.4.0)
ERROR: No matching distribution found for huggingface_hub==0.9.1
MacBook-Pro:diffusers rashmi_margani$ pip install huggingface_hub==0.9.1
ERROR: Could not find a version that satisfies the requirement huggingface_hub==0.9.1 (from versions: 0.0.1, 0.0.2, 0.0.3rc1, 0.0.3rc2, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.4.0)
ERROR: No matching distribution found for huggingface_hub==0.9.1

**Comment by bubbleshark** [comment]
Hi @rashmimarganiatgithub ,
huggingface_hub 3.9.1 requires: Python >=3.7.0. Please checkout the python version that you are using is upper than 3.7.0 or not. Thanks

**Comment by patrickvonplaten** [comment]
Hey @rashmimarganiatgithub,

It seems like @bubbleshark is on the correct path here! Could you update your Python version and try again? :-)

**Comment by rashmimarganiatgithub** [comment]
@bubbleshark , issue resolved. thanks.
