### ISSUE TITLE
Training text_to_image on multi-GPU with Megatron-LM or DeepSpeed does not work

### ISSUE THREAD

**Issue by zipliucc** [huggingface/diffusers#3484]
I have an EC2 instance with 4 GPUs and each GPU has 16GB memory.

By default, hugging face uses Data Parallelism and tries to fit one copy of the model in each GPU. Of course, 16GB is not enough and I ran into CUDA Out of Memory error.

I tried to use Tensor Parallelism and Pipeline Parallelism through **_Megatron-LM_** . For example, with Pipeline Parallel Degree of 4 using Megatron-LM, it is supposed to split the model over 4 GPUs and totally 64 GB GPU memory. However, I still ran into CUDA Out of Memory error.

I also tried to use ZeRO Stage 2 or 3 through _**DeepSpeed**_. However, I still ran into CUDA Out of Memory error.

In both cases, I used **_hugging face accelerate_** to configure Megatron-LM or DeepSpeed. 

I wonder if the diffuser repo works out of box with Megatron-LM and DeepSpeed. Or, do I need to make code change to make it work with Tensor/Pipeline parallelism? 

Thank you very much,

**Comment by zipliucc** [comment]
Here is one example. 

Accelerate config
`In which compute environment are you running?
This machine                                                                                                              
--------------------------------------------------------------------------------------------------------------------------
Which type of machine are you using?                                                                                      
multi-GPU                                                                                                                 
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1                                
Do you wish to optimize your script with torch dynamo?[yes/NO]:                                                           
Do you want to use DeepSpeed? [yes/NO]:                                                                                   
Do you want to use FullyShardedDataParallel? [yes/NO]:                                                                    
Do you want to use Megatron-LM ? [yes/NO]: yes
What is the Tensor Parallelism degree/size? [1]:
What is the Pipeline Parallelism degree/size? [1]:4
What is the number of micro-batches? [1]:1
Do you want to enable selective activation recomputation? [YES/no]: 
Do you want to use distributed optimizer which shards optimizer state and gradients across data pralellel ranks? [YES/no]: 
What is the gradient clipping value based on global L2 Norm (0 to disable)? [1.0]: 
How many GPU(s) should be used for distributed training? [1]:4
--------------------------------------------------------------------------------------------------------------------------
Do you wish to use FP16 or BF16 (mixed precision)? 
fp16 `

Accelerate command & arguments.
`export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export TRAIN_DIR="/home/ubuntu/code/labweek23-itg-support/Nexus/"
mkdir "mymodel"
export OUTPUT_DIR="mymodel"


accelerate launch --mixed_precision="fp16" --multi_gpu train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$TRAIN_DIR \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_checkpointing \
  --gradient_accumulation_steps=4 \
  --mixed_precision="fp16" \
  --max_train_steps=5000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir=${OUTPUT_DIR} 
`

With this configuration, I was trying to run Pipeline Parallelization, one model over 4 GPUs. However, I got torch.cuda.OutOfMemoryErrorCUDA out of memory

**Comment by zipliucc** [comment]
Hi @patrickvonplaten ,

Thank you so much for the suggestions. Really appreciate your insights and feedback .

Regards,

Zhipeng

**Comment by sayakpaul** [comment]
Closing this issue then. In case problems persist, feel free to re-open :)

**Comment by chaojiewang94** [comment]
@zipliucc have you find the solution to split the model over 4 GPUs?

**Comment by zipliucc** [comment]
Hi @chaojiewang94 , sorry for missing your message. 

No I did not figure out how to make the Tensor Parallelism or Pipeline Parallelism work over multiple GPU.

I managed to make the fine-tune work on single GPU with "--use_8bit_adam"
