### ISSUE TITLE
 lpw_stable_diffusion_onnx  AttributeError: 'OnnxRuntimeModel' object has no attribute 'config'  OnnxStableDiffusionImg2ImgPipeline

### ISSUE THREAD

**Issue by dushwe** [huggingface/diffusers#3489]
code:
device = "cuda"
model_id = "./sd_v15_onnx"   
pipe = OnnxStableDiffusionImg2ImgPipeline.from_pretrained(
        model_id,  
       custom_pipeline="lpw_stable_diffusion_onnx",
       torch_dtype=torch.float16,
       provider="CUDAExecutionProvider"
       ).to(device)

logs: 
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/hdq/work/diffusers/scripts/img2img.py:32 in <module>                                       │
│                                                                                                  │
│   29                                                                                             │
│   30 device = "cuda"                                                                             │
│   31 model_id = "./sd_v15_onnx"                                   │
│ ❱ 32 pipe = OnnxStableDiffusionImg2ImgPipeline.from_pretrained(                                  │
│   33 │   │   model_id,                                                                           │
│   34 │      custom_pipeline="lpw_stable_diffusion_onnx",                                         │
│   35 │      torch_dtype=torch.float16,                                                           │
│                                                                                                  │
│ ******/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py:107 │
│ 4 in from_pretrained                                                                             │
│                                                                                                  │
│   1071 │   │   │   )                                                                             │
│   1072 │   │                                                                                     │
│   1073 │   │   # 8. Instantiate the pipeline                                                     │
│ ❱ 1074 │   │   model = pipeline_class(**init_kwargs)                                             │
│   1075 │   │                                                                                     │
│   1076 │   │   return_cached_folder = kwargs.pop("return_cached_folder", False)                  │
│   1077 │   │   if return_cached_folder:                                                          │
│                                                                                                  │
│ /root/.cache/huggingface/modules/diffusers_modules/git/lpw_stable_diffusion_onnx.py:461 in       │
│ __init__                                                                                         │
│                                                                                                  │
│    458 │   │   │   │   feature_extractor=feature_extractor,                                      │
│    459 │   │   │   │   requires_safety_checker=requires_safety_checker,                          │
│    460 │   │   │   )                                                                             │
│ ❱  461 │   │   │   self.__init__additional__()                                                   │
│    462 │                                                                                         │
│    463 │   else:                                                                                 │
│    464                                                                                           │
│                                                                                                  │
│ /root/.cache/huggingface/modules/diffusers_modules/git/lpw_stable_diffusion_onnx.py:489 in       │
│ __init__additional__                                                                             │
│                                                                                                  │
│    486 │   │   │   self.__init__additional__()                                                   │
│    487 │                                                                                         │
│    488 │   def __init__additional__(self):                                                       │
│ ❱  489 │   │   self.unet.config.in_channels = 4                                                  │
│    490 │   │   self.vae_scale_factor = 8                                                         │
│    491 │                                                                                         │
│    492 │   def _encode_prompt(                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'OnnxRuntimeModel' object has no attribute 'config'

System Info:

diffusers. 0.16.1
onnxruntime 1.14.1
onnxruntime-gpu 1.14.1
python 3.8.13
torch      1.12.1+cu113
transformers              4.28.1
huggingface-hub           0.14.1

how to  solve ?

**Comment by sayakpaul** [comment]
Ccing @echarlaix as well.

**Comment by echarlaix** [comment]
Hi @dushwe, 

When loading a `diffusers` pipeline, the model config will be used to determine which class should be used to load each subcomponent. Here it seems that you used `optimum` to export your model so you'll need to update your model [`model_index.json`](https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/onnx/model_index.json#L18) to specify that `OnnxRuntimeModel` needs to be used for each ONNX subcomponent
