### ISSUE TITLE
OSError: fatal: unable to access 'https://huggingface.co/nageshmashette/ddpm-butterflies-128/': server certificate verification failed. CAfile: none CRLfile: none

### ISSUE THREAD

**Issue by NageshMashette** [huggingface/diffusers#3491]
after running 10 to 20 epochs i am getting error like:-
OSError: fatal: unable to access 'https://huggingface.co/nageshmashette/ddpm-butterflies-128/': server certificate verification failed. CAfile: none CRLfile: none

but while running 1 or 2 epochs its running fine and getting results. please help on this issue.

**Comment by patrickvonplaten** [comment]
Hey @NageshMashette,

This sounds like there was a problem with your internet connection, could you try again?

**Comment by NageshMashette** [comment]
Hi @patrickvonplaten ,
  i tried once again still its same error after running some epoch, i.e i tried 0-20 epochs still its same.

**Comment by patrickvonplaten** [comment]
Can you add a reproducible code snippet?

**Comment by NageshMashette** [comment]
Thanks @patrickvonplaten its SSL related issue. solved it thanks.
