### ISSUE TITLE
'StableDiffusionInpaintPipeline' has no attribute 'from_ckpt'

### ISSUE THREAD

**Issue by Pirog17000** [huggingface/diffusers#3497]
### Describe the bug

Title is self-explanatory. There's no way to load inpaint model from safetensors using from_ckpt

I'm using the same approach as written in 'Load Safetensors' docs page:
```
pipeline = StableDiffusionPipeline.from_ckpt(
    "https://huggingface.co/WarriorMama777/OrangeMixs/blob/main/Models/AbyssOrangeMix/AbyssOrangeMix.safetensors"
)
```

but for Inpaint pipeline it doesn't work:
`pipe = StableDiffusionInpaintPipeline.from_ckpt("downloaded_inpaint_model.safetensors")`
throws an error 'StableDiffusionInpaintPipeline' has no attribute 'from_ckpt'

Maybe I'm just doing something wrong or understood it wrong and inpaint models should be loaded from safetensor other way?

### Reproduction

-

### System Info

- `diffusers` version: 0.17.0.dev0           
- Platform: Windows-10-10.0.19045-SP0        
- Python version: 3.10.9                     
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.13.2            
- Transformers version: 4.28.1
- Accelerate version: 0.17.0.dev0
- xFormers version: 0.0.17+57edbb7.d20230228

**Comment by Pirog17000** [comment]
pipe = StableDiffusionInpaintPipeline.from_ckpt("downloaded_inpaint_model.safetensors", use_safetensors=True) 
loads the pipeline, but later on throws another error:

```
Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape
torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is
torch.Size([320, 4, 3, 3]).
```

**Comment by Pirog17000** [comment]
converted file with `--num_in_channels 9` into diffusers, expected to see single 'safetensors', got a folder with bunch of safetensors. Anyway, seems it's working, but not as expected from the beginning :)

_Any way to convert 'to diffusers into single .safetensors file and read it easily?'_

**Comment by patrickvonplaten** [comment]
Will try to make sure that the `StableDiffusionInpaintPipeline` also works with native SD v1-5 checkpoint.

**Comment by patrickvonplaten** [comment]
See: https://github.com/huggingface/diffusers/pull/3533

**Comment by sayakpaul** [comment]
Since #3533 is merged, I am closing this issue. Feel free reopen in case problems persist.
