### ISSUE TITLE
Textual Inversion Embedding & Compel Library

### ISSUE THREAD

**Issue by alexisrolland** [huggingface/diffusers#3501]
I'm trying to use Textual Inversion Embeddings in my current implementation of diffusers. After multiple tests I came to realize it did not work because I was using Compel to convert my prompt into embeddings. When removing Compel and passing the prompt directly to diffusers inference method it worked.

What is not clear to me:

- is the problem because textual inversion embeddings are not supported when doing inference with prompt_embeds?
- is the problem because of the way Compel creates the prompt embeddings?

What would be nice:

- To have an API / example how to convert a prompt to embeddings with diffusers / without Compel.
- To have an API / example how to do inference with prompt_embeds and Textual Inversion Embeddings.

To some degree, I think this brings back the question of diffusers relying on Compel for prompt weighting which is an essential feature. It would make sense to me diffusers would natively support that and ensure compatibility with other features at the same time.

**Comment by alexblattner** [comment]
would you like to use the A1111 format instead? I have code for that

**Comment by patrickvonplaten** [comment]
Hey @alexisrolland, 

Thanks for the issue! I see how this can be a problem currently. Can you maybe add a quick code snippet that shows your use case? I'll give it a thought on how we can solve this

**Comment by StephanGocht** [comment]
There is a related issue in the compel github ( https://github.com/damian0815/compel/issues/28 ).

**Comment by alexisrolland** [comment]
Hi @patrickvonplaten 

I have finally produced a self-contained piece of code to reproduce the issue. It seems that using `maybe_convert_prompt` solves the problem but to be honest I don't know if that makes sense.

# Example without textual inversion embedding
```py
from compel import Compel
from diffusers import StableDiffusionPipeline
import io
import torch

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
compel = Compel(tokenizer=pipe.tokenizer, text_encoder=pipe.text_encoder)

prompts = ["charturnerv2, multiple views of the same character in the same outfit, a character turnaround of a woman wearing a black jacket and red shirt, best quality, intricate details."]
prompt_embeds = compel(prompts)
generator = torch.Generator("cuda").manual_seed(1)
image = pipe(prompt_embeds=prompt_embeds, num_inference_steps=50, num_images_per_prompt=1, generator=generator).images[0]

# Save image
data = io.BytesIO()
image.save(data, format='png')
data = data.getvalue()
with open('/tmp/embeddings/image.png', 'wb') as f:
    f.write(data)
```

Result:
![image](https://github.com/huggingface/diffusers/assets/13064696/4675f09c-35b0-47b1-a96a-deb341bbb3a4)

# Example with textual inversion embedding - KO

The embedding does not seem to have the desired effect

```py
pipe_ti = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
pipe_ti.load_textual_inversion("/tmp/embeddings/charturnerv2.pt", token="charturnerv2")
compel = Compel(tokenizer=pipe_ti.tokenizer, text_encoder=pipe_ti.text_encoder)

prompts = ["charturnerv2, multiple views of the same character in the same outfit, a character turnaround of a woman wearing a black jacket and red shirt, best quality, intricate details."]
prompt_embeds = compel(prompts)
generator = torch.Generator("cuda").manual_seed(1)
image = pipe_ti(prompt_embeds=prompt_embeds, num_inference_steps=50, num_images_per_prompt=1, generator=generator).images[0]

# Save image
data = io.BytesIO()
image.save(data, format='png')
data = data.getvalue()
with open('/tmp/embeddings/image_2.png', 'wb') as f:
    f.write(data)
```

Result:
![image_2](https://github.com/huggingface/diffusers/assets/13064696/eda2d0c3-e4d7-4862-bf95-02d2cb394869)

# Example with textual inversion embedding and `maybe_convert_prompt` - Seems OK

```py
pipe_ti_bis = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
pipe_ti_bis.load_textual_inversion("/tmp/embeddings/charturnerv2.pt", token="charturnerv2")
compel = Compel(tokenizer=pipe_ti_bis.tokenizer, text_encoder=pipe_ti_bis.text_encoder)

prompts = ["charturnerv2, multiple views of the same character in the same outfit, a character turnaround of a woman wearing a black jacket and red shirt, best quality, intricate details."]
prompts = pipe_ti_bis.maybe_convert_prompt(prompts, pipe_ti_bis.tokenizer)
prompt_embeds = compel(prompts)
image = pipe_ti_bis(prompt_embeds=prompt_embeds, num_inference_steps=50, num_images_per_prompt=1, generator=generator).images[0]

# Save image
data = io.BytesIO()
image.save(data, format='png')
data = data.getvalue()
with open('/tmp/embeddings/image_3.png', 'wb') as f:
    f.write(data)
```

Result:
![image_3](https://github.com/huggingface/diffusers/assets/13064696/6fd6caf4-5c31-4ecd-8637-d94385926cbc)

**Comment by pdoane** [comment]
@patrickvonplaten - there is a solution to this is in damian0815/compel#29 that uses Compel's interface for multi-vector embeddings.  Calling `maybe_convert_prompt` externally works in many situations but isn't robust (e.g. if an embedding token exists in a useLora(...) section).  As a minor point, it would be possible to implement a more efficient version of the textual inversion manager with some changes to the diffusers data structures but I doubt it's worth it.

@damian0815 - will you be able to review the PR soon?

**Comment by patrickvonplaten** [comment]
Also slightly related: https://github.com/huggingface/diffusers/pull/3588#issuecomment-1569752038

**Comment by damian0815** [comment]
sorry for being slow @pdoane - your PR is in compel 1.1.6
