### ISSUE TITLE
I made the most sophisticated pipeline thus far but I broke some rules

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#3502]
My pipeline can divide an area into multiple areas and can use multicontrolnet at the same time. The only 2 things my pipeline can't do are upscaling and img2img (can't use loras when loading from ckpt either). here's the pipeline:
[Pipeline.txt](https://github.com/huggingface/diffusers/files/11528093/Pipeline.txt)

here's how to use it:
```
pipe = MultiStableDiffusion.from_pretrained("runwayml/stable-diffusion-v1-5",torch_dtype=torch.float16,safety_checker=None,requires_safety_checker=False).to("cuda")
prompt=["a beautiful park","shining hot ((sun)) (((round)))","beautiful sky, beautiful clouds, beautiful sunset, beautiful sunrise, beautiful weather, beautiful day"]
negative_prompt=["a dark park","worst quality","a beautiful park"]
promptE=[]
negative_promptE=[]
for i in range(len(prompt)):
    cond, uncond =text_embeddings(pipe,prompt[i],negative_prompt[i], clip_stop_at_last_layers=2)#I use takuma's code
    promptE.append(cond)
    negative_promptE.append(uncond)
generator = torch.manual_seed(2733424006)
buffer=open('Untitled.png', 'rb')
buffer.seek(0)
image_bytes = buffer.read()
imageM = Image.open(BytesIO(image_bytes))
buffer=open('Untitled1.png', 'rb')
buffer.seek(0)
image_bytes = buffer.read()
imageM1 = Image.open(BytesIO(image_bytes))
pos=["0:0-512:512",imageM1,imageM]  #the way this works is if it's a string "startingX:startingY-endingX:endingY" the first one has to cover all the image for this to work
mask_types=[1,16,2] #strength priority. this means that the first prompt is the weakest and the middle one the strongest
loras_apply={1:["67464"]}
# controlnet = ControlNetModel.from_pretrained("lllyasviel/control_v11p_sd15_openpose", local_files_only=True,torch_dtype=torch.float16).to("cuda")
# pipe.loadControlnet(controlnet)    this is a line that exists no where else. I made this option in case we want to use controlnet or not
buffer=open('pose.png', 'rb')
buffer.seek(0)
image_bytes = buffer.read()
images = Image.open(BytesIO(image_bytes))
image = pipe(
    prompt=None,
    negative_prompt=None,
    prompt_embeds=promptE,
    negative_prompt_embeds=negative_promptE,
    pos=pos,
    # image=images,
    # controlnet_image=images,         this works exactly like the controlnet pipeline
    # controlnet_conditioning_scale=1.0,      this works exactly like the controlnet pipeline
    # loras_apply=loras_apply,            you need to use takuma's lora loader for this to work and add it to the top
    mask_types=mask_types,
    num_inference_steps=21,
    generator=generator,
    guidance_scale=7.0,
).images[0]
image.save("Lout2.png")
```

**Comment by SlZeroth** [comment]
is it possible to load multiple loras?

**Comment by SlZeroth** [comment]
because I want to inference with "<dog> and <cat>"

**Comment by alexblattner** [comment]
@SlZeroth the way you inference mutliple loras is the following:
in this line:

`loras_apply={1:["67464"]}`

we are applying lora 67464 to the second prompt. if you want multiple lora, just add more loras in the list. here's a more complex example:

`loras_apply={1:["67464","myLoraFolder/somelora.safetensors"],2:["anotherLora"],5:["anothernotherLora"]}`

in this example, I am applying "67464" and "myLoraFolder/somelora.safetensors" to the second prompt, "anotherLora" to the third and "anothernotherLora" to the sixth (doesn't exist in the code I wrote previously)

my code doens't read <dog:lora> and <cat:lora> instead, it loads those loras for the full relevant part and that's it. I think it works the same as what you wrote.

instead do something like this:
"dog and cat" as prompt and then at the same position, load the lora.

does that clarify everything? or is something unclear?

**Comment by alexblattner** [comment]
also, you need to have this to load loras:
[loraLoader.txt](https://github.com/huggingface/diffusers/files/11574009/loraLoader.txt)

**Comment by SlZeroth** [comment]
Thank you for your assistance! I do have another inquiry. When I'm learning to utilize dreambooth+lora via the kohya sdscript, the lora file size exceeds 100 megabytes. However, while using the train_dreambooth_lora.py script provided by diffusers, the file size is merely 3 megabytes. I've noticed that the output from diffusers/train_dreambooth_lora.py is significantly poor in comparison. Could you explain the disparity between the two situations? @alexblattner

**Comment by alexblattner** [comment]
I'm not on the team and have no idea. Sorry about that
