### ISSUE TITLE
The model is not loaded directly into `CUDA`

### ISSUE THREAD

**Issue by Mustapha-AJEGHRIR** [huggingface/diffusers#351]
### Describe the bug

In the [Getting started with Diffusers] https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/diffusers_intro.ipynb) notebook available in the README. The model is not automatically loaded into `CUDA` with :
```python
image_pipe = DDPMPipeline.from_pretrained("google/ddpm-celebahq-256")
```
Thes next cell `image_pipe()["sample"]` takes 2 hours instead of 2 minutes.
I have solved this with :
```python
image_pipe = DDPMPipeline.from_pretrained("google/ddpm-celebahq-256").to("cuda")
```

### Reproduction

Open the [Getting started with Diffusers] https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/diffusers_intro.ipynb) notebook in Colab. I tested this in the free version with `T4` GPU. 
The Following cell will take 2 houres instead of 2 minutes :
```python
images = image_pipe()["sample"]
````

### System Info

```shell
- Colab free version with `T4` GPU.
```

**Comment by patrickvonplaten** [comment]
Thanks a lot for the issue :heart:  I will fix this asap :-)

**Comment by patrickvonplaten** [comment]
Fixed! Thanks a lot for spotting this
