### ISSUE TITLE
Script for converting diffusers controlnet to original controlnet

### ISSUE THREAD

**Issue by iszotic** [huggingface/diffusers#3537]
**Is your feature request related to a problem? Please describe.**
Hi, I trained a controlnet with diffusers example and I want it in the original controlnet format.

**Describe the solution you'd like**
The same script as this one, but reversed, going from diffusers controlnet to original controlnet.
https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_controlnet_to_diffusers.py

**Comment by patrickvonplaten** [comment]
A better place for such a script might be the original ControlNet repo maybe?

**Comment by ghpkishore** [comment]
@patrickvonplaten Given that diffusers controlnet model naming of weights can differ and keep getting updated, Wouldn't it be better that the diffusers team provide the script for converting the controlnet model to original controlnet. There is also the additional fact that a lot of controlnet training happens using diffusers since it is easier to do so with the diffusers library. 

Any changes in the controlnet model would then mean updating the script as well, since the output format is fixed as per the original model which was released. These are just my thoughts, let me know what you think

**Comment by patrickvonplaten** [comment]
How difficult would it be to add `diffusers` to https://github.com/Mikubill/sd-webui-controlnet ? Would this something the community would like? I sadly really don't have the time to make sure all diffusers -> other_format works

Also note that we're actively working on integrating diffusers better into https://github.com/vladmandic/automatic

**Comment by ghpkishore** [comment]
@patrickvonplaten I am not sure how difficult it would be. i tried a few times before to try and get the ui extension to work with diffusers, but didn't understand which part of the code I would need to change. There is a huge demand with respect to controlnet atleast. It is one of the most used workflows for B2B usecases.

**Comment by ghpkishore** [comment]
@takuma104 If i remember correctly, the original script to convert controlnet from .pth to diffusers came from your repo, what are your views on this? Do you think this is something trivial and unnecessary or do you think the file which converts the checkpoints from .pth to diffusers, should also contain a reverse script from diffusers to .pth .

**Comment by takuma104** [comment]
@ghpkishore I have a conversion script that I created before, so please feel free to use it if you like. Considering that there seems to be a growing demand for it, I'm thinking about opening a PR to put it in /script.

https://github.com/huggingface/diffusers/issues/3015#issuecomment-1500917937

**Comment by ghpkishore** [comment]
Thanks @takuma104 really appreciate this. On a side note, have you seen the glyph control (https://github.com/AIGText/GlyphControl-release/issues/2#issuecomment-1577861535) , the one which produces text for SD. It is supposed to be based on SD. It is trained with v2. Any ideas on working with it? I asked the repo authors and they mentioned it is possible to extract the controlnet from that. They haven't given any way yet. Do you know how it can be done. There is this link: https://github.com/Mikubill/sd-webui-controlnet/blob/main/extract_controlnet.py . I wanted to know if this would work given that it is trained with a different architecture .
