### ISSUE TITLE
Question about main_process_first

### ISSUE THREAD

**Issue by cnnAndBn** [huggingface/diffusers#3539]
Hi, @sayakpaul  @patrickvonplaten 
sayakpaul
  I am new to diffuser lib and accelerator ,  in the example/train_text_to_image.py  https://github.com/huggingface/diffusers/blob/c13dbd5c3a53017d27de35ad77b8d57f04c8ec7c/examples/text_to_image/train_text_to_image.py#L700
     I see the main_process_first is called, I am confused about this. Is it necessary to  use it?  why should the main process do the operation first? 

   Thanks a lot！

**Comment by sayakpaul** [comment]
Thanks for your question. 

We recommend posting such questions on our [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63) or on [Discord](https://discuss.huggingface.co/t/join-the-hugging-face-discord/11263).

Now, to answer your question, we do this to ensure a deterministic shuffle order.

**Comment by cnnAndBn** [comment]
Thanks for your quick reply!😀
Ok I would ask the question on your recommanded place since this question.
But I still not very clear about why let the main process do first can ensure a  deterministic shuffle order. 
Addtionally, I see you  pass the seed to the shuffle function, so every process can get the same seed value which can make sure each of them gets the same dataset?

Thanks again! hope your answer😍
