### ISSUE TITLE
Can't control cache directory

### ISSUE THREAD

**Issue by spencerkohan** [huggingface/diffusers#3545]
**What API design would you like to have changed or added to the library? Why?**

I would like to be able to control the cache directory for pipelines.

The HF Datasets library already has a good solution for thie: https://huggingface.co/docs/datasets/cache:
- The cache directory can be set through an environment variable
- The cache dir can be set via a parameter on individual load operations

**What use case would this enable or better enable? Can you give us a code example?**

I'm running Diffusers in the context of a docker container.  Currently I am not able to set the cache location (maybe this is possible but it's not documented so it's not discoverable) and so I need to download the models each time I restart the docker container.

I would like to be able to set the cache to a location where I can attach a volume, so that I can cache data between runs and save time on this lengthy step before I can start working.

**Comment by patrickvonplaten** [comment]
Hey @spencerkohan,

Can you try using: https://huggingface.co/docs/diffusers/v0.16.0/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.from_pretrained.cache_dir ?
