### ISSUE TITLE
Open Parti Prompts: The better way to evaluate diffusion models.

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#3548]
Quantitative measures like FID or CLIP-score say very little about image quality in practice, better measures are needed!

Introducing Open Parti Prompts, a community-driven approach to compare models with human preference ❤️

The leaderboard is live and can be accessed here:

👉 https://huggingface.co/spaces/OpenGenAI/parti-prompts-leaderboard

Open Parti Prompts is based on the community's preferences that state to what percentage a model is on average preferred over other state-of-the-art models.

Your preference counts! You can contribute to the leaderboard by playing a round of "What AI model is best for you?":

👉 https://huggingface.co/spaces/OpenGenAI/open-parti-prompts

You are shown several images and you select the one you think best matches the prompt. You don't know which model generated which image.

The prompts are taken from Google's well-curated [Parti Prompts dataset](https://huggingface.co/datasets/nateraw/parti-prompts).

The dataset includes 1600 prompts of different challenges and categories such as "Properties & Positioning" and "World knowledge".

![Open Parti Prompts](https://github.com/huggingface/diffusers/assets/23423619/e80d4498-a516-4253-b37e-9e86d990c641)

**Comment by Abhinay1997** [comment]
@patrickvonplaten the space is down. Just a heads up.

**Comment by pcuenca** [comment]
> @patrickvonplaten the space is down. Just a heads up.

Both the leaderboard and the Space work for me. Can you please retry @Abhinay1997?

**Comment by Abhinay1997** [comment]
@pcuenca,  I still see a runtime error on the leaderboard space. Attached a screenshot for your reference. Do let me know if you need the entire log.
<img width="1411" alt="Screenshot 2023-06-09 at 4 51 34 PM" src="https://github.com/huggingface/diffusers/assets/24771261/8c4c71d4-eb58-45e8-8e69-f8cd693533c3">
