### ISSUE TITLE
[Pipelines] Support for Uni-ControlNet

### ISSUE THREAD

**Issue by wfng92** [huggingface/diffusers#3564]
### Model/Pipeline/Scheduler description

From the official repository, [Uni-ControlNet](https://github.com/ShihaoZhaoZSH/Uni-ControlNet) (All-in-One Control to Text-to-Image Diffusion Models) categorizes various conditions into two distinct groups: local conditions and global conditions. Accordingly, two additional adapters are added: local control adapter and global control adapter. 

![image](https://github.com/huggingface/diffusers/assets/43742196/4ed16453-a58b-4fb9-bec9-6dbc1b2f60ff)

Would be great to have Uni-ControlNet in `diffusers` module since it is built upon ControlNet.

Pinging ControlNet expert @takuma104 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

Paper: https://arxiv.org/abs/2305.16322
Code: https://github.com/ShihaoZhaoZSH/Uni-ControlNet
Project page: https://shihaozhaozsh.github.io/unicontrolnet/
Pre-trained models: https://drive.google.com/file/d/1lagkiWUYFYbgeMTuJLxutpTW0HFuBchd/view?usp=sharing

**Comment by alexblattner** [comment]
@patrickvonplaten I created a pipeline that lets users use a more precise version of https://github.com/opparco/stable-diffusion-webui-two-shot. It can also use multi controlnet at the same time and it can have loras applied to specific zones only.

Would that be valuable?

**Comment by kadirnar** [comment]
@patrickvonplaten , @alexblattner 

Can we do this using the diffusers library?

https://github.com/opparco/stable-diffusion-webui-two-shot

**Comment by alexblattner** [comment]
@kadirnar yes, my pipeline can do this better. Instead of dividing weirdly, I made it so you can make zones by specifying a starting point and ending point. Also, you can pass masks in my pipeline to specify areas to which you can apply loras  and prompts. it all works too.

**Comment by kadirnar** [comment]
Can you share the codes? Or open a pull request to add to the diffusers library? I really want to try this.

**Comment by alexblattner** [comment]
@kadirnar sadly it requires external code so it can't be used within diffusers as is. It isn't perfect by any means, just saying. I mean I could add that code inside the file on second though to mitigate that issue. it can be a bit too much of a hassle to do a pull request. I have never done a pull request so.... Oh well. I'll give it a shot and give you an update

**Comment by asomoza** [comment]
yes, we have them for Flux and SDXL, we still need one for SD 3.5 though.

**Comment by asomoza** [comment]
IMO we can close this and open a new one when there's one for SD 3.5 or other model. We can't add support before someone trained the model because the implementation varies depending on the model authors, e.g. SDXL one can use multiple conditions at the same time and the FLUX one can't.

**Comment by sayakpaul** [comment]
Agree. Closing this then
