### ISSUE TITLE
[examples/text_to_image] cuda out of memory, though I followed the instructions of train_text_to_image.py

### ISSUE THREAD

**Issue by N1cekiko** [huggingface/diffusers#3565]
### Describe the bug

when I ran the script: examples/text_to_image/text_to_image.py, using the follwing command:

export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export dataset_name="lambdalabs/pokemon-blip-captions"

python train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$dataset_name \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --max_train_steps=15000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir="sd-pokemon-model" \
  --mixed_precision="fp16"  

I tried to decrease the resolution and remove --center_crop --random_flip, it did not work.

The hardware I used: V100, 32GB
pytorch1.11

logs:

### Reproduction

[train_1p.txt](https://github.com/huggingface/diffusers/files/11571262/train_1p.txt)

### System Info

- `diffusers` version: 0.17.0.dev0
- Platform: Linux-5.4.0-60-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.5
- PyTorch version (GPU?): 1.11.0+cu102 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.29.1
- Accelerate version: 0.19.0
- xFormers version: not installed
- Using GPU in script?: <fill in> yes
- Using distributed or parallel set-up in script?: <fill in> neither 1p or 8p can work

**Comment by patrickvonplaten** [comment]
cc @sayakpaul here

**Comment by sayakpaul** [comment]
Could you paste the full error trace? Will need to check where does this stem from. 

Because for a 32 GB V100 card, this seems weird.

**Comment by N1cekiko** [comment]
![image](https://github.com/huggingface/diffusers/assets/38829641/11642118-7b5a-4943-b5df-119d4c19275b)

**Comment by N1cekiko** [comment]
I noticed that this bug is the same as the one mentioned in issue2094(https://github.com/huggingface/diffusers/issues/3094) , it has been closed though the prolem is not solved, could you please open the issue again?

**Comment by sayakpaul** [comment]
> I noticed that this bug is the same as the one mentioned in issue2094(https://github.com/huggingface/diffusers/issues/3094) , it has been closed though the prolem is not solved, could you please open the issue again?

We closed the issue because of https://github.com/huggingface/diffusers/issues/3094#issuecomment-1519293627.

Could you follow the suggestions shared in that thread and let us know if the issues still persist?

**Comment by N1cekiko** [comment]
I have tried, but still not working.

**Comment by sayakpaul** [comment]
Then please post a detailed thread including what have you already tried and their error logs. Without complete and comprehensive details, it's hard for us to suggest properly.

**Comment by N1cekiko** [comment]
Thanks for your kind reply and patience. Here are the launch scipts and the logs：
![image](https://github.com/huggingface/diffusers/assets/38829641/87777ec6-c1e6-44a5-b0d6-5e7c0a463506)

![image](https://github.com/huggingface/diffusers/assets/38829641/b3cbe411-369b-415f-a021-fb423373f63c)

**Comment by sayakpaul** [comment]
Interesting. 

Which library versions are you using?

@pcuenca if you have access to a 24 GB card, could you try to reproduce it once? I currently don't have access to one.

**Comment by N1cekiko** [comment]
I just git clone the latest master branch, and install diffusers locally; Then install the requirements for text_to_image.

**Comment by sayakpaul** [comment]
And what Torch version are you? Have you tried using memory efficient attention with xformers?

**Comment by N1cekiko** [comment]
I used pytorch1.11, without Xformers.

**Comment by sayakpaul** [comment]
Could you try with PyTorch 1.13.1 and xformers?

**Comment by medalwill** [comment]
I also encounter this problem, and degrading my Pytorch version doesn't work.
Then I found something, it seems that accelerate always works in the base environment.
So I abandon my conda virtual environment and degrade torch.
It works!!!!!
