### ISSUE TITLE
[New Pipeline]: Uni-ControlNet: All-in-One Control to Text-to-Image Diffusion Models

### ISSUE THREAD

**Issue by kadirnar** [huggingface/diffusers#3569]
Github: https://github.com/ShihaoZhaoZSH/Uni-ControlNet
Project Page: https://shihaozhaozsh.github.io/unicontrolnet/
Paper: https://arxiv.org/abs/2305.16322

**Comment by patrickvonplaten** [comment]
Duplicate of https://github.com/huggingface/diffusers/issues/3564

**Comment by kadirnar** [comment]
Thank you. Can you add this too?

Repo: https://github.com/SHI-Labs/Prompt-Free-Diffusion
HF Demo: https://huggingface.co/spaces/shi-labs/Prompt-Free-Diffusion
Paper: https://arxiv.org/pdf/2305.16223.pdf

**Comment by patrickvonplaten** [comment]
@kadirnar,

Could you open a new issue for this?

**Comment by kadirnar** [comment]
> Thank you. Can you add this too?
> 
> Repo: https://github.com/SHI-Labs/Prompt-Free-Diffusion HF Demo: https://huggingface.co/spaces/shi-labs/Prompt-Free-Diffusion Paper: https://arxiv.org/pdf/2305.16223.pdf

https://github.com/huggingface/diffusers/issues/3638
