### ISSUE TITLE
cannot disable downloading when loading ckpt

### ISSUE THREAD

**Issue by reveperdu** [huggingface/diffusers#3570]
### Describe the bug

I want to load a ckpt without Internet connection(to github, specifically), but loading the ckpt triggers downloading the config file from stable diffusion repo on github, even if it has been downloaded before, and local_files_only set to True.

### Reproduction

#no Internet connection
from diffusers import StableDiffusionPipeline
pipe=StableDiffusionPipeline.from_ckpt(local_ckpt_path,local_files_only=True)

### System Info

linux lite 6.0 (Ubuntu 22.04)
python 3.10.6
diffusers 0.16.1

**Comment by patrickvonplaten** [comment]
I see! Yes we need to allow to pass this argument: https://github.com/huggingface/diffusers/blob/66356e7dd5612ec19808891f99c52799efcd92be/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#LL979C5-L979C25 (the config file) 

also in the https://github.com/huggingface/diffusers/blob/66356e7dd5612ec19808891f99c52799efcd92be/src/diffusers/loaders.py#L1218 method . Would you like to open a PR here? :-)

**Comment by alexblattner** [comment]
this works:
```
pipe = MultiStableDiffusion.from_ckpt(
    "safetensors/deliberate.safetensors",local_files_only=True, torch_dtype=torch.float16,safety_checker=None,requires_safety_checker=False
).to("cuda")
```
MultiStableDiffusion is my pipeline but functionally similar to txt2img
