### ISSUE TITLE
"class_labels should be provided" in local upscaler pipeline

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#3573]
Hi, I'm getting this:

│ /usr/local/lib/python3.8/site-packages/torch/utils/_contextlib.py:115 in decorate_context        │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ /mecomics-api/utils/multiDiffusionUpscale.py:771 in __call__                                     │
│                                                                                                  │
│   768 │   │   │   │   │   │   # self.load_lora_weights(loras_apply.get(i))                       │
│   769 │   │   │   │   │   │   for j in loras_apply.get(i):                                       │
│   770 │   │   │   │   │   │   │   all_loras[j].alpha=1.0                                         │
│ ❱ 771 │   │   │   │   │   noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=   │
│   772 │   │   │   │   │   noise_preds.append(noise_pred)                                         │
│   773 │   │   │   │   │   if loras_apply is not None and loras_apply.get(i) is not None:         │
│   774 │   │   │   │   │   │   for j in loras_apply.get(i):                                       │
│                                                                                                  │
│ /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:1501 in _call_impl             │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /home/alexblattnershalom/.local/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.p │
│ y:691 in forward                                                                                 │
│                                                                                                  │
│   688 │   │                                                                                      │
│   689 │   │   if self.class_embedding is not None:                                               │
│   690 │   │   │   if class_labels is None:                                                       │
│ ❱ 691 │   │   │   │   raise ValueError("class_labels should be provided when num_class_embeds    │
│   692 │   │   │                                                                                  │
│   693 │   │   │   if self.config.class_embed_type == "timestep":                                 │
│   694 │   │   │   │   class_labels = self.time_proj(class_labels)                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: class_labels should be provided when num_class_embeds > 0

here's the upscaler pipeline:
[upscaler.txt](https://github.com/huggingface/diffusers/files/11576114/upscaler.txt)

here's the og custom pipeline:
[Pipeline.txt](https://github.com/huggingface/diffusers/files/11576118/Pipeline.txt)

**Comment by alexblattner** [comment]
@patrickvonplaten is there someone who can help with this by any chance?

**Comment by alexblattner** [comment]
I would also like to point out that this pipeline: 
[originalUpscaler.txt](https://github.com/huggingface/diffusers/files/11588993/originalUpscaler.txt)
has exactly the same problem and it is the same of the original pipeline except for the imports

**Comment by patrickvonplaten** [comment]
Hey @alexblattner,

Sorry could you provide a simple, minimal code snippet that I could copy-paste into a Python console to reproduce?

**Comment by alexblattner** [comment]
@patrickvonplaten something like this. the simplest possible way to my code. It's essentially the same as the most basic example possible. it is using originalUpscaler.txt (actually .py in the environment)
`
from utils.upscale import StableDiffusionUpscalePipeline
pipe=StableDiffusionUpscalePipeline.from_pretrained("stabilityai/stable-diffusion-x4-upscaler",torch_dtype=torch.float16)
image=pipe(image=image,prompt=prompt).images[0]
`

**Comment by alexblattner** [comment]
@patrickvonplaten the only difference with the og upscale pipeline is those imports:

import inspect
from typing import Callable, List, Optional, Tuple, Union, Dict, Any
from packaging import version
import numpy as np
import torch.nn.functional as F
import PIL
import torch
from transformers import CLIPImageProcessor, CLIPTextModel, CLIPTokenizer
import torchvision
from diffusers import DiffusionPipeline, ControlNetModel
from diffusers.configuration_utils import FrozenDict
from diffusers.loaders import LoraLoaderMixin, TextualInversionLoaderMixin,FromCkptMixin
from diffusers.image_processor import VaeImageProcessor
from diffusers.models import AutoencoderKL, UNet2DConditionModel
from diffusers.models.attention_processor import AttnProcessor2_0, LoRAXFormersAttnProcessor, XFormersAttnProcessor
from diffusers.pipelines.stable_diffusion import StableDiffusionPipelineOutput
from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker
from diffusers.schedulers import DDIMScheduler, LMSDiscreteScheduler, PNDMScheduler,KarrasDiffusionSchedulers,DDPMScheduler
from diffusers.utils import deprecate, is_accelerate_available, is_accelerate_version, logging, randn_tensor, replace_example_docstring,PIL_INTERPOLATION
from diffusers.models import ModelMixin
logger = logging.get_logger(__name__)  # pylint: disable=invalid-name

**Comment by alexblattner** [comment]
help anyone?
