### ISSUE TITLE
from_ckpt not working properly on windows

### ISSUE THREAD

**Issue by LyubimovVladislav** [huggingface/diffusers#3574]
### Describe the bug

When attempting to use the `StableDiffusionPipeline.from_ckpt()` with HF checkpoint link on Windows OS, a `HFValidationError` exception is raised. This issue stems from how the Path is processed in the code [here](https://github.com/huggingface/diffusers/blob/67cf0445ef48b1f913b90ce0025ac0c75673e32e/src/diffusers/loaders.py#L1366). On Windows, the `repo_id` and `file_path` will contain backslashes instead of forward slashes, resulting in an improper repo_id and file_path format. E.g., repo_id = 'runwayml\\\stable-diffusion-v1-5', file_path = 'blob\\\main\\\v1-5-pruned-emaonly.ckpt'
This issue is not present on Linux systems.

### Reproduction

```
from diffusers import StableDiffusionPipeline
StableDiffusionPipeline.from_ckpt('https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/v1-5-pruned-emaonly.ckpt')
```

### System Info

- Platform: Windows-10-10.0.19045-SP0
- `diffusers` version: 0.16.1
- Python version: 3.10.6
- Huggingface_hub version: 0.14.1

   <br>
- Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- `diffusers` version: 0.16.1
- Python version: 3.10.6
- Huggingface_hub version: 0.14.1

**Comment by patrickvonplaten** [comment]
Hey @LyubimovVladislav,

Thanks a mille for the issue! Would you like to open a pull request that makes sure the line: https://github.com/huggingface/diffusers/blob/67cf0445ef48b1f913b90ce0025ac0c75673e32e/src/diffusers/loaders.py#L1366 and following work both on Linux and Windows? 

I sadly don't have a Windows computer to test this
