### ISSUE TITLE
What sampler does the official Runway ML demo use?

### ISSUE THREAD

**Issue by phokphokphok** [huggingface/diffusers#3575]
What sampler does the official Runway ML demo use? https://runwayml-stable-diffusion-v1-5.hf.space/
I get much more creative results using this instead of A111 locally and I want to replicate it

**Comment by patrickvonplaten** [comment]
The demo uses the DPM-MultiStepSampler from the amazing @LuChengTHU . See here: https://huggingface.co/docs/diffusers/api/schedulers/multistep_dpm_solver#diffusers.DPMSolverMultistepScheduler
