### ISSUE TITLE
[Pipelines] Support for Mixture of Diffusers

### ISSUE THREAD

**Issue by kadirnar** [huggingface/diffusers#3583]
Github: https://github.com/albarji/mixture-of-diffusers
Paper: https://arxiv.org/abs/2302.02412
HF Demo: https://huggingface.co/spaces/albarji/mixture-of-diffusers

**Comment by sayakpaul** [comment]
IIUC the authors already provide the pipeline in their codebase. So, I would maybe prefer it if the users follow their codebase for this. 

@patrickvonplaten WDYT?

**Comment by kadirnar** [comment]
I want to add this because I want to use pip package.

**Comment by bghira** [comment]
wouldn't it also be feasible to use this plus Controlnet Tiles to break a single image into tiles and upscale and then possibly inpaint the seams?
