### ISSUE TITLE
Adding Daam

### ISSUE THREAD

**Issue by isamu-isozaki** [huggingface/diffusers#3599]
**Is your feature request related to a problem? Please describe.**
This is a feature request. I think it'll be nice to add in daam from [here](https://github.com/castorini/daam) to diffusers. This is a way to get the attention maps from each token to see their contributions for generation like this
![example](https://github.com/huggingface/diffusers/assets/23430101/7dd03aae-490e-41a9-86db-c94731da53bb)
The paper for this tech is [here](https://arxiv.org/abs/2210.04885)
**Describe the solution you'd like**
When I get some time, I'm planning to make a pr but feel free for anyone to take this one!

**Comment by sayakpaul** [comment]
Is it similar to [Attend and Excite](https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/attend_and_excite)? 

Cc: @hila-chefer

**Comment by okaris** [comment]
I have needed to expose the attention maps several time while implementing some of the new papers (Example #3719) @sayakpaul do you think it makes sense to expose the attention maps in the return output of unet_2d_condition ?

**Comment by sayakpaul** [comment]
> @sayakpaul yup kind of! That+the cross attention vis! Ah, does diffusers already have cross-attention map visualization via attend and excite? That's pretty much what I wanted

We don't have a direct visualization but the original Attend and Excite [repository](https://github.com/yuval-alaluf/Attend-and-Excite) provides tooling for that. 

@isamu-isozaki

**Comment by sayakpaul** [comment]
> I have needed to expose the attention maps several time while implementing some of the new papers (Example #3719) @sayakpaul do you think it makes sense to expose the attention maps in the return output of unet_2d_condition ?

Is it possible to use the same design as [Attend and Excite](https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/attend_and_excite) or [Pix2Pix Zero](https://huggingface.co/docs/diffusers/main/en/api/pipelines/pix2pix_zero) for that? I think we would not want to change the output types of the models just yet. @patrickvonplaten @williamberman WDYT?

**Comment by williamberman** [comment]
I'm hesitant to include this in diffusers source. Could we have an explanation of what the third party library accomplishes, approximately how many people are using it and what for, and what the architectural necessity is for it to be in source formally?

If it can be added in a very small number of lines of code, I'm more inclined to include it but scanning their source it's between 100 and 1000 loc

There's libraries like compel https://github.com/damian0815/compel that we recommend in our docs but don't maintain in source

**Comment by isamu-isozaki** [comment]
@sayakpaul  Sry for the late reply and interest. I was thinking of doing something like CLIPTextModel where we can have an optional argument output_attentions for getting access to the attention maps in the pipeline so that it's more consistent but I like basing on existing sources like that too.

**Comment by isamu-isozaki** [comment]
@williamberman The library mainly 
1. Gets the cross-attention maps from the text encoder
2. Averages them across all cross attention maps(so you have the average attention per token location for all attention maps)
3. Interpolate to output image size so we can see the contribution of each token in a way
I personally think just optionally outputting the attention maps in step 1 might be enough with say a separate independent function that can do steps 2 and 3. We can definitely start off with a community pipeline. I can prob copy the stable diffusion pipeline and the changes might be lower than 100 lines I think.

**Comment by isamu-isozaki** [comment]
oh yup, my idea is pretty much what @okaris is thinking. @okaris am I right in that it be done without much changes?

**Comment by williamberman** [comment]
Yeah that sounds like it should be maintained outside of source unless we see a lot of requests for it
