### ISSUE TITLE
how to merge inpainting diffusion model using checkpoint_merger.py

### ISSUE THREAD

**Issue by yanchaoguo** [huggingface/diffusers#3600]
当我使用下面方法进行merger时 报错了：
merged_pipe = pipe.merge([ "runwayml/stable-diffusion-inpainting",  "andite/anything-v4.0", "runwayml/stable-diffusion-v1-5"], local_files_only=False, safety_checker=None, force = True, interp = "add_diff", alpha = 1).to("cuda", torch_dtype=torch.float16)

error：
│   285 │   def add_difference(theta0, theta1, theta2, alpha):                                     │
│ ❱ 286 │   │   return theta0 + (theta1 - theta2) * (1.0 - alpha)                                  │
│   287                                                                                            │
 
**RuntimeError: The size of tensor a (9) must match the size of tensor b (4) at non-singleton dimension 1**
@pcuenca

**Comment by sayakpaul** [comment]
Could you provide a fully reproducible code snippet for this? Ideally a Colab Notebook.

**Comment by Abhinay1997** [comment]
@yanchaoguo , it fails while merging the unets of "runwayml/stable-diffusion-inpainting" with the others. The unets weights might have different shapes so it'll fail while merging. 

I was able to merge  "runwayml/stable-diffusion-v1-5" and "andite/anything-v4.0" without any issues
