### ISSUE TITLE
Torch.compile dynamic input support

### ISSUE THREAD

**Issue by AlphaAtlas** [huggingface/diffusers#3603]
`torch.compile` support in diffusers is interesting in theory, but in reality users tend to change settings, use extensions and swap stuff out, forcing lengthy recompiles whenever that happens. Dynamic input support would help mitigate this.

I am testing stable diffusion with `pipe.unet = torch.compile(pipe.unet, dynamic=True)`, and the current blocker (with pytorch/triton nightly) is https://github.com/pytorch/pytorch/issues/101228

I figured I should repost the issue here. Is there anything that can help on diffuser's end?

**Comment by djj0s3** [comment]
any update here? +1 would be nice

**Comment by AlphaAtlas** [comment]
It was supposedly solved upstream, but I have been away from my PC for a month and havent tested it yet.

**Comment by patrickvonplaten** [comment]
Torch 2.1 will come out soon - we'll test everything then!

**Comment by Metal079** [comment]
Seems to still not work, can I get a confirmation thats the case?

**Comment by aiXander** [comment]
Also hoping dynamic compile might work at some point... +1
