### ISSUE TITLE
Readme image is broken

### ISSUE THREAD

**Issue by FarukOzderim** [huggingface/diffusers#3611]
Looks like the readme image is somehow broken.

<img width="422" alt="image" src="https://github.com/huggingface/diffusers/assets/44067394/e88be2ea-e4c2-4379-8a35-45ce1fe89441">

**Comment by patrickvonplaten** [comment]
Thanks for the issue - should be fixed here: https://github.com/huggingface/diffusers/commit/a359ab4e29c8cc064bde3c828d35912fb15c9bd2
