### ISSUE TITLE
train dreambooth out of gpu memory with torch2.0

### ISSUE THREAD

**Issue by conansherry** [huggingface/diffusers#3613]
### Describe the bug

if torch version is 2.0 and not use --use_8bit_adam, will out of memory.
but use --use_8bit_adam, result is wrong.

when i change torch version to 1.13, everything is ok.

### Reproduction

below is shell command
`
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="./dog"
export CLASS_DIR="path_to_class_images"
export OUTPUT_DIR="path_to_saved_model"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --train_text_encoder \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of sks dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_checkpointing \
  --learning_rate=2e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=800
`

### System Info

My gpu is RTX 3090, 24G memory. difussers=0.16.1

**Comment by TANZHAOJIE** [comment]
I have met the similar problem, 4090 24g vram got oom error when using torch 2.0, but no problem when swiched to torch 1.13.1

**Comment by sayakpaul** [comment]
Check some comments here too:
https://github.com/huggingface/diffusers/issues/3565#issuecomment-1567984137

**Comment by patrickvonplaten** [comment]
Actually same here, I've also experienced problems with torch 2.0 - not really sure why :-/ Maybe we should contact the Pytorch team here cc @pcuenca @sayakpaul

**Comment by sayakpaul** [comment]
See the internal [thread](https://huggingface.slack.com/archives/C04DBJ0HLH1/p1685943719616849).

**Comment by pcuenca** [comment]
@sayakpaul similar results as in the other issue.

- Torch 2.0.1, dreambooth with text_encoder: 26 GB (OOM in 3090)
- Torch 2.0.1, dreambooth without text_encoder: 24 GB (fits)
- Torch 1.13.1 + xFormers, with text_encoder: 14 GB

**Comment by patrickvonplaten** [comment]
Interesting there is clearly a problem then with PT 2.0 it seems cc @Chillee as well

**Comment by Chillee** [comment]
I assume this is without compilation? cc: @drissguessous

**Comment by simonnxren** [comment]
anybody solve this issue? I got the same error on text2image training.

**Comment by medalwill** [comment]
> anybody solve this issue? I got the same error on text2image training.

Try to degrade ur torch version and do not use conda virtual environment. Maybe it can help.

**Comment by medalwill** [comment]
您好，您的邮件已收到！祝好！Get it! Best regard!

**Comment by sayakpaul** [comment]
> it seems accelerate have some problem with torch2.0? will it be solved in the future?

Any particular incidents that suggest so? It could very well be the case that Torch 2.0 SDPA backward pass is slower than that of xformers. 

But just in case, I am tagging @muellerzr. Zach, have you faced any instances of weird memory problems in Torch 2.0 and not in Torch 1.13.1 (for same code)?

**Comment by krNeko9t** [comment]
> > it seems accelerate have some problem with torch2.0? will it be solved in the future?
> 
> Any particular incidents that suggest so? It could very well be the case that Torch 2.0 SDPA backward pass is slower than that of xformers.
> 
> But just in case, I am tagging @muellerzr. Zach, have you faced any instances of weird memory problems in Torch 2.0 and not in Torch 1.13.1 (for same code)?

sorry, i made a mistake. i encountered this promblem today. while reinstalling my virtual env, some package force me to use pytorch2.0. At the start i thought it is accelerate, but found out it's xformers instead.
