### ISSUE TITLE
Tutorial 'Effective and efficient diffusion' gets an import error.

### ISSUE THREAD

**Issue by lhaippp** [huggingface/diffusers#3622]
### Describe the bug

Hi,

Thanks for the great job!
There is a minor error in the tutorial [https://huggingface.co/docs/diffusers/stable_diffusion](https://huggingface.co/docs/diffusers/stable_diffusion), Tutorial 'Effective and efficient diffusion', the section of 'Memory'

![image](https://github.com/huggingface/diffusers/assets/22257640/2fdf7bdf-d900-4c8a-b9c3-8a2a146a5fa6)

```
rather than from PIL import image
it should be from PIL import Image
```

### Reproduction

```
![image](https://github.com/huggingface/diffusers/assets/22257640/752c46a9-9be1-4b7a-901c-401df41408a2)

rather than from PIL import image
it should be from PIL import Image
```

### System Info

latest

**Comment by stevhliu** [comment]
Thanks for raising this issue! It's been fixed on the [`main`](https://huggingface.co/docs/diffusers/main/en/stable_diffusion#memory) version of the docs :)

**Comment by sayakpaul** [comment]
Closing the issue then.
