### ISSUE TITLE
Inpainting pipeline throws exception when providing latents

### ISSUE THREAD

**Issue by reimager** [huggingface/diffusers#3631]
### Describe the bug

After [this](https://github.com/huggingface/diffusers/commit/d114d80fd2b5a1b7c5f3d2ec67b92a442d8f18f9) commit if I call the inpaint pipeline with latents I get:

```
<cut>
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/src/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 937, in __call__
    latents_outputs = self.prepare_latents(
  File "/usr/local/src/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 662, in prepare_latents
    outputs += (noise,)
UnboundLocalError: local variable 'noise' referenced before assignment
```

because return_noise is True, but since I have provided latents noise is undefined

### Reproduction

Call the inpaint pipeline with latents:

```
    args = {
        "prompt_embeds": prompt_embeds,
        "negative_prompt_embeds": negative_prompt_embeds,
        "image": [image_input]*batch_size,
        "mask_image": image_mask,
        "width": width,
        "height": height,
        "guidance_scale": guidance_scale,
        "num_inference_steps": steps,
        "latents": latents,
    }
    pipe(**args)
```

### System Info

- `diffusers` version: 0.17.0.dev0
- Platform: Linux-5.10.0-23-amd64-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.1.0a0+fe05266 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.30.0.dev0
- Accelerate version: 0.20.0.dev0
- xFormers version: 0.0.21+a205b24.d20230531
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by sayakpaul** [comment]
@reimager could you also provide a full snippet? That will be very easy for us to reproduce the error.

**Comment by reimager** [comment]
> @reimager could you also provide a full snippet? That will be very easy for us to reproduce the error.

```
import torch
from PIL import Image
from pytorch_lightning import seed_everything
from diffusers.utils import load_image
from diffusers import (
    StableDiffusionInpaintPipeline,
)
from diffusers.schedulers import (
    EulerAncestralDiscreteScheduler,
)

mask = load_image("http://metaloft.com/images/depth-mask.png").convert("RGBA")
image = load_image("http://metaloft.com/images/depth-input.png").convert("RGB")

model = "runwayml/stable-diffusion-inpainting"
scheduler = EulerAncestralDiscreteScheduler.from_pretrained(model, subfolder="scheduler", use_karras_sigmas=True)
pipe = StableDiffusionInpaintPipeline.from_pretrained(model, torch_dtype=torch.float16, revision="fp16", scheduler=scheduler)
pipe.to("cuda")
pipe.enable_xformers_memory_efficient_attention()

batch_size = 1
channels = 4
downsampling_factor = 8
width, height = image.size
latents = torch.randn([batch_size, channels, height // downsampling_factor, width // downsampling_factor], device="cuda").to(torch.float16)

args = {
    "prompt": "a dog",
    "image": [image]*batch_size,
    "mask_image": mask,
    "guidance_scale": 7.0,
    "width": width,
    "height": height,
    "num_inference_steps": 20,
    "latents": latents,
}
result = pipe(**args)
result.images[0].save(f"output.png")
```

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu can you check this. I think we should be able to handle this soon with your PR

**Comment by yiyixuxu** [comment]
@patrickvonplaten 
I don't think it's related to my PR at all 😅 since they are trying to pass the initial noise (vs trying to pass the image latent directly which would be the use case that the PR handles)

fixed here https://github.com/huggingface/diffusers/pull/3641

**Comment by sayakpaul** [comment]
@reimager could you install `pip git+https://github.com/huggingface/diffusers@fix-inpaint` and see if the error resolved?

**Comment by reimager** [comment]
@sayakpaul sorry just saw this. It looks like its already merged.
I ran my tests against head and everything looks good. Thank you!
