### ISSUE TITLE
[Need Help] Training or Finetune on `stable_diffusion_controlnet_inpaint.py` (inpaintinig pipeline with stable diffusion and controlnet)

### ISSUE THREAD

**Issue by wuyujack** [huggingface/diffusers#3645]
Hi all,

I am looking for some references to create a training/finetune file for the [stable_diffusion_controlnet_inpaint.py](https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_controlnet_inpaint.py). I have looked at the file like [train_controlnet.py](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py) and [train_dreambooth.py](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py), but have no luck to create a runnable training pipeline for inpainting. It would be much appreciated if someone could give some references or hints on this :)

**Comment by patrickvonplaten** [comment]
Actually, it should be pretty straight-forward to adapt the controlnet training: https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py for inpainting no? Instead of just orig image and control image, we need orig image, mask, new image and control orig image. Think it shouldn't be too difficult to get this to work using https://huggingface.co/runwayml/stable-diffusion-inpainting as a base model.

**Comment by patrickvonplaten** [comment]
Could be a cool side project to train canny controlnet not on SD v1-5 but on SD inpainting

**Comment by kadirnar** [comment]
> Hi all,
> 
> I am looking for some references to create a training/finetune file for the [stable_diffusion_controlnet_inpaint.py](https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_controlnet_inpaint.py). I have looked at the file like [train_controlnet.py](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py) and [train_dreambooth.py](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py), but have no luck to create a runnable training pipeline for inpainting. It would be much appreciated if someone could give some references or hints on this :)

https://github.com/huggingface/diffusers/tree/main/examples/research_projects/dreambooth_inpaint ?

**Comment by wuyujack** [comment]
@kadirnar @patrickvonplaten  Thank you for your insights and I have read the [dreambooth_inpaint](https://github.com/huggingface/diffusers/tree/main/examples/research_projects/dreambooth_inpaint) but the thing is not that trivial as I was thought :(

I am still debugging, like writing my own train dataset to load the `mask` and `masked_image`, and working on making the training doable :(

**Comment by engrmusawarali** [comment]
How do we create weights for the controlnet inpaint which uses stable diffusion inpaint as backbone.

**Comment by DN6** [comment]
@engrmusawarali Could you please ask "how to" questions in the [discussion section](https://github.com/huggingface/diffusers/discussions).

**Comment by engrmusawarali** [comment]
@DN6 https://github.com/huggingface/diffusers/discussions/6684
