### ISSUE TITLE
How much VRAM is required to finetune "CompVis/stable-diffusion-v1-4" model ? 

### ISSUE THREAD

**Issue by atharmzaalo2023** [huggingface/diffusers#3648]
I am trying to finetune the above mentioned model on "lambdalabs/pokemon-blip-captions" dataset , My GPU config is as follows, I am using single Tesla T4 with 15.36 GB VRAM , while fine tuning it on pokemon blip captions dataset using the examples provided [here](https://github.com/huggingface/diffusers/tree/main/examples/text_to_image) , I am running into CUDA out of memory error , can anyone please give suggestion on how we can train this script on the above mentioned machine , I tried increasing gradient accumulation steps and reducing image size and also fp16  but that doesnt  work.

**Comment by patrickvonplaten** [comment]
cc @sayakpaul do you have numbers here? IF you just use LoRA I think you can get away with just 15GB RAM

**Comment by sayakpaul** [comment]
When we added support for LoRA to that example, I clearly remember having been able to run that on a Tesla T4. With LoRA, this should be quite possible as suggested in the [docs](https://huggingface.co/docs/diffusers/main/en/training/lora#texttoimage) too. 

Cc: @pcuenca as well.

**Comment by atharmzaalo2023** [comment]
Thanks I will try running Lora

**Comment by doem97** [comment]
Hi all @sayakpaul do you remember the least VRAM for fine-tuning this sd v1.4 or v1.5? I am using 3090 (24G) whereas bs=1 and acc_step=8 still lead to the OOM problem. I think the base model is so big that those bs or acc_step configs even didn't start to work.

**Comment by sayakpaul** [comment]
Are you using LoRA here? Which script are you using?

**Comment by doem97** [comment]
> Are you using LoRA here? Which script are you using?

Not using LoRA. Script `train_text_to_image.py`. I am comparing different adaptation methods, so have to run a vanilla fine-tuning as a baseline.

**Comment by doem97** [comment]
P.s. This is training command:
```bash
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export dataset_name="lambdalabs/pokemon-blip-captions"
export CACHE_DIR="./output/cache"
export OUTPUT_DIR="./output/pokemon/debug"

accelerate launch --mixed_precision="fp16" train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$dataset_name \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=8 \
  --gradient_checkpointing \
  --max_train_steps=15000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --enable_xformers_memory_efficient_attention \
  --output_dir=${OUTPUT_DIR} \
  --cache_dir=${CACHE_DIR}
 ```
Just the same as in tutorial.
