### ISSUE TITLE
Not Able to Import Unet2DModel on MacOS

### ISSUE THREAD

**Issue by chetan-guevara** [huggingface/diffusers#3655]
### Describe the bug

<img width="1283" alt="Screenshot 2023-06-02 at 2 45 40 PM" src="https://github.com/huggingface/diffusers/assets/3173623/2602e32d-867f-4165-a852-0348543ab11d">

### Reproduction

use this line in a Python notebook: "from diffusers import UNet2DModel, DDIMPipeline, DDPMPipeline, DDIMScheduler, DDPMScheduler" 

I get the same error with huggingface_hub 0.14.1 and 0.15.1

### System Info

Mac OS Ventura 
Just cleaned the entire hard disk so this is a clean install

**Comment by patrickvonplaten** [comment]
cc @Wauplin here maybe? This looks like a problem with `huggingface_hub`

**Comment by Wauplin** [comment]
Hi @chetan-guevara , that's a weird issue. Can you run this snippet in your notebook and copy-paste the output? It might help figuring out the issue.

```py
>>> from huggingface_hub import dump_environment_info
>>> dump_environment_info()
```

**Comment by chetan-guevara** [comment]
Thanks. Here is the output: 

<img width="1181" alt="Screenshot 2023-06-05 at 9 50 16 AM" src="https://github.com/huggingface/diffusers/assets/3173623/940703bc-076c-418c-bee7-0b701a2dda1d">

**Comment by chetan-guevara** [comment]
ImportError: cannot import name 'dump_environment_info' from 'huggingface_hub' (/usr/local/anaconda3/lib/python3.10/site-packages/huggingface_hub/__init__.py)

**Comment by Wauplin** [comment]
I'm pretty sure there is an error with the setup then (dump_environment_info being in the lib for a few months already).

Can you do 

```py
from huggingface_hub import __version__
print(__version__)
```
?

**Comment by chetan-guevara** [comment]
Can't do that either. It looks like I can import huggingface_hub, but I can't import any sublibraries from it! I haven't encountered this type of issue before 

What do you recommend to address it? 
<img width="1141" alt="Screenshot 2023-06-05 at 12 53 50 PM" src="https://github.com/huggingface/diffusers/assets/3173623/053e4ed5-eae2-45e0-9d2d-f6d281c59844">

**Comment by Wauplin** [comment]
Hmm :confused: 

To help debugging the issue:
1. How did you install `huggingface_hub`? What tool are you using to manage dependencies (pip, conda, pyenv, poetry,...)?
2. Can you run `pip install --upgrade huggingface_hub` in your terminal?
3. Can you run
```py
import huggingface_hub
print(dir(huggingface_hub))
```
in your notebook?
4. Can you run `pip freeze | grep "huggingface"` in your terminal and copy the output?
5. Can you run `python -c "import huggingface_hub; print(huggingface_hub.__version__)"` in your terminal and report back?
6. Can you run `huggingface-cli env` in your terminal and report back?

For some reason there is a problem in the setup so let's figure it out :)

**Comment by Wauplin** [comment]
@chetan-guevara given you answer at 4. 5. and 6., it seems that you have conflicts/issues to determine which python path and python libs you are using (difference between 0.14 and 0.15). I guess that when you're using jupyter notebook, it's not using the same context. I can't really help with that as it is really machine-related.

However what I can recommend you to do is to get a fresh start:
1. Open terminal and go to local folder
2. Run `python -m venv .venv` ([will create a local virtual env](https://docs.python.org/3/library/venv.html#how-venvs-work))
3. Run `source .venv/bin/activate` (will active this environment)
4. Install with pip: `pip install --upgrade huggingface_hub`
5. Run `pip freeze | grep huggingface` and `huggingface-cli env` to check install (both should output `0.15.1`)
6. Run `jupyter notebook` and start coding

Everytime you want to run your project, you must do a `source .venv/bin/activate` first to be sure you're in the right environment. You can create an alias for this one if it's easier.

**Comment by chetan-guevara** [comment]
@Wauplin I tried creating a virtual-env as you suggested and that didn't fix the problem (i'm still getting this error: 
ImportError: cannot import name 'get_session' from 'huggingface_hub.utils' (/usr/local/anaconda3/lib/python3.10/site-packages/huggingface_hub/utils/__init__.py))

so I uninstalled anaconda and reinstalled it so there would be no conflicts with different python kernels / environments and i would be crystal clear about all the steps involved. and I'm running into the same problem again. however, this time, there is no version conflict with huggingface-hub. here are my answers to the questions you asked previously:

1. How did you install huggingface_hub? What tool are you using to manage dependencies (pip, conda, pyenv, poetry,...)?
Pip

2. Can you run pip install --upgrade huggingface_hub in your terminal?
Done

3. Can you run import huggingface_hub print(dir(huggingface_hub))
in your notebook?

['CONFIG_NAME', 'CachedFileInfo', 'CachedRepoInfo', 'CachedRevisionInfo', 'CardData', 'CommitInfo', 'CommitOperation', 'CommitOperationAdd', 'CommitOperationDelete', 'CorruptedCacheException', 'DatasetCard', 'DatasetCardData', 'DatasetFilter', 'DatasetSearchArguments', 'DeleteCacheStrategy', 'Discussion', 'DiscussionComment', 'DiscussionCommit', 'DiscussionEvent', 'DiscussionStatusChange', 'DiscussionTitleChange', 'DiscussionWithDetails', 'EvalResult', 'FLAX_WEIGHTS_NAME', 'HFCacheInfo', 'HUGGINGFACE_CO_URL_HOME', 'HUGGINGFACE_CO_URL_TEMPLATE', 'HfApi', 'HfFileMetadata', 'HfFolder', 'InferenceApi', 'KerasModelHubMixin', 'ModelCard', 'ModelCardData', 'ModelFilter', 'ModelHubMixin', 'ModelSearchArguments', 'PYTORCH_WEIGHTS_NAME', 'PyTorchModelHubMixin', 'REPO_TYPE_DATASET', 'REPO_TYPE_MODEL', 'REPO_TYPE_SPACE', 'Repository', 'TF2_WEIGHTS_NAME', 'TF_WEIGHTS_NAME', '_save_pretrained_fastai', 'cached_download', 'change_discussion_status', 'comment_discussion', 'create_commit', 'create_discussion', 'create_pull_request', 'create_repo', 'dataset_info', 'delete_file', 'delete_repo', 'edit_discussion_comment', 'from_pretrained_fastai', 'from_pretrained_keras', 'get_dataset_tags', 'get_discussion_details', 'get_full_repo_name', 'get_hf_file_metadata', 'get_model_tags', 'get_repo_discussions', 'hf_hub_download', 'hf_hub_url', 'list_datasets', 'list_metrics', 'list_models', 'list_repo_files', 'logging', 'merge_pull_request', 'metadata_eval_result', 'metadata_load', 'metadata_save', 'metadata_update', 'model_info', 'move_repo', 'notebook_login', 'push_to_hub_fastai', 'push_to_hub_keras', 'rename_discussion', 'repo_type_and_id_from_hf_id', 'save_pretrained_keras', 'scan_cache_dir', 'set_access_token', 'snapshot_download', 'space_info', 'try_to_load_from_cache', 'unset_access_token', 'update_repo_visibility', 'upload_file', 'upload_folder', 'whoami']

4. Can you run pip freeze | grep "huggingface" in your terminal and copy the output?
huggingface-hub==0.15.1

6. Can you run python -c "import huggingface_hub; print(huggingface_hub.__version__)" in your terminal and report back?
0.15.1

8. Can you run huggingface-cli env in your terminal and report back?

huggingface_hub version: 0.15.1
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.10.9
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /Users/chetan/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: osxkeychain
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- gradio: N/A
- numpy: 1.23.5
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /Users/chetan/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /Users/chetan/.cache/huggingface/assets
- HF_TOKEN_PATH: /Users/chetan/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False

Any ideas of where to look next?

**Comment by chetan-guevara** [comment]
FYI
<img width="1156" alt="Screenshot 2023-06-06 at 3 55 27 PM" src="https://github.com/huggingface/diffusers/assets/3173623/a5f02bb1-06d5-4f17-b3c4-b3c29a5b43be">

**Comment by chetan-guevara** [comment]
Yes, it works now! 

Why is it that the import statements only work while in a virtual environment? 

I had imported all the necessary libaries into the normal environment so I'm confused as to why things don't work there

**Comment by Wauplin** [comment]
> Yes, it works now! 

Great!

> Why is it that the import statements only work while in a virtual environment?

Can't say about the exact issue but for some reason your default environment (`/usr/local/anaconda3/lib/python3.10/site-packages`) is broken. I'd advice you to do a `pip uninstall huggingface_hub` in this one. The other environment (the "virtual env") is freshly new so not broken.

Environments in Python are quite important to understand. The final question is always "when I run `import ...`, where should Python look for this library". Depending on which environment is activated, the answer is different. I'd strongly recommend to read this guide to get an overview of the question: https://realpython.com/python-virtual-environments-a-primer .

But in the end, glad you having it working now! I'll close this issue now :)
