### ISSUE TITLE
Fix additional noise latents added to unet input in dreambooth upsampler training scripts

### ISSUE THREAD

**Issue by williamberman** [huggingface/diffusers#3658]
### Describe the bug

The additional latents are random noise and instead need to be added to the original image as during inference

https://github.com/huggingface/diffusers/blob/7a39691362e5448b4417f37e135158fcda5ae7fb/examples/dreambooth/train_dreambooth.py#L1215-L1222

compared to 

https://github.com/huggingface/diffusers/blob/7a39691362e5448b4417f37e135158fcda5ae7fb/src/diffusers/pipelines/deepfloyd_if/pipeline_if_superresolution.py#L867-L871

### Reproduction

n/a

### System Info

n/a

**Comment by sayakpaul** [comment]
Closing with https://github.com/huggingface/diffusers/pull/3659
