### ISSUE TITLE
Understanding Dreambooth and text2img

### ISSUE THREAD

**Issue by leabrix** [huggingface/diffusers#3667]
Hi,

i am currently working with the dreambooth and a custom version of mine of the text2img script. I was wondering however if there are any differences between these two if prior preservation is not used (as i do currently).

I get different results with both which kind of confuses me. I couldnt really find material on that specifically online, so it would be really appreciated if someone is willing to explain to me what exactly the difference is.
What is clear to me:
- the dataloading is different. But afaik it should not have a direct inpact on learning since in both cases we use the image with the corresponding prompt as input for the model / text encoder.
- both use the same basic learning procedure

What confuses me:
- How do different learning rates affect both scripts differently if both use basically the same input and the same learning procedure?

Thanks in advance!

**Comment by patrickvonplaten** [comment]
Hey @leabrix,

Could you maybe try to use the forum for such questions: https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63 ? We try to keep Github mostly for bugs and technical issues.

Thank you!
