### ISSUE TITLE
Problem while reading data from metadata.jsonl file while fine tuning train_text_to_image_lora.py

### ISSUE THREAD

**Issue by atharmzaalo2023** [huggingface/diffusers#3674]
I am trying to fine tune lora model on custom dataset . My Directory structure is as follows

|- Images (folder)
|- train(folder)
  |  |- metadata.jsonl
  |  |- ashish_1.jpg
  |  |- ashish_2.jpg
  |  |- ...
|- train_text_to_image_lora.py

My metadata.jsonl file looks like this
{"file_name": "train/ashish_1.jpg", "text": "An image of Ashish looking angry"}
{"file_name": "train/ashish_2.jpg", "text": "An image of Ashish  standing"}
{"file_name": "train/ashish_3.jpg", "text": "An image of Ashish  talking on mobile phone"}
.......

While I am trying to fine tune the train_text_to_image_lora.py using below config

export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export TRAIN_DIR="Images"
export OUTPUT_DIR="sd-model-1"

accelerate launch --mixed_precision="fp16" train_text_to_image_lora.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$TRAIN_DIR \
  --resolution=512 --random_flip \
  --train_batch_size=1 \
  --num_train_epochs=5 --checkpointing_steps=5000 \
  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --seed=42 \
  --output_dir="sd-model-1" \

I am getting the below traceback I am attaching screenshot of traceback below , can someone please help me with it @patrickvonplaten @sayakpaul 
![text_to_image](https://github.com/huggingface/diffusers/assets/134913498/9bba42a0-d100-4c05-8ad1-5fddcb851b7c)

**Comment by sayakpaul** [comment]
Could you try to maybe reproduce the issue in a more minimal fashion? 

It should be possible reproduce the issue with your local dataset and the `datasets` library. 

If we can minimize the issue to `datasets`, then I would suggest closing this issue here and opening one on the https://github.com/huggingface/datasets repository, instead.

**Comment by atharmzaalo2023** [comment]
@sayakpaul  I can write minimal fashion here

My Directory structure is as follows

|- Images (folder)
|- train(folder)
| |- metadata.jsonl
| |- ashish_1.jpg
| |- ashish_2.jpg
| |- ...
|- train_text_to_image_lora.py

My metadata.jsonl file looks like this
{"file_name": "train/ashish_1.jpg", "text": "An image of Ashish looking angry"}
{"file_name": "train/ashish_2.jpg", "text": "An image of Ashish standing"}
{"file_name": "train/ashish_3.jpg", "text": "An image of Ashish talking on mobile phone"}

While I am trying to load this using huggingface datasets as follows
dataset = load_dataset("imagefolder", data_dir="Images", split="train")

I am getting "ValueError: image at ashish_1.jpg doesn't have metadata in /home/athar.sayed/diffusers/examples/text_to_image/Images/train/metadata.jsonl"

I am also attaching the traceback here
![load_dataset_error](https://github.com/huggingface/diffusers/assets/134913498/11061521-3aa3-4678-bb5d-51e4a3b92401)

**Comment by sayakpaul** [comment]
Cc: @lhoestq

**Comment by lhoestq** [comment]
Hi ! try using the relative path from the metadata file:
```
{"file_name": "ashish_1.jpg", "text": "An image of Ashish looking angry"}
{"file_name": "ashish_2.jpg", "text": "An image of Ashish standing"}
{"file_name": "ashish_3.jpg", "text": "An image of Ashish talking on mobile phone"}
```

**Comment by atharmzaalo2023** [comment]
@lhoestq  Thanks alot it worked

**Comment by sayakpaul** [comment]
Closing the issue then :)
