### ISSUE TITLE
New watermark-free models for text2video (Modelscope): Potat1, Zeroscope Animov 0.1.1 and Animov 512x

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#3679]
### Model/Pipeline/Scheduler description

Potat:
https://huggingface.co/camenduru/potat1
First Open-Source 1024x576 Text To Video Model - no watermark. 

Zeroscope:
https://huggingface.co/cerspense/zeroscope_v1_320s
Modelscope without the watermark, trained in 320x320, with no skipped frames for less flicker. See comparison here: https://www.youtube.com/watch?v=r4tOc30Zu0w Model was trained on a subset of the vimeo90k dataset + a selection of music videos

Animov(0.1.1):
https://huggingface.co/strangeman3107/animov-0.1.1
It was trained at 448x384 resolution.
This is a text2video model for diffusers, fine-tuned with a [modelscope](https://huggingface.co/damo-vilab/text-to-video-ms-1.7b) to have an anime-style appearance.

Animov(512x)
https://huggingface.co/strangeman3107/animov-512x
The model now has a much more anime-style look compared to the previous version.
It was trained at a resolution of 512x512.

### Open source status

- [ ] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

Zeroscope and the Animovs works right off the bat with Diffusers API. 

However, I'm getting this error with Portat, so it might need a fix first: 
https://huggingface.co/camenduru/potat1/discussions/2

**Comment by patrickvonplaten** [comment]
Cool!
