### ISSUE TITLE
Implement `save_pretrained()` for Multi-ControlNet

### ISSUE THREAD

**Issue by DJBen** [huggingface/diffusers#3683]
### Describe the bug

If we load multiple controlnet onto `StableDiffusionControlNetPipeline`, it refuses to be saved using `pipe.save_pretrained` because it is not implemented.

I'd like to implement it myself if that's okay, but I am fairly new to the development of `diffusers`, so I would like to get some pointers from you folks, e.g. what pitfalls to watch for?

```
/root/src/diffusers/pipelines/controlnet/pipeline_controlnet.py:729 in save_pretrained           
                                                                                                 
❱ 729 raise NotImplementedError("Currently, the `save_pretrained()` is not implemented for Mul
```

My need for this use case arises from hosting a serverless function that loads the pipeline from cached files and run inference. It is essential to avoid re-downloading the SD models (and controlnets) every time in its code start.

### Reproduction

There's a [snippet](https://gist.github.com/DJBen/579bc215d069eddf6a2380cda9937fd1) that reproduces this on [Modal](https://modal.com/). You could reproduce that by calling 

```
modal run pipeline_with_multicontrolnet_fails_to_save.py::stub.pipeline_with_multicontrolnet
```

Here's the essential code:

```python
import diffusers
import torch
import os

hugging_face_token = "<insert hugging face token>"
controlnet_dir = f"./edit-anything-v0-4-sd15/"
controlnet_inpaint_dir = f"./control_v11p_sd15_inpaint/"
sd_dir = f"./stable-diffusion-v1-5/"

edit_anything_controlnet = diffusers.ControlNetModel.from_pretrained(
    "shgao/edit-anything-v0-4-sd15",
    cache_dir=controlnet_dir,
    torch_dtype=torch.float16,
)
edit_anything_controlnet.save_pretrained(controlnet_dir, safe_serialization=True)

inpaint_controlnet = diffusers.ControlNetModel.from_pretrained(
    "lllyasviel/control_v11p_sd15_inpaint",
    cache_dir=controlnet_inpaint_dir,
    torch_dtype=torch.float16,
)

inpaint_controlnet.save_pretrained(controlnet_inpaint_dir, safe_serialization=True)

pipe = diffusers.StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=[edit_anything_controlnet, inpaint_controlnet], # this turns the controlnet into MultiControlNet
    cache_dir=sd_dir,
    torch_dtype=torch.float16,
    use_auth_token=hugging_face_token,
)
pipe.scheduler = diffusers.UniPCMultistepScheduler.from_config(pipe.scheduler.config)
pipe.save_pretrained(sd_dir, safe_serialization=True)
```

### System Info

- `diffusers` version: 0.17.0.dev0
- Platform: Linux-5.13.0-1029-aws-x86_64-with-glibc2.31
- Python version: 3.10.8
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.29.2
- Accelerate version: 0.19.0
- xFormers version: 0.0.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by DJBen** [comment]
@patrickvonplaten Your code can properly *load* the SDcontrolnet pipeline, but there's an issue saving the pipeline programmatically. 

```python
pipe = diffusers.StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet= # what to write here? Omitting this arg emits an error.
    cache_dir=sd_dir,
    torch_dtype=torch.float16,
    use_auth_token=hugging_face_token,
)
pipe.save_pretrained(sd_dir, safe_serialization=True)
```

Unless we can have a way to save the `StableDiffusionControlNetPipeline` without supplying all the controlnet?

**Comment by patrickvonplaten** [comment]
Took some time to implement it, should work now here: https://github.com/huggingface/diffusers/pull/3747

Note that this will only work for **local** saving & loading though. It's not possible to allow directly loading mulitple controlnets from the Hub
