### ISSUE TITLE
Represent learnt concept in textual inversion with more than one token

### ISSUE THREAD

**Issue by Luvata** [huggingface/diffusers#369]
### Describe the bug

As we discuss in #266 
> The original textual inversion support [using more than one vector](https://github.com/rinongal/textual_inversion/blob/main/ldm/modules/embedding_manager.py#L39) to represent the learnt concept.
For the current implementation, if we just extend the learned vocab and CLIP token embedding then it would use only one vector for it.

What could be the best way to support this? cc @patil-suraj 

### System Info

diffusers v0.2.4

**Comment by patrickvonplaten** [comment]
cc @patil-suraj - are we planning on supporting this soon or rather not?

**Comment by Luvata** [comment]
Some people [1] claimed that using more than one token to represent the learnt concept help improve the inversion performance
(Ctrl-F `num_vectors`). But I guess to implement that, the current pipeline would change a lot
[reddit #1](https://www.reddit.com/r/StableDiffusion/comments/wz88lg/i_got_stable_diffusion_to_generate_competentish/)

**Comment by patrickvonplaten** [comment]
+1

**Comment by isamu-isozaki** [comment]
HI! I implemented this for my project in a bit of a hacky way but I can make a pr for it if you want! Basically, I transformed the placeholder token to n other placeholder tokens combined.

**Comment by isamu-isozaki** [comment]
I made a pr for what I mean (here)[https://github.com/huggingface/diffusers/pull/661]! It might make it a bit verbose so I'm thinking it might be better to inherit the tokenizer then do things but it does work.

**Comment by patil-suraj** [comment]
Hey @isamu-isozaki, thanks a lot! How are the results with your approach, this is different from the way it's done in the offical repo no ?

**Comment by isamu-isozaki** [comment]
@patil-suraj Hi! Yup the approach is a bit different in how the tokens are assigned but you can get the same result by having one token for initializing token. In my experiments, having more token do produce better results. For example, I was just doing fast experiments with 5e-4 with batch size 1 and for the default one token example I got something like 

![media_images_samples_12059_dcfd44f36abc51083f13](https://user-images.githubusercontent.com/23430101/192833104-bdc71d25-d1fc-4fc0-9d23-75850f68e067.png)

as an end result but with say 12 tokens or so, with the same parameters, I got

![media_images_samples_12028_77a0c2cac01cb55a13c1](https://user-images.githubusercontent.com/23430101/192833319-18699ccc-7577-4842-8a06-6591cf40ccd1.png)

**Comment by isamu-isozaki** [comment]
I'll double check the original implementation again but for this one, you can have each placeholder token start with a different initial value. So you can describe your subject not just with one token but with a sentence.

The main problem for this implementation is that it makes the prompt quite verbose. For example, for the picture below, the prompt was
"A picture of <frida>_0 <frida>_1 <frida>_2 <frida>_3 <frida>_4 <frida>_5 <frida>_6 <frida>_7 <frida>_8 <frida>_9 <frida>_10 <frida>_11"

**Comment by patil-suraj** [comment]
Cool, thanks for the explanation! 
I'm also thinking about how to support the original implementation in `diffusers`. Will have something working soon!

**Comment by isamu-isozaki** [comment]
@patil-suraj Sounds good! Let me know if you need any help.

**Comment by sayakpaul** [comment]
Seems to be supported now. Closing hence
