### ISSUE TITLE
Issues in the docstrings for Kandinsky pipeline(s)

### ISSUE THREAD

**Issue by freespirit** [huggingface/diffusers#3693]
### Describe the bug

I noticed a few issues with the docstrings in Kandinsky pipelines:

1. Wrong model name in the [pipeline_kandinsky.py example](https://github.com/huggingface/diffusers/blob/8669e8313dfedd5da1fd84e8abab92eda82623c0/src/diffusers/pipelines/kandinsky/pipeline_kandinsky.py#LL44C48-L44C48):
```py
pipe_prior = KandinskyPriorPipeline.from_pretrained("kandinsky-community/Kandinsky-prior")
```
should be
```py
pipe_prior = KandinskyPriorPipeline.from_pretrained("kandinsky-community/kandinsky-2-1-prior")
```

2. The `KandinskyPriorPipelineOutput`'s members were renamed in 32ea2142c056fae722b0cabaa799697a861cd039 but the relevant docstrings throughout the Kandinsky pipelines were not. For example, the [`src/diffusers/pipelines/kandinsky/pipeline_kandinsky.py`](https://github.com/huggingface/diffusers/blob/8669e8313dfedd5da1fd84e8abab92eda82623c0/src/diffusers/pipelines/kandinsky/pipeline_kandinsky.py#L49) has this docstring:

```py
pipe_prior = ...
out = pipe_prior(prompt)
image_emb = out.images
zero_image_emb = out.zero_embeds
```

In addition to using the correct member names, I would suggest renaming the variables:
```py
pipe_prior = ...
out = pipe_prior(prompt)
image_emb = out.image_embeds
negative_image_embeds = out.negative_image_embeds
```

### Reproduction

```py
from diffusers import KandinskyPipeline, KandinskyPriorPipeline
import torch

pipe_prior = KandinskyPriorPipeline.from_pretrained("kandinsky-community/Kandinsky-prior") # wrong model id
pipe_prior.to("cuda")

prompt = "red cat, 4k photo"
out = pipe_prior(prompt)
image_emb = out.images # wrong name
zero_image_emb = out.zero_embeds # wrong name
```

### System Info

latest commit: 3c0579b1b70aeb3873f0002b8271eb69cd4bcced

**Comment by yiyixuxu** [comment]
@freespirit oh thanks!! a PR would be great 🤗🤗🤗🤗😇😇😇😇

**Comment by freespirit** [comment]
> @freespirit oh thanks!! a PR would be great 🤗🤗🤗🤗😇😇😇😇

I made one🤗
https://github.com/huggingface/diffusers/pull/3695

**Comment by yiyixuxu** [comment]
@freespirit thank you!
