### ISSUE TITLE
loading state_dict for UNet2DConditionModel when convert safetensors to diffusers model

### ISSUE THREAD

**Issue by FrancisDacian** [huggingface/diffusers#3696]
`RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
	size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).`

when I try to convert the safetensors model from civitai (https://civitai.com/api/download/models/31799) to diffusers model, I met this error. Anyone has encountered the same issue?
I am using this script: scripts/convert_original_stable_diffusion_to_diffusers.py

**Comment by patrickvonplaten** [comment]
Seems like a duplicate of: https://github.com/huggingface/diffusers/issues/3254 Could you try whether this issue helps you to solve yours?

**Comment by zhixideyu** [comment]
Have you solved it？
