### ISSUE TITLE
Lack of functionality in stable diffusion inpainting 

### ISSUE THREAD

**Issue by Inkorak** [huggingface/diffusers#370]
The img2img can handle init_image as FloatTensor and PIL image with
```
if not isinstance(init_image, torch.FloatTensor):
   init_image = preprocess(init_image)
```
But inpainting cannot work like this with init_image and mask_image. It's only working with FloatTensor. Although the typing states that it can work with both. 
```
init_image: Union[torch.FloatTensor, PIL.Image.Image],
mask_image: Union[torch.FloatTensor, PIL.Image.Image],
```
It is desirable to have uniformity.
Also, preprocess function in img2img and preprocess_image function in inpainting are the same, they differ only in the name.

**Comment by patrickvonplaten** [comment]
Ah yeah good point @Inkorak ! @patil-suraj @pcuenca - should we add two `if` statements here as well just like we have in image-2-image? Wdyt?

**Comment by patil-suraj** [comment]
good point, will fix this!
