### ISSUE TITLE
Major update on Controlnet v1.1, Feature Reference-only Control

### ISSUE THREAD

**Issue by jinwonkim93** [huggingface/diffusers#3701]
sd-webui-controlnet now supports reference-only control, which does not require any control models. it guides diffusion directly using images as references. It would be nice to have it on diffusers.

https://github.com/Mikubill/sd-webui-controlnet/pull/1235/files

I think the method for reference-only is continually added + updated which requires flexible implementation. Is there anything you want me to give you a hand?

https://github.com/Mikubill/sd-webui-controlnet/discussions/1280

**Comment by adhikjoshi** [comment]
@takuma104

**Comment by patrickvonplaten** [comment]
We have an implementation here: https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_reference.py does this work for your case @jinwonkim93 or do we need more here?

**Comment by wilfrediscoming** [comment]
> 

Does this method work for inpainting pipeline?

**Comment by wilfrediscoming** [comment]
> We have an implementation here: https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_reference.py does this work for your case @jinwonkim93 or do we need more here?

I mean this method, does it work for inpainting pipeline?

**Comment by jinwonkim93** [comment]
> > We have an implementation here: https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_reference.py does this work for your case @jinwonkim93 or do we need more here?
> 
> I mean this method, does it work for inpainting pipeline?

method itself does, but the pipeline mention above does not support inpainting

**Comment by wilfrediscoming** [comment]
> > > We have an implementation here: https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_reference.py does this work for your case @jinwonkim93 or do we need more here?
> > 
> > 
> > I mean this method, does it work for inpainting pipeline?
> 
> method itself does, but the pipeline mention above does not support inpainting

If I use the control net pipeline, do you know if there is any way I can add a reference image for inpainting?

**Comment by jinwonkim93** [comment]
> > > > We have an implementation here: https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_reference.py does this work for your case @jinwonkim93 or do we need more here?
> > > 
> > > 
> > > I mean this method, does it work for inpainting pipeline?
> > 
> > 
> > method itself does, but the pipeline mention above does not support inpainting
> 
> If I use the control net pipeline, do you know if there is any way I can add a reference image for inpainting?

Take a look at https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_controlnet_inpaint.py, https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_controlnet_reference.py 

It will be easy to adapt.

**Comment by wilfrediscoming** [comment]
@jinwonkim93 Thank you. After looking at the code I am quite lost. My code is very simple, and I am currently using canny edge for controlnet.. 

can you give me some hints/examples how can I add another Controlnet with reference image into it? 

`from diffusers import ControlNetModel, StableDiffusionControlNetInpaintPipeline

device = torch.device('cuda')

# Canny
controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny")

pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting",
    controlnet=controlnet,
)`
