### ISSUE TITLE
Load StableDiffusionInpaintPipeline using from_ckpt

### ISSUE THREAD

**Issue by aycaecemgul** [huggingface/diffusers#3704]
Hi, I tried to load an inpaint pipeline but i got an error that says: 'StableDiffusionInpaintPipeline' has no attribute 'from_ckpt' .
if i am understanding #3533 correctly: we cannot load an inpaint pipeline using from_ckpt. we have to load txt2img pipeline with from_ckpt and load a inpaint pipeline using txt2img pipeline components, but this does not totally cover #3497 

Since i only have the inpaint weight, loading a pipeline like this would be great!
`
pipe = StableDiffusionInpaintPipeline.from_ckpt(safetensors_path, torch_dtype=torch.float16).to(device)
`

**Comment by patrickvonplaten** [comment]
Hey @aycaecemgul,

Can you add a fully reproducible code snippet here?
