### ISSUE TITLE
The model never saves to HF

### ISSUE THREAD

**Issue by smileBeda** [huggingface/diffusers#3705]
### Describe the bug

When running the full https://huggingface.co/docs/diffusers/main/en/tutorials/basic_training training, all that gets saved are the images, the logs.
No `unet` and no `scheduler` is saved. Basically, the model is missing, which is the whole point of the exercise.

### Reproduction

Just run through the steps of https://huggingface.co/docs/diffusers/main/en/tutorials/basic_training, the last step `notebook_launcher(train_loop, args, num_processes=1)` load the `train_loop` and that function is supposed to save the model, yet, it never does.

### Logs

```shell
100%
1000/1000 [01:37<00:00, 10.20it/s]

Adding files tracked by Git LFS: ['samples/0000.png']. This may take a bit of time if the files are large.
Upload file samples/0000.png: 100%
526k/526k [00:01<00:00, 491kB/s]
Upload file logs/train_example/events.out.tfevents.1686132774.2b487d1c587c.748.1: 100%
7.71k/7.71k [00:01<?, ?B/s]
To https://huggingface.co/XXX/ddpm-butterflies-129
   722846e..b4db147  main -> main
```
```


### System Info

latest Python, GPU with 30GB, CPU with 25GB, 100GB hdd, everything exactly as described in the paper, no line of code changed.
Same results on Google Colab.

**Comment by patrickvonplaten** [comment]
@sayakpaul can you take a look here?

**Comment by sayakpaul** [comment]
Hmm seems like the [Colab Notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers_doc/en/pytorch/basic_training.ipynb) has got some deprecated / removed functionalities around both `accelerate` and `huggingface_hub`:

* `logging_dir` should no longer passed to `Accelerator`. See https://github.com/huggingface/diffusers/pull/3714 (cc: @muellerzr).
* Not sure, but I remember @Wauplin warning us about using the `Repository` object from `huggingface_hub` and instead adapting a combination of `create_repo()` and `upload_folder`. Henceforth, I think [this tutorial](https://huggingface.co/docs/diffusers/main/en/tutorials/basic_training) needs to be adjusted. @Wauplin could you comment on this? 

As a consequence of the above point just `repo = Repository(config.output_dir, clone_from=repo_name)` won't work and result into "Repository not found error." This is also why we do

https://github.com/huggingface/diffusers/blob/a06317abeaad843d7a722562c2ec6fbb988b0ad8/examples/unconditional_image_generation/train_unconditional.py#L365

before instantiating `Repository()`. 

Nonetheless, I created this [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/667b6250cf85b6c71651aba31bdc7a48/basic_training.ipynb) which should do the job as a temporary workaround. 

If it solves the problem, maybe we can close the issue?

**Comment by Wauplin** [comment]
> Not sure, but I remember @Wauplin warning us about using the Repository object from huggingface_hub and instead adapting a combination of create_repo() and upload_folder. Henceforth, I think [this tutorial](https://huggingface.co/docs/diffusers/main/en/tutorials/basic_training) needs to be adjusted. @Wauplin could you comment on this?

I confirm that the `upload_folder()` should be preferred instead of `Repository`. The idea is that you don't have to download the entire existing repo to push your training results. Also it is less error prone + errors should be more explicit. In both cases, `create_repo(..., exists_ok=True)` **must be** called before the training to ensure the repo exists on the Hub (at some point, `Repository` was taking care of it but it has been removed since quite some time).

**Comment by Wauplin** [comment]
Also `get_full_repo_name` is not needed anymore and should be removed if the tutorial is updated. You can change

```py
        if config.push_to_hub:
            repo_name = get_full_repo_name(Path(config.output_dir).name)
            repo_id = create_repo(
                repo_id=repo_name, exist_ok=True
            ).repo_id
```

by 

```py
        if config.push_to_hub:
            repo_id = create_repo(repo_id=Path(config.output_dir).name, exist_ok=True).repo_id
```

`create_repo` returns the real/full repo id already so no need to pre-compute it :) (it saves some code + 1 whoami call)

**Comment by smileBeda** [comment]
@sayakpaul , I tested your colab nb

On the step to load dataset, I got `ModuleNotFoundError: No module named 'datasets'`. That was solved by first running `!pip install datasets`. Tiny oversight I think? In the wording on nb start it says:
> Before you begin, make sure you have 🤗 Datasets installed to load and preprocess image datasets, and 🤗 Accelerate, to simplify training on any number of GPUs. The following command will also install [TensorBoard](https://www.tensorflow.org/tensorboard) to visualize training metrics (you can also use [Weights & Biases](https://docs.wandb.ai/) to track your training).

So I would have assumed that command to add `datasets` too, but it seems it does not, maybe the wording can be adjusted.

Note that the exact same happened on the "create unet`, with `diffusers`.

It never asked me for the HF token, thus resulting in error on the final step, that is because the cell where it would ask for token, has a `#` comment in it, so removing that and running that cell did solve this too.

Finally, it did upload the unet files, so that works now it seems.
Weirdly, the samples look awful, while they where pretty nice in the first run I did when I opened this ticket... but that is another detail.

**Comment by sayakpaul** [comment]
Ccing @stevhliu for the notebook wording issue.

**Comment by stevhliu** [comment]
Hi @smileBeda, thanks for the feedback! 

I'm unable to reproduce the error with loading a dataset. I believe running the following and installing the [`training`](https://github.com/huggingface/diffusers/blob/0bab447670f47c28df60fbd2f6a0f833f75a16f5/setup.py#L188)  dependency should also install the `datasets` package:

```py
!pip install diffusers[training]
```
