### ISSUE TITLE
OOM when use multi-gpu by 3090Ti

### ISSUE THREAD

**Issue by wangmiaowei** [huggingface/diffusers#3717]
### Describe the bug

Is there any attempt to finetune a stable diffusion model using multi 3090ti with 24Mem by running train_text_to_image.py? 

I tried lots of accurate configs but OOM still occurs.  I use another card and found using only one gpu takes 25G while use multiple GPUs takes about 35G/card. Is there any valid solution?

### Reproduction

export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export dataset_name=""

accelerate launch --mixed_precision="fp16" --multi_gpu  train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$dataset_name \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --enable_xformers_memory_efficient_attention \
  --gradient_checkpointing \
  --max_train_steps=15000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir output

### System Info

python3.9, diffusers='0.17.0.dev0'

**Comment by patrickvonplaten** [comment]
What is your PyTorch version?

**Comment by patrickvonplaten** [comment]
And your xformers version?

**Comment by wangmiaowei** [comment]
PyTorch version == 1.13.0+cu11.7 Xformers =0.0.20

**Comment by patrickvonplaten** [comment]
And this only happens when multi GPU is used ? Not when using single GPU? 

cc @sayakpaul @williamberman here

**Comment by wangmiaowei** [comment]
@sayakpaul  Thanks for your reply, when you use 515*512 finetune SD, how about the GPU memory occupancy in your A100?

**Comment by sayakpaul** [comment]
Currently, I am unable spin up a machine with multiple GPUs. So, will revisit later. Meanwhile pinging @muellerzr to see if he has any insights to share regarding the memory increase.

**Comment by Nikki-Gu** [comment]
I met the same problem. Also on 3090Ti, it is okay to runing on single GPU, but ran OOM while using multi GPUs.

**Comment by jiaxinxie97** [comment]
Hi all, Do you have solution for this? I encounter the same problem, try to install xformers in different ways. In my intuition, it is because xformers does not in multi-gpu training, I can run in batch size=1, which is the same as not enable xformers in single-gpu run.

**Comment by nightrain-vampire** [comment]
Hi everyone, I met the same issue on a RTX 3090 with 24GB. It is okay to run on single GPU, but OOM when --multi-gpu was set. It seems that it is a stable problem in multi GPUs mode.

**Comment by sayakpaul** [comment]
Where does the code error out? Can you share your error trace?
