### ISSUE TITLE
MPS: models require an initial pass for reproducibility

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#372]
I have no idea what's causing this, I suspect something related to RNGs, as we know they don't work properly in `mps` yet.

This is a pending task from our initial `mps` support (#355) that we need to investigate. For now, we have adopted two workarounds:
- Perform an extra pass as appropriate so tests pass.
- Recommend users that care about reproducibility / accuracy to do the same.

**Comment by pcuenca** [comment]
In the second part of [this comment](https://github.com/pytorch/pytorch/issues/84039#issuecomment-1241973904) I documented a similar behaviour using `einsum` vs `matmul`. I used @patil-suraj's branch to run the tests without the warmup pass, but they still failed. So there must be other ops that have a similar behaviour.

**Comment by Birch-san** [comment]
I found that this mitigation works, but I assume it only works if you're consistent in the size of `x` and `context` that you submit to `CrossAttention` (e.g. same image dimensions, number of samples, number of conditions).

it's not a cheap mitigation. unless we get lucky and there's a fast-path for zeroes or something.

**Comment by patrickvonplaten** [comment]
cc @pcuenca :-)

**Comment by clamp-7724** [comment]
when I try to excute the code:
from torch import autocast
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4", 
	use_auth_token=True
).to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
with autocast("cuda"):
    image = pipe(prompt)["sample"][0]  
    
image.save("astronaut_rides_horse.png")

It showed me that
AttributeError: 'StableDiffusionPipeline' object has no attribute 'to'

'pip install --upgrade diffusers' is not worked

what should I do to solve this question? is it a version problem?

**Comment by patrickvonplaten** [comment]
Is this still relevant (gently pinging @pcuenca )

**Comment by pcuenca** [comment]
> Is this still relevant
Yes, unfortunately, still an issue with the RC of PyTorch 1.13 from the `test` wheel.

@Birch-san In my experience this is only required the first time you use the model. Is this negatively impacting your use case in a non-transient mode?

**Comment by Birch-san** [comment]
personally I run pytorch stable 1.12.1 (because it's faster than 1.13RC or the nightlies https://github.com/pytorch/pytorch/issues/85297, https://github.com/pytorch/pytorch/issues/87010), so I don't encounter the einsum reproducibility problem.

my use-case is almost always "launch txt2img just to generate 1 image" (i.e. transient), so if I were on an exposed version of pytorch: this issue would hit me every time.

it's more than just non-determinism; the first einsum result is *nonsense*. so quality will be strictly lower (I expect it means the highest sigma gets denoised to some mess, but subsequent denoising brings the image back on track, albeit undersampled and with the composition a bit randomized).

I guess the real questions are:

- which versions of pytorch does HF support?
- will this bug be promoted to pytorch 1.13 stable?
  - from @pcuenca's testing: sounds like it is
  - that'll be the least of your worries, because (from my testing) the [42x einsum perf regression](https://github.com/pytorch/pytorch/issues/87010) is *also* in 1.13 RC

**Comment by pcuenca** [comment]
Thanks @Birch-san! Great work posting all those details in PyTorch's github, it looks like they are really helping!

I'll do some more testing about the non-determinism to try to isolate what ops are still affected.

**Comment by RahulBhalley** [comment]
Why GH closed it? It should remain open until solved.

**Comment by patrickvonplaten** [comment]
Gently pinging @pcuenca here (not sure if we have time to closer look into this issue though). Would be extremely nice if the community could also look into it / investigate here a bit

**Comment by RahulBhalley** [comment]
Yeah bot. Address it.

**Comment by pcuenca** [comment]
I'll ask in the PyTorch forums again.

**Comment by Birch-san** [comment]
wasn't this problem due to this einsum bug:  
https://github.com/pytorch/pytorch/issues/85224

solved since at least `1.13.0.dev20220928` (so should be in latest stable, 1.13.1).

in any case: diffusers CrossAttention doesn't use einsum any more. it uses baddbmm and bmm.

**Comment by RahulBhalley** [comment]
We might instead close it as now Apple has released SD with CoreML.

**Comment by Birch-san** [comment]
hard disagree that a CoreML model is a substitute to having a working PyTorch MPS model.  
but I do think [diffusers is deterministic on MPS](https://github.com/huggingface/diffusers/issues/372#issuecomment-1374846894) anyway.

**Comment by RahulBhalley** [comment]
Right. Although we can train SD with MPS only (with more powerful future version of M-series chips) and CoreML is just for inference.

**Comment by pcuenca** [comment]
This doesn't fully work for me yet.

The way I'm testing is by commenting these lines: https://github.com/huggingface/diffusers/blob/97958bcdc808649d13b0fa3b0f7fad686caf3866/tests/test_modeling_common.py#L53-L55

and then running the tests for `test_from_save_pretrained` on `UNet2DModelTests`. If the lines are commented the tests fail, and they succeed otherwise.

**Comment by pcuenca** [comment]
Update: the bot was right in this case. This was never resolved in PyTorch 1.13, but works in PyTorch 2.

**Comment by patrickvonplaten** [comment]
Smart bot!
