### ISSUE TITLE
StableDiffusionControlNetPipeline.from_ckpt() does not exist

### ISSUE THREAD

**Issue by tripzero** [huggingface/diffusers#3722]
StableDiffusionControlNetPipeline doesn't appear to inherit from FromCkptMixin so there is no ability to load safetensors like we can with StableDiffusionPipeline.from_ckpt().  Adding the class doesn't fix it as there is another failure in the from_ckpt code.

It would be cool to support from_ckpt() in StableDiffusionControlNetPipeline

**Comment by patrickvonplaten** [comment]
Hmm this would be a bit trickier since `StableDiffusionControlNetPipeline.from_ckpt` would need two links as an input, one for the controlnet, one of the base SD ckpt. How were you envisioning this to look like?

**Comment by tripzero** [comment]
3 is to do both... keywords for both controlnet or controlnet_model_path.  That way users can use either a pretrained or checkpoint for the controlnet.

**Comment by deepbuzin** [comment]
Stumbled upon this same problem just a second ago. Has somebody come up with a workaround yet, perhaps, by loading it via a vanilla pipeline, disassembling it and reassembling it back into a ControlNet version? Is that a thing one could in theory do?

**Comment by patrickvonplaten** [comment]
A new `FromControlNetCkptMixin` similar to https://github.com/huggingface/diffusers/blob/231bdf2e560a57976749b55a941bcf3f311df6fc/src/diffusers/loaders.py#L1333 that implements [this](https://github.com/huggingface/diffusers/issues/3722#issuecomment-1592168253) approach makes a lot of sense to me

**Comment by tripzero** [comment]
> Would still be nice to have the mixin update!

Agreed.  The workaround is okay, but having to convert every safetensor to diffusers format is annoying and unnecessary in StableDiffusionPipeline.  So this is about consistency and ease of use.

**Comment by patrickvonplaten** [comment]
Hey @tripzero, 

Can you check if this works for you: https://github.com/huggingface/diffusers/pull/4084
