### ISSUE TITLE
StableDiffusionPipeline.from_ckpt() is unable to load checkpoints offline

### ISSUE THREAD

**Issue by nimadez** [huggingface/diffusers#3729]
When the network connection is disabled, StableDiffusionPipeline.from_ckpt() is unable to load checkpoints from local_files_only because it tries to download the .yaml configuration from the GitHub repository.

This problem can be solved by adding this line to from_ckpt() in [loaders.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/loaders.py):
```
original_config_file = kwargs.pop("original_config_file", None)
```
and pass it to download_from_original_stable_diffusion_ckpt()
```
pipe = download_from_original_stable_diffusion_ckpt(
        pretrained_model_link_or_path,
        pipeline_class=cls,
        original_config_file=original_config_file,  <-- here
        model_type=model_type,
        stable_unclip=stable_unclip,
        controlnet=controlnet,
        from_safetensors=from_safetensors,
        extract_ema=extract_ema,
        image_size=image_size,
        scheduler_type=scheduler_type,
        num_in_channels=num_in_channels,
        upcast_attention=upcast_attention,
        load_safety_checker=load_safety_checker,
        prediction_type=prediction_type,
    )
```

**Comment by patrickvonplaten** [comment]
Agree, we should try to fix this. @nimadez would you like to open a PR with the code changes as shown above?
