### ISSUE TITLE
Wrong time step in inpainting blending

### ISSUE THREAD

**Issue by ernestchu** [huggingface/diffusers#3730]
I might be wrong, but at the first glance, `init_latents_proper` should be diffused to step `t-1` instead of `t`. (`1` here means generalized step size). Can someone explain the current implementation for me? Thanks

https://github.com/huggingface/diffusers/blob/c42f6ee43e0408c5fe8a1d3dc3cdeb9eb3a02fa6/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py#L1309

**Comment by patrickvonplaten** [comment]
Investigating this!
