### ISSUE TITLE
How to use local safetensors model for inference?

### ISSUE THREAD

**Issue by Eugeoter** [huggingface/diffusers#3732]
I've known that from_pretraind function is able to load online model. But I have a local safetensors stable diffusion model (xxx.safetensors). How to use this file to generate images without AUTOMATIC1111 webui?

**Comment by VincentNeemie** [comment]
python ./scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path '{thepathofyoursafetensormodel/name}.safetensors'  --dump_path $wheretounloadthemodel --from_safetensors

Something like this i believe

**Comment by Eugeoter** [comment]
I think I've found the solution. StableDiffusionPipeline.from_ckpt(use_safetensors=True) works for me. Anyway, thank you for your reply!

> `python ./scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path '{thepathofyoursafetensormodel/name}.safetensors' --dump_path $wheretounloadthemodel --from_safetensors` @Eugeoter Something like this i believe

**Comment by VincentNeemie** [comment]
> I think I've found the solution. StableDiffusionPipeline.from_ckpt(use_safetensors=True) works for me. Anyway, thank you for your reply!
> 
> > `python ./scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path '{thepathofyoursafetensormodel/name}.safetensors' --dump_path $wheretounloadthemodel --from_safetensors` @Eugeoter Something like this i believe

I'm glad! 
Thanks for posting your solution too

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
ps @Eugeoter how did you load the local safetensor? I tried something like>model_id="animePastelDream_softBakedVae.safetensors" StableDiffusionPipeline.from_pretrained(model_id,cache_dir="stbldiff",use_safetensors=True) 

but it doesnt work.
it throws>[Errno 2] No such file or directory: 'stbldiff\\models--animePastelDream_softBakedVae.safetensors\\refs\\main'
but my model is just inside of stbldiff folder.
