### ISSUE TITLE
Hyper pigmentation since Diffusers 15 (breaks on certain VAEs?)

### ISSUE THREAD

**Issue by CustodialMatter** [huggingface/diffusers#3736]
### Describe the bug  

(edits: added more affected checkpoint examples)

I was hoping a savant could take a look at this picture and in one second describe what we're doing wrong

warning, mild cartoon nudity:

https://imgur.com/a/Y672o4R

Literally, if we run the same prompt in Diffusers 15, it works, on any machine, on different kinds of GPUs and drivers. It doesn't matter if xformers is on, off, etc. We've not had luck isolating it.

In those same environments, with the same prompts, if we upgrade to 16 and now 17, these unusual colors can be reproduced.

### Reproduction

Download the Cetus model from Civitai, for example.  NSFW link:

https://civitai.com/models/6755/cetus-mix

I'm calling out this one because it's one of those oddball fine-tunes that doesn't bake their VAE and offers it as two separate files.  Other models also do this (makes me think its VAE related).  Others impacted: Aom3, ao2 hard, darkrev

Example prompt, censored here obviously, where the square brackets are negatives in our software so they can be written in a single line

/render /sampler:k_euler_a /guidance:16 (((((((cool prompt))))))) ((((((safe for work)))))) ((masterpiece, intricately detailed, best quality, high resolution)) , ((some prompt)) , some text, another prompt, another token, lets get more tokens, ((((lit by television light, dimly lit)))) 

[[white background, simple background, boring background, debug token]] tokens, token, tokens, tokens, [[[[low resolution, worst quality, blurry, gnarly, sfw, ugly]]]] [[bad quality, worst quality, blurry, low resolution, token, token, token, token]] [[large token]] 

It would be difficult to tell you which exact vae this is because Civitai users have a nasty habit of renaming files that someone else created as their own. So how widespread this issue is, I'm not sure.

### Logs

```shell
Nothing notable, it renders normally
```

### System Info

latest diffusers, latest everything

**Comment by patrickvonplaten** [comment]
Hey @DumbestPersonHere,

Could you try to add a codesnippet that just include diffusers code? It seems like you're using A1111 in your workflow above

**Comment by infinitytmbots** [comment]
I'm having the same issue as well with several models in later versions. Doesn't seem to be a VAE issue as well.
![Uploading i
![imageToSave2art1](https://github.com/huggingface/diffusers/assets/69136448/61f1a30f-a7bc-4d31-94a5-23afee1f4b21)
mageToSave1art1.png…]()
![imageToSave3art1](https://github.com/huggingface/diffusers/assets/69136448/404d7e54-82e8-4013-a6c0-028bdc594f19)

**Comment by DumbestPersonHere** [comment]
Could it be related to the safety checker?

**Comment by patrickvonplaten** [comment]
Hard to reproduce the issue here without more info on how to reproduce

**Comment by infinitytmbots** [comment]
The issue is related to using a custom safety filter. 
in the newer versions of the StableDiffusionPipeline, image post-processing denormalises images that have the nsfw_concept present in them.
The denormalisation determination is done on the assumption that `has_nsfw_concepts` returns an array of booleans. When filters return otherwise, the denormalisation occurs on the original images resulting in hyperpigmentation.
