### ISSUE TITLE
Wrong link about LoRA in the release page of v0.17.0

### ISSUE THREAD

**Issue by off99555** [huggingface/diffusers#3741]
Notice the following link doesn't point to a PR:
`Thanks to @takuma104 for contributing this feature via [this PR](https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/lora_non_lora_comparison.png).`

https://github.com/huggingface/diffusers/releases/tag/v0.17.0
![image](https://github.com/huggingface/diffusers/assets/15215732/701538f5-b536-448a-8182-50f8a72f0235)

**Comment by patrickvonplaten** [comment]
cc @sayakpaul,

@off99555 would you like to open a PR to change it?

**Comment by sayakpaul** [comment]
I have fixed the release docs which you @off99555 could have updated I think. Thanks for reporting. 

Hence closing the issue.

**Comment by off99555** [comment]
For clarification, I don't think I have edit permission on that page though. There is no Edit button anywhere on it.

![image](https://github.com/huggingface/diffusers/assets/15215732/4102e749-af7c-406c-b3de-ee82df30260d)

**Comment by sayakpaul** [comment]
Yes, that is why I edited it myself :)
