### ISSUE TITLE
Reshape in Unet_3D seems to be wrong

### ISSUE THREAD

**Issue by rob-hen** [huggingface/diffusers#3753]
### Describe the bug

Looking at the [reshape operation](https://github.com/huggingface/diffusers/blob/38adcd21bd9cc69f84710deb161c578b6478944f/src/diffusers/models/unet_3d_condition.py#L466)  of the input sample within `unet_3d_condition.py,` it looks as if it is not correct.

### Reproduction

``` python
import torch
import rearrange

sample = torch.randn((1,16,4,64,64))
num_frames = 16
x = sample.permute(0, 2, 1, 3, 4).reshape((sample.shape[0] * num_frames, -1) + sample.shape[3:])
y = rearrange(x,"B F C H W -> (B F) C H W")


print(sample[0,1,2,3,4])
print(x[1,2,3,4])
print(y[1,2,3,4])
```

### Logs

```shell
>>> sample[0,1,2,3,4]
tensor(-0.6282)
>>> x[1,2,3,4]
tensor(0.9876)
>>> y[1,2,3,4]
tensor(-0.6282)
```

### System Info

diffusers id `38adcd21bd9cc69f84710deb161c578b6478944f`

**Comment by rob-hen** [comment]
The confusion arises from line [402](https://github.com/huggingface/diffusers/blob/38adcd21bd9cc69f84710deb161c578b6478944f/src/diffusers/models/unet_3d_condition.py#LL402C46-L402C46) which says `sample.shape[1]` is the frame dimension. However, according to line [451](https://github.com/huggingface/diffusers/blob/38adcd21bd9cc69f84710deb161c578b6478944f/src/diffusers/models/unet_3d_condition.py#L451), its actually `sample.shape[2]`

**Comment by patrickvonplaten** [comment]
Hey @rob-hen, 

Could you post a code snippet that shows a current failure case of `diffupsers` as a reason of the seemingly incorrect reshape? We probably need to see a `diffusers` failure to continue here

**Comment by rob-hen** [comment]
To make it more clear:

the referenced line 402 says: `sample (`torch.FloatTensor`): (batch, num_frames, channel, height, width) noisy inputs tensor`, i.e. the sample[1] describes the frame. 

However, in line 451, we have `num_frames = sample.shape[2]`, contradicting line 402.

**Comment by patrickvonplaten** [comment]
I see, would you like to open a PR to fix the docstrings? :-)
