### ISSUE TITLE
[New feature] Add ControlNet `conditioning_scale` scheduling to StableDiffusionControlNetPipeline

### ISSUE THREAD

**Issue by julien-blanchon** [huggingface/diffusers#3759]
**Is your feature request related to a problem? Please describe.**

In many use case a fixed ControlNet `conditioning_scale` is not appropriate. For example in [this](https://huggingface.co/spaces/blanchon/qrcode-diffusion) project, I'm trying to constraint a stable diffusion model to overlay a QR code using ControlNet brightness conditioning. However a static conditioning scale will constraint the generated image to be boxed as a QR code.

A common solution is to schedule the conditioning scale during denoising. In [Automatic1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui) this is done with a linear schedule from a **start** value to a **end** value.

**Describe the solution you'd like**

A linear schedule from a **start** value to a **end** value is enough for most use cases. A more complex schedule system could be implemented later if needed but will result to a more complex API.

This could be done in the `StableDiffusionControlNetPipeline` class.

A **first implementation** could be: *A tuple[float, float] `(start, end)` as `conditioning_scale` value and (keep the standard float `value` for a fixed `conditioning_scale` value in the same function).*

```python
...

pipe(
    # ...
    conditioning_scale=(0.01, 0.1),
    # ...
)
```

**Describe alternatives you've considered**

A **second implementation** could be: *A custom scheduling ControlNetScaleSchedule class (and keep standard API in the same function)*

```python
controlNetScaleSchedule = ControlNetScaleSchedule(
    start=0.01,
    end=0.1,
    schedule="linear",
)

pipe(
    # ...
    conditioning_scale=controlNetScaleSchedule,
    # ...
)
```

A **third implementation** could be: *A separed \_\_call\_\_ method overload with a `start_conditioning_scale` and `end_conditioning_scale` parameters*

```python
class StableDiffusionControlNetPipeline(...):
    ...

    @overload
    def __call__(
        self,
        ...
        start_conditioning_scale: float,
        end_conditioning_scale: float,
        ...
    ) -> torch.Tensor:
        ...

    ...


pipe(
    # ...
    start_conditioning_scale=0.01,
    end_conditioning_scale=0.1,
    # ...
)
```

**Comment by Bochu3** [comment]
I'm looking for this feature too. There are start and end setting in community pipeline but not in the official one
#3758

**Comment by julien-blanchon** [comment]
As I said in #3758, we need to discuss the best implementation and what will fit the most with the hugginface way of doing.

I personally like the idea of using @overload in my project because this make the typing easier and tend to produce simpler function. But this is not very pythonic and not well suported by every IDE. Plus this could be misleading for some people.
What's your point on that ? Is `overload` allowed in diffusers.

The 1st idea is the most pythonic but will need many refactoring (you can have a look on my PR #3760 (oups made this by error :(().

The 2nd idea has the disadvantage of the first one + a second layer of complexity with the Sceduler class.

My point of view is that `@overload` is still the best implementation we can make

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten here. Related to https://github.com/huggingface/diffusers/issues/3758

**Comment by Abecid** [comment]
Great Feature!
