### ISSUE TITLE
Can't load 2 community pipelines in same process

### ISSUE THREAD

**Issue by reimager** [huggingface/diffusers#3761]
### Describe the bug

Loading 2 community pipelines leads to it confusing the 2 classes.
Reproducible steps below

### Reproduction

I'm trying to avoid loading community pipelines through the hub so I'm only loading community pipelines locally now.

So I'm doing something like:
```
mkdir -p /usr/local/src/diffusers/community_models/stable_diffusion_controlnet_img2img
cp /usr/local/src/diffusers/examples/community/stable_diffusion_controlnet_img2img.py /usr/local/src/diffusers/community_models/stable_diffusion_controlnet_img2img/pipeline.py
mkdir -p /usr/local/src/diffusers/community_models/stable_diffusion_reference
cp /usr/local/src/diffusers/examples/community/stable_diffusion_reference.py /usr/local/src/diffusers/community_models/stable_diffusion_reference/pipeline.py
```

The problem is that you still can't load 2 community pipelines. There is some class caching somewhere, so when you try to load the second one, it actually tries to load the first pipeline's class. For example:

```py
import torch
from diffusers import (
    DiffusionPipeline,
)

print("Loading community pipeline controlnet...")
mod1 = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", custom_pipeline="/usr/local/src/diffusers/community_models/stable_diffusion_controlnet_img2img", tourch_dtype=torch.float16, safety_checker=None, required_safety_checker=False, local_files_only=True, controlnet=None)

print("Loading community pipeline reference...")
mod2 = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", custom_pipeline="/usr/local/src/diffusers/community_models/stable_diffusion_reference", tourch_dtype=torch.float16, safety_checker=None, required_safety_checker=False, local_files_only=True)

print("done")
```

the second from_pretrained throws the exception:

```
Traceback (most recent call last):
  File "./test.py", line 15, in <module>
    mod2 = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", custom_pipeline="/usr/local/src/diffusers/community_models/stable_diffusion_reference", revision="fp16", tourch_dtype=torch.float16, safety_checker=None, required_safety_checker=False, local_files_only=True)
  File "/usr/local/src/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 1096, in from_pretrained
    raise ValueError(

ValueError: Pipeline <class 'diffusers_modules.local.pipeline.StableDiffusionControlNetImg2ImgPipeline'> expected {'vae', 'controlnet', 'safety_checker', 'unet', 'tokenizer', 'text_encoder', 'feature_extractor', 'scheduler'}, but only {'vae', 'safety_checker', 'unet', 'tokenizer', 'text_encoder', 'feature_extractor', 'scheduler'} were passed.
```

notice the class is actually "StableDiffusionControlNetImg2ImgPipeline" which expects a controlnet argument so it throws said exception.

### System Info

- `diffusers` version: 0.17.1
- Platform: Linux-5.10.0-23-amd64-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.1.0a0+fe05266 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.31.0.dev0
- Accelerate version: 0.20.0.dev0
- xFormers version: not installed

**Comment by reimager** [comment]
For others encountering this issue a janky/undocumented workaround for this issue is just importing them directly

```
import sys
sys.path.insert(0, '/usr/local/src/diffusers/community_models')
from stable_diffusion_controlnet_img2img.pipeline import StableDiffusionControlNetImg2ImgPipeline
from stable_diffusion_reference.pipeline import StableDiffusionReferencePipeline

print("Loading community pipeline controlnet...")
mod1 = StableDiffusionControlNetImg2ImgPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", revision="fp16", tourch_dtype=torch.float16, safety_checker=None, required_safety_checker=False, local_files_only=True, controlnet=None)

print("Loading community pipeline reference...")
mod2 = StableDiffusionReferencePipeline.from_pretrained("runwayml/stable-diffusion-v1-5", revision="fp16", tourch_dtype=torch.float16, safety_checker=None, required_safety_checker=False, local_files_only=True)

print("done")
```

**Comment by satwiksunnam19** [comment]
`!pip install git+https://github.com/huggingface/diffusers.git `

`! pip install transformers`
`! pip install patch_ng`
`! pip install safetensors`
`!pip install omegaconf`

`import sys`

`%cd /content/diffusers/examples/community`
`import torch`
`sys.path.insert(0, '/usr/local/src/diffusers/examples/community')`
`from stable_diffusion_controlnet_img2img import StableDiffusionControlNetImg2ImgPipeline`
`from stable_diffusion_reference import StableDiffusionReferencePipeline`

`print("Loading community pipeline controlnet...")`
`mod1 = StableDiffusionControlNetImg2ImgPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", revision="fp16", tourch_dtype=torch.float16, safety_checker=None, required_safety_checker=False, controlnet=None)`

`print("Loading community pipeline reference...")`
`mod2 = StableDiffusionReferencePipeline.from_pretrained("runwayml/stable-diffusion-v1-5", revision="fp16", tourch_dtype=torch.float16, safety_checker=None, required_safety_checker=False)`

`print("done")`

This works absolutely fine with my system 
` local_files_only=True` if  you wanted to use this it should have all the model weights ex :(VAE, Feature_Extractor, etc..)placed in the correct folder, if you don't want to use the above parameter remove that and this works absolutely fine 

![image](https://github.com/huggingface/diffusers/assets/83942187/53ff4dea-b704-47bf-beb7-14906634a01b)

**Comment by reimager** [comment]
> This works absolutely fine with my system ` local_files_only=True` if you wanted to use this it should have all the model weights ex :(VAE, Feature_Extractor, etc..)placed in the correct folder, if you don't want to use the above parameter remove that and this works absolutely fine

Yes, I'm aware importing them directly works - thats why I posted it as a workaround, but that is not the documented way to load community pipelines.

**Comment by satwiksunnam19** [comment]
If you have the structured folder like diffusers, that might work, i think so you have missing folder structure or folders in it
