### ISSUE TITLE
DDPO Example

### ISSUE THREAD

**Issue by abhijitpal1247** [huggingface/diffusers#3768]
**Is your feature request related to a problem? No.
A clear and concise description of what the problem is. 
Current implementation of DDPO supports only TPU. 
A general implementation that also supports GPU would be a great addition to the existing examples of diffusers library.

Supporting links:

- https://github.com/jannerm/ddpo
- https://github.com/vinhkhuc/ddpo/tree/support_gpu

**Comment by abhijitpal1247** [comment]
CC @jannerm

**Comment by dg845** [comment]
Hi, I'd be interested in working on this if the DDPO authors don't pick this up :).

**Comment by patrickvonplaten** [comment]
Go for it! :-)

**Comment by dg845** [comment]
I have opened a PR with some rough initial code at #3860.

**Comment by abhijitpal1247** [comment]
@patrickvonplaten, @dg845 
I guess, an implementation is available by the authors: https://github.com/kvablack/ddpo-pytorch
