### ISSUE TITLE
Quatered image produced, StableDiffusionPanoramaPipeline

### ISSUE THREAD

**Issue by inkyusa** [huggingface/diffusers#3769]
### Describe the bug

Hi,
Anyone experienced the following when running the [multidifussion tutorial](https://huggingface.co/docs/diffusers/main/en/api/pipelines/panorama)? 
It generates a quater dolomites with the default setup but, correct one with `height=1024`

### Reproduction

Just did as shown in https://huggingface.co/docs/diffusers/main/en/api/pipelines/panorama

```
import torch
from diffusers import StableDiffusionPanoramaPipeline, DDIMScheduler

model_ckpt = "stabilityai/stable-diffusion-2-base"
scheduler = DDIMScheduler.from_pretrained(model_ckpt, subfolder="scheduler")
pipe = StableDiffusionPanoramaPipeline.from_pretrained(model_ckpt, scheduler=scheduler, torch_dtype=torch.float16)

pipe = pipe.to("cuda")

prompt = "a photo of the dolomites"
image = pipe(prompt).images[0]  #1/4
#image = pipe(prompt, height=1024).images[0] #looks ok.
image.save("dolomites.png")
```
![quater-dolomites](https://github.com/huggingface/diffusers/assets/5215050/f1b9bbb8-b4dd-4819-8df0-566b693448b1)

### System Info

- `diffusers` version: 0.18.0.dev0
- Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.27
- Python version: 3.9.16
- PyTorch version (GPU?): 1.13.0 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.29.2
- Accelerate version: 0.18.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
I can reproduce this on Colab. However installing from this commit https://github.com/huggingface/diffusers/commit/2f997f30ab660472561f5e1b5232d4f116315b1b, fixes the issue. 

```
!pip install -q git+https://github.com/huggingface/diffusers@2f997f30ab660472561f5e1b5232d4f116315b1b
```

So, my gut says it was likely introduced in https://github.com/huggingface/diffusers/pull/3546. 

Cc: @Isotr0py. Could you look into it once?

**Comment by Isotr0py** [comment]
I tested a94977b8b32b94ccd00d2f8f812aadb46764baba on Colab, and it works normally.
```
!pip install git+https://github.com/huggingface/diffusers@a94977b8b32b94ccd00d2f8f812aadb46764baba
```
![下载](https://github.com/huggingface/diffusers/assets/41363108/fd4b1f83-76e7-4b6e-a5e9-4a5b96e52dc5)

And this issue also appeared in `DPMSolverMultistepScheduler`, it seems that it's not about the schedulers but the blocks initialization.

So I think it was introduced in #3632, because we make some small changes to blocks initialization to support batched denoise. I may miss something in this PR.

I will check it out once I have spare time.

**Comment by sayakpaul** [comment]
@inkyusa could you install `diffusers` from source (i.e., `pip install git+https://github.com/huggingface/diffusers/`) and retry once? 

@Isotr0py helped fixed in https://github.com/huggingface/diffusers/pull/3800. Thank you!

**Comment by inkyusa** [comment]
Thanks for the response and hotfix.
I tested with d49e2dd54caebcc3b781724b751c66e1d2a5556e and confirmed that it worked as it should.
Cheers,
