### ISSUE TITLE
Benchmark for max-autotune VS reduce-overhead ?

### ISSUE THREAD

**Issue by oxysoft** [huggingface/diffusers#3775]
Reading the docs for `torch.compile`, I couldn't help but notice this 'max-autotune' option. Real-time addicts like me are always on the lookout for any millisecond they can scrape, so I think it would be interesting to include this in the benchmarks on this page https://huggingface.co/docs/diffusers/main/en/optimization/torch2.0#using-accelerated-transformers-and-torchcompile as well as comparing the overhead tradeoff.

Nicolas

**Comment by patrickvonplaten** [comment]
Thanks for the pointer! Do you have any benchmark numbers for using `max-autotune`?
