### ISSUE TITLE
Cannot load multiple LoRAs. Need to revert PR #3649

### ISSUE THREAD

**Issue by JemiloII** [huggingface/diffusers#3781]
### Describe the bug

https://github.com/huggingface/diffusers/pull/3649 Introduced a bug. It automatically reverts any lora loaded when calling load_lora_weights. I can no longer load multiple loras. Rather than automatically unloading loras, we should have a method to unload them individually and a method to unload them all. This change has completely broke my app and I have to downgrade or revert the files in PR #3649

### Reproduction

Just use load_lora_weights multiple times and note that only a single lora is in use.

### System Info

diffusers v0.17.1

**Comment by sayakpaul** [comment]
Were you observing expected outputs with multiple LoRAs? If so, I would appreciate some concrete examples here. I am asking this because we actually don't have the technical implementation to support operating with multiple LoRAs. 

Also, if you checked the PR https://github.com/huggingface/diffusers/pull/3649, you'd have noticed that we had to do it to avoid latching into recursive calls to monkey-patching. 

So, the broader question here is supporting multiple LoRAs in a streamlined manner (which we are internally brainstorming already).

**Comment by sayakpaul** [comment]
>  I still see this as a bug as there is no option to not disable the auto-remove feature added

See https://github.com/huggingface/diffusers/issues/3689. Specifically https://github.com/huggingface/diffusers/issues/3689#issuecomment-1582323065

Regarding supporting other formats and multiple variants of them, we don't have anything immediate. We will continue to monitor it and look for opportunities here and happy to accept community contributions after some discussions with the potential contributors. 

A good example is: https://github.com/huggingface/diffusers/pull/3437 (by @takuma104). 

Cc: @patrickvonplaten

**Comment by takuma104** [comment]
@JemiloII If you want to use multiple LoRAs at the same time right now, you can use the hook version I wrote before. Although this code couldn't be directly merged into Diffusers, it's what I personally use. The usage is written in the comments, so please refer to that.
https://gist.github.com/takuma104/e38d683d72b1e448b8d9b3835f7cfa44

**Comment by JemiloII** [comment]
@takuma104 Yeah, this works very well. I was able to reuse my original LoRA scales/weights from before and generate the same images.

**Comment by sayakpaul** [comment]
@JemiloII thanks for trying out Takuma's version. 

With https://github.com/huggingface/diffusers/issues/3781#issuecomment-1591273917 in mind, maybe we can close the issue? 

As mentioned, we will revisit the design to support multiple LoRAs from diffusers preferably using `peft`.

**Comment by JemiloII** [comment]
Sounds good to me. Thanks again.
