### ISSUE TITLE
Correspondence of Text-To-Video pipeline to Modelscope

### ISSUE THREAD

**Issue by rob-hen** [huggingface/diffusers#3784]
The text-to-video pipeline `TextToVideoSDPipeline` described [here](https://huggingface.co/docs/diffusers/api/pipelines/text_to_video) is used to implement [VideoFusion](https://arxiv.org/pdf/2303.08320.pdf) if I understand correct. However, VideoFusion uses a base model, base noise and a residual model with a residual noise. 

Looking at the source code of the pipeline I don't see that a shared noise is sampled or that there are two diffusion models involved. Also there is no option to set the parameter `lambda`, as described in the paper, to balance between the base and residual information. 

How can thus the pipeline be used for modelscope/videofusion?

**Comment by jfischoff** [comment]
Your not the only one asking about this https://github.com/modelscope/modelscope/issues/284

I think, but could be wrong, that the models in the wild use the architecture in the huggingface and modelscope but not the one in the paper. I'm curious about this as well.

**Comment by rob-hen** [comment]
Hey @patrickvonplaten,

but again, that model is referencing to VideoFusion. So I still don't understand the relation to it.

**Comment by patrickvonplaten** [comment]
Ah I see, I think in this case it'd be best to ask the authors on the original code repo: https://github.com/modelscope/modelscope

**Comment by WangJiuniu** [comment]
VideoFusion is another work from our team, which is weakly related to this model. This model is called ModelScope Text-to-Video (ModelScopT2V). Please see the 19th page of the following PDF for the implementation detail.

Thank you!

[ModelScopeT2V_slides.pdf](https://github.com/modelscope/modelscope/files/11901459/ModelScopeT2V_slides.pdf)
