### ISSUE TITLE
has_nsfw_concept is a bool

### ISSUE THREAD

**Issue by orenong** [huggingface/diffusers#3790]
Hi, I noticed that most of the implementations of the smooth zoom in SD died because of an error that comes from 

pipeline_stable_diffusion_inpaint.py, line 1064 

"TypeError: 'bool' object is not iterable"

Wonder if anybody knows what caused it and if it's a bug

**Comment by takhyun12** [comment]
I had the same issue after the version upgrade, but I was able to resolve it.

I had used a trick to disable the safety_check in the pipeline as follows, but after the version upgrade, the code checks if it's None, so I made the following changes.

Before:
```python
pipeline.safety_checker = lambda images, clip_input: (images, False)
```
After:
```python
pipeline.safety_checker = lambda images, clip_input: (images, None)
```

**Comment by orenong** [comment]
> Can you please add a reproducible code snippet?
The colab in this one is an example for when it breaks
https://github.com/BalintKomjati/smooth-infinite-zoom 


> I had the same issue after the version upgrade, but I was able to resolve it.
> 
> I had used a trick to disable the safety_check in the pipeline as follows, but after the version upgrade, the code checks if it's None, so I made the following changes.
> 
> Before:
> 
> ```python
> pipeline.safety_checker = lambda images, clip_input: (images, False)
> ```
> 
> After:
> 
> ```python
> pipeline.safety_checker = lambda images, clip_input: (images, None)
> ```
I can't disable NSFW, it's highly important for my use case

**Comment by rsxdalv** [comment]
Unless something has been fixed in the background, this issue does not seem to be fixed.

Here's the downstream impact: https://github.com/riffusion/riffusion/issues/148
