### ISSUE TITLE
StableDiffusionControlNetImg2ImgPipeline Not Working As it Should

### ISSUE THREAD

**Issue by xiankgx** [huggingface/diffusers#3792]
### Describe the bug

I'm using StableDiffusionControlNetImg2ImgPipeline and I believe it to be a "generalized" pipeline:
- If I want to do text2image, I set strength=1.0
- If I want to do image2image, I set strength<1.0
- If I want to use ControlNet, I set controlnet_conditioning_scale to > 1.0
- If I want to disable ControlNet, I set controlnet_conditioning_scale to 0.0

However, I find that this is not the case for image2image. From conventional Stable Diffussion image2image, **with a low strength value close to 0.0**, I would expect **the generated image to be very similar to the input image**. As you can see below from my experimentations with StableDiffusionControlNetImg2ImgPipeline, this is not the case.

For this bug description, I will use the following settings:
```
image: https://images.unsplash.com/photo-1523450001312-faa4e2e37f0f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z2lybCUyMGRhbmNpbmd8ZW58MHx8MHx8fDA%3D&w=1000&q=80
prompt: girl dancing
num_inference_steps: 20
guidance_scale: 9.0
seed: 21
```
Here are what I got. The following images are in the format: input_image, controlnet_1_control_image, controlnet_2_control_image, and generated_image

**strength=1.0; controlnet_conditioning_scale=[0.5, 0.5]**
![image](https://github.com/huggingface/diffusers/assets/4113258/f80b5964-7c9c-45cb-a56b-03858557e879)

**strength=1.0; controlnet_conditioning_scale=[0, 0]**
![image](https://github.com/huggingface/diffusers/assets/4113258/7574e515-4288-48d0-a8ab-1449af47e942)

**strength=0.1; controlnet_conditioning_scale=[0.5, 0.5]**
![image](https://github.com/huggingface/diffusers/assets/4113258/3dbbcba2-26d1-4c2a-81c0-dbdeb779c9c3)

**strength=0.1; controlnet_conditioning_scale=[0, 0]**
![image](https://github.com/huggingface/diffusers/assets/4113258/42b24b1d-d0ed-4d54-a370-fe447ab399cd)

As you can see from the above images, for a low strength value, the generated images is very pale. This contradicts with my past experience with Stable Diffusion image2image.

Here are my environment:
```
diffusers==0.17.1
torch==2.0.1
torchvision==0.15.2
accelerate==0.20.3
xformers==0.0.20
```

### Reproduction

```
diffusers==0.17.1
torch==2.0.1
torchvision==0.15.2
accelerate==0.20.3
xformers==0.0.20
```

### System Info

```
diffusers==0.17.1
torch==2.0.1
torchvision==0.15.2
accelerate==0.20.3
xformers==0.0.20
```

**Comment by xiankgx** [comment]
Hmmm, I think this is also a problem of the standard StableDiffusionImg2ImgPipeline.

strength=0.1
![image](https://github.com/huggingface/diffusers/assets/4113258/0a7519be-1cf6-4a71-931e-8bde188609c3)

**Comment by xiankgx** [comment]
This is what I got from DreamStudio.

Top row: image_weight: 10%, bottom row: image_weight: 90%
![image](https://github.com/huggingface/diffusers/assets/4113258/14983ff7-7f89-4fa1-992b-37d2ee7db712)

**Comment by patrickvonplaten** [comment]
@yiyixuxu @sayakpaul does any of you have time to pick this one up?

**Comment by xiankgx** [comment]
Sorry guys, I think this is a usage error.

Images to pipeline call function should be of type PIL.Image.Image, while I was supplying some images of type np.ndarray.

**Comment by yiyixuxu** [comment]
hi @xiankgx:

Thanks for letting us know! However all our img2img pipelines should be able to work with images in all 3 format: np.ndarray, PIL.Image and torch tensor so I don't think it is a usage error - would you be able to provide an example of numpy image that you used? I'd be happy to look into this
