### ISSUE TITLE
Unused parameters in scheduler `init`'s

### ISSUE THREAD

**Issue by natolambert** [huggingface/diffusers#380]
**What API design would you like to have changed or added to the library? Why?**

I see some of the [schedulers](https://github.com/huggingface/diffusers/blob/7bd50cabafc60bf45ebbe1957b125d3f4c758ba8/src/diffusers/schedulers/scheduling_lms_discrete.py#L34) had these parameters added to init
```
        trained_betas: Optional[np.ndarray] = None,
        timestep_values: Optional[np.ndarray] = None,
```
I'm guessing the first is an option to directly pass betas when creating the scheduler, but what is `timestep_values` for? I didn't see any uses. 

I would like to regularize these (e.g. seems like all DDPM -like schedulers can use `trained_betas` pretty easily)

Can easily address this while completing #376.

**Comment by patrickvonplaten** [comment]
Is this issues still relevant? Think you are right indeed and we can remove such parameters

**Comment by Hafiidz** [comment]
To add, I keep getting this warning/log with default example txt2img and img2img pipe. `{'trained_betas'} was not found in config. Values will be initialized to default values.`

**Comment by natolambert** [comment]
I think I have updated all the unused parameters throughout documentation changes.

RE @Hafiidz 's point, I think that is because the config on the hub is missing the entry? I'm not 100% sure. Future model versions will likely address this.

**Comment by patrickvonplaten** [comment]
@Hafiidz, 

That's good feedback, I think we should relax the warning to a logger.info statement to make for better user experience. @anton-l do you have a spare minute to take a look here?

**Comment by patil-suraj** [comment]
@patrickvonplaten Yes, those were added for BDDM which we don't have now, so I think it's fine to remove them now.

**Comment by patrickvonplaten** [comment]
@anton-l could you take a look?

**Comment by anton-l** [comment]
Not sure about removing `trained_betas`, because they are functioning as designed, and someone might be using them already.
Gently deprecating them is an option, but only if we don't have plans for pipelines that need them. @patil-suraj is BDDM on our roadmap?

**Comment by natolambert** [comment]
What's BDDM?

**Comment by kashif** [comment]
https://github.com/tencent-ailab/bddm speech model
