### ISSUE TITLE
--checkpoints_total_limit argument doesn't work in training examples

### ISSUE THREAD

**Issue by ShlomoLibo** [huggingface/diffusers#3802]
### Describe the bug

When training examples from ```diffusers/examples``` (e.g.  ```diffusers/examples/unconditional_image_generation```) and using ```--checkpoints_total_limit```, the desired behavior of limiting the number of checkpoints doesn't work. Instead, there is no limit to the number of checkpoints and the behavior is identical with or without the flag.

**Reason for the bug:**
The description of the ```--checkpoints_total_limit``` argument is the following:
```
"Max number of checkpoints to store. Passed as `total_limit` to the `Accelerator` `ProjectConfiguration`."
            " See Accelerator::save_state https://huggingface.co/docs/accelerate/package_reference/accelerator#accelerate.Accelerator.save_state"
            " for more docs"
```
When actually inspecting closely, ```total_limit``` flag used only in case that the ```ProjectConfiguration``` object passed to ```Accelerator``` has ```automatic_checkpoint_naming=True```, instead of using that flag, the training scripts use their own naming scheme involving the ```global_steps``` as index, thus the ```total_limit``` feature is not used and ```--checkpoints_total_limit``` has no effect.

**Possible Solution Idea:**
Modify the script such that the checkpointing part will look something similar to:
```
                if global_step % args.checkpointing_steps == 0:
                    if accelerator.is_main_process:
                        project_configuration.iteration = global_step
                        save_location = accelerator.save_state(args.output_dir)
                        logger.info(f"Saved state to {save_location}")
```
The changes it implied is that checkpoints would be saved in a single directory called ```checkpoints``` and the seperator would be "_" instead of "-" (i.e. ```<out_dir>/checkpoints/checkpoint_500``` instead of ```<out_dir>/checkpoint-500```
Thus compatibility with ```--resume_from_checkpoint``` should be checked for.

**I fixed locally the ```unconditional_image_generation``` script and it works for me, if this issue and the solution are confirmed to be good, I intend to make a PR for all the examples for which this issue is relevant**

### Reproduction

1.  Setup environment as described in ```diffusers/blob/main/examples/unconditional_image_generation/README.md``

2.  Run the following training script:
```
accelerate launch train_unconditional.py \
  --dataset_name="huggan/flowers-102-categories" \
  --resolution=64 --center_crop --random_flip \
  --output_dir="ddpm-ema-flowers-64" \
  --train_ \
  --gradient_accumulation_steps=1 \
  --use_ema \
  --learning_rate=1e-4 \
  --lr_warmup_steps=500\
  --checkpoints_total_limit=1\
  --checkpointing_steps=1
```

### System Info

- `diffusers` version: 0.18.0.dev0
- Platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.31
- Python version: 3.11.3
- PyTorch version (GPU?): 2.0.1+cu117 (False)
- Huggingface_hub version: 0.15.1
- Transformers version: not installed
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

Note: the command ```diffusers-cli env``` was run on the file server, the server on which the script is run on uses a GPU.

### Who can help?

@williamberman @sayakpaul @yiyi

**Comment by williamberman** [comment]
https://github.com/huggingface/diffusers/pull/3681 will be merged shortly

**Comment by ShlomoLibo** [comment]
> #3681 will be merged shortly

Dang, missed it :D
