### ISSUE TITLE
Running `diffusers` with `torch`-DDP leads to warning on stride mismatch

### ISSUE THREAD

**Issue by eeshandhekane** [huggingface/diffusers#3809]
### Describe the bug

Hey folks! 
First off, thanks a lot for the amazing work with `diffusers`! 
Recently, we have observed a warning while using `diffusers`-based models and running scripts. 
We also observe similar warning while using *only* the models provided in `diffusers/models/`. 
While this error might not be critical, we wanted to highlight the issue.
Thanks in advance!

### Reproduction

Below are the steps that can be taken to observe this warning:
  1. Download the `diffusers` repository as mentioned in the documentation.
  2. Set a run with `train_unconditional.py` script as mentioned in the [Unconditional image generation](https://huggingface.co/docs/diffusers/training/unconditional_training) tutorial.
  3. Use vanilla `torch` DDP.

With this setup, we observe that we hit a warning about stride mismatch in the gradients and the bucket view:
<img width="1724" alt="warning-image" src="https://github.com/huggingface/diffusers/assets/26852397/c981d75f-dd6b-49fb-9017-5e09ec0c71ba">

### System Info

We are using the following version of different packages:
Diffusers: `diffusers==0.15.0`
Torch: `torch==1.13.0`
Python: `Python 3.9.16`

**Comment by patrickvonplaten** [comment]
Interesting! Thanks for the heads-up, gently pinging @williamberman and @sayakpaul here

**Comment by williamberman** [comment]
Neat @eeshandhekane ! afaik accelerate is what handles manually wrapping in ddp under the hood, I'm not familiar with this warning and what the performance implications are. Might be worth starting a thread on the accelerate forum. W/out concrete numbers on what the performance impacts are I'm not sure how actionable it is for us :)

**Comment by sayakpaul** [comment]
Would also suggest trying to replicate this in a minimal manner (potentially with a similar but smaller model). 

I am going to close this thread for now, as there's nothing actionable here for us as of yet. As @williamberman suggested, maybe open a thread here: https://github.com/huggingface/accelerate.
