### ISSUE TITLE
Error in section `3. How to write your own inference pipeline with diffusers` of the notebook `diffusers/stable_diffusion.ipynb`

### ISSUE THREAD

**Issue by pootow** [huggingface/diffusers#381]
### Describe the bug

Just open the notebook in colab, and you will get:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-27-912da26b456b>](https://localhost:8080/#) in <module>
      1 #image = torch.from_numpy(image)       # it seems image needs to be a tensor but a numpy, this line fixes this error, but a new error comes out.
----> 2 image = (image / 2 + 0.5).clamp(0, 1)
      3 image = image.detach().cpu().permute(0, 2, 3, 1).numpy()
      4 images = (image * 255).round().astype("uint8")
      5 pil_images = [Image.fromarray(image) for image in images]

AttributeError: 'numpy.ndarray' object has no attribute 'clamp'
```

### Reproduction

Just open the notebook in colab and run.

### System Info

colab

**Comment by pootow** [comment]
I've found how to fix this. Just a line blow the creation of `scheduler`

```python
scheduler.set_format("pt")
```

**Comment by pcuenca** [comment]
Hi @pootow, thanks for reporting this!

However, I'm unable to reproduce the problem, the notebook is working fine for me. Note that PyTorch format `"pt"` is the default: https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_lms_discrete.py#L36.

Would it be possible that you have some local changes in the notebook, or that you are using a version of diffusers different than `0.2.4`?

**Comment by pootow** [comment]
Sorry, I can't reproduce it either.
