### ISSUE TITLE
Lora loaded with load_lora_weights has no effect on generation.

### ISSUE THREAD

**Issue by lucmaki** [huggingface/diffusers#3811]
### Describe the bug

Trying to load lora with diffusers for the first time given the new update, but they do not seem to have any effect. In this case, I'm trying a Lora that leads to an messy oily painting style and worked perfectly well in Auto1111.

Trying Auto1111, we get this:
![visual](https://github.com/huggingface/diffusers/assets/26182176/66c96188-283b-4de6-a5cb-c0459f83a1b4)

But with diffusers in colab with same parameters, model and workflow to generate (see code below):
![176148ae-5a82-43e7-b5c5-8973da48668e](https://github.com/huggingface/diffusers/assets/26182176/3a29f732-de87-46fb-8571-cb28bbba1346)

Tried pumping up the Lora scaling value, but nothing seems to change. It's all same result I get when I tried not loading the lora at all.

### Reproduction

Starts with standard pipelines, lora loaded for both at the end:
```
import requests
import torch
from PIL import Image
from io import BytesIO

import torch
from diffusers import StableDiffusionImg2ImgPipeline, StableDiffusionPipeline, DPMSolverMultistepScheduler

model_path = "/content/drive/MyDrive/data/models/diffusion/CUSTOM"
lora_path = "/content/drive/MyDrive/data/models/diffusion/LoRA/LORA1.safetensors"

scheduler = DPMSolverMultistepScheduler.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="scheduler")

pipe_txt2img = StableDiffusionPipeline.from_pretrained(model_path,
                                                      scheduler = scheduler,
                                                      torch_dtype=torch.float16,
                                                      safety_checker=None).to("cuda")

pipe_img2img = StableDiffusionImg2ImgPipeline.from_pretrained(model_path,
                                                      scheduler = scheduler,
                                                      torch_dtype=torch.float16,
                                                      safety_checker=None).to("cuda")


pipe_txt2img.load_lora_weights(".", weight_name=lora_path)
pipe_img2img.load_lora_weights(".", weight_name=lora_path)

```

Then inference (small then upscaled, but each pipeline individually had the same issue):
 
```
prompt = "masterpiece, concept art, artstation, abstract, surrealism, (abstract brush strokes:0.8).\
A girl standing amidst a swirling vortex of insects, her face a mask of determination. The background alternates between the chaos of a city in turmoil and the quiet solitude of her loft."
negative_prompt= "lowres, text, naked, bad anatomy, bad hands, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry"
height = 480
width = 640

with torch.no_grad():
    # Step 1: Generate low res image
    image = pipe_txt2img(prompt=prompt,
                         negative_prompt=negative_prompt,
                         height=height,
                         width=width,
                         num_inference_steps=25,
                         guidance_scale=7).images[0]

    # Step 2: Generate 2x high res image from low res image
    width = int(width*2)
    height = int(height*2)
    image = image.resize((width, height))

    image = pipe_img2img(prompt=prompt,
                 negative_prompt=negative_prompt,
                 image=image, 
                 strength=0.60,
                 num_inference_steps=20,
                 guidance_scale=7).images[0]

display(image)
```

### System Info

- `diffusers` version: 0.18.0.dev0
- Platform: Linux-5.15.107+-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: 0.0.20
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@patrickvonplaten
@sayakpaul

**Comment by patrickvonplaten** [comment]
Thanks for the nice reproducible cc'ing @sayakpaul here

**Comment by sayakpaul** [comment]
Thanks for the snippet. I am afraid we don't have the actual LoRA parameter yet. Could you host that on the Hugging Face Hub and let us know?

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
@lucmaki right now which api do you use then?I also wanted to try LoRA made by others.

**Comment by DevonPeroutky** [comment]
I'm also seeing the same issue

**Comment by lucmaki** [comment]
Update: The model and Lora are to be kept private for now, but anyway I've found that with this simple workaround it works:

```
lora_state_dict = safetensors.torch.load_file(
   lora_path, device="cpu"
)

pipe_img2img.load_lora_weights(lora_state_dict)
```

**Comment by sayakpaul** [comment]
Oh okay. If that is case, could we close this issue?
