### ISSUE TITLE
{'controlnet'} was not found in config. Values will be initialized to default values.

### ISSUE THREAD

**Issue by dgr9527** [huggingface/diffusers#3812]
### Describe the bug

I tried the training of the ControlNet in the main branch right away. 
In function log_validation, The following prompts appear:{'controlnet'} was not found in config. Values will be initialized to default values.

### Reproduction

def log_validation(batchs, vae, text_encoder, tokenizer, unet, controlnet, args, accelerator, weight_dtype, step):
    logger.info("Running validation... ")

    controlnet = accelerator.unwrap_model(controlnet)

    pipeline = StableDiffusionControlNetInpaintPipeline.from_pretrained(
        args.pretrained_model_name_or_path,
        vae=vae,
        text_encoder=text_encoder,
        tokenizer=tokenizer,
        unet=unet,
        controlnet=controlnet,
        requires_safety_checker = False,
        safety_checker=None,
        revision=args.revision,
        torch_dtype=weight_dtype,
    )

  pass

### Logs

```shell
06/17/2023 13:23:04 - INFO - __main__ - Running validation... 
{'controlnet'} was not found in config. Values will be initialized to default values.
```

### System Info

- `diffusers` version: 0.18.0.dev0
- Platform: Linux-5.8.0-43-generic-x86_64-with-glibc2.31
- Python version: 3.10.0
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.30.1
- Accelerate version: 0.20.3
- xFormers version: 0.0.20

### Who can help?

@patrickvonplaten @sayakpaul

**Comment by patrickvonplaten** [comment]
Ping again @yiyixuxu here

**Comment by yiyixuxu** [comment]
@dgr9527 Thanks for reporting the issue!
can you provide the command that you used?

**Comment by liuxz-cs** [comment]
So do you solve this problem? I get the similar problem.

**Comment by sayakpaul** [comment]
Could you maybe help us with the command you're using to start your run?

**Comment by liuxz-cs** [comment]
> Could you maybe help us with the command you're using to start your run?

I run my training script with the command 

```
export CUDA_VISIBLE_DEVICES=0,1
python -m torch.distributed.run \
    --nproc_per_node=2  train.py
```

And I complete a new class of Pipeline inherited from diffusers.DiffusionPipeline

I use this to initialize the class

```
pipeline = Controlnet3DStableDiffusionPipeline.from_pretrained(
    pretrained_sd_model_path,
    vae=vae,
    text_encoder=text_encoder,
    unet=unet, 
     controlnet=controlnet,
)
```
I also use accelerate to do the training in multiple gpus with 
```
unet, controlnet, optimizer, lr_scheduler, text_encoder = accelerator.prepare(
        unet, 
        controlnet, 
        optimizer,
        lr_scheduler, 
        text_encoder
    )
```

**Comment by sayakpaul** [comment]
ControlNet3D is not something we maintain. So, we cannot provide any support here sadly.

**Comment by liuxz-cs** [comment]
> ControlNet3D is not something we maintain. So, we cannot provide any support here sadly.

Controlnet3DStableDiffusionPipeline   this class is implemented by ourselves, and it consists of Controlnet and temporal layers, I do not think it matters with this problem

**Comment by max-fofanov** [comment]
Did you fix this issue? I also do sometimes encounter it when using StableDiffusionControlNetImg2ImgPipeline
