### ISSUE TITLE
How to finetune stable diffusion with multi-gpu under the mode of model  parallelism

### ISSUE THREAD

**Issue by chaojiewang94** [huggingface/diffusers#3813]
I wonder if there is any solution to run the demo in  https://github.com/huggingface/diffusers/tree/main/examples/text_to_image with multi-gpu, where VRAM of each gpu is 16G and the total VRAM is 64G.

I don't want to use Lora or 8-bit optimazation method

**Comment by patrickvonplaten** [comment]
This should help I think: 
https://huggingface.co/docs/diffusers/training/distributed_inference
