### ISSUE TITLE
AttributeError: module transformers has no attribute CLIPImageProcessor

### ISSUE THREAD

**Issue by carlthome** [huggingface/diffusers#3816]
### Describe the bug

Getting `AttributeError: module transformers has no attribute CLIPImageProcessor` with [code](https://github.com/carlthome/stable-diffusion/blob/main/main.py) that used to work six months ago. No changes on my end as far as I know.

### Reproduction

```
git clone git@github.com:carlthome/stable-diffusion.git
cd stable-diffusion
pip install -r requirements.txt
python main.py
```

### Logs

```shell
device=device(type='cuda')
Fetching 19 files: 100%|███████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 32930.49it/s]
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
Traceback (most recent call last):
  File "/home/carl/Repos/carlthome/stable-diffusion/main.py", line 12, in <module>
    pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
  File "/home/carl/Repos/carlthome/stable-diffusion/.direnv/python-3.10.11/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 582, in from_pretrained
    class_obj = getattr(library, class_name)
  File "/home/carl/Repos/carlthome/stable-diffusion/.direnv/python-3.10.11/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1069, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module transformers has no attribute CLIPImageProcessor
```

### System Info

- `diffusers` version: 0.7.2
- Platform: Linux-6.1.31-x86_64-with-glibc2.37
- Python version: 3.10.11
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.11.0
- Transformers version: 4.24.0
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
Hey @carlthome,

We cannot maintain repos building on top of diffusers such as `git clone git@github.com:carlthome/stable-diffusion.git`
=> Could you try to add a reproducible code snippet that just depends on `diffusers` ?
