### ISSUE TITLE
class_labels should be provided when num_class_embeds > 0

### ISSUE THREAD

**Issue by rakesh-reddy95** [huggingface/diffusers#3823]
Hi @patrickvonplaten @sayakpaul 

I'm training controlnet for Edge. I followed the readme and executed the scripts and tried to train the circle filling dataset with the base model as stable diffusion v2.1. But facing the following error:

ValueError: class_labels should be provided when num_class_embeds > 0

I see we have to pass the 'class_labels' in the following function call.

                down_block_res_samples, mid_block_res_sample = controlnet(
                    noisy_latents,
                    timesteps,
                    encoder_hidden_states=encoder_hidden_states,
                    controlnet_cond=controlnet_image,
                    return_dict=False,
                )

Because, when the class_embedding ='projection' is given it enters the following condition and throws the error, as by default the class_labels is None (https://github.com/huggingface/diffusers/blob/f7cc9adc05c36985c8b3f3e95a54940ddac5b4ca/src/diffusers/models/controlnet.py#LL449C9-L449C16). 

if self.class_embedding is not None:
            if class_labels is None:
                raise ValueError("class_labels should be provided when num_class_embeds > 0")

            if self.config.class_embed_type == "timestep":
                class_labels = self.time_proj(class_labels)

            class_emb = self.class_embedding(class_labels).to(dtype=self.dtype)
            emb = emb + class_emb
            
Can you please check this bug or give the working notebook to test? Or tell us what value to be passed for class_labels while calling controlnet?

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu and @williamberman here

**Comment by sayakpaul** [comment]
For easier reproducibility, please include all the commands you used for launching training and the library versions.

**Comment by rakesh-reddy95** [comment]
@sayakpaul 
This can be closed now. I will be passing the empty class embeddings to the controlnet and Clip generated embeddings to Unet. Ideally the current diffusers controlnet supports stable-diffusion-1.5 but when we use Stable diffusion 2.1 unclip, the class_embedding will not be passed as Null. Hence the script has to get the class_labels which are missing. 


 Following this: https://github.com/HeliosZhao/ControlNet-Stable-UnCLIP/blob/main/train_controlnet_unclip_depth.py
