### ISSUE TITLE
Tokenizer error using civitai models as a starting point

### ISSUE THREAD

**Issue by elbamos** [huggingface/diffusers#3827]
I'm getting this error: 

```
ValueError: Calling CLIPTokenizer.from_pretrained() with the path to a single file or url is not supported for this tokenizer. Use a model identifier or the path to a directory
instead.
```

I see that at least one person on Reddit ran into the same issue, but that was months ago and there's no explanation of how it was fixed. Can anyone help?

**Comment by patrickvonplaten** [comment]
Hey @elbamos,

Could you please try to add a minimal, reproducible code snippet?
