### ISSUE TITLE
TypeError when using LayoutLMv3 in pipeline for Document QA

### ISSUE THREAD

**Issue by FFFiend** [huggingface/diffusers#3828]
I get the following error: ```forward() got an unexpected keyword argument 'image'``` when I run the code below:

```
img = Image.open("test.png").convert("RGB")

nlp = pipeline("document-question-answering","microsoft/layoutlmv3-base")

nlp(img, 'what is the number of tabs open in this window?')
```

Haven't seen anyone run into the same issue, was wondering what the fix is.

**Comment by patrickvonplaten** [comment]
Hey @FFFiend, I think this is not related to `diffusers`, but rather `transformers`: https://github.com/huggingface/transformers ?

**Comment by FFFiend** [comment]
Oops, my bad.
