### ISSUE TITLE
Add controlnet module to instruct pix2pix training code 

### ISSUE THREAD

**Issue by mahdip72** [huggingface/diffusers#3834]
How can I add controlnet module to the instruct pix2pix training code?
Should I use it this way:

```
controlnet = ControlNetModel.from_pretrained(args.controlnet_model_name_or_path)
unet = UNet2DConditionModel.from_pretrained("timbrooks/instruct-pix2pix")

.
.
.

down_block_res_samples, mid_block_res_sample = controlnet(
                    noisy_latents,
                    timesteps,
                    encoder_hidden_states=encoder_hidden_states,
                    controlnet_cond=controlnet_image,
                    return_dict=False)

model_pred = unet(
    noisy_latents,
    timesteps,
    encoder_hidden_states=encoder_hidden_states,
    down_block_additional_residuals=[
        sample.to(dtype=weight_dtype) for sample in down_block_res_samples
    ],
    mid_block_additional_residual=mid_block_res_sample.to(dtype=weight_dtype),
).sample
```

Or should I change it?

**Comment by patrickvonplaten** [comment]
Hmm I'm not sure Controlnet fits into this training script tbh - @sayakpaul wdyt?

**Comment by mahdip72** [comment]
I know that controlnet is added to Inpainting SD but I could not find a training script. Only inference code is available. If I see ControlnetInpainting training script maybe I would be able to get an inspiration from it. 
[This link](https://github.com/mikonvergence/ControlNetInpaint)

**Comment by mahdip72** [comment]
I tested the mentioned code in the first post. Generaly, it works okay. But I want to train both unet and controlnet models together, as available in the original repo. In accelerator library, we can only consider one model for gradiant accumulation. 

```
with accelerator.accumulate(controlnet):
    latents = vae.encode(batch["edited_pixel_values"].to(weight_dtype)).latent_dist.sample()
    latents = latents * vae.config.scaling_factor
.
.
.
```
You guys do you have any idea how to solve it?

**Comment by sayakpaul** [comment]
I think this question is better on our Discord forum or the Discuss form TBH since it doesn't relate to the core codebase in general. 

That said, for ControlNet suitable training, I am going to have to refer you to: https://github.com/huggingface/diffusers/blob/main/examples/controlnet (cc: @williamberman and @yiyixuxu).

I am also going to close this issue because of what I stated earlier in the comment.
