### ISSUE TITLE
Bug from_ckpt doesnt use cache_dir parameter when loading and converting safetensor

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [huggingface/diffusers#3836]
### Describe the bug

>pipe = StableDiffusionPipeline.from_ckpt(model_path,use_safetensors=True,cache_dir="store")

___________
During conversion it will ignore the cache_dir flag and direct use huggingfacehub default cache location.

Ideally cache_dir is for users to point to their local path where it stores all models and user can quickly swap between models.
This bug breaks the centralization of model and creates redundancy.

for example,in my cache dir I already have models--openai--clip-vit-large-patch14
but now its downloading again and putting it into the default cache location.the converted model also doesnt obey cache_dir parameter.
I suspect from_ckpt(...) doesnt use the cache_dir parameter

### Reproduction

- setup a inference stable diffusion inference script
- download a 3rd party safetensor model like from civitai site
- put to a folder you like,aka for cache_dir
- edit the code to use  .from_ckpt()
- let it run and check your hugging face cache folder.its downloading to there.

### Logs

```shell
downloading to default cache dir>
Downloading pytorch_model.bin:  25%|█████████████████████                                                               | 304M/1.22G
```

### System Info

py3.10
diffusers                    0.17.0

### Who can help?

hey~@patrickvonplaten, @sayakpaul, and @williamberman can you help me take a look?

**Comment by patrickvonplaten** [comment]
Would you like to open a PR to fix it maybe? :-)

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
fix it.now conversion is fully local.Maybe will PR when I think its stable and etc.

But i just wonder why dont diffusers use like a centralized config system and just some static functions that fetches the values? it would probably automatically make all functions behave consistently just by calling a function with a config object and the inner getting all the values,like cache_dir,use_safetensors=True etc 
all functions can quickly support some common user config if the function uses it.

Besides if the config system is centralized user can even create like a json to save&load config.

in end user usage maybe we can just pass None to not use the preset and fully use passed parameter like =...loadpretrain(modelpath,userconf=None,cache_dir="somepath",device='cpu',load_safety_checker=True)
=...loadpretrain(modelpath,userconf=None,cache_dir="somepath",device='cpu',load_safety_checker=True)
and imagine it having potential to be
=...loadpretrain(modelpath,userconf=loadedconfobject)
=...loadpretrain(modelpath,userconf=loadedconfobject)

**Comment by sayakpaul** [comment]
Closing the issue then! 

But to answer your question here

> But i just wonder why dont diffusers use like a centralized config system and just some static functions that fetches the values? it would probably automatically make all functions behave consistently just by calling a function with a config object and the inner function implement get the values,like cache_dir,use_safetensors=True etc..

We do make use of specific configurations to initialize our models and pipelines. You can learn more about it here: https://huggingface.co/docs/diffusers/main/en/api/configuration.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
So I assume we just do 
diffusers.ConfigMixin.load_config(path,somepath="cache_dir")
#diffusers.ConfigMixin.save_config("diffusersconf.json")

and the pipeline will automatically use it?

I havent opened the PR,why closing it so early?

**Comment by sayakpaul** [comment]
Apologies. I think I didn't understand your query properly. Reopening.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
the config ecosystem is there.But StableDiffusionPipeline.from_ckpt() dont properly respect* the config setting itself.

and I am just a bit confused at how to even use the function with the configmixin object.Because at least as far s I know I havent see any official example that show loading config with pipeline

**Comment by sayakpaul** [comment]
So, after a pipeline is loaded you can access the individual components like so: `pipeline.unet`, `pipeline.text_encoder`, and so on. 

All of those components have got a `config` attribute which you can access by `pipeline.unet.config`. Does this help?

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
noted,huge thanks.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
bump not fixed yet
