### ISSUE TITLE
Pass large images/masks to StableDiffusionInpaintPipeline 

### ISSUE THREAD

**Issue by classicboyir** [huggingface/diffusers#3837]
Currently the `StableDiffusionInpaintPipeline` implementation only allows for 512*512 images/masks. However, in some community applications, I noticed that larger images/masks are also passed to the inpainting model (most probably not through this pipeline). 

The ask is to add this a feature to the `StableDiffusionInpaintPipeline` if it's technically feasible.

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu can you look into this when starting the inpaint refactoR

**Comment by benihime91** [comment]
I would like to request some visibility and clarification regarding the inpaint refactor feature. At the moment, it seems that Diffuser's inpaint functionality is lagging behind Automatic1111's inpaint, even though the settings are similar. I have provided two examples below for comparison. The first example is from Automatic1111's web UI, and the second example is from Diffuser's pipeline. Both examples utilize the same model, scheduler, and seed.

Example 1: 
![00622-8-Face of a yellow cat, high resolution, sitting on a park bench](https://github.com/huggingface/diffusers/assets/52747515/7480e7b8-d855-4bce-ab83-070ef8a0577c)

Example 2: 
![download](https://github.com/huggingface/diffusers/assets/52747515/87e503de-8ba5-4733-80aa-c4bbb33f2aaf)

I would appreciate any information or updates regarding the inpaint refactor feature and its progress. Thank you.

**Comment by patrickvonplaten** [comment]
Hey @benihime91,

We need to be able to run code here. I can't act upon just seeing two different images. How did you generate them? Can you copy-paste the code here?
