### ISSUE TITLE
LoRA weights won't load (HeaderTooLarge)

### ISSUE THREAD

**Issue by jorgejgnz** [huggingface/diffusers#3853]
I'm following [train_text_to_image_lora.py](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py) example.

Saving LoRA weights with:
```
unet = unet.to(torch.float32)
unet.save_attn_procs("path/to/pytorch_lora_weights.bin")
```

Then, loading weights with:
```
unet.load_attn_procs("path/to/pytorch_lora_weights.bin")
```

Results in the following error:
```
File ".../foo.py", line 177, in main
    unet.load_attn_procs("path/to/pytorch_lora_weights.bin")
File ".../lib/python3.9/site-packages/diffusers/loaders.py", line 203, in load_attn_procs
    state_dict = safetensors.torch.load_file(model_file, device="cpu")
File ".../lib/python3.9/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

Is this a bug or there is something I'm missing?
Thank you

**Comment by innat** [comment]
Uninstall safetensor if it is available on your system.

**Comment by jelling** [comment]
> Uninstall safetensor if it is available on your system.
> 
> ```
> pip uninstall safetensors
> ```

Not OP but I had the same issue today and this did not fix it. 

The odd thing is that `.safetensors` LoRAs were loading for me the other day at commit with commit `fc6acb6b97e93d58cb22b5fee52d884d77ce84d8` of Diffusers. I know this because this was running within a Docker image. 

So my LoRA file has not changed, and even with pulling diffusers from main, I'm now getting the previously fixed `HeaderTooLarge` error. Perhaps something else changed in the stack?

**Comment by perrywu1989** [comment]
i have the same issue, what can i do to solve this?

**Comment by innat** [comment]
Uninstalling safetensor did solve my issue somehow but I know it's not the right way. Here was my requirements file.

```
accelerate==0.18.0
bitsandbytes==0.38.1
controlnet-aux==0.0.3
deepspeed==0.9.0
diffusers==0.15.0
timm==0.6.13
torch==2.0.0+cu118
torchvision==0.15.1+cu118
transformers==4.28.1
xformers==0.0.18

or 
diffusers==0.17.0 # ok seems.
```

**Comment by patrickvonplaten** [comment]
cc @sayakpaul @williamberman here

**Comment by patrickvonplaten** [comment]
> I'm following [train_text_to_image_lora.py](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py) example.
> 
> Saving LoRA weights with:
> 
> ```
> unet = unet.to(torch.float32)
> unet.save_attn_procs("path/to/pytorch_lora_weights.bin")
> ```
> 
> Then, loading weights with:
> 
> ```
> unet.load_attn_procs("path/to/pytorch_lora_weights.bin")
> ```
> 
> Results in the following error:
> 
> ```
> File ".../foo.py", line 177, in main
>     unet.load_attn_procs("path/to/pytorch_lora_weights.bin")
> File ".../lib/python3.9/site-packages/diffusers/loaders.py", line 203, in load_attn_procs
>     state_dict = safetensors.torch.load_file(model_file, device="cpu")
> File ".../lib/python3.9/site-packages/safetensors/torch.py", line 259, in load_file
>     with safe_open(filename, framework="pt", device=device) as f:
> safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
> ```
> 
> Is this a bug or there is something I'm missing? Thank you

This should work correctly. @sayakpaul can you maybe check real quick? PyTorch weights should be correctly loaded even if safetensors is installed

**Comment by patrickvonplaten** [comment]
Can you copy-paste a code snippet that shows the exact failure case @jelling ? 
Also I don't think you can/should load a LoRA weight with `enable_xformers_memory_efficient_attention` -> you should just load it with `load_lora_weights` and then call `enable_xformers_memory_efficient_attention`
