### ISSUE TITLE
Would a new "AutoPipeline" API abstraction be helpful?

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#3855]
Many checkpoints can be used for different tasks, e.g. img2img, text2img, but in order to do this at the moment, one has to know what pipelines are linked to each other, e.g. one has to know that `StableDiffusionPipeline` is linked to `StableDiffusionImg2ImgPipeline` when switching from text2img to img2img. Would a new API such as:

`AutoForText2Image`, `AutoForImage2Image`, and `AutoForInpainting`, so that the following case is possible:

```py
from diffusers import AutoForText2Image

text2img = AutoForText2Image.from_pretrained("runwayml/stable-diffusion-v1-5")

img2img = AutoForImage2Image(**text2img.components)
```

**Comment by alexblattner** [comment]
I know you guys don't like my idea, but I think that there's too many pipelines and that there should be a way to use parts of one with another without recreating the pipeline from scratch or using another available. why should there be so many inpainting pipelines when there's just one part that's changed from the original to fit the inpainting part?

I understand wanting to have easily distinguishable pipelines, but this will needlessly increase the workload in my opinion. It's harder in the short term but amazing for the long term

**Comment by patrickvonplaten** [comment]
Ok let's go ahead with a `Auto<Task>Pipeline` so that we can easily switch between tasks for the same checkpoint. 
I'd say we implement the following API:

```py
from diffusers import AutoPipelineForTextToImage, AutoPipelineForImageToImage, AutoPipelineForInpainting

text2image = AutoPipelineForTextToImage.from_pretrained("runwayml/stable-diffusion-v1-5")
image2image = AutoPipelineForImageToImage.from_pipe(text2image)  # zero cost -> we just transfer the components
...
```

@yiyixuxu would you like to give this a try?
