### ISSUE TITLE
Conda version is not updated

### ISSUE THREAD

**Issue by RafailFridman** [huggingface/diffusers#3873]
Hi!
When trying to install diffusers with conda, it installs a pretty old version (0.11):
https://anaconda.org/anaconda/diffusers-torch

Are there plans to update the conda package to the newer version?

**Comment by patrickvonplaten** [comment]
Any reason to not install it via pip ? Guess we can indeed update it on conda though

**Comment by RafailFridman** [comment]
It is just more convenient for me to install everything with conda/mamba.
Thanks

**Comment by patrickvonplaten** [comment]
Guess we could update it there. Need to look into it
