### ISSUE TITLE
StableDiffusionControlNetInpaintPipeline Demo Error, Trying to Fix yields unexpected results

### ISSUE THREAD

**Issue by djj0s3** [huggingface/diffusers#3876]
### Describe the bug

Following instructions from https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py 

there is a function for the controlnet image
```
def make_inpaint_condition(image, image_mask):
        ...     image = np.array(image.convert("RGB")).astype(np.float32) / 255.0
        ...     image_mask = np.array(image_mask.convert("L")).astype(np.float32) / 255.0

        ...     assert image.shape[0:1] == image_mask.shape[0:1], "image and image_mask must have the same image size"
        ...     image[image_mask > 0.5] = -1.0  # set as masked pixel
        ...     image = np.expand_dims(image, 0).transpose(0, 3, 1, 2)
        ...     image = torch.from_numpy(image)
        ...     return image
```
This function however throws an error when used:
```
/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/diffusers/image_processor.py:204: FutureWarning: Passing 'image' as torch tensor with value range in [-1,1] is deprecated. The expected value range for image tensor is [0,1] when passing as pytorch tensor or numpy Array. You passed `image` with value range [-1.0,1.0]
```

I've updated the workflow 2 ways. 1, modifying the function to return a PIL image
ex:
```
def make_inpaint_condition(image, image_mask):
    image = np.array(image.convert("RGB")).astype(np.float32) / 255.0
    image_mask = np.array(image_mask.convert("L")).astype(np.float32) / 255.0

    assert image.shape[0:2] == image_mask.shape[0:2], "image and image_mask must have the same image size"
    
    image[image_mask > 0.5] = -1.0  # set as masked pixel
    
    # Convert the values back to the range [0, 255]
    image = (image + 1.0) * 127.5
    image = np.clip(image, 0, 255)  # Clip values to the valid range
    
    # Convert the float array back to uint8
    image = image.astype(np.uint8)
    
    # Convert the NumPy array back to a PIL Image
    pil_image = Image.fromarray(image)
    
    return pil_image
 ```
I've also just used the controlnet feature for creating a controlnet image:
```
processor_id = 'lineart_anime'
processor = LineartDetector.from_pretrained("lllyasviel/Annotators")
control_image = processor(image, False)
```

The latter works great with the img2img controlnet pipeline. However with this pipeline the image quality is completely poor with both alternate approaches. I've tried passing along a tensor object to no avail as well. 

### Reproduction

see above

### System Info

 cuda: "11.6"
  system_packages:
    - "ffmpeg" 
    - "libsm6" 
    - "libxext6" 
  python_version: "3.10"
  python_packages:
    - "diffusers==0.17.1"
    - "torch==2.0.1"
    - "torchvision==0.15.2"
    - "ftfy==6.1.1"
    - "scipy==1.10.1"
    - "transformers==4.29.2"
    - "accelerate==0.19.0"
    - "safetensors==0.3.1"
    - "wget==3.2"
    - "onnxruntime-gpu==1.15.0"
    - "controlnet-aux==0.0.5"
    - "mediapipe==0.10.0"
    - "pyparsing==3.0.9"
    - "compel==1.2.1"
    - "pynvml==11.5.0"
    - "xformers==0.0.20"
    - "rembg==2.0.47"

### Who can help?

@patrickvonplaten @sayakpaul

**Comment by djj0s3** [comment]
Following up. Any time I address this error 
```Passing 'image' as torch tensor with value range in [-1,1] is deprecated. The expected value range for image tensor is [0,1] when passing as pytorch tensor or numpy Array.``` 
say change this line 
`image[image_mask > 0.5] = -1.0  # set as masked pixel` 
to 
`image[image_mask > 0.5] = 0.0  # set as masked pixel within [0, 1] range` 

the error is fixed. But passing that image to the Pipeline completely changes the results. Attaching 2 images below as a comparison. The first image is with the error thrown, using -1 to set the masked pixel as instructed in the pipeline instructions. the second image is addressing the error which yields a very not good image. 

![beforeFix](https://github.com/huggingface/diffusers/assets/1120027/a66167ab-a06e-4f2f-9dee-8515e8803cd5)
![afterFix](https://github.com/huggingface/diffusers/assets/1120027/0a60ae6f-7a97-42e3-bb1e-fa13ba4323b0)

**Comment by patrickvonplaten** [comment]
Hey @djj0s3,

Note that this is not an error but just a deprecation warning which is actually wrong. Here we can probably just ignore the warning as the image has to be -1 for controlnet inpainting. So => I'd recommend just ignoring the warning here

**Comment by djj0s3** [comment]
Gotcha. Thanks! Is that also the reason I get unexpected results in the pipeline when I pass a PIL image instead? Should that also be formatted in the -1,1 range before passing it through?

**Comment by patrickvonplaten** [comment]
I would need a reproducible code snippet here

**Comment by djj0s3** [comment]
Snippet available in the code example here: https://github.com/huggingface/diffusers/blob/41ea88f38c8508e3d6cd33929ef666a5ea905715/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py#L48

**Comment by djj0s3** [comment]
I think we're good.  Ignoring that deprecation warning is fine, and I got it all working (but I do not remember which fix did it, sorry!).
