### ISSUE TITLE
I am using train_ Instrument_ Error training model for imagefolder in pix2pix

### ISSUE THREAD

**Issue by zhenzi0322** [huggingface/diffusers#3878]
### Describe the bug

Traceback (most recent call last):
  File "D:\packages\python\Envs\my-diffusers-J71KlA6V\lib\site-packages\datasets\builder.py", line 1629, in _prepare_split_single
    for key, record in generator:
  File "D:\packages\python\Envs\my-diffusers-J71KlA6V\lib\site-packages\datasets\packaged_modules\folder_based_builder\folder_based_builder.py", line 311, in _generate_examples
    raise ValueError(
ValueError: image at demo/19971.jpg doesn't have metadata in D:\demo11\metadata.jsonl.

### Reproduction

datas/instructpix2pix/metadata.jsonl
```
{"file_name": "inputs/19971.jpg","edit_prompt": "Make it thinner", "edited_image": "demo/19971.jpg"}
```

```python
import os
from datasets import load_dataset


def main():
    train_data_dir = "datas/instructpix2pix"
    data_files = {}
    if train_data_dir is not None:
        data_files["train"] = os.path.join(train_data_dir, "**")
    dataset = load_dataset(
        "imagefolder",
        data_files=data_files,
    )
    print(dataset["train"].column_names)


if __name__ == '__main__':
    main()
```

### System Info

Traceback (most recent call last):
  File "D:\packages\python\Envs\my-diffusers-J71KlA6V\lib\site-packages\datasets\builder.py", line 1629, in _prepare_split_single
    for key, record in generator:
  File "D:\packages\python\Envs\my-diffusers-J71KlA6V\lib\site-packages\datasets\packaged_modules\folder_based_builder\folder_based_builder.py", line 311, in _generate_examples
    raise ValueError(
ValueError: image at demo/19971.jpg doesn't have metadata in D:\demo11\metadata.jsonl.

**Comment by sayakpaul** [comment]
@lhoestq do you have any suggestions for @zhenzi0322?

**Comment by zhenzi0322** [comment]
I don't know what caused the problem, but there should be no problem with the data format. It's just that the dataset in the local folder cannot be loaded

**Comment by lhoestq** [comment]
In metadata.jsonl you define "file_name:": "inputs/19971.jpg" whereas the path to the image is "demo/19971.jpg" - can you try moving your file or fixing your metadata.jsonl ?

**Comment by zhenzi0322** [comment]
I currently need this project and I need to load a custom dataset locally

**Comment by sayakpaul** [comment]
Hi @zhenzi0322!

Since the feature itself is not supported yet, I'd suggest writing the dataloader using torch (using Dataset and DataLoader classes), maybe? 

@lhoestq would you by chance have any suggestions on how @zhenzi0322 could this with `datasets` using the native utilities provided by the library?

**Comment by zhenzi0322** [comment]
I don't know how to write it. I want to load it directly using datasets

**Comment by sayakpaul** [comment]
Maybe this could help? 

https://pytorch.org/tutorials/beginner/basics/data_tutorial.html

**Comment by zhenzi0322** [comment]
No help, I don't know how to load it into diffusers either

**Comment by lhoestq** [comment]
> @lhoestq would you by chance have any suggestions on how @zhenzi0322 could this with datasets using the native utilities provided by the library?

Maybe using something like

```python
from datasets import Dataset, Image, Features, Value

def generate()
    for line in open("datas/instructpix2pix/metadata.jsonl"):
        example = json.loads(line)
        example["image"] = example.pop("file_name")
        yield example

features = Features({"image": Image(), "edited_image": Image(), "edit_prompt": Value("string")})
ds = Dataset.from_generator(generate, features=features)
```
