### ISSUE TITLE
How to use models like chilloutmix to do inpainting task?

### ISSUE THREAD

**Issue by AdamMayor2018** [huggingface/diffusers#3882]
I tried as https://huggingface.co/docs/diffusers/api/diffusion_pipeline mentioned:
`text2img = StableDiffusionPipeline.from_pretrained("/data/cx/ysp/aigc-smart-painter/models/chilloutmix_NiPrunedFp32Fix")
inpaint = StableDiffusionInpaintPipeline(**text2img.components)
seger = RawSeger()
REST_API_URL = 'http://localhost:9900/sd/inpaint'
painter = GridPainter()
img_path = "/data/cx/ysp/aigc-smart-painter/assets/cloth1.jpg"
image = Image.open(img_path)
box = [220, 20, 500, 320]
new_image = draw_box(np.array(image), cords=box, color=(255, 0, 0), thickness=2)
show_image(new_image)
mask = seger.prompt_with_box(image, box=box, reverse=False)
mask = Image.fromarray(mask)
show_image(mask)
end = time.time()
prompt = "best quality,symmetry realistic,real life,photography,masterpiece,8K,HDR,highres,1 gril, looking at viewer"
images = inpaint(prompt=prompt, image=image, mask_image=mask, num_images_per_prompt=1,
         num_inference_steps=50, guidance_scale=7.5,)

painter.image_grid(images, rows=1, cols=len(images) // 1)
painter.image_show()
print("finished")`

I got this error:
expects 4 but received `num_channels_latents`: 4 + `num_channels_mask`: 1 + 
`num_channels_masked_image`: 4 = 9. Please verify the config of `pipeline.unet` 
or your `mask_image` or `image` input.

Process finished with exit code 1

How can I convert model like chilloutmix to do inpainting task?
Thank you !

**Comment by patrickvonplaten** [comment]
Hey @AdamMayor2018 ,

This should work on the newest `diffusers` version. Which version are you using?

**Comment by AdamMayor2018** [comment]
@patrickvonplaten   
I'm using 0.16.1 at the moment.  should I upgrade to 0.17? and what extra changes should I notice?
Thanks!

**Comment by AdamMayor2018** [comment]
@patrickvonplaten 
I tried 0.17 with chilloutmix, it works perfect.
Besides, I know when doing inpanting task on stable-diffusion-webui, there is a choice to select whether to inpaint masked region or the whole picture, I wonder whether this can be controlled with diffusers? If so, could u give me some suggestions.
Thanks!
