### ISSUE TITLE
Cannot use realistic vision in dreambooth

### ISSUE THREAD

**Issue by borismartirosyandenovo** [huggingface/diffusers#3883]
Is there any way to use realistic vision model with safetensors extension in diffusers library to train a dreambooth on it? I have tried almost everything but couln't find appropriate solution

**Comment by patrickvonplaten** [comment]
Can you link the realistic vision model here? I'm not sure to which checkpoint you are referring to

**Comment by borismartirosyandenovo** [comment]
1. I have tried this (downloaded .safetensors file from civit.ai)
https://civitai.com/models/4201/realistic-vision-v13
2. also tried those huggingface repos:
     SG161222/Realistic_Vision_V2.0
     SG161222/Realistic_Vision_V1.4
     danbrown/RealisticVision-v2-0

**Comment by patrickvonplaten** [comment]
@borismartirosyandenovo, you need to first load them into `diffusers` format and then you can run dreambooth on it:

```py
from diffusers import DiffusionPipeline

# download https://civitai.com/models/4201/realistic-vision-v13 and save to <path>
pipe = DiffusionPipeline.from_ckpt("<path>")

pipe.save_pretrained("<path/to/diffusers>")
```

Now you can train from `<path/to/diffusers>`
