### ISSUE TITLE
are there any ways to reduce the vram usage of train_text_to_image.py?

### ISSUE THREAD

**Issue by zhangvia** [huggingface/diffusers#3885]
### Describe the bug

at present, the script almost run out of my gpu vram.i got a 4090. i set the bs=1,resolution 512,i enable the xformers.the training procedure used 23g vram with torch2.1, 22g vram with torch1.13.1.
and when i want to use the dynamo of torch2.1 to reduce vram usage, some weird things happened.

using the same script, sometimes the dynamo will reduce the vram usage, sometimes it didn't. yesterday i can use the dynamo to reduce the vram usage from 23g to 13g with bs=1,resolution=512,xformers.but today,same script,same machine, it used 23g vram....
and i notice that the dynamo compile info were different from yesterday,but i don't know why,and i can't reproduce the 13g training.

now i start with a new environment use miniconda. everything is the newest version, the dynamo never reduce the vram usage. i want to know can dynamo reduce the vram usage?and are there any other ways to reduce the vram usage and increase the batchsize without effect the training result?i do know the gradient_accumulation,but that will slower the training procedure greatly

### Reproduction

i didn't change anything about the code,just use the main repo of diffusers. my environment like this:
```python
- `Accelerate` version: 0.20.3
- Python version: 3.10.11
- Numpy version: 1.25.0
- PyTorch version (GPU?): 2.1.0.dev20230523+cu117(True)
- transfomers version: 4.30.2
- xformers version: 0.0.21+9d3d92c.d20230628(install from source)
- `Accelerate` default config:
       compute_environment: LOCAL_MACHINE
       distributed_type: 'NO'
       downcast_bf16: 'no'
       dynamo_config: {
         dynamo_backend: INDUCTOR
       }
       gpu_ids: '0'
       machine_rank: 0
       main_training_function: main
       mixed_precision: fp16
       num_machines: 1
       num_processes: 1
       rdzv_backend: static
       same_network: true
       tpu_env: []
       tpu_use_cluster: false
       tpu_use_sudo: false
       use_cpu: false
```

the command like this:
```python
export NCCL_P2P_DISABLE=1
export NCCL_DEBUG=INFO
export MODEL_NAME="/media/74nvme/checkpoints/diffusers_models/stable-diffusionv2-1/"
export dataset_name="/media/74nvme/data/sd_data_pokemon/"

accelerate launch  train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$dataset_name \
  --resolution=512 \
  --center_crop \
  --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --max_train_steps=15000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --scale_lr \
  --mixed_precision=fp16 \
  --enable_xformers_memory_efficient_attention \
  --output_dir="./sd-pokemon-model"
```

### System Info

- `diffusers` version: 0.18.0.dev0
- Platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.31
- Python version: 3.10.11
- PyTorch version (GPU?): 2.1.0.dev20230523+cu117 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: 0.0.21+9d3d92c.d20230628
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@sayakpaul @williamberman @patrickvonplaten can anyone help?

**Comment by zhangvia** [comment]
now my test result is :
with the conda environment above :
|model|resolution|batchsize|dynamo|vram|
|----|----|----|----|----|
|sdv1-5| 512|1|w|22g vram|
|sdv1-5| 512|1|o|22g vram|
|sdv1-5| 256|1|w|22g vram|
|sdv1-5| 256|1|o|22g vram|
|sdv2-1|512|1|w|23g vram|
|sdv2-1|512|1|o|23g vram|
|sdv2-1|256|1|w|22g vram|
|sdv2-1|256|1|o|22g vram|

it looks like the torch compile can't reduce the vram usage.but sometimes i do reduce the vram by using dynamo.can anyone give me a definite answer that if the dynamo can reduce vram usage or it only can speedup the training?

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
Hi there. Here are a couple of ways:

* Precompute the text embeddings so that for every training step, you don't end up computing the same thing. 
* Precompute the image encodings from the VAE in a similar spirit as above. 

Hope that helps :)

**Comment by zhangvia** [comment]
> Hi there. Here are a couple of ways:
> 
> * Precompute the text embeddings so that for every training step, you don't end up computing the same thing.
> * Precompute the image encodings from the VAE in a similar spirit as above.
> 
> Hope that helps :)

so,the dynamo can't help to reduce the vram usage? it just can speed up the training a little bit?

**Comment by sayakpaul** [comment]
I will have to defer that to @pcuenca as I am not that equipped with dynamo just yet :)

**Comment by simonnxren** [comment]
anybody has any ideas on this? is this just the problem with torch2? everything works fine for torch1.12.

**Comment by patrickvonplaten** [comment]
Torch dynamo does not help with VRAM optimization, it's just faster. It actually tends to require more memory. Can you run text to image with < 24 GB VRAM on your setup as described here: https://github.com/huggingface/diffusers/tree/main/examples/text_to_image#hardware?

**Comment by zhangvia** [comment]
yes,the torch dynamo can't help with vram optimization. i test it on 4090.it turns out that torch dynamo will use 22g or 23g with xformers.if i disable the xformers, there will be oom error. and i try the deepspeed, it can offload the params to cpu,but it will slow down the train procedure. now i'm using the colossalai based on diffusers repo train script, it can let me set the batchsize to 16 on 4090,and won't slow down the train procedure.may be you guys can give it a shot.
