### ISSUE TITLE
diffusers sd pipeline   large difference in effect

### ISSUE THREAD

**Issue by dushwe** [huggingface/diffusers#3887]
### Describe the bug

shape affects the semantic information of the generated image

### Reproduction

    from lpw_stable_diffusion import StableDiffusionLongPromptWeightingPipeline
    pipe = StableDiffusionLongPromptWeightingPipeline.from_pretrained(
            model_id,
            # torch_dtype=torch.float16,
            provider="CPUExecutionProvider",
             safety_checker=None,
        ).to(device)

### System Info

diffusers== 0.16.1
python==3.8.13
torch==1.12.1+cu113

### Who can help?

shape: 512 * 512 

![tmpi8vk10fy](https://github.com/huggingface/diffusers/assets/19389452/95881221-a219-4eba-a03d-c1126211d56a)

shape: 576 * 768 
![tmp2512pkxc](https://github.com/huggingface/diffusers/assets/19389452/fba13457-5619-467a-b3eb-a999ed9ba44a)

shape: 768 * 512 
![tmphtsfc0o9](https://github.com/huggingface/diffusers/assets/19389452/200086f3-7a77-4d07-a3e1-500ad9277e63)

  
    from lpw_stable_diffusion import StableDiffusionLongPromptWeightingPipeline
    pipe = StableDiffusionLongPromptWeightingPipeline.from_pretrained(
            model_id,
            # torch_dtype=torch.float16,
            provider="CPUExecutionProvider",
             safety_checker=None,
    
        ).to(device)

How to align this effect  ？

**Comment by patrickvonplaten** [comment]
This is a know problem because the model was trained on 512x512 - I don't think there is much we can do sadle
