### ISSUE TITLE
Code in readme seems to be broken

### ISSUE THREAD

**Issue by AndreyRub** [huggingface/diffusers#389]
### Describe the bug

Several sample code units provided in README.md are broken:

**1. Example of image generation**
This line does not work:
`image = pipe(prompt).images[0]`
Instead I used:
`image = pipe(prompt)["sample"][0] ` after reading the [blog](https://huggingface.co/blog/stable_diffusion)

**2.  Example of image generation from initial image:**
`from diffusers import StableDiffusionImg2ImgPipeline` does not work

### Reproduction

```
# make sure you're logged in with `huggingface-cli login`
from torch import autocast
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", use_auth_token=True)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
with autocast("cuda"):
    image = pipe(prompt).images[0]
```

```
from torch import autocast
import requests
import torch
from PIL import Image
from io import BytesIO

from diffusers import StableDiffusionImg2ImgPipeline
```

### System Info
Installed using `pip install diffusers`
Python=3.8.5
diffusers==0.2.4
Linux Ubuntu

**Comment by patrickvonplaten** [comment]
Hey @AndreyRub,

Thanks for the message. Colud you try doing:

```
pip uninstall diffusers
pip install git+https://github.com/huggingface/diffusers.git
```

? We'll do a release tomorrow - but until then you need to use master for this :-) 
The `0.2.4` version doesn't have this API yet ;-)

**Comment by AndreyRub** [comment]
Thank you, that works. 
Maybe need to keep the `master` branch as previous release? Or maybe a branch per release?

**Comment by patrickvonplaten** [comment]
Now it should also work with:

```
pip install --upgrade diffusers
```

which should give you `0.3.0` :-)
