### ISSUE TITLE
How to apply the schedulers in diffusers to original SD

### ISSUE THREAD

**Issue by DummyNodeHead** [huggingface/diffusers#3890]
Hi! Thanks for this great work! Diffusers helps me a lot in many aspects!

Because of my recent work, I would like to know wether the schedulers in diffusers can be directly used in original SD? If yes, what should I do? 

Any response will be greatly appreciated! Again, thank you all for this convenient framework!

**Comment by patrickvonplaten** [comment]
I don't know how to do this honestly. Maybe opening an issue on the original repo could make sense?
