### ISSUE TITLE
Run the safety checker as a standalone module

### ISSUE THREAD

**Issue by thjan** [huggingface/diffusers#3892]
I've been trying for some time to get the safety checker to run outside of the DiffusionPipeline but can´t seem to get it running. 
After a lot of messing around with the loading, it seems something happens to the `vision_model` when initialized through `DiffusionPipeline.from_pretrained` which I'm missing. 
 Here is a minimal example of what I'm trying to achieve: 
 ```
pipe = DiffusionPipeline.from_pretrained(model_path, requires_safety_checker=True, prediction_type='epsilon', image_size=768, upcast_attention=True)
pipe.enable_xformers_memory_efficient_attention()
pipe = pipe.to(device, torch_dtype=torch.float16)

#Initialize the safety checker as a standalone
safety_checker_cfg = CLIPConfig.from_json_file(f'{model_path}/safety_checker/config.json')
safety_checker_standalone = StableDiffusionSafetyChecker(safety_checker_cfg)

#Equivalent of enable_xformers_memory_efficient_attention
for module in safety_checker_standalone.modules():
    if hasattr(module, "set_use_memory_efficient_attention_xformers"):
        module.set_use_memory_efficient_attention_xformers(True, None)
safety_checker_standalone.to(device, dtype=torch.float16)


image = np.asarray(Image.open('./src/models/safety_checker/naked.png'))

# Run safety checker from Diffusion pipeline
(_, nsfw) = pipe.run_safety_checker(image=image, device=device, dtype=torch.float16)

# Run standalone safety checker with same inputs
safety_checker_input = pipe.feature_extractor(image, return_tensors="pt").to(device)
(_, nsfw_standalone) = safety_checker_standalone(images=image, clip_input=safety_checker_input.pixel_values.to(torch.float16))

print(nsfw)
print(nsfw_standalone)
 ```
This returns: 
```
[True]
[False]
```
I feel like I'm missing something obvious in the way the model is initialized. Both the DiffusionPipeline and `safety_checker_standalone` are initialized from the same `config.json` which is located next to the `bin` file with the weights. My weights are extracted from a `ckpt` file obtained through fine tuning with dreambooth, although they are IMO not suspicious since the DiffusionPipeline loads the same files as the standalone safety checker (at least I printed the config at initialization and confirmed they are the same). 
 Is there some optimization/modification applied to the vision model during the loading ? 
  
 By digging into the code of the safety checker, I noticed that the result tensors start to diverge after this line: 
`pooled_output = self.vision_model(clip_input)[1]  # pooled_output` located in `safety_checker.py:52` 

I am using diffusers `0.16.1` obtained through a pip install  with python 3.9.

Thank you

**Comment by patrickvonplaten** [comment]
Hey @thjan,

The following should work:

```py
import PIL
from transformers import CLIPImageProcessor
from diffusers.pipelines.stable_diffusion import StableDiffusionSafetyChecker

feature_extractor = CLIPImageProcessor.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="feature_extractor")
safety_checker = StableDiffusionSafetyChecker.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="safety_checker")
device = "cpu"

image = PIL.Image.open("/home/patrick/images/0.png")

safety_checker_input = feature_extractor(image, return_tensors="pt").to(device)
image, has_nsfw_concept = safety_checker(images=image, clip_input=safety_checker_input.pixel_values)
```
