### ISSUE TITLE
convert checkpoints of inP2P to diffuser type 

### ISSUE THREAD

**Issue by hey0chen** [huggingface/diffusers#3898]
MagicBrush released their dataset and checkpoints of instructPix2Pix rencently,but the checkpoints doesn't match diffuser, can someone provide solution?

**Comment by hey0chen** [comment]
Can someone solve this problem? @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @hey0chen,

Could you please link to MagicBrush or the other checkpoints you had in mind?

**Comment by hey0chen** [comment]
> Hey @hey0chen,
> 
> Could you please link to MagicBrush or the other checkpoints you had in mind?

Thanks for your reply! I have tried to convert MagicBursh’s checkpoints, but it didn’t work well,maybe you can do it ?
MagicBursh : https://github.com/OSU-NLP-Group/MagicBrush, it’s really a great work,but it would be a pity if diffusers can’t work
