### ISSUE TITLE
control-a-video

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#3902]
### Model/Pipeline/Scheduler description

https://github.com/Weifeng-Chen/control-a-video

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by jfischoff** [comment]
Excited about controlnet3d which looks like it could be used with the TextToVideoSDPipeline (so zeroscope)

**Comment by patrickvonplaten** [comment]
Feel free to open a PR @chiral-carbon :-)

**Comment by chiral-carbon** [comment]
hey @patrickvonplaten, would you have any recommendation on what to refer for integrating new models/pipelines? would appreciate any pointers!

**Comment by patrickvonplaten** [comment]
Sure, see: https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md

**Comment by a-r-r-o-w** [comment]
Marking as closed due to superior models supported now!
