### ISSUE TITLE
invalid pipeline tests `test_float16_inference`

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#3906]
### Describe the bug

I think this test is invalid 

The same `components` objects are attached to both `pipe` and `pipe_fp16`  - when we do `pipe_fp16.to(torch.float16)`, we change all the weights in `components` to `fp16` for both `pipe` and `pipe_fp16`

Am I right? I verified this by adding some lines to print out dtype when running a test; but happy to provide some sort of reproducible scripts if it isn't clear.  I think it will be easy to fix too but may cause more tests failing so would rather fix it in a separate PR 

Let me know 

https://github.com/huggingface/diffusers/blob/174dcd697faf88370f1e7b2eeabb059dd8f1b2f4/tests/pipelines/test_pipelines_common.py#L469

```python
    def test_float16_inference(self, expected_max_diff=1e-2):
        components = self.get_dummy_components()
        pipe = self.pipeline_class(**components)
        pipe.to(torch_device)
        pipe.set_progress_bar_config(disable=None)

        pipe_fp16 = self.pipeline_class(**components)
        pipe_fp16.to(torch_device, torch.float16)
        pipe_fp16.set_progress_bar_config(disable=None)

        output = pipe(**self.get_dummy_inputs(torch_device))[0]
        output_fp16 = pipe_fp16(**self.get_dummy_inputs(torch_device))[0]

        max_diff = np.abs(to_np(output) - to_np(output_fp16)).max()
        self.assertLess(max_diff, expected_max_diff, "The outputs of the fp16 and fp32 pipelines are too different.")

```

### Reproduction

N/A

### System Info

diffusers` version: 0.18.0.dev0

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
@yiyixuxu would definitely be helpful to have a reproducible script for this for us to understand this better. 

Also, I edited the issue description to tag Patrick.

**Comment by patrickvonplaten** [comment]
Hey @yiyixuxu,

Good catch, we are indeed missing a:
```py
components = self.get_dummy_components()
```
here in the test to make sure the components are different. Could you fix the tests ?
