### ISSUE TITLE
how to fine-tuning the sd model in low resolutions

### ISSUE THREAD

**Issue by XiaoyuZhuang** [huggingface/diffusers#3914]
When fine-tuning the stable diffusion model, there is a parameter called 'resolution' which, if set to a value like 128 or 256 to reduce GPU memory usage, could potentially have negative effects on training performance and results.

Would setting the resolution to a value other than 512, such as 128 or 256, have any adverse impact on training effectiveness and the final results?

Is there a way to modify the pre-trained model's resolution to 128 or 256, or do I need to train a separate low-resolution version of the model?

I have experimented with different resolutions, and it seems that setting the resolution to 512 produces the best results. Training with lower resolutions tends to generate complex and messy outputs.

I couldn't find any similar issues on GitHub, as most discussions focus on super-resolution. Thank you for your response!

**Comment by patrickvonplaten** [comment]
This has been a problem for SD 1.+ and SD 2.+ but has been nicely solved in SD-XL see technical report here: https://github.com/Stability-AI/generative-models/blob/main/assets/sdxl_report.pdf -> see section 2.2
