### ISSUE TITLE
Zero convolution?

### ISSUE THREAD

**Issue by okaris** [huggingface/diffusers#3917]
Hi, I was comparing the diffusers implementation of stable diffusion vs stability's implementation. I noticed that stability uses zero convolution for the transformer out projection whereas diffusers do not. Can anyone help me understand why please?

Diffusers:
https://github.com/huggingface/diffusers/blame/da2ce1a6b92f48cabe9e9d3944c4ee8b007b2871/src/diffusers/models/transformer_2d.py#L205

Stability:
https://github.com/Stability-AI/stablediffusion/blob/cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf/ldm/modules/attention.py#L312C34-L312C34

**Comment by lijuncheng16** [comment]
> ``Since the zero convolution does not add new noise to deep features, the training is as fast as fine tuning a diffusion model, compared to training new layers from scratch.``
Section 3.1 of the controlnet paper contains the answer to your question: https://arxiv.org/pdf/2302.05543.pdf.
It's not guaranteed zero modules are better, and both are okay.

**Comment by okaris** [comment]
Thank you for the reference. I was wondering was that the reason behind this decision when porting to diffusers.

**Comment by xiankgx** [comment]
Are you training ControlNet models? If not, then there is probably little difference. These are just different weights initialization.
