### ISSUE TITLE
How to control the position of an object in an image using text in a txt2img model?

### ISSUE THREAD

**Issue by XiaoyuZhuang** [huggingface/diffusers#3918]
How to control the position of an object in an image using text in a txt2img model? I know this is easy to achieve in an img2img model, but how can it be done in a txt2img model?

Or, how can a model be fine-tuned to achieve this effect? For example, specifying x=0, y=1, which corresponds to the top-left corner.

I have tried similar approaches, but they are not sensitive to the position. I suspect it may be due to insensitivity to the text input. I tried using compel to enhance the positional features, but still couldn't control the position. Do I need to retrain the text_encoder related part for this?

In my fine-tuning code, I commented out the no_grad parts for text_encoder and others. Is this correct, and will it automatically train the text_encoder?

Thank you!

**Comment by patrickvonplaten** [comment]
@XiaoyuZhuang could you maybe try asking on the forum: https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63 or on discord: https://discord.gg/G7tWnz98XR ? We try to keep GitHub clean for bug issues

**Comment by patrickvonplaten** [comment]
But to answer here quickly - this is something that SD-XL seems to have solved quite well with micro-controlling. See section 2.2 of  https://github.com/Stability-AI/generative-models/blob/main/assets/sdxl_report.pdf
