### ISSUE TITLE
convert_ldm_clip_checkpoint() got an unexpected keyword argument 'local_files_only'

### ISSUE THREAD

**Issue by Thymustw** [huggingface/diffusers#3919]
I'm got this error while using [convert_from_ckpt.py]

D:\ai\HCP-Diffusion>python -m hcpdiff.tools.sd2diffusers --checkpoint_path="C:\Users\nmsl\Downloads\v1-5-pruned.ckpt" --original_config_file="C:\Users\nmsl\Downloads\v1-inference.yaml" --dump_path="D:\ai\HCP-Diffusion\model" --to_safetensors
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.9)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\nmsl\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main    │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\nmsl\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code               │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ D:\ai\HCP-Diffusion\hcpdiff\tools\sd2diffusers.py:335 in <module>                                │
│                                                                                                  │
│   332 │   args = parser.parse_args()                                                             │
│   333 │                                                                                          │
│   334 │   if args.vae_pt_path is None:                                                           │
│ ❱ 335 │   │   convert_ckpt(args)                                                                 │
│   336 │   else:                                                                                  │
│   337 │   │   sd_vae_to_diffuser(args)                                                           │
│   338 │   # python -m hcpdiff.tools.sd2diffusers --checkpoint_path test/control_sd15_canny.pth   │
│                                                                                                  │
│ D:\ai\HCP-Diffusion\hcpdiff\tools\sd2diffusers.py:177 in convert_ckpt                            │
│                                                                                                  │
│   174 │   vae.save_pretrained(args.dump_path)                                                    │
│   175                                                                                            │
│   176 def convert_ckpt(args):                                                                    │
│ ❱ 177 │   pipe = load_sd_ckpt(                                                                   │
│   178 │   │   checkpoint_path=args.checkpoint_path,                                              │
│   179 │   │   original_config_file=args.original_config_file,                                    │
│   180 │   │   image_size=args.image_size,                                                        │
│                                                                                                  │
│ C:\Users\nmsl\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\stab │
│ le_diffusion\convert_from_ckpt.py:1328 in download_from_original_stable_diffusion_ckpt           │
│                                                                                                  │
│   1325 │   │   │   feature_extractor=feature_extractor,                                          │
│   1326 │   │   )                                                                                 │
│   1327 │   elif model_type == "FrozenCLIPEmbedder":                                              │
│ ❱ 1328 │   │   text_model = convert_ldm_clip_checkpoint(checkpoint, local_files_only=local_file  │
│   1329 │   │   tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14")        │
│   1330 │   │                                                                                     │
│   1331 │   │   if load_safety_checker:                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: convert_ldm_clip_checkpoint() got an unexpected keyword argument 'local_files_only'

here is the hole error, the sd-model and yaml is download from [https://huggingface.co/runwayml/stable-diffusion-v1-5]

is someone have this problems or how to fix it, thanks.

**Comment by patrickvonplaten** [comment]
Hey @Thymustw,

Could you please add a reproducible code snippet?
