### ISSUE TITLE
Can Schedule method be different for train and inference?

### ISSUE THREAD

**Issue by mzeynali** [huggingface/diffusers#3920]
Hi guys,
Suppose I trained a Stable Diffusion with DDPM Schedule sampling. Is it possible to use other method Schedule in the inference phase? I want to know, the best practice is that to be same method in both train and inference? Or can be different?

**Comment by patrickvonplaten** [comment]
Hey @mzeynali ,

All the scheduler does during training is to add noise which is more or less the same for all schedulers (DDPM, DDIM, Euler, Heun, ...). So during inference you can use a bunch of different schedulers: https://huggingface.co/docs/diffusers/using-diffusers/schedulers
