### ISSUE TITLE
Docs: Add example for image-to-image-video from a file

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#3926]
**Is your feature request related to a problem? Please describe.**
I'm so happy that you have added image-to-image-video. Thank you!

One small thing. In the current example, it is upscaling a generated video, so maybe an example for styling of an existing video could maybe also be added? 

I mean, show in an example how a video file can be imported as an alternative first step?

**Comment by patrickvonplaten** [comment]
Hey @tin2tin,

I haven't found time to play around with img2img too much yet sadly. Would be keen to know if the community has found some cool use cases

**Comment by tin2tin** [comment]
@patrickvonplaten I added your Zeroscope XL upscale step to the Generative AI add-on for Blender: https://twitter.com/tintwotin/status/1675865908105846785 

What I'm asking is a doc example using a video file/image sequence as input for the upscaling. So, you can render a lot of unscaled files, and then only upscale the good ones.
