### ISSUE TITLE
[Docs] Add docstrings about feed-forward chunking

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#3935]
@patrickvonplaten added support for feed-forward chunking to optimize memory usage for video pipelines. PRs: https://github.com/huggingface/diffusers/pull/3930, https://github.com/huggingface/diffusers/pull/3934. 

Even though `enable_forward_chunking` is included in the docstring, I believe we should also add a little section to the pipeline documentation pages that are affected by it.

**Comment by patrickvonplaten** [comment]
Feel free to open a PR for it @sayakpaul

**Comment by sayakpaul** [comment]
@stevhliu WDYT about this?

**Comment by stevhliu** [comment]
I think that's a good idea! What do you also think about creating a more comprehensive image-to-video guide similar to the ones found in this [section](https://huggingface.co/docs/diffusers/using-diffusers/pipeline_overview)?

**Comment by sayakpaul** [comment]
I like the idea.
