### ISSUE TITLE
huggingface folder in .cache folder in ubuntu and its exact purposes

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#3940]
hi. I want to create a system where the models are in external disks and I suddenly saw that the folder in the cache folder exists and it's something that clearly exists in the disk. What would be the most efficient approach for me?

**Comment by patrickvonplaten** [comment]
What is an external disk?

**Comment by JeLuF** [comment]
You can use the `HF_HOME` environment variable to configure where the cache will be placed. 
https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhome

Alternatively, you could use a symbolic link
https://www.freecodecamp.org/news/symlink-tutorial-in-linux-how-to-create-and-remove-a-symbolic-link/

**Comment by alexblattner** [comment]
@JeLuF thanks, that helps a lot! I would still appreciate knowing the purpose of the contents of the folder

**Comment by JeLuF** [comment]
The folder contains model files that diffusers needs. 
```
pipeline = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
```
This would load the SD 1.5 model from huggingface and place it into that folder. And when you create an image, it would also need to download a LAION model, e.g. from [here](https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K). Very oversimplified, the SD1.5 model tells the AI how to draw, and the LAION model is needed by the AI to understand the prompt.

If you use other pipelines, like for example the latent upscaler, the models used by those would also be placed into that folder.

**Comment by alexblattner** [comment]
@JeLuF isn't there something that can be done to make sure the files in the folders are shared? I use models from civitai sometimes and they seem to have consistent requirements.

again, thank you for your detailed answer

**Comment by JeLuF** [comment]
I'm not sure what you mean. The huggingface libraries only download models when they are not yet in the cache. So they are in a sense "shared" between runs. SD1 and SD2 use different LAION models, so perhpas this is what you encountered. Civitai has both kinds of models. Hard to tell without more details.

**Comment by jrittvo** [comment]
Are these cached base models and CLIP necessary for using other models (merged or trained) that reside on a local drive?

**Comment by alexblattner** [comment]
@JeLuF even local loads were added to my cache though. I don't think that it only does this for non existing ones

**Comment by alexblattner** [comment]
@patrickvonplaten I realized that the term could mean different things. You can attach to a google cloud instance memory that does not belong to the starting instance. I was planning on attaching the external disks on multiple instances so they can immediately use the models (there's going to be quasi infinite amounts)

**Comment by alexblattner** [comment]
this is how you can choose the location of that folder:

```
from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", cache_dir="path/to/cache")
```
