### ISSUE TITLE
`from_ckpt` is a bad name 

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#3946]
### Describe the bug

We've gotten a couple of issues like: https://github.com/huggingface/diffusers/issues/3390 that show that `from_ckpt` is a bad name because people think they cannot load `safetensors` checkpoints with it. To me `ckpt` just stood for "checkpoint" and I didn't realize that people strongly associated `.ckpt` with this method (thinking that any `.safetensors` checkpoint can't be loaded with `from_ckpt`) 

Let's maybe deprecate the method and rename it no? 

### Reproduction

Marking this as a bug since multiple people seem to have this problem.

Let's call the new method maybe:

`from_single_file(...)` or any better ideas fro names cc @sayakpaul @yiyixuxu @pcuenca @williamberman @apolinario ? 

### System Info

Not needed

**Comment by sayakpaul** [comment]
Maybe `from_single_ckpt`? Checkpoint, to me at least, could mean a single checkpoint file or shards of checkpoints. If we make it abundantly clear from the documentation, will that help?

**Comment by JeLuF** [comment]
`from_single_ckpt` would still be strongly associated with `ckpt`. In order to prevent confusion, it's porbably best to avoid `ckpt`, or to be very verbose: `from_ckpt_or_safetensors`

**Comment by bghira** [comment]
why not just `from_local_file` ?

**Comment by sanbuphy** [comment]
from_local_file +1

**Comment by williamberman** [comment]
hm interesting, tbh I think  something with "local file" is more confusing because it implies something like "this should be used for loading anything locally and doesn't infer anything about the format". Is there an alternative naming convention people use for the .ckpt files that we could put in the name? Something like `from_non_diffusers_ckpt` or `from_ldm_ckpt`? I'm pretty open to whatever here

**Comment by bghira** [comment]
that's a good point. why can't `from_pretrained` simply be extended to use `from_ckpt` as if it were an internal method that we don't tell users to rely on?

I remember that being one of the first things I tried was to load a .safetensors or .ckpt file (both were available, and I had no idea what I was doing) via `from_pretrained('/path/to/file.safetensors')` and programmatically speaking there's no real technical issue preventing that from happening automatically.

**Comment by sanbuphy** [comment]
> that's a good point. why can't `from_pretrained` simply be extended to use `from_ckpt` as if it were an internal method that we don't tell users to rely on?
> 
> I remember that being one of the first things I tried was to load a .safetensors or .ckpt file (both were available, and I had no idea what I was doing) via `from_pretrained('/path/to/file.safetensors')` and programmatically speaking there's no real technical issue preventing that from happening automatically.

I agree with you. The first time I attempted to load the safetensors, I simply used the from_pretrained function.

**Comment by patrickvonplaten** [comment]
Solved with https://github.com/huggingface/diffusers/pull/3968

**Comment by patrickvonplaten** [comment]
There is nothing forbidden about dispatching `from_single_files(...)` from `from_pretrained(...)`, we can still do this in a future PR. This however requires a lot more work since `from_pretrained(...)` is the core of all pipelines here. An easier first improvement is to rename `from_ckpt` here.

Feel free to open a new issue about it @MLator and we'll try to tackle it (or give it a try yourself if you'd like to show us newbies how it's done haha)
