### ISSUE TITLE
Generated images are pale

### ISSUE THREAD

**Issue by bohdanWsib** [huggingface/diffusers#3948]
### Describe the bug

I'm experimenting with prompted image editing. I use this [implementation](https://github.com/huggingface/diffusers/tree/main/examples/community#edict-image-editing-pipeline) using diffusers lib EDICT pipeline. Everything works pretty fine but I receive "pale" images. I do it using google colab with free gpu. Please help me

I get this:
![result_image](https://github.com/huggingface/diffusers/assets/133372767/c90ab129-f53c-4ea7-a08c-d611a07e39a3)

I want this:
![68747470733a2f2f68756767696e67666163652e636f2f64617461736574732f4a6f7173616e2f696d616765732f7265736f6c76652f6d61696e2f696d6167656e65745f646f675f315f63726f707065645f67656e6572617465642e706e67](https://github.com/huggingface/diffusers/assets/133372767/b0d8dfd7-3f2c-4ce2-8c2d-d9e209c1b065)

### Reproduction

```
from diffusers import DiffusionPipeline, DDIMScheduler
from transformers import CLIPTextModel
import torch, PIL, requests
from io import BytesIO
from IPython.display import display

def center_crop_and_resize(im):

    width, height = im.size
    d = min(width, height)
    left = (width - d) / 2
    upper = (height - d) / 2
    right = (width + d) / 2
    lower = (height + d) / 2

    return im.crop((left, upper, right, lower)).resize((512, 512))

torch_dtype = torch.float16
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# scheduler and text_encoder param values as in the paper
scheduler = DDIMScheduler(
        num_train_timesteps=1000,
        beta_start=0.00085,
        beta_end=0.012,
        beta_schedule="scaled_linear",
        set_alpha_to_one=False,
        clip_sample=False,
)

text_encoder = CLIPTextModel.from_pretrained(
    pretrained_model_name_or_path="openai/clip-vit-large-patch14",
    torch_dtype=torch_dtype,
)

# initialize pipeline
pipeline = DiffusionPipeline.from_pretrained(
    pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4",
    custom_pipeline="edict_pipeline",
    revision="fp16",
    scheduler=scheduler,
    text_encoder=text_encoder,
    leapfrog_steps=True,
    torch_dtype=torch_dtype,
).to(device)

# download image
image_url = "https://huggingface.co/datasets/Joqsan/images/resolve/main/imagenet_dog_1.jpeg"
response = requests.get(image_url)
image = PIL.Image.open(BytesIO(response.content))

# preprocess it
cropped_image = center_crop_and_resize(image)

# define the prompts
base_prompt = "A dog"
target_prompt = "A golden retriever"

result_images = pipeline(
    base_prompt=base_prompt,
    target_prompt=target_prompt,
    image=cropped_image,
)

# Extract the image from the list
result_image = result_images[0]

# Save the result image
result_image.save("result_image.png")

display(result_image)
```

### System Info

 `diffusers` version: 0.17.1
- Platform: Linux-5.15.107+-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: idk what does it mean :(

### Who can help?

 @patrickvonplaten @sayakpaul  @williamberman @Joqsan

**Comment by sayakpaul** [comment]
Pinging our original contributor for the pipeline @Joqsan.
