### ISSUE TITLE
Demo code for UniDiffuser returns output of NaNs

### ISSUE THREAD

**Issue by ethansmith2000** [huggingface/diffusers#3951]
### Describe the bug

Model is able to go through all steps of diffusion but fails on the self.numpy_to_pil() step where it says it encounters illegal values. upon printing them i see the array is full of NaNs

### Reproduction

<img width="913" alt="Screen Shot 2023-07-05 at 3 07 37 AM" src="https://github.com/huggingface/diffusers/assets/98723285/807630f0-9066-423e-b1f9-cbd7321978bd">

### System Info

- `diffusers` version: 0.17.1
- Platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: 0.0.16
- Using GPU in script?: A100

### Who can help?

@patrickvonplaten

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by dg845** [comment]
I think the issue should be mitigated by using `torch 2.x`. The full UniDiffuser checkpoints seems to have some numerical stability issues on `torch 1.x`, can investigate more if necessary.

**Comment by sayakpaul** [comment]
@ethansmith2000 does upgrading PT 2.0 solve the problem?
