### ISSUE TITLE
HeaderTooLarge : Lora

### ISSUE THREAD

**Issue by satou23** [huggingface/diffusers#3960]
### Describe the bug

it show error while loading lora model which is a safetensors model

here is the lora model
https://civitai.com/api/download/models/31475

### Reproduction

import torch
import requests
from PIL import Image
from diffusers import StableDiffusionImg2ImgPipeline
from diffusers import DPMSolverMultistepScheduler

repo_id = "stablediffusionapi/meinapastel"

dpm = DPMSolverMultistepScheduler.from_pretrained(repo_id, subfolder="scheduler")

pipe = StableDiffusionImg2ImgPipeline.from_pretrained(repo_id, scheduler=dpm, custom_pipeline="lpw_stable_diffusion", safety_checker = None, feature_extractor=None, requires_safety_checker = False)
pipe = pipe.to("cuda")

pipe.load_lora_weights(".", weight_name="/content/gstamp_02-000008.safetensors")

### Error message

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <cell line: 19>:19                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/diffusers/loaders.py:893 in load_lora_weights            │
│                                                                                                  │
│    890 │   │   │   │   │   │   subfolder=subfolder,                                              │
│    891 │   │   │   │   │   │   user_agent=user_agent,                                            │
│    892 │   │   │   │   │   )                                                                     │
│ ❱  893 │   │   │   │   │   state_dict = safetensors.torch.load_file(model_file, device="cpu")    │
│    894 │   │   │   │   except IOError as e:                                                      │
│    895 │   │   │   │   │   if not allow_pickle:                                                  │
│    896 │   │   │   │   │   │   raise e                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/safetensors/torch.py:259 in load_file                    │
│                                                                                                  │
│   256 │   ```                                                                                    │
│   257 │   """                                                                                    │
│   258 │   result = {}                                                                            │
│ ❱ 259 │   with safe_open(filename, framework="pt", device=device) as f:                          │
│   260 │   │   for k in f.keys():                                                                 │
│   261 │   │   │   result[k] = f.get_tensor(k)                                                    │
│   262 │   return result                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
SafetensorError: Error while deserializing header: HeaderTooLarge

### System Info

- `diffusers` version: 0.17.1
- Platform: Linux-5.15.107+-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.2
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
- safetensors installed

**Comment by sayakpaul** [comment]
Hi. 

I am able to successfully load it like so:

```bash
!wget https://civitai.com/api/download/models/31475 -O lora.safetensors
```
```python
import torch
import requests
from PIL import Image
from diffusers import StableDiffusionImg2ImgPipeline
from diffusers import DPMSolverMultistepScheduler

repo_id = "stablediffusionapi/meinapastel"

dpm = DPMSolverMultistepScheduler.from_pretrained(repo_id, subfolder="scheduler")

pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    repo_id, scheduler=dpm, custom_pipeline="lpw_stable_diffusion", safety_checker = None, feature_extractor=None, requires_safety_checker=False)
pipe = pipe.to("cuda")

pipe.load_lora_weights(".", weight_name="lora.safetensors")
```

Could you maybe try again?

**Comment by satou23** [comment]
it works now,thxxxxxxxx

**Comment by sayakpaul** [comment]
Closing it then.
