### ISSUE TITLE
What's the difference between diffusers[training] and diffusers[torch]

### ISSUE THREAD

**Issue by wikiwen** [huggingface/diffusers#3964]
In [readme doc](https://github.com/huggingface/diffusers), `pip install diffusers[torch]`.
In [training doc](https://huggingface.co/docs/diffusers/tutorials/basic_training), `pip install diffusers[training]`.
Why different package is designed? Can these two package be designed to only one.

**Comment by sayakpaul** [comment]
For `training`, we use additional installations such as Jinja2 and Tensorboard and we don't package those in `torch`.
