### ISSUE TITLE
SD-XL not working anymore after you deleted the branch

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/diffusers#3967]
### Describe the bug

No errors but not loading anything into vram

installed requirements are like this

```
--extra-index-url https://download.pytorch.org/whl/cu113
torch==2.0.1
python-dotenv
accelerate
transformers
invisible-watermark
numpy>=1.17
PyWavelets>=1.1.1
opencv-python>=4.1.0.25
safetensors
gradio==3.11.0
git+https://github.com/huggingface/diffusers.git
```

![image](https://github.com/huggingface/diffusers/assets/19240467/21e22161-79b9-4d3e-a8ed-72b6d8abf2a3)

### Reproduction

above

### System Info

@patrickvonplaten

**Comment by FurkanGozukara** [comment]
it is just super super slow i dont get why

**Comment by bghira** [comment]
Colab isn't great for benchmarking. if it's slow, it's likely just Colab's fault.

**Comment by sayakpaul** [comment]
`sd_xl` was merged into `main` yesterday. So, you should be able to use it (given you have access to the weights) by installing from the `main`:` pip install git+https://github.com/huggingface/diffusers`.

For speeding things up, you can also use `torch.compile()`as noted in the doc: https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl.

**Comment by FurkanGozukara** [comment]
> `sd_xl` was merged into `main` yesterday. So, you should be able to use it (given you have access to the weights) by installing from the `main`:` pip install git+https://github.com/huggingface/diffusers`.
> 
> For speeding things up, you can also use `torch.compile()`as noted in the doc: https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl.

when will this feature come to windows?
it says not available on windows comon

**Comment by bghira** [comment]
Pytorch is a different project @FurkanGozukara if you want compile support on Windows, it would need to be implemented by **them.**

your patience would be greatly appreciated, we're all trying our best to make this a good experience and SDXL isn't even generally available yet - in its current form, it is intended for **researchers** to be experimenting with it.

if you do not have adequate hardware available to you, that's not something that the huggingface team can resolve.
