### ISSUE TITLE
TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected  keyword argument 'vae_path'

### ISSUE THREAD

**Issue by hello202320** [huggingface/diffusers#3973]
### Describe the bug

There is a TypeError when using the script  convert_original_stable_diffusion_to_diffusers.py

### Reproduction

!python convert_original_stable_diffusion_to_diffusers.py --from_safetensors --checkpoint_path="/content/Counterfeit-V2.5_pruned.safetensors" --dump_path='/content/model' --device='cuda:0'

### Logs

```shell
2023-07-06 16:52:00.022897: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py │
│ :138 in <module>                                                             │
│                                                                              │
│   135 │   )                                                                  │
│   136 │   args = parser.parse_args()                                         │
│   137 │                                                                      │
│ ❱ 138 │   pipe = download_from_original_stable_diffusion_ckpt(               │
│   139 │   │   checkpoint_path=args.checkpoint_path,                          │
│   140 │   │   original_config_file=args.original_config_file,                │
│   141 │   │   image_size=args.image_size,                                    │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected 
keyword argument 'vae_path'
```

### System Info

- `diffusers` version: 0.18.0
- Platform: Linux-5.15.107+-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.2
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: 0.0.20

**Comment by sayakpaul** [comment]
I don't see any issue in the implementation: 

https://github.com/huggingface/diffusers/blob/1fbcc78d6e55613b902015ff65a1d850594fa859/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L1080

Could you maybe provide a Colab Notebook instance for us to look deeper?

**Comment by patrickvonplaten** [comment]
Hey @hello202320,

I think you need to update your `diffusers` version. Note that 0.18.0 definitely has a `vae_path` kwarg as shown by Sayak above.

**Comment by Akmpfen** [comment]
+1 - I have the same issue

**Comment by CaiNiaoCYY** [comment]
+1 - I have the same issue

**Comment by patrickvonplaten** [comment]
Can you please post a copy-pastable, reproducible, minimal code snippet? :-)

**Comment by AbeEstrada** [comment]
This is the cause: https://github.com/huggingface/diffusers/pull/4817/files

Just revert to `checkpoint_path=args.checkpoint_path` if you're using `diffusers==0.20.1`

**Comment by patrickvonplaten** [comment]
Make sure to use current "main" when converting model checkpoints :pray: - we're not keeping the scripts backwards compatible with previous versions
