### ISSUE TITLE
StableDiffusionImg2Img not working on MPS

### ISSUE THREAD

**Issue by ballenvironment** [huggingface/diffusers#3978]
### Describe the bug

Img2Img pipeline doesn't work. It works perfectly fine on text2img (using the same settings). I get this error:

```
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1, 512] because the unspecified dimension size -1 can be any value and is ambiguous
```

### Reproduction

```py
generator = StableDiffusionImg2ImgPipeline.from_ckpt(model, torch_dtype=torch.float32, local_files_only=True).to("mps")
image = generator(
                image=image,
                strength=denoise,
                prompt_embeds=conditioning,
                negative_prompt_embeds=negative_conditioning,
                num_inference_steps=steps,
                guidance_scale=cfg,
                num_images_per_prompt=1,
                generator=torch.manual_seed(seed)
            ).images[0]
```
image is a PIL Image.

### System Info

MacOS 13.2, M1 Pro MBP

**Comment by sayakpaul** [comment]
Hi.

Which `model` are you using while loading the pipeline? 

Cc: @pcuenca

**Comment by ballenvironment** [comment]
SD 1.5 (it doesn't seem to work for any models I tried). Actually it doesn't work on CPU either, get the same error.

Diffusers: `0.18.0`
Torch: `2.0.1`

**Comment by sayakpaul** [comment]
Could you provide a fully reproducible code snippet for this? Preferably a Colab Notebook?

**Comment by ballenvironment** [comment]
Ok, I figured it out. When calculating the value for denoise I was doing `int(denoise)`, which was truncating the value
down to 0. The fix was to change it to `float(denoise)`.

The error occurs when `strength` is set to 0. I'm not sure if that's a bug, but an easy workaround could be to set it to 0.01 if it's 0.
