### ISSUE TITLE
Timeembedding sin and cos is Error????

### ISSUE THREAD

**Issue by kache1995** [huggingface/diffusers#3981]
I get code from transformers or ddpm, the time embedding is :
``` python
emb = torch.stack([torch.sin(emb), torch.cos(emb)], dim=-1) 
emb = emb.view(T, d_model)#[sin,cos,sin,cos,.....]
```
but diffusers/src/diffusers/models/embeddings.py  get_timestep_embedding is :
``` python
emb = torch.cat([torch.sin(emb), torch.cos(emb)], dim=-1)#[sin,sin,sin,sin,.....sin,cos,cos,cos,....cos]
```
the correct form is [sin,cos,sin,cos,.....]??????

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @kache1995,

Could you please send a link to the code snippets you mention? 
What code line do you refer to with 
> I get code from transformers or ddpm, the time embedding is :

**Comment by kache1995** [comment]
> Hey @kache1995,
> 
> Could you please send a link to the code snippets you mention? What code line do you refer to with
> 
> > I get code from transformers or ddpm, the time embedding is :

1：transformer article 
from transformer article https://arxiv.org/pdf/1706.03762.pdf， the page 6：
![image](https://github.com/huggingface/diffusers/assets/43060760/6f2de276-05e6-4f5d-972f-0aa2470a4a14)
at even positions(2i), use sin. 
at odd positions(2i+1)， use cos.
2：transformer code 
from huggingface's transformer code : https://github.com/huggingface/transformers/blob/495729427045c7a58e040fa9bf6df81c16f54208/examples/research_projects/bertabs/modeling_bertabs.py#L266
we can see that ：
``` python
pe[:, 0::2] = torch.sin()
pe[:, 1::2] = torch.cos()
``` 
but I also find that many people use it ([sin,sin,sin,...sin,cos,cos,cos....cos])，I donot know whether it is a error

**Comment by patrickvonplaten** [comment]
We've made sure that the `diffusers` code is 1-to-1 the same as the original DDPM and Stable Diffusion Code:
- https://github.com/hojonathanho/diffusion
- https://github.com/CompVis/latent-diffusion
