### ISSUE TITLE
ValueError: class_labels should be provided when num_class_embeds > 0

### ISSUE THREAD

**Issue by misi0202** [huggingface/diffusers#3984]
### Describe the bug

class_labels should be provided when num_class_embeds > 0
I found the error when i use unet in forward
![image](https://github.com/huggingface/diffusers/assets/101965629/5e5b68e2-c2d9-4ec1-9c3c-ec7269adddac)

### Reproduction

def forward(self,batch):
        
        images = batch[:]
        latents = self.vae.encode(images)['latent_dist'].sample().data
        latents *= 0.18215
        #latents = latents.sample().data
        noise = torch.randn_like(latents,device=self.device)
        timesteps = torch.randint(1,len(self.noise_scheduler),(latents.shape[0],),device=self.device)
        #noise_latents = self.noise_scheduler.add_noise(latents,noise,timesteps)
        conditioning = latents[:]
        self.unet = UNet2DConditionModel.from_pretrained(args.model_name,subfolder = 'unet')
        return self.unet(noise,timesteps,conditioning)['sample'],noise

### System Info

- `diffusers` version: 0.17.1
- Platform: Linux-5.10.0-60.18.0.50.r865_35.hce2.x86_64-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.2
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: 0.0.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by sayakpaul** [comment]
Hi @misi0202 could you provide a fully reproducible code snippet for this? 

The snippet you provided only seems to be a part of what you tried.

**Comment by misi0202** [comment]
[x4_train.txt](https://github.com/huggingface/diffusers/files/11977356/x4_train.txt)
@sayakpaul this is my full code

**Comment by misi0202** [comment]
I forget the error traceback 
`/root/workspace/train_for_x4/x4_train.py:139 in <module>                                         │
│                                                                                                  │
│   136                                                                                            │
│   137                                                                                            │
│   138 if __name__ == "__main__":                                                                 │
│ ❱ 139 │   main()                                                                                 │
│   140                                                                                            │
│   141                                                                                            │
│   142                                                                                            │
│                                                                                                  │
│ /root/workspace/train_for_x4/x4_train.py:135 in main                                             │
│                                                                                                  │
│   132 │   │   device_train_microbatch_size=1,                                                    │
│   133 │   │   max_duration='5ep',                                                                │
│   134 │   │   )                                                                                  │
│ ❱ 135 │   trainer.fit()                                                                          │
│   136                                                                                            │
│   137                                                                                            │
│   138 if __name__ == "__main__":                                                                 │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/composer/trainer/trainer.py:1804 in fit                   │
│                                                                                                  │
│   1801 │   │   │   self.state.scaler = ClosureGradScaler() if self._use_closures() else GradSca  │
│   1802 │   │                                                                                     │
│   1803 │   │   self.first_batch_complete = False                                                 │
│ ❱ 1804 │   │   self._train_loop()                                                                │
│   1805 │                                                                                         │
│   1806 │   def close(self):                                                                      │
│   1807 │   │   """Shutdown the trainer.                                                          │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/composer/trainer/trainer.py:1979 in _train_loop           │
│                                                                                                  │
│   1976 │   │   │   │   │   │   self.logger.log_metrics({'time/token': self.state.timestamp.toke  │
│   1977 │   │   │   │   │   │   self.logger.log_metrics({'time/token_in_epoch': self.state.times  │
│   1978 │   │   │   │   │                                                                         │
│ ❱ 1979 │   │   │   │   │   total_loss_dict = self._train_batch(use_grad_scaling)                 │
│   1980 │   │   │   │   │                                                                         │
│   1981 │   │   │   │   │   if use_grad_scaling:                                                  │
│   1982 │   │   │   │   │   │   self.state.scaler.update()                                        │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/composer/trainer/trainer.py:2166 in _train_batch          │
│                                                                                                  │
│   2163 │   │   │   │   │   │   │   optimizer.step(closure=lambda loss_dict=total_loss_dict, **k  │
│   2164 │   │   │   │   │   │   │   │   microbatches, loss_dict, **kwargs).item())                │
│   2165 │   │   │   │   else:                                                                     │
│ ❱ 2166 │   │   │   │   │   self._train_microbatches(microbatches, total_loss_dict)               │
│   2167 │   │   │   │   │   if not self.state.deepspeed_enabled:                                  │
│   2168 │   │   │   │   │   │   for optimizer in self.state.optimizers:                           │
│   2169 │   │   │   │   │   │   │   if use_grad_scaling:                                          │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/composer/trainer/trainer.py:2266 in _train_microbatches   │
│                                                                                                  │
│   2263 │   │   │                                                                                 │
│   2264 │   │   │   for microbatch_idx, self.state.batch in enumerate(microbatches):              │
│   2265 │   │   │   │   is_final_microbatch = microbatch_idx + 1 == len(microbatches)             │
│ ❱ 2266 │   │   │   │   microbatch_loss_dict = self._train_microbatch(use_grad_scaling, current_  │
│   2267 │   │   │   │                                                                             │
│   2268 │   │   │   │   # Aggregate each loss in microbatch_loss_dict into total_loss_dict        │
│   2269 │   │   │   │   for k, microbatch_loss in microbatch_loss_dict.items():                   │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/composer/trainer/trainer.py:2329 in _train_microbatch     │
│                                                                                                  │
│   2326 │   │   │   self.engine.run_event(Event.BEFORE_FORWARD)                                   │
│   2327 │   │   │                                                                                 │
│   2328 │   │   │   with _get_precision_context(self.state.precision, self.state.deepspeed_enabl  │
│ ❱ 2329 │   │   │   │   self.state.outputs = self.state.model(self.state.batch)                   │
│   2330 │   │   │                                                                                 │
│   2331 │   │   │   self.engine.run_event(Event.AFTER_FORWARD)                                    │
│   2332                                                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501 in _call_impl             │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /root/workspace/train_for_x4/x4_train.py:68 in forward                                           │
│                                                                                                  │
│    65 │   │   # 将图片作为cond 输入进UNet                                                        │
│    66 │   │   conditioning = latents                                                             │
│    67 │   │   # 模型更新                                                                         │
│ ❱  68 │   │   u = self.unet(noise,timesteps,conditioning)['sample']                              │
│    69 │   │   return u,noise                                                                     │
│    70                                                                                            │
│    71                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1501 in _call_impl             │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_condition.py:742 in forward      │
│                                                                                                  │
│   739 │   │   emb = self.time_embedding(t_emb, timestep_cond)                                    │
│   740 │   │   if self.class_embedding is not None:                                               │
│   741 │   │   │   if class_labels is None:                                                       │
│ ❱ 742 │   │   │   │   raise ValueError("class_labels should be provided when num_class_embeds    │
│   743 │   │   │                                                                                  │
│   744 │   │   │   if self.config.class_embed_type == "timestep":                                 │
│   745 │   │   │   │   class_labels = self.time_proj(class_labels)                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: class_labels should be provided when num_class_embeds > 0`

**Comment by sayakpaul** [comment]
Thanks for providing the snippet. But it seems like you have used another library called composer here. Would really appreciate if you could maybe provide a Colab Notebook which would help us reproducing this issue as minimally as possible. 

Also cc: @patrickvonplaten

**Comment by misi0202** [comment]
I forget my error traceback,here
![截屏2023-07-07 00 27 40](https://github.com/huggingface/diffusers/assets/101965629/196f8ed2-f7bc-41f0-90bf-a83dc15b507c)
![截屏2023-07-07 00 28 20](https://github.com/huggingface/diffusers/assets/101965629/35ed3f93-0445-4a7a-a313-ae825ed9b1db)

![截屏2023-07-07 00 27 55](https://github.com/huggingface/diffusers/assets/101965629/5e3a40ba-5ea6-45b3-a2e5-51b3acf33283)

**Comment by sayakpaul** [comment]
I understand but would be great if the reproduction could be more minimal as that really helps us to dive straight to the issue.

**Comment by misi0202** [comment]
> I understand but would be great if the reproduction could be more minimal as that really helps us to dive straight to the issue.
[error.txt](https://github.com/huggingface/diffusers/files/11979658/error.txt)
maybe this can help you?though it get killed in my environment

**Comment by sayakpaul** [comment]
Thanks for providing the snippet:

```python
from diffusers import AutoencoderKL, DDPMScheduler, UNet2DConditionModel,DDIMScheduler
import torch
device = "cuda"
model_name = 'stabilityai/stable-diffusion-x4-upscaler'
unet = UNet2DConditionModel.from_pretrained(model_name,subfolder = 'unet')

unet.enable_xformers_memory_efficient_attention()

vae = AutoencoderKL.from_pretrained(model_name, subfolder='vae')
noise_scheduler = DDIMScheduler.from_pretrained(model_name, subfolder='scheduler')

tensor_dataset = torch.zeros(1,3,1024,768)
images = tensor_dataset
latents = vae.encode(images)['latent_dist'].sample().data
latents *= 0.18215

noise = torch.randn_like(latents,device=device)


timesteps = torch.randint(1,len(noise_scheduler),(latents.shape[0],),device=device)

conditioning = latents

u = unet(noise,timesteps,conditioning)['sample']
```

Looking at the source code, seems like your inputs to the UNet is flawed: 

https://github.com/huggingface/diffusers/blob/04ddad484e26ed9689eef5aeee674895d007485a/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_latent_upscale.py#L501C1-L506C25

So, I am pinging @yiyixuxu to confirm.

**Comment by yiyixuxu** [comment]
Hi @misi0202:

the error message says "class_labels should be provided when num_class_embeds > 0" - you are using the UNet config from x4 upscaler pipeline, which expect you to pass a `class_labels` argument 

You can take a look at upscale pipeline here to understand how you can create this `class_labels` argument 
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py#L724
