### ISSUE TITLE
Support mesh output in `ShapEPipeline`

### ISSUE THREAD

**Issue by hysts** [huggingface/diffusers#3986]
**Is your feature request related to a problem? Please describe.**

`ShapEPipeline` was added in `diffusers==0.18.0`, which is nice, but currently it doesn't support outputting the generated result in mesh formats and only supports outputting rendered video in a specific way like this:
![](https://github.com/huggingface/diffusers/assets/25161192/3daee27c-b060-4d7f-b93a-6dfafdeca302)

With the [original Shap-E implementation](https://github.com/openai/shap-e), we can get output in mesh format as you can see in [this Space](https://huggingface.co/spaces/hysts/Shap-E).

https://github.com/huggingface/diffusers/assets/25161192/bd73c77e-0173-4287-9e8d-5e3febf2dfc6

I think it would be awesome if we can do the same thing with diffusers implementation as the original implementation.

**Comment by adhikjoshi** [comment]
True, more export of 3D formats are needed.
