### ISSUE TITLE
how to use part of the controlnet models with a "StableDiffusionControlNetInpaintPipeline" object?

### ISSUE THREAD

**Issue by AdamMayor2018** [huggingface/diffusers#3988]
I created a "StableDiffusionControlNetInpaintPipeline" object with a list of controlnet models such as "canny","openpose", but sometimes I want to use canny only or openpose only.Is there's a way to reuse part of the controlnet models with a already inited "StableDiffusionControlNetInpaintPipeline" object?

**Comment by sayakpaul** [comment]
I think for that you will have reinitialize the pipeline once with your preferred ControlNet models. 

@patrickvonplaten does it make sense to add a feature to `StableDiffusionControlNetPipeline` to load and unload a ControlNet _after_ it's been initialized?

**Comment by AdamMayor2018** [comment]
@sayakpaul In my scenario, different pipelines need to be used to collaborate with each other to complete business functions，while requireinitializing  differenet controlnet models result in a waste of memory.（if using gpu, this is worse）

**Comment by patrickvonplaten** [comment]
Hey Adam sure you could just do something like the following:

```py
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
import torch

multi_controlnet = [
    ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-openpose", torch_dtype=torch.float16),
    ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny", torch_dtype=torch.float16),
]

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16
)


pipe.controlnet = multi_controlnet[0] # just use one controlnet

...

pipe.controlnet = multi_controlnet  # switch again to multi controlnet
```

**Comment by AdamMayor2018** [comment]
Great! Thx! @patrickvonplaten
