### ISSUE TITLE
Different prompting strategy lead to quite different results. 

### ISSUE THREAD

**Issue by krNeko9t** [huggingface/diffusers#3993]
The topic was discussed in #2431. And it mentioned that we may realize similar results by Compel.
But I tried the library today, and get results that are far apart.
- model id: https://huggingface.co/prompthero/openjourney-v4
- common parameter: CFG scale:7.5, schedular: DDM++ 2M, steps: 20, seed: 835450454
- A1111 style prompts: two white dog, playing with one (ball:1.21)
  - results:![01191-835450454-two white dog, playing with one (ball_ 1 21)](https://github.com/huggingface/diffusers/assets/42951801/b91c07c6-843a-4a4b-8772-96ffe70908d3)
- compel style prompts: two white dog, playing with one ball++
  - results: ![image (2)](https://github.com/huggingface/diffusers/assets/42951801/46f29044-53a5-4b09-8632-0d0f5cd46c8d)

As I mentioned in https://github.com/huggingface/diffusers/issues/2431#issuecomment-1624852459, It's pretty frustrating when you can't reproduce the result produced by other platform, so is there any chance to facilitate the prompting strategy used by A1111?

**Comment by wuyangecit** [comment]
I refer to the code of webui and apply it to diffusers_pipeline. You can try it. [test.ipynb](https://github.com/wuyangecit/prompting_strategy_for_diffusers/blob/main/test.ipynb)
The input prompt and negative prompt should have the same length (which means a multiple of 77 with the same multiple), because diffusers_pipeline does not support embeddings with inconsistent tensors (the implementation logic of cfg is different from webui). 
The generated images may have some deviations, but they are still very similar.

**Comment by krNeko9t** [comment]
wow, your code do really helps me a lot. and sorry for notice it so late.
so "The input prompt and negative prompt should have the same length" means that we can't simply pass negative_prompt to the pipeline? But why i didn't find it in the official document(in fact i didn't find any negative prompting instruction there)

**Comment by krNeko9t** [comment]
> I refer to the code of webui and apply it to diffusers_pipeline. You can try it. [test.ipynb](https://github.com/wuyangecit/prompting_strategy_for_diffusers/blob/main/test.ipynb) The input prompt and negative prompt should have the same length (which means a multiple of 77 with the same multiple), because diffusers_pipeline does not support embeddings with inconsistent tensors (the implementation logic of cfg is different from webui). The generated images may have some deviations, but they are still very similar.

wow, your code do really helps me a lot. and sorry for notice it so late.
so "The input prompt and negative prompt should have the same length" means that we can't simply pass negative_prompt to the pipeline? But why i didn't find it in the official document(in fact i didn't find any negative prompting instruction there)

**Comment by krNeko9t** [comment]
And your code replace the vae of origin one, is this important?

**Comment by wuyangecit** [comment]
> And your code replace the vae of origin one, is this important?

1. Diffuser requires the input embeddings and negative embeddings to have the same dimensions, but this is not required in WebUI, so the lengths are not in the same range, resulting in differences in the generated images (in my code). It is recommended to keep length in the same range. More details can be found in the implementation of both classifier-free guidance methods.

2. VAE does not affect the content of the generated images, but only impacts the clarity of the images.

**Comment by krNeko9t** [comment]
I found that one reason of diferent result is the schedulers' config, and it seems no one makes effort of adjusting it, just leave it default, but the default behavior seems differ from the A1111?

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten 

> I found that one reason of diferent result is the schedulers' config, and it seems no one makes effort of adjusting it, just leave it default, but the default behavior seems differ from the A1111?

Could you expand more on this? 

We try to keep the default values of the scheduler matching the original implementations. But it's very easy to change the scheduler config. This doc shows many examples: https://huggingface.co/docs/diffusers/main/en/using-diffusers/control_brightness.

**Comment by krNeko9t** [comment]
> Cc: @patrickvonplaten
> 
> > I found that one reason of diferent result is the schedulers' config, and it seems no one makes effort of adjusting it, just leave it default, but the default behavior seems differ from the A1111?
> 
> Could you expand more on this?
> 
> We try to keep the default values of the scheduler matching the original implementations. But it's very easy to change the scheduler config. This doc shows many examples: https://huggingface.co/docs/diffusers/main/en/using-diffusers/control_brightness.

I try the same model on both A1111 and diffuser, and with "DPM++ 2M" scheduler, the result is perfectly matched, but with "Euler a" is not. So I think maybe it has something to do with the scheduler config, and in most cases we leave it default and it works fine, but in this situation, it's hard for a newer user to find the difference and adjust the config.

As for the original issue, what i'm (and I think a lot of others) hoping is that we can use the same prompt strategy as A1111, better be supported officially. And compel is another new thing to learn, (it's more about user habits) which is not a good alternative.

**Comment by patrickvonplaten** [comment]
Agree maybe opening an issue on Compel side can help here

**Comment by krNeko9t** [comment]
https://github.com/damian0815/compel/issues/16
there is already an issue.
