### ISSUE TITLE
[Doc] Add demo(space) to Readme file

### ISSUE THREAD

**Issue by kadirnar** [huggingface/diffusers#4001]
@patrickvonplaten 
Shall we add space to this table? I can send a pull request if you want.

https://github.com/huggingface/diffusers#popular-tasks--pipelines

**Comment by sayakpaul** [comment]
Let's please use our Discord forum for this.

**Comment by kadirnar** [comment]
@sayakpaul ,

Why? I want to add a new feature.

**Comment by kadirnar** [comment]
@sayakpaul ,
I want to do this.

Task | Pipeline | 🤗 Hub | Space 
-- | -- | -- | --
Unconditional Image Generation | DDPM | google/ddpm-ema-church-256 | Space Link
Text-to-Image | Stable Diffusion Text-to-Image | runwayml/stable-diffusion-v1-5 | Space Link
Text-to-Image | unclip | kakaobrain/karlo-v1-alpha | Space Link
... | ... | ... | ... |

**Comment by sayakpaul** [comment]
Feel free to directly open a PR.
