### ISSUE TITLE
[SD-XL] Ability to easily split prompt over the two text encoders

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#4004]
**Is your feature request related to a problem? Please describe.**
SDXL 0.9 comes with a new dual text encoder pipeline.

OpenCLIP ViT-bigG/14 and CLIP-L are both paired up in this pipeline. When running through ComfyUI, the CLIP nodes allow for inputting different pieces of the prompt, to different encoders. The default configuration is like ours, and the same prompt is handed to both encoders.

However, the creative outcome of having additional flexibility of treating the entire embed space as a single concat over the whole prompt's context, drastically alters the results.

**Describe the solution you'd like**
We are interested in adding optional parameters to the SDXL Base and Img2Img pipelines to allow this flexibility.

* `prompt_2` and `negative_prompt_2` would be great names, as they match the naming convention of `text_encoder_2`/`tokenizer_2`

**Describe alternatives you've considered**

* Creating a custom pipeline, which does not force-multiply our efforts.

**Comment by patrickvonplaten** [comment]
Hey @bghira,

Can you show me an example of where providing different text prompts for each text encoder gives much better results? I don't see the use case here a 100% at the moment

**Comment by bghira** [comment]
nor i or anyone i've asked haven't been able to get the prompt embeds working, and imo having a built in way of doing this seems like it would be really beneficial without having users need to pull Compel in, which they may not be comfortable with.

The subject portion of the prompt in OpenCLIP, and style in CLIP-L:
![OpenCLIP prompt](https://github.com/huggingface/diffusers/assets/59658056/fecb3eb9-b42d-4ec0-84f2-75c67a69b51a)

The subject portion of prompt in CLIP-L and the style in OpenCLIP:
![image](https://github.com/huggingface/diffusers/assets/59658056/fcdde663-e478-41ba-b30c-690e81748679)

The subject and style prompt in OpenCLIP, with CLIP-L as unconditional guidance:
![image](https://github.com/huggingface/diffusers/assets/59658056/34ac767e-f3fe-4d86-b939-34f000d80343)

**Comment by bghira** [comment]
nor i or anyone i've asked haven't been able to get the prompt embeds working, and imo having a built in way of doing this seems like it would be really beneficial without having users need to pull Compel in, which they may not be comfortable with.

The subject portion of the prompt in OpenCLIP, and style in CLIP-L:
![image](https://github.com/huggingface/diffusers/assets/59658056/34ac767e-f3fe-4d86-b939-34f000d80343)

The subject portion of prompt in CLIP-L and the style in OpenCLIP:
![image](https://github.com/huggingface/diffusers/assets/59658056/7940d6d1-028a-4e85-a52b-090dce464ce0)


The subject and style prompt in CLIP-L, with OpenCLIP as unconditonal guidance:
![image](https://github.com/huggingface/diffusers/assets/59658056/be1ef4ee-9efc-4fc4-a75f-db28bf961249)

The subject and style prompt in OpenCLIP, with CLIP-L as unconditional guidance:
![image](https://github.com/huggingface/diffusers/assets/59658056/ebfe83f2-dbce-401b-8d87-a39813f3201a)

Both encoders have both portions of the prompt
![image](https://github.com/huggingface/diffusers/assets/59658056/e1f1bddf-bc2c-401a-bb79-c51f8834e9f8)

**Comment by sayakpaul** [comment]
Spectacular results! 

> nor i or anyone i've asked haven't been able to get the prompt embeds working

Could you expand on this further? Do you mean passing `prompt_embeds` don't work with our SDXL pipeline?

**Comment by patrickvonplaten** [comment]
Ok this seems to make a lot of sense then, thanks for the results! Think it shouldn't be too difficult to support it wit has you say a `prompt_2` and `negative_prompt_2` input, ok for me to add this! @bghira would you like to give the PR a try? :-)

**Comment by bghira** [comment]
@patrickvonplaten i know my limits, and text embeds seem to be one :D i simply propose the idea for others who willing to take it up and understand these components better.

**Comment by patrickvonplaten** [comment]
Actually I think we can have prompt_embeds with Compel as well as a very easy user-interface with `prompt_2` and `negative_prompt_2` :-) So if you'd like to add this, I'm more than happy to review a PR!

**Comment by MercuryOoO** [comment]
> nor i or anyone i've asked haven't been able to get the prompt embeds working, and imo having a built in way of doing this seems like it would be really beneficial without having users need to pull Compel in, which they may not be comfortable with.
> 
> The subject portion of the prompt in OpenCLIP, and style in CLIP-L: ![image](https://private-user-images.githubusercontent.com/59658056/252156340-34ac767e-f3fe-4d86-b939-34f000d80343.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODQ1NjcsIm5iZiI6MTcwNjM4NDI2NywicGF0aCI6Ii81OTY1ODA1Ni8yNTIxNTYzNDAtMzRhYzc2N2UtZjNmZS00ZDg2LWI5MzktMzRmMDAwZDgwMzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZjY1MDJjNTg2N2JiODRjODhkNWYzZjYyN2ViM2FiMzc1Mjk1ZDI0ZDY4ODM2NjllODczOWE3NDM1ZWY1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.93YlZymLBr5dzRbz7BICqr8Fs_vdxwsQSNA2uW5ouWI)
> 
> The subject portion of prompt in CLIP-L and the style in OpenCLIP: ![image](https://private-user-images.githubusercontent.com/59658056/252156765-7940d6d1-028a-4e85-a52b-090dce464ce0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODQ1NjcsIm5iZiI6MTcwNjM4NDI2NywicGF0aCI6Ii81OTY1ODA1Ni8yNTIxNTY3NjUtNzk0MGQ2ZDEtMDI4YS00ZTg1LWE1MmItMDkwZGNlNDY0Y2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOTFhMWIzYzg1YzJmMTg2N2Y5MTJkNDQ5NzFlYWU5NWRiYWU3YThlM2MwMGI5NDNhODRlYjQ1YjcwYTRmZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ip1cH2Y1YvX9hiVqnLhCb0sIn-hWVYgeqnDqcZGB7q8)
> 
> The subject and style prompt in CLIP-L, with OpenCLIP as unconditonal guidance: ![image](https://private-user-images.githubusercontent.com/59658056/252156663-be1ef4ee-9efc-4fc4-a75f-db28bf961249.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODQ1NjcsIm5iZiI6MTcwNjM4NDI2NywicGF0aCI6Ii81OTY1ODA1Ni8yNTIxNTY2NjMtYmUxZWY0ZWUtOWVmYy00ZmM0LWE3NWYtZGIyOGJmOTYxMjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NjA3ZjJhZWZhZjVkN2YwN2NhNTA0NmVmYzNiMmZiYjc3ODVhOWFiNDg0ODA0MjZlMTBhNjRhMDRlNzY3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ibllEc56HjjtxcAwCOOaFtqUEr_XoQpUyUwSdnOPFfY)
> 
> The subject and style prompt in OpenCLIP, with CLIP-L as unconditional guidance: ![image](https://private-user-images.githubusercontent.com/59658056/252156619-ebfe83f2-dbce-401b-8d87-a39813f3201a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODQ1NjcsIm5iZiI6MTcwNjM4NDI2NywicGF0aCI6Ii81OTY1ODA1Ni8yNTIxNTY2MTktZWJmZTgzZjItZGJjZS00MDFiLThkODctYTM5ODEzZjMyMDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYzgzZjVkMjM5NTgwYzYyNTEyNDViYTY0NGU4MTU1NTM5ZGFjYmJjNGMwZmYxODI5ZTU2ZjljY2M4ZDg5ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3SA_9Jir6d-9-7JacjtkdHYuOXZu34nMbYceSsWVlbY)
> 
> Both encoders have both portions of the prompt ![image](https://private-user-images.githubusercontent.com/59658056/252156814-e1f1bddf-bc2c-401a-bb79-c51f8834e9f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODQ1NjcsIm5iZiI6MTcwNjM4NDI2NywicGF0aCI6Ii81OTY1ODA1Ni8yNTIxNTY4MTQtZTFmMWJkZGYtYmMyYy00MDFhLWJiNzktYzUxZjg4MzRlOWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE5Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMWEzZDZkMjJjZmQ2ZmQzZTczYTg0ZDU2NDQwMDhmZDdmYWFhMTVhY2UxNTNiMGFhMjViY2MxNjRhZTk5ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FwX6DKHa994CYo_-icrTvr6jEZkGhKklaO2Y5tj_nYE)

Off-topic, since I didn't find a way to send you a private message, I took the liberty of asking you here. Can you tell me what model and prompt you used to generate these images?

**Comment by bghira** [comment]
that is my model, Terminus. though it is a much earlier version. I don't have the prompt anymore.

**Comment by MercuryOoO** [comment]
> Terminus

Thanks!
