### ISSUE TITLE
StableDiffusionInpaintPipeline doesn't preserve aspect ratio

### ISSUE THREAD

**Issue by ballenvironment** [huggingface/diffusers#4005]
**Is your feature request related to a problem? Please describe.**
StableDiffusionImg2ImgPipeline works without providing `width` and `height` (it automatically uses the original width/height and preserves the aspect ratio). On the other hand, StableDiffusionInpaintPipeline doesn't use the original width/height when
not provided, and it complains when given values that are not divisible by 8.

**Describe the solution you'd like**
```py
# StableDiffusionInpaintPipeline
image = generator(
                image=input_image,
                mask_image=input_mask,
                # Optional width=width,
                # Optional height=height,
                strength=denoise,
                prompt_embeds=conditioning,
                negative_prompt_embeds=negative_conditioning,
                num_inference_steps=steps,
                guidance_scale=cfg,
                generator=torch.manual_seed(seed)
).images[0]
```

**Describe alternatives you've considered**
I have to manually resize the image to values that are divisible by 8, rather than diffusers doing it for me.

**Additional context**

**Comment by patrickvonplaten** [comment]
@yiyixuxu can you take a look here?

**Comment by yiyixuxu** [comment]
We will add the function to automatically resize when we refactor the inpaint pipelines with image_processor
