### ISSUE TITLE
[SD-XL] Flax implementation

### ISSUE THREAD

**Issue by mar-muel** [huggingface/diffusers#4007]
Is there a plan for supporting the SD-XL pipeline in flax? If so, I would be happy to help bringing it to diffusers 🤗

**Comment by patrickvonplaten** [comment]
cc @pcuenca here! @mar-muel it'd be great if you could start working on a PR, we'd definitely like to implement a SD-XL Flax pipeline :-)

**Comment by pcuenca** [comment]
@mar-muel That'd be fantastic! Would you like to get started? We can help during the process as needed :)

**Comment by mar-muel** [comment]
Yes, I'm potentially interested... However, I need to see how much time I can commit, currently going through the guides. What would be the best way to kickstart this?

**Comment by pcuenca** [comment]
Not sure tbh. I think I'd start from the current UNet flax implementation (https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_condition_flax.py), and then go over the changes performed in the main `sd_xl` PR trying to replicate them: https://github.com/huggingface/diffusers/pull/3859/files#diff-82dc116be034805ec08e24069d853854b00fe559f5178b87269653fa43d1e7c8.

I'd then test numerically that the UNet gives results close to the PyTorch version when using the same latents. Then I'd continue with the other components of the pipeline.

**Comment by pcuenca** [comment]
And of course it's understandable you are still not sure about the time commitment. Take a look if you want and we'll go from there :)

**Comment by mar-muel** [comment]
Alright yes, sounds good! My colleague @MasterScrat decided to join in :) We'll open PR as soon as we have something workable
