### ISSUE TITLE
[SDXL 0.9] Quick question regarding SDXL and example training scripts

### ISSUE THREAD

**Issue by xiankgx** [huggingface/diffusers#4013]
Hi team, thank you for the hard work in porting SDXL 0.9 to diffusers. If I may, can I know what are the status of the compatibility of example training scripts (text-to-image, dreambooth, controlnet, etc) for SDXL 0.9? I'm using the version 0.18.1 of diffusers right now.

**Comment by sayakpaul** [comment]
DreamBooth is already compatible:

https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_sdxl.md

ControlNet is being worked on: https://github.com/huggingface/diffusers/pull/4038

If you have anything specific, feel free to open separate issues. For now, I am going to close this thread.
