### ISSUE TITLE
[Lora] control weight block by bloak

### ISSUE THREAD

**Issue by ZhouXiner** [huggingface/diffusers#4017]
https://github.com/hako-mikan/sd-webui-lora-block-weight

this project provides the function of controlling different loras weight block by block.
I think that is a good way to fuse different loras and control the effect of lora. 
Is there any way we can control the weight in diffuers?

**Comment by sayakpaul** [comment]
Is the idea to apply different `scales` to each block while merging the LoRA parameters? No, we don't allow that. We have a single `scale` parameter that allows you to change the weighting, but that applies to _all_ the blocks.

**Comment by ZhouXiner** [comment]
ok, thanks.
