### ISSUE TITLE
Outpaint Help

### ISSUE THREAD

**Issue by ballenvironment** [huggingface/diffusers#4018]
Hello, I am trying to implement outpaint, which doesn't have a pipeline in diffusers, but I thought it would be possible with `StableDiffusionInpaintPipeline`. However, I can't seem to get it to work.

My initial idea was to extend the borders of the image and fill it with white, then create a mask with white on the extended areas. I also applied a blur to the mask because I thought it would work better with soft edges, but I'm not noticing any difference.

Image:

<img width="400" src="https://github.com/huggingface/diffusers/assets/111252136/d7512358-a26e-406b-bb28-d8b8f8b5303c"/>

Mask:

<img width="400" src="https://github.com/huggingface/diffusers/assets/111252136/ed8bff50-5d63-4bd9-a0ec-535d6ea4c8fa"/>

Output:

<img width="400" src="https://github.com/huggingface/diffusers/assets/111252136/d208dd2e-092e-4611-9d77-da168df94a3d"/>

It does seem to change some of the content in the original image (in the bounds of the blurred mask), but the borders are left practically untouched. Could someone explain what is the correct way of implementing outpaint?

**Comment by sayakpaul** [comment]
Could you please provide a full code snippet that we could experiment with? 

Cc: @patrickvonplaten as well.

**Comment by ballenvironment** [comment]
I'm just using `StableDiffusionInpaintPipeline` as normal, using the image and mask I showed above. Here is a short code snippet that is the gist of it. 

```py
from diffusers import StableDiffusionInpaintPipeline
from PIL import Image

image = Image.open("image.png")
mask = Image.open("mask.png")

generator = StableDiffusionInpaintPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
generator.enable_attention_slicing()

image = generator(
      image=image,
      mask_image=mask,
      width=mask.width,
      height=mask.height,
      strength=0.7,
      prompt="prompt",
      negative_prompt="negative prompt",
      num_inference_steps=20,
      guidance_scale=7,
      num_images_per_prompt=1,
      generator=torch.manual_seed(0)
  ).images[0]

image.save("output.png")
```

**Comment by sayakpaul** [comment]
Thanks!

What happens when you don't apply any filtering to the mask? Also, does the behavior persist when changing the mask?

**Comment by ballenvironment** [comment]
I get the same result with no blur applied. (I thought the blur would've helped). It only changes content within the original image, never on the extended borders.

**Comment by patrickvonplaten** [comment]
But your mask also is set to 0 on the borders no? So if the mask is set to 0 nothing will be changed there

**Comment by xiankgx** [comment]
1. Are your masks pixel values 255 in the areas you want to inpaint/outpaint? From the mask image it seems it is (white on the outside).

2. I believe the inpainting pipeline is pretty much a pipeline like the img2img, with the "strength" parameter. If my understanding is correct, the unmasked areas are almost never modified in the generation process (save for the reconstruction errors). What will change is then just the masked areas (255 or white). If we have strength=1.0, then you should be able to inpaint/outpaint/redraw your masked areas. If we have strength<1.0, then it keeps some of your initial image. This is probably what you are not trying to do with outpaint, because then your white padded areas in your input image will leak into the generated output also. Hence, you probably have no choice, but to set strength to be 1.0.

**Comment by ballenvironment** [comment]
> 2. I believe the inpainting pipeline is pretty much a pipeline like the img2img, with the "strength" parameter. If my understanding is correct, the unmasked areas are almost never modified in the generation process (save for the reconstruction errors), no matter what "strength" value you put, because there is a line of code which keeps replace the unmasked latent values. What will change is then just the masked areas (255 or white). If we have strength=1.0, then you should be able to inpaint/outpaint/redraw your masked areas. If we have strength<1.0, then it keeps some of your initial image, which is probably what you are not trying to do with outpaint, because then your white padded areas in your input image (you padded the image with white just so that image and mask have the same shape) will leak into the generated output also. Hence, you probably have no choice, but to set strength to be 1.0.

Ah, that was it. The strength has to be set to `1.0`, anything less than that and it doesn't seem to work. I had it at like 0.7 or so, now with it set to 1.0 it is correctly painting on the expanded areas.

**Comment by sayakpaul** [comment]
> Ah, that was it. The strength has to be set to 1.0, anything less than that and it doesn't seem to work. I had it at like 0.7 or so, now with it set to 1.0 it is correctly painting on the expanded areas.

If you think any part of our documentation can be improved here, please let us know. You can also contribute a PR directly which is be tremendously helpful. 

Cc: @patrickvonplaten @stevhliu
