### ISSUE TITLE
Unload lora weights after they have been loaded

### ISSUE THREAD

**Issue by pietrobolcato** [huggingface/diffusers#4027]
### Describe the bug

There's no method to unload LoRA weights after they have been loaded. An issue was opened already (https://github.com/huggingface/diffusers/issues/3689) but that doesn't solve the problem

### Reproduction

1. Generate without LoRA, a fresh loaded pipeline

![image](https://github.com/huggingface/diffusers/assets/3061306/929c9239-19f8-43a5-a123-7de8ef0220cc)

3. Generate with LoRA

![image](https://github.com/huggingface/diffusers/assets/3061306/c2381423-bf80-419c-84de-e073b475da16)

4. Remove LoRA:

```
self.text_to_image_pipeline.unet.set_attn_processor(AttnProcessor2_0())
```

![image](https://github.com/huggingface/diffusers/assets/3061306/fea3e348-c64d-4b40-9d23-c1412886a440)

All the settings are kept the same. It would be really great to have a built-in method in the pipeline to unload the LoRA weights, this is really helpful at inference time!

If needed, this is the code whole code:

```python
"""Text to image component class"""

import random
import sys
from typing import List

import torch
from compel import Compel
from diffusers import DiffusionPipeline, StableDiffusionPipeline
from diffusers.models.attention_processor import AttnProcessor2_0
from diffusers.pipelines.stable_diffusion import StableDiffusionPipelineOutput

from src.image_generation.components import utils
from src.image_generation.components.postprocessor import Postprocessor


class TextToImage:
    """Initialize the text to image pipeline, and expose methods to perform inference"""

    def __init__(
        self,
        model_pipeline: DiffusionPipeline,
        postprocessor: Postprocessor = None,
        enable_xformers: bool = False,
    ) -> None:
        """Initalize the text to image pipeline

        Parameters
        ----------
        model_pipeline : DiffusionPipeline
            The base model pipeline to copy the components from
        postprocessor : Postprocessor, optional
            The postprocessor class, initialized and with the model loaded

            Defaults to None
        enable_xformers: bool, optional
            If true, it enables xformers optimization for the pipelines. It needs the
            package `xformer` to be installed for it to work.

            Defaults to False
        """
        self.device = utils.get_device()
        self.postprocessor = postprocessor

        self.text_to_image_pipeline = StableDiffusionPipeline(
            **model_pipeline.components,
        ).to(self.device)

        self.compel_processor = Compel(
            tokenizer=self.text_to_image_pipeline.tokenizer,
            text_encoder=self.text_to_image_pipeline.text_encoder,
        )

        if enable_xformers:
            utils.enable_xformers(self.text_to_image_pipeline)

    def generate(
        self,
        prompt: str,
        negative_prompt: str = "",
        width: int = 512,
        height: int = 512,
        num_inference_steps: int = 20,
        guidance_scale: float = 7.5,
        num_images_per_prompt: int = 1,
        seed: int = None,
        apply_gfpgan: bool = False,
        lora_path: str = None,
    ) -> StableDiffusionPipelineOutput:
        """Performs text to image inference

        Parameters
        ----------
        prompt : str
            The prompt or prompts to guide the image generation. It supports prompt
            weight using `+` and `-`, according to https://github.com/damian0815/compel
        negative_prompt : str, optional
            The prompt or prompts not to guide the image generation

            Defaults to ""
        width : int, optional
            The width of the generated image.

            Defaults to 512
        height : int, optional
            The height of the generated image.

            Defaults to 512
        num_inference_steps : int, optional
            The number of denoising steps. More denoising steps usually lead to a higher
            quality image at the expense of slower inference.

            Defaults to 20
        guidance_scale : float, optional
            Higher guidance scale encourages to generate images that are closely linked
            to the text prompt, usually at the expense of lower image quality.

            Defaults to 7.5
        num_images_per_prompt : int, optional
            The number of generated images per prompt

            Defaults to 1
        seed : int, optional
            An integer used as random seed to have reproducible results
            If None, random seeds will be generated.

            Defaults to None
        apply_gfpgan : bool, optional
            If true, applies GPFGAN on the generated images. GFPGAN must be initialized
            in the constructor, otherwise a warning is raised.

            Defaults to False
        lora_path : str, optional
            If specified, it loads a LoRA weight before running inference

            Defaults to None

        Returns
        -------
        StableDiffusionPipelineOutput:
            An object containing the list of generated images, and a flag expressing if
            NSFW was detected.

            The images can be accessed using the `images` property, and the NSFW flag
            using the `nsfw_content_detected` property.
        """
        if seed is None:  # set random seed
            seed = random.randint(0, sys.maxsize)
        
        if lora_path is not None:  # load LoRA
            self.text_to_image_pipeline.load_lora_weights(lora_path)
        else: # unload LoRA
            self.text_to_image_pipeline.unet.set_attn_processor(AttnProcessor2_0())

        result = self.text_to_image_pipeline(
            prompt_embeds=self.compel_processor(prompt),
            negative_prompt_embeds=self.compel_processor(negative_prompt),
            width=width,
            height=height,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            num_images_per_prompt=num_images_per_prompt,
            generator=torch.manual_seed(seed),
        )

        # apply postprocessing if model is initialized and flag set to true
        if apply_gfpgan and self.postprocessor:
            result.images = self.postprocessor.apply_gfpgan(result)

        return result
```

### System Info

Diffusers 0.18.1, python 3.10.11

### Who can help?

@sayakpaul

**Comment by pietrobolcato** [comment]
It would be really great to have a method to unload lora weights, this is super helpful at inference time when an endpoint can switch between many LoRA, or just fall back to the original model weights

Thanks for the great work!

**Comment by sayakpaul** [comment]
We need to be able to reproduce first. As noted in https://github.com/huggingface/diffusers/issues/3689#issuecomment-1582323065, with the approach you followed, I was able to unload the LoRA attention processor already. 

If you could provide your LoRA file, I can look into it further. But meanwhile, I will just add a test to ensure the robustness of the approach.

**Comment by pietrobolcato** [comment]
Thanks a lot @sayakpaul! I will provide tomorrow with the LoRA and ideally a colab to reproduce the issue

**Comment by pietrobolcato** [comment]
Hey dear @sayakpaul, as promised I created a colab where it's very easy to reproduce the issue. You can access it [here](https://colab.research.google.com/drive/1QkcLSMGTQ1ujoDPgtQgFv93cZUCgMW9s?usp=sharing). It simply istantiates a diffuser pipeline with SD 1.5, generate an image without any lora applied, then applies the lora and unload it, and compare the difference between the output. The result looks like:

![image](https://github.com/huggingface/diffusers/assets/3061306/0d5066bc-5753-42e0-ad4d-e1726eb78535)

As you can see, there's a clear difference, which is the issue I'm talking about. 

I'm no diffusers expert so take this with a big grain of salt, but looking at the implementation of `load_lora_weights` it appears that the LoRA weights are loaded both in the unet and the text encoder, as shown [here](https://github.com/huggingface/diffusers/blob/6632823690707604ef364e4d2fa02269bf1a7d07/src/diffusers/loaders.py#L828). Couldn't the problem arise from the fact that to unload the LoRA we only replace the Unet and not the text encoder as well?

You can find the LoRA in the colab, but for convenience you can also access it [here](https://civitai.com/models/60132/colored-icons-logo-generator). 

Thank you so much! Let me know if I can do anything else to help :)

**Comment by sayakpaul** [comment]
Thanks much for being so eloquent! And you're absolutely right here:

> I'm no diffusers expert so take this with a big grain of salt, but looking at the implementation of load_lora_weights it appears that the LoRA weights are loaded both in the unet and the text encoder, as shown [here](https://github.com/huggingface/diffusers/blob/6632823690707604ef364e4d2fa02269bf1a7d07/src/diffusers/loaders.py#L828). Couldn't the problem arise from the fact that to unload the LoRA we only replace the Unet and not the text encoder as well?

So, when I did:

```python
# unload lora
pipeline.unet.set_attn_processor(AttnProcessor2_0())
pipeline._remove_text_encoder_monkey_patch()
```

The problem actually went away:

![image](https://github.com/huggingface/diffusers/assets/22957388/a56453df-c68e-464b-af20-123ba3a2a19d)


Here's my Colab Notebook: https://colab.research.google.com/gist/sayakpaul/f5669f344a213d20854e9bd04d35f57b/issue-4027-hf-diffusers.ipynb

I think it makes sense for us to create an unloading utility from the pipeline-level and document it in details.

**Comment by rvorias** [comment]
I'm keeping a "zero lora" around to load if I want vanilla gen. Don't know about the time difference between loading lora weights vs removing + injecting tho.

**Comment by pietrobolcato** [comment]
> Thanks much for being so eloquent! And you're absolutely right here:
> 
> > I'm no diffusers expert so take this with a big grain of salt, but looking at the implementation of load_lora_weights it appears that the LoRA weights are loaded both in the unet and the text encoder, as shown [here](https://github.com/huggingface/diffusers/blob/6632823690707604ef364e4d2fa02269bf1a7d07/src/diffusers/loaders.py#L828). Couldn't the problem arise from the fact that to unload the LoRA we only replace the Unet and not the text encoder as well?
> 
> So, when I did:
> 
> ```python
> # unload lora
> pipeline.unet.set_attn_processor(AttnProcessor2_0())
> pipeline._remove_text_encoder_monkey_patch()
> ```
> 
> The problem actually went away:
> 
> ![image](https://user-images.githubusercontent.com/22957388/252855607-a56453df-c68e-464b-af20-123ba3a2a19d.png)
> 
> Here's my Colab Notebook: https://colab.research.google.com/gist/sayakpaul/f5669f344a213d20854e9bd04d35f57b/issue-4027-hf-diffusers.ipynb
> 
> I think it makes sense for us to create an unloading utility from the pipeline-level and document it in details.

Sounds great dear @sayakpaul happy to be of help! From my end user perspective an utility method to unload the lora would really be great! Also given that the current method of manually re-setting the AttnProcessor2_0 is not really future proof as the default attention processor might change in diffusers, and if the end user has a custom function to unload lora, it need to update it and keep up with this details of internal implementation which could cause problems.

> I'm keeping a "zero lora" around to load if I want vanilla gen. Don't know about the time difference between loading lora weights vs removing + injecting tho.

@rvorias that's a very good idea, a good workaround for the time being! how did you export the zero lora weights?

**Comment by sayakpaul** [comment]
> Sounds great dear @sayakpaul happy to be of help! From my end user perspective an utility method to unload the lora would really be great! Furthermore, the current manual resetting of AttnProcessor2_0 may not be suitable for future changes in the default attention processor within diffusers. If the end user has a custom function to unload lora, they would need to update it and stay updated with the internal implementation details, which could potentially lead to problems

We cannot be tracking what the end user use to unload LoRA when there's a recommendation. Given how things are designed in diffusers, the attention processors won't likely change. 

I have started #4034 to ship this. So, with thay, hopefully, we will close this.

**Comment by pietrobolcato** [comment]
> > Sounds great dear @sayakpaul happy to be of help! From my end user perspective an utility method to unload the lora would really be great! Furthermore, the current manual resetting of AttnProcessor2_0 may not be suitable for future changes in the default attention processor within diffusers. If the end user has a custom function to unload lora, they would need to update it and stay updated with the internal implementation details, which could potentially lead to problems
> 
> We cannot be tracking what the end user use to unload LoRA when there's a recommendation. Given how things are designed in diffusers, the attention processors won't likely change.
> 
> I have started #4034 to ship this. So, with thay, hopefully, we will close this.

Sounds good dear @sayakpaul really appreciate your help and work! :)

**Comment by sayakpaul** [comment]
https://github.com/huggingface/diffusers/pull/4034 is now merged and hence I am closing the issue :)
