### ISSUE TITLE
How to combine the reference-only with inpainting and depth control?

### ISSUE THREAD

**Issue by AmberCheng** [huggingface/diffusers#4042]
### Model/Pipeline/Scheduler description

Hi, I recently want to combine the reference-only with image inpaint , with depth control to replace background for portrait images. However, I have no idea to build this pipeline as for there is no reference with inpaint pipeline example.  Could you please help me to figure it out?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by patrickvonplaten** [comment]
This is not possible at the moment, I'm afraid. Would you maybe like to add a community pipeline for this? :-) 

See: https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md#6-contribute-a-community-pipeline

**Comment by AmberCheng** [comment]
> 

thanks, I may have a try~
