### ISSUE TITLE
has no attribute 'from_single_file'

### ISSUE THREAD

**Issue by zhaoyun0071** [huggingface/diffusers#4052]
### Describe the bug

'StableDiffusionControlNetImg2ImgPipeline' has no attribute 'from_single_file'
ControlNetModel has no attribute 'from_single_file'

load single file is very important

pls 

### Reproduction

controlnet = ControlNetModel.from_single_file

### System Info

0.18.2

**Comment by ezjhpark23** [comment]
also
`AttributeError: type object 'StableDiffusionControlNetPipeline' has no attribute 'from_single_file'`

**Comment by patrickvonplaten** [comment]
And a forth issue here haha: https://github.com/huggingface/diffusers/issues/3907 

Alright time to fix this will open a PR

**Comment by zhaoyun0071** [comment]
> Hey @zhaoyun0071,
> 
> Can you check if this works for you: #4084

perfect work, i test diffusers-0.19.0.dev0

ControlNetModel.from_single_file   
AutoencoderKL.from_single_file
StableDiffusionControlNetPipeline.from_single_file
StableDiffusionControlNetImg2ImgPipeline.from_single_file
all work!!!

now I look forward Loading multiple Lora models with different proportions

**Comment by philz1337x** [comment]
Could you add CLIPTokenizer.from_single_file as well @patrickvonplaten

**Comment by CrackerHax** [comment]
FluxControlNetModel needs too

**Comment by riflemanl** [comment]
Yes, FluxControlNetModel needs from_single_file, too.  Original Flux related models are all huge, Many people help to release fp8 models including ControlNet models as well. All those 3rd party released models are all single file based. So, diffusers must have from_singl_file support to help developers can git all these models including base models, controlnet models all work together in 24GB VRAM.

**Comment by LostBee** [comment]
If anyone else is still getting this issue then instead of using 'DiffusionPipeline' class, please use 'StableDiffusionXLPipeline', specialy if you're working on a model like 'epicrealismXL' which I'm using.
