### ISSUE TITLE
Blurred output from Finetuned Inpainting model 

### ISSUE THREAD

**Issue by shreyassks** [huggingface/diffusers#4057]
I am trying to finetune inpainting model on 5 images of dog. I have trained for 400, 1000, 1500 steps but at inference I get blurred output. What could have gone wrong?

!accelerate launch train_dreambooth_inpaint.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-inpainting"  \
  --instance_data_dir="./instance-images/" \
  --output_dir="./notebooks/" \
  --instance_prompt="a photo of sks dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --train_text_encoder \
  --use_8bit_adam \
  --gradient_accumulation_steps=1 \
  --learning_rate=4e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=1500

<img width="517" alt="Screenshot 2023-07-12 at 5 42 59 PM" src="https://github.com/huggingface/diffusers/assets/44189581/ef019c02-d80c-4af1-b2ed-2c1318caa20a">

**Comment by patrickvonplaten** [comment]
Think for such questions you might find a better answer on the forum: https://discuss.huggingface.co/
