### ISSUE TITLE
Unloading a Textual Inversion Checkpoint

### ISSUE THREAD

**Issue by sarmientoj24** [huggingface/diffusers#4063]
### Model/Pipeline/Scheduler description

This is how I load a textual inversion checkpoint

```
pipeline.load_textual_inversion('myckpt.bin')
```

Is unloading implemented?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by patrickvonplaten** [comment]
Why do you need to unload it? The checkpoints are really not that heavy no? For now, I'd recommend doing:

```py
pipe.text_encoder.resize_token_embeddings(len(pipe.tokenizer) - len(pipe.tokenizer.added_tokens_encoder)
```

**Comment by patrickvonplaten** [comment]
We could think about adding an unload textual inversion function though

**Comment by sarmientoj24** [comment]
@patrickvonplaten wont there be problems if i loaded 1000+ different textual inversions?

**Comment by patrickvonplaten** [comment]
Not necessarily no I don't think so. What problem did you have in mind

**Comment by sarmientoj24** [comment]
The token's "space" in the embedding getting "full"? 
Alright, thank you!

**Comment by segalinc** [comment]
is this solved? I am looking for the same problem when you might load the textual inversion with some args, you want to unload it and reaload it with different args, like torch type or variant for isnstance

**Comment by isidentical** [comment]
Is there a chance we can revive this ticket since this seems like a cool functionality for APIs that load arbitrary textual inversions that might conflict with each other in the tokens they are dealing with.

**Comment by patrickvonplaten** [comment]
Agree I think it makes sense to add such a functionality - @sayakpaul wdyt about how to best unload the tokens?

**Comment by sayakpaul** [comment]
Cc: @apolinario does this seem relevant?

**Comment by sayakpaul** [comment]
Not stale.

**Comment by sayakpaul** [comment]
I think @fabiorigano is working on this?

**Comment by fabiorigano** [comment]
Yes, I am waiting for further review of PR #6656
