### ISSUE TITLE
Generation with lora_scale doesn't remain consistent when using prompt embeddings

### ISSUE THREAD

**Issue by pietrobolcato** [huggingface/diffusers#4067]
### Describe the bug

When using compel and prompt embeddings, and performing inference with LoRA weights loaded, `lora_scale` doesn't work as expected. Specifically, if I do the following actions in the following order:

1. Create a SD pipeline
2. Load a model
3. Load a LoRA
4. Generate an image with `lora_scale` = 1
5. Generate an image with `lora_scale` = 0
6. Generate an image with `lora_scale` = 1
7. Generate an image with `lora_scale` = 1

The image generated in Step 6. is different from the image generated in Step 4. All the following images, if  `lora_scale` is not changed again, remain consistent. Basically what happens is that somehow it takes one generation to get back on track and remain consistent. See plot attached:

![image](https://github.com/huggingface/diffusers/assets/3061306/ab3dcf56-3183-4073-a344-43a5ec44560a)

We can see that `Image 3` is different from `Image 1`, and from `Image 4` on, as long as `lora_scale` don't change, it remains consistent. 

This doesn't happen when not using compel and prompt embeddings:

![image](https://github.com/huggingface/diffusers/assets/3061306/8184ada7-58cc-4771-9d8c-9aea28a8ebd6)

### Reproduction

I prepared a colab that shows the issue, accessible here: https://colab.research.google.com/drive/1ciFZPcvMsNZiZOpfHtLih5V6OyRh8Z6d?usp=sharing

### System Info

diffusers[torch]==0.18.1 -q
transformers==4.30.2 -q
compel==1.2.1 -q

### Who can help?

@sayakpaul @patrickvonplaten @williamberman

**Comment by sayakpaul** [comment]
Thanks for reporting the issue. Could you try to reproduce the issue without `compel` as that is an external dependency?

**Comment by pietrobolcato** [comment]
Sure will try! Thanks @sayakpaul!

**Comment by pietrobolcato** [comment]
> I ran into this issue yesterday, and a workaround I think you can try is set `pipe._lora_scale = your_lora_alpha` manually **before** creating the prompt embeds using compel.
> 
> For e.g.
> 
> ```python
> lora_alpha = 0.8 # the desired alpha
> 
> pipe._lora_scale = lora_alpha  # this workaround sets the alpha before compel is run
> 
> prompt_embeds = compel("photo of a tuna")
> 
> pipe(prompt_embeds=prompt_embeds, cross_attention_kwargs={"scale": lora_alpha}, ...)
> ```
> 
> The reason for this is that compel calls the text-encoder while generating the prompt_embeds, but the lora alpha is set only during the actual call to the pipeline (since we pass the alpha then). So we need to set the alpha manually before that, so that compel picks up the correct alpha.
> 
> I hope this is similar to what you're experiencing, and helps you. Either case, I think this needs a better solution, but I'm not sure how to solve this without changing the API.

That solves the issue, thank you so much! Great find :) appreciate a lot your help!

**Comment by sayakpaul** [comment]
Closing this issue then. Feel free to reopen :)
