### ISSUE TITLE
Unloading a Textual Inversion Checkpoint from Pipeline

### ISSUE THREAD

**Issue by sarmientoj24** [huggingface/diffusers#4069]
### Describe the bug

This is how I load a textual inversion checkpoint

```
pipeline.load_textual_inversion('myckpt.bin')
```

Is unloading implemented?

### Reproduction

```
pipeline.load_textual_inversion('myckpt.bin')
```

### System Info

Latest diffusers

**Comment by patrickvonplaten** [comment]
Duplicate of https://github.com/huggingface/diffusers/issues/4063

@sarmientoj24 can you please make sure to not post the same issue twice?
