### ISSUE TITLE
Inpaint only+lama support

### ISSUE THREAD

**Issue by adelacvg** [huggingface/diffusers#4071]
**Is your feature request related to a problem? Please describe.**
It was comfy to use the inpaint only + lama controlnet on sd webui to do inpaint that match the firefly's inpaint quality.
But it's not support in diffusers.

**Describe the solution you'd like**
I hope diffusers can add an official controlnet inapintonly+lama pipeline for better inpaint results.

**Describe alternatives you've considered**
There has been many community pipeline for inpaint or inpaint controlnet, maybe it can give some help. And the inpaint controlnet input parameters are not support a mask as input, hope it can support mask as input.

**Comment by kelisiya** [comment]
+1
