### ISSUE TITLE
Can ControlNet support more than 3 channels input image?

### ISSUE THREAD

**Issue by irimsky** [huggingface/diffusers#4072]
Now the controlnet only take image(tensor) with 3 channels as input conditioning image.

If I want to use a tensor with **more than 3 channels** as the conditioning image,  is there any solution?

**Comment by xiankgx** [comment]
In theory you can do this by modifying ControlNet yourself.

**Comment by andreemic** [comment]
Yeah you would have to modify these UNet blocks by adding an extra input channel. Wherever the weights get loaded from a pre-trained checkpoint you'd have to make sure the existing channels get assigned your pre-trained weights and the new channel is initialised randomly.

<img width="672" alt="Screenshot 2023-07-16 at 13 51 07" src="https://github.com/huggingface/diffusers/assets/27695722/5da91e71-c654-4a4b-a2da-0e14a9de7762">

I'm not sure where the config would have to be changed in Diffusers but somewhere is going to be defined how many input channels these blocks have. You have to change that.

**Comment by andreemic** [comment]
Well and of course train the controlnet part to adapt to learn incorporating your newly added channel.
