### ISSUE TITLE
`'Tensor' object has no attribute 'astype'` when running DeepFloyd IF safety checker

### ISSUE THREAD

**Issue by ifsheldon** [huggingface/diffusers#4073]
### Describe the bug

I guess someone has made a mistake on data types. When I run the example code of DeepFloyd IF, I got `'Tensor' object has no attribute 'astype' `

And I digged into the code a bit. The error comes from 

https://github.com/huggingface/diffusers/blob/92a57a8e84a98a4da87b6a0621615eed4a23edc4/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py#L206

which was copied from 

https://github.com/huggingface/diffusers/blob/92a57a8e84a98a4da87b6a0621615eed4a23edc4/src/diffusers/pipelines/deepfloyd_if/pipeline_if.py#L397

When I added a breakpoint and check the datatype, it was indeed a `Tensor`, not a `numpy.ndarray`.

### Reproduction

The example code is from https://github.com/deep-floyd/IF/blob/develop/README.md#example  and I just copied it, comment out `enable_xformers_memory_efficient_attention` and tried to run it on my machine.

Just FYI the code is 
```

from diffusers import DiffusionPipeline
from diffusers.utils import pt_to_pil
import torch

# stage 1
stage_1 = DiffusionPipeline.from_pretrained("DeepFloyd/IF-I-XL-v1.0", variant="fp16", torch_dtype=torch.float16)
#stage_1.enable_xformers_memory_efficient_attention()  # remove line if torch.__version__ >= 2.0.0
stage_1.enable_model_cpu_offload()

# stage 2
stage_2 = DiffusionPipeline.from_pretrained(
    "DeepFloyd/IF-II-L-v1.0", text_encoder=None, variant="fp16", torch_dtype=torch.float16
)
#stage_2.enable_xformers_memory_efficient_attention()  # remove line if torch.__version__ >= 2.0.0
stage_2.enable_model_cpu_offload()

# stage 3
safety_modules = {"feature_extractor": stage_1.feature_extractor, "safety_checker": stage_1.safety_checker, "watermarker": stage_1.watermarker}
stage_3 = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-x4-upscaler", **safety_modules, torch_dtype=torch.float16)
#stage_3.enable_xformers_memory_efficient_attention()  # remove line if torch.__version__ >= 2.0.0
stage_3.enable_model_cpu_offload()

prompt = 'a photo of a kangaroo wearing an orange hoodie and blue sunglasses standing in front of the eiffel tower holding a sign that says "very deep learning"'

# text embeds
prompt_embeds, negative_embeds = stage_1.encode_prompt(prompt)

generator = torch.manual_seed(0)

# stage 1
image = stage_1(prompt_embeds=prompt_embeds, negative_prompt_embeds=negative_embeds, generator=generator, output_type="pt").images
pt_to_pil(image)[0].save("./if_stage_I.png")

# stage 2
image = stage_2(
    image=image, prompt_embeds=prompt_embeds, negative_prompt_embeds=negative_embeds, generator=generator, output_type="pt"
).images
pt_to_pil(image)[0].save("./if_stage_II.png")

# stage 3
image = stage_3(prompt=prompt, image=image, generator=generator, noise_level=100).images
image[0].save("./if_stage_III.png")

```

### Logs

```shell
Traceback (most recent call last):
  File "/home/ai/code/DeepfloydIF/main1.py", line 43, in <module>
    image = stage_3(prompt=prompt, image=image, generator=generator, noise_level=100).images
  File "/home/ai/mambaforge/envs/deepfloyd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ai/mambaforge/envs/deepfloyd/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py", line 769, in __call__
    image, has_nsfw_concept, _ = self.run_safety_checker(image, device, prompt_embeds.dtype)
  File "/home/ai/mambaforge/envs/deepfloyd/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py", line 208, in run_safety_checker
    safety_checker_input = self.feature_extractor(self.numpy_to_pil(image), return_tensors="pt").to(device)
  File "/home/ai/mambaforge/envs/deepfloyd/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1379, in numpy_to_pil
    return numpy_to_pil(images)
  File "/home/ai/mambaforge/envs/deepfloyd/lib/python3.10/site-packages/diffusers/utils/pil_utils.py", line 41, in numpy_to_pil
    images = (images * 255).round().astype("uint8")
AttributeError: 'Tensor' object has no attribute 'astype'. Did you mean: 'dtype'?
```
```


### System Info

```
Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.18.1
- Platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1 (True)
- Huggingface_hub version: 0.16.2
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: 0.0.20
- Using GPU in script?: 4090
- Using distributed or parallel set-up in script?: <fill in>

```

### Who can help?

@patrickvonplaten I saw the commits were from you. Probably you can test it again?

**Comment by patrickvonplaten** [comment]
@yiyixuxu can you take a look here?

**Comment by yingjie-han** [comment]
I got the same error.
Enviroment：
diffusers version: 0.20.0
Platform: Linux-5.4.0-128-generic-x86_64-with-glibc2.35
Python version: 3.8.16
PyTorch version (GPU?): 2.0.0 (False)
Huggingface_hub version: 0.14.1
Transformers version: 4.30.2
Accelerate version: 0.19.0
xFormers version: No
Using GPU in script?: No
Using distributed or parallel set-up in script?: No

**Comment by patrickvonplaten** [comment]
Gently pinging @yiyixuxu again

**Comment by yiyixuxu** [comment]
@yingjie-han @ifsheldon 

Thanks for reporting the bug - it is an important one! sorry it took so long to fix, I somehow missed this issue
let me know if this works for you https://github.com/huggingface/diffusers/pull/4886
