### ISSUE TITLE
Minor error in the docstring of `ShapEImg2ImgPipeline`

### ISSUE THREAD

**Issue by hysts** [huggingface/diffusers#4075]
The first argument of `__call__` is `image`, not `prompt` here.
https://github.com/huggingface/diffusers/blob/92a57a8e84a98a4da87b6a0621615eed4a23edc4/src/diffusers/pipelines/shap_e/pipeline_shap_e_img2img.py#L217-L218

**Comment by stevhliu** [comment]
Thanks for catching this, it'll be fixed in #3905!
