### ISSUE TITLE
"NameError: name 'init_empty_weights' is not defined" when accelerate is not installed

### ISSUE THREAD

**Issue by cstueckrath** [huggingface/diffusers#4077]
https://github.com/huggingface/diffusers/blame/92a57a8e84a98a4da87b6a0621615eed4a23edc4/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L1344

`init_empty_weights()` is imported from accelerate if is_accelerate_available() returns true. However if that's not the case there is no fallback.
We had to pin diffusers to 0.18.1 in https://github.com/nod-ai/SHARK/pull/1648

**Comment by patrickvonplaten** [comment]
Can you install accelerate - we more or less enforce it now with this PR: https://github.com/huggingface/diffusers/pull/4078

Think accelerate is very lightweight so it shouldn't really create a problem no?

**Comment by cstueckrath** [comment]
I see. Shouldn't this be then set as a dependency for pip installs of Diffusers?

**Comment by patrickvonplaten** [comment]
We would do this if we wouldn't support FLAX but with when running diffusers on FLAX one really doesn't need accelerate
