### ISSUE TITLE
Add in-painting pipeline for Stable Diffusion XL

### ISSUE THREAD

**Issue by DaveFerBear** [huggingface/diffusers#4080]
**Is your feature request related to a problem? Please describe.**
SDXL is awesome- is there a plan to add an in-painting pipeline?

**Describe the solution you'd like**
There are several pipes in the stable diffusion repo for SD 1.5 and 2.1:
- `StableDiffusionPipeline`
- `StableDiffusionImg2ImgPipeline`
- `StableDiffusionInpaintPipeline`
- `StableDiffusionInstructPix2PixPipeline`
- etc.

However for SDXL, there are only:
- `StableDiffusionXLPipeline`
- `StableDiffusionXLImg2ImgPipeline`

I'd love a `StableDiffusionXLInpaintPipeline` or `StableDiffusionXLInpaintPipelineLegacy`.

**Describe alternatives you've considered**
Would otherwise write my own, but wondering if any community members are already working on this.

**Additional context**
n/a

**Comment by AmericanPresidentJimmyCarter** [comment]
Related: #4064 describes a universal inpainting method for latent diffusion modules which should give superior results to the original hacky inpainting implementations from CompVis (pre-RunwayML models).

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/pull/4098

**Comment by sayakpaul** [comment]
Closing the issue with #4098.
