### ISSUE TITLE
Example script for training a lora for the SDXL refiner

### ISSUE THREAD

**Issue by BitPhinix** [huggingface/diffusers#4085]
It would be neat to extend the SDXL dreambooth Lora script with an example of how to train the refiner. Just training the base model isn't feasible for accurately generating images of subjects such as people, animals, etc.

**Comment by AmericanPresidentJimmyCarter** [comment]
It should just be a CLI arg on the normal training script that lets you select to which timesteps you would like to train. The refiner model is trained on low noise timesteps 0 to 200.

**Comment by sayakpaul** [comment]
Feel free to raise a PR :)

More than happy to help.
