### ISSUE TITLE
During multi-gpus training, each card will execute the cache text embedding operation once?

### ISSUE THREAD

**Issue by pixeli99** [huggingface/diffusers#4089]
```python
text_encoders = [text_encoder_one, text_encoder_two]
tokenizers = [tokenizer_one, tokenizer_two]
train_dataset = get_train_dataset(args, accelerator)
compute_embeddings_fn = functools.partial(
    compute_embeddings,
    text_encoders=text_encoders,
    tokenizers=tokenizers,
    proportion_empty_prompts=args.proportion_empty_prompts,
)
with accelerator.main_process_first():
    train_dataset = train_dataset.map(compute_embeddings_fn, batched=True)
```

Each card will execute the above code during training, which will occupy too much disk space. Is this unreasonable? Or is it possible that I have misunderstood because currently, a fill50k training requires 15*8GB of storage space when using 8 cards.

**Comment by patrickvonplaten** [comment]
cc @williamberman

**Comment by williamberman** [comment]
Sorry, I'm not sure which training script this code is in? @pixeli99

**Comment by pixeli99** [comment]
> Sorry, I'm not sure which training script this code is in? @pixeli99

hi,
Sorry for my late reply. You can take a look here
https://github.com/huggingface/diffusers/blob/3eb498e7b4868bca7460d41cda52d33c3ede5502/examples/controlnet/train_controlnet_sdxl.py#L995

My question is whether this code can be selectively executed. If I have to cache these embeddings, it will consume approximately 1TB of my hard drive space, and my dataset size is 500K.

Whether this consumption is normal, and I find that it seems that every GPU will execute this cache, which is very strange. Of course, it may be that I understand it incorrectly

**Comment by williamberman** [comment]
Ah yes understood, unfortunately I as well am not really familiar with the semantics here of what datasets and accelerate are actually doing here. See some of my questions here https://github.com/huggingface/diffusers/pull/4038#discussion_r1266078401

@sayakpaul probably understands better

**Comment by pixeli99** [comment]
![image](https://github.com/huggingface/diffusers/assets/46072190/e1ef1fff-e760-4f2d-8da3-a45b1564386c)
Yes, it seems that every card will perform cache operations. Did I misunderstand?

**Comment by sayakpaul** [comment]
There's an answer here by @lhoestq: https://github.com/huggingface/diffusers/pull/4038#discussion_r1269295048

Also ccing @muellerzr for additional insights in case.

**Comment by williamberman** [comment]
Ah yes, super helpful @pixeli99 ! So @sayakpaul I believe if you follow up on my comment here https://github.com/huggingface/diffusers/pull/4038#discussion_r1269710936 it should fix this. It looks like it's re doing the same computation on all processes and re-caching the results. Manually telling datasets a hash key will fix this :)
