### ISSUE TITLE
AttributeError: 'StableDiffusionPipeline' object has no attribute 'enable_attention_slicing'

### ISSUE THREAD

**Issue by kritonpc** [huggingface/diffusers#409]
### Describe the bug

I'm getting the error ```AttributeError: 'StableDiffusionPipeline' object has no attribute 'enable_attention_slicing'``` Without it I can use stable diffusion properly, but I'm trying to save space, as it uses all 10gb off my 3080 

### Reproduction

```
# make sure you're logged in with `huggingface-cli login`
from torch import autocast
from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4", 
    revision="fp16", 
    torch_dtype=torch.float16,
    use_auth_token=True
)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
pipe.enable_attention_slicing()
with autocast("cuda"):
    image = pipe(prompt).images[0]  
```

### Logs

```shell
Traceback (most recent call last):
  File "c:/Users/Mr.Gamio/Programming/AIPicGen/Tests/testSingle.py", line 24, in <module>
    pipe.enable_attention_slicing()
AttributeError: 'StableDiffusionPipeline' object has no attribute 'enable_attention_slicing'
```

### System Info

I actually get the error 
```
Traceback (most recent call last):
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mr.gamio\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mr.Gamio\AppData\Local\Programs\Python\Python37\Scripts\diffusers-cli.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'diffusers.commands'
``` 
when calling diffusers-cli env
I am on windows 10 with an nvidia 3080 with the latest version of diffusers

**Comment by deepdiffuser** [comment]
This feature hasn't been released yet. In the mean time, you can install the latest main thru pip:

`pip install git+https://github.com/huggingface/diffusers.git@main`

**Comment by patrickvonplaten** [comment]
Now also:

```
pip install diffusers --upgrade
```

which should give you `0.3.0` which has `enable_attention_slicing` :-)

**Comment by pcuenca** [comment]
Closing this snow. @kritonpc please, reopen if it wasn't resolved :)

**Comment by wangm-word** [comment]
I have a similar question    AttributeError: 'StableDiffusionPipeline' object has no attribute 'parameters'     diffusers 0.15.0  can you help me solve it?

**Comment by posravishtasp** [comment]
Guys I a mvery new to SD, recently started SD.Next, now getting this error:
AttributeError: 'StableDiffusionPipeline' object has no attribute 'upcast_vae'
PLEASEEEEEEEEE help. Thank you
