### ISSUE TITLE
SDXL LoRA script adds strange noise/reduces quality of base model

### ISSUE THREAD

**Issue by killah-t-cell** [huggingface/diffusers#4107]
### Describe the bug

I spent the day training LoRAs for SDXL with the diffusers script and observed something odd. No matter how little or how much I train a LoRA, adding it to the base model adds significant noise and reduces its quality. 

This is the output with a LoRA weight 1
<img width="942" alt="Screenshot 2023-07-14 at 6 12 04 PM" src="https://github.com/huggingface/diffusers/assets/26853713/241aba1e-9f8c-47d7-8882-4100e27c75e5">

This is the output with LoRA weight 0.1 
<img width="1003" alt="Screenshot 2023-07-14 at 6 19 27 PM" src="https://github.com/huggingface/diffusers/assets/26853713/8b8c7518-5a7b-4eca-aa7f-dcdd948fa60f">

And this is without any LoRA
<img width="1005" alt="Screenshot 2023-07-14 at 6 11 50 PM" src="https://github.com/huggingface/diffusers/assets/26853713/e2b32c11-4132-4945-a940-458876dfdebd">

To the best of my understanding, this is NOT an overbaked LoRA. This phenomenon can be observed even at very low training steps (50) and only starts to get worst around 800 steps (when the LoRA is – in fact – overbaked).

I am not sure why this happens but critically, this does not happen when I play with the kohya script. 

<img width="1021" alt="Screenshot 2023-07-14 at 6 17 02 PM" src="https://github.com/huggingface/diffusers/assets/26853713/673d76fb-d2a7-4adc-a55b-354038e89baf">

### Reproduction

Here is the training script

```
#!/bin/bash

export MODEL_NAME="stabilityai/stable-diffusion-xl-base-0.9"
export INSTANCE_DIR="data"
export OUTPUT_DIR="lora-trained-xl"

accelerate launch train_dreambooth_lora_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --mixed_precision="bf16" \
  --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
  --instance_prompt="a photo of jsxm female person" \
  --resolution=1024 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --learning_rate=1e-4 \
  --report_to="wandb" \
  --lr_scheduler="cosine_with_restarts" \
  --lr_warmup_steps=0 \
  --max_train_steps=650 \
  --validation_prompt="a photo of jsxm female person in a flowery dress" \
  --validation_epochs=15 \
  --seed="0" \
  --push_to_hub \
  --train_text_encoder \
  --checkpointing_steps=100 \
```

I can also send the dataset by request (23 1024x1024 jpg images). Also happy to provide wandb access with a bunch of examples (just don't want to share publicly).

### System Info

diffusers sdxl lora script

### Who can help?

@sayakpaul @patr

**Comment by sayakpaul** [comment]
Thanks for reporting! A couple of questions:

* Does this problem persist when you send the LoRA outputs to the Refiner? Does the quality improve with that? 
* Does this problem persist when using prior preservation? 
* Does this problem persist when training the text encoders as well? 
* In the Kohya script, are you also targeting non-attention blocks for LoRA fine-tuning? 

Would be cool to do a collective effort to investigate the issues :-)

**Comment by BitPhinix** [comment]
I am experiencing the same issue!

- Does this problem persist when you send the LoRA outputs to the Refiner? Does the quality improve with that?
   - The quality definitely improves but is still far away from the non-Lora version + using the refiner (non-finetuned) is not feasible anyway because it losses subject fidelity
- Does this problem persist when using prior preservation?
  - Haven't tested that yet. I will try and report back, but I am not using it for Kohya either so I don't think it'll make a huge difference (especially because these issues occur even with a fairly untrained Lora)
- Does this problem persist when training the text encoders as well?
  - Yes, it makes almost no difference.
- In the Kohya script, are you also targeting non-attention blocks for LoRA fine-tuning?
  - No, I'm using "vanilla" loras

**Comment by sayakpaul** [comment]
Cool, thanks for providing further insights! 

Could we ensure the Kohya version uses the same LoRA rank? 

Another issue could be stemming from the use of SDPA in the LoRA attention processor. Could you see if disabling that leads to any improvements? 

Could I also have some results of loading randomly initialised LoRA into the pipeline?

At the moment, I am unable to think of a reason for the artifacts to pop up. So, appreciate any help :-)

**Comment by killah-t-cell** [comment]
- even at the same rank it persists
- I could not, unfortunately try without the SDPA because my GPU ran out of memory

I'll keep playing with it, here's also a [wandb](https://wandb.ai//canofsoup/dreambooth-lora-sd-xl/reports/validation-23-07-16-23-03-36---Vmlldzo0ODk2MTQ3?accessToken=c8hlrgjc8npztin8aga3ww7m234ml0xr6z345b0rtmvgfm8k9jn089867j14a75n) result for reference. You can observe the LoRA would be great if it weren't for the patchy noise it generates.

**Comment by sayakpaul** [comment]
Thanks!

Hmm, maybe the strength of the noise added during training -- that needs to be adjusted. But really, what is interesting is, you don't get these noisy artifacts when training with Kohya with an apparently identical setup. 

Maybe there's a tiny bit of internal differences we're missing out on here but hard to know :(

**Comment by patrickvonplaten** [comment]
@killah-t-cell can you maybe also provide a reproducible code snippet / setup of the koyho ss setup?

**Comment by killah-t-cell** [comment]
Ok so I used a configuration that approximates diffusers with the dog example and generated an image for each epoch. 

Here's the config_file.toml you can plug into the [kohya notebook](https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-trainer-XL.ipynb)

```
[sdxl_arguments]
cache_text_encoder_outputs = true
no_half_vae = true
min_timestep = 0
max_timestep = 1000
shuffle_caption = false

[model_arguments]
pretrained_model_name_or_path = "/content/pretrained_model/sd_xl_base_0.9.safetensors"
vae = "/content/vae/sdxl_vae.safetensors"

[dataset_arguments]
debug_dataset = false
in_json = "/content/LoRA/meta_lat.json"
train_data_dir = "/content/LoRA/dog"
dataset_repeats = 1
keep_tokens = 0
resolution = "1024,1024"
color_aug = false
token_warmup_min = 1
token_warmup_step = 0

[training_arguments]
output_dir = "/content/drive/MyDrive/kohya-trainer/output"
output_name = "sdxl_lora"
save_precision = "fp16"
save_every_n_epochs = 1
train_batch_size = 1
max_token_length = 225
mem_eff_attn = false
sdpa = true
xformers = false
max_train_epochs = 100
max_data_loader_n_workers = 8
persistent_data_loader_workers = true
gradient_checkpointing = true
gradient_accumulation_steps = 1
mixed_precision = "fp16"

[logging_arguments]
log_with = "tensorboard"
logging_dir = "/content/LoRA/logs"
log_prefix = "sdxl_lora"

[sample_prompt_arguments]
sample_every_n_epochs = 1
sample_sampler = "euler_a"

[saving_arguments]
save_model_as = "safetensors"

[optimizer_arguments]
optimizer_type = "AdaFactor"
learning_rate = 1e-4
max_grad_norm = 0
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False",]
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = 100

[additional_network_arguments]
no_metadata = false
network_module = "networks.lora"
network_dim = 32
network_alpha = 16
network_args = [ "conv_dim=32", "conv_alpha=16",]
network_train_unet_only = true
```

This is still running (I'll update as it runs, but you can see that at 100 steps diffusers introduces some noise compared to pure XL-base while kohya does not)

(diffusers)
![image](https://github.com/huggingface/diffusers/assets/26853713/f655854c-c9cb-4f39-932a-c58704f6c416)

(kohya)
<img width="1022" alt="Screenshot 2023-07-17 at 10 54 12 AM" src="https://github.com/huggingface/diffusers/assets/26853713/9ab84262-89ba-45cd-9387-478aeba6fcb3">

**Comment by killah-t-cell** [comment]
(for full disclosure I do think the kohya script on average trains "worse". That is, it takes longer to capture the subject. Diffusers really captures the subject every time but it's just so noisy / degraded that I can't use it)

**Comment by sayakpaul** [comment]
@killah-t-cell from what I can see it's actually not the same as what we have in SDXL (at least with which you got the noisy results). 

* We don't have support for LoRA fine-tuning conv layers (from `network_args = [ "conv_dim=32", "conv_alpha=16",]`). 
* Network alpha and LoRA rank dimensions also vary from the standard setting we have in diffusers. 
* Also not sure if `max_token_length = 225` has an effect here. 

So, maybe those differences are introducing the noise which could probably be mitigated with a bit of hyperparameter tuning.

**Comment by sayakpaul** [comment]
Yeah until and unless there's a closer reproduction, it's really hard for us to pinpoint what is really going on. 

I am also assuming Kohya style LoRA initialise the LoRA params the same way we do in diffusers. I would also, like to ensure it the scheduler settings during training are exactly identical as the effects of noise on SDXL seem to be more sensitive. 

I have gone through our source code (LoRA, training script) a couple times today to look for potential suspects but couldn't find one. If you have further ideas for us to look into, happy to do so.

**Comment by sayakpaul** [comment]
@killah-t-cell an interesting finding [here](https://wandb.ai/sayakpaul/dreambooth-lora-sd-xl/runs/o54i6ees): 

If you see this run page on Weights and Biases, you will notice a difference:

<img width="1607" alt="image" src="https://github.com/huggingface/diffusers/assets/22957388/1c96cce7-4090-4234-9dff-9e88f2bc9434">

The "validation" inference examples don't seem to have the noise. So, I am wondering what discrepancy we're introducing during the serialization. I will investigate this. But meanwhile if you have any idea, let me know.

**Comment by patrickvonplaten** [comment]
Could it be related to the watermarker?

**Comment by samedii** [comment]
Seeing bad results with textual inversion in case it might be related

**Comment by patrickvonplaten** [comment]
I don't think we have worked on a textual inversion training script no?

**Comment by samedii** [comment]
You're right. I put something together myself but I'm having similar issues. Has worked well with previous versions of SD though

Thought I might mention it in case it helps narrow down where the issue is

**Comment by bghira** [comment]
are you perhaps running batched outputs?
