### ISSUE TITLE
StableDiffusionXLImg2ImgPipeline: Unable to load with 16GB VRAM

### ISSUE THREAD

**Issue by PtrMan** [huggingface/diffusers#4111]
### Describe the bug

Loading StableDiffusionXLImg2ImgPipeline on 16GB VRAM A4000 hardware isn't possible anymore.

This runs out of memory with the latest master, it loaded in the past without low_cpu_mem_usage=True ,  which also doesn't work now.

    pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(model_id_or_path, torch_dtype=torch.float16,    low_cpu_mem_usage=True)

loading and using the non-imageToImage pipeline DOES work.

I already tried

    export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256'

no success

### Reproduction

see above

### System Info

latest git master

**Comment by patrickvonplaten** [comment]
Hey @PtrMan, sorry I cannot reproduce this. I can load it with just 12 GB

**Comment by PtrMan** [comment]
strange... this crashes given 16GB VRAM
    
    #  img2img 
    
    print('[d] load libs...')
    from diffusers import DiffusionPipeline
    import torch
    
    from commonA import *
    
    #import requests
    
    import torch
    
    from PIL import Image
    
    #from io import BytesIO
    
    from diffusers import StableDiffusionXLImg2ImgPipeline
    
    
    print('[d] ... done')
    
    device = "cuda"
    
    
    
    logger = LoggerA()
    logger.outFilepath = 'log imageToImage sdxl B0000.txt'
    
    for it in range(70):
    
    
        initImagePath = ""
        
        
        initImageA = Image.open(initImagePath)
        
        
        
        initImage = initImageA
        initImage = initImage.convert("RGB")
        
        currentImage = initImage
    
    
    
        model_id_or_path = "stabilityai/stable-diffusion-xl-base-0.9"
        #model_id_or_path = 'stabilityai/stable-diffusion-xl-refiner-0.9'
    
        #pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(model_id_or_path, torch_dtype=torch.float16,    low_cpu_mem_usage=True)
        pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(model_id_or_path, torch_dtype=torch.float16, use_safetensors=True, variant="fp16",    low_cpu_mem_usage=True)
    
        # see https://stable-diffusion-art.com/samplers/
        from diffusers.schedulers import UniPCMultistepScheduler
        pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
    
        pipe.to("cuda")
    
        # if using torch < 2.0
        pipe.enable_xformers_memory_efficient_attention()
        
        #pipe.enable_model_cpu_offload()
    
    
    
    
        prompt = ''
        promptNeg = ''
        imageToImageStrength=0.9
        guidance=8.0
        
        
        numSteps=50
        
        
        
        #pipeOutput = pipe(prompt=prompt, negative_prompt=promptNeg, image=currentImage, num_inference_steps=numSteps, strength=imageToImageStrength, guidance_scale=8.0,  output_type="latent").images
        
        
        a, b, c, d = pipe.encode_prompt(prompt)  
        pipeOutput = pipe(prompt_embeds=a, pooled_prompt_embeds=c, negative_prompt=promptNeg, image=currentImage, num_inference_steps=numSteps, strength=imageToImageStrength, guidance_scale=8.0,  output_type="latent").images
    
    
        del pipe
    
        pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-refiner-0.9", torch_dtype=torch.float16, use_safetensors=True, variant="fp16",   low_cpu_mem_usage=True)
    
    
        # see https://stable-diffusion-art.com/samplers/
        from diffusers.schedulers import UniPCMultistepScheduler
        pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
    
    
        pipe.to("cuda")
    
        # if using torch < 2.0
        # pipe.enable_xformers_memory_efficient_attention()
        
        #pipe.enable_model_cpu_offload()
        
        
        images = pipe(prompt=prompt, negative_prompt=promptNeg, image=pipeOutput).images
        #a, b, c, d = pipe.encode_prompt(prompt)
        #images = pipe(prompt_embeds=a, pooled_prompt_embeds=c, negative_prompt=promptNeg, image=pipeOutput).images
        
        del pipe # hopefully unload from VRAM
    
        currentImage = images[0]
    
    
    
    
        import hashlib
        import time
        hash0 = hashlib.sha1((str(time.time())).encode("UTF-8")).hexdigest()
        outFilename = f'imageToImage MMM sdxl09 {hash0[:12]}.png'
        currentImage.save(outFilename)
    
        currentImage.show()
    
    
        logDat = {}
        logDat['promptPos'] = prompt
        logDat['promptNeg'] = promptNeg
        logDat['guidanceScale'] = guidance
        logDat['initImagePath'] = initImagePath
        logDat['imageToImageStrength'] = imageToImageStrength
        logDat['outFilename'] = outFilename
        logger.log(logDat)

**Comment by patrickvonplaten** [comment]
Can you try to replace:

```py
a, b, c, d = pipe.encode_prompt(prompt) 
```

with

```py
with torch.no_grad():
    a, b, c, d = pipe.encode_prompt(prompt) 
```

**Comment by PtrMan** [comment]
this worked, also I don't have the problem anymore. Thanks everyone. I guess it was a user error

**Comment by PtrMan** [comment]
Thanks for the tipp but it still doesn't work
