### ISSUE TITLE
StableDiffusionXLImg2ImgPipeline: passing embeddings did not work

### ISSUE THREAD

**Issue by PtrMan** [huggingface/diffusers#4116]
### Describe the bug

I retrieved the positive embeddings for a prompt with the method encode_prompt() to get the embeddings and passed it into the pipeline.

It did crash in some pipeline internals days ago.

Can't try it now because I only got access to 16GB machines and because of the other issue.

### Reproduction

see description

### System Info

0.19dev?

**Comment by patrickvonplaten** [comment]
No reproducible code snippet here, so we can't help really
