### ISSUE TITLE
'AutoencoderKL' has no attribute 'from_single_file'

### ISSUE THREAD

**Issue by zhaoyun0071** [huggingface/diffusers#4118]
### Describe the bug

now 0.18.2 many pipeline support from_single_file，very great work!
but I also found some modules not support.

for example ，I want to load a single file SD model  SD-1-5.safetensors，this is ok。
but I want load a VAE single safetensor too,but now not support it.

It now feels like a mixture of the two models：single model and diffusers model.

### Reproduction

from diffusers import AutoencoderKL

vae = AutoencoderKL.from_single_file(
".\vae-ft-mse-840000-ema-pruned.safetensors").cuda()

### System Info

0.18.2 diffusers

### Who can help?

:@patrickvonplaten, @sayakpaul, and @williamberman

**Comment by sayakpaul** [comment]
Hi. 

We don't have `from_single_file()` utility on a model-level.

**Comment by zhaoyun0071** [comment]
> Working on it here: https://github.com/huggingface/diffusers/pull/4084

perfect work, i test diffusers-0.19.0.dev0

ControlNetModel.from_single_file
AutoencoderKL.from_single_file
StableDiffusionControlNetPipeline.from_single_file
StableDiffusionControlNetImg2ImgPipeline.from_single_file
all work!!!

now I look forward Loading multiple Lora models with different proportions
