### ISSUE TITLE
Does SD 2.1 config need update?

### ISSUE THREAD

**Issue by Alexander-Jin** [huggingface/diffusers#4127]
Hi, I am testing SD2.1 and find the generation has some problems.

I initialize each component, unet/vae/text encoder from config and model checkpoint(not fp16, not safe tensor) from each folder in SD2.1 model hub. I need to do a little name change in vae state_checkpoint (key to to_k, value to to_v, etc). Then the generation quality is poor (with fb16/fp16/fp32). It worked before.

 I personally trained some models with different settings with SD GitHub repo and do checkpoint transform. That checkpoint works though.

So I think maybe some default setting in unet codes causes this problem, and the old configs from SD 2.1 does not cover some setting currently used. How can I debug this? Thanks

seudo codes:
load json config
unet = unet(**config)
unet.load_state_dict(state_dict).

This is how I loaded unet.

With the latest version of diffusers. PyTorch is also the latest version.

**Comment by killah-t-cell** [comment]
can you share some example outputs?

**Comment by patrickvonplaten** [comment]
Please provide a reproducible code snippet here :-)
