### ISSUE TITLE
About SDXL ControlNet

### ISSUE THREAD

**Issue by pixeli99** [huggingface/diffusers#4129]
Hello, it seems that wandb is recording all black images. Can you confirm if it's working properly on your end during development? I have also printed the pixel values of the val image, and they are all 0.

![image](https://github.com/huggingface/diffusers/assets/46072190/79adbd58-1749-4f9c-b9be-5243f71ffa9d)

Commit id is: 156dd27e48e231a871ea864b439b49d19d03f6ab
![image](https://github.com/huggingface/diffusers/assets/46072190/141109f9-b486-433d-930d-100a908bf839)

**Comment by sayakpaul** [comment]
This is insufficient info. 

I don't know about:

* what dataset are you using. 
* what are the hyperparameters are you using. 

> Can you confirm if it's working properly on your end during development?

Refer to: https://github.com/huggingface/diffusers/pull/4038#issuecomment-1637333324

**Comment by pixeli99** [comment]
Sorry, I may not have explained clearly. I don't want to trouble you to reproduce this issue for me. I just want to confirm if you can display the image normally during the testing process. If so, then it is an issue with my data and I will debug it myself :)

```python
 --pretrained_model_name_or_path=$MODEL_DIR \
 --output_dir=$OUTPUT_DIR \
 --train_data_dir=/18940970966/diffusion_re/laion2b \
 --resolution=1024 \
 --learning_rate=1e-5 \
 --validation_image "processed_sa_10746077_cropped.PNG" "processed_1280X1280.PNG"\
 --validation_prompt "a big house, 8k" "a car running on the road, 8k" \
 --train_batch_size=4 \
 --gradient_accumulation_steps=2 \
 --mixed_precision fp16 \
 --validation_steps 100 \
 --checkpointing_steps 500 \
 --max_train_steps 10000
```

**Comment by sayakpaul** [comment]
Does this issue persist if you use the improved VAE as shown in https://github.com/huggingface/diffusers/pull/4038#issuecomment-1637333324?

**Comment by pixeli99** [comment]
In that case, can I understand it as long as I turn off mixed precision training, this problem will not occur? Because I also saw friends in the PR reacting to similar situations.

**Comment by sayakpaul** [comment]
The original VAE might have instability issues in the FP16 mode which is why the recommendation to use the improved VAE that works reasonably well under FP16.

**Comment by pixeli99** [comment]
Thank you very much for your reply, my question has been resolved.

**Comment by sayakpaul** [comment]
No problem and we're happy to help always :)
