### ISSUE TITLE
What's the difference between DreamBooth Lora and Dreambooth?

### ISSUE THREAD

**Issue by MaxTran96** [huggingface/diffusers#4146]
I see there's a train_dreambooth.py and train_dreambooth_lora.py. What's the difference between them? i also see there's a train_dreambooth_lora_sdxl.py, when will there be a pure dreambooth version of sdxl? i.e train_dreambooth_sdxl.py. Another question is, is it possible to pass negative prompt into SDXL?

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
DreamBooth implements the full DreamBooth algorithm using Stable Diffusion. DreamBooth LoRA makes use of Low-Rank Approximation to make it possible to run DreamBooth on consumer GPUs as we're only training a handful of params here. 

If you read the README, these details will be clearer. 

As for a full DreamBooth version of SDXL, I don't think we will work on it yet as the memory constraints of SDXL is much higher. 

Yes, it's possible to pass negative prompts to SDXL.

**Comment by MaxTran96** [comment]
is there an example of how i can pass negative prompt to sdxl? the example on hugginface doesn't include that. Also should i be using the implementation from hugginface or this https://github.com/bmaltais/kohya_ss/blob/master/sdxl_train_network.py? I noticed they both use to train sdxl model but i wasn't sure whether i should use the official implementation or this repo.

**Comment by patrickvonplaten** [comment]
We recommend using Diffusers' official SDXL LoRA dreamboothing script: https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sdxl.py
