### ISSUE TITLE
SDXL model config error for inpainting

### ISSUE THREAD

**Issue by junhyoung-ew** [huggingface/diffusers#4148]
https://github.com/huggingface/diffusers/blob/ed2a3584ab2ee59676eb95c884ba2d7bb831f41d/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py#L643

hi, thank you for inpainting task.
I got error that "AttributeError: 'FrozenDict' object has no attribute 'force_upcast'".
I check sdxl model, but i didn't found vae.config.force_upcast
Can you guide me correctly?

**Comment by patrickvonplaten** [comment]
Hey @junhyoung-ew,

Can you add a reproducible code snippet please?

**Comment by junhyoung-ew** [comment]
I don't know `vae.config.force_upcast` that what is meaning.

so, i can't fix code.. :(
