### ISSUE TITLE
Support using different attention kwargs for different types of processors in one model.

### ISSUE THREAD

**Issue by eliphatfs** [huggingface/diffusers#4152]
**Is your feature request related to a problem? Please describe.**
Say you want to use CustomDiffusion for some layers, and LoRA for some others.
You want to pass a {'scale': 0.5} to LoRA.
Then the code goes:
```python
TypeError: __call__() got an unexpected keyword argument 'scale'
```

Because CustomDiffusion has no idea what this parameter will do.

**Describe the solution you'd like**
1. The easiest solution is to drop excess kwargs for implemented attention processors. The downside is that silent bugs may come up.
2. Perhaps implementing a flag to indicate whether excess kwargs are expected or not. Downside of this fix is that it looks a bit too ad-hoc.
3. Add support for attn kwargs that also specify the layers or attn-proc types affected. The downside is a bit complicated design and also is a lot of work, possibly need to modify every pipeline.

**Additional context**
I see a similar issue in this comment: https://github.com/huggingface/diffusers/pull/1639#issuecomment-1420734927
But it did not get enough attention.

**Comment by patrickvonplaten** [comment]
What exactly is CustomDiffusion? Could you add a reproducible code snippet? :-)

**Comment by patrickvonplaten** [comment]
Ah I see, I think we could indeed allow passing the `cross_attention_kwargs` to custom diffusion. @sayakpaul what do you think?

**Comment by sayakpaul** [comment]
Sure! I like the idea. 

Would you maybe like to open a PR? Happy to help.

**Comment by eliphatfs** [comment]
What solution would you prefer?

**Comment by sayakpaul** [comment]
Supporting a scale argument in the Custom Diffusion attention processor?

**Comment by eliphatfs** [comment]
Then say I want to mix LoRA with vanilla AttnProc;
Moreover, when new processors are added as new papers come up, we would need to update all attention processors if we introduce a new kwarg and I don't want to do that.

**Comment by sayakpaul** [comment]
How would you have approached it otherwise? Happy to discuss.

**Comment by eliphatfs** [comment]
I described three solutions that I thought of in my issue body; but none is perfect to me.

**Comment by sayakpaul** [comment]
Okay then we will keep it open for now.
