### ISSUE TITLE
the program gets stuck for a long tim when use from_single_file

### ISSUE THREAD

**Issue by hckj588ku** [huggingface/diffusers#4158]
### Describe the bug

In my project, users can choose their preferred model, so I need to switch frequently between StableDiffusionPipeline and StableDiffusionXlPipeline. Sometimes, when the program switches to StableDiffusionPipeline and then back to StableDiffusionXlPipeline, it gets stuck at the from_single_file step, and it may even be stuck for up to 10 minutes.

### Reproduction

`

    if "sdxl" in Config.model_path:
            pipeline = StableDiffusionXLPipeline.from_single_file(
                '/home/ai_draw/ai_draw_consume/preview_images/models/sdxl/sdxl.safetensors',
                torch_dtype=torch.float16,use_safetensors=True,
                variant='fp16')
            pipeline.to(DEVICE)
            # pipeline.unet = torch.compile(pipeline.unet, mode="reduce-overhead", fullgraph=True)
            # refiner.unet = torch.compile(refiner.unet, mode="reduce-overhead", fullgraph=True)
            pipeline.scheduler = DDIMScheduler.from_config(pipeline.scheduler.config)
            images = pipeline([prompts],
                              negative_prompt=[Config.negative_prompt],
                              num_images_per_prompt=len(seeds),
                              generator=generator,
                              width=Config.width,
                              height=Config.height,
                              guidance_scale=Config.scale,
                              num_inference_steps=Config.steps,
                              ).images
            refiner = StableDiffusionXLImg2ImgPipeline.from_pretrained(
                '/home/ai_draw/ai_draw_consume/preview_images/models/stable-diffusion-xl-refiner-0.9/',
                torch_dtype=torch.float16,
                variant='fp16')
            refiner.to(DEVICE)
            outputs = refiner([prompts],
                              negative_prompt=[Config.negative_prompt],
                              num_images_per_prompt=len(seeds),
                              generator=generator,
                              guidance_scale=Config.scale,
                              num_inference_steps=Config.steps,
                              image=images
                              ).images
        else:
            pipeline = StableDiffusionPipeline.from_pretrained(Config.model_path, torch_dtype=torch.float16)
            callback = sample_callback
            pipeline.unet.set_attn_processor(AttnProcessor2_0())
            if 'runFX' not in Config.model_path and 'rmada' not in Config.model_path and Config.lora_path:
                load_lora_weight(Config.lora_path, pipeline)
            pipeline.to(DEVICE)
            # text_encoder = CLIPTextModel.from_pretrained(Config.model_path,
            #                                              subfolder="text_encoder", num_hidden_layers=11,
            #                                              torch_dtype=torch.float16).to(DEVICE)
            # pipeline.text_encoder = text_encoder
            pipeline.scheduler = DDIMScheduler.from_config(pipeline.scheduler.config)
            outputs = pipeline([prompts],
                               negative_prompt=[Config.negative_prompt],
                               num_images_per_prompt=len(seeds),
                               generator=generator,
                               width=Config.width,
                               height=Config.height,
                               guidance_scale=Config.scale,
                               num_inference_steps=Config.steps,
                               callback=callback,
                               callback_steps=8,
                               ).images`

### System Info

A100 GPU

### Who can help?

@partic

**Comment by patrickvonplaten** [comment]
Hey @hckj588ku,

What version of `diffusers` are you using? Can you make sure to use at least `0.18.2` ?

**Comment by hckj588ku** [comment]
> Hey @hckj588ku,
> 
> What version of `diffusers` are you using? Can you make sure to use at least `0.18.2` ?

yes ,I’m sure my version is 0.18.2,

**Comment by patrickvonplaten** [comment]
Hmm weird, I have a hard time reproducing it. For me doing the following:
https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl#loading-single-file-checkpoints-original-file-format

takes no more than 2 seconds

**Comment by hckj588ku** [comment]
> 
I'm not sure why either. Could it be because I need to switch between models frequently?This situation sometimes occurs, but there is no pattern to it.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
i believe it is a disk transfer speed limit? and every time one 1st run of a new/changed model it needs to clear cache then load the newest model?so if the model is 2Gb and speed is 40Mb/s,you would need to wait a bit?
