### ISSUE TITLE
Ability to interrupt generate process

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#4165]
Ability to interrupt generate process

**Comment by patrickvonplaten** [comment]
This is related to https://github.com/huggingface/diffusers/issues/374

Maybe there is some kind of stopping criteria we could logic we could implement? 

cc @DN6

**Comment by vladmandic** [comment]
i think simple and sufficient approach is to have `interrupt` method that sets internal flag on a pipeline.
and its checked as a first thing inside scheduler loop and runs `continue` instead of current step.
that basically just skips all remaining steps and pipeline itself remains consistent.

for my use-case, if i want to skip any post-processing steps (vae decode, safetey checks, etc.) - that is simple, i use `output_type=latent` so they dont execute anyhow and i run those postprocessing steps explicitly.

**Comment by vladmandic** [comment]
Request is still valid/open.

**Comment by DN6** [comment]
Hi @vladmandic I have time to look into this week. Will draft up a proposal for it.

**Comment by TimothyAlexisVass** [comment]
Until then...
Is there currently a better way than something like this?
```
cancel_inference = False

def cancel():
    cancel_inference = True

def callback_function(step, timesteps, latents):
    if cancel_inference:
        raise Exception("Inference cancelled.")

images = pipe("Beauty", callback=callback_function).images
```

**Comment by patrickvonplaten** [comment]
> Hi @vladmandic I have time to look into this week. Will draft up a proposal for it.

Gentle ping here @DN6

**Comment by gabgren** [comment]
+1, would be very useful to gracefully stop the generation process in between steps :)

**Comment by patrickvonplaten** [comment]
Ping again @DN6

**Comment by DN6** [comment]
Hi @vladmandic I'm planning on circling back to this early next week.

**Comment by DN6** [comment]
@patrickvonplaten @vladmandic's Proposal to interrupt the generation process.    

Option 1: (@vladmandic's suggestion)
 
1. add an `interrupt` attribute to the pipeline

2. update callbacks to accept the pipeline
```python
callback(self, step_idx, t, latents)
``` 

And then inside the callback

```python
def callback(pipe, step_idx, t, latents):
    if should_stop:
        pipe.interrupt = True
```

3. Update denoising loop
```
for i, t in enumerate(timesteps):
      if self.interrupt:
          continue 
```

**Option 2**  

We could create a dedicated pipeline monitoring callback that raises an exception and we add a try/except to the denoising loop. 
```
try:
    # run denoising as usual

except PipelineGenerationAbort:
      logger.info("Aborted generation")
```

**Comment by TimothyAlexisVass** [comment]
Think that #5427 is related.
And possible to solve both these and all related issues with the option to pass _self_ to the callback.

**Comment by patrickvonplaten** [comment]
> @patrickvonplaten @vladmandic's Proposal to interrupt the generation process.
> 
> Option 1: (@vladmandic's suggestion)
> 
> 1. add an `interrupt` attribute to the pipeline
> 2. update callbacks to accept the pipeline
> 
> ```python
> callback(self, step_idx, t, latents)
> ```
> 
> And then inside the callback
> 
> ```python
> def callback(pipe, step_idx, t, latents):
>     if should_stop:
>         pipe.interrupt = True
> ```
> 
> 3. Update denoising loop
> 
> ```
> for i, t in enumerate(timesteps):
>       if self.interrupt:
>           continue 
> ```
> 
> **Option 2**
> 
> We could create a dedicated pipeline monitoring callback that raises an exception and we add a try/except to the denoising loop.
> 
> ```
> try:
>     # run denoising as usual
> 
> except PipelineGenerationAbort:
>       logger.info("Aborted generation")
> ```

I like the idea of adding an interrupt attribute to the pipeline!
