### ISSUE TITLE
different inpainting in stable diffusion and diffusers

### ISSUE THREAD

**Issue by Laidawang** [huggingface/diffusers#4168]
In stable diffusion we can use like original Stable Diffusion checkpoint. like realisticVisionV30_v30VAE.safetensors to do inpaint, but in diffusers's inpainting pipeline we must select corresponding inpainting model which means "realisticVisionV30_v30VAE-inpainting" to do the inpaint. Is there a way to use the original model for inpaint?

**Comment by patrickvonplaten** [comment]
You can also use the orginal model for inpaint. Both checkpoint types are supported here
