### ISSUE TITLE
Replace Command-Line Arguments with config.yaml Settings in train.py files

### ISSUE THREAD

**Issue by helpmeIamnewbie** [huggingface/diffusers#4169]
I'm trying to use SDXL Lora and Dreambooth to fine-tuning SDXL.
and, I feel uncomfortable when setting a lot of argparsers in terminal. 
so, I think use config.yaml file and just set this config.yaml file to argparser.
than, when training, py file will read this YAML file and set variables in it.
ex) 
#config.yaml
MODEL_NAME: "stabilityai/stable-diffusion-xl-base-0.9"
... etc

and add train_dreambooth_lora_sdxl.py to
```python
import yaml

def load_config(config_file):
    with open(config_file, "r") as file:
        config = yaml.safe_load(file)
    return config

 parser.add_argument("--config_file", type=str, default="config.yaml",
              help="Path to the config.yaml file.")

config = load_config(args.config_file)
pretrained_model_name_or_path = config.get("MODEL_NAME")
```

like this. Is there any reason that we should use argparsers, just ignore it.
Thank you once again for your hard work and dedication to maintaining this valuable open-source project. I look forward to your feedback on this.

**Comment by shauray8** [comment]
mentioning @patrickvonplatem here, maybe he can tell whether this would be a valuable addition to the project. If it is, I'd be more than happy to contribute and lend a hand in building it if @helpmeIamnewbie is okay with it.

**Comment by helpmeIamnewbie** [comment]
@shauray8 
after open this issue, I try to make it but got failed. instead, I make run.py files and success to adapt some of args in my project.
my run.py file is look like

```python
def quote_arg(arg):
    # Function to quote arguments with spaces
    return f'"{arg}"' if " " in arg else arg

def load_config(config_file):
    with open(config_file, "r") as file:
        config = yaml.safe_load(file)
    return config

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the training script with config.yaml settings.")
    parser.add_argument("config_file", type=str, help="Path to the config.yaml file.")
    args = parser.parse_args()

    # Load the configuration from the config.yaml file
    config = load_config(args.config_file)

    token = config["TOKEN_NAME"]
    class_name = config["CLASS_NAME"]
    
    # Prepare the command string
    command = "accelerate launch train.py"
    command += f" --pretrained_model_name_or_path={quote_arg(config['MODEL_NAME'])}"
    command += f" --pretrained_vae_model_name_or_path={quote_arg(config['PRETRAINED_VAE_MODEL_NAME_OR_PATH'])}"
    command += f" --instance_data_dir=/opt/ml/stable-diffusion-xl/data/tokens/{token}"
    command += f" --class_data_dir=/opt/ml/stable-diffusion-xl/data/generated/{class_name}"
    command += f" --output_dir=/opt/ml/stable-diffusion-xl/weights/{token}"
    if config["PUSH_TO_HUB"]:
        command += " --push_to_hub"
        command += f" --hub_model_id={config['HUB_MODEL_ID']}"
        etc..
        
    subprocess.run(command, shell=True)
```

like this. I think it is not very good code, so thanks a lot for your any advice or help.

**Comment by patrickvonplaten** [comment]
Interesting idea! @williamberman @sayakpaul @yiyixuxu wdyt?

**Comment by shauray8** [comment]
@helpmeIamnewbie All in all this is a good starting point I think, can have a bunch of refactors over time, one of which I can think of right now is 

```python

command = f"accelerate launch train.py \
               --pretrained_model_name_or_path={quote_arg(config['MODEL_NAME'])} \
               --pretrained_vae_model_name_or_path={quote_arg(config['PRETRAINED_VAE_MODEL_NAME_OR_PATH'])} \
               --instance_data_dir=/opt/ml/stable-diffusion-xl/data/tokens/{token} \
               --class_data_dir=/opt/ml/stable-diffusion-xl/data/generated/{class_name} \
               --output_dir=/opt/ml/stable-diffusion-xl/weights/{token} \
               --epochs={epochs} \
               --learning_rate={learning_rate}"

```
making it just a single super long f-string.

**Comment by sayakpaul** [comment]
I like configuration based parsing too. 

This is a good example of I would have gone about it
https://github.com/showlab/Tune-A-Video/blob/5803c255ba25538a63eb2b9fcab610550e03f66c/train_tuneavideo.py#L367

Currently, we don't have the cycles to do the refactoring but happy to accept and help in PRs if a design similar to the above is adopted.

**Comment by helpmeIamnewbie** [comment]
@shauray8 I think if I want change to configuration based parsing, I should use first method to design similar with 
https://github.com/showlab/Tune-A-Video/blob/5803c255ba25538a63eb2b9fcab610550e03f66c/train_tuneavideo.py#L367
and.. do I have to refactoring all-train.py files in diffusers to PR?

**Comment by shauray8** [comment]
if you want to adopt the new configuration-based parsing method, you will indeed need to refactor all the files to incorporate the changes.

**Comment by williamberman** [comment]
I think the omega conf which can override cli args is a good idea, let's avoid the f string interpolation :) idea. Happy to review a PR if someone puts it up :)

**Comment by helpmeIamnewbie** [comment]
oh, thanks. than I'll try it for train.py files in examples folder. but I think it takes quite a long time..
