### ISSUE TITLE
HyperDreamBooth Support

### ISSUE THREAD

**Issue by tronizx** [huggingface/diffusers#4170]
found and interesting paper from google [https://hyperdreambooth.github.io/](https://hyperdreambooth.github.io/), I think you all already know about that. but I think it will be great idea to introduce it in diffusers, if we start to work on this project, it only needs few images to train a simple few KB size model. and google again hadn't released any code yet! what do you think about this project??

**Comment by madstuntman11** [comment]
@tronizx please check this issue https://github.com/huggingface/diffusers/issues/4095
