### ISSUE TITLE
Incorrect render of Reference page from HF Diffusers home page

### ISSUE THREAD

**Issue by suvadityamuk** [huggingface/diffusers#4171]
### Describe the bug

On clicking the "Reference" button on the [Diffusers homepage](https://huggingface.co/docs/diffusers/index), I get the following text returned
![image](https://github.com/huggingface/diffusers/assets/70141886/8759a443-cf08-40f3-b4fc-fe870f1c39f0)

Not sure if this is intended.

### Reproduction

Referenced in "Describe the Bug", hope that helps!

### System Info

HF Diffusers Webpage

### Who can help?

@stevhliu

**Comment by stevhliu** [comment]
Thanks for reporting! I'll look into this and get back to you :)

**Comment by stevhliu** [comment]
Fixed!
