### ISSUE TITLE
from_single_file() always use gpu loading regardless of device=,torch_dtype=

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [huggingface/diffusers#4174]
### Describe the bug

1) from_single_file() always use gpu loading regardless of device=,torch_dtype=

2) (self mod diffusers caused this)when attempting to save modified result using image.save() it throws,AttributeError: 'Tensor' object has no attribute 'save'
i suspect the pipeline somehow doesnt return a image since diffusers 0.18

### Reproduction

from PIL import Image
import torch

import os
os.environ["HF_HUB_OFFLINE"] = "1"

gendevice="cpu"#possible val,"cpu","cuda","cuda:0","cuda:1"
desireorchdtype=None
if gendevice!="cpu":
    desireorchdtype=torch.float16#to save memory with small quality trade.
    
from diffusers import StableDiffusionInpaintPipeline
pipe = StableDiffusionInpaintPipeline.from_pretrained("saik0s/realistic_vision_inpainting", torch_dtype=desireorchdtype, safety_checker=None,requires_safety_checker=False,cache_dir="stbldiff")#,local_files_only=True
image = pipe(prompt="make the background green", image=Image.open("test.png"), mask_image=Image.open("mask.png"),negative_prompt="bad body",height=None,width=None,num_inference_steps=5).images[0]
image.save("moded.png")

### System Info

py 3.11,venv

### Who can help?

@patrickvonplaten, @sayakpaul

**Comment by patrickvonplaten** [comment]
Hey @cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw, 

I sadly cannot reproduce the error - the inpainting pipeline returns perfectly fine an image for me that can be saved

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
you are right the 2nd bug seems to be cause by the self modification i made.

do you happen to know how to solve the 1st bug?
I can only use cpu because my gpu is weak.
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.25 GiB already allocated

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
still the same it throws torch.cuda.OutOfMemoryError: CUDA out of memory when I am trying to load my model from_pretrained() so it never reaches > pipe.enable_model_cpu_offload() I did call torch.cuda.empty_cache() before loading but doesnt seems to solve the problem.

**Comment by sayakpaul** [comment]
Is it possible to share a Colab Notebook with us?

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
if possible preventing from_single_file() using gpu loading would be the best.unless we have a way to load the model into cpu but evl using gpu

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
i dont have experience with using collab but should be relatively possible to share the code.However I believe the main bottleneck is my hardware.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
It seems to worked with from_pretrained(model_id, torch_dtype=torch.float16)
and then pipe.enable_model_cpu_offload() as your suggestion.
In my side I can get it to work now.

I think it is a minor bug to not support cpu eval though.will keep this open until that is fixed.will edit tittle

**Comment by sayakpaul** [comment]
On CPU, I don't think it will ever be supported though.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
in case for reproducibility>
pipe = StableDiffusionInpaintPipeline.from_single_file(model_id, torch_dtype=torch.float16)
pipe.enable_model_cpu_offload()
pipe(prompt_embeds=embeddedprompt,image=image,.........)
