### ISSUE TITLE
Mandatory authentication for diffusers

### ISSUE THREAD

**Issue by giuliocn** [huggingface/diffusers#4176]
**Is your feature request related to a problem? Please describe.**
At the moment some HF diffusion models can be leveraged inside a notebook without mandatory authentication. The growing popularity of these models could increase the likelihood of potential misuse. In that case HF ethical guidelines would be violated:
> Responsibility: as a community and through teamwork, we hold a collective responsibility to our users by anticipating and mitigating this technology’s potential risks and dangers.

As noted below, some of the more powerful models do already require authentication such as  [stable-diffusion-xl-base-0.9](https://huggingface.co/stabilityai/stable-diffusion-xl-base-0.9), but I would like to add that other models might allow harmful content to be created without authentication by disabling the built-in security measures.

**Describe the solution you'd like**
A short term fix would be to add a mandatory authentication step for leveraging any diffusion model. 

**Describe alternatives you've considered**
A long term solution would require a longer list of goals to be accomplished:
1. Mandatory Authentication built-in
2. Link Users to Organizations, if any
3. Users should fill a specific and structured request for a model
4. Requests should be automatically evaluated.
5. Some requests might be reviewed by a human.
 
**Additional context**
Further context about this feature request will be added at a later time.

**Comment by patrickvonplaten** [comment]
Hey @giuliocn,

Thanks for the issue. Note that some of the more powerful models do already require authentication such as: https://huggingface.co/stabilityai/stable-diffusion-xl-base-0.9

**Comment by sayakpaul** [comment]
@giuliocn the authentication bit is also governed by the original licensing as imposed by the authors of a particular work. As @patrickvonplaten mentioned SDXL 0.9 currently requires you to authenticate and then only you'll be able to use the checkpoints. 

Could we close the issue here?
