### ISSUE TITLE
About the temperature parameter

### ISSUE THREAD

**Issue by suzukimain** [huggingface/diffusers#4184]
Is there a way to adjust the temperature parameter when generating images?

**Comment by patrickvonplaten** [comment]
What is the temperature parameter?

**Comment by suzukimain** [comment]
I’m sorry. The temperature parameter refers to the sampling temperature.

**Comment by suzukimain** [comment]
According to this page, sampling temperature has already been implemented in Stable Diffusion. Is there a way to change this value?
https://github.com/huggingface/diffusers/issues/2841#issue-1641778605

**Comment by alexblattner** [comment]
@suzukimain are you trying to use sonar? I literally did this last week :)

check my profile. It's  only usable for euler samplers though

**Comment by suzukimain** [comment]
@alexblattner Sorry. I don't know how to use it, so could you please explain in detail?

**Comment by alexblattner** [comment]
@suzukimain first you import either the euler or eulerA samplers from my repo, then you do your regular pipe stuff, then you add the samplers, then you write this:

pipe.scheduler.momentum= "the temperature you want, between -1 and 1"

**Comment by suzukimain** [comment]
@alexblattner  I tried to run the code in example.py, but what do I need to run it?
```python
from schedulers.EulerA import EulerA
```

**Comment by alexblattner** [comment]
https://github.com/alexblattner/modified-euler-samplers-for-sonar-diffusers

There's 2 important files here Euler.py and EulerA.py. Use one of them and import the class like the code you just wrote but without writing schedulers

**Comment by suzukimain** [comment]
Thank you very much. Resolved.
