### ISSUE TITLE
[Question] Maybe the sample code in Readme is outdated?

### ISSUE THREAD

**Issue by QIN2DIM** [huggingface/diffusers#419]
## Desc

Maybe the sample code in Readme is outdated? (🤦‍♂️Or my operation is faulty. I copied and ran multiple examples directly, all with similar errors`AttributeError: 'dict' object has no attribute 'images'`.

## Env

**python** v3.10
**diffusers** v0.2.4
**huggingface-hub** v0.9.1
**transformers** v4.21.3
**torch** v1.12.1+cu116
**scipy** v1.9.1

## Screenshot
![image](https://user-images.githubusercontent.com/62018067/189103666-552f77dc-52fc-47c7-addb-09dbb94ce5b6.png)

**Comment by QIN2DIM** [comment]
Maybe it's another situation ...
- https://github.com/huggingface/diffusers/blob/e54206d095b62f35b8e13cd9a4d86c016ae7c3d9/README.md

**Comment by minimaxir** [comment]
The README examples assume you are installing from GitHub `main` instead of PyPI.

**Comment by minimaxir** [comment]
`0.3.0` will likely be pushed soon. https://github.com/huggingface/diffusers/commit/3f55d1359fb7b93070d87c2afe9c453668249d45

**Comment by QIN2DIM** [comment]
yeah~ Thank you for your reply
