### ISSUE TITLE
So why is from_ckpt very different from from_pretrained with the arguments?

### ISSUE THREAD

**Issue by JemiloII** [huggingface/diffusers#4192]
More of a question to learn. But I've noticed that from_ckpt and from_pretrained is very different.

So I'm using the StableDiffusionPipeline for additional context.

from_ckpt
```
cache_dir = kwargs.pop("cache_dir", DIFFUSERS_CACHE)
resume_download = kwargs.pop("resume_download", False)
force_download = kwargs.pop("force_download", False)
proxies = kwargs.pop("proxies", None)
local_files_only = kwargs.pop("local_files_only", HF_HUB_OFFLINE)
use_auth_token = kwargs.pop("use_auth_token", None)
revision = kwargs.pop("revision", None)
extract_ema = kwargs.pop("extract_ema", False)
image_size = kwargs.pop("image_size", 512)
scheduler_type = kwargs.pop("scheduler_type", "pndm")
num_in_channels = kwargs.pop("num_in_channels", None)
upcast_attention = kwargs.pop("upcast_attention", None)
load_safety_checker = kwargs.pop("load_safety_checker", True)
prediction_type = kwargs.pop("prediction_type", None)
torch_dtype = kwargs.pop("torch_dtype", None)
use_safetensors = kwargs.pop("use_safetensors", None if is_safetensors_available() else False)
```

from_pretained
```
cache_dir = kwargs.pop("cache_dir", DIFFUSERS_CACHE)
resume_download = kwargs.pop("resume_download", False)
force_download = kwargs.pop("force_download", False)
proxies = kwargs.pop("proxies", None)
local_files_only = kwargs.pop("local_files_only", HF_HUB_OFFLINE)
use_auth_token = kwargs.pop("use_auth_token", None)
revision = kwargs.pop("revision", None)
from_flax = kwargs.pop("from_flax", False)
torch_dtype = kwargs.pop("torch_dtype", None)
custom_pipeline = kwargs.pop("custom_pipeline", None)
custom_revision = kwargs.pop("custom_revision", None)
provider = kwargs.pop("provider", None)
sess_options = kwargs.pop("sess_options", None)
device_map = kwargs.pop("device_map", None)
max_memory = kwargs.pop("max_memory", None)
offload_folder = kwargs.pop("offload_folder", None)
offload_state_dict = kwargs.pop("offload_state_dict", False)
low_cpu_mem_usage = kwargs.pop("low_cpu_mem_usage", _LOW_CPU_MEM_USAGE_DEFAULT)
variant = kwargs.pop("variant", None)
use_safetensors = kwargs.pop("use_safetensors", None if is_safetensors_available() else False)
```

Something else interesting is that from_ckpt required me to install `omegaconf` to use, and then when it ran, it seemed to download some 1.75GB model. What it was, no clue. Not really a fan of things automatically downloading, especially to some cache not in my project directory.

Also in, the from_pretrained method, it accepts 
```
safety_checker=None,
requires_safety_checker=False,
```

but from check_point does not and instead requires
```
load_safety_checker=False,
```

But the from_pretrained doesn't show some annoying warning message, while from_ckpt does. Really annoying because it auto-does this and just clogs up my terminal and logs.

I've also noticed that from_pretrained fails to load any safetensor file I give it, while from_ckpt just runs the safetensor file. I also noticed something interesting, haven't tried it yet, but why does from_ckpt have a controlnet input? So we can add controlnet by just using this? Will the pipe then accept the same inputs as StableDiffusionControlNetPipeline? Still not really sure how to understand the StableDiffusionControlNetPipeline inputs when it comes to generating an input because we have `image`, `control_image`, and `controlnet_conditioning_scale`. From my experience, `image` and `controlnet_conditioning_scale` are bound to be the same length / size if they are an array and are also bound to how many controlnets in use.

Thanks for any and all insights into my inquires.

**Comment by patrickvonplaten** [comment]
`from_pretrained(...)` is a global, very well-tested method that loads any diffusers models.
`from_ckpt` is deprecated in favor of `from_single_file`
`from_single_file` can be used for many SD-like pipeline as a convenience function to load checkpoints of their original format

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
it seemed to download some 1.75GB model.>refer,https://github.com/huggingface/diffusers/issues/3836

**Comment by JemiloII** [comment]
> **it seemed to download some 1.75GB model.**>refer,#3836

So that doesn't make sense since I point to a local safetensor file. I never use the repo/id format. I really, really dislike that format.



> `from_pretrained(...)` is a global, very well-tested method that loads any diffusers models. `from_ckpt` is deprecated in favor of `from_single_file` `from_single_file` can be used for many SD-like pipeline as a convenience function to load checkpoints of their original format

Appreciate the heads-up. feels weird to have these different methods. I guess I will stick to from_ckpt until I update.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
diffusers currenntly dont fully support native safetensor.or at least they need some extra modules to work properly?i suspect?
so it downloads clips model etc.. is what i wanted to tell you.^^

**Comment by patrickvonplaten** [comment]
Just to clarify what's going on here:

1.) Diffusers has supported `safetensors` since a long time (`safetensors` was created at Hugging Face). You can always load models in `diffusers` format with `use_safetensors=True` see: https://huggingface.co/docs/diffusers/main/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.from_pretrained.use_safetensors
=> this way you will ensure that diffusers weights are loaded in safetensors format

2.) Don't use `from_ckpt` => just use `from_single_file` if you want to load the original SD format

**Comment by JemiloII** [comment]
Just letting you know that safetensors do not work correctly in from_pretrained. I have only ever seen them work with from_ckpt/from_single_file.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
yeah that how they designed it. to be.

**Comment by Judy0406-CJ** [comment]
@patrickvonplaten Does `from_pretrained` have better performance than `from_single_file`? 
I have a local/single safetensors model file, considering if it is making sense to convert to the format that `from_pretrained` can load or just simply using `from_single_file`

**Comment by patrickvonplaten** [comment]
Hey @Judy0406-CJ,

That's probably a good question for https://github.com/huggingface/diffusers/discussions - do you mind posting it there?
