### ISSUE TITLE
Black result when using DDIM with rsbetazerosnr=True

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [huggingface/diffusers#4195]
### Describe the bug

it will return a few kb black image upon enabling rescale_betas_zero_snr in DDIM scheduler to generate image with StableDiffusionPipeline()

### Reproduction

#can try any stable diffusion example and add
pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config, rescale_betas_zero_snr=True, timestep_spacing=timestepspacing)

for example:
![out0_0](https://github.com/huggingface/diffusers/assets/122155102/7215a2c1-e898-4b7c-924b-3790771ea3d8)

### System Info

v0.18.2,py3.11

### Who can help?

@patrickvonplaten and @williamberman

**Comment by patrickvonplaten** [comment]
I cannot reproduce the problem

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
hm yeah weird seems to only be an issue if using safetensor model with from_single_file()

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
bump waiting for more time to retest if this issues still exist

**Comment by patrickvonplaten** [comment]
no reproducible code snippet means, we can't help you. Please be mindful of our time - we're reviewing 200 issues a day and every bump of an issue pings us.

**Comment by jloganolson** [comment]
I am also having this issue - to reproduce the black image: 
```
pipe = StableDiffusionXLPipeline.from_pretrained(SDXL_PATH)
pipe.scheduler = DDIMScheduler.from_config(
    pipe.scheduler.config, rescale_betas_zero_snr=True, timestep_spacing="trailing"
)
pipe.to("cuda")

prompt = "A lion in galaxies, spirals, nebulae, stars, smoke, iridescent, intricate detail, octane render, 8k"
pipe(prompt, guidance_rescale=0.7).images[0]
```
You also get this error: `diffusers/image_processor.py:65): RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")`

If you use the basic DDIM scheduler, the image is generated `pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)`

float16 and safetensors don't appear to affect it so left that out in reproduction but you can use this to reproduce as well:
`pipe = StableDiffusionXLPipeline.from_pretrained(SDXL_PATH,torch_dtype=torch.float16, variant="fp16", use_safetensors=True)`

**Comment by MaxxP0** [comment]
i also have this issue. but disabeling rbzsnr at inference solves it for me. I dont know if this comes at a loss in image quality tough

**Comment by patrickvonplaten** [comment]
See: https://github.com/huggingface/diffusers/issues/5103
