### ISSUE TITLE
Downloading real regularization images (Custom Diffusion Cat training example)

### ISSUE THREAD

**Issue by taeyeopl** [huggingface/diffusers#4199]
### Describe the bug

The provided scripts stop at 98% (196 / 200).

### Reproduction

pip install clip-retrieval
python retrieve.py --class_prompt cat --class_data_dir real_reg/samples_cat --num_class_images 200

### Logs

```shell
(custom) user@Puget-233195:/ssd1/workspace/diffusers/examples/custom_diffusion$  python retrieve.py --class_prompt "cat" --class_data_dir real_reg/samples_cat --num_class_images 200
/home/user/anaconda3/envs/custom/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
downloading real regularization images:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 196/200 [00:55<00:00,  5.66it/s]
```

### System Info

Python 3.8.5
diffusers '0.19.0.dev0'
Ubuntu 22.04.2 LTS

### Who can help?

@williamberman, @sayakpaul, @yiyixuxu

**Comment by sayakpaul** [comment]
It doesn't seem like a fault of the script but rather an installation problem. Cc @nupurkmr9

**Comment by nupurkmr9** [comment]
The `requests.get(images["url"])` in line 60 sometimes takes time which can be resolved by setting a timeout, i.e., `requests.get(images["url"],timeout=30)`. 
I will add the timeout arg to the next pull request as well. 
Thanks.

**Comment by sayakpaul** [comment]
Being worked out in: https://github.com/huggingface/diffusers/pull/4214/

**Comment by sayakpaul** [comment]
#4214 should have fixed the problem.
