### ISSUE TITLE
Add flash attention 2

### ISSUE THREAD

**Issue by adhikjoshi** [huggingface/diffusers#4200]
Flash attention 2 helps in faster speeds, here is birch labs implementation in diffusers

https://gist.github.com/Birch-san/4315701264b72bb72e8eac5a529ee93a

@patrickvonplaten

**Comment by sayakpaul** [comment]
Can we have some inference timing comparison of diffusers with

* SDPA
* xformers
* Flash attention 2?

**Comment by patrickvonplaten** [comment]
Very cool! I think we should support as soon as it's in `xformers` - think we're close to getting a new pypi version for `xfromers`: https://github.com/facebookresearch/xformers/issues/795#issuecomment-1644035122
