### ISSUE TITLE
Implement using RetNet instead of transformers

### ISSUE THREAD

**Issue by tronizx** [huggingface/diffusers#4209]
New RetNet is introduced i think it should be implemented in diffusers .  I think you already knew about it but it may be helpful for faster inference.
 
![Screenshot 2023-07-22 193832](https://github.com/huggingface/diffusers/assets/87223249/5d3e595e-6047-4ae2-ae32-642e4b4e0f0d)

**Comment by sayakpaul** [comment]
RetNet: https://arxiv.org/abs/2307.08621

Do we have pre-trained weights available for RetNets that could go with any of our existing pipelines? I guess once that's the case, we can revisit this.

**Comment by tronizx** [comment]
I don't think right now we have! but let see if any pretrained model will come from Micrsoft in future.
