### ISSUE TITLE
Slow loading time with safetensors

### ISSUE THREAD

**Issue by aviadmx** [huggingface/diffusers#4217]
### Describe the bug

When use_safetensors is True while loading a pipeline with from_pretrained, the first call is slow, the next one is the same as without safetensors.

### Reproduction

https://huggingface.co/stabilityai/stable-diffusion-2-inpainting
```
from diffusers import StableDiffusionInpaintPipeline
import time

time_without_safetensors = time.time()
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-inpainting",
    torch_dtype=torch.float16,
    use_safetensors=False
)
pipe.to("cuda")
print("without safetensors took", time.time() - time_without_safetensors)

time_with_safetensors = time.time()
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-inpainting",
    torch_dtype=torch.float16,
    use_safetensors=True
)
pipe.to("cuda")
print("with safetensors took", time.time() - time_with_safetensors)

```
Run the code once to fully download the models, if they dont exist.
Then:
First run, without safetensors 2.5s, with safetensors 20s (why?)
Second run, without safetensors 1.4s, with safetensors 1.4s.

### Expected behavior

Expected safetensors loading to be faster.

### System Info

Ubuntu 18
Python 3.10.11
safetensors 0.3.1
diffusers 0.15.1
transformers 4.27.3
accelerate 0.17.1

**Comment by sayakpaul** [comment]
Could we have a comparison with local files only? Maybe the non safetensors parameters weights were already cached locally and the safetensors files are being downloaded because they weren't cached?

**Comment by aviadmx** [comment]
The results are the same with local files

**Comment by sayakpaul** [comment]
Could you upgrade `diffusers` and see if that impacts the findings?
