### ISSUE TITLE
diffusers.FlaxStableDiffusionPipeline doesnt have negative prompts

### ISSUE THREAD

**Issue by peternasser99** [huggingface/diffusers#4218]
as title 🤷‍♀️🤷‍♀️
diffusers.FlaxStableDiffusionPipeline doesnt have negative prompts so any model checkpoint cant generate any decent faces

**Comment by sayakpaul** [comment]
I see it has `neg_prompt_ids`:

https://github.com/huggingface/diffusers/blob/09fab5610e639ea9d63833921b57a5eae0154f10/src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py#L321. I suppose you can use that. 

cc: @pcuenca

**Comment by pcuenca** [comment]
That's exactly right, @sayakpaul! @peternasser99, you need to prepare the negative prompt ids in exactly the same way you prepare the normal prompt ids. I took a note to update the documentation and make it clearer.

**Comment by peternasser99** [comment]
@sayakpaul @pcuenca thanks 👍👍

**Comment by pcuenca** [comment]
The documentation PR is on-going, closing this issue.
