### ISSUE TITLE
RAM cache is not cleared when using cpu model offloading

### ISSUE THREAD

**Issue by mahdip72** [huggingface/diffusers#4220]
I use stable diffusion inference using code on my local Ubuntu machine to analyze dozens of images. However, when the CPU model offloading option is enabled, the system's RAM gradually increases with each inference run. It appears that the cache of the stable diffusion (SD) modules is not being cleared and is stored inside the RAM, causing this incremental RAM usage. Unlike in Windows, where this issue is not present, enabling the CPU offloading option in Ubuntu prevents the removal of module caches from the GPU VRAM, leaving only the last used modules in memory. As a result, I am unable to utilize the cuda cache to efficiently manage the cache of modules stored in the RAM.

Do you know any solution to remove modules cache inside RAM?

**Comment by sayakpaul** [comment]
Do you have a reproducible code snippet for us? 

Maybe also, how you're investigating the RAM, etc.? 

Also, cc: @pcuenca

**Comment by pcuenca** [comment]
I haven't observed this problem myself, a code snippet as requested by @sayakpaul would be really helpful :)

**Comment by mahdip72** [comment]
Thanks for your responses. I use a simple inference code like below on multiple images:
```python
import torch
from controlnet_aux import NormalBaeDetector
from diffusers import StableDiffusionPipeline, ControlNetModel

controlnet_path = "lllyasviel/sd-controlnet-normal"
controlnet = ControlNetModel.from_pretrained(controlnet_path, torch_dtype=torch.float16)
normal_predictor = NormalBaeDetector.from_pretrained("lllyasviel/Annotators")

model_path = "path_to_saved_model" # diffusers checkpoint
pipe = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=torch.float16)
pipe.enable_model_cpu_offload()

normal_image = normal_predictor(img)
image = pipe(prompt='an empty room', image=normal_image).images[0]

image.save("result.png")

```
After thorough investigation, I have identified that the root cause of this issue lies within the Docker container where my code is executed. Outside the container, there are no cache problems, and the memory growth stabilizes after a few inferences, reaching approximately extra 2 GB with an input resolution of 768×768.

However, inside the Docker container, the memory usage gradually increases, although it does not interfere with other processes, which is acceptable for my purposes. Therefore, I consider this matter resolved.

Thank you for your assistance.
