### ISSUE TITLE
Add Taesd light weight encoder/decoder

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#4233]
https://github.com/madebyollin has build a super cool "preview" VAE (Conv+Relu resblocks and 2x upsample layers) for almost instant encode/decode operations. 

This can be used very nicely to preview latents inputs / outputs when denoising 

Repo: https://github.com/madebyollin/taesd
Weights for SD: https://huggingface.co/madebyollin/taesd
Weights for SDXL: https://huggingface.co/madebyollin/taesdxl (modifié) 

@yiyixuxu @sayakpaul anybody time to pick this one up? 

Happy to give it a try otherwise

**Comment by sayakpaul** [comment]
Happy to.

**Comment by patrickvonplaten** [comment]
We might have to change some code in https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/autoencoder_kl.py but it should more or less work out of the box
