### ISSUE TITLE
How to train instruct-pix2pix with controlnet and inference

### ISSUE THREAD

**Issue by mzeynali** [huggingface/diffusers#4234]
Hi guys,
I want to train instruct-pix2pix using controlnet condition. As you know, currently available for [instruct-pix2pix](https://huggingface.co/docs/diffusers/training/instructpix2pix) and [control net](https://huggingface.co/docs/diffusers/training/controlnet) separately. 
**Q1)** Have you plan about this problem for implementation?
**Q2)** How I can merge them and add controlnet into instruct-pix2pix?
**Q3)** Suppose this issue is done, I want to do start training, In your opinion, If we use controlnet pretraining network, and freeze that network and I want to train only instruct-pix2pix model, Is it common way to do?

**Comment by patrickvonplaten** [comment]
Isn't that a duplicate of https://github.com/huggingface/diffusers/issues/4232 ? Why two issues?
