### ISSUE TITLE
Test for khoya style checkpoint conversions

### ISSUE THREAD

**Issue by williamberman** [huggingface/diffusers#4247]
It would be great to add some tests for converting khoya style checkpoints. These don't have to be super in depth but just sanity checks that we can convert the checkpoints correctly :)

**Comment by patrickvonplaten** [comment]
Maybe also cc @DN6 here if you find some time to pick it up :-)

**Comment by sayakpaul** [comment]
@williamberman yes with you on this. 

If you can, could you also maybe list a couple of points off the top of your mind that you would like to see in these tests? 

@DN6 feel free to bug me for this one as much as possible :)

**Comment by DN6** [comment]
Hi @sayakpaul it looks like the user added some tests for loading and unloading these types of checkpoints? 
https://github.com/huggingface/diffusers/commit/ff8f58086b83414f785a0d1e9b1064331cd14ca4#diff-addc76c32ca1ded9bcc8be9ad7e8c44178737df9821dd529e973828486c3ae5bR797

Is this not enough to verify that the checkpoints are converted correctly?

**Comment by sayakpaul** [comment]
I would think those would suffice. That is why wanted to double-check with @williamberman.

**Comment by williamberman** [comment]
ah nice! I missed this in the PR
