### ISSUE TITLE
`check_inputs` `StableDiffusionUpscalePipeline` fails when passing `prompt_embeds`

### ISSUE THREAD

**Issue by JulianKnodt** [huggingface/diffusers#4249]
There is an implicit assumption in the below region that `prompt` is always passed, and not prompt embeds, because it only checks `prompt` for the batch size.

https://github.com/huggingface/diffusers/blob/5652c43f8398473702bfdc30b55700cd378b1e87/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py#L430

**Comment by patrickvonplaten** [comment]
Good catch! @yiyixuxu do you think you could give this a try?

**Comment by sayakpaul** [comment]
Closing with https://github.com/huggingface/diffusers/pull/4278
