### ISSUE TITLE
Can I input an image to guide generation using the stable diffusion already fine-tuned with the dreambooth

### ISSUE THREAD

**Issue by liyiyue2021** [huggingface/diffusers#4253]
Can I input an image to guide the stable diffusion already fine-tuned with the dreambooth?  It's a bit like stable diffusion image-to-image generation, but with Dreambooth's fine-tuned model to generate.

**Comment by patrickvonplaten** [comment]
Could you please use the forum for training related questions: https://discuss.huggingface.co/
