### ISSUE TITLE
Diffusers results much worse than sd-webui

### ISSUE THREAD

**Issue by DummyNodeHead** [huggingface/diffusers#4255]
### Describe the bug

Hi, I’m faced with a confusing situation and would appreciate any advice from anyone. When I generate images with diffusers, the result quality is much worse than the images generated from sd-webui.

And I also found that usually images generated by diffusers are not as good as those of sd-webui. But this time diffusers can't even generate a valid image. I hope this situation would help you guys find the bug!

### Reproduction

Base Model: https://civitai.com/models/94098?modelVersionId=100380
LoRA: https://civitai.com/models/100873/van-gogh-style

1. Convert model to diffusers with convert_original_stable_diffusion_to_diffusers.py
2. Add LoRA into converted base model with convert_lora_safetensors_to_diffusers.py
3. Generate image with StableDiffusionPipeline.from_pretrained('path_of_converted_model_in_2'). In float16.
4. Sampler remains the same: DDIM
5. Generate images with same prompt and seed. prompt is "vg, best quality, masterpiece, RAW photo, 1girl, solo, lokking at viewer, smile". seed is 12345. A little difference is that in sd-webui there is <lora:vg:1> in the prompt which indicates the LoRA I use. And no neg-prompt is used.
6. size = 512 by 512, guidance_scale=7, steps=30, clip-skip=1

I'm quite sure there are no other models or something that I add into the sd-webui. All settings remain default with sd-webui.

The Results are quite different. Diffusers can't even generate a reasonable result. 

![img_v2_2289b254-48b8-43d5-9f7d-469a099ca4eg](https://github.com/huggingface/diffusers/assets/72564247/9340e91d-1116-4ab1-a7e5-d6fb8a3cb60f)

![img_v2_3acd879c-c754-47b4-8206-ed5bd7a6df6g](https://github.com/huggingface/diffusers/assets/72564247/43983334-b53c-432b-bc6e-991837299d0b)

I also tried generating with diffusers with a larger steps=150. But the result is still a mess.

### System Info

- `diffusers` version: 0.16.0
- Platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.35
- Python version: 3.9.16
- PyTorch version (GPU?): 2.0.1 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.30.2
- Accelerate version: 0.19.0
- xFormers version: 0.0.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
cc @sayakpaul here for LoRA

**Comment by DummyNodeHead** [comment]
> 

You are right. I checked the weights I loaded and indeed that's the problem of what you said in #3725 . Now I've debugged my code according to `load_lora_weights()` and it works. Greatly appreciate your help !!!
