### ISSUE TITLE
LoRA unloading is broken

### ISSUE THREAD

**Issue by isidentical** [huggingface/diffusers#4263]
### Describe the bug

Seems like LoRA unloading stopped working after the commit ebfe343149b3aa501bac50621c33eefee59c15e2.

### Reproduction

Tested this with a Kohya-SS style LoRA

```py
pipe = StableDiffusionPipeline.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    safety_checker=None,
)
pipe.load_lora_weights(...)
pipe.unload_lora_weights()
pipe(...)
```

### System Info

Running on the latest version of diffusers. Bisected it to PR #4259. Looking into the cause now 👀 

### Who can help?

@patrickvonplaten, @sayakpaul, and @williamberman

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten

**Comment by isidentical** [comment]
I just noticed that this doesn't happen on regular invocations but rather happens on a particular setup which involves clearing out the system level module cache (^1 like in the script below).

From what I have gathered, every time we clear out the system level module cache (`sys.modules`) and perform a fresh load of diffusers the unloading logic gets confused by the types (e.g. two different `LoRAAttnProcessor` classes, one from the initial time the lora is loaded and one freshly created/imported).

I was able to get a workaround by not refreshing the module cache on our own app and since this is a very particular use case I understand if you guys want to ignore it. If it is OK to fix, we can do type-name checks instead of direct type checks. 

```py
def fresh_checkout_and_add_path():
    from pathlib import Path
    from subprocess import check_call, check_output

    repo_dir = Path("/data/diffusers")
    if not repo_dir.exists():
        check_call(["git", "clone", "https://github.com/isidentical/diffusers.git", str(repo_dir)])

    branch = "main"
    check_call(["git", "fetch", "origin"], cwd=str(repo_dir))
    check_call(["git", "checkout", branch], cwd=str(repo_dir))
    check_call(["git", "reset", "--hard", f"origin/{branch}"], cwd=str(repo_dir))
    rev_hash = check_output(["git", "rev-parse", "HEAD"], cwd=str(repo_dir), text=True).strip()
    import sys

    if str(repo_dir / "src") not in sys.path:
        sys.path.insert(0, str(repo_dir / "src"))

    import importlib

    importlib.invalidate_caches()
    for module in sys.modules.copy():
        if module.startswith("diffusers"):
            del sys.modules[module]


    return rev_hash
```

**Comment by patrickvonplaten** [comment]
Aii this sounds like a difficult problem. Is the root cause #4259 or was there a problem before already?

**Comment by patrickvonplaten** [comment]
I wonder whether it might be easiest to clean all this up with https://github.com/huggingface/diffusers/issues/4260

**Comment by patrickvonplaten** [comment]
Ping issue to keep open

**Comment by patrickvonplaten** [comment]
Is this issue now fixen on "main" @isidentical if you could double-check this would be amazing!
