### ISSUE TITLE
ImportError: cannot import name 'StableDiffusionXLControlNetPipeline' from 'diffusers.pipelines.controlnet'

### ISSUE THREAD

**Issue by Dai-Wenxun** [huggingface/diffusers#4265]
### Describe the bug

ImportError: cannot import name 'StableDiffusionXLControlNetPipeline' from 'diffusers.pipelines.controlnet'

### Reproduction

import torch
from diffusers import StableDiffusionPipeline
pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipeline.to("cuda")
image = pipeline("A cat").images[0]
image.save("image_of_squirrel_painting.png")

### Logs

```shell
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\WorkSpace\gen\diffusers\src\diffusers\__init__.py", line 63, in <module>
    from .pipelines import (
  File "D:\WorkSpace\gen\diffusers\src\diffusers\pipelines\__init__.py", line 20, in <module>
    from .auto_pipeline import AutoPipelineForImage2Image, AutoPipelineForInpainting, AutoPipelineForText2Image
  File "D:\WorkSpace\gen\diffusers\src\diffusers\pipelines\auto_pipeline.py", line 20, in <module>
    from .controlnet import (
ImportError: cannot import name 'StableDiffusionXLControlNetPipeline' from 'diffusers.pipelines.controlnet' (D:\WorkSpace\gen\diffusers\src\diffusers\pipelines\controlnet\__init__.py)
```

### System Info

Traceback (most recent call last):
  File "D:\software\miniconda3\envs\pt113cu117\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\software\miniconda3\envs\pt113cu117\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\software\miniconda3\envs\pt113cu117\Scripts\diffusers-cli.exe\__main__.py", line 4, in <module>
  File "D:\WorkSpace\gen\diffusers\src\diffusers\__init__.py", line 63, in <module>
    from .pipelines import (
  File "D:\WorkSpace\gen\diffusers\src\diffusers\pipelines\__init__.py", line 20, in <module>
    from .auto_pipeline import AutoPipelineForImage2Image, AutoPipelineForInpainting, AutoPipelineForText2Image
  File "D:\WorkSpace\gen\diffusers\src\diffusers\pipelines\auto_pipeline.py", line 20, in <module>
    from .controlnet import (
ImportError: cannot import name 'StableDiffusionXLControlNetPipeline' from 'diffusers.pipelines.controlnet' (D:\WorkSpace\gen\diffusers\src\diffusers\pipelines\cont
rolnet\__init__.py)

**Comment by Dai-Wenxun** [comment]
I pull the latest diffusers and currently at 428dbfec

**Comment by TC-Elulade** [comment]
I'm trying to fine-tune a stable diffusion model using LoRA and got the same error.

My code:
!accelerate launch --mixed_precision="fp16" train_text_to_image_lora.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$DATASET_NAME --caption_column="text" \
  --resolution=512 --random_flip \
  --train_batch_size=1 \
  --num_train_epochs=100 --checkpointing_steps=5000 \
  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --seed=42 \
  --output_dir="sd-pokemon-model-lora" \
  --validation_prompt="girl wearing a school uniform" --report_to="wandb"

The Error:
Traceback (most recent call last):
  File "/content/diffusers/examples/text_to_image/train_text_to_image_lora.py", line 41, in <module>
    import diffusers
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 63, in <module>
    from .pipelines import (
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/__init__.py", line 20, in <module>
    from .auto_pipeline import AutoPipelineForImage2Image, AutoPipelineForInpainting, AutoPipelineForText2Image
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/auto_pipeline.py", line 20, in <module>
    from .controlnet import (
ImportError: cannot import name 'StableDiffusionXLControlNetPipeline' from 'diffusers.pipelines.controlnet' (/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/controlnet/__init__.py)

Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_text_to_image_lora.py', '--pretrained_model_name_or_path=', '--dataset_name=', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=100', '--checkpointing_steps=5000', '--learning_rate=1e-04', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--seed=42', '--output_dir=sd-pokemon-model-lora', '--validation_prompt=girl wearing a school uniform', '--report_to=wandb']' returned non-zero exit status 1.

I've already tried installing diffusers==0.18.2 but it won't even run (it always ends up wanting me to use the installation from source). Any fixes?

**Comment by rvorias** [comment]
I think this conditional import statement is the culprit:

https://github.com/huggingface/diffusers/blob/34abee090750d22fef357bfb1ffd564c961b9e1d/src/diffusers/pipelines/controlnet/__init__.py#L10C6-L11C79

Make sure to `pip install "invisible-watermark>=0.2.0"`

**Comment by djgould** [comment]
> I think this conditional import statement is the culprit:
> 
> https://github.com/huggingface/diffusers/blob/34abee090750d22fef357bfb1ffd564c961b9e1d/src/diffusers/pipelines/controlnet/__init__.py#L10-L11
> 
> Make sure to `pip install "invisible-watermark>=0.2.0"`, it worked for me.

beat me to it! This worked for me as well.

**Comment by djgould** [comment]
Feels like the conditional import shouldn't be needed given requires_backend should be checking for `invisible_watermark` but not familiar enough to say for sure.

https://github.com/huggingface/diffusers/blob/161449d51ae24f9b0f4935e8574bbe55c59fe0a4/src/diffusers/utils/dummy_torch_and_transformers_and_invisible_watermark_objects.py#L5C21-L17

**Comment by TC-Elulade** [comment]
> I think this conditional import statement is the culprit:
> 
> https://github.com/huggingface/diffusers/blob/34abee090750d22fef357bfb1ffd564c961b9e1d/src/diffusers/pipelines/controlnet/__init__.py#L10-L11
> 
> Make sure to `pip install "invisible-watermark>=0.2.0"`, it worked for me.

Thanks so much, the error no longer comes up :)

**Comment by Osama-Atallah** [comment]
> I'm trying to fine-tune a stable diffusion model using LoRA and got the same error.
> 
> My code: !accelerate launch --mixed_precision="fp16" train_text_to_image_lora.py --pretrained_model_name_or_path=$MODEL_NAME --dataset_name=$DATASET_NAME --caption_column="text" --resolution=512 --random_flip --train_batch_size=1 --num_train_epochs=100 --checkpointing_steps=5000 --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 --seed=42 --output_dir="sd-pokemon-model-lora" --validation_prompt="girl wearing a school uniform" --report_to="wandb"
> 
> The Error: Traceback (most recent call last): File "/content/diffusers/examples/text_to_image/train_text_to_image_lora.py", line 41, in import diffusers File "/usr/local/lib/python3.10/dist-packages/diffusers/**init**.py", line 63, in from .pipelines import ( File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/**init**.py", line 20, in from .auto_pipeline import AutoPipelineForImage2Image, AutoPipelineForInpainting, AutoPipelineForText2Image File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/auto_pipeline.py", line 20, in from .controlnet import ( ImportError: cannot import name 'StableDiffusionXLControlNetPipeline' from 'diffusers.pipelines.controlnet' (/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/controlnet/**init**.py)
> 
> Traceback (most recent call last): File "/usr/local/bin/accelerate", line 8, in sys.exit(main()) File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main args.func(args) File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 979, in launch_command simple_launcher(args) File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_text_to_image_lora.py', '--pretrained_model_name_or_path=', '--dataset_name=', '--caption_column=text', '--resolution=512', '--random_flip', '--train_batch_size=1', '--num_train_epochs=100', '--checkpointing_steps=5000', '--learning_rate=1e-04', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--seed=42', '--output_dir=sd-pokemon-model-lora', '--validation_prompt=girl wearing a school uniform', '--report_to=wandb']' returned non-zero exit status 1.
> 
> I've already tried installing diffusers==0.18.2 but it won't even run (it always ends up wanting me to use the installation from source). Any fixes?

Use this to install from the source:

git clone https://github.com/huggingface/diffusers
cd diffusers
git checkout 5e80827
pip install .

It will work. 
5e80827 is the hash for version 18.2 because the latest version 19.0.dev produces that error

**Comment by Osama-Atallah** [comment]
For whom is doing inference, try to import diffusers==18.2

**Comment by patrickvonplaten** [comment]
Very sorry about this everybody - we forgot to add optional dependency importing for SDXL. This meant that if one didn't have the watermarking library installed the import failed. 

This is fixed in: https://github.com/huggingface/diffusers/pull/4272
