### ISSUE TITLE
Update _convert_kohya_ss_state_dict to directly output the new naming conventions

### ISSUE THREAD

**Issue by williamberman** [huggingface/diffusers#4268]
`_convert_kohya_ss_state_dict` outputs the legacy lora conventions when the additional layer was stored on the model without a formal separate module. We should update it to directly output the new naming convention with formal lora layers

See previous discussion: https://github.com/huggingface/diffusers/pull/4147#discussion_r1272877147

**Comment by hackpk** [comment]
@williamberman Can I work on this??

**Comment by hackpk** [comment]
@williamberman Thanks I will be needing some help

**Comment by Lorenzobattistela** [comment]
@williamberman I'd like to work on this. I checked the discussion and I do understand that we need to update output to new naming conventions. Where can i find these conventions? Thanks in advance

**Comment by amk16** [comment]
Hey is anyone working on this otherwise could I?

**Comment by AbhinavJangra29** [comment]
is anyone working on this ?

**Comment by sayakpaul** [comment]
It's done already. So, closing this
