### ISSUE TITLE
[Pipelines] Add BLIP diffusion

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#4274]
BLIP diffusion (Salesforce): https://dxli94.github.io/BLIP-Diffusion-website/

BLIP diffusion enables subject-driven zero-shot image generation which is probably its best USP. 

* Code with pre-trained weights: https://github.com/salesforce/LAVIS/tree/main/projects/blip-diffusion
* Paper: https://arxiv.org/abs/2305.14720

From the official website mentioned above:

<img width="1058" alt="image" src="https://github.com/huggingface/diffusers/assets/22957388/29a134af-6756-4d48-a072-e46ed0cd56ba">

**Comment by ayushtues** [comment]
Hey @sayakpaul I'll be interested in contributing to this model, will start by raising a PR soon

**Comment by ariG23498** [comment]
Just noticed that this is done! I think we should probably close this issue ^_^
