### ISSUE TITLE
how o convert trained LoRA bin format file to A111 safetensor format

### ISSUE THREAD

**Issue by futureflsl** [huggingface/diffusers#4281]
### Describe the bug

I find script convert_lora_safetensor_to_diffusers.py,but it seems like convert safetensors to bin,not bin to safetensors,I try run this script,error like this:
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\fut\Desktop\tinaniu\convert_lora_safetensor_to_diffusers.py:125 in <module>             │
│                                                                                                  │
│   122 │   lora_prefix_text_encoder = args.lora_prefix_text_encoder                               │
│   123 │   alpha = args.alpha                                                                     │
│   124 │                                                                                          │
│ ❱ 125 │   pipe = convert(base_model_path, checkpoint_path, lora_prefix_unet, lora_prefix_text_   │
│   126 │                                                                                          │
│   127 │   pipe = pipe.to(args.device)                                                            │
│   128 │   pipe.save_pretrained(args.dump_path, safe_serialization=args.to_safetensors)           │
│                                                                                                  │
│ C:\Users\fut\Desktop\tinaniu\convert_lora_safetensor_to_diffusers.py:31 in convert               │
│                                                                                                  │
│    28 │   pipeline = StableDiffusionPipeline.from_pretrained(base_model_path, torch_dtype=torc   │
│    29 │                                                                                          │
│    30 │   # load LoRA weight from .safetensors                                                   │
│ ❱  31 │   state_dict = load_file(checkpoint_path)                                                │
│    32 │                                                                                          │
│    33 │   visited = []                                                                           │
│    34                                                                                            │
│                                                                                                  │
│ D:\anaconda3\lib\site-packages\safetensors\torch.py:259 in load_file                             │
│                                                                                                  │
│   256 │   ```                                                                                    │
│   257 │   """                                                                                    │
│   258 │   result = {}                                                                            │
│ ❱ 259 │   with safe_open(filename, framework="pt", device=device) as f:                          │
│   260 │   │   for k in f.keys():                                                                 │
│   261 │   │   │   result[k] = f.get_tensor(k)                                                    │
│   262 │   return result                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
SafetensorError: Error while deserializing header: HeaderTooLarge

### Reproduction

SafetensorError: Error while deserializing header: HeaderTooLarge

### System Info

diffusers==0.18.2

**Comment by patrickvonplaten** [comment]
I don't believe we have a Diffusers LoRA => A1111 format converter. However you can just use SD.Next with diffusers to try out your LoRA: https://github.com/vladmandic/automatic
