### ISSUE TITLE
[Question] Combining Image-to-Image and ControlNet

### ISSUE THREAD

**Issue by alexisrolland** [huggingface/diffusers#4288]
Hello,

In A1111 WebUI, it is possible to generate an image by combining and image input with a ControlNet. One use case I have seen for instance is using the image of character, and combine it with Openpose ControlNet to create variations of the character while preserving the exact same pose.

I am wondering if such combination would be feasible with `diffusers`? I looked in the documentation, I found how to do multi-ControlNet but did not find anything related to image-to-image + ControlNet.

Thank you

**Comment by alexblattner** [comment]
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py

you're welcome

**Comment by alexisrolland** [comment]
Thank you, apparently I don't know how to search... it seems it's been there the whole time. Sharing the link to the doc for future readers https://huggingface.co/docs/diffusers/v0.19.2/en/api/pipelines/controlnet#diffusers.StableDiffusionControlNetImg2ImgPipeline
