### ISSUE TITLE
[Tests] Add some tests for the principle of connected pipelines as introduced

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#4289]
connected pipelines were introduced in this PR: https://github.com/huggingface/diffusers/pull/4207 . We have neither added good documentation, nor good tests for this yet. 

It would be great if someone could take care of this.
In terms of tests we should both test:

- that dummy pipelines that have the `self._load_connected_pipes` set to True behave as expected
- test that passing `load_connected_pipeline` to `DiffusionPipeline.from_pretrained(...)` behaves as expected

 Maybe cc @DN6 or @yiyixuxu

**Comment by patrickvonplaten** [comment]
We still need tests here. They should take too long to write - @DN6 do you want to give this a try or should I go ahead?

**Comment by DN6** [comment]
@patrickvonplaten Would take me a little time to get up to speed on this. If you could add the tests, I'm happy to review them.
