### ISSUE TITLE
How can I update the StableDiffusionControlNetPipeline controlnet input?

### ISSUE THREAD

**Issue by JemiloII** [huggingface/diffusers#4293]
I don't see in the docs how to update the StableDiffusionControlNetPipeline controlnet input. Curious how this can be achieved. I leave my model loaded in memory and only update the settings that have changed so generation can be smooth and fast.

~~If it helps, I'm currently using diffusers 0.17.1~~
I have updated it to the latest 18.2. Btw, the update was really smooth; I appreciated that.

**Comment by alexblattner** [comment]
like the regular controlnet pipeline

**Comment by JemiloII** [comment]
@alexblattner what do you mean?

I want to do something like this.

```
pipeline = StableDiffusionControlNet.from_pretrained(
 ...
 # Never include load controlnet 
)

# Load it something like this?
pipeline.controlnet = controlnet

or

# load something like this??
pipleine.load_controlnet(controlnet)

or

# I'd really just love to do this.
loaded_controlnet_1 = pipeline.apply_controlnet = controlnet1
loaded_controlnet_2 = pipeline.apply_controlnet = controlnet2

pipeline.remove_controlnet(loaded_controlnet_1)
pipeline.remove_controlnet(loaded_controlnet_2)
```

It's kinda hard to see how I can do something like this.

**Comment by alexblattner** [comment]
@JemiloII you'll have to create your custom pipeline for that

**Comment by alexblattner** [comment]
@JemiloII I will soon release a pipeline this week that will let you do this and more

**Comment by JemiloII** [comment]
@alexblattner anywhere i can find the example of how to do this?

**Comment by alexblattner** [comment]
@JemiloII sorry about the delay. I haven't added the option to remove controlnets individually, but you can revert and add back easily:

https://github.com/alexblattner/RubberDiffusers
