### ISSUE TITLE
Multiple lora with different weights

### ISSUE THREAD

**Issue by shubhamworks** [huggingface/diffusers#4300]
How can I add different weights to different Loras added to the pipeline? As per my understanding, the cross_attention_kwargs only takes one argument scale, which is common for all the LoRAs.
`cross_attention_kwargs={"scale":0.6}`

@sayakpaul

**Comment by sayakpaul** [comment]
Currently, you cannot load multiple LoRA weights.

**Comment by gadicc** [comment]
See also https://github.com/huggingface/diffusers/issues/2613 ("Support for adding multiple LoRA layers to Diffusers").
