### ISSUE TITLE
load_lora_weight() doesn't work for sdxl lora trained model from https://github.com/TheLastBen/fast-stable-diffusion

### ISSUE THREAD

**Issue by MaxTran96** [huggingface/diffusers#4302]
### Describe the bug

Hi i tried using TheLastBen runpod to lora trained a model from SDXL base 0.9. I then test ran that model on ComfyUI and it was able to generate inference just fine

but when i tried to do that via code
```
STABLE_DIFFUSION_SDXL = 'stabilityai/stable-diffusion-xl-base-0.9'
pipe = DiffusionPipeline.from_pretrained(
    STABLE_DIFFUSION_SDXL,
    torch_dtype=torch.float16,
    use_safetensors=True,
    safety_checker=None,
    variant='fp16'
).to('cuda')
pipe.load_lora_weights(".", weight_name=lora_path)
```

it returns 
```
>>> pipe.load_lora_weights(".", weight_name=lora_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 857, in load_lora_weights
    self.load_lora_into_unet(state_dict, network_alpha=network_alpha, unet=self.unet)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/loaders.py", line 1055, in load_lora_into_unet
    unet.load_attn_procs(unet_lora_state_dict, network_alpha=network_alpha)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/loaders.py", line 364, in load_attn_procs
    raise ValueError(f"Module {key} is not a LoRACompatibleConv or LoRACompatibleLinear module.")
ValueError: Module down_blocks.1.attentions.0.proj_in is not a LoRACompatibleConv or LoRACompatibleLinear module.
```

i also tried using a custom code that i found from previous git issue in diffuser repo
```
def load_lora_weights(pipeline, checkpoint_path, multiplier, device, dtype):
    LORA_PREFIX_UNET = "lora_unet"
    LORA_PREFIX_TEXT_ENCODER = "lora_te"
    # load LoRA weight from .safetensors
    state_dict = load_file(checkpoint_path, device=device)
    updates = defaultdict(dict)
    for key, value in state_dict.items():
        # it is suggested to print out the key, it usually will be something like below
        # "lora_te_text_model_encoder_layers_0_self_attn_k_proj.lora_down.weight"
        layer, elem = key.split('.', 1)
        updates[layer][elem] = value
    # directly update weight in diffusers model
    for layer, elems in updates.items():
        if "text" in layer:
            layer_infos = layer.split(LORA_PREFIX_TEXT_ENCODER + "_")[-1].split("_")
            curr_layer = pipeline.text_encoder
        else:
            layer_infos = layer.split(LORA_PREFIX_UNET + "_")[-1].split("_")
            curr_layer = pipeline.unet
        # find the target layer
        temp_name = layer_infos.pop(0)
        while len(layer_infos) > -1:
            try:
                curr_layer = curr_layer.__getattr__(temp_name)
                if len(layer_infos) > 0:
                    temp_name = layer_infos.pop(0)
                elif len(layer_infos) == 0:
                    break
            except Exception:
                if len(temp_name) > 0:
                    temp_name += "_" + layer_infos.pop(0)
                else:
                    temp_name = layer_infos.pop(0)
        # get elements for this layer
        weight_up = elems['lora_up.weight'].to(dtype)
        weight_down = elems['lora_down.weight'].to(dtype)
        alpha = elems['alpha']
        if alpha:
            alpha = alpha.item() / weight_up.shape[1]
        else:
            alpha = 1.0
        # update weight
        if len(weight_up.shape) == 4:
            curr_layer.weight.data += multiplier * alpha * torch.mm(weight_up.squeeze(3).squeeze(2), weight_down.squeeze(3).squeeze(2)).unsqueeze(2).unsqueeze(3)
        else:
            curr_layer.weight.data += multiplier * alpha * torch.mm(weight_up, weight_down)
    return pipeline
pipe = load_lora_weights(pipe, lora_path, 1.0, 'cuda', torch.float16)
```
it's able to load but when i ran 
```
positive_prompt = 'photo of nasdxl'
negative_prompt = '(worst quality, low quality:1.4),deformed, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, blurry, ((((mutated hands and fingers)))), watermark, watermarked, oversaturated, censored, distorted hands, amputation, missing hands, obese, doubled face, double hands,(((missing arms))),(((missing legs))), (((extra arms))),(((extra legs))), badhandsv5, badhandv4, deepnegative'
images = pipe(
    prompt=positive_prompt,
    negative_prompt=negative_prompt,
    generator=torch.Generator(device='cuda').manual_seed(111111)
).images
```
it generated images that don't contain my trained subject. Is this a bug? The inference for this model works just fine on ComfyUI. I noticed that it has a k_sampler node, do i need to process the model with k_sampler so that it can correctly generate image that contain my trained subject?

### Reproduction

Trained a model using https://github.com/TheLastBen/fast-stable-diffusion
and ran the inference code i provided above

### System Info

AWS EC2 g4.4xlarge

### Who can help?

@sayakpaul @patri

**Comment by patrickvonplaten** [comment]
Working on it! See: https://github.com/huggingface/diffusers/pull/4287

**Comment by MaxTran96** [comment]
When can we expect to have it ready? And how would i then run inference by loading the lora weight.

**Comment by MaxTran96** [comment]
Just curious, the issue you mentioned is for Kohya-style LoRA, what's the difference between that and the regular Lora method? Is https://github.com/TheLastBen/diffusers/blob/main/examples/dreambooth/train_dreambooth_rnpd_sdxl_lora.py Kohya-style Lora or the regular Lora.

**Comment by MaxTran96** [comment]
Hello, any update? Also i don't think the fix from https://github.com/huggingface/diffusers/pull/4287 is working for my case

i'm still getting this error 
>>> pipe.load_lora_weights(lora_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 872, in load_lora_weights
    state_dict, network_alphas = self.lora_state_dict(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/loaders.py", line 1098, in lora_state_dict
    state_dict = cls._map_sgm_blocks_to_diffusers(state_dict, unet_config)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/loaders.py", line 1121, in _map_sgm_blocks_to_diffusers
    raise ValueError("Checkpoint not supported")
ValueError: Checkpoint not supported

I trained this model using TheLastBen's runpod SDXL trainer https://github.com/TheLastBen/fast-stable-diffusion. Inference works fine on ComfyUI with the lora model loaded. but when i tried to use the code below to load my lora .safetensors file

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-0.9", torch_dtype=torch.float16)
pipe.load_lora_weights(lora_path)
pipe.to(torch_dtype=torch.float16)
pipe.to("cuda")

i got the error above

Attached below is the link to my safetensor file https://drive.google.com/file/d/1WATYshwvISm4YKDJkABSysmC5iV-sqm8/view?usp=sharing


@patrickvonplaten

**Comment by sayakpaul** [comment]
That means it has other forms of adapter weights probably or has a format we're not aware of. For now, we will restrict to Kohya-style checkpoints since those are the most popular ones. We will also try add support for LoHo (LyCORIS-exclusive).

**Comment by MaxTran96** [comment]
How come I can run just fine on ComfyUI? Does ComfyUI not use the same inference code as diffusers?

**Comment by sayakpaul** [comment]
I don't think so.

**Comment by MaxTran96** [comment]
Is it possible to implement something like this to read lora .safetensors file?  https://github.com/comfyanonymous/ComfyUI/issues/980

@sayakpaul @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @MaxTran96 can you add more specific code, I don't follow the issue: https://github.com/comfyanonymous/ComfyUI/issues/980

**Comment by TheLastBen** [comment]
Using kohya lora library https://github.com/bmaltais/kohya_ss/blob/master/networks/lora.py, it is possible to load the lora into diffusers unet or text encoder

can be loaded like this

Given `pipeline` is the main pipeline :

```
import  lora

for weights_file in ['lora.safetensors']:
    if ";" in weights_file:
        weights_file, multiplier = weights_file.split(";")
        multiplier = float(multiplier)
    else:
        multiplier = 1.0

    lora_model, weights_sd = lora.create_network_from_weights(
        multiplier, weights_file, pipeline.unet, None, True
    )
    lora_model.merge_to(pipeline.unet, weights_sd)
```

**Comment by MaxTran96** [comment]
By "Given pipeline is the main pipeline", is this still how i define pipe?
pipe = DiffusionPipeline.from_pretrained(
            STABLE_DIFFUSION_SDXL,
            torch_dtype=torch.float16,
            use_safetensors=True,
            variant='fp16'
        )

**Comment by MaxTran96** [comment]
Also i was able to do this from https://github.com/comfyanonymous/ComfyUI/issues/980#issuecomment-1666054414

**Comment by patrickvonplaten** [comment]
Does it work now? We should try to make it possible to load LoRAs from the lastben notebook.

If it still doesn't work, let's maybe try to open a PR to fix it?

**Comment by TheLastBen** [comment]
it would involve using Kohya's LoRAs file system, multimodalart did it in LoraTheExplorer https://huggingface.co/spaces/multimodalart/LoraTheExplorer

**Comment by MaxTran96** [comment]
yes it worked, i was able to do that from this issue https://github.com/comfyanonymous/ComfyUI/issues/980#issuecomment-1666054414

**Comment by patrickvonplaten** [comment]
Here also a colab from @apolinario for reference:
https://colab.research.google.com/drive/14aEJsKdEQ9_kyfsiV6JDok799kxPul0j

@sayakpaul do you want to take this one making sure theLastBen LoRAs work? Otherwise happy to take it over

**Comment by sayakpaul** [comment]
Too much on my plate currently. Sorry.

**Comment by patrickvonplaten** [comment]
No worries! I'll take it :-)

**Comment by patrickvonplaten** [comment]
With #4797, the following code snippet works just fine for me now:

```py
from diffusers import AutoPipelineForText2Image
import torch

path = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = AutoPipelineForText2Image.from_pretrained(path, torch_dtype=torch.float16)
pipe.enable_model_cpu_offload()

lora_model_id = "TheLastBen/Papercut_SDXL"
lora_filename = "papercut.safetensors"
pipe.load_lora_weights(lora_model_id, weight_name=lora_filename)

prompt = "papercut sonic"

image = pipe(prompt=prompt, 
    num_inference_steps=20, 
    generator=torch.manual_seed(0)
).images[0]
image
```
![aa_0 (3)](https://github.com/huggingface/diffusers/assets/23423619/4d832e9c-4b0e-4811-a4f9-c99f4607b1df)

**Comment by MaxTran96** [comment]
Does the Lora model need to always be uploaded to HF in order to be used via that python code?

**Comment by MaxTran96** [comment]
@patrickvonplaten  is it possible to not have lora_model_id and use it?

**Comment by sayakpaul** [comment]
You would then need to download it locally and use it like so:

```
pipe.load_lora_weights(path_to_the_folder_where_the_lora_file_is, weight_name=lora_filename)
```

**Comment by MaxTran96** [comment]
hi i have a hard time loading the DreamShaperXL safetensors
```
from diffusers import AutoPipelineForText2Image, DiffusionPipeline, AutoencoderKL
import torch

path = "stabilityai/stable-diffusion-xl-base-1.0"
vae = AutoencoderKL.from_pretrained("stabilityai/sdxl-vae", torch_dtype=torch.float16, use_safetensors=True)

#pipe = AutoPipelineForText2Image.from_pretrained(path, torch_dtype=torch.float16)

STABLE_DIFFUSION_SDXL = 'stabilityai/stable-diffusion-xl-base-1.0'
dtype = torch.float16
variant='fp16'
pipe = DiffusionPipeline.from_pretrained(
            STABLE_DIFFUSION_SDXL,
            torch_dtype=dtype,
            vae=vae,
            use_safetensors=True,
            variant=variant,
            custom_pipeline="lpw_stable_diffusion_xl"  # for long prompt
)
pipe.enable_model_cpu_offload()
pipe.load_lora_weights("/home/ubuntu/content/VenusAI/model_database", weight_name="dreamshaperXL10_alpha2Xl10.safetensors")
```

I got this error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 909, in load_lora_weights
    self.load_lora_into_unet(state_dict, network_alphas=network_alphas, unet=self.unet)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/loaders.py", line 1266, in load_lora_into_unet
    unet.load_attn_procs(state_dict, network_alphas=network_alphas)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/diffusers/loaders.py", line 479, in load_attn_procs
    raise ValueError(
ValueError: None does not seem to be in the correct format expected by LoRA or Custom Diffusion training.
```
@sayakpaul @patrickvonplaten

**Comment by MaxTran96** [comment]
i tried both AutoPipelineForText2Image and DiffusionPipeline, they dont seem to work. Let me know what i did wrong here

**Comment by sayakpaul** [comment]
Where is this LoRA from? Could you provide us with a Colab Notebook that reproduces the problem end-to-end?

Additionally, which trainer was used to obtain the LoRA file?

**Comment by MaxTran96** [comment]
i got this lora from here https://civitai.com/models/112902/dreamshaper-xl-09-alpha. How should i load this lora?

**Comment by TheLastBen** [comment]
> i got this lora from here https://civitai.com/models/112902/dreamshaper-xl-09-alpha. How should i load this lora? @sayakpaul

this is not a LoRA, it's a full model

**Comment by MaxTran96** [comment]
so how should i load this?

**Comment by patrickvonplaten** [comment]
You can load it just like any other base model:

```py
from diffusers import AutoPipelineForText2Image
import torch

path = "Lykon/dreamshaper-xl-1-0"

pipe = AutoPipelineForText2Image.from_pretrained(path, torch_dtype=torch.float16)
pipe.enable_model_cpu_offload()

lora_model_id = "TheLastBen/Papercut_SDXL"
lora_filename = "papercut.safetensors"
pipe.load_lora_weights(lora_model_id, weight_name=lora_filename)

prompt = "papercut sonic"

image = pipe(prompt=prompt, 
    num_inference_steps=20, 
    generator=torch.manual_seed(0)
).images[0]
image
```
