### ISSUE TITLE
[Training] Support for SDXL Text to Image LoRA

### ISSUE THREAD

**Issue by wfng92** [huggingface/diffusers#4304]
Currently, the `diffusers` package supports training SDXL via Dreambooth LoRA which works great for single subject/style image generation. It would be great to have a training script similar to [train_text_to_image_lora.py](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py), which supports SDXL training using image-caption pairs datasets.

> Note: This is not the same issue as #4150 (vanilla fine-tuning)

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
Text-to-image LoRA for SDXL could require a lot of computation power, I would assume. This is why we restricted the downstream usage to DreamBooth LoRA only. If you would like to open a PR for this, happy to help/review :)

**Comment by wfng92** [comment]
> Text-to-image LoRA for SDXL could require a lot of computation power, I would assume. This is why we restricted the downstream usage to DreamBooth LoRA only. If you would like to open a PR for this, happy to help/review :)

Based on the issue raised on the kohya repository, it seems SDXL LoRA is trainable on 12GB GPU (with text encoder, network_dim of 32, latent cache). Hope someone will be able to contribute a barebone training script that supports SDXL training using image-caption pairs datasets. Thanks.
