### ISSUE TITLE
from_pretrained error when local_files_only=True

### ISSUE THREAD

**Issue by wfng92** [huggingface/diffusers#4307]
### Describe the bug

After all the files have been downloaded locally, changing the value of `local_files_only` to `True` will raise reference before assignment error.

### Reproduction

```python
from diffusers import StableDiffusionXLPipeline
import torch

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    cache_dir="./cache/",
    local_files_only=True,
    variant="fp16",
    use_safetensors=True
)
pipe.to("cuda")

...
```

### Logs

```shell
Traceback (most recent call last):
  File "E:\NGWF\test.py", line 4, in <module>
    pipe = StableDiffusionXLPipeline.from_pretrained(
  File "E:\NGWF\myenv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 902, in from_pretrained
    cached_folder = cls.download(
  File "E:\NGWF\myenv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1477, in download
    if pipeline_class._load_connected_pipes:
UnboundLocalError: local variable 'pipeline_class' referenced before assignment
```

### System Info

- `diffusers` version: 0.19.0
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.11
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: 0.0.20

**Comment by eliphatfs** [comment]
https://github.com/huggingface/diffusers/commit/b3e5cd6b4d7fd5d03d75e78688dce52be02217b3#diff-e3b955d2305b6677e114507f68df06ea9e10b77944e55ed7fba1dd971f4bf6ffR1476

**Comment by patrickvonplaten** [comment]
Thank you, fixing now! Will go into a patch release

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/issues/4311

**Comment by patrickvonplaten** [comment]
I can reproduce, thanks for the nice code snippet. Will also add a test, this should have been caught by our fasts tests

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/pull/4318
