### ISSUE TITLE
discrepancy between the default value of `guidance_scale` of `StableDiffusionXLPipeline` and its docstring description

### ISSUE THREAD

**Issue by hysts** [huggingface/diffusers#4308]
The default value seems to be set to 5.0, but the docstring says that it's 7.5.
https://github.com/huggingface/diffusers/blob/20e92586c1fda968ea3343ba0f44f2b21f3c09d2/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L557
https://github.com/huggingface/diffusers/blob/20e92586c1fda968ea3343ba0f44f2b21f3c09d2/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L602

**Comment by Tanupriya-Singh** [comment]
I can work on this if the issue can be assigned to me.

**Comment by patrickvonplaten** [comment]
It be great if we could correct the docstring to state 5.0 - @Tanupriya-Singh would you like to open a PR?

**Comment by Tanupriya-Singh** [comment]
Thanks @patrickvonplaten , I will open a PR shortly.

**Comment by Tanupriya-Singh** [comment]
@patrickvonplaten , Here's my PR, let me know if any issues:
https://github.com/huggingface/diffusers/pull/4339

(It's my first open-source contribution :) )

**Comment by Tanupriya-Singh** [comment]
@hysts The PR is merged, we should be good to close this. Let me know if any issues.

**Comment by hysts** [comment]
Awesome! Thanks!
