### ISSUE TITLE
Staircase/Scanline artifacts with SDXL 1.0

### ISSUE THREAD

**Issue by n00mkrad** [huggingface/diffusers#4310]
### Describe the bug

SDXL creates colorful scanline-like artifacts, especially on areas with high-frequency detail.

SDXL - Diffusers 0.19.0 - 25 Steps of DPMSolverMultistepScheduler with Karras - 20% refine steps - CFG Scale 7

Left: SDXL 1.0 - Right: SDXL 0.9

![image](https://github.com/huggingface/diffusers/assets/61149547/75990ca4-5b0c-468e-9d61-1f470a03104c)
![image](https://github.com/huggingface/diffusers/assets/61149547/be984df6-488f-4bc3-af11-945dff0670c4)

### Reproduction

Run SDXL 1.0 and compare results with SDXL 0.9

### System Info

Diffusers 0.19.0 - Windows 10 22H2 - RTX 4090 with drivers 536.40 - FP16 model

**Comment by n00mkrad** [comment]
Also happens without refiner model.

**Comment by n00mkrad** [comment]
**Workaround: Copy the 0.9 VAE to the 1.0 model.**

The 1.0 VAE is broken.

**Comment by sayakpaul** [comment]
Thanks for investigating. We think it will be beneficial for potentially similar future issues :)

**Comment by fralumz** [comment]
The onnx vae should be reverted to 0.9 as well.

**Comment by Woisek** [comment]
This VAE fixed it for me:
https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/tree/main

**Comment by sayakpaul** [comment]
It is still missing a reproducible code snippet.

**Comment by sayakpaul** [comment]
@patrickvonplaten WDYT?

**Comment by patrickvonplaten** [comment]
Hey @catboxanon,

This is really more an issue for the repo here: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/discussions as Stability AI decides how to name the files in their repo. Could you open an issue there?
