### ISSUE TITLE
local_files_only=True, variable pipeline_class referenced before assignment

### ISSUE THREAD

**Issue by Glaceon-Hyy** [huggingface/diffusers#4311]
https://github.com/huggingface/diffusers/blob/20e92586c1fda968ea3343ba0f44f2b21f3c09d2/src/diffusers/pipelines/pipeline_utils.py#L1474C1-L1483C4

**Comment by patrickvonplaten** [comment]
Fixed in: https://github.com/huggingface/diffusers/pull/4318

**Comment by patrickvonplaten** [comment]
Sorry about this - will make a patch releaes
