### ISSUE TITLE
SAG for inpainting and img2img

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#4312]
Hello, SAG is great and produces great results, but there are no pipelines that use it with img2img or inpainting. Can it be done?

this is the pipeline btw:
https://github.com/huggingface/diffusers/blob/8e5921cac14c84a670b4e9d89d717b5356e5b9e9/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py

**Comment by alexblattner** [comment]
I think this is pretty basic... Can someone look into it?

**Comment by alexblattner** [comment]
@patrickvonplaten @sayakpaul is there any way to look into this. That's the biggest downside of the pipeline implementation. Always slightly modifying stuff when most of the code repeats.

**Comment by sayakpaul** [comment]
We try to maintain the consistency and reduce the repetition bit by using `make fix-copies` and `# Copied from ...` statements. 

Sorry we won't have the time to look into extending the pipeline to the above use cases right now, but happy to review PRs.

**Comment by alexblattner** [comment]
@sayakpaul the issue is that it refuses to work when developing in a pip install environment. I would take care of it if it didn't do that, but then what about the dozens of other pipelines? shit's a nightmare

**Comment by alexblattner** [comment]
I made it work with my new pipeline RubberDiffusers
