### ISSUE TITLE
Possible misuse of scheduler in function log_validation in train_dreambooth.py

### ISSUE THREAD

**Issue by wyz894272237** [huggingface/diffusers#4313]
I copy train_dreambooth.py and use it to fully train IF Stage II. During training, I found it is unavoidable to generate images with noise point.I personally think it is due to the mandatory use of DPMSolverMultistepScheduler in function log_validation. When I try to use the origin scheduler DDPMScheduler offered by (https://huggingface.co/DeepFloyd/IF-II-M-v1.0/tree/main/scheduler), the problem is alleviated. Here are some comparisons using same checkpoint (above is DPMSolverMultistepScheduler).

![image](https://github.com/huggingface/diffusers/assets/43692893/4350b3d1-fd0e-40be-95bd-ee543cff93ee)
![image](https://github.com/huggingface/diffusers/assets/43692893/acca5036-9602-49b9-b1d2-c063b0a4bf70)

![image](https://github.com/huggingface/diffusers/assets/43692893/6cb61721-3db3-47b8-a2df-574bddbae712)
![image](https://github.com/huggingface/diffusers/assets/43692893/fb95e413-e8f4-448a-9729-de61cf5c8c3d)

Perhaps you could consider passing a new args parameter to control.

**Comment by sayakpaul** [comment]
Thanks so much for finding this!

Would you maybe like to open a PR for this?

**Comment by wyz894272237** [comment]
Thanks for you reply. I tried training twice and found this problem both times. One trained for a day, the other for two hours, both on one 8xA100. I think the DPMSolverMultistepScheduler is overly inclined to speed over quality, which may not be applied to an architecture without vae such as IF. I will open a PR for this.

**Comment by bghira** [comment]
possibly that the noise schedule implemented by DPM++ 2M during training is just incongruent with the choice made by the DF team. you will observe similar issues when you try fine-tuning Stable Diffusion 2.1 with DDIM instead of DDPM.
