### ISSUE TITLE
TypeError: 'NoneType' not iterable in forward() of unet_2d_condition.py

### ISSUE THREAD

**Issue by StefosGeo** [huggingface/diffusers#4324]
### Describe the bug

I tried to run train_dreambooth.py using the following parameters: 

```
 --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0"  \
  --instance_data_dir="./photos" \
  --class_data_dir="./class_man" \
  --output_dir="./results" \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of qwer man" \
  --class_prompt="a photo of man" \
  --resolution=512 \
  --train_batch_size=2 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=120 \
  --max_train_steps=1000
```

And I get the following error:

`File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 840, in forward if "text_embeds" not in added_cond_kwargs: TypeError: argument of type 'NoneType' is not iterable`

After investigating the code I saw that the variable `'added_cond_kwargs'` by default has None value. But the code doesn't handle this situation. It seams that `'forward()' `method its not working using the default parameters

### Reproduction

```
python3 train_dreambooth.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0"  \
  --instance_data_dir="./photos" \
  --class_data_dir="./class_man" \
  --output_dir="./results" \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of qwer man" \
  --class_prompt="a photo of man" \
  --resolution=512 \
  --train_batch_size=2 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=120 \
  --max_train_steps=1000
```

### Logs

```shell
File "/workspace/train_dreambooth.py", line 1378, in <module>
    main(args)
  File "/workspace/train_dreambooth.py", line 1226, in main
    model_pred = unet(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 840, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
```

### System Info

diffusers-0.15.0.dev0, ubuntu, python3.10

**Comment by KernelA** [comment]
I have the same issue with `diffusers[torch]~=0.19.3` and  `StableDiffusionInpaintPipeline`.

**Comment by parthmannan** [comment]
Running into the same issue with diffusers 0.20.0.dev0

**Comment by patrickvonplaten** [comment]
@sayakpaul @williamberman here

**Comment by KernelA** [comment]
It was my mistake. It works without error after replacement `StableDiffusionInpaintPipeline` on StableDiffusionXLInpaintPipeline`.

**Comment by adam-dunamu** [comment]
Is this issue solved?
Same error occurs in version `0.20.0.dev0`, when I try to reproduce [textual inversion example](https://github.com/huggingface/diffusers/tree/main/examples/textual_inversion) on SDXL1.0.

**Comment by sayakpaul** [comment]
We don't have a textual inversion script that supports SDXL.

**Comment by adam-dunamu** [comment]
Ok, thank you for your response. @sayakpaul
