### ISSUE TITLE
Different results when using train_dreambooth.py and train_dreambooth_lora.py

### ISSUE THREAD

**Issue by nayan-dhabarde** [huggingface/diffusers#4331]
**I am using exact same parameters for both train_dreambooth.py and train_dreambooth_lora.py while training, here is the script**
```
!accelerate launch train_dreambooth_lora.py \
  --pretrained_model_name_or_path="SG161222/Realistic_Vision_V4.0"  \
  --instance_data_dir="training_images" \
  --output_dir="result" \
  --class_data_dir="man_dataset" \
  --train_text_encoder \
  --instance_prompt="a photo of nayan12k man" \
  --class_prompt="a photo of man" \
  --resolution=512\
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --checkpointing_steps=100 \
  --learning_rate=1e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=1000 \
  --max_train_steps=1000 \
  --seed="1337" 
```

**When i use the inference script similar to this one:**
from diffusers import StableDiffusionPipeline
import torch 

pipe = StableDiffusionPipeline.from_pretrained("SG161222/Realistic_Vision_V4.0", torch_dtype=torch.float16)
pipe = pipe.to("cuda")
pipe.load_lora_weights("{path_to_checkpoint}")
image = pipe("A photo of nayan12k man wearing a suit", num_inference_steps=25).images[0]

I dont see any impace of load_lora_weights on it, where as when I do inference for train_dreambooth.py I can see the results

**Comment by LLjo** [comment]
same here

**Comment by patrickvonplaten** [comment]
Sorry I don't understand the issue here `train_dreambooth.py` fine-tunes the whole model and not just some lora weights

**Comment by nayan-dhabarde** [comment]
@patrickvonplaten Should I be expecting the similar results when  using same parameters such max_train_steps, num_class_images, class images itself, training images, and all other parameters while training when i use
1. train_dreambooth.py
2. train_dreambooth_lora.py
basically if i run inference on output of 1 and 2 with same prompts. I see that lora one is not showing the features of the training images at all.
But I used exact same configuration and used script train_dreambooth.py. I can see the face features.
The inference script is same as the one used in your examples and README
