### ISSUE TITLE
[SDXL 1.0]Slow compilation caused by torch.nonzero in scheduling_euler_discrete.py

### ISSUE THREAD

**Issue by kevint324** [huggingface/diffusers#4334]
**Is your feature request related to a problem? Please describe.**
Yes. The problem is slow compilation caused by torch.nonzero.

I'm running the diffuser with a TPU-like device with a XLA backend.
It works great with the huggingface diffusers on models like stable-diffusion 1/2.

Today I was trying the recently released [stabilityai/stable-diffusion-xl-base-1.0](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0) model and noticed the performance is really poor.

I found the cause of performance degration is that the model is recompiling the graph for each iteration.
The only difference in each traced graph if casued by the nonzero calls from [here](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_euler_discrete.py#L203), [here](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_euler_discrete.py#L364) and [here](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_euler_discrete.py#L422), 

It is a known issue that [nonzero could be a performance disaster](https://pytorch.org/xla/release/1.13/index.html#known-performance-caveats) for XLA backend device.

**Describe the solution you'd like**
As nonzero really causes trouble for XLA (and other graph compiler as well), is there a workaround or replacement for the nonzero?

**Describe alternatives you've considered**
Anything that could workaround the dynamic shapes.

**Additional context**

The traced hlo , 3 out of 32300 lines are different

![image](https://github.com/huggingface/diffusers/assets/8800468/0e04f650-5d3e-4df6-909d-58ed8d278a95)

Thanks. Great work!

**Comment by kevint324** [comment]
oh , I just found the exact same issue report here https://github.com/huggingface/diffusers/issues/3950
I'll try it out

**Comment by patrickvonplaten** [comment]
Yes indeed related to #3950 . Also cc @pcuenca
