### ISSUE TITLE
Feature extraction from Unet of Stable Diffusion

### ISSUE THREAD

**Issue by danushv07** [huggingface/diffusers#4336]
Thanks to the HF community for this wonderful library. I'm currently working on a project where we are interested in looking into the intermediate features(feature maps from different layers) of the Unet in Stable diffusion model.

The `transformers` library has the option of `output_hidden_states` to extract the intermediate features from a transformer model. Similarly, is there an option to do so from the `StableDiffusionPipeline` ? I couldn't find an option for this, but please correct me if I'm wrong here.

If there's isn't an option, we would like to have one. I would be interested in working on this as a project also.

**Comment by sayakpaul** [comment]
Since this feature is not a widely requested one, we are currently not prioritizing it. 

@patrickvonplaten @williamberman what are your thoughts?

**Comment by danushv07** [comment]
@sayakpaul thanks for the reply.  There are few projects that focus on extracting features from SD models (especially from the Unet). I would like to work on this and submit it as a PR. If this still satisfies as a need (maybe in the future) you can definitely merge it.

**Comment by williamberman** [comment]
I understand the use case but I think we might need to see a few more requests for it before adding? I think the needed code is small enough if someone wants to extract intermediate results for a one off project. Perfectly reasonable feature though if more people request it

**Comment by aisagarw** [comment]
Do we have this functionality anywhere now? I too was looking at extracting features from the Unet of Stable Diffusion..

**Comment by aisagarw** [comment]
@danushv07 were you able to figure out the same? Thanks in advance!
