### ISSUE TITLE
shrek why StableDiffusionXLPipeline.from_single_file() still tries to load from 🤗 hub.i thought its meant for local?

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [huggingface/diffusers#4345]
**What API design would you like to have changed or added to the library? Why?**
make StableDiffusionXLPipeline.from_single_file() only load from local,aka make it normal shrek.
is it a intentional design to practically make StableDiffusionXLPipeline.from_single_file() a wrapper for from_pretrained()?
😄 if yes i probably need to give 🤗 a 🤗 to make the api more logical and consistent, 

**What use case would this enable or better enable? Can you give us a code example?**
you can just download the safetensor from hf site and load it locally.
why bother ping 🤗 hub and waste 🤗 server bandwidth more and make 🤗  become 😫

**Comment by patrickvonplaten** [comment]
haha thanks for using all them smileys

**Comment by patrickvonplaten** [comment]
did this PR solve it: https://github.com/huggingface/diffusers/pull/4271

Otherwise - I agree with you, when passing `local_files_only=True` to `from_single_file()` no internet connection should be needed. Let me know if the PR doesn't solve it

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
Hmm let me try it.will reply in a few days

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
it works with properly now.closes issue.
