### ISSUE TITLE
StableDiffusionUpscalePipeline fails without a text_encoder despite prompt_embeds being already encoded

### ISSUE THREAD

**Issue by keturn** [huggingface/diffusers#4349]
### Describe the bug

When we've already constructed `prompt_embeds`, StableDiffusionUpscalePipeline shouldn't require a tokenizer or text encoder, since there's no more tokenizing or text encoding to do. But it fails, as it references the encoder anyway.

Similar use case to #4249.

I think there are a **lot** of pipelines written to accept either `prompt` _or_ `prompt_embeds`. That means it's likely this isn't the only pipeline with this bug; maybe there's an opportunity to factor out some common logic.

This issue was discovered while attempting to integrate this upscaler in InvokeAI: https://github.com/invoke-ai/InvokeAI/pull/3996

### Reproduction

```py
import requests
from PIL import Image
from io import BytesIO
from diffusers import StableDiffusionUpscalePipeline
import torch
from compel import Compel

# load model and scheduler
model_id = "stabilityai/stable-diffusion-x4-upscaler"
pipeline = StableDiffusionUpscalePipeline.from_pretrained(model_id, variant="fp16", torch_dtype=torch.float16)
pipeline = pipeline.to("cuda")

# construct prompt embeddings
prompt = "a white cat"
compel = Compel(tokenizer=pipeline.tokenizer, text_encoder=pipeline.text_encoder)
conditioning = compel.build_conditioning_tensor(prompt)

# that done, we don't need the text_encoder or tokenizer anymore

pipeline = StableDiffusionUpscalePipeline(
    text_encoder=None,
    tokenizer=None,
    vae=pipeline.vae,
    unet=pipeline.unet,
    scheduler=pipeline.scheduler,
    low_res_scheduler=pipeline.low_res_scheduler)

# let's download an  image
url = "https://huggingface.co/datasets/hf-internal-testing/diffusers-images/resolve/main/sd2-upscale/low_res_cat.png"
response = requests.get(url)
low_res_img = Image.open(BytesIO(response.content)).convert("RGB")
low_res_img = low_res_img.resize((128, 128))

upscaled_image = pipeline(prompt_embeds=conditioning, image=low_res_img).images[0]
```

### Logs

```
diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py:271, in StableDiffusionUpscalePipeline._encode_prompt(self, prompt, device, num_images_per_prompt, do_classifier_free_guidance, negative_prompt, prompt_embeds, negative_prompt_embeds, lora_scale)
--> 271 prompt_embeds = prompt_embeds.to(dtype=self.text_encoder.dtype, device=device)
AttributeError: 'NoneType' object has no attribute 'dtype'
```

### System Info

- `diffusers` version: 0.19.2
- Platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
- Python version: 3.11.4
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: yes, nvidia RTX
- Using distributed or parallel set-up in script?: no

**Comment by bghira** [comment]
i looked at this one and it seems like the torch dtype can be grabbed from the init in the super class, but it isn't currently stored there. @keturn is this something you wanted to take on for a simple fix or are you wanting a more comprehensive solution ? or, leaving it up to others? i can do this simple fix, and even something more comprehensive but i'm not sure of the direction @sayakpaul or @patrickvonplaten would take with something more invasive.

**Comment by sayakpaul** [comment]
Hmm thanks for reporting. Indeed we maybe have surfaced this bug in other pipelines too. 

A related discussion is happening here: https://github.com/huggingface/diffusers/issues/4140 that concerns tackling the `encode_prompt()` function. 

As you would see in that thread, different pipelines have slightly different ways of achieving this. So, this is why we have an `encode_prompt()` is all the pipelines except for the ones where it can be directly copied from another one. In that case, we add a "Copied from ..." comment on top of the method. 

So taking this info into consideration, let's maybe discuss here a bit about the design and then happy to proceed with a PR and keep you folks looped in :) 

Cc: @patrickvonplaten @yiyixuxu @williamberman @DN6

**Comment by williamberman** [comment]
Ah yeah thanks for bringing this up -- fixed here https://github.com/huggingface/diffusers/pull/4396
