### ISSUE TITLE
SDXL image generation bug, has poor quality.

### ISSUE THREAD

**Issue by conansherry** [huggingface/diffusers#4353]
### Describe the bug

All images generate some green-red blobs
![Snipaste_2023-07-29_12-15-45](https://github.com/huggingface/diffusers/assets/2148224/b5d758d7-2838-42e2-b0f7-b74baaf019fe)
![Snipaste_2023-07-29_12-16-09](https://github.com/huggingface/diffusers/assets/2148224/309f0e40-b6ac-4a31-a428-484ed2c6fa10)

### Reproduction

```
from diffusers import DiffusionPipeline
from diffusers import StableDiffusionXLPipeline, StableDiffusionXLImg2ImgPipeline
import torch

base = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
base.to("cuda")

use_refine = False

if use_refine:
    refiner = DiffusionPipeline.from_pretrained(
        "stabilityai/stable-diffusion-xl-refiner-1.0",
        text_encoder_2=base.text_encoder_2,
        vae=base.vae,
        torch_dtype=torch.float16,
        use_safetensors=True,
        variant="fp16",
    )
    refiner.to("cuda")

seed = torch.Generator('cuda').manual_seed(12345)
prompt = "A majestic lion jumping from a big stone at night"
negative_prompt = ""
base_image = base(prompt=prompt, 
                  negative_prompt=negative_prompt, 
                  generator=seed, 
                  output_type='latent' if use_refine else 'pil'
                  ).images[0]

if not use_refine:
    base_image.save('test_base.png')
else:
    refine_image = refiner(
        prompt=prompt,
        negative_prompt=negative_prompt, 
        image=base_image[None, :],
    ).images[0]
    refine_image.save('test_refine.png')
print('')
```

### System Info

diffusers 0.19.2

**Comment by conansherry** [comment]
more reulst
![image](https://github.com/huggingface/diffusers/assets/2148224/e8060914-86ed-4dcd-bfdb-eeae3fc5ef55)
![image](https://github.com/huggingface/diffusers/assets/2148224/fbc4319d-40b3-4619-bcaf-5c7c0a9cdbb6)

**Comment by conansherry** [comment]
compare with A1111 WEBUI which is OK
![image](https://github.com/huggingface/diffusers/assets/2148224/d6183dc0-e4f3-4db6-8f6c-4b4cb9f7ae9e)

**Comment by conansherry** [comment]
I found the problem is watermarker = true

**Comment by FeiiYin** [comment]
> I found the problem: watermarker = true add_watermarker=False, everything is ok.

@conansherry Hi, watermarker parameters should be passed to which function? Many thx!

**Comment by patrickvonplaten** [comment]
Yes it's indeed the watermarker here

**Comment by patrickvonplaten** [comment]
See: https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl#watermarker
