### ISSUE TITLE
launch issue of Stable Diffusion UI with Python error

### ISSUE THREAD

**Issue by gotosoda** [huggingface/diffusers#4359]
After doing a git pull for the lat latest update , Stable Diffusion will not loadthe UI and i get the folling error(s)

error: Your local changes to the following files would be overwritten by merge:
        launch.py
        modules/styles.py
Please commit your changes or stash them before you merge.
Aborting
Updating 22bcc7be..68f336bd
venv "D:\AI\StableDiffusionAUTO1111\stable-diffusion-webui\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "D:\AI\StableDiffusionAUTO1111\stable-diffusion-webui\launch.py", line 1, in <module>
    from modules import launch_utils
ImportError: cannot import name 'launch_utils' from 'modules' (unknown location)

**Comment by sayakpaul** [comment]
It does not seem to be `diffusers` problem.
