### ISSUE TITLE
how can i run lora training with sdxl1.0 on google colab?

### ISSUE THREAD

**Issue by frankchieng** [huggingface/diffusers#4360]
git clone https://github.com/huggingface/diffusers
cd diffusers
pip install -e .

after i run the above code on colab and finish lora training,then execute the following python code:

from huggingface_hub.repocard import RepoCard
from diffusers import DiffusionPipeline
import torch

lora_model_id = "lora-trained-xl"
card = RepoCard.load(lora_model_id)
base_model_id = card.data.to_dict()["base_model"]

pipe = DiffusionPipeline.from_pretrained(base_model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")
pipe.load_lora_weights(lora_model_id)
image = pipe("A picture of a sks dog in a bucket", num_inference_steps=25).images[0]
image.save("sks_dog.png")

ImportError: cannot import name 'DiffusionPipeline' from 'diffusers' (unknown location) appears? is there any dependency missing or the cloud computation platform is different with local environment?i'm totally confused

**Comment by MaxTran96** [comment]
Following

**Comment by frankchieng** [comment]
this problem solved, but when i train lora thr Zero-2 stage of deepspeed and offload optimizer states and parameters to CPU, torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 14.75 GiB total capacity; 14.06 GiB already allocated; 8.81 MiB free; 14.38 GiB reserved in total by PyTorch) 
why GPU VRAM is always so highly occupied?
![1690709364251](https://github.com/huggingface/diffusers/assets/130369523/11750e97-69d3-4da5-b061-680536199323)

**Comment by patrickvonplaten** [comment]
Uff that will be a tough one if you don't have a A100 on a google colab. How much memory does a T4 give you?

**Comment by frankchieng** [comment]
> 

For colab Pro member,25G VRAM CPU and 16G GPU RAM,A100 is much more expensive,as far as i know,lora sdxl 1.0 can be trained on colab with 16G GPU well using python script

**Comment by patrickvonplaten** [comment]
Actually we will get some additional memory savings when fixing: https://github.com/huggingface/diffusers/issues/4377
