### ISSUE TITLE
Please support from_single_file() for AutoPipeline 

### ISSUE THREAD

**Issue by wodsoe** [huggingface/diffusers#4367]
Please support from_single_file() for AutoPipeline!!!

**Comment by patrickvonplaten** [comment]
`from_single_file` only makes sense for Stable Diffusion Pipelines not for other pipelines of `diffusers` such as Kandinsky, IF, Karlo, ... whereas `AutoPipeline` is meant to be used for all pipelines.

**Comment by n00mkrad** [comment]
> Could you make SDAutoPipeline with from_single_file() ?

I think that's impossible because single files don't contain any information about the architecture they're for.

**Comment by sayakpaul** [comment]
Precisely https://github.com/huggingface/diffusers/issues/4367#issuecomment-1657117702
