### ISSUE TITLE
original_size, and target_size have no impact for StableDiffusionXL

### ISSUE THREAD

**Issue by GeorgePearse** [huggingface/diffusers#4372]
### Describe the bug

height and width get set to defaults despite use of original_size or target_size. I think the order of the pairs of lines need to be swapped. 

### Reproduction

```
from diffusers import StableDiffusionXLPipeline
import torch

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
pipe.to("cuda")

prompt = "a drawing of a circle"
image = pipe(
    prompt=prompt, 
    num_inference_steps=5,
    target_size=(1920,1080),
).images[0]

assert image.size == (1920, 1080), 'target_size has not worked as expected'
```

Responsible lines 
```shell
# 0. Default height and width to unet
height = height or self.default_sample_size * self.vae_scale_factor
width = width or self.default_sample_size * self.vae_scale_factor

original_size = original_size or (height, width)
target_size = target_size or (height, width)
```
```


### System Info

![image](https://github.com/huggingface/diffusers/assets/47161914/bc269d00-932e-4e0e-bddb-b2d96574c31f)

**Comment by bghira** [comment]
that doesn't actually change the resulting image size. those are `width` and `height` parameters.

the target_w/h parameters are just conditionings to tell the model you want to pull from that part of the data distribution.

**Comment by GeorgePearse** [comment]
I'm using the code, and width and height successfully impact the output image, original_size and target_size do absolutely nothing because of the order in which they're defined, e.g. they're just set to the values of height and width, which themselves are just set to defaults.

**Comment by bghira** [comment]
If target_size is not None or another falsy value, it will remain as its current value.

If target_size is None or another falsy value, it will be set to (height, width).

the values of target_size are not overridden if they are already provided and are valid.

**Comment by bghira** [comment]
the `height` and `width` parameters define the *actual* size of the image.

target_w / target_h and crop_w / crop_h are different conditioning inputs, and unrelated to the **size**.

**Comment by GeorgePearse** [comment]
Thanks! Complete error in my understanding of the docstrings

**Comment by hashnimo** [comment]
Finally someone asked the question. I was also confused with the Hugging Face SDXL documentation because there was no mention about the width and height parameters.

This helped a lot.

**Comment by sayakpaul** [comment]
Feel free to open a PR if you think the documentation could be improved.
