### ISSUE TITLE
Issue in StableDiffusionControlNetInpaintPipeline 

### ISSUE THREAD

**Issue by Onkarsus13** [huggingface/diffusers#4374]
### Describe the bug

<img width="784" alt="Screenshot 2023-07-30 at 5 18 28 PM" src="https://github.com/huggingface/diffusers/assets/46415298/4fdcc8df-460b-44d6-b7b9-4d64377dfc58">

there is one small mistake in the "StableDiffusionControlnetInpaintPipeline",

in line 1268
 `control_model_input` shoud have 9 dimentions 

here only 4 dims are there

it shoud be concatinated input 

`latent_model_input = torch.cat([control_model_input, mask, masked_image_latents], dim=1)`

this is same input how we give to unet

### Reproduction

`latent_model_input = torch.cat([control_model_input, mask, masked_image_latents], dim=1)`

### System Info

I am using current version of Diffuser

### Who can help?

@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @Onkarsus13 could you add a code snippet showing when an error is produced?

**Comment by Onkarsus13** [comment]
<img width="821" alt="Screenshot 2023-08-04 at 9 44 49 AM" src="https://github.com/huggingface/diffusers/assets/46415298/6d150b0c-9e3e-4689-8a4a-789af5560fb8">

`control_model_input` shoud be the concatination of  ("noisy_latent, mask_image_latent and mask")

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu

**Comment by 2213601279** [comment]
yean,And i also have this error, also StableDiffusionControlNetInpaintPipeline。
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead

**Comment by 2213601279** [comment]
@patrickvonplaten

**Comment by patrickvonplaten** [comment]
@yiyixuxu can you take a look here?

**Comment by Onkarsus13** [comment]
https://github.com/Onkarsus13/Diff_SceneTextEraser
You can check my customized github repo i have solved this issue

**Comment by yiyixuxu** [comment]
Sorry, there is not enough information here for me to reproduce the error

@Onkarsus13 @2213601279  @junnikokuki 
can any of you provide a reproducible code example that causes the error? 

Here is an example of a "reproducible code example". This exact example runs fine. I would really appreciate if you provide one that's not and I can get an error when I run it and debug from here

thanks :) 

```python
# !pip install transformers accelerate
from diffusers import StableDiffusionControlNetInpaintPipeline, ControlNetModel, DDIMScheduler
from diffusers.utils import load_image
import numpy as np
import torch

init_image = load_image(
    "https://huggingface.co/datasets/diffusers/test-arrays/resolve/main/stable_diffusion_inpaint/boy.png"
)
init_image = init_image.resize((512, 512))

generator = torch.Generator(device="cpu").manual_seed(1)

mask_image = load_image(
    "https://huggingface.co/datasets/diffusers/test-arrays/resolve/main/stable_diffusion_inpaint/boy_mask.png"
)
mask_image = mask_image.resize((512, 512))


def make_inpaint_condition(image, image_mask):
    image = np.array(image.convert("RGB")).astype(np.float32) / 255.0
    image_mask = np.array(image_mask.convert("L")).astype(np.float32) / 255.0

    assert image.shape[0:1] == image_mask.shape[0:1], "image and image_mask must have the same image size"
    image[image_mask > 0.5] = -1.0  # set as masked pixel
    image = np.expand_dims(image, 0).transpose(0, 3, 1, 2)
    image = torch.from_numpy(image)
    return image


control_image = make_inpaint_condition(init_image, mask_image)

controlnet = ControlNetModel.from_pretrained(
    "lllyasviel/control_v11p_sd15_inpaint", torch_dtype=torch.float16
)
pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16
)

pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()

# generate image
image = pipe(
    "a handsome man with ray-ban sunglasses",
    num_inference_steps=20,
    generator=generator,
    eta=1.0,
    image=init_image,
    mask_image=mask_image,
    control_image=control_image,
).images[0]
```

**Comment by yiyixuxu** [comment]
@Onkarsus13 could you share your colab maybe?

**Comment by Onkarsus13** [comment]
Hii @yiyixuxu  
Issue is resolved, With the above code its working now 
But what i feel, Control_model_input shoud be the concationation of (noisy_latent, mask, masked_image_latent)
So that model will learn more. just a experiment actually :)

**Comment by 2213601279** [comment]
@Onkarsus13 https://github.com/Onkarsus13/Diff_SceneTextEraser

**Comment by 2213601279** [comment]
@Onkarsus13 https://github.com/Onkarsus13/Diff_SceneTextEraser
