### ISSUE TITLE
StableDiffusionXLPipeline crashes when calling load_textual_inversion

### ISSUE THREAD

**Issue by frankjoshua** [huggingface/diffusers#4376]
### Describe the bug

The documentation shows that SDXL supports textual inversion.

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    pipe.load_textual_inversion("./embedding.pt")
  File "/opt/venv/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'load_textual_inversion'

### Reproduction

from diffusers import StableDiffusionXLPipeline
import torch

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
pipe.load_textual_inversion("./embedding.pt")
pipe.to("cuda")

prompt = "Astronaut in a jungle, cold color palette, muted colors, detailed, 8k"
image = pipe(prompt=prompt).images[0]

### System Info

- `diffusers` version: 0.19.2
- Platform: Linux-5.19.0-50-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: 0.0.20
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by CoffeeVampir3** [comment]
I can confirm this is an issue, I was able to reproduce this on the bleeding edge of diffusers. It looks like the TI Mixin is missing entirely, but because of the multiple text encoders I'm not sure this will actually work correctly. In any case, I can confirm that on
`diffusers                     0.20.0.dev0`

This issue persists, and the code appears to simply not be present to perform the operation.

Error for reference:
```
Traceback (most recent call last):
  File "/home/blackroot/Desktop/tachyon-j/t.py", line 82, in <module>
    pipe.load_textual_inversion("ti-test.safetensors")
  File "/home/blackroot/mambaforge/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'load_textual_inversion'
```

**Comment by patrickvonplaten** [comment]
We don't have support yet for textual inversion for Stable Diffusion XL.

Might be worth adding though cc @sayakpaul

**Comment by frankjoshua** [comment]
The reason I created the issue is because the documentation indicated that it should work. Also, yes this is a very desirable feature.

https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/stable_diffusion_xl#diffusers.StableDiffusionXLImg2ImgPipeline

In addition the pipeline inherits the following loading methods:

Textual-Inversion: [loaders.TextualInversionLoaderMixin.load_textual_inversion()](https://huggingface.co/docs/diffusers/v0.19.3/en/api/pipelines/stable_diffusion/inpaint#diffusers.StableDiffusionInpaintPipeline.load_textual_inversion)
LoRA: [loaders.LoraLoaderMixin.load_lora_weights()](https://huggingface.co/docs/diffusers/v0.19.3/en/api/pipelines/stable_diffusion/inpaint#diffusers.StableDiffusionInpaintPipeline.load_lora_weights)
Ckpt: [loaders.FromSingleFileMixin.from_single_file()](https://huggingface.co/docs/diffusers/v0.19.3/en/api/pipelines/stable_diffusion/img2img#diffusers.StableDiffusionImg2ImgPipeline.from_single_file)
