### ISSUE TITLE
Lora extension with weight

### ISSUE THREAD

**Issue by Gynjn** [huggingface/diffusers#4379]
First of all. Thank you for your effort.

I have some question when loading lora weight in sd.

1. Is it the right way that putting sd model in this way? I mean it doesn't have to be converted with like "convert_models_diffuser_to_diffusers.py" in diffusers?

`model_base = "/hdd/jinnnn/anylora.safetensors"`
`pipeline = StableDiffusionImg2ImgPipeline.from_single_file(model_base, 
                                         torch_dtype=torch.float16, safety_checker=None,
                                         requires_safety_checker=False).to('cuda')`

2. When loading lora weight in format of autimatic1111 with this line, the safetensors file must be in the ./ directory, right?

`pipeline.load_lora_weights(".", weight_name="light_and_shadow.safetensors")`

3. Then how can I adjust the weight of the lora weight like `<lora:light_and_shadow:0.7>` in webui? 
Is there any option that put any argument like "lora_weight" in "load_lora_weights" function?

4. How can I use the trigger word in prompt? For example if my trigger word is 'iom', just putting 'iom' in my prompt is applied in generation?
In connection with question 3, can I adjust the lora applied weight with text prompt?

**Comment by Gynjn** [comment]
Also, when using `load_lora_weights` is it automatically setting the rank and alpha that was used in trainig in webui?

**Comment by sayakpaul** [comment]
> When loading lora weight in format of autimatic1111 with this line, the safetensors file must be in the ./ directory, right?
> pipeline.load_lora_weights(".", weight_name="light_and_shadow.safetensors")

"." means the current working directory. You can specify any local directory. Or directly provide a suitable repo_id as shown in the docs: https://huggingface.co/docs/diffusers/main/en/training/lora#supporting-a1111-themed-lora-checkpoints-from-diffusers

> Then how can I adjust the weight of the lora weight like <lora:light_and_shadow:0.7> in webui?
Is there any option that put any argument like "lora_weight" in "load_lora_weights" function?

We don't support that. You can control the scale as shown in this document: https://huggingface.co/docs/diffusers/main/en/training/lora. 

> trigger word

Yeah you should include it in the prompt. Note that, diffusers natively doesn't support prompt weighting. 

> Also, when using load_lora_weights is it automatically setting the rank and alpha that was used in trainig in webui?

Alphas are automatically applied during `load_lora_weights()`. Regarding `scale`, I have already answered it.
