### ISSUE TITLE
HOW TO Overcoming the Influence of Seed and Enhancing the Role of Text Prompts

### ISSUE THREAD

**Issue by XiaoyuZhuang** [huggingface/diffusers#4382]
I fine-tuned a text2img model using Lora, based on the v1.5 version of stable diffusion. The results generated are very good.
But they can’t be controlled. It seems that the generated results are more based on the seed. Changing the seed changes the image, And if I don’t change the seed and only change the text prompt, the result doesn’t change, or there are only very slight changes. 
1. How should I solve this problem?
2. I would like to request a new feature that helps balance the influence between the seed and the prompt, as some questions are indeed sensitive to the seed.

**Comment by sayakpaul** [comment]
Feel free to ask this in our Discord community. 

Feel free to propose the design in a separate issue thread.
