### ISSUE TITLE
how can i put my controlnet model which is traind by train_controlnet.py to the automatic1111 ?

### ISSUE THREAD

**Issue by JaosonMa** [huggingface/diffusers#4383]
I have traind a controlnet model with the diffuser/examples/controlnet/train_controlnet.py，which i got a diffusion_pytorch_model.bin and a config.json。 how can i use them in stablediffusion webui? 
this is my files:
![image](https://github.com/huggingface/diffusers/assets/23551774/6b3fb235-f977-4cb7-9677-cbc45699c766)

this is the sdwebui/models/controlnet/files
![image](https://github.com/huggingface/diffusers/assets/23551774/ea96eb21-9fa4-49d2-a174-04d381f114cf)

**Comment by JaosonMa** [comment]
@patrickvonplaten

**Comment by sayakpaul** [comment]
You can use this script: https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_controlnet_to_diffusers.py.

**Comment by VV-A-VV** [comment]
> You can use this script: https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_controlnet_to_diffusers.py.

Hi,

It seems to be the script converts the original controlnet format to the diffuser format, and it cannot convert the diffuser models(with json configure file and .bin model checkpoint) to the format of original controlnet(with .ckpt or safetensor with yaml configure file).  

I have tried to use this script but it seems cannot deal with config.json file.  Anyone can help?
