### ISSUE TITLE
Anyone tried convert sdxl .safetensor lora yet? 

### ISSUE THREAD

**Issue by WaltBao** [huggingface/diffusers#4386]
I think [this script](https://github.com/huggingface/diffusers/blob/main/scripts/convert_lora_safetensor_to_diffusers.py) is not suitable for sdxl pipeline

**Comment by WaltBao** [comment]
More specifically, I'm using StablediffusionXLImg2ImgPipeline with sdxl refiner 1.0

**Comment by Gynjn** [comment]
Is it related with #4287?

**Comment by WaltBao** [comment]
> 

Thank you for reply, I tried this code: 

`from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-refiner-1.0", torch_dtype=torch.float16)
pipe.load_lora_weights(r"C:\Users\Admin\Downloads/sd_xl_offset_example-lora_1.0.safetensors")
pipe.to(torch_dtype=torch.float16)
pipe.to("cuda")

prompt = "beautiful scenery nature glass bottle landscape, , purple galaxy bottle"
negative_prompt = "text, watermark"

image = pipe(prompt, negative_prompt=negative_prompt, num_inference_steps=25).images[0]`

 but receiving this error: 
'CrossAttnDownBlock2D' object has no attribute '0'

**Comment by WaltBao** [comment]
The base model works fine, I would like to know how to load lora in img2img pipeline thank you

**Comment by sayakpaul** [comment]
We don't support img2img LoRAs. If you have an example LoRA (that is img2img) please link us to that.

**Comment by patrickvonplaten** [comment]
Think img2img LoRA should be exactly the same as t2i LoRA no?

**Comment by Gynjn** [comment]
> Think img2img LoRA should be exactly the same as t2i LoRA no?

Should be!

@sayakpaul 

> We don't support img2img LoRAs. If you have an example LoRA (that is img2img) please link us to that.

https://civitai.com/models/112902/dreamshaper-xl10-alpha2

https://civitai.com/models/118223/sdxloil-paintingoil-brush-stroke

The first one is base model and sceond one is lora file

**Comment by sayakpaul** [comment]
```python
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16)
pipe.load_lora_weights("stabilityai/stable-diffusion-xl-base-1.0", weight_name="sd_xl_offset_example-lora_1.0.safetensors")
pipe.to(torch_dtype=torch.float16)
pipe.to("cuda")

prompt = "beautiful scenery nature glass bottle landscape, purple galaxy bottle"
negative_prompt = "text, watermark"

image = pipe(prompt, negative_prompt=negative_prompt, num_inference_steps=25).images[0]
```

Colab here: https://colab.research.google.com/gist/sayakpaul/f8d9057bd1ae4d4f4ba276293d2d2574/scratchpad.ipynb. 

I am able to run this fine. 

Also @WaltBao, I am not sure if we should actually loading the LoRA with the refiner model since it was trained on the base model. 

@Gynjn please open a new ticket with the error trace and tag me :)
