### ISSUE TITLE
Question about text_encoder support in train_dreambooth_inpaint_lora.py

### ISSUE THREAD

**Issue by hlyu09** [huggingface/diffusers#4400]
Hi, it seems that although `args.train_text_encoder` is included in [train_dreambooth_inpaint_lora.py](https://github.com/huggingface/diffusers/blob/main/examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint_lora.py), the script does not add LoRA layers to the text encoder part. Is it safe to follow [this text2image example](https://github.com/huggingface/diffusers/blob/main/examples/research_projects/lora/train_text_to_image_lora.py) to add LoRA model to text encoders? Thanks!

(I also wanted to ask another question about inpainting fine-tuning if possible: I can only find dreambooth fine-tuning scripts for inpainting models. Is there a specific reason for the absence of the text2image fine-tuning scripts for inpainting models? Thanks!)

**Comment by sayakpaul** [comment]
> Is it safe to follow [this text2image example](https://github.com/huggingface/diffusers/blob/main/examples/research_projects/lora/train_text_to_image_lora.py) to add LoRA model to text encoders? Thanks!

Feel free to :) 

> (I also wanted to ask another question about inpainting fine-tuning if possible: I can only find dreambooth fine-tuning scripts for inpainting models. Is there a specific reason for the absence of the text2image fine-tuning scripts for inpainting models? Thanks!)

It's based on the community interest actually. Those examples are in the `research_projects` folder which we don't actively maintain.
