### ISSUE TITLE
StableDiffusionXLInpaintPipeline.from_single_file() cant correct use

### ISSUE THREAD

**Issue by skyheros001** [huggingface/diffusers#4402]
### Describe the bug

StableDiffusionXLInpaintPipeline.from_single_file(.....)

The pipe will become of type StableDiffusionXLPipeline and cannot be used

>>>Init_ Image=load_ Image (img_url). convert ("RGB")

>>>Mask_ Image=load_ Image (mask_url). convert ("RGB")

>>>Prompt="A Majestic tiger sitting on a bench"

>>>Image=pipe（

... prompt=prompt, image=init_ Image, mask_ Image=mask_ Image, num_ Inference_ Steps=50, length=0.80

...). images [0]

Is this a bug

### Reproduction

from diffusers import StableDiffusionXLInpaintPipeline
import gc
pipe = None
torch.cuda.empty_cache()
gc.collect()

pipe = StableDiffusionXLInpaintPipeline.from_single_file("R:/SDXL1.0UI/sd/model/base/GuoFeng4.1_2.5D_Beta.safetensors")
print(type(pipe))
pipe.to(torch_dtype=torch.float16)
pipe.to("cuda")
pipe.enable_model_cpu_offload()

image_inpainting = pipe(prompt=prompt, image=image_source_for_inpaint, mask_image=image_mask_for_inpaint, num_inference_steps=50, strength=0.80).images[0]

TypeError: StableDiffusionXLPipeline.__call__() got an unexpected keyword argument 'image'

### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.19.3
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@williamberman,@sayakpaul,@yiyixuxu

**Comment by sayakpaul** [comment]
Could you also provide the safetensors file you're using for reproducibility? Cc: @patrickvonplaten

**Comment by yiyixuxu** [comment]
I can reproduce this 

```python
from diffusers import StableDiffusionXLInpaintPipeline
import torch


pipe = StableDiffusionXLInpaintPipeline.from_single_file(
    "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_base_1.0.safetensors",
    torch_dtype=torch.float16, 
    use_safetensors=True)
print(type(pipe))
```

**Comment by yiyixuxu** [comment]
@skyheros001  

I fixed it here https://github.com/huggingface/diffusers/pull/4408
can you confirm it's working for you now?

**Comment by skyheros001** [comment]
> @skyheros001
> 
> 我修复了它#4408 你能确认它现在对你有用吗？

Thank you very much for your correction. It's very useful. Thank you ：）

**Comment by sayakpaul** [comment]
May I know why it was reopened?
