### ISSUE TITLE
"LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by andysingal** [huggingface/diffusers#4403]
### Describe the bug

Kaggle notebook, GPU P100

### Reproduction

```
from diffusers.utils import load_image

image = load_image(
    "https://hf.co/datasets/huggingface/documentation-images/resolve/main/diffusers/input_image_vermeer.png"
)
image

import cv2
from PIL import Image
import numpy as np

image = np.array(image)

low_threshold = 100
high_threshold = 200

image = cv2.Canny(image, low_threshold, high_threshold)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
canny_image = Image.fromarray(image)
canny_image

commandline_args = os.environ.get('COMMANDLINE_ARGS', "--skip-torch-cuda-test --no-half")

print('model load')
load_time = time.time()
controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-normal", torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    pretrained_model_name_or_path='runwayml/stable-diffusion-v1-5',
    torch_dtype=torch.float16,
    vae=AutoencoderKL.from_pretrained(
        pretrained_model_name_or_path='stabilityai/sdxl-vae',
        torch_dtype=torch.float16
    ),
    controlnet=controlnet,
    safety_checker=None,
    requires_safety_checker=False,

)

# pipe.load_lora_weights("/content/test_models.safetensors")

pipe.safety_checker = None if pipe.safety_checker is None else lambda images, **kwargs: (images, False)
pipe.enable_attention_slicing()

time_load = time.time() - load_time
print(f"Models loaded in {time_load:.2f}s")

generator = torch.Generator(device="cuda").manual_seed(2)
prompt = ["A victorian woman with blue eyes and red hair wearing intricate silver metal crystal, best quality, extremely detailed"]
pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config)

image = pipe(
    image=canny_image,
    prompt= prompt,
    generator=generator,
    num_inference_steps=28,
    guidance_scale=12.0,
    negative_prompt=["monochrome, lowres, bad anatomy, worst quality, low quality"]
).images[0]

display(image)

### Logs

```shell
same as above
```

### System Info

after looking at similar issues , i tried commandline_args = os.environ.get('COMMANDLINE_ARGS', "--skip-torch-cuda-test --no-half") but it did not work 

### Who can help?

@sayakpaul @patrickvonplaten @will

**Comment by sayakpaul** [comment]
It usually happens when you specify float16 data type but place your modules on the CPU. 

I don't see if you're using GPUs for executing the actual code. 

So, maybe just do: `pipe = pipe.to("cuda")` and hopefully, it will resolve the issue.

**Comment by andysingal** [comment]
i got a black image:
<img width="513" alt="Screenshot 2023-08-01 at 10 36 44 AM" src="https://github.com/huggingface/diffusers/assets/20493493/7c839443-9be4-4e59-a54b-600f25f721aa">
@sayakpaul can you please help on what is going wrong?

**Comment by sayakpaul** [comment]
Could you provide a Colab Notebook that reproduces this problem?

**Comment by andysingal** [comment]
https://colab.research.google.com/drive/1ugDzRm5qlyG7ynycv4weaCuiA5XIdtf2?usp=sharing
@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
The Colab Notebook has a lot of stuff. Could you please provide that just has the minimal code snippet to reproduce the problem?

**Comment by andysingal** [comment]
> 

i shared in the initial comment
@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
@andysingal a few things:

* The original code snippet you provided had multiple problems unrelated to the error you reported in this issue. Hence, I kept on asking for a minimal Colab Notebook. I created [this Colab Notebook](https://colab.research.google.com/gist/sayakpaul/a52faff7b93440ed5bb2ae21dbda5a9e/scratchpad.ipynb) hence. 
* You are using a canny filtered image as the conditioning image but you're using the wrong ControlNetModel: `"lllyasviel/sd-controlnet-normal"`. 
* You're also using the SDXL VAE to generate images with a SD pipeline. 
* Fixing the above checkpoint to `"lllyasviel/sd-controlnet-canny"` and the default SD VAE resolved the issue. You can check out the Colab Notebook here: https://colab.research.google.com/gist/sayakpaul/a52faff7b93440ed5bb2ae21dbda5a9e/scratchpad.ipynb. 

Going forward, let's, please try to respect what the maintainers are asking for :) 

Also, as we can see, this was not really an issue of `diffusers` in particular. So, I would suggest posting these issues on our Discord forum.

**Comment by andysingal** [comment]
> @andysingal a few things:
> 
> * The original code snippet you provided had multiple problems unrelated to the error you reported in this issue. Hence, I kept on asking for a minimal Colab Notebook. I created [this Colab Notebook](https://colab.research.google.com/gist/sayakpaul/a52faff7b93440ed5bb2ae21dbda5a9e/scratchpad.ipynb) hence.
> * You are using a canny filtered image as the conditioning image but you're using the wrong ControlNetModel: `"lllyasviel/sd-controlnet-normal"`.
> * You're also using the SDXL VAE to generate images with a SD pipeline.
> * Fixing the above checkpoint to `"lllyasviel/sd-controlnet-canny"` and the default SD VAE resolved the issue. You can check out the Colab Notebook here: https://colab.research.google.com/gist/sayakpaul/a52faff7b93440ed5bb2ae21dbda5a9e/scratchpad.ipynb.
> 
> Going forward, let's, please try to respect what the maintainers are asking for :)
> 
> Also, as we can see, this was not really an issue of `diffusers` in particular. So, I would suggest posting these issues on our Discord forum.

Any reason i cannot use a sd vae model other than default? @sayakpaul

**Comment by andysingal** [comment]
> pipe.to("cuda")

Thanks @sayakpaul , will do. I already shared the code but will be more precise. Thanks Again!!
