### ISSUE TITLE
[Examples] Create textual inversion training script for SDXL

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#4405]
We have training for textual inversion in place: https://github.com/huggingface/diffusers/tree/main/examples/textual_inversion. 

Might be worth adding one compatible with SDXL.

**Comment by AI-Casanova** [comment]
There are a few TI embeddings in the community already [Example](https://civitai.com/models/118418/negativexl) trained, I assume, on Kohya. It would be appreciated if the loading script for Diffusers was cross compatible (which would most likely just be a matter of being embedding size/order agnostic I assume)

Also users of SDNext would be thrilled if loading came before training.

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten for the loading the part as he brought in the support for this: 

<img width="979" alt="image" src="https://github.com/huggingface/diffusers/assets/22957388/6ea5a895-5ba3-456a-b8b6-ad5283ce3e0a">

(from [here](https://huggingface.co/docs/diffusers/api/loaders#diffusers.loaders.TextualInversionLoaderMixin.load_textual_inversion.example-2))

**Comment by patrickvonplaten** [comment]
@AI-Casanova can you point to some SDXL TI examples that we could use to implement a loading function?

**Comment by AI-Casanova** [comment]
@patrickvonplaten the most popular one on Civitai is linked above, and here is another https://civitai.com/models/119032/unaestheticxl-or-negative-ti

They are rare enough at the moment, likely because one has to be on A1111 Dev branch or Comfyui in order to use them.

**Comment by patrickvonplaten** [comment]
Cool, I'll give it a look :-)

**Comment by jelling** [comment]
> Also users of SDNext would be thrilled if loading came before training.

@patrickvonplaten can you comment on whether it will be possible to use existing TIs with XL? Or will fresh training be necessary?

**Comment by sayakpaul** [comment]
Fresh script and fresh training is necessary.

**Comment by alfredplpl** [comment]
@patrickvonplaten I would like to use negative TIs on a Hugging Face Space: https://huggingface.co/spaces/aipicasso/picasso-diffusion-latest-demo .
Are there any alternatives?

**Comment by alfredplpl** [comment]
Is this alternative method?
```
pipe = StableDiffusionXLPipeline.from_pretrained(model_id, torch_dtype=torch.float16)

embeddings_dict = {}
with safe_open("unaestheticXLv31.safetensors", framework="pt") as f:
    for k in f.keys():
        embeddings_dict[k] = f.get_tensor(k)

print(embeddings_dict["clip_l"].shape,embeddings_dict["clip_g"].shape)
unaestheticXLv31=""
for i in range(len(embeddings_dict["clip_l"])):
    token = f"sksd{chr(i+65)}"
    unaestheticXLv31 += token
    pipe.tokenizer.add_tokens(token)
    token_id = pipe.tokenizer.convert_tokens_to_ids(token)
    pipe.text_encoder.resize_token_embeddings(len(pipe.tokenizer))
    pipe.text_encoder_2.resize_token_embeddings(len(pipe.tokenizer))
    pipe.text_encoder.get_input_embeddings().weight.data[token_id] = embeddings_dict["clip_l"][i]
    pipe.text_encoder_2.get_input_embeddings().weight.data[token_id] = embeddings_dict["clip_g"][i]
```

However, I got the warning:
```
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embeding dimension will be 49409. This might induce some performance reduction as *Tensor Cores* will not be available. For more details  about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
```

How can I fix it?

**Comment by AI-Casanova** [comment]
@alfredplpl 
`pipe.text_encoder.resize_token_embeddings(len(pipe.tokenizer),pad_to_multiple_of=128)
 pipe.text_encoder_2.resize_token_embeddings(len(pipe.tokenizer),pad_to_multiple_of=128)`

Seems to work, and won't pad beyond what's necessary even with the loop.

**Comment by alfredplpl** [comment]
@AI-Casanova Thanks. I got it.

**Comment by oss-roettger** [comment]
Maybe this can help you to fix the TI huggingface pipeline for SDXL:
I' ve pnublished a TI stand-alone notebook that works for SDXL. Since it uses the huggigface API it should be easy for you to reuse it (most important: actually there are two embeddings to handle: one for text_encoder and also one for text_encoder_2):
https://github.com/oss-roettger/XL-Textual-Inversion

**Comment by alfredplpl** [comment]
@patrickvonplaten Thank you for your implementation. It works well.
https://github.com/huggingface/diffusers/blob/a139213578a2ec8cc0643877fa51caf59e13ed0e/docs/source/en/using-diffusers/textual_inversion_inference.md

@oss-roettger Thank you for your tips. It seems TI for SDXL is implemented.

**Comment by alfredplpl** [comment]
Now, we can load TI. But, we cannot create TI training script.

@sayakpaul I found the training code:
https://github.com/kohya-ss/sd-scripts/blob/main/sdxl_train_textual_inversion.py

It would be useful for us.

**Comment by alfredplpl** [comment]
@patrickvonplaten It might be a good idea to correct README.md. 
https://github.com/huggingface/diffusers/blob/a139213578a2ec8cc0643877fa51caf59e13ed0e/docs/source/en/using-diffusers/textual_inversion_inference.md

dn118 is not the TI creator.  Aikimi is the TI creator. Aikimi will maintain the TIs.
So, I denote the diff:
```python
- file = hf_hub_download("dn118/unaestheticXL", filename="unaestheticXLv31.safetensors")
+ file = hf_hub_download("Aikimi/unaestheticXL_Negative_TI", filename="unaestheticXLv31.safetensors")
```

Thanks in advance.

**Comment by bsun0802** [comment]
+1 the current textual_inversion.py not working if using `stabilityai/stable-diffusion-xl-base-1.0`, while `stabilityai/stable-diffusion-2` worked. 
```
Traceback (most recent call last):
  File "/home/bsunmiracle/diffusers/examples/textual_inversion/textual_inversion.py", line 992, in <module>
    main()
  File "/home/bsunmiracle/diffusers/examples/textual_inversion/textual_inversion.py", line 860, in main
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/bsunmiracle/local/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bsunmiracle/local/miniconda3/envs/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bsunmiracle/local/miniconda3/envs/diffusers/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 967, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kovtcharov** [comment]
I also recently ran into the error above. Curious if anyone has found a workaround.
