### ISSUE TITLE
Improve T2I Adapter Tests

### ISSUE THREAD

**Issue by DN6** [huggingface/diffusers#4416]
The current set of T2I adapter tests run a single test for multiple adapters. 
https://github.com/huggingface/diffusers/blob/6c49d542a352b556e412d8763592050d3a0dec77/tests/pipelines/stable_diffusion/test_stable_diffusion_adapter.py#L183-L293

These should be broken up into individual tests (since precision requirements can vary across Adapter conditions), similar to how the Controlnet tests are set up
https://github.com/huggingface/diffusers/blob/6c49d542a352b556e412d8763592050d3a0dec77/tests/pipelines/controlnet/test_controlnet.py

**Comment by patrickvonplaten** [comment]
Sounds good to me

**Comment by sayakpaul** [comment]
@DN6 is this still relevant?

**Comment by DN6** [comment]
We broke it up already. Closing as done
