### ISSUE TITLE
SDXL trained to use offset noise but not used in inference

### ISSUE THREAD

**Issue by samedii** [huggingface/diffusers#4419]
### Describe the bug

It sounds like they trained with offset noise but from I can tell the inference implementation does not use offset noise?
![image](https://github.com/huggingface/diffusers/assets/1872050/1078f8b0-8d7f-4c9e-a8c8-a88f832ae306)

https://arxiv.org/pdf/2307.01952.pdf

_I may have missed it of course but I've read through the sampler, pipeline and unet and I've searched the codebase for offset and 0.05._

### Reproduction

.

### System Info

Diffusers 0.19.3

### Who can help?

@patrickvonplaten

**Comment by samedii** [comment]
Maybe the intent of training with offset noise is to avoid having to add offset noise during inference?

**Comment by samedii** [comment]
Okay thanks for the answer!

**Comment by patrickvonplaten** [comment]
You can load the offset LoRA as follows:
https://github.com/huggingface/diffusers/releases/tag/v0.19.2
