### ISSUE TITLE
[SD-XL] Instruct Pix2Pix fine-tuning script unconditionally upcasts VAE to float32 when built-in VAE is used

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#4424]
```py
    # Move vae, unet and text_encoder to device and cast to weight_dtype
    # The VAE is in float32 to avoid NaN losses.
    if args.pretrained_vae_model_name_or_path is not None:
        vae.to(accelerator.device, dtype=weight_dtype)
    else:
        vae.to(accelerator.device, dtype=torch.float32)
```

I believe this causes the training to fail when operating in mixed precision, eg. `fp16` or `bf16`:

```
RuntimeError: Input type (c10::BFloat16) and bias type (float) should be the same
```

**Comment by sayakpaul** [comment]
It's not unconditional. 

When you supply a VAE that has better numerical behavior (such as: https://huggingface.co/madebyollin/sdxl-vae-fp16-fix), we don't do the upcast. Otherwise, we upcast. 

Could you help me try to reproduce this issue?

**Comment by bghira** [comment]
yes, use ptx0/s1 model that has the better vae included

**Comment by sayakpaul** [comment]
That is model specific then. In my experiments, the upcasting was needed for the worse VAE (with fp16). 

Feel free to reopen if the issue is persistent.

**Comment by bghira** [comment]
yes, but the model's scheduler config has it disabled. the training script needs to take this into consideration.

in fact, we can just pass the value through. the problem is that the VAE is being initialized without its config.

**Comment by sayakpaul** [comment]
Possible to maybe fix this in a PR?

**Comment by sayakpaul** [comment]
Done :-)

**Comment by bghira** [comment]
@github-actions bad bot
