### ISSUE TITLE
3D diffuser consists of Conv2D layers

### ISSUE THREAD

**Issue by Meghpal** [huggingface/diffusers#4425]
**What API design would you like to have changed or added to the library? Why?**
I was looking for unconditional 3D diffusion models and possibly creating it myself. However, the current 3d_conditional model that uses the 3Dblocks I was intending to use seem to not be 3D, but at the base they are Lora compatible conv2Ds. This part is confusing to me in terms of diffusion architecture, I was expecting usage of conv3Ds. Is there some hint for understanding why or how it currently works with 2D? Is these a lead on how to create an unconditional 3D diffusion model given the current modules?

**What use case would this enable or better enable? Can you give us a code example?**
Clueless right now, but looking into making custom 3D diffusion from scratch/TensorFlow basics.

**Comment by sayakpaul** [comment]
Well, that is because the underlying works that use those blocks don't rely on Conv2Ds. 

I would suggest you go through the following works to understand this a bit better:

* https://huggingface.co/papers/2303.08320
* https://huggingface.co/papers/2303.13439
