### ISSUE TITLE
Init_image behaviour is inconsistent across pipelines

### ISSUE THREAD

**Issue by antoche** [huggingface/diffusers#4429]
### Describe the bug

The expectations of image-to-image pipelines regarding the format of the input image are unclear and inconsistent:

- `StableDiffusionImg2ImgPipeline` can take a PIL Image, or a numpy float array in the range [0, 1], or a torch float tensor in the range [0, 1].
- `StableDiffusionInpaintPipeline` can take a PIL Image, or a numpy **uint8** array in the range **[0, 255]** (but the **mask** should be float [0,1]), or a torch float tensor in the range **[-1, 1]**
- `RePaintPipeline` can take a PIL Image, or a torch float tensor in the range **[-1, 1]**, and **cannot** take a numpy array.

These are only 3 examples based on my own use, I have not done an exhaustive audit of the myriad of pipelines in the project.

The docstrings are also out of date and/or inconsistent:
- `StableDiffusionImg2ImgPipeline` only says `torch.FloatTensor` or `PIL.Image.Image` and does not mention the expected type/range.
- `StableDiffusionInpaintPipeline` only says `PIL.Image.Image` and does not mention the expected type/range.
- `pipeline_stable_diffusion_img2img.py` still has a leftover unused `preprocess` function that implements the old input processing code.

I would expect the various pipelines taking similar inputs to have similar expectations and behaviors (ideally, the one encoded by `VaeImageProcessor` and used by `StableDiffusionImg2ImgPipeline` and some others). 

I thought #2304 was supposed to harmonize this API, and it certainly improved things for some pipelines, but not all pipelines appear to have been updated to follow the new standard.

These inconsistencies make it very difficult to use the `diffusers` library without having to write lots of boilerplate code specific to each pipeline just to massage the inputs into the various expected formats.

### Reproduction

No need to run anything.

### System Info

Audit run on 0.16.1, however a quick look at `main` doesn't seem to show much differences.

### Who can help?

@patrickvonplaten

**Comment by yiyixuxu** [comment]
@antoche 
thanks for the issue
we are on it! 😅

**Comment by antoche** [comment]
Related: https://github.com/huggingface/transformers/issues/25195

If passing a float tensor in [0,1] to `StableDiffusionDepth2ImgPipeline`, the computed depth map (and therefore the result of the pipeline) will be wrong when using transformers-4.31 because transformers automatically rescales the image. So even though `StableDiffusionDepth2ImgPipeline` can handle that type of input in `prepare_latents`, it will still give the wrong results.

**Comment by patrickvonplaten** [comment]
> * StableDiffusionInstructPix2PixPipeline

@yiyixuxu can we include those in your refactor PR?

**Comment by yiyixuxu** [comment]
ok - I think we will just have to use image_processor to process the depth map :)

**Comment by yiyixuxu** [comment]
I think so 

@antoche is there any pipeline I missed?

Thanks

YiYi
