### ISSUE TITLE
[CoreML] Make diffusers work natively with Mac CoreML

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#443]
Required changes to make diffusers work out of the book with CoreML: https://gist.github.com/madebyollin/86b9596ffa4ab0fa7674a16ca2aeab3d?permalink_comment_id=4295017

**Comment by patrickvonplaten** [comment]
cc @pcuenca @anton-l @patil-suraj

**Comment by pcuenca** [comment]
/cc @hollance too.

I can do some testing here.

**Comment by patil-suraj** [comment]
Fix is here #445, #446
