### ISSUE TITLE
segment anything model for text-guided image editing- GroundingDINO with SD

### ISSUE THREAD

**Issue by andysingal** [huggingface/diffusers#4433]
@patrickvonplaten  @sayakpaul  Any updates on this pipeline. I am trying to use GroundingDINO with Stable diffusion . While trying on a custom dataset i got the following error(Since there is no documentation of HF it would be a nice addition):
Issue: https://github.com/IDEA-Research/GroundingDINO/issues/184
Colab: https://colab.research.google.com/drive/1uObAs_PI6caKHhwZRN3mQSzkc3zxrkeR?usp=sharing
Dataset: https://www.kaggle.com/datasets/abbymorgan/animals-toy-dataset

**Comment by patrickvonplaten** [comment]
duplicate of https://github.com/huggingface/diffusers/issues/3019#issuecomment-1664487546

@andysingal as stated in the issue, please be mindful of the maintainers time. If everybody posts 10 questions related to personal questions per day, this library could not exist

**Comment by andysingal** [comment]
Dear Patrick,
      Thanks for your email. I usually ask after researching your previous
issues and non responsive discord channel. When I am left with no choice, I
end up sharing my concern on your issues board.

In regards to the below question there is a lot of research work done but
no documentation on GroundingDINO with stable diffusion , I ended up
creating a repo Andyrasika/GroundingDINO. I will try to add more as I work
on it.

I really appreciate all the work you all do to keep me motivated to learn
something new everyday. Thanks Again for all your team effort.

I will make sure to keep it minimal ☺️.

Have a good day!!
Best,
Ankush Singal
