### ISSUE TITLE
Converting CIVITAI safetensors with VAE to diffusers

### ISSUE THREAD

**Issue by sarmientoj24** [huggingface/diffusers#4436]
### Describe the bug

I can convert CIVITAI safetensors to diffusers. But most CIVITAI have VAE with them.
How do I convert CIVITAI safetensors w/ VAE to diffusers?

### Reproduction

Just using the script from diffusers

### System Info

Latest diffusers on Colab

**Comment by patrickvonplaten** [comment]
You can just use the official script for this: https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py

**Comment by alexblattner** [comment]
@patrickvonplaten how do you convert VAE too?

**Comment by Malrama** [comment]
@patrickvonplaten how do you convert VAE too?
