### ISSUE TITLE
StableDiffusionXLPipeline Error

### ISSUE THREAD

**Issue by Gynjn** [huggingface/diffusers#4438]
### Describe the bug

When I try to set the pipe with `StableDiffusionXLImg2ImgPipeline`, I think it returns the pipe with 'StableDiffusionXLPipeline'

I downloaded the model in civitiai

https://civitai.com/models/112902/dreamshaper-xl10-alpha2

https://civitai.com/models/118223/sdxloil-paintingoil-brush-stroke

### Reproduction

```
from diffusers import StableDiffusionXLImg2ImgPipeline
from diffusers.utils import load_image
from PIL import Image
import torch

pipe = StableDiffusionXLImg2ImgPipeline.from_single_file("/hdd/jinnnn/dreamshaperXL10_alpha2Xl10.safetensors", torch_dtype=torch.float16, variant="fp16", use_safetensors=True)
# pipe.load_lora_weights(".", weight_name="/hdd/jinnnn/oil_painting.safetensors")
pipe.to("cuda")

init_image = load_image("/hdd/jinnnn/arrange/IMG_2447.jpg").convert("RGB")

prompt = "a masterpiece, best quality, oil painting, 1boy"

negative_prompt = ("(low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2), blush"
                   "bad composition, inaccurate eyes, extra digit, fewer digits, (extra arms:1.2), large breasts")

pipe.safety_checker = None
pipe.requires_safety_checker = False

image = pipe(prompt, image=init_image).images[0]
```

### Logs

```shell
TypeError: StableDiffusionXLPipeline.__call__() got an unexpected keyword argument 'image'
```

### System Info

- `diffusers` version: 0.19.3
- Platform: Linux-4.15.0-166-generic-x86_64-with-glibc2.27
- Python version: 3.10.11
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.2
- Transformers version: 4.25.1
- Accelerate version: 0.18.0
- xFormers version: 0.0.20

### Who can help?

@patrickvonplaten @sayakpaul @williamberman

**Comment by sayakpaul** [comment]
This is likely happening because the definitions of `load_lora_weights()` and `save_lora_weights()` (irrelevant here but for comprehensiveness) are not there in the pipeline source. 

https://github.com/huggingface/diffusers/blob/816ca0048f7a38531a6f036299d2dd274abb5639/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L866

https://github.com/huggingface/diffusers/blob/816ca0048f7a38531a6f036299d2dd274abb5639/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L898

I think adding the `load_lora_weights()` method to `StableDiffusionXLImg2ImgPipeline` should solve the problem. 

If possible for you, would you maybe like to fix this and open a PR?

**Comment by Gynjn** [comment]
@sayakpaul I checked it with removing the line `load_lora_weight` but it keeps returning `StableDiffusionXLPipeline` type..

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten 

@yiyixuxu didn't you fix something similar yesterday?

**Comment by Gynjn** [comment]
I think the issue comes from `.from_single_file`

It returns the pipe type `StableDiffusionXLImg2ImgPipeline` when 

```
pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
```)

**Comment by yiyixuxu** [comment]
@Gynjn it has been fixed in here https://github.com/huggingface/diffusers/pull/4408

Install diffusers from the source, and your script should work

**Comment by Gynjn** [comment]
Got it. I checked it loading eaxct pipe type, but when I load lora it returns error 
`AttributeError: 'ModuleList' object has no attribute '4'`

Can you check it? @yiyixuxu

**Comment by Gynjn** [comment]
It seems it is related with #4456
