### ISSUE TITLE
IndexError on num_inference_steps values: 3, 9, 27, ...?

### ISSUE THREAD

**Issue by sausix** [huggingface/diffusers#444]
### Describe the bug

Some `num_inference_steps` values seem to be "problematic" and throw an IndexError.

Also the iteration status output does not end on that value in any relation. If it's on purpose, it's still confusing:

num_inference_steps: **5**
**6**it [00:49,  8.27s/it]

num_inference_steps: **6**
**8**it [01:02,  7.87s/it]

num_inference_steps: **7**
**9**it [01:10,  7.88s/it]

num_inference_steps: **8**
**9**it [01:13,  8.19s/it]

### Reproduction

```
from diffusers import StableDiffusionPipeline

TOKEN = "(censored)"
MODEL_ID = "CompVis/stable-diffusion-v1-4"

pipe = StableDiffusionPipeline.from_pretrained(MODEL_ID, use_auth_token=TOKEN)
res = pipe("a photo of an astronaut riding a horse on mars", num_inference_steps=3, guidance_scale=7.5)
```

Tested on command line too. Unrelated to PyCharm environment.

### Logs

```shell
/usr/bin/python3 /home/as/.config/JetBrains/PyCharm2022.2/scratches/scratch.py 

0it [00:07, ?it/s]
Traceback (most recent call last):
  File "/home/as/.config/JetBrains/PyCharm2022.2/scratches/scratch.py", line 7, in <module>
    res = pipe("a photo of an astronaut riding a horse on mars", num_inference_steps=3, guidance_scale=7.5)
  File "/home/as/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 148, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs)["prev_sample"]
  File "/usr/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 136, in step
    return self.step_plms(model_output=model_output, timestep=timestep, sample=sample)
  File "/usr/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 212, in step_plms
    prev_sample = self._get_prev_sample(sample, timestep, prev_timestep, model_output)
  File "/usr/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 230, in _get_prev_sample
    alpha_prod_t = self.alphas_cumprod[timestep + 1 - self._offset]
IndexError: index 1000 is out of bounds for dimension 0 with size 1000
```

### System Info

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-5.19.7-arch1-1-x86_64-with-glibc2.36
- Python version: 3.10.6
- PyTorch version (GPU?): 1.12.1+cu102 (True)
- Huggingface_hub version: 0.9.1
- Transformers version: 4.21.3
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by jonatanklosko** [comment]
I believe this is the issue well summarized in [this comment](https://github.com/CompVis/stable-diffusion/issues/111#issuecomment-1229483511).

The original bug comes from the `DDIMScheduler`:

```
>>> from diffusers import DDIMScheduler
>>> scheduler = DDIMScheduler()
>>> scheduler.set_timesteps(3, offset=1)
>>> scheduler.timesteps
tensor([1000,  667,  334,    1])
```

Note how the number of steps is not `3` as we specify.

The same off-by-1 issue is present in `PNDMScheduler`:

```
>>> from diffusers import PNDMScheduler
>>> scheduler = PNDMScheduler(skip_prk_steps=True)
>>> scheduler.set_timesteps(3, offset=1)
>>> scheduler.timesteps
[1000, 667, 667, 334, 1]
```

The expected number of steps is 4, and not 5. Sidenote: it is a bit confusing that `set_timesteps(3)` should result in 4 timesteps, but that's because it's actualy `set_timesteps(num_ddim_timesteps)`.

**Comment by jonatanklosko** [comment]
A loosely related question: why do we need the `offset` option? As far as I can see, the original implementation doesn't have a configurable offset and it is assumed to be 1. Also, in the stable diffusion pipeline it is always set to 1:

https://github.com/huggingface/diffusers/blob/5adb0a7bf7fee1732f307dfda9013bf2cf7b0ff9/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L220-L223

And it's not clear from the docs :D

https://github.com/huggingface/diffusers/blob/5adb0a7bf7fee1732f307dfda9013bf2cf7b0ff9/src/diffusers/schedulers/scheduling_pndm.py#L141

**Comment by sausix** [comment]
> I believe this is the issue well summarized in [this comment](https://github.com/CompVis/stable-diffusion/issues/111#issuecomment-1229483511).

I am sorry for opening duplicate report. Did not see that. I made a search for "num_inference_steps", not for "ddim_steps". But searching now for "num_inference_steps" also does not show this thread.

**Comment by jonatanklosko** [comment]
@sausix the issue I referenced is in another repository, so it's all good :)

**Comment by natolambert** [comment]
Thanks for all the details on this, I'm going to take a look.

**Comment by natolambert** [comment]
@jonatanklosko I wrote the scheduler docs and saw the offset parameter in multiple schedulers. When I worked on them more it wasn't there, so I need to do more reading before writing accurate docs, so I'll look at this too (maybe we should make another issue for it, depending on how fast all these can be solved).

**Comment by natolambert** [comment]
Okay, I've tracked down what `offset` is for, seems like it's used to make the final timestep of inference in stable diffusion `1` rather than zero.

You can see where it is used in diffusers with [this search](https://github.com/huggingface/diffusers/search?q=offset) (the stable diffusion pipelines). This is matching the stable diffusion implementation [here](https://github.com/CompVis/stable-diffusion/blob/69ae4b35e0a0f6ee1af8bb9a5d0016ccb27e36dc/ldm/modules/diffusionmodules/util.py#L56) (with a weird comment from the authors).

**Comment by jonatanklosko** [comment]
@natolambert yeah, my confusion was mostly that in the original implementation it is set to 1 and same in the stable diffusion pipeline, so I wondered if `offset=0` is ever used. Now I looked for [set_timesteps](https://github.com/huggingface/diffusers/search?q=set_timesteps) and looks like in most cases offset is not specified.

Interestingly in CompVis/latent-diffusion they also use offset of 1 ([ref](https://github.com/CompVis/latent-diffusion/blob/a506df5756472e2ebaf9078affdde2c4f1502cd4/ldm/modules/diffusionmodules/util.py#L57)), which is not the case in the latent diffusion pipeline ([ref](https://github.com/huggingface/diffusers/blob/f6fb3282b18f44f14bcb95a34a16203906df992a/src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py#L134)), not sure if that's expected or not.

Another possible inconsistency I found is this:

https://github.com/huggingface/diffusers/blob/8eaaa546d89f836b716e92348786d878f883ee86/src/diffusers/schedulers/scheduling_pndm.py#L338-L339

https://github.com/huggingface/diffusers/blob/8eaaa546d89f836b716e92348786d878f883ee86/src/diffusers/schedulers/scheduling_ddim.py#L204-L205

It's equivalent for `offset=1`, but not for `offset=0`

**Comment by natolambert** [comment]
Yeah I just realized the 1 vs `int` difference. I'm not sure, if you want more on that open another issue.

**Comment by natolambert** [comment]
@patrickvonplaten @patil-suraj, I'm not sure about the discrepancy @jonatanklosko brings up above with the indexing and offset. 

I vaguely remember there being some of the PNDM tests failing a while back confusing people. Maybe it was because this change was introduced? I'll keep looking a bit.

**Comment by natolambert** [comment]
@jonatanklosko I can tell you that the `PNDMScheduler` and `DDIMScheduler` have indexed the alpha's differently for a while. Before introducing offset, `PNDMScheduler` had

```
alpha_prod_t = self.alphas_cumprod[timestep + 1]
alpha_prod_t_prev = self.alphas_cumprod[timestep_prev + 1]
```

Though I'm not sure why `DDIMScheduler` isn't shifted by the offset.

**Comment by natolambert** [comment]
@jonatanklosko Can you make new issues for these? I don't love straying away from the original subject. Makes it harder for us to keep track of everything 🤗

**Comment by jonatanklosko** [comment]
@natolambert sure I will!

I'm also looking through https://github.com/openai/glide-text2im and I'm almost sure they don't use the 1 offset there, so maybe that's the reason for making it configurable.

**Comment by natolambert** [comment]
I opened #465 to keep this on track about the indexing error.

**Comment by jonatanklosko** [comment]
@natolambert perfect, thank you!

**Comment by natolambert** [comment]
Okay the power of 3 thing seems fixed in #466, I need to check the number of iterations though before merged. 

@sausix

**Comment by natolambert** [comment]
Okay, looks good to me, will close this issue as we will merge #466 shortly.

```bash
>>> res = pipe("a photo of an astronaut riding a horse on mars", num_inference_steps=3, guidance_scale=7.5)
100%|██████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:08<00:00,  2.02s/it]
>>> res = pipe("a photo of an astronaut riding a horse on mars", num_inference_steps=5, guidance_scale=7.5)
100%|██████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:08<00:00,  1.36s/it]
>>> res = pipe("a photo of an astronaut riding a horse on mars", num_inference_steps=6, guidance_scale=7.5)
100%|██████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.40s/it]
>>> res = pipe("a photo of an astronaut riding a horse on mars", num_inference_steps=7, guidance_scale=7.5)
100%|██████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:11<00:00,  1.44s/it]
>>> res = pipe("a photo of an astronaut riding a horse on mars", num_inference_steps=9, guidance_scale=7.5)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:14<00:00,  1.48s/it]

**Comment by sausix** [comment]
@natolambert Thank for fixing quickly.
Will test it tommorrow too. Found some other non 3 related iterations yesterday.

**Comment by patil-suraj** [comment]
> @natolambert yeah, my confusion was mostly that in the original implementation it is set to 1 and same in the stable diffusion pipeline, so I wondered if `offset=0` is ever used. Now I looked for [set_timesteps](https://github.com/huggingface/diffusers/search?q=set_timesteps) and looks like in most cases offset is not specified.
> 
> Interestingly in CompVis/latent-diffusion they also use offset of 1 ([ref](https://github.com/CompVis/latent-diffusion/blob/a506df5756472e2ebaf9078affdde2c4f1502cd4/ldm/modules/diffusionmodules/util.py#L57)), which is not the case in the latent diffusion pipeline ([ref](https://github.com/huggingface/diffusers/blob/f6fb3282b18f44f14bcb95a34a16203906df992a/src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py#L134)), not sure if that's expected or not.
> 
> Another possible inconsistency I found is this:
> 
> https://github.com/huggingface/diffusers/blob/8eaaa546d89f836b716e92348786d878f883ee86/src/diffusers/schedulers/scheduling_pndm.py#L338-L339
> 
> https://github.com/huggingface/diffusers/blob/8eaaa546d89f836b716e92348786d878f883ee86/src/diffusers/schedulers/scheduling_ddim.py#L204-L205
> 
> It's equivalent for `offset=1`, but not for `offset=0`

The offsetting is very specific to latnet/stable diffusion model, it's not used by other models like the original ddpm models. 
Also we should indeed update the latent diffusion pipeline to add the offset there. Feel free to open a PR if you want :)

**Comment by jonatanklosko** [comment]
@patil-suraj I'm happy to send a PR, but it seems to me that `offset` would make more sense as scheduler configuration field, rather than argument to `set_timestamps`, as mentioned in https://github.com/huggingface/diffusers/issues/465#issuecomment-1242818476, wdyt?

**Comment by patrickvonplaten** [comment]
Let's close the issue only when the PR is in main :-)
