### ISSUE TITLE
Disentangle ONNX and non-ONNX pipeline

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#4440]
The `OnnxStableDiffusionUpscalePipeline` pipeline should not inherit from `StableDiffusionUpscalePipeline`. This is not in-sync with our design philosophy and has led to multiple errors already as can be seen here: https://github.com/huggingface/diffusers/pull/2158#issuecomment-1650580180 .

Anybody keen on removing the inheritance and potentially fixing the error as well? cc @DN6 maybe?

Also cc @yiyixuxu @sayakpaul here

**Comment by sayakpaul** [comment]
I think these optimization-honed pipelines should be graduated to `optimum`.

**Comment by patrickvonplaten** [comment]
Agree

**Comment by sayakpaul** [comment]
Yeah. Would lean toward the latter. I think that is easier.

**Comment by DN6** [comment]
I can handle it 👍🏽
