### ISSUE TITLE
loading multi Lora models with different weights

### ISSUE THREAD

**Issue by zhaoyun0071** [huggingface/diffusers#4443]
Thank you to the developers for their great work. Currently, Diffusers has very complete functionality, especially in supporting single SD models.
However, in the AI painting industry, loading multi Lora models with different weights has been proven effective by many users. So, when can diffusers add multi  Lora models with different weights?
For example, in the following form:
`pipe.load_lora_weights(['lora1.safetensors','lora2.safetensors','lora3.safetensors'],weights=[0.1,0.4,0.5])`

**Comment by patrickvonplaten** [comment]
cc @sayakpaul here, but note that we don't have this fetaure supported yet and it will probably take a while until it's fully supported

**Comment by sayakpaul** [comment]
Yeah, currently it's not supported. It's being also discussed in #4348. So, I am gonna close this thread to consolidate efforts.
