### ISSUE TITLE
How to finetune lora model ?

### ISSUE THREAD

**Issue by kelisiya** [huggingface/diffusers#4445]
**Is your feature request related to a problem? Please describe.**
If I have a model from civitai , how  to finetune it in sd1.5 and sdxl?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by patrickvonplaten** [comment]
See: https://huggingface.co/docs/diffusers/v0.19.3/en/training/text2image#lora

**Comment by kelisiya** [comment]
> https://huggingface.co/docs/diffusers/v0.19.3/en/training/text2image#lora

I don't want to fine-tune the text2img model directly, but when I get a lora from civitai, I want to fine-tune the lora again to achieve better results, similar to getting a pre-trained lora

**Comment by kelisiya** [comment]
> See: https://huggingface.co/docs/diffusers/v0.19.3/en/training/text2image#lora

Although merging lora into sd can be trained, I also lose the parameter information of the existing lora, and the output lora will not match, which is undoubtedly very troublesome for fine-tuning.
