### ISSUE TITLE
Outpainting results from diffusers' StableDiffusionControlNetPipeline is much worse than those from A1111 webui. How to improve?

### ISSUE THREAD

**Issue by xiyichen** [huggingface/diffusers#4448]
I am trying to outpaint some human images (mainly the lower-body part) with SD 1.5 conditioned on ControlNet's inpainting and openpose. I have been using A1111 webui with ControlNet extension and it has been working quite well:
Here are my settings in the webui:
<img width="774" alt="Screenshot 2023-08-03 at 15 08 30" src="https://github.com/huggingface/diffusers/assets/50854238/f5d2ed63-bd8e-467a-81cb-28293eb45fe4">
![1691046578453](https://github.com/huggingface/diffusers/assets/50854238/8baf5891-6fe8-4006-bce9-bca903a3d6bf)
<img width="774" alt="Screenshot 2023-08-03 at 15 10 00" src="https://github.com/huggingface/diffusers/assets/50854238/8b9e6c76-3986-437a-9159-cb799d35131d">

Note that 2 ControlNet units are enabled, one for OpenPose and one for ControlNet's inpainting model. For OpenPose I enabled "Preview as Input" and upload my custom json file with all joints defined (although the lower-body joints are not visible in the input image).
Here is the result I get from the webui, which looks good:
![00001-2019210750](https://github.com/huggingface/diffusers/assets/50854238/491a2de1-180c-473d-83d0-44376c4cc7f1)

Now, I'm trying to reproduce this result using diffusers' StableDiffusionControlNetPipeline. Below is my code:

```
import numpy as np
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, DDIMScheduler
import torch
from diffusers.utils import load_image
import cv2
from PIL import Image

def make_inpaint_condition(image, image_mask):
    image = np.array(image.convert("RGB")).astype(np.float32) / 255.0
    image_mask = np.array(image_mask.convert("L")).astype(np.float32)
    assert image.shape[0:1] == image_mask.shape[0:1], "image and image_mask must have the same image size"
    image[image_mask < 128] = -1.0 # set as masked pixel
    image = np.expand_dims(image, 0).transpose(0, 3, 1, 2)
    image = torch.from_numpy(image)
    return image


controlnet_inpaint = ControlNetModel.from_pretrained('lllyasviel/control_v11p_sd15_inpaint', 
                                                      torch_dtype=torch.float16)
controlnet_openpose = ControlNetModel.from_pretrained('lllyasviel/control_v11p_sd15_openpose', 
                                                       torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                                         controlnet=[controlnet_inpaint, controlnet_openpose], 
                                                         torch_dtype=torch.float16, 
                                                         safety_checker=None).to('cuda')
pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()
pipe.enable_xformers_memory_efficient_attention()


                                                         
original_image = load_image('./image.png')
mask_image = load_image('./mask.png')
inpaint_condition_image = make_inpaint_condition(original_image, mask_image)
openpose_condition_image = load_image('./pose.png')
generated_img = pipe(prompt="best quality, photorealistic, empty background", 
     negative_prompt="lowres, bad hands, bad feet, worst quality",
     num_inference_steps=20,
     guidance_scale=10.0,
     image=[inpaint_condition_image, openpose_condition_image]).images[0]

generated_img.save('./test.png') 
```

and here is the result I get from diffusers:
![test (17)](https://github.com/huggingface/diffusers/assets/50854238/59fe3240-2650-4d9e-a46f-4359b368dc93)

The legs look much less realistic and the background is kind of noisy. I have been using the same SD model (sd v1.5), same controlnet models (v1.1 for OpenPose and inpainting), and same sampler (DDIM), but the results from diffusers are much worse than the webui. What can I do to reproduce the results I get from the webui?

It also seems that with the diffusers pipeline, the unmasked part is also slightly modified. Is there any post-processing applied to it?

**Comment by xiyichen** [comment]
![cn_test_2_2](https://github.com/huggingface/diffusers/assets/50854238/f547cda2-46b0-4ac7-8eac-3cbe171b3edf)
![image (17)](https://github.com/huggingface/diffusers/assets/50854238/a42fc440-3e27-4e6e-84ec-563fc59cf29b)

For this input, it seems human outpainting is not even working with diffusers.
webui result:
<img width="1410" alt="WX20230803-164929@2x" src="https://github.com/huggingface/diffusers/assets/50854238/4fea5167-e3a6-430e-8733-f9d9dbb95967">
diffusers result:
![test (18)](https://github.com/huggingface/diffusers/assets/50854238/853a85c5-e8a7-4ae8-8a6f-fa2960cf0f9f)

**Comment by xiyichen** [comment]
I switched to StableDiffusionControlNetInpaintPipeline and was able to get outpainting results with similar qualities to the webui.

**Comment by kelisiya** [comment]
Would you like to share your latest pipeline? I'm trying to reproduce the inference_only+lama in the webui, but I found that the strength is preserved in the diffusers, but not in the webui, I want to figure out how you align the results

**Comment by xiyichen** [comment]
You can checkout my pipeline [here](https://github.com/xiyichen/diffusers_scripts/blob/main/inpainting_scripts/inpainting_rv.py). I didn't try out lama though.

**Comment by kelisiya** [comment]
> You can checkout my pipeline [here](https://github.com/xiyichen/diffusers_scripts/blob/main/inpainting_scripts/inpainting_controlnet.py). I didn't try out lama though.

Have you tried to reproduce inpaint_only+lama choice in diffusers controlnet inpainting?
