### ISSUE TITLE
example/texual_inversion/   multi text inversion is actually not working.

### ISSUE THREAD

**Issue by Suho0922** [huggingface/diffusers#4450]
### Describe the bug

https://github.com/huggingface/diffusers/blob/4c4fe042a7f718f30f6bd897b967ff800e035347/examples/textual_inversion/textual_inversion.py#L629C1-L648
https://github.com/huggingface/diffusers/blob/4c4fe042a7f718f30f6bd897b967ff800e035347/examples/textual_inversion/textual_inversion.py#L706-L716https://github.com/huggingface/diffusers/blob/4c4fe042a7f718f30f6bd897b967ff800e035347/examples/textual_inversion/textual_inversion.py#L521C1-L537

code makes multiple placeholder and embeddings but the training text is using only placeholder token

### Reproduction

export MODEL_NAME="runwayml/stable-diffusion-v1-5"&&
export DATA_DIR="./cat"&&
accelerate launch textual_inversion.py \
	--num_vectors 4\
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$DATA_DIR \
  --learnable_property="object" \
  --placeholder_token="<cat>" --initializer_token="cat" \
	--output_dir="basic_multi_4_vectors_cat"\
	--validation_prompt="A photo of <cat>"\
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --max_train_steps=3000 \
  --learning_rate=5.0e-04 --scale_lr \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --save_as_full_pipeline \
	--num_validation_images=3\
	--validation_steps=100

### System Info

- `diffusers` version: 0.20.0.dev0
- Platform: Linux-5.4.0-1098-oracle-x86_64-with-debian-buster-sid
- Python version: 3.7.11
- PyTorch version (GPU?): 1.10.0 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
@sayakpaul any chance you have time to look into this?

**Comment by sayakpaul** [comment]
Sorry, I am a bit swamped at the moment. 

If no one picks up, I will try looking into it next week.

**Comment by sayakpaul** [comment]
But https://github.com/huggingface/diffusers/pull/4452 seems to be fixing this, though.

**Comment by patrickvonplaten** [comment]
Yeah actually #4452 seems to be the solution - thanks community :heart:
