### ISSUE TITLE
How to convert diffusers SDXL lora into safetensors that works with AUTO1111 webui

### ISSUE THREAD

**Issue by ljbq** [huggingface/diffusers#4453]
### Describe the bug

I trained a lora on SDXL with this diffusers script: https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sdxl.py

I get great results when using the output .bin with the diffusers inference code.
How can I convert the .bin to .safetensors that can be loaded in AUTO1111 webui?

### Reproduction

Train a lora on SDXL with this diffusers script: https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sdxl.py
The lora model cannot be loaded in AUTO1111 webui

### System Info

Python 3.10

**Comment by patrickvonplaten** [comment]
@ljbq we don't provide a conversion code yet sadly
