### ISSUE TITLE
The loaders load_lora_into_unet() function throw out "AttributeError: 'ModuleList' object has no attribute '4'"

### ISSUE THREAD

**Issue by xhinker** [huggingface/diffusers#4456]
### Describe the bug

In Diffusers Version: 0.20.0.dev0 

When loading SDXL LoRA to SDXL pipeline. 

Works by 

```python
lora_path = r"path/to/SDXLLoRA.safetensors"
base_pipe.load_lora_weights(lora_path)
```

However, when extracting state_dict, and network_alphas manually feed into unet like this:

```python
state_dict, network_alphas = base_pipe.lora_state_dict(
    lora_path
)
base_pipe.load_lora_into_unet(
    state_dict
    , network_alphas = network_alphas
    , unet = base_pipe.unet
)
```

Throws out errors 

```
[1612](file:///d%3A/az_git_folder/azcode/azcode_venv_win_p310/lib/site-packages/torch/nn/modules/module.py?line=1611)     if name in modules:
   [1613](file:///d%3A/az_git_folder/azcode/azcode_venv_win_p310/lib/site-packages/torch/nn/modules/module.py?line=1612)         return modules[name]
-> [1614](file:///d%3A/az_git_folder/azcode/azcode_venv_win_p310/lib/site-packages/torch/nn/modules/module.py?line=1613) raise AttributeError("'{}' object has no attribute '{}'".format(
   [1615](file:///d%3A/az_git_folder/azcode/azcode_venv_win_p310/lib/site-packages/torch/nn/modules/module.py?line=1614)     type(self).__name__, name))

AttributeError: 'ModuleList' object has no attribute '4'
```

Is this a bug, or anything I missed somewhere? my understanding is that `load_lora_weights()` is basically take the  `state_dict, network_alphas` then call `load_lora_into_unet` and `load_lora_into_text_encoder`, why would this exception been thrown out?  Thanks 

### Reproduction

Sample code to reproduce the issue: 

```python
import torch
from diffusers import StableDiffusionXLPipeline

# load SDXL base pipeline
base_model_checkpoint_path = r"path/to/sd_xl_base_1.0.safetensors"
base_pipe = StableDiffusionXLPipeline.from_single_file(
    base_model_checkpoint_path
    , torch_dtype = torch.float16
    , use_safetensors = True
    , load_safety_checker = False
)

# add LoRA
lora_path = r"path/to/SDXLLoRA.safetensors"
state_dict, network_alphas = base_pipe.lora_state_dict(
    lora_path
)
base_pipe.load_lora_into_unet(
    state_dict
    , network_alphas = network_alphas
    , unet = base_pipe.unet
)
```

### System Info

Diffusers Version: 0.20.0.dev0 
Python version: Python 3.10.11
Torch version: 2.0.0+cu117

### Who can help?

@patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
Will take a look.

**Comment by xhinker** [comment]
> Will take a look.

Thank you Sayak, I saw some amazing LoRA related PRs from you, so thought you may have the answer 😊, looking forward to your findings

**Comment by sayakpaul** [comment]
Could you provide a fully reproducible code snippet (preferably a Colab Notebook)? 

I tried this: https://gist.github.com/sayakpaul/f8d9057bd1ae4d4f4ba276293d2d2574 and it just worked fine.

**Comment by xhinker** [comment]
> Could you provide a fully reproducible code snippet (preferably a Colab Notebook)?
> 
> I tried this: https://gist.github.com/sayakpaul/f8d9057bd1ae4d4f4ba276293d2d2574 and it just worked fine.

Hi, Sayakpaul, 

Thanks for looking into it!

pipe.load_lora_weights function works for me too. the exception is thrown out when calling the `load_lora_into_unet` function like this:  

```python 
# add LoRA
lora_path = r"path/to/SDXLLoRA.safetensors"
state_dict, network_alphas = base_pipe.lora_state_dict(
    lora_path
)
base_pipe.load_lora_into_unet(
    state_dict
    , network_alphas = network_alphas
    , unet = base_pipe.unet
)
```

**Comment by sayakpaul** [comment]
Well, you should always use `load_lora_weights()` no matter which part of the state_dict you want to load.

**Comment by xhinker** [comment]
> Well, you should always use `load_lora_weights()` no matter which part of the state_dict you want to load.

Any considerations on why we shouldn't use load_lora_into_unet function? I can successfully call it for SD 1.5 LoRAs and add LoRA weight to the pipeline, works perfectly

**Comment by sayakpaul** [comment]
SDXL has some implications on the loading side, that is why. For now, we find it easier to always promote `load_lora_weights()`.

**Comment by xhinker** [comment]
> SDXL has some implications on the loading side, that is why. For now, we find it easier to always promote `load_lora_weights()`.

The same I really don't understand is the  `load_lora_weights` function is just a wrapper calls `lora_state_dict`, `load_lora_into_unet`, and then `load_lora_into_text_encoder`. here is a copy of the function body:

```python
def load_lora_weights(self, pretrained_model_name_or_path_or_dict: Union[str, Dict[str, torch.Tensor]], **kwargs):
      state_dict, network_alphas = self.lora_state_dict(pretrained_model_name_or_path_or_dict, **kwargs)
      self.load_lora_into_unet(state_dict, network_alphas=network_alphas, unet=self.unet)
      self.load_lora_into_text_encoder(
          state_dict,
          network_alphas=network_alphas,
          text_encoder=self.text_encoder,
          lora_scale=self.lora_scale,
      )
```

Why it works inside of load_lora_weights, but not working by calling it outside?  even the outside call `load_lora_into_text_encoder` works without a problem.  but only `load_lora_into_unet` always throw out exception, which really puzzles me.

**Comment by sayakpaul** [comment]
I am sorry, but sadly, we don't have the time to look into right now. Feel free to share findings if you have any and we will try to reason why.

**Comment by sayakpaul** [comment]
Can you also check if you can successfully call load_lora_into_unet into a pipeline when the pipeline is initialised with `from_pretrained()` and NOT using the single checkpoint loading method? Will help us to track this issue down.

**Comment by xhinker** [comment]
> Can you also check if you can successfully call load_lora_into_unet into a pipeline when the pipeline is initialised with `from_pretrained()` and NOT using the single checkpoint loading method? Will help us to track this issue down.

Took some time to download the model file and use `from_pretrained()` function, the same exception.

**Comment by sayakpaul** [comment]
https://colab.research.google.com/gist/sayakpaul/7c1d04ffd94483b5b99c2b24f910c5ca/scratchpad.ipynb

see if this works :)

**Comment by xhinker** [comment]
> https://colab.research.google.com/gist/sayakpaul/7c1d04ffd94483b5b99c2b24f910c5ca/scratchpad.ipynb
> 
> see if this works :)

OMG, your solution works! Thank You so much @sayakpaul  Your sample code tells everything!

I go back to the `StableDiffusionXLPipeline` code and found the overrided `load_lora_weights` function used the `unet_config=self.unet.config`  

```python
...
def load_lora_weights(self, pretrained_model_name_or_path_or_dict: Union[str, Dict[str, torch.Tensor]], **kwargs):
      # We could have accessed the unet config from `lora_state_dict()` too. We pass
      # it here explicitly to be able to tell that it's coming from an SDXL
      # pipeline.
      state_dict, network_alphas = self.lora_state_dict(
          pretrained_model_name_or_path_or_dict,
          unet_config=self.unet.config,
          **kwargs,
      )
      self.load_lora_into_unet(state_dict, network_alphas=network_alphas, unet=self.unet)
     ....
```

Again, Thank You @sayakpaul !

**Comment by markrmiller** [comment]
Ah man, thought I had found the solution here for this, but I get it load_lora_eights and that colab code with every lora I try from civits.

```
File "/home/markmiller/finetune-diffusion/controlnet_sdxl_2.py", line 91, in __init__
    self.pipe.load_lora_weights("./models/", weight_name="samdoesart.safetensors")
  File "/home/markmiller/finetune-diffusion/diffusers/src/diffusers/loaders.py", line 885, in load_lora_weights
    self.load_lora_into_unet(state_dict, network_alphas=network_alphas, unet=self.unet)
  File "/home/markmiller/finetune-diffusion/diffusers/src/diffusers/loaders.py", line 1223, in load_lora_into_unet
    unet.load_attn_procs(state_dict, network_alphas=network_alphas)
  File "/home/markmiller/finetune-diffusion/diffusers/src/diffusers/loaders.py", line 347, in load_attn_procs
    attn_processor = getattr(attn_processor, sub_key)
  File "/opt/conda/envs/ftd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ModuleList' object has no attribute '4'
```

**Comment by markrmiller** [comment]
Whoops, my bad. I left the load_lora_weights uncommented when I put the colab code below it. The colab code does work for me. Seems my recent source diffusers checkout that I grabbed for img2img controlnet is not passing the config to load_lora_into_unet anymore.

**Comment by yaping1119** [comment]
The loaders load_lora_into_unet() function throw out AttributeError: 'DownBlock2D' object has no attribute 'attentions'

**Comment by sayakpaul** [comment]
Feel free to open a new issue thread with all the details.
