### ISSUE TITLE
When will guide diffusion and unet_1d_condition be supported ？

### ISSUE THREAD

**Issue by YChienHung** [huggingface/diffusers#4463]
Just like titles,
I need guide diffusion’s feature and unet_1d_condition, but I don't find them in this repo,
please support them,
thx !

**Comment by patrickvonplaten** [comment]
Can you provide some links to papers / codebase please?

**Comment by YChienHung** [comment]
as for guide diffusion:
its paper: https://arxiv.org/abs/2105.05233
its repo: https://github.com/openai/guided-diffusion

as for  unet_1d_condition: 
you may be able to refer to [unet_2d_condition.py] in this repository.(https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_condition.py)
