### ISSUE TITLE
Dynamic threasholding example and mimic scale please

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#4466]
Hi. I know that dynamic threasholding is implemented, however there are no examples on how to use them. Also, in this repo: https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/tree/master    there's a variable called mimic scale which is nowhere to be found in diffusers

**Comment by patrickvonplaten** [comment]
We haven't done any extensive testing yet, I'd just try it out and see what works :-)

**Comment by alexblattner** [comment]
@patrickvonplaten but, how do you use it? Can I get an example?

**Comment by alexblattner** [comment]
@patrickvonplaten I know you guys are focused on SDXL which is great, but I would love some info on how to use this considering how it's already implemented.

**Comment by JincanDeng** [comment]
I face the same problem. Anyone know how to use it?

**Comment by alexblattner** [comment]
@sayakpaul sorry to call you, but we have no way to know stuff without insisting. This question will be ignored and auto closed at this rate

**Comment by sayakpaul** [comment]
I am not sure what Patrick was referring to either, actually. Ccing @yiyixuxu if she knows.

**Comment by patrickvonplaten** [comment]
Most of our schedulers have `dynamic_thresholding` as shown here: https://github.com/huggingface/diffusers/blob/24c5e7708bb75076dd8e79ccaea195640555f945/src/diffusers/schedulers/scheduling_dpmsolver_multistep.py#L151 

What I meant above is that I haven't played around with these values extensively, it would be great if someone could do it and post some findings :-)

**Comment by alexblattner** [comment]
me and @Hzj199 will be working on an implementation: https://github.com/huggingface/diffusers/issues/4497
