### ISSUE TITLE
DWPose controlnet

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#4467]
here's the most precise openpose controlnet derivative I've ever seen: https://github.com/IDEA-Research/DWPose/tree/main

Absolutely worth implementing! This is beyond amazing and all who tried using the regular controlnet openpose can tell you how much better it is and the paper shows direct examples! Insane precision!

**Comment by kamathis4** [comment]
@sayakpaul is this model up for implementation?

**Comment by sayakpaul** [comment]
Sure!

**Comment by slavakurilyak** [comment]
+1 for DWPose integration by @IDEA-Research

/cc @yzd-v and @ailingzengzzz
