### ISSUE TITLE
Prompt truncation detection and return of tokenized prompts

### ISSUE THREAD

**Issue by shirayu** [huggingface/diffusers#447]
**Is your feature request related to a problem? Please describe.**

There are examples of long prompts on the web, but many people are unaware that long strings are truncated.
However, there is no way to know wheter `StableDifusionPipelineOutputprompt` truncated long `prompt` or not.

Long prompts are truncated [here](https://github.com/huggingface/diffusers/blob/f6fb3282b18f44f14bcb95a34a16203906df992a/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L175-L181) implicitly.

https://github.com/huggingface/diffusers/blob/f6fb3282b18f44f14bcb95a34a16203906df992a/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L175-L181

**Describe the solution you'd like**

Returns a bool value indicating whether it has been truncated or not.
It is more convenient to return a tokenized prompt as well.

https://github.com/huggingface/diffusers/blob/f6fb3282b18f44f14bcb95a34a16203906df992a/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L276-L279

**Describe alternatives you've considered**

**Additional context**
In my app, after generating images, it tokenizes prompts separately to check whether they has been truncated or not.
However, this is a waste to tokenize them again.

https://github.com/shirayu/purepale/blob/ab89a20e1a0e1728d4cc98a3d8381b131c7c6319/purepale/serve.py#L167-L172

**Comment by patrickvonplaten** [comment]
Thanks for opening this issue - that's a good comment indeed! 

Cc @anton-l @patil-suraj here
