### ISSUE TITLE
fail to get expected results on sdxl+controlnet on fill50k

### ISSUE THREAD

**Issue by YongtaoGe** [huggingface/diffusers#4476]
### Describe the bug

The generated images seem not to correspond to the input condition images after around 10000 iterations.

### Reproduction

```
CUDA_VISIBLE_DEVICES='0' accelerate launch train_controlnet_sdxl.py \
 --pretrained_model_name_or_path=$MODEL_DIR \
 --output_dir=$OUTPUT_DIR \
 --pretrained_vae_model_name_or_path=$VAE_DIR \
 --train_data_dir "examples/controlnet/data/fill50k" \
 --resolution=1024 \
 --learning_rate=1e-5 \
 --max_train_steps=15000 \
 --validation_image "./data/condition_images/fill50k_conditioning_image_1.png" \
 --validation_prompt "red circle with blue background" \
 --validation_steps=100 \
 --train_batch_size=2 \
 --gradient_accumulation_steps=1 \
 --report_to="wandb" \
 --enable_xformers_memory_efficient_attention \
 --max_grad_norm=1.0 \
 --tracker_project_name sd_xl_train_controlnet_fill50k \
 --seed=12 \
 --logging_dir='logs_fill50k' \
 --num_validation_images=2 \
```

### Logs
Here are the results on 9899 iters.

![validation_9899_625e1ee3a3046dd10554](https://github.com/huggingface/diffusers/assets/22744013/1339b89a-5f3b-448d-8d44-2fd27c8af73c)
![validation_9899_43b527f55827e9f7781a](https://github.com/huggingface/diffusers/assets/22744013/0eb1f9bc-3887-4516-8744-1280ea3451eb)

### System Info

a100x1

**Comment by sayakpaul** [comment]
With almost the similar script, we're getting promising results on a different dataset. So, i highly doubt if this is a script-problem. Could use some hyperparameter tuning sweeps. 

Ccing @okotaku who recently shared some cool [results](https://discord.com/channels/879548962464493619/1014556868829532210/1138096114021699644).

**Comment by haoqiangyu** [comment]
> With almost the similar script, we're getting promising results on a different dataset. So, i highly doubt if this is a script-problem. Could use some hyperparameter tuning sweeps.
> 
> Ccing @okotaku who recently shared some cool [results](https://discord.com/channels/879548962464493619/1014556868829532210/1138096114021699644).

@sidthekidder The link ([results](https://discord.com/channels/879548962464493619/1014556868829532210/1138096114021699644)) can't be accessed, maybe I didn't join the discord channel.

**Comment by okotaku** [comment]
@haoqiangyu 
https://github.com/okotaku/diffengine/pull/31

Here is my results.

https://discord.com/channels/879548962464493619/1014556868829532210/1137955469546233946

Here is the message link;)

I feel my model was under fitting. I plan to use more epochs or higher lr.

**Comment by okotaku** [comment]
@haoqiangyu I trained ControlNet small and mid for SDXL for 3 epochs. The results look promising.

https://github.com/okotaku/diffengine/pull/49

#### stable_diffusion_xl_controlnet_small_fill50k

![input1](https://datasets-server.huggingface.co/assets/fusing/fill50k/--/default/train/74/conditioning_image/image.jpg)

![example1](https://github.com/okotaku/diffengine/assets/24734142/8556346f-bdc4-45be-b1fd-1467d9147c1d)

#### stable_diffusion_xl_controlnet_mid_fill50k

![input1](https://datasets-server.huggingface.co/assets/fusing/fill50k/--/default/train/74/conditioning_image/image.jpg)

![example1](https://github.com/okotaku/diffengine/assets/24734142/74be361b-ec28-465a-8e7e-55b1a6210e80)
