### ISSUE TITLE
SDXL Kohya LoRA sometimes produces weird results

### ISSUE THREAD

**Issue by LrsChrSch** [huggingface/diffusers#4484]
### Describe the bug

I am using both the SDXL 1.0 Base and the refiner model to generate images. I have two different LoRAs being loaded after each other into the base model (see reproduction)

Both LoRAs are trained using the Kohya GUI.

I uploaded both LoRAs here:
1. https://drive.google.com/file/d/1thZQt5-1uiJ50Hm46_4KYOfIr4b6OniE/view?usp=sharing
2. https://drive.google.com/file/d/1sEiiUJZ3DPDv6t0ohSyUkg7Eh6RSmnkd/view?usp=sharing

The first of these works flawlessly, but loading the second one produces weird gray mushy textures
Doesn't matter if the second one is loaded alone or together with the first one.

I initially thought that it might be because the second one was trained using a network dimension of 128, but I retrained the network using the same settings as the first one (with 8 dimensions) and it gives roughly the same results.

https://huggingface.co/docs/diffusers/v0.19.3/en/training/lora#known-limitations-specific-to-the-kohyastyled-loras
Here it says, that SDXL LoRAs with both text encoders might lead to weird results. As far as I can tell both LoRAs have both text encoders. Only difference is that for some reason, one works and the other one doesnt.

I checked both LoRAs in ComfyUI and they work flawlessly; I only have issues when using the script (see reproduction)
Not using the refiner yields similar results. they just aren't refined, but still look the same

Hope you can help! Thanks in advance! I'm pretty sure it's just a problem with the way I've set this up.

### Reproduction

Importing and stuff:
```
import torch
from diffusers import StableDiffusionXLPipeline, StableDiffusionXLImg2ImgPipeline

diffuser_base = StableDiffusionXLPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True, device_map="auto")

diffuser_refiner = StableDiffusionXLImg2ImgPipeline.from_pretrained("stabilityai/stable-diffusion-xl-refiner-1.0", text_encoder_2=diffuser_base.text_encoder_2, vae=diffuser_base.vae, torch_dtype=torch.float16, variant="fp16", use_safetensors=True, device_map="auto")


```

Generating:
```
n_steps = 25
high_noise_frac = 0.8

prompt = "a cat playing with a red ball"
negative_prompt = "deformed"

# optional: This is actually running in a jupyter notebook so I just use this line to unload the LoRAs when needed
# diffuser_base.unload_lora_weights()

diffuser_base.load_lora_weights("crtx.safetensors")
# diffuser_base.load_lora_weights("cmpstrct.safetensors")


generator = torch.Generator(device="cuda").manual_seed(1)

image = diffuser_base(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=n_steps,
    denoising_end=high_noise_frac,
    width=1024,
    height=1024,
    output_type="latent",
    guidance_scale=7,
    generator=generator
).images
image = diffuser_refiner(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=n_steps,
    denoising_start=high_noise_frac,
    image=image,
    guidance_scale=7,
    generator=generator
).images[0]

image.show()
```

Using no LoRA (different prompt than in the example, but you'll  get what I mean)
![no](https://github.com/huggingface/diffusers/assets/86013790/db430525-48e8-4f3f-ae30-a67f09c7d9a0)

Using the working LoRA only (or loading the LoRA AFTER the broken one)
Don't worry, it should something like this. As long as it isn't gray, it's good.
![first](https://github.com/huggingface/diffusers/assets/86013790/9e10646c-9505-43e5-acae-0325c29834f7)

Using the broken LoRA only
![broken](https://github.com/huggingface/diffusers/assets/86013790/fbb2c7c4-c759-4787-99ea-af0f038fce00)

Using both LoRAs with the broken one loaded AFTER the working one
![both](https://github.com/huggingface/diffusers/assets/86013790/bdc2ebcf-bbfb-40db-a85a-701f3f89c17a)

Using a retrained version of the broken LoRA with only 8 dimensions
![sm](https://github.com/huggingface/diffusers/assets/86013790/735c95e9-9f40-4834-92ce-fefd36abf154)

Using both LoRAs (the bigger ones) in ComfyUI. This is what it should basically look like, although this one has yet another prompt.
![ComfyUI_00282_](https://github.com/huggingface/diffusers/assets/86013790/198502bb-ba76-4589-9aed-aa874540cf18)

### System Info

- `diffusers` version: 0.19.3
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.10
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: 0.0.20
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@williamberman @patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
@LrsChrSch thanks for your detailed report!

Could you install `diffusers` from `main` and see if these issues exist?

**Comment by LrsChrSch** [comment]
Awesome, that works! Thanks!

Updating to `diffusers version: 0.20.0.dev0` using `pip install git+https://github.com/huggingface/diffusers.git` does the trick

I'm guessing multiple LoRA support is still a work-in-progress; only the one loaded at the end affects the image, but according to  #2613 that's just how it is at the moment.

In any case: works for me! Thanks again, closing for now.
