### ISSUE TITLE
SDXL Refiner broken in latest diffusers

### ISSUE THREAD

**Issue by catid** [huggingface/diffusers#4491]
### Describe the bug

Using the example "ensemble of experts" code produces this error: TypeError: StableDiffusionXLPipeline.call() got an unexpected keyword argument 'denoising_start'

### Reproduction

Use example code from e.g. https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0 for ensemble of experts with refiner.

### Logs

```shell
File "/home/catid/mambaforge/envs/sdxl/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/catid/mambaforge/envs/sdxl/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/catid/mambaforge/envs/sdxl/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/catid/mambaforge/envs/sdxl/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/catid/mambaforge/envs/sdxl/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/catid/mambaforge/envs/sdxl/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/catid/mambaforge/envs/sdxl/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/catid/sdxl/server.py", line 92, in generate
    image_data = generate_image(request.prompt, request.steps, request.guide)
  File "/home/catid/sdxl/server.py", line 80, in generate_image
    refined_image = refiner_pipe(
  File "/home/catid/mambaforge/envs/sdxl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: StableDiffusionXLPipeline.__call__() got an unexpected keyword argument 'denoising_start'
```

### System Info

Ubuntu Linux with Nvidia 4090x2

### Who can help?

@patrickvonplaten @sayakpaul @williamberman

**Comment by sayakpaul** [comment]
@patrickvonplaten the [docs](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl) need to be updated as we no longer have the `denoising_start` argument.

**Comment by catid** [comment]
@sayakpaul Looks like it doesn't have `image` either.  What's the proper way to do the ensemble of experts image denoising that starts with 1.0-base and ends with 1.0-refiner?

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten here.

**Comment by patrickvonplaten** [comment]
Please make sure to use the refiner with the correct pipeline which is the Img2Img pipeline: https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl#diffusers.StableDiffusionXLImg2ImgPipeline

**Comment by patrickvonplaten** [comment]
Or use it as a mixture of experts as explained here: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0#%F0%9F%A7%A8-diffusers

But load it either with DiffusionPipeline or StableDiffusionXLImg2ImgPipeline, not with StableDiffusionXLPipeline

**Comment by patrickvonplaten** [comment]
I don't know which docs should be updated here @sayakpaul

**Comment by catid** [comment]
Ah got it thanks.  Trying to disable watermarks and used the wrong class

**Comment by sayakpaul** [comment]
Closing the issue then.

**Comment by TimothyAlexisVass** [comment]
The document referenced in this doesn't show a way to use the refiner.
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0#%F0%9F%A7%A8-diffusers

```
# run both experts
image = base(
    prompt=prompt,
    num_inference_steps=n_steps,
    denoising_end=high_noise_frac,
    output_type="latent",
).images
image = refiner(
    prompt=prompt,
    num_inference_steps=n_steps,
    denoising_start=high_noise_frac, # <<< This won't work, right?
    image=image,
).images[0]
```

**Comment by TimothyAlexisVass** [comment]
The document referenced in this "Or use it as a mixture of experts" doesn't show a way to use the refiner.
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0#%F0%9F%A7%A8-diffusers

Also, it is exactly what the issue initially was about.
