### ISSUE TITLE
How to convert a diffuser pipeline of XL to checkpoint or safetensors

### ISSUE THREAD

**Issue by FeiiYin** [huggingface/diffusers#4494]
I need to fine-tune stable diffusion unet or something like that. Then I have to convert the pipeline into ckpt for webui usage.
Before I use the `scripts/convert_diffusers_to_original_stable_diffusion.py` for transforming. 
But currently it cannot convert correctly for XL pipeline and webui may raise bugs.
Thanks in advance.

**Comment by sayakpaul** [comment]
Yeah that script needs to be adjusted a bit for SDXL. Unfortunately, we don't have the cycles to look into right now. But, more than happy to review a PR.

**Comment by syorami** [comment]
Any updates on this issue?
