### ISSUE TITLE
Prompt fusion

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#4496]
**Is your feature request related to a problem? Please describe.**
I would like to get a wider range of results

**Describe the solution you'd like**
Prompt fusion

**Describe alternatives you've considered**
Doing it myself, but I'd have to redo it for every new pipeline

**Additional context**
https://github.com/ljleb/prompt-fusion-extension

**Comment by sayakpaul** [comment]
Could you elaborate the issue a bit more? 

Notice that if something needs to be copied from one module to the other in our library, we make use of `# Copied from ...` comments to help preserve our sanity, hahaha. Then we have utilities like `make fix-copies` that can automate most of it.

**Comment by sayakpaul** [comment]
Oh cool. If you want to contribute a PR, happy to review!

**Comment by alexblattner** [comment]
@sayakpaul I'll be honest, I have decided to do this in a different structure than the regular diffusers pipeline one. I'll implement it for an extension of the stable diffusion pipeline that I am working on since it can be modified far easier. I think it makes no sense to create an entirely new pipeline for every single tiny change, especially when I want to implement a lot of things at the same time.

thanks for the offer though

**Comment by sayakpaul** [comment]
Understandable. Leaving it open in case someone wants to pick it up.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
I had implemented this with my own custom py rust code wrap around the pipeline generation func call and change some preparation code.not that hard need like 1 week work.
But definitely not elegant code,kinda spagetthi.

I tested with img2img and it works well,like say ["1 girl wearing eyeglass,1 girl with jacket"]

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
if you are talking about like fully compatible syntax with A1111 that's slightly different story.But I think you can ping compel dev and see if its natively supported or not if not ,then need homeroll or copy paste some code from extension.

**Comment by alexblattner** [comment]
@cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw may I see your code? this could save me some time and my implementation also isn't great

**Comment by alexblattner** [comment]
> if you are talking about like fully compatible syntax with A1111 that's slightly different story.But I think you can ping compel dev and see if its natively supported or not if not ,then need homeroll or copy paste some code from extension.

this is something that needs its own pipeline regardless of whether it is A1111's syntax. Right now, it just doesn't exist in diffusers.

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
> this is something that needs its own pipeline regardless of whether it is A1111's syntax. Right now, it just doesn't exist in diffusers.

I dont think needs its own pipeline.lol.in the end its just a wrapper for txt2img or img2img its not really like that much different. We can just add a argument like usefusionprompt/usermultistepprompt=True

But I guess a pipeline will be easier to mantain?lol


its just a for loop for the execution.The harder part is to make sure it works with both compel and normal prompt which cause the script to have excessive if else.and a lot of prompt preprocessing.

The core part is to make sure the image is shared across the execution so it goes from.eg img2img ["1girl with eyeglass","1 sexy girl"] =original image>eyeglass>sexy girl

```
pertstepimg=image
stepnum=0
for petstepprompt in split_arrays:
```

**Comment by gajendr-nikhil** [comment]
@sayakpaul I would like to work on this. Please assign me this issue 

(ps: this is my personal GitHub id, my other GitHub @nikhil-masterful is for job related)

**Comment by sayakpaul** [comment]
@gajendr-nikhil maybe let's first discuss the API design you have in mind so that we can see and brainstorm a bit?

**Comment by nikhil-masterful** [comment]
> @gajendr-nikhil maybe let's first discuss the API design you have in mind so that we can see and brainstorm a bit?

Sounds good. Let me look at the original implementation and give you my thoughts on the design

**Comment by patrickvonplaten** [comment]
I'd like to handle this feature request as part of: https://github.com/huggingface/diffusers/issues/4778 to make sure we have a unified API here :-)

**Comment by gajendr-nikhil** [comment]
@patrickvonplaten please go ahead. 

Let me know if there's any way for me to contribute to this feature request. Would love to be a part

**Comment by alexblattner** [comment]
I made a new pipeline that should handle the flexibility issues of diffusers: https://github.com/alexblattner/RubberDiffusers

It also has prompt fusion working. I'm not going to close this issue because it's not implemented on diffusers as its own pipeline yet technically

**Comment by haofanwang** [comment]
Interested.
