### ISSUE TITLE
How to train stable-diffusion-xl-base-1.0 without lora?

### ISSUE THREAD

**Issue by KimmiShi** [huggingface/diffusers#4507]
Hi, I want to train `stable-diffusion-xl-base-1.0` without lora, how to do this?

I can run `train_text_to_image_lora_sdxl.py` .
But `train_text_to_image.py` with  `MODEL_NAME="stabilityai/stable-diffusion-xl-base-1.0"` with raise an error: 

```
diffusers/models/unet_2d_condition.py:836 in forward                                                        │
│   833 │   │   │   aug_emb = self.add_embedding(text_embs, image_embs)        │
│   834 │   │   elif self.config.addition_embed_type == "text_time":           │
│   835 │   │   │   # SDXL - style                                             │
│ ❱ 836 │   │   │   if "text_embeds" not in added_cond_kwargs:                 │
│   837 │   │   │   │   raise ValueError(                                      │
│   838 │   │   │   │   │   f"{self.__class__} has the config param `addition_ │
│   839 │   │   │   │   )                                                      │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: argument of type 'NoneType' is not iterable
```

the `added_cond_kwargs` is none in this case.

**Comment by sayakpaul** [comment]
It won't work. I am working on https://github.com/huggingface/diffusers/pull/4505 to fix this.

**Comment by KimmiShi** [comment]
> It won't work. I am working on #4505 to fix this.

Thanks, I found your PR just a short while ago and I am testing this code.

**Comment by muyuWang** [comment]
Hi, I have the same problem as you mentioned. Have you fixed it already？ And could you tell me how you solved this? Thanks

**Comment by sayakpaul** [comment]
Refer to https://github.com/huggingface/diffusers/pull/4505.
