### ISSUE TITLE
StableDiffusionXLInpaintPipeline and StableDiffusionXLImg2ImgPipeline

### ISSUE THREAD

**Issue by wooyeolBaek** [huggingface/diffusers#4511]
I have tested using the `load_lora_weights()` and `save_lora_weights()` functions from `StableDiffusionXLPipeline` in `StableDiffusionXLInpaintPipeline` and `StableDiffusionXLImg2ImgPipeline`, and they work well. 

Can I open a PR?

---

              This is likely happening because the definitions of `load_lora_weights()` and `save_lora_weights()` (irrelevant here but for comprehensiveness) are not there in the pipeline source. 

https://github.com/huggingface/diffusers/blob/816ca0048f7a38531a6f036299d2dd274abb5639/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L866

https://github.com/huggingface/diffusers/blob/816ca0048f7a38531a6f036299d2dd274abb5639/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L898

I think adding the `load_lora_weights()` method to `StableDiffusionXLImg2ImgPipeline` should solve the problem. 

If possible for you, would you maybe like to fix this and open a PR?

_Originally posted by @sayakpaul in https://github.com/huggingface/diffusers/issues/4438#issuecomment-1662336456_

**Comment by sayakpaul** [comment]
Sure. Feel free to :)
