### ISSUE TITLE
Custom Inpainting models on StableDiffusionControlNetInpaintPipeline

### ISSUE THREAD

**Issue by vijishmadhavan** [huggingface/diffusers#4522]
Is there a way to use custom Inpainting models like SG161222/Realistic_Vision_V5.1_noVAE on StableDiffusionControlNetInpaintPipeline? 
Can somebody help?

**Comment by sayakpaul** [comment]
You could convert that checkpoint to diffusers format first and then use it with the pipeline. 

Conversion script: https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_controlnet_to_diffusers.py
