### ISSUE TITLE
AnimateDiff in Diffusers Library

### ISSUE THREAD

**Issue by Pie31415** [huggingface/diffusers#4524]
### Model/Pipeline/Scheduler description

I think it would be cool to work on turning AnimateDiff into a diffusers pipeline that can be used via the library.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

Paper: https://arxiv.org/abs/2307.04725
Github: https://github.com/guoyww/AnimateDiff

**Comment by Pie31415** [comment]
I would like to work on this pipeline if it's something that people are interested in.

**Comment by DN6** [comment]
@Pie31415 go for it 👍🏽 Feel free to add me to do a review and let me know if I can help.

**Comment by Pie31415** [comment]
@DN6 Sounds good. I'll have time to work on this in a few weeks. I'll ping you once something is up.

**Comment by DN6** [comment]
@Pie31415 Looking at the AnimateDiff repo, it looks like it's adding an additional motion module to the 3D Conditional Unet. This is a similar paradigm to Adapters and Controlnets. It might be a route worth investigating when trying to create the Motion Module.

**Comment by haofanwang** [comment]
Agree to @DN6 , this absolutely worths a shot.

**Comment by DN6** [comment]
@haofanwang Would you be interested in collaborating on this? Would be great to get your eyes on a review.

**Comment by Pie31415** [comment]
Yeah, I would definitely appreciate all the help/suggestions. These next 2 weeks will be a little busy because of exams but after that I'm really excited to get started and working with you all.

**Comment by charlesmccarthy** [comment]
awesome to see it count me as interested

**Comment by Skquark** [comment]
I integrated AnimateDiff into my project https://DiffusionDeluxe.com using the modified CLI version.  The official one is pretty outdated, made for an old Diffusers version and Torch < 2.0 which made it unusable, so I found a refactored fork by Neggles at https://github.com/neggles/animatediff-cli which is much better coding.  He even got rid of the 16 frame limit, which was essential for animating anything of value.  I'd suggest using that code as the base of the AnimateDiff Pipeline within Diffusers, would save some time reworking it...

**Comment by notdanilo** [comment]
Any update on this? I would love to try it :)

**Comment by DN6** [comment]
Hi @Pie31415. How is the PR progressing for this?

**Comment by DN6** [comment]
@notdanilo Please feel free to go ahead here

**Comment by Pie31415** [comment]
Hi @DN6, still active on the PR. I've been out of the country for the last week and will be back soon. I'll push some updates once I'm back. Should be around end of aug/start of sept.

@notdanilo I'll ping you once the pipeline is up.

**Comment by notdanilo** [comment]
@Pie31415 thanks! I would be happy to follow the development branch to learn a bit and possibly become a contributor myself in the future.

**Comment by ykk648** [comment]
I did some works on https://github.com/ykk648/AnimateDiff , mainly reconstructed animatediff codes to support diffusers 0.20.1, it can be easily adapted to diffusers like controlnet/adapter did, check if it helps, I can help to this [PR](https://github.com/huggingface/diffusers/pull/4570) if you need.

**Comment by DN6** [comment]
@ykk648 If you can, please go ahead and open a PR. Others can possible collaborate with you on it as well.

**Comment by Pie31415** [comment]
@ykk648 Sounds good. I'll take a look through your code and ping you here if I have any questions.

Do you also happen to have a discord acc? It might be easier for me to communicate with you there.

**Comment by ykk648** [comment]
@Pie31415  My discord username: tylerluan, you can send me an email, the response may be faster:  tylerluan@163.com

**Comment by patrickvonplaten** [comment]
Solved with https://github.com/huggingface/diffusers/pull/5702
