### ISSUE TITLE
Little artifacts on the img generated by sdxl refiner 1.0, mostly red green and blue

### ISSUE THREAD

**Issue by WaltBao** [huggingface/diffusers#4530]
### Describe the bug

I don't know if it is the problem of the model itself
![sdxl_artifacts](https://github.com/huggingface/diffusers/assets/106211276/52d4b0ec-c9ff-4e2a-8c99-bda385fd99ce)

### Reproduction

pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    sd_model_path, torch_dtype=torch.float16, requires_aesthetics_score=True
    )
    pipe.enable_xformers_memory_efficient_attention()
    pipe = pipe.to("cuda")

    condition_img = load_image(condition_img_path)
    condition_img = condition_img.resize((512, 512))
    prompt = “something”
    negative_prompt="woman, human head, human, face, eyes, hands, legs, animal, side angle, bottles, bottle, cups, cup, sharp edge of models, hard edges, deformed, mutated, ugly, disfigured, blur, blurry, noise, noisy"

    new_image = pipe(
        prompt=prompt,
        prompt_2=prompt,
        image=condition_img,
        negative_prompt=negative_prompt,
        negative_prompt_2=negative_prompt,
        num_inference_steps=80,
        strength=0.7,
        guidance_scale = 10,
        aesthetic_score = 6.0,
        negative_aesthetic_score = 2.5,
        original_size = (512, 512),
        target_size = (512, 512)
    ).images[0]

### System Info

- `diffusers` version: 0.19.3
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.28.1
- Accelerate version: 0.16.0
- xFormers version: 0.0.19
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@patrickvonplaten

**Comment by CoffeeVampir3** [comment]
> ### Describe the bug
> 
> I don't know if it is the problem of the model itself ![sdxl_artifacts](https://user-images.githubusercontent.com/106211276/259069397-52d4b0ec-c9ff-4e2a-8c99-bda385fd99ce.jpeg)
> ### Reproduction
> 
> pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained( sd_model_path, torch_dtype=torch.float16, requires_aesthetics_score=True ) pipe.enable_xformers_memory_efficient_attention() pipe = pipe.to("cuda")
> 
> ```
> condition_img = load_image(condition_img_path)
> condition_img = condition_img.resize((512, 512))
> prompt = “something”
> negative_prompt="woman, human head, human, face, eyes, hands, legs, animal, side angle, bottles, bottle, cups, cup, sharp edge of models, hard edges, deformed, mutated, ugly, disfigured, blur, blurry, noise, noisy"
> 
> new_image = pipe(
>     prompt=prompt,
>     prompt_2=prompt,
>     image=condition_img,
>     negative_prompt=negative_prompt,
>     negative_prompt_2=negative_prompt,
>     num_inference_steps=80,
>     strength=0.7,
>     guidance_scale = 10,
>     aesthetic_score = 6.0,
>     negative_aesthetic_score = 2.5,
>     original_size = (512, 512),
>     target_size = (512, 512)
> ).images[0]
> ```
> 
> ### Logs
> 
> _No response_
> ### System Info
> 
>     * `diffusers` version: 0.19.3
> 
>     * Platform: Windows-10-10.0.19045-SP0
> 
>     * Python version: 3.10.6
> 
>     * PyTorch version (GPU?): 2.0.1+cu117 (True)
> 
>     * Huggingface_hub version: 0.14.1
> 
>     * Transformers version: 4.28.1
> 
>     * Accelerate version: 0.16.0
> 
>     * xFormers version: 0.0.19
> 
>     * Using GPU in script?:
> 
>     * Using distributed or parallel set-up in script?:
> 
> 
> ### Who can help?
> 
> @patrickvonplaten

This is very likely the watermarker from the sdxl pipe. Here's my recommendation:
```
pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
sd_model_path, torch_dtype=torch.float16, requires_aesthetics_score=True,
add_watermarker=False #Add this
)
```
I had issues with this not actually disabling the watermarker, so I'd also recommend this:
```
class NoWatermarker:
    def __init__(self):
        pass

    def apply_watermark(self, images: torch.FloatTensor):
        return images
```

Then after constructing the pipe:
```
pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
sd_model_path, torch_dtype=torch.float16, requires_aesthetics_score=True,
add_watermarker=False #Add this
)
pipe.watermark = NoWatermarker()
```

Additionally, I'd recommend using the SDXL base 1.0 model with 0.9 vae as the 1.0 vae also applies a horrible watermark to the images.
