### ISSUE TITLE
How to debug custom pipeline locally ?

### ISSUE THREAD

**Issue by pansanity666** [huggingface/diffusers#4533]
Hi, 
    I build diffusers from source, and I am using ControlNet. However, diffusers seems not to load the custom pipeline from ```diffusers/examples/community/stable_diffusion_controlnet_img2img.py``` as I expected. Instead, it seems to download from the hub and cache a new ```stable_diffusion_controlnet_img2img.py``` somewhere else.  

My question is how to make it load from my local ```diffusers/examples/community/stable_diffusion_controlnet_img2img.py``` so that I can debug it locally?

Best,

**Comment by sayakpaul** [comment]
I hope this documentation helps: https://huggingface.co/docs/diffusers/main/en/using-diffusers/custom_pipeline_examples. 

Closing the issue, feel free to reopen. 

Also, since this is usage question, we'd appreciate if you posted it on our Discord forum going forward.

**Comment by pansanity666** [comment]
I have read this doc, yet my problem not solved. Where is the discord ?

**Comment by sayakpaul** [comment]
https://discuss.huggingface.co/t/join-the-hugging-face-discord/11263
