### ISSUE TITLE
Question regarding SDXL micro-conditioning and diffusers SDXL training

### ISSUE THREAD

**Issue by xiankgx** [huggingface/diffusers#4537]
In the past with SD 1.x and SD 2.x, we just need to set the resolution with the SD training scripts.

However, with SDXL 0.9/1.0 with the micro-conditioning with original image size, crop coordinates, target size, does this mean if we finetune the model on 1024x1024, the model COULD be largely unchanged in other resolutions like 512x512 because these micro-conditions are not present during finetuning.

Does this also means that the current SDXL training scripts would not be sufficient without some sort some of aspect ratio bucketing and training at various target sizes.

Please shed like in this.

**Comment by xiankgx** [comment]
@sayakpaul

**Comment by sayakpaul** [comment]
You are right. However, the LoRA fine-tuning script for text_to_image fine-tuning with SDXL has the support. #4505 also has it. Would be good to add it to the other scripts too. Does this answer your question?

**Comment by xiankgx** [comment]
Hi @sayakpaul , thanks for the swift reply. However, I don't understand what you mean by "has support". I'm currently working with the SDXL LoRA training script, and while it supports micro-conditioning, there is no "data bucketing training" which would make a finetuned model generalizable to other aspect ratios/resolution which was previously not required in SD 1.x/2.x due to the absence of micro-conditioning.

**Comment by xiankgx** [comment]
To be clearer, I'm attempting to finetune a model with by own dataset, and my ideal situation is for it to be able to generate at the shorter side size of 1024 with the common aspect ratios like 1:1, 4:3, 16:9, etc. However, without explicitly training for these target resolutions, there is a high chance my finetuned model will only work when generating at 1024x1024.

**Comment by sayakpaul** [comment]
We won't be incorporating support for aspect ratio bucketing in our training scripts to keep them simple and customizable enough for the community. 

>  However, I don't understand what you mean by "has support". 

I meant we now store the original sizes and the crop coordinates during dataloading and prepare the micro-conditioning embeddings accordingly. At least this is the case for this script: https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora_sdxl.py. But we won't support fine-tuning with multiple aspect ratios anytime soon for the reasons stated above.

**Comment by xiankgx** [comment]
Ok, thank you so much for the enlightenment.

**Comment by bghira** [comment]
@xiankgx if you are comfortable with python. you could implement a LoRA training script based on the Diffusers one, using the `train_sdxl.py` script in my project as a basis. this is a general fine-tune script, and it supports data bucketing without cropping. however, it does not have LoRA network support. this would be trivial to add.

**Comment by xiankgx** [comment]
Hi @bghira , can you point me to your training script and/or project?

**Comment by sayakpaul** [comment]
Here: https://github.com/bghira/SimpleTuner. Any reason why this was reopened?

**Comment by xiankgx** [comment]
Sorry, I will close this. Thanks @sayakpaul .
