### ISSUE TITLE
convert inpainting tensorRT OutOfMemory in 3090

### ISSUE THREAD

**Issue by kelisiya** [huggingface/diffusers#4538]
Why do we need so much cuda memory? this is unreasonable

**Comment by sayakpaul** [comment]
Hi. We don't maintain TensorRT conversion scripts. Feel free to ping the author of those scripts directly. So, I am gonna close this issue.

**Comment by henbucuoshanghai** [comment]
inpainting tensorRT 解决了吗？哪里有好的开源感谢
