### ISSUE TITLE
The first image generated with LMSScheduler is completely green

### ISSUE THREAD

**Issue by allo-** [huggingface/diffusers#454]
### Describe the bug

The first image generated with LMSScheduler is just a green image.

### Reproduction

Run with:

    lms = LMSDiscreteScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear"
    pipe = StableDiffusionPipeline.from_pretrained(..., scheduler=lms)

instead of using the default scheduler. Then the first image is completely green. The workaround I am using is to run one step before the actual diffuse function:

    if isinstance(pipe.scheduler, LMSDiscreteScheduler):
        # Prevent an empty first frame
        with autocast("cuda"):
            image = diffuse(pipe, text_embeddings, init1, 1, settings["guidance_scale"], eta)

Afterward I compute images similarly, but using e.g. 50 steps instead of one and everything is fine. The default scheduler also seems to work. I did not test other schedulers yet.

### System Info

Diffusers from git, python 3.10.6, CUDA with a RTX 3060 card

**Comment by patrickvonplaten** [comment]
cc @anton-l

**Comment by patrickvonplaten** [comment]
Probably related to: https://github.com/huggingface/diffusers/issues/336

**Comment by patrickvonplaten** [comment]
@allo- is this issue still relevant?

**Comment by allo-** [comment]
I removed the workaround and cannot reproduce the issue. I guess I close here for now and if my scripts without the workarounds get the problem again I reopen or make a new issue.

**Comment by anton-l** [comment]
Yes, the issue was caused by improper LMS timesteps initialization and should be fixed now :)
