### ISSUE TITLE
StableDiffusionXLImg2ImgPipeline cannot produce more than 1 images

### ISSUE THREAD

**Issue by eminn** [huggingface/diffusers#4542]
### Describe the bug

If the `num_images_per_prompt=1`, it works fine but any value bigger than 1 produces the following error.

### Reproduction

```python
import torch

from diffusers import AutoencoderKL, DiffusionPipeline, StableDiffusionXLImg2ImgPipeline

vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)

pipe = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    vae=vae,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
)
pipe.to("cuda")
pipe.enable_vae_slicing()
pipe.enable_vae_tiling()

refiner = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0",
    vae=vae,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
)
refiner.to("cuda")
refiner.enable_vae_slicing()
refiner.enable_vae_tiling()

generator = torch.Generator("cuda").manual_seed(0)


prompt = "a woman holding a coffee mug"
images = pipe(prompt=prompt, num_images_per_prompt=2, generator=generator).images
refined_images = refiner(prompt=prompt, image=images, generator=generator).images
```

### Logs

```shell
python test_inference.py 
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.73it/s]
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  4.32it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:11<00:00,  4.38it/s]
  0%|                                                                                                                                                                                                   | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/code/test_inference.py", line 37, in <module>
    images = refiner(prompt=prompt, negative_prompt=negative_prompt, image=image, generator=generator).images
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/code/diffusers/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 963, in __call__
    noise_pred = self.unet(
                 ^^^^^^^^^^
  File "/code/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/diffusers/src/diffusers/models/unet_2d_condition.py", line 871, in forward
    emb = emb + aug_emb if aug_emb is not None else emb
          ~~~~^~~~~~~~~
RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0
```

### System Info

- `diffusers` version: 0.20.0.dev0
- Platform: Linux-5.15.107+-x86_64-with-glibc2.31
- Python version: 3.11.4
- PyTorch version (GPU?): 2.0.0+cu118 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: Yes, A100 40gb
- Using distributed or parallel set-up in script?: no

### Who can help?

@patrickvonplaten  @sayakpaul

**Comment by sayakpaul** [comment]
@yiyixuxu could you take a look here?

**Comment by adi-bhatl-1998** [comment]
from fastcore.all import concat
negative_prompt=None
prompt = "a woman holding a coffee mug"
images = pipe(prompt=prompt, num_images_per_prompt=2, generator=generator).images
negative_prompt="white"
refined_images = concat(refiner(prompt=prompt, num_images_per_prompt=2,negative_prompt=negative_prompt, image=images[1], generator=generator,guidance_scale=g,strength=0.7).images for g in [3,7])
1.define your negative prompt . it can be something you want to avoid in the image .
2. when you feed your images variable to the refiner pipe make sure to pass only one among the list images , that is either images[0] or images[1] as in most  models are not equipped to handle more than a single image as an input

**Comment by eminn** [comment]
> @eminn
> 
> from fastcore.all import concat negative_prompt=None prompt = "a woman holding a coffee mug" images = pipe(prompt=prompt, num_images_per_prompt=2, generator=generator).images negative_prompt="white" refined_images = concat(refiner(prompt=prompt, num_images_per_prompt=2,negative_prompt=negative_prompt, image=images[1], generator=generator,guidance_scale=g,strength=0.7).images for g in [3,7]) 1.define your negative prompt . it can be something you want to avoid in the image . 2. when you feed your images variable to the refiner pipe make sure to pass only one among the list images , that is either images[0] or images[1] as in most models are not equipped to handle more than a single image as an input

Hi @adi-bhatl-1998, Thanks for your reply. For item 1, it is leftover from cleaning up the script for bug report, I'll remove it shouldn't be relevant.

For item 2, the point is passing multiple images and getting back multiple ones, the pipeline supports passing images as list, see https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py#L659-L666

**Comment by eminn** [comment]
@adi-bhatl-1998  In meantime when I was looking into your script, I realized that I wasn't passing the `num_images_per_prompt` to the refiner, somehow I thought passing images as a list would make it work. After providing the same `num_images_per_prompt` parameter, it works. Thanks for the heads up.
