### ISSUE TITLE
Support controlnet param in AutoPipeline from_pipe() method

### ISSUE THREAD

**Issue by slep0v** [huggingface/diffusers#4545]
Currently from_pipe() method preserves 'controlnet' property of the pipeline.
So the transitions like:

t2i/i2i/inpaint <-> (t2i/i2i/inpaint)_controlnet

are only possible by using from_pretrained method which will take additional memory and compute time.

**Comment by sayakpaul** [comment]
Please elaborate this a bit more so that the core contributor of AutoPipeline (@yiyixuxu) could understand it in finer details.

**Comment by slep0v** [comment]
Sure! 
Suppose we have a `pipeline` which is an instance of `StableDiffusionControlNetPipeline` class (same applies to img2img and inpaint variants).

Now AutoPipeline transformation such as
`new_pipeline = AutoPipelineForText2Image.from_pipe(pipeline)`
Will also create a `StableDiffusionControlNetPipeline`

And conversely if `pipeline` is a `StableDiffusionPipeline`, then
`new_pipeline = AutoPipelineForText2Image.from_pipe(pipeline, controlnet=controlnet)`
does not create a `ControlNet` version.

Currently usage of `from_pipe` alongside of `controlnet` param works only to update ControlNet models if a pipeline is already a `StableDiffusionControlNetPipeline`.

___

What I propose is to include explicit ControlNet mode switch in the `from_pipe` method:

- `AutoPipelineFor{...}.from_pipe(pipeline, controlnet=controlnet)` - in addition to current behavior allow to transform a pipeline into a ControlNet version
- `AutoPipelineFor{...}.from_pipe(pipeline, controlnet=None)` - make sure that new pipeline will be **not** a ControlNet version, even if it wasn't
- `AutoPipelineFor{...}.from_pipe(pipeline)` - if not specified (`'controlnet' not in kwargs`) - preserve the type of a pipeline (ControlNet stays ControlNet, vanilla stays vanilla)

**Comment by yiyixuxu** [comment]
@slep0v 

Thanks! Yes I agree we should support `from_pipe` between a pipeline and its ControlNet pipeline counterpart.

I think the design can work. let me know what you think @sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
Makes sense to me!

**Comment by patrickvonplaten** [comment]
Agree! @yiyixuxu want to give it a try?

**Comment by yiyixuxu** [comment]
@patrickvonplaten yep, i'd love to!

**Comment by yiyixuxu** [comment]
@slep0v We added this feature based on your design. Thanks! 
https://github.com/huggingface/diffusers/pull/4861
