### ISSUE TITLE
[Need Help] A training script for train a t2i model to inpainting model

### ISSUE THREAD

**Issue by Bikesuffer** [huggingface/diffusers#4552]
Hi, recently there is small stable diffusion model (SD-Small) provided by the segmind(https://github.com/segmind/distill-sd)

But it is for text-2-img task. 
When I use the SD-Small Unet in the StableDiffusionInpaintPipeline, the generated result looks not right(masked area content is totally different from the non-masked area content).
I am wondering if there is a training script that I can use to train a t2i Unet to an inpainting Unet?

**Comment by sayakpaul** [comment]
Please post these questions on our Discord forum as it's not related to our codebase.
