### ISSUE TITLE
Incorrect initialization value of guidance_rescale in different pipelines

### ISSUE THREAD

**Issue by a-r-r-o-w** [huggingface/diffusers#4553]
Hi! I've been trying to understand how SD inference works, and diffusers has been really helpful with that.

As I was going through the code, I found this line of code, which might be a minor bug. The documentation says that it is defaulted to `0.7` but the code has it defaulted to `0.0`. The [arxiv](https://arxiv.org/pdf/2305.08891.pdf) paper states that `0.7` works great as well.

https://github.com/huggingface/diffusers/blob/7b07f9812a58bfa96c06ed8ffe9e6b584286e2fd/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L543

Some of the pipelines with this initialization value issue:
[src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py)
[src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py)
[All pipelines in src/diffusers/pipelines/stable_diffusion_xl](https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines/stable_diffusion_xl)
[examples/community/stable_diffusion_reference.py](https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_reference.py)

Is this something that needs to be fixed?

**Comment by sayakpaul** [comment]
Would you mind opening up a PR for this?
