### ISSUE TITLE
Kandinsky 2.2 example fails with OOM

### ISSUE THREAD

**Issue by bgjackma** [huggingface/diffusers#4554]
### Describe the bug

I am attempting to execute the basic example given for the Kandinsky 2.2 pipeline in Colab, but I'm getting OOM errors due to what appears to be a memory leak in the prior pipeline.

### Reproduction

[Gist of minimal notebook](https://gist.github.com/bgjackma/8524a16a87bb4661c99d7422c0ec5974)

### System Info

Google Colab Notebook
T4 runtime
diffusers 0.19.3

### Who can help?

@patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu 

Have you tried using model offloading? 

I would try:

```python
pipe_prior = KandinskyV22PriorPipeline.from_pretrained("kandinsky-community/kandinsky-2-2-prior")
pipe_prior.enable_model_cpu_offload()
```

When you call the offloading API, you don't have to explicitly place the pipeline on GPU.

**Comment by seruva19** [comment]
It should work in colab if you load it using half precision:

```python
pipe_prior = KandinskyV22PriorPipeline.from_pretrained("kandinsky-community/kandinsky-2-2-prior", torch_dtype=torch.float16)
```
