### ISSUE TITLE
AttributeError: 'super' object has no attribute '__getattr__'

### ISSUE THREAD

**Issue by RossoneriZhao** [huggingface/diffusers#4557]
### Describe the bug

When building the DiffusionPipeline from_pretrained, I get the bug:
"AttributeError: 'super' object has no attribute '__getattr__'"

### Reproduction

from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
	"stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
).to("cuda")

### Logs

```shell
Traceback (most recent call last):
  File "/home/dqwang/scratch/jtzhao/Coke/diffuser/test.py", line 5, in <module>
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
  File "/home/dqwang/mambaforge/envs/diffuser/lib/python3.7/site-packages/diffusers/pipelines/pipeline_utils.py", line 923, in from_pretrained
    **kwargs,
  File "/home/dqwang/mambaforge/envs/diffuser/lib/python3.7/site-packages/diffusers/pipelines/pipeline_utils.py", line 1430, in download
    use_onnx = use_onnx if use_onnx is not None else pipeline_class._is_onnx
  File "/home/dqwang/mambaforge/envs/diffuser/lib/python3.7/site-packages/diffusers/utils/import_utils.py", line 575, in __getattr__
    return super().__getattr__(cls, key)
AttributeError: 'super' object has no attribute '__getattr__'
```

### System Info

diffusers version: 0.19.3
Platform: Linux-5.15.0-25-generic-x86_64-with-debian-bookworm-sid
Python version: 3.7.12
PyTorch version (GPU?): 1.13.1+cu117 (True)
Huggingface_hub version: 0.16.4
Transformers version: not installed
Accelerate version: 0.20.3
xFormers version: not installed
Using GPU in script?: Yes
Using distributed or parallel set-up in script?: No

**Comment by realliujiaxu** [comment]
You need use StableDiffusionPipeline instead of DiffusionPipeline.

**Comment by ClementPinard** [comment]
Hi, thanks for the info !

FYI, the doc needs to be updated as it uses DiffusionPipeline sometimes, e.g. here : https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/stable_diffusion_xl#1-ensemble-of-expert-denoisers

**Comment by sayakpaul** [comment]
Related to: https://github.com/huggingface/diffusers/issues/4598.

**Comment by m-pektas** [comment]
When I apply the followings, it works for me. ✅ 
- You need to install diffusers and transformers libraries with pip 
- Use StableDiffusionPipeline instead of DiffusionPipeline.

Readme file need to be updated. ⚠️

**Comment by patrickvonplaten** [comment]
Corrected on "main"
