### ISSUE TITLE
Please add “original_config_file” argument for download_from_original_stable_diffusion_ckpt()

### ISSUE THREAD

**Issue by wodsoe** [huggingface/diffusers#4561]
Please add “original_config_file” argument for download_from_original_stable_diffusion_ckpt(),
then can set a local config file.

![QQ截图20230810213746](https://github.com/huggingface/diffusers/assets/40934627/607875a4-739e-43c9-90a0-289431ba9787)
![QQ截图20230810214036](https://github.com/huggingface/diffusers/assets/40934627/5b33f59e-2223-4bce-931f-5467b2cdc4cc)

**Comment by PC-USTC** [comment]
I also had the problem

**Comment by sayakpaul** [comment]
@DN6 could you give this a look?

**Comment by patrickvonplaten** [comment]
I don't fully understand the issue here @wodsoe - `original_config_file` is present here: https://github.com/huggingface/diffusers/blob/24c5e7708bb75076dd8e79ccaea195640555f945/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L1115

**Comment by Louis24** [comment]
not working
