### ISSUE TITLE
Strange blue artifacts when running on MPS

### ISSUE THREAD

**Issue by abesmon** [huggingface/diffusers#457]
### Describe the bug

When running SD on mps, pictures appears with strange blue artifacts.

They appear on any count of inference steps. I tried on 50 and on 100. Blue noise everywhere

![astronaut_rides_horse](https://user-images.githubusercontent.com/16459467/189448686-5ddafd8a-8182-4b1d-b6c0-68adb5b7e34d.png)
![robotic artist drawing on apple macbook_1](https://user-images.githubusercontent.com/16459467/189448647-4b5fd4cf-462e-4290-8eeb-7f599abd9787.png)
![robotic artist drawing on apple macbook](https://user-images.githubusercontent.com/16459467/189448650-0904e234-2a84-4ea1-8cf3-84f41d5fd0e9.png)

### Reproduction

```
import torch
from torch import autocast
from diffusers import StableDiffusionPipeline

model_id = "CompVis/stable-diffusion-v1-4"
device = "mps"
pipe = StableDiffusionPipeline.from_pretrained(model_id, use_auth_token=True)
pipe = pipe.to(device)
prompt = "robotic artist drawing on apple MacBook"
_ = pipe(prompt, num_inference_steps=1)
image = pipe(prompt, num_inference_steps=100)["sample"][0] 
```

### Logs

```shell
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
{'trained_betas'} was not found in config. Values will be initialized to default values.
```
in `StableDiffusionPipeline.from_pretrained(model_id, use_auth_token=True)`

```
/opt/anaconda3/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py:663: UserWarning: The operator 'aten::index.Tensor' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  pooled_output = last_hidden_state[torch.arange(last_hidden_state.shape[0]), input_ids.argmax(dim=-1)]
```
on `pipe(prompt, num_inference_steps=1)`
```


### System Info

- `diffusers` version: 0.3.0
- Platform: macOS-12.4-arm64-arm-64bit
- Python version: 3.9.12
- PyTorch version (GPU?): 1.13.0.dev20220604 (False)
- Huggingface_hub version: 0.8.1
- Transformers version: 4.21.3
- Using GPU in script?: mps
- Using distributed or parallel set-up in script?: <fill in>

**Comment by abesmon** [comment]
it seems that it was caused by PyTorch version. I've upgraded to `1.13.0.dev20220909` and now everything's fine:

![robotic artist drawing on apple macbook_2](https://user-images.githubusercontent.com/16459467/189451944-2b661bfa-034d-4e37-bffc-f34f29580d3e.png)
![robotic artist drawing on apple macbook_3](https://user-images.githubusercontent.com/16459467/189451954-83e4c796-fd23-4e50-b413-64a8ade0ff7a.png)

**Comment by abesmon** [comment]
strange thing: new PyTorch version dramatically slows everything down.

previously (1.13.0.dev20220604) inference step took ~ 2s
now (1.13.0.dev20220909) it takes ~7-8s

**Comment by patil-suraj** [comment]
cc @pcuenca
