### ISSUE TITLE
Running the SD API, but the memory keeps increasing and does not automatically release?

### ISSUE THREAD

**Issue by pengfei-lyu** [huggingface/diffusers#4573]
Guys, I'm using this API to generate images, but as I continue to use it, I find that the available memory keeps decreasing and it does not free up automatically. 
So, is there any way to resolve this issue?

**Comment by sayakpaul** [comment]
There's no way for us to know how you're using the API and in what settings. Please elaborate on those things and we might be able to provide some answers.

**Comment by pengfei-lyu** [comment]
> There's no way for us to know how you're using the API and in what settings. Please elaborate on those things and we might be able to provide some answers.

Use flask to call the api to generate results. In addition, this is the API boot command. What information is needed More specific information?

com:
nohup python launch.py --listen --enable-insecure-extension-acces --xformers --no-half-vae --no-half --disable-nan-check --api --api-log --no-gradio-queue --opt-sdp-attention --skip-version-check > ./runlog.log 2>&1 &

**Comment by sayakpaul** [comment]
Does this happen with FastAPI, too? Sorry, this does not fall under our jurisdiction, so, we cannot comment definitively. I welcome you to join our [Discord forum](https://discuss.huggingface.co/t/join-the-hugging-face-discord/11263) and posting your issue there.
