### ISSUE TITLE
Inconsistency with Documentation: SDXL MultiControlNet Cannot Be Used

### ISSUE THREAD

**Issue by yamkz** [huggingface/diffusers#4585]
### Describe the bug

In the documentation, there is an indication that MultiControlNet is supported, as seen in the following description:
"controlnet (ControlNetModel or List[ControlNetModel]) — Provides additional conditioning to the unet during the denoising process. If you set multiple ControlNets as a list, the outputs from each ControlNet are added together to create one combined additional conditioning."

However, when actually entering a list or tuple, the following error occurs:

`if isinstance(controlnet, (list, tuple)):
    raise ValueError("MultiControlNet is not yet supported.")
`
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py

### Reproduction

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-6-a996611905d6>](https://localhost:8080/#) in <cell line: 44>()
     42 
     43 # Initialize the XL pipeline with the controlnets
---> 44 pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
     45     "Linaqruf/animagine-xl", controlnet=controlnets, vae=vae, torch_dtype=torch.float16
     46 )

1 frames
[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py](https://localhost:8080/#) in __init__(self, vae, text_encoder, text_encoder_2, tokenizer, tokenizer_2, unet, controlnet, scheduler, force_zeros_for_empty_prompt, add_watermarker)
    121 
    122         if isinstance(controlnet, (list, tuple)):
--> 123             raise ValueError("MultiControlNet is not yet supported.")
    124 
    125         self.register_modules(

ValueError: MultiControlNet is not yet supported.

### System Info

Environment: Google Colab
library: opencv-python diffusers transformers accelerate safetensors diffusers["torch"] transformers

**Comment by sayakpaul** [comment]
There's no indication in the document that would suggest that SDXL MultiControlNet is supported. 

However, https://github.com/huggingface/diffusers/pull/4597.

**Comment by yamkz** [comment]
thank you!

Also, the document is saying this about it
https://huggingface.co/docs/diffusers/main/en/api/pipelines/controlnet_sdxl#diffusers.StableDiffusionXLControlNetPipeline
![image](https://github.com/huggingface/diffusers/assets/57112629/a83a83d8-34bb-4143-8ad7-c7ef223b43e3)
