### ISSUE TITLE
Incremental Diffusion

### ISSUE THREAD

**Issue by deepdiffuser** [huggingface/diffusers#459]
**Is your feature request related to a problem? Please describe.**

An interesting feature for consumers of the `diffusers` API may be *incremental diffusion*, that is, the ability to parse diffusion results at every `n` steps during the pipeline run.

**Describe the solution you'd like**
One way of implementing this is through a callback as an optional kwarg to the diffusion pipeline, as here (https://github.com/deepdiffuser/diffusers/commit/af6ebdad9a64cd57bab98f5802d8e9aac254aeb2), but I'm open to other suggestions.

**Describe alternatives you've considered**
I've considered just unrolling the diffusion loop into the caller, and this works, but it might still be interesting to have this as a feature in the pipeline.

**Additional context**

- My attempt at implementing this: https://github.com/deepdiffuser/diffusers/commit/af6ebdad9a64cd57bab98f5802d8e9aac254aeb2

**Comment by patrickvonplaten** [comment]
Hey @deepdiffuser, I think we could easily add such a pipeline under the https://github.com/huggingface/diffusers/tree/main/examples/community folder. Would you like to give it a try? Would love to advertise it!

**Comment by jamestiotio** [comment]
I am a proponent of adding this to the official examples.

Looking through the [original Stable Diffusion repository](https://github.com/CompVis/stable-diffusion), it seems that their implementation provides the parameters `callback` and `img_callback` [here](https://github.com/CompVis/stable-diffusion/blob/main/ldm/models/diffusion/ddim.py#L156-L157), [here](https://github.com/CompVis/stable-diffusion/blob/main/ldm/models/diffusion/ddpm.py#L1161-L1162), and [here](https://github.com/CompVis/stable-diffusion/blob/main/ldm/models/diffusion/plms.py#L163-L164). Adding this feature would further align the available API between `diffusers` and the original Stable Diffusion repository.

Furthermore, exposing such callbacks in the official examples would allow for further customization by consumers of `diffusers` and follow the **easy-to-tweak** philosophy defined in [this README](https://github.com/huggingface/diffusers/blob/main/examples/README.md). One use case for this feature might include updating a user interface to show the current status of inference.

I believe that adding this to the official examples would benefit users of the `diffusers` library significantly. I also don't mind creating a PR for this feature if the maintainers are okay with this!

**Comment by patrickvonplaten** [comment]
A PR would be great @jamestiotio ! Thanks a lot for offering to do this. 

Think then we could also see better what the best place is :-) Note that we follow this philosophy for diffusion pipelines: https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines#contribution

**Comment by ayan4m1** [comment]
Just tagging on to this, I don't think I solved the problem the same way you're all discussing, but this is how I got that functionality: https://github.com/ayan4m1/diffusers/commit/fc2d3ddafa4a0c711e332848a6ae873f079797a8
