### ISSUE TITLE
Stable Diffusion ONNX requires cpu `onnxruntime` even if CUDA version is installed

### ISSUE THREAD

**Issue by Vijayabhaskar96** [huggingface/diffusers#460]
### Describe the bug

The ONNX support doesn't work with `CUDAExecutionProvider` I installed `onnxruntime-gpu`
Running 
`import onnxruntime as ort
ort.get_device()`
results
`GPU`
and 
`ort.get_available_providers()`
results
`['CPUExecutionProvider', 'TensorrtExecutionProvider', 'CUDAExecutionProvider']`
but diffusers complains onnxruntime not installed and wants me to install the cpu version(pip install onnxruntime).

### Reproduction

Install 
`pip install onnxruntime-gpu`

and run
```
from diffusers import StableDiffusionOnnxPipeline

pipe = StableDiffusionOnnxPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    revision="onnx",
    provider="CUDAExecutionProvider",
    use_auth_token=true,
)
```

### System Info

- `diffusers` version: 0.3.0
- Platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Huggingface_hub version: 0.9.1
- Transformers version: 4.21.3
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by pcuenca** [comment]
Works for me. Could you please paste the exact error messages you get when you run the example? Thanks!

**Comment by Vijayabhaskar96** [comment]
Here is the [Colab Notebook](https://colab.research.google.com/drive/1gPEaEojk1OqYc7JGLSS964KCBrNwKC_C?usp=sharing). replicating the error.

**Comment by SkyTNT** [comment]
This is my PR trying to fix this issues: #440

**Comment by pcuenca** [comment]
Oh, I see, I didn't understand it initially; it works for me because I have both packages installed.

Thanks @Vijayabhaskar96 and @SkyTNT, what do you think @anton-l ?

**Comment by patrickvonplaten** [comment]
@anton-l is this solved now?

**Comment by anton-l** [comment]
Fixed in https://github.com/huggingface/diffusers/pull/440 :+1:

**Comment by patrickvonplaten** [comment]
Thanks!
