### ISSUE TITLE
Controlnet SD-XL-v1-refiner+base

### ISSUE THREAD

**Issue by mzeynali** [huggingface/diffusers#4602]
Currently, I tested controlnet SD-XL-v1-base model, and it's great, but I want to know when you want to release controlnet SD-XL-v1-base+refinner codes?

**Comment by xiankgx** [comment]
Hmmm, its already released. You just need to chain the models together. Or look for a pipeline that incorporates both.

**Comment by mzeynali** [comment]
@xiankgx Can you give that link, I don't find that.

**Comment by sayakpaul** [comment]
Discord forum is a better place to ask questions like this.
