### ISSUE TITLE
StableDiffusionLongPromptWeightingPipeline with inpaint model report error

### ISSUE THREAD

**Issue by junnikokuki** [huggingface/diffusers#4605]
### Describe the bug

I use StableDiffusionInpaintPipeline and dreamshaper v8 inpainting model to do inpainting, it works well. Then I want to make more prompts, so I added the StableDiffusionLongPromptWeightingPipeline. But it reports following error:

   File "/data/images/codes/models/sd/lpw_stable_diffusion.py", line 1451, in inpaint
     return self.__call__(
   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
     return func(*args, **kwargs)
   File "/data/images/codes/models/sd/lpw_stable_diffusion.py", line 1061, in __call__
     noise_pred = self.unet(
   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1538, in _call_impl
     result = forward_call(*args, **kwargs)
   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 899, in forward
     sample = self.conv_in(sample)
   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
     return forward_call(*args, **kwargs)
   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 463, in forward
     return self._conv_forward(input, self.weight, self.bias)
   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
     return F.conv2d(input, weight, bias, self.stride,
   RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[2, 4, 85, 64] to have 9 channels, but got 4 channels instead

If I change to dreamshaper v8 with no inpaint model it works but without inpaint effect.

### Reproduction

with StableDiffusionInpaintPipeline:
results = pipe(prompt=prompt, negative_prompt=negative_prompt, image=init_img, mask_image=mask_img, height=h, width=w, strength=strength, num_inference_steps=steps, num_images_per_prompt=num_images_per_prompt, guidance_scale=guidance_scale)

with StableDiffusionLongPromptWeightingPipeline:

results = pipe.inpaint(prompt=prompt, negative_prompt=negative_prompt, image=init_img, mask_image=mask_img, height=h, width=w, strength=strength, num_inference_steps=steps, num_images_per_prompt=num_images_per_prompt, guidance_scale=guidance_scale)

### System Info

diffusers 0.18.2
debian
python 3.10

**Comment by alexblattner** [comment]
where is StableDiffusionLongPromptWeightingPipeline from? could you provide a link?

**Comment by evanferguson28** [comment]
Judging from the error message, it's probably something to do with the inpaint model's unet having 9 in channels while the base model's having only 4. It's possible that the StableDiffusionLongPromptWeightingPipeline isn't compatible with inpaint models. 
I would suggest that you use whichever pipeline that works for your inpaint model (StableDiffusionInpaintPipeline maybe) and swap in the _encode_prompt() function implemented by StableDiffusionLongPromptWeightingPipeline.

**Comment by sayakpaul** [comment]
Hey, we don't maintain the community pipelines. 

So, will suggest pinging the author of the pipeline.

**Comment by junnikokuki** [comment]
> Judging from the error message, it's probably something to do with the inpaint model's unet having 9 in channels while the base model's having only 4. It's possible that the StableDiffusionLongPromptWeightingPipeline isn't compatible with inpaint models. I would suggest that you use whichever pipeline that works for your inpaint model (StableDiffusionInpaintPipeline maybe) and swap in the _encode_prompt() function implemented by StableDiffusionLongPromptWeightingPipeline.

I do same as you pointed. Here is my solution:

from diffusers.loaders import TextualInversionLoaderMixin
from lpw_stable_diffusion import get_weighted_text_embeddings 
from transformers import CLIPTokenizer

    do_classifier_free_guidance = guidance_scale > 1.0
    if isinstance(pipe, TextualInversionLoaderMixin):
        prompt = pipe.maybe_convert_prompt(prompt, pipe.tokenizer)
        if do_classifier_free_guidance:
            negative_prompt = pipe.maybe_convert_prompt(negative_prompt, pipe.tokenizer)

    prompt_embeds, negative_prompt_embeds = get_weighted_text_embeddings(
        pipe=pipe,
        prompt=prompt,
        uncond_prompt=negative_prompt if do_classifier_free_guidance else None,
        max_embeddings_multiples=_count_token(pipe.tokenizer, prompt, negative_prompt),
    )

Then I use prompt_embeds and negative_prompt_embeds to do inpaint.
