### ISSUE TITLE
Provides t2iadapter_style_sd14v1 model

### ISSUE THREAD

**Issue by debugger-zhang** [huggingface/diffusers#4609]
### Model/Pipeline/Scheduler description

See https://huggingface.co/TencentARC/T2I-Adapter/blob/main/models/t2iadapter_style_sd14v1.pth

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by sayakpaul** [comment]
Feel free to run the conversion script https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_t2i_adapter.py.

Cc: @williamberman

**Comment by debugger-zhang** [comment]
t2iadapter_style_sd14v1 is not based on Adapter or Adapter-Light architecture, so it can not be converted with the script.

**Comment by sayakpaul** [comment]
Then we need to probably add different support for it. Feel free to open a PR and we're more than happy to guide.
