### ISSUE TITLE
Please support “class” feature in unet_1d.py

### ISSUE THREAD

**Issue by YChienHung** [huggingface/diffusers#4613]
Hello, 
I'm writing a project which need class feature.

Could you add `class_embed_type: Optional[str] = None, num_class_embeds: Optional[int] = None` into UNet1DModel?

Thank you so much!

**Comment by sayakpaul** [comment]
Feel free to fork the repo and incorporate it. Until and unless this is a widely requested feature, we won't likely be incorporating it.
