### ISSUE TITLE
ImportError: cannot import name 'StableDiffusionControlnetPipeline' from 'diffusers'

### ISSUE THREAD

**Issue by kkwhale7** [huggingface/diffusers#4615]
### Describe the bug

Traceback (most recent call last):
  File "../canny/test.py", line 27, in <module>
    from diffusers import StableDiffusionControlnetPipeline, ControlNetModel
ImportError: cannot import name 'StableDiffusionControlnetPipeline' from 'diffusers' (/opt/conda/lib/python3.8/site-packages/diffusers/__init__.py)

### Reproduction

import torch
import transformers
from diffusers import StableDiffusionPipeline
from diffusers import StableDiffusionControlnetPipeline, ControlNetModel

### System Info

- `diffusers` version: 0.18.2
- Platform: Linux-5.4.0-153-generic-x86_64-with-glibc2.10
- Python version: 3.8.13
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.22.0.dev0
- xFormers version: 0.0.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@patrickvonplaten  @sayakpaul

**Comment by sayakpaul** [comment]
It's `StableDiffusionControlNetPipeline` and not `StableDiffusionControlnetPipeline`.
