### ISSUE TITLE
Failure to load SDXL checkpoint on low ram (16gb) system.

### ISSUE THREAD

**Issue by Symbiomatrix** [huggingface/diffusers#4624]
### Describe the bug

I've written what little I know in vlad's repo: https://github.com/vladmandic/automatic/issues/2015

Basically, convert_from_ckpt.download_from_original_stable_diffusion_ckpt when accelerate is enabled loads the entire model to ram, which is right about the edge of the system's capacity. Then, it adds VAE to that, and loading the frozen tokenizers + text encoders causes the load to collapse (possibly with a lovely screen flash and killing some processes).
If moving the unet to cpu is deferred till after the tokenizers are loaded, the memory is overtaxed but doesn't crash, seemingly without affecting the load adversely. So that's one option, or make the cliptokenizer load respect available system memory.

[This branch](https://github.com/Symbiomatrix/diffusers/tree/bugfix1) demonstrates what I've updated. Do note I'm not at all sure that it's behaving correctly, it basically runs but looks a bit lacklustre in my tests and loras break. Could be something else.

### Reproduction

1) Have system with low ram (16gb, ~10gb available), but sufficient vram.
2) Load SDXL model.
3) Wait until failure: `Diffusers failed loading model using pipeline: {MODEL} Stable Diffusion XL [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 6553600 bytes. `
4) Rinse & repeat.

### System Info

Python version: 3.10
Platform: Windows 10
Diffusers: 0.19.3
GPU: RTX 3090
RAM: 16gb

### Who can help?

@williamberman, @patrickvonplaten, and @sayakpaul

**Comment by sayakpaul** [comment]
Thanks for reporting this!

Do you think it might be better to discuss this on a PR, instead? 

@DN6 could it make sense to add a separate SLOW testing suite (possibly weekly) to validate the most important conversion scripts we have under `scripts/`?

**Comment by Symbiomatrix** [comment]
@sayakpaul I opened one, but it's quite a hackjob of a fix.

**Comment by DN6** [comment]
@sayakpaul sounds good. We can add slow testing for conversions.

**Comment by Symbiomatrix** [comment]
PR has been merged, closing.
