### ISSUE TITLE
Modify lora weight after loading them

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#4630]
**Is your feature request related to a problem? Please describe.**
In order to be able to put more focus on some loras rather than others under specific conditions is necessary when implementing stuff like twoshot. I have my own version of this, but it is already not up to date.

**Describe the solution you'd like**
A way to make it so you can reference a lora you loaded into the pipeline already and modify the weight applied

**Describe alternatives you've considered**
Make it myself, but my loader is inferior.

**Additional context**
Here's how my loader does it:
reference=pipe.apply_lora(i, 0.0)
reference.alpha=the new weight you want

**Comment by alexblattner** [comment]
@sayakpaul can you show an example for code that uses scale? Is there a plan to support multiple loras?

**Comment by sayakpaul** [comment]
Check out: https://huggingface.co/docs/diffusers/main/en/training/lora. 

> Is there a plan to support multiple loras?

Yes but not immediately.

**Comment by alexblattner** [comment]
no offense, but this is really basic and a staple for months in A1111.... When do you think it could be implemented more or less?

**Comment by wen020** [comment]
@sayakpaul Does sdxl support loading multiple lora?

**Comment by sayakpaul** [comment]
No.

**Comment by yegorsw** [comment]
I just found this thread, and I would also be interested in loading multiple LoRA weights. Since it isn't in the works yet, is there any way of pre-merging two different LoRAs (with a separate weight for each) and using that as the new LoRA?

**Comment by patrickvonplaten** [comment]
You can fuse multiple LoRA weights: https://huggingface.co/docs/diffusers/main/en/api/loaders#diffusers.loaders.LoraLoaderMixin.fuse_lora

**Comment by alexblattner** [comment]
@patrickvonplaten this is far too basic... with takuma's months old repo, you can do far more. https://gist.github.com/takuma104/e38d683d72b1e448b8d9b3835f7cfa44

this looks elegant:
```
lora1 = pipe.apply_lora('lora1.safetensors', 0.0) #can start with any other weight you want too
lora2 = pipe.apply_lora('lora2.safetensors', 0.0)
lora1.alpha=0.5
```

if you implement something like that, it'd be amazing
