### ISSUE TITLE
load_textual_inversion doesn't work on SDXL

### ISSUE THREAD

**Issue by JeLuF** [huggingface/diffusers#4638]
### Describe the bug

According to the 0.19.3 documentation at https://huggingface.co/docs/diffusers/v0.19.3/en/api/pipelines/stable_diffusion/stable_diffusion_xl#diffusers.StableDiffusionXLPipeline , the StableDiffusionXLPipeline supports `load_textual_inversion()`:

> In addition the pipeline inherits the following loading methods:
>
>Textual-Inversion: [loaders.TextualInversionLoaderMixin.load_textual_inversion()](https://huggingface.co/docs/diffusers/v0.19.3/en/api/pipelines/stable_diffusion/inpaint#diffusers.StableDiffusionInpaintPipeline.load_textual_inversion)
LoRA: StableDiffusionXLPipeline.load_lora_weights()
Ckpt: [loaders.FromSingleFileMixin.from_single_file()](https://huggingface.co/docs/diffusers/v0.19.3/en/api/pipelines/stable_diffusion/img2img#diffusers.StableDiffusionImg2ImgPipeline.from_single_file)

Trying to call the function generates the error:
`RuntimeError: Embedding ...\SDXL\badX.pt can't be loaded: 'StableDiffusionXLPipeline' object has no attribute 'load_textual_inversion'`

The source code does not mention the TextualInversionLoaderMixin in the class definition at https://github.com/huggingface/diffusers/blob/v0.19.3/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L82C44-L82C44
```py
class StableDiffusionXLPipeline(DiffusionPipeline, FromSingleFileMixin, LoraLoaderMixin):
```

### Reproduction

```py
from diffusers import StableDiffusionXLPipeline
import torch
pipe = StableDiffusionXLPipeline.from_single_file( r"D:\2.35\dev\models\stable-diffusion\SDXL\dreamshaperXL10_alpha2Xl10.safetensors" )
pipe.load_textual_inversion("badX.pt")
```

### Logs

```shell
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ <stdin>:1 in <module>                                                                            │
│                                                                                                  │
│ D:\2.35\dev\stable-diffusion\env\lib\site-packages\diffusers\configuration_utils.py:137 in       │
│ __getattr__                                                                                      │
│                                                                                                  │
│   134 │   │   │   deprecate("direct config name access", "1.0.0", deprecation_message, standar   │
│   135 │   │   │   return self._internal_dict[name]                                               │
│   136 │   │                                                                                      │
│ ❱ 137 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'"   │
│   138 │                                                                                          │
│   139 │   def save_config(self, save_directory: Union[str, os.PathLike], push_to_hub: bool = F   │
│   140 │   │   """                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'load_textual_inversion'
```

### System Info

Python 3.8
Diffusers 0.19.3

### Who can help?

@stevhliu @yiyixuxu

**Comment by stevhliu** [comment]
Hi @JeLuF, `load_textual_inversion` was removed from SDXL in #4404 because it's not actually supported yet. This is reflected on the `main` version of the docs. If you're interested in contributing to this feature, check out #4405! 🤗

**Comment by JeLuF** [comment]
That's confusing. I would have expected that the 0.19.3 documentation is the most relevant one when I'm using 0.19.3.

**Comment by sayakpaul** [comment]
Will be fixed in the recent release. But if you're interested to contribute, we're more than happy to help@

**Comment by linnanwang** [comment]
is it ready now? Thanks

**Comment by sayakpaul** [comment]
I don't understand your question. Feel free to open a new issue thread.

**Comment by linnanwang** [comment]
Thanks forks!
