### ISSUE TITLE
Native diffusers LoRA weights not working with `load_lora_weights` on a local file

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#4641]
### Describe the bug

Doing a `pipe.load_lora_weights("path/to/pytorch_lora_weights.bin")` trained natively with diffusers and in diffusers format, but downloaded locally is failing.

- Doing `pipe.load_lora_weights("path/to/random_community_lora.safetensors")` works 
- Doing `pipe.load_lora_weights("hub_user/hub_repo")` also works 

The LoRA here is https://huggingface.co/minimaxir/sdxl-ugly-sonic-lora 

### Reproduction

Repro Colab: https://colab.research.google.com/drive/1nQT87AmDQvG3lZirLTbwdQTrsIag9Hmw?usp=sharing

### Logs

```shell
load_lora_weights(self, pretrained_model_name_or_path_or_dict, **kwargs)
    870         # it here explicitly to be able to tell that it's coming from an SDXL
    871         # pipeline.
--> 872         state_dict, network_alphas = self.lora_state_dict(
    873             pretrained_model_name_or_path_or_dict,
    874             unet_config=self.unet.config,

/usr/local/lib/python3.10/dist-packages/diffusers/loaders.py in lora_state_dict(cls, pretrained_model_name_or_path_or_dict, **kwargs)
   1091                 or k.startswith("lora_te2_")
   1092             )
-> 1093             for k in state_dict.keys()
   1094         ):
   1095             # Map SDXL blocks correctly.

UnboundLocalError: local variable 'state_dict' referenced before assignment
```

### System Info

diffusers == 0.19.3

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
Thanks for reporting. 

Potentially related: https://github.com/huggingface/diffusers/issues/4504. 

PR: https://github.com/huggingface/diffusers/pull/4523. I will probably make it merge-ready today and get it in the release.

**Comment by sayakpaul** [comment]
The easiest way to get rid of it would be to do:

```python
pipe.load_lora_weights(".")
```

Since the `weight_name` is already in the expected `diffusers` format.

**Comment by sayakpaul** [comment]
Should be fixed in https://github.com/huggingface/diffusers/pull/4523.
