### ISSUE TITLE
when i load a controlnet model,where is the inference code?

### ISSUE THREAD

**Issue by henbucuoshanghai** [huggingface/diffusers#4643]
I have read the code of con in  diffusers/models/controlnet.py.
but when I load a con weight,where is the code?
tks

**Comment by sayakpaul** [comment]
Refer to https://huggingface.co/docs/diffusers/main/en/api/pipelines/controlnet, https://huggingface.co/docs/diffusers/main/en/api/pipelines/controlnet_sdxl.
