### ISSUE TITLE
Implementing Fooocus

### ISSUE THREAD

**Issue by adhikjoshi** [huggingface/diffusers#4645]
Authors of controlnet have released Fooocus, which is essentially tricks to get the best quality images,

https://github.com/lllyasviel/Fooocus

List of hidden tricks

https://github.com/lllyasviel/Fooocus#list-of-hidden-tricks

How can we implement those hidden tricks on diffusers?

**Comment by sayakpaul** [comment]
Implementation questions are better redirected to our Discord forum.

**Comment by patrickvonplaten** [comment]
I think it would make a lot of sense to gauge a bit what we can learn from Fooocus - what are the most important tricks in your opinion @adhikjoshi ?

**Comment by haoqiangyu** [comment]
@patrickvonplaten 
The implementation of the "sharpness" parameter is more meaningful to sdxl, because sdxl tends to generate smoother pictures.
https://github.com/lllyasviel/Fooocus/blob/09e0d1cb3ae5a1d74443009a41da9f96c1b54683/modules/patch.py#L11

**Comment by zengjie617789** [comment]
@haoqiangyu I found the diffusers implemented the SAG in pipeline which only support SD1.5. Does the fooocus use the version of SDXL of SAG?
