### ISSUE TITLE
convert controlnet to onnx failed

### ISSUE THREAD

**Issue by yuxiaoranyu** [huggingface/diffusers#4646]
### Describe the bug

when i run convert_stable_diffusion_controlnet_to_onnx.py，while runing convert unet to onnx，have a bug

============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Unet: original .. 11360 nodes, 12381 tensors, 5 inputs, 1 outputs
Unet: cleanup .. 11360 nodes, 12381 tensors, 5 inputs, 1 outputs
Segmentation fault (core dumped)
it is bug log

### Reproduction

python convert_stable_diffusion_controlnet_to_onnx.py

### System Info

- `diffusers` version: 0.20.0.dev0
- Platform: Linux-4.4.0-186-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: 3080
- Using distributed or parallel set-up in script?: python setup.py develop

**Comment by sayakpaul** [comment]
Cc: @echarlaix

**Comment by yuxiaoranyu** [comment]
@echarlaix I use 90G memory to convert,but get same bug,During the conversion process, I observed that up to 45G memory was used,

**Comment by yuxiaoranyu** [comment]
i use the latest code convert onnx, tensorrt succeed, thanks author

**Comment by 2213601279** [comment]
> 我使用最新的代码转换onnx，tensorrt成功，感谢作者
I'd like to excuse me how to use the converted onnx. This is my code example:
`
    control_image = make_inpaint_condition(input_image, mask_image)


    controlnet = ControlNetModel.from_pretrained("./../Checkpoints/ControlNet/models/cldm/inpaint2img", torch_dtype=torch.float16)

#    pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
#        "./../Checkpoints/ControlNet/models/ldm/realisticvision_v4",
#        controlnet=controlnet,
#        torch_dtype=torch.float16,
#        safety_checker=None,
#    )
    # ONNX 推理
    pipe = ORTStableDiffusionInpaintPipeline.from_pretrained(
        "/home/aigc/aigc_development_env/aigc_algorithm_server/ProjectVTON/Checkpoints/ControlNet/onnx_models/inpaint_realist_piplineInpaint",
        controlnet=controlnet,
        torch_dtype=torch.float16,
        safety_checker=None,
        revision="onnx"
    )
`

**Comment by 2213601279** [comment]
> 我使用最新的代码转换onnx，tensorrt成功，感谢作者
I'd like to excuse me how to use the converted onnx. This is my code example:



    control_image = make_inpaint_condition(input_image, mask_image)


    controlnet = ControlNetModel.from_pretrained("./../Checkpoints/ControlNet/models/cldm/inpaint2img", torch_dtype=torch.float16)

#    pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
#        "./../Checkpoints/ControlNet/models/ldm/realisticvision_v4",
#        controlnet=controlnet,
#        torch_dtype=torch.float16,
#        safety_checker=None,
#    )
    # ONNX 推理
    pipe = ORTStableDiffusionInpaintPipeline.from_pretrained(
        "/home/aigc/aigc_development_env/aigc_algorithm_server/ProjectVTON/Checkpoints/ControlNet/onnx_models/inpaint_realist_piplineInpaint",
        controlnet=controlnet,
        torch_dtype=torch.float16,
        safety_checker=None,
        revision="onnx"
    )
thinks for you

**Comment by Alex621Lin** [comment]
@yuxiaoranyu 
Hello!
Nice to meet you!
I'm very interested in ControlNet model and I want also convert into onnx model.
But I don't have rich experience with this. So I hope you help me.
I'm really grateful if you share the convert_stable_diffusion_controlnet_to_onnx.py

Warm regards, Alex

**Comment by haoweiz23** [comment]
> > 我使用最新的代码转换onnx，tensorrt成功，感谢作者
> > I'd like to excuse me how to use the converted onnx. This is my code example:
> 
> ```
>     control_image = make_inpaint_condition(input_image, mask_image)
> 
> 
>     controlnet = ControlNetModel.from_pretrained("./../Checkpoints/ControlNet/models/cldm/inpaint2img", torch_dtype=torch.float16)
> 
> #    pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
> #        "./../Checkpoints/ControlNet/models/ldm/realisticvision_v4",
> #        controlnet=controlnet,
> #        torch_dtype=torch.float16,
> #        safety_checker=None,
> #    )
>     # ONNX 推理
>     pipe = ORTStableDiffusionInpaintPipeline.from_pretrained(
>         "/home/aigc/aigc_development_env/aigc_algorithm_server/ProjectVTON/Checkpoints/ControlNet/onnx_models/inpaint_realist_piplineInpaint",
>         controlnet=controlnet,
>         torch_dtype=torch.float16,
>         safety_checker=None,
>         revision="onnx"
>     )
> 
>     pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
>     pipe.enable_model_cpu_offload()
>     pipe.enable_xformers_memory_efficient_attention()
> ```
> 
> thinks for you

@2213601279 你好，我想知道你是怎么将controlnet输入到pipeline的呢？据我所知ORTStableDiffusionInpaintPipeline并没有controlnet接口，请问方便分享下么？

**Comment by crispyberry** [comment]
> > > 我使用最新的代码转换onnx，tensorrt成功，感谢作者
> > > I'd like to excuse me how to use the converted onnx. This is my code example:
> > 
> > 
> > ```
> >     control_image = make_inpaint_condition(input_image, mask_image)
> > 
> > 
> >     controlnet = ControlNetModel.from_pretrained("./../Checkpoints/ControlNet/models/cldm/inpaint2img", torch_dtype=torch.float16)
> > 
> > #    pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
> > #        "./../Checkpoints/ControlNet/models/ldm/realisticvision_v4",
> > #        controlnet=controlnet,
> > #        torch_dtype=torch.float16,
> > #        safety_checker=None,
> > #    )
> >     # ONNX 推理
> >     pipe = ORTStableDiffusionInpaintPipeline.from_pretrained(
> >         "/home/aigc/aigc_development_env/aigc_algorithm_server/ProjectVTON/Checkpoints/ControlNet/onnx_models/inpaint_realist_piplineInpaint",
> >         controlnet=controlnet,
> >         torch_dtype=torch.float16,
> >         safety_checker=None,
> >         revision="onnx"
> >     )
> > 
> >     pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
> >     pipe.enable_model_cpu_offload()
> >     pipe.enable_xformers_memory_efficient_attention()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > thinks for you
> 
> @2213601279 你好，我想知道你是怎么将controlnet输入到pipeline的呢？据我所知ORTStableDiffusionInpaintPipeline并没有controlnet接口，请问方便分享下么？

@haoweiz23 Hi! You can have a look at https://github.com/crispyberry/Onnx_DiffusionControlnetPipeline Plug controlnet into sd's unet model before converting onnx. Then modify the pipeline so you don't need to run controlnet separately again, just run the new unet directly. The disadvantage is that it can't hot-swap different models very well.
