### ISSUE TITLE
UNet2DModel doesn't pass "num_layers" into its mid_block

### ISSUE THREAD

**Issue by godfather991** [huggingface/diffusers#4647]
### Describe the bug

UNet2DModel doesn't specify the parameter "num_layers" of its mid_block, casuing its midblock to always has 1 ResBlock despite of the "layers_per_block". As is shown in the link below:

https://github.com/huggingface/diffusers/blob/7c3e7fedcdfb702a095861c418964e9d1e2c958a/src/diffusers/models/unet_2d.py#L182C35-L182C35

### Reproduction

self.mid_block = UNetMidBlock2D(
    in_channels=block_out_channels[-1],
    temb_channels=time_embed_dim,
    num_layers=layers_per_block,
    resnet_eps=norm_eps,
    resnet_act_fn=act_fn,
    output_scale_factor=mid_block_scale_factor,
    resnet_time_scale_shift=resnet_time_scale_shift,
    attention_head_dim=attention_head_dim if attention_head_dim is not None else block_out_channels[-1],
    resnet_groups=norm_num_groups,
    add_attention=add_attention,
)

### System Info

found in the newest version of Diffuser

### Who can help?

@patrickvonplaten @sayakpaul @williamberman

**Comment by sayakpaul** [comment]
I think it's by design i.e., we didn't expect this block to be configurable like that. For example, if you check out https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_2d_condition.py, the story is different.

**Comment by godfather991** [comment]
Thanks for explaining!
