### ISSUE TITLE
Discrepancy in scheduler `offset` usage

### ISSUE THREAD

**Issue by natolambert** [huggingface/diffusers#465]
**What API design would you like to have changed or added to the library? Why?**

@jonatanklosko brought up an issue with some confusing code (why are `alphas` indexed differently across `PNDMScheduler` and `DDIMScheduler`), and some inconsistency in the offset usage.

Two questions:
1. Why does only one shift by offset?
2. Can `offset` be changed from an arbitrary `int` to a `bool` setting that shifts by 1 (the integer shift is more confusing if the only use case is stable diffusion inference with `offset = 1`)

Discussion began in #444, see [here](https://github.com/huggingface/diffusers/issues/444#issuecomment-1242811446)

https://github.com/huggingface/diffusers/blob/8eaaa546d89f836b716e92348786d878f883ee86/src/diffusers/schedulers/scheduling_pndm.py#L338-L339

https://github.com/huggingface/diffusers/blob/8eaaa546d89f836b716e92348786d878f883ee86/src/diffusers/schedulers/scheduling_ddim.py#L204-L205

I can tell you that the PNDMScheduler and DDIMScheduler have indexed the alpha's differently for a while. Before introducing offset, PNDMScheduler had

```
alpha_prod_t = self.alphas_cumprod[timestep + 1]
alpha_prod_t_prev = self.alphas_cumprod[timestep_prev + 1]
```

And DDIMScheduler had

```
alpha_prod_t = self.alphas_cumprod[timestep]
alpha_prod_t_prev = self.alphas_cumprod[timestep_prev]
```

At minimum, we can figure this out and document better!

**Comment by natolambert** [comment]
Additional info from @jonatanklosko :

> I'm also looking through [openai/glide-text2im](https://github.com/openai/glide-text2im) and I'm almost sure they don't use the 1 offset there, so maybe that's the reason for making it configurable.

**Comment by jonatanklosko** [comment]
Looking specifically at

```
alpha_prod_t = self.alphas_cumprod[timestep + 1 - self._offset] 
```

I think it doesn't work as expected. The last timestamp is always `0 + offset`, so this means for that timestamp we will always get `alpha[1]`, no matter what the timestamp actually is (same goes for other timesteps actually). This means that unless `offset=1`, we will use wrong a alpha.

**Comment by jonatanklosko** [comment]
As far as I understand in CompVis/stable-diffusion the offset is 1, so the last timestep is `1` and they use timestep `0` for the previous alpha. In openai/glide-text2im on the other hand, the offset is 0 and for timestamp `0` the previous alpha is fixed to the value of 1.

Currently `DDIMScheduler` has the `set_alpha_to_one` option, so both of the approaches can be replicated with `offset=1, set_alpha_to_one=False` and `offset=0, set_alpha_to_one=True` respectively.

Putting the issue form the previous comment aside, currently `PNDMScheduler` behaves as if it had `set_alpha_to_one=False` (since it does `prev_timestep = max(timestep - self.config.num_train_timesteps // self.num_inference_steps, 0)`).

Perhaps it would make sense to unify these. In particular, I wonder if `offset` should be a configuration-level property, the same way `set_alpha_to_one` is (especially that the two seem related). This should also help to clean up this:

https://github.com/huggingface/diffusers/blob/8eaaa546d89f836b716e92348786d878f883ee86/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L219-L225

**Comment by patil-suraj** [comment]
cc @patrickvonplaten @anton-l

**Comment by patrickvonplaten** [comment]
@jonatanklosko, that's a very good idea. I think it makes indeed a lot of sense to move `offset` directly to the config as this is not a parameter one would change really for the same model.

**Comment by patrickvonplaten** [comment]
@jonatanklosko would you like to open a PR for it (maybe with some deprecation cycle?)

**Comment by patrickvonplaten** [comment]
Just to summarize, I think by having both:

``steps_offset`` and ``set_alpha_to_one`` in the config as you suggested @jonatanklosko we should enable all use cases that we need. We should then indeed document this nicely. 

@jonatanklosko very cool summary here, let me know if you need any help :-)

**Comment by jonatanklosko** [comment]
@patrickvonplaten there's also https://github.com/huggingface/diffusers/issues/465#issuecomment-1242816683, do you think removing `1 - self._offset` makes sense?

**Comment by patrickvonplaten** [comment]
Yes I think it makes sense to adapt the code here a bit to allow all the following options:

1. final prev_timestep gives `timesteps[0]` and final timestep gives `timesteps[1]` (compvis) => `set_alpha_to_one=False` and `offset=1`
2. final prev_timestep gives `1` and final timestep fives `timesteps[1]` => `set_alpha_to_one=True` and `offset=1`
4. final prev_timestep gives `1` and final timestep fives `timesteps[0]` (glide) => `set_alpha_ot_one=True` and `offset=0`
5. final prev_timestep gives `timesteps[0]` and final timstep gives `timesteps[0]` => `set_alpha_to_one=False` and `offset=0`

I think we can use the `final_alpha_cumprod` approach here: https://github.com/huggingface/diffusers/blob/25a51b63ca75e1351069bee87a0fb3df5abb89c3/src/diffusers/schedulers/scheduling_ddim.py#L119 
would make sense as well. 

So for the logic, I think all you need to do is to add the following line in `step_pls`
```py
alpha_prod_t_prev = self.alphas_cumprod[prev_timestep + self._offset] if prev_timestep >= 0 else self.final_alpha_cumprod
```

and also define `self.final_alpha_cumprod = np.array(1.0) if set_alpha_to_one else self.alphas_cumprod[self._offset]`

**Comment by patrickvonplaten** [comment]
So we can essentially merge the DDIM `alpha_to_one` logic into PNDM and move the offset logic more to init. Hope this makes sense :-)

**Comment by jonatanklosko** [comment]
By `timesteps[n]` you probably meant `alphas_cumprod[n]` in the list of cases above, no?

Also here:

```python
alpha_prod_t_prev = self.alphas_cumprod[prev_timestep + self._offset] if prev_timestep >= 0 else self.final_alpha_cumprod
```

I don't see why we need to add the offset. For example, at timestamp `101`, prev timestamp would be `1`, so we want to take `alphas_cumprod[1]` rather than `alphas_cumprod[1 + self._offset]`.

**Comment by patrickvonplaten** [comment]
> By `timesteps[n]` you probably meant `alphas_cumprod[n]` in the list of cases above, no?
> 
> Also here:
> 
> ```python
> alpha_prod_t_prev = self.alphas_cumprod[prev_timestep + self._offset] if prev_timestep >= 0 else self.final_alpha_cumprod
> ```
> 
> I don't see why we need to add the offset. For example, at timestamp `101`, prev timestamp would be `1`, so we want to take `alphas_cumprod[1]` rather than `alphas_cumprod[1 + self._offset]`.

Yes very good point! The PR looks very nice
