### ISSUE TITLE
Key-Locked Rank One Editing for Text-to-Image Personalization

### ISSUE THREAD

**Issue by blx0102** [huggingface/diffusers#4651]
https://arxiv.org/abs/2305.01644
This new method can enhance the ability of personalized t2i, even when user only provide only one image of their subject.

![](https://research.nvidia.com/labs/par/Perfusion/static/images_perfusion/Teaser.png)

**Comment by sayakpaul** [comment]
We're aware of this. However, IIRC, they have not yet open-sourced the codebase. When they do, we're happy to accept PRs regarding this.

**Comment by tvaranka** [comment]
Implementation by lucidrains: https://github.com/lucidrains/perfusion-pytorch

**Comment by sayakpaul** [comment]
Sadly, this didn't catch up match in the community. So, closing this due to lack of interest.
