### ISSUE TITLE
Add SDXL ControlNet pipelines for img2img and inpaint

### ISSUE THREAD

**Issue by pdoane** [huggingface/diffusers#4660]
Base SD1.5 has StableDiffusionControlNetImg2ImgPipeline and StableDiffusionControlNetInpaintPipeline but there is no corresponding versions for SDXL ControlNet.

**Comment by pdoane** [comment]
Duplicate of #4589

**Comment by yamkz** [comment]
Is StableDifferenceXLControlNetInpaintPipeline already implemented?
