### ISSUE TITLE
How to call a different scheduler when training a model from repo

### ISSUE THREAD

**Issue by jmaccall316** [huggingface/diffusers#4662]
I notice that the settings in train_dreambooth_lora_sdxl.py and the scheduler config from the repo seem to conflict. In the .py the noise scheduler is DDPM but whenever training starts it seems to still indicate that I am using the repo config scheduler, ie. EulerDiscreteScheduler. It used to be you could specify scheduler config by path but that seemed to have deprecated at some point.

**Comment by sayakpaul** [comment]
No. It still uses DDPM. Since we initialize it from the default scheduler config (which Euler Discrete), you might have seen some warnings which are completely harmless actually.
