### ISSUE TITLE
use_safetensors Fails on Windows When There Are Alternative bin Files

### ISSUE THREAD

**Issue by NullSenseStudio** [huggingface/diffusers#4665]
### Describe the bug

When a model contains safetensors and bin weights diffusers will only download the bin weights. An error is raised when `use_safetensors=True`:
```
OSError: Could not found the necessary `safetensors` weights in {'vae/diffusion_pytorch_model.fp16.bin', 'text_encoder/pytorch_model.fp16.bin', 'unet/diffusion_pytorch_model.fp16.safetensors', 'text_encoder/model.fp16.safetensors', 'vae/diffusion_pytorch_model.fp16.safetensors', 'unet/diffusion_pytorch_model.fp16.bin', 'safety_checker/pytorch_model.fp16.bin', 'safety_checker/model.fp16.safetensors'} (variant=fp16)
```
With a warning before it like:
```vae\diffusion_pytorch_model.fp16.safetensors not found```

This is happening due to a windows separator being inserted where a unix separator is expected.
https://github.com/huggingface/diffusers/blob/a10107f92b09ecb4bdabd53d91a0ca6e2df29409/src/diffusers/pipelines/pipeline_utils.py#L177

### Reproduction

```python
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
```

A model like SDXL 1.0 doesn't have this issue due to not having bin weights to compare against.
```python
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
```

### System Info

platform: Windows 11
python: 3.10.7
diffusers: 0.19.3

### Who can help?

@patrickvonplaten

**Comment by sayakpaul** [comment]
Thanks for reporting this! 

@DN6 could you look into it?

**Comment by DN6** [comment]
On it 👍🏽

**Comment by patrickvonplaten** [comment]
Gentle ping here @DN6
