### ISSUE TITLE
why canny controlnet generation so elusive?

### ISSUE THREAD

**Issue by frankchieng** [huggingface/diffusers#4670]
### Describe the bug

i have tried with some different canny edge detection algorithm like cv2 edges = cv.Canny(img,100,200) and this git clone https://github.com/FienSoP/canny_edge_detector
it looks like fine with canny image:
![car_gist_gray](https://github.com/huggingface/diffusers/assets/130369523/4b9916da-dd2c-4e62-85d4-ec47a807e1be)
but in the end when inference,the render is awkward and weird
![image](https://github.com/huggingface/diffusers/assets/130369523/b7e2e94d-fe44-4f9f-92b3-0621b8778cc7)
when i use the official canny edge image like this 
![raw_women](https://github.com/huggingface/diffusers/assets/130369523/4635b429-997e-4163-b302-c42d0e5c5d77)
the result is ok
![image](https://github.com/huggingface/diffusers/assets/130369523/cd72fc9f-2114-43b2-bdbb-6ac36aa6d5c7)
i just curious which step makes the result totally confusing?

### Reproduction

canny edge detection code as below:
import os
import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
from PIL import Image
img = cv.imread('/content/car.jpg', cv.IMREAD_GRAYSCALE)
assert img is not None, "file could not be read, check with os.path.exists()"
edges = cv.Canny(img,100,200)
print(os. getcwd())
fig1 = plt.gcf()
plt.axis('off')
plt.imshow(edges,cmap= 'gray')
fig1.savefig('/content/car_Greys.png',bbox_inches='tight', pad_inches=-0.1)

### System Info

google colab environment

**Comment by xiankgx** [comment]
Try generating at 1024 by 1024. Resize your canny image beforehand.

**Comment by sayakpaul** [comment]
Cc: @patil-suraj here maybe too.
