### ISSUE TITLE
Reduce the VRAM requirement for training sdxl_lora

### ISSUE THREAD

**Issue by aihao2000** [huggingface/diffusers#4672]
**Is your feature request related to a problem? Please describe.**

Even with lora, sdxl training requires too much VRAM.

**Describe the solution you'd like**

Add a new training script.Can we reduce the VRAM cost by precomputing ```latents,prompt_embeds,pooled_embeds```, so that vae and text_encoder can be removed during training.

**Comment by sayakpaul** [comment]
Which script are you referring to?

**Comment by sayakpaul** [comment]
Yeah, we're aware of it. If you want to open a PR to incorporate that support, that will be amazing!
