### ISSUE TITLE
ControlNet Reference Only for SD XL

### ISSUE THREAD

**Issue by jelling** [huggingface/diffusers#4675]
**Is your feature request related to a problem? Please describe.**

There is currently a Diffusers [example for using "Reference Only" with ControlNet.](https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_controlnet_reference.py) But there is not yet one for XL.

**Describe the solution you'd like**

It would be great to have an example for SD XL. 

Please and thanks!

**Comment by sayakpaul** [comment]
Feel free to add a PR :)

**Comment by jelling** [comment]
Yeah, I may do that. Before I dive in, are there any known reasons why reference only wouldn't work with the XL controlnet? 

(What I'm working around is that because textual inversions aren't supported yet for XL - thank you for your help with understanding that btw - I now need a new solution for a problem that I was previously solving with TIs.)

**Comment by sayakpaul** [comment]
The ControlNet accepts additional embeddings for SDXL. Maybe that needs to be rejigged.

**Comment by charlesmccarthy** [comment]
any updates on this?

**Comment by reimager** [comment]
Commenting so this isn't stale. Still following this issue. This pipeline would be really useful.

**Comment by sayakpaul** [comment]
Welcome to PRs.

**Comment by DN6** [comment]
PRs are welcome for this addition. But I'm just curious to understand why IP adapters wouldn't be able to provide similar functionality?

**Comment by reimager** [comment]
> PRs are welcome for this addition. But I'm just curious to understand why IP adapters wouldn't be able to provide similar functionality?

I originally struggled to get good results with the ip_adapter, but I was using another implementation. I have since tried the current one in diffusers with load_ip_adapter and it does seem to work great and basically has the same effect as reference-only so maybe this is obsolete.

**Comment by shabri-arrahim** [comment]
Need this too

**Comment by Adenialzz** [comment]
need this

**Comment by Adenialzz** [comment]
> PRs are welcome for this addition. But I'm just curious to understand why IP adapters wouldn't be able to provide similar functionality?

IP-Adapter use CLIP image encoder to produce **semantic** image features which may be lack of **detailed texture features**. While dense features from reference only controlnet will work better in specific situations.
