### ISSUE TITLE
Positional embedding for continuous input in Transformer2DModel

### ISSUE THREAD

**Issue by durdur69** [huggingface/diffusers#4681]
https://github.com/huggingface/diffusers/blob/74d902eb59f873b6156621220937f8e2521dfdc0/src/diffusers/models/transformer_2d.py#L136

I'm trying to understand where positional embeddings are added to the input in Transformer2DModel.

If the input is vectorized, ImagePositionalEmbeddings() is applied. If the input is patched, PatchEmbed() is applied. However, if the input is continuous, a groupnorm is applied and then the input is linearly projected to the inner dim, but later in the code there is no mention of positional embeddings being added. Is there an explanation for this? Thanks.

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten

**Comment by patrickvonplaten** [comment]
I don't fully understand the question. The flag `is_input_continuous` is used to separate between a standard continuous model like `Transformer2dModel` and token-based model like VQ-Diffusion: https://huggingface.co/microsoft/vq-diffusion-ithq

**Comment by durdur69** [comment]
Regardless of whether the input is continuous or token-based, doesn't positional information need to be added to the input embeddings for the model to make use of spatial information? 

This is done via learned height and width embeddings in ImagePositionalEmbeddings: https://github.com/huggingface/diffusers/blob/716286f19ddd9eb417113e064b538706884c8e73/src/diffusers/models/embeddings.py#L317 

Likewise in PatchEmbed, sin/cos positional embeddings are added to the input: https://github.com/huggingface/diffusers/blob/74d902eb59f873b6156621220937f8e2521dfdc0/src/diffusers/models/embeddings.py#L145C9-L145C78

But I see no such injection of positional information if the input is continuous. Wouldn't one expect the continuous input to be linearly projected to the inner/embedding dim of the transformer, and then positional embeddings added?

**Comment by ZHANG1023** [comment]
hello, I also have the same question

**Comment by sayakpaul** [comment]
> But I see no such injection of positional information if the input is continuous. Wouldn't one expect the continuous input to be linearly projected to the inner/embedding dim of the transformer, and then positional embeddings added?

I think that is because originally, this case was covered to implement the transformer-like blocks typically seen in the UNets of models like SD and SDXL. They don't really do positional embeddings.
