### ISSUE TITLE
Issue in utilizing the Canny image in the `StableDiffusionXLControlNetPipeline`

### ISSUE THREAD

**Issue by smmms71** [huggingface/diffusers#4685]
Hello. I'm facing an issue with utilizing the `StableDiffusionXLControlNetPipeline` for making inferences. Specifically, I'm trying to provide different types of control images, such as Canny edge or depth images to pipeline. 
In the `StableDiffusionControlNetInpaintPipeline`, there's a parameter called control_image which seems to serve this purpose. Could you please guide me on how to use the control image functionality within the StableDiffusionXLControlNetPipeline?

**Comment by sayakpaul** [comment]
We don't support inpainting with SDXL ControlNets yet. @yiyixuxu is working on integrating that.

**Comment by yiyixuxu** [comment]
hi @smmms71 
I'm not sure if I understand your issue - if you want to know how to use `StableDiffusionXLControlNetPipeline`, you can checkout our example here in our doc https://huggingface.co/docs/diffusers/main/en/api/pipelines/controlnet_sdxl#diffusers.StableDiffusionXLControlNetPipeline.__call__.example
