### ISSUE TITLE
Eliminating Lipschitz Singularities in Diffusion Models via Repeated Sampling at Low Noise Levels

### ISSUE THREAD

**Issue by clarencechen** [huggingface/diffusers#4689]
### Model/Pipeline/Scheduler description

**Abstract**
Diffusion models, which employ stochastic differential equations to sample images through integrals, have emerged as a dominant class of generative models. However, the rationality of the diffusion process itself receives limited attention, leaving the question of whether the problem is well-posed and well-conditioned. In this paper, we uncover a vexing propensity of diffusion models: they frequently exhibit the infinite Lipschitz near the zero point of timesteps. This poses a threat to the stability and accuracy of the diffusion process, which relies on integral operations. We provide a comprehensive evaluation of the issue from both theoretical and empirical perspectives. To address this challenge, we propose a novel approach, dubbed E-TSDM, which eliminates the Lipschitz singularity of the diffusion model near zero. Remarkably, our technique yields a substantial improvement in performance, e.g., on the high-resolution FFHQ dataset (256×256). Moreover, as a byproduct of our method, we manage to achieve a dramatic reduction in the Frechet Inception Distance of other acceleration methods relying on network Lipschitz, including DDIM and DPM-Solver, by over 33%. We conduct extensive experiments on diverse datasets to validate our theory and method. Our work not only advances the understanding of the general diffusion process, but also provides insights for the design of diffusion models.

**Engineering Considerations**
As noted in the paper, this technique has not been tested in large-scale text-to-image generative models such as Stable Diffusion, and will need extensive testing before it can be incorporated into Diffusers. This technique will also require sending different timestep values to the denoising UNet and the scheduler step function.

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

Paper: https://arxiv.org/pdf/2306.11251.pdf (Pseudocode present in paper, but no code repo)

**Comment by sayakpaul** [comment]
Thanks for opening it up! I think it would be great to accompany this thread with some visual examples. That will help to determine the further steps better.
