### ISSUE TITLE
Unable to load a specific LoRa after 0.20.0 update

### ISSUE THREAD

**Issue by sinanhlvc** [huggingface/diffusers#4697]
### Describe the bug

Hi! The new version breaks loading [this](https://civitai.com/models/4219?modelVersionId=10897) LoRa on SD 1.5, with the following error. 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-5-f943ddb36269>](https://localhost:8080/#) in <cell line: 1>()
----> 1 pipeline.load_lora_weights(".", weight_name="wanostyle_2.safetensors")

2 frames
[/usr/local/lib/python3.10/dist-packages/diffusers/loaders.py](https://localhost:8080/#) in _modify_text_encoder(cls, text_encoder, lora_scale, network_alphas, rank, dtype, patch_mlp)
   1388         if patch_mlp:
   1389             for name, mlp_module in text_encoder_mlp_modules(text_encoder):
-> 1390                 fc1_alpha = network_alphas.pop(name + ".fc1.lora_linear_layer.down.weight.alpha")
   1391                 fc2_alpha = network_alphas.pop(name + ".fc2.lora_linear_layer.down.weight.alpha")
   1392 

KeyError: 'text_model.encoder.layers.0.mlp.fc1.lora_linear_layer.down.weight.alpha'
```

The LoRa was working correctly on 0.19.3. 

### Reproduction

[Here's](https://colab.research.google.com/drive/1JiaDKnUoV-Xhyxa2MGfVnGdBDrI132s2?usp=sharing) a colab with the example. 

### System Info

- `diffusers` version: 0.20.0
- Platform: Linux-5.15.109+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@williamberman  @patrickvonplaten  @sayakpaul @isidentical

**Comment by sayakpaul** [comment]
https://github.com/huggingface/diffusers/pull/4706 should fix it :-)
