### ISSUE TITLE
AudioLDM 2

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#4698]
### Describe the bug

Consistency check failed: file should be of size 221586761 but has size 158281580

### Reproduction

Download the music model(cvssp/audioldm2-music) and get the error.

### Logs

```shell
raise EnvironmentError(
OSError: Consistency check failed: file should be of size 221586761 but has size 158281580 ((ÔÇª)on_pytorch_model.bin).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
```

### System Info

The alpha 21/8.

### Who can help?

@sanchit-gandhi

**Comment by tin2tin** [comment]
(I should properly make another report but trying the cvssp/audioldm2 model I get this error: 
File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\torch\nn\functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select))

**Comment by sanchit-gandhi** [comment]
Hey @tin2tin - cool to see that you're using the AudioLDM2 model already! Could you provide a reproducible code snippet to show how you're loading and running the model? This way I can reproduce the error locally on my side. Thanks!

**Comment by tin2tin** [comment]
I somehow got it working today, so I'll close it.
