### ISSUE TITLE
Glide pipeline generates wrong image dimensions

### ISSUE THREAD

**Issue by xinmiaolin** [huggingface/diffusers#47]
Hi,

Thank you very much for this amazing repository.

I was running the inference code for the glide pipeline, but the output is not of good dimension
![Screen Shot 2022-06-29 at 5 54 34 PM](https://user-images.githubusercontent.com/43487018/176570020-fca00fad-409c-4523-b506-9f6026ba621e.png)

This is the error:

![Screen Shot 2022-06-29 at 5 55 21 PM](https://user-images.githubusercontent.com/43487018/176570121-351f3c9b-5aa6-4145-91ad-23bffadfed3a.png)

It seems that the output is still the embeddings. Any suggestions, please?

Thanks!

**Comment by natolambert** [comment]
Hi @xinmiaolin, thanks for speaking up. Can you copy the text of your error into the issue so I can try to help a little more precisely? It's hard to read and search.

**Comment by xinmiaolin** [comment]
> Hi @xinmiaolin, thanks for speaking up. Can you copy the text of your error into the issue so I can try to help a little more precisely? It's hard to read and search.

Hi the problem is solved, just the output image if of the correct dimension already.
