### ISSUE TITLE
Cannot install diffusers through PIP, conflicting dependencies

### ISSUE THREAD

**Issue by trapbuilder2** [huggingface/diffusers#470]
### Describe the bug

pip install --upgrade diffusers
Collecting diffusers
  Using cached diffusers-0.3.0-py3-none-any.whl (153 kB)
Collecting regex!=2019.12.17
  Using cached regex-2022.9.11-cp37-cp37m-win32.whl (250 kB)
Collecting Pillow
  Using cached Pillow-9.2.0-cp37-cp37m-win32.whl (2.8 MB)
Requirement already satisfied: importlib-metadata in c:\users\ryans\appdata\local\programs\python\python37-32\lib\site-packages (from diffusers) (0.8)
Collecting huggingface-hub>=0.8.1
  Using cached huggingface_hub-0.9.1-py3-none-any.whl (120 kB)
Collecting diffusers
  Using cached diffusers-0.2.4-py3-none-any.whl (112 kB)
  Using cached diffusers-0.2.3-py3-none-any.whl (112 kB)
  Using cached diffusers-0.2.2-py3-none-any.whl (107 kB)
  Using cached diffusers-0.2.1-py3-none-any.whl (106 kB)
  Using cached diffusers-0.2.0-py3-none-any.whl (106 kB)
  Using cached diffusers-0.1.3-py3-none-any.whl (95 kB)
  Using cached diffusers-0.1.2-py3-none-any.whl (94 kB)
  Using cached diffusers-0.1.1-py3-none-any.whl (143 kB)
  Using cached diffusers-0.1.0-py3-none-any.whl (143 kB)
  Using cached diffusers-0.0.4-py3-none-any.whl (93 kB)
  Using cached diffusers-0.0.3-py3-none-any.whl (95 kB)
  Using cached diffusers-0.0.2-py3-none-any.whl (40 kB)
  Using cached diffusers-0.0.1-py3-none-any.whl (7.5 kB)
ERROR: Cannot install diffusers==0.0.1, diffusers==0.0.2, diffusers==0.0.3, diffusers==0.0.4, diffusers==0.1.0, diffusers==0.1.1, diffusers==0.1.2, diffusers==0.1.3, diffusers==0.2.0, diffusers==0.2.1, diffusers==0.2.2, diffusers==0.2.3, diffusers==0.2.4 and diffusers==0.3.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    diffusers 0.3.0 depends on torch>=1.4
    diffusers 0.2.4 depends on torch>=1.4
    diffusers 0.2.3 depends on torch>=1.4
    diffusers 0.2.2 depends on torch>=1.4
    diffusers 0.2.1 depends on torch>=1.4
    diffusers 0.2.0 depends on torch>=1.4
    diffusers 0.1.3 depends on torch>=1.4
    diffusers 0.1.2 depends on torch>=1.4
    diffusers 0.1.1 depends on torch>=1.4
    diffusers 0.1.0 depends on torch>=1.4
    diffusers 0.0.4 depends on torch>=1.4
    diffusers 0.0.3 depends on torch>=1.4
    diffusers 0.0.2 depends on torch>=1.4.0
    diffusers 0.0.1 depends on torch>=1.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### Reproduction

pip install --upgrade diffusers

### System Info

Windows 10 version 21H2

**Comment by natolambert** [comment]
Can you provide more info on your environment? I've seen errors like this in the past when I have an old version of PyTorch installed or something of the likes.

**Comment by trapbuilder2** [comment]
I don't believe I've ever installed PyTorch. I don't know how to check my environment, but I assume it is as close to factory settings as can be. I believe this is the first time I've run PIP on this machine, but if there's a way to check something pertinent to this issue then please tell me how

**Comment by natolambert** [comment]
Gotcha, thanks this helps. I can think about it a little, hmm.

**Comment by trapbuilder2** [comment]
Note: I reinstalled Python and now experience this error:

pip install --upgrade diffusers
Fatal error in launcher: Unable to create process using '"C:\Users\[redacted]\AppData\Local\Programs\Python\Python37-32\python.exe"  "C:\Users\[redacted]\AppData\Local\Programs\Python\Python37-32\Scripts\pip.exe" install --upgrade diffusers': The system cannot find the file specified.

I installed the 64 bit version, do I need the 32 bit version for pip?

**Comment by trapbuilder2** [comment]
The installation never completed, but it seems to be running fine now. Issue closed
