### ISSUE TITLE
Example script to train a VQ-VAE

### ISSUE THREAD

**Issue by jbdel** [huggingface/diffusers#4702]
**Describe the solution you'd like**
Example script to train a VQ-VAE

**Describe alternatives you've considered**
This example [train_unconditional.py](https://github.com/huggingface/diffusers/blob/main/examples/unconditional_image_generation/train_unconditional.py) is close but requires some edits such as another loss, remove the noise added to image,...

**Comment by sayakpaul** [comment]
Feel free to add a community example.

**Comment by isamu-isozaki** [comment]
Ah, I'll make a pr of a vqgan script I have in open-muse for hacktoberfest! I know suraj has his own but as far as I can see, I think they are similar
