### ISSUE TITLE
Modifying train_controlnet.py for Inpainting Question

### ISSUE THREAD

**Issue by nkpkg23** [huggingface/diffusers#4705]
Hi, I was trying to modify the train_controlnet.py code for stable diffusion inpainting, but after training, all of the inpainted images look noisy and like intermediate decoding steps (as shown below). I modified the script based on how latent_model_input is created in https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py, using the original image, masked image, and control original image. It looks like in issue #3645 that a new image also needs to be included. I have not included that, which may have contributed to the issue. Is the new image supposed to be the new inpainted image, and how should it be included in the training script?
![new_image](https://github.com/huggingface/diffusers/assets/141064371/764c41ef-f16d-4916-bc34-4020f30d97af)

**Comment by lOJQKA** [comment]
Hello, i see you closed this issue.
Have you solute that? If yes, can you tell me what's the "new image" and how can i get it?
Thanks.
