### ISSUE TITLE
want to  fit controlnet inference in 12 gb Ram( 2080 ti GPU ) 

### ISSUE THREAD

**Issue by AparnaAgrawal02** [huggingface/diffusers#4711]
i have trained Controlnet on 2080 0ti with the given script in Readme. but inferece is not fitting. can someone help me with it. 
i have tried 
#pipe.enable_model_cpu_offload()
 pipe.enable_sequential_cpu_offload()
add no grad grd accummulation
pipe.enable_vae_slicing()
pipe.enable_vae_tiling()
pipe.enable_xformers_memory_efficient_attention()
pipe.enable_sequential_cpu_offload()

**Comment by universewill** [comment]
mark
