### ISSUE TITLE
AutoencoderTiny is incompatible with ImageToImage, Inpainting Pipelines

### ISSUE THREAD

**Issue by slep0v** [huggingface/diffusers#4720]
### Describe the bug

Current Pipelines are implemented to expect VAE to be `AutoencoderKL` which encodes image **into distribution and not latents**. Such distribution is further sampled inside of a pipe method `_encode_vae_image`:

```
image_latents = self.vae.encode(image).latent_dist.sample(generator=generator)
```

AutoencoderTiny returns latents directly and does not require sampling, which naturally causes the following error when running inference with **all pipes that require image as input**: (img2img, inpaint) +controlnet counterparts:
```
AttributeError: 'AutoencoderTinyOutput' object has no attribute 'latent_dist
```

Possible solutions:
1) Calculate and return `DiagonalGaussianDistribution` mean and logvar on `latent_dist` getattr. But I guess this might conflict with the logic of making distilled VAE
2) Adapt all pipelines to check for the VAE type and either sample or use ready latents.

### Reproduction

Run `__call__ ` method on `StableDiffusionInpaintPipeline`, `StableDiffusionImageToImagePipeline`, `StableDiffusionInpaintPipeline`, `StableDiffusionInpaintPipeline`, `StableDiffusionControlNetImg2ImgPipeline`, `StableDiffusionControlNetInpaintPipeline`

I am not sure about XL pipeline, but I guess it would be also incompatible.

### System Info

- `diffusers` version: 0.20.0
- Platform: Windows-10-10.0.19045-SP0       
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0.0+cu118 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: 0.0.18.dev502
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by sayakpaul** [comment]
Thanks for the detailed issue thread! 

> Calculate and return DiagonalGaussianDistribution mean and logvar on latent_dist getattr. But I guess this might conflict with the logic of making distilled VAE

You're right. 

> Adapt all pipelines to check for the VAE type and either sample or use ready latents.

Could you elaborate a bit more here? Maybe with pseudo-code snippets?

**Comment by slep0v** [comment]
Sure! In `prepare_latents` method of pipelines change

```
elif isinstance(generator, list):
                init_latents = [
                    self.vae.encode(image[i : i + 1]).latent_dist.sample(generator[i]) for i in range(batch_size)
                ]
                init_latents = torch.cat(init_latents, dim=0)
            else:
                init_latents = self.vae.encode(image).latent_dist.sample(generator)
```

to

```
elif isinstance(generator, list):
                init_latents = [
                    produce_latents(self.vae.encode(image[i : i + 1]), generator=generator[i]) for i in range(batch_size)
                ]
                init_latents = torch.cat(init_latents, dim=0)
            else:
                init_latents = produce_latents(self.vae.encode(image), generator=None)
```

Where
```
def produce_latents(encoder_output: BaseOutput, generator):
    if hasattr(encoder_output, 'latent_dist'):
        return encoder_output.latent_dist.sample(generator)
    elif hasattr(encoder_output, 'latents'):
        return sencoder_output.latents
    else:
        raise AttributeError('Could not access latents of provided encoder_output')
```

I think it is better to check for the attribute of encoder output in case new encoders apperar (each should be able to provide either latents or latent_dist for future sampling)

**Comment by sayakpaul** [comment]
Looks like a clean design to me. `prepare_latents()` are also not used publicly that much so we can do this in a way that is backward compatible as well. @patrickvonplaten @yiyixuxu WDYT here?

@slep0v looks like you already have a very good idea of the solution you're proposing, would you maybe like to open a PR?

**Comment by patrickvonplaten** [comment]
Nice design! Works for me @slep0v :-)

**Comment by slep0v** [comment]
Alright, I'll open a PR. 

@patrickvonplaten where would you like me to put `produce_latents` function? I am not fully familiar with the project structure but defenitely wouldn't like to repeat it in each pipeline class.

**Comment by sayakpaul** [comment]
The generator needs to be reinitialised for every iteration of testing for as the generator is an advanced one (where it's states are changed in place). 

> @patrickvonplaten where would you like me to put produce_latents function? I am not fully familiar with the project structure but defenitely wouldn't like to repeat it in each pipeline class.

We make use of "# Copied from ..." statements to loosen that burden of copy-pasting. So, we would need to add it for each pipeline but it can be automated to a good extent with the copy mechanism.
