### ISSUE TITLE
StableDiffusionXLImg2ImgPipeline not working as expected when using with stable-diffusion-xl-base-1.0 checkpoint

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#4724]
### Describe the bug

I can't get the classic img2img example to work with sdxl 1.0
this is the output I get using the script I attached in reproduction section

![fantasy_landscape_sdxl](https://github.com/huggingface/diffusers/assets/12631849/438a850c-60d1-442f-8907-5280b8c47450)

as a reference, here is output for sd1.5 with same inputs (when resize image to `768 x 512`)

![fantasy_landscape_sd15](https://github.com/huggingface/diffusers/assets/12631849/1f71f99d-1760-4b0d-969d-a8359eb3c872)

### Reproduction

```python
import requests
import torch
from PIL import Image
from io import BytesIO

from diffusers import StableDiffusionImg2ImgPipeline, StableDiffusionXLImg2ImgPipeline, AutoencoderKL

# inputs

device = "cuda"

url = "https://raw.githubusercontent.com/CompVis/stable-diffusion/main/assets/stable-samples/img2img/sketch-mountains-input.jpg"

response = requests.get(url)
prompt = "A fantasy landscape, trending on artstation"

## pipe sdxl
init_image = Image.open(BytesIO(response.content)).convert("RGB")
init_image = init_image.resize((1024, 1024))
model_id_or_path = "stabilityai/stable-diffusion-xl-base-1.0"

vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)
pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    model_id_or_path, 
    vae=vae,
    torch_dtype=torch.float16)
pipe = pipe.to(device)

generator = torch.manual_seed(0)
images = pipe(prompt=prompt, image=init_image, strength=0.75, guidance_scale=7.5, generator=generator).images
images[0].save("fantasy_landscape_sdxl.png")
```

### System Info

- `diffusers` version: 0.21.0.dev0
- Platform: Linux-4.19.0-24-cloud-amd64-x86_64-with-glibc2.28
- Python version: 3.10.8
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.13.2
- Transformers version: 4.27.3
- Accelerate version: 0.17.0.dev0
- xFormers version: 0.0.20
- Using GPU in script?: YES
- Using distributed or parallel set-up in script?: NO

### Who can help?

@patrickvonplaten

**Comment by yiyixuxu** [comment]
The result looking good now with `strength= 0.99` ! 
![fantasy_landscape_sdxl_0 99](https://github.com/huggingface/diffusers/assets/12631849/7f7bdf3b-043a-4aa9-9784-57c8d6e2c890)

**Comment by yiyixuxu** [comment]
comparing euler vs ddim at different strength values, I would tell if one is better than another

strength = 0.75
euler         |  ddim
:-------------------------:|:-------------------------:
![fantasy_landscape_sdxl_0 75](https://github.com/huggingface/diffusers/assets/12631849/55a1a5d8-d44f-4ffa-878e-76795950fc7f)  |  ![fantasy_landscape_sdxl_ddim_0 75](https://github.com/huggingface/diffusers/assets/12631849/89fe3119-fc39-4c47-9092-d69ba43d66c6)

strength = 0.80

euler         |  ddim
:-------------------------:|:-------------------------:
![fantasy_landscape_sdxl_0 8055555820465088](https://github.com/huggingface/diffusers/assets/12631849/46991ea4-20ad-4321-95af-be7e362f7173) |  ![fantasy_landscape_sdxl_ddim_0 8055555820465088](https://github.com/huggingface/diffusers/assets/12631849/425cbab2-57e2-4c4c-80c1-41254c8f11d1)

strength = 0.86

euler         |  ddim
:-------------------------:|:-------------------------:
![fantasy_landscape_sdxl_0 8611111044883728](https://github.com/huggingface/diffusers/assets/12631849/4e8083dd-00cd-446a-a87d-400c6ca76849) |  ![fantasy_landscape_sdxl_ddim_0 8611111044883728](https://github.com/huggingface/diffusers/assets/12631849/b1e34d6e-f7f7-4e73-93e0-3404dda63640)

strength = 0.91

euler         |  ddim
:-------------------------:|:-------------------------:
![fantasy_landscape_sdxl_0 9166666865348816](https://github.com/huggingface/diffusers/assets/12631849/f95f0e17-569a-4a0e-832a-44f52598041a) | ![fantasy_landscape_sdxl_ddim_0 9166666865348816](https://github.com/huggingface/diffusers/assets/12631849/34e63dbe-d349-45ee-a7c5-fcb777bf0c70)

strength = 0.97

euler         |  ddim
:-------------------------:|:-------------------------:
![fantasy_landscape_sdxl_0 9722222089767456](https://github.com/huggingface/diffusers/assets/12631849/319b62cf-eb1d-4964-85b8-dd41b5409448)  |  ![fantasy_landscape_sdxl_ddim_0 9722222089767456](https://github.com/huggingface/diffusers/assets/12631849/b0029182-5fe9-44e1-939d-eb2235e23e72)

strength = 1.

euler         |  ddim
:-------------------------:|:-------------------------:
![fantasy_landscape_sdxl_1 0](https://github.com/huggingface/diffusers/assets/12631849/62dc06db-cb60-4b92-a8a9-9e2a6f8f22ea) | ![fantasy_landscape_sdxl_ddim_1 0](https://github.com/huggingface/diffusers/assets/12631849/e88e3519-8448-4f7f-aa0c-dd9b750f30e0)

**Comment by bghira** [comment]
for anyone who comes along later, try Inverse DDIM, too!
