### ISSUE TITLE
Auto Pipelines May Break When Using local_files_only

### ISSUE THREAD

**Issue by NullSenseStudio** [huggingface/diffusers#4727]
### Describe the bug

Auto pipelines fetch a model's config file to determine what class to use. They only pass `pretrained_model_or_path` to `load_config()`, leaving meaningful arguments like `local_files_only`, `cache_dir`, `use_auth_token`, and others to only be passed to the later `from_pretrained()` call.

The issue with `local_files_only` can occur when the cached model is outdated. The `local_config()` call will create a new snapshot directory with only `model_index.json` in it, leading to the later `from_pretrained()` call trying to use that snapshot without the necessary weights and other files.

I believe this issue and potentially others can be avoided if kwargs is passed to `load_config()` like it is in `from_pretrained()`.

### Reproduction

I don't have any specific code to reproduce this as it depends on varying cached model versions. You may be able to alter a snapshot's hash to simulate an outdated cache (`{model}/refs/main` and `{model}/snapshots/{hash}`).

### Logs

```shell
>>> from diffusers import AutoPipelineForText2Image, StableDiffusionPipeline
>>> import torch
>>>
>>> pipe = StableDiffusionPipeline.from_pretrained(
...     "stabilityai/stable-diffusion-2-1", torch_dtype=torch.float16, local_files_only=True
... )
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:34<00:00,  6.91s/it]
>>> # StableDiffusionPipeline loaded fine because it didn't alter the snapshot
>>>
>>> pipe = AutoPipelineForText2Image.from_pretrained(
...     "stabilityai/stable-diffusion-2-1", torch_dtype=torch.float16, local_files_only=True
... )
Loading pipeline components...:   0%|                                                            | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NullSense\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\auto_pipeline.py", line 311, in from_pretrained
    return text_2_image_cls.from_pretrained(pretrained_model_or_path, **kwargs)
  File "C:\Users\NullSense\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1069, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "C:\Users\NullSense\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 471, in load_sub_model
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "C:\Users\NullSense\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\modeling_utils.py", line 511, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "C:\Users\NullSense\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\configuration_utils.py", line 342, in load_config
    raise EnvironmentError(
OSError: Error no file named config.json found in directory D:\huggingface\hub\models--stabilityai--stable-diffusion-2-1\snapshots\5cae40e6a2745ae2b01ad92ae5043f95f23644d6.
```

### System Info

platform: Windows 11
python: 3.10.7
diffusers: 0.19.3

### Who can help?

@patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu

**Comment by patrickvonplaten** [comment]
Great catch @NullSenseStudio - I can confirm that this is indeed a bug! @yiyixuxu can you have a look here?
