### ISSUE TITLE
data_collator can't work in Trainer with LoRA Model

### ISSUE THREAD

**Issue by z379035389** [huggingface/diffusers#4730]
### Describe the bug

I defined a data_collator and used it in the Transformers Trainer and it worked. Due to de "CUDA out of memory", I choose LoRA to adapt my model. But then `features` in data_collator has nothing. I don't know why. 

### Reproduction

# this defines data_collator
@dataclass
class DataCollatorForMultipleChoice:
    """
    Data collator that will dynamically pad the inputs for multiple choice received.
    """

    tokenizer: PreTrainedTokenizerBase
    padding: Union[bool, str, PaddingStrategy] = True
    max_length: Optional[int] = None
    pad_to_multiple_of: Optional[int] = None

    def __call__(self, features):
        label_name = "label" if "label" in features[0].keys() else "labels"
        labels = [feature.pop(label_name) for feature in features] #len(labels) == 4
        batch_size = len(features)
        print(features[0])
        num_choices = len(features[0]["input_ids"])
        flattened_features = [
            [{k: v[i] for k, v in feature.items()} for i in range(num_choices)] for feature in features
        ]
        flattened_features = sum(flattened_features, [])
        # len(flattened_features) 64
        batch = self.tokenizer.pad(
            flattened_features,
            padding=self.padding,
            max_length=self.max_length,
            pad_to_multiple_of=self.pad_to_multiple_of,
            return_tensors="pt",
        )
        # for k, v in batch.items():
        #     print(k, v.shape)  # v.shape [64,74]

        batch = {k: v.view(batch_size, num_choices, -1) for k, v in batch.items()}
        
        # for k, v in batch.items():
        #     print(k, v.shape)  # v.shape [16,4,74]
        batch["labels"] = torch.tensor(labels, dtype=torch.int64)

        return batch

.......

# this shows how I use LoRA
from transformers import AutoModelForMultipleChoice, TrainingArguments, Trainer,AutoModelForCausalLM,AutoModel
from peft import LoraConfig, get_peft_model
from deepspeed.runtime.zero.stage_1_and_2 import estimate_zero2_model_states_mem_needs_all_live
def print_trainable_parameters(model):
    trainable_params = 0
    all_param = 0
    for _, param in model.named_parameters():
        all_param += param.numel()
        if param.requires_grad:
            trainable_params += param.numel()
    print(
        f"trainable params: {trainable_params} || all params: {all_param} || trainable%: {100 * trainable_params / all_param:.2f}"
    )
config = LoraConfig(
    r=8,
    lora_alpha=16,
    #"gate_proj","down_proj","up_proj" 
    target_modules=["q_proj","v_proj","MossPooler.dense","gate_proj","down_proj","up_proj"],
    lora_dropout=0.1,
    bias="lora_only",
    modules_to_save=["classifier","pooler","decode_head"]
)
model = AutoModelForMultipleChoice.from_pretrained(
    "/root/dataln/wuyan/moss-base-7b")
# model.resize_token_embeddings(len(tokenizer))
lora_model = get_peft_model(model,config)

.......

# this causes OOM
training_args = TrainingArguments(
    output_dir="my_awesome_swag_model",
    evaluation_strategy="steps",
    logging_strategy="steps",
    logging_steps=500,
    save_strategy="steps",
    save_steps=1500,
    load_best_model_at_end=True,
    learning_rate=1e-3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    save_total_limit=5,
    num_train_epochs=3,
    weight_decay=0.01,
    # deepspeed="/root/dataln/wuyan/deepspeed_config_zero3.json"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_swag["train"],
    eval_dataset=tokenized_swag["validation"].select(range(50)),
    tokenizer=tokenizer,
    data_collator=DataCollatorForMultipleChoice(tokenizer=tokenizer),
    compute_metrics=compute_metrics,
)

trainer.train()

# and this causes data_collator bug

training_args = TrainingArguments(
    output_dir="my_awesome_swag_model",
    evaluation_strategy="steps",
    logging_strategy="steps",
    logging_steps=500,
    save_strategy="steps",
    save_steps=1500,
    load_best_model_at_end=True,
    learning_rate=1e-3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    save_total_limit=5,
    num_train_epochs=3,
    weight_decay=0.01,
    # deepspeed="/root/dataln/wuyan/deepspeed_config_zero3.json"
)

trainer = Trainer(
    model=lora_model,
    args=training_args,
    train_dataset=tokenized_swag["train"],
    eval_dataset=tokenized_swag["validation"].select(range(50)),
    tokenizer=tokenizer,
    data_collator=DataCollatorForMultipleChoice(tokenizer=tokenizer),
    compute_metrics=compute_metrics,
)

trainer.train()

### System Info

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/root/dataln/wuyan/dataset_example.ipynb](https://vscode-remote+ssh-002dremote-002bv100.vscode-resource.vscode-cdn.net/root/dataln/wuyan/dataset_example.ipynb) 单元格 9 in ()
      [1](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0) training_args = TrainingArguments(
      [2](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=1)     output_dir="my_awesome_swag_model",
      [3](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2)     evaluation_strategy="steps",
   (...)
     [15](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=14)     # deepspeed="/root/dataln/wuyan/deepspeed_config_zero3.json"
     [16](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=15) )
     [18](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=17) trainer = Trainer(
     [19](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=18)     model=lora_model,
     [20](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=19)     args=training_args,
   (...)
     [25](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=24)     compute_metrics=compute_metrics,
     [26](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=25) )
---> [28](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=27) trainer.train()

File [~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/transformers/trainer.py:1539](https://vscode-remote+ssh-002dremote-002bv100.vscode-resource.vscode-cdn.net/root/dataln/wuyan/~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/transformers/trainer.py:1539), in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1534     self.model_wrapped = self.model
   1536 inner_training_loop = find_executable_batch_size(
   1537     self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size
   1538 )
-> 1539 return inner_training_loop(
   1540     args=args,
   1541     resume_from_checkpoint=resume_from_checkpoint,
   1542     trial=trial,
   1543     ignore_keys_for_eval=ignore_keys_for_eval,
   1544 )

File [~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/transformers/trainer.py:1787](https://vscode-remote+ssh-002dremote-002bv100.vscode-resource.vscode-cdn.net/root/dataln/wuyan/~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/transformers/trainer.py:1787), in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1784     rng_to_sync = True
   1786 step = -1
-> 1787 for step, inputs in enumerate(epoch_iterator):
   1788     total_batched_samples += 1
   1789     if rng_to_sync:

File [~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/accelerate/data_loader.py:384](https://vscode-remote+ssh-002dremote-002bv100.vscode-resource.vscode-cdn.net/root/dataln/wuyan/~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/accelerate/data_loader.py:384), in DataLoaderShard.__iter__(self)
    382 # We iterate one batch ahead to check when we are at the end
    383 try:
--> 384     current_batch = next(dataloader_iter)
    385 except StopIteration:
    386     yield

File [~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/torch/utils/data/dataloader.py:633](https://vscode-remote+ssh-002dremote-002bv100.vscode-resource.vscode-cdn.net/root/dataln/wuyan/~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/torch/utils/data/dataloader.py:633), in _BaseDataLoaderIter.__next__(self)
    630 if self._sampler_iter is None:
    631     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    632     self._reset()  # type: ignore[call-arg]
--> 633 data = self._next_data()
    634 self._num_yielded += 1
    635 if self._dataset_kind == _DatasetKind.Iterable and \
    636         self._IterableDataset_len_called is not None and \
    637         self._num_yielded > self._IterableDataset_len_called:

File [~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/torch/utils/data/dataloader.py:677](https://vscode-remote+ssh-002dremote-002bv100.vscode-resource.vscode-cdn.net/root/dataln/wuyan/~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/torch/utils/data/dataloader.py:677), in _SingleProcessDataLoaderIter._next_data(self)
    675 def _next_data(self):
    676     index = self._next_index()  # may raise StopIteration
--> 677     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    678     if self._pin_memory:
    679         data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)

File [~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py:54](https://vscode-remote+ssh-002dremote-002bv100.vscode-resource.vscode-cdn.net/root/dataln/wuyan/~/dataln/huier/envs/attack_llms/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py:54), in _MapDatasetFetcher.fetch(self, possibly_batched_index)
     52 else:
     53     data = self.dataset[possibly_batched_index]
---> 54 return self.collate_fn(data)

/root/dataln/wuyan/dataset_example.ipynb](https://vscode-remote+ssh-002dremote-002bv100.vscode-resource.vscode-cdn.net/root/dataln/wuyan/dataset_example.ipynb) 单元格 9 in DataCollatorForMultipleChoice.__call__(self, features)
     [21](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=20) batch_size = len(features)
     [22](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=21) print(features[0])
---> [23](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=22) num_choices = len(features[0]["input_ids"])
     [24](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=23) 
     [25](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=24) 
     [26](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=25) flattened_features = [
     [27](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=26)     [{k: v[i] for k, v in feature.items()} for i in range(num_choices)] for feature in features
     [28](vscode-notebook-cell://ssh-remote%2Bv100/root/dataln/wuyan/dataset_example.ipynb#X11sdnNjb2RlLXJlbW90ZQ%3D%3D?line=27) 

KeyError: 'input_ids'

### Who can help?

@williamberman @sayakpaul

**Comment by sayakpaul** [comment]
It should go to `peft`.
