### ISSUE TITLE
My prompt is more important in sd-webui-controlnet and diffusers

### ISSUE THREAD

**Issue by Laidawang** [huggingface/diffusers#4732]
in [sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet) we can choose My prompt is more important.
![image](https://github.com/huggingface/diffusers/assets/85244566/5542175f-0eaa-4993-96b0-a80a38cd160d)
in diffusers how can we get the same operation？
I checked the official website documentation, it seems that guessmode and "ControlNet is more important" are equivalent.

**Comment by Laidawang** [comment]
i've checked the source code of sd-webui-controlnet.
I think this will works.
![image](https://github.com/huggingface/diffusers/assets/85244566/b967677a-3ae6-416d-aa6a-695ab7a1c859)

**Comment by sayakpaul** [comment]
You can reduce `controlnet_guidance_scale` and increase `guidance_scale` while calling the pipeline.

**Comment by patrickvonplaten** [comment]
@Laidawang can you by any chance figure out what changes are needed exactly to in order to have this working in `diffusers`?

**Comment by alexblattner** [comment]
@sayakpaul @patrickvonplaten here's a little more guidance: https://github.com/Mikubill/sd-webui-controlnet#more-control-modes-previously-called-guess-mode
