### ISSUE TITLE
train_dreambooth_lora.py can not resume from checkpoint," No inf checks were recorded for this optimizer."

### ISSUE THREAD

**Issue by HollowKnight111** [huggingface/diffusers#4733]
### Describe the bug

i use diffusers==0.21.0 ,accelerate==0.22.0

when i running "accelerate launch train_dreambooth_lora.py   --pretrained_model_name_or_path="/home/gxh/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/aa9ba505e1973ae5cd05f5aedd345178f52f8e6a"    --instance_data_dir="/home/gxh/gxh_data/code/diffusers/examples/dreambooth/dog"   --output_dir="test"   --instance_prompt="a photo of sks dog"   --resolution=512   --train_batch_size=1   --gradient_accumulation_steps=1   --checkpointing_steps=100   --learning_rate=1e-4   --lr_scheduler="constant"   --lr_warmup_steps=0   --max_train_steps=200   --validation_prompt="A photo of sks dog in a bucket"   --validation_epochs=50   --seed="0" --resume_from_checkpoint="checkpoint-100"

it occurs " No inf checks were recorded for this optimizer."

### Reproduction

train_dreambooth_lora.py

### Logs

```shell
8/23/2023 15:17:13 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'clip_sample_range', 'timestep_spacing', 'thresholding', 'prediction_type', 'sample_max_value', 'variance_type', 'dynamic_thresholding_ratio'} was not found in config. Values will be initialized to default values.
{'force_upcast', 'scaling_factor'} was not found in config. Values will be initialized to default values.
{'encoder_hid_dim_type', 'time_embedding_act_fn', 'resnet_time_scale_shift', 'addition_time_embed_dim', 'conv_out_kernel', 'conv_in_kernel', 'dual_cross_attention', 'resnet_out_scale_factor', 'num_class_embeds', 'mid_block_type', 'addition_embed_type', 'time_embedding_type', 'mid_block_only_cross_attention', 'encoder_hid_dim', 'addition_embed_type_num_heads', 'time_cond_proj_dim', 'only_cross_attention', 'transformer_layers_per_block', 'upcast_attention', 'resnet_skip_time_act', 'class_embeddings_concat', 'cross_attention_norm', 'projection_class_embeddings_input_dim', 'use_linear_projection', 'timestep_post_act', 'attention_type', 'num_attention_heads', 'time_embedding_dim', 'class_embed_type'} was not found in config. Values will be initialized to default values.
08/23/2023 15:17:17 - INFO - __main__ - ***** Running training *****
08/23/2023 15:17:17 - INFO - __main__ -   Num examples = 5
08/23/2023 15:17:17 - INFO - __main__ -   Num batches each epoch = 5
08/23/2023 15:17:17 - INFO - __main__ -   Num Epochs = 40
08/23/2023 15:17:17 - INFO - __main__ -   Instantaneous batch size per device = 1
08/23/2023 15:17:17 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
08/23/2023 15:17:17 - INFO - __main__ -   Gradient Accumulation steps = 1
08/23/2023 15:17:17 - INFO - __main__ -   Total optimization steps = 200
Resuming from checkpoint checkpoint-100
08/23/2023 15:17:17 - INFO - accelerate.accelerator - Loading states from test/checkpoint-100
Loading unet.
08/23/2023 15:17:17 - INFO - accelerate.checkpointing - All model weights loaded successfully
08/23/2023 15:17:17 - INFO - accelerate.checkpointing - All optimizer states loaded successfully
08/23/2023 15:17:17 - INFO - accelerate.checkpointing - All scheduler states loaded successfully
08/23/2023 15:17:17 - INFO - accelerate.checkpointing - GradScaler state loaded successfully
08/23/2023 15:17:17 - INFO - accelerate.checkpointing - All random states loaded successfully
08/23/2023 15:17:17 - INFO - accelerate.accelerator - Loading in 0 custom states
Steps:   0%|                                                                                                                                          | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_dreambooth_lora.py", line 1426, in <module>
    main(args)
  File "train_dreambooth_lora.py", line 1219, in main
    optimizer.step()
  File "/home/gxh/anaconda3/envs/diff/lib/python3.8/site-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/gxh/anaconda3/envs/diff/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 372, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
Steps:   0%|                                                                                                                                          | 0/100 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/gxh/anaconda3/envs/diff/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/gxh/anaconda3/envs/diff/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/gxh/anaconda3/envs/diff/lib/python3.8/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/gxh/anaconda3/envs/diff/lib/python3.8/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/gxh/anaconda3/envs/diff/bin/python', 'train_dreambooth_lora.py', '--pretrained_model_name_or_path=/home/gxh/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/aa9ba505e1973ae5cd05f5aedd345178f52f8e6a', '--instance_data_dir=/home/gxh/gxh_data/code/diffusers/examples/dreambooth/dog', '--output_dir=ltqtest', '--instance_prompt=a photo of sks dog', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--checkpointing_steps=100', '--learning_rate=1e-4', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=200', '--validation_prompt=A photo of sks dog in a bucket', '--validation_epochs=50', '--seed=0', '--resume_from_checkpoint=checkpoint-100']' returned non-zero exit status 1.
```

### System Info

diffusers 0.21.0 
accelerate 0.22.0
ubuntu 20.0
python 3.8
torch 2.0.1

### Who can help?

@patrickvonplaten, @sayakpaul

**Comment by HollowKnight111** [comment]
this is the tree structure of  /test  directory ，where i store checkpoint
.
├── checkpoint-100
│   ├── optimizer.bin
│   ├── pytorch_lora_weights.safetensors
│   ├── random_states_0.pkl
│   ├── scaler.pt
│   └── scheduler.bin
├── logs
│   └── dreambooth-lora
│       ├── 1692773137.4828043
│       │   └── events.out.tfevents.1692773137.gxh-SYS-4029GP-TRTC-ZY001.3032328.1
│       ├── 1692773137.4857657
│       │   └── hparams.yml
│       ├── 1692773270.7491136
│       │   └── events.out.tfevents.1692773270.gxh-SYS-4029GP-TRTC-ZY001.3033032.1
│       ├── 1692773270.7520492
│       │   └── hparams.yml
│       ├── 1692773404.043574
│       │   └── events.out.tfevents.1692773404.gxh-SYS-4029GP-TRTC-ZY001.3033566.1
│       ├── 1692773404.0466995
│       │   └── hparams.yml
│       ├── 1692773538.8097754
│       │   └── events.out.tfevents.1692773538.gxh-SYS-4029GP-TRTC-ZY001.3034079.1
│       ├── 1692773538.8130376
│       │   └── hparams.yml
│       ├── 1692773737.5656817
│       │   └── events.out.tfevents.1692773737.gxh-SYS-4029GP-TRTC-ZY001.3034796.1
│       ├── 1692773737.5688643
│       │   └── hparams.yml
│       ├── 1692773814.7127948
│       │   └── events.out.tfevents.1692773814.gxh-SYS-4029GP-TRTC-ZY001.3035186.1
│       ├── 1692773814.715951
│       │   └── hparams.yml
│       ├── 1692774031.5167942
│       │   └── events.out.tfevents.1692774031.gxh-SYS-4029GP-TRTC-ZY001.3036150.1
│       ├── 1692774031.5197215
│       │   └── hparams.yml
│       ├── 1692774328.5853114
│       │   └── events.out.tfevents.1692774328.gxh-SYS-4029GP-TRTC-ZY001.3037101.1
│       ├── 1692774328.5884876
│       │   └── hparams.yml
│       ├── 1692775037.6693494
│       │   └── events.out.tfevents.1692775037.gxh-SYS-4029GP-TRTC-ZY001.3039601.1
│       ├── 1692775037.6722612
│       │   └── hparams.yml
│       ├── events.out.tfevents.1692773137.gxh-SYS-4029GP-TRTC-ZY001.3032328.0
│       ├── events.out.tfevents.1692773270.gxh-SYS-4029GP-TRTC-ZY001.3033032.0
│       ├── events.out.tfevents.1692773404.gxh-SYS-4029GP-TRTC-ZY001.3033566.0
│       ├── events.out.tfevents.1692773538.gxh-SYS-4029GP-TRTC-ZY001.3034079.0
│       ├── events.out.tfevents.1692773737.gxh-SYS-4029GP-TRTC-ZY001.3034796.0
│       ├── events.out.tfevents.1692773814.gxh-SYS-4029GP-TRTC-ZY001.3035186.0
│       ├── events.out.tfevents.1692774031.gxh-SYS-4029GP-TRTC-ZY001.3036150.0
│       ├── events.out.tfevents.1692774328.gxh-SYS-4029GP-TRTC-ZY001.3037101.0
│       └── events.out.tfevents.1692775037.gxh-SYS-4029GP-TRTC-ZY001.3039601.0
└── pytorch_lora_weights.safetensors

**Comment by sayakpaul** [comment]
Unable to reproduce:

https://colab.research.google.com/gist/sayakpaul/d891ad250f9fb218938178691fb0786f/scratchpad.ipynb

**Comment by HollowKnight111** [comment]
Thanks for your colab code. I have to choose gpu id in my training，so I have to set "accelerate config".Following a blog,I set  "Mixed precision type"to fp16 before. If I set it to “no” like your code，this error will not occur.




> Unable to reproduce:
> 
> https://colab.research.google.com/gist/sayakpaul/d891ad250f9fb218938178691fb0786f/scratchpad.ipynb

**Comment by sayakpaul** [comment]
That seems like an `accelerate` specific thing and not really related to `diffusers`.

**Comment by HollowKnight111** [comment]
Yes,thanks for your help!

> That seems like an `accelerate` specific thing and not really related to `diffusers`.

**Comment by garychan22** [comment]
By adding the following line in load_model_hook seems to resolve the problem

```
unet_new_state_dict = {}
    for p, v in lora_state_dict.items():
        if p.startswith("unet."):
            p = p.replace("unet.", "")
            unet_new_state_dict[p] = v
missings, unexpecteds = unet_.load_state_dict(unet_new_state_dict, strict=False)
```

**Comment by sayakpaul** [comment]
We have a fast test that actually tests the checkpointing behaviour of DreamBooth LoRA. 

https://github.com/huggingface/diffusers/blob/19f3161d94ed3678df2411fe423c833d3da30e1c/examples/test_examples.py#L1401

**Comment by garychan22** [comment]
@sayakpaul  thanks for the suggestion, the similar errror `AssertionError: No inf checks were recorded for this optimizer.` arises in the fast test due to unknown reason, the only solution I can refer to is 


> By adding the following line in load_model_hook seems to resolve the problem
> 
> ```
> unet_new_state_dict = {}
>     for p, v in lora_state_dict.items():
>         if p.startswith("unet."):
>             p = p.replace("unet.", "")
>             unet_new_state_dict[p] = v
> missings, unexpecteds = unet_.load_state_dict(unet_new_state_dict, strict=False)
> ```

**Comment by sayakpaul** [comment]
Could you try opening a PR for this and tag @williamberman to review it?
