### ISSUE TITLE
 Loading LoRA with 12 hidden layer TextEncoder and use clip_skip=2

### ISSUE THREAD

**Issue by EnzoWuu** [huggingface/diffusers#4735]
While attempting to load the LoRA model, I've encountered an issue when using the parameter clip_skip=2. 
The problem arises due to the textencoder component within the LoRA model containing parameters for 12 layers. If I load 
 pipline with config[num_hidden_layers=11], an error occurs when using load_lora_weights().

It would be great if we could dynamically adjust the num_hidden_layers after the pipeline has already been loaded. Alternatively, resolving this loading error issue would also be appreciated.

**Comment by sayakpaul** [comment]
We don't support CLIP skip.
