### ISSUE TITLE
Can I adapt existing UNet Blocks?

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#474]
**What API design would you like to have changed or added to the library? Why?**

In diffusers, we add Downsample2D  (for the non-final block), [see here](https://github.com/huggingface/diffusers/blob/8eaaa546d89f836b716e92348786d878f883ee86/src/diffusers/models/unet_2d.py#L114). This could be a conv layer or avg. pool layer. However, in guided-diffusion, it uses Res block for downsampling (controlled by [resblock_updown](https://github.com/openai/guided-diffusion/blob/22e0df8183507e13a7813f8d38d51b072ca1e67c/guided_diffusion/unet.py#L446)  argument). I could find SkipDownBlock2D kind similar, but I think it does not give what I need here.
Question: Should I create a new type of down block for guided diffusion?
Here are the links to the specific lines in the repos.
[Unet in guided-diffusion](https://github.com/openai/guided-diffusion/blob/22e0df8183507e13a7813f8d38d51b072ca1e67c/guided_diffusion/unet.py#L514)
[DownBlock2D in diffusers](https://github.com/huggingface/diffusers/blob/8eaaa546d89f836b716e92348786d878f883ee86/src/diffusers/models/unet_blocks.py#L588)

cc @patil-suraj @ydshieh

**Comment by patrickvonplaten** [comment]
In general, it's always safest to add a new block if the current block is logically different to what you need. Given that blocks are retrieved via "name-matching" e.g. you look up the block name in the config and according to the name you pick the correct block class from https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_blocks.py, it doesn't really hurt to add one more block class.

**Comment by ydshieh** [comment]
Thanks @patrickvonplaten.

To @patil-suraj (for a continuation on our Slack discussion)

> (ydshieh) Guided diffusion also has those Res Blocks, but the difference is it uses `ResBlock` for the place where we have `add_downsample`.

> (suraj) `resblock_updown` means up/down sampling layer with the `resblock`. That’s exactly what the `DownBlock2D` does. It `up/downsamples` with res block.

In `diffusers`, `DownBlock2D` have some `ResBlock`, then a `downsampling` layer (`Downsample2D`), which is conv layer or average pooling layer.

In `guided-diffusion`, the `resblock_updown` is used to specify what the `downsampling` layer should be. Before the downsampling, it already has the necessary Res blocks. However, if `resblock_updown` is `True`, it will create an extra `Resblock`, which is different from `Downsample2D` in diffusers.

You can see these lines in `guided-diffusions`:

#### Adding usual Resblocks
https://github.com/openai/guided-diffusion/blob/22e0df8183507e13a7813f8d38d51b072ca1e67c/guided_diffusion/unet.py#L490

#### Adding extra Resblocks
https://github.com/openai/guided-diffusion/blob/22e0df8183507e13a7813f8d38d51b072ca1e67c/guided_diffusion/unet.py#L518

**Comment by ydshieh** [comment]
Let me know if I missed some details and made the wrong claim above.

**Comment by patrickvonplaten** [comment]
This sounds reasonable to me @ydshieh :-) 
Should we see in a PR how it could look like - I think we can just add a new `unet_block` for this

**Comment by ydshieh** [comment]
I was thinking to add a new block type in my PR for [blended-diffusion](https://github.com/huggingface/diffusers/pull/362), which  is far from being ready.

My idea is to add something called `GuidedDiffusionDownBlock` in 

https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_blocks.py

and use `down_block_type == "GuidedDiffusionDownBlock"` in [get_down_block](https://github.com/huggingface/diffusers/blob/25a51b63ca75e1351069bee87a0fb3df5abb89c3/src/diffusers/models/unet_blocks.py#L24) to use it.

Does this sound good? If it is not clear, I can open a draft PR to demonstrate what I mean.

**Comment by patrickvonplaten** [comment]
Yes this sounds very nice!
