### ISSUE TITLE
Implementing inference from Custom Diffusion Checkpoints

### ISSUE THREAD

**Issue by aashish2000** [huggingface/diffusers#4742]
The section detailing inference steps from Custom Diffusion Checkpoints has been left as TODO in the official documentation. Is there an official timeline for this? Would it be possible to get a simple checkpoint inference script soon?

**Comment by patrickvonplaten** [comment]
Feel free to give it a try yourself if you'd like :-) No concrete timeline here

**Comment by aashish2000** [comment]
Sure, I can take this up. I was able to hack together a script for this, let me clean it up and share. Should I open up a Pull request with the updated documentation?

**Comment by aashish2000** [comment]
Hi @patrickvonplaten, I had implemented the inference from checkpoints for Custom Diffusion based on the resume_from_checkpoint functionality of `train_custom_diffusion.py`. My code was working on `diffusers==0.17.0.dev0` but the same code doesn't work on the current version of diffusers. The resume_from_checkpoint functionality is also broken on the current version of diffusers after the introduction of the --no_safe_serialization flag. 

The error I get when trying to load a checkpoint is:
`Error(s) in loading state_dict for AttnProcsLayers:
        Missing key(s) in state_dict: "layers.1.to_q_custom_diffusion.weight", "layers.1.to_out_custom_diffusion.0.weight", "layers.1.to_out_custom_diffusion.0.bias", "layers.3.to_q_custom_diffusion.weight", "layers.3.to_out_custom_diffusion.0.weight", "layers.3.to_out_custom_diffusion.0.bias", "layers.5.to_q_custom_diffusion.weight", "layers.5.to_out_custom_diffusion.0.weight", "layers.5.to_out_custom_diffusion.0.bias", "layers.7.to_q_custom_diffusion.weight", "layers.7.to_out_custom_diffusion.0.weight", "layers.7.to_out_custom_diffusion.0.bias", "layers.9.to_q_custom_diffusion.weight", "layers.9.to_out_custom_diffusion.0.weight", "layers.9.to_out_custom_diffusion.0.bias", "layers.11.to_q_custom_diffusion.weight", "layers.11.to_out_custom_diffusion.0.weight", "layers.11.to_out_custom_diffusion.0.bias", "layers.13.to_q_custom_diffusion.weight", "layers.13.to_out_custom_diffusion.0.weight", "layers.13.to_out_custom_diffusion.0.bias", "layers.15.to_q_custom_diffusion.weight", "layers.15.to_out_custom_diffusion.0.weight", "layers.15.to_out_custom_diffusion.0.bias", "layers.17.to_q_custom_diffusion.weight", "layers.17.to_out_custom_diffusion.0.weight", "layers.17.to_out_custom_diffusion.0.bias", "layers.19.to_q_custom_diffusion.weight", "layers.19.to_out_custom_diffusion.0.weight", "layers.19.to_out_custom_diffusion.0.bias", "layers.21.to_q_custom_diffusion.weight", "layers.21.to_out_custom_diffusion.0.weight", "layers.21.to_out_custom_diffusion.0.bias", "layers.23.to_q_custom_diffusion.weight", "layers.23.to_out_custom_diffusion.0.weight", "layers.23.to_out_custom_diffusion.0.bias", "layers.25.to_q_custom_diffusion.weight", "layers.25.to_out_custom_diffusion.0.weight", "layers.25.to_out_custom_diffusion.0.bias", "layers.27.to_q_custom_diffusion.weight", "layers.27.to_out_custom_diffusion.0.weight", "layers.27.to_out_custom_diffusion.0.bias", "layers.29.to_q_custom_diffusion.weight", "layers.29.to_out_custom_diffusion.0.weight", "layers.29.to_out_custom_diffusion.0.bias", "layers.31.to_q_custom_diffusion.weight", "layers.31.to_out_custom_diffusion.0.weight", "layers.31.to_out_custom_diffusion.0.bias".`

Where do I need to modify the checkpoint loading code to rectify this error?

**Comment by aniket004** [comment]
Hey.. are you able to implement that? Sharing would be helpful. Thanks!

**Comment by ChrisWang13** [comment]
> Hi @patrickvonplaten, I had implemented the inference from checkpoints for Custom Diffusion based on the `resume_from_checkpoint` functionality of `train_custom_diffusion.py`. My code was working on `diffusers==0.17.0.dev0` but the same code doesn't work on the current version of diffusers. The `resume_from_checkpoint` functionality is also broken on the current version of diffusers after the introduction of safe serialization of weights.
> 
> The error I get when trying to load a checkpoint is: `Error(s) in loading state_dict for AttnProcsLayers: Missing key(s) in state_dict: "layers.1.to_q_custom_diffusion.weight", "layers.1.to_out_custom_diffusion.0.weight", "layers.1.to_out_custom_diffusion.0.bias", "layers.3.to_q_custom_diffusion.weight", "layers.3.to_out_custom_diffusion.0.weight", "layers.3.to_out_custom_diffusion.0.bias", "layers.5.to_q_custom_diffusion.weight", "layers.5.to_out_custom_diffusion.0.weight", "layers.5.to_out_custom_diffusion.0.bias", "layers.7.to_q_custom_diffusion.weight", "layers.7.to_out_custom_diffusion.0.weight", "layers.7.to_out_custom_diffusion.0.bias", "layers.9.to_q_custom_diffusion.weight", "layers.9.to_out_custom_diffusion.0.weight", "layers.9.to_out_custom_diffusion.0.bias", "layers.11.to_q_custom_diffusion.weight", "layers.11.to_out_custom_diffusion.0.weight", "layers.11.to_out_custom_diffusion.0.bias", "layers.13.to_q_custom_diffusion.weight", "layers.13.to_out_custom_diffusion.0.weight", "layers.13.to_out_custom_diffusion.0.bias", "layers.15.to_q_custom_diffusion.weight", "layers.15.to_out_custom_diffusion.0.weight", "layers.15.to_out_custom_diffusion.0.bias", "layers.17.to_q_custom_diffusion.weight", "layers.17.to_out_custom_diffusion.0.weight", "layers.17.to_out_custom_diffusion.0.bias", "layers.19.to_q_custom_diffusion.weight", "layers.19.to_out_custom_diffusion.0.weight", "layers.19.to_out_custom_diffusion.0.bias", "layers.21.to_q_custom_diffusion.weight", "layers.21.to_out_custom_diffusion.0.weight", "layers.21.to_out_custom_diffusion.0.bias", "layers.23.to_q_custom_diffusion.weight", "layers.23.to_out_custom_diffusion.0.weight", "layers.23.to_out_custom_diffusion.0.bias", "layers.25.to_q_custom_diffusion.weight", "layers.25.to_out_custom_diffusion.0.weight", "layers.25.to_out_custom_diffusion.0.bias", "layers.27.to_q_custom_diffusion.weight", "layers.27.to_out_custom_diffusion.0.weight", "layers.27.to_out_custom_diffusion.0.bias", "layers.29.to_q_custom_diffusion.weight", "layers.29.to_out_custom_diffusion.0.weight", "layers.29.to_out_custom_diffusion.0.bias", "layers.31.to_q_custom_diffusion.weight", "layers.31.to_out_custom_diffusion.0.weight", "layers.31.to_out_custom_diffusion.0.bias".`
> 
> Where do I need to modify the checkpoint loading code to rectify this error?

Try `pipe.unet.load_attn_procs(model_path, subfolder="checkpoint-1000", weight_name="model.bin")`
