### ISSUE TITLE
Inpaint + Lama Preprocessor

### ISSUE THREAD

**Issue by 0sparsh2** [huggingface/diffusers#4750]
### Model/Pipeline/Scheduler description

Automatic1111 supports preprocessor of Inpaint+Lama for the Inpaint ControlNet model over web ui. 
Is there a way to add the same functionality for Diffusers pipeline? 
I wish to perform outpainting like how it's mentioned here (https://github.com/Mikubill/sd-webui-controlnet/discussions/1597)

### Open source status

- [] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/Mikubill/sd-webui-controlnet/discussions/1597

**Comment by kelisiya** [comment]
Inpainting in webui uses text2img, while controlnet_inpainting in diffusers retains the strength of img2img. I have done some experiments and the results of the two frameworks cannot be aligned yet.

**Comment by kelisiya** [comment]
+1

**Comment by 0sparsh2** [comment]
> results

But it's just about the preprocessor right? Since purely inpainting with diffusers in text2image is still possible here (passing a 512×512 image and having a 768×512) as output

**Comment by kelisiya** [comment]
> > results
> 
> But it's just about the preprocessor right? Since purely inpainting with diffusers in text2image is still possible here (passing a 512×512 image and having a 768×512) as output

I'm still exploring the webui code, but I think the implementation of controlnet inpainting is different, so even with the same preprocessing, I can't get consistent results.

**Comment by kelisiya** [comment]
> > results
> 
> But it's just about the preprocessor right? Since purely inpainting with diffusers in text2image is still possible here (passing a 512×512 image and having a 768×512) as output

lama image as a condition to Controlnet

**Comment by 0sparsh2** [comment]
Got it! I have been trying to go through the webui code too to implement, they have added ControlNet Lama annotator in the GitHub, will update here in case I am able to make it work
Thanks

**Comment by JohanHuynh0130** [comment]
hi! Is there any updates to this? I'm really looking forward on a way to implement

**Comment by kelisiya** [comment]
> hi! Is there any updates to this? I'm really looking forward on a way to implement

I found the code for encoding the mask area in autopipeline for inpainting. In fact, lama-like operations have been implemented in sdxl-inpainting. All you need to do is to use lama for inpainting first, and then send the result and mask to sdxl inpainting. in the model. You can find this through hugging demo. When you paint the periphery of the image, it still recovers very well～

https://huggingface.co/spaces/diffusers/stable-diffusion-xl-inpainting

**Comment by wuyanzhang** [comment]
> > hi! Is there any updates to this? I'm really looking forward on a way to implement
> 
> I found the code for encoding the mask area in autopipeline for inpainting. In fact, lama-like operations have been implemented in sdxl-inpainting. All you need to do is to use lama for inpainting first, and then send the result and mask to sdxl inpainting. in the model. You can find this through hugging demo. When you paint the periphery of the image, it still recovers very well～
> 
> https://huggingface.co/spaces/diffusers/stable-diffusion-xl-inpainting

Hello, Could you provide a complete pipeline for reference? Thank you！

**Comment by ajkrish95** [comment]
@kelisiya I don't think I follow your response. The original query was regarding outpainting and using the inpaint+lama preprocessor Automatic provides. Can you explain in more detail how running through lama and then sending to SDXL Inpainting solves the problem.

**Comment by mlinmg** [comment]
I'm trying to implement it in the ComfyUI, but in the final part where I pass the image as a control it mess up the generated image
