### ISSUE TITLE
Something wrong with train_dreambooth_lora.py

### ISSUE THREAD

**Issue by HollowKnight111** [huggingface/diffusers#4753]
### Describe the bug

I think it should be
```python
        if args.class_prompt is not None:
            pre_computed_class_prompt_encoder_hidden_states = compute_text_embeddings(args.class_prompt)
        else:
            pre_computed_class_prompt_encoder_hidden_states = None
``` 
rather than
https://github.com/huggingface/diffusers/blob/24c5e7708bb75076dd8e79ccaea195640555f945/examples/dreambooth/train_dreambooth_lora.py#L1001-L1004

### Reproduction

accelerate launch train_dreambooth.py  ...

### System Info

- `Accelerate` version: 0.22.0
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.10
- Python version: 3.8.0
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 125.55 GB
- GPU type: NVIDIA GeForce RTX 3090
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: 6
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []

### Who can help?

 @williamberman, @sayakpaul, @yiyixuxu

**Comment by yuananf** [comment]
Seems introduced in https://github.com/huggingface/diffusers/pull/4395

**Comment by sayakpaul** [comment]
Cc: @williamberman

**Comment by williamberman** [comment]
thanks!
