### ISSUE TITLE
OSError: Error no file named model_index.json found in directory after load fine tuned textual inversion

### ISSUE THREAD

**Issue by Adorablepet** [huggingface/diffusers#4754]
I train the textual inversion fine tuning cat toy example from [here](https://github.com/huggingface/diffusers/tree/main/examples/textual_inversion)

And python raises error when inference 

`Traceback (most recent call last):
  File "infer.py", line 6, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
  File "/opt/conda/envs/diffusers/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 952, in from_pretrained
    config_dict = cls.load_config(cached_folder)
  File "/opt/conda/envs/diffusers/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 364, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory /workspace/diffusers/examples/textual_inversion/textual_inversion_cat.
`
Run this script to fine tune the cat dataset

`python -u textual_inversion.py --pretrained_model_name_or_path=$MODEL_NAME --train_data_dir=$DATA_DIR --learnable_property="object" --placeholder_token="<cat-toy>" --initializer_token="toy" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=4 --max_train_steps=3000 --learning_rate=5.0e-04 --scale_lr --lr_scheduler="constant" --lr_warmup_steps=0 --output_dir="textual_inversion_cat"`

Then run inference code to appear error

`from diffusers import StableDiffusionPipeline
import torch

model_id = "/workspace/diffusers/examples/textual_inversion/textual_inversion_cat"

pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")

prompt = "A <cat-toy> backpack"

image = pipe(prompt, num_inference_steps=50, guidance_scale=7.5).images[0]

image.save("cat-backpack.png")`

textual_inversion_cat dir, as follow:

![image](https://github.com/huggingface/diffusers/assets/29625016/eb9e6dde-b153-4b8f-8b0e-416a82cd7235)
![image](https://github.com/huggingface/diffusers/assets/29625016/ea9c202f-941e-4b94-a037-b5bcfa015756)

could you help me ,thanks.

**Comment by Adorablepet** [comment]
@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Can you please post a reproducible code snippet?

**Comment by Adorablepet** [comment]
> Can you please post a reproducible code snippet?


diffusers: 0.20.0



`from diffusers import StableDiffusionPipeline
import torch

model_id = "/workspace/diffusers/examples/textual_inversion/textual_inversion_cat"

pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")

prompt = "A backpack"

image = pipe(prompt, num_inference_steps=50, guidance_scale=7.5).images[0]

image.save("cat-backpack.png")`

**Comment by patrickvonplaten** [comment]
Hey @Adorablepet,

Thanks for the reproducible code snippet. Note that textual inversion weights need to be loaded in combination with a base model. So in your case, it should be:

```py
from diffusers import StableDiffusionPipeline
import torch

text_inv_id = "/workspace/diffusers/examples/textual_inversion/textual_inversion_cat"

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to("cuda")
pipe.load_textual_inversion(text_inv_id)

prompt = "A backpack"

image = pipe(prompt, num_inference_steps=50, guidance_scale=7.5).images[0]

image.save("cat-backpack.png")
```

**Comment by Adorablepet** [comment]
@patrickvonplaten thanks. This is very useful.

**Comment by aishu194** [comment]
Hello I have faced the similar error and I am using amused. 

`import torch
from diffusers import AmusedPipeline
from pathlib import Path
import re
import slugify

DIR_NAME="./images/"
dirpath = Path(DIR_NAME)
# create parent dir if doesn't exist
dirpath.mkdir(parents=True, exist_ok=True)

# pipe = AmusedPipeline.from_pretrained(
#     "amused/amused-512", variant="fp16", torch_dtype=torch.float16
# )

pipe = AmusedPipeline.from_pretrained(
    "diffusers/examples/amused/amused_finetune/checkpoint-5/", variant="fp16", torch_dtype=torch.float16
)
pipe = pipe.to("cuda")

prompt = "yellow and red background poster for product promotion"
negative_prompt = "low quality, ugly"
num_images_per_prompt = 4
output = pipe(prompt, negative_prompt=negative_prompt, num_images_per_prompt=num_images_per_prompt, generator=torch.manual_seed(100))

for idx, image in enumerate(output.images):
    print(image)
    image_name = prompt+'-'+str(idx)+'.jpg'
    image_path = dirpath / image_name
    image.save(image_path)`


could you kindly help me with this please! Thanks in advance

**Comment by mauricio-repetto** [comment]
@patrickvonplaten hi! how are you? I was facing the same issue but because I was following the instruction from the script at https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/README.md when doing the inference piece, it does not mention to load the base model and then load the weights but just load the model directly from the output folder, is it that the documentation is outdated?

![image](https://github.com/huggingface/diffusers/assets/11300196/79483840-35eb-44ed-8109-c0c90b094231)

Thank you!

**Comment by rs545837** [comment]
It's easy, you just need to load the base pipeline first and then load the trained unet over it. 

from diffusers import StableDiffusionPipeline, UNet2DConditionModel, DDIMScheduler
import torch

checkpoint_path = "sd-kanji/checkpoint-3000"

# Load the base pipeline first
pipeline = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    torch_dtype=torch.float16
)

# Load the trained UNet
unet = UNet2DConditionModel.from_pretrained(
    f"{checkpoint_path}/unet",
    torch_dtype=torch.float16
)

# Update the pipeline with trained UNet
pipeline.unet = unet

# Move to GPU
pipeline = pipeline.to("cuda")

# Generate an image
prompt = "chinese"
image = pipeline(
    prompt=prompt,
    num_inference_steps=50,
    guidance_scale=7.5
).images[0]

# Save the generated image
image.save("generated_kanji.png")
