### ISSUE TITLE
Support for training style with examples/dreambooth/train_dreambooth_lora_sdxl.py

### ISSUE THREAD

**Issue by OranHe** [huggingface/diffusers#4756]
**Is your feature request related to a problem? Please describe.**
I'm trying to use _examples/dreambooth/train_dreambooth_lora_sdxl.py_ to train an original style dreambooth SDXL model. If I'm right, this script only support train object for now.

**Describe the solution you'd like**
Support for training style with examples/dreambooth/train_dreambooth_lora_sdxl.py

**Describe alternatives you've considered**

it will be better if train_dreambooth_lora_sdxl.py support args **train_data_dir and caption_column** just like train_text_to_image_lora_sdxl.py

`accelerate launch train_text_to_image_lora_sdxl.py  \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0"  \
  --train_data_dir=$DATA_DIR --caption_column="text"  \
  --resolution=1024 --random_flip  \
  --train_batch_size=1 --num_train_epochs=1000 --checkpointing_steps=200  \
  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0  \
  --output_dir="sdxl-lora"`

**Comment by Xargonus** [comment]
Hi, I don't have experience with training styles using DreamBooth, but aren't the options **instance_data_dir** and **instance_prompt** equivalent to the **train_data_dir** and **caption_column** that you mention?

**Comment by mspilimbergo** [comment]
@OranHe were you able to figure out how to train a model with an original style? Any suggestion would be appreciated! I am trying to train a lora with dragon ball z styles. 


Thanks!
