### ISSUE TITLE
Support saving multiple t2i adapter models under one checkpoint

### ISSUE THREAD

**Issue by williamberman** [huggingface/diffusers#4768]
Similarly to how we support serializing multiple controlnet checkpoints under one combined controlnet checkpoint. We should be able to support multiple t2i adapter checkpoints under one combined t2i adapter checkpoint

see some discussion here: https://github.com/huggingface/diffusers/pull/4621/files#r1295338783

**Comment by VitjanZ** [comment]
I'd like to try this.
