### ISSUE TITLE
Memory issue on colab free for SDXL + Clip-vit-G + Xformers + accelerate

### ISSUE THREAD

**Issue by putuoka** [huggingface/diffusers#4772]
Reproduction code demo https://colab.research.google.com/drive/15CsxWNpALN-gnQJO4ad2pQy0CMotf58h

error message:

Your session crashed after using all available RAM. If you are interested in access to high-RAM runtimes, you may want to check out Colab Pro.

Is there a solution for this that would work within the colab free?

**Comment by patrickvonplaten** [comment]
Hey @putuoka,

Could you please try to use the forum or discord for such questions:
- forum: https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63
- discord: https://discord.gg/G7tWnz98XR

**Comment by putuoka** [comment]
solved by myself with restart runtime. thanks
