### ISSUE TITLE
Loading CivitAI Lora

### ISSUE THREAD

**Issue by MaxTran96** [huggingface/diffusers#4773]
### Describe the bug

According to https://github.com/huggingface/diffusers/releases/tag/v0.19.2, i can load Lora by
```
pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16)
pipe.load_lora_weights("stabilityai/stable-diffusion-xl-base-1.0", weight_name="sd_xl_offset_example-lora_1.0.safetensors")
pipe.to("cuda")
```
but in https://github.com/huggingface/diffusers/pull/4287
you wrote 
```
from diffusers import DiffusionPipeline
import torch
pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16)
pipe.load_lora_weights("./sd_xl_offset_example-lora_1.0.safetensors")
```

Are  these identical?
```
pipe.load_lora_weights("stabilityai/stable-diffusion-xl-base-1.0", weight_name="sd_xl_offset_example-lora_1.0.safetensors")
pipe.to("cuda")
```
and 
```
pipe.load_lora_weights("./sd_xl_offset_example-lora_1.0.safetensors")
```

Does that mean i can also load any civitai lora model? Do i need to download and put this in local path? Can i reference it by url and load it from there similar to huggingface model_id? How do you suggest i should load lora weight from civitai? i.e https://civitai.com/models/112902/dreamshaper-xl10

@patrickvonplaten 

### Reproduction

N/A

### System Info

ec2

**Comment by MaxTran96** [comment]
can you give me an example of how i would them into the pipeline? Those civitai LoRas don't have "hub_id" as far as i know. I might be wrong

**Comment by alexblattner** [comment]
@MaxTran96 for the first option, you would have to download the lora on your computer and for the second one you should upload it to huggingface. I would recommend the first option because the lora will be downloaded to your computer regardless, the process is less time consuming and if you have no internet connect you'll be able to use it

**Comment by jndietz** [comment]
Is this really a bug?  I'm able to load kohya-trained SDXL LoRAs into diffusers without any issues.

```python
lora = "c:\path\to\some-lora.safetensors"
pipe.load_lora_weights(lora)
```

**Comment by MaxTran96** [comment]
i figured out why, i was loading the full checkpoint civitAI model DreamShaper into .load_lora_weight() and i dont think its how its supposed to be right? We can close this issue :D
