### ISSUE TITLE
ModelScope Image to VIdeo Pipeline

### ISSUE THREAD

**Issue by junhaozhang98** [huggingface/diffusers#4779]
### Model/Pipeline/Scheduler description

ModelScope Image to VIdeo Pipeline.

Open sourced and checkpoints are available on huggingface. It is similar to  modelscope text to video pipeline.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://huggingface.co/damo-vilab/MS-Image2Video

**Comment by patrickvonplaten** [comment]
Do we have any idea about how good/powerful the model is?

**Comment by junhaozhang98** [comment]
Yes. You can refere below two links.

https://modelscope.cn/models/damo/Image-to-Video/summary

https://modelscope.cn/studios/damo/I2VGen-XL-Demo/summary

**Comment by sayakpaul** [comment]
We support it https://huggingface.co/docs/diffusers/v0.27.0/en/api/pipelines/i2vgenxl
