### ISSUE TITLE
Innequality typo in euler discrete scheduler

### ISSUE THREAD

**Issue by williamberman** [huggingface/diffusers#4785]
### Describe the bug

I think this is a typo for multiple innequalities. I'd just propose a code change but I'm not familiar with the math for if it is really supposed to be just a < b and b < c

https://github.com/huggingface/diffusers/blob/2764db3194fc1b5069df7292fd938657d8568995/src/diffusers/schedulers/scheduling_euler_discrete.py#L396

This bit specifically 
```
s_tmin <= sigma <= s_tmax
```

**Comment by patrickvonplaten** [comment]
The `gamma` parameter is actually incorrectly computed, we should probably just delete it

**Comment by williamberman** [comment]
yeah no issues with removing the gamma as well
