### ISSUE TITLE
Cannot download DeepFloyd IF

### ISSUE THREAD

**Issue by thuanz123** [huggingface/diffusers#4789]
### Describe the bug

I, as well as some of my friends, cannot download the DeepFloyd IF models anymore

### Reproduction

from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("DeepFloyd/IF-I-XL-v1.0")

### System Info

- `diffusers` version: 0.21.0.dev0
- Platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.31
- Python version: 3.11.3
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.30.2
- Accelerate version: 0.22.0.dev0
- xFormers version: 0.0.20
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by patrickvonplaten** [comment]
Hey @thuanz123,

I don't have a problem downloading the model can you do the following:

1. First make sure you have accepted the gated license:
2. Make sure you're loggind in:
```py
from huggingface_hub import login
login()
```
3. Run:
```py
from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("DeepFloyd/IF-I-XL-v1.0")
```

**Comment by patrickvonplaten** [comment]
If this doesn't work for you, can you please share your error message?

**Comment by thuanz123** [comment]
hi @patrickvonplaten, the download is normal at first but then shut down in the middle. Below is the error log
![image](https://github.com/huggingface/diffusers/assets/32274287/0ab162a3-4677-44c2-a8ab-b970b84b129b)

**Comment by patrickvonplaten** [comment]
This looks like a bug with the `huggingface_hub` . Gently pinging @Wauplin here in case you have any idea :sweat_smile:

**Comment by Wauplin** [comment]
Can it be that you don't have enough free space on your disk?

**Comment by thuanz123** [comment]
There are still 2TB left so storage can't be the problem
