### ISSUE TITLE
Docs has a spelling errors in 0.19.3

### ISSUE THREAD

**Issue by icarried** [huggingface/diffusers#4792]
![image](https://github.com/huggingface/diffusers/assets/54706854/5dec68b0-a950-4d9c-b422-852960d51b38)

**Comment by icarried** [comment]
https://huggingface.co/docs/diffusers/v0.19.3/en/api/pipelines/auto_pipeline
it should be "PipelineForImageToImage", not "PipelineForImageoImage"

**Comment by patrickvonplaten** [comment]
Nice catch! Wanna open a PR to fix it? :-)

**Comment by icarried** [comment]
> Nice catch! Wanna open a PR to fix it? :-)

Yes,  I wanna open a PR to fix it!

**Comment by patrickvonplaten** [comment]
Nice job!
