### ISSUE TITLE
Error : could not open requirements file 

### ISSUE THREAD

**Issue by hussainafroz** [huggingface/diffusers#4803]
![image](https://github.com/huggingface/diffusers/assets/83532496/0bc404a1-57ac-4779-b4d2-135d5b5843f9)

**Comment by patrickvonplaten** [comment]
Note that you can find the `requirements.txt` files inside the folders of `examples`. 

Can you do:

```
cd examples/dreambooth && pip install -r requirements.txt
```

?

**Comment by hussainafroz** [comment]
its working patrick. thanks for your help

**Comment by hussainafroz** [comment]
done
