### ISSUE TITLE
Failing Integration Test on SHAP-E Img2Img Pipeline

### ISSUE THREAD

**Issue by DN6** [huggingface/diffusers#4808]
### Describe the bug

The following test:
https://github.com/huggingface/diffusers/blob/766aa50f70120ab8c08c221fb95c68661422fef0/tests/pipelines/shap_e/test_shap_e_img2img.py#L256

Fails to generate the appropriate image from the SHAP-E Pipeline. Looking at the generated and expected images, it looks like the generated images are inverted. (255's being produced instead of 0's).

generated output array:
```
image = array([[[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., ...55.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]]], dtype=float32)
expected_image = array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., ...,
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)
expected_max_diff = 10

    def assert_mean_pixel_difference(image, expected_image, expected_max_diff=10):
        image = np.asarray(DiffusionPipeline.numpy_to_pil(image)[0], dtype=np.float32)
        expected_image = np.asarray(DiffusionPipeline.numpy_to_pil(expected_image)[0], dtype=np.float32)
        avg_diff = np.abs(image - expected_image).mean()
>       assert avg_diff < expected_max_diff, f"Error image deviates {avg_diff} pixels on average"
E       AssertionError: Error image deviates 236.1259002685547 pixels on average
E       assert 236.1259 < 10
```
### Reproduction

Run the following slow test for SHAP-E Pipeline
https://github.com/huggingface/diffusers/blob/766aa50f70120ab8c08c221fb95c68661422fef0/tests/pipelines/shap_e/test_shap_e_img2img.py#L256

### System Info

- `diffusers` version: 0.21.0.dev0
- Platform: Linux-5.10.0-23-cloud-amd64-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: 0.0.20
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by DN6** [comment]
@yiyixuxu. It looks like you added this test. Would you be able to investigate into why it is failing?

**Comment by yiyixuxu** [comment]
ohh I think we changed the default background from black to white and did not update the test!
will update
