### ISSUE TITLE
StableDiffusionControlNetImg2ImgPipeline

### ISSUE THREAD

**Issue by wanglaofei** [huggingface/diffusers#4813]
how to train a StableDiffusionControlNetImg2ImgPipeline? The official code  works for text2img controlnet, but there is no img2img controlnet training code, I don't know where to find the relevant training code.

**Comment by patrickvonplaten** [comment]
img2img training code doesn't exist as img2img pretty much always uses the exact same checkpoints as text-to-image => So if your model has strong text-to-image capabilities it'll also be good at image-to-image
