### ISSUE TITLE
Allow image resizing also for torch and numpy inputs

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#4816]
At the moment we only allow to resize images if they are in the PIL format, see here: https://github.com/huggingface/diffusers/blob/e3f3672f46877c18aa4088d852988b35fc4d1e1b/src/diffusers/image_processor.py#L277

I think it's time to allow also such tensors to be resized. In PyTorch this is quite simple by using: https://pytorch.org/docs/stable/generated/torch.nn.functional.interpolate.html#torch.nn.functional.interpolate similar to how we do it here: https://github.com/huggingface/diffusers/blob/e3f3672f46877c18aa4088d852988b35fc4d1e1b/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py#L641

For the numpy case, I would actually convert the tensor to pytorch first and then use the same function as above and go back to numpy again.

@yiyixuxu could you maybe take a look at this?

**Comment by gajendr-nikhil** [comment]
@patrickvonplaten can I take this up ?

**Comment by yiyixuxu** [comment]
@gajendr-nikhil 

sure! That'd be lovely  
Let me know if you have any questions. Note that we want this feature soon so if you lose availability please let us know:)

**Comment by gajendr-nikhil** [comment]
@yiyixuxu  My plan is to open a PR for this on/before 8/30
Let me know if that's good

**Comment by yiyixuxu** [comment]
@gajendr-nikhil 
great, look forward to that!

**Comment by patrickvonplaten** [comment]
Cool!

**Comment by gajendr-nikhil** [comment]
@patrickvonplaten @yiyixuxu Created a PR https://github.com/huggingface/diffusers/pull/4832
