### ISSUE TITLE
Kandinsky2_2 call ignores latents

### ISSUE THREAD

**Issue by thoppe** [huggingface/diffusers#4818]
The latest Kandinsky2_2 version in diffusers `0.20.1` completely ignores the input noise latents. Here are one of the offending lines:

https://github.com/huggingface/diffusers/blob/5eeedd9e3336882d598091e191559f67433b6427/src/diffusers/pipelines/kandinsky2_2/pipeline_kandinsky2_2_prior_emb2emb.py#L532C4-L532C4

Which references the code `latents = image_embeds`. No matter what you put in for `latents` when you call any of the functions it is completely overwritten. I'm assuming this isn't the case based off the docs:

```
latents (`torch.FloatTensor`, *optional*):
     Pre-generated noisy latents, sampled from a Gaussian distribution, to be used as inputs for image
     generation. Can be used to tweak the same generation with different prompts. If not provided, a latents
     tensor will ge generated by sampling using the supplied random `generator`.
```

**Comment by patrickvonplaten** [comment]
Ah yeah good point - @yiyixuxu could you take a look when you have some time? :-)

**Comment by yiyixuxu** [comment]
@patrickvonplaten 
I think maybe we just remove this argument and update the docstring? 
The img2img pipeline in both sd and sd-xl don't support this argument

**Comment by thoppe** [comment]
I was able to get it to work (it didn't seem that hard?), but I'm not sure I understand the code base well enough that I trust my PR without someone looking it over. I don't want to do it if you're going to dump the feature though.

**Comment by yiyixuxu** [comment]
@thoppe 
I will wait for @patrickvonplaten feedback here
I'm pretty sure it was copied from a text2imge pipeline and never intended to be an actual feature here. If we are going to add this feature, we should add it to all img2img pipelines.

**Comment by thoppe** [comment]
@yiyixuxu makes sense! 

I was trying to have a little bit more control over noise manipulation through latent interpolations, so there might be a use case for it in general for img2img pipelines.

**Comment by patrickvonplaten** [comment]
Yes, I'm with @yiyixuxu here, I don't really see how `latents` makes sense in the prior_emb2emb context => let's remove it?
