### ISSUE TITLE
Some methods mix the usage of numpy and torch

### ISSUE THREAD

**Issue by ydshieh** [huggingface/diffusers#482]
### Describe the bug

Here are what I find in `resnet.py` (not checking other files at this moment).

Goal: replace this with pure torch methods

- [FirUpsample2D._upsample_2d](https://github.com/huggingface/diffusers/blob/f4781a0b27ffb3ea61ecd25b0b87305e0960304e/src/diffusers/models/resnet.py#L137)
- [FirDownsample2D. _downsample_2d](https://github.com/huggingface/diffusers/blob/f4781a0b27ffb3ea61ecd25b0b87305e0960304e/src/diffusers/models/resnet.py#L222)
- [upsample_2d](https://github.com/huggingface/diffusers/blob/f4781a0b27ffb3ea61ecd25b0b87305e0960304e/src/diffusers/models/resnet.py#L394)
- [downsample_2d](https://github.com/huggingface/diffusers/blob/f4781a0b27ffb3ea61ecd25b0b87305e0960304e/src/diffusers/models/resnet.py#L428)

**Comment by patrickvonplaten** [comment]
Thanks a lot for opening this, we should indeed make those pure PyTorch functions
