### ISSUE TITLE
SDXL trainig loss nan,validate generage black image

### ISSUE THREAD

**Issue by zdxpan** [huggingface/diffusers#4820]
tranning met loss is nan, and the pred_noise cntain nan, which will case the tranning fail， the traing target is predict noise with given noise, which mse alwas nearby 1 (~= 1), 
possible reason 
1、 lr too large  
2、 data had some nan value

i try to continue after find the loss and noise_pred be nan
is there anty other reason? and good solution?

and met the log_validate validate image alwas balck

**Comment by patrickvonplaten** [comment]
Can you try to use the forum for such questions: https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63 ?
