### ISSUE TITLE
RubberDiffusers. Diffusers but far more flexible!

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#4823]
### Model/Pipeline/Scheduler description

Every month a new feature comes out and it only works for txt2img or img2img. Why? Because diffusers requires a new pipeline for every single variation. Also, those variations are not very different from one another. So, I made RubberDiffusers! It works just like diffusers, but all you need to enable a feature is to apply a function on it that will add the small piece of code that does what you want!

Examples:
1. Prompt fusion with MultiControlnet:
controlnet1 = ControlNetModel.from_pretrained("lllyasviel/control_v11p_sd15_openpose", torch_dtype=torch.float32,local_files_only=True).to('cuda')
controlnet2 = ControlNetModel.from_pretrained("lllyasviel/control_v11p_sd15_canny", torch_dtype=torch.float32,local_files_only=True).to('cuda')
pipe=StableDiffusionRubberPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", torch_dtype=torch.float32,safety_checker=None, requires_safety_checker=False,
).to("cuda")
pipe=apply_controlnet(pipe)
pipe=apply_promptFusion(pipe)

pipe.add_controlnet(controlnet1)
pipe.add_controlnet(controlnet2)

img1= load your image
img2= load your image
image=pipe(
    [["woman dancing on the beach",10],["woman dancing on the floor",20]],
    prompt_embeds=None,
    num_inference_steps=20,
    generator=generator,
    # callback=printer,
    controlnet_conditioning_scale=[0.5,0.5],
    controlnet_image=[image1,image2],
).images[0]

2. SAG with inpainting:
pipe=StableDiffusionRubberPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", torch_dtype=torch.float32,safety_checker=None, requires_safety_checker=False,
).to("cuda")
pipe=apply_SAG(pipe)
pipe=apply_inpainting(pipe)
prompt="a dog sitting on a bench"
mask=load your mask
input_image=load the image that you want to apply the mask to
image=pipe(
    prompt,
    prompt_embeds=None,
    num_inference_steps=20,
    generator=generator,
    mask_image=mask,
    image=image,
    strength=0.75,
    sag_scale=0.75,
).images[0]

You can make whatever combination you want, but in the end, Stable Diffusion has its own logic.

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/alexblattner/RubberDiffusers

I did this

**Comment by knoopx** [comment]
Diffusers really needs a pipeline refactor, there's too many dupe code and is hard to extend. I wish they addressed these issues here.

**Comment by alexblattner** [comment]
@knoopx, you're welcome to use my repo for now. It automatically updates because it just extends the regular txt2img pipeline. Sadly, they refuse to do this for reproducibility reasons (their words not mine) which my implementation solves easily, but they have a lot they are behind on so I doubt they'll do anything about that even though it would save them a lot of time in the long run
