### ISSUE TITLE
ControlNet Reference with MultiControlNet gives errors

### ISSUE THREAD

**Issue by 0sparsh2** [huggingface/diffusers#4826]
### Describe the bug

I want to use Stable Diffusion ControlNet reference pipeline but I am coming across 2 issues
1) Bug - When executing the below code, I receive an error
```ValueError: `control_guidance_start`: [0.0] has 1 elements but there are 2 controlnets available. Make sure to provide 2.```
I believe the pipeline isn't calling pipeline_controlnet from diffusers correctly
2) Ability to define control_guidance_start and control_guidance_end values, currently the params only support control weight

https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_controlnet_reference.py

### Reproduction

import cv2
import diffusers
import torch
import numpy as np
from PIL import Image
from diffusers import ControlNetModel
from diffusers import DPMSolverMultistepScheduler, DiffusionPipeline
from diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_controlnet import MultiControlNetModel

input_image = Image.open("/content/segmented_object.png") 
mask_image = Image.open("/content/object_mask.png")
ref_image = Image.open("/content/controlnet_ref_image.png")

#Inpaint controlnet
def make_inpaint_condition(image, image_mask):
    #image = Image.fromarray(image)
    #image_mask = Image.fromarray(image_mask)
    image = np.array(image.convert("RGB")).astype(np.float32) / 255.0
    image_mask = np.array(image_mask.convert("L")).astype(np.float32) / 255.0
    assert image.shape[0:1] == image_mask.shape[0:1], "image and image_mask must have the same image size"
    image[image_mask > 0.5] = -1.0  # set as masked pixel
    image = np.expand_dims(image, 0).transpose(0, 3, 1, 2)
    image = torch.from_numpy(image)
    return image

inpaint_image = make_inpaint_condition(input_image,mask_image)

#get canny image
image = cv2.Canny(np.array(input_image), 100, 200)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
canny_image = Image.fromarray(image)

controlnet_canny = ControlNetModel.from_pretrained("lllyasviel/control_v11p_sd15_canny", torch_dtype=torch.float16)
controlnet_inpaint = ControlNetModel.from_pretrained("lllyasviel/control_v11p_sd15_inpaint", torch_dtype=torch.float16)  

model = "SG161222/Realistic_Vision_V2.0"
scheduler = DPMSolverMultistepScheduler.from_pretrained(model, subfolder="scheduler", use_karras_sigmas=True)

pipe = DiffusionPipeline.from_pretrained(model,
                                        custom_pipeline="stable_diffusion_controlnet_reference",
                                        torch_dtype=torch.float16,
                                        controlnet=[controlnet_inpaint, controlnet_canny],
                                        revision="main",
                                        scheduler=scheduler)

result_img = pipe(ref_image=ref_image,
    prompt="photo of a object placed on a wooden table in alps",
    image=[inpaint_image, canny_image],
    num_inference_steps=20,
    guess_mode=True,
    controlnet_conditioning_scale= [1.0,1.0],
    style_fidelity=0.75,
    reference_attn=True,
    reference_adain=True).images[0]

result_img.show()

### Logs

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-80d2538d3785> in <cell line: 1>()
----> 1 result_img = pipe(ref_image=ref_image,
      2     prompt="photo of a bottle with shadow, minimilstic photography",
      3     image=[inpaint_image, canny_image],
      4     num_inference_steps=20,
      5     guess_mode=True,

2 frames
/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py in decorate_context(*args, **kwargs)
    113     def decorate_context(*args, **kwargs):
    114         with ctx_factory():
--> 115             return func(*args, **kwargs)
    116 
    117     return decorate_context

~/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_controlnet_reference.py in __call__(self, prompt, image, ref_image, height, width, num_inference_steps, guidance_scale, negative_prompt, num_images_per_prompt, eta, generator, latents, prompt_embeds, negative_prompt_embeds, output_type, return_dict, callback, callback_steps, cross_attention_kwargs, controlnet_conditioning_scale, guess_mode, attention_auto_machine_weight, gn_auto_machine_weight, style_fidelity, reference_attn, reference_adain)
    235 
    236         # 1. Check inputs. Raise error if not correct
--> 237         self.check_inputs(
    238             prompt,
    239             image,

/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/controlnet/pipeline_controlnet.py in check_inputs(self, prompt, image, callback_steps, negative_prompt, prompt_embeds, negative_prompt_embeds, controlnet_conditioning_scale, control_guidance_start, control_guidance_end)
    575         if isinstance(self.controlnet, MultiControlNetModel):
    576             if len(control_guidance_start) != len(self.controlnet.nets):
--> 577                 raise ValueError(
    578                     f"`control_guidance_start`: {control_guidance_start} has {len(control_guidance_start)} elements but there are {len(self.controlnet.nets)} controlnets available. Make sure to provide {len(self.controlnet.nets)}."
    579                 )

ValueError: `control_guidance_start`: [0.0] has 1 elements but there are 2 controlnets available. Make sure to provide 2.
```

### System Info

- `diffusers` version: 0.20.1
- Platform: Linux-5.15.109+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.32.1
- Accelerate version: 0.22.0
- xFormers version: 0.0.21

### Who can help?

@patrickvonplaten, @sayakpaul, and @williamberman

**Comment by sayakpaul** [comment]
We don't maintain community examples. Please tag the pipeline author here :-)

**Comment by 0sparsh2** [comment]
> We don't maintain community examples. Please tag the pipeline author here :-)

got it, I'll do that, thanks

**Comment by 0sparsh2** [comment]
@okotaku Could you please help out with this error

**Comment by williamberman** [comment]
there's also an officially maintained controlnet pipeline. see the blog post here for a tutorial on how to use https://huggingface.co/blog/controlnet

**Comment by williamberman** [comment]
does the multicontrolnet use case work with the official pipeline?

**Comment by 0sparsh2** [comment]
> does the multicontrolnet use case work with the official pipeline?

Yes, that's working with official pipeline as well as other custom pipelines like ControlNetInpaint where I am using multi controlnet currently

**Comment by CesarERamosMedina** [comment]
One way to go around the error you are getting is to set the check_inputs function as a dummy function (since this is the one throwing the exception):
def check_inputs_patch(*args, **kwargs):
    return

pipe.check_inputs = check_inputs_patch

**Comment by hajiarab1988** [comment]
> > there's also an officially maintained controlnet pipeline. see the blog post here for a tutorial on how to use https://huggingface.co/blog/controlnet
> 
> Thanks for the resource! The issue I am facing here is with particularly with multi-controlnet functionality while using stable diffusion controlnet reference pipeline Just as a hack, I have been able to make the pipeline function by slightly modifying the pipelines internally but they aren't the true solution.
> 
> I think if there is a way for the user to define control start and end point as well as inputs, this would be resolved

Hi, could you please explain in more detail how you exactly achieved that? If possible, could you provide a snippet of your code that helped you resolve this issue?

**Comment by wilfrediscoming** [comment]
> > does the multicontrolnet use case work with the official pipeline?
> 
> Yes, that's working with official pipeline as well as other custom pipelines like ControlNetInpaint where I am using multi controlnet currently

Can you provide the code for ControlNetInpaint? I am struggling to get it work

**Comment by sayakpaul** [comment]
Cc @yiyixuxu for ControlNet inpainting. 

Hi @wilfrediscoming, could you follow this doc https://huggingface.co/docs/diffusers/main/en/using-diffusers/controlnet#inpainting and see if things are working? If the issue is coming from the code snippet shown in the doc, please open a new issue.
