### ISSUE TITLE
MultiControlNet, wrong tensor size

### ISSUE THREAD

**Issue by Yakonrus** [huggingface/diffusers#4830]
### Describe the bug

  File "C:\Users\Yakon\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\models\controlnet.py", line 754, in forward
    sample = sample + controlnet_cond
RuntimeError: The size of tensor a (96) must match the size of tensor b (128) at non-singleton dimension 3

### Reproduction

        controlnet = [
            ControlNetModel.from_pretrained("diffusers/controlnet-canny-sdxl-1.0", torch_dtype=torch.float16),
            ControlNetModel.from_pretrained("diffusers/controlnet-depth-sdxl-1.0", torch_dtype=torch.float16),
        ]
        
        vae = AutoencoderKL.from_pretrained(
            "madebyollin/sdxl-vae-fp16-fix",
            torch_dtype=torch.float16
        )
        
        pipe_c = StableDiffusionXLControlNetPipeline.from_pretrained(
            "stabilityai/stable-diffusion-xl-base-1.0",
            controlnet=controlnet,
            vae=vae,
            torch_dtype=torch.float16,
            variant="fp16",
            use_safetensors=True,
            add_watermarker=False,
        )
        
        images = [image_с, depth_image]  // Canny image, depth image
        
        image_c = pipe_c(
            prompt=prompt,
            negative_prompt=nprompt,
            generator=generator,
            image=images,
            num_inference_steps=30,
            controlnet_conditioning_scale=[1.0, 0.8],
        ).images[0]

### System Info

diffusers-0.20.1

**Comment by patrickvonplaten** [comment]
@yiyixuxu could you take a look here?

**Comment by yiyixuxu** [comment]
@Yakonrus 
Thanks for the issue!
Can you provide a code snippet that's reproducible? In the example you provided, I wouldn't know what input image you used

**Comment by Yakonrus** [comment]
https://drive.google.com/file/d/1VammSstyJ-VNTAwOHNvKgMvZyecPxWYJ/view?usp=sharing

Windows 11
Python 3.10.11
torch 2.0.1+cu118
diffusers 0.20.1

Input - any usial .jpg

**Comment by Yakonrus** [comment]
@yiyixuxu 

https://drive.google.com/file/d/1VammSstyJ-VNTAwOHNvKgMvZyecPxWYJ/view?usp=sharing

Windows 11
Python 3.10.11
torch 2.0.1+cu118
diffusers 0.20.1

Input - any usial .jpg

**Comment by yiyixuxu** [comment]
@Yakonrus 
Thanks for the issue. 

I'm not able to reproduce your error with the inputs I prepared. 
If you still experience the error, please provide a reproducible code snippet. Thanks!

```python
from diffusers import (
                       ControlNetModel,
                       StableDiffusionXLControlNetPipeline,
                       AutoencoderKL, 
                       )
from transformers import DPTImageProcessor, DPTForDepthEstimation

from diffusers.utils import load_image
from PIL import Image
import torch
import numpy as np
import cv2

# load model
controlnet_canny = ControlNetModel.from_pretrained(
    "diffusers/controlnet-canny-sdxl-1.0",
    variant="fp16",
    torch_dtype=torch.float16
)
controlnet_depth = ControlNetModel.from_pretrained(
    "diffusers/controlnet-depth-sdxl-1.0",
    variant="fp16",
    torch_dtype=torch.float16
)
vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)
pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    controlnet=[controlnet_canny, controlnet_depth],
    vae=vae,
    variant="fp16",
    torch_dtype=torch.float16,
)
pipe.to('cuda')

# load image
raw_image = load_image("https://huggingface.co/datasets/hf-internal-testing/diffusers-images/resolve/main/sd_controlnet/hf-logo.png")
size = (1024, 1024)

# get canny
image_canny = cv2.Canny(np.array(raw_image.resize(size)), 100, 200)
image_canny = image_canny[:, :, None]
image_canny = np.concatenate([image_canny, image_canny, image_canny], axis=2)
image_canny = Image.fromarray(image_canny)
image_canny

# get depth
depth_estimator = DPTForDepthEstimation.from_pretrained("Intel/dpt-hybrid-midas").to("cuda")
feature_extractor = DPTImageProcessor.from_pretrained("Intel/dpt-hybrid-midas")

image_depth = feature_extractor(images=raw_image, return_tensors="pt").pixel_values.to("cuda")
with torch.no_grad(), torch.autocast("cuda"):
    depth_map = depth_estimator(image_depth).predicted_depth

depth_map = torch.nn.functional.interpolate(
    depth_map.unsqueeze(1),
    size=size,
    mode="bicubic",
    align_corners=False,
)
depth_min = torch.amin(depth_map, dim=[1, 2, 3], keepdim=True)
depth_max = torch.amax(depth_map, dim=[1, 2, 3], keepdim=True)
depth_map = (depth_map - depth_min) / (depth_max - depth_min)
image_depth = torch.cat([depth_map] * 3, dim=1)

image_depth = image_depth.permute(0, 2, 3, 1).cpu().numpy()[0]
image_depth = Image.fromarray((image_depth * 255.0).clip(0, 255).astype(np.uint8)).resize(size)
image_depth

# run
prompt = "aerial view, a futuristic research complex in a bright foggy jungle, hard lighting"
negative_prompt = 'wrong, low quality, bad quality, sketches'
controlnet_conditioning_scale = [1.0, 0.8]  # recommended for good generalization

images = pipe(
    prompt, 
    negative_prompt=negative_prompt, 
    image=[image_canny, image_depth], 
    controlnet_conditioning_scale=controlnet_conditioning_scale,
    ).images

images[0].save(f"test_1_out.png")
```

**Comment by Yakonrus** [comment]
https://drive.google.com/file/d/1VammSstyJ-VNTAwOHNvKgMvZyecPxWYJ/view?usp=sharing
jpg aspect ratio - 3:2

**Comment by yiyixuxu** [comment]
@Yakonrus 
you can find this section here on how to create a reproducible, minimal bug report.https://huggingface.co/docs/diffusers/conceptual/contribution#21-reproducible-minimal-bug-reports

Thanks!
YiYi

**Comment by Yakonrus** [comment]
Found the answer

https://huggingface.co/diffusers/controlnet-depth-sdxl-1.0
feature_extractor = DPTFeatureExtractor.from_pretrained("Intel/dpt-hybrid-midas")

in your snippet
feature_extractor = DPTImageProcessor.from_pretrained("Intel/dpt-hybrid-midas")

DPTImageProcessor - works
DPTFeatureExtractor - not works

**Comment by yiyixuxu** [comment]
@Yakonrus 
oh great!
you should use `DPTImageProcessor`, instead of `DPTFeatureExtractor` then
