### ISSUE TITLE
convert_original_stable_diffusion_to_diffusers.py failed SDXL model

### ISSUE THREAD

**Issue by TimYao18** [huggingface/diffusers#4837]
### Describe the bug

Use this script to Convert SDXL based model,
failed in diffusers==0.20.0 or 0.20.1, error:
```bash
download_from_original_stable_diffusion_ckpt
    pipe = pipeline_class(
TypeError: __init__() got an unexpected keyword argument 'text_encoder_2'
```

But success in diffusers==0.19.3

### Reproduction

python3 convert_original_stable_diffusion_to_diffusers.py --checkpoint_path RealitiesEdgeXL_.safetensors --from_safetensors --device cpu --extract_ema --dump_path RealitiesEdgeXL_diffusers

### Logs

```shell
Traceback (most recent call last):
  File "/Users/Tim/ml-stable-diffusion/convert_original_stable_diffusion_to_diffusers.py", line 154, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1591, in download_from_original_stable_diffusion_ckpt
    pipe = pipeline_class(
TypeError: __init__() got an unexpected keyword argument 'text_encoder_2'
```

### System Info

- `diffusers` version: 0.20.1
- Platform: macOS-14.0-arm64-arm-64bit
- Python version: 3.9.13
- PyTorch version (GPU?): 2.0.1 (False)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.29.2
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Can you try if:

```py
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_single_file("RealitiesEdgeXL_.safetensors", extract_ema=True)
pipe.save_pretrained("/your/dump/path")
```

works? (or without `extract_ema=True`)

This should be the preferred way now

**Comment by salman-aziz-4425** [comment]
> ```python
>  diffusers import StableDiffusionXLPipeline
> 
> pipe = StableDiffusionXLPipeline.from_single_file("RealitiesEdgeXL_.safetensors", extract_ema=True)
> pipe.save_pretrained("/your/dump/path")
> ```
how we can them for generating text to image if model is stored in safetensor format?

**Comment by TimYao18** [comment]
> Can you try if:
> 
> ```python
> from diffusers import StableDiffusionXLPipeline
> 
> pipe = StableDiffusionXLPipeline.from_single_file("RealitiesEdgeXL_.safetensors", extract_ema=True)
> pipe.save_pretrained("/your/dump/path")
> ```
> 
> works? (or without `extract_ema=True`)
> 
> This should be the preferred way now

Hi [patrickvonplaten](https://github.com/patrickvonplaten), I tried and it works. 
Currently, diffusers==0.20.2 is still not working using scripts to convert XL model.

**Comment by reimager** [comment]
Adding this in case others have the same issue:

use "--pipeline_class_name StableDiffusionXLPipeline"

**Comment by Jiancong** [comment]
Is there any update on this bug? I met the same problem.

**Comment by Dav1nx1** [comment]
> Adding this in case others have the same issue: when calling the convert script use "--pipeline_class_name StableDiffusionXLPipeline"

This works for me.
