### ISSUE TITLE
PNDMSchedulerTest::test_full_loop_no_noise uses time index rather than time_step in `step`

### ISSUE THREAD

**Issue by natolambert** [huggingface/diffusers#484]
### Describe the bug

One can see the usage of the `PNDMScheduler` in the `PNDMPipeline` (Or stable diffusion for that matter), and it looks like this, with timesteps passed into the scheduler

https://github.com/huggingface/diffusers/blob/f4781a0b27ffb3ea61ecd25b0b87305e0960304e/src/diffusers/pipelines/pndm/pipeline_pndm.py#L97-L101

Though, in the `test_scheduler` file it is backwards. This may cause some unintended behavior going forward.

https://github.com/huggingface/diffusers/blob/f4781a0b27ffb3ea61ecd25b0b87305e0960304e/tests/test_scheduler.py#L633-L655

### System Info

Not a runtime bug.

**Comment by patrickvonplaten** [comment]
Oh good point! Thanks for pointing this out @natolambert - we should fix the tests here. They are wrong

**Comment by natolambert** [comment]
I would've done it directly, but the systems I use (m1 mac and a GCP machine) always fail on that specific test anyways, so I can't update the numbers that easily.

**Comment by patrickvonplaten** [comment]
Ok happy to take care of it!

**Comment by patrickvonplaten** [comment]
Waiting here until the schedulers are all in PyTorch / Numpy respectively at which point we have to update the tests anyway

**Comment by patrickvonplaten** [comment]
This can be closed by now as PNDM is fixed I believe :-)
