### ISSUE TITLE
Does sdxl support loading multiple lora?

### ISSUE THREAD

**Issue by wen020** [huggingface/diffusers#4843]
Does sdxl support loading multiple lora?

**Comment by patrickvonplaten** [comment]
Could you explain your use case in a bit more detail? Do you want to dynamically switch out LoRAs during runtime or do you want to run a forward pass with multiple LoRAs contributing to the inference?

**Comment by patrickvonplaten** [comment]
Guess related here: https://github.com/huggingface/diffusers/issues/4348#issuecomment-1698938657

We should probably try to leverage PEFT for this here
