### ISSUE TITLE
train dreambooth ,have strange result

### ISSUE THREAD

**Issue by 1235555555shan** [huggingface/diffusers#4846]
### Model/Pipeline/Scheduler description

Hello, I trained the dreambooth according to the document, and trained the text_encoder unet at the same time, but how could the predicted result be like this, and I urgently need help. If you don't use unet text encoder, it can be normal a little bit, looking forward to reply

![image](https://github.com/huggingface/diffusers/assets/85985529/aa3ab5aa-1789-4ba5-b9d2-edd9392298f1)

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by patrickvonplaten** [comment]
Could you try to use the forum: https://discuss.huggingface.co/ for such questions instead? We're trying to keep GitHub for issues mostly
