### ISSUE TITLE
how to use multiple GPUs to train textual inversion?

### ISSUE THREAD

**Issue by Adorablepet** [huggingface/diffusers#4849]
I train the textual inversion fine tuning cat toy example from [here](https://github.com/huggingface/diffusers/tree/main/examples/textual_inversion)

my env:
diffusers: 0.20.0
torch: 1.12.1+cu113
accelerate: 0.22.0

train script, as follow:

```
CUDA_VISIBLE_DEVICES="0,1,2,3" python -u textual_inversion.py --pretrained_model_name_or_path=$MODEL_NAME --train_data_dir=$DATA_DIR --learnable_property="object" --placeholder_token="<cat-toy>" --initializer_token="toy" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=4 --max_train_steps=3000 --learning_rate=5.0e-04 --scale_lr --lr_scheduler="constant" --lr_warmup_steps=0 --output_dir="textual_inversion_cat"
```

But it only trained in cuda:0,  Is there any way to solve the problem of training on a multi gpus？Thanks.

**Comment by patrickvonplaten** [comment]
Make sure you set your `accelerate` config correctly. See: https://huggingface.co/docs/accelerate/v0.22.0/en/package_reference/cli#accelerate-config
