### ISSUE TITLE
Function to Convert PIL->Latents

### ISSUE THREAD

**Issue by ksteinfe** [huggingface/diffusers#4857]
**Is your feature request related to a problem? Please describe.**
I'm trying to use a StableDiffusionXLControlNetPipeline which takes "latents" as an argument to set the initial noise for the diffusion process. In other image-to-image diffuser pipelines, we can pass an image to serve this purpose, which then gets converted to latents internally, but the StableDiffusionXLControlNetPipeline doesn't offer this argument. 

**Describe the solution you'd like**
Provide a function to convert a PIL image to the latents that are required for setting the initialization image for a diffuser pipeline.

**Describe alternatives you've considered**
I've tried to implement this function myself. My non-working function below. The error this produces is "RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [128] and input of shape [128, 512, 840]"

```
# PIL to LATENTS
# Convert init image to latents to serve as the initalization image for SDXL
def pil_to_latent(img, vae):
  image = torchvision.transforms.functional.pil_to_tensor(img.convert("RGB"))
  image = image / image.max() # ensures it is in the range 0 to 1 with no alpha channel
  image = image.half().cuda()
  data_latents = vae.encode(image.mul(2).sub(1)).latent_dist.sample() * vae.scaling_factor # the scaling factor is eff-ing brutally esoteric haha
  torch.randn_like((data_latents), 0)
  return data_latents
```

**Additional context**
Here is the context in which I would use this function to make a call to StableDiffusionXLControlNetPipeline

```
better_vae = AutoencoderKL.from_pretrained(
    "madebyollin/sdxl-vae-fp16-fix",
    torch_dtype=torch.float16,
)
controlnet_base = ControlNetModel.from_pretrained(
    "diffusers/controlnet-depth-sdxl-1.0",
    variant="fp16",
    use_safetensors=True,
    torch_dtype=torch.float16
)
pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    vae=better_vae,
    controlnet=controlnet_base,
    use_safetensors=True,
    variant="fp16",
    torch_dtype=torch.float16,
)

images = pipe(
    PROMPT,
    image=CONTROLNET_DEPTH_GUIDE_IMAGE,
    num_inference_steps=30,
    generator=generator,
    latents = pil_to_latent(INIT_PIL_IMG, pipe.vae)
).images
```

**Comment by patrickvonplaten** [comment]
Could you have a look at the example on this PR's description: https://github.com/huggingface/diffusers/pull/4819#issue-1870712683 ? 

I think it should solve your qusetion

**Comment by ksteinfe** [comment]
Appreciate the nudge in the right direction, @patrickvonplaten. I feel like I must be close but am missing something critical. My revised function below based on the example you pointed me towards. I'm no longer getting any errors, and am able to generate images, but things don't look right. 

Is there something wrong with the values or dtype of my latents? I see that they're in a range of [-1,1]. Should I be adding noise? print from function below returns:


`torch.float16	 torch.Size([1, 3, 1024, 2000])	 min:-1.0	 max:1.0`


**INIT_PIL_IMG**
![image](https://github.com/huggingface/diffusers/assets/2659599/3c0a6b03-ed4f-4443-b341-f9f53b1b1225)

**CONTROLNET_DEPTH_GUIDE_IMAGE**
![image](https://github.com/huggingface/diffusers/assets/2659599/4288f9fa-d292-4052-a922-aca17b5de960)

**RESULT**
![image](https://github.com/huggingface/diffusers/assets/2659599/b4beee20-1bef-40ae-aecd-7aac9c930e15)

```

def pil_to_latent(img, sd_pipe):
  image = sd_pipe.image_processor.preprocess(img).to(sd_pipe.device).half()
  print("{}\t {}\t min:{}\t max:{}".format(image.dtype, image.shape, torch.min(image), torch.max(image)))
  image_latents = (
      sd_pipe.vae.encode(image).latent_dist.sample() * sd_pipe.vae.config.scaling_factor
  )
  return image_latents
```

**Comment by ksteinfe** [comment]
I think I mostly have this solved, with the help of @rynmurdock
For anyone who might come across a similar issue, below is a function that seems to work in the sense that it sets the latents as expected. The X pipeline still needs to be adapted to skip those generation steps that come before the step specified by denoising_start.

Note that this script relies on the `get_timesteps()` function from the SDXL Img2Img pipeline, at: https://github.com/huggingface/diffusers/blob/ef9824f9f79dbe0096df6797af274b316f1c4970/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py#L494

```
def pil_to_latent(img, sd_pipe, generator, noisiness, num_inference_steps, denoising_start):  # denoising_start is a value 0.0->1.0
    img = resize_image(img, 1024)
    image = sd_pipe.image_processor.preprocess(img).to(sd_pipe.device).half() # ksteinfe added .half()
    image_latents = (
        sd_pipe.vae.encode(image).latent_dist.sample() * sd_pipe.vae.config.scaling_factor
    )
    sd_pipe.scheduler.set_timesteps(num_inference_steps, device=sd_pipe.device)
    #timestep = sd_pipe.scheduler.timesteps[0]
    timesteps, num_inference_steps = get_timesteps(sd_pipe, num_inference_steps, 0.00, sd_pipe.device, denoising_start=denoising_start) # 0.00 for 'strength' argument because this value is ignored if we provide denoising_start
    timestep = torch.tensor([timesteps[0]])
    noisy_latents = sd_pipe.scheduler.add_noise(image_latents, torch.randn_like(image_latents), timestep)
    return noisy_latents```

**Comment by ksteinfe** [comment]
Thanks @patrickvonplaten for the pointers!

**Comment by imiraoui** [comment]
Is there an easier way?
