### ISSUE TITLE
fix guidance_rescale docstring to reflect true default value

### ISSUE THREAD

**Issue by codinggosu** [huggingface/diffusers#4864]
guidance_rescale is a parameter available in many pipelines that was implemented in this [pr](https://github.com/huggingface/diffusers/pull/3664).

To maintain backwards compatibility, and due to concerns about the results with guidance_scale applied not being objectively better all the time, the default value was determined to be best left as 0, and not 0.7 as originally planned. 

This has been reflected in the code, but not the docstring. 

I propose an issue to correct all occurrences of the bad docstring. 

```            
guidance_rescale (`float`, *optional*, defaults to 0.7):
```
will be changed to 
```
guidance_rescale (`float`, *optional*, defaults to 0.0):
```

**Comment by codinggosu** [comment]
since this is a docstring problem (no real impact on the logic of the code) I didn't now whether this satisfies the requirements of an "issue" (not a bug or a feature request)

I have read the contribution guide but wasn't able to see a clear answer about this so I have filed this as an issue nevertheless. 

I will also make a pr to fix this.. so I thought an issue accompanying the pr would be necessary.

**Comment by stevhliu** [comment]
Thanks for catching this, looking forward to reviewing your PR 😄
