### ISSUE TITLE
DPM++ SDE sampling crashes if batch size changes between invocations

### ISSUE THREAD

**Issue by damian0815** [huggingface/diffusers#4875]
### Describe the bug

When using `DPMSolverSDEScheduler`, the internal `self.noise_sampler` is initialized to return noise with a batch size matching the first batch passed, and then cached. Subsequent usages with the same batch size function, but if the batch size changes `RuntimeError` is raised. For example, with initial batch size 3 and subsequent batch size 2 the runtime error is:
```
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 696, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs, return_dict=False)[0]
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpmsolver_sde.py", line 481, in step
    prev_sample = prev_sample + self.noise_sampler(sigma_fn(t), sigma_fn(t_next)) * s_noise * sigma_up
RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0
```

To fix this, the batch size of `self.noise_sampler` should be checked against the incoming sample's batch size, and if it does not match then `self.noise_sampler` should be re-initialized to match.

### Reproduction

```
pipeline = StableDiffusionPipeline.from_pretrained('runwayml/stable-diffusion-v1-5')
pipeline.scheduler = DPMSolverSDEScheduler.from_config(scheduler_config, use_karras_sigmas=True, noise_sampler_seed=0)
# batch size 3
pipeline(prompts=["a cat playing with a ball in the forest", "a dog eating dinner", "an eagle"], num_inference_steps=10)
# then batch size 2
pipeline(prompts=["a cat playing with a ball in the forest", "a dog eating dinner"], num_inference_steps=10)
```
result: crash in the second `pipeline` invocation:
```
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 696, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs, return_dict=False)[0]
  File "/workspace/venv/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpmsolver_sde.py", line 481, in step
    prev_sample = prev_sample + self.noise_sampler(sigma_fn(t), sigma_fn(t_next)) * s_noise * sigma_up
RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0
```

### System Info

diffusers == 0.20.2

### Who can help?

@patrickvonplaten @williamberman

**Comment by patrickvonplaten** [comment]
@yiyixuxu can you take a look here?

**Comment by yiyixuxu** [comment]
@damian0815 
Could you use `DPMSolverSinglestepScheduler` instead? https://huggingface.co/docs/diffusers/main/en/api/schedulers/singlestep_dpm_solver

It implements the same algorithm as `DPMSolverSDEScheduler` and it is the default one from the author ( we might deprecate `DPMSolverSDEScheduler` soon)

**Comment by damian0815** [comment]
when i try and use `DPMSolverSinglestepScheduler` instead i get an error: 

```
...
    scheduler = scheduler_class.from_config(scheduler_config)
  File "/workspace/venv-invoke/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 254, in from_config
    model = cls(**init_dict)
  File "/workspace/venv-invoke/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
  File "/workspace/venv-invoke/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpmsolver_singlestep.py", line 186, in __init__
    raise NotImplementedError(f"{algorithm_type} does is not implemented for {self.__class__}")
NotImplementedError: sde-dpmsolver++ does is not implemented for <class 'diffusers.schedulers.scheduling_dpmsolver_singlestep.DPMSolverSinglestepScheduler'>
```

which suggests that SDE algorithm is not, in fact, implemented here. i traced `sde-dpmsolver++` back to the scheduler_config.json inside my model file - not sure if it's supposed to be there or not.

**Comment by yiyixuxu** [comment]
@damian0815 ohh thanks so much! I think you're right; going to look into it today!

@patrickvonplaten I think we got the mapping wrong here. https://huggingface.co/docs/diffusers/main/en/api/schedulers/overview
`DPMSolverSinglestepScheduler` doesn't support the SDE variant
