### ISSUE TITLE
Make noise_init_strength of lora layer weights an input arg

### ISSUE THREAD

**Issue by aiXander** [huggingface/diffusers#4877]
I'm curious why the std of the weights is set to 1/rank by default?
https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/lora.py#L40

**Comment by patrickvonplaten** [comment]
Hey @aiXander, 

Could you please post such questions on: https://discuss.huggingface.co/ ? We try to keep GitHub clean for bug issues and PRs
