### ISSUE TITLE
ValueError: Key `down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor` is invalid, expected torch.Tensor but received <class 'dict'>

### ISSUE THREAD

**Issue by Sandeep-Narahari** [huggingface/diffusers#4889]
### Describe the bug

After completing the training I got this error while training custom diffusion 
![Screenshot from 2023-09-05 02-40-37](https://github.com/huggingface/diffusers/assets/46187761/a60eb91a-9210-43f0-a542-f326f28ac2d2)

### Reproduction

`!accelerate launch train_custom_diffusion.py \
  --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4"  \
  --output_dir=/content/output \
  --concepts_list=/content/meta.json \
  --with_prior_preservation --real_prior --prior_loss_weight=1.0 \
  --resolution=512  \
  --train_batch_size=1  \
  --learning_rate=1e-5  \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --num_class_images=200 \
  --scale_lr --hflip  \
  --enable_xformers_memory_efficient_attention \
  --modifier_token "<new1>+<new2>" `

### System Info

Google collab
Python 3.10.12
diffusers Version: 0.21.0.dev0
clip-retrieval Version: 2.37.0

### Who can help?

@sayakpaul @yiyixuxu @willi

**Comment by sayakpaul** [comment]
Could you provide the Colab Notebook you're using for this?

**Comment by canberk17** [comment]
@sayakpaul, I believe this is related to the issue discussed here: #4704 .@Sandeep-Narahari, could you try adding 
`--no_safe_serialization` to your arguments and see if that'll do the trick?

**Comment by Sandeep-Narahari** [comment]
Yeah correct got it , working now , Thank you
