### ISSUE TITLE
"from_single_file" consumes a lot of CPU RAM and cannot be allocated to GPU/CUDA.

### ISSUE THREAD

**Issue by putuoka** [huggingface/diffusers#4894]
reproduction code https://colab.research.google.com/drive/1v0xiESZi187acMP-aHSJLvtVm8MK5UTI

Unlike from_pretrained, even when using "torch_dtype=torch.float16" and the .to("cuda") command, it is still processed using CPU RAM and consumes very high amounts, crashing with over 12GB of CPU RAM usage.

I have tried it with device_map="auto" but it still does not work. low_mem_cpu_usage="true" also does not help.

**Comment by patrickvonplaten** [comment]
Hey @putuoka, can you try loading with `variant="fp16"` to make sure the fp16 are loaded and not the fp32 ones?

**Comment by putuoka** [comment]
> Hey @putuoka, can you try loading with `variant="fp16"` to make sure the fp16 are loaded and not the fp32 ones?

I have already written it in the example reproduction link above, the result remains the same.

**Comment by patrickvonplaten** [comment]
Then I don't really know what's going on. If you have `accelerate` installed and use `variant="fp16"` as well as `torch_dtype=torch.float16` you should not require more CPU or GPU RAM than the size of the model weights.

**Comment by Garry435** [comment]
I am also facing the same issue , when I do from_single_file , it download config files right , but after that , when it tries to make pipeline , it takes all of ram crashing the session , it is not using a single byte of gpu while loading pipeline . The gpu remains untouched

**Comment by putuoka** [comment]
> I am also facing the same issue , when I do from_single_file , it download config files right , but after that , when it tries to make pipeline , it takes all of ram crashing the session , it is not using a single byte of gpu while loading pipeline . The gpu remains untouched

yes exactly The gpu remains untouched.

**Comment by alexblattner** [comment]
also, when reusing the same file for checkpoint, it doesn't reuse it.

**Comment by sayakpaul** [comment]
Hi all. 

It would be much appreciated if you could help us understand things a bit better. 

1. Some code snippet to show how exactly you're doing things. 
2. Output of `diffusers-cli env` so that we can see the environment you're using this in. 
3. A log of the CPU RAM usage with the different options you have tried.

**Comment by alexblattner** [comment]
@sayakpaul here are my logs:
1
GPU 0: Tesla T4, GPU Memory Usage: 0.00 GB
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
/home/alexblattnershalom/.local/lib/python3.10/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
2
GPU 0: Tesla T4, GPU Memory Usage: 5.13 GB
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
3
GPU 0: Tesla T4, GPU Memory Usage: 9.49 GB
4
GPU 0: Tesla T4, GPU Memory Usage: 9.49 GB
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.94it/s]
Traceback (most recent call last):
  File "/mecomics-api/tester2.py", line 89, in <module>
    fimage=tempipe(prompt, **kwargs).images[0]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/alexblattnershalom/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 731, in __call__
    image = self.vae.decode(latents / self.vae.config.scaling_factor, return_dict=False)[0]
  File "/home/alexblattnershalom/.local/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/home/alexblattnershalom/.local/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 285, in decode
    decoded = self._decode(z).sample
  File "/home/alexblattnershalom/.local/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 272, in _decode
    dec = self.decoder(z)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alexblattnershalom/.local/lib/python3.10/site-packages/diffusers/models/vae.py", line 271, in forward
    sample = up_block(sample, latent_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alexblattnershalom/.local/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 2334, in forward
    hidden_states = upsampler(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alexblattnershalom/.local/lib/python3.10/site-packages/diffusers/models/resnet.py", line 169, in forward
    hidden_states = self.conv(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alexblattnershalom/.local/lib/python3.10/site-packages/diffusers/models/lora.py", line 149, in forward
    return F.conv2d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 14.58 GiB total capacity; 9.94 GiB already allocated; 201.62 MiB free; 10.10 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

here's the code:
def checkGPU(num):
    print(num)
    if torch.cuda.is_available():
        # Get the number of available GPUs
        num_gpus = torch.cuda.device_count()
        
        for gpu_id in range(num_gpus):
            # Select the GPU
            torch.cuda.set_device(gpu_id)
            
            # Get GPU properties
            gpu_name = torch.cuda.get_device_name(gpu_id)
            gpu_memory = torch.cuda.max_memory_allocated(gpu_id) / (1024 ** 3)  # Convert to GB
            
            # Print GPU information
            print(f"GPU {gpu_id}: {gpu_name}, GPU Memory Usage: {gpu_memory:.2f} GB")
checkGPU(1)
pipe=StableDiffusionPipeline.from_single_file(
    "./checkpoint/lyriel.safetensors", torch_dtype=torch.float32,local_files_only=True,safety_checker=None, requires_safety_checker=False,
).to('cuda')

pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config)
checkGPU(2)

# vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse-original").to("cuda")
# pipe.vae = vae
buffer = open('img111.png', 'rb')
buffer.seek(0)
image_bytes = buffer.read()
buffer.close()
# Convert image bytes to Base64 string
image = Image.open(BytesIO(image_bytes))
buffer=open('tmask.png', 'rb')
buffer.seek(0)
image_bytes = buffer.read()
buffer.close()
mask_image = Image.open(BytesIO(image_bytes))
buffer=open('poses/gpose.png', 'rb')
buffer.seek(0)
image_bytes = buffer.read()
tempipe=StableDiffusionPipeline.from_single_file("./checkpoint/lyriel.safetensors",
    vae=pipe.vae,
    text_encoder=pipe.text_encoder,
    tokenizer=pipe.tokenizer,
    unet=pipe.unet,
    scheduler=pipe.scheduler
).to("cuda")
checkGPU(3)

# tempipe=apply_img2img(tempipe)
# pipe=apply_inpainting(pipe)
kwargs=dict()
generator = torch.manual_seed(12121)
# kwargs['image']=image
# kwargs['mask_image']=mask_image
kwargs['generator']=generator
# kwargs['strength']=0.75
kwargs['num_inference_steps']=20
prompt="girl, 4k, beautiful day in the park"
checkGPU(4)

fimage=tempipe(prompt, **kwargs).images[0]
fimage.save("img6.png")

**Comment by jndietz** [comment]
I am using SDXL, and subsequently `StableDiffusionXLPipeline`.  I am also using `from_single_file`.

When I construct the pipeline, I expect a normal amount of GPU RAM to be used - around 8.5 GB (out of my total 24 GB).  Probably some other windows processes using some GPU RAM.

![image](https://github.com/huggingface/diffusers/assets/4515791/255456e7-68e1-45be-ae55-9d695d578f88)

When I actually use the pipeline, and infer an image, it slightly increases to 10GB, then after inference is complete, it balloons up to 16GB!

![image](https://github.com/huggingface/diffusers/assets/4515791/664f726d-17bc-4779-b5e3-28ca7aa73f57)

**Comment by alexblattner** [comment]
bumping

**Comment by patrickvonplaten** [comment]
You should use `accelerate` to see an improvement in CPU mem usage

**Comment by andriwas** [comment]
up

**Comment by patrickvonplaten** [comment]
Does this code snippet: 

```py
# Load the model and configure the pipeline
model_path = "C:/github/stable-diffusion-webui/models/Stable-diffusion/sdxl/sd_xl_base_1.0_0.9vae.safetensors"
pipe = StableDiffusionXLPipeline.from_single_file(
    model_path, revision="fp16", variant="fp16", torch_dtype=torch.float16
)
pipe.to("cuda")
pipe.scheduler = DPMSolverMultistepScheduler.from_config(
                    pipe.scheduler.config, use_karras_sigmas=True
                )
```

with `accelerate` load to errors for you?

**Comment by ruu2** [comment]
In my case, RAM crash seems to occur at that code below.

[diffusers/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py)

```
def download_from_original_stable_diffusion_ckpt(
...
            if is_accelerate_available():  # SBM Now move model to cpu.
                if model_type in ["SDXL", "SDXL-Refiner"]:
                    for param_name, param in converted_unet_checkpoint.items():
                        print(param_name)
                        # ↓ THIS LINE
                        set_module_tensor_to_device(unet, param_name, "cpu", value=param)
```

where `print` statement is inserted by me.

I'm not sure what exactly that code is doing, but I suspect this code duplicates the weights of the model and exhausts all CPU memory available.

I tried `set_module_tensor_to_device(unet, param_name, "cuda", value=param)` instead of  `set_module_tensor_to_device(unet, param_name, "cpu", value=param)`.

I think this replacement is workaround and may cause undesirable side-effect. But, at least, RAM crash was avoided and image was generated.

I hope this information is helpful for investigating.


I tried at Google Colab. RAM size is 12.7GB and VRAM size is 15GB.


Code snippet I tried is
```
import diffusers
import torch

model_path = "/content/sd_xl_base_1.0_0.9vae.safetensors"
pipe = diffusers.StableDiffusionXLPipeline.from_single_file(
    model_path, revision="fp16", variant="fp16", torch_dtype=torch.float16
)
pipe.to("cuda")
pipe.scheduler = diffusers.DPMSolverMultistepScheduler.from_config(
                    pipe.scheduler.config, use_karras_sigmas=True
                )
prompt = "A photo of an astronaut riding a horse"
negative_prompt=""
image = pipe(prompt=prompt,negative_prompt=negative_prompt,width=1024,height=1024).images[0]
image
```

Result of diffusers-cli env is
```
- `diffusers` version: 0.21.2
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.33.2
- Accelerate version: 0.23.0
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
```

**Comment by Garry435** [comment]
Yeah that works, I too figured it out but forgot to share nvm ,
You can run this cell in colab before importing diffusers , this will fix that :
```
lines = open("/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py").readlines()
i = 0
l_index = None
for line in lines:
    if l_index == None:
        if line.startswith("def download_from_original_stable_diffusion_ckpt"):
            l_index=i
    else:
        if line.startswith("    return pipe"):
            e_index=i
            break
    i+=1
e_index= e_index+1
func_lines = ''.join(lines[l_index:e_index])

old_ln='''    if isinstance(checkpoint_path_or_dict, str):
        if from_safetensors:
            from safetensors.torch import load_file as safe_load

            checkpoint = safe_load(checkpoint_path_or_dict, device="cpu")
        else:
            if device is None:
                device = "cuda" if torch.cuda.is_available() else "cpu"
                checkpoint = torch.load(checkpoint_path_or_dict, map_location=device)
            else:
                checkpoint = torch.load(checkpoint_path_or_dict, map_location=device)
    elif isinstance(checkpoint_path_or_dict, dict):
        checkpoint = checkpoint_path_or_dict'''
new_ln='''    if from_safetensors:
        from safetensors.torch import load_file as safe_load

        checkpoint = safe_load(checkpoint_path_or_dict, device="cpu")
    else:
        if device is None:
            device = "cpu" if torch.cuda.is_available() else "cpu"
            checkpoint = torch.load(checkpoint_path_or_dict, map_location=device)
        else:
            checkpoint = torch.load(checkpoint_path_or_dict, map_location=device)'''

old_ln2='''set_module_tensor_to_device(vae, param_name, "cpu", value=param)'''
new_ln2='''set_module_tensor_to_device(vae, param_name, "cuda", value=param)'''

old_ln3='''set_module_tensor_to_device(unet, param_name, "cpu", value=param)'''
new_ln3='''set_module_tensor_to_device(unet, param_name, "cuda", value=param)'''
n_func_lines = func_lines.replace(old_ln,new_ln).replace(old_ln2,new_ln2).replace(old_ln3,new_ln3)
lines = ''.join(lines)
lines = lines.replace(func_lines,n_func_lines)
open("/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py","w").write(lines)
```

**Comment by jndietz** [comment]
@patrickvonplaten Thanks for the response - I think what I'm experiencing is in the normal range of RAM usage especially for SDXL.

**Comment by Rorutop** [comment]
> I tried `set_module_tensor_to_device(unet, param_name, "cuda", value=param)` instead of `set_module_tensor_to_device(unet, param_name, "cpu", value=param)`.

Tried that and the ram is standing strong even its at 12.1gb ram until it crashed eventually..

```
2024-02-13 15:29:26.547030: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
```

**Comment by sayakpaul** [comment]
Does disabling XLA help in any way?
