### ISSUE TITLE
I'd like to use vae-ft-mse-840000-ema-pruned, but I don't have config.... should be usable with safetensors only

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#4898]
Hi, I'm trying to use vae-ft-mse-840000-ema-pruned, but diffusers require a config.js file. At first, I downloaded the safetensors file from civitai, then tried this: stabilityai/sd-vae-ft-mse-original which didn't work because it doesn't have a config file. I looked through the community discussion and someone said to just use this: stabilityai/sd-vae-ft-ema , but I am not sure if it is the same VAE I am looking for.

In any case, is there a way to use a vae safetensors without config?

**Comment by sayakpaul** [comment]
You should be able to use `from_single_file()` here I think. 

```python
from diffusers import AutoencoderKL

vae = AutoencoderKL.from_single_file("...")
```

**Comment by alexblattner** [comment]
@sayakpaul it worked! thanks!
