### ISSUE TITLE
Missing schema: Invalid URL

### ISSUE THREAD

**Issue by creatorrr** [huggingface/diffusers#49]
Throwing `MissingSchema: Invalid URL` on trying to load a sample `DiffusionPipeline` from the huggingface hub. It does download the model files but fails right after. Maybe it's a problem with the model?

I tried to run:

```python
pipeline = DiffusionPipeline.from_pretrained("fusing/glide-base")
```

Error:
```
Could not locate the glide.py inside /home/diwank/.cache/huggingface/diffusers/models--fusing--glide-base/snapshots/510aa20b54bbb8b77c170812dc0cbbbd06f58a6a.

MissingSchema: Invalid URL '/home/diwank/.cache/huggingface/diffusers/models--fusing--glide-base/snapshots/510aa20b54bbb8b77c170812dc0cbbbd06f58a6a/glide.py': No scheme supplied.
Perhaps you meant http:///home/diwank/.cache/huggingface/diffusers/models--fusing--glide-base/snapshots/510aa20b54bbb8b77c170812dc0cbbbd06f58a6a/glide.py?
```

Environment: 
- `python`: `3.10.5`
- `os`: `ubuntu22.04`
- `diffusers`: `0.0.4`

**Comment by creatorrr** [comment]
Installing from source `master@abedfb0` gives a different error:
`AttributeError: module 'diffusers' has no attribute 'GLIDE'`

**Comment by patrickvonplaten** [comment]
Hey @creatorrr,

I think you can now download all official available models: https://huggingface.co/models?library=diffusers

Could you maybe open a new issue if something doesn't work? 
Note that we don't have GLIDE added yet.
