### ISSUE TITLE
Memory Issues: Compvis/Stable-Diffusion works, diffusers does not 

### ISSUE THREAD

**Issue by PhilippeNguyen** [huggingface/diffusers#490]
### Describe the bug

Hi, I've been able to run the stable diffusion scripts from [https://github.com/CompVis/stable-diffusion](https://github.com/CompVis/stable-diffusion) perfectly fine.
However, the [basic text to image example given on the readme of the diffusers page ](https://github.com/huggingface/diffusers/blob/main/README.md#text-to-image-generation-with-stable-diffusion) does not work. I get a CUDA memory error along the lines of:
`RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 7.93 GiB total capacity; 6.29 GiB already allocated; 122.44 MiB free; 6.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

This occurs even when using fp16 and "enable_attention_slicing". These settings are supposed to reduce the memory footprint to ~4GB, but when I run it, it still reaches ~6GB before erroring 

### Reproduction

```
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4", 
    revision="fp16", 
    torch_dtype=torch.float16,
    use_auth_token=True
)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
pipe.enable_attention_slicing()
with autocast("cuda"):
    image = pipe(prompt).images[0]  
```

### System Info

- `diffusers` version: 0.3.0
- Platform: Linux-5.4.0-125-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.11
- PyTorch version (GPU?): 1.12.1+cu102 (True)
- Huggingface_hub version: 0.9.1
- Transformers version: 4.21.3
- Using GPU in script?: GTX 1070, 8GB RAM
- Using distributed or parallel set-up in script?: no

**Comment by anton-l** [comment]
@patrickvonplaten we might need a better test for peak VRAM consumption to verify this, wdyt?

**Comment by patrickvonplaten** [comment]
Hmm, I just verified again and the code above should definitely work with 8GB of RAM. 

@PhilippeNguyen could you try doing the following on your computer:

```
git clone https://github.com/huggingface/diffusers.git
cd diffusers
pip install -e ".[dev]"
```

and then run this test: 

```
RUN_SLOW=1 pytest -sv tests/test_pipelines.py::PipelineTesterMixin::test_stable_diffusion_memory_chunking 
```

As you can see here: https://github.com/huggingface/diffusers/blob/b56f102765707ce34c7016409a8b901942edb977/tests/test_pipelines.py#L1102

This test makes sure that VRAM is below 4GB. 

@PhilippeNguyen could you maybe try the following: Make sure GPU is not used by another process.

**Comment by PhilippeNguyen** [comment]
Thanks for the quick response, the tests worked and because of it I realized what the problem was. 
So despite what the code snippet above says, I was actually running model with use_auth_token=False, and pointing to the directory where I downloaded the model locally. Switching this to True and using the huggingface cache gets the model working with ~4GB VRAM usage (according to nvidia-smi).

So there is just something strange about loading with 'use_auth_token=False', but otherwise doesn't seem like a big issue.
Thanks again.

**Comment by patrickvonplaten** [comment]
@PhilippeNguyen note that you can also download the `fp16` weights locally:

```
git clone git lfs install
git clone https://huggingface.co/CompVis/stable-diffusion-v1-4 -b fp16
```

And then load the weights locally there with `torch_dtype=torch.float16`
