### ISSUE TITLE
Savetensors loading

### ISSUE THREAD

**Issue by Justinfungi** [huggingface/diffusers#4902]
```model_path = "Train/stable-diffusion/models/happi.safetensors"
torch_dtype = torch.float16
use_safetensors = True

pipe = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=torch_dtype, use_safetensors=use_safetensors)
pipe = pipe.to(device)```

i plan to load the savetensors in locally, but the from_pretrained is not support this type of load. is there any method i can load it?

**Comment by agcty** [comment]
If you are using SDXL you can use `.from_single_file()`. This just works for inference though, if you want to do something like dreambooth training I think you have to first convert the .safetensors file to the diffusers folder format as explained here: #4905

**Comment by sayakpaul** [comment]
Thanks for answering @agcty!

**Comment by Justinfungi** [comment]
Is there any way to convert the savetensor back to ckpt. i saw there is a gui version of this. but i wonder if there is an official version or not
