### ISSUE TITLE
Make GLIGEN modular

### ISSUE THREAD

**Issue by rchuzh99** [huggingface/diffusers#4904]
**Is your feature request related to a problem? Please describe.**
I have been experimenting with the [StableDiffusionGLIGENPipeline](https://github.com/huggingface/diffusers/blob/3105c710ba16fa2cf54d8deb158099a4146da511/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_gligen.py) and finding it effective so far. The current implementation tightly couples the SD and GLIGEN models into a single consolidated set of UNet weights, unlike the more modular T2I-adapter approach.

For future work, it could be beneficial to make the grounding networks more plug-and-play to enable adapting them into standard SD models in a more modular fashion.

**Describe the solution you'd like**

- [ ] Implement an adapter-style approach for the GLIGEN module (GSAD, PositionNet, FourierEmbedder) => Separate weights and module

**Comment by sayakpaul** [comment]
Thanks for bringing this up. We might have to strike the right balance here to ensure our API design stays consistent w.r.t the changes. 

I am ccing @nikhil-masterful and @tuanh123789, our amazing contributors who contributed the GLIGEN-related pipelines to carry forward the discussions here.

**Comment by rchuzh99** [comment]
@sayakpaul , thank you for the prompt reply and not to forget @nikhil-masterful and @tuanh123789 for your part in implementing the GLIGEN grounding module to the diffusers library.
