### ISSUE TITLE
How to convert pretrained SDXL .safetensors model to diffusers folder format

### ISSUE THREAD

**Issue by agcty** [huggingface/diffusers#4905]
As SDXL is gaining adoption, more and more community based models pop up that that are just saved as a .safetensors file. E.g the popular Realistic Vision: https://civitai.com/models/139562?modelVersionId=154590

When running train_dreambooth_lora_sdxl.py, the training script expects the diffusers folder format to accelerate text encoder, unet etc. As far as I know, there is no possible way to use `StableDiffusionXLPipeline.from_single_file()` to do the same.

Is there a way to convert a SDXL 1.0 fine-tuned .safetensors file to the diffusers folder format?

I found this but it doesn't seem to be applicable to SDXL scripts/convert_lora_safetensor_to_diffusers.py.

**Comment by alkollo** [comment]
Would be also interrested in a such script like convert_original_stable_diffusion_to_diffusers.py for 1.5/2 .

Hope a release soon,
Thank you for your works guy @Huggingface ^^

**Comment by agcty** [comment]
@patrickvonplaten wow that was much much easier than expected, thanks!
