### ISSUE TITLE
How to check whether the image is flagged as inappropriate automated?

### ISSUE THREAD

**Issue by sarmientoj24** [huggingface/diffusers#4906]
Is there a way to know whether the generated image (without seeing it) was flagged as inappropriate?

**Comment by patrickvonplaten** [comment]
I don't understand the question

**Comment by stevhliu** [comment]
Yeah, you'll get this message from the pipeline:

```
Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed.
```

**Comment by sayakpaul** [comment]
I think @stevhliu answers this question already. Closing it.
