### ISSUE TITLE
Combined pipeline's `from_pretrained` method: does it make sense to allow passing prior pipeline object? 

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#4908]
Should we enable the below API for combined pipelines? 

```python
pipe_prior = DiffusionPipeline.from_pretrained(custom_prior_checkpoint, ...)
pipe = AutoPipelineForText2Image.from_pretrained("kandinsky-community/kandinsky-2-2-decoder", prior_pipe = pipe_prior, ...)
```
currently, we will automatically load the connected pipeline as specified in the model card; This API would make it easier to use with a different checkpoint (e.g. fine-tuned) or a different prior pipeline class entirely (e.g. we have 2 prior pipeline classes for Kandinsky) 

On the other hand, we always have the option to create prior and decoder pipelines separately and chain them together, so this might be just over-engineering. 

Let me know what you think!
YiYi

**Comment by patrickvonplaten** [comment]
The following already works no:

```py
pipe_prior = DiffusionPipeline.from_pretrained(custom_prior_checkpoint, ...)
prior_components = {"prior_" + k: v for k,v in pipe_prior.items()}
pipe = AutoPipelineForText2Image.from_pretrained("kandinsky-community/kandinsky-2-2-decoder", **prior_components)
```
