### ISSUE TITLE
Script for converting SD weights from compvis to diffusers

### ISSUE THREAD

**Issue by Inkorak** [huggingface/diffusers#491]
It is desirable to have a script for converting SD weights from compvis to diffusers and vice versa. People are already finetuning models, but they do it on different bases. Examples: [for diffusers](https://huggingface.co/hakurei/waifu-diffusion), [for compvis](https://huggingface.co/naclbit/trinart_stable_diffusion_v2) 

Therefore, it would be nice to be able to convert them.

**Comment by patrickvonplaten** [comment]
Agree! It'd be nice to add such a script - we already have a CompVis->Diffusers one: https://github.com/huggingface/diffusers/blob/main/scripts/convert_ldm_original_checkpoint_to_diffusers.py but it'd be nice to clean this up a bit. Would be nice to add the other direction too.

**Comment by hysts** [comment]
I was thinking of opening an issue similar to this one. I successfully converted [this fine-tuned SD model](https://huggingface.co/naclbit/trinart_stable_diffusion) to diffusers some days ago, but spent quite some time trying to figure out how. I found and used [this conversion script](https://github.com/huggingface/diffusers/blob/ldm-txt2im-conv-script/scripts/convert_ldm_txt2img_original_checkpoint_to_diffusers.py), but I think the script is a bit outdated and I had to make some change after running it. What I did is described [here](https://huggingface.co/naclbit/trinart_stable_diffusion_v2/discussions/2#63209fa044a1fe6c92c91360). I guess at least [this line](https://github.com/huggingface/diffusers/blob/4dec014d4a82a073d8425e10bc779fb2fcb66866/scripts/convert_ldm_txt2img_original_checkpoint_to_diffusers.py#L598) needs to be updated, but I'm not sure if it would work with just that change. I hope this info helps anyone who wants to open a PR on this.

**Comment by patil-suraj** [comment]
Hey @hysts ! We just merged the new conversion script, you can find it here https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py

**Comment by hysts** [comment]
Cool! Thank you so much!

**Comment by FurkanGozukara** [comment]
how to run this script a single example please from a python app

**Comment by FurkanGozukara** [comment]
how to run this script a single example please from a python app
@patrickvonplaten @LysandreJik @anton-l @duongna21 

here my current app which script do i need to add


```
import torch
from diffusers import StableDiffusionPipeline
from torch import autocast

pipe = StableDiffusionPipeline.from_pretrained("lambdalabs/dreambooth-avatar", torch_dtype=torch.float16)  
pipe = pipe.to("cuda")

prompt = "photo of keanu reeves, avatarart style"
scale = 7.5
n_samples = 4

with autocast("cuda"):
  images = pipe(n_samples*[prompt], guidance_scale=scale).images

for idx, im in enumerate(images):
  im.save(f"{idx:06}.png")
```

**Comment by ysig** [comment]
> Agree! It'd be nice to add such a script - we already have a CompVis->Diffusers one: https://github.com/huggingface/diffusers/blob/main/scripts/convert_ldm_original_checkpoint_to_diffusers.py but it'd be nice to clean this up a bit. Would be nice to add the other direction too.

@patrickvonplaten This script simply doesn't work for the [original ldm](https://ommer-lab.com/files/latent-diffusion/text2img.zip) (and any ldm trained) model. For example in the script there is a [qkv splitting operation](https://github.com/huggingface/diffusers/blob/main/scripts/convert_ldm_original_checkpoint_to_diffusers.py#L200) on weight tensors but such weights are nowhere to be found in the original state_dict (attaching all key names)
[keys.txt](https://github.com/huggingface/diffusers/files/11141715/keys.txt)

Looking further I found [this](https://huggingface.co/CompVis/ldm-text2im-large-256/tree/refs%2Fpr%2F5/unet) which probably also explains the need for json input but there is no information of how to convert ldm weights to this bin format.

Can you please help?
Thanks :)

**Comment by FurkanGozukara** [comment]
> > Agree! It'd be nice to add such a script - we already have a CompVis->Diffusers one: https://github.com/huggingface/diffusers/blob/main/scripts/convert_ldm_original_checkpoint_to_diffusers.py but it'd be nice to clean this up a bit. Would be nice to add the other direction too.
> 
> @patrickvonplaten This script simply doesn't work for the [original ldm](https://ommer-lab.com/files/latent-diffusion/text2img.zip) (and any ldm trained) model. For example in the script there is a [qkv splitting operation](https://github.com/huggingface/diffusers/blob/main/scripts/convert_ldm_original_checkpoint_to_diffusers.py#L200) on weight tensors but such weights are nowhere to be found in the original state_dict (see [keys.txt](https://github.com/huggingface/diffusers/files/11141715/keys.txt))
> 
> Looking further I found [this](https://huggingface.co/CompVis/ldm-text2im-large-256/tree/refs%2Fpr%2F5/unet) which probably also explains the need for json vs yaml input but there is no information of how to convert ldm weights to this bin format.
> 
> Can you please help? Thanks :)

I made a video about this it works now

10.) Python Code - Hugging Face Diffusers Script - PC - Free
[**How to Run and Convert Stable Diffusion Diffusers (.bin Weights) & Dreambooth Models to CKPT File**](https://www.youtube.com/watch?v=-6CA18MS0pY)
[![image](https://user-images.githubusercontent.com/19240467/218344677-3f812cf3-db37-4ccb-8f81-99b8a1d5ef00.png)](https://www.youtube.com/watch?v=-6CA18MS0pY)

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara Thank you for your answer. However, my question is all about doing the inverse of what the video describes.

ok so you want to generate diffusers

just use dreambooth extension of web ui. make a training model. it will extract diffusers : https://youtu.be/pom3nQejaTs

**Comment by patrickvonplaten** [comment]
> generate

@FurkanGozukara, let's please stay on topic and try to not answer every issue with a video ;-) We would be very happy if the GitHub here could stay as "on-topic" and precise and possible and answer issues in text & PRs

**Comment by patrickvonplaten** [comment]
@ysig, could you make a google colab that shows that the conversion error doesn't work?

**Comment by ysig** [comment]
@patrickvonplaten [collab](https://colab.research.google.com/drive/1lnBzCWypcp9D0kEfxepwfaC896WEjnHM?usp=sharing)

**Comment by patrickvonplaten** [comment]
@ysig, I see those are latent diffusion weights no stable diffusion weights no? Sadly we don't have too much time to look into this model as it's a bit outdated

**Comment by eliahuhorwitz** [comment]
@ysig Did you get it working?

**Comment by ysig** [comment]
No, I ported all my code to the diffusers codebase which is really nice, and trained a model with it instead. However I think the diffusers team should support this conversion as it is basic.

**Comment by eliahuhorwitz** [comment]
> No, I ported all my code to the diffusers codebase which is really nice, and trained a model with it instead. However I think the diffusers team should support this conversion as it is basic.

Thanks
