### ISSUE TITLE
Error in loading custom text_encoder in  StableDiffusionPipeline.from_single_file

### ISSUE THREAD

**Issue by Garry435** [huggingface/diffusers#4911]
### Describe the bug

When i am doing 
pipe = diffusers.StableDiffusionPipeline.from_single_file(
    model_path,
    load_safety_checker=False,
    scheduler_type='dpm',
    text_encoder=text_encoder
 )
I am getting an error , this is weird because when I am specifying a text_encoder in from_pretrained() , it is not raising error , but when I do it in from_single_file it raises following error :
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1612             if name in modules:
   1613                 return modules[name]
-> 1614         raise AttributeError("'{}' object has no attribute '{}'".format(
   1615             type(self).__name__, name))
   1616 

AttributeError: 'ModuleList' object has no attribute '11'

### Reproduction

import diffusers
import transformers
import torch

model_path = "64094.safetensors"

text_encoder = transformers.CLIPTextModel.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    subfolder = "text_encoder",
    num_hidden_layers = 11,
)

pipe = diffusers.StableDiffusionPipeline.from_single_file(
    model_path,
    load_safety_checker=False,
    scheduler_type='dpm',
    text_encoder=text_encoder
 )

### Logs

```shell
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1612             if name in modules:
   1613                 return modules[name]
-> 1614         raise AttributeError("'{}' object has no attribute '{}'".format(
   1615             type(self).__name__, name))
   1616 

AttributeError: 'ModuleList' object has no attribute '11'
```

### System Info

- `diffusers` version: 0.20.2
- Platform: Linux-5.15.109+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (T4): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.33.0
- Accelerate version: 0.22.0
- xFormers version: 0.0.21

### Who can help?

@sayakpaul  @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Can you add a link to: model_path = "64094.safetensors"? I don't have this checkpoint saved locally

**Comment by Garry435** [comment]
Although it's a common error , which occurs on every civitai model , but to be specific I am using https://civitai.com/models/10028/neverending-dream-ned

**Comment by patrickvonplaten** [comment]
@DN6 can you check here?

**Comment by DN6** [comment]
Hi @Garry435. The issue seems to be due to a mismatch in the layers of the `CLIPTextModel` you're passing to `text-encoder` and the one present in the Civit checkpoint. 

Just so I understand your use case, are you trying to use the weights of the CLIP model in the Civit checkpoint or the one that you created using `from_pretrained`?

**Comment by Garry435** [comment]
i am tryna do `num_hidden_layers = 11` so i thought of using a different CLIPTextModel using `from_pretrained`  , the thing is when i do 
```
pipe = diffusers.StableDiffusionPipeline.from_single_file(model_path) 
pipe.save_pretrained('untitled')
```
then after this when i try to load the model from folder , the the code works and i can pass a custom text_encoder without any error

**Comment by DN6** [comment]
Hi @Garry435 Would you be able to share two complete code snippets with me. One where the model is not working as expected and one where the model does work?

**Comment by DN6** [comment]
You could also try the following snippet to set the text encoder to your custom one. 

```python
import diffusers
import transformers
import torch

model_path = "64094.safetensors"

text_encoder = transformers.CLIPTextModel.from_pretrained(
"runwayml/stable-diffusion-v1-5",
subfolder = "text_encoder",
num_hidden_layers = 11,
)

pipe = diffusers.StableDiffusionPipeline.from_single_file(
model_path,
load_safety_checker=False,
scheduler_type='dpm'
)
pipe.text_encoder = text_encoder
```

**Comment by Garry435** [comment]
Thanks for your help  that works good
