### ISSUE TITLE
Ability to convert custom CivitAI checkpoints of SDXL to diffusers 

### ISSUE THREAD

**Issue by MaxTran96** [huggingface/diffusers#4912]
**Is your feature request related to a problem? Please describe.**
https://github.com/TheLastBen/fast-stable-diffusion/issues/2528#issuecomment-1705740810

**Describe the solution you'd like**
convert custom civitai checkpoint of sdxl 1.0 to diffusers 

**Describe alternatives you've considered**
I tried using TheLastBen notebook to do so

**Additional context**

**Comment by adhikjoshi** [comment]
You can find it in scripts directory or they're here on huggingface

https://huggingface.co/stablediffusionapi

**Comment by apolinario** [comment]
Hey @MaxTran96 , this model has diffusers weights here https://huggingface.co/Lykon/dreamshaper-xl-1-0

**Comment by AmericanPresidentJimmyCarter** [comment]
Hey, @Birch-san has a script. https://github.com/waifu-diffusion/sdxl-ckpt-converter/

**Comment by MaxTran96** [comment]
Thank you all!
