### ISSUE TITLE
controlnet-openpose-sdxl-1.0

### ISSUE THREAD

**Issue by Yakonrus** [huggingface/diffusers#4913]
### Model/Pipeline/Scheduler description

Is this model coming?

https://huggingface.co/thibaud/controlnet-openpose-sdxl-1.0
There is such a model.

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by apolinario** [comment]
It should already work

**Comment by Yakonrus** [comment]
https://huggingface.co/thibaud/controlnet-openpose-sdxl-1.0
This model works
I asked about model from diffusers
Depth model and Canny models are here, but for some reason there is no such one, although for the SD 1.5 there are
