### ISSUE TITLE
StableDiffusionXLControlNetInpaintPipeline

### ISSUE THREAD

**Issue by Yakonrus** [huggingface/diffusers#4914]
### Model/Pipeline/Scheduler description

At the moment it is not possible to use ControlNet with standard models at SD XL inpaint pipeline.

StableDiffusionControlNetInpaintPipeline
Will there be an analogue for SD XL?
If yes, approximately when?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by sebi75** [comment]
What do you mean? You can use the base model with controlnets trained by diffusers team for sdxl.

**Comment by Yakonrus** [comment]
StableDiffusionControlNetXLInpaintPipeline
Pipeline for SDXL, not model
It is not exists

**Comment by sebi75** [comment]
> StableDiffusionXLControlNetInpaintPipeline Pipeline for SDXL, not model It is not exists

Oh, I see.
It was a PR for that, now it's merged in main branch, but I think it will be available via a new version at the next release.
You can still use it by referencing it in a requirements.txt like this:
requirements.txt
```
git+https://github.com/huggingface/diffusers.git@main
```

**Comment by sayakpaul** [comment]
https://github.com/huggingface/diffusers/issues/4914#issuecomment-1708197685 should solve this issue. Thanks!
