### ISSUE TITLE
Finetuning image-to-image StableDiffusionXLImg2ImgPipeline on a custom dataset

### ISSUE THREAD

**Issue by miquel-espinosa** [huggingface/diffusers#4915]
Hi,

Is there any example/tutorial/script for fine-tuning StableDiffusionXLImg2ImgPipeline?
It would really help to get up to speed with custom datasets.
Is there any current example or script that could be easily adapted for the purpose?

Thanks in advance,

**Comment by canberk17** [comment]
@miquel-espinosa  you can use the dreambooth [tutorial](https://huggingface.co/docs/diffusers/training/dreambooth) provided in the documents as example.

```
accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=400 \
  --push_to_hub
```

where `instance_data_dir` points at your data.

**Comment by sayakpaul** [comment]
There are multiple training examples that leverage SDXL:

* [DreamBooth](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_sdxl.md)
* [Vanilla text-to-image fine-tuning](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/README_sdxl.md) 
* [ControlNet](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/README_sdxl.md)
* [InstructPix2Pix](https://github.com/huggingface/diffusers/blob/main/examples/instruct_pix2pix/README_sdxl.md)
