### ISSUE TITLE
multi sd pipeline inference concurrently

### ISSUE THREAD

**Issue by LSC527** [huggingface/diffusers#4920]
Assume there are two different sd pipeline and two gpus. The thing I want is doing inference these two pipelines concurrently, each one on a separate gpu, and then doing something with the outcomes.
This is easy for simple nn.Module like torchvision.models:
```py
import torch
import torchvision

model0 = torchvision.models.resnet18().eval().to("cuda:0")
model1 = torchvision.models.resnet50().eval().to("cuda:1")

img0 = torch.randn(1, 3, 224, 224).to("cuda:0")
img1 = torch.randn(1, 3, 224, 224).to("cuda:1")

out0 = model0(img0)
out1 = model1(img1)
```
The forward functions of model0 and model1 are launch asynchronously because no synchronize exists between them.
However, sd pipeline.\_\_call\_\_ is something much more complex and cannot launch asynchronously.

**Comment by sayakpaul** [comment]
Have you looked into the following?

* https://huggingface.co/docs/diffusers/main/en/training/distributed_inference
* https://huggingface.co/docs/diffusers/main/en/api/pipelines/paradigms

**Comment by LSC527** [comment]
@sayakpaul Thx for sharing those inspiring docs.
BTW, I've implemented concurrent pipeline inference by unwraping the __call__ function and calling unet.forward of two pipelines togother. Massive code changes required although.
