### ISSUE TITLE
Will there be an android demo？

### ISSUE THREAD

**Issue by AndreaChiChengdu** [huggingface/diffusers#4922]
Very honored to experience the ios version of https://github.com/huggingface/swift-coreml-diffusers, could you tell me whether there will be an android version?
thanks very much！

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sayakpaul** [comment]
I don't think so. I would like to refer you to: https://farmaker47.medium.com/stable-diffusion-example-in-an-android-application-part-2-621b6c6ef590. 

Cc: @pcuenca
