### ISSUE TITLE
StableDiffusionSAGPipeline doesn't work with any Euler schedulers

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#4924]
so here's the bug:
lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py", line 732, in pred_x0
    alpha_prod_t = self.scheduler.alphas_cumprod[timestep]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

here's the code used to get there:
```
from diffusers import EulerDiscreteScheduler,StableDiffusionSAGPipeline

pipe=StableDiffusionSAGPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", torch_dtype=torch.float32,local_files_only=True,safety_checker=None, requires_safety_checker=False,
).to('cuda')

pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config)
kwargs=dict()
generator = torch.manual_seed(12121)
# kwargs['image']=image
# kwargs['mask_image']=mask_image
kwargs['generator']=generator
# kwargs['strength']=0.75
kwargs['num_inference_steps']=20
prompt="girl, 4k, beautiful day in the park"
fimage=pipe(prompt, **kwargs).images[0]
```

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu

**Comment by alexblattner** [comment]
@sayakpaul I fixed it.
here's what needs to be done:
replace lines 729-730 with:
```
newt=t.view(1)
# Noise it again to match the noise level
degraded_latents = self.scheduler.add_noise(degraded_latents, noise=eps, timesteps=t)
```

replace lines 737 with:
```
#conver timestep to int
numerical_value = int(timestep.tolist())
alpha_prod_t = self.scheduler.alphas_cumprod[numerical_value]
```

replace lines 757 with:
```
#conver timestep to int
numerical_value = int(timestep.tolist())
alpha_prod_t = self.scheduler.alphas_cumprod[numerical_value]
```

that will fix it and work like usual for all other cases.

**Comment by jweihe** [comment]
I tried the fix, unfortunately, it didn't work at all.

**Comment by alexblattner** [comment]
@jweihe you are correct, let me look into it

**Comment by jweihe** [comment]
@alexblattner have you solved it?

**Comment by alexblattner** [comment]
@jweihe not yet. It should take while though, sorry about that

**Comment by jweihe** [comment]
@alexblattner I tried to make the fix and added the following two pieces of code, but the results generated are not correct
`    def pred_euler_x0(self, sample, model_output, timestep):
        s_churn= 0.0
        s_noise=1.0
        s_tmin= 0.0
        s_tmax= float("inf")
        if isinstance(timestep, torch.Tensor):
            timestep = timestep.to(self.scheduler.timesteps.device)
        # print('self.scheduler.timesteps',self.scheduler.timesteps)
        # print('timestep',timestep)
        step_index = (self.scheduler.timesteps == timestep).nonzero().item()
        sigma = self.scheduler.sigmas[step_index]

        gamma = min(s_churn / (len(self.scheduler.sigmas) - 1), 2**0.5 - 1) if s_tmin <= sigma <= s_tmax else 0.0

        noise = randn_tensor(
            model_output.shape, dtype=model_output.dtype, device=model_output.device ,generator=None
        )

        eps = noise * s_noise
        sigma_hat = sigma * (gamma + 1)
        # print('gamma',gamma)
        if gamma > 0:
            sample = sample + eps * (sigma_hat**2 - sigma**2) ** 0.5
        # 1. compute predicted original sample (x_0) from sigma-scaled predicted noise
        # NOTE: "original_sample" should not be an expected prediction_type but is left in for
        # backwards compatibility
        # self.scheduler.config.prediction_type="original_sample"
        if self.scheduler.config.prediction_type == "original_sample" or self.scheduler.config.prediction_type == "sample":
            pred_original_sample = model_output
        elif self.scheduler.config.prediction_type == "epsilon":
            pred_original_sample = sample - sigma_hat * model_output
        elif self.scheduler.config.prediction_type == "v_prediction":
            # * c_out + input * c_skip
            pred_original_sample = model_output * (-sigma / (sigma**2 + 1) ** 0.5) + (sample / (sigma**2 + 1))
        else:
            raise ValueError(
                f"prediction_type given as {self.scheduler.config.prediction_type} must be one of `epsilon`, or `v_prediction`"
            )
        return pred_original_sample

    def pred_euler_epsilon(self, sample, model_output, timestep):
        s_churn= 0.0
        s_noise=1.0
        s_tmin= 0.0
        s_tmax= float("inf")
        if isinstance(timestep, torch.Tensor):
            timestep = timestep.to(self.scheduler.timesteps.device)

        step_index = (self.scheduler.timesteps == timestep).nonzero().item()
        sigma = self.scheduler.sigmas[step_index]

        gamma = min(s_churn / (len(self.scheduler.sigmas) - 1), 2**0.5 - 1) if s_tmin <= sigma <= s_tmax else 0.0

        noise = randn_tensor(
            model_output.shape, dtype=model_output.dtype, device=model_output.device ,generator=None
        )

        eps = noise * s_noise
        sigma_hat = sigma * (gamma + 1)

        if gamma > 0:
            sample = sample + eps * (sigma_hat**2 - sigma**2) ** 0.5
        # 1. compute predicted original sample (x_0) from sigma-scaled predicted noise
        # NOTE: "original_sample" should not be an expected prediction_type but is left in for
        # backwards compatibility
        # self.scheduler.config.prediction_type="original_sample"
        if self.scheduler.config.prediction_type == "original_sample" or self.scheduler.config.prediction_type == "sample":
            # pred_original_sample = model_output
            pred_eps=(sample - model_output) / sigma_hat
        elif self.scheduler.config.prediction_type == "epsilon":
            # pred_original_sample = sample - sigma_hat * model_output
            # pred_eps=(sample - model_output) / sigma_hat
            # pred_eps=sample - model_output/ sigma_hat
            pred_eps=model_output
            # pred_eps=(sample - model_output) / sigma_hat
        elif self.scheduler.config.prediction_type == "v_prediction":
            # * c_out + input * c_skip
            # pred_original_sample = model_output * (-sigma / (sigma**2 + 1) ** 0.5) + (sample / (sigma**2 + 1))
            pred_eps=model_output
        else:
            raise ValueError(
                f"prediction_type given as {self.scheduler.config.prediction_type} must be one of `epsilon`, or `v_prediction`"
            )
        return pred_eps`

**Comment by alexblattner** [comment]
@jweihe thanks for trying, I'll try looking into it in about 2 days. I'm just in the middle of something important in the last few days. I'll let you know how it goes ASAP

**Comment by alexblattner** [comment]
@jweihe I took a look at your code. Would you mind elaborating the significant changes you've made? You are adding code from the euler samplers directly here from what I can tell. Personally, I don't think the there should be special code just for eulers, but a slight alteration that also takes eulers into account

**Comment by jweihe** [comment]
The procedure necessitates the introduction of noise; however, it is imperative to identify the image x_0 and the predicted epsilon during this process. Consequently, I discern a requisite to refine these two components.

**Comment by jweihe** [comment]
@alexblattner   The procedure necessitates the introduction of noise; however, it is imperative to identify the image x_0 and the predicted epsilon during this process. Consequently, I discern a requisite to refine these two components.
