### ISSUE TITLE
Dreambooth doesn't return pytorch_model.bin

### ISSUE THREAD

**Issue by canberk17** [huggingface/diffusers#4932]
### Describe the bug

I successfully trained my DreamBooth model following the [tutorial](https://huggingface.co/docs/diffusers/training/dreambooth), and I pushed it to the [hub](https://huggingface.co/ckandemir/dog) with the validation images. 

However, when I call my model from the hub  using `pipeline = DiffusionPipeline.from_pretrained` ,  it is telling me there is no file named `pytorch_model.bin` but it used the same model to generate the validation images on the hub.

Here is my colab [link](https://colab.research.google.com/drive/1Aw0gOP_XYHTSTM9ai5oz771Nc0BvhyoY#scrollTo=51HNpiTtAbxm)

### Reproduction

from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("ckandemir/dog")

### Logs

```shell
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-14-973dd0a6a5fb> in <cell line: 3>()
      1 from diffusers import DiffusionPipeline
      2 
----> 3 pipeline = DiffusionPipeline.from_pretrained("ckandemir/dog")

2 frames
/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   2726                     )
   2727                 else:
-> 2728                     raise EnvironmentError(
   2729                         f"Error no file named {_add_variant(WEIGHTS_NAME, variant)}, {TF2_WEIGHTS_NAME},"
   2730                         f" {TF_WEIGHTS_NAME + '.index'} or {FLAX_WEIGHTS_NAME} found in directory"

OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /root/.cache/huggingface/hub/models--ckandemir--dog/snapshots/c0c87a008c458170f30e36b91fc9d6dac9cad3ca/text_encoder.
```

### System Info

- Platform: Linux-5.15.109+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Using GPU in script: Yes, NVIDIA-SMI 525.105.17 Driver Version: 525.105.17 CUDA Version: 12.0
- Using distributed or parallel set-up in script?: <>

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
You're not loading the checkpoints in the right way. Please follow the docs carefully: https://huggingface.co/docs/diffusers/main/en/training/lora.
