### ISSUE TITLE
Can "lora_layers = AttnProcsLayers(unet.attn_processors) " be used in "train_text_to_image_lora_sdxl.py"?

### ISSUE THREAD

**Issue by ZihaoW123** [huggingface/diffusers#4935]
### Describe the bug

For training the lora of SD-XL in "train_text_to_image_lora_sdxl.py", unet are prepared by "accelerator.prepare":
`unet, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(unet, optimizer, train_dataloader, lr_scheduler)`

However,  for SD-1.5/2.1 in "train_text_to_image_lora.py", lora_layers are prepared by "accelerator.prepare":
`lora_layers = AttnProcsLayers(unet.attn_processors)`
`lora_layers, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(lora_layers, optimizer, train_dataloader, lr_scheduler)`

Can SD-XL also use the function "AttnProcsLayers(unet.attn_processors)" to get the "lora_layers" of "unet" in "train_text_to_image_lora_sdxl.py" and reduce the usage of GPU graphics memory?
 

### Reproduction

None

### System Info

- `diffusers` version: 0.21.0.dev0
- Platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.32.1
- Accelerate version: 0.22.0
- xFormers version: 0.0.21
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

**Comment by sayakpaul** [comment]
Cc: @williamberman
