### ISSUE TITLE
Object Removal in the the new Inpainting SDXL model?

### ISSUE THREAD

**Issue by JohanHuynh0130** [huggingface/diffusers#4943]
Hi Everyone!

I just started using it and the results are great! However, it has one big issue: It’s hard to remove a big object out of the input. Let’s say I want to empty a room, instead, it will keep throwing random asterisks into the input.

Any ideas how to implement or setting the parameters to achieve this

**Comment by sayakpaul** [comment]
Please post these questions on our Discord forum or the Discussion forum as they are not directly related to our codebase and focus on usage examples.
