### ISSUE TITLE
StableDiffusionXLPipeline to natively support the TextualInversionLoaderMixin.

### ISSUE THREAD

**Issue by alkollo** [huggingface/diffusers#4950]
**Is your feature request related to a problem? Please describe.**
Yes, while working with the StableDiffusionXLPipeline, I found that it didn't natively support the TextualInversionLoaderMixin. As a result, I had to extend the class manually to incorporate this functionality, which isn't ideal for long-term usage and code cleanliness.

**Describe the solution you'd like**
I would like the TextualInversionLoaderMixin to be natively integrated into the StableDiffusionXLPipeline. By doing so, it would enable users to easily leverage the textual inversion capabilities without needing to extend classes or modify the existing pipeline.

Here's an example of how I extended the class:
```
# Define the new class
class ExtendedStableDiffusionXLPipeline(StableDiffusionXLPipeline, loaders.TextualInversionLoaderMixin):
    pass

pipeline = ExtendedStableDiffusionXLPipeline.from_single_file(
    "./sd_xl_base_1.0.safetensors", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)

# load textual inversion
REPO_DIR = Path(__file__).resolve().parent
neg = str(REPO_DIR / "embeddings/EasyNegative.safetensors")
pipeline.load_textual_inversion(neg)
```

**Describe alternatives you've considered**
An alternative would be to keep extending the class as I did, but this isn't scalable or user-friendly for those who might not be familiar with extending classes or the inner workings of the pipeline.

**Additional context**
Integrating this feature would streamline the process for users looking to leverage both the diffusion pipeline and textual inversion capabilities, making the library more versatile and user-friendly.

**Comment by patrickvonplaten** [comment]
I think it can be done natively since this PR - can you try this: https://github.com/huggingface/diffusers/pull/4903#issue-1881958969

**Comment by patrickvonplaten** [comment]
I should however add better docs for this usecase!

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/pull/5039
