### ISSUE TITLE
Textual Inversion _pickle.UnpicklingError

### ISSUE THREAD

**Issue by sam-motamed** [huggingface/diffusers#4954]
### Describe the bug

After training Textual Inversion, loading the model gives me a ``` _pickle.UnpicklingError: invalid load key, '`' ```

### Reproduction

```
pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to("cuda")
 text_inv_id = '/home/sam_motamed/diffusers/examples/textual_inversion/textual_inversion_model'
pipe.load_textual_inversion(text_inv_id)
```

### Logs

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam_motamed/.local/lib/python3.9/site-packages/diffusers/loaders.py", line 885, in load_textual_inversion
    state_dict = torch.load(model_file, map_location="cpu")
  File "/home/sam_motamed/.local/lib/python3.9/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/sam_motamed/.local/lib/python3.9/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '`'.
```

### System Info

- `diffusers` version: 0.21.0.dev0
- Platform: Linux-5.15.0-1040-gcp-x86_64-with-glibc2.31
- Python version: 3.9.5
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.33.1
- Accelerate version: 0.22.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@patrickvonplaten @sayakpaul @williamberman

**Comment by sayakpaul** [comment]
There is no reproducible code snippet.

**Comment by taehyeonEum** [comment]
Did you solve the error? I have same issue
