### ISSUE TITLE
Upgrade to Diffusers 0.17 and get CUDA OUT OF MEMORY 

### ISSUE THREAD

**Issue by Junsheng121** [huggingface/diffusers#4956]
Without any change when fine-tuning the sd pretrained model, but when I upgrade diffusers from 0.16 to 0.17, I got a CUDA OUT OF MEMORY. My device is a rtx3090.

**Comment by sayakpaul** [comment]
Upgrade to the latest version maybe? (0.21.0)

**Comment by Junsheng121** [comment]
Thanks a lot~
