### ISSUE TITLE
Run so slow

### ISSUE THREAD

**Issue by gaogao2002** [huggingface/diffusers#4958]
StableDiffusionPipeline.from_single_file（）
It is too slow to run this code(my model has been downloaded in my own device）.Are there some ways to address it？

**Comment by patrickvonplaten** [comment]
Reproducible code snippet please. Also the title could be a bit more descriptive please.

**Comment by knoopx** [comment]
from_single_file loads the original checkpoint and converts it into diffusers structure on-the-fly, that's why it's slower. Also use safetensors, they load way faster.

**Comment by alexblattner** [comment]
@patrickvonplaten please consider making diffusers less rigid. Why should there be a config file for every little thing?
