### ISSUE TITLE
train_instruct_pix2pix.py initialized Unet missing bias copy

### ISSUE THREAD

**Issue by ori-liberman** [huggingface/diffusers#4960]
on train_instruct_pix2pix.py, when using a modified UNet which is initialized from pre-trained checkpoints, on the update of the first convolution layer, the weights are copied but the bias is not. The bias values needs to be copied as well.
need to add the following line to the code below.
`        new_conv_in.bias.copy_(unet.conv_in.bias) 
`

   ```
 # InstructPix2Pix uses an additional image for conditioning. To accommodate that,
    # it uses 8 channels (instead of 4) in the first (conv) layer of the UNet. This UNet is
    # then fine-tuned on the custom InstructPix2Pix dataset. This modified UNet is initialized
    # from the pre-trained checkpoints. For the extra channels added to the first layer, they are
    # initialized to zero.
    logger.info("Initializing the InstructPix2Pix UNet from the pretrained UNet.")
    in_channels = 8
    out_channels = unet.conv_in.out_channels
    unet.register_to_config(in_channels=in_channels)

    with torch.no_grad():
        new_conv_in = nn.Conv2d(
            in_channels, out_channels, unet.conv_in.kernel_size, unet.conv_in.stride, unet.conv_in.padding
        )
        new_conv_in.weight.zero_()
        new_conv_in.weight[:, :4, :, :].copy_(unet.conv_in.weight)
        new_conv_in.bias.copy_(unet.conv_in.bias) # missing line
        unet.conv_in = new_conv_in
```

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
That's how it's done in the original codebase too but could be interesting:

https://github.com/timothybrooks/instruct-pix2pix/blob/0dffd1eeb02611c35088462d1df88714ce2b52f4/stable_diffusion/ldm/models/diffusion/ddpm_edit.py#L220

If observe better performance with the bias initialization, do feel free to send over a PR :)
