### ISSUE TITLE
Converting SDXL models to diffuser

### ISSUE THREAD

**Issue by JoaoMaio** [huggingface/diffusers#4964]
### Describe the bug

When trying to convert a SDXL to diffuser on Colab and it won't completely finish the process and always ends with ^C as you can see in the image: 

![image](https://github.com/huggingface/diffusers/assets/73291213/b6ccff2d-abe3-4b11-a5b9-749cdd77fc57)

I've tried with different SDXL models and all they don't work. With other models that don't use SDXL works at the first time. 

### Reproduction

python convert_original_stable_diffusion_to_diffusers.py \\ --checkpoint_path protovisionXLHighFidelity3D_beta0520Bakedvae.safetensors \\
--dump_path Proto \\
 --pipeline_class_name StableDiffusionXLPipeline \\
 --from_safetensors

### Logs

```shell
2023-09-10 20:26:00.002944: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Downloading (…)olve/main/vocab.json: 100% 961k/961k [00:00<00:00, 4.91MB/s]
Downloading (…)olve/main/merges.txt: 100% 525k/525k [00:00<00:00, 2.67MB/s]
Downloading (…)cial_tokens_map.json: 100% 389/389 [00:00<00:00, 2.40MB/s]
Downloading (…)okenizer_config.json: 100% 905/905 [00:00<00:00, 5.86MB/s]
Downloading (…)lve/main/config.json: 100% 4.52k/4.52k [00:00<00:00, 18.7MB/s]
^C
```

### System Info

Using Colab Free version

- `diffusers` version: 0.20.2
- Platform: Linux-5.15.109+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.33.1
- Accelerate version: 0.22.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@patrickvonplaten can you help me?

**Comment by patrickvonplaten** [comment]
Can you try to convert it as follows:

```py
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_single_file("<your-safetensors-file>")
pipe.save_pretrained("<your-diffusers-folder>")
```

**Comment by JoaoMaio** [comment]
Basically it crashes because  it tries to use more Ram than the Colab has, is there any option to limit or something similar?

**Comment by patrickvonplaten** [comment]
Yes, maybe just use fp16 precision:

```py
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_single_file("<your-safetensors-file>", torch_dtype=torch.float16)
pipe.save_pretrained("<your-diffusers-folder>", variant="fp16")
```

**Comment by JoaoMaio** [comment]
It still crashes, but I'm going to try it on my pc (32 Gb Ram) and then upload it to the Colab. Ty for your help
