### ISSUE TITLE
about   Import error?  diffusers   v0.20.1,   ImportError: cannot import name 'CrossAttention'  

### ISSUE THREAD

**Issue by zhanghongyong123456** [huggingface/diffusers#4969]
### Describe the bug

from diffusers.models.attention import CrossAttention, FeedForward, AdaLayerNorm
ImportError: cannot import name 'CrossAttention' from 'diffusers.models.attention'

### Reproduction

 from diffusers.models.attention import CrossAttention, FeedForward, AdaLayerNorm

### System Info

ubuntu  18.04    python 3.10.   diffusers   v0.20.1

**Comment by Dennis-Rall** [comment]
`CrossAttention` was renamed to `Attention` here https://github.com/huggingface/diffusers/commit/e828232780554d54bdb527d3390fab0be042b72a#diff-852d5806e41c100ee99c68c9e1059bfad9c0177e6f4416f0faf5a2f2a6a64067

**Comment by sayakpaul** [comment]
Cc: @DN6. 

Closing the issue with https://github.com/huggingface/diffusers/issues/4969#issuecomment-1713590616.

**Comment by Yuezhengrong** [comment]
> `CrossAttention` was renamed to `Attention` here [e828232#diff-852d5806e41c100ee99c68c9e1059bfad9c0177e6f4416f0faf5a2f2a6a64067](https://github.com/huggingface/diffusers/commit/e828232780554d54bdb527d3390fab0be042b72a#diff-852d5806e41c100ee99c68c9e1059bfad9c0177e6f4416f0faf5a2f2a6a64067)
> 
> so changing your import to `from diffusers.models.attention import Attention as CrossAttention, FeedForward, AdaLayerNorm` should make your code work again

thanks! it works!
