### ISSUE TITLE
tile_colorfix in diffusers

### ISSUE THREAD

**Issue by Laidawang** [huggingface/diffusers#4970]
for the tile controlnet, in sd-webui-controlnet. It supports [tile-colorfix and sharpness] (https://github.com/Mikubill/sd-webui-controlnet/pull/1434) to fix the color difference problem during tile model inference. How can we implement this in diffusers?

**Comment by fedeveloperi81** [comment]
and I also get problems with color and sharpness

**Comment by alexblattner** [comment]
bumping this

**Comment by moonsunstars39** [comment]
Any news?

**Comment by asomoza** [comment]
Could you please post a reproducible code where this happens in diffusers?. Giving us an auto1111 issue doesn't help that much. 

Also does this happen with SD 1.5 only or with SDXL too?
