### ISSUE TITLE
converting .safetensor model to diffusers

### ISSUE THREAD

**Issue by leebeet** [huggingface/diffusers#4974]
### Describe the bug

using the convert_original_stable_diffusion_to_diffusers.py to convert safetensor model to diffusers. but the script always end with this error:

Traceback (most recent call last):
  File "convert_original_stable_diffusion_to_diffusers.py", line 154, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected keyword argument 'checkpoint_path_or_dict'

Don't understand the resason, every thing is setup, the diffuser is installed.
Not sure if it's relative to the mac os version, my mac is runing the sonoma beta OS 14.0
and xcode 15 beta7.

Could you help with this~? thanx ahead

### Reproduction

1. using the convert_original_stable_diffusion_to_diffusers.py to convert safetensor model to diffusers.
2. terminal already cd to the folder which the model in.
3. "python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path sample.safetensors --from_safetensors --device cpu --extract_ema --dump_path sample_diffusers"
4. get the error: 
Traceback (most recent call last):
  File "convert_original_stable_diffusion_to_diffusers.py", line 154, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected keyword argument 'checkpoint_path_or_dict'

### System Info

python version: 3.8/3.11
diffuser version: 0.20
Mac OS: Sonoma beta OS 14.0
xcode 15 beta7.

### Who can help?

@patrickvonplaten

**Comment by leebeet** [comment]
i was totally followed the step from https://github.com/godly-devotion/MochiDiffusion/wiki/How-to-convert-Stable-Diffusion-models-to-Core-ML

**Comment by leebeet** [comment]
I just tried your suggestion, it works~. thanks so much! i was sticking into this problem a whole day!

**Comment by DarkAlchy** [comment]
@Garry435 How do we use that?  In the cmd window it doesn't work.

All I want to do is convert SDXL from a safetensor to a .bin only it seems impossible now YET the script to merge the TE1/2/Unet/Vae demands a .bin YET we are only given a .safetensor of each.

**Comment by kieranxsomer** [comment]
You guys do know Linaqurf has a conversion script working for the last month lol, https://colab.research.google.com/github/Linaqruf/sdxl-model-converter/blob/main/sdxl_model_converter.ipynb
it works entirely fine, and is running via SDScripts.

**Comment by willtejeda** [comment]
You just have to change the line 155 to checkpoint_path_or_dict in the convert_original_stable_diffusion_to_diffusers.py file 
![image](https://github.com/huggingface/diffusers/assets/49048735/1071e97e-2a3c-4d01-84cc-296b0f4a39e3)

**Comment by CHNtentes** [comment]
> You just have to change the line 155 to checkpoint_path_or_dict in the convert_original_stable_diffusion_to_diffusers.py file ![image](https://private-user-images.githubusercontent.com/49048735/287141389-1071e97e-2a3c-4d01-84cc-296b0f4a39e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDEwMDgsIm5iZiI6MTcwOTYwMDcwOCwicGF0aCI6Ii80OTA0ODczNS8yODcxNDEzODktMTA3MWU5N2UtMmEzYy00ZDAxLTg0Y2MtMjk2YjBmNGEzOWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAxMDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMzYxMTBhMTA4NmU2ZmM2OTM2MTIxZmFjNDM1YmJiNzFkODlkMWJiZTEyOTI3NTJkOTFlYTk3ZWIzZThiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OUt_2r8zaTLB6j5N8EhjXTpyg9aEudmImi8lcmPlSng)

I cloned new code, which is already the same as yours. However, I still get the same error as OP...

**Comment by duskfallcrew** [comment]
I have it working in a google colab, which is the same HF raw file in here, though I think Linaqruf's one was using KohyaSS. 

I use this script:
https://raw.githubusercontent.com/huggingface/diffusers/main/scripts/convert_original_stable_diffusion_to_diffusers.py

it's a dictionary issue, if it's useful maybe peek at my implimentation of it here:
def convert_dict(config):
https://github.com/duskfallcrew/sd15-to-diffusers
It's literally using the same Juypter/ Colab set up as Linaqruf's and i think the code is as follows;

(I pasted from the colab) - I don't program I just usually know how to patch so maybe this helps?

import os
import urllib.request
from urllib.parse import urlparse, unquote
from pathlib import Path



os.chdir(root_dir)
#@markdown ### **Conversion Config**
#@markdown Make sure you TICK SAFETENSORS or it won't convert.
#@markdown Dump path is where you would like your model to be stored before uploading.

checkpoint_path = "/models/modelname.safetensors" #@param {'type': 'string'}
dump_path = "/models/modelname" #@param {'type': 'string'}
from_safetensors = True  # @param {type: "boolean"}

def convert_dict(config):
    args = ""
    for k, v in config.items():
        if k.startswith("_"):
            args += f'"{v}" '
        elif isinstance(v, str):
            args += f'--{k}="{v}" '
        elif isinstance(v, bool) and v:
            args += f"--{k} "
        elif isinstance(v, float) and not isinstance(v, bool):
            args += f"--{k}={v} "
        elif isinstance(v, int) and not isinstance(v, bool):
            args += f"--{k}={v} "
    return args



def check_and_download_script(script_name, script_url):
    if not os.path.exists(script_name):
        print(f"{script_name} not found, downloading...")
        urllib.request.urlretrieve(script_url, script_name)

def run_script(script_name, script_args):
    !python {script_name} {script_args}


def main():
    script_name = "convert_original_stable_diffusion_to_diffusers.py"
    script_url = "https://raw.githubusercontent.com/huggingface/diffusers/main/scripts/convert_original_stable_diffusion_to_diffusers.py"
    check_and_download_script(script_name, script_url)

    config = {
        "checkpoint_path": checkpoint_path,
        "dump_path": dump_path,
        "from_safetensors": from_safetensors,

    }
    run_script(script_name, convert_dict(config))
    print(f"♻ Conversion Succesful, head to upload!")

main()

**Comment by ryanle-gamo** [comment]
> You guys do know Linaqurf has a conversion script working for the last month lol, https://colab.research.google.com/github/Linaqruf/sdxl-model-converter/blob/main/sdxl_model_converter.ipynb it works entirely fine, and is running via SDScripts.

Your solution fixed my problem. Thank you.

**Comment by ryanle-gamo** [comment]
> You just have to change the line 155 to checkpoint_path_or_dict in the convert_original_stable_diffusion_to_diffusers.py file ![image](https://github.com/huggingface/diffusers/assets/49048735/1071e97e-2a3c-4d01-84cc-296b0f4a39e3)

Your solution fixed my problem. Thank you.
