### ISSUE TITLE
`StableDiffusionPipeline`: Failure with OpenvinoEP using Onnxruntime

### ISSUE THREAD

**Issue by lalith-mcw** [huggingface/diffusers#4981]
### Describe the bug

Facing issues with `OpenvinoEP` with  `OnnxStableDiffusionPipeline.from_pretrained` function

### Reproduction

options = SessionOptions()
options.graph_optimization_level = GraphOptimizationLevel.ORT_DISABLE_ALL
onnxPipeline = OnnxStableDiffusionPipeline.from_pretrained(self.model, revision="onnx", provider="OpenVINOExecutionProvider", provider_options=[{'device_type' : 'CPU_FP32'}], sess_options = options)

### Logs

```shell
return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running OpenVINO-EP-subgraph_4 node. Name:'OpenVINOExecutionProvider_OpenVINO-EP-subgraph_4_0' Status Message: /home/onnxruntimedev/onnxruntime/onnxruntime/core/providers/openvino/ov_interface.cc:53 onnxruntime::openvino_ep::OVExeNetwork onnxruntime::openvino_ep::OVCore::LoadNetwork(const string&, std::string&, ov::AnyMap&, std::string) [OpenVINO-EP]  Exception while Loading Network for graph: OpenVINOExecutionProvider_OpenVINO-EP-subgraph_4_0Check 'false' failed at src/inference/src/core.cpp:149:
invalid external data: ExternalDataInfo(data_full_path: weights.pb, offset: 46080, data_length: 1280)
```

### System Info

Checking with an older version of diffusers `1.14.0`
python version `3.9`
onnxruntime-openvino `1.15.0`
onnxruntime `1.15.0`
openvino `2023.0`

### Who can help?

@patrickvonplaten, @sayakpaul, and @williamberman

**Comment by sayakpaul** [comment]
@echarlaix could you take a look here?

**Comment by echarlaix** [comment]
Hi @lalith-mcw, 



Instead of exporting your model to ONNX and perform inference with ONNX Runtime using the OpenVINO execution provider, you can export your model to the OpenVINO format and perform inference with OpenVINO Runtime directly using [`optimum`](https://huggingface.co/docs/optimum/main/en/intel/index).


To load a pytorch model and convert it to the OpenVINO format on-the-fly, you can set `export=True` when loading your model. More info in the documentation : https://huggingface.co/docs/optimum/main/en/intel/inference#stable-diffusion

```python
from optimum.intel import OVStableDiffusionPipeline

model_id = "runwayml/stable-diffusion-v1-5"
pipeline = OVStableDiffusionPipeline.from_pretrained(model_id, export=True)
image = pipeline("sailing ship in storm by Rembrandt").images[0]
```

**Comment by lalith-mcw** [comment]
@echarlaix it would be better if its `jit` conversion internally using the EP

I have the models downloaded from
https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/onnx

Trying to have a generic solutions with different execution provider support with `OnnxRT` using `onnx` models
