### ISSUE TITLE
Schedulers to have functions for converting between x0 and epsilon

### ISSUE THREAD

**Issue by ethansmith2000** [huggingface/diffusers#4983]
**Is your feature request related to a problem? Please describe.**
There are some things I have been messing with such as dynamic thresholding and other operations which are typically done to x0/pred_original_sample. There have been a number of different ways I've gone about this from patching scheduler classes to using functions externally, but the general case is that a well sized set of functions needs to be set up to cater to how each scheduler goes about the conversion.

fortunately most are pretty simple, and many can be repurposed for a few different schedulers.
```
def denoise_ddim(scheduler, timestep, sample, model_output):
    # 2. compute alphas, betas
    alpha_prod_t = scheduler.alphas_cumprod[timestep]
    beta_prod_t = 1 - alpha_prod_t
    pred_original_sample = (sample - beta_prod_t ** (0.5) * model_output) / alpha_prod_t ** (0.5)

    return pred_original_sample

def renoise_ddim(scheduler, timestep, sample, original_sample):
    # 2. compute alphas, betas
    alpha_prod_t = scheduler.alphas_cumprod[timestep]
    beta_prod_t = 1 - alpha_prod_t
    noise_pred = (sample - original_sample * alpha_prod_t ** 0.5) / beta_prod_t ** 0.5

    return noise_pred
    
 def denoise_euler_a(scheduler, timestep, sample, model_output):
    step_index = (scheduler.timesteps == timestep).nonzero().item()
    sigma = scheduler.sigmas[step_index]
    pred_original_sample = sample - sigma * model_output

    return pred_original_sample


def renoise_euler_a(scheduler, timestep, sample, original_sample):
    step_index = (scheduler.timesteps == timestep).nonzero().item()
    sigma = scheduler.sigmas[step_index]
    noise_pred = (sample - original_sample) / sigma

    return noise_pred
```
but it does get a bit more complicated for schedulers that add some additional noise in between steps when getting x0.

**Describe the solution you'd like**
It would be nice if schedulers had a denoise/renoise method that can be used by doing something like scheduler.denoise(), scheduler.renoise(), I think this may also be a good way to break down extensive step() methods into a few functions.

**Describe alternatives you've considered**
I noticed that when doing the .step() method, you can also get the pred_original_sample that way. For non-stateful schedulers this works just fine, but for those that update something internally this is not very practical.

**Comment by sayakpaul** [comment]
Cc @yiyixuxu and @patrickvonplaten here.

**Comment by patrickvonplaten** [comment]
Hmm I currently don't see how to put this design into `diffusers` - it doesn't really fit with our scheduler design. Can't you build such functions using e.g. the `DDIMScheduler`?

**Comment by ethansmith2000** [comment]
@patrickvonplaten for the most part I don't mind building it out as needed on my own, but noticing as its become more frequent i figured it may be useful for the broader community. I made a very rough example of what it may look like here, overall logic within scheduler would remain the same but the x0->epsilon and eps->x0 ca be a function of their own maybe.
https://github.com/huggingface/diffusers/compare/main...ethansmith2000:diffusers:main

**Comment by ethansmith2000** [comment]
for some context as to why this would be useful, the following tools all do operations to x0(pred_original_sample)
- Fooocus self guidance https://github.com/lllyasviel/Fooocus/discussions/117#sharpness
- dynamic thresholding https://github.com/mcmonkeyprojects/sd-dynamic-thresholding
- tonemapping https://github.com/comfyanonymous/ComfyUI_experiments/blob/master/sampler_tonemap.py
