### ISSUE TITLE
CLIPImageProjection not in _import_structure on '0.21.0.dev0'

### ISSUE THREAD

**Issue by MrDasix** [huggingface/diffusers#4993]
### Describe the bug

I'm having an error running the StableDiffusionGLIGENTextImagePipeline example. The error says that "module diffusers has no attribute CLIPImageProjection". That's probably because CLIPImageProjection is not added to the _import_structure dictionary on the __init__.py file.

### Reproduction

Try to run the example shown in [StableDiffusionGLIGENTextImagePipeline ](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/gligen#diffusers.StableDiffusionGLIGENTextImagePipeline)

### System Info

- `diffusers` version: 0.21.0.dev0
- Platform: Linux-5.4.0-113-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@patrickvonplaten, @sayakpaul, @williamberman

**Comment by patrickvonplaten** [comment]
@DN6 can you take a look here?

**Comment by patrickvonplaten** [comment]
Maybe related to: https://github.com/huggingface/diffusers/pull/4987 ?

**Comment by lyleguo** [comment]
the 'module diffusers has no attribute CLIPImageProjection' problem occurs again in the newest version

**Comment by sayakpaul** [comment]
Can you maybe open a new issue thread here?
