### ISSUE TITLE
`KDPM2DiscreteScheduler` and `KDPM2AncestralDiscreteScheduler` Missing `use_karras_sigmas` argument

### ISSUE THREAD

**Issue by CodeCorrupt** [huggingface/diffusers#5002]
### Describe the bug

Hey HF team, I'm trying to mimic the A1111 samplers using the table listed [in the docs](https://github.com/huggingface/diffusers/blob/main/docs/source/en/api/schedulers/overview.md)  but it seems the [`KDPM2DiscreteScheduler`](https://github.com/huggingface/diffusers/blob/0e0db625d0b7da2e6c27336845514b4460bd0000/src/diffusers/schedulers/scheduling_k_dpm_2_discrete.py#L71) and [`KDPM2AncestralDiscreteScheduler`](https://github.com/huggingface/diffusers/blob/0e0db625d0b7da2e6c27336845514b4460bd0000/src/diffusers/schedulers/scheduling_k_dpm_2_ancestral_discrete.py#L72) schedulers don't actually support the `use_karras_sigmas=True` argument. 

Please let me know if I'm just missing something :hugs: 

### Reproduction

```python
from diffusers import KDPM2DiscreteScheduler, KDPM2AncestralDiscreteScheduler

KDPM2DiscreteScheduler(**common_config, use_karras_sigmas=True)
KDPM2AncestralDiscreteScheduler(**common_config, use_karras_sigmas=True)
```

### Logs

```shell
[... Trimmed logs ...]
  File "/app/lib/models.py", line 41, in get_all_schedulers
    "DPM2 Karras": KDPM2DiscreteScheduler(**common_config, use_karras_sigmas=True),
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_karras_sigmas'
```

### System Info

- `diffusers` version: 0.20.2
- Platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: Yes - A6000
- Using distributed or parallel set-up in script?: No

### Who can help?

@patrickvonplaten and @williamberman

**Comment by patrickvonplaten** [comment]
@yiyixuxu can you give this a try?
