### ISSUE TITLE
SDXL dreambooth can't be resumed from a checkpoint at fp16 training

### ISSUE THREAD

**Issue by epi-morphism** [huggingface/diffusers#5004]
### Describe the bug

`train_dreambooth_lora_sdxl.py` can't be resumed from a checkpoint using fp16. The log error is `Attempting to unscale FP16 gradients.`

This is a big blocker from being able to train on the free colab tier since you need fp16 to fit in vram, but also need to resume from checkpoints since it can hit a timeout at any moment.

### Reproduction

Reproduce with: https://colab.research.google.com/drive/15woNcXcpsa3GDGk6cmDtIL2V8zRtOOj3

### System Info

latest diffusers, system is whatever is on colab (see linked colab above)

### Who can help?

@patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
Cc: @muellerzr @SunMarc

**Comment by danieltanhx** [comment]
temporary solution is to brute force into /usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py change line 284 from "optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)" to "optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, True)"

**Comment by SunMarc** [comment]
Hi @danieltanhx , indeed these is an issue with the optimizer where the gradient are somehow calculated in dtype `torch.float16` instead of `torch.float32` after resuming the training. We will work on fixing this asap cc @muellerzr .

**Comment by patrickvonplaten** [comment]
Let's wait for the next accelerate release here then

**Comment by epi-morphism** [comment]
> temporary solution is to brute force into /usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py change line 284 from "optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)" to "optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, True)"

Have confirmed that this silences the error and lets it continue from a checkpoint. However the end trained lora result doesn't look that good so I suspect something is still off, i.e. not quite a working solution. As patrick said I guess we'll wait until the next accelerate release.

**Comment by SunMarc** [comment]
After investigation, it seems like it is an issue on the diffusers side. 
When we resume the checkpoint, we load back the unet lora weights. It uses successively the following functions  `load_model_hook`, `load_lora_into_unet` and `load_attn_procs`. In `load_attn_procs`, the entire unet with lora weight will be converted to the the dtype of the unet. The problem is that in the script, we cast all non-trainable weigths to fp16 or bf16 for mixed precision training setup (vae, non-lora text_encoder and non-lora unet). 

```py
# For mixed precision training we cast all non-trainable weigths (vae, non-lora text_encoder and non-lora unet) to half-precision
# as these weights are only used for inference, keeping weights in full precision is not required.
weight_dtype = torch.float32
if accelerator.mixed_precision == "fp16":
    weight_dtype = torch.float16
elif accelerator.mixed_precision == "bf16":
    weight_dtype = torch.bfloat16

# Move unet, vae and text_encoder to device and cast to weight_dtype
unet.to(accelerator.device, dtype=weight_dtype)
```

So in the end, the lora layers end up being converted also in `load_attn_procs`. See code below or the [link](https://github.com/huggingface/diffusers/blob/78a78515d64736469742e5081337dbcf60482750/src/diffusers/loaders.py#L550) to the code source. 

```py 
# set lora layers
for target_module, lora_layer in lora_layers_list:
    target_module.set_lora_layer(lora_layer)
self.to(dtype=self.dtype, device=self.device)
```

To solve this issue, we can either modify `load_attn_procs` to set the lora_layers after this line 
`self.to(dtype=self.dtype, device=self.device)` or convert the lora_layers back to fp32  in the script. 
LMK what which option you prefer @patrickvonplaten , it will do a PR to fix that.

**Comment by patrickvonplaten** [comment]
It would be nice if we could convert the lora_layers back to fp32 to solve the issue. IMO the difference in precision between layers is a idiosyncrasy of the example scripts and should not influence how the load_attn_procs work for inference. 

It would be super nice to open a PR fixing it only in the examples scripts

**Comment by yuxu915** [comment]
@SunMarc @patrickvonplaten hi, really thanks for your investigation and solution.
But I still need more specific details on how to make the changes. 
Could you please provide step-by-step instructions or a code snippet to help me understand how to apply your solution?
Your assistance would be greatly appreciated.

**Comment by yuxu915** [comment]
@SunMarc @patrickvonplaten hi, really thanks for your investigation and solution.
I modify the code as: `unet.to(accelerator.device, dtype=torch.float32)` to fix the bug, however, when I check the validation results, it seems that training didn't start from the checkpoint I specified; instead, it started from the beginning.
could you help solving the problem? Thank you so much.

**Comment by yuxu915** [comment]
> > temporary solution is to brute force into /usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py change line 284 from "optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)" to "optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, True)"
> 
> Have confirmed that this silences the error and lets it continue from a checkpoint. However the end trained lora result doesn't look that good so I suspect something is still off, i.e. not quite a working solution. As patrick said I guess we'll wait until the next accelerate release.

hi, @epi-morphism , have you finally solved the problem? Would you like to share your solution?

**Comment by epi-morphism** [comment]
> > > temporary solution is to brute force into /usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py change line 284 from "optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)" to "optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, True)"
> > 
> > 
> > Have confirmed that this silences the error and lets it continue from a checkpoint. However the end trained lora result doesn't look that good so I suspect something is still off, i.e. not quite a working solution. As patrick said I guess we'll wait until the next accelerate release.
> 
> hi, @epi-morphism , have you finally solved the problem? Would you like to share your solution?

Nope, just waiting

**Comment by yuxu915** [comment]
> I modify the code as: `unet.to(accelerator.device, dtype=torch.float32)`

As mentioned above, I modify the code from `unet.to(accelerator.device, dtype=weight_dtype)` to  `unet.to(accelerator.device, dtype=torch.float32)` in `train_dreambooth_lora_sdxl.py` , the error is fixed, however, training seems start at very beginning rather than the designated checkpoint.

**Comment by SunMarc** [comment]
I was able to fix the prior version of the [file](https://gist.github.com/SunMarc/dd571c7b082abe963495d1a7bdc0c901), but the new commit of the example with the new lora layers returns another issue when using mixed_precision + resuming checkpoint. I will investigate more later. 
```
  File "/home/marc/anaconda3/envs/accelerate/lib/python3.11/site-packages/torch/cuda/amp/grad_scaler.py", line 372, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: No inf checks were recorded for this optimizer.
```

**Comment by patrickvonplaten** [comment]
cc @sayakpaul can you take a look here?

**Comment by sayakpaul** [comment]
@patrickvonplaten, Marc is investigating it. See https://github.com/huggingface/diffusers/issues/5004#issuecomment-1769571701

**Comment by sayakpaul** [comment]
Can you try using a numerically more calibrated VAE and see what happens? 

https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_sdxl.md#specifying-a-better-vae

**Comment by epi-morphism** [comment]
> Can you try using a numerically more calibrated VAE and see what happens?
> 
> https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_sdxl.md#specifying-a-better-vae

I was using the madebyollin vae fix (as in the colab) `madebyollin/sdxl-vae-fp16-fix`

**Comment by sayakpaul** [comment]
If you could open up a new issue thread with a fully reproducible snippet, that would be very helpful!

**Comment by epi-morphism** [comment]
> If you could open up a new issue thread with a fully reproducible snippet, that would be very helpful!

The colab linked at the top post is reproducible :) https://colab.research.google.com/drive/15woNcXcpsa3GDGk6cmDtIL2V8zRtOOj3

**Comment by sayakpaul** [comment]
So, I ran it yesterday actually for something else. Things seemed fine, hence asked.

**Comment by epi-morphism** [comment]
> So, I ran it yesterday actually for something else. Things seemed fine, hence asked.

I just re-ran the colab and made this one for the logs but I'm still getting the same errors as in the top so I'm not sure what's up with that :) https://colab.research.google.com/drive/1H9tRH7oUWnycYrw32M-nk1i6nFH8wgks Seems like the same error is still there in the latest diffusers i.e. `AssertionError: No inf checks were recorded for this optimizer.` when using `--resume_from_checkpoint` in fp16

**Comment by sayakpaul** [comment]
Hi @epi-morphism!

Indeed, the current LoRA SDXL training script is not rendering the subject image at all while it's training. See here as an example: https://wandb.ai/xin-sayak/dreambooth-lora-sd-xl/runs/axim7chx. I will investigate this further. 

You also mentioned ([comment](https://github.com/huggingface/diffusers/issues/5004#issuecomment-1777137352)):

> (And the same basic setup but not resuming and using the normal provided dreambooth training scripts, all things equal, tend to produce loras that work correctly.)

Does this mean you used a non-LoRA variant of the DreamBooth training script? I am guessing you used SD (and not SDXL) for that?

**Comment by epi-morphism** [comment]
> Does this mean you used a non-LoRA variant of the DreamBooth training script? I am guessing you used SD (and not SDXL) for that?

Nope I meant SDXL with basically the config in the colab above. I was getting successful loras as late as early this week with that (though the loras that were resumed from checkpointing looked broken). Not sure what the differences in our non resumed loras are but I somewhat suspect it's not related to this issue (i.e. not the same as resuming bugs) so potentially better suited for a different bug report. Perhaps we're just starting it different flags of some kind.

Here's the exact set of flags I was using for the lora worked (again, broken after resuming though)
```
!accelerate launch train_dreambooth_lora_sdxl.py \
  --output_dir="ckpts" \
  --instance_prompt="photo of sks" \
  --max_train_steps=6000 \
  --resolution=512 \
  --pretrained_vae_model_name_or_path "madebyollin/sdxl-vae-fp16-fix" \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --instance_data_dir="/content/images" --mixed_precision="fp16" --allow_tf32 \
  --train_batch_size=1 --gradient_accumulation_steps=4 \
  --gradient_checkpointing --learning_rate=3e-5 \
  --use_8bit_adam --checkpointing_steps=300 \
  --seed 72 --center_crop --rank 4 \
  --validation_prompt="photo of sks" \
  --validation_epochs=300 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0
```

But again I suspect it's an unrelated problem to this issue.

**Comment by sayakpaul** [comment]
https://gist.github.com/sayakpaul/0b5c13f2020ac5ee7a3547a0f8ccd781 -- you can check that even non-resumed runs lead to broken LoRAs. Corresponding run page: https://wandb.ai/xin-sayak/dreambooth-lora-sd-xl/runs/axim7chx.

**Comment by sayakpaul** [comment]
@epi-morphism 

Okay training is actually not broken. Turned out to be an LR thing.

Colab: https://colab.research.google.com/gist/sayakpaul/13864eb0427bef50f5e95f08b60a03a3/scratchpad.ipynb

WandB: https://wandb.ai/xin-sayak/dreambooth-lora-sd-xl/runs/qb1rc2pn?workspace=user-sayakpaul

I am training on PT 2.0 as well to see if it's working as expected. Will update here. 

But currently, I don't have any handle on why resuming the training from an FP16 checkpoint doesn't work as expected. Maybe if we could have exact same parameters (used initially) that could help prevent the bug? I will run this myself and see.

**Comment by sayakpaul** [comment]
Yup works with PT 2.0 as well: https://wandb.ai/xin-sayak/dreambooth-lora-sd-xl/runs/ketnbcdw.

**Comment by LWprogramming** [comment]
Hi, what are the colab notebooks intended to demonstrate? I just see that it looks like you get a training run going (the wandb logs are private in case you intended for there to be information there)

**Comment by unrue** [comment]
Ok,

from your Colab I get an out of memory:
```
`  File "/content/diffusers/examples/dreambooth/diffusers/src/diffusers/models/resnet.py", line 755, in forward
    output_tensor = (input_tensor + hidden_states) / self.output_scale_factor
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 598.81 MiB is free. Process 292077 has 14.16 GiB memory in use. Of the allocated memory 12.34 GiB is allocated by PyTorch, and 522.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0% 2/500 [04:59<20:42:14, 149.67s/it, loss=0.331, lr=0.0001]`
```

Trying in local, having a GPU V100 qith 32 gb of VRAM, I get out of memory too:

```
  File */image2image_env/diffusers/src/diffusers/models/attention_processor.py", line 743, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "*/image2image_env/diffusers/src/diffusers/models/attention_processor.py", line 598, in get_attention_scores
    attention_scores = torch.baddbmm(
RuntimeError: CUDA out of memory. Tried to allocate 1.25 GiB (GPU 0; 31.75 GiB total capacity; 27.43 GiB already allocated; 958.50 MiB free; 29.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I tried removing   --gradient_accumulation_steps=2  --gradient_checkpointing  and a lower resolution with no effect. How is that possible that 32 Gb of Vram are not enough? (Vram is available, i checked)

Other question, during training I see:

`Generating 4 images with prompt: A photo of sks dog in a bucket.`

Where such images are saved in order to display during training phase? I don't see any image saved.

**Comment by yuxu915** [comment]
hi, @sayakpaul @epi-morphism , another bug is that when resume training from a middle lora checkpoint, it stops update the model( i.e. checkpionts remain the same as the start one), have you ever meet this bug? really thanks.

**Comment by epi-morphism** [comment]
still an issue, not stale

**Comment by sayakpaul** [comment]
Have you tried this with the updated version of the script? Cc: @SunMarc

**Comment by epi-morphism** [comment]
> Have you tried this with the updated version of the script? Cc: @SunMarc

Tried the latest version just now. Can't say if or if it hasn't been fixed since it hits this error
```
ValueError: Query/Key/Value should either all have the same dtype, or (in the quantized case) Key/Value should have dtype torch.int32
  query.dtype: torch.float32
  key.dtype  : torch.float16
  value.dtype: torch.float16
```

Reproduce with colab at the top.

**Comment by epi-morphism** [comment]
> Have you tried this with the updated version of the script? Cc: @SunMarc

Ok I fixed the above (by not using memory efficient attention). The issue is the same as in the original post i.e.
```
ValueError: Attempting to unscale FP16 gradients.
```

So the issue is not stale, still a bug.
See exact logs and reproduce with this https://colab.research.google.com/drive/1hW5vWnhXjPyHAuq9p9LdhUcej7GFt6-u

**Comment by sayakpaul** [comment]
So, it's the training resume step where you're facing problems, yeah? Again, cc: @SunMarc.

**Comment by sayakpaul** [comment]
This needs to be solved first: https://github.com/huggingface/diffusers/issues/6510.

**Comment by nbardy** [comment]
Tracked this down to the norm layers.

Tracing the types they go from float16 -> float32

https://github.com/huggingface/diffusers/blob/dd63168319d4cd3c5f5951daaf2a37a26d2f9b73/src/diffusers/models/attention.py#L299-L317

https://github.com/huggingface/diffusers/blob/dd63168319d4cd3c5f5951daaf2a37a26d2f9b73/src/diffusers/models/attention.py#L350C13-L361

**Comment by sayakpaul** [comment]
Have been solved with: https://github.com/huggingface/diffusers/pull/6514. So, I am actually going to close this.
