### ISSUE TITLE
example training scripts end up truncating progress bar on resume

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#5005]
### Describe the bug

I noticed some discrepancies in the progress bar tracking, as it seemed like the numbers weren't adding up.

### Reproduction

The progress bar begins on a certain step already, with a limited range.

Later, we skip through steps, hoping to meet the resume step. We update the progress bar along the way.

It's not very consequential, but it's confusing. Am I misunderstanding the goal of this code snippet?

Seeing this code in the SDXL pix2pix trainer:

```py
    # Potentially load in the weights and states from a previous save
    if args.resume_from_checkpoint:
        if args.resume_from_checkpoint != "latest":
            path = os.path.basename(args.resume_from_checkpoint)
        else:
            # Get the most recent checkpoint
            dirs = os.listdir(args.output_dir)
            dirs = [d for d in dirs if d.startswith("checkpoint")]
            dirs = sorted(dirs, key=lambda x: int(x.split("-")[1]))
            path = dirs[-1] if len(dirs) > 0 else None

        if path is None:
            accelerator.print(
                f"Checkpoint '{args.resume_from_checkpoint}' does not exist. Starting a new training run."
            )
            args.resume_from_checkpoint = None
        else:
            accelerator.print(f"Resuming from checkpoint {path}")
            accelerator.load_state(os.path.join(args.output_dir, path))
            global_step = int(path.split("-")[1])

            resume_global_step = global_step * args.gradient_accumulation_steps
            first_epoch = global_step // num_update_steps_per_epoch
            resume_step = resume_global_step % (num_update_steps_per_epoch * args.gradient_accumulation_steps)

    # Only show the progress bar once on each machine.
    progress_bar = tqdm(range(global_step, args.max_train_steps), disable=not accelerator.is_local_main_process)
    progress_bar.set_description("Steps")

    for epoch in range(first_epoch, args.num_train_epochs):
        unet.train()
        train_loss = 0.0
        for step, batch in enumerate(train_dataloader):
            # Skip steps until we reach the resumed step
            if args.resume_from_checkpoint and epoch == first_epoch and step < resume_step:
                if step % args.gradient_accumulation_steps == 0:
                    progress_bar.update(1)
                continue
```

### System Info

N/A

### Who can help?

@sayakpaul

**Comment by bghira** [comment]
@sayakpaul it seems to me like having the progress bar unconditionally have its range from 0 to max steps would be awesome, and then just update the progress bar in the beginning to the global_step, and then, eliminate the whole nonsense about skipping steps before resume step has been reached, as it is purely unnecessary in pytorch/diffusers?

**Comment by sayakpaul** [comment]
> Later, we skip through steps, hoping to meet the resume step. We update the progress bar along the way.

That is what we follow for `diffusers` and `transformers` examples. We haven't received similar reports, though.

**Comment by bghira** [comment]
@sayakpaul it took an awful lot of debug statements to figure out. can we fix it?

**Comment by sayakpaul** [comment]
What needs fixing? I don't want to suddenly introduce something that has been there for quite a while especially if the behaviour is well expected.

**Comment by bghira** [comment]
the steps that the trainer plans before saving a first checkpoint are thrown away when it resumes. it does not complete the planned training session

**Comment by bghira** [comment]
so if you start a training session and it wants to do 1000 steps, then you save a ckpt at step 300, it will resume with a range for the progress bar from 300 to 1000. in other words position zero on the progress bar, is step 300.

but then we go through and resume during the training loop, pushing the progress bar along one tick for each fake optimization step.

there's no need to do this, just set the progress bar range correctly.
