### ISSUE TITLE
TryOnDiffusion: A Tale of Two UNets Implementation

### ISSUE THREAD

**Issue by kailashahirwar** [huggingface/diffusers#5008]
### Model/Pipeline/Scheduler description

Is there anyone working on the "TryOnDiffision: A Tale of Two UNets" implementation in diffusers? It looks like a promising approach for virtual try-on with groundbreaking results. We have been trying to implement it and we welcome contributions from the Hugging Face and diffusers community. 

https://tryondiffusion.github.io

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://tryondiffusion.github.io

**Comment by Guanbin-Huang** [comment]
i want to join to be a contributor, but my level is just intermediate, know stable diffusion, sde and diffusers api, how do i join?

**Comment by failbetter77** [comment]
I want to deeply understand about tryondiffusion... i have some questions bout tryondiffusion
but, I can ask about it anyone... can i join? 
for example ,,,  the input of tryondiffusion is "noised image,  clothing agnostic RGB".
The two image  are concated.  Is it similar to image to image method?
what is the size of unet input channel?

**Comment by takesukeDS** [comment]
I'm working on replicating their result using diffusers as a part of my thesis. 
The main concern is that their 4M dataset is not publicly available, and the total size of available datasets for vton is like 1/100 of theirs. (Even use of some datasets are limited to research purpose) Additionally, the resolutions vary accross the datasets.
As shown in their paper, the tryon result should be worse than that trained with 4M dataset.

@failbetter77 
kindly read their paper first

**Comment by failbetter77** [comment]
> I'm working on replicating their result using diffusers as a part of my thesis. The main concern is that their 4M dataset is not publicly available, and the total size of available datasets for vton is like 1/100 of theirs. (Even use of some datasets are limited to research purpose) Additionally, the resolutions vary accross the datasets. As shown in their paper, the tryon result should be worse than that trained with 4M dataset.
> 
> @failbetter77 kindly read their paper first

uhmm, I read the paper... i think i miss something, can you explain about my qeustion? 

and i think it's worth train tryondiffusion with viton, becuase at the end of the paper
they tested it with 10k  and i think it's not that bad...(?)


![image](https://github.com/huggingface/diffusers/assets/100422523/06b6e923-5c5c-47b1-a62e-85555c0bff93)

**Comment by failbetter77** [comment]
> I'm working on replicating their result using diffusers as a part of my thesis. The main concern is that their 4M dataset is not publicly available, and the total size of available datasets for vton is like 1/100 of theirs. (Even use of some datasets are limited to research purpose) Additionally, the resolutions vary accross the datasets. As shown in their paper, the tryon result should be worse than that trained with 4M dataset.
> 
> @failbetter77 kindly read their paper first

i think it's worth, because at the end of the paper the test with 10k.
it's not that bad.... (or is it bad? ) 
![image](https://github.com/huggingface/diffusers/assets/100422523/216f74cf-5f6e-4c16-bbfe-2b7c373665c6)

can you give me a hint? 
I'm really confused with the model input.  
two channel( noised image(128x128x3), clothing agnostic RGB(128x128x3)) are concatted, and do 3x3 convolution...
is it correct that the models' input is  128x128x6 ?

**Comment by takesukeDS** [comment]
> i think it's worth, because at the end of the paper the test with 10k. it's not that bad.... (or is it bad? ) ![image](https://user-images.githubusercontent.com/100422523/267871783-216f74cf-5f6e-4c16-bbfe-2b7c373665c6.png)
Probably (and apparently) good results still should be obtained. However, I'm not sure about their quality of tryon images.
Because with VITON-HD's unpaired test set, better FID was reported by HR-VITON (probably with different setting).
![hr-viton_FID](https://github.com/huggingface/diffusers/assets/114966174/ff6c5ea1-6da9-430f-a151-734fc78fc196)
Additionally, cherry-picking is often conducted in this research area. As you can see, the failure cases of HR-VITON presented in TryOnDiffusion's paper are not shown in HR-VITON's original paper.

> can you give me a hint? I'm really confused with the model input. two channel( noised image(128x128x3), clothing agnostic RGB(128x128x3)) are concatted, and do 3x3 convolution... is it correct that the models' input is 128x128x6 ?
I can not tell you somthing 100% correct. But I'm assuming so. Since particular implementation is not mentioned other than concatenation. My assumption comes probably from the discussion in  [FiLM article](https://distill.pub/2018/feature-wise-transformations/) and other image2image diffusion models like you mentioned. 

Does it help your situation a bit?

**Comment by kailashahirwar** [comment]
> > I'm working on replicating their result using diffusers as a part of my thesis. The main concern is that their 4M dataset is not publicly available, and the total size of available datasets for vton is like 1/100 of theirs. (Even use of some datasets are limited to research purpose) Additionally, the resolutions vary accross the datasets. As shown in their paper, the tryon result should be worse than that trained with 4M dataset.
> > @failbetter77 kindly read their paper first
> 
> i think it's worth, because at the end of the paper the test with 10k. it's not that bad.... (or is it bad? ) ![image](https://user-images.githubusercontent.com/100422523/267871783-216f74cf-5f6e-4c16-bbfe-2b7c373665c6.png)
> 
> can you give me a hint? I'm really confused with the model input. two channel( noised image(128x128x3), clothing agnostic RGB(128x128x3)) are concatted, and do 3x3 convolution... is it correct that the models' input is 128x128x6 ?

"The person-UNet (top) takes the clothing-agnostic RGB and the noisy image as input. Since both inputs are pixel-wise aligned, we directly concatenate them along the channel dimension at the beginning of UNet processing" - this is mentioned in the paper.

**Comment by kailashahirwar** [comment]
> Feel free to add this as a community pipeline.

Sure. We will add this as a community pipeline when ready with the implementation.

**Comment by Guanbin-Huang** [comment]
> > > I'm working on replicating their result using diffusers as a part of my thesis. The main concern is that their 4M dataset is not publicly available, and the total size of available datasets for vton is like 1/100 of theirs. (Even use of some datasets are limited to research purpose) Additionally, the resolutions vary accross the datasets. As shown in their paper, the tryon result should be worse than that trained with 4M dataset.
> > > @failbetter77 kindly read their paper first
> > 
> > 
> > i think it's worth, because at the end of the paper the test with 10k. it's not that bad.... (or is it bad? ) ![image](https://user-images.githubusercontent.com/100422523/267871783-216f74cf-5f6e-4c16-bbfe-2b7c373665c6.png)
> > can you give me a hint? I'm really confused with the model input. two channel( noised image(128x128x3), clothing agnostic RGB(128x128x3)) are concatted, and do 3x3 convolution... is it correct that the models' input is 128x128x6 ?
> 
> "The person-UNet (top) takes the clothing-agnostic RGB and the noisy image as input. Since both inputs are pixel-wise aligned, we directly concatenate them along the channel dimension at the beginning of UNet processing" - this is mentioned in the paper.

what GPUs do you use for reproduce? I have 3090ti x 8 not sure it is enough? if i can offer support on hard device, i can help.

**Comment by beniz** [comment]
FYI, we have a tryondiffusion inspired implementation in JoliGEN, the PR is still under review https://github.com/jolibrain/joliGEN/pull/530 but we have some results on other domains datasets.

You can easily test it from the doc included in the PR, but basically, it is a simple call like: 

```
python3 train.py --dataroot /path/to/data/viton_bbox_ref_mini --checkpoints_dir /path/to/checkpoints --name viton --config_json examples/example_ddpm_unetref_viton.json
```

We are using this for conditioning the diffusion with a reference image (as opposed to an aligned canny as in ControlNet). Reference image conditioning (for us) thus allows an unaligned component as input, that is aligned to the output by the secondary UNet.

Feel free to comment in the PR directly if related to joliGEN (to not pollute) here, and/or to get inspiration/reference for your implementation into diffusers. Good luck :)

**Comment by kailashahirwar** [comment]
> > > > I'm working on replicating their result using diffusers as a part of my thesis. The main concern is that their 4M dataset is not publicly available, and the total size of available datasets for vton is like 1/100 of theirs. (Even use of some datasets are limited to research purpose) Additionally, the resolutions vary accross the datasets. As shown in their paper, the tryon result should be worse than that trained with 4M dataset.
> > > > @failbetter77 kindly read their paper first
> > > 
> > > 
> > > i think it's worth, because at the end of the paper the test with 10k. it's not that bad.... (or is it bad? ) ![image](https://user-images.githubusercontent.com/100422523/267871783-216f74cf-5f6e-4c16-bbfe-2b7c373665c6.png)
> > > can you give me a hint? I'm really confused with the model input. two channel( noised image(128x128x3), clothing agnostic RGB(128x128x3)) are concatted, and do 3x3 convolution... is it correct that the models' input is 128x128x6 ?
> > 
> > 
> > "The person-UNet (top) takes the clothing-agnostic RGB and the noisy image as input. Since both inputs are pixel-wise aligned, we directly concatenate them along the channel dimension at the beginning of UNet processing" - this is mentioned in the paper.
> 
> what GPUs do you use for reproduce? I have 3090ti x 8 not sure it is enough? if i can offer support on hard device, i can help.

That's great. Let's put the resources to use once the implementation is ready.

**Comment by kailashahirwar** [comment]
If anyone wants to contribute, please join our Discord server at https://discord.gg/uSYQJCeS

Also, share your ideas and implementations here!

**Comment by 5thGenDev** [comment]
> If anyone wants to contribute, please join our Discord server at https://discord.gg/uSYQJCeS
> 
> Also, share your ideas and implementations here!

The link has been expired

**Comment by remigere** [comment]
Hi I'd like to contribute as well but can;'t join the link
I work in MLE

**Comment by 5thGenDev** [comment]
@remigere Look for beniz's comment about TryOnDiffusion inspired implementation in JoliGEN  https://github.com/jolibrain/joliGEN/pull/530

**Comment by kailashahirwar** [comment]
> > If anyone wants to contribute, please join our Discord server at https://discord.gg/uSYQJCeS
> > Also, share your ideas and implementations here!
> 
> The link has been expired

Try this link https://discord.gg/YQ2wJD7g

**Comment by rsamf** [comment]
@kailashahirwar Can you post a permanent link? I'd like to join as well.

**Comment by AnthonyDreams** [comment]
@kailashahirwar Expired invitation link :(

**Comment by tanayag** [comment]
> Feel free to add this as a community pipeline.

Hi @sayakpaul 
We have one implementation ready, https://github.com/kailashahirwar/tryondiffusion . We are working on procuring the dataset to train our parallel UNets to validate them. So we'll be starting with a small dataset. The problem is that the network is too big and we are in dire need of some GPU resources. It's an open-source project, and if Hugging Face could provide support wrt GPUs, that'd be awesome. 

For now, we want to validate if the concept of Parallel-Unet works, and we can start that by training just 128x128 parallel UNet, instead of all three networks.

**Comment by vade** [comment]
Out of curiosity - what sort of GPU resources do you need @tanayag ?

**Comment by Shashank-jais** [comment]
Can Someone help me in running this project to test on some images
