### ISSUE TITLE
LoRA can not train text encoder in "train_text_to_image_lora_sdxl.py"?

### ISSUE THREAD

**Issue by Kevin7720** [huggingface/diffusers#5012]
### Describe the bug

`train_text_to_image_lora.py`  "`--train_text_encoder`" is work, but `train_text_to_image_lora_sdxl.py`  "`--train_text_encoder`" is not work.

### Reproduction

accelerate launch train_dreambooth_lora_sdxl.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" --pretrained_vae_model_name_or_path="stabilityai/sdxl-vae" --output_dir="traintextencorder" --resolution=512 --train_batch_size=2 --gradient_accumulation_steps=1 --learning_rate=1e-5 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=3000  --instance_data_dir="dog" --instance_prompt="A photo of a sks dog." --train_text_encoder

### Logs

```shell
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 88 89 90 91 92 93 94 95
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
```

### System Info

- `diffusers` version: 0.21.0.dev0
- Platform: Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.14.0a0+44dac51 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.33.1
- Accelerate version: 0.22.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@williamberman, @patrickvonplaten, and @sayakpaul

**Comment by sayakpaul** [comment]
Are you launching this from a machine having multiple GPUs?

**Comment by Kevin7720** [comment]
@sayakpaul yes, I am.

**Comment by Kevin7720** [comment]
I had 4 GPUs.
![image](https://github.com/huggingface/diffusers/assets/50312749/85a70f2d-2dd0-4067-b959-a72e67dac5bd)
This is my accelerate config setting.
![image](https://github.com/huggingface/diffusers/assets/50312749/6a497372-2c09-4728-87ec-f82cca47e845)

**Comment by sayakpaul** [comment]
Yeah I remember there was a similar issue reported a while back. I think the limitation is to only use a machine with a single GPU for now.

**Comment by Kevin7720** [comment]
Thank you for your help, it is working.

**Comment by sayakpaul** [comment]
Closing then.

**Comment by leyangjin** [comment]
Is this issue sovled now? I am still encountered with the same issue when I use train_text_to_image_lora_sdxl.py with 4 GPUs.
<img width="1166" alt="image" src="https://github.com/huggingface/diffusers/assets/82919244/4da4629d-bef2-499d-9ba4-9c11f0d2b50e">

**Comment by sayakpaul** [comment]
Does this help?

https://github.com/huggingface/diffusers/pull/5355

**Comment by Kevin7720** [comment]
> Yeah I remember there was a similar issue reported a while back. I think the limitation is to only use a machine with a single GPU for now.


On single GPU is working. You can try it.

> @sayakpaul Hi, is this issue sovled now? I am still encountered with the same issue when I use train_text_to_image_lora_sdxl.py with 4 GPUs. <img alt="image" width="1166" src="https://user-images.githubusercontent.com/82919244/280897661-4da4629d-bef2-499d-9ba4-9c11f0d2b50e.png">

**Comment by leyangjin** [comment]
> Does this help?
> 
> #5355

Hi @sayakpaul, thank you for your help!. Acutally The version of train_text_to_image_lora_sdxl.py has adapted the changes in this PR. However, the problem still exists.

**Comment by leyangjin** [comment]
> > Yeah I remember there was a similar issue reported a while back. I think the limitation is to only use a machine with a single GPU for now.
> 
> On single GPU is working. You can try it.
> 
> > @sayakpaul Hi, is this issue sovled now? I am still encountered with the same issue when I use train_text_to_image_lora_sdxl.py with 4 GPUs. <img alt="image" width="1166" src="https://user-images.githubusercontent.com/82919244/280897661-4da4629d-bef2-499d-9ba4-9c11f0d2b50e.png">

Hi, thank you for your help! Sorry that since my dataset size is quite large, I may have to use multiple GPUs

**Comment by sayakpaul** [comment]
Then I am not sure what could be the problem here.

**Comment by leyangjin** [comment]
@patrickvonplaten Hi, could you please help me with this? I think the bug has been here for several months. Thank you!

**Comment by sayakpaul** [comment]
@leyangjin could you try out some suggestions from [this thread](https://github.com/huggingface/diffusers/issues/4046) too? 

Sorry for being a bit haphazard here.
