### ISSUE TITLE
Importing UNet2DModel from diffusers in version 0.21.0 causes error name 'PreTrainedTokenizer' is not defined

### ISSUE THREAD

**Issue by RandomGamingDev** [huggingface/diffusers#5022]
### Describe the bug

When running the line:
```py
from diffusers import UNet2DModel
```
the error
`name 'PreTrainedTokenizer' is not defined`
is thrown, but only in the current latest version v0.21.0 and not version v0.20.2 before that

I thought that it could've been an API change, but it doesn't look that much like one and it appears that some of the docs on huggingface haven't updated to match this considering that https://huggingface.co/docs/diffusers/tutorials/basic_training no longer functions without erroring out on the 
```py
from diffusers import UNet2DMode
```
part.

### Reproduction

```py
from diffusers import UNet2DMode
```
https://huggingface.co/docs/diffusers/tutorials/basic_training
(the google colab isn't working)

### Logs

```shell
NameError                                 Traceback (most recent call last)

/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py in _get_module(self, module_name)
    683         try:
--> 684             return importlib.import_module("." + module_name, self.__name__)
    685         except Exception as e:

18 frames

NameError: name 'PreTrainedTokenizer' is not defined


The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)

/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py in _get_module(self, module_name)
    684             return importlib.import_module("." + module_name, self.__name__)
    685         except Exception as e:
--> 686             raise RuntimeError(
    687                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
    688                 f" traceback):\n{e}"

RuntimeError: Failed to import diffusers.models.unet_2d because of the following error (look up to see its traceback):
name 'PreTrainedTokenizer' is not defined
```
```


### System Info

v0.21.0 only, Google Colab, Python version Python 3.10.12

### Who can help?

_No response_

**Comment by DN6** [comment]
Hi @RandomGamingDev Could you try installing `transformers` with `pip install transformers` and rerunning your code?

**Comment by patrickvonplaten** [comment]
Hmm even without `transformers` this should give a better error message - checking!

**Comment by patrickvonplaten** [comment]
Should we solved here: https://github.com/huggingface/diffusers/pull/5035

@DN6 note that `UNet2DModel` is a model that is not conditioned on text which means that there is no reason really to force someone that imports a unconditional `UNet2DModel` to have transformers installed
