### ISSUE TITLE
AttributeError: 'AutoencoderTinyOutput' object has no attribute 'latent_dist'

### ISSUE THREAD

**Issue by yanchaoguo** [huggingface/diffusers#5029]
### Describe the bug

AttributeError                            Traceback (most recent call last)
Cell In[2], line 3
      1 seed = torch.manual_seed(10240)
      2 pipe.vae = AutoencoderTiny.from_pretrained("madebyollin/taesdxl", torch_dtype=torch.float16, local_files_only=True).to("cuda")
----> 3 result_img = pipe(ref_image=style_image,
      4       prompt="1girl",
      5       generator = seed,
      6       num_inference_steps=20,
      7       reference_attn=True,
      8       reference_adain=True).images[0]
      9 result_img

File /usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_xl_reference.py:316, in StableDiffusionXLReferencePipeline.__call__(self, prompt, prompt_2, ref_image, height, width, num_inference_steps, denoising_end, guidance_scale, negative_prompt, negative_prompt_2, num_images_per_prompt, eta, generator, latents, prompt_embeds, negative_prompt_embeds, pooled_prompt_embeds, negative_pooled_prompt_embeds, output_type, return_dict, callback, callback_steps, cross_attention_kwargs, guidance_rescale, original_size, crops_coords_top_left, target_size, attention_auto_machine_weight, gn_auto_machine_weight, style_fidelity, reference_attn, reference_adain)
    305 latents = self.prepare_latents(
    306     batch_size * num_images_per_prompt,
    307     num_channels_latents,
   (...)
    313     latents,
    314 )
    315 # 7. Prepare reference latent variables
--> 316 ref_image_latents = self.prepare_ref_latents(
    317     ref_image,
    318     batch_size * num_images_per_prompt,
    319     prompt_embeds.dtype,
    320     device,
    321     generator,
    322     do_classifier_free_guidance,
    323 )
    325 # 8. Prepare extra step kwargs. TODO: Logic should ideally just be moved out of the pipeline
    326 extra_step_kwargs = self.prepare_extra_step_kwargs(generator, eta)

File ~/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_xl_reference.py:169, in StableDiffusionXLReferencePipeline.prepare_ref_latents(self, refimage, batch_size, dtype, device, generator, do_classifier_free_guidance)
    167     ref_image_latents = torch.cat(ref_image_latents, dim=0)
    168 else:
--> 169     ref_image_latents = self.vae.encode(refimage).latent_dist.sample(generator=generator)
    170 ref_image_latents = self.vae.config.scaling_factor * ref_image_latents
    172 # duplicate mask and ref_image_latents for each generation per prompt, using mps friendly method

AttributeError: 'AutoencoderTinyOutput' object has no attribute 'latent_dist'

### Reproduction

pipe = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    custom_pipeline="stable_diffusion_xl_reference",
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16", safety_checker=None, local_files_only=True,
).to('cuda:0')
pipe.vae = AutoencoderTiny.from_pretrained("madebyollin/taesdxl", torch_dtype=torch.float16, local_files_only=True).to("cuda")
result_img = pipe(ref_image=style_image,
      prompt="1girl",
      generator = seed,
      num_inference_steps=20,
      reference_attn=True,
      reference_adain=True).images[0]
result_img

### System Info

- `diffusers` version: 0.21.0
- Platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.33.1
- Accelerate version: 0.21.0
- xFormers version: 0.0.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by sayakpaul** [comment]
Could you provide a Colab Notebook reproducing this error?

**Comment by yanchaoguo** [comment]
> Could you provide a Colab Notebook reproducing this error?

I am in china, please reference coding from  Reproduction

**Comment by sayakpaul** [comment]
Now I see. You are using a custom pipeline in your code and we don't maintain the community pipelines. I am going to have to ask you to tag the author of the pipeline here.
