### ISSUE TITLE
How to unfuse_lora only the first one after I have added multiple lora?

### ISSUE THREAD

**Issue by yanchaoguo** [huggingface/diffusers#5032]
base.load_lora_weights("models/safetensors/SDXL/国风插画SDXL.safetensors") 
base.fuse_lora(lora_scale=.7)
base.load_lora_weights("models/safetensors/SDXL/sd_xl_offset_example-lora_1.0.safetensors")
base.fuse_lora(lora_scale=.8)
Now, When I execute unfuse_lora() only the most recent one has been unfuse .

so,how to unfuse '国风插画SDXL.safetensors'  or unfuse all lora weights

**Comment by patrickvonplaten** [comment]
Good question! This is currently not possible sadly :sweat_smile: 

As soon as you've fused two LoRAs you can sadly not go back anymore and will have to reload the full original model weights. 

It's a TODO!

cc @apolinario @sayakpaul

**Comment by alexblattner** [comment]
@patrickvonplaten I highly recommend getting inspiration from this: https://gist.github.com/takuma104/e38d683d72b1e448b8d9b3835f7cfa44#gistcomment-4666052

it's better than what is currently implemented in diffusers except it has no lycoris support

**Comment by yanchaoguo** [comment]
> @patrickvonplaten I highly recommend getting inspiration from this: https://gist.github.com/takuma104/e38d683d72b1e448b8d9b3835f7cfa44#gistcomment-4666052
> 
> it's better than what is currently implemented in diffusers except it has no lycoris support

It isn’t suppored SDXL

**Comment by Damarcreative** [comment]
I tried using stable diffusion 1.5 I got the output:

```
if Use_LoRA_add_detail:
  pipe.load_lora_weights(".", weight_name="/content/model/lora/add_detail.safetensors")
  pipe.fuse_lora()

if Use_LoRA_Kimono:
  pipe.load_lora_weights(".", weight_name="/content/model/lora/kimono.safetensors")
  pipe.fuse_lora()

if Use_LoRA_Graffiti_Poster_Comic_Style:
  pipe.load_lora_weights(".", weight_name="/content/model/lora/mjty-000016.safetensors")
  pipe.fuse_lora()
```

```
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
bfa0f2|OK  |    12MiB/s|/content/model/lora/add_detail.safetensors

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
e1f247|OK  |    18MiB/s|/content/model/lora/kimono.safetensors

Status Legend:
(OK):download completed.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
66da65|OK  |    28MiB/s|/content/model/lora/mjty-000016.safetensors

Status Legend:
(OK):download completed.
The current API is supported for operating with a single LoRA file. You are trying to load and fuse more than one LoRA which is not well-supported.
The current API is supported for operating with a single LoRA file. You are trying to load and fuse more than one LoRA which is not well-supported.
```
