### ISSUE TITLE
change config in LoRA changing

### ISSUE THREAD

**Issue by sunhaozhepy** [huggingface/diffusers#5050]
**Is your feature request related to a problem? Please describe.**
When training a LoRA, sometimes I get the impression that the LoRA model didn't fully capture the characteristics of the training set. I suspect this is related to underfitting in DL. I wonder whether changing the model configuration, e.g. increasing the number of parameters of the LoRA model, would mitigate this issue.

**Describe the solution you'd like**
I see that a LoRA of Stable Diffusion is always about 2.3M and that of Stable Diffusion XL, 23M. I would like to know whether there is an API (for example an argument that I can pass to the training script) for me to change this, or otherwise I would be glad if the Diffusers groups could add this feature.

**Comment by isidentical** [comment]
You can customize the rank which adds more information for the cost of higher lora size, for us 128 to 256 is ideal!

**Comment by sunhaozhepy** [comment]
Ah yes I see, that's great! Thanks for your reply.
