### ISSUE TITLE
How to download config.json if it is not in the root directory.

### ISSUE THREAD

**Issue by suzukimain** [huggingface/diffusers#5055]
Is there any way to download vae for a model where config.json is not in the root directory?

```python
vae = AutoencoderKL.from_pretrained("redstonehero/kl-f8-anime2")
``` 

For example, as shown above, there is no problem if config.json exists in the root directory, but if it does not exist, an error will occur.

```python
vae = AutoencoderKL.from_pretrained("hakurei/waifu-diffusion")
``` 
I would be glad to get your advice.

**Comment by shauray8** [comment]
Hi, @suzukimain you can use `subfolder="vae"`. I would recommend you take advantage of the forum as these questions are better answered in the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63).

**Comment by suzukimain** [comment]
Resolved. Thanks for the advice.
