### ISSUE TITLE
Finetune Stable Diffusion XL on multiple concepts

### ISSUE THREAD

**Issue by Maximilianwte** [huggingface/diffusers#5059]
Hey,

I was looking into the LoRA training script for Stable diffusion XL. Would it be possible in the future to add support of being able to provide prompts for the training images from the name of the image or separate text file (similar to training in stable diffusion like here: 

    parser.add_argument(
        "--read_prompts_from_txts",
        action="store_true",
        help="Use prompt per image. Put prompts in the same directory as images, e.g. for image.png create image.png.txt.",
    )

in https://raw.githubusercontent.com/ShivamShrirao/diffusers/main/examples/dreambooth/train_dreambooth.py  

Thank you for your help.

**Comment by bghira** [comment]
it would be more than a trivial change.

currently, LoRA training only ever expects an instance prompt, and it computes a single text embedding that it uses, unless the text encoder is training:

```py
                if not args.train_text_encoder:
                    unet_added_conditions = {
                        "time_ids": add_time_ids.repeat(elems_to_repeat, 1),
                        "text_embeds": unet_add_text_embeds.repeat(elems_to_repeat, 1),
                    }
                    prompt_embeds_input = prompt_embeds.repeat(elems_to_repeat, 1, 1)
                    model_pred = unet(
                        noisy_model_input,
                        timesteps,
                        prompt_embeds_input,
                        added_cond_kwargs=unet_added_conditions,
                    ).sample
                else:
                    unet_added_conditions = {"time_ids": add_time_ids.repeat(elems_to_repeat, 1)}
                    prompt_embeds, pooled_prompt_embeds = encode_prompt(
                        text_encoders=[text_encoder_one, text_encoder_two],
                        tokenizers=None,
                        prompt=None,
                        text_input_ids_list=[tokens_one, tokens_two],
                    )
                    unet_added_conditions.update({"text_embeds": pooled_prompt_embeds.repeat(elems_to_repeat, 1)})
                    prompt_embeds_input = prompt_embeds.repeat(elems_to_repeat, 1, 1)
                    model_pred = unet(
                        noisy_model_input, timesteps, prompt_embeds_input, added_cond_kwargs=unet_added_conditions
                    ).sample
```

**Comment by Maximilianwte** [comment]
Ah I see, thanks a lot for the clarification. Is there any way possible to train multiple concepts into one stable diffusion xl instance (e.g. training a lora from a lora checkpoint, that is already trained with a different concept)?

**Comment by bghira** [comment]
why not just train and load multiple loras?

**Comment by Maximilianwte** [comment]
Sounds also good. Best way to do that by converting the first lora into diffuser like this (https://github.com/huggingface/diffusers/blob/main/scripts/convert_lora_safetensor_to_diffusers.py) or different way of just loading multiple lora's?

Thanks a lot for your suggestions already!
