### ISSUE TITLE
convert_original_stable_diffusion_to_diffusers produces argument error on config_files

### ISSUE THREAD

**Issue by SirRichie** [huggingface/diffusers#5061]
### Describe the bug

Trying to use the latest version of the conversion script does not work since the call to download_from_original_stable_diffusion_ckpt tries to use args.config_files which cannot be passed as an argument.

### Reproduction

Use convert_original_stable_diffusion_to_diffusers.py with any checkpoint_path and dump_file

### System Info

latest versions of diffusers transformers scipy ftfy accelerate safetensors omegaconf on Google colab

**Comment by sayakpaul** [comment]
Could you provide the Colab Notebook you're using and the stack trace you're seeing? The description of the issue is not defined enough for us to comment further otherwise.

**Comment by bahamute-tete** [comment]
I had the same problem using the conversion tool. 
My issue is：

 Traceback (most recent call last):
  File "d:\Python\diffusers\scripts\convert_original_stable_diffusion_to_diffusers.py", line 157, in <module>
    config_files=args.config_files,
AttributeError: 'Namespace' object has no attribute 'config_files'

So I located this place and added a  definition about config_files to temporarily ensure that the script can run smoothly.
like this:
    parser.add_argument("--config_files", type=str, default=None, required=False,help="1111", )

Hope it helps you

**Comment by elcolie** [comment]
Commit: `79a3f39eb508207d789dcdb397f077132a27779c`
Download file from https://civitai.com/models/139565/realistic-stock-photo

```bash
python scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ~/Downloads/realisticStockPhoto_v10.safetensors --from_safetensors --dump_path ai_directory/sdxl/realisticStockPhoto_v10
```

Error:
```bash
Traceback (most recent call last):
  File "/Users/sarit/study/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 157, in <module>
    config_files=args.config_files,
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'config_files'
```

I had tried comment out like 157. And got next problem.
```bash
Traceback (most recent call last):
  File "/Users/sarit/study/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 154, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1615, in download_from_original_stable_diffusion_ckpt
    pipe = pipeline_class(
           ^^^^^^^^^^^^^^^
TypeError: StableDiffusionPipeline.__init__() got an unexpected keyword argument 'text_encoder_2'
```

**Comment by bahamute-tete** [comment]
hello ! 你发的那个问题我研究下，这个问题在只会在转换XL的模型时候才会发生，SD1.5 的模型是不会出问题的。
根据定位 我发现问题主要是在 diffuser库的convert_from_ckpt.py 这个文件的1221 行：
&nbsp; &nbsp;if pipeline_class is None:
&nbsp; &nbsp; &nbsp; &nbsp; pipeline_class = StableDiffusionPipeline if not controlnet else StableDiffusionControlNetPipeline



pipeline_class 使用的是StableDiffusionPipeline  这个管线里是没有 text_encoder_2 的；这个只能在XL模型下面才会有 
所以我尝试了修改 
&nbsp;from diffusers import (
&nbsp; &nbsp; &nbsp; &nbsp; LDMTextToImagePipeline,
&nbsp; &nbsp; &nbsp; &nbsp; PaintByExamplePipeline,
&nbsp; &nbsp; &nbsp; &nbsp; StableDiffusionControlNetPipeline,
&nbsp; &nbsp; &nbsp; &nbsp; StableDiffusionInpaintPipeline,
&nbsp; &nbsp; &nbsp; &nbsp; StableDiffusionPipeline,
&nbsp; &nbsp; &nbsp; &nbsp; StableDiffusionXLImg2ImgPipeline,
&nbsp; &nbsp; &nbsp; &nbsp; StableUnCLIPImg2ImgPipeline,
&nbsp; &nbsp; &nbsp; &nbsp; StableUnCLIPPipeline,
&nbsp; &nbsp; &nbsp; &nbsp; StableDiffusionXLPipeline,​
&nbsp; &nbsp; )

&nbsp; &nbsp; if pipeline_class is None:
&nbsp; &nbsp; &nbsp; &nbsp; pipeline_class = StableDiffusionXLPipeline if not controlnet else StableDiffusionControlNetPipeline


这样修改以后 运行是可以的 ；
因为我是个新手，具体要怎么修改我也不清楚，故将我的发现分享给你



在






Ragnarok
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huggingface/diffusers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 晚上6:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huggingface/diffusers] convert_original_stable_diffusion_to_diffusers produces argument error on config_files (Issue #5061)





 
Commit: 79a3f39eb508207d789dcdb397f077132a27779c
 Download file from https://civitai.com/models/139565/realistic-stock-photo
 python scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ~/Downloads/realisticStockPhoto_v10.safetensors --from_safetensors --dump_path ai_directory/sdxl/realisticStockPhoto_v10
 
Error:
 Traceback (most recent call last):   File "/Users/sarit/study/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 157, in <module&gt;     config_files=args.config_files,                  ^^^^^^^^^^^^^^^^^ AttributeError: 'Namespace' object has no attribute 'config_files'
 
I had tried comment out like 157. And got next problem.
 Traceback (most recent call last):   File "/Users/sarit/study/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 154, in <module&gt;     pipe = download_from_original_stable_diffusion_ckpt(            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/Users/sarit/anaconda3/envs/try_openai/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1615, in download_from_original_stable_diffusion_ckpt     pipe = pipeline_class(            ^^^^^^^^^^^^^^^ TypeError: StableDiffusionPipeline.__init__() got an unexpected keyword argument 'text_encoder_2'

**Comment by elcolie** [comment]
I think my issue is not `diffusers`. It is problem from `safetensors` I downloaded.

**Comment by SirRichie** [comment]
It is the issue @elcolie  describes. Calling the script always results in AttributeError: 'Namespace' object has no attribute 'config_files'
And when looking at the script that makes sense since config_files is not defined anywhere.

**Comment by patrickvonplaten** [comment]
Note that the better way to convert SDXL is the following:

```py
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_single_file("~/Downloads/realisticStockPhoto_v10.safetensors")
pipe.save_pretrained("/your/diffusers/dump_folder")
```
