### ISSUE TITLE
Missing requirements in examples\controlnet

### ISSUE THREAD

**Issue by geroldmeisinger** [huggingface/diffusers#5067]
### Describe the bug

Using `examples/controlnet` only installs the requirements needed for CPU training which is terribly slow. It should also install requirements for CUDA training whether or not this will be used by default.
Also some requirements for CPU training are missing on Windows at all.

**Missing requirements for training with CUDA (all platforms)**
https://pytorch.org/get-started/locally -> Stable -> Windows -> Conda -> Python -> CUDA (latest)

```
pip install xformers bitsandbytes
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
```

**Missing requirements for training with CUDA (Windows only)**

```
conda install chardet cchardet
pip install bitsandbytes-windows
```

### Reproduction

I recently tried to train a control net with the train_controlnet.py example and documented the whole process [in this article](https://civitai.com/articles/2078#heading-35427). The errors appear on a fresh installation of Miniconda (on Windows). To reproduce just start the training on test dataset according to the [tutorial](https://huggingface.co/docs/diffusers/training/controlnet):

```
accelerate launch train_controlnet.py --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --output_dir="control-ini/" --dataset_name="fusing/fill50k"
```

### Logs

**Missing requirements for all platforms**

```
ModuleNotFoundError: No module named 'bitsandbytes'
```

```
ValueError: xformers is not available. Make sure it is installed correctly
```

```
PackagesNotFoundError: The following packages are not available from current channels:

- xformers
```

**Missing requirements for Windows**

```
ModuleNotFoundError: No module named 'chardet'
ModuleNotFoundError: No module named 'cchardet'
...
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (%USERPROFILE%\miniconda3\envs\controlnet\Lib\site-packages\charset_normalizer\constant.py)
```

```
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

the following belongs to `xformers` I think:
```
Error caught was: No module named 'triton'
```

### System Info

- d0cf681a1ff3dc2c394c40d877e8fcaf7caa8080
- Windows 10
- Miniconda3 Windows 64-bit

### Who can help?

@williamberman, @sayakpaul, @yiyixuxu

**Comment by patrickvonplaten** [comment]
cc @williamberman @pat

**Comment by williamberman** [comment]
I think xformers and bitsandbytes are documented as optional instal requirements and then I'm not sure if we officially support windows. I think the installation instructions for cuda vs cpu torch is better left to the pytorch docs
