### ISSUE TITLE
examples\controlnet option to save inference validation images to disk

### ISSUE THREAD

**Issue by geroldmeisinger** [huggingface/diffusers#5069]
**Is your feature request related to a problem? Please describe.**
I recently tried to train a control net with the `train_controlnet.py` example and documented the whole process [in this article](https://civitai.com/articles/2078#heading-3270). Following the [controlnet tutorial ](https://huggingface.co/docs/diffusers/training/controlnet) it is possible to provide the arguments `--validation_image` and `--validation_prompt` to run the inference script every 100 steps to generate an image. I just started out and didn't look into projects like Tensorboard and WandB yet and wanted to make the training process as simple as possible. If no trackers are installed the script will still run the inference script, which takes some time, only to discard the image afterwards.

By looking at the related source this image will then be sent to `accelerate.trackers` which can either be `tensorboard` or `wandb`. It would also be nice if the image could be simply saved to disk :)

`train_controlnet.py 119`
```
    for validation_prompt, validation_image in zip(validation_prompts, validation_images):
        validation_image = Image.open(validation_image).convert("RGB")

        images = []

        for _ in range(args.num_validation_images):
            with torch.autocast("cuda"):
                image = pipeline(
                    validation_prompt, validation_image, num_inference_steps=20, generator=generator
                ).images[0]

            images.append(image)

        image_logs.append(
            {"validation_image": validation_image, "images": images, "validation_prompt": validation_prompt}
        )

    for tracker in accelerator.trackers:
        if tracker.name == "tensorboard":
            for log in image_logs:
                images = log["images"]
                validation_prompt = log["validation_prompt"]
                validation_image = log["validation_image"]

                formatted_images = []

                formatted_images.append(np.asarray(validation_image))

                for image in images:
                    formatted_images.append(np.asarray(image))

                formatted_images = np.stack(formatted_images)

                tracker.writer.add_images(validation_prompt, formatted_images, step, dataformats="NHWC")
        elif tracker.name == "wandb":
            formatted_images = []

            for log in image_logs:
                images = log["images"]
                validation_prompt = log["validation_prompt"]
                validation_image = log["validation_image"]

                formatted_images.append(wandb.Image(validation_image, caption="Controlnet conditioning"))

                for image in images:
                    image = wandb.Image(image, caption=validation_prompt)
                    formatted_images.append(image)

            tracker.log({"validation": formatted_images})
        else:
            logger.warn(f"image logging not implemented for {tracker.name}")

        return image_logs
```

**Describe the solution you'd like**
Specifiy no tracker by default and save images to disk by default.

**Describe alternatives you've considered**
Of course you can always remove the arguments and run the validation manually either with the provided `inference.py` script or any UI.

**Additional context**
I'm on d0cf681a1ff3dc2c394c40d877e8fcaf7caa8080

**Comment by sayakpaul** [comment]
If you want to open a PR for this, we'd be keen to review and merge :-)
