### ISSUE TITLE
Add ControlNet for Würstchen and examples\train_controlnet_wuerstchen.py

### ISSUE THREAD

**Issue by geroldmeisinger** [huggingface/diffusers#5071]
[Introducing Würstchen: Fast Diffusion for Image Generation](https://huggingface.co/blog/wuerstchen).

**Describe the solution you'd like**
Please implement ControlNet pipeline and training script for Würstchen.
Würstchen requires only 12x12 latent space instead of 64x64 compared to Stable Diffusion. If this also means a 28x times (4096 / 144) speed-up in training, this would be awesome! _Less thinking, more tinkering!_

**Describe alternatives you've considered**
* Watch training script slowly train on my home GPU
* Rent cloud GPU
* Buy bigger hardware and pollute the planet

**Comment by pabloppp** [comment]
The speedup is not that high, since Stable Diffusion uses a U-Net that quickly goes from 64x64 to 16x16 so don't expect a x28 speeup over SD. I guess you could expect better x2 and x6 speedup 🤔 but not sure, especially for finetunings like ControlNet

**Comment by geroldmeisinger** [comment]
we can never know unless we try 🥺

**Comment by geroldmeisinger** [comment]
*cough cough* Stable Cascade *cough*

**Comment by bghira** [comment]
@geroldmeisinger have you used the current wurstschen scripts to try training it yet? does that work for stable cascade? if it does, adding controlnet support to this script is fairly easy for unet based models, and the existing example script for controlnet training should help get you started on adapting the dataloader.

if you'd like help with that, i'm on the Hugging Face Discord server, as well

**Comment by geroldmeisinger** [comment]
> @geroldmeisinger have you used the current wurstschen scripts to try training it yet? does that work for stable cascade? if it does, adding controlnet support to this script is fairly easy for unet based models, and the existing example script for controlnet training should help get you started on adapting the dataloader.

yes. I tried to run the official training script (batchsize=4, bf16) but ran into OOM. I'd hope that a diffusers implementation would provide more optimization and lower VRAM requirements.

**Comment by bghira** [comment]
i meant the diffusers wurstchen scripts, can you give it a try?

**Comment by bghira** [comment]
i'm talking about [these](https://github.com/huggingface/diffusers/tree/b69fd990ad8026f21893499ab396d969b62bb8cc/examples/wuerstchen/text_to_image) scripts.

as a side note, controlnet training will likely not require less memory than the official scripts.

**Comment by geroldmeisinger** [comment]
I'll take a look, thanks!
