### ISSUE TITLE
pred_text is prompt pass the unet?pred_uncond is is negative_prompt pass the unet?

### ISSUE THREAD

**Issue by henbucuoshanghai** [huggingface/diffusers#5072]
pred = pred_uncond + guidance_scale * (pred_text - pred_uncond)
why use this calculation?

**Comment by patrickvonplaten** [comment]
It's called classifier-free guidance. See https://sander.ai/2022/05/26/guidance.html for example

**Comment by henbucuoshanghai** [comment]
kind replay,but it is also used in dall2?sd?sdxl?
for the  negative_prompt?
