### ISSUE TITLE
Support for PyTorch 2.1 torch.export To Load / Save Compiled Stable Diffusion Models 

### ISSUE THREAD

**Issue by djj0s3** [huggingface/diffusers#5074]
Diffusers supports PyTorch 2.0's torch.compile which yields significant performance gains. However, the torch2.0 implementation did not include support for saving and loading the compiled result, which unfortunately limits its use in some environments. An example would be a production environment where new GPUs need to spin up to meet demand but require a "warm" up with compilation happening each time.  With the new PyTorch 2.1 support, we should be able to save the compilation once and load it dynamically. PyTorch2.1 is now in RC so seems like a good time for this to be officially supported by Diffusers.

**Comment by djj0s3** [comment]
Upon reading the torch 2.1 docs, I'd expect to do something like the pseudocode below to utilize torch.export.* with Diffusers:
```
pipe = StableDiffusionPipeline.from_pretrained(
            <MODEL>,
            torch_dtype=torch.float16,
        )
example_inputs = {
            'prompt_embeds': promptEmbeds,
            'negative_prompt_embeds': negPromptEmbeds,
            'num_images_per_prompt': numImages,
            'guidance_scale': guidanceScale,
            'generator': generator,
            'num_inference_steps': numSteps,
        }
fileName = "exported_pipe";
if not os.path.exists(fileName):
	exported_pipe = torch.export.export(pipe, args=(), kwargs=example_inputs)
        torch.export.save(exported_program, fileName)
else:
        pipe = torch.export.load(fileName)

```

**Comment by patrickvonplaten** [comment]
@djj0s3 we usually only compile the unet, so I guess we would only have to export/load the unet no?

**Comment by djj0s3** [comment]
That makes sense to me. Export seems to trace the whole model though sorta like tracing if I follow the docs correctly. What inputs would we send through unet?

**Comment by patrickvonplaten** [comment]
The unet takes all the inputs as defined here: https://github.com/huggingface/diffusers/blob/04d696d65053644775b104cb3af92aff8338e6fc/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L831

**Comment by djj0s3** [comment]
Gave that approach a whirl (note, I'm using SD1.5, not XL put your last comment pointed me in the right direction!) but I ran into this issue while trying to compile. Not sure if you folks have tried out export on your end. 
```
torch._dynamo.exc.Unsupported: call_function UserDefinedClassVariable() [] {'sample': TensorVariable()}
from user code:
File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/diffusers/models/unet_2d_condition.py", line 1046, in forward
return UNet2DConditionOutput(sample=sample)
```

**Comment by yuananf** [comment]
PyTorch 2.1 was released. https://pytorch.org/blog/pytorch-2-1/

**Comment by AbhinavGopal** [comment]
Wondering about this right now. Was anyone able to figure out how to save + load compiled unets?
