### ISSUE TITLE
LPW XL :  mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by adhikjoshi** [huggingface/diffusers#5081]
### Describe the bug

When trying to use SDXLLongPromptWeightingPipeline, and more than 2 samples, it gives the below error

> mat1 and mat2 shapes cannot be multiplied

### Reproduction

```
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0"
    , torch_dtype       = torch.float16
    , use_safetensors   = True
    , variant           = "fp16"
    , custom_pipeline   = "lpw_stable_diffusion_xl",
)

prompt = "photo of a cute (white) cat running on the grass"*20
prompt2 = "chasing (birds:1.5)"*20
prompt = f"{prompt},{prompt2}"
negative_prompt = "blur, low quality, carton, animate"

pipe.to("cuda")
images = pipe(prompt,negative_prompt,num_images_per_prompt = 2).images[0]

pipe.to("cpu")
torch.cuda.empty_cache()
images.save("ssss.png")
```

### System Info

diffusers==0.21

### Who can help?

@patrickvonplaten @xhinker @sayakpaul

**Comment by patrickvonplaten** [comment]
@xhinker could you take a look here? :-)

**Comment by xhinker** [comment]
Hi, @adhikjoshi , The pipeline currently support one image at a time, if you need to generate more than 1 image at one time, you may consider use a loop to do it.

**Comment by adhikjoshi** [comment]
> Hi, @adhikjoshi , The pipeline currently support one image at a time, if you need to generate more than 1 image at one time, you may consider use a loop to do it.  

Imo it wouldn't be hard to fix

**Comment by sayakpaul** [comment]
> > Hi, @adhikjoshi , The pipeline currently support one image at a time, if you need to generate more than 1 image at one time, you may consider use a loop to do it.
> 
> Imo it wouldn't be hard to fix

Happy to welcome your PRs :)
