### ISSUE TITLE
 RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)

### ISSUE THREAD

**Issue by hosnasn1987** [huggingface/diffusers#5082]
### Describe the bug

I build a model named sd-dreambooth-library/snapp-g-data via this notebook:
https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_dreambooth_training.ipynb#scrollTo=30lu8LWXmg5j

i want to give it to the ControlNet model via this code:

https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/controlnet.ipynb

but in the last step i get this error and i cant solve it :

RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)

what should i do?

### Reproduction

generator = torch.manual_seed(2)
prompt = "a photo of cat, best quality, extremely detailed"
output = pipe(
    prompt,
    canny_image,
    negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality",
    generator=generator,
    num_inference_steps=20,
)generator = torch.manual_seed(2)
prompt = "a photo of cat, best quality, extremely detailed"
output = pipe(
    prompt,
    canny_image,
    negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality",
    generator=generator,
    num_inference_steps=20,
)

### System Info

colab.research

**Comment by patrickvonplaten** [comment]
Hey @hosnasn1987,

Can you:
1.) upload your trained model to the hub
2.) Copy-paste a completely reproducable code snippet? 
I can't run:
```py
generator = torch.manual_seed(2)
prompt = "a photo of cat, best quality, extremely detailed"
output = pipe(
prompt,
canny_image,
negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality",
generator=generator,
num_inference_steps=20,
)generator = torch.manual_seed(2)
prompt = "a photo of cat, best quality, extremely detailed"
output = pipe(
prompt,
canny_image,
negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality",
generator=generator,
num_inference_steps=20,
)
```

**Comment by hosnasn1987** [comment]
it is my model in huggingface:
https://huggingface.co/sd-dreambooth-library/my-cat
and I get the error exactly in the part you have copied

**Comment by hosnasn1987** [comment]
> Hey @hosnasn1987,
> 
> Can you: 1.) upload your trained model to the hub 2.) Copy-paste a completely reproducable code snippet? I can't run:
> 
> ```python
> generator = torch.manual_seed(2)
> prompt = "a photo of cat, best quality, extremely detailed"
> output = pipe(
> prompt,
> canny_image,
> negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality",
> generator=generator,
> num_inference_steps=20,
> )generator = torch.manual_seed(2)
> prompt = "a photo of cat, best quality, extremely detailed"
> output = pipe(
> prompt,
> canny_image,
> negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality",
> generator=generator,
> num_inference_steps=20,
> )
> ```


it is my model in huggingface:
https://huggingface.co/sd-dreambooth-library/my-cat
and I get the error exactly in the part you have copied
