### ISSUE TITLE
FlaxStableDiffusionXLPipeline Import Error

### ISSUE THREAD

**Issue by gokerguner** [huggingface/diffusers#5084]
I've tried to run a Stable Diffusion XL with a script with its pipeline in a TPU instance. 

diffusers version:0.21.1
Python version:Python 3.8.10

I do my works in a Linux Ubuntu, there is no conda or other environment.

I take an import error in import line `from diffusers import FlaxStableDiffusionXLPipeline`

The error message is: `ImportError: cannot import name 'FlaxStableDiffusionXLPipeline' from 'diffusers' (/home/goker/.local/lib/python3.8/site-packages/diffusers/__init__.py)`

What could be my mistake?

**Comment by patrickvonplaten** [comment]
Yeah it's not yet merged, we're working with some Google folks to optimize the pipeline. Open PR here: https://github.com/huggingface/diffusers/pull/4254
