### ISSUE TITLE
SD ONNX remaining pipelines

### ISSUE THREAD

**Issue by GreenLandisaLie** [huggingface/diffusers#510]
It has caught my attention that you guys already made an onnx pipeline for SD but it seems to be txt2img.
To my knowledge no one has done it for img2img and inpaint yet. 
Is that possible? If so, I'd like to request that feature.
Thanks for everything you have been doing so far!

**Comment by anton-l** [comment]
@GreenLandisaLie yes, for sure! We're still testing things with onnx, but if you or someone else want to submit a PR for img2img pipelines already - happy to integrate it :)

**Comment by anton-l** [comment]
Implemented in https://github.com/huggingface/diffusers/pull/552
