### ISSUE TITLE
T2I Multiadapter XL exceptions

### ISSUE THREAD

**Issue by reimager** [huggingface/diffusers#5108]
### Describe the bug

I'm trying to replicate the t2i Multi-Adapter similar to the example here:
https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/adapter

but with the XL pipeline, but without much success. I always get one of two exceptions:

```
Traceback (most recent call last):
  File "/workspace/experiments/./multiadapter.py", line 38, in <module>
    images = pipe(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/src/diffusers/src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py", line 771, in __call__
    height, width = self._default_height_width(height, width, image)
  File "/usr/local/src/diffusers/src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py", line 582, in _default_height_width
    height = (height // self.adapter.total_downscale_factor) * self.adapter.total_downscale_factor
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
```

This one seems related to: https://github.com/huggingface/diffusers/issues/4427

```
Traceback (most recent call last):
  File "/workspace/experiments/./multiadapter.py", line 31, in <module>
    images = pipe(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/src/diffusers/src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py", line 774, in __call__
    adapter_input = _preprocess_adapter_image(image, height, width).to(device)
AttributeError: 'list' object has no attribute 'to'
```

This is is because I'm not sure I'm calling the pipeline correctly
image does not seem to take a list of lists, but with multiple input images and a batch_size greater than 1, a list of list seems like the only option?

### Reproduction
```
import torch
from PIL import Image
from diffusers.utils import load_image
from diffusers import StableDiffusionXLAdapterPipeline, MultiAdapter, T2IAdapter


cond_keypose = load_image(
    "https://huggingface.co/datasets/diffusers/docs-images/resolve/main/t2i-adapter/keypose_sample_input.png"
)
cond_depth = load_image(
    "https://huggingface.co/datasets/diffusers/docs-images/resolve/main/t2i-adapter/depth_sample_input.png"
)

batch_size = 4
conds = [cond_keypose, cond_depth]
prompt = "A man walking in an office room with a nice view"

adapters = MultiAdapter([
    T2IAdapter.from_pretrained("TencentARC/t2i-adapter-openpose-sdxl-1.0", torch_dtype=torch.float16, varient="fp16"),
    T2IAdapter.from_pretrained("TencentARC/t2i-adapter-depth-midas-sdxl-1.0", torch_dtype=torch.float16, varient="fp16"),
])

adapters = adapters.to(torch.float16).to("cuda")

pipe = StableDiffusionXLAdapterPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    adapter=adapters,
).to("cuda")

images = pipe(
    prompt=[prompt]*batch_size,
    image=[conds]*batch_size,
    adapter_conditioning_scale=[0.8, 0.8],
)

# Also fails
# images = pipe(
#     [prompt]*batch_size,
#     [conds]*batch_size,
#     adapter_conditioning_scale=[0.8, 0.8],
# )

# Also fails
# images = pipe(
#     prompt,
#     conds,
#     num_images_per_prompt=batch_size,
#     adapter_conditioning_scale=[0.8, 0.8],
# )
```

### System Info

- `diffusers` version: 0.21.1
- Platform: Linux-5.10.0-25-amd64-x86_64-with-glibc2.35
- Python version: 3.10.6
- PyTorch version (GPU?): 2.1.0a0+b5021ba (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.32.0.dev0
- Accelerate version: 0.22.0.dev0
- xFormers version: 0.0.22+04de99b.d20230915
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@williamberman

**Comment by ghunkins** [comment]
@reimager A patch version fixing various issues for T2I MultiAdapter just got released. Do you have the same issues with that version?

```bash
pip install --upgrade diffusers==0.21.2
```

**Comment by reimager** [comment]
> @reimager A patch version fixing various issues for T2I MultiAdapter just got released. Do you have the same issues with that version?

I just tried 0.21.2 and the exceptions were the same in all 3 use cases above.
Its entirely possible I'm calling the pipeline wrong - I'm especially confused how calling it with positional arguments vs keyword arguments gives different results.

**Comment by patrickvonplaten** [comment]
Hmm it looks like there is still a bug here - I'll check later today!

**Comment by ghunkins** [comment]
I ended up trying it out and received an error as well. MultiAdapter and `adapter_conditioning_scale` passed as a list. Thanks @patrickvonplaten. 👏 

```bash
File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/diffusers/models/adapter.py", line 258, in forward
    return self.adapter(x)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/diffusers/models/adapter.py", line 344, in forward
    x = block(x)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/diffusers/models/adapter.py", line 368, in forward
    x = self.downsample(x)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/diffusers/models/resnet.py", line 221, in forward
    assert hidden_states.shape[1] == self.channels
```

**Comment by yiyixuxu** [comment]
@reimager 
We just merged in the PR that fixes this https://github.com/huggingface/diffusers/pull/5127 - you can find an example how to use multi adapter with sdxl adapter pipeline there 

A few notes:
* The signature of `StableDiffusionXLAdapterPipeline` is different from `StableDiffusionAdapterPipeline`https://github.com/huggingface/diffusers/blob/2badddfdb6b34eedb6155987b1cd823f6d7cdd3e/src/diffusers/pipelines/t2i_adapter/pipeline_stable_diffusion_xl_adapter.py#L608-L614  that's why calling it with same positional arguments you would use for `StableDiffusionAdapterPipeline` would not work. In your case, you actually passed the `cond` argument as `prompt2` and `None` as `image,` hence the error `TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'`
* to generate multiple images for each prompt, you can use `num_images_per_prompt` argument, no need to do `prompt=[prompt]*batch_size` and `image=[conds]*batch_size`

**Comment by reimager** [comment]
Thank you!!
