### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars

### ISSUE THREAD

**Issue by kevint324** [huggingface/diffusers#5110]
### Describe the bug

I loaded the stable diffusion XL 1.0 model on my disk and followed instructions from
https://huggingface.co/docs/diffusers/v0.8.0/en/using-diffusers/loading#loading-pipelines-locally

The code is simply load the pretrained model.

```
import torch
from diffusers import DiffusionPipeline
from diffusers import StableDiffusionPipeline

model_name =  "./sd-xl-base-1.0"

pipeline = DiffusionPipeline.from_pretrained(model_name, torch_dtype=torch.float16,use_safetensors=True, variant="fp16")
```

It works well when your PWD is at the same directory as  the python script ( python ./xx.py)

But HFValidationError complains when PWD is changed.

On success

```
$ cd sd-xl-1.0/ && python diff.py
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.73it/s]
```

On failure
```
$ python sd-xl-1.0/diff.py 
Traceback (most recent call last):
  File "sd-xl-1.0/diff.py", line 11, in <module>
    pipeline = DiffusionPipeline.from_pretrained(model_name, torch_dtype=torch.float16,use_safetensors=True, variant="fp16")
  File "/home/tonghengwen/anaconda3/envs/pytorch/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 939, in from_pretrained
    cached_folder = cls.download(
  File "/home/tonghengwen/anaconda3/envs/pytorch/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1441, in download
    info = model_info(
  File "/home/tonghengwen/anaconda3/envs/pytorch/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/tonghengwen/anaconda3/envs/pytorch/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: './sd-xl-base-1.0'.
```

### Reproduction

```
import torch
from diffusers import DiffusionPipeline
from diffusers import StableDiffusionPipeline

model_name =  "./sd-xl-base-1.0"

pipeline = DiffusionPipeline.from_pretrained(model_name, torch_dtype=torch.float16,use_safetensors=True, variant="fp16")
```

Test above code from diffrent location

### System Info

diffusers-0.21.2
python3.8
Ubuntu 20

### Who can help?

 @patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
In that case, you need to use absolute path.

**Comment by kevint324** [comment]
sorry, I forgot to mention that absolute path is not accepted either @sayakpaul 

```
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/tonghengwen/code/pytorch-test/xla_playground/pytorch/sd-xl-base-1.0'. Use `repo_type` argument if needed.
```

**Comment by kevint324** [comment]
Hi Sayak,

I tried to reproduce the bug in colab but found the absolute path works just fine.
https://colab.research.google.com/drive/1jAwtC2-uAgc6bAmcSNcmvnZ7j-EIn6Sy?usp=sharing

The I figured out there's bug in my local code and after that everything just works great.

Thanks for the reply!

BTW, maybe add some hint in the document or the error message about the absolute path usage could be helpful.

**Comment by sayakpaul** [comment]
Cool. Thanks. Feel free to open a PR then. I am closing the issue then since you've figured it out :)

**Comment by kevint324** [comment]
I filed a PR to update the error message.
https://github.com/huggingface/huggingface_hub/pull/1683

This is a quick fix for current issue. A few explanations.

```
    if repo_id.count("/") > 1:
        raise HFValidationError(
            "Repo id must be in the form 'repo_name', 'namespace/repo_name' or '/path/to/repo' :"
            f" '{repo_id}'."
        )
```

`if repo_id.count("/") > 1:` and `'/path/to/repo' ` may look confusing.

The problem is when user provides a invalid /path/to/local/repo, eg, typo, the os.path.isdir will fail and pipeline_utils will assume user is providing a repo_id which should contains less than 1 '/'
