### ISSUE TITLE
add clip skip for StableDiffusionLongPromptWeightingPipeline+LORA

### ISSUE THREAD

**Issue by Charlse-s** [huggingface/diffusers#5113]
**Is your feature request related to a problem? Please describe.**
StableDiffusionLongPromptWeightingPipeline.__call__() got an unexpected keyword argument 'clip_skip'

**Describe the solution you'd like**
add CLIP skip as described in #4834
no support for StableDiffusionLongPromptWeightingPipeline?

diffusers == 0.22.0.dev0

check the call function of StableDiffusionLongPromptWeightingPipeline

def __call__(
        self,
        prompt: Union[str, List[str]],
        negative_prompt: Optional[Union[str, List[str]]] = None,
        image: Union[torch.FloatTensor, PIL.Image.Image] = None,
        mask_image: Union[torch.FloatTensor, PIL.Image.Image] = None,
        height: int = 512,
        width: int = 512,
        num_inference_steps: int = 50,
        guidance_scale: float = 7.5,
        strength: float = 0.8,
        num_images_per_prompt: Optional[int] = 1,
        add_predicted_noise: Optional[bool] = False,
        eta: float = 0.0,
        generator: Optional[Union[torch.Generator, List[torch.Generator]]] = None,
        latents: Optional[torch.FloatTensor] = None,
        prompt_embeds: Optional[torch.FloatTensor] = None,
        negative_prompt_embeds: Optional[torch.FloatTensor] = None,
        max_embeddings_multiples: Optional[int] = 3,
        output_type: Optional[str] = "pil",
        return_dict: bool = True,
        callback: Optional[Callable[[int, int, torch.FloatTensor], None]] = None,
        is_cancelled_callback: Optional[Callable[[], bool]] = None,
        callback_steps: int = 1,
        cross_attention_kwargs: Optional[Dict[str, Any]] = None,
    ):

Actually it can work with:

text_encoder = CLIPTextModel.from_pretrained("base_model", subfolder="text_encoder", num_hidden_layers=10, torch_dtype=torch.float16)
pipe.text_encoder = text_encoder

but it will return error when use lora :
pipe.load_lora_weights() #4735

**Comment by patrickvonplaten** [comment]
Hey @Charlse-s,

Can you contact the original author here?
