### ISSUE TITLE
T2IAdapter

### ISSUE THREAD

**Issue by wanglaofei** [huggingface/diffusers#5116]
### Describe the bug

in the class MultiAdapter(), the forward input xs should be chunked into n chunks (n=number of adapters)

### Reproduction

x_list = torch.chunk(xs, self.num_adapter, dim=1)
accume_state = None
for x, w, adapter in zip(x_list, adapter_weights, self.adapters):

in the line 88 in the adapter.py

### System Info

- `diffusers` version: 0.21.2
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.7.16
- PyTorch version (GPU?): 1.13.1 (False)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
Hey @wanglaofei,

Can you add a reproducible code snippet here? Also cc @williamberman can you double check that everything works as expected?
