### ISSUE TITLE
how to use controlnet's reference_only fuction with diffusers??

### ISSUE THREAD

**Issue by sudip550** [huggingface/diffusers#5118]
### Model/Pipeline/Scheduler description

can anyone help me to understand how to use controlnet's reference_only fuction with diffusers

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by patrickvonplaten** [comment]
I'm not sure if the community examples work with all the diffusers goodies and whether they have all the features that exist

**Comment by sudip550** [comment]
> I'm not sure if the community examples work with all the diffusers goodies and whether they have all the features that exist

my idea is that, we'll upload/submit 2 images, 1 of only clothes and other is of person. when we run our python script, new image should be generated in which person will wear that clothes which we have provided in 1st image.........
