### ISSUE TITLE
error loading a local .safetensors using XLPipeline.from_single_file

### ISSUE THREAD

**Issue by garychan22** [huggingface/diffusers#5128]
### Describe the bug

I have downloaded the sdxl-base-1.0 *.safetensors from https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/tree/main

I am trying to load the model following 
```
sdxl_model_path = "/xxx/xxx/sd_xl_base_1.0.safetensors"
pipe = StableDiffusionXLPipeline.from_single_file(
           sdxl_model_path, torch_dtype=torch.float16, variant="fp16", use_safetensors=True, local_files_only=True,
)
```

The error is raised
```
OSError: Can't load tokenizer for 'laion/CLIP-ViT-bigG-14-laion2B-39B-b160k'.
```

### Reproduction

As aforementioned

### System Info

- `diffusers` version: 0.21.1
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.17
- Python version: 3.8.18
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.17.1
- Transformers version: 4.33.2
- Accelerate version: 0.23.0
- xFormers version: 0.0.21
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
Unable to reproduce it: 
https://colab.research.google.com/gist/sayakpaul/fd58fcc09c3ab633c6eb8ca946f74ad7/scratchpad.ipynb
