### ISSUE TITLE
Question regarding DDPMScheduler

### ISSUE THREAD

**Issue by xiankgx** [huggingface/diffusers#5130]
### Describe the bug

The `current_beta_t` is computed from alphas_cumprod and alphas_cumprod_prev at the following line:

[https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py#L287](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py#L287)

However, betas is already an attribute in the DDPMScheduler class at the following lines:

[https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py#L157-L174](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py#L157-L174)

This makes me wonder, why is `current_beta_t` not just `self.betas[t]` instead? I tried to print out both values and they are not the same. `current_beta_t` is then proceeded to compute variance in the line which is defined in Eqn. 7 at the [DDPM paper](https://arxiv.org/pdf/2006.11239.pdf).

[https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py#L292](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py#L292)

If my understanding of this is wrong, please enlighten me.

### Reproduction

Add `print(f">>> t: {t}, prev_t: {prev_t}, current_beta_t: {current_beta_t}, self.betas[t]: {self.betas[t]}")` after line https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py#L287 and run a pipeline forward call.

### System Info

diffusers git

### Who can help?

@patrickvonplaten @williamberman

**Comment by xiankgx** [comment]
The variance implemented in diffusers

```
prev_t = self.previous_timestep(t)

alpha_prod_t = self.alphas_cumprod[t]
alpha_prod_t_prev = self.alphas_cumprod[prev_t] if prev_t >= 0 else self.one
current_beta_t = 1 - alpha_prod_t / alpha_prod_t_prev

variance = (1 - alpha_prod_t_prev) / (1 - alpha_prod_t) * current_beta_t
```

vs

The variance implemented in DeepFloyd IF

```
# https://github.com/deep-floyd/IF/blob/develop/deepfloyd_if/model/gaussian_diffusion.py#L148-L150
self.posterior_variance = (
    betas * (1.0 - self.alphas_cumprod_prev) / (1.0 - self.alphas_cumprod)
)
```

I do not understand why are we not taking the beta at time t directly but instead recalculate beta_t using alphas_cumprod. I also don't understand why am I seeing a difference in values between the two.

I'm not sure if this helps anything, but I'm trying to finetune a model at bfloat16. Could it be the reduced presision that led to this? But the difference in values is quite huge.

**Comment by laksjdjf** [comment]
current_beta_t is in formula (19) of https://arxiv.org/abs/2102.09672

**Comment by xiankgx** [comment]
Hi @laksjdjf , thanks for pointing that out. However, do you know the discrepancies in the current_beta_t that I'm seeing? And why are we not just taking self.betas[t] instead?

**Comment by laksjdjf** [comment]
self.betas[t] is used for single step inference. If multiple steps are to be inferred at once, it must be replaced by the expression current_beta_t.

**Comment by xiankgx** [comment]
Do you mind explaining why is that the case?
