### ISSUE TITLE
Possible discrepancy in instructpix2pix example script wrt dataset format

### ISSUE THREAD

**Issue by gunshi** [huggingface/diffusers#5136]
Hi,
I'm following the instruct_pix2pix train script [here](https://github.com/huggingface/diffusers/blob/main/examples/instruct_pix2pix/train_instruct_pix2pix.py) and facing some issues with getting a custom dataset to work with it. I checked the demo dataset link provided in the readme and it seems to be a parquet dataset with only three fields (original_image, edit_prompt and edited_image). 
This should be fine since the train script for instruct_pix2pix wants to operate on these column names but the confusing part is that the script calls the load_dataset() function coming from hugging face/datasets, which is not designed to be expecting these keys, and wouldn't load these columns as image files out of the box.

I'm confused then, if the script would only work if we pull the dataset from huggingface (in which case it might be bypassing these checks within load_datset()) and otherwise always fail on local datasets unless we somehow hacked the load_dataset() function to work as we want or added a dataset script? 

More context:

I was looking to run it on my own dataset stored locally on disk, so I created a metadata.jsonl file each line of which looks like the following following the instructions on the readme:
`{"file_name": "", "original_image": "210166/210166_idx=13.jpg", "edited_image": "210166/210166_idx=17.jpg", "edit_prompt": "change the lighting"}`
The reason I added the file_name key is because huggingface/datasets will complain about this key being absent if it isn't there. When I run the script on my dataset (provided as --train_data_dir), the script errors out on the load_dataset step with the error:

`ValueError: image at 100045/100045_idx=0.jpg doesn't have metadata in /scratch/demo_dataset/val/metadata.jsonl.` My hypothesis is because the load_dataset is not supposed to be working out of the box for the kind of dataset that instruct_pix2pix tutorial suggests to create.

Any pointers are appreciated, thanks!

**Comment by patrickvonplaten** [comment]
cc @sayakpaul could you check here?

**Comment by sayakpaul** [comment]
Yeah we do assume the dataset is well formatted but otherwise, I think you would need to make changes to the data preprocessors a bit.

**Comment by sayakpaul** [comment]
Additionally pinging @lhoestq in case he has any pointers to share for rightfully using metadata here. I have not unfortunately played around with passing metadata that much so, cannot comment much on that.

**Comment by gunshi** [comment]
I see, upon digging further my conclusion is that this script will work with datasets that have a parquet file that directly stores the images as the values in the `edited_image` and `original_image` columns. This seems to be difficult to do for a large dataset and I assume I will run out of memory on loading (unless parquet files aren't loaded in one go). A generator-based solution to data-loading seems more optimal for image datasets but I'm finding it difficult to figure out how to code that even after reading the hugging face code and docs - for eg. at which point should we be actually reading the image file into memory and so on.

I guess my general question would be: what is the current dataset format expectation when training img2img style tasks with diffusers? The only image-based dataset definition I see in the datasets lib is the Imagefolder, which is restricted to loading data for image-to-text or text-to-image style tasks. For img2img we need a way to tell the data loader to load multiple columns in a metadata file as images. 

I'd be happy to contribute a PR for this if I can be given some pointers on which base class to build off off (folder_based vs imagefolder or is the correct thing to do here to write a loading script?).

**Comment by sayakpaul** [comment]
> I guess my general question would be: what is the current dataset format expectation when training img2img style tasks with diffusers? The only image-based dataset definition I see in the datasets lib is the Imagefolder, which is restricted to loading data for image-to-text or text-to-image style tasks. For img2img we need a way to tell the data loader to load multiple columns in a metadata file as images.

The simplest is format and host your dataset like the one present in the example script. If you need something that scales seamlessly, then I welcome you to check out this: https://github.com/sayakpaul/instructpix2pix-sdxl/blob/main/scripts/dataloader.py

**Comment by gunshi** [comment]
Got it, thanks!
Could you provide a link to the repo/documentation that describes how the parquet files were created? I did not find them here: https://github.com/huggingface/diffusers/tree/main/examples/instruct_pix2pix.
Thanks again!

**Comment by lhoestq** [comment]
> Additionally pinging @lhoestq in case he has any pointers to share for rightfully using metadata here. I have not unfortunately played around with passing metadata that much so, cannot comment much on that.

Hi ! The metadata.jsonl approach doesn't support multi-images examples (though this can surely be implemented, let me know if you'd like to see something like this).

> Upon digging further my conclusion is that this script will work with datasets that have a parquet file that directly stores the images as the values in the edited_image and original_image columns. This seems to be difficult to do for a large dataset and I assume I will run out of memory on loading (unless parquet files aren't loaded in one go).

You can stream the Parquet data with little RAM usage (only one row group in memory at a time) by using load_dataset(..., streaming=True).

For example if you have a directory of multiple parquet files

```
my_dataset/
├── train-00000.parquet
├── train-00001.parquet
...
└── train-NNNNN.parquet
```

You can do

```python
from datasets import load_dataset

ds = load_dataset("path/to/my_dataset", split="train", streaming=True)
```

**Comment by gunshi** [comment]
Hey @lhoestq , thanks for your reply!
Yes would be keen to see a skeleton for how to code it according to the metadata.jsonl approach since that seems like the cleanest solution since it doesn't need data to be regenerated every time we might want to add an attribute associated to the image pair or change how we sampled image pairs etc, we can just create a new metadata.jsonl and that's it.

**Comment by lhoestq** [comment]
I think we would have to modify the `datasets` module responsible for loading image datasets with metadata (aka the "imagefolder" module) to work with multiple images. Cc @mariosasko for visibility.

Maybe if we check for columns named `*_file_name` or something like that ?

For now you'd need a dataset script or define a generator function to pass to `Dataset.from_generator` or `IterableDataset.from_generator` though, similar to the `gen_examples` function in instruct-pix2pix-dataset make_dataset.py file

**Comment by mariosasko** [comment]
The multi-image support has already been requested here: https://github.com/huggingface/datasets/issues/5760.

> Maybe if we check for columns named *_file_name or something like that ?

Yes, the `*_file_name` naming scheme for the muli-image ImageFolder has crossed my mind too. 

I am putting this on my TO-DO list :).

**Comment by gunshi** [comment]
Hey!
I came across the dataset.from_dict() method of creating a dataset and decided to generate it for my case like so:

`from datasets import Dataset, Image
dataset = Dataset.from_dict({"original_image": ["path1", "path2", "path3"..], "edited_image": ["path1", "path2", "path3"..], edit_prompt: ["prompt1", "prompt2", "prompt3"]})
`

and this ended up working pretty well for me!
The images are lazy loaded through PIL as far as I understand, so it doesn't hurt to just instantiate your dataset this way (I think?) instead of using load_dataset() as it shouldn't lead to a memory overflow. 
Thanks!

**Comment by gunshi** [comment]
@mariosasko Should I close this issue since I have found an easy way to be loading data combinations where multiple images are required for training a single datapoint (the dict method)? In my opinion this circumvents the need for having an Imagefolder style loader and is much more flexible since the ImageFolder/metadata.jsonl will hardcode certain keys to look out for.

**Comment by mariosasko** [comment]
@gunshi Yes, feel free to close this issue

**Comment by KazusaKitakawa** [comment]
it worked!
