### ISSUE TITLE
pipe.enable_attention_slicing()o throwing a error

### ISSUE THREAD

**Issue by UglyStupidHonest** [huggingface/diffusers#514]
### Describe the bug

When I activate the pipe=pipe.enable_attention_slicing() for low memory 

I get "TypeError: 'NoneType' object is not callable"

I'm using a model I trained with textual inversion does that impact that function ?

### System Info

diffusers-0.3.0,Ubuntu 20.04.4 LTS, rtx 3090

**Comment by pcuenca** [comment]
Hi!

There was a mistake in the documentation that was fixed later, you don't have to assign the result of the function. Please, try the following instead:

pipe.enable_attention_slicing()

Does that work for you?

**Comment by UglyStupidHonest** [comment]
Works indeed thank you so much!!
