### ISSUE TITLE
BLIP-Diffusion don't support multi controlnet 

### ISSUE THREAD

**Issue by yanchaoguo** [huggingface/diffusers#5140]
how to use multiple controlnet in blip-diffusion case

**Comment by linnanwang** [comment]
@yanchaoguo what's multi controlnet? can you please be specific? Thnks

**Comment by yanchaoguo** [comment]
> @yanchaoguo what's multi controlnet? can you please be specific? Thnks

this :https://github.com/huggingface/diffusers/pull/4388 

don't use multiple controlnet in BlipDiffusionControlNetPipeline

**Comment by sayakpaul** [comment]
Cc: @ayushtues

**Comment by ayushtues** [comment]
Will need to modify the existing implementation to support multi-controlnet for BLIP-Diffusion, @sayakpaul do we want this feature addition? Can pick it up if needed

**Comment by ayushtues** [comment]
@linnanwang an example of Multi-controlnet is : https://github.com/huggingface/diffusers/blob/c78ee143e9d3cb52147cbdcda13707d02f96961c/src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py#L997

**Comment by sayakpaul** [comment]
If you find some cool results, I don't mind having it.
