### ISSUE TITLE
Configure for checkpoints saving number

### ISSUE THREAD

**Issue by deJQK** [huggingface/diffusers#5141]
Checkpoint files saving number can be controlled by modifying [this line](https://github.com/huggingface/diffusers/blob/main/examples/instruct_pix2pix/train_instruct_pix2pix.py#L387) to
```
accelerator_project_config = ProjectConfiguration(
        total_limit=args.checkpoints_total_limit,
        automatic_checkpoint_naming=args.checkpoints_total_limit is not None,
        project_dir=args.output_dir,
        logging_dir=logging_dir
    )
```
without the need of [these lines](https://github.com/huggingface/diffusers/blob/main/examples/instruct_pix2pix/train_instruct_pix2pix.py#L872-L884).

**Comment by patrickvonplaten** [comment]
Sure! Do you want to open a PR to improve it here @deJQK ? :-)

**Comment by deJQK** [comment]
Thanks @patrickvonplaten . I am not familiar with git command and do not yet know how to open a PR. Could you please kindly help me do it or directly modify the code? Thanks!

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md
