### ISSUE TITLE
dimension mismatch errror

### ISSUE THREAD

**Issue by linnanwang** [huggingface/diffusers#5142]
### Describe the bug

            images = self._pipe(
                prompt_embeds=conditioning_prompt,
                pooled_prompt_embeds=pooled_prompt,
                negative_prompt_embeds=conditioning_neg_prompt,
                negative_pooled_prompt_embeds=pooled_neg_prompt,
                height=res[0],
                width=res[1],
                num_images_per_prompt=num_images,
                output_type="latent",
                num_inference_steps=INFER_STEP,
            ).images
            images = self._refiner_pipe(
                 prompt_embeds=conditioning_prompt,
                 pooled_prompt_embeds=pooled_prompt,
                 negative_prompt_embeds=conditioning_neg_prompt,
                 negative_pooled_prompt_embeds=pooled_neg_prompt,
                 denoising_start=high_noise_frac,
                 num_images_per_prompt=num_images,
                 num_inference_steps=REFINE_STEP,
                 image=images,
             ).images

There will be a dimension mismatch error in the refiner step. Please check thank you. If you use text prompt, it should be fine, but raised error when you use text embedding.

### Reproduction

see above codes.

### System Info

the latest diffusers 

### Who can help?

@patrickvonplaten @sayakpaul @williamberman

**Comment by sayakpaul** [comment]
Check https://github.com/huggingface/diffusers/issues/5075#issuecomment-1723348256
