### ISSUE TITLE
same data input to the unet network，the result is tiny different，which cause the different of the output img。

### ISSUE THREAD

**Issue by tnickMoxuan** [huggingface/diffusers#5143]
### Describe the bug

same data input to the unet network，the result is tiny different，which cause the different of the output img。
![image](https://github.com/huggingface/diffusers/assets/120445480/4a0880ca-1712-4fbe-a9b7-329d6a49724b)

### Reproduction

![image](https://github.com/huggingface/diffusers/assets/120445480/59f1897a-76b8-4934-9d1f-3b570a5fd7df)

### System Info

diffuser version is 0.21.1

**Comment by patrickvonplaten** [comment]
Sorry I really don't understand the issue here, could you maybe add a reproducible code snippet showing the bug?
