### ISSUE TITLE
StableDiffusionUpscalePipeline does not implement `from_single_file` method

### ISSUE THREAD

**Issue by vladmandic** [huggingface/diffusers#5150]
### Describe the bug

Exactly as title suggests - pipeline `StableDiffusionUpscalePipeline` does not implement `from_single_file` method so loading from safetensors is not possible.

### Reproduction

attempt to load a model from safetensors.

### Logs

```shell
N/A
```

### System Info

diffusers==0.21.2

### Who can help?

@williamberman @patrickvonplaten @sayakpaul

**Comment by patrickvonplaten** [comment]
Yes, we can add this one @DN6 can you take a look here?

**Comment by vladmandic** [comment]
btw, this also applies to StableDiffusionLatentUpscalePipeline (used for x2 model)

**Comment by DN6** [comment]
Hi @vladmandic would you mind sharing a code snippet of how you're trying to load the safetensors model? Are you loading the model locally or pulling from the hub?

**Comment by vladmandic** [comment]
@DN6 i'm not sure i understand - i'm talking about using `from_single_file` which is not implemented for those models.
using `from_pretrained` works just fine, either from local storage or from hub - but thats not a single safetensors model format.

**Comment by DN6** [comment]
@vladmandic Sorry for the confusion. Fix has been merged to main.
