### ISSUE TITLE
Würstchen bug in 0.21.3 alpha

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#5152]
### Describe the bug

Generating an image with Würstchen 1024x1024 causes the error in the log.

### Reproduction

Generating an image with Würstchen 1024x1024 causes the error in the log.

### Logs

```shell
File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\configuration_utils.py", line 636, in inner_init
    init(self, *args, **init_kwargs)
  File "C:\Users\45239\AppData\Roaming\Python\Python310\site-packages\diffusers\schedulers\scheduling_ddpm_wuerstchen.py", line 113, in __init__
    self._init_alpha_cumprod = torch.cos(self.s / (1 + self.s) * torch.pi * 0.5) ** 2
RuntimeError: "cos_vml_cpu" not implemented for 'Half'
```

### System Info

Diffusers 0.21.3 alpha
Win 11

**Comment by patrickvonplaten** [comment]
Hey @tin2tin, 

Could you maybe add a reproducible code snippet? It looks very much like you're running a fp16 operation on CPU here, you should probably make sure your pipeline is on GPU

**Comment by tin2tin** [comment]
Could be my GPU going shaky on me. Can't reproduce now. Closing.
