### ISSUE TITLE
FreeU: Free Lunch in Diffusion U-Net

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#5153]
### Model/Pipeline/Scheduler description

FreeU, a method that substantially improves diffusion model sample quality at no costs: no training, no additional parameter introduced, and no increase in memory or sampling time.

Promising results on image and video generation tasks demonstrate that our FreeU can be readily integrated to existing diffusion models, e.g., Stable Diffusion, DreamBooth, ModelScope, Rerender and ReVersion, to improve the generation quality with only a few lines of code. All you need is to adjust two scaling factors during inference.

![image](https://github.com/huggingface/diffusers/assets/1322593/d6421dd4-b116-423d-9039-ce96560ee6c3)

https://github.com/huggingface/diffusers/assets/1322593/14526120-26ce-4c5a-8e1e-4ae1f97eb50e

The code is in the readme here:
https://github.com/ChenyangSi/FreeU

### Open source status

- [X] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://chenyangsi.top/FreeU/
https://github.com/ChenyangSi/FreeU

**Comment by tin2tin** [comment]
Camenduru did a quick fork here with the implementation for SD 1.5 here: https://github.com/Stability-AI/stablediffusion/compare/main...camenduru:stablediffusion:FreeU

**Comment by adhikjoshi** [comment]
Diffusers implementation available?
