### ISSUE TITLE
Script to convert a folder checkpoint to .safetensors

### ISSUE THREAD

**Issue by segalinc** [huggingface/diffusers#5162]
**Is your feature request related to a problem? Please describe.**
I have trained a stable diffusion but the text2image.py script doesn't return a model_xxx.safetensors for the checkpoint but all separate .bin and unet, optimizer, scheduler files. 

the request is a script from 
checkpoint-10000
|-- unet
|-----config.json
|-----diffusion_pytorch_model.safetensors
|-----index.html
|---unet_ema
|-----config.json
|-----diffusion_pytorch_mdoe.safetensors
|-----index.html
|--index.html
|--optimizer.bin
|--random_states_0.pkl
|--scheduler.bin

to
model_10000.safetensors

**Describe the solution you'd like**
A convert_checkpoint_to_safetensor.py script that is different from converting .ckpt to .safetensor

**Describe alternatives you've considered**
no alternatives

**Additional context**

**Comment by sayakpaul** [comment]
Here's the file you're looking for `diffusion_pytorch_mdoe.safetensors`. 

If you want to load it back into the UNet, you could just do:

```python
your_unet_class.from_pretrained("absolute_path")
```

Here's an example:

```python
my_unet = UNet2DConditionModel.from_pretrained("checkpoint-1000/unet")
```

**Comment by segalinc** [comment]
so I should just 
```
base = DiffusionPipeline.from_pretrained(
                                          'runwayml/stable-diffusion-v1-5',
                                          variant="fp16",
                                          use_safetensors=True,
                                          torch_dtype=torch.float16,
                                          unet=my_unet)

```

what if I need to use this model in AUTO1111?
that would be the ultimate purpose so this wouldn't work I think

**Comment by segalinc** [comment]
also based on the text_to_image.py you then have to convert it to diffuser folder structure checkpoint first as it won't find the VAE or config

**Comment by sayakpaul** [comment]
You use https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion.py script to convert to a single checkpoint, but we don't guarantee their correctness nor do we maintain them.

**Comment by segalinc** [comment]
Ok I'll give it a try.. I am already looking into different version of this but there is always something not matching or working properly
