### ISSUE TITLE
Inconsistent Results Between AUTOMATIC1111 UI and Diffusers Package Implementation of ControlNet

### ISSUE THREAD

**Issue by sebi75** [huggingface/diffusers#5163]
**Summary**

ControlNet does not seem to function identically between AUTOMATIC1111's UI and an implementation using the Diffusers package, despite using identical configuration and models. When using Diffusers, shapes overflow unexpectedly from the main object being inpainted, which is not the case when using AUTOMATIC1111's UI.

**Steps to Reproduce**

Use the same models and settings for both AUTOMATIC1111's UI and an implementation using the Diffusers package.
Generate results using ControlNet in both environments.
Compare the generated shapes.

**Expected Behavior**
The generated shapes should not overflow from the main object when using ControlNet in both AUTOMATIC1111's UI and the Diffusers package.

**Actual Behavior**
Shapes overflow unexpectedly from the main object when using the Diffusers package, while the shapes are well-controlled in AUTOMATIC1111's UI.

**Questions**

Are there any known issues that might explain this behavior?
Is there an estimated time for a fix?

_Thank you for looking into this issue._

**Comment by linnanwang** [comment]
@sebi75 can you please paste some image comparisons? thanks

**Comment by sebi75** [comment]
@linnanwang 
Yes, of course.
And these results are consistent in the same way: Automatic111 produces constantly expected results, and diffusers implementation produces results always with this exact flaw.

**Automatic1111** result:
![00056-award winning product photography, RAW photo(low angle)1 3, a bottle emerging from ripples in a lake surrounded by plants and fl](https://github.com/huggingface/diffusers/assets/36008268/bc12e880-51f4-450c-b953-416fdd5a4e29)

**Diffusers** result:
![example-diffusers](https://github.com/huggingface/diffusers/assets/36008268/8fece99b-e81b-4bfb-b8dd-b5a32b86f7b5)

**Comment by patrickvonplaten** [comment]
Hey @sebi75,

Could you please add a code snippet of the diffusers code you're using? Would like to get behind this issue. Might also be related to: https://github.com/huggingface/diffusers/issues/3959#issuecomment-1719589059

**Comment by sebi75** [comment]
Hey @patrickvonplaten 
Thanks for hopping onto this issue so fast, of course.
`
from diffusers import StableDiffusionControlNetInpaintPipeline, EulerAncestralDiscreteScheduler, ControlNetModel
import PIL
import controlnet_hinter

rgba_init_image: PIL.Image.Image = "rgbaImageURL" # load image with PIL from image url
image_mask = create_image_mask(rgba_init_image) # image with the object black and the transparent pixels white

def flatten(self, img, bgcolor="#ffffff"):
        if img.mode == "RGBA":
            background = Image.new('RGBA', img.size, bgcolor)
            background.paste(img, mask=img)
            img = background

        return img.convert('RGB')

dtype = torch.float16
controlnet_canny_model_id = "lllyasviel/sd-controlnet-canny"

controlnet = ControlNetModel.from_pretrained(
            controlnet_canny_model_id, torch_dtype=dtype).to("cuda")

controlnet_inpaint_pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
            self.sd_real_cache,
            controlnet=controlnet,
            torch_dtype=dtype,
            safety_checker=None,
        )
controlnet_inpaint_pipe.to("cuda")

controlnet_inpaint_pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(
            controlnet_inpaint_pipe.scheduler.config)

generator = torch.Generator(device="cpu").manual_seed(3)

init_image = flatten(rgba_init_image)
control_image = controlnet_hinter.hint_canny(
                rgba_init_image, width=512, height=512, low_threshold=100, high_threshold=200
            )

output = controlnet_inpaint_pipe(image=rgba_init_image,
mask_image=image_mask,
width=512, height=512,
strength=1.0,
prompt,
negative_prompt,
guidance_scale=1.0,
num_inference_steps=40,
control_image=control_image,
controlnet_conditioning_scale=1.0,
control_guidance_start=0.0,
control_guidance_end=1.0)
`

This is mainly the code that I used to always get such kind of results.

**Comment by yiyixuxu** [comment]
Hi @linnanwang 

Can you share the image and mask you used?

Thanks!

YiYi

**Comment by sebi75** [comment]
> Hi @sebi75
> 
> Can you share the image and mask you used?
> 
> Thanks!
> 
> YiYi

Hi @yiyixuxu
![mask](https://github.com/huggingface/diffusers/assets/36008268/b6afef01-d926-46c0-a6f8-45f3d5e4b2f8)
![rescaled-512](https://github.com/huggingface/diffusers/assets/36008268/a80d7d26-6b58-4198-95f3-22247bab7ad9)

**Comment by yiyixuxu** [comment]
@sebi75 thank you!!!

**Comment by tiago-falves** [comment]
I'm curious as well. It appears that Automatic1111 employs some form of preprocessing. For creating a Python API, is utilizing a diffuser the most optimal approach? Alternatively, should I operate Automatic1111 on a server and access its API directly? Which method offers quicker performance? Also, do they yield varying results?

**Comment by babyta** [comment]
![test1](https://github.com/huggingface/diffusers/assets/37787795/e726e734-3ca7-4d83-9f68-6091425c522c)
Hello, I used your code and the results were even more outrageous. How do I generate a realistic background?

**Comment by yiyixuxu** [comment]
@babyta increase your guidance scale if you want better background :)

**Comment by yiyixuxu** [comment]
not stale always fresh........

**Comment by babyta** [comment]
StableDiffusionControlNetInpaintPipeline  Do you have any good suggestions on optimizing this pipeline, such as using tensorrt?
