### ISSUE TITLE
SDXL Pretrain on 400K dataset

### ISSUE THREAD

**Issue by linnanwang** [huggingface/diffusers#5165]
### Describe the bug

Hello there, 

I have collected 400K images and prompts and trying to pretrain a SDXL using the diffuser scripts. However, the current script is crazily slow in mapping stage. When I add num_procs in map to 10, there is another cuda error. Then I set spawn process, another error. 

So, does the current script support for large scale dataset training? I'm using a folder with 400K images and a meta json file. Any suggestions to improve it? Thank you.

### Reproduction

please see above

### System Info

none

### Who can help?

@williamberman @sayakpaul thanks

**Comment by sayakpaul** [comment]
For large-scale training please repurpose https://github.com/huggingface/diffusers/blob/main/examples/research_projects/controlnet/train_controlnet_webdataset.py.
