### ISSUE TITLE
Missing scaling factor of vqvae in unconditional ldm pipeline

### ISSUE THREAD

**Issue by asparius** [huggingface/diffusers#5166]
### Describe the bug

After encoding the images by the vae, the resulting latent is multiplied by its scaling factor. However, when latents are created after denoising they don't get multiplied by the inverse of the scaling factor in the unconditional pipeline which leads to garbage results if it is not added manually. I suspect it is a bug because scaling and inverse scaling are necessary to the best of my knowledge, please correct me if otherwise. The below function is the encoding function in training.

### Reproduction

def pil_to_latent_torch(input_im):
    with torch.no_grad():
        latent = vae.encode(input_im.to(torch_device) *2 -1) # 
    return 0.13215 * latent.latent_dist.sample() # 0.1325 is the scaling factor of sdxl vae

### System Info

- `diffusers` version: 0.21.1
- Platform: Linux-3.10.0-693.11.6.el7.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.8
- PyTorch version (GPU?): 2.0.1+cu117 (False)
- Huggingface_hub version: 0.17.1
- Transformers version: 4.33.1
- Accelerate version: 0.23.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
Hey @asparius,

Thanks for the issue - would you like to open a PR? :-)

**Comment by asparius** [comment]
@patrickvonplaten I would be glad to help, could you point out to the official documentation for the contribution?
