### ISSUE TITLE
Remove Lora after loading it

### ISSUE THREAD

**Issue by linnanwang** [huggingface/diffusers#5170]
**Is your feature request related to a problem? Please describe.**
Hello there, not sure if this feature has been implemented or not, is there an api that removes lora after loading it? Thanks.

**Comment by sayakpaul** [comment]
Yeah. If you used `fuse_lora()`, then use `unfuse_lora()`. Note that `unfuse_lora()`'s support is only limited to a single active LoRA at the moment.

**Comment by neue** [comment]
unfuse_lora doesn't return the model to the pure state before the fuse. 

If you generate with the same seed a raw image, then run the same code where a lora is fused and unfused before generation the two images will be slightly different.
