### ISSUE TITLE
CIVITAI Safetensors LoRA works worse on latest diffusers compared to 0.18.2 for SD1.5

### ISSUE THREAD

**Issue by sarmientoj24** [huggingface/diffusers#5191]
### Describe the bug

I noticed that when I use some LoRA from CIVITAI, it 
- breaks the image when using latest diffusers
- but does not necessarily work on 0.18.2 (but does not break the image)
- in 0.18.2, loading LoRA **but not using it in prompt** does not **automatically** gets applied to the image
- in latest LoRA, even without using the `<lora:LORA_HERE:1.2>`, it still uses the LoRA in the image
- I was testing some LoRA, and for example, a LoRA that changes "breast sizes" have generated images only focus on breast and crops the face (for latest diffusers). meanwhile, for 0.18.2, it doesnt break the image but the LoRA doesnt seem to apply properly in the image (LoRA is basically useless)

### Reproduction

Use diffusers 0.18.2 and diffusers latest and compare LoRA

I also use this
```
LPWStableDiffusionPipeline = get_class_from_dynamic_module("lpw_stable_diffusion", module_file="lpw_stable_diffusion.py")
pipeline = LPWStableDiffusionPipeline(**pipeline.components)

scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config, use_karras_sigmas=True, algorithm_type='sde-dpmsolver++')
```

### System Info

diffusers 0.18.2 vs latest

**Comment by sayakpaul** [comment]
`LPWStableDiffusionPipeline` is a custom pipeline that we don't maintain. Please tag the author of the pipeline for that. 

> in 0.18.2, loading LoRA but not using it in prompt does not automatically gets applied to the image

It might very well be a silent bug. 

> in latest LoRA, even without using the <lora:LORA_HERE:1.2>, it still uses the LoRA in the image

If you used `load_lora_weights()` and didn't unload the weights then LoRA will get applied until and unless you specify `scale` to be 0 via `cross_attention_kwargs` during your pipeline call. We don't support prompt weighting natively in `diffusers`. So, formats like "<lora:LORA_HERE:1.2>" in prompts are a no-op.

**Comment by sarmientoj24** [comment]
is there a way to use `cross_attention_kwargs` for specific LoRAs then?

**Comment by sarmientoj24** [comment]
Say I have 5 Loras and i'm gonna use the prompt

**Comment by sayakpaul** [comment]
I think we're deviating from the issue topic here but yes, what you are asking for is possible. 

Check out: https://huggingface.co/docs/diffusers/main/en/training/lora#working-with-multiple-lora-checkpoints

**Comment by sarmientoj24** [comment]
@sayakpaul i am confused that in that doc, loaded and fused loras are already "activated" yet the prompt still has `<lora:kame_sdxl_v2:1>`

why?
