### ISSUE TITLE
Unloading specific LORA from loaded LORAs

### ISSUE THREAD

**Issue by sarmientoj24** [huggingface/diffusers#5195]
I know that there is an `unload_lora_weights` function that exist. But is it possible to unload specific LORAs in the pipeline?
Too many LORAs loaded mess the image.

Also, it seems like Loading the LORA and not using it in the prompt already changes the image that it seemingly use the LoRA.

**Comment by patrickvonplaten** [comment]
Multi-adapter LoRA is in the making, but not yet available. The next release will surely include it :-)

**Comment by sarmientoj24** [comment]
Thanks @patrickvonplaten appreciate your work.
will it have the same use as A1111? One thing i noticed is that i can use two loras on my first generate, then a different lora on the next and the lora that was used before doesn't affect the second time I generate with a different lora. bottomline is, the LoRA only gets loaded when it is in the prompt. 

Or are they just doing the loading under the hood?
