### ISSUE TITLE
Repaint + ControlNet (+ LoRA/text inversion) with StableDiffusion

### ISSUE THREAD

**Issue by uminaty** [huggingface/diffusers#5205]
### Model/Pipeline/Scheduler description

I have implemented a pipeline in order to be able to use at the same time ControlNet and Repaint (a method that doesn't require a specific inpainting model).

Specifically, I started from StableDiffusionRepaintPipeline and adapted it to ControlNet.

Would it be interesting to add it ? If yes where and how ? 

I hadn't found this pipeline so I made it myself, but it may already exist !

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by 2018zhaizhijun** [comment]
> ### Model/Pipeline/Scheduler description
> I have implemented a pipeline in order to be able to use at the same time ControlNet and Repaint (a method that doesn't require a specific inpainting model).
> 
> Specifically, I started from StableDiffusionRepaintPipeline and adapted it to ControlNet.
> 
> Would it be interesting to add it ? If yes where and how ?
> 
> I hadn't found this pipeline so I made it myself, but it may already exist !
> 
> ### Open source status
> * [ ]  The model implementation is available
> * [ ]  The model weights are available (Only relevant if addition is not a scheduler).
> 
> ### Provide useful links for the implementation
> _No response_

Hi, it's a wonderful work. I'm also seeking for adapting StableDiffusionRepaintPipeline to ControlNet, could you share your implementation with me? Thanks a lot!

**Comment by uminaty** [comment]
Hi @2018zhaizhijun, thanks for your interest !

Unfortunately, I don't have access to this code anymore, I'll check with my former colleagues to see if they've kept it.
