### ISSUE TITLE
SDXL Controlnet&T2IAdapter Script generates black images for validation set

### ISSUE THREAD

**Issue by nbardy** [huggingface/diffusers#5209]
### Describe the bug

![image](https://github.com/huggingface/diffusers/assets/1278972/14d9c30c-b739-4510-9b61-cbf7b71874d5)

Running the train script for SDXL t2i_adapter with the default setting and  getting black results for the validation images.

### Reproduction

Here's the notebook I'm using:

https://colab.research.google.com/drive/1kzxpHKJoEDesZq2QoK4j4ERcx2ZeK5Ud?usp=sharing

### Logs

```shell
https://wandb.ai/nbardy-facet/sd_xl_train_t2iadapter/runs/icm2hfbt?workspace=user-nbardy-facet
```

### System Info

Google Colab A100

### Who can help?

@sayakpaul @patrickvonplaten 

Wondering if this was working or if it's still a WIP.

**Comment by nbardy** [comment]
![image](https://github.com/huggingface/diffusers/assets/1278972/640693ce-147d-4cd4-af20-1124497d3ad8)

Same issue is happening with the Controlnet script. Going to see if I can debug it.

**Comment by sayakpaul** [comment]
Have you tried using a better VAE? 

https://github.com/huggingface/diffusers/blob/main/examples/controlnet/README_sdxl.md#specifying-a-better-vae

**Comment by nbardy** [comment]
Thanks @sayakpaul.

This fixes it.

Makes sense to put this in the default command imo. 

Put up a PR here: https://github.com/huggingface/diffusers/pull/5223
