### ISSUE TITLE
I get a message that I need to specify `pad_to_multiple_of` when loading an embed.

### ISSUE THREAD

**Issue by suzukimain** [huggingface/diffusers#5212]
```python

pipe.load_textual_inversion("embed/negative",weight_name="EasyNegativeV2.safetensors",token="EasyNegative")
```

When I ran the code above, I got the following message How can I resolve this issue?
```
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embedding dimension will be 49539. This might induce some performance reduction as *Tensor Cores* will not be available. For more details about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
```

**Comment by segalinc** [comment]
have the same exact issue. have you solve it?

**Comment by suzukimain** [comment]
No, it could not be resolved.

**Comment by MrAnayDongre** [comment]
You need to provide `pad_to_multiple_of` parameter in the multiple of 8, 16 or 32 which will create a new embedding dimension for Tensor Cors. Make sure to further change your code according to the new embedding layer.

**Comment by patrickvonplaten** [comment]
BTW this is not an error but just a warning

**Comment by patrickvonplaten** [comment]
So everything will work just fine. I'll open a PR in transformers to make it less scary: https://github.com/huggingface/transformers/pull/26545

**Comment by segalinc** [comment]
I actually get an error when trying to generate the image so not just a warning. 
I don't know if it's incompatibility between the textual inversion model that was trained from SD1.5 and I am trying to use it on SDXL but I see in auto1111 they can do it

**Comment by karu03** [comment]
the 'pad_to_multiple_of' is an parameter which is used for padding to resize the embedding layer to use tensor cores for better performance

if you don't pass the arg it will give you the warning
"You are resizing the embedding layer without providing a pad_to_multiple_of parameter. This means that the new embedding dimension will be 268525. This might induce some performance reduction as Tensor Cores will not be available.

as @MrAnayDongre said

it uses int input EX: 4 (TF32) / 8 (FP16) / 16 (INT8) 32 (TF32) / 64 (FP16) / 128 (INT8)
it depends on the GPU architecture
for easy way
32 (TF32) / 64 (FP16) / 128 (INT8) is for high end GPU like A100

for more info visit this article by Nvidia:https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#

you can use this args in you code to resize the embedings as model.resize_token_embeddings(original_vocab_size,pad_to_multiple_of = 8
