### ISSUE TITLE
StableDiffusionUpscalePipeline changes brightness significantly when source image is dark

### ISSUE THREAD

**Issue by omegayal1234** [huggingface/diffusers#5215]
### Describe the bug

When using the StableDiffusionUpscalePipeline with the model "stabilityai/stable-diffusion-x4-upscaler"  to upscale image of low brightness, the overall brightness in the upscaled result changes a lot. 

input image:
![test](https://github.com/huggingface/diffusers/assets/136558089/0baf5d6f-ef59-4f91-83de-9d2333319736)

result image:
![test_out](https://github.com/huggingface/diffusers/assets/136558089/b72318f1-cd45-4c48-a223-475804f59e30)

In addition, the pipeline always shows the warning (no matter the brightness of the output image is correct or wrong):
The configuration file of the vae does not contain `scaling_factor` or it is set to 0.18215, which seems highly unlikely. If your checkpoint is a fine-tuned version of `stabilityai/stable-diffusion-x4-upscaler` you should change 'scaling_factor' to 0.08333 Please make sure to update the config accordingly, as not doing so might lead to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull Request for the `vae/config.json` file

### Reproduction

from diffusers import StableDiffusionUpscalePipeline
from diffusers.utils import load_image
import torch

model_id = "stabilityai/stable-diffusion-x4-upscaler"
pipeline = StableDiffusionUpscalePipeline.from_pretrained(
    model_id, revision="fp16", torch_dtype=torch.float16
)
pipeline = pipeline.to("cuda")

image = load_image("./test.png").convert("RGB")
output = pipeline(prompt="", image=image, num_inference_steps=20).images[0]
output.save("test_out.png")

### System Info

Python: 3.10.6
Platform: Linux db6dd98bfc33 5.4.0-159-generic #176-Ubuntu SMP Mon Aug 14 12:04:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
diffuser: 0.21.3
torch: 2.0.0+cu117

### Who can help?

@patrickvonplaten

**Comment by bghira** [comment]
very-dark images are a challenge for stable diffusion models.

can you try to set the scheduler config so that `timestep_spacing=trailing` and `rescale_betas_zero_snr=True` for the upscaler?

you can do this using `pipeline.scheduler = DDIMScheduler.from_pretrained(model_id, timestep_spacing='trailing', rescale_betas_zero_snr=True)`

**Comment by omegayal1234** [comment]
Thanks for the suggestion!
When using `pipeline.scheduler = DDIMScheduler.from_pretrained(model_id, timestep_spacing='trailing', rescale_betas_zero_snr=True)`, the following error will occur:

`pipeline.scheduler = DDIMScheduler.from_pretrained(model_id, timestep_spacing='trailing', rescale_betas_zero_snr=True)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_utils.py", line 140, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 397, in load_config
    raise EnvironmentError(
OSError: stabilityai/stable-diffusion-x4-upscaler does not appear to have a file named scheduler_config.json.`

If I change the code to:
`config = pipeline.scheduler.config`
`pipeline.scheduler = DDIMScheduler.from_config(config, timestep_spacing='trailing', rescale_betas_zero_snr=True)`
The result is good, i.e., the brightness is similar the the original image.

**Comment by bghira** [comment]
@patrickvonplaten maybe you want to bump the upscaler config so this is default

**Comment by bghira** [comment]
@omegayal1234 oops, i forgot `subdir='scheduler'` for my `from_pretrained`.
