### ISSUE TITLE
[HacktoberFest][Missing Docstrings] UNet2DConditionModel

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#5228]
This feature request is included in this years Diffusers' Hacktoberfest 👨‍💻! 

Hacktoberfest's purpose is to give upcoming open-source developers the opportunity to learn about open-source and programming by fixes simple issues (like this one).

**How to solve the issue**:

- 1. Every issue has a description further below explaining the problem. First, you should try to understand the issue.
- 2. Second, follow the [contribution guide](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md) to learn how to contribute to Diffusers.\
- 3. Claim this issue for you by opening a PR that links to this issue and writing "I am solving this issue in `<link-to-pr>`"
**Issue**

The [forward method of UNet2DConditionModel](https://github.com/huggingface/diffusers/blob/78a78515d64736469742e5081337dbcf60482750/src/diffusers/models/unet_2d_condition.py#L754) is missing a couple of docstrings, e.g. for `class_lables`, `attention_mask` ... -> can you add all the missing ones?

**Comment by Nandika-A** [comment]
Hello! I am working on this issue.

**Comment by a-r-r-o-w** [comment]
I've solved this in #5248.
