### ISSUE TITLE
[HacktoberFest][Missing Docstrings] Autoencoder `decode`

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#5230]
This feature request is included in this years Diffusers' Hacktoberfest 👨‍💻! 

Hacktoberfest's purpose is to give upcoming open-source developers the opportunity to learn about open-source and programming by fixes simple issues (like this one).

**How to solve the issue**:

- 1. Every issue has a description further below explaining the problem. First, you should try to understand the issue.
- 2. Second, follow the [contribution guide](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md) to learn how to contribute to Diffusers.\
- 3. Claim this issue for you by opening a PR that links to this issue and writing "I am solving this issue in `<link-to-pr>`"

**Issue**

The [decode method of AutoencoderKL](https://github.com/huggingface/diffusers/blob/78a78515d64736469742e5081337dbcf60482750/src/diffusers/models/autoencoder_kl.py#L283) is completely missing docstrings, can you add them?

**Comment by freespirit** [comment]
I am solving this issue in #5242
