### ISSUE TITLE
[HacktoberFest][Missing Docstrings] Adapters

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#5231]
This feature request is included in this years Diffusers' Hacktoberfest 👨‍💻! 

Hacktoberfest's purpose is to give upcoming open-source developers the opportunity to learn about open-source and programming by fixes simple issues (like this one).

**How to solve the issue**:

- 1. Every issue has a description further below explaining the problem. First, you should try to understand the issue.
- 2. Second, follow the [contribution guide](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md) to learn how to contribute to Diffusers.\
- 3. Claim this issue for you by opening a PR that links to this issue and writing "I am solving this issue in `<link-to-pr>`"

**Issue**

The forward methods of the adapter modles and nn.Modules, [e.g.](https://github.com/huggingface/diffusers/blob/78a78515d64736469742e5081337dbcf60482750/src/diffusers/models/adapter.py#L261) are completely missing docstrings, can you add them?

**Comment by mallikharjuna160003** [comment]
Working on it :)

**Comment by mallikharjuna160003** [comment]
Please assign to me

**Comment by Nandika-A** [comment]
I have solved this issue in #5253
