### ISSUE TITLE
Hacktoberfest!

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/diffusers#5232]
👨‍💻 **Hacktoberfest** is starting soon :heart_eyes: !

The purpose of Hacktoberfest is to give beginning, upcoming developers the opportunity to easily contribute to larger codebases and by doing so learning how to contribute to the open-source system.

Diffusers needs a 🧹 clean-up for the winter (doc strings, tests and more) so that we all have a more **pleasant** time working with the codebase. Do you want to help and by doing so learn how to contribute to Diffusers?

:point_right: Check out open **Hacktoberfest** feature requests [here](https://github.com/huggingface/diffusers/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) :slightly_smiling_face:

**Comment by nancy-singh10** [comment]
hey this is newbie 
plz assign me work under hacktoberfest @patrickvonplaten

**Comment by sparshstark** [comment]
Hello, please assign me an issue under hacktoberfest @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Feel free to just open a PR and link it to the Hacktoberfest issue: https://github.com/huggingface/diffusers/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest this way you're automatically assigned to the issue.

**Comment by kadirnar** [comment]
Hi @patrickvonplaten,

I have made many contributions to the diffusers library. I want to do more. But pipelines and scheduler codes seem complicated to me. I want to learn these. How should I start?

**Comment by patrickvonplaten** [comment]
https://www.youtube.com/watch?v=cS6JQpEY9cs

and then try to understand the different schedulers a bit more in-depth:
- https://arxiv.org/abs/2206.00364
- https://arxiv.org/abs/2010.02502
- https://arxiv.org/abs/2206.00927
