### ISSUE TITLE
on the textual inversion training colab, a way to output .bin file before the training is fully completed

### ISSUE THREAD

**Issue by ciaobnsr** [huggingface/diffusers#524]
since the training usually takes few hours, and for different datasets, objects or styles, you can adapt with different training parameters, is there a way to output the .bin -let's say- every 1000 steps or so?

that would be very useful to check if the training is going in a good direction and maybe you can economize your gpu/usage if you are happy with the results.
it's very frustrating when you are 1000steps to complete a 10000steps training and runtime disconnects ending with hours of hours of training gone without a checkpoint.

also the ability to somehow save and resume the training would be a dream.

**Comment by patrickvonplaten** [comment]
cc @patil-suraj

**Comment by isamu-isozaki** [comment]
HI! I implemented this for my project and I'm happy to make a pr here if you want! It can also log images at fixed intervals

**Comment by isamu-isozaki** [comment]
I think I did it here https://github.com/huggingface/diffusers/pull/645

**Comment by isamu-isozaki** [comment]
@patil-suraj Np! Glad to help.

**Comment by patrickvonplaten** [comment]
@patil-suraj - re-pinging you here

**Comment by isamu-isozaki** [comment]
@patrickvonplaten @patil-suraj hullo. I made a pr and I think it already got merged.
