### ISSUE TITLE
[HacktoberFest][Missing Docstrings] Würstchen

### ISSUE THREAD

**Issue by stevhliu** [huggingface/diffusers#5241]
This feature request is included in this year's Diffusers Hacktoberfest 🎃! 

Hacktoberfest's purpose is to give upcoming open-source developers the opportunity to learn about open-source and programming by fixing simple issues (like this one).

**How to solve the issue**:

- 1. Every issue has a description further below explaining the problem. First, you should try to understand the issue.
- 2. Second, follow the [contribution guide](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md) to learn how to contribute to Diffusers.\
- 3. Claim this issue for you by opening a PR that links to this issue and writing, "I am solving this issue in `<link-to-pr>`".

**Issue**

The Würstchen API docs are a bit out of sync. For example:

-  `prior_num_inference_steps=60` in `WuerstchenCombinedPipeline.__call__` but the [docstring](https://huggingface.co/docs/diffusers/main/en/api/pipelines/wuerstchen#diffusers.WuerstchenCombinedPipeline.__call__.prior_num_inference_steps) says it defaults to 30.
- The [`WuerstchenPriorPipeline`](https://huggingface.co/docs/diffusers/main/en/api/pipelines/wuerstchen#diffusers.WuerstchenPriorPipeline) is missing some arguments like `latent_mean`, `latent_std`, and `resolution_multiple`. The `height`, `width`, `num_inference_steps`, and `guidance_scale` in the `__call__` are also out of sync.
- The [`WuerstchenDecoderPipeline`](https://huggingface.co/docs/diffusers/main/en/api/pipelines/wuerstchen#diffusers.WuerstchenDecoderPipeline.__call__) also has the same issues in the `__call__` function where some of the parameters are not aligned with what's in the function signature.

**Comment by jgyfutub** [comment]
I am solving this issue

**Comment by barrynorthern-tf** [comment]
@jgyfutub remember to include the link to the PR
