### ISSUE TITLE
"module diffusers has no attribute CLIPImageProjection" happens again

### ISSUE THREAD

**Issue by lyleguo** [huggingface/diffusers#5246]
### Describe the bug

When trying to run the given demo example,
"module diffusers has no attribute CLIPImageProjection" error occurs again.

### Reproduction

the example in https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/gligen#diffusers.StableDiffusionGLIGENTextImagePipeline

### System Info

diffusers-0.21.4

**Comment by sayakpaul** [comment]
Cc: @DN6

**Comment by DN6** [comment]
Hi @lyleguo I think the fix for this didn't make it into the last release. If you install diffusers from source it should work. The fix will be included in the next release. 

In your virtual environment run: 
```
pip install --upgrade git+https://github.com/huggingface/diffusers.git
```

Then try running the example again.
