### ISSUE TITLE
[WinError 126]

### ISSUE THREAD

**Issue by luffylaf** [huggingface/diffusers#5247]
### Describe the bug

hello i cant solve this problem 
OSError: [WinError 126] Le module spécifié est introuvable. Error loading "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\lib\c10.dll" or one of its dependencies.
Appuyez sur une touche pour continuer...

### Reproduction

OSError: [WinError 126] Le module spécifié est introuvable. Error loading "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\lib\c10.dll" or one of its dependencies.
Appuyez sur une touche pour continuer...

### System Info

windows

### Who can help?

luffylaf

**Comment by a-r-r-o-w** [comment]
This does not seem like a problem with diffusers. Relevant links with mentions of having solved the issue:
- [1](https://discuss.pytorch.org/t/filenotfounderror-could-not-find-module-c10-dll/88422)
- [2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9929)
