### ISSUE TITLE
Missing docs in multiple diffusers/models files

### ISSUE THREAD

**Issue by a-r-r-o-w** [huggingface/diffusers#5249]
Multiple classes such as [this](https://github.com/huggingface/diffusers/blob/78a78515d64736469742e5081337dbcf60482750/src/diffusers/models/unet_2d_blocks.py#L1114) in the models directory are missing documentation or an explanation for what the different parameters mean, and sometimes type hints. Has it been done this way by choice to allow for a clean and direct code view? if not, I would be happy to take this up as an issue and write the docs.

**Comment by sayakpaul** [comment]
I think it was on purpose in some sense because these blocks are usually modified to accommodate different features. But maybe @patrickvonplaten can shed more light!

**Comment by patrickvonplaten** [comment]
Hey @a-r-r-o-w, 

Good point! Actually it would be amazing if all these blocks would have better type hints and doc strings - we simply forgot to add those when the library was created

**Comment by a-r-r-o-w** [comment]
Got it @patrickvonplaten! Will work on this and open a PR as soon as possible :rocket:

**Comment by a-r-r-o-w** [comment]
Hey @patrickvonplaten. After making changes to multiple files and viewing the diff, I find it really difficult to go over and review the changes I've made, and I think it would be the same for other reviewers. Should I open PRs one by one for the different files and would you like me to maintain a tracker for the different files like you did #287? This would also allow for other collaborators to open PRs with improvements on files that are yet to have type hints and docs added.

**Comment by DN6** [comment]
@a-r-r-o-w Go ahead and open smaller PRs for the type hints. And I can do a review.
