### ISSUE TITLE
Issue with diffusers training notebook when trying to load images from local disk

### ISSUE THREAD

**Issue by GeorvityLabs** [huggingface/diffusers#525]
### Describe the bug

![Screenshot from 2022-09-16 02-47-27](https://user-images.githubusercontent.com/58555432/190510599-c6731a78-bad7-4f30-8223-52a7c25a75e3.png)

### Reproduction

https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/training_example.ipynb

^notebook i used

### System Info

Ubuntu 20.04

**Comment by GeorvityLabs** [comment]
any thoughts on how this could be fixed @tmabraham

**Comment by GeorvityLabs** [comment]
@anton-l any suggestions on a fix for this

**Comment by GeorvityLabs** [comment]
^ here I am loading images from local disk , but since the format changes, it's giving this error .
what would be a potential fix ?

**Comment by GeorvityLabs** [comment]
fixed the issue , in the 
change 
dataset = load_dataset(config.dataset_name, data_dir="path")
to
dataset = load_dataset(config.dataset_name, data_dir="path",split="train")

**Comment by patrickvonplaten** [comment]
@anton-l could you check here whether we should update the training colab?
