### ISSUE TITLE
Website should have times when the pages were last updated

### ISSUE THREAD

**Issue by landmann** [huggingface/diffusers#5251]
I'm looking at the huggingface documentation [here](https://huggingface.co/docs/diffusers/using-diffusers/weighted_prompts#blending), but it seems this library is quite outdated and confusing. Sometimes it uses tuples, sometimes it uses lists, it's not clear. It also uses `blend`, but this [compel code](https://github.com/damian0815/compel) doesn't use `blend`.

**Comment by sayakpaul** [comment]
Cc: @mishig25

**Comment by patrickvonplaten** [comment]
@landmann please make sure to check the "main" part of the documentation: https://huggingface.co/docs/diffusers/main/en/index
