### ISSUE TITLE
[HacktoberFest] remove outdated schedulers

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#5257]
This feature request is included in this year's Diffusers Hacktoberfest 🎃! 

Hacktoberfest's purpose is to give upcoming open-source developers the opportunity to learn about open-source and programming by fixing simple issues (like this one).

**How to solve the issue**:

- 1. Every issue has a description further below explaining the problem. First, you should try to understand the issue.
- 2. Second, follow the [contribution guide](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md) to learn how to contribute to Diffusers.\
- 3. Claim this issue for you by opening a PR that links to this issue and writing, "I am solving this issue in `<link-to-pr>`".

**Issue**

[KarrasVeScheduler](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_karras_ve.py) and [ScoreSdeVpScheduler](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_sde_vp.py) are outdated and can be removed from the codebase, can you remove them?  you should:
1. create a `schedulers/deprecated/` folder
2. move these two schedulers to the folder
3. remove the relevant tests

**Comment by a-r-r-o-w** [comment]
Hi @yiyixuxu. I'm working on this issue at the moment. I have a few questions:
- Do the relevant tests need to removed completely or put into a deprecated folder as well?
- Should a deprecation warning be logged if the mentioned schedulers are used?
- Do any files in the `docs/` folder such as [this](https://github.com/huggingface/diffusers/blob/0c7cb9a61391710e57dc15e7dcd2d2b6e39ecdce/docs/source/en/_toctree.yml#L358) and [this](https://github.com/huggingface/diffusers/blob/main/docs/source/en/api/schedulers/stochastic_karras_ve.md) need to be updated or will it be handled automatically?

**Comment by yiyixuxu** [comment]
> Do the relevant tests need to removed completely or put into a deprecated folder as well?

let's remove the tests completely 

> Should a deprecation warning be logged if the mentioned schedulers are used?

I think I don't need a deprecation message. But we need to make sure users can still use these schedulers. e.g. we should make sure `from diffusers import KarrasVeScheduler` still works by updating the `__init__.py` files. e.g. we can change `from .scheduling_karras_ve import KarrasVeScheduler` to from `.deprecated.scheduling_karras_ve import KarrasVeScheduler`
https://github.com/huggingface/diffusers/blob/907fd91ce9532751c43c4cfd853e1d5d95bb929b/src/diffusers/schedulers/__init__.py#L147 

> Do any files in the docs/ folder such as [this](https://github.com/huggingface/diffusers/blob/0c7cb9a61391710e57dc15e7dcd2d2b6e39ecdce/docs/source/en/_toctree.yml#L358) and [this](https://github.com/huggingface/diffusers/blob/main/docs/source/en/api/schedulers/stochastic_karras_ve.md) need to be updated or will it be handled automatically?

we don't need to update doc 

cc @patrickvonplaten here

**Comment by Tjs002** [comment]
@yiyixuxu can i work on this?

**Comment by yiyixuxu** [comment]
@Tjs002 
Thanks for volunteering! we have already received a PR on this issue though
please checkout other beginner-friendly issues you can work on here 🤗🤗🤗🤗🤗🤗🤗🤗https://github.com/huggingface/diffusers/labels/hacktoberfest
