### ISSUE TITLE
[HacktoberFest] make fast test for `StableDiffusionControlNetImg2ImgPipeline` smaller when applicable

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#5264]
This feature request is included in this year's Diffusers Hacktoberfest 🎃! 

Hacktoberfest's purpose is to give upcoming open-source developers the opportunity to learn about open-source and programming by fixing simple issues (like this one).

**How to solve the issue**:

- 1. Every issue has a description further below explaining the problem. First, you should try to understand the issue.
- 2. Second, follow the [contribution guide](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md) to learn how to contribute to Diffusers.\
- 3. Claim this issue for you by opening a PR that links to this issue and writing, "I am solving this issue in `<link-to-pr>`".

**Issue**

We want to run our fast tests run faster. But what is a fast test for a pipeline, though? 

This class holds all fast tests here: https://github.com/huggingface/diffusers/blob/4f74a5e1f7d9274931f8d782864f769266a24ecf/tests/pipelines/controlnet/test_controlnet_img2img.py#L63

The idea of this issue is to try to identify if the pipeline components (such as the UNet, text encoder, VAE) could be made smaller without disturbing the correctness of the tests. 

For example, could we reduce the number of blocks in the UNet? This is how the UNet is initialized:

https://github.com/huggingface/diffusers/blob/4f74a5e1f7d9274931f8d782864f769266a24ecf/tests/pipelines/controlnet/test_controlnet_img2img.py#L74

Similar idea could be applied to the [ControlNetModel](https://github.com/huggingface/diffusers/blob/4f74a5e1f7d9274931f8d782864f769266a24ecf/tests/pipelines/controlnet/test_controlnet_img2img.py#L85), [VAE](https://github.com/huggingface/diffusers/blob/4f74a5e1f7d9274931f8d782864f769266a24ecf/tests/pipelines/controlnet/test_controlnet_img2img.py#L102), and [text encoder](https://github.com/huggingface/diffusers/blob/4f74a5e1f7d9274931f8d782864f769266a24ecf/tests/pipelines/controlnet/test_controlnet_img2img.py#L111). 

Cc: @DN6

**Comment by p1kit** [comment]
Is this issue still open to be picked ??

**Comment by p1kit** [comment]
Raised a PR for the fix. Please have a look.
