### ISSUE TITLE
[HacktoberFest] Update Docs/README.md

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [huggingface/diffusers#5265]
**Is your feature request related to a problem? Please describe.**

For a REAME.md file, I think we can make use of the documentation styling in the programming language that is being used in the project, i.e. Python here.

**Describe the solution you'd like**

I think we can make the documentation better if we use 'py' styling in the README.md wherever it is applicable for linting.

**Describe alternatives you've considered**
 
I have added 'py' extension in the README.md code blocks.

**Additional context**

Existing README.md

![image](https://github.com/huggingface/diffusers/assets/63872951/e53ed486-f051-48e0-ae70-0cf15d035bf1)

README.md after my changes

![image](https://github.com/huggingface/diffusers/assets/63872951/c4cb6712-2215-4af5-a0fa-94a7a7dc7eeb)

Please suggest if I should raise a PR for the same.

Thank you!

**Comment by stevhliu** [comment]
Hi thanks for your suggestion, feel free to open a PR!
