### ISSUE TITLE
Possibility to add filters to the generation process (modifying latents at each step)

### ISSUE THREAD

**Issue by TimothyAlexisVass** [huggingface/diffusers#5268]
**Is your feature request related to a problem? Please describe.**
I've added filters to the inference process with a workaround solution.
It happens in the latent space.
It would be great if there was some similar solutio as `callback` called something like `modifying_callback` which would modify the latents at each step.

**Additional context**
The example below works similar to an unsharp mask.
I think the settings can be improved upon greatly (since using the ImageFilter.UnsharpMark from PIL will often give a better result), but it's promising.

The importance would be to open up the possibility to add filters to the process.
I think OpenCV may be a great candidate for this.

**[Example comparing sharpness = 2 and sharpness = 8 https://youtu.be/e2uf1_oQmGA](https://youtu.be/e2uf1_oQmGA)**
![2](https://github.com/huggingface/diffusers/assets/55708319/9efff6af-51e9-4786-b504-62b41857886b)
![8](https://github.com/huggingface/diffusers/assets/55708319/22e35eba-6998-4877-820f-50ee636f7441)

**Example with manually applied unsharp mask on the resulting png where sharpness was set to 2**
This was done with Pillow (PIL) ImageFilter `image.filter(ImageFilter.UnsharpMask(radius = 0.777, percent = 345, threshold = 0))`
![result](https://github.com/huggingface/diffusers/assets/55708319/83c6abb1-651c-4c2c-afb9-77e44c8c7cb1)

**Comment by patrickvonplaten** [comment]
Agree that we need this! Very much related to: https://github.com/huggingface/diffusers/issues/4778 and https://github.com/huggingface/diffusers/pull/5266

**Comment by patrickvonplaten** [comment]
It's mostly that we should think about how we can enable functionality in diffusers that allow the user to change different variables / states (guidance scale, prompt embeddings, unet output, ...) after each denoising step

**Comment by TimothyAlexisVass** [comment]
I don't suggest adding a `sharpness` parameter per say, but a sort of patching that could happen at each step.
Then, _one way_ to use that could be to implement the sampling sharpness filter, which may not actually be the best example as it has been currently implemented in Fooocus though. I have gotten better result by just using Unsharp mask and sharpness from the Pillow library on the resulting PIL data.

But, it would open up the possibility to implement sharpness, among other things, on the latents, rather than the decoded result.

**Comment by TimothyAlexisVass** [comment]
I think this is as simple as this:

Just like we have callback we could have a `modifier_callback`or whatever you want to call it... something like this:

```
def modifier_callback_function(steps, timesteps, latents):
    return my_filter_function(latents)

pipe("LOVE", modifier_callback=modifier_callback_function)
```

But instead of only performing some stuff in parallel with the pipeline, it modifies the latents before they are used in the next step.

**Comment by TimothyAlexisVass** [comment]
Here is an example which I made with Diffusers and the workaround method:
https://github.com/huggingface/diffusers/assets/55708319/a49823a8-69b2-4cbc-8e75-a9776f27ba62

It's changing between large values to illustrate the filter effect clearly.

**Comment by TimothyAlexisVass** [comment]
And here is another example using the filter in a different way:
**Smooth:**
![smooth](https://github.com/huggingface/diffusers/assets/55708319/e9c7c60a-7685-4117-9d65-aacc6d3258df)
**Regular(ish)**
![regularish](https://github.com/huggingface/diffusers/assets/55708319/2f526266-3a2f-49ac-8157-53a9d550e1c0)
**Extreme**
![extreme](https://github.com/huggingface/diffusers/assets/55708319/d81bdd2b-4aef-47a8-abe1-c4ee0c0ee376)

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu here

**Comment by TimothyAlexisVass** [comment]
Thank you @yiyixuxu and @patrickvonplaten for this implementation. 😄 
https://youtu.be/jjdrhIgLDvQ

**Comment by sayakpaul** [comment]
All @yiyixuxu! 

Please help us spread the word about the feature and thank you very much for sharing your awesome work! Keep it up :)
