### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by TimothyAlexisVass** [huggingface/diffusers#5270]
### Describe the bug

When trying to clear memory for a pipeline some is still in use.

### Reproduction

This becomes evident when we want to test and compare different Stable Diffusion checkpoints (have tried with SDXL).
```
import gc
import torch
def clear_memory(pipeline):
    pipeline.to('cpu')
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()
    torch.clear_autocast_cache()
    model=None

for model in ["checkpoint1", "checkpoint2", "checkpoint3"]:
    pipe = DiffusionPipeline.from_pretrained(f"{username}/{model}", use_safetensors=True)
    images = pipe("beauty", generator=torch.manual_seed(1338)).images
    clear_memory(pipeline)
    # VRAM used is increased with every iteration
```

### System Info

Diffusers 0.21.4

### Who can help?

@williamberman @patrickvonplaten @sayakpaul

**Comment by patrickvonplaten** [comment]
Hey @TimothyAlexisVass, 

I'm not sure to what extent this is a problem with diffusers or just generally with PyTorch. E.g. if you take the following code snippet:

```py
import torch
import gc

shape = (30_000, 30_000)

input = torch.randn(shape, device="cuda")


def clear_memory(model):
    model.to('cpu')
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()
    torch.clear_autocast_cache()

for _ in range(6):
    linear = torch.nn.Linear(*shape).to("cuda")
    output = linear(input)

    print("finished...")

    clear_memory(linear)
```

and you monitor GPU usage a bit with `nvidia-smi` you can see that after the first linear forward pass memory usage still increased. There is lots of such issues out in the wild: https://github.com/pytorch/pytorch/issues?page=4&q=is%3Aissue+gpu+memory+leak+is%3Aclosed or https://github.com/facebookresearch/detectron2/issues/1728 , so to me it seems a bit like PyTorch just hangs on top some GPU memory and will only release it if really necessary

**Comment by patrickvonplaten** [comment]
Hmm, but actually nevertheless, I can't really reproduce the problem. If you run:

```py
#!/usr/bin/env python3
import torch
import gc
from diffusers import DiffusionPipeline

shape = (30_000, 30_000)

input = torch.randn(shape, device="cuda")


def clear_memory(model):
    model.to('cpu')
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.ipc_collect()
    torch.clear_autocast_cache()

for _ids in ["runwayml/stable-diffusion-v1-5", "CompVis/stable-diffusion-v1-4", "runwayml/stable-diffusion-v1-5", "CompVis/stable-diffusion-v1-4", "runwayml/stable-diffusion-v1-5"]:
    pipe = DiffusionPipeline.from_pretrained(_ids, use_safetensors=True).to("cuda")
    pipe("hey", num_inference_steps=1)
    print("finished...")

    clear_memory(pipe)
```

Memory never peaks higher than it does after the first iteration.

**Comment by TimothyAlexisVass** [comment]
Perhaps it is isolated to SDXL? There are others who have pointed this out too:
https://discord.com/channels/879548962464493619/1023029736760426526

I will update with a minimal reproducible example.

**Comment by TimothyAlexisVass** [comment]
Interestingly enough, I haven't been able to reproduce this yet either.
@segalinc

**Comment by TimothyAlexisVass** [comment]
As far as I can deduce, this happens with notebook environments when defining the pipelines in one cell and doing inference in another. Then, when trying to redefine the pipelines in the previous cell, the memory isn't fully cleared.
I don't think this can be fixed by making changes in the Diffusers package...

It is true that there is some memory usage left after running clear_memory, but when I tested this, I got the same result as @patrickvonplaten.

Even though it differed between environments, the peak memory usage was the same and the remaining usage after clearing was also the same for each iteration.

**Comment by patrickvonplaten** [comment]
Ah yeah in Google Colabs memory mangement is a whole other issue. Could you maybe have a look into this notebook to see how we clear memory in Google Colabs to be sure the memory is correctly removed: https://colab.research.google.com/github/patrickvonplaten/notebooks/blob/master/Getting_the_most_out_of_LLMs.ipynb
(especially have a look at the `flush()` function)

**Comment by segalinc** [comment]
Thank you for the suggestion. I will have time next week to try as I have to work on another task rn.
The only difference I see from my "flush" is ` torch.cuda.reset_peak_memory_stats()`
My intention is to keep the pipe and clean up the model only. 
What I would expect is that the memory usage would go down to the initial amount used only by the pipe but as I load/unload different unet I see that even when flushing there is some residual memory that stays allocate and increase a bit over time
