### ISSUE TITLE
Question about flax model output classes

### ISSUE THREAD

**Issue by mishig25** [huggingface/diffusers#528]
For example here, it is using `from dataclasses import dataclass`
https://github.com/huggingface/diffusers/blob/d8b0e4f433778f9d4555cfab642e43db3aff4833/src/diffusers/models/unet_2d_condition_flax.py#L22-L23

But transformers equivalents use `@flax.struct.dataclass`. For example [here](https://github.com/huggingface/transformers/blob/21f6f58721dd9154357576be6de54eefef1f1818/src/transformers/models/bert/modeling_flax_bert.py#L63-L64)
```py
@flax.struct.dataclass
class FlaxBertForPreTrainingOutput(ModelOutput):
```

The benefit of using `@flax.struct.dataclass` over naive `python dataclass` is that: [`jax.jit` can consume @flax.struct.dataclass](https://github.com/huggingface/transformers/pull/11886)

So the question is: should we use `@flax.struct.dataclass`  on `diffusers` as well ?

**Comment by patil-suraj** [comment]
Good catch @mishig25 !

We should indeed use `@flax.struct.dataclass` here for flax outputs as you said it works well with JAX.

**Comment by pcuenca** [comment]
My mistake, I used `flax.struct.dataclass` for the schedulers but blindly copied the code here from the PyTorch version. Thanks a lot @mishig25, I'll fix it :)

**Comment by mishig25** [comment]
perfect!
