### ISSUE TITLE
ControlNet-LLLite support

### ISSUE THREAD

**Issue by mycodeiscat** [huggingface/diffusers#5284]
### Model/Pipeline/Scheduler description

Hi,
Is it possible to add support for ControlNet-LLLite to diffusers? The architecture is slightly different, but the results and performance look good.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

Documentation: [https://github.com/kohya-ss/sd-scripts/blob/main/docs/train_lllite_README.md](https://github.com/kohya-ss/sd-scripts/blob/main/docs/train_lllite_README.md)
Weights: [https://huggingface.co/kohya-ss/controlnet-lllite](https://huggingface.co/kohya-ss/controlnet-lllite)
ComfyUI node: [https://github.com/kohya-ss/ControlNet-LLLite-ComfyUI](https://github.com/kohya-ss/ControlNet-LLLite-ComfyUI)

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
How does this fare to T2I Adapters? Could you also write a more elaborate description of how it works, how are the results, etc.?

**Comment by ziniuwan** [comment]
any updates on this?

**Comment by mycodeiscat** [comment]
@sayakpaul 
>A single LLLite module consists of a conditioning image embedding that maps a conditioning image to a latent space and a small network with a structure similar to LoRA. The LLLite module is added to U-Net's Linear and Conv in the same way as LoRA. `
T2IAdapter guides generations more loosely, which results in different output variations. Its performance is comparable to other T2I Adapters while maintaining a closer resemblance to the control image.

Here's an example from Canny ControlNet; other examples look similar.
![xyz_grid-0004-1](https://github.com/huggingface/diffusers/assets/47571787/7caf8526-5b95-41b6-a4c4-f48a07f2e0c3)

**Comment by sayakpaul** [comment]
Thanks for sharing!

I am not entirely convinced that this adapter method is significantly better than ControlNets and T2I Adapters (in terms of the trade-off between performance and quality). So, not very keen on adding it. 

So, would like to request for a second opinion from @patrickvonplaten.

**Comment by mycodeiscat** [comment]
For anyone interested in using it, made an unofficial hack to use ControlNetLLLite with diffusers pipelines
[ControlNet-LLLite-diffusers](https://github.com/mycodeiscat/ControlNet-LLLite-diffusers)
