### ISSUE TITLE
A small spell issue

### ISSUE THREAD

**Issue by YourLights** [huggingface/diffusers#5294]
### Describe the bug

Hello! Thank you for spending time to deal with this little issue.

This spell issue comes from ("self.prcoessor.attention_op" in diffusers.models.attention_processor.__file__), and should be replaced to processor. I found it when trying train_text_to_image_lora.py script.

The diffusers.__version__=='0.21.4', but I have no ideal about the dev's condition.

By the way i wish there will have a huge simplification version of code in lora and something else, where the codes just replace the module components in transfomers attention (add property and cover forward function or something).

Thank you!

### Reproduction

python train_text_to_image_lora.py

### System Info

win10

**Comment by stevhliu** [comment]
Hi thanks for raising this issue, but I can't find the typo you're referring to. Do you mind providing a link?

https://github.com/huggingface/diffusers/blob/02a8d664a2a49289c4058d584b3694f3e4a1b0d2/src/diffusers/models/attention_processor.py#L388

**Comment by YourLights** [comment]
@stevhliu Thank you for spending times! This typo comes from https://github.com/huggingface/diffusers/archive/refs/tags/v0.21.4.zip/diffusers-0.21.4/src/diffusers/models/attention_processor.py  line:382. At that time i want to try the latest but not the dev version to solve the lora training on examples/text_to_image/train_text_to_image_lora.py.

**Comment by YourLights** [comment]
This is better: https://github.com/huggingface/diffusers/archive/refs/tags/v0.21.4.zip  ---unzip--> diffusers-0.21.4/src/diffusers/models/attention_processor.py line:382.

**Comment by stevhliu** [comment]
Oh I see now, the typo was fixed in #5066 and it should work if you update to the `main` version of the library :)
