### ISSUE TITLE
Why this package [diffusers] keep connecting the internet!

### ISSUE THREAD

**Issue by Louis24** [huggingface/diffusers#5300]
### Describe the bug

It takes two minutes to connect to the Internet every time, and I have already downloaded it, so the local files

### Reproduction

It takes two minutes to connect to the Internet every time, and I have already downloaded it, so the local files

### System Info

Not related

### Who can help?

@patrickvonplaten

**Comment by stevhliu** [comment]
Hi, if you're specifying the directory path to the local files nothing should be downloaded (assuming you're referring to model weights because I'm not sure what you're trying to load):

```py
pipeline = DiffusionPipeline.from_pretrained("./stable-diffusion-v1-5")
```

**Comment by DN6** [comment]
@Louis24 If you have downloaded the files onto your machine, you can use @stevhliu's suggestion to load files locally. Alternatively you can set the `cache_dir` argument in `from_pretrained` to the folder with your models.

**Comment by patrickvonplaten** [comment]
@Louis24 if you don't want to connect to the internet you can disable it by setting a global flag: 
`export HF_HUB_OFFLINE=True`

**Comment by Louis24** [comment]
> HF_HUB_OFFLINE

Thanks, I have change 3 Envs but still get 
os.environ['HF_DATASETS_OFFLINE'] = '1'
os.environ['TRANSFORMERS_OFFLINE'] = '1'
os.environ['HF_HUB_OFFLINE'] = '1'

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000145E1028B50>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

I have prepare all the weight in the specific folders.

However the code run smoothly before  I reinstalled my computer. Did I lose some kind of authentication for huggingface?

**Comment by bghira** [comment]
need some kind of reproducer if possible

**Comment by Louis24** [comment]
`import os
import torch
import diffusers

os.environ['HF_DATASETS_OFFLINE'] = '1'
os.environ['TRANSFORMERS_OFFLINE'] = '1'
# os.environ['HF_HUB_OFFLINE'] = '1'
# os.environ['CURL_CA_BUNDLE'] = ''

# https://huggingface.co/docs/transformers/installation#offline-mode

print(torch.__version__)
print(diffusers.__version__)


def infer(base_model, lora_model, prompt, negative_prompt, width, height, guidance_scale, num_inference_steps,
          num_images_per_prompt):
    pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
                                                              torch_dtype=torch.float16,
                                                              use_safetensors=True,
                                                              safety_checker=None,
                                                              load_safety_checker=False,
                                                              requires_safety_checker=False)

    pipe.load_lora_weights(lora_model)
    # pipe.vae = diffusers.AutoencoderKL.from_pretrained("C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors.safetensors")
    # pipe.scheduler = diffusers.schedulers.DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)
    pipe = pipe.to("cuda")

    print("Load Finished")

    while True:
        print("TYPE PROMPT OR ... TO STOP")
        x = input()

        if "..." in prompt:
            print("BYE")
            break

        image = pipe(prompt=prompt + x,
                     negative_prompt=negative_prompt,
                     width=width,
                     height=height,
                     guidance_scale=guidance_scale,
                     num_inference_steps=num_inference_steps,
                     num_images_per_prompt=num_images_per_prompt).images

        for i in range(len(image)):
            image[i].save(f"{x}-{i}.png")


if __name__ == '__main__':
    infer(base_model="C:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\models/Stable-diffusion/realisticVision.safetensors",
          lora_model="C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/models/Lora/Fox.safetensors",
          prompt="masterpiece, best quality, top quality, ultra highres, 8k hdr, 8k wallpaper, ",
          negative_prompt="lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry",
          width=512,
          height=512,
          guidance_scale=7,
          num_inference_steps=25,
          num_images_per_prompt=4)
`

**Comment by Louis24** [comment]
'''
import os
import torch
import diffusers

os.environ['HF_DATASETS_OFFLINE'] = '1'
os.environ['TRANSFORMERS_OFFLINE'] = '1'
# os.environ['HF_HUB_OFFLINE'] = '1'
# os.environ['CURL_CA_BUNDLE'] = ''

# https://huggingface.co/docs/transformers/installation#offline-mode

print(torch.__version__)
print(diffusers.__version__)


def infer(base_model, lora_model, prompt, negative_prompt, width, height, guidance_scale, num_inference_steps,
          num_images_per_prompt):
    pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
                                                              torch_dtype=torch.float16,
                                                              use_safetensors=True,
                                                              safety_checker=None,
                                                              load_safety_checker=False,
                                                              requires_safety_checker=False)

    pipe.load_lora_weights(lora_model)
    # pipe.vae = diffusers.AutoencoderKL.from_pretrained("C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors.safetensors")
    # pipe.scheduler = diffusers.schedulers.DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)
    pipe = pipe.to("cuda")

    print("Load Finished")

    while True:
        print("TYPE PROMPT OR ... TO STOP")
        x = input()

        if "..." in prompt:
            print("BYE")
            break

        image = pipe(prompt=prompt + x,
                     negative_prompt=negative_prompt,
                     width=width,
                     height=height,
                     guidance_scale=guidance_scale,
                     num_inference_steps=num_inference_steps,
                     num_images_per_prompt=num_images_per_prompt).images

        for i in range(len(image)):
            image[i].save(f"{x}-{i}.png")


if __name__ == '__main__':
    infer(base_model="C:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\models/Stable-diffusion/realisticVision.safetensors",
          lora_model="C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/models/Lora/Fox.safetensors",
          prompt="masterpiece, best quality, top quality, ultra highres, 8k hdr, 8k wallpaper, ",
          negative_prompt="lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry",
          width=512,
          height=512,
          guidance_scale=7,
          num_inference_steps=25,
          num_images_per_prompt=4)
'''

**Comment by Louis24** [comment]
def infer(base_model, lora_model, prompt, negative_prompt, width, height, guidance_scale, num_inference_steps,
          num_images_per_prompt):
    pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
                                                              torch_dtype=torch.float16,
                                                              use_safetensors=True,
                                                              safety_checker=None,
                                                              load_safety_checker=False,
                                                              requires_safety_checker=False)

    pipe.load_lora_weights(lora_model)
    # pipe.vae = diffusers.AutoencoderKL.from_pretrained("C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors.safetensors")
    # pipe.scheduler = diffusers.schedulers.DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)
    pipe = pipe.to("cuda")

    print("Load Finished")

**Comment by Louis24** [comment]
`def infer(base_model, lora_model, prompt, negative_prompt, width, height, guidance_scale, num_inference_steps,
          num_images_per_prompt):
    pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
                                                              torch_dtype=torch.float16,
                                                              use_safetensors=True,
                                                              safety_checker=None,
                                                              load_safety_checker=False,
                                                              requires_safety_checker=False)

    pipe.load_lora_weights(lora_model)
    # pipe.vae = diffusers.AutoencoderKL.from_pretrained("C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors.safetensors")
    # pipe.scheduler = diffusers.schedulers.DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)
    pipe = pipe.to("cuda")

    print("Load Finished")`

**Comment by Louis24** [comment]
def infer(base_model, lora_model, prompt, negative_prompt, width, height, guidance_scale, num_inference_steps,
num_images_per_prompt):

  pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
  torch_dtype=torch.float16,
  use_safetensors=True,
  safety_checker=None,
  load_safety_checker=False,
  requires_safety_checker=False)

  pipe.load_lora_weights(lora_model)

  pipe = pipe.to("cuda")

  print("Load Finished")

**Comment by Louis24** [comment]
Before rebooting the computer, it works very well. Now I have stable diffusion and lora model. I guess I need the clip model, maybe it was downloaded and automatically put in the cache folder before

> need some kind of reproducer if possible

**Comment by Louis24** [comment]
![image](https://github.com/huggingface/diffusers/assets/18719360/c498865b-a1aa-4ac5-afd1-99aa02f995e2)
Can I specify the path?

**Comment by bghira** [comment]
from_single_file is likely how the problem is arising.

use `from_pretrained`

**Comment by Louis24** [comment]
![image](https://github.com/huggingface/diffusers/assets/18719360/4a862f6e-f5d4-4ada-8fc5-a232a0fdc887)
I got this file 
![image](https://github.com/huggingface/diffusers/assets/18719360/58cdc41b-5295-4f47-949e-33374969d8b3)
Where shall I change the path?

**Comment by Louis24** [comment]
@patrickvonplaten @stevhliu @bghira still not working，works fine last week same code and same env

**Comment by DN6** [comment]
@Louis24 Set the `config_file` argument in `from_single_file` to point to your local version of the yaml file.

**Comment by Louis24** [comment]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000207AAB78D60>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

> @Louis24 Set the `config_file` argument in `from_single_file` to point to your local version of the yaml file.



> from_single_file is likely how the problem is arising.
> 
> use `from_pretrained`



> @Louis24 if you don't want to connect to the internet you can disable it by setting a global flag: `export HF_HUB_OFFLINE=True`



> @Louis24 Set the `config_file` argument in `from_single_file` to point to your local version of the yaml file.

**Comment by DN6** [comment]
Is this error still happening after setting the `config_file`?

**Comment by Louis24** [comment]
> Is this error still happening after setting the `config_file`?
Of course yes! 
Now I'm confused. Sometimes it works and sometimes it doesn't. I'm currently in China and I don't know if it's because Chinese area is blocked, but I've already used VPN.

**Comment by DN6** [comment]
Could you please share a short snippet of how you are loading the config file and weights locally?

**Comment by Louis24** [comment]
> Could you please share a short snippet of how you are loading the config file and weights locally?

  pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
                                                              torch_dtype=torch.float16,
                                                              use_safetensors=True,
                                                              safety_checker=None,
                                                              load_safety_checker=False,
                                                              requires_safety_checker=False,
                                                              config_file="C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/configs/v1-inference.yaml")

**Comment by neue** [comment]
try adding `local_files_only = True` to the pipeline config that was the only thing I found that actually stops it trying to connect to the server needlessly.

**Comment by Louis24** [comment]
> try adding `local_files_only = True` to the pipeline config that was the only thing I found that actually stops it trying to connect to the server needlessly.

I have added.

**Comment by DN6** [comment]
@Louis24 I think this should have been fixed in #5440. 

Can you install `diffusers` from main `pip install git+https://github.com/huggingface/diffusers.git` and try running again?

**Comment by Louis24** [comment]
> pip install git+https://github.com/huggingface/diffusers.git

Thank you for the advice, since in China may have resitrict, I use  python -m pip install --proxy=http://127.0.0.1:7890 git+https://github.com/huggingface/diffusers.git but still no speed

**Comment by Louis24** [comment]
> @Louis24 I think this should have been fixed in #5440.
> 
> Can you install `diffusers` from main `pip install git+https://github.com/huggingface/diffusers.git` and try running again?

python -m pip install --proxy=http://127.0.0.1:7890 --index-url=https://pypi.org/simple git+https://github.com/huggingface/diffusers.git

**Comment by Louis24** [comment]
fatal: unable to access 'https://github.com/huggingface/diffusers.git/': Empty reply from server
  error: subprocess-exited-with-error

**Comment by Louis24** [comment]
> try adding `local_files_only = True` to the pipeline config that was the only thing I found that actually stops it trying to connect to the server needlessly.

I've tried, not working

**Comment by TsingZ0** [comment]
@Louis24 I still have this problem, did you solve it?
