### ISSUE TITLE
[Hacktoberfest] DeepFloyd IF docstrings

### ISSUE THREAD

**Issue by stevhliu** [huggingface/diffusers#5302]
This feature request is included in this year's Diffusers Hacktoberfest 🎃!

Hacktoberfest's purpose is to give upcoming open-source developers the opportunity to learn about open-source and programming by fixing simple issues (like this one).

How to solve the issue:

- Every issue has a description further below explaining the problem. First, you should try to understand the issue.
- Second, follow the [contribution guide](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md) to learn how to contribute to Diffusers.
- Claim this issue for you by opening a PR that links to this issue and writing, "I am solving this issue in <link-to-pr>".

Issue

For each of the DeepFloyd IF pipelines:

1. The [`encode_prompt`](https://huggingface.co/docs/diffusers/main/en/api/pipelines/deepfloyd_if#diffusers.IFPipeline.encode_prompt) parameters are all mixed up and need to be reformatted
2. The parameter values in [`__call__`](https://huggingface.co/docs/diffusers/main/en/api/pipelines/deepfloyd_if#diffusers.IFPipeline.__call__) are out of sync (for example, `num_inference_steps` should be 100 but the docstring says it is 50). Please also check if other values are also incorrect, like the `guidance_scale`

**Comment by m0saan** [comment]
@stevhliu I would like to work on this please!
