### ISSUE TITLE
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'load_lora_weights'

### ISSUE THREAD

**Issue by SlZeroth** [huggingface/diffusers#5311]
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained('C:/Users/test/ML/models/majicmix_xl', torch_dtype=torch.bfloat16).to("cuda")
pipe.load_lora_weights("lora.safetensors")

I got AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'load_lora_weights' error when load a lora file only when model is XL

I tested with 1.5 and its work.

pipe = DiffusionPipeline.from_pretrained('C:/Users/test/ML/models/majicmix_1.5', torch_dtype=torch.bfloat16).to("cuda")
pipe.load_lora_weights("lora.safetensors")

**Comment by SlZeroth** [comment]
my diffusers version is latest version

**Comment by DN6** [comment]
Hi @SlZeroth I'm unable to reproduce this. Could you verify your diffusers version by running the following command? 

```
python -c "import diffusers; print(diffusers.__version__)"
```

**Comment by SlZeroth** [comment]
this is the my problem
