### ISSUE TITLE
ControlNet Reference Inpainting Pipeline

### ISSUE THREAD

**Issue by ajkrish95** [huggingface/diffusers#5314]
### Model/Pipeline/Scheduler description

Can we implement a ControlNet reference Inpainting Pipeline? Currently there is a community pipeline for ControlNet reference but there is no ControlNet reference Inpainting Pipeline.

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by DN6** [comment]
@ajkrish95 Would you like to open a PR to add this to the community pipelines?
