### ISSUE TITLE
[`PEFT`] Documenting PEFT API

### ISSUE THREAD

**Issue by younesbelkada** [huggingface/diffusers#5317]
# Feature request

Let's properly document PEFT API ! 
PEFT integration (LoRA, AdaLora, IA3, ..)  is coming soon in diffusers in the next releases, allowing many cool applications - let's properly document them to educate users on what is possible to achieve with PEFT backend

Related: https://github.com/huggingface/diffusers/pull/5151

**Comment by younesbelkada** [comment]
This is done right ? @sayakpaul

**Comment by sayakpaul** [comment]
Yup.

**Comment by stevhliu** [comment]
I believe all the PEFT-related APIs are documented:

- `set_adapters`
- `disable_lora`
- `enable_lora`
- `get_active_adapters`
- `get_list_adapters`
- `fuse_lora`
- `unfuse_lora`

I only looked in the `loaders.py` file (I assume this is where they'll be), but feel free to let me know if I've missed anything else! I think to make it even nicer, we can add some code snippets to the API docs as well (see [here](https://huggingface.co/docs/diffusers/main/en/api/loaders#diffusers.loaders.UNet2DConditionLoadersMixin.set_adapters) for example).

If that sounds good to you, I can open a PR for that! 🙂

**Comment by sayakpaul** [comment]
That sounds about right to me. @younesbelkada @pacman100 WDYT?

**Comment by younesbelkada** [comment]
Sounds great @sayakpaul @stevhliu - Thank you!
