### ISSUE TITLE
[`PEFT`] Add `adapter_name` to `fuse_lora`

### ISSUE THREAD

**Issue by younesbelkada** [huggingface/diffusers#5320]
# Feature request

Diffusers will be soon using PEFT as backend for adapters such as LoRA - we should make sure users can fuse a specific adapter in the base model. Hence, we should add an argument `adapter_name` in `fuse_lora` and make sure to fuse only that adapter in the base model

Related: https://github.com/huggingface/diffusers/pull/5151

**Comment by DN6** [comment]
cc: @sayakpaul

**Comment by patrickvonplaten** [comment]
Is this still relevant? cc @sayakpaul @younesbelkada ?

**Comment by younesbelkada** [comment]
Yes I think so: https://github.com/huggingface/diffusers/blob/main/src/diffusers/loaders.py#L2264 cc @pacman100 @BenjaminBossan as well, I can work on that in the next days if no one is on it!

**Comment by younesbelkada** [comment]
Just made https://github.com/huggingface/peft/pull/1132 which is a first step towards addressing this feature

**Comment by younesbelkada** [comment]
Will be fixed with #5823
