### ISSUE TITLE
LoRA Civital all failing but previously okay

### ISSUE THREAD

**Issue by linnanwang** [huggingface/diffusers#5328]
### Describe the bug

Here is the error message:  

File "/home/linnan/codes/lora_test.py", line 7, in <module>
    pipe.load_lora_weights("/home/linnan/LORAS/dressed-animals/pytorch_lora_weights.safetensors")
  File "/home/linnan/envs/sd/lib/python3.10/site-packages/diffusers/loaders.py", line 2787, in load_lora_weights
    state_dict, network_alphas = self.lora_state_dict(
  File "/home/linnan/envs/sd/lib/python3.10/site-packages/diffusers/loaders.py", line 1288, in lora_state_dict
    state_dict = torch.load(model_file, map_location="cpu")
  File "/home/linnan/envs/sd/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/linnan/envs/sd/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

### Reproduction

import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16
)
pipe.load_lora_weights("pytorch_lora_weights.safetensors")
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]

### Logs

```shell
see above
```

### System Info

installed with pip install git+https://github.com/huggingface/diffusers

### Who can help?

@sayakpaul @patrickvonplaten Now all Civital LoRAs are failing. Thanks for your help.

**Comment by sayakpaul** [comment]
Cannot reproduce it.

**Comment by patrickvonplaten** [comment]
@linnanwang can you please add a reproducible code snippet?

**Comment by linnanwang** [comment]
Sorry for the late reply, and the code is okay and it turns out I download a wrong safetensors...Let me close this ticket, and appreciate your help here.
