### ISSUE TITLE
Accelerate.prepare() and Accelerate.accumulate() need multiple models passed in during training

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#5334]
### Describe the bug

As indicated [here](https://github.com/huggingface/accelerate/pull/1708) we need to pass all of the models we want to apply gradient accumulation steps to into the `accumulate()` method

### Reproduction

Run the `train_dreambooth.py` example script with `--gradient_accumulation_steps` > 1 and multiple GPUs.

### System Info

git main diffusers branch

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
Feel free to open PRs. 

Cc: @BenjaminBossan
