### ISSUE TITLE
Implementing EDICT for memory efficient backpropagation through chain/time/steps

### ISSUE THREAD

**Issue by ysig** [huggingface/diffusers#5348]
Currently backpropagation through chain is impossible in diffusers, due to obvious memory limitations.
However recently through [invertible networks](https://openreview.net/pdf?id=HJsjkMb0Z) and [MemCNN](https://memcnn.readthedocs.io/en/latest/index.html) a recent technique known as EDICT [[paper](https://arxiv.org/abs/2211.12446),[code](https://github.com/salesforce/EDICT)] has been proposed that allows to do this and it has been used successfully deployed in this diffusion editing method known as DOODL [[paper](https://arxiv.org/abs/2303.13703), [code](https://github.com/salesforce/DOODL)].
As the code is already in diffusers, it would be cool if the team implemented this in the most efficient way package wise.

**Comment by DN6** [comment]
@ysig Feel free to open a PR with a reference implementation. Maybe add it to the example training scripts?
