### ISSUE TITLE
Is xformer necessary for SDXL?

### ISSUE THREAD

**Issue by g-jing** [huggingface/diffusers#5350]
I wonder if we have to use xformer so to use SDXL? I am trying to get the attention map of the cross attention and self attention inside of the Unet, but it is hard to get that with xformer since it directly get the result from q, k, and v instead of getting attention map from q and k first.

**Comment by DN6** [comment]
@g-jing  xformers isn't necessary when running SDXL.

**Comment by stevhliu** [comment]
Hi, it is not used by default and only used if you call `enable_xformers_memory_efficient_attention`. If you did enable it, you can turn it off with [`disable_xformers_memory_efficient_attention`](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/img2img#diffusers.StableDiffusionImg2ImgPipeline.disable_xformers_memory_efficient_attention).
