### ISSUE TITLE
Use of LoRa sliders

### ISSUE THREAD

**Issue by Jonarod** [huggingface/diffusers#5352]
**Is your feature request related to a problem? Please describe.**
In civitai, a lot of LoRa "sliders" are popping up like this one: [hair-length-slider-lora](https://civitai.com/models/114215?modelVersionId=123434). It would allow one to play around with different weights values to apply the LoRa effect. In A1111, in the prompt, one would use different weights, using this syntax: `<lora:name_of_lora:weight>` so for the provided LoRa example, it would be something like this `<lora:hair_length_slider_v1:5>`.

I am not able to make this behaviour to work in HuggingFace.

**Describe alternatives you've considered**
So far, the only way I could apply new slider-weights to a LoRa is by fusing the LoRa and play with the `lora_scale` as if it were the slider's values.
However, this is not quite the same intent, as originally the weights are meant to be controlled from within a prompt directly, independently from the currently loaded model.

**Comment by DN6** [comment]
@Jonarod Would you be able to provide a code snippet to demonstrate how this is achieved in A1111?

**Comment by patrickvonplaten** [comment]
cc @sayakpaul @younesbelkada @pacman100 - is this something we could achieve with the new PEFT integration?

**Comment by sayakpaul** [comment]
Wow, this is very commendable! 

So, what I am seeing here is that `diffusers` can natively support this if I am not wrong. Also cc @apolinario here because we were talking about it a couple days back.

**Comment by apolinario** [comment]
Hey @Jonarod , under the hood AUTOMATIC1111 is taking the LoRA information on your prompt (`<lora:name_of_lora:weight>`) and adding it to the model with a `lora_scale`, just like it is possible in `diffusers` with a `lora_scale` 

As you have alluded, you can apply a LoRA scale when fusing a LoRA into the Unet. While this makes inference fast, is not super practical for this use-case as you'd need to unfuse and fuse again with another scale. 

To swap the `lora_scale` in inference time, you can follow what @pacman100 has described should arrive at similar results on what you get by including the LoRA on your prompts with AUTO1111.

**Comment by Jonarod** [comment]
I see.
Very thankful for the prompt support, really appreciated.

I don't know the actual HF philosophy on this one, is it considered the final solution for this use case?
Or should I leave this feature opened until the Lora scaling can be done from the prompt directly?

A solution I could imagine would be to, for example, parse the prompt with some regex first to actually extract the Lora scale, and then automatically apply the relevant kwargs as described above.

So I'll leave it opened on my end, but feel free to close it if that does not correspond to HuggingFace's roadmap :)

**Comment by Jonarod** [comment]
I was able to reproduce the scaling without fuse using `cross_attention_kwargs={"scale": lora_scale}` as demonstrated. Again, thanks for pointing that out.

However the disadvantage of this method is that scaling applies for all LoRas loaded. It is not possible to have multiple scales for multiple LoRas like in classic webUI solutions (be it A1111, ComfyUI, ...).
Also, the SOTA seems to adopt the `<lora:name:scale>` pattern as is visible in major models zoos like Civitai and others. Since some time now, a lot of new images have emerged with prompts similar to this:
```
photo of a redhead woman with black rim glasses <lora:add_detail:1> <lora:weight_slider_v2:-1> <lora:hair_length_slider_v1:2>
```
which is becoming the standard right now.

Finally, fusing/merging LoRas with checkpoints and/or upcoming serialisation of `torch.compile()`'d models, would make the final user lose the ability to further modulate the scale of the "LoRa_sliders" once loaded (since so far we only have 1 global scale argument for all LoRas). Hence IMHO, offloading LoRa scaling into prompts does not seem so much of a bad idea, and maybe that's why it's getting so popular too.

**Comment by sayakpaul** [comment]
Hi @Jonarod. Thanks for your interest.

We like to keep prompting solely to prompting. This is why, for prompt weighting, we refer users to `compel`. See: https://huggingface.co/docs/diffusers/main/en/using-diffusers/weighted_prompts. 

So, this kind of offloading is a bit of an anti-pattern for us. 

However, with the `peft` integration (that is upcoming), using multiple LoRAs with multiple scales is going to be much easier. See [here](https://github.com/huggingface/diffusers/pull/5151) and [here](https://github.com/huggingface/diffusers/pull/5359). 

I hope that makes sense.

**Comment by Jonarod** [comment]
So if I read correctly, the new PR will address the need for multiple LoRa adapters with this solution:

```
pipe.set_adapters(["pixel", "toy"], adapter_weights=[0.5, 1.0])
```
Then if I am correct, it is up to the developer to load/unload adapters between inferences.

Cool with me, looking forward to this new PR !!
Thank you all for your support !! 🙏🏼
