### ISSUE TITLE
Issue with Custom Attention Processors Compatibility

### ISSUE THREAD

**Issue by denemmy** [huggingface/diffusers#5358]
Version of diffusers: **0.21.4**

**Description**
I've encountered difficulties with the compatibility of custom attention processors in the diffusers library, particularly when attempting to use the [IP-Adapter](https://github.com/tencent-ailab/IP-Adapter) with custom attention processors.

**Details of the Issue**
In [diffusers/models/attention_processors.py](https://github.com/huggingface/diffusers/blob/9c82b68f074df116f0c5044d20a0cf9c0086b5ac/src/diffusers/models/attention_processor.py#L366), line 360:

`
non_lora_processor_cls_name = self.processor.__class__.__name__
lora_processor_cls = getattr(import_module(__name__), "LoRA" + non_lora_processor_cls_name)
`

The attention processor is being located by class name, which is not suitable for custom attention processors. This approach limits the extensibility and adaptability of the code to use with custom processors, as it tightly couples the logic with the class name.

[diffusers/models/unet_2d_condition.py](https://github.com/huggingface/diffusers/blob/9c82b68f074df116f0c5044d20a0cf9c0086b5ac/src/diffusers/models/unet_2d_condition.py#L594), line 604, within the attn_processors method:

`processors[f"{name}.processor"] = module.get_processor(return_deprecated_lora=True)`

The method is called with a flag (return_deprecated_lora=True) that triggers the execution of non-optimal code. I understand that this is a temporary solution, but it completely breaks the logic of using custom attention processors.

**Reference**
An implementation that uses IP-Adapter and diffusers library with custom attention processors can be observed in this repository: [IP-Adapter Implementation](https://github.com/tencent-ailab/IP-Adapter/blob/d580c50a291566bbf9fc7ac0f760506607297e6d/ip_adapter/ip_adapter.py#L79).

**Issue Impact and Urgency**
The diffusers codebase experiences frequent changes, and it's noted that occasionally, these changes introduce breaking functionalities with new versions. Ensuring compatibility and stability, especially when utilizing custom processors, is crucial for maintaining a reliable user experience and functionality.

**Suggestion**
Is it possible to consider a more adaptable solution that allows easier integration of custom processors?

Thank you for considering this issue and for your continued work on the diffusers library.

**Comment by patrickvonplaten** [comment]
Hey @denemmy,

Thanks for pointing this out, we should indeed make sure that custom attention processors still work as expected all the while we deprecate our LoRA attention processors.

Could you maybe add a minimum code snippet that we could execute that shows how the current design is problematic? 

Also cc @DN6 here
