### ISSUE TITLE
Add `output_attentions` option to `DiffusionPipeline.__call__`

### ISSUE THREAD

**Issue by JoaoLages** [huggingface/diffusers#536]
In the same way that `transformers` has this option for generate/forward methods (example in [here](https://github.com/huggingface/transformers/blob/5e636eee4af48ccd03b4d9c1a1e6f7a1b92a643f/src/transformers/generation_utils.py#L927)), we could have the same option in `DiffusionPipeline.__call__`.

I started the implementation in [here](https://github.com/JoaoLages/diffusers/tree/add-output-attentions) but found out that storing the attention vectors for StableDiffusion is really memory intensive! 💣 
I could not find a way to surpass this problem, any ideas?

**Comment by patrickvonplaten** [comment]
I guess that's just how it is - if we store tensors we need for memory. Also what is the main use case to store attentions in `diffusers`? In Transformers it was mainly done to be able to analyse relationships between words - what would be the use case here?

**Comment by JoaoLages** [comment]
> I guess that's just how it is - if we store tensors we need for memory. Also what is the main use case to store attentions in `diffusers`? In Transformers it was mainly done to be able to analyse relationships between words - what would be the use case here?

Mainly to analyze relationships between the generated image and the input text.
