### ISSUE TITLE
Provide single file safetensors of hf-internal-testing/tiny-stable-diffusion-torch and SDXL

### ISSUE THREAD

**Issue by noskill** [huggingface/diffusers#5360]
Such files would be useful for tests.

Is there an option to convert hf-internal-testing/tiny-stable-diffusion-torch to a single safetensors file?
I tried convert_diffusers_to_original_stable_diffusion.py but when loading it produces "NotImplementedError: Cannot copy out of meta tensor; no data!".  I think it's due to some layers being present in default config and missing in tiny model

**Comment by xddun** [comment]
How to convert multiple piped files into a single SafeTensor file?

For example, from this address: https://huggingface.co/Vargol/sdxl-lightning-4-steps/tree/main

```python
import torch
from diffusers import StableDiffusionXLPipeline, EulerDiscreteScheduler

base = "Vargol/sdxl-lightning-4-steps"

pipe = StableDiffusionXLPipeline.from_pretrained(base, torch_dtype=torch.float16).to("cuda")
```

How can I convert `pipe` into a single SafeTensor file as a whole?


Just like the file `sd_xl_base_1.0_0.9vae.safetensors`, which contains the components needed from `diffusers`.

**Comment by noskill** [comment]
Thanks
Also now there is a tiny SDXL model https://huggingface.co/hf-internal-testing/tiny-sdxl-pipe
