### ISSUE TITLE
[`PEFT` / `Tests` ] Re-design testing suite for `Unet2DConditionModel` & `Unet3DConditionModel`

### ISSUE THREAD

**Issue by younesbelkada** [huggingface/diffusers#5363]
In the current PEFT integration the `Unet2DConditionModel` and `Unet3DConditionModel` testers are being silently tested in `PeftLoraLoaderMixinTests`. Since the API changed a bit - i.e. no need to call `set_attn_procs` but call `add_adapter` instead, I propose to refactor the testing suite of the unets and make sure their core functionality does not get broken by future PRs

cc @DN6 @sayakpaul @pacman100 @patrickvonplaten 

Related #5151

**Comment by sayakpaul** [comment]
> Since the API changed a bit - i.e. no need to call set_attn_procs but call add_adapter instead, I propose to refactor the testing suite of the unets and make sure their core functionality does not get broken by future PRs

As we begin to deprecate the existing LoRA APIs, do you think the tests would need updates as the [new peft tests](https://github.com/huggingface/diffusers/blob/main/tests/lora/test_lora_layers_peft.py) already make use `add_adapter()`, for example.

**Comment by sayakpaul** [comment]
Not stale.

**Comment by DN6** [comment]
What were you thinking for the refactor @younesbelkada? As @sayakpaul mentioned there is currently a dedicated runner for PEFT using the latest API.

**Comment by sayakpaul** [comment]
In our `test_lora_layer_peft.py`, we already do `add_adapter()`. So, I think it's not needed actually. In the upcoming versions, we can fully delete `test_lora_layers_old_backend.py`.

**Comment by sayakpaul** [comment]
@younesbelkada WDYT?

**Comment by younesbelkada** [comment]
@sayakpaul I think the CI suite is already great as is, I don't think this is a high prio :/

**Comment by sayakpaul** [comment]
I think so as well. Closing this for now then. Cc: @DN6
