### ISSUE TITLE
add blip inpainting pipe support 

### ISSUE THREAD

**Issue by yanchaoguo** [huggingface/diffusers#5371]
how to use mask inpainting with blip diffusion [blip_diffusion](https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines/blip_diffusion)

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
Is inpainting natively supported by BLIP Diffusion? The official site doesn't state so: https://dxli94.github.io/BLIP-Diffusion-website/
