### ISSUE TITLE
How to use safety_checker in StableDiffusionXLPipeline?

### ISSUE THREAD

**Issue by hundredwz** [huggingface/diffusers#5372]
### Describe the bug

I want to use safety_checker in StableDiffusionXLPipeline, but it seems that `safety_checker` keyword does not take effect

### Reproduction

```python
pipe = StableDiffusionXLPipeline.from_pretrained(
    "nyxia/mysterious-xl",
    torch_dtype=torch.float16,
    safety_checker = StableDiffusionSafetyChecker.from_pretrained("CompVis/stable-diffusion-safety-checker"),
).to("cuda")
pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
result = pipe(
        prompt="1girl",
)
```

### Logs

I got folling error

```shell

Keyword arguments {'safety_checker': StableDiffusionSafetyChecker(
  (vision_model): CLIPVisionModel(
    (vision_model): CLIPVisionTransformer(
      (embeddings): CLIPVisionEmbeddings(
        (patch_embedding): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
        (position_embedding): Embedding(257, 1024)
      )
      (pre_layrnorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (encoder): CLIPEncoder(
        (layers): ModuleList(
          (0-23): 24 x CLIPEncoderLayer(
            (self_attn): CLIPAttention(
              (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
              (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
              (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
              (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (layer_norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (mlp): CLIPMLP(
              (activation_fn): QuickGELUActivation()
              (fc1): Linear(in_features=1024, out_features=4096, bias=True)
              (fc2): Linear(in_features=4096, out_features=1024, bias=True)
            )
            (layer_norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          )
        )
      )
      (post_layernorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (visual_projection): Linear(in_features=1024, out_features=768, bias=False)
)} are not expected by StableDiffusionXLPipeline and will be ignored.
```

### System Info

- `diffusers` version: 0.20.0
- Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.0
- Accelerate version: 0.23.0
- xFormers version: 0.0.22
- Using GPU in script?:  yes

### Who can help?

@yiyixuxu @sayakpaul @DN6 @patrickvonplaten

thanks for your kindly help

**Comment by sayakpaul** [comment]
StableDiffusionXL doesn't make use of a safety checker in its original implementation. Hence we don't support it. But if you want to use it, you could follow the implementation from [here](https://github.com/huggingface/diffusers/blob/cf03f5b7188c603ff037d686f7256d0571fbd651/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L760) and repurpose it for your use case.

**Comment by hundredwz** [comment]
> StableDiffusionXL doesn't make use of a safety checker in its original implementation. Hence we don't support it. But if you want to use it, you could follow the implementation from [here](https://github.com/huggingface/diffusers/blob/cf03f5b7188c603ff037d686f7256d0571fbd651/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L760) and repurpose it for your use case.

ok, thank you. I will take a try.
