### ISSUE TITLE
Callback for `WuerstchenCombinedPipeline`

### ISSUE THREAD

**Issue by soumik12345** [huggingface/diffusers#5373]
A callback similar to existing pipelines such as [`diffusers.StableDiffusionPipeline`](https://huggingface.co/docs/diffusers/v0.21.0/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline) and [`diffusers.KandinskyCombinedPipeline`](https://huggingface.co/docs/diffusers/v0.21.0/en/api/pipelines/kandinsky#diffusers.KandinskyCombinedPipeline) for the [Wuerstchen Pipelines](https://huggingface.co/docs/diffusers/v0.21.0/en/api/pipelines/wuerstchen).

The callback system in the aforementioned pipelines consists of a function `callback(step: int, timestep: int, latents: torch.FloatTensor)` that gets called every `callback_steps` step of the denoising loop during inference. The callback function and the `callback_steps` (float) are both optional parameters that are to be passed to the `__call__` method for the [`WuerstchenCombinedPipeline`](https://huggingface.co/docs/diffusers/v0.21.0/en/api/pipelines/wuerstchen#diffusers.WuerstchenCombinedPipeline) and [`WuerstchenDecoderPipeline`](https://huggingface.co/docs/diffusers/v0.21.0/en/api/pipelines/wuerstchen#diffusers.WuerstchenDecoderPipeline).

A callback function for the Wuerstchen Pipelines could potentially be used for visualizing intermediate latents during the denoising loop.

**Comment by sayakpaul** [comment]
Here's an example of how you can visualise intermediate latents:
https://github.com/madebyollin/taesd/blob/main/examples/Previewing_During_Image_Generation.ipynb

**Comment by sayakpaul** [comment]
But yes supporting callbacks for these pipelines would be nice! 

@yiyixuxu @patrickvonplaten WDYT?

**Comment by soumik12345** [comment]
I am willing to contribute the callback system for the Wuerstchen pipelines.
