### ISSUE TITLE
StableDiffusionXLControlNetPipeline does not have the from_single_file attribute

### ISSUE THREAD

**Issue by rafationgson** [huggingface/diffusers#5375]
When i use the StableDiffusionXLControlNetPipeline and call the "from_single_file" method it returns an error that the attribute does not exist, but in the docs it states that the pipeline inherits the method from the DiffusionPipeline. Would like to use this attribute to deploy models with controlnet using only the safetensor file.

**Comment by rafationgson** [comment]
Hi @DN6 here is a code example. For diffusers version I am using `0.19.3`

```
import os
import shutil
import torch
from diffusers import StableDiffusionXLControlNetPipeline

if os.path.exists('diffusers-cache'):
    shutil.rmtree('diffusers-cache')
os.makedirs('diffusers-cache', exist_ok=True)

pipeline = StableDiffusionXLControlNetPipeline.from_single_file('https://huggingface.co/newbking/shikianimexl_v10/blob/main/shikianimexl_v10.safetensors', torch_dtype=torch.float16)
pipeline.save_pretrained('diffusers-cache')
```

**Comment by DN6** [comment]
@rafationgson Can you try upgrading to the latest version of diffusers and running your code?

**Comment by rafationgson** [comment]
Hi @DN6 updated to latest version and it is working. Thank you!
