### ISSUE TITLE
Use `HfApi` instead of `Repository` in training scripts

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#5383]
`Repository` [is being deprecated](https://github.com/huggingface/huggingface_hub/pull/1724), but we still use it in a couple of training scripts:

- https://github.com/huggingface/diffusers/blob/4d2c981d551566961bbc7254ae9556d76dd95764/examples/dreambooth/train_dreambooth_flax.py#L19
- https://github.com/huggingface/diffusers/blob/4d2c981d551566961bbc7254ae9556d76dd95764/examples/unconditional_image_generation/train_unconditional.py#L19

Research projects:
- https://github.com/huggingface/diffusers/blob/4d2c981d551566961bbc7254ae9556d76dd95764/examples/research_projects/onnxruntime/unconditional_image_generation/train_unconditional.py#L17
- https://github.com/huggingface/diffusers/blob/4d2c981d551566961bbc7254ae9556d76dd95764/examples/research_projects/intel_opts/textual_inversion_dfq/textual_inversion.py#L16

Docs:
- https://github.com/huggingface/diffusers/blob/4d2c981d551566961bbc7254ae9556d76dd95764/docs/source/en/tutorials/basic_training.md?plain=1#L287C43-L287C53
- `ko` translation of above

cc @Wauplin

**Comment by Wauplin** [comment]
Thanks for opening the issue @pcuenca! If it can help, here is the PR in `transformers` that removed `Repository` in training scripts: https://github.com/huggingface/transformers/pull/25095.

**Comment by patrickvonplaten** [comment]
Cool, @sayakpaul do you have time to update our examples here maybe?
