### ISSUE TITLE
How to train an unconditional latent diffusion model ?

### ISSUE THREAD

**Issue by Rashfu** [huggingface/diffusers#5392]
It seems that there is only one available unconditional LDM model (CompVis/ldm-celebahq-256). 
```python
pipeline = LDMPipeline.from_pretrained("CompVis/ldm-celebahq-256")
```
How can I train this unconditional model on my own dataset? The LDM model includes the training of both `VQModel` and `UNet2DModel`, but the [official training examples](https://github.com/huggingface/diffusers/blob/main/examples/unconditional_image_generation/train_unconditional.py) seem not to be fully applicable.

**Comment by nityanandmathur** [comment]
@patrickvonplaten, does diffusers support training an unconditional LDM model now?
