### ISSUE TITLE
cannot import name 'compute_snr' from 'diffusers.training_utils' 

### ISSUE THREAD

**Issue by RhodianSK** [huggingface/diffusers#5402]
I'm trying to train using the script train_text_to_image_lora.py and I am getting the following error:
```
 Traceback (most recent call last):
  File "G:\Project Files\Kohya_SS - Data\Text to Image LoRA\train_text_to_image_lora.py", line 46, in <module>
    from diffusers.training_utils import compute_snr
ImportError: cannot import name 'compute_snr' from 'diffusers.training_utils' (C:\Python3109\lib\site-packages\diffusers\training_utils.py)
Traceback (most recent call last):
  File "C:\Python3109\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python3109\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python3109\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Python3109\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Python3109\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Python3109\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Python3109\\python.exe', 'train_text_to_image_lora.py', '--pretrained_model_name_or_path=G:\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\SDXL\\sd_xl_base_1.0.safetensors', '--dataset_name=G:\\Project Files\\Kohya_SS - Data\\Training\\JasonXB\\JasonXB512-512-Processed', '\\']' returned non-zero exit status 1.
'--dataloader_num_workers' is not recognized as an internal or external command,
```

Can anyone shed any light on how to resolve it? 

Thanks...

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
Which version of `diffusers` are you using? 

It's right there if you're using `main`:

https://github.com/huggingface/diffusers/blob/cc12f3ec929d0359080cb6233c598e4f6d1f4f69/src/diffusers/training_utils.py#L30

**Comment by RhodianSK** [comment]
I'm using 0.21.4...

I've tried "pip install diffusers --upgrade" and nothing is updated, so I assume that I am on the latest.


------ Original Message ------
From "Sayak Paul" ***@***.******@***.***>>
To "huggingface/diffusers" ***@***.******@***.***>>
Cc "RhodianSK" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Date 17/10/2023 1:07:52 AM
Subject Re: [huggingface/diffusers] cannot import name 'compute_snr' from 'diffusers.training_utils' (Issue #5402)


Which version of diffusers are you using?

It's right there if you're using main:

https://github.com/huggingface/diffusers/blob/cc12f3ec929d0359080cb6233c598e4f6d1f4f69/src/diffusers/training_utils.py#L30

**Comment by sayakpaul** [comment]
No, you're not. 

v0.21.4 doesn't have `compute_snr()` in training utils:
https://github.com/huggingface/diffusers/blob/v0.21.4-patch/src/diffusers/training_utils.py

For training examples, we advice to always install `diffusers` from the `main` branch:

```bash
pip install git+https://github.com/huggingface/diffusers
```

If you do the above, that should solve the problem.

**Comment by RhodianSK** [comment]
Thanks, not sure what happened....


------ Original Message ------
From "Sayak Paul" ***@***.******@***.***>>
To "huggingface/diffusers" ***@***.******@***.***>>
Cc "RhodianSK" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Date 17/10/2023 4:40:51 PM
Subject Re: [huggingface/diffusers] cannot import name 'compute_snr' from 'diffusers.training_utils' (Issue #5402)


No, you're not.

v0.21.4 doesn't have compute_snr() in training utils:
https://github.com/huggingface/diffusers/blob/v0.21.4-patch/src/diffusers/training_utils.py

For training examples, we advice to always install diffusers from the main branch:

pip install git+https://github.com/huggingface/diffusers

If you do the above, that should solve the problem.

**Comment by sayakpaul** [comment]
Closing this issue then.
