### ISSUE TITLE
sdxl.from_single_file not overwriting the weights

### ISSUE THREAD

**Issue by linnanwang** [huggingface/diffusers#5405]
### Describe the bug

ckpt1
ckpt2
SDXL.from_single_file(ckpt1)
img1 = SDXL.generate_image()
SDXL.from_single_file(ckpt2)
img2 = SDXL.generate_image()

It seems img1 and img2 are all generate from ckpt1. And the weights from ckpt2 is not reloaded. 

Is it designed like this? Thanks.

### Reproduction

see above

### System Info

the main branch of diffusrs

### Who can help?

@yiyixuxu @sayakpaul @DN6 @patr

**Comment by patrickvonplaten** [comment]
Hey @linnanwang,

Can you please post a completely reproducible issue? I'm not able to run the issue above
