### ISSUE TITLE
Using the SDXL refiner with SD 1.x models

### ISSUE THREAD

**Issue by holwech** [huggingface/diffusers#5409]
I've been attempting to use the SDXL refiner together with SD 1.x models but so far haven't been able to produce good results. I think this is an idea many people will explore at some point, so I figured it justifies a ticket here. Sorry if this is too off topic.

I have looked into the Diffusers source code for SDXL to understand how it works with the refiner and I tried to recreate it for SD 1.x. Unfortunately, the output image does not look good at all. It's not obvious to me why this is not working, but I don't have very deep knowledge of how diffusion models work. Attempting to combine SD 1.x with the refiner might fundamentally not make sense? Is the latents from SD 1.x so different that the refiner is not able make anything useful out of it?

If that's the case, is there any way to use the refiner together with SD 1.x without having to pass it through SDXL?

Here is a reproduction:

https://colab.research.google.com/drive/1lUHih8KsSGuKFTfYBz0I-6FkMEU5GkdP?usp=sharing

And an example:

SD output:
![image](https://github.com/huggingface/diffusers/assets/7474295/be64aeb9-c7ec-4e2f-b322-77eefe0ca515)

Refiner output:
![image](https://github.com/huggingface/diffusers/assets/7474295/348402df-ee2e-49ec-ad80-14899848f2ef)

**Comment by patrickvonplaten** [comment]
I haven't looked into trying to combine the two yet. Maybe someone from the community would like to help here :-)

**Comment by knoopx** [comment]
@AmericanPresidentJimmyCarter somebody did already https://huggingface.co/city96/SD-Latent-Interposer/tree/main

**Comment by holwech** [comment]
That's awesome! Thanks for sharing :)
