### ISSUE TITLE
Allow setting GroupNorm groups in UNet1D classes

### ISSUE THREAD

**Issue by petrzjunior** [huggingface/diffusers#5415]
**Is your feature request related to a problem? Please describe.**
`ResidualTemporalBlock1D` [currently](https://github.com/huggingface/diffusers/blob/29f15673ed5c14e4843d7c837890910207f72129/src/diffusers/models/resnet.py#L703-L714) does allow setting the number of normalization groups.
This behavior could then be propagated through:
- [DownResnetBlock1D](https://github.com/jannerm/diffuser/blob/7ea422860cc0106e5ca5949d980f04b799d5462c/diffuser/models/temporal.py#L20C86-L20C86)
- [UpResnetBlock1D](https://github.com/huggingface/diffusers/blob/29f15673ed5c14e4843d7c837890910207f72129/src/diffusers/models/unet_1d_blocks.py#L86C7-L86C22)
- [ValueFunctionMidBlock1D](https://github.com/huggingface/diffusers/blob/29f15673ed5c14e4843d7c837890910207f72129/src/diffusers/models/unet_1d_blocks.py#L146C7-L146C30)
- [MidResTemporalBlock1D](https://github.com/huggingface/diffusers/blob/29f15673ed5c14e4843d7c837890910207f72129/src/diffusers/models/unet_1d_blocks.py#L166C7-L166C28)

I also noticed that in [UNet1DModel](https://github.com/huggingface/diffusers/blob/29f15673ed5c14e4843d7c837890910207f72129/src/diffusers/models/unet_1d.py#L41C7-L41C18) the `norm_num_groups` is only propagated to the "out" layer, while [UNet2DModel](https://github.com/huggingface/diffusers/blob/29f15673ed5c14e4843d7c837890910207f72129/src/diffusers/models/unet_2d.py#L40C7-L40C18) propagates it into all nested blocks.

**Describe the solution you'd like**
Add parameter `n_groups` to `ResidualTemporalBlock1D` and pass it to both `Conv1dBlock` constructors. Also consider passing the parameter throughout the whole 1D UNet architecture.

**Describe alternatives you've considered**
Currently the default of 8 groups is used, which is probably a good default, but cannot be customized.

**Comment by DN6** [comment]
Hi @petrzjunior, would you be able to open a PR with your proposed change? We would be happy to review it.

**Comment by petrzjunior** [comment]
@DN6 Sure! I'll make a PR in the following days.
