### ISSUE TITLE
An Issue may relate to be compatible among accelerate, PT 2.1 and train_unconditional.py while trying to save checkpoints.

### ISSUE THREAD

**Issue by linhduongtuan** [huggingface/diffusers#5425]
### Describe the bug

An Issue may relate to be compatible among accelerate, PT 2.1 and train_unconditional.py while trying to save checkpoints.

### Reproduction

I am encountering an issue while trying to reimplement the unconditional_image_generation 

accelerate launch --mixed_precision="fp16" --multi_gpu train_unconditional.py \
    --dataset_name="huggan/flowers-102-categories" \
  --resolution=512 --center_crop --random_flip \
  --output_dir="ddpm-ema-flowers-512" \
  --train_batch_size=2 \
  --num_epochs=100 \
  --gradient_accumulation_steps=1 \
  --use_ema \
  --learning_rate=1e-4 \
  --lr_warmup_steps=500 \
  --mixed_precision="fp16" \
  --logger="wandb"

And it raises an error when saving a checkpoint, which may relate to be compatible between diffusers, accelerate and Pytorch version 2.1?

### System Info

OS: Ubuntu 20.4
CUDA 12.1
Pytorch 2.1
Accelerate 0.23.0
Diffusers 0.22.0.dev0

### Who can help?

Hi @sayakpaul 
<img width="1391" alt="accelerate_error" src="https://github.com/huggingface/diffusers/assets/22388092/f8a011c4-9a6e-4f8e-86a8-8a09a7ff3ff5">

**Comment by sayakpaul** [comment]
Cc: @SunMarc @muellerzr

**Comment by muellerzr** [comment]
Not entirely sure how this is happening, as `save_on_each_node` is only on the dev version of accelerate and not the latest release. Are you positive you’re not using a dev version of accelerate? If you are, please pull the latest version which fixed this

**Comment by linhduongtuan** [comment]
@muellerzr  thank you very much. I will try it again following you suggestion!
Linh

**Comment by linhduongtuan** [comment]
Hi @sayakpaul 

I have another question.
I would like to fine-tune SD models for unconditional image generation. So, I want to set the conditioning key like a command conditioning_key = 'concat' if concat_mode else 'crossattn'. My question is how can I set this argument using the train_unconditional.py script?

Thank in advance
Linh

**Comment by sayakpaul** [comment]
You will have to modify the training script when you're initializing the UNet. We don't provide support for it right off the bat.

**Comment by linhduongtuan** [comment]
@sayakpaul thank you very much for answering my question.
Best,
Linh

**Comment by linhduongtuan** [comment]
@muellerzr It now works for me if I use accelerate version 0.23 instead of the 0.23.dev branch.
Thank you for supporting.
Linh
