### ISSUE TITLE
DDP Warning: Grad strides do not match bucket view strides warning 

### ISSUE THREAD

**Issue by mrsalehi** [huggingface/diffusers#543]
### Describe the bug

During fine tuning the diffusion model with accelerate on multiple GPUs I got the following warning (it does not happen on a single gpu):
```
python3.8/site-packages/torch/autograd/__init__.py:173: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [320, 320, 1, 1], strides() = [320, 1, 320, 320]
bucket_view.sizes() = [320, 320, 1, 1], strides() = [320, 1, 1, 1] (Triggered internally at  ../torch/csrc/distributed/c10d/reducer.cpp:312.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
```
It turns out this warning can occur when a tensor is permuted without calling `contiguous()` on it (Pytorch [issue #47163](https://github.com/pytorch/pytorch/issues/47163) is relevant). As I further investigated, this is happening when the inputs are passed to the `SpatialTransformer` module which is defined in `diffusers/models/attention.py`. When I call contiguous on the hidden states before passing them to the out projection layer in the spatial transformer the warning disappears.

### Reproduction

`transformers==4.22.1`
`diffusers @ git+https://github.com/huggingface/diffusers.git@9e439d8c600229556452fa758c8b6145905d8efd`
`accelerate==0.12.0`

### System Info

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-4.19.0-21-cloud-amd64-x86_64-with-glibc2.17
- Python version: 3.8.13
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Huggingface_hub version: 0.9.1
- Transformers version: 4.22.1
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Yes

**Comment by patrickvonplaten** [comment]
Hey @mrsalehi, 

Could you provide maybe a fully reproducible code snippet maybe? :-) Happy to look into it then!

**Comment by superhero-7** [comment]
hi @mrsalehi , could you tell me how you fixed the warning more specifically? And maybe provide your code,that would be great!
I add .contiguous,but it didn't work,here is my code in the class SpatialTransformer:
`    def forward(self, x, context=None):
        # note: if no context is given, cross-attention defaults to self-attention
        b, c, h, w = x.shape
        x_in = x
        x = self.norm(x)
        x = self.proj_in(x)
        x = rearrange(x, 'b c h w -> b (h w) c')
        for block in self.transformer_blocks:
            x = block(x, context=context)
        x = rearrange(x, 'b (h w) c -> b c h w', h=h, w=w).contiguous()
        # x = rearrange(x, 'b (h w) c -> b c h w', h=h, w=w)
        x = self.proj_out(x)
        return x + x_in`
Thanks a lot!

**Comment by mrsalehi** [comment]
Hi @superhero-7 .
It seems like they have changed the source code entirely. If I'm not mistaken, they have changed `SpatialTransformer` class to `Transformer2DModel` in commit `ef2ea33c3bc061fffa8bc4ccd640306ca1a1847d`. I have no experience with this modified code but if the code on master branch still gives this warning, may be you could look into the forward pass of the new class? For example I can see the following lines in the code and it is very similar to what I changed: 
```
if self.is_input_continuous:
    hidden_states = hidden_states.reshape(batch, height, weight, inner_dim).permute(0, 3, 1, 2)
```
So you can try adding `contiguous` after the permute? 
And of course I'm just guessing and this could be totally wrong!

**Comment by ayu1729** [comment]
> Hey @mrsalehi,
> 
> Could you provide maybe a fully reproducible code snippet maybe? :-) Happy to look into it then!

The code in attention.py is changed but the issue remains.

**Comment by zbzbzbb95** [comment]
> hi @mrsalehi , could you tell me how you fixed the warning more specifically? And maybe provide your code,that would be great! I add .contiguous,but it didn't work,here is my code in the class SpatialTransformer:
> 
> ```
> def forward(self, x, context=None):
>     # note: if no context is given, cross-attention defaults to self-attention
>     b, c, h, w = x.shape
>     x_in = x
>     x = self.norm(x)
>     x = self.proj_in(x)
>     x = rearrange(x, 'b c h w -> b (h w) c')
>     for block in self.transformer_blocks:
>         x = block(x, context=context)
>     x = rearrange(x, 'b (h w) c -> b c h w', h=h, w=w).contiguous()
>     # x = rearrange(x, 'b (h w) c -> b c h w', h=h, w=w)
>     x = self.proj_out(x)
>     return x + x_in
> ```
> 
> Thanks a lot!



> hi @mrsalehi , could you tell me how you fixed the warning more specifically? And maybe provide your code,that would be great! I add .contiguous,but it didn't work,here is my code in the class SpatialTransformer:
> 
> ```
> def forward(self, x, context=None):
>     # note: if no context is given, cross-attention defaults to self-attention
>     b, c, h, w = x.shape
>     x_in = x
>     x = self.norm(x)
>     x = self.proj_in(x)
>     x = rearrange(x, 'b c h w -> b (h w) c')
>     for block in self.transformer_blocks:
>         x = block(x, context=context)
>     x = rearrange(x, 'b (h w) c -> b c h w', h=h, w=w).contiguous()
>     # x = rearrange(x, 'b (h w) c -> b c h w', h=h, w=w)
>     x = self.proj_out(x)
>     return x + x_in
> ```
> 
> Thanks a lot!

hey @superhero-7 Did you slove this problem? I met the same situation. Adding .contiguous didn't work :(

**Comment by akameswa** [comment]
@zbzbzbb95 The warning is harmless according to the attached references. 
1. https://github.com/pytorch/pytorch/issues/83909
2. https://github.com/huggingface/peft/issues/941
