### ISSUE TITLE
[Pipeline] ScaleCrafter: Tuning-free Higher-Resolution Visual Generation with Diffusion Models

### ISSUE THREAD

**Issue by ayushtues** [huggingface/diffusers#5442]
### Model/Pipeline/Scheduler description

ScaleCrafter: Tuning-free Higher-Resolution Visual Generation with Diffusion Models : https://yingqinghe.github.io/scalecrafter/

TLDR from github repo : ScaleCrafter is capable of generating images with a resolution of 4096 x 4096 and videos with a resolution of 2048 x 1152 based on pre-trained diffusion models on a lower resolution. Notably, our approach needs no extra training/optimization.

Code: https://github.com/yingqinghe/scalecrafter
Project Page : https://yingqinghe.github.io/scalecrafter/

Built on top of diffusers, so should be easy to add

![image](https://github.com/huggingface/diffusers/assets/43698245/75558f77-a256-41f6-ac06-35124e267224)

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by ayushtues** [comment]
Happy to pick this up if it seems interesting enough

**Comment by DN6** [comment]
Hi @ayushtues We can definitely add this to our community pipelines if you're interested in working on it?

**Comment by ayushtues** [comment]
Hi sure, happy to work on it!
