### ISSUE TITLE
Integrate Pixart Alpha

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [huggingface/diffusers#5444]
Pixart Alpha is a new generative model that makes 1024x1024 images with just 600m parameters (!).

Paper: https://pixart-alpha.github.io/

![carousel2](https://github.com/huggingface/diffusers/assets/110263573/271c93a6-1d3f-443c-9432-575eda5a57f7)

> The most advanced text-to-image (T2I) models require significant training costs (e.g., millions of GPU hours), seriously hindering the fundamental innovation for the AIGC community while increasing CO2 emissions. This paper introduces PIXART-α, a Transformer-based T2I diffusion model whose image generation quality is competitive with state-of-the-art image generators (e.g., Imagen, SDXL, and even Midjourney), reaching near-commercial application standards. Additionally, it supports high-resolution image synthesis up to 1024px resolution with low training cost, as shown in Figure 1 and 2. To achieve this goal, three core designs are proposed: (1) Training strategy decomposition: We devise three distinct training steps that separately optimize pixel dependency, text-image alignment, and image aesthetic quality; (2) Efficient T2I Transformer: We incorporate cross-attention modules into Diffusion Transformer (DiT) to inject text conditions and streamline the computation-intensive class-condition branch; (3) High-informative data: We emphasize the significance of concept density in text-image pairs and leverage a large Vision-Language model to auto-label dense pseudo-captions to assist text-image alignment learning. As a result, PIXART-α's training speed markedly surpasses existing large-scale T2I models, e.g., PIXART-α only takes 10.8% of Stable Diffusion v1.5's training time (~675 vs. ~6,250 A100 GPU days), saving nearly $300,000 ($26,000 vs. $320,000) and reducing 90% CO2 emissions. Moreover, compared with a larger SOTA model, RAPHAEL, our training cost is merely 1%. Extensive experiments demonstrate that PIXART-α excels in image quality, artistry, and semantic control. We hope PIXART-α will provide new insights to the AIGC community and startups to accelerate building their own high-quality yet low-cost generative models from scratch. 

Weights: https://huggingface.co/PixArt-alpha/PixArt-alpha
Inference code: https://github.com/PixArt-alpha/PixArt-alpha

**Comment by patrickvonplaten** [comment]
Very cool! Does the model work well?

**Comment by isamu-isozaki** [comment]
![fid](https://github.com/huggingface/diffusers/assets/23430101/848ac19f-59c3-4226-a5a5-eb9e8f0ff168)
![understanding text](https://github.com/huggingface/diffusers/assets/23430101/7df1ffb3-4946-4c87-b965-39c8679383c9)
fid is similar to sd1.5 but seems to have a better understanding of text

**Comment by AmericanPresidentJimmyCarter** [comment]
Bumping this for more info:

1. The model is available on CivitAI for anyone looking for it, they had officially released the weights a while ago and then removed the it from their HF (?). Regardless they are now widely available.
2. The model uses the exact same code as from IF for conditioning, so that much is the same.

**Comment by adhikjoshi** [comment]
Model is really really good, we should have it

**Comment by patrickvonplaten** [comment]
Weights are not available yet, see: https://github.com/PixArt-alpha/PixArt-alpha#-download-models

**Comment by AmericanPresidentJimmyCarter** [comment]
Regardless of what they state on their github, the weights are available.

**Comment by sayakpaul** [comment]
Yeah this model will be integrated and I have a good amount of progress. See `feat/pixart-alpha`. We are in touch with the original authors regarding the weights. So, when that is out, we should be good to go.
