### ISSUE TITLE
ValueError on FlaxStableDiffusionPipeline

### ISSUE THREAD

**Issue by YusukeSuzuki** [huggingface/diffusers#5450]
### Describe the bug

`FlaxStableDiffusionPipeline.__call__()` raises `ValueError: assignment destination is read-only`.

Probably NSFW filters are involved.

### Reproduction

- FlaxStableDiffusionPipeline
- 'CompVis/stable-diffusion-v1-4'
- revision='bf16'
- dtype=jnp.bfloat16
- prompt 'pretty asian girl' (no negative prompt)

### Logs

```shell
File "diffusers-api/diffusers_tasks.py", line 27, in generate
    images = app.pipeline(prompt_ids, p_params, rng, jit=True)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ".anyenv/envs/pyenv/versions/3.11.6/envs/diffusion/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py", line 419, in __call__
    images[i] = np.asarray(images_uint8_casted[i])
    ~~~~~~^^^
ValueError: assignment destination is read-only
```

### System Info

jax/flax cuda environment
diffusers 0.21.4

**Comment by patrickvonplaten** [comment]
Hey @YusukeSuzuki,

This error has nothing to do with `diffusers` per-se but instead with how Flax/JAX works.
