### ISSUE TITLE
What is function of `attention_mask` in `get_attention_scores`?

### ISSUE THREAD

**Issue by g-jing** [huggingface/diffusers#5457]
What is function of `attention_mask` in `get_attention_scores`? I guess it is used to ignore some value when calculating the attention map
I can not find a example in diffusers library that actually use this `attention_mask`. Could you provide an example on how to use it?

https://github.com/huggingface/diffusers/blob/e5168588864d72a4dca37e90318c6b11da0eaaf1/src/diffusers/models/attention_processor.py#L454

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/blob/1ade42f72998ec47147cb35e10f5d2283737e420/src/diffusers/pipelines/unclip/pipeline_unclip.py#L396

Karlo uses it
