### ISSUE TITLE
sdxl image-to-image load lora file: ValueError: Cannot load because down.weight expected shape

### ISSUE THREAD

**Issue by kolar1988** [huggingface/diffusers#5466]
### Describe the bug

I am trying to run image-to-image with sdxl model and lora file, but when pipe.load_lora_weights is error.

same model and same lora file, text-to-image  is well.

### Reproduction

pipe = SDXLLongPromptWeightingPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0",
                                                                   torch_dtype=torch.float16,
                                                                   use_safetensors=False,
                                                                   variant="fp16")
pipe.load_lora_weights(local_lora_path)

local_lora_path : https://civitai.com/models/120096/pixel-art-xl 

### Logs

```shell
pipe.load_lora_weights(local_lora_path)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 1071, in load_lora_weights
    self.load_lora_into_unet(state_dict, network_alphas=network_alphas, unet=self.unet)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/loaders.py", line 1456, in load_lora_into_unet
    unet.load_attn_procs(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/loaders.py", line 462, in load_attn_procs
    load_model_dict_into_meta(lora, value_dict, device=device, dtype=dtype)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/modeling_utils.py", line 144, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load because down.weight expected shape tensor(..., device='meta', size=(16, 1536)), but got torch.Size([16, 1280]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.
```

### System Info

diffusers                    0.21.4
pytorch-lightning            1.5.9
torch                        1.13.1

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
Need a fully reproducible and minimal code snippet for us to look further.

**Comment by kolar1988** [comment]
oh, sorry, the problem with my own code

**Comment by Tinaa23** [comment]
> I am trying to run image-to-image with sdxl model and lora file, but when pipe.load_lora_weights is error.
> 
> same model and same lora file, text-to-image is well.
> 
> ### Reproduction
> pipe = SDXLLongPromptWeightingPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, use_safetensors=False, variant="fp16") pipe.load_lora_weights(local_lora_path)
> 
> local_lora_path : https://civitai.com/models/120096/pixel-art-xl
> 
> ### Logs
> ```shell
> pipe.load_lora_weights(local_lora_path)
>   File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 1071, in load_lora_weights
>     self.load_lora_into_unet(state_dict, network_alphas=network_alphas, unet=self.unet)
>   File "/usr/local/lib/python3.8/dist-packages/diffusers/loaders.py", line 1456, in load_lora_into_unet
>     unet.load_attn_procs(
>   File "/usr/local/lib/python3.8/dist-packages/diffusers/loaders.py", line 462, in load_attn_procs
>     load_model_dict_into_meta(lora, value_dict, device=device, dtype=dtype)
>   File "/usr/local/lib/python3.8/dist-packages/diffusers/models/modeling_utils.py", line 144, in load_model_dict_into_meta
>     raise ValueError(
> ValueError: Cannot load because down.weight expected shape tensor(..., device='meta', size=(16, 1536)), but got torch.Size([16, 1280]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.
> ```
> 
> ### System Info
> diffusers 0.21.4 pytorch-lightning 1.5.9 torch 1.13.1
> 
> ### Who can help?
> @sayakpaul @patrickvonplaten

Hi @kolar1988 . I am facing a similar issue in my code but it happens when I want to load ip-adapter sdxl. Can you please tell how you fixed it? This is the error I am receiving: `ValueError: Cannot load because to_k_ip.0.weight expected shape tensor(..., device='meta', size=(320, 1280)), but got torch.Size([640, 2048]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`.`
