### ISSUE TITLE
[New Pipeline]: Rerender-A-Video: Zero-Shot Video-to-Video Translation

### ISSUE THREAD

**Issue by SingleZombie** [huggingface/diffusers#5467]
### Model/Pipeline/Scheduler description

We propose a zero-shot video-to-video translation framework for SD. (https://www.mmlab-ntu.com/project/rerender/)

Features:

* Temporal consistency: cross-frame constraints for low-level temporal consistency.
* Zero-shot: no training or fine-tuning required.
* Flexibility: compatible with off-the-shelf models (e.g., [ControlNet](https://github.com/lllyasviel/ControlNet), [LoRA](https://civitai.com/)) for customized translation.

### Open source status

- [X] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

Official Repo: https://github.com/williamyang1991/Rerender_A_Video
The Diffusers implementation is available in my personal repository: https://github.com/SingleZombie/diffusers-Rerender. You can follow the `README` to test the pipeline. We need some help to improve the codes:
1. We use `GMFlow` to compute the optical flow. However, `GMFlow` cannot be installed by pip. Currently we move the whole repo of `GMFlow`to the root directory.
2. We don't know what type our pipeline belongs to. StableDiffusion? Or ControlNet? Temporarily we put it under `stable_diffusion` folder  .
3. We need to calculate `pred_x0` with `DDIMSchduler`, but there is no available API and we have to use some dirty implementations. (P.S. we found the performance with `UniPCMultistepScheduler` is worse than with DDIM)

I think the first issue is the most critial. After the first issued is resovled, I will create a PR and let's work for the remaining issues in the PR.

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten and @DN6 here. 

> We use GMFlow to compute the optical flow. However, GMFlow cannot be installed by pip. Currently we move the whole repo of GMFlowto the root directory.

I think we can independently create a PyPI package for GMFlow just like we did for `controlnet_aux`: https://github.com/patrickvonplaten/controlnet_aux. We will of course, provide all the courtesy and credits to the original authors. 

> We don't know what type our pipeline belongs to. StableDiffusion? Or ControlNet? Temporarily we put it under stable_diffusion folder .

Since it's a zero-shot text-to-video pipeline, we could definitely put it under [`text_to_video_synthesis`](https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines/text_to_video_synthesis) just like we have put `TextToVideoZero`.

> We need to calculate pred_x0 with DDIMSchduler, but there is no available API and we have to use some dirty implementations. (P.S. we found the performance with UniPCMultistepScheduler is worse than with DDIM)

Should be possible to implement a patch for it. 

Let me know if there are any other questions.

**Comment by SingleZombie** [comment]
> Cc: @patrickvonplaten and @DN6 here.
> 
> > We use GMFlow to compute the optical flow. However, GMFlow cannot be installed by pip. Currently we move the whole repo of GMFlowto the root directory.
> 
> I think we can independently create a PyPI package for GMFlow just like we did for `controlnet_aux`: https://github.com/patrickvonplaten/controlnet_aux. We will of course, provide all the courtesy and credits to the original authors.
> 
> > We don't know what type our pipeline belongs to. StableDiffusion? Or ControlNet? Temporarily we put it under stable_diffusion folder .
> 
> Since it's a zero-shot video-to-video pipeline, we could definitely put it under [`text_to_video_synthesis`](https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines/text_to_video_synthesis) just like we have put `TextToVideoZero`.
> 
> > We need to calculate pred_x0 with DDIMSchduler, but there is no available API and we have to use some dirty implementations. (P.S. we found the performance with UniPCMultistepScheduler is worse than with DDIM)
> 
> Should be possible to implement a patch for it.
> 
> Let me know if there are any other questions.

Thanks for your responce. I will move the codes to `text to video synthesis` folder. Since we have no idea how to create a PyPI package, could you help us do it? Or is there any guides?

**Comment by sayakpaul** [comment]
We can, for sure. But I would like to seek some advice from @patrickvonplaten before that :-)

**Comment by patrickvonplaten** [comment]
Could we add the pipeline as a community pipeline maybe?

**Comment by SingleZombie** [comment]
> Could we add the pipeline as a community pipeline maybe?

Sure. What is the difference between a community pipeline and a normal pipeline? A community pipeline only has one file in `examples/community/` ?  Once the gmflow package is ready, I will create a PR.

**Comment by sayakpaul** [comment]
It's easier to get a community pipeline into `diffusers`. It's also easier to maintain long-term. It keep the core library source-code lightweight.

**Comment by abi98213** [comment]
Hey @SingleZombie we tested the pipeline for verification and found that it is not producing coherent results as the original repo does produce. Is that the case or the diffusers fork produces same quality results ?
Thanks

**Comment by SingleZombie** [comment]
> Hey @SingleZombie we tested the pipeline for verification and found that it is not producing coherent results as the original repo does produce. Is that the case or the diffusers fork produces same quality results ? Thanks

I think it is because the original repo uses Ebsynth to postprocess the results. In Diffusers pipeline we only implement the diffusion processing module.

**Comment by SingleZombie** [comment]
> We can, for sure. But I would like to seek some advice from @patrickvonplaten before that :-)

Hi @sayakpaul, is there any progress on the GMFlow PyPI package?

**Comment by sayakpaul** [comment]
Well, I think it can still be added as a community pipeline. We will need to add the installation instructions in the README of the community pipelines so that users always install GMFlow before running the pipeline. Would this work?

**Comment by SingleZombie** [comment]
> Well, I think it can still be added as a community pipeline. We will need to add the installation instructions in the README of the community pipelines so that users always install GMFlow before running the pipeline. Would this work?

Got it. We will create a PR soon.

**Comment by tin2tin** [comment]
@sayakpaul Do you still plan to make the GMFlow PyPI package available?
