### ISSUE TITLE
SDXL inpaint UNet2DConditionModel: TyperError in regards with added_cond_kwargs.get("text_embeds")

### ISSUE THREAD

**Issue by IoannisDem** [huggingface/diffusers#5471]
### Describe the bug

Hello,

I am trying to utilize the UNet2DConditionModel from diffusers and when I pass the parameters needed it throws an error. From my understanding StabilityAI uses the same unet for "stabilityai/stable-diffusion-2-inpainting" and when I call the UNet2DConditionModel using the equivalent code it works.
Does it make any difference if I am using SDXL or SD2in this scenario? But even if it doesnt matter, why does it raises the error?

Thank you in advance!

### Reproduction

inpaint_unet = UNet2DConditionModel.from_pretrained("diffusers/stable-diffusion-xl-1.0-inpainting-0.1",
                                                    subfolder="unet", 
                                                    use_auth_token=token).to('cuda')

latent_model_input_inpaint = torch.rand([2, 9, 64, 64])
t = torch.Tensor([781])
encoder_hidden_states = torch.rand([2, 77, 1024])

output_xl = inpaint_unet(latent_model_input_inpaint, t, encoder_hidden_states)

### Logs

```shell
873     aug_emb = self.add_embedding(text_embs, image_embs)
    874 elif self.config.addition_embed_type == "text_time":
    875     # SDXL - style
--> 876     if "text_embeds" not in added_cond_kwargs:
    877         raise ValueError(
    878             f"{self.__class__} has the config param `addition_embed_type` set to 'text_time' which requires the keyword argument `text_embeds` to be passed in `added_cond_kwargs`"
    879         )
    880     text_embeds = added_cond_kwargs.get("text_embeds")

TypeError: argument of type 'NoneType' is not iterable
```

### System Info

diffusers: 0.21.4
python:: 3.10
sagemaker

### Who can help?

@yiyixuxu @sayakpaul @DN6 @patrickvonplaten @DN6 @yiyixuxu @sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
No need to tag four team members for this :-) 

As the error correctly says, you are not specifying the inputs to the UNet. I would suggest, referring to the source code of the pipeline especially where the UNet is involved to know how it should be provided with inputs.

**Comment by sayakpaul** [comment]
SDXL UNet is different. It takes additional embeddings which are required inputs hence my suggestion.

**Comment by IoannisDem** [comment]
Thank you!
This is done by using the 'addition_time_embed_dim' under the  @register_to_config of the UNet module correct?
I am still not quite what the additional embedding should look like wrt to the content (image and text) but I will try to figure it out.
If you have any advise I would love to here.

**Comment by sayakpaul** [comment]
I suggest you to take a look at the SDXL training scripts (example [here](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sdxl.py)) to see how those additional input embeddings are formed.

**Comment by CVerSMH** [comment]
> 哈哈哈对不起，这是我提出的第一个问题。在 stabilityai sd2 的情况下，我使用完全相同的输入并且它有效，并且从他们的源代码来看，他们似乎使用相同的 UNET。另外，我不太确定我错过了什么，因为我相信所有三个输入都提供了。

Hello, how did you solve this problem?
