### ISSUE TITLE
[New Pipeline] Stable Diffusion Reference Only. Zero-shot secondary creation of any character, line art coloring, style transfer. Different from ControlNet Reference Only and more stable powerful.

### ISSUE THREAD

**Issue by aihao2000** [huggingface/diffusers#5474]
### Model/Pipeline/Scheduler description

This is my latest work. Stable Diffusion Reference Only is an Imgs2Img pipeline. Only 4G/8G VRAM is needed to implement secondary creation of any character, line drawing coloring, and style transfer. It contains a new pipeline and a new UNetModel. Are diffusers interested in adding this work? According to tests, the stability is higher than Mutl-ControlNet Reference Only + Any condition.
The tests and code can be viewed at https://github.com/aihao2000/stable-diffusion-reference-only

### Open source status

- [X] The model implementation is available
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/aihao2000/stable-diffusion-reference-only

**Comment by aihao2000** [comment]
@sayakpaul https://github.com/huggingface/diffusers/issues/5553. We should be able to continue on this issue. My work needs to contain a custom pipeline and a custom module. And I have a pretrained model stored on huggingfacehub. It turns out that you can directly call StableDiffusionReferenceOnly.from_trained like https://colab.research.google.com/drive/1aLKbm8YAXsGP2Y3umx0letLIY_rhl8VL?usp=sharing. But it doesn’t work after the recent update. It seems that I can’t find the module I wrote myself.
```
ValueError Traceback (most recent call last)
in <cell line: 1>()
----> 1 automatic_coloring_pipeline = StableDiffusionReferenceOnlyPipeline.from_pretrained(
2 "AisingioroHao0/stable-diffusion-reference-only-automatic-coloring-0.1.2"
3 ).to(device)
4 automatic_coloring_pipeline.scheduler = UniPCMultistepScheduler.from_config(
5 automatic_coloring_pipeline.scheduler.config

1 frames
[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py](https://localhost:8080/#) in download(cls, pretrained_model_name, **kwargs)
1683 custom_components[component] = module_candidate
1684 elif module_candidate not in LOADABLE_CLASSES and not hasattr(pipelines, module_candidate):
-> 1685 raise ValueError(
1686 f"{candidate_file} as defined in model_index.json does not exist in {pretrained_model_name} and is not a module in 'diffusers/pipelines'."
1687 )

ValueError: unet/stable_diffusion_reference_only.models.unet_2d_dobule_condition.py as defined in model_index.json does not exist in AisingioroHao0/stable-diffusion-reference-only-automatic-coloring-0.1.2 and is not a module in 'diffusers/pipelines'.
```

**Comment by sayakpaul** [comment]
I took a look into your Hub repo. I don't think you're following what's instructed in https://huggingface.co/docs/diffusers/main/en/using-diffusers/custom_pipeline_overview.

Please ensure your structure is _exactly_ as instructed in the docs.

**Comment by aihao2000** [comment]
@sayakpaul Why add these format checks? Or is it not good to just let it print a warning instead of raising an error? Originally, I only needed to install my package and then use my Pipeline class to call from_pretrained. It seems that I have to put some code into the model repository, or maintain a huggingface hub code repository in a different format.

**Comment by aihao2000** [comment]
@sayakpaul According to my testing, although there is a commit that adds the ability to load custom modules and pipeline codes from huggingfacehub, when I have relevant code locally, this is unnecessary and unnecessary errors are reported. I haven't looked at the source code carefully, but according to my testing, just change the ```raise error``` to ```print``` or ```log``` in any way you like. It will not affect normal work and is more powerful. I strongly recommend modifying it

**Comment by sayakpaul** [comment]
Feel free to PR.
