### ISSUE TITLE
Is a DreamBooth model wegiths trained with xformers_memory_efficient_attention could be loaded into a model without xformers_memory_efficient_attention?

### ISSUE THREAD

**Issue by g-jing** [huggingface/diffusers#5476]
I am training DreamBooth following https://github.com/huggingface/diffusers/blob/main/examples/custom_diffusion/README.md. Could a DreamBooth model wegiths trained with xformers_memory_efficient_attention be loaded into a model without xformers_memory_efficient_attention? Thanks.

**Comment by patrickvonplaten** [comment]
Yes sure, you can use a model that has been trained with xformers without xformers afterward
