### ISSUE TITLE
Request implementation of EDM

### ISSUE THREAD

**Issue by Luciennnnnnn** [huggingface/diffusers#5480]
### Model/Pipeline/Scheduler description

https://github.com/NVlabs/edm

These schedulers looks great! The results in paper demonstrated better performance than popular scheduler DDPM/DDIM.

### Open source status

- [X] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/NVlabs/edm

**Comment by isamu-isozaki** [comment]
Huh aren't those schedulers already implemented as "karras" schedulers https://huggingface.co/docs/diffusers/api/schedulers/overview

**Comment by Luciennnnnnn** [comment]
@patrickvonplaten Yeah, #4481 is what I look for, thanks.
