### ISSUE TITLE
segmind/SSD-1B training on train_dreambooth_lora_sdxl.py & train_text_to_image_lora_sdxl.py

### ISSUE THREAD

**Issue by danieltanhx** [huggingface/diffusers#5487]
Can allow the script to run on distilled SDXL? the script can't run because of fp16 safetensor in the text_encoders,vae and unets of segmind/SSD-1B. https://huggingface.co/segmind/SSD-1B

**Comment by patrickvonplaten** [comment]
I think it should work out of the box no?

**Comment by danieltanhx** [comment]
In the end up, i converted text_encoders,vae,unet weights to fp32 based on https://github.com/danieltanhx/sd-model-converter.git. The author of that repo will add in fp32 weights https://huggingface.co/segmind/SSD-1B/discussions/1

**Comment by danieltanhx** [comment]
close

**Comment by danieltanhx** [comment]
@patrickvonplaten, i added variant as one of my arg params in order to accept fp16 weight locally. it will be best to add variant for all the training scripts
