### ISSUE TITLE
[Request]Add swiglu activation function support

### ISSUE THREAD

**Issue by ezra-ch** [huggingface/diffusers#5490]
Add in swiglu support for attention.py and activations.py please. swiglu is the go to activation function for many SOTA LLM models and audio models.

**Comment by ezra-ch** [comment]
If anyone is interested I implemented a hack
#https://github.com/ezra-ch/diffusers/commit/81a27e5f0bb10436ff5dc8964897747cbb3de00a
Implementing the following
![image](https://github.com/huggingface/diffusers/assets/69337319/d2dc7d2d-3202-486a-ad1e-abbdc14cb2df)
I'm not sure if its correct but it trains.

**Comment by ezra-ch** [comment]
If anyone is interested I attempted an implementation
#https://github.com/ezra-ch/diffusers/commit/81a27e5f0bb10436ff5dc8964897747cbb3de00a
Implementing the following for feedforward using SwiGLU 
![image](https://github.com/huggingface/diffusers/assets/69337319/0bce1653-415f-43bb-b176-1d68b0e155f0)
I'm not sure if its correct but it trains.

**Comment by sayakpaul** [comment]
Will stand by what I said here: https://github.com/huggingface/diffusers/issues/5490#issuecomment-1775042831.
