### ISSUE TITLE
inpaint background with kandinsky2.2

### ISSUE THREAD

**Issue by crapthings** [huggingface/diffusers#5494]
the inpaint background is failed, what's wrong?

![a](https://github.com/huggingface/diffusers/assets/1147704/e8e5248d-3540-4108-8eda-5d382f6bbf0b)
![amsk](https://github.com/huggingface/diffusers/assets/1147704/4979ae0c-26ea-44af-87ef-4740cf4eb8f9)
![download (7)](https://github.com/huggingface/diffusers/assets/1147704/797b30e5-7d37-4dcf-8169-9b817ed9bc68)
![mask123](https://github.com/huggingface/diffusers/assets/1147704/882e1cdb-73ab-4d14-9b77-72c8c008b654)

```py
import torch
import numpy as np
from PIL import Image, ImageOps
from diffusers import AutoPipelineForInpainting
import rembg

modelName = 'kandinsky-community/kandinsky-2-2-decoder-inpaint'

pipe = AutoPipelineForInpainting.from_pretrained(modelName, torch_dtype = torch.float16).to('cuda')
# pipe.enable_model_cpu_offload()


prompt = 'young lady, in front of garden, beautiful, 4k'

image = Image.open('./a.jpg')
mask = Image.open('./mask123.png').convert('RGB')
# mask = ImageOps.invert(mask)
# mask = mask.convert('L')
# mask = np.array(mask)

image = pipe(
    image = image,
    mask_image = mask,
    prompt = prompt,
    width = image.width,
    height = image.height,
    num_inference_steps = 50,
    # prior_steps = 10,
).images[0]

display(image)
```

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu

**Comment by yiyixuxu** [comment]
will ask the authors
I don't think this is a bug - the model might just not work well for outpainting
