### ISSUE TITLE
Unclear sentence in docs about torch.compile and image size

### ISSUE THREAD

**Issue by holwech** [huggingface/diffusers#5495]
I was reading the [docs](https://huggingface.co/docs/diffusers/optimization/torch2.0#using-accelerated-transformers-and-torchcompile) about using `torch.compile` and saw the following sentence:

> Calling the compiled pipeline on a different image size will re-trigger compilation which can be expensive.

What exactly is meant by this? If inference is done at 512px image size and then afterwards at 768px, this will re-trigger compilation?

If that's the case, why is this happening? Does the image size affect the unet somehow?

**Comment by patrickvonplaten** [comment]
> What exactly is meant by this? If inference is done at 512px image size and then afterwards at 768px, this will re-trigger compilation?

Yes

> If that's the case, why is this happening? Does the image size affect the unet somehow?

Compilation in machine learning not only depends on the function, but also on the input shapes. If you change the input shape torch.compile sees this as a new function that needs to be compiled

**Comment by patrickvonplaten** [comment]
> What exactly is meant by this? If inference is done at 512px image size and then afterwards at 768px, this will re-trigger compilation?

Yes

> If that's the case, why is this happening? Does the image size affect the unet somehow?

Compilation in machine learning not only depends on the function, but also on the input shapes. If you change the input shape torch.compile sees this as a new function that needs to be compiled

**Comment by holwech** [comment]
Thanks, makes sense :)
