### ISSUE TITLE
ControlNet Scribble with SDXL

### ISSUE THREAD

**Issue by rafationgson** [huggingface/diffusers#5503]
Hello! I would like to ask if there will be support for Controlnet scribble with SDXL. Currently I have only seen models for canny, depth and openpose.

**Comment by patrickvonplaten** [comment]
cc @patil-suraj as well

**Comment by sayakpaul** [comment]
Have you tried out the T2I Adapter? 

https://huggingface.co/spaces/TencentARC/T2I-Adapter-SDXL-Sketch

It's quite high-quality.

**Comment by rafationgson** [comment]
Tried T2I Adapter and the results are good. Thank you!
