### ISSUE TITLE
LCM pipeline fails when initialized without scheduler

### ISSUE THREAD

**Issue by a-r-r-o-w** [huggingface/diffusers#5515]
### Describe the bug

I installed the latest version of diffusers on colab after #5448 was merged. The LCM pipeline fails to initialize when using the code present in [docs](https://github.com/huggingface/diffusers/blob/main/docs/source/en/api/pipelines/latent_consistency_models.md) with the error:

```
ValueError: Pipeline <class 'diffusers.pipelines.latent_consistency_models.pipeline_latent_consistency_models.LatentConsistencyModelPipeline'> expected {'text_encoder', 'scheduler', 'feature_extractor', 'vae', 'safety_checker', 'tokenizer', 'unet'}, but only {'text_encoder', 'feature_extractor', 'vae', 'safety_checker', 'tokenizer', 'unet'} were passed.
```

### Reproduction

Install the version of diffusers post #5448. Also need `transformers` to be installed.

```py
import torch
from diffusers import DiffusionPipeline, LatentConsistencyModelPipeline, LCMScheduler

pipe = LatentConsistencyModelPipeline.from_pretrained( # or DiffusionPipeline.from_pretrained
    "SimianLuo/LCM_Dreamshaper_v7",
    torch_dtype=torch.float32,
)
pipe.to(torch_device="cuda", torch_dtype=torch.float32)
```

Above code fails with the errors as mentioned in logs. To be able to use it, I have to do something like:

```py
scheduler = LCMScheduler.from_pretrained(
    "SimianLuo/LCM_Dreamshaper_v7",
    subfolder="scheduler"
)
pipe = LatentConsistencyModelPipeline.from_pretrained( # or DiffusionPipeline.from_pretrained
    "SimianLuo/LCM_Dreamshaper_v7",
    scheduler=scheduler
)
pipe.to(torch_device="cuda", torch_dtype=torch.float32)
```

### Logs

```shell
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: 

pip install accelerate
.
Loading pipeline components...: 100%
5/5 [00:36<00:00, 10.37s/it]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-54-80a9e89ed402> in <cell line: 1>()
----> 1 pipe = DiffusionPipeline.from_pretrained(
      2     "SimianLuo/LCM_Dreamshaper_v7",
      3     torch_dtype=torch.float32,
      4     safety_checker=None
      5 )

/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
   1290         elif len(missing_modules) > 0:
   1291             passed_modules = set(list(init_kwargs.keys()) + list(passed_class_obj.keys())) - optional_kwargs
-> 1292             raise ValueError(
   1293                 f"Pipeline {pipeline_class} expected {expected_modules}, but only {passed_modules} were passed."
   1294             )

ValueError: Pipeline <class 'diffusers.pipelines.latent_consistency_models.pipeline_latent_consistency_models.LatentConsistencyModelPipeline'> expected {'text_encoder', 'scheduler', 'feature_extractor', 'vae', 'safety_checker', 'tokenizer', 'unet'}, but only {'text_encoder', 'feature_extractor', 'vae', 'safety_checker', 'tokenizer', 'unet'} were passed.
```

### System Info

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.1
- Accelerate version: not installed
- xFormers version: not installed
- Using GPU in script?: True
- Using distributed or parallel set-up in script?: False

### Who can help?

@patrickvonplaten @dg845

**Comment by dg845** [comment]
Hi @a-r-r-o-w, the [`SimianLuo/LCM_Dreamshaper_v7`](https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7) checkpoint has not been updated to work with the official `diffusers` pipeline yet (https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7/discussions/7 needs to be merged). I think [`dg845/imagebind-test-dev`](https://huggingface.co/dg845/imagebind-test-dev) should work with the official pipeline as a stopgap solution.

Note that once https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7/discussions/7 is merged, compatibility with the community pipeline will be broken (see https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7/discussions/10). The `SimianLuo/LCM_Dreamshaper_v7` checkpoint can still be used with the community pipeline via a `revision` to `from_pretrained` as follows:

```python
from diffusers import DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained(
    "SimianLuo/LCM_Dreamshaper_v7",
    custom_pipeline="latent_consistency_txt2img",
    custom_revision="main",
    revision="fb9c5d",
)
```

**Comment by dg845** [comment]
The checkpoint PRs ([7](https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7/discussions/7), [10](https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7/discussions/10)) have been merged. The following code should work now:

```python
from diffusers import LatentConsistencyModelPipeline

pipe = LatentConsistencyModelPipeline.from_pretrained("SimianLuo/LCM_Dreamshaper_v7")
```

**Comment by a-r-r-o-w** [comment]
> Hi @a-r-r-o-w, the [`SimianLuo/LCM_Dreamshaper_v7`](https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7) checkpoint has not been updated to work with the official `diffusers` pipeline yet (https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7/discussions/7 needs to be merged). I think [`dg845/imagebind-test-dev`](https://huggingface.co/dg845/imagebind-test-dev) should work with the official pipeline as a stopgap solution.
> 
> Note that once https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7/discussions/7 is merged, compatibility with the community pipeline will be broken (see https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7/discussions/10). The `SimianLuo/LCM_Dreamshaper_v7` checkpoint can still be used with the community pipeline via a `revision` to `from_pretrained` as follows:
> 
> ```python
> from diffusers import DiffusionPipeline
> 
> pipe = DiffusionPipeline.from_pretrained(
>     "SimianLuo/LCM_Dreamshaper_v7",
>     custom_pipeline="latent_consistency_txt2img",
>     custom_revision="main",
>     revision="fb9c5d",
> )
> ```
> 
> [In particular, the way the pipeline loads the `scheduler` from the checkpoint is different, which is why instantiating the `scheduler` separately and then loading the rest of the pipeline with `from_pretrained` works.]

Ah! Alright, that makes sense. And yep, after the merge it's working as expected. Thanks for your awesome work integrating LCM!

Marking this issue as closed.
