### ISSUE TITLE
Network unreachable

### ISSUE THREAD

**Issue by unrue** [huggingface/diffusers#5519]
Hi,
I'm using dreambooth on HPC machine. After installing and configuration as required, when launched on compute node dreambooth get "Network unreachable" error. I think is trying to download the models, but compute node are not opened to internet. Is there a way to download such models before start and to indicate where to find? Thanks.

`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/CompVis/stable-diffusion-v1-4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14f0386f67f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
`

**Comment by unrue** [comment]
Ok, simply follow such manual: 

[https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main](url)

**Comment by patrickvonplaten** [comment]
Hey @unrue, 

You can simply pass a path to a local folder to the script:

```py
accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path <path/to/local/folder>
```
