### ISSUE TITLE
Bug in train_text_to_image_sdxl.py

### ISSUE THREAD

**Issue by julkaztwittera** [huggingface/diffusers#5529]
### Describe the bug

Every time I try to run `train_text_to_image_sdxl.py` I get the following error during mapping:

```
pyarrow.lib.ArrowInvalid: Column 2 named prompt_embeds expected length 1000 but got length 999
```
 I tried to add batch_size=1 but it caused even more errors further.

### Reproduction

```
export MODEL_NAME="stabilityai/stable-diffusion-xl-base-1.0"
export VAE_NAME="madebyollin/sdxl-vae-fp16-fix"
export DATASET_NAME="path_to_my_dataset"

accelerate launch train_text_to_image_sdxl.py \
  --dataset_name=$DATASET_NAME --caption_column="text" \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --pretrained_vae_model_name_or_path=$VAE_NAME \
  --enable_xformers_memory_efficient_attention \
  --resolution=128 --random_flip \
  --proportion_empty_prompts=0.2 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 --gradient_checkpointing \
  --max_train_steps=10000 \
  --learning_rate=1e-06 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --report_to="wandb" \
  --validation_prompt="Pororo and Crong at home" --validation_epochs 5 \
  --checkpointing_steps=5000 \
  --output_dir="sdxl-pororo_finetuning" \
  --push_to_hub
```

### System Info

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-6.1.0-1013-oem-x86_64-with-glibc2.35
- Python version: 3.11.4
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.1
- Accelerate version: 0.23.0
- xFormers version: 0.0.22.post4
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

**Comment by patrickvonplaten** [comment]
cc @DN6

**Comment by patrickvonplaten** [comment]
@julkaztwittera, We need to get access to a dummy dataset to reproduce this error. The above snippet doesn't work because we don't have:
```
export DATASET_NAME="path_to_my_dataset"
```

**Comment by julkaztwittera** [comment]
OK, I had one unlabeled image in my dataset which caused the problem.

**Comment by julkaztwittera** [comment]
OK, I had one unlabeled image in my dataset which caused the problem.
