### ISSUE TITLE
SDXL_DreamBooth_LoRA_.ipynb no longer working

### ISSUE THREAD

**Issue by ghost** [huggingface/diffusers#5537]
### Describe the bug

Hello !

SDXL_DreamBooth_LoRA_.ipynb is no longer working.

Seems to be incompatible with latest pytorch or xformers.

### Reproduction

Try to launch the default notebook on Google Colab T4 or copy paste the code in Kaggle T4. 

### Logs

```shell
On Google Colab :

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cu118)
    Python  3.10.13 (you have 3.10.12)

xFormers wasn't build with CUDA support
    requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)

On Kaggle :

UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)

ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU
```

### System Info

Default T4 config from Google Colab and Kaggle

**Comment by DN6** [comment]
HI @jvachez There are known issues with Torch 2.1 and xformers. Can you trying running the notebook without installing xformers.

**Comment by knoopx** [comment]
@jvachez it is telling you that you have a version mismatch between the cuda versions of xformers and pytorch (you have cuda 11.8 installed but xformers needs cuda 12.1).
