### ISSUE TITLE
Why is the pipeline_stable_diffusion_upscale.py file not using the encoder-decoder latent?

### ISSUE THREAD

**Issue by AnasHXH** [huggingface/diffusers#5538]
### Describe the bug

There is no training script for pipeline_stable_diffusion_upscale.py because the authors chose not to utilize the latent domain for the Super-resolution task. Additionally, the U-Net implemented in pipeline_stable_diffusion_upscale.py only accepts 7 channels. How is this achieved?

### Reproduction

None

### System Info

None

### Who can help?

[AnasHXH](https://github.com/AnasHXH)

**Comment by DN6** [comment]
Hi @AnasHXH The UNet in the super resolution model uses a latent noise tensor with shape `(batch, 4, image height, image width)` concatenated with the image which has a shape of `(batch, 3, image height, image width` resulting in 7 input channels.

**Comment by AnasHXH** [comment]
I'm aware of that, but since there's no encoding process applied to the image, there isn't a latent domain!
