### ISSUE TITLE
Inference out of memory

### ISSUE THREAD

**Issue by unrue** [huggingface/diffusers#5540]
I successfully trained Dreambooth with dog dataset test using HPc machine having Tesla V100 card, and pytorch 1.10.1, and now I'm trying to make inference from the manual, having a Cuda out of memory error:

```
from diffusers import StableDiffusionPipeline
import torch

model_id = "out_train"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
prompt = "A photo of sks dog in a bucket"
image = pipe(prompt, num_inference_steps=50, guidance_scale=7.5).images[0]
image.save("dog-bucket.png")


`  File "****/lib/python3.8/site-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 31.75 GiB total capacity; 1.02 GiB already allocated; 17.62 MiB free; 1.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`
```

How can be possible training works well and inference not? The gpu memory is free, not already occupied when the inference start

I tried also:
```
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:128
``
```

with no effect. Any suggest? Thanks.

**Comment by DN6** [comment]
Hi @unrue it is difficult to say from just this snippet and without access to your checkpoint. 

Can you confirm that your finetuned model checkpoint size is similar to the original? And what version of `diffusers` are you using?

**Comment by unrue** [comment]
Hi,

yes the finetuned model checkpoint size is similar to the original, in fact on cpu,  inference works well. I'm using diffusers 0.22.0.dev0

**Comment by DN6** [comment]
Hmm is it possible to share your checkpoint on the hub so that I can test? 

In the meantime, you could try replacing 
```
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
```
with 
```
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe.enable_model_cpu_offload()
```

to see if it helps.

**Comment by unrue** [comment]
Hi,

adding enable_model_cpu_offload not solved() the problem. I'm not used checkpoint during training. I can restart training, but it takes some time.

**Comment by DN6** [comment]
Hi sorry, I meant could you upload the checkpoint you are having this issue with to the HF Hub so that we can try to reproduce the error on our side.

**Comment by unrue** [comment]
Hi,

enabling checkpointing raise an Out of Memory during training phase :/

```
`    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 31.75 GiB total capacity; 29.29 GiB already allocated; 752.62 MiB free; 29.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
^MSteps:   0%|          | 1/200 [00:18<1:00:53, 18.36s/it, loss=0.0966, lr=5e-6]Traceback (most recent call last):
```
`

**Comment by unrue** [comment]
Hi,

I uploaded my model here:

[https://huggingface.co/gfatigati/Dog-text-encoder/tree/main/out_train_text_encoder](url)

**Comment by patrickvonplaten** [comment]
@unrue, please make sure to provide a minimal, reproducible code snippet. As long is there is no code snippet that we can copy-paste into a console, we can't treat this issue. We're only a few people maintaining this repo and can't have chats about incomplete code snippets and error messages on every issue. 

Thanks!

**Comment by unrue** [comment]
Hi,

I changed HPC system. Now I'm using Ampere Gpus. The inference run on GPU but is extremely slow. More than 30 minutes to make inference on a single image. I used train text encoder training, and the code is the same of above.  Why inference is so slow? Thanks.
