### ISSUE TITLE
Can any pre-trained model be inverted?

### ISSUE THREAD

**Issue by pikeyang** [huggingface/diffusers#5551]
I'm trying to invert face images, similar to diffae. I want to know if all pre-trained models have the ability to do image2latent, and then latent2image

**Comment by DN6** [comment]
HI @pikeyang if you're trying image inversion you can refer to 
https://huggingface.co/docs/diffusers/v0.21.0/en/api/pipelines/pix2pix_zero#pix2pix-zero

The current models/pipelines do not have `image2latent` methods built in to them.
