### ISSUE TITLE
Converting bin models to fp16?

### ISSUE THREAD

**Issue by Amin456789** [huggingface/diffusers#5554]
Hi!

can someone please tell me how can i convert fp32 diffuser models [the ones that have unet vae tokenizer etc.. folders that are used for stable diffusion] to fp16?
i can't find any tutorial or script but i can see some people converted their bin files in smaller size.
i need it cause i want to convert LCM dreamshaper model to fp16 and test it out

kind regards

**Comment by a-r-r-o-w** [comment]
Not sure if this is the correct way, but `diffusers/commands` contains code for converting to fp16 and can be used as:

```bash
diffusers-cli fp16_safetensors --ckpt_id=SimianLuo/LCM_Dreamshaper_v7 --fp16 --use_safetensors
```

Also not sure if this would work straight away though. See:
- #5515
- https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7/commit/40f68ba3f7b5f52e166d1cdaea4be8bc48c9f52a

**Comment by Amin456789** [comment]
thank u so much for answer, so we have to wait they support safetensors in the future,
but what about converting the bin file? do u know anyway that we can convert the bin to fp16? i mean pytorch_model.bin in unet they can be smaller without converting them to safetensors

**Comment by Amin456789** [comment]
damn what was i thinking :D, all the unet text encoder etc are in safetensors i though they are bin
anyway, i converted them to fp16 with sd webui [dunno, maybe older diffusers were being used], but with fastsdcpu i got bunch of errors so i gave up for now till official fp16 support someday

**Comment by Amin456789** [comment]
closing it for now
