### ISSUE TITLE
Not able to run the lora sdxl dreambooth script in the examples directory

### ISSUE THREAD

**Issue by mahendra0203** [huggingface/diffusers#5565]
### Describe the bug

When I run the dreambooth script for lora sdxl, I get the following error, 
"stabilityai/stable-diffusion-xl-base-1.0 does not appear to have a file named diffusion_pytorch_model.bin"

The full error being, Entry Not Found for url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/76d28af79639c28a79fa5c6c6468febd3490a37e/unet/diffusion_pytorch_model.bin
Seems like there is some change is required in the sdxl lora script

### Reproduction

run the command 
accelerate launch train_dreambooth_lora_sdxl.py   --pretrained_model_name_or_path=$MODEL_NAME    --instance_data_dir=$INSTANCE_DIR   --pretrained_vae_model_name_or_path=$VAE_PATH     --output_dir=$OUTPUT_DIR   --class_prompt="man"   --instance_prompt="a photo of TOK man"   --resolution=512   --train_batch_size=1   --gradient_accumulation_steps=4   --learning_rate=1e-5   --report_to="wandb"   --lr_scheduler="constant"   --lr_warmup_steps=0   --max_train_steps=1500   --validation_prompt="A photo of sks man looking at the camera "   --validation_epochs=100 

//Value of the command
#MODEL_NAME="stabilityai/stable-diffusion-xl-base-1.0"
#VAE_PATH="madebyollin/sdxl-vae-fp16-fix"

### Logs

```shell
Downloading (…)ch_model.safetensors:  88%|█████████████████████████████▊    | 9.02G/10.3G [01:43<00:14, 87.3MB/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/76d28af79639c28a79fa5c6c6468febd3490a37e/unet/diffusion_pytorch_model.bin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/diffusers/src/diffusers/utils/hub_utils.py", line 320, in _get_model_file
    model_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1608, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-653cc33b-777ff2016c8553204154baf4;d1f9d013-dc31-4a11-9f75-9ebe309e25f0)

Entry Not Found for url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/76d28af79639c28a79fa5c6c6468febd3490a37e/unet/diffusion_pytorch_model.bin.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1375, in <module>
    main(args)
  File "/workspace/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 704, in main
    unet = UNet2DConditionModel.from_pretrained(
  File "/workspace/diffusers/src/diffusers/models/modeling_utils.py", line 768, in from_pretrained
    model_file = _get_model_file(
  File "/workspace/diffusers/src/diffusers/utils/hub_utils.py", line 349, in _get_model_file
    raise EnvironmentError(
OSError: stabilityai/stable-diffusion-xl-base-1.0 does not appear to have a file named diffusion_pytorch_model.bin.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

### System Info

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-5.4.0-139-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.1
- Accelerate version: 0.24.0
- xFormers version: 0.0.22.post7
- Using GPU in script?: yes, only one gpu , running on runpod, 48 gb ram
- Using distributed or parallel set-up in script?: No

### Who can help?

Not able to run the lora sdxl dreambooth script in the examples directory
It isn't able to find 'diffusion_pytorch_model.bin" huggingface repo.

@yiyixuxu @sayakpaul @DN6 @patrickvonplaten

**Comment by sayakpaul** [comment]
Unable to reproduce. 

Could you reproduce the error in a Colab Notebook?

**Comment by mahendra0203** [comment]
Ok. Let me try to run it in a notebook.

**Comment by mahendra0203** [comment]
Tried running the code on this notebook, https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb .   

The model does run, but after finishing the training steps, it throws the following error ,



Steps: 100% 100/100 [05:56<00:00,  3.38s/it, loss=0.0255, lr=0.0001]Model weights saved in output_dir/pytorch_lora_weights.safetensors

Downloading (…)ain/model_index.json: 100% 609/609 [00:00<00:00, 2.96MB/s]

Fetching 17 files:   0% 0/17 [00:00<?, ?it/s]

Downloading (…)ch_model.safetensors:   0% 0.00/335M [00:00<?, ?B/s]

Downloading (…)ch_model.safetensors:   9% 31.5M/335M [00:00<00:01, 245MB/s]

Downloading (…)ch_model.safetensors:  19% 62.9M/335M [00:00<00:00, 278MB/s]

Downloading (…)ch_model.safetensors:  28% 94.4M/335M [00:00<00:01, 170MB/s]

Downloading (…)ch_model.safetensors:  34% 115M/335M [00:01<00:03, 57.5MB/s]

Downloading (…)ch_model.safetensors:  41% 136M/335M [00:02<00:05, 37.3MB/s]

Downloading (…)ch_model.safetensors:  47% 157M/335M [00:02<00:03, 49.6MB/s]

Downloading (…)ch_model.safetensors:  60% 199M/335M [00:02<00:01, 81.9MB/s]

Downloading (…)ch_model.safetensors:  69% 231M/335M [00:02<00:00, 107MB/s] 

Downloading (…)ch_model.safetensors:  78% 262M/335M [00:03<00:01, 53.6MB/s]

Downloading (…)ch_model.safetensors:  85% 283M/335M [00:04<00:00, 55.6MB/s]

Downloading (…)ch_model.safetensors: 100% 335M/335M [00:04<00:00, 73.6MB/s]

Fetching 17 files: 100% 17/17 [00:05<00:00,  3.34it/s]

Loading pipeline components...:   0% 0/7 [00:00<?, ?it/s]Loaded text_encoder as CLIPTextModel from `text_encoder` subfolder of stabilityai/stable-diffusion-xl-base-1.0.

Loading pipeline components...:  14% 1/7 [00:02<00:16,  2.82s/it]Loaded text_encoder_2 as CLIPTextModelWithProjection from `text_encoder_2` subfolder of stabilityai/stable-diffusion-xl-base-1.0.

Loading pipeline components...:  29% 2/7 [00:17<00:47,  9.56s/it]{'dropout', 'attention_type', 'reverse_transformer_layers_per_block'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth_lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--instance_data_dir=instance_data', '--output_dir=output_dir', '--mixed_precision=fp16', '--instance_prompt=a photo of sks man', '--resolution=512', '--train_batch_size=2', '--gradient_accumulation_steps=2', '--gradient_checkpointing', '--learning_rate=1e-4', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=100', '--checkpointing_steps=717']' died with <Signals.SIGKILL: 9>.

**Comment by sayakpaul** [comment]
The kernel died: 

> died with <Signals.SIGKILL: 9>.

But your original issue is resolved. So, I guess the issue can be closed?

**Comment by mahendra0203** [comment]
Sounds good. Thank you for your prompt response, @sayakpaul
