### ISSUE TITLE
How to set the "transformer_in" layer's hidden size in LoRA training?

### ISSUE THREAD

**Issue by lxycopper** [huggingface/diffusers#5575]
### Describe the bug

I modify the code for text-to-image [lora](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py) as Figure 1,
<img width="908" alt="image" src="https://github.com/huggingface/diffusers/assets/52530394/0639998b-8106-49d9-8761-c58014095e7e">
However, in 3D UNet there is a "transformer_in" layer that does not exist in 2D UNet. So I add "transformer_in" process in the code. And I set the "hidden_size" to be "unet.config.block_out_channels[0]" following the 3D UNet's definition as [this link](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unet_3d_condition.py) Figure 2:
<img width="641" alt="image" src="https://github.com/huggingface/diffusers/assets/52530394/c23efadc-e22d-4bd9-aa3f-7e69bd83a7c2">
But the there is a shape error as Figure 3
![image](https://github.com/huggingface/diffusers/assets/52530394/7a279e34-2af8-4409-8e93-606f61fd506f)
:

### Reproduction

Load a 3D UNet. Adapt the LoRA codes as Figure 1.

### System Info

- `diffusers` version: 0.21.4
- Platform: Linux-5.11.0-34-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.0.1 (True)
- Huggingface_hub version: 0.18.0
- Transformers version: 4.26.0
- Accelerate version: 0.23.0
- xFormers version: 0.0.22.post7
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @patrickvonplaten @DN6 @yiyi

**Comment by DN6** [comment]
@sayakpaul could you take a look here please.

**Comment by sayakpaul** [comment]
Since it's 3D, the layer dimensions would change too. We don't have LoRA compatible layers for the UNet3D model IIUC. 

I would recommend checking out SDXL LoRA DreamBooth training script and adapting it for your use case.

**Comment by lxycopper** [comment]
> Since it's 3D, the layer dimensions would change too. We don't have LoRA compatible layers for the UNet3D model IIUC.
> 
> I would recommend checking out SDXL LoRA DreamBooth training script and adapting it for your use case.

Thank you, hope you may update the LoRA layers for UNet3D.

**Comment by ShashwatNigam99** [comment]
Is there a plan to add LoRA support for UNet3D? It will become increasingly important with better text2video models coming in everyday. 

Is it possible to get some guidance (from someone more familiar with the codebase) as to what would be the right way to make edits in the current code to add LoRA support for UNet3D? I would like to take up the coding work - will prepare a rough change outline first and start working on it.

**Comment by sayakpaul** [comment]
We need checkpoints for testing that. But if you're looking to conduct LoRA training on UNet3D models in `diffusers` it should be easy with `peft`. Refer to https://github.com/huggingface/diffusers/pull/5388 for a (small) overview of the changes needed.
