### ISSUE TITLE
ControlNets not working correctly when FreeU is enabled

### ISSUE THREAD

**Issue by simonnxren** [huggingface/diffusers#5580]
ControlNets not working correctly when FreeU is enabled. Does anybody have the same issue?

**Comment by DN6** [comment]
@simonnxren Could you provide a code example we can use to reproduce your issue.

**Comment by simonnxren** [comment]
@DN6 Sorry, I accidently commented out some lines in my code, causing the controlnet scale goes to really low value. So, no issues at all, thanks!
