### ISSUE TITLE
UniDiffuser fail to load from checkpoints

### ISSUE THREAD

**Issue by jinhong-ni** [huggingface/diffusers#5592]
### Describe the bug

The current version of diffusers (I've tested on both 0.21.4 and 0.21.0) seems to falsely name the `image_processor` as `clip_image_processor`, where the latter is not expected by `UniDiffuserPipeline`, resulting in the `ValueError` indicating missing `image_processor`.

### Reproduction

import torch

from diffusers import UniDiffuserPipeline

device = "cuda"
model_id_or_path = "thu-ml/unidiffuser-v1"
pipe = UniDiffuserPipeline.from_pretrained(model_id_or_path, torch_dtype=torch.float16)
pipe.to(device)

sample = pipe(num_inference_steps=20, guidance_scale=8.0)
image = sample.images[0]
text = sample.text[0]
image.save("unidiffuser_joint_sample_image.png")
print(text)

### Logs

```shell
unet/diffusion_pytorch_model.safetensors not found
The config attributes {'clip_image_processor': ['transformers', 'CLIPImageProcessor']} were passed to UniDiffuserPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
Keyword arguments {'clip_image_processor': ['transformers', 'CLIPImageProcessor']} are not expected by UniDiffuserPipeline and will be ignored.
Loading pipeline components...: 100%|██████████| 8/8 [00:06<00:00,  1.18it/s]

ValueError: Pipeline <class 'diffusers.pipelines.unidiffuser.pipeline_unidiffuser.UniDiffuserPipeline'> expected {'vae', 'image_processor', 'text_decoder', 'clip_tokenizer', 'image_encoder', 'scheduler', 'unet', 'text_encoder', 'text_tokenizer'}, but only {'vae', 'text_decoder', 'clip_tokenizer', 'image_encoder', 'scheduler', 'unet', 'text_encoder', 'text_tokenizer'} were passed.
```

### System Info

- `diffusers` version: 0.21.0
- Platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.31
- Python version: 3.11.4
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.32.0
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@DN6 @yiyixuxu

**Comment by DN6** [comment]
Hi @jinhong-ni I think the Unidiffuser pipeline and checkpoint were updated recently, so there might be issues with `diffusers` version `0.21.0`. 

Could you try install diffusers from source and rerunning your code
```
pip install git+https://github.com/huggingface/diffusers.git
```
