### ISSUE TITLE
raise ValueError(f"`height` and `width` have to be divisible by 8 but are 427 and 640

### ISSUE THREAD

**Issue by BeijingBlueSky** [huggingface/diffusers#5595]
### Describe the bug

Hi, I am using diffuser for inpainting, and the size of input image is (427, 640),  to keep the input and output the same resolution, i set the `height=427` and `width=640` in the pipeline(e.g., `img = pipeline(prompt=prompt, image=init_image, mask_image=mask_image, height=427, width=640).images[0]`), but I get an error: `ValueError: `height` and `width` have to be divisible by 8 but are 427 and 640`. Does inpainting have to require the output to be a multiple of 8? Can I customize the output size? (Because I want to inpaint only the area which masked and keep the other areas unchanged)

### Reproduction

```python
import PIL
import torch
import numpy as np

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0' 

from diffusers import StableDiffusionInpaintPipeline

pipeline = StableDiffusionInpaintPipeline.from_pretrained(
    "../data/stable-diffusion-2-inpainting",
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
)

pipeline = pipeline.to("cuda")

init_image = PIL.Image.open('./input.jpg').convert("RGB")
mask_image = PIL.Image.open('./input_mask.jpg').convert("RGB")

width, height = init_image.size[0], init_image.size[1] # (427, 640)

prompt = ""
img = pipeline(prompt=prompt, image=init_image, mask_image=mask_image, height=height, width=width).images[0]

img.save('output.jpg')
```

### Logs

```shell
Traceback (most recent call last):
    img= pipeline(prompt=prompt, image=init_image, mask_image=mask_image, height=height, width=width).images[0]
  File "/home/tools/anaconda3/envs/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tools/anaconda3/envs/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 894, in __call__
    self.check_inputs(
  File "/home/tools/anaconda3/envs/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 560, in check_inputs
    raise ValueError(f"`height` and `width` have to be divisible by 8 but are {height} and {width}.")
ValueError: `height` and `width` have to be divisible by 8 but are 427 and 640.
```

### System Info

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-5.4.0-159-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.0
- Accelerate version: 0.23.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by DN6** [comment]
Hi @BeijingBlueSky The Stable Diffusion Pipeline does require image sizes that are divisible by 8 in order for the latent encoder to work. 

Can you resize your image and mask so that the height and width are divisible by 8? It seems like you would only have to slightly change the height dimension by 3 pixels for it to work.
