### ISSUE TITLE
Bug in the `_modify_text_encoder` method

### ISSUE THREAD

**Issue by eezywu** [huggingface/diffusers#5598]
### Describe the bug

The bottom code in diffusers/loaders.py would cause AttributeError: 'int' object has no attribute 'pop'， when patch_mlp is True and the rank is an int variable instead of a dict
```Python
  current_rank_fc1 = rank.pop(f"{name}.fc1.lora_linear_layer.up.weight")
  current_rank_fc2 = rank.pop(f"{name}.fc2.lora_linear_layer.up.weight")
```
maybe we should fix it as the following:
```Python
  if isinstance(rank, dict):
      current_rank_fc1 = rank.pop(f"{name}.fc1.lora_linear_layer.up.weight")
      current_rank_fc2 = rank.pop(f"{name}.fc2.lora_linear_layer.up.weight")
  else:
      current_rank_fc1 = current_rank_fc2 = rank
```

### Reproduction

call `_modify_text_encoder` with paramters of `patch_mlp=True` and `rank=[int]`

### System Info

diffusers version: 0.22.0.dev0
python version: 3.8.0

**Comment by DN6** [comment]
Hi @eezywu would you be able to provide a full code example to reproduce this issue?
