### ISSUE TITLE
How I can train instrct-pix2pix + lora?

### ISSUE THREAD

**Issue by mzeynali** [huggingface/diffusers#5599]
How I can train instrct-pix2pix + lora?

**Comment by DN6** [comment]
Hi @mzeynali 

You can reference the training scripts for instructpix2pix 
https://github.com/huggingface/diffusers/blob/2b78f1edb69efd3c01653cdc5c62ba7787570fb7/examples/instruct_pix2pix/

and the Dreambooth LoRA scripts. 
https://github.com/huggingface/diffusers/blob/2b78f1edb69efd3c01653cdc5c62ba7787570fb7/examples/dreambooth

You would have to combine some components from each of these script  and create a new script for training IP2P with LoRA.

**Comment by mzeynali** [comment]
@DN6 thanks so much, isn't there implemented codes for this?

**Comment by patrickvonplaten** [comment]
@mzeynali, please try to use the forum for such questions: https://discuss.huggingface.co/ - we try to keep GitHub clean for issues and bug requests ideally
