### ISSUE TITLE
Fine Tuning SDXL inpainting weights. 

### ISSUE THREAD

**Issue by rajdeep2804** [huggingface/diffusers#5601]
I was wondering how can train SDXL inpainting model also how to build custom dataset for such task and feed it to model. It'll be really helpful if someone could guide with the process.

**Comment by DN6** [comment]
Hi @rajdeep2804 You can checkout some of the discussions here on Inpainting models (although they are discussing SD 1.5, the principles still apply to SDXL)
https://huggingface.co/runwayml/stable-diffusion-inpainting/discussions/9
