### ISSUE TITLE
ImportError: cannot import name 'is_safetensors_available' from 'diffusers.utils'

### ISSUE THREAD

**Issue by peepeepeepoopoopoo** [huggingface/diffusers#5603]
### Describe the bug

Hello, I have the following error: ImportError: cannot import name 'is_safetensors_available' from 'diffusers.utils'

### Reproduction

Traceback (most recent call last):
  File "C:\Users\USUARIO\Desktop\wonder3d\test_mvdiffusion_seq.py", line 40, in <module>
    from mvdiffusion.models.unet_mv2d_condition import UNetMV2DConditionModel
  File "C:\Users\USUARIO\Desktop\wonder3d\mvdiffusion\models\unet_mv2d_condition.py", line 47, in <module>
    from diffusers.utils import (
ImportError: cannot import name 'is_safetensors_available' from 'diffusers.utils' (C:\Users\USUARIO\AppData\Local\Programs\Python\Python311\Lib\site-packages\diffusers\utils\__init__.py)

### System Info

windows 10 GTX 1660 6GB - RAM 16GB

**Comment by DN6** [comment]
@peepeepeepoopoopoo Could you please provide a code example to help us reproduce this issue.

**Comment by peepeepeepoopoopoo** [comment]
> @peepeepeepoopoopoo Could you please provide a code example to help us reproduce this issue.

**I don't know exactly what you're referring to, I'm a newbie, but I want to run Wonder3D (AI to go from 2D to 3D), this is all I get in CMD:**

Microsoft Windows [Version 10.0.19044.1706]
(c) Microsoft Corporation. All rights reserved.

C:\Users\USER\Desktop\wonder3d>@echo off
set PYTHON_PATH=C:\Users\USER\AppData\Local\Programs\Python\Python311\python.exe
set SCRIPT_PATH=C:\Users\USER\Desktop\wonder3d\test_mvdiffusion_seq.py

%PYTHON_PATH% %SCRIPT_PATH%
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\wonder3d\test_mvdiffusion_seq.py", line 40, in <module>
    from mvdiffusion.models.unet_mv2d_condition import UNetMV2DConditionModel
  File "C:\Users\USER\Desktop\wonder3d\mvdiffusion\models\unet_mv2d_condition.py", line 47, in <module>
    from diffusers.utils import (
ImportError: cannot import name 'is_safetensors_available' from 'diffusers.utils' (C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\diffusers\utils\__init__.py)

**Comment by Vv0905** [comment]
请问解决了吗
