### ISSUE TITLE
Add per image caption support for SDXL dreambooth.

### ISSUE THREAD

**Issue by aravindhv10** [huggingface/diffusers#5605]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Implement per image captions for SDXL dreambooth similar to Everydream2 (https://github.com/victorchall/EveryDream-trainer) which only works for SD-1.5.

I have tried to make a preliminary implementation here:
https://github.com/aravindhv10/diffusers/blob/main/examples/dreambooth/per_image_caption_sdxl_dreambooth.py
can this be merged with some improvements?

**Describe alternatives you've considered**
Checked 3rd party scripts for SDXL dreambooth which implement per image captions but was not satisfied.

**Additional context**
No

**Comment by aravindhv10** [comment]
For getting my per image caption implemented, I had started with the sdxl lora dreambooth script provided in the example, is it better to do it from the sdxl controlnet training script instead ?

**Comment by DN6** [comment]
Hi @aravindhv10 is the goal of this script to create a dataset that you can use to finetune SDXL?

**Comment by aravindhv10** [comment]
The main goal I had was to finetune SDXL on custom dataset, yes.

**Comment by aravindhv10** [comment]
Yes thanks for pointing out, the changes seem exciting!
