### ISSUE TITLE
Need a way to switch pipeline type when using custom pipelines

### ISSUE THREAD

**Issue by vladmandic** [huggingface/diffusers#5613]
With standard SD pipelines, you can switch from txt2img to img2img easily:

```py
        if new_pipe_type == DiffusersTaskType.TEXT_2_IMAGE:
            new_pipe = diffusers.AutoPipelineForText2Image.from_pipe(pipe)
        elif new_pipe_type == DiffusersTaskType.IMAGE_2_IMAGE:
            new_pipe = diffusers.AutoPipelineForImage2Image.from_pipe(pipe)
        elif new_pipe_type == DiffusersTaskType.INPAINTING:
            new_pipe = diffusers.AutoPipelineForInpainting.from_pipe(pipe)
```

but when using model whose pipeline is defined as custom_pipeline, there is no such option.
for example,
```py
pipe = DiffusionPipeline.from_pretrained("SimianLuo/LCM_Dreamshaper_v7")
```
will load a model using `LatentConsistencyModelPipeline` which is implemented in `latent_consistency_txt2img.py`

or i can specify custom_pipeline manually, for example:
```py
pipe = DiffusionPipeline.from_pretrained("SimianLuo/LCM_Dreamshaper_v7", custom_pipeline="latent_consistency_img2img")
```

but I don't see a way to switch a custom pipeline from **txt2img** to **img2img** for an already loaded model.
and that functionality exists for standard pipelines.

cc: @yiyixuxu @DN6 @patrickvonplaten @sayakpaul @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Ah yeah I see! We'll have LCM supported in the release tomorrow in main and will then also switch to that as the default way of loading. Does lcm img2img work reasonably well? Happy to quickly add it tomorrow to `diffusers` core as well

**Comment by vladmandic** [comment]
I'm testing using `diffusers==0.22.0.dev` and LCM loading for txt2img without specifying `custom_pipeline` works just fine.
but the rest is not there - i think mostly stuff in `pipelines/auto_pipeline.py` also needs entries for LCM so it knows how to switch.

does LCM img2img work ok? well, its not sdxl for sure. but it does work and opens totally new use-cases - its fast enough that on RTX4090 i can run it with webcam input in real-time with sufficient frames per second!

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/pull/5632
