### ISSUE TITLE
StableDiffusionInpaintPipeline does not work with LMSDiscreteScheduler

### ISSUE THREAD

**Issue by shirayu** [huggingface/diffusers#562]
### Describe the bug

`StableDiffusionInpaintPipeline` does not work with `LMSDiscreteScheduler`

### Reason
- This seems to be because of the absence of special operations for `LMSDiscreteScheduler` as performed in `StableDiffusionImg2ImgPipeline` 

https://github.com/huggingface/diffusers/blob/429dace10a356a776f935fc11e16d5b321b496f3/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L206-L212
 
https://github.com/huggingface/diffusers/blob/429dace10a356a776f935fc11e16d5b321b496f3/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py#L245

### Proposal:

I think it is better to unify pipelines  as proposed in #551, since most processes are the same.

### Logs

```shell
"/path/to/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 245, in __call__
    timesteps = torch.tensor([timesteps] * batch_size, dtype=torch.long, device=self.device)

TypeError: only integer tensors of a single element can be converted to an index
```

### System Info

- diffusers 429dace10a356a776f935fc11e16d5b321b496f3

**Comment by anton-l** [comment]
Support for K-LMS is coming in https://github.com/huggingface/diffusers/pull/587
