### ISSUE TITLE
sdxl controlNet not support encoder_hid_proj model

### ISSUE THREAD

**Issue by junqiangwu** [huggingface/diffusers#5621]
### Describe the bug

I was training sdxl+controlNet recently, but I changed sdxl model,when I only used a single text encode to extract prompt_embedding. In the UNet2DConditionModel implementation, feature mapping was performed by using encoder_hid_proj, but in controlNet, this function was not implemented, causing the training to fail.

### Reproduction

None

### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.20.0
- Platform: Linux-4.18.0-2.4.3.3.kwai.x86_64-x86_64-with-glibc2.27
- Python version: 3.9.16
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.28.1
- Accelerate version: 0.23.0
- xFormers version: 0.0.19+1c73b40.d20230425
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @yiyixuxu @DN6 @patrickvonplaten

**Comment by sayakpaul** [comment]
There's no reproduction code. Please provide one.
