### ISSUE TITLE
Enhanced safety checker functionality

### ISSUE THREAD

**Issue by suzukimain** [huggingface/diffusers#5623]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like.**
I request the ability to flexibly configure the safety checker.

**Describe alternatives you've considered.**
[I made a trial.](https://github.com/suzukimain/diffusers_mod.git) However, I am not sure if it is reflected well.thank you

**Additional context**

**Comment by yiyixuxu** [comment]
@suzukimain 

Thanks for your request - can you elaborate a little bit more on this feature?

YiYi

**Comment by suzukimain** [comment]
@yiyixuxu This function weakens the safety checker without removing it.

**Comment by Skquark** [comment]
I'm a fan of this feature request too.. I didn't mind safety checker in theory to prevent blatant NSFW, but the sensitivity is up way too high where the simplest innocent images of the most non-adult things have always been censored, which gets obnoxious. It's so sensitive that it hasn't been practical to keep on, and it's embarrassing the types of art it deems unsafe. Turn down the judgementalism, please.

**Comment by suzukimain** [comment]
@yiyixuxu I would be happy to hear back from you regarding this request.
