### ISSUE TITLE
A bug in diffusers/models/transformer_temporal.py

### ISSUE THREAD

**Issue by neilfei** [huggingface/diffusers#5633]
### Describe the bug

Line 174 of diffusers/models/transformer_temporal.py is currently `.reshape(batch_size, height, width, channel, num_frames)`, which is part of the following code block:

        # 3. Output
        hidden_states = self.proj_out(hidden_states)
        hidden_states = (
            hidden_states[None, None, :]
            .reshape(batch_size, height, width, channel, num_frames)
            .permute(0, 3, 4, 1, 2)
            .contiguous()
        )

However, maybe this line should be `.reshape(batch_size, height, width, num_frames, channel)`

### Reproduction

Line 174 of diffusers/models/transformer_temporal.py should be `.reshape(batch_size, height, width, num_frames, channel)`

### System Info

- `diffusers` version: 0.22.0.dev0                                                                                                                                                                                       [2/1823]
- Platform: Linux-5.4.0-148-generic-x86_64-with-glibc2.31                                                       
- Python version: 3.10.13                                                                                       
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.1
- Accelerate version: 0.24.0 
- xFormers version: 0.0.22
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Yes

### Who can help?

@DN6 @yiyixuxu @sayakpaul @DN6 @patrickvonplaten

**Comment by sayakpaul** [comment]
Could you elaborate why should it be like that?

Cc: @patrickvonplaten

**Comment by neilfei** [comment]
> Could you elaborate why should it be like that?
> 
> Cc: @patrickvonplaten

The complete `forward` function of the `TransformerTemporalModel` in `diffusers/models/transformer_temporal.py` is currently as follows:

    def forward(
        self,
        hidden_states,
        encoder_hidden_states=None,
        timestep=None,
        class_labels=None,
        num_frames=1,
        cross_attention_kwargs=None,
        return_dict: bool = True,
    ):
        # 1. Input
        batch_frames, channel, height, width = hidden_states.shape
        batch_size = batch_frames // num_frames

        residual = hidden_states

        hidden_states = hidden_states[None, :].reshape(batch_size, num_frames, channel, height, width)
        hidden_states = hidden_states.permute(0, 2, 1, 3, 4)

        hidden_states = self.norm(hidden_states)
        hidden_states = hidden_states.permute(0, 3, 4, 2, 1).reshape(batch_size * height * width, num_frames, channel)

        hidden_states = self.proj_in(hidden_states)

        # 2. Blocks
        for block in self.transformer_blocks:
            hidden_states = block(
                hidden_states,
                encoder_hidden_states=encoder_hidden_states,
                timestep=timestep,
                cross_attention_kwargs=cross_attention_kwargs,
                class_labels=class_labels,
            )

        # 3. Output
        hidden_states = self.proj_out(hidden_states)
        hidden_states = (
            hidden_states[None, None, :]
            .reshape(batch_size, height, width, channel, num_frames)
            .permute(0, 3, 4, 1, 2)
            .contiguous()
        )
        hidden_states = hidden_states.reshape(batch_frames, channel, height, width)

        output = hidden_states + residual

        if not return_dict:
            return (output,)

        return TransformerTemporalModelOutput(sample=output)

We can see that the input `hidden_states` has the shape of `[batch_frames, channel, height, width]`, where `batch_frames` equals `batch_size * num_frames`. Then it is reshaped to `[batch_size * height * width, num_frames, channel]` before being inputted into `self.transformer_blocks`. The `hidden_states` coming out of `self.transformer_blocks` still has the shape of `[batch_size * height * width, num_frames, channel]`.

The line `.reshape(batch_size, height, width, channel, num_frames)` in the `# 3. Output` part obviously makes no sense, which should be `.reshape(batch_size, height, width, num_frames, channel)` instead. Moreover, considering the following `.permute(0, 3, 4, 1, 2)` and `hidden_states = hidden_states.reshape(batch_frames, channel, height, width)` operations, it is clear that `hidden_states` should be reshaped to `[batch_size, height, width, num_frames, channel]` rather than `[batch_size, height, width, channel, num_frames]`.

**Comment by DN6** [comment]
@neilfei I think this has been fixed already
https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/transformer_temporal.py

**Comment by neilfei** [comment]
@DN6 Ah I see! I'll close this issue.
