### ISSUE TITLE
How to use the ip adapter controlnet?

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#5643]
Hi, I can't use this specific controlnet because it's from here: https://huggingface.co/lllyasviel/sd_control_collection/tree/main

and the format doesn't allow from_pretrained. When I use from_single_file, I get:
```

stable_diffusion/convert_from_ckpt.py", line 422, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'
```
I used this to get the error:
`ControlNetModel.from_single_file("./ip-adapter_sd15_plus.pth", torch_dtype=torch.float32,local_files_only=True).to('cuda')`

a similar error was raised and the response was: "just don't use from_single_file" https://github.com/huggingface/diffusers/issues/5577

**Comment by yiyixuxu** [comment]
cc @sayakpaul 

I don't think we support ip adapter yet?
https://github.com/huggingface/diffusers/pull/4944#issuecomment-1792123528

**Comment by alexblattner** [comment]
@yiyixuxu that's a problem....

**Comment by alexblattner** [comment]
great way to start: https://github.com/tencent-ailab/IP-Adapter
