### ISSUE TITLE
DPM/UniPC schedulers (possibly more) seem to have massive stability issues on model KohakuXL vs ComfyUI

### ISSUE THREAD

**Issue by Xynonners** [huggingface/diffusers#5646]
### Describe the bug

The model KohakuXL in diffusers, seems to run into a massive noise/stability issue that doesn't seem to be present within ComfyUI/AUTO1111, on UniPC/DPM schedulers (possibly more) that doesn't go away with high step counts.
At 15S:
![test](https://github.com/huggingface/diffusers/assets/63993670/699e5a62-ec9c-4fd7-8cee-e96d6b4081d7)
At 30S:
![test](https://github.com/huggingface/diffusers/assets/63993670/a4817c8e-5cfa-48c3-9069-1a90a2960ae2)
Euler A 30S:
![test](https://github.com/huggingface/diffusers/assets/63993670/7dcbc39a-0c59-4983-9ae2-81b04e6136a9)

### Reproduction

```python
import torch
from accelerate.utils import ProjectConfiguration
from accelerate import Accelerator
from diffusers import StableDiffusionXLPipeline, DPMSolverMultistepScheduler, EulerAncestralDiscreteScheduler
accelerator_config = ProjectConfiguration(
    project_dir="test",
    automatic_checkpoint_naming=True,
    total_limit=10,
)
accelerator = Accelerator(
    log_with="aim",
    mixed_precision="bf16",
    project_config=accelerator_config,
    gradient_accumulation_steps=16,
)
pipeline = StableDiffusionXLPipeline.from_single_file("models/kohakuXLBeta_beta71.safetensors").to(accelerator.device)
pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config)
generator = torch.Generator(device=accelerator.device).manual_seed(42)
ims = pipeline(width=1024, height=1024, guidance_scale=14.0, prompt="realistic car 3 d render sci - fi car and sci - fi robotic factory structure in the coronation of napoleon painting and digital billboard with point cloud in the middle, unreal engine 5, keyshot, octane, artstation trending, ultra high detail, ultra realistic, cinematic, 8 k, 1 6 k, in style of zaha hadid, in style of nanospace,", num_inference_steps=15, generator=generator)
for img in ims.images:
    img.save("test.png")
```

### Logs

```shell
Not Applicable
```

### System Info

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-6.5.6-273-tkg-tt-x86_64-with-glibc2.38
- Python version: 3.11.5
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.1
- Accelerate version: 0.24.0
- xFormers version: not installed
- Using GPU in script?: RTX6000
- Using distributed or parallel set-up in script?: yes in accelerate config, no in this script

### Who can help?

@yiyixuxu @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Can you try whether the fix to DPM provided here: https://github.com/huggingface/diffusers/pull/5541 could help?

**Comment by nhnt11** [comment]
In my experience, #5541 helps but not completely. I just filed https://github.com/huggingface/diffusers/issues/5689 to document another issue we found.

**Comment by Xynonners** [comment]
@patrickvonplaten using euler_at_final with either default, use_karras_sigmas, or use_lu_lambdas does help the issue slightly, but it is still very apparent. 

use_karras_sigmas tends to be less noisy than default, while use_lu_lambdas tends to have larger but less splotches.

**Comment by yiyixuxu** [comment]
hi @Xynonners 

sorry I can't reproduce this. I tried this script
```python
import torch
from diffusers import StableDiffusionXLPipeline, DPMSolverMultistepScheduler, EulerAncestralDiscreteScheduler

pipeline = StableDiffusionXLPipeline.from_pretrained("KBlueLeaf/kohaku-xl-beta7.1", torch_dtype=torch.float16)
pipeline.enable_model_cpu_offload()
generator = torch.Generator(device="cuda").manual_seed(42)
ims = pipeline(prompt="realistic car 3 d render sci - fi car and sci - fi robotic factory structure in the coronation of napoleon painting and digital billboard with point cloud in the middle, unreal engine 5, keyshot, octane, artstation trending, ultra high detail, ultra realistic, cinematic, 8 k, 1 6 k, in style of zaha hadid, in style of nanospace,", num_inference_steps=30, generator=generator)
ims.images[0].save("euler.png")

pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config)
generator = torch.Generator(device="cuda").manual_seed(42)
ims = pipeline(prompt="realistic car 3 d render sci - fi car and sci - fi robotic factory structure in the coronation of napoleon painting and digital billboard with point cloud in the middle, unreal engine 5, keyshot, octane, artstation trending, ultra high detail, ultra realistic, cinematic, 8 k, 1 6 k, in style of zaha hadid, in style of nanospace,", num_inference_steps=30, use_lu_lambdas =True, euler_at_final = True, generator=generator)

ims.images[0].save("dpm.png")
```
euler
![yiyi_test_5_out_euler](https://github.com/huggingface/diffusers/assets/12631849/4334b346-7723-4716-bc8b-8425a6bf1d55)

dpm
![yiyi_test_5_out_dpm](https://github.com/huggingface/diffusers/assets/12631849/6e36ee51-fa99-4f98-b45a-b121d0317a8b)

**Comment by Xynonners** [comment]
@yiyixuxu I narrowed it down to the guidance_scale parameter, it seems like DPM is unstable at high guidance scale.
```python
import torch
from diffusers import StableDiffusionXLPipeline, DPMSolverMultistepScheduler, EulerAncestralDiscreteScheduler

pipeline = StableDiffusionXLPipeline.from_single_file("UpDraft/models/kohakuXLBeta_beta71.safetensors", torch_dtype=torch.float16)
pipeline.enable_model_cpu_offload()
generator = torch.Generator(device="cuda").manual_seed(42)
ims = pipeline(guidance_scale=14.0, prompt="realistic car 3 d render sci - fi car and sci - fi robotic factory structure in the coronation of napoleon painting and digital billboard with point cloud in the middle, unreal engine 5, keyshot, octane, artstation trending, ultra high detail, ultra realistic, cinematic, 8 k, 1 6 k, in style of zaha hadid, in style of nanospace,", num_inference_steps=30, generator=generator)
ims.images[0].save("euler.png")

pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config)
generator = torch.Generator(device="cuda").manual_seed(42)
ims = pipeline(guidance_scale=14.0, prompt="realistic car 3 d render sci - fi car and sci - fi robotic factory structure in the coronation of napoleon painting and digital billboard with point cloud in the middle, unreal engine 5, keyshot, octane, artstation trending, ultra high detail, ultra realistic, cinematic, 8 k, 1 6 k, in style of zaha hadid, in style of nanospace,", num_inference_steps=30, use_lu_lambdas =True, euler_at_final = True, generator=generator)
ims.images[0].save("dpm.png")
```

Also, the introduction of accelerate also, while making the model much slower, also seems to serve to destabilize it a larger amount.
dpm:
![dpm](https://github.com/huggingface/diffusers/assets/63993670/41feac60-5f4f-4342-a31a-0d2a3762e9fe)
dpm + accelerate:
![test](https://github.com/huggingface/diffusers/assets/63993670/bb44a2df-c49a-41e1-9df2-1d8431e31947)

**Comment by Xynonners** [comment]
lowered to 15
![dpm](https://github.com/huggingface/diffusers/assets/63993670/1dad1474-602e-499e-8972-89f93147c32e)

**Comment by patrickvonplaten** [comment]
@yiyixuxu can you look into this to see if it has been fixed?

**Comment by patrickvonplaten** [comment]
Gentle re-ping

**Comment by yiyixuxu** [comment]
cc @Beinsezii here since you have been testing our schedulers
is this still an issue?

**Comment by Beinsezii** [comment]
`DPMSolverMultistep` has been my default ever since I added ZSNR and I've never once seen images like that across a fair variety of XL models. Closest I can think of is running a funky noise schedule directly on bf16 but that should be fixed forever since I added an upcast in `step()` with #7097

@Xynonners should probably try again on the latest pytorch/diffusers.

**Comment by yiyixuxu** [comment]
closing this for now!
feel free to re-open if you continue to see issue
