### ISSUE TITLE
Add LORA Loader to community pipelines

### ISSUE THREAD

**Issue by frozencure** [huggingface/diffusers#5656]
**Is your feature request related to a problem? Please describe.**

**Problem**
When using any community pipeline none of the `LoraLoaderMixin` methods are available and I have to either implement the methods myself or find a different workaround.

When the diffusion pipeline is initialized in the following way:
```
DiffusionPipeline.from_pretrained(
          "runwayml/stable-diffusion-inpainting",
          custom_pipeline='stable_diffusion_controlnet_inpaint',
          ...
      )
```
**Proposed Solution**
Currently, all community pipelines extend the `DiffusionPipeline` (`class CommunityPipeline(DiffusionPipeline)`).  The solution I would like is to somehow be able to initialize a custom community pipeline that inherits the `LoraLoaderMixin` functionality.

**Comment by patrickvonplaten** [comment]
Hey @frozencure, 

 The community pipelines are maintained by the respective authors, can you maybe say which community pipeline exactly you'd like to see enhanced and ping the author here?
