### ISSUE TITLE
name 'PreTrainedTokenizer' is not defined in diffusers 0.22.1

### ISSUE THREAD

**Issue by WiNE-iNEFF** [huggingface/diffusers#5661]
### Describe the bug

when i try to loading pretrained model using DDPMPipeline or DiffusionPipeline, i take error `Failed to import diffusers.models.unet_2d because of the following error (look up to see its traceback):
name 'PreTrainedTokenizer' is not defined`

### Reproduction

`
from diffusers import DiffusionPipeline
image_pipe = DiffusionPipeline.from_pretrained(huggan/fastgan-few-shot-painting).to(device)
`

### Logs

```shell
NameError                                 Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py in _get_module(self, module_name)
    683         try:
--> 684             return importlib.import_module("." + module_name, self.__name__)
    685         except Exception as e:

20 frames
NameError: name 'PreTrainedTokenizer' is not defined

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py in _get_module(self, module_name)
    684             return importlib.import_module("." + module_name, self.__name__)
    685         except Exception as e:
--> 686             raise RuntimeError(
    687                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
    688                 f" traceback):\n{e}"

RuntimeError: Failed to import diffusers.models.unet_2d because of the following error (look up to see its traceback):
name 'PreTrainedTokenizer' is not defined
```

### System Info

`- `diffusers` version: 0.22.1
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.18.0
- Transformers version: not installed
- Accelerate version: 0.24.1
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>`

### Who can help?

@DN6 @yiyixuxu @sayakpaul @patrickvonplaten

**Comment by kremHabashy** [comment]
Similar error when importing anything from  diffusers.models:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
    709         try:
--> 710             return importlib.import_module("." + module_name, self.__name__)
    711         except Exception as e:

13 frames
NameError: name 'PreTrainedModel' is not defined

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
    710             return importlib.import_module("." + module_name, self.__name__)
    711         except Exception as e:
--> 712             raise RuntimeError(
    713                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
    714                 f" traceback):\n{e}"

RuntimeError: Failed to import diffusers.models.autoencoder_kl because of the following error (look up to see its traceback):
name 'PreTrainedModel' is not defined
```

**Comment by yiyixuxu** [comment]
ohh sorry I'm not able to reproduce this error 

cc @sayakpaul maybe

**Comment by giacomov** [comment]
Same here. Can't import any model on the latest release. Gonna try reverting back to older releases, but something like this should have probably been caught  by the tests :-)

**Comment by giacomov** [comment]
FYI, the problem is NOT present in version 0.21.4, so reverting to that fixes the problem for now.

**Comment by sayakpaul** [comment]
Installing transformers should fix the issue as of now. But I will investigate more deeply.

**Comment by sayakpaul** [comment]
This is indeed quite weird. We have a dedicated workflow just for checking if the pipelines can be imported correctly: https://github.com/huggingface/diffusers/blob/main/.github/workflows/pr_dependency_test.yml

It actually errors out too, when using the latest diffusers release:
https://colab.research.google.com/gist/sayakpaul/8418c8d7a17281ab393cd76e9632bdc2/scratchpad.ipynb

But ... on my Mac, locally, it doesn't error out. I, of course, tested it in a fresh environment with `diffusers` installed like so: `pip install -e .` from the `main` branch. It doesn't error out either on `v0.22.0` branch 🤯

**Comment by wmthor** [comment]
Installing `transformers` didn't work for me. But it's quite strange, installing 0.21.4 fixes it, even when changing back to the latest version 0.22.1 after that.

Running on Google Collab environment.

**Comment by sayakpaul** [comment]
Does installing from https://github.com/huggingface/diffusers/pull/5668 branch resolve it? If not, could you provide a reproducible Colab?
