### ISSUE TITLE
[Hub + Examples] Standardize model cards in the training scripts

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#5667]
The [model card](https://github.com/huggingface/diffusers/blob/64603389da01082055a901f2883c4810d1144edb/src/diffusers/utils/hub_utils.py#L125) helper in diffusers does not set either a `finetuned_from` or `base_model` metadata. 

If we follow the template and start adding the `finetuned_from` or `base_model` tag in the metadata portion of the model cards in our training scripts, that will lead to a solid UI improvement on the Hub. 

@Wauplin, actually, I need a bit of advice here. I did try to use the template before and found to be a bit non-trivial to use compared to just writing one myself. Could you help with some pointers on how to do this cleanly? You can take [this model card](https://github.com/huggingface/diffusers/blob/64603389da01082055a901f2883c4810d1144edb/examples/dreambooth/train_dreambooth_lora_sdxl.py#L66) from the SDXL DreamBooth LoRA training script as an example.

**Comment by sayakpaul** [comment]
Thank you! @pcuenca WDYT?

**Comment by Wauplin** [comment]
Also, personal opinion, I would keep a custom model card template as you already did. But also check [the default temaplte](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/templates/modelcard_template.md) if some fields could be populated by `diffusers` (developers, get_started_code, training data,... ?).

**Comment by pcuenca** [comment]
This looks very nice, thanks @Wauplin! I think it's a good idea to use a template and populate it from the training scripts. I feel we could make it work with just one template for all, don't you think?

**Comment by sayakpaul** [comment]
Certainly. Let me work on something quick and open this up for discussions. Might need some help. Will see.

**Comment by sayakpaul** [comment]
Picking it up again. @linoytsaban since you worked on a beautiful model card in #5508, I was wondering if you would like to give this a try. We don't have to do start with all at once, we can just with one and take it from there.

**Comment by julien-c** [comment]
i think not stale

**Comment by linoytsaban** [comment]
@sayakpaul oops I missed the tag! I can definitely give it a try

**Comment by Wauplin** [comment]
This issue will be partly achieved (or at least greatly simplified) by @sayakpaul's ongoing work in https://github.com/huggingface/diffusers/pull/6678.

**Comment by sayakpaul** [comment]
More tracking: https://github.com/huggingface/diffusers/issues/6891.
