### ISSUE TITLE
Save training `dtype` as part of the configuration

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#567]
It'd be interesting to know the type that was used to train. However, as pointed out by @patrickvonplaten and @patil-suraj:

* It needs to be saved as a string; `jnp.bfloat16` etc. cannot be serialized.
* We need to decide the naming to make it clear what it means.

Context: https://github.com/huggingface/diffusers/pull/565#issuecomment-1251024861

**Comment by patrickvonplaten** [comment]
Thanks for opening this issue - let's keep it in mind when improving JAX over time
