### ISSUE TITLE
why does it take 30 seconds to load lora and generate images using PEFT?

### ISSUE THREAD

**Issue by chinatian** [huggingface/diffusers#5676]
I upgraded lora's loading method to PEFT. It can load multiple loras normally, but compared to the previous diffusers version, it only takes less than 10 seconds to load a single lora, while the PEFT method takes 30s+. The graphics card I use is 3090.

my code：

adapter_name = weight_name.replace('.safetensors','')
pipeline.load_lora_weights(lora_dir, weight_name=weight_name,adapter_name=adapter_name)
pipeline.set_adapters(adapter_name_list, adapter_weights=mult_list)

....

Last uninstalled code：

pipe.disable_lora()
pipe.unload_lora_weights()

@sayakpaul
@younesbelkada
@pacman100

**Comment by sayakpaul** [comment]
Can you provide a complete Colab Notebook demonstrating the slowdown?

**Comment by chinatian** [comment]
Sorry, I cannot provide Colab Notebook, but testing with jupyter notebook found that a lot of time is spent on:
pipe.unload_lora_weights()

Now, the loading process of lora is as follows, which can be controlled within 10 seconds on 3090.

pipeline.enable_lora()

adapter_name = weight_name.replace('.safetensors','')
pipeline.load_lora_weights(lora_dir, weight_name=weight_name,adapter_name=adapter_name)
pipeline.set_adapters(adapter_name_list, adapter_weights=mult_list)

...


pipeline.enable_lora()


> Can you provide a complete Colab Notebook demonstrating the slowdown?

**Comment by sayakpaul** [comment]
You don't have to do `enable_lora()`. 

We haven't noticed anything like this and cannot reproduce it. So, without something more concrete in terms of reproducibility, we cannot really proceed here.

**Comment by chinatian** [comment]
> You don't have to do .`enable_lora()`
> 
> We haven't noticed anything like this and cannot reproduce it. So, without something more concrete in terms of reproducibility, we cannot really proceed here.

Sorry, the process used ended up calling:
pipeline.disable_lora()

Thank you so much
