### ISSUE TITLE
"scaled_dot_product_attention" using in "models/attention_processor.py" may lead to error when using autograd to calculate higher order derivatives

### ISSUE THREAD

**Issue by zhongzero** [huggingface/diffusers#5678]
### Describe the bug

In `models/attention_processor.py` we will use `AttnProcessor2_0()` instead of `AttnProcessor()` when torch 2.x is used which uses `torch.nn.functional.scaled_dot_product_attention` for native Flash/memory_efficient_attention , but this may lead to some error saying `derivative for aten::_scaled_dot_product_efficient_attention_backward is not implemented` . The error occurs when we try to using autugrad to calculate higher order derivatives.
More specifically, when we use a pretrained `UNet2DConditionModel` , calling it `unet`, and try to using `torch.autograd.grad()` to calculate higher order derivatives of the input of `unet`, error occurs.
But it will be fine if we go back to use `AttnProcessor()` in `models.attention_processor.py.Attention.__init__()`.
I think it will be better adding a new args for it or currently going back to use `AttnProcessor()` until pytorch offering better support.

### Reproduction

```python
import torch
import torch.nn.functional as F
from diffusers import UNet2DConditionModel

unet = UNet2DConditionModel.from_pretrained("CompVis/stable-diffusion-v1-4", subfolder="unet", revision=None).to("cuda")
unet.train()

noisy_latents = torch.rand(1, 4, 64, 64).type(torch.FloatTensor).to("cuda")
timesteps = torch.rand(1).type(torch.LongTensor).to("cuda")
encoder_hidden_states = torch.rand(1, 77, 768).type(torch.FloatTensor).to("cuda")
encoder_hidden_states.requires_grad_(True)
target = torch.rand(1, 4, 64, 64).type(torch.FloatTensor).to("cuda")
model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
loss = F.mse_loss(model_pred.float(), target.float(), reduction="mean")

grads = torch.autograd.grad(loss, encoder_hidden_states, retain_graph=True, create_graph=True, allow_unused=True)

Sum = torch.tensor(0, dtype = torch.float32, requires_grad = True).to("cuda")
for i in range(0,len(grads)):
    Sum = Sum + grads[i].sum()

grads_outloop=torch.autograd.grad(Sum, encoder_hidden_states, allow_unused=True)
```

### Logs

```shell
Traceback (most recent call last):
  File "ErrorReproduction.py", line 22, in <module>
    grads_outloop=torch.autograd.grad(Sum, encoder_hidden_states, allow_unused=True)
  File "/home/myusername/miniconda3/envs/myenvname/lib/python3.8/site-packages/torch/autograd/__init__.py", line 394, in grad
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: derivative for aten::_scaled_dot_product_efficient_attention_backward is not implemented
```

### System Info

- `diffusers` version: 0.22.1
- Platform: Linux-5.4.0-99-generic-x86_64-with-glibc2.17
- Python version: 3.8.18
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.35.0
- Accelerate version: 0.24.1
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@DN6 @sayakpaul

**Comment by sayakpaul** [comment]
Thanks for reporting the issue. This issue is however not present when you try to train something like SDXL with DreamBooth and LoRA (https://github.com/huggingface/diffusers/commits/main/examples/dreambooth/train_dreambooth_lora_sdxl.py). 

So, it does sound like a specific use case. 

Maybe for these, using xformers-based attention processor is safer?

**Comment by patrickvonplaten** [comment]
Hmm that indeed sounds quite specific as an issue. @zhongzero could you maybe try to use the default, native attention class instead:

```py
unet = UNet2DConditionModel.from_pretrained("CompVis/stable-diffusion-v1-4", subfolder="unet", revision=None).to("cuda")
unet.set_default_attn_processor()
unet.train()
```
