### ISSUE TITLE
About the inpaint mode: fill, original, latent noise, latent nothing

### ISSUE THREAD

**Issue by atlantistin** [huggingface/diffusers#5691]
There is different mode to use inpainting in WebUI, and it can get the different result.
Could this be implemented in diffusers ???

**Comment by yiyixuxu** [comment]
I think what we currently have is similar to "original". we are still exploring these options! and would definitely be interested in add if they are helpful 

would you be interested in sharing more about your experience using these different inpaint mode? e.g. which mode you use most often and why, etc

thanks in advance!

**Comment by atlantistin** [comment]
Thank you very much!
I found that the parameter of strength can regulate it.
For example, if I need to create a new skin, I'll make it lower to make sure it's similar to the original skin.

**Comment by ka1tte** [comment]
Can the mentioned function be used now?

**Comment by ka1tte** [comment]
> Thank you very much! I found that the parameter of strength can regulate it. For example, if I need to create a new skin, I'll make it lower to make sure it's similar to the original skin.
In fact, this is a different function from inpaint mode. We still need to control the initialization method of the masked area.

**Comment by dain5832** [comment]
I guess #6072 mentions about masked_content option.
