### ISSUE TITLE
pipeline_pixart_alpha negative prompt normalization

### ISSUE THREAD

**Issue by Bigfield77** [huggingface/diffusers#5692]
Hello, 
    first great work on implementing pixart-alpha so fast, I am really happy to be able to try it!

**Is your feature request related to a problem? Please describe.**
    I have noticed that, when using negative prompt, if the negative prompt is much shorter than the prompt it seems to have too much effect.

    Here's an example with the following prompt: "a fall day in an abandoned  city on an ageless planet, the plants and vegetation are decidedly alien but in a subtle way. the sky is hues of crimsons  and turquoise, a space ring is visible in the sky faintly reflecting the sun's glow"

with no negative prompt:
![image](https://github.com/huggingface/diffusers/assets/108305548/10d38eb6-1f09-42b3-a40d-42fa1f409e9a)
**Describe the solution you'd like**

With negative prompt "painting":
![image](https://github.com/huggingface/diffusers/assets/108305548/6eedd172-2e4a-4628-b63f-e6edd2baa587)

**Describe alternatives you've considered**

    As a naive solution I tried 'normalising' the negative embedding according to the relation of the length of the negative prompt to the normal prompt like:
negative_prompt_embeds = negative_prompt_embeds.mul(0.15*(len(negative_prompt)/len(textPrompt)))

    and it seems to give better results:
![image](https://github.com/huggingface/diffusers/assets/108305548/1071e03c-3014-400a-9ce1-25746ebd4270)

   I tried with a longer negative prompt: "painting,bad composition,burned toast, photoshop, 3d, blender, sketch, cartoon, drawing,anime, bad framing, unrealistic"

  and it seems to work ok too
![image](https://github.com/huggingface/diffusers/assets/108305548/7024aa44-19b7-465e-866c-72d1df4179af)

EDIT
   For fun I tried making the prompt shorter than the negative prompt and it breaks in an 'interesting' way lol
   same long negative prompt as before and the prompt is ''a fall day in an abandoned  city'
   ![image](https://github.com/huggingface/diffusers/assets/108305548/d0f557b3-349d-4727-8cfe-d54e47ece935)

   

Thanks for your time!
François

**Comment by yiyixuxu** [comment]
interesting! cc @sayakpaul 

it this an issue unique with pixart-alpha? then maybe we can add something in the doc

**Comment by Bigfield77** [comment]
It seems to have been fixed in the latest version :)

    It must have been related to the change to prompt masking

    Closing this issue.

Thanks!
