### ISSUE TITLE
DPMSolverSinglestepScheduler lacks self.sigmas during initialization

### ISSUE THREAD

**Issue by LWprogramming** [huggingface/diffusers#5710]
### Describe the bug

`DPMSolverSinglestepScheduler` not initialized with sigmas, but required for add_noise. only set after setting timesteps.

### Reproduction

```
import torch
from diffusers import DPMSolverSinglestepScheduler

foo = DPMSolverSinglestepScheduler()
placeholder_latents = torch.randn(1, 64, 64)
placeholder_noise = torch.randn(1, 64, 64)
print(hasattr(foo, "sigmas")) # False
foo.add_noise(placeholder_latents, placeholder_noise, 10) # crash
```

### System Info

- `diffusers` version: 0.22.2
- Platform: Linux-5.19.17-coreweave-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.1.0a0+fe05266 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.30.0.dev0
- Accelerate version: 0.19.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

### Who can help?

@patrickvonplaten

**Comment by LWprogramming** [comment]
did this end up getting changed?

**Comment by yiyixuxu** [comment]
hi @LWprogramming 
we did fix it here https://github.com/huggingface/diffusers/pull/6006
sorry I forgot to link it to this issue
