### ISSUE TITLE
pip install --upgrade diffusers[torch] fails with Python 3.12 on Windows 11

### ISSUE THREAD

**Issue by canxerian** [huggingface/diffusers#5712]
### Describe the bug

`pip install --upgrade diffusers[torch]`  with Python 3.12 results in a failed installation, with one the (many) errors being: 

`ERROR: Could not find a version that satisfies the requirement torch (from versions: none)`

Workaround: 
Use Python 3.11.

Note:
Writing this to hopefully save others from a day of head scratching.

### Reproduction

Run `pip install --upgrade diffusers[torch]` using Python 3.12

### System Info

Python 3.12.x

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul @painebenjamin, I would like to try this issue. Thanks

**Comment by Bhavay-2001** [comment]
Hi @yiyixuxu since i am new to open source, could you please suggest how can I begin solving. Thanks

**Comment by canxerian** [comment]
Probably could just put a small note in the Installation section of the README.

Something along the lines of "use Python 3.11 and below on Windows"

**Comment by Bhavay-2001** [comment]
Hi @canxerian, need to check with the maintainers if there is a possible solution to this or should we just add the note below.

**Comment by patrickvonplaten** [comment]
We should really start to test `diffusers` more on Windows

**Comment by Bhavay-2001** [comment]
Hi @patrickvonplaten, please let me know how can I contribute to the issue. Thanks

**Comment by asomoza** [comment]
This is not a problem with diffusers, pytorch it's not supported for python 3.12 on windows:

https://pytorch.org/get-started/locally/

`Currently, PyTorch on Windows only supports Python 3.8-3.11; Python 2.x is not supported.`

**Comment by Bhavay-2001** [comment]
Hi @patrickvonplaten, as mentioned by @asomoza should we mention in the documentation file?
Thanks

**Comment by patrickvonplaten** [comment]
> Hi @patrickvonplaten, as mentioned by @asomoza should we mention in the documentation file? Thanks

@yiyixuxu @DN6 does anybody of you have time to double check how well `diffusers` is supported on Windows?

**Comment by Bhavay-2001** [comment]
Hi @canxerian, can we just add a small note on the installation page regarding this?
