### ISSUE TITLE
Check for `pytorch_lora_weights.safetensors` or `pytorch_lora_weights.bin` first before checking for multiple files

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#5719]
### Describe the bug

If a repo contains both `pytorch_lora_weights.safetensors` and some other safetensors file, loading it with  
```py
lcm_lora_id = "lcm-sd/lcm-sdxl-base-1.0-lora"
pipe.load_lora_weights(lcm_lora_id, adapter_name="lora", use_auth_token=True)
```
errors out, for example, a repo with:
<img width="311" alt="image" src="https://github.com/huggingface/diffusers/assets/788417/79d746b7-3c7e-4d55-a76d-37366545d8a1">

will yield: 
```
ValueError: Provided path contains more than one weights file in the .safetensors format. Either specify `weight_name` in `load_lora_weights` or make sure there's only one  `.safetensors` or `.bin` file in  lcm-sd/lcm-sdxl-base-1.0-lora.
```

However, I believe that if a repo has a canonical weight in the diffusers format  `pytorch_lora_weights.safetensors`, it should load that independently/before checking if there are multiple 

### Reproduction

```py
from diffusers import DiffusionPipeline, LCMScheduler
import torch

model_id = "stabilityai/stable-diffusion-xl-base-1.0"
lcm_lora_id = "lcm-sd/lcm-sdxl-base-1.0-lora"

pipe = DiffusionPipeline.from_pretrained(model_id, variant="fp16")
pipe.scheduler = LCMScheduler.from_config(pipe.scheduler.config)

pipe.load_lora_weights(lcm_lora_id, adapter_name="lora", use_auth_token=True)
```

### System Info

`diffusers==0.22.3`
`peft==0.6.0`

**Comment by patrickvonplaten** [comment]
Fixed on "main"
