### ISSUE TITLE
convert_original_stable_diffusion_to_diffusers.py is failed with SDXL model

### ISSUE THREAD

**Issue by Jiancong** [huggingface/diffusers#5737]
### Describe the bug

I tried with converting a safetensor into diffusers readable. Met following issues. Please help to check it.

### Reproduction

python3 convert_original_stable_diffusion_to_diffusers.py --checkpoint_path sdxlFixedvaeFp16Remove_baseFxiedVaeV2Fp16.safetensors --dump_path BaseModel/ --from_safetensors

You can download sdxlFixedvaeFp16Remove_baseFxiedVaeV2Fp16.safetensors from https://civitai.com/models/117188/sdxlfixedvaefp16remove-watermark

### Logs

```shell
(python310) root@autodl-container-c6d211b23c-81a60d70:~/autodl-fs/SD# python3 convert_original_stable_diffusion_to_diffusers.py --checkpoint_path sdxlFixedvaeFp16Remove_baseFxiedVaeV2Fp16.safetensors --dump_path BaseModel/ --from_safetensors
Traceback (most recent call last):
  File "/root/autodl-fs/SD/convert_original_stable_diffusion_to_diffusers.py", line 154, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/root/miniconda3/envs/python310/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1591, in download_from_original_stable_diffusion_ckpt
    pipe = pipeline_class(
TypeError: StableDiffusionPipeline.__init__() got an unexpected keyword argument 'text_encoder_2'
```

### System Info

(python310) root@autodl-container-c6d211b23c-81a60d70:~/autodl-fs/SD# diffusers-cli env

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.20.0
- Platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: 0.0.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@yiyixuxu @sayakpaul @DN6 @patrickvonplaten

**Comment by asomoza** [comment]
I convert them like this:

```
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_single_file("~/Downloads/sdxlFixedvaeFp16Remove_baseFxiedVaeV2Fp16.safetensors")
pipe.save_pretrained("/your/diffusers/dump_folder")
```

I tested it with that model and it works without a problem.

Reply copied from: https://github.com/huggingface/diffusers/issues/5061#issuecomment-1727914545

**Comment by Jiancong** [comment]
> I convert them like this:
> 
> ```
> from diffusers import StableDiffusionXLPipeline
> 
> pipe = StableDiffusionXLPipeline.from_single_file("~/Downloads/sdxlFixedvaeFp16Remove_baseFxiedVaeV2Fp16.safetensors")
> pipe.save_pretrained("/your/diffusers/dump_folder")
> ```
> 
> I tested it with that model and it works without a problem.
> 
> Reply copied from: [#5061 (comment)](https://github.com/huggingface/diffusers/issues/5061#issuecomment-1727914545)

It's working. Thanks a lot.

**Comment by sayakpaul** [comment]
Cool. @younesbelkada cc for this issue.

**Comment by kopyl** [comment]
@sayakpaul @younesbelkada  yo. Is this fixed now?
