### ISSUE TITLE
The argument down_intrablock_additional_residuals should not be changed inside the function UNet2DConditionModel.forward()

### ISSUE THREAD

**Issue by wzhgba** [huggingface/diffusers#5751]
I found the argument down_intrablock_additional_residuals is poped inside the UNet2DConditionModel.forward() function, and don't think it's a good design. This argument is the result of the adapter, and is repeatedly passed into the forward function during the denoising process. If the argument is changed by the function, the later function call will miss the information from the adapter.

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul @yiyixuxu, can you please help me to work around this issue? Thanks

**Comment by patrickvonplaten** [comment]
Can you please provide a reproducible code snippet?
