### ISSUE TITLE
StableDiffusionXLControlNetPipeline can't work with load_lora_weights calling.

### ISSUE THREAD

**Issue by Jiancong** [huggingface/diffusers#5753]
### Describe the bug

I've tried with StableDiffusionXLControlNetPipeline to load_lora_weights . But failed.

### Reproduction

Use this link https://colab.research.google.com/drive/1eOL_TgdAzNee5GWdODQ8OjT83C4If954?usp=sharing

### Logs

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors", adapter_name="toy")
      2 pipe.set_adapters("toy")

File ~/miniconda3/envs/python310/lib/python3.10/site-packages/diffusers/loaders.py:928, in LoraLoaderMixin.load_lora_weights(self, pretrained_model_name_or_path_or_dict, **kwargs)
    907 """
    908 Load LoRA weights specified in `pretrained_model_name_or_path_or_dict` into `self.unet` and
    909 `self.text_encoder`.
   (...)
    925         See [`~loaders.LoraLoaderMixin.lora_state_dict`].
    926 """
    927 state_dict, network_alphas = self.lora_state_dict(pretrained_model_name_or_path_or_dict, **kwargs)
--> 928 self.load_lora_into_unet(state_dict, network_alphas=network_alphas, unet=self.unet)
    929 self.load_lora_into_text_encoder(
    930     state_dict,
    931     network_alphas=network_alphas,
    932     text_encoder=self.text_encoder,
    933     lora_scale=self.lora_scale,
    934 )

File ~/miniconda3/envs/python310/lib/python3.10/site-packages/diffusers/loaders.py:1210, in LoraLoaderMixin.load_lora_into_unet(cls, state_dict, network_alphas, unet)
   1207     warnings.warn(warn_message)
   1209 # load loras into unet
-> 1210 unet.load_attn_procs(state_dict, network_alphas=network_alphas)

File ~/miniconda3/envs/python310/lib/python3.10/site-packages/diffusers/loaders.py:366, in UNet2DConditionLoadersMixin.load_attn_procs(self, pretrained_model_name_or_path_or_dict, **kwargs)
    364 attn_processor = self
    365 for sub_key in key.split("."):
--> 366     attn_processor = getattr(attn_processor, sub_key)
    368 # Process non-attention layers, which don't have to_{k,v,q,out_proj}_lora layers
    369 # or add_{k,v,q,out_proj}_proj_lora layers.
    370 if "lora.down.weight" in value_dict:

File ~/miniconda3/envs/python310/lib/python3.10/site-packages/torch/nn/modules/module.py:1614, in Module.__getattr__(self, name)
   1612     if name in modules:
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))

AttributeError: 'ModuleList' object has no attribute '4'
```

### System Info

2023-11-10 18:28:11.618443: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-10 18:28:12.291443: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-10 18:28:13.738187: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.23.0.dev0
- Platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.17
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.26.0
- Accelerate version: 0.22.0.dev0
- xFormers version: 0.0.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

 @yiyixuxu @sayakpaul @DN6 @patrickvonplaten

**Comment by sayakpaul** [comment]
Could install `diffusers` from `main` and not install `peft`? And report the findings?

**Comment by Jiancong** [comment]
> Could install `diffusers` from `main` and not install `peft`? And report the findings?

Updated notebook at https://www.kaggle.com/entering/2-2-sdxl-controlnet-ipynb. And give following error log:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[6], line 2
      1 pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors", adapter_name="toy")
----> 2 pipe.set_adapters("toy")

File /opt/conda/lib/python3.10/site-packages/diffusers/loaders.py:2476, in LoraLoaderMixin.set_adapters(self, adapter_names, adapter_weights)
   2470 def set_adapters(
   2471     self,
   2472     adapter_names: Union[List[str], str],
   2473     adapter_weights: Optional[List[float]] = None,
   2474 ):
   2475     # Handle the UNET
-> 2476     self.unet.set_adapters(adapter_names, adapter_weights)
   2478     # Handle the Text Encoder
   2479     if hasattr(self, "text_encoder"):

File /opt/conda/lib/python3.10/site-packages/diffusers/loaders.py:723, in UNet2DConditionLoadersMixin.set_adapters(self, adapter_names, weights)
    712 """
    713 Sets the adapter layers for the unet.
    714 
   (...)
    720         adapters.
    721 """
    722 if not USE_PEFT_BACKEND:
--> 723     raise ValueError("PEFT backend is required for `set_adapters()`.")
    725 adapter_names = [adapter_names] if isinstance(adapter_names, str) else adapter_names
    727 if weights is None:

ValueError: PEFT backend is required for `set_adapters()`.

**Comment by sayakpaul** [comment]
You cannot do:

```python
pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors", adapter_name="toy")
pipe.set_adapters("toy")
```

Without `peft`. Sorry, I should have been clear. Could you try:

```python
pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors")
```

And see if it works? This way, we can know if `peft` is causing the issue.

**Comment by Jiancong** [comment]
> You cannot do:
> 
> ```python
> pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors", adapter_name="toy")
> pipe.set_adapters("toy")
> ```
> 
> Without `peft`. Sorry, I should have been clear. Could you try:
> 
> ```python
> pipe.load_lora_weights("CiroN2022/toy-face", weight_name="toy_face_sdxl.safetensors")
> ```
> 
> And see if it works? This way, we can know if `peft` is causing the issue.

Using load_lora_weights is wokring fine for loading. But use this pipeline to inference, gives following NoneType in image checking.


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 4
      1 prompt = "toy_face of a hacker with a hoodie"
      3 lora_scale= 0.9
----> 4 image = pipe(
      5     prompt, num_inference_steps=30, cross_attention_kwargs={"scale": lora_scale}, generator=torch.manual_seed(0)
      6 ).images[0]

File /opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py:973, in StableDiffusionXLControlNetPipeline.__call__(self, prompt, prompt_2, image, height, width, num_inference_steps, guidance_scale, negative_prompt, negative_prompt_2, num_images_per_prompt, eta, generator, latents, prompt_embeds, negative_prompt_embeds, pooled_prompt_embeds, negative_pooled_prompt_embeds, output_type, return_dict, callback, callback_steps, cross_attention_kwargs, controlnet_conditioning_scale, guess_mode, control_guidance_start, control_guidance_end, original_size, crops_coords_top_left, target_size, negative_original_size, negative_crops_coords_top_left, negative_target_size, clip_skip)
    968     control_guidance_start, control_guidance_end = mult * [control_guidance_start], mult * [
    969         control_guidance_end
    970     ]
    972 # 1. Check inputs. Raise error if not correct
--> 973 self.check_inputs(
    974     prompt,
    975     prompt_2,
    976     image,
    977     callback_steps,
    978     negative_prompt,
    979     negative_prompt_2,
    980     prompt_embeds,
    981     negative_prompt_embeds,
    982     pooled_prompt_embeds,
    983     negative_pooled_prompt_embeds,
    984     controlnet_conditioning_scale,
    985     control_guidance_start,
    986     control_guidance_end,
    987 )
    989 # 2. Define call parameters
    990 if prompt is not None and isinstance(prompt, str):

File /opt/conda/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py:564, in StableDiffusionXLControlNetPipeline.check_inputs(self, prompt, prompt_2, image, callback_steps, negative_prompt, negative_prompt_2, prompt_embeds, negative_prompt_embeds, pooled_prompt_embeds, negative_pooled_prompt_embeds, controlnet_conditioning_scale, control_guidance_start, control_guidance_end)
    556 is_compiled = hasattr(F, "scaled_dot_product_attention") and isinstance(
    557     self.controlnet, torch._dynamo.eval_frame.OptimizedModule
    558 )
    559 if (
    560     isinstance(self.controlnet, ControlNetModel)
    561     or is_compiled
    562     and isinstance(self.controlnet._orig_mod, ControlNetModel)
    563 ):
--> 564     self.check_image(image, prompt, prompt_embeds)
    565 elif (
    566     isinstance(self.controlnet, MultiControlNetModel)
    567     or is_compiled
    568     and isinstance(self.controlnet._orig_mod, MultiControlNetModel)
    569 ):
    570     if not isinstance(image, list):

File /opt/conda/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py:657, in StableDiffusionXLControlNetPipeline.check_image(self, image, prompt, prompt_embeds)
    647 image_is_np_list = isinstance(image, list) and isinstance(image[0], np.ndarray)
    649 if (
    650     not image_is_pil
    651     and not image_is_tensor
   (...)
    655     and not image_is_np_list
    656 ):
--> 657     raise TypeError(
    658         f"image must be passed and be one of PIL image, numpy array, torch tensor, list of PIL images, list of numpy arrays or list of torch tensors, but is {type(image)}"
    659     )
    661 if image_is_pil:
    662     image_batch_size = 1

TypeError: image must be passed and be one of PIL image, numpy array, torch tensor, list of PIL images, list of numpy arrays or list of torch tensors, but is <class 'NoneType'>

**Comment by sayakpaul** [comment]
Please be a little careful in your code :) 

```
image = pipe(
    prompt, num_inference_steps=30, cross_attention_kwargs={"scale": lora_scale}, generator=torch.manual_seed(0)
).images[0]
```

Doesn't have an image input which is necessary for a ControlNet pipeline. The error message is quite evident of that.

**Comment by Jiancong** [comment]
> Please be a little careful in your code :)
> 
> ```
> image = pipe(
>     prompt, num_inference_steps=30, cross_attention_kwargs={"scale": lora_scale}, generator=torch.manual_seed(0)
> ).images[0]
> ```
> 
> Doesn't have an image input which is necessary for a ControlNet pipeline. The error message is quite evident of that.

Oh I see. I've updated the code and it works.  

But actually, my question is, how can I fuse multiple lora without PEFT?

**Comment by sayakpaul** [comment]
Fusing multiple LoRAs is recommended to be used with `peft`. 

I think it's better we solve the issue you're facing with `peft` here. Cc: @younesbelkada

**Comment by younesbelkada** [comment]
Hi @Jiancong 
Thanks for the issue - Can provide us a simple reproducer of the bug? in the colab you shared you only call `set_adapters()` without fusing anything

**Comment by Jiancong** [comment]
> Hi @Jiancong Thanks for the issue - Can provide us a simple reproducer of the bug? in the colab you shared you only call `set_adapters()` without fusing anything

I've updated the multiple LoRAs working notebook here.  https://www.kaggle.com/code/entering/2-2-sdxl-controlnet-ipynb   This notebook can effectively solve the problem which caused by different env and package version for me.

Back to this issue, I found that in my local GPU env with following `diffusers-cli env` output, it gives error message which I've described in the very first of this bug report.  

2023-11-10 18:28:11.618443: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-10 18:28:12.291443: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-10 18:28:13.738187: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.23.0.dev0
- Platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.17
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.26.0
- Accelerate version: 0.22.0.dev0
- xFormers version: 0.0.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>



After upgrading my env to the following, the PEFT and controlnet with LoRA works fine.

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.24.0.dev0
- Platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.35.0
- Accelerate version: 0.24.1
- xFormers version: 0.0.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
