### ISSUE TITLE
How to we generate LCM LoRA of an existing model?

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/diffusers#5756]
I generated a DreamBooth model from SDXL base 1.0

To get the speed boost of LCM I need to generate a LCM LoRA from this model

How we do it? I don't see documentation

**Comment by patrickvonplaten** [comment]
cc @patil-suraj

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/tree/main/examples/consistency_distillation

**Comment by FurkanGozukara** [comment]
> cc @patil-suraj

thank you so much

we have to do a fine tuning for that right? it is not like we can extract a LCM lora from already trained model I presume?

**Comment by ShashwatNigam99** [comment]
Yes, given a pretrained model, you obtain its LCM version using distillation. Two options 
- use an LCM-LoRA model for finetuning (basically learns a LoRA for your model for converting it into an LCM) 
- use consistency distillation to learn a LCM version of your diffusion model from scratch.

You will also need access to a dataset for performing either.

**Comment by FurkanGozukara** [comment]
> You will also need access to a dataset for performing either.

Which makes it useless sadly

**Comment by patil-suraj** [comment]
LCM-LoRA is generic so you could also try to directly apply the LoRA to your dreambooth trained model and it should work.
Here's an example of using the LCM-LoRA with dreambooth models/LoRAs: https://huggingface.co/docs/diffusers/using-diffusers/inference_with_lcm_lora#combine-with-styled-loras

I haven't tried this but another approach could be take the LCM trained base model and do dreambooth on it using the consistency training with the linked scripts.

**Comment by FurkanGozukara** [comment]
> LCM-LoRA is generic so you could also try to directly apply the LoRA to your dreambooth trained model and it should work. Here's an example of using the LCM-LoRA with dreambooth models/LoRAs: https://huggingface.co/docs/diffusers/using-diffusers/inference_with_lcm_lora#combine-with-styled-loras
> 
> I haven't tried this but another approach could be take the LCM trained base model and do dreambooth on it using the consistency training with the linked scripts.

I tried and results were terrible :D
