### ISSUE TITLE
train_dreambooth_lora_sdxl.py resume from checkpoint errors.

### ISSUE THREAD

**Issue by kosukekurimoto** [huggingface/diffusers#5757]
### Describe the bug

I get the following issue when trying to resume from checkpoint.

### Reproduction

!accelerate launch train_dreambooth_lora_sdxl.py
--pretrained_model_name_or_path=$MODEL_NAME
--instance_data_dir=$INSTANCE_DIR
--pretrained_vae_model_name_or_path=$VAE_PATH
--output_dir=$OUTPUT_DIR
--mixed_precision="fp16"
--instance_prompt="XXXX style"
--class_prompt="style"
--resolution=1024
--train_batch_size=1
--gradient_accumulation_steps=4
--learning_rate=1e-5
--lr_scheduler="constant"
--lr_warmup_steps=0
--max_train_steps=5000
--validation_prompt="a illustration of a woman"
--validation_epochs=25
--resume_from_checkpoint="latest"
--seed="0"

### Logs

```shell
Steps: 70% 3500/5000 [00:02<?, ?it/s, loss=0.0251, lr=1e-5]Traceback (most recent call last):
File "/content/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1372, in
main(args)
File "/content/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1164, in main
optimizer.step()
File "/usr/local/lib/python3.10/dist-packages/accelerate/optimizer.py", line 132, in step
self.scaler.step(self.optimizer, closure)
File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py", line 413, in step
len(optimizer_state["found_inf_per_device"]) > 0
AssertionError: No inf checks were recorded for this optimizer.
Steps: 70% 3500/5000 [00:03<?, ?it/s, loss=0.0251, lr=1e-5]
Traceback (most recent call last):
File "/usr/local/bin/accelerate", line 8, in
sys.exit(main())
File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
args.func(args)
File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
simple_launcher(args)
File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth_lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--instance_data_dir=/content/drive/Shareddrives/XXXX/train-images', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--output_dir=/content/drive/Shareddrives/XXXX/output', '--mixed_precision=fp16', '--instance_prompt=ausantacm style', '--class_prompt=style', '--resolution=1024', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--learning_rate=1e-5', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=5000', '--validation_prompt=a illustration of a woman', '--validation_epochs=25', '--resume_from_checkpoint=latest', '--seed=0']' returned non-zero exit status 1.
```

### System Info

- `diffusers` version: 0.23.0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.35.0
- Accelerate version: 0.24.1
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by yuxu915** [comment]
hi, @kosukekurimoto , remove flag `--mixed_precision="fp16"` seems work for me, however, resume training seems doesn't update the model, all checkpoints remain the same while training, and I dont know why.

**Comment by sayakpaul** [comment]
Can you try with the latest updates made to the script?

**Comment by sayakpaul** [comment]
Closing due to inactivities.
