### ISSUE TITLE
Remove `torch` dependency from Flax implementations

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#576]
**Is your feature request related to a problem? Please describe.**

The following line fails unless PyTorch is installed:
```
from diffusers import FlaxPNDMScheduler
```

This is because `modeling_utils.py` imports `torch`. Since Flax implementations are separate (schedulers, models and pipelines use their own code), it should be possible to use Flax without PyTorch.

**Describe the solution you'd like**
Be able to import flax components without PyTorch.

**Comment by patrickvonplaten** [comment]
Very much agree on this one! Can look into it tomorrow

**Comment by patrickvonplaten** [comment]
Think this has been solved by now - thanks to your PR @pcuenca
