### ISSUE TITLE
TemporalConvLayer would raise error when in_dim is not equal to out_dim 

### ISSUE THREAD

**Issue by CSU-NXY** [huggingface/diffusers#5762]
### Describe the bug

In class `TemporalConvLayer`, `conv2`'s output dimension is `in_dim`, but `conv3`'s input dimension is `out_dim`. When `in_dim` is not equal to `out_dim`, this would raise following error (assume `in_dim=512` and `out_dim=256`):

RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [256] and input of shape [1, 512, 16, 256, 256]

### Reproduction

1. Create a TemporalConvLayer with different in_dim and out_dim
2. Run the forward process of this layer

### System Info

I don't think system info is relevant to this issue

**Comment by patrickvonplaten** [comment]
Hey @CSU-NXY,

Can you please provide a reproducible code snippet?
