### ISSUE TITLE
Image+Image+Text to Image

### ISSUE THREAD

**Issue by tval2** [huggingface/diffusers#5766]
Maybe a dumb question but I can't seem to find good ways to have multiple images to image modeling. I looked into Multi-ControlNet but I can't tell how to use it. I'm trying to train a model that takes in 2 images and a prompt: 
1. a template base image (e.g. a photo of a room in someone's house with a painting on the wall)
2. a photo of a painting someone made (e.g. not a famous one like a Van Gogh, just someone's painting)
3. an optional text prompt describing the 2nd image...may not be necessary but curious what people here say

And I want to place image2 in image1 to replace the painting on the wall with the new one. Is this the right forum / model to use? I thought maybe creating a custom dataset and then simply feeding 2 image controls in would do the job but really could use some experts' guidance here.

**Comment by yiyixuxu** [comment]
IP-Adapter is perfect for this.. 
https://github.com/huggingface/diffusers/pull/5713
