### ISSUE TITLE
Does the training code in diffusers implement correct mixed precision training?

### ISSUE THREAD

**Issue by Luciennnnnnn** [huggingface/diffusers#5769]
### Describe the bug

Hi, I notice many of example training code explicitly cast every tensor into float16, other than use `torch.autocast`. For example, this controlnet [code](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py) convert every tensors into float16 if we use `--mixed_precision fp16`, though the name is mixed precision, I do not see any "mix" in process. I have a more complex training code, so it's important for me to understand how to precisely implement mixed precision training in diffusers.

### Reproduction

.

### System Info

.

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
Training happens in mixed-precision. Which is why we pass the stuff we're training to `accelerate.prepare()`.

**Comment by Luciennnnnnn** [comment]
Hi @sayakpaul , thank you for immediate responses, after check the source code of `accelerate.prepare() `, I have no problem about how mixed precision is applied. Then, i'll close the issue, thanks!
