### ISSUE TITLE
About guidance_scale in LCM-LoRA

### ISSUE THREAD

**Issue by haofanwang** [huggingface/diffusers#5773]
This is a replicated issue from https://github.com/luosiallen/latent-consistency-model/issues/40.

As suggested in [latent-consistency/lcm-lora-sdv1-5](https://huggingface.co/latent-consistency/lcm-lora-sdv1-5), it is recommended to disable guidance_scale or use values between 1.0 and 2.0. The effect of guidance_scale can be found in [this post](https://twitter.com/Haofan_Wang/status/1723219204537827449). But in the paper, it seems that it should be fine to set the guidance_scale to 7.5 for classifier-free guidance. What causes this difference?

**Comment by haofanwang** [comment]
Solved.

**Comment by SKDDJ** [comment]
> Solved.

So what is the reason?
