### ISSUE TITLE
How to fine tune Stable Diffusion on custom dataset {caption, image}?

### ISSUE THREAD

**Issue by npk7264** [huggingface/diffusers#5774]
I need to do the task that fine tuning SD on custom dataset {caption, image} and custom size? Could you please give me a tutorial for this task?

**Comment by npk7264** [comment]
@dosu-bot Can you give me a tutorial?

**Comment by hoang1007** [comment]
You have 2 options:

1. You can follow [here](https://huggingface.co/docs/datasets/dataset_script) to create your own dataset, and pass the dataset path to the script with `--dataset_name` option.
2. You can structure you images like this [here](https://huggingface.co/docs/datasets/image_dataset#imagefolder) and create a metadata file (metadata.jsonl/metadata.csv) that provides the captions corresponding to each image. Then pass the path of your image folder to the script with `--train_data_dir` option.

Diffusers's training scripts will resize and crop your images to have the same size base on the `resolution` passed to the script (default is 512), but it may cause some information loss in your images. You can try [kohya-ss](https://github.com/kohya-ss/sd-scripts) for more advanced options.
