### ISSUE TITLE
remove the unneeded lines in get_processor

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#5776]
### Describe the bug

can't not access `Unet.attn_processor` after calling `load_lora_weights()`, will get an attribute error

```
AttributeError: 'UNet2DConditionModel' object has no attribute 'Attention.attn_processor'. Did you mean: 'attn_processors'?
```

tracked this all the way down to an exception inside `get_processor()`. seems like we have only some but not all layers that's LoRA activated and trigger an exception here https://github.com/huggingface/diffusers/blob/b1fbef544c993288447181a6c8d8c68d89387ebe/src/diffusers/models/attention_processor.py#L430

I saw a notes says 
```
  # TODO(Sayak, Patrick). The rest of the function is needed to ensure backwards compatible
        # serialization format for LoRA Attention Processors. It should be deleted once the integration
        # with PEFT is completed.
```

Can we delete the rest of function now??? Not familar with the context so not sure what's the best way to do here

I think these bugs are related https://github.com/huggingface/diffusers/issues/5441

### Reproduction

```python
from diffusers import AutoPipelineForText2Image
import torch

pipeline = AutoPipelineForText2Image.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16).to("cuda")
pipeline.load_lora_weights("ostris/super-cereal-sdxl-lora", weight_name="cereal_box_sdxl_v1.safetensors")
print(pipeline.unet.attn_processor)
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/yiyi_huggingface_co/diffusers/yiyi_test_3.py", line 6, in <module>
    print(pipeline.unet.attn_processor)
  File "/home/yiyi_huggingface_co/diffusers/src/diffusers/models/modeling_utils.py", line 214, in __getattr__
    return super().__getattr__(name)
  File "/home/yiyi_huggingface_co/mambaforge/envs/hug_dev_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processor'. Did you mean: 'attn_processors'?
```

### System Info

`diffusers` version: 0.24.0.dev0

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by yiyixuxu** [comment]
cc @sayakpaul here

**Comment by sayakpaul** [comment]
Do you have `peft` installed in your environment? What happens when it's not installed?

I will defer to this @patrickvonplaten.

**Comment by yiyixuxu** [comment]
> Do you have peft installed in your environment? What happens when it's not installed?
no :) this is what happened when it is not installed

**Comment by patrickvonplaten** [comment]
@yiyixuxu did you maybe just forgot to add an `s`? 

```diff
from diffusers import AutoPipelineForText2Image
import torch

pipeline = AutoPipelineForText2Image.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16).to("cuda")
pipeline.load_lora_weights("ostris/super-cereal-sdxl-lora", weight_name="cereal_box_sdxl_v1.safetensors")
- print(pipeline.unet.attn_processor)
+ print(pipeline.unet.attn_processors)
```

**Comment by yiyixuxu** [comment]
OMG yes!!!! lol
