### ISSUE TITLE
training pixart by dreamblooth error

### ISSUE THREAD

**Issue by wen020** [huggingface/diffusers#5777]
### Describe the bug

I use diffusers pipeline training(https://huggingface.co/docs/diffusers/training/dreambooth) and use pixart as the base model(https://huggingface.co/PixArt-alpha/PixArt-XL-2-512x512), but an error will be reported.
image
![image](https://github.com/huggingface/diffusers/assets/54690997/cd99df00-d041-424d-9660-e8c4c6796578)

And the base model have not find unet.

Please tell me how to solve this. thanks

### Reproduction

https://huggingface.co/docs/diffusers/training/dreambooth

### System Info

diffusers==2.1.0

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
You need to make changes to adapt it to PixArt-Alpha. It's not gonna work right off the bat.

**Comment by patrickvonplaten** [comment]
@sayakpaul I don't think we should adapt the "main" dreambooth script here as it's getting too bloated and we're literally getting asked every 2nd day to add something new. It's supposed to be just an example. I'd propose to create a new slim script and add it to the community folder instead

**Comment by sayakpaul** [comment]
Yeah. Absolutely 💯
