### ISSUE TITLE
Why does unload_lora_weights take 14 seconds in PEFT mode?

### ISSUE THREAD

**Issue by chinatian** [huggingface/diffusers#5793]
my code:

import time

pipe.disable_lora()
print('disable_lora')

ts = time.time()
pipe.unload_lora_weights()
print(f'unload_lora_weights {time.time() - ts:.3f}s')

unload_lora_weights 14.214s

My platform:

- GPU 3090
- diffusers 0.23.0.dev0
- peft 0.6.0.dev
- transformers 4.34.1
- Ubuntu 22.04.3 LTS

Who can help?
@yiyixuxu @sayakpaul @DN6 @patrickvonplaten

**Comment by sayakpaul** [comment]
Cc: @pacman100 @younesbelkada

**Comment by pacman100** [comment]
Hello @chinatian, the PR https://github.com/huggingface/diffusers/pull/5741 should resolve it.

**Comment by chinatian** [comment]
Great, how long will it take for this PR https://github.com/huggingface/diffusers/pull/5741 to be merged into the main branch?

**Comment by younesbelkada** [comment]
@chinatian quite soon I would say, we need first to wait for https://github.com/huggingface/peft/pull/1106 being merged which should be done quite quickly

**Comment by chinatian** [comment]
@pacman100 I noticed that this PR #5741 has been merged into the main branch, but I use
pip install git+https://github.com/huggingface/diffusers
After upgrading to the latest version of diffusers, the unload_lora_weights method still takes 13 seconds+

Did I do something wrong?

**Comment by asomoza** [comment]
I tried it and the loras unload almost instantly, both the `unload_lora_weights` and the new `delete_adapters` methods works.

Did you also update peft with pip install git+https://github.com/huggingface/peft ?

That's required for it to work and also mentioned here by @younesbelkada and in the PR.

**Comment by chinatian** [comment]
@asomoza Thanks, after upgrading peft, unload_lora_weights is executed instantly.

**Comment by sayakpaul** [comment]
Closing the issue here since @pacman100 and team have resolved it beautifully!
