### ISSUE TITLE
There is no “tokenizer/config.json” on stabilityai/stable-diffusion-xl-base-1.0

### ISSUE THREAD

**Issue by chenyang23333** [huggingface/diffusers#5794]
### Describe the bug

The error log is “There is no “tokenizer/config.json” on stabilityai/stable-diffusion-xl-base-1.0”，but there is no this file in huggingface.( https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0)

### Reproduction

python train_controlnet_sdxl.py  --pretrained_model_name_or_path=$MODEL_DIR  --output_dir=$OUTPUT_DIR  --dataset_name=fusing/fill50k  --mixed_precision="fp16"  --resolution=1024  --learning_rate=1e-5  --max_train_steps=15000  --validation_image "./conditioning_image_1.png" "./conditioning_image_2.png"  --validation_prompt "red circle with blue background" "cyan circle with brown floral background"  --validation_steps=100  --train_batch_size=1  --gradient_accumulation_steps=4  --report_to="wandb"  --seed=42 

### Logs

```shell
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like stabilityai/stable-diffusion-xl-base-1.0 is not the path to a directory containing a file named tokenizer/config.json.
```

### System Info

It is not important

**Comment by yiyixuxu** [comment]
Hi:

we need a reproducible script in order to understand your issue:)

Thanks!
YiYi

**Comment by chenyang23333** [comment]
> Hi:
> 
> we need a reproducible script in order to understand your issue:)
> 
> Thanks! YiYi

python train_controlnet_sdxl.py --pretrained_model_name_or_path=$MODEL_DIR --output_dir=$OUTPUT_DIR --dataset_name=fusing/fill50k --mixed_precision="fp16" --resolution=1024 --learning_rate=1e-5 --max_train_steps=15000 --validation_image "./conditioning_image_1.png" "./conditioning_image_2.png" --validation_prompt "red circle with blue background" "cyan circle with brown floral background" --validation_steps=100 --train_batch_size=1 --gradient_accumulation_steps=4 --report_to="wandb" --seed=42

**Comment by patrickvonplaten** [comment]
There is a file here: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/tokenizer/tokenizer_config.json

**Comment by standardAI** [comment]
Hi @chenyang23333. I think you ran this command without an internet connection, also your cache didn't have the necessary files.
