### ISSUE TITLE
glide training generates weird images

### ISSUE THREAD

**Issue by xinmiaolin** [huggingface/diffusers#58]
Hi,

Thanks for this amazing repository! I am currently training Glide using the script `train_glide_text_to_image.py`. However, the generated images do not make sense and no matter the text prompt, the generated images are all similar to each other.

Below, for the text "a woman walks her dog on the beach"
![Screen Shot 2022-06-30 at 4 21 59 PM](https://user-images.githubusercontent.com/43487018/176794295-14a7b120-757c-4165-b844-02bec3271f83.png)

and for "puppy in a christmas present"
![Screen Shot 2022-06-30 at 4 22 28 PM](https://user-images.githubusercontent.com/43487018/176794348-cd1f7287-647e-4569-be33-89a06732be9f.png)

I have been training for ~40 epochs on the default dog captions dataset. Besides, the pretrained model fusing/glide-base is able to produce quite good results. for example, for "puppy in a christmas present"
![Screen Shot 2022-06-30 at 4 23 32 PM](https://user-images.githubusercontent.com/43487018/176794437-c29948eb-1dfc-443b-b5a6-6b9aca8de066.png)

Does anyone know what could go wrong during training?

Thanks!

**Comment by anton-l** [comment]
Hi @xinmiaolin! We haven't done enough testing with Glide so far, so the script is not working as intended just yet. But we will publish a separate non-Glide text2img training script soon!

**Comment by xinmiaolin** [comment]
> Hi @xinmiaolin! We haven't done enough testing with Glide so far, so the script is not working as intended just yet. But we will publish a separate non-Glide text2img training script soon!

Hi, are you also going to publish a working Glide training script soon? 

Also, is the fusing/glide-base model trained using the huggingface/diffusers code or other repository? The reason that I asked this is to know whether the Glide implementation of huggingface/diffusers is correct so that we can continue working using it even though the training script is not working right now.

Thank you!

**Comment by anton-l** [comment]
Hi @xinmiaolin! We've had to postpone the release of our Glide port to focus on making the library's API more robust, but it will be released in the next major version :)

**Comment by anton-l** [comment]
Closing this as the Glide example has been deprecated.
A fully functional example is expected after Glide is re-added to the library.
