### ISSUE TITLE
Extending callback functionality to pipeline components.

### ISSUE THREAD

**Issue by TimothyAlexisVass** [huggingface/diffusers#5802]
# Is your feature request related to a problem? Please describe
One implementation is Kohya's "Deep shrink" algorithm for increased resolution with limited cloning/collapsing, which requires modifications to the latents in the unet.

Here is an example with deep shrink:
## Cloning/collapsing on high resolutions
<img width="1198" alt="image" src="https://github.com/huggingface/diffusers/assets/55708319/9c2b9e9f-3874-426e-8244-84c3ac66f4e2">

## Limit it during inference. Code currently available:
[Comfy node](https://gist.github.com/laksjdjf/487a28ceda7f0853094933d2e138e3c6)
[Kohya's original code](https://gist.github.com/kohya-ss/3f774da220df102548093a7abc8538ed)

## Results
<img width="1197" alt="image" src="https://github.com/huggingface/diffusers/assets/55708319/e0cc1d44-6f91-45da-b57c-6602b5a1d672">

# Describe the solution you'd like
Possibility to do modifications in processing done by components of pipelines, during inference.

## Additional details

https://twitter.com/kohya_tech/status/1724273551937786164 [Announcement of discovery/breakdown]

### Translated tweets:<br>
Kohya Tech - @kohya_tech @kohya_tech - Nov 14<br>
Yesterday, I tried to find a method to prevent the composition from collapsing when generating high resolution images. The first attached image is 4 images normally generated at 2688x1536, and the second image is generated by applying the same seed. Highres fix is ​​not applied in either case. Taverns and towns are usually pretty good, but I think you'll find that they're more stable when applied.<br>
<hr>
The idea is extremely simple; we know that composition is determined by timesteps that are close to noise'' and composition is determined by deep parts of U-Net,'' so we just reduce the latents in that part. I have placed the differences realized by the sd-scripts generation script."
<hr>

**Comment by yiyixuxu** [comment]
hi! 
can you explain a little bit more about this feature? what is cloning/collapsing?

**Comment by TimothyAlexisVass** [comment]
If you look at the first image. When generating a larger than what the model has been trained on, it will make duplicates and repeating the same kind of concept.
Those images are 2688x1536 which is larger than SDXL is trained on.

By limiting it during inference with technique that Kohya has implemented, it can be mitigated and instead get the more coherent results in the second example.

**Comment by TimothyAlexisVass** [comment]
@yiyixuxu I've updated the initial description

**Comment by yiyixuxu** [comment]
interesting! basically we resize the latents in some of the blocks. 

It seems to be more of an experimental feature and I think this is not something we want to add into our unet at the moment
cc @patrickvonplaten @sayakpaul

**Comment by TimothyAlexisVass** [comment]
Can we use the existing callback functionality to implement this? Or could we extend that?

**Comment by yiyixuxu** [comment]
umm we don't support callback functions for unet .... think the resize happens inside the unet no?

**Comment by TimothyAlexisVass** [comment]
Could we extend the callback functionality to the components of a pipeline?

**Comment by yiyixuxu** [comment]
@patrickvonplaten 

Is this something we would like to support? I think It requires code change the unet but should be very straightforward and minimum: basically just resize latents in some of the blocks during initial noisy timesteps

Not sure how much this is used and how effective this technique works - should we be open to a PR from community and evaluate how it works from there?

**Comment by patrickvonplaten** [comment]
For now, let's go with a community pipeline no?

**Comment by yiyixuxu** [comment]
@patrickvonplaten 
it need to modify unet code though -

**Comment by TimothyAlexisVass** [comment]
I think the solution is to extend callback functionality in the sub components.
Because of the brilliant advancement in opening up latent modifications in the callback function, I was able to do this:
https://timothyalexisvass.github.io/sdxl-correction/

Remember, the original wish I had was completely unrelated to that, but simply to be able to do unsharp masking on the latents.

With a good framework for doing other modifications, we open up more possibility.

The actual request is about accessing and modifying pipeline components during inference.
I can change the title of the issue.

**Comment by yiyixuxu** [comment]
@TimothyAlexisVass 
I don't think we should add callback to models. Unlike pipelines, I think it is very very uncommon people need to tweak model's forward pass for inference. Also it's not practical because models will have too many execution points, you basically need to have a callback for every step in the forward pass and it just doesn't make sense.

**Comment by patrickvonplaten** [comment]
> @patrickvonplaten it need to modify unet code though -

Can we do it in a hacky way by only modifying the unet from the community pipeline?

**Comment by yiyixuxu** [comment]
@patrickvonplaten 
ohh like create special down/up blocks and override the ones in UNET from the community pipeline? should be doable

@TimothyAlexisVass WDYT? interested in opening a PR?

**Comment by TimothyAlexisVass** [comment]
@yiyixuxu 
Sorry for the late reply.
Basically this technique "fakes" another downscale in the unet if the resolution is larger than the model has been trained on.
I think it's a hacky solution and I think that without a consensus about opening up ability to affect things for components, it's not so important. There are really great upscaling methods which make that specific hack redundant.
I didn't, at that time, understand the difficulty of extending the existing callback functionality.
If someone wants to implement it, I don't mind that the title is changed.

**Comment by yiyixuxu** [comment]
ok should we close the issue then?

**Comment by jfischoff** [comment]
@TimothyAlexisVass what are the great upscaling alternatives you speak of?

**Comment by TimothyAlexisVass** [comment]
> @TimothyAlexisVass what are the great upscaling alternatives you speak of?

Well, that was some time ago. Controlnet Tile + Ultimate SD upscaling is easy to use:

You can check out some comparisons here:
https://imgsli.com/MTgzNDM2/3/1

**Comment by crapthings** [comment]
https://github.com/huggingface/diffusers/issues/7265
