### ISSUE TITLE
BlipDiffusionPipeline

### ISSUE THREAD

**Issue by fkjkey** [huggingface/diffusers#5804]
### Describe the bug

When using the blipdiffusion pipe
I downloaded the Salesforce/blipdiffusion file to the local and replaced it to the local path.
![image](https://github.com/huggingface/diffusers/assets/146184493/0979bfb9-f285-4426-ab66-91b48340dbf6)

 But the tonkenizer cannot be loaded accurately
This is normal for me to do in the other stablediffusion pipe
I wonder if there is a problem with the Salesforce/blipdiffusion configuration file

### Reproduction

controlnet_tile = ControlNetModel.from_pretrained(
    "/home/img2video/models/control/control_v11f1e_sd15_tile", torch_dtype=torch.float16
)
blip_diffusion_pipe = BlipDiffusionControlNetPipeline.from_pretrained(
    "/home/lora_test/model/BLIP_DIFFUSION",
    controlnet=controlnet_tile,
    torch_dtype=torch.float16,
).to("cuda")
img = Image.open('/home/lora_test/test_img/yt.jpg')#/home/lora_test/v2i_lora_data /home/lora_test/test_img
img3 = Image.open('/home/lora_test/test_img/E1.jpg')
output = blip_diffusion_pipe(
    prompt='wearing a black jacket',
    neg_prompt='over-exposure, under-exposure, saturated, duplicate, out of frame, lowres, cropped, worst quality, low quality, jpeg artifacts, morbid, mutilated, out of frame, ugly, bad anatomy, bad proportions, deformed, blurry, duplicate',
    reference_image=img,
    condtioning_image=img3,
    source_subject_category='cat',
    target_subject_category='human',
    guidance_scale=7.5,
    num_inference_steps=20,
    height=512,
    width=384,
    genertor=torch.manual_seed(42),
).images[0]
output.save('/home/lora_test/test_img/test.jpg')

### Logs

```shell
(diffusersV2) root@de265bb42427:/home/lora_test/ip_adapter# python test.py 
Loading pipeline components...:  86%|██████████████████████████████████████████████████████████████████████████████████████████▊               | 6/7 [00:04<00:00,  1.99it/s]'
Traceback (most recent call last):
  File "/home/lora_test/ip_adapter/test.py", line 27, in <module>
    blip_diffusion_pipe = BlipDiffusionControlNetPipeline.from_pretrained(
  File "/root/anaconda3/envs/diffusersV2/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 1253, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/root/anaconda3/envs/diffusersV2/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 506, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/root/anaconda3/envs/diffusersV2/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3236, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/anaconda3/envs/diffusersV2/lib/python3.9/site-packages/diffusers/pipelines/blip_diffusion/modeling_blip2.py", line 438, in __init__
    self.tokenizer = BertTokenizer.from_pretrained("bert-base-uncased", truncation_side="right")
  File "/root/anaconda3/envs/diffusersV2/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2008, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.
```

### System Info

diffusers=0.23.0
transformers=4.35.0
torch=2.0.1

**Comment by yiyixuxu** [comment]
cc @sayakpaul for BlipDiffusion

@fkjkey 
I can't reproduce your issue 

this works so probably not an issue with the config 
```python
from diffusers.pipelines import BlipDiffusionPipeline
import torch

blip_diffusion_pipe = BlipDiffusionPipeline.from_pretrained(
    "Salesforce/blipdiffusion", torch_dtype=torch.float16
).to("cuda")
```

**Comment by fkjkey** [comment]
@yiyixuxu 
Okay, I'll try again, thanks
One more question, can I replace the blipdiffusion unet with the stablediffusion unet
and
Can blipdiffusion use      .load_lora_weights or      .load_textual_inversion
I didn't find it in the implementation of the pipeline

**Comment by yiyixuxu** [comment]
I think BLIP has it own checkpoint so no to both 
cc @sayakpaul here to confirm 
> One more question, can I replace the blipdiffusion unet with the stablediffusion unet
> Can blipdiffusion use .load_lora_weights or .load_textual_inversion

**Comment by sayakpaul** [comment]
The UNet in BLIP diffusion is a `UNet2DConditionModel`:
https://github.com/huggingface/diffusers/blob/ecbe27a07f627b1d400f61e9d4bb9ca96521763c/src/diffusers/pipelines/blip_diffusion/pipeline_blip_diffusion.py#L89

But it doesn't inherit the `LoraLoaderMixin`:
https://github.com/huggingface/diffusers/blob/ecbe27a07f627b1d400f61e9d4bb9ca96521763c/src/diffusers/pipelines/blip_diffusion/pipeline_blip_diffusion.py#L75

So, LoRA-specific APIs like `load_lora_weights()` aren't available to the pipeline. I am not sure of any LoRAs trained on BLIP Diffusion either that are publicly available for us to test. Cc: @ayushtues here as he contributed the pipeline.

**Comment by fkjkey** [comment]
@yiyixuxu 
I'm sorry to bother you again
I re-downloaded the salesforce/blipdiffusion file

Traceback (most recent call last):
  File "/home/lora_test/ip_adapter/test.py", line 27, in <module>
    blip_diffusion_pipe = BlipDiffusionPipeline.from_pretrained(
  File "/root/anaconda3/envs/diffusersV2/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 1253, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/root/anaconda3/envs/diffusersV2/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 506, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/root/anaconda3/envs/diffusersV2/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3236, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/anaconda3/envs/diffusersV2/lib/python3.9/site-packages/diffusers/pipelines/blip_diffusion/modeling_blip2.py", line 438, in __init__
    self.tokenizer = BertTokenizer.from_pretrained("bert-base-uncased", truncation_side="right")
  File "/root/anaconda3/envs/diffusersV2/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2008, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

It will try to download the file bert-base-uncased.Can you try downloading the file locally to see if the same problem occurs
I have this confusion mainly because, in the other stablediffusion pipeline, I download the file and use the local path, it does not appear to go to another place to download the other file
Or give me a suggestion, about downloading the Bert - base - uncased file, how to use it in BlipDiffusionPipeline. From_pretrained

**Comment by fkjkey** [comment]
I modified the source code and passed it in tokenizer and it worked
`class Blip2QFormerModel(Blip2PreTrainedModel):
    """
    Querying Transformer (Q-Former), used in BLIP-2.
    """

    def __init__(self, config: Blip2Config,_tokenizer):
        super().__init__(config)
        self.config = config
        self.embeddings = Blip2TextEmbeddings(config.qformer_config)
        self.visual_encoder = Blip2VisionModel(config.vision_config)
        self.query_tokens = nn.Parameter(torch.zeros(1, config.num_query_tokens, config.qformer_config.hidden_size))
        # if not hasattr(config, "tokenizer") or config.tokenizer is None:
        #     self.tokenizer = BertTokenizer.from_pretrained("bert-base-uncased", truncation_side="right")
        # else:
        #     self.tokenizer = BertTokenizer.from_pretrained(config.tokenizer, truncation_side="right")
        self.tokenizer = _tokenizer
        self.tokenizer.add_special_tokens({"bos_token": "[DEC]"})
        self.proj_layer = ProjLayer(
            in_dim=config.qformer_config.hidden_size,
            out_dim=config.qformer_config.hidden_size,
            hidden_dim=config.qformer_config.hidden_size * 4,
            drop_p=0.1,
            eps=1e-12,
        )

        self.encoder = Blip2QFormerEncoder(config.qformer_config)

        self.post_init()`
Then pass it in and call it
`tokenizer = CLIPTokenizer.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/tokenizer')
text_encoder = ContextCLIPTextModel.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/text_encoder')
vae = AutoencoderKL.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/vae')
unet = UNet2DConditionModel.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/unet')
image_processor = BlipImageProcessor.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/image_processor')
# scheduler = EulerAncestralDiscreteScheduler
bert = BertTokenizer.from_pretrained("/home/lora_test/model/BLIP_DIFFUSION/bert", truncation_side="right")
qformer = Blip2QFormerModel.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/qformer',bert)
# qformer.config.tokenizer=tokenizer#/home/lora_test/blip /home/lora_test/model/BLIP_DIFFUSION/qformer

blip_diffusion_pipe = BlipDiffusionPipeline.from_pretrained(
    '/home/lora_test/model/BLIP_DIFFUSION',
    tokenizer = tokenizer,
    text_encoder = text_encoder,
    vae = vae,
    unet = unet,
    qformer = qformer,
    image_processor = image_processor,
    # scheduler = scheduler,
).to("cuda")
cond_subject = "cat"
tgt_subject = "cat"
text_prompt_input = "swimming underwater"

cond_image = Image.open('/home/lora_test/test_img/yt.jpg')
guidance_scale = 7.5
num_inference_steps = 25
negative_prompt = "over-exposure, under-exposure, saturated, duplicate, out of frame, lowres, cropped, worst quality, low quality, jpeg artifacts, morbid, mutilated, out of frame, ugly, bad anatomy, bad proportions, deformed, blurry, duplicate"


output = blip_diffusion_pipe(
    text_prompt_input,
    cond_image,
    cond_subject,
    tgt_subject,
    guidance_scale=guidance_scale,
    num_inference_steps=num_inference_steps,
    neg_prompt=negative_prompt,
    height=512,
    width=512,
).images
output[0].save("/home/lora_test/test_img/image.png")`

**Comment by fkjkey** [comment]
I modified the source code constructor and passed tokenizer in, and it worked.
class Blip2QFormerModel(Blip2PreTrainedModel):
    """
    Querying Transformer (Q-Former), used in BLIP-2.
    """

    def __init__(self, config: Blip2Config,_tokenizer):
        super().__init__(config)
        self.config = config
        self.embeddings = Blip2TextEmbeddings(config.qformer_config)
        self.visual_encoder = Blip2VisionModel(config.vision_config)
        self.query_tokens = nn.Parameter(torch.zeros(1, config.num_query_tokens, config.qformer_config.hidden_size))
        # if not hasattr(config, "tokenizer") or config.tokenizer is None:
        #     self.tokenizer = BertTokenizer.from_pretrained("bert-base-uncased", truncation_side="right")
        # else:
        #     self.tokenizer = BertTokenizer.from_pretrained(config.tokenizer, truncation_side="right")
        self.tokenizer = _tokenizer
        self.tokenizer.add_special_tokens({"bos_token": "[DEC]"})
        self.proj_layer = ProjLayer(
            in_dim=config.qformer_config.hidden_size,
            out_dim=config.qformer_config.hidden_size,
            hidden_dim=config.qformer_config.hidden_size * 4,
            drop_p=0.1,
            eps=1e-12,
        )

        self.encoder = Blip2QFormerEncoder(config.qformer_config)

        self.post_init()

tokenizer = CLIPTokenizer.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/tokenizer')
text_encoder = ContextCLIPTextModel.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/text_encoder')
vae = AutoencoderKL.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/vae')
unet = UNet2DConditionModel.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/unet')
image_processor = BlipImageProcessor.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/image_processor')
bert = BertTokenizer.from_pretrained("/home/lora_test/model/BLIP_DIFFUSION/bert", truncation_side="right")
qformer = Blip2QFormerModel.from_pretrained('/home/lora_test/model/BLIP_DIFFUSION/qformer',bert)

blip_diffusion_pipe = BlipDiffusionPipeline.from_pretrained(
    '/home/lora_test/model/BLIP_DIFFUSION',
    tokenizer = tokenizer,
    text_encoder = text_encoder,
    vae = vae,
    unet = unet,
    qformer = qformer,
    image_processor = image_processor,
).to("cuda")

**Comment by CesarERamosMedina** [comment]
> So, LoRA-specific APIs like load_lora_weights() aren't available to the pipeline. I am not sure of any LoRAs trained on BLIP Diffusion either that are publicly available for us to test. 
@sayakpaul I wonder if the existing HF LoRA training script would even work with BLIPDiffusion given that it uses a ContextClipTextModel (as opposed to a ClipTextModel)

**Comment by sayakpaul** [comment]
You'd need to modify the script. It won't work right off the bat.
