### ISSUE TITLE
low attention to prompt in SDXL

### ISSUE THREAD

**Issue by saeedkhanehgir** [huggingface/diffusers#5816]
Hi, 
One of the difference between DALLE3 and SDXL is that SDXL pay less attention to prompt,
Is there a way to solve this problem? I don't Know. for example changing the text encoder to other  can help to solve this problem ? 
Thanks

**Comment by AmericanPresidentJimmyCarter** [comment]
Yes. You can relabel the LAION 5b dataset with GPT4V API, then you can remove the old text encoder and retrain the entire model with the other weights frozen and using a good text encoder like T5 XXL. It will only be a few millions of dollars to caption 5b.

**Comment by yiyixuxu** [comment]
You can't change to a different text encoder that the model wasn't trained on at inference time

I think SDXL is still the best we have in term of prompt following. cc @sayakpaul

**Comment by sayakpaul** [comment]
You can do prompt-weighting: https://huggingface.co/docs/diffusers/main/en/using-diffusers/weighted_prompts. 

Also, for questions, please post them on [our Discord forum](http://hf.co/join/discord). Issues are supposed to be about bugs, feature requests, API design RFCs, etc.

**Comment by saeedkhanehgir** [comment]
thanks a bunch @yiyixuxu  @sayakpaul 

I have another question. I have to use Compel to solve long sequence length problem . I want to know that  can Compel decrease attention to prompt ?
