### ISSUE TITLE
Activation function and Fourier process 

### ISSUE THREAD

**Issue by power9799** [huggingface/diffusers#5817]
### Model/Pipeline/Scheduler description

Hi, i tried to add an activation function to GELU, before i even started , i keep getting import use_PEFT_Backend  error, even though i already have utils  installed. 
it says attempted relative import with no known parent package.
If i change the activation function, the data from stable diffusion probably wont work yeah, either i would need to retrain or convert the stable diffusion model data or i need to add another activation layer to  the  gelu model and train it again.
also can if I want to change the scalar diffusion process to fourier, i would need to change the unet models’    forward and backward process and  yeah? Or is it better to add scalar to fourier converter? 

### Open source status

- [ ] The model implementation is available.
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/activations.py#L50
https://github.com/huggingface/diffusers/blob/v0.23.0/src/diffusers/models/unet_1d.py#L41

**Comment by yiyixuxu** [comment]
Hi:
sorry I don't really understand what's the issue here - can you provide a reproducible script?

**Comment by power9799** [comment]
> Hi: sorry I don't really understand what's the issue here - can you provide a reproducible script?
Here is the error while adding a new activation function.
ImportError                               Traceback (most recent call last)
[( in <cell line: 33>()
     31 from torch import nn
     32 get_ipython().system('pip install python-utils')
---> 33 from ..utils import USE_PEFT_BACKEND
     34 from .lora import LoRACompatibleLinear
     35 

ImportError: attempted relative import with no known p
