### ISSUE TITLE
Problematic default value for `text_encoder_projection_dim` in `get_add_time_ids()` method of `StableDiffusionXLPipeline`

### ISSUE THREAD

**Issue by tyler-tomita** [huggingface/diffusers#5824]
### Describe the bug

The `get_add_time_ids()` method of `StableDiffusionXLPipline` currently has the following defaults defined in line 573 of `stable_diffusion_xl/pipeline_stable_diffusion_xl.py`:
```
def _get_add_time_ids(
        self, original_size, crops_coords_top_left, target_size, dtype, text_encoder_projection_dim=None
    ):
```

The problem is in line 579:
```
self.unet.config.addition_time_embed_dim * len(add_time_ids) + text_encoder_projection_dim
```
If `text_encoder_projection_dim` assumes the default value of `None`, then you end up adding an `int` to a `None`, which is an undefined operation resulting in a `TypeError`

### Reproduction

```
import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16
)
pipe = pipe.to("cuda")

with torch.no_grad():
    time_ids = pipe._get_add_time_ids([512, 512], [0,0], [512,512], dtype=torch.float16)
```

### Logs

```shell
File "/home/textual_inversion_xl.py", line 765, in main
    time_ids = pipe._get_add_time_ids([512, 512],[0,0],[512,512],dtype=unet.dtype).to(unet.device)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 579, in _get_add_time_ids
    self.unet.config.addition_time_embed_dim * len(add_time_ids) + text_encoder_projection_dim
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```
```


### System Info

```
- `diffusers` version: 0.23.0
- Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.1.0 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.35.1
- Accelerate version: 0.24.1
- xFormers version: 0.0.22.post7
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
- ```

### Who can help?

@yiyixuxu @sayakpaul @DN6 @patrickvonplaten

**Comment by yiyixuxu** [comment]
hey thanks you! good point 

are you interested in open an PR to fix it? Just need to add an `if ...`  condition to handle the default None case IMO

**Comment by charchit7** [comment]
hey @yiyixuxu I'll update this.

**Comment by charchit7** [comment]
Added check here : #5843

**Comment by kghamilton89** [comment]
Hello @yiyixuxu, I'll give this a try as my first HuggingFace contribution.

**Comment by kghamilton89** [comment]
Per @yiyixuxu, support for this use case not needed. Suggested to close issue, @tyler-tomita.
