### ISSUE TITLE
Training DreamBooth with Pixart Alpha doesn't work.

### ISSUE THREAD

**Issue by quocanh34** [huggingface/diffusers#5845]
### Describe the bug

The model didn't generate the object I want. I trained with instance prompt "a photo of sks dog" and it generated with a random dog. Maybe there are problems with my training code scripts.

All I did is to change the code train_dreambooth.py from diffusers to adapt it with Pixart-Alpha-Pipeline instead of DiffusionPipeline, and I also used transformer for the denoising model (instead of unet). The code runs without any errors. 

That's why I wonder where did I go wrong? In the forward method of transformer, did I miss something?

![image](https://github.com/huggingface/diffusers/assets/79373948/be197ab9-fa35-4a6b-ae23-00714481538d)

### Reproduction

Here is my full training scripts:
https://pastecode.io/s/hrofzbuc

### System Info

diffusers version: 0.24.0.dev0

### Who can help?

@patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
We cannot offer guidance on things that we haven't implemented ourselves or maintained. I suggest you post it on our Discord forum as it doesn't related to the codebase that is a part of the library.

**Comment by quocanh34** [comment]
Thanks, I have also asked the author, good day @sayakpaul
