### ISSUE TITLE
diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py --resume_from_checkpoint error

### ISSUE THREAD

**Issue by stpic270** [huggingface/diffusers#5846]
### Describe the bug

I have tried to continue training in **google colab** for diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py script with flag resume_from_checkpoint 'latest' but I have got error: No inf checks were recorded for this optimizer. I tried to solve it with different accelerate, vae model and optimizer versions. I also tried to turn off "mixed_precision"  parameter but could not overcome the problem. I also saw similar problem with dreambooth - https://github.com/huggingface/diffusers/issues/3279#issuecomment-1806658482 but as I said tried different versions of accelerate, so should I open issue with accelerate ?

### Reproduction

The latest versions when I got this issues:
torch==

! accelerate launch /content/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
  --train_data_dir="/content/EN_DATA" \
  --caption_column="text" \
  --resolution=512 --random_flip \
  --gradient_accumulation_steps=11 \
  --train_batch_size=3 \
  --num_train_epochs=1 --checkpointing_steps=1 --checkpoints_total_limit=3 \
  --learning_rate=3e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --mixed_precision="fp16" \
  --validation_prompt="Beutiful comet in a cartoon style" \
  --seed=42 \
  --report_to="wandb" \
  --output_dir='/content/output_dir_5_epochs' \
  --resume_from_checkpoint 'latest' \
  --use_8bit_adam

### Logs

```shell
Resuming from checkpoint checkpoint-3
11/17/2023 16:49:34 - INFO - accelerate.accelerator - Loading states from /content/output_dir_5_epochs/checkpoint-3
Loading unet.
11/17/2023 16:49:35 - INFO - accelerate.checkpointing - All model weights loaded successfully
11/17/2023 16:49:36 - INFO - accelerate.checkpointing - All optimizer states loaded successfully
11/17/2023 16:49:36 - INFO - accelerate.checkpointing - All scheduler states loaded successfully
11/17/2023 16:49:36 - INFO - accelerate.checkpointing - All dataloader sampler states loaded successfully
11/17/2023 16:49:36 - INFO - accelerate.checkpointing - GradScaler state loaded successfully
11/17/2023 16:49:36 - INFO - accelerate.checkpointing - All random states loaded successfully
11/17/2023 16:49:36 - INFO - accelerate.accelerator - Loading in 0 custom states
Steps:   0% 3/7765 [00:20<?, ?it/s, lr=0.0003, step_loss=0.0715]Traceback (most recent call last):
  File "/content/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py", line 1263, in <module>
    main(args)
  File "/content/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py", line 1089, in main
    optimizer.step()
  File "/usr/local/lib/python3.10/dist-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py", line 413, in step
    len(optimizer_state["found_inf_per_device"]) > 0
AssertionError: No inf checks were recorded for this optimizer.
Steps:   0% 3/7765 [00:22<?, ?it/s, lr=0.0003, step_loss=0.0715]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

### System Info

- `diffusers` version: 0.24.0.dev0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.24.1
- xFormers version: 0.0.22.post7+cu118

### Who can help?

@sayakpaul could you have a look, please?

**Comment by yuxu915** [comment]
hi, @stpic270 , remove flag `--mixed_precision="fp16"` works for me, however, after that, another problem is that model  did not update during each iteration of training. Maybe you could have a try🍻

**Comment by stpic270** [comment]
> hi, @stpic270 , remove flag `--mixed_precision="fp16"` works for me, however, after that, another problem is that model did not update during each iteration of training. Maybe you could have a try🍻

Hiiii, I am sorry for late response, I tried to use --mixed_precision="fp16", however didn't have any success 
But I used decided to use flag --train_text_encoder. It is said "Training the text encoder requires additional memory", but I spent extra 500 megabyte for batch_size 3 and resolution 512 with   --mixed_precision="fp16". I also changed --num_validation_images=2 (instead of 4) in order to avoid memory problem after each epoch
My whole set of parameters looks like this:
! accelerate launch /kaggle/working/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --pretrained_vae_model_name_or_path='madebyollin/sdxl-vae-fp16-fix' \
  --train_data_dir=None --load_dataset_from_disk="/kaggle/input/my-en-data-cleaned" \
  --caption_column="text" \
  --resolution=512 --random_flip \
  --gradient_accumulation_steps=16 \
  --train_batch_size=3 \
  --num_train_epochs=8 --checkpointing_steps=25 --checkpoints_total_limit=3 \
  --learning_rate=3e-4 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --mixed_precision="fp16" --resume_from_checkpoint='latest' \
  --validation_prompt="Cool dragon white background" \
  --seed=42 --train_text_encoder --snr_gamma 5.0 \
  --validation_epochs=1 --num_validation_images=2 \
  --report_to="wandb" --adam_weight_decay=1e-1 \
  --output_dir='/kaggle/working/output_dir_5_epochs'

**Comment by sayakpaul** [comment]
Thanks for the updates. We recently updated our LoRA training scripts with PEFT. So, I welcome you to check it out!
