### ISSUE TITLE
Convert training checkpoint to a model for a piple

### ISSUE THREAD

**Issue by kopyl** [huggingface/diffusers#5851]
I need to be able to convert a training checkpoint into a model with a data structure like this: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/tree/main

Meaning it should be possible to load it with a pipeline (specifically `StableDiffusionXLPipeline`)

currently the checkpoint directory structure looks like this:
```
optimizer.bin
random_states_0.pkl
scaler.pt
scheduler.bin
unet
```

So i just need something which i can give a path to this directory, path to output model directory and convert it.

The checkpoint directory is made with this script: https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py

**Comment by kopyl** [comment]
I found a way to load into my pipeline, although i still have to provide some data (but i could get it from my training arguments):

```
!pip install git+https://github.com/huggingface/diffusers.git
!pip install transformers


from diffusers import StableDiffusionXLPipeline, UNet2DConditionModel, AutoencoderKL
import torch


unet = UNet2DConditionModel.from_pretrained(
    "/workspace/unet", use_safetensors=True, torch_dtype=torch.float16
).to("cuda")

vae = AutoencoderKL.from_pretrained(
    "madebyollin/sdxl-vae-fp16-fix",
    torch_dtype=torch.float16
).to("cuda")

pipeline = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    vae=vae,
    unet=unet,
    torch_dtype=torch.float16,
).to("cuda")

prompt = "an icon of a boat"
image = pipeline(prompt=prompt, guidance_scale=10).images[0]
image
```

**Comment by patrickvonplaten** [comment]
This way: https://github.com/huggingface/diffusers/issues/5851#issuecomment-1817251703 of loading it looks good to me!
