### ISSUE TITLE
Update Pillow library

### ISSUE THREAD

**Issue by CristoJV** [huggingface/diffusers#586]
### Describe the bug

Compatibility error when installing Pillow library > 9.1

|Deprecated | Use Instead|
|----------------|----------|
|Image.LANCZOS | Image.Resampling.LANCZOS|
|Image.NEAREST | Image.Resampling.NEAREST|
|Image.BILINEAR| Image.Resampling.BILINEAR|

Here the [link](https://pillow.readthedocs.io/en/stable/deprecations.html)

### Reproduction

pip install pillow==9.1
```python
from diffusers import AutoencoderKL, UNet2DConditionModel
```

### System Info

Compatibility error when installing Pillow library > 9.1

```console
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1030         try:
-> 1031             return importlib.import_module("." + module_name, self.__name__)
   1032         except Exception as e:

19 frames

AttributeError: module 'PIL.Image' has no attribute 'Resampling'


The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1034                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1035                 f" traceback):\n{e}"
-> 1036             ) from e
   1037 
   1038     def __reduce__(self):

RuntimeError: Failed to import transformers.models.clip.feature_extraction_clip because of the following error (look up to see its traceback):
module 'PIL.Image' has no attribute 'Resampling'
```

**Comment by anton-l** [comment]
Hi @CristoJV! I wasn't able to reproduce the error locally with PIllow 9.2.0 installed, and it looks like the deprecation will come with version 10.0, which is not released yet. Could you please verify your `PIL.__version__`?
Capping the Pillow version at 10.0 in the meantime: https://github.com/huggingface/diffusers/pull/588
