### ISSUE TITLE
Using ControlNet only with `UNet2DModel`

### ISSUE THREAD

**Issue by ChengAoShen** [huggingface/diffusers#5861]
**What API design would you like to have changed or added to the library? Why?**
I want to use ControlNet only with a normal DDPM process rather than StableDiffusion, which means I need to build `ControlNetModel` with `UNet2DModel` instead of `UNet2DConditionModel`. I want only to use conditions from *ControlNet* to control the final output. In detail, I want to utilize the conditional images to fusion new images.  For example, I want to fusion emojis in my research and I already trained a U-net that can generate emojis directly. In this case, I need a `ControlNetModel` created by the normal `UNet2DModel` to accept conditional images and generate new emojis (or maybe the predicted noise during the training process).

**What use case would this enable or better enable? Can you give us a code example?**
```python
ControlNetModel.from_unet(unet)
```
where `unet` is `UNet2DModel`.

*Moreover, I want to know how to train this model (maybe I can use the original `train_unconditional.py`), please help me if you have some advice.*

**Comment by patrickvonplaten** [comment]
Hmm I haven't looked into such an example yet

**Comment by ljw919** [comment]
> **What API design would you like to have changed or added to the library? Why?** I want to use ControlNet only with a normal DDPM process rather than StableDiffusion, which means I need to build `ControlNetModel` with `UNet2DModel` instead of `UNet2DConditionModel`. I want only to use conditions from _ControlNet_ to control the final output. In detail, I want to utilize the conditional images to fusion new images. For example, I want to fusion emojis in my research and I already trained a U-net that can generate emojis directly. In this case, I need a `ControlNetModel` created by the normal `UNet2DModel` to accept conditional images and generate new emojis (or maybe the predicted noise during the training process).
> 
> **What use case would this enable or better enable? Can you give us a code example?**
> 
> ```python
> ControlNetModel.from_unet(unet)
> ```
> 
> where `unet` is `UNet2DModel`.
> 
> _Moreover, I want to know how to train this model (maybe I can use the original `train_unconditional.py`), please help me if you have some advice._

Can I use the controlnetmodel to generate the controlnet using Unet2dConditionModel, and set the text embedding input as None ?
