### ISSUE TITLE
stable-diffusion-v1-4 does not have required filenames for variant=fp16

### ISSUE THREAD

**Issue by andreaskundig** [huggingface/diffusers#5863]
Running a [stable_diffusion notebook ](https://github.com/fastai/diffusion-nbs/blob/master/stable_diffusion.ipynb ) from the fast.ai course on colab, I get an error asking me to open an issue here. Apparently you would even be grateful !??

```
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", revision="fp16", torch_dtype=torch.float16).to("cuda")
```

/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py:267: FutureWarning: You are loading the variant fp16 from CompVis/stable-diffusion-v1-4 via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that CompVis/stable-diffusion-v1-4 currently does not have the required variant filenames in the 'main' branch. 
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'CompVis/stable-diffusion-v1-4 is missing fp16 files' so that the correct variant file can be added.

**Comment by patrickvonplaten** [comment]
Hey @andreaskundig,

CompVis 1-4 has fp16 weights here: https://huggingface.co/CompVis/stable-diffusion-v1-4/blob/main/unet/diffusion_pytorch_model.fp16.safetensors

Can you try again with:

```
pip install --upgrade diffusers
```
?

**Comment by andreaskundig** [comment]
Since I'm running this in colab, I need to pip install diffusers at every session. This is how the notebook starts
```
!pip install -Uq diffusers transformers fastcore
```

Just to be sure I also executed your upgrade code.
```
pip install --upgrade diffusers
```
Many "Requirement already satisfied" seem to indicate the first installation was enough.
```
Collecting diffusers
  Downloading diffusers-0.23.1-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 7.7 MB/s eta 0:00:00
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from diffusers) (9.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from diffusers) (3.13.1)
Requirement already satisfied: huggingface-hub>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from diffusers) (0.19.3)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.10/dist-packages (from diffusers) (6.8.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from diffusers) (1.23.5)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from diffusers) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from diffusers) (2.31.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from diffusers) (0.4.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.13.2->diffusers) (2023.6.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.13.2->diffusers) (4.66.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.13.2->diffusers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.13.2->diffusers) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.13.2->diffusers) (23.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata->diffusers) (3.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers) (2023.7.22)
Installing collected packages: diffusers
Successfully installed diffusers-0.23.1
```

Unsurprisingly when running the same line as in the description of the issue, I get get the same error messages
```
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", revision="fp16", torch_dtype=torch.float16).to("cuda")

/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py:267: FutureWarning: You are loading the variant fp16 from CompVis/stable-diffusion-v1-4 via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that CompVis/stable-diffusion-v1-4 currently does not have the required variant filenames in the 'main' branch. 
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'CompVis/stable-diffusion-v1-4 is missing fp16 files' so that the correct variant file can be added.
  warnings.warn(
```

**Comment by johnshaughnessy** [comment]
I reproduced this issue (using the [same notebook](https://github.com/fastai/diffusion-nbs/blob/68767dd6d6893d3bfa8237f975caa71a766a543d/stable_diffusion.ipynb) ).

I was able to fix the issue by changing `revision="fp16"` to `variant="fp16"` as the warning suggested:

```diff
- pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", revision="fp16", torch_dtype=torch.float16).to("cuda")
+ pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", variant="fp16", torch_dtype=torch.float16).to("cuda")
```

My issue is fixed, but since the `fp16` variant is available, I suspect there may be a problem with the code that handles the (deprecated) `"revision"` parameter:

https://github.com/huggingface/diffusers/blob/2a7f43a73bda387385a47a15d7b6fe9be9c65eb2/src/diffusers/pipelines/pipeline_utils.py#L252-L271

I will attach screenshots below for posterity.

Screenshot reproducing the issue:
![snip_2023_11_26_22_38_10](https://github.com/huggingface/diffusers/assets/4072106/2f3c5564-d6af-47fc-bf2b-46d627d36cff)

Screenshot with the issue fixed:
![snip_2023_11_26_22_36_17](https://github.com/huggingface/diffusers/assets/4072106/96842cb7-bc01-468f-ba91-7d54bd0624e6)

**Comment by johnshaughnessy** [comment]
I found some related issues:

- https://github.com/huggingface/diffusers/issues/5918 reports that stabilityai/stable-diffusion-2-1-base is missing fp16.safetensors, but they are here: https://huggingface.co/stabilityai/stable-diffusion-2-1-base/blob/main/unet/diffusion_pytorch_model.fp16.bin

- https://github.com/huggingface/diffusers/issues/5929 reports that runwayml/stable-diffusion-v1-5 is missing fp16.safetensors, but they are here: https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/unet/diffusion_pytorch_model.fp16.safetensors

I'm not very familiar with the diffusers code, but it seems like they're running into the same (or similar) problem.
