### ISSUE TITLE
AnimateDiff + ControlNet

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#5866]
### Model/Pipeline/Scheduler description

Anyone interested in adding a `AnimateDiffControlNetPipeline`? 

The expected behavior is to allow user to pass a list of conditions (e.g. pose) and use them to condition the generation for each frame. 

see comfy UI example workflow here
https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved#txt2img-w-initial-controlnet-input-using-openpose-images--latent-upscale-w-full-denoise

![image](https://user-images.githubusercontent.com/7365912/265043418-23291941-864d-495a-8ba8-d02e05756396.gif)
![image](https://user-images.githubusercontent.com/7365912/270298571-621a2ca6-2f08-4ed1-96ad-8e6635303173.gif)

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by charchit7** [comment]
Hey @yiyixuxu, I'm excited to give this a try. Do you have an estimated time frame for how long it might take?

**Comment by staghado** [comment]
Interested as well!

**Comment by yiyixuxu** [comment]
cc @DN6 here

**Comment by a-r-r-o-w** [comment]
@charchit7 @staghado If it's alright, I'd like to jump in as well if you're collaborating.

**Comment by charchit7** [comment]
@a-r-r-o-w, @staghado happy to collaborate :)

**Comment by EdoardoBotta** [comment]
I'm happy to collaborate on this as well.

**Comment by a-r-r-o-w** [comment]
@charchit7 @staghado @EdoardoBotta Awesome! Let's set up a server to discuss more on this and distribute work?

**Comment by hackpk** [comment]
@charchit7 @staghado @EdoardoBotta @a-r-r-o-w Can I join too?

**Comment by charchit7** [comment]
Please reach out on discord : .archer_cs

**Comment by souvikg544** [comment]
Hello ! I have worked on Animate Anyone and Animate Diff and would love to make a contribiution for the pipeline here. I see a PR that had been merged. Are there any adittional issues in this which will be worth a solve ?

**Comment by a-r-r-o-w** [comment]
Hello @souvikg544, I think we forgot marking this issue as resolved. Please feel free to look at the others ones tagged `good-first-issue` or `Good Second Issue` if you'd like to help add anything. Looking forward to your PRs, thanks!
