### ISSUE TITLE
Dataset access of LCM training

### ISSUE THREAD

**Issue by littletomatodonkey** [huggingface/diffusers#5868]
Hi, thanks for your good job in LCM-LoRA training ! I want to try the new feature, but it seems that i do not have access to the training data since i do not have aws account, could you please provide a new data address such as google drive or huggingface for better access? Thanks !

**Comment by patrickvonplaten** [comment]
cc @patil-suraj

**Comment by sayakpaul** [comment]
Follow https://github.com/huggingface/diffusers/pull/5908.
