### ISSUE TITLE
Conversion to onnx does not work: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

### ISSUE THREAD

**Issue by kopyl** [huggingface/diffusers#5873]
### Describe the bug

The script scripts/convert_stable_diffusion_checkpoint_to_onnx.py

### Reproduction

Run the script scripts/convert_stable_diffusion_checkpoint_to_onnx.py with SD 1.5 model

### System Info

Linux

**Comment by patrickvonplaten** [comment]
cc @DN6 can you take a look here?

**Comment by DN6** [comment]
@kopyl Can you please run `diffusers-cli env` and paste the output here? It is difficult to reproduce your issue without knowing your environment details.

**Comment by kopyl** [comment]
@DN6 hey. Solved it by exporting with optimum export, thank you
