### ISSUE TITLE
Classifier free guidance implementation does not match the description in the paper?

### ISSUE THREAD

**Issue by juancamilog** [huggingface/diffusers#5882]
The [paper](https://arxiv.org/pdf/2207.12598.pdf) describes classifier free guidance as this:

<img width="687" alt="image" src="https://github.com/huggingface/diffusers/assets/2013726/74c94bb4-09dd-4091-a3f1-239e70c76a25">

But in all of the pipelines in diffusers is implemented like this:

https://github.com/huggingface/diffusers/blob/ebc7bedeb7d07269f4e2b2ce38afb77ed9b4c91e/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L853

(see other pipelines [here](https://github.com/search?q=repo%3Ahuggingface%2Fdiffusers%20noise_pred_uncond%2C%20noise_pred_text%20%3D%20noise_pred.chunk(2)&type=code))

According to the paper, if we set the guidance weight to 0, we get the **original text-conditioned** prediction. But in the diffusers implementation setting the guidance scale to 0 gives you the **unconditional** prediction.

Is this a bug?

**Comment by patrickvonplaten** [comment]
Actually in `diffusers` setting `guidance_scale=0` is the same as setting `guidance_scale=1.0` which is equal to the original text-conditioned prediction.

**Comment by jonatanklosko** [comment]
This is very confusing, I just noticed this discrepancy between a couple papers and found this issue.

There are two formulations:

### 1. $\epsilon = \epsilon_{cond} + w(\epsilon_{cond} - \epsilon_{uncond})$

This formulation is used by the original paper [Classifier-free diffusion guidance](https://arxiv.org/pdf/2207.12598.pdf), Equation (6):

<img width="538" alt="image" src="https://github.com/huggingface/diffusers/assets/17034772/abd6368e-01cd-415e-8cc8-e038490ce80a">

### 2. $\epsilon = \epsilon_{uncond} + w(\epsilon_{cond} - \epsilon_{uncond})$

This formulation is used by the [Imagen Paper](https://arxiv.org/pdf/2205.11487.pdf), Equation (2):

<img width="542" alt="image" src="https://github.com/huggingface/diffusers/assets/17034772/49d01482-2168-488d-be2d-4d99b2faa3a4">

This is also used in the original [Stable Diffusion source](https://github.com/CompVis/latent-diffusion/blob/a506df5756472e2ebaf9078affdde2c4f1502cd4/ldm/models/diffusion/ddim.py#L177) and here in `diffusers`.

---

Comparing the equations side by side, it's clear that the original version puts more wright towards the conditioning.

Interestingly enough, I noticed this while reading the [LCM paper](https://arxiv.org/pdf/2310.04378.pdf) and in the paper the authors use formulation 1. However in [the official source code](https://github.com/luosiallen/latent-consistency-model) they use `diffusers`, which in turn implies formulation 2.

**Comment by jonatanklosko** [comment]
An additional perspective is that for $w > 1$ it's really $w^{(1)} = w^{(2)} - 1$. Which means that setting a particular guidance scale has less effect that originally expected, but since that's a hand-picked parameter it doesn't matter in a way.

**Comment by jonatanklosko** [comment]
Ah, I've just realised that LCM has it's own pipeline and there is a comment exactly referring to the above:

https://github.com/huggingface/diffusers/blob/325f6c53edf10a7b3f4804d4b38e89f95873d3c2/src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_text2img.py#L776-L780

**Comment by patrickvonplaten** [comment]
Yeah, I fully agree with your reasoning here @jonatanklosko! Sadly there are two definitions flying around and we early on decided to go with the one from the imagen paper. The original definition from the CFG paper is probably a bit better, but it's not really possible to change now
