### ISSUE TITLE
[IP-Adapter] support face model

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#5886]
We recently added IP-adapter support to many of our pipelines in diffusers! You can now very easily load your IP-Adapter into a diffusers pipeline with `pipe.load_ip_adapter(...)`; 

However right now we do not support [`IPAdapterFull`](https://github.com/tencent-ailab/IP-Adapter/blob/e317f750e1829e846c944b9fdd7a2f2842c46501/ip_adapter/ip_adapter.py#L314) model checkpoints. Anyone interested to add that support for this? It will allow us to use the very cool face models with diffusers! 

the goal would be to make [this example](https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter-full-face_demo.ipynb) work with diffusers API. e.g.
```python
from diffusers import StableDiffusionPipeline
import torch
from diffusers.utils import load_image

base_model_path = "dreamlike-art/dreamlike-anime-1.0/"
pipeline = StableDiffusionPipeline.from_pretrained(
    base_model_path, torch_dtype=torch.float16)
pipeline.to("cuda")

image = load_image("https://huggingface.co/datasets/YiYiXu/testing-images/resolve/main/ai_face2.png")

pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="models", weight_name="ip-adapter-full-face_sd15.bin")
pipeline.set_ip_adapter_scale(0.6)
generator = torch.Generator(device="cpu").manual_seed(33)
images = pipeline(
    prompt="A photo of a girl wearing a black dress, holding red roses in hand, upper body, behind is the Eiffel Tower",
    ip_adapter_image=image,
    negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality", 
    num_inference_steps=50,
    generator=generator,
).images
images[0]
```

 You will need to look into [this PR](https://github.com/huggingface/diffusers/pull/5713/files#diff-272077719e5ba4349d4f0ee80bdc959ef954934af1df782deac4d297e359c08a) to understand how `load_ip_adapter` works and then make it work for [`IPAdapterFull`](https://github.com/tencent-ailab/IP-Adapter/blob/e317f750e1829e846c944b9fdd7a2f2842c46501/ip_adapter/ip_adapter.py#L314) model from the original repo.

**Comment by hackpk** [comment]
@yiyixuxu Can I work on this?

**Comment by yiyixuxu** [comment]
@hackpk sure!

**Comment by noobjam** [comment]
@yiyixuxu Can i get started on this?

**Comment by fabiorigano** [comment]
@yiyixuxu @hackpk do you mind if I try it too?

**Comment by hackpk** [comment]
@fabiorigano You must be an experienced ML developer as you have already added the PR. I've just started ML Learning. In This case, I will unassign myself from this Issue But Can you please explain the code? where did proj.0weight come from? I thought I needed an extra parameter to know if it is IPadapter or IpadapterFull? It would be a great help if you can provide some learning resources. Also what about the Resample, the original code is doing some resampling, if you could explain that to me it would again help me understand things a little bit more. Thanks

**Comment by fabiorigano** [comment]
> @fabiorigano You must be an experienced ML developer as you have already added the PR. I've just started ML Learning. In This case, I will unassign myself from this Issue But Can you please explain the code? where did proj.0weight come from? I thought I needed an extra parameter to know if it is IPadapter or IpadapterFull? It would be a great help if you can provide some learning resources. Also what about the Resample, the original code is doing some resampling, if you could explain that to me it would again help me understand things a little bit more. Thanks

Hi @hackpk, I am not that experienced actually, I started to develop this feature yesterday and only commented today :) 

About your questions:
- IPAdapter is only using a fully connected layer as projection (ImageProjection), the keys in the state_dict are proj.weight and proj.bias
- IPAdatpterFull is using a multi layer perceptron (MLPProjection), the keys in the state_dict are proj.0.weight, proj.0.bias, proj.2.weight, proj.2.bias, proj.3.weight, proj.3.bias (you can find them by inspecting the dictionary), that are weights and bias for the two fully connected layers and the final layernorm.

Resampler is not used by IPAdapterFull, because IPAdapterFull uses MLPProjection (init_proj method is overridden).

**Comment by hackpk** [comment]
@fabiorigano Thanks for the detailed explanation i do understand some things now I will inspect for more.

**Comment by jenniferzxm** [comment]
@yiyixuxu I am interested in working on this issue and I am wondering if there is any more work that I can potentially contribute to?

**Comment by yiyixuxu** [comment]
@jenniferzxm I think the only remaining one is kandinsky + ip-adapter - interested? https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter_t2i_demo.ipynb

**Comment by jenniferzxm** [comment]
> @jenniferzxm I think the only remaining one is kandinsky + ip-adapter - interested? https://github.com/tencent-ailab/IP-Adapter/blob/main/ip_adapter_t2i_demo.ipynb

I will look more into it and reply asap.

**Comment by iibrahimli** [comment]
@yiyixuxu Looking forward to IPAdapter support! It seems like there are multiple contributors eager to work on this, is there an expected timeline for this? I would be interested to contribute but do not want to duplicate efforts 🤗

**Comment by yiyixuxu** [comment]
we have two open PR on this already - aim to merge both this week :)
