### ISSUE TITLE
Inference on train_text_to_image.py produces warning Token indices sequence length is longer than the specified maximum sequence length for this model 

### ISSUE THREAD

**Issue by bhosalems** [huggingface/diffusers#5890]
### Describe the bug

How to resolve the below error,

Token indices sequence length is longer than the specified maximum sequence length for this model (82 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['cartilaginous support']

### Reproduction

Run the inference on the saved model of the Stable diffusion pipeline to convert text to image with more than 77 tokens.

### System Info

_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   2.0.0                    pypi_0    pypi
accelerate                0.24.0                   pypi_0    pypi
aiohttp                   3.8.6                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asttokens                 2.4.0              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
bitsandbytes              0.41.1                   pypi_0    pypi
blas                      1.0                         mkl
blessings                 1.7             py39h06a4308_1002
brotli-python             1.0.9            py39h6a678d5_7
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cachetools                5.3.2                    pypi_0    pypi
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h5eee18b_3
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.7           unix_pyh707e725_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
cryptography              41.0.3           py39hdda0065_0
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
datasets                  2.14.6                   pypi_0    pypi
debugpy                   1.8.0            py39h3d6467e_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
diffusers                 0.22.0.dev0              pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
docker-pycreds            0.4.0                      py_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.12.4                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.10.0                pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
giflib                    5.2.1                h5eee18b_3
gitdb                     4.0.11             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.40             pyhd8ed1ab_0    conda-forge
gmp                       6.2.1                h295c915_3
gnutls                    3.6.15               he1e5248_0
google-auth               2.23.3                   pypi_0    pypi
google-auth-oauthlib      1.1.0                    pypi_0    pypi
gpustat                   0.6.0              pyhd3eb1b0_1
grpcio                    1.59.0                   pypi_0    pypi
huggingface-hub           0.17.3                   pypi_0    pypi
idna                      3.4              py39h06a4308_0
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
intel-openmp              2023.1.0         hdb19cb5_46305
ipykernel                 6.26.0             pyhf8b6a83_0    conda-forge
ipython                   8.16.1             pyh0d859eb_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1
jupyter_client            8.5.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.12.0           py39hf3d152e_0    conda-forge
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.8.0.34                      0    nvidia
libcurand                 10.3.4.52                     0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h5eee18b_1
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgfortran-ng            13.2.0               h69a702a_2    conda-forge
libgfortran5              13.2.0               ha4646dd_2    conda-forge
libiconv                  1.16                 h7f8727e_2
libidn2                   2.3.4                h5eee18b_0
libnpp                    11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libpng                    1.6.39               h5eee18b_0
libprotobuf               3.20.3               he621ea3_0
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libtasn1                  4.19.0               h5eee18b_0
libtiff                   4.5.1                h6a678d5_0
libunistring              0.9.10               h27cfd23_0
libwebp                   1.3.2                h11a3e52_0
libwebp-base              1.3.2                h5eee18b_0
lightning-utilities       0.9.0              pyhd8ed1ab_0    conda-forge
llvm-openmp               14.0.6               h9e868ea_0
lz4-c                     1.9.4                h6a678d5_0
markdown                  3.5                      pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mkl                       2023.1.0         h213fc3f_46343
mkl-service               2.4.0            py39h5eee18b_1
mkl_fft                   1.3.8            py39h5eee18b_0
mkl_random                1.2.4            py39hdb19cb5_0
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.15                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
nettle                    3.7.3                hbbd107a_1
numpy                     1.26.0           py39h5f9d8c6_0
numpy-base                1.26.0           py39hb5e798b_0
nvidia-ml                 7.352.0            pyhd3eb1b0_0
oauthlib                  3.2.2                    pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openjpeg                  2.4.0                h3ad879b_0
openssl                   3.1.4                hd590300_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.1                    pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.0.1           py39ha6cbd5a_0
pip                       23.3             py39h06a4308_0
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
protobuf                  4.23.4                   pypi_0    pypi
psutil                    5.9.6                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   13.0.0                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0           py39h06a4308_0
pysocks                   1.7.1            py39h06a4308_0
python                    3.9.18               h955ad1f_0
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.13.1          py3.9_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.1           py39h8c080ef_2    conda-forge
readline                  8.2                  h5eee18b_0
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0           py39h06a4308_0
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.4.0                    pypi_0    pypi
scipy                     1.11.3           py39h5f9d8c6_0
sentry-sdk                1.32.0             pyhd8ed1ab_0    conda-forge
setproctitle              1.1.10          py39h3811e60_1004    conda-forge
setuptools                68.0.0           py39h06a4308_0
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.41.2               h5eee18b_0
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tbb                       2021.8.0             hdb19cb5_0
tensorboard               2.15.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tokenizers                0.14.1                   pypi_0    pypi
torch-fidelity            0.3.0                    pypi_0    pypi
torchaudio                0.13.1               py39_cu117    pytorch
torchmetrics              1.2.0              pyhd8ed1ab_0    conda-forge
torchtriton               2.1.0                      py39    pytorch
torchvision               0.14.1               py39_cu117    pytorch
tornado                   6.3.3            py39hd1e30aa_1    conda-forge
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.12.0             pyhd8ed1ab_0    conda-forge
transformers              4.34.1                   pypi_0    pypi
typing_extensions         4.7.1            py39h06a4308_0
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.18          py39h06a4308_0
wandb                     0.15.12            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.8              pyhd8ed1ab_0    conda-forge
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2           py39h06a4308_0
xformers                  0.0.22.post7    py39_cu11.7.1_pyt1.13.1    xformers
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.9.2                    pypi_0    pypi
zeromq                    4.3.5                h59595ed_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h5eee18b_0
zstd                      1.5.5                hc292b87_0

**Comment by bhosalems** [comment]
Below is the relevant code for the inference. I have tried initializing the pipeline manually with the tokenizer, but it still does not work. 
```
 tokenizer = CLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer")
    pipeline = StableDiffusionPipeline.from_pretrained(args.pretrained_model_name_or_path, 
                                                   torch_dtype=torch.float16, tokenizer=tokenizer)
    pipeline.safety_checker = None
    pipeline.requires_safety_checker = False
    device = torch.device(f'cuda:{args.device}')
    pipeline = pipeline.to(device)
    pipeline.set_progress_bar_config(disable=True)

    if args.enable_xformers_memory_efficient_attention:
        pipeline.enable_xformers_memory_efficient_attention()

    if args.seed is None:
        generator = None
    else:
        generator = torch.Generator(device=args.device).manual_seed(args.seed)
    for i in tqdm(range(len(val_dataset)), desc="Runing inference"):
        prompt = val_dataset[i]['text']
        with torch.autocast("cuda"):
            image = pipeline(prompt, num_inference_steps=args.num_val_inference, generator=generator).images[0]
```

**Comment by sayakpaul** [comment]
1. The code is not fully reproducible. 
2. When the token length exceeds 77, we'll just discard the extra part: 

https://github.com/huggingface/diffusers/blob/67d070749ae393a234470b6ef653821bb4f02cc6/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L391

**Comment by bhosalems** [comment]
Is there any way to take care of extra tokens rather than just ignore anything after 77?

**Comment by sayakpaul** [comment]
You can refer to the "Extending the Stable Diffusion Token Limit by 3x" section of this blog:
https://blog.novelai.net/novelai-improvements-on-stable-diffusion-e10d38db82ac

Going forward, let's try to ask these questions on our [Discord forum](https://hf.co/join/discord) rather than opening an issue that doesn't really talk about an issue within the library.
