### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by power9799** [huggingface/diffusers#5892]
### Describe the bug

Getting import error while adding activation function

### Reproduction

ImportError Traceback (most recent call last)
[( in <cell line: 33>()
31 from torch import nn
32 get_ipython().system('pip install python-utils')
---> 33 from ..utils import USE_PEFT_BACKEND
34 from .lora import LoRACompatibleLinear
35

### System Info

Diffuser , google colab

**Comment by ShashwatNigam99** [comment]
Could you provide the colab link as well? Most likely you haven't installed/imported the peft library

**Comment by power9799** [comment]
> Could you provide the colab link as well? Most likely you haven't installed/imported the peft library

I installed the wrong thing, the upgraded diffuser instead of pip diffusers  I think. Now it is running.
