### ISSUE TITLE
Typo in noise level formula in Karras scheduler

### ISSUE THREAD

**Issue by sgrigory** [huggingface/diffusers#590]
### Describe the bug

Comparing the formula for noise levels in `KarrasVeScheduler` 

https://github.com/huggingface/diffusers/blob/a45dca077c636cd60199bab888da4ecfcc206d18/src/diffusers/schedulers/scheduling_karras_ve.py#L107-L113

with [Karras, Tero, et al.](https://arxiv.org/abs/2206.00364) (VE column of Table 1), it seems to me that there is `**2` missing, and the correct formula should be

```python
self.schedule = [
            (
                self.config.sigma_max**2
                * (self.config.sigma_min**2 / self.config.sigma_max**2) ** (i / (num_inference_steps - 1))
            )
            for i in self.timesteps
        ]
```

This way the noise indeed ranges from `sigma_min` to `sigma_max`, as the docstring says.

Please let me know if I'm misunderstanding something here

This actually affects the generated images: they become less grainy and oversaturated after this is fixed

### System Info

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.14
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Huggingface_hub version: 0.9.1
- Transformers version: 4.22.1
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by natolambert** [comment]
Hi @sgrigory - great catch! This scheduler isn't used in any big spaces / demos yet, so do you want to make a PR to change this? If not, I can easily do so (there may need to be a couple updated tests too) 🤗

**Comment by sgrigory** [comment]
@natolambert - thanks, sure, here is the PR: https://github.com/huggingface/diffusers/pull/627 . I've fixed one affected test I found, please let me know if you see any others which need adjustments
