### ISSUE TITLE
How to set config in VaeImageProcessor?

### ISSUE THREAD

**Issue by youyuge34** [huggingface/diffusers#5912]
I created a `StableDiffusionControlNetImg2ImgPipeline` and I want to manually set the config `do_normalize` in `VaeImageProcessor`. I wonder how can I set? I look for it in the pipe.vae.config and see nothing about it.

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/diffusers/blob/07eac4d65a8ec67e7ae971da4431f67095e9db8a/src/diffusers/image_processor.py#L67

You can do:

```py
self.image_processor.register_to_config(do_normalize=True)
```
