### ISSUE TITLE
Kandinsky 3.0

### ISSUE THREAD

**Issue by trouble-maker007** [huggingface/diffusers#5926]
### Model/Pipeline/Scheduler description

Kandinsky 3.0 is an open-source text-to-image diffusion model built upon the Kandinsky2-x model family.

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

github:https://github.com/ai-forever/Kandinsky-3
model weights:https://huggingface.co/kandinsky-community/kandinsky-3

**Comment by shauray8** [comment]
#5913
