### ISSUE TITLE
[doc] add a doc page for kandinsky 3.0! 

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#5936]
we recently added kandinsky 3.0 to diffusers https://github.com/huggingface/diffusers/pull/5913

one of the to-do remaining is to add a doc page for kandinsky 3.0. 
Anyone up to it?

 
current dog page: https://huggingface.co/docs/diffusers/main/en/api/pipelines/kandinsky3#kandinsky-3

info about the model:
github:https://github.com/ai-forever/Kandinsky-3
model weights:https://huggingface.co/kandinsky-community/kandinsky-3
blogpost: https://habr.com/ru/companies/sberbank/articles/775590/

**Comment by charchit7** [comment]
Hi @yiyixuxu added here : #5937 :) please let me know if changes required.
