### ISSUE TITLE
Follow The Policy Objective of Diffusion-DPO

### ISSUE THREAD

**Issue by 1073521013** [huggingface/diffusers#5947]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

**Describe the solution you'd like.**

**Describe alternatives you've considered.**

**Additional context.**

**Comment by sayakpaul** [comment]
It will reside in `huggingface/trl`:

https://github.com/huggingface/trl

Cc: @lvwerra @kashif
