### ISSUE TITLE
Make LoRACompatibleConv padding_mode work

### ISSUE THREAD

**Issue by jinghuan-Chen** [huggingface/diffusers#5957]
**Is your feature request related to a problem? Please describe.**
Due to #4315 ,the forward method is implemented in https://github.com/huggingface/diffusers/blob/50a749e90990932d49556ee54a333278559722f3/src/diffusers/models/lora.py#L354-L365
If you modify the padding mode of LoRACompatibleConv to achieve some other effects, such as padding_mode="circular" to generate a seamless panorama, the existing implementation method will not work.

**Describe the solution you'd like.**
I recommend following the forward implementation of pytorch Conv2d, so that users can modify the padding mode and it will be reflected.https://github.com/pytorch/pytorch/blob/00412e6dfacdec5a8508c841b3ea0846388dc872/torch/nn/modules/conv.py#L452-L457

**Describe alternatives you've considered.**
The existing implementation also calls the function of F.conv2d, so the modification cost is low.

**Comment by sayakpaul** [comment]
Not stale.

**Comment by sayakpaul** [comment]
Not stale.
