### ISSUE TITLE
clip-guided stable diffusion correctness

### ISSUE THREAD

**Issue by keturn** [huggingface/diffusers#596]
### Describe the bug

the clip-guided pipeline uses these text-embeddings:

https://github.com/huggingface/diffusers/blob/2345481c0e21f1bd84c0d85b866b57d34506d836/examples/community/clip_guided_stable_diffusion.py#L285-L288

defined earlier as:

https://github.com/huggingface/diffusers/blob/2345481c0e21f1bd84c0d85b866b57d34506d836/examples/community/clip_guided_stable_diffusion.py#L234-L237

which I read as using the _unconditioned_ (i.e. null prompt) embeddings.

Is that the way it's supposed to work? That doesn't feel like how it's supposed to work. Like, if the normal classifier-free guidance function is turned off, it would be using the embeddings from the text prompt, not the nulls.

But this pipeline was added without any tests or samples or other reference material, so I really don't know.

### System Info

👀

**Comment by patrickvonplaten** [comment]
cc @patil-suraj might be good to take a look soon since we just released it :-)

**Comment by ajundo** [comment]
Using the predicted x_0 for CLIP is reasonable, feeding x_{t-1} makes no sense. x_{t-1} have no semantic information and the gradient is kind of noise.

**Comment by patil-suraj** [comment]
That's a great catch @keturn ! Sorry to come back to this only now, will send a fix right away.

**Comment by patil-suraj** [comment]
Also updated the colab notebook https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/CLIP_Guided_Stable_diffusion_with_diffusers.ipynb#scrollTo=-bzXx-2EhlQY

**Comment by ajundo** [comment]
> Someone posted another concern on [discord](https://discord.com/channels/879548962464493619/1009713274113245215/1022866292065173534):
> 
> > I think there's a bug in the community CLIP guidance example - https://github.com/huggingface/diffusers/blob/8211b622270e4d010a88e5f33573f5ce3869df6a/examples/community/clip_guided_stable_diffusion.py#L132-L135
> > 
> > IIUC the correct behavior would be to use pred_original_sample to do the CLIP comparison - i.e. it should be the sample, not pred_original_sample * (fac) + latents * (1 - fac)

Afaik, this is correct because the conditional diffusion is conditional on predicted x_t rather than predicted x_0。

**Comment by zzhang2816** [comment]
I think the correct format is "sample = pred_original_sample * (fac) + noise_pred * (1 - fac)"
<img width="863" alt="Screenshot 2023-04-11 at 15 33 21" src="https://user-images.githubusercontent.com/77660497/231281768-f04152f4-0386-4c93-94dd-6eeebf701f01.png">
