### ISSUE TITLE
ControlNET SDXL train - RuntimeWarning: invalid value encountered in cast images = (images * 255).round().astype("uint8")

### ISSUE THREAD

**Issue by alelordelo** [huggingface/diffusers#5960]
### Describe the bug

When running the train_controlnet_sdxl.py
https://github.com/huggingface/diffusers/blob/main/examples/controlnet/README_sdxl.md

With:
-  Runpod Jupyter Notrebooks on an A100 GPU
- Same settings as tutorial, and a custom dataset with exact same structure of tutorial I get this:
/workspace/src/diffusers/image_processor.py:88: RuntimeWarning: invalid value encountered in cast
images = (images * 255).round().astype("uint8")

And WanDB shows black images as outputs

### Reproduction

Run train_controlnet_sdxl.py 

### Logs

```shell
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
11/28/2023 10:28:14 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'variance_type', 'dynamic_thresholding_ratio', 'thresholding', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
{'dropout', 'attention_type', 'reverse_transformer_layers_per_block'} was not found in config. Values will be initialized to default values.
11/28/2023 10:28:22 - INFO - __main__ - Initializing controlnet weights from unet
Map: 100%|██████████████████████████| 3766/3766 [00:09<00:00, 387.27 examples/s]

11/28/2023 10:28:48 - INFO - __main__ - ***** Running training *****
11/28/2023 10:28:48 - INFO - __main__ -   Num examples = 3766
11/28/2023 10:28:48 - INFO - __main__ -   Num batches each epoch = 3766
11/28/2023 10:28:48 - INFO - __main__ -   Num Epochs = 16
11/28/2023 10:28:48 - INFO - __main__ -   Instantaneous batch size per device = 1
11/28/2023 10:28:48 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4
11/28/2023 10:28:48 - INFO - __main__ -   Gradient Accumulation steps = 4
11/28/2023 10:28:48 - INFO - __main__ -   Total optimization steps = 15000
Steps:   1%|        | 100/15000 [03:34<8:53:03,  2.15s/it, loss=0.0138, lr=1e-5]11/28/2023 10:32:22 - INFO - __main__ - Running validation... 
{'controlnet', 'feature_extractor', 'image_encoder'} was not found in config. Values will be initialized to default values.

Loading pipeline components...:   0%|                     | 0/7 [00:00<?, ?it/s]Loaded text_encoder as CLIPTextModel from `text_encoder` subfolder of stabilityai/stable-diffusion-xl-base-1.0.

Loading pipeline components...:  14%|█▊           | 1/7 [00:00<00:01,  3.82it/s]Loaded tokenizer_2 as CLIPTokenizer from `tokenizer_2` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loaded scheduler as EulerDiscreteScheduler from `scheduler` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loaded tokenizer as CLIPTokenizer from `tokenizer` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loaded text_encoder_2 as CLIPTextModelWithProjection from `text_encoder_2` subfolder of stabilityai/stable-diffusion-xl-base-1.0.

Loading pipeline components...: 100%|█████████████| 7/7 [00:01<00:00,  6.88it/s]
{'lower_order_final', 'disable_corrector', 'solver_order', 'dynamic_thresholding_ratio', 'predict_x0', 'thresholding', 'solver_type', 'solver_p'} was not found in config. Values will be initialized to default values.
/workspace/DatasetNormalsStabilityCrop/diffusers/src/diffusers/image_processor.py:88: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")
Steps:   1%|         | 200/15000 [07:48<8:58:44,  2.18s/it, loss=0.136, lr=1e-5]11/28/2023 10:36:36 - INFO - __main__ - Running validation... 
{'controlnet', 'feature_extractor', 'image_encoder'} was not found in config. Values will be initialized to default values.

Loading pipeline components...:   0%|                     | 0/7 [00:00<?, ?it/s]Loaded text_encoder as CLIPTextModel from `text_encoder` subfolder of stabilityai/stable-diffusion-xl-base-1.0.

Loading pipeline components...:  14%|█▊           | 1/7 [00:00<00:01,  3.94it/s]Loaded tokenizer_2 as CLIPTokenizer from `tokenizer_2` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loaded scheduler as EulerDiscreteScheduler from `scheduler` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loaded tokenizer as CLIPTokenizer from `tokenizer` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loaded text_encoder_2 as CLIPTextModelWithProjection from `text_encoder_2` subfolder of stabilityai/stable-diffusion-xl-base-1.0.

Loading pipeline components...: 100%|█████████████| 7/7 [00:01<00:00,  6.77it/s]
{'lower_order_final', 'disable_corrector', 'solver_order', 'dynamic_thresholding_ratio', 'predict_x0', 'thresholding', 'solver_type', 'solver_p'} was not found in config. Values will be initialized to default values.
Steps:   2%|▏        | 300/15000 [12:01<8:52:50,  2.17s/it, loss=0.154, lr=1e-5]11/28/2023 10:40:49 - INFO - __main__ - Running validation... 
{'controlnet', 'feature_extractor', 'image_encoder'} was not found in config. Values will be initialized to default values.

Loading pipeline components...:   0%|                     | 0/7 [00:00<?, ?it/s]Loaded text_encoder as CLIPTextModel from `text_encoder` subfolder of stabilityai/stable-diffusion-xl-base-1.0.

Loading pipeline components...:  14%|█▊           | 1/7 [00:00<00:01,  3.88it/s]Loaded tokenizer_2 as CLIPTokenizer from `tokenizer_2` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loaded scheduler as EulerDiscreteScheduler from `scheduler` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loaded tokenizer as CLIPTokenizer from `tokenizer` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loaded text_encoder_2 as CLIPTextModelWithProjection from `text_encoder_2` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
```

### System Info

diffusers 0.24.0.dev0

Requirement already satisfied: importlib-metadata in /usr/lib/python3/dist-packages (from diffusers==0.24.0.dev0) (4.6.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from diffusers==0.24.0.dev0) (3.9.0)
Requirement already satisfied: huggingface-hub>=0.19.4 in /usr/local/lib/python3.10/dist-packages (from diffusers==0.24.0.dev0) (0.19.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from diffusers==0.24.0.dev0) (1.24.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from diffusers==0.24.0.dev0) (2023.10.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from diffusers==0.24.0.dev0) (2.31.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from diffusers==0.24.0.dev0) (0.4.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from diffusers==0.24.0.dev0) (9.3.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.4->diffusers==0.24.0.dev0) (2023.10.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.4->diffusers==0.24.0.dev0) (4.66.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.4->diffusers==0.24.0.dev0) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.4->diffusers==0.24.0.dev0) (4.4.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.19.4->diffusers==0.24.0.dev0) (23.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.24.0.dev0) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.24.0.dev0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.24.0.dev0) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.24.0.dev0) (2022.12.7)

### Who can help?

@sayakpaul @yiyixuxu @DN6 @patrickvonplaten

**Comment by sayakpaul** [comment]
Are you using a numerically stable VAE?

https://github.com/huggingface/diffusers/blob/main/examples/controlnet/README_sdxl.md#specifying-a-better-vae
