### ISSUE TITLE
ControlNet for Stable Diffusion 2.1

### ISSUE THREAD

**Issue by jdp8** [huggingface/diffusers#5966]
**Is your feature request related to a problem? Please describe.**
I tried to use the `scripts/convert_stable_diffusion_controlnet_to_onnx.py` script to convert [thibaud's Canny ControlNet for SD 2.1](https://huggingface.co/thibaud/controlnet-sd21-canny-diffusers) to ONNX format but it did not work, specifically a segmentation fault occurred. The command I used was `python scripts/convert_stable_diffusion_controlnet_to_onnx.py --model_path "stabilityai/stable-diffusion-2-1" --controlnet_path "thibaud/controlnet-sd21-canny-diffusers" --output_path "models/sd21-canny" --opset 17 --fp16`

**Describe the solution you'd like.**
It would be great if the conversion of ControlNet for SD 2.1 to ONNX format was possible. Perhaps some changes in the same script to account for this version of ControlNet.

**Describe alternatives you've considered.**
I have not tried anything else to convert this ControlNet to ONNX but for now I am using ControlNet 1.0 and 1.1 with SD 1.5 and it's enough but it would be great to have ControlNet for SD 2.1.

**Additional context.**
N/A.

**Comment by sayakpaul** [comment]
Maybe attach some logs in the message as well regarding the failure. Cc: @echarlaix

**Comment by jdp8** [comment]
Ok, I'll add the error message that appears when running the command that I mentioned.

![image](https://github.com/huggingface/diffusers/assets/68886123/a01154cb-c169-49de-9794-f3f34bc23445)
