### ISSUE TITLE
Text2Video and/or Img2Video Conversion Script to ONNX

### ISSUE THREAD

**Issue by jdp8** [huggingface/diffusers#5968]
**Is your feature request related to a problem? Please describe.**
Not sure if I'm getting ahead of myself since some of the models that I will mention are new but I am not able to convert certain Text2Video or Img2Video models from Diffusers format to ONNX format. Some of the models are:

1. Text2Video
    - [damo-vilab/text-to-video-ms-1.7b](https://huggingface.co/damo-vilab/text-to-video-ms-1.7b)
    - [cerspense/zeroscope_v2_576w](https://huggingface.co/cerspense/zeroscope_v2_576w)
2. Img2Video
    - [stabilityai/stable-video-diffusion-img2vid](https://huggingface.co/stabilityai/stable-video-diffusion-img2vid)

**Describe the solution you'd like.**
A script that can convert Text2Video or Img2Video models from Diffusers format to ONNX format.

**Describe alternatives you've considered.**
I tried using the `scripts/convert_stable_diffusion_checkpoint_to_onnx.py` script to see if that would work by any chance but it did not.

**Additional context.**
N/A.

**Comment by sayakpaul** [comment]
Cc: @echarlaix
