### ISSUE TITLE
train_unconditional.py fails on call to evaluate()

### ISSUE THREAD

**Issue by jdk514** [huggingface/diffusers#597]
### Describe the bug

On the first attempt to call `evaluate()` in the train_loop() function, the DDPMPipeline fails due to an incompatible output form the model.

This raises an AttributeError: 'dict' object has no attribute 'shape'

![image](https://user-images.githubusercontent.com/3916001/191408604-a4335643-6fb3-439e-adaa-b5d4189bcc71.png)

### Reproduction

Currently encountered when running the collab notebook unaltered.

### Logs

```shell
Logs included in bug description.
```

### System Info

Google Collab Notebook found at https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/training_example.ipynb

**Comment by umarfm** [comment]
@anton-l @jdk514 did any of you manage to run it with:

!pip install git+https://github.com/huggingface/diffusers.git

It still shows the same error to me:

AttributeError: 'dict' object has no attribute 'shape'

PS: I am running it for only 5 epochs!

**Comment by omer-dor** [comment]
> @anton-l @jdk514 did any of you manage to run it with:
> 
> !pip install git+https://github.com/huggingface/diffusers.git
> 
> It now shows this to me:
> 
> AttributeError: 'ImagePipelineOutput' object has no attribute 'sample'

In evaluate function, this worked for me:
I changed .sample
![image](https://user-images.githubusercontent.com/84913922/194534755-832c188e-8b79-4070-94c9-83c925b9631f.png)

to .images

![image](https://user-images.githubusercontent.com/84913922/194534890-82dad4b2-daa0-4a2d-9675-9b3e237a31e2.png)

**Comment by LuisGalvezCarrasco** [comment]
Hi, I replaced **!pip install diffusers[training]=0.3.0** for **!pip install git+https://github.com/huggingface/diffusers.git**, but I'm getting the following error:

![Screenshot from 2022-10-16 01-40-28](https://user-images.githubusercontent.com/65005615/196018521-5d3acba9-0d7d-438a-b917-39324f3530ba.png)

It is the original notebook , I did not modify anything more than the line I mentioned.

It is worth mentioning that a few days ago I did the same procedure and it did not throw me this error.

**Comment by LuisGalvezCarrasco** [comment]
I'm going to help myself :), after some thought I realized that omitting the second argument **tensor_format="pt"** works fine.

I was afraid something would go wrong but it works fine, the training was successful and the generated images are consistent.

**Comment by anton-l** [comment]
@LuisGalvezCarrasco indeed, `tensor_format` has been deprecated in the latest version :) 
Updated the training notebook to `diffusers==0.5.1`: https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/training_example.ipynb
