### ISSUE TITLE
`Min-SNR weighting` in Training controlnet document (main branch)

### ISSUE THREAD

**Issue by GoGiants1** [huggingface/diffusers#5972]
### Describe the bug

Hello! I'm a user who recently discovered `diffusers` and I'm enjoying learning about it.

I noticed that in the main branch documentation, there is a section on `Training > ControlNet`  that introduces the [min snr weighting](https://huggingface.co/docs/diffusers/main/en/training/controlnet#min-snr-weighting), but this argument is not implemented in `training_controlnet.py`.

It would be nice if could either remove this part from the documentation or implement this feature in the controlnet as well.

Thank you.

### Reproduction

```bash
accelerate launch train_controlnet.py \
    --pretrained_model_name_or_path=$BASE_MODEL_DIR \
    --controlnet_model_name_or_path=$CONTROLNET_MODEL_DIR \
    --output_dir=$OUTPUT_DIR \
    --dataset_name=$DATASET_NAME \
    --resolution=512 \
    --learning_rate=1e-5 \
    --validation_image "./conditioning-1.png" "./conditioning-2.png" "./conditioning-3.png" \
    --validation_prompt  "$VAL_PROMPT_1" "$VAL_PROMPT_2" "$VAL_PROMPT_3" \
    --train_batch_size=1 \
    --gradient_accumulation_steps=4 \
    --gradient_checkpointing \
    --use_8bit_adam \
    --push_to_hub \
    --hub_model_id="***/ControlNet_Canny_Retrain11K" \
    --report_to="wandb" \
    --hub_token=$HF_TOKEN \
    --checkpointing_steps=5000 \
    --snr_gamma=5.0

```

### System Info

- `diffusers` version: 0.24.0.dev0
- Platform: Linux-5.15.0-1015-aws-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.30.2
- Accelerate version: 0.23.0
- xFormers version: 0.0.21
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by sayakpaul** [comment]
Would you like to open a PR for it? :)

**Comment by GoGiants1** [comment]
@sayakpaul Sure! Is `min snr weighting` work for controlnet's training?

**Comment by bghira** [comment]
it works, you just need to look at the existing implementations first
