### ISSUE TITLE
use multi subject dreambooth for inpainting models

### ISSUE THREAD

**Issue by hosnasn1987** [huggingface/diffusers#5973]
Hi @kopsahlong

i want to use your script for inpainting model

i can use this script(examples/research_projects/dreambooth_inpaint) for defining one subject for model, but i want to define many objects and fine tune inpainting model by them. 

can you help me?

**Comment by sayakpaul** [comment]
Might be easier for you to contact the author via email. Issue threads are for bugs, feature requests, etc. Hence I am gonna close this.
