### ISSUE TITLE
Support IP Adapter for AnimateDiffPipeline

### ISSUE THREAD

**Issue by vladmandic** [huggingface/diffusers#5976]
Like title says, request is to support newly IP adapter (via PR #5713) for existing AnimateDiffPipeline
as AnimateDiff would greatly benefit from style stabilization brought by IP adapter

CC @yiyixuxu @DN6 @sayakpaul @patrickvonplaten

**Comment by DN6** [comment]
@yiyixuxu I believe you were already working on this right?

**Comment by yiyixuxu** [comment]
yep yep @sayakpaul  is here to prove 
![animation (1)](https://github.com/huggingface/diffusers/assets/12631849/9e33c995-5cc4-45a1-9514-6f086d30775b)

**Comment by yiyixuxu** [comment]
face model will be supported soon I think will works better for animatediff

**Comment by yiyixuxu** [comment]
@vladmandic 

we haven't done any comms about it and I guess very easy to miss in our doc but here it is 
https://huggingface.co/docs/diffusers/main/en/using-diffusers/loading_adapters?model=AnimateDiff

**Comment by vladmandic** [comment]
right :)
i used diffusers from main branch from two days ago and `AnimateDiffPipeline` did not have `load_ip_adapter` method.
just checked out latest diffusers main and it works fine! thanks!

**Comment by sayakpaul** [comment]
Thanks for checking! If you have a cool example to share with us, that would be great!
