### ISSUE TITLE
Do not save `unet.unet` keys when training LoRAs

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#5977]
### Describe the bug

When training LoRAs, sometimes they end up with a `unet.unet` key like in this case https://huggingface.co/sayakpaul/new-lora-check-v15/blob/main/pytorch_lora_weights.safetensors5/tree/main
```
unet.unet.up_blocks.1.attentions.2.transformer_blocks.1.attn2.processor.to_v_lora.up.weight
```

While loading up this format [is supported on diffusers](https://github.com/huggingface/diffusers/blob/5ae3c3a56b52094cd01d184da38255136d7715e7/src/diffusers/loaders/lora.py#L538), it is probably undesirable to have such keys and maybe better off deprecated and make sure all keys have a single `unet` prefix 

(Internal Slack thread: https://huggingface.slack.com/archives/C03UQJENJTV/p1701261840645189) 

### Reproduction

Training a LoRA with our example [notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb)/script yields the `unet.unet` output https://huggingface.co/LinoyTsaban/corgy_dog_LoRA

### System Info

diffusers==0.23.1

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
This should all go away with https://github.com/huggingface/diffusers/pull/5388.
