### ISSUE TITLE
PDAE  and Disdiff

### ISSUE THREAD

**Issue by YChienHung** [huggingface/diffusers#5978]
### Model/Pipeline/Scheduler description

There are two diffusion model with autoencoder，whose name are PDAE  and Disdiff.
If diffuser support PDAE quickly, it would be a good job.

### Open source status

- [X] The model implementation is available.
- [x] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/ckczzj/PDAE
https://github.com/ThomasMrY/DisDiff

**Comment by nileshkokane01** [comment]
@sayakpaul ,

I can try this,  do you know where I can take inspiration from, any pointers to starters will be helpful.

**Comment by YChienHung** [comment]
> @sayakpaul ,
> 
> I can try this, do you know where I can take inspiration from, any pointers to starters will be helpful.
> 
> P.S: I'm already going through the original implementation.

Thanks for your interest in this work. I have recurrented  the models without diffusers succinctly, if you have any questions, I would be happy to help you.

**Comment by sayakpaul** [comment]
Thanks for your interest. You can refer to https://huggingface.co/docs/diffusers/using-diffusers/contribute_pipeline to know more about how to contribute a custom pipeline.
