### ISSUE TITLE
INVALID_ARGUMENT : Got invalid dimensions for input: latent_model_input // Whenever I modify the prompt height and weight from 512x512

### ISSUE THREAD

**Issue by Stable777** [huggingface/diffusers#598]
Hi
I read the instruction mentioning changing the "create_onnx.py" file, but that one is nowhere to be found?
So I went ahead and modified save_onnyx.py aswell as dml_onny.py, is that correct?
Anyway, the error message I am facing is:
`File "C:\Users\...\Desktop\StableDif2\amd_venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: latent_model_input for the following indices
 index: 2 Got: 128 Expected: 64
 index: 3 Got: 128 Expected: 64
 Please fix either the inputs or the model.`

(Followed this tutorial by the way: https://www.youtube.com/watch?v=Lk2syPsVMQM)

**Comment by Stable777** [comment]
Solution:
Went  modifying dml_onnx AND save_onnx aswell!

**Comment by anton-l** [comment]
Hi @Stable777! Your issue doesn't seem to be related to the `huggingface/diffusers` repository, you'll need to ping @harishanand95 at https://github.com/harishanand95/diffusers :)

**Comment by harishanand95** [comment]
Hi @Stable777, Please follow this new approach if you face any further issues and report any issues in either https://github.com/harishanand95/diffusers or in the gist. Thanks! 
https://gist.github.com/harishanand95/75f4515e6187a6aa3261af6ac6f61269

**Comment by Stable777** [comment]
Thanks for the new method @harishanand95 , but it has the same problem, I can't make anything highter than 512x768.
