### ISSUE TITLE
Controlnet SDXL - generated models as ".pth" or  ".safetensors"?

### ISSUE THREAD

**Issue by alelordelo** [huggingface/diffusers#5980]
I am following the tutorial on:
https://github.com/huggingface/diffusers/blob/main/examples/controlnet/README_sdxl.md

After training, I located this under the checkpoints folder:
diffusion_pytorch_model.safetensors
config.json

I was expecting a ".pth" model like (as its common on WebUI ControlNET folder):
control_v11p_sd15_normalbae.pth

For inference, should I use the diffusion_pytorch_model.safetensors directly on WebUI ControlNET folder?

Who can help?

@sayakpaul @yiyixuxu @DN6 @patrickvonplaten

**Comment by sayakpaul** [comment]
Sorry, we cannot offer guidance beyond our library. 

But you can load the safetensors file and then serialize that using PyTorch in the native PyTorch format. 

Refer to the documentation here to know how to load the safetensors file:
https://huggingface.co/docs/safetensors/api/torch
