### ISSUE TITLE
fp16 variant causing system RAM issue on colab with train_dreambooth_lora_sdxl

### ISSUE THREAD

**Issue by jmaccall316** [huggingface/diffusers#5984]
### Describe the bug

This is kind of a weird one. When I try to specify the variant arg it downloads the right version but before the GPU can start running the System RAM craps out at 12.7 GB (max) and you get the dreaded kill signal (not even cuda out of memory error) 

Tried to diagnose what the problem was by changing some args... The only way I could get the GPU to start without the system RAM maxing out was by NOT specifying "variant"  at all.

### Reproduction

#!/usr/bin/env bash
!accelerate launch train_dreambooth_lora_sdxl.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --output_dir="/content/drive/MyDrive/lora-trained-xl-fp168bit" \
 --variant="fp16" \
  --instance_prompt="Photo of a TOK dog" \
  --resolution=1024 \
  --train_batch_size=2 \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-4 \
  --dataset_name="/content/in" \
  --train_text_encoder \
  --gradient_checkpointing \
  --text_encoder_lr=3e-5 \
  --image_column="image" \
  --caption_column="text" \
  --adam_weight_decay=0.01 \
  --use_8bit_adam \
  --adam_weight_decay_text_encoder=0.01 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --mixed_precision="fp16" \
  --num_train_epochs=15 \
  --rank=24 \
  --snr_gamma=5.0 \
  --repeats=15 \
  --checkpointing_steps=40 \
  --seed="0" 

### Logs

```shell
Just gave kill signal upon system RAM maxing out.
```

### System Info

Google Colab V100 

https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb

**Comment by sayakpaul** [comment]
That is because you're also training the text encoder (SDXL has got two text encoders). 

If you keep it UNet only, it should run.

**Comment by jmaccall316** [comment]
> That is because you're also training the text encoder (SDXL has got two text encoders).
> 
> If you keep it UNet only, it should run.

I understand training the text_encoder uses more RAM, but the issue at hand is not that I couldn't run these settings at all, the issue is that I couldn't run it with the fp16 variant, which is like half the size. On the other hand, using the full version worked fine, so why would training text_encoder work for the full precision model but need more system RAM for the half version? I just thought it might be leaky somehow or something, not sure.

**Comment by sayakpaul** [comment]
That is weird indeed. Will investigate.

**Comment by rmac85** [comment]
Huh?


> That is weird indeed.
> 
> In your training command, I don't see any specification of variant, though. Also, are you using diffusers from source?

Huh? recheck the third arg, dude, --variant="fp16"  
Diffusers are always diffusers, I never specify a version..

**Comment by sayakpaul** [comment]
Ah sorry, but we don't need to sound sarcastic here. A little decent tone goes a long way. 

Worth checking if installing from `main` helps remedy the problem.

**Comment by jmaccall316** [comment]
> Ah sorry, but we don't need to sound sarcastic here. A little decent tone goes a long way.
> 
> Worth checking if installing from `main` helps remedy the problem.

Absolutely I am not trying to sound sarcastic, just reporting an error. When you first responded it seemed as though you had missed where  I had specified the variant, which drew the "huh"...  It was the third arg so yeah, that had been missed.  By installing diffusers that is the auto main repo,  didn't install an old diffusers or specify a version...  I am not angry or trying to be a tone or whatever.

**Comment by sayakpaul** [comment]
Could you try installing diffusers from source (`pip install git+https://github.com/huggingface/diffusers.git`) and see if that helps?

**Comment by rmac85** [comment]
It's an official HF colab https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb

So diffusers are already set to install from source (pip install git+https://github.com/huggingface/diffusers.git -q)

**Comment by sayakpaul** [comment]
Is this still a problem?
