### ISSUE TITLE
safetensors.torch bug

### ISSUE THREAD

**Issue by lawrence-cj** [huggingface/diffusers#5989]
### Describe the bug

When using 
`import safetensors`: https://github.com/huggingface/diffusers/blob/f72b28c75b2b4b720a5d8de78556694cf4b893fd/src/diffusers/models/modeling_utils.py#L25
then `safetensors.torch`: https://github.com/huggingface/diffusers/blob/f72b28c75b2b4b720a5d8de78556694cf4b893fd/src/diffusers/models/modeling_utils.py#L111
Bug reported `AttributeError: module 'safetensors' has no attribute 'torch'`.

**Maybe we can change**
from import safetensors
to import safetensors.torch as safetensors_torch

### Reproduction

import safetensors
safetensors.torch

### Logs

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'safetensors' has no attribute 'torch'
```

### System Info

diffusers==0.23.0
safetensors==0.4.1

**Comment by lawrence-cj** [comment]
When loading .safetensor type ckpt. BTW, .bin ckpt won't cause the error.

**Comment by sayakpaul** [comment]
I mean could you provide a full code snippet for us to see?
