### ISSUE TITLE
cannot recurrent the lora effect on the webui

### ISSUE THREAD

**Issue by DoctorTar** [huggingface/diffusers#5995]
trained my lora in diffusers, It works in local inference,but I cant recurrent it on the webui.
![image](https://github.com/huggingface/diffusers/assets/147801017/fbebba8f-278a-4855-bf12-b1d0198223f5)
![image](https://github.com/huggingface/diffusers/assets/147801017/752247fc-82de-4f84-a253-8af0a8f900da)
![image](https://github.com/huggingface/diffusers/assets/147801017/e85a1c30-54da-4b07-b204-c8a9809a8bb9)

I am not ask for the exactly same result from both side since I know there are lots of params and seed is only one of them, but the lora effect didt work for sure, this is the result I ran in local without lora:
![image](https://github.com/huggingface/diffusers/assets/147801017/b633ca07-4c6a-461b-b750-73dc976c4493)

i wonder the problem may be on the base model safetensors, I loaded SDXL path in local (stabilityai/stable-diffusion-xl-base-1.0) and I saw a bunch of files in that folder ,but I dont know which one is the model actually using. In the webui I just used sd_xl_base_1.0.safetensors and the vae from 'stabilityai__stable-diffusion-xl-base-1.0/vae/diffusion_pytorch_model.safetensors'

Thanks for helping

**Comment by DoctorTar** [comment]
btw, this is the result on webui without lora ,there is only a slight difference compared the loraed version
![image](https://github.com/huggingface/diffusers/assets/147801017/301c7c7a-6121-443b-9e4e-cb3e3a674a01)

**Comment by sayakpaul** [comment]
Can you provide the code you're using in a minimal fashion? It's a little hard for us to see through the code rather than read it.

**Comment by sayakpaul** [comment]
I don't know where does `sd_models/lora_models/3d_style_v1` come from here `lora_path=os.path.join(nas_path,'sd_models/lora_models/3d_style_v1')`.

**Comment by sayakpaul** [comment]
Well, to verify the results, we need access to the file, otherwise we cannot do anything.

**Comment by DoctorTar** [comment]
> Well, to verify the results, we need access to the file, otherwise we cannot do anything.

well but i dont think the lora model is the key of this problem, it works fine in my local venv but useless in the webui, I just wonder the base model I actually using when use **sdxl = DiffusionPipeline.from_pretrained(stable_diffusionXL_path)** because there are a bunch of file in this folder,but webui seems to only need the sd_xl_base_1.0.safetensors file

**Comment by sayakpaul** [comment]
Oh that is not a problem. That is because diffusers has a separate serialization format.

**Comment by DoctorTar** [comment]
> Oh that is not a problem. That is because diffusers has a separate serialization format.

so what model is the pipeline really using when **DiffusionPipeline.from_pretrained(stable_diffusionXL_path)** ? is it loading the sd_xl_base_1.0.safetensors or the other files like vae, text_encoder ....?
