### ISSUE TITLE
IP adapter plus face is failing with LCM Lora  - new diffusers (v0.24.0) release.  

### ISSUE THREAD

**Issue by AyushUnleashed** [huggingface/diffusers#6008]
### Describe the bug

![image](https://github.com/huggingface/diffusers/assets/77686324/e7f4b0c6-9b26-403c-b8fb-180aef1ea211)

I am getting key error, while trying to change the ip adapter to "ip-adapter-plus-face_sd15.bin" model of h94/IP-Adapter

### Reproduction

Just take sample code of IP adapter - LCM Lora from [new release v0.24.0](https://github.com/huggingface/diffusers/releases/tag/v0.24.0) of diffusers
& change model weight_name from "ip-adapter_sd15.bin" to  "ip-adapter-plus-face_sd15.bin"

### System Info

 Google colab
 
 `diffusers` version: 0.24.0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.24.1
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @yiyixuxu @DN6 @patrickvonplaten

**Comment by sayakpaul** [comment]
Please copy-paste actual code snippet, not screenshots. 

Cc: @yiyixuxu could you take a look?

**Comment by yiyixuxu** [comment]
it's not supported yet but will be soon 
https://github.com/huggingface/diffusers/pull/5915
https://github.com/huggingface/diffusers/pull/5911

**Comment by AyushUnleashed** [comment]
Thanks @yiyixuxu for the information
