### ISSUE TITLE
torch.Size() issue with convert_original_stable_diffusion_to_diffusers

### ISSUE THREAD

**Issue by zhuraromdev** [huggingface/diffusers#6016]
### Describe the bug

Hello,

I attempted to convert a model from Civitai (https://civitai.com/models/132632?modelVersionId=168582) to Diffusers, but encountered an error:

```
ValueError: Trying to set a tensor of shape torch.Size([320, 9, 3, 3]) in "weight" (which has shape torch.Size([320, 4, 3, 3])), this look incorrect.
```

Additionally, when attempting to load a model using the pipeline:
```python
inpaint_pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
                                                                            "epinikion/epicphotogasm_v4-inpainting.safetensors",
                                                                            use_auth_token=True,
                                                                            controlnet=controlnet[0],
                                                                            use_safetensors=True,
                                                                            safety_checker=None,
                                                                            torch_dtype=torch.float32).to('cpu')
```

I encountered the following error:
```
OSError: Cannot load model epinikion/epicphotogasm_v4-inpainting.safetensors: model is not cached locally and an error occured while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.
```

Thank you in advance for your assistance!

### Reproduction

I was running the code with the command above:

```shell
python3 packages/stable-diffusion-service/server/scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path packages/stable-diffusion-service/models/epinikion/epicphotogasm_v4-inpainting.safetensors --dump_path packages/stable-diffusion-service/models/epinikion_converted/ --from_safetensors --device cpu --extract_ema
```

### Logs

```shell
python3 packages/stable-diffusion-service/server/scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path packages/stable-diffusion-service/models/epinikion/epicphotogasm_v4-inpainting.safetensors --dump_path packages/stable-diffusion-service/models/epinikion_converted/ --from_safetensors --device cpu --extract_ema
args: Namespace(checkpoint_path='packages/stable-diffusion-service/models/epinikion/epicphotogasm_v4-inpainting.safetensors', original_config_file=None, num_in_channels=None, scheduler_type='pndm', pipeline_type=None, image_size=None, prediction_type=None, extract_ema=True, upcast_attention=False, from_safetensors=True, to_safetensors=False, dump_path='packages/stable-diffusion-service/models/epinikion_converted/', device='cpu', stable_unclip=None, stable_unclip_prior=None, clip_stats_path=None, controlnet=None, half=False, vae_path=None, pipeline_class_name=None)
Traceback (most recent call last):
  File "/Users/romanzhuravskyi/Sites/render-engine/packages/stable-diffusion-service/server/scripts/convert_original_stable_diffusion_to_diffusers.py", line 156, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/Users/romanzhuravskyi/Sites/render-engine/venv/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1447, in download_from_original_stable_diffusion_ckpt
    set_module_tensor_to_device(unet, param_name, "cpu", value=param)
  File "/Users/romanzhuravskyi/Sites/render-engine/venv/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([320, 9, 3, 3]) in "weight" (which has shape torch.Size([320, 4, 3, 3])), this look incorrect.
(base)
```

### System Info

- `diffusers` version: 0.24.0
- Platform: macOS-13.6-arm64-arm-64bit
- Python version: 3.9.6
- PyTorch version (GPU?): 2.1.0 (False)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.33.2
- Accelerate version: 0.23.0
- xFormers version: not installed
- Using GPU in script?: no

### Who can help?

@yiyixuxu @DN6 @sayakpaul @patrickvonplaten @yiyixuxu

**Comment by sayakpaul** [comment]
`safetensors` files are supposed to be loaded using `from_single_file()`.

**Comment by mazharosama** [comment]
How do you know that the architecture is different? I am trying to use https://civitai.com/models/403361/juggernaut-xl-inpainting, and am getting the exact same error. The description says, "Created in Automatic1111 by merging [the base SDXL inpainting model (by wangqyqq)](https://huggingface.co/wangqyqq/sd_xl_base_1.0_inpainting_0.1.safetensors/tree/main), Juggernaut XL (the non-lightning model), SDXL base and the fp16 fix VAE."

No matter if we set num_in_channels to 9, the conversion script doesn't take it into account and use 4 as num_in_channels.

**Comment by asomoza** [comment]
I convert the inpaint models loading them in a pipeline first and then saving them with `save_pretrained`, for example I did it for [this model](https://huggingface.co/OzzyGT/RealVisXL_V4.0_inpainting).

**Comment by mazharosama** [comment]
Loading model doesn't work for this (and other similar models):
https://civitai.com/models/403361/juggernaut-xl-inpainting

I created a PR that solves the issue. May you please review it?

**Comment by asomoza** [comment]
oh yeah, you're right, just as information, if you pass the config from the inpainting model it works:

pipe = StableDiffusionXLInpaintPipeline.from_single_file(
    "juggernautXL_versionXInpaint.safetensors",
    torch_dtype=torch.float16,
    config="diffusers/stable-diffusion-xl-1.0-inpainting-0.1",
).to("cuda")

cc: @DN6
