### ISSUE TITLE
Error converting VAE safetensor to diffusers / UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 25944: invalid continuation byte

### ISSUE THREAD

**Issue by Adeel-Intizar** [huggingface/diffusers#6034]
![image](https://github.com/huggingface/diffusers/assets/56041154/b16c1d0a-e3d7-47ae-9c30-972aa26b2682)

I am facing the above error while converting a sd model from civitai which has config file and vae safetensor separately, i only get this error while trying to convert vae safetensor to diffusers format using the "convert_from_sd_to_diffusers.py" script

how can i solve this issue?

**Comment by Adeel-Intizar** [comment]
https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py

using latest diffusers with conda, using latest script from diffusers scripts, my diffusers version = 0.23.1

using below command in cmd

!python convert_original_stable_diffusion_to_diffusers.py --from_safetensors --device cpu --checkpoint_path juggernaut_aftermath.safetensors --dump_path juggernaut_aftermath --original_config_file juggernaut_aftermath.yaml --vae_path TRCVAE.safetensors


the error only occurs when trying to convert vae as well, it works well using only checkpoint and config file

**Comment by Adeel-Intizar** [comment]
https://civitai.com/models/46422?modelVersionId=127207

you can find those safetensors files in this link

**Comment by sayakpaul** [comment]
Could you provide an end-to-end reproducible code for us? That will be much more useful.
