### ISSUE TITLE
Cross attention map utils 🚀

### ISSUE THREAD

**Issue by wooyeolBaek** [huggingface/diffusers#6036]
Hi,
We have implemented cross attention map visualization code for diffusers. We haven't been able to find attention map code for diffusers yet. So, we're sharing it in case anyone need it. 😊
@taemin6697 @rlaehghks5 @Hyunmin-H
![t2i_image](https://github.com/huggingface/diffusers/assets/75835117/0656533c-4059-4eef-9ff9-133841d66d2c)
![attn_maps](https://github.com/huggingface/diffusers/assets/75835117/2c4595ab-d228-4103-bcd6-a38180b6f804)

HF space: https://huggingface.co/spaces/We-Want-GPU/diffusers-cross-attention-map-SDXL-t2i
github: https://github.com/wooyeolBaek/attention-map

```python
import torch
from diffusers import StableDiffusionXLPipeline
from utils import (
    cross_attn_init,
    register_cross_attention_hook,
    attn_maps,
    get_net_attn_map,
    resize_net_attn_map,
    save_net_attn_map,
)

cross_attn_init()

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
)
pipe.unet = register_cross_attention_hook(pipe.unet)
pipe = pipe.to("cuda")

prompt = "A photo of a black puppy, christmas atmosphere"
image = pipe(prompt).images[0]
image.save('test.png')

dir_name = "attn_maps"
net_attn_maps = get_net_attn_map(image.size)
net_attn_maps = resize_net_attn_map(net_attn_maps, image.size)
save_net_attn_map(net_attn_maps, dir_name, pipe.tokenizer, prompt)
```

**Comment by taemin6697** [comment]
@sayakpaul I need a GPU, so I would appreciate it if you could lend me one. Will the demo work on HF Spaces?

**Comment by wooyeolBaek** [comment]
we finished the HF space demo!

https://colab.research.google.com/drive/1tvaXul9ilEQevziIz9ObkK515kT3dIuo?usp=sharing

**Comment by sayakpaul** [comment]
Awesome. Now, I would like to request you to do it on HF Spaces and let us know the Space URL.

Pinging @AK391 for additional references.

**Comment by taemin6697** [comment]
Since the above problem only occurs in the CPU, it can be resolved immediately if you provide a GPU. @sayakpaul

**Comment by sayakpaul** [comment]
Yes yes. @hysts could you assign this space a GPU? 

https://huggingface.co/spaces/We-Want-GPU/diffusers-cross-attention-map-SDXL-t2i

**Comment by wooyeolBaek** [comment]
HF space done! Thanks for providing the GPU :)

https://huggingface.co/spaces/We-Want-GPU/diffusers-cross-attention-map-SDXL-t2i

**Comment by sayakpaul** [comment]
Alright. Closing the issue then. Thanks again from your great work.

**Comment by Miriam2040** [comment]
Is it working for Image to Image?

**Comment by wooyeolBaek** [comment]
Sure, it works in image-to-image as well.
However, it runs only with square latents, so you need to use a square input image.
