### ISSUE TITLE
Sdxl-turbo distilling example?

### ISSUE THREAD

**Issue by noway2beatme** [huggingface/diffusers#6042]
### Model/Pipeline/Scheduler description

Thanks for your dedication to the community, and any update would be greatly appreciated.

I'm excited about the sdxl-turbo algorithm and would like to inquire if there is any chance for an open-source diffusers version of the ADD distilling example.

### Open source status

- [ ] The model implementation is available.
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by patrickvonplaten** [comment]
Maybe better to ask in the original code base: https://github.com/Stability-AI/generative-models
