### ISSUE TITLE
'StableDiffusionImg2ImgPipeline' object has no attribute 'do_classifier_free_guidance'

### ISSUE THREAD

**Issue by Abdelrahman-Hanafy** [huggingface/diffusers#6044]
### Describe the bug

I try to use the "CompVis/ldm-celebahq-256" unet with the "runwayml/stable-diffusion-v1-5" clip to make img to  img pipeline generate more human-like output as a part of my graduation project

### Reproduction

unet = UNet2DModel.from_pretrained("CompVis/ldm-celebahq-256", subfolder="unet")
vqvae = VQModel.from_pretrained("CompVis/ldm-celebahq-256", subfolder="vqvae")
scheduler = DDIMScheduler.from_config("CompVis/ldm-celebahq-256", subfolder="scheduler")

text_encoder = CLIPTextModel.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="text_encoder")
tokenizer = CLIPTokenizer.from_pretrained("runwayml/stable-diffusion-v1-5",subfolder="tokenizer" )
feature_extractor = CLIPImageProcessor.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="feature_extractor")

pipe = StableDiffusionImg2ImgPipeline(vae = vqvae ,scheduler=scheduler,unet=unet,
                                      text_encoder =text_encoder ,tokenizer =tokenizer , feature_extractor =feature_extractor ,
                                      safety_checker = None, requires_safety_checker = False)
                                  
prompt = "a man with short hair and rounded galsses"
path_to_input_image = "/content/me.jpg"
input_image = Image.open(path_to_input_image).convert("RGB")

image = pipe(prompt=prompt, image=input_image)

### Logs

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-49ce8d343913> in <cell line: 8>()
      6 # input_image = input_image.resize((W, H))
      7 
----> 8 image = pipe(prompt=prompt, image=input_image, guidance_scale = 2)

2 frames
/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py in decorate_context(*args, **kwargs)
    113     def decorate_context(*args, **kwargs):
    114         with ctx_factory():
--> 115             return func(*args, **kwargs)
    116 
    117     return decorate_context

/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py in __call__(self, prompt, image, strength, num_inference_steps, timesteps, guidance_scale, negative_prompt, num_images_per_prompt, eta, generator, prompt_embeds, negative_prompt_embeds, ip_adapter_image, output_type, return_dict, cross_attention_kwargs, clip_skip, callback_on_step_end, callback_on_step_end_tensor_inputs, **kwargs)
    910             device,
    911             num_images_per_prompt,
--> 912             self.do_classifier_free_guidance,
    913             negative_prompt,
    914             prompt_embeds=prompt_embeds,

/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py in __getattr__(self, name)
    136             return self._internal_dict[name]
    137 
--> 138         raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    139 
    140     def save_config(self, save_directory: Union[str, os.PathLike], push_to_hub: bool = False, **kwargs):

AttributeError: 'StableDiffusionImg2ImgPipeline' object has no attribute 'do_classifier_free_guidance'
```

### System Info

- `diffusers` version: 0.24.0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: Colab T4
- Using distributed or parallel set-up in script?: no

### Who can help?

@yiyixuxu @DN @sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu

**Comment by LWprogramming** [comment]
Was able to replicate. It's really weird because
```
>>> print( "do_classifier_free_guidance" in dir(pipe))
True
>>> pipe.do_classifier_free_guidance # attribute error
```

**Comment by dahui-y** [comment]
I have the same issue. @yiyixuxu have any suggestions for this issue?

**Comment by yiyixuxu** [comment]
Hi @Abdelrahman-Hanafy 

`StableDiffusionImg2ImgPipeline` woud not work with `Unet2DModel` - you will have to make your own img2img pipeline based on `LDMPipeline`

Best,
YiYi

**Comment by tingxueronghua** [comment]
I also face this problem when using StableDiffusionControlNetPipeline. And can reproduce the problem in StableDiffusionPipeline. Exactly the same situation. Want to inquire whether this behavior is designed to be so? @yiyixuxu @sayakpaul 

> Was able to replicate. It's really weird because
> 
> ```
> >>> print( "do_classifier_free_guidance" in dir(pipe))
> True
> >>> pipe.do_classifier_free_guidance # attribute error
> ```

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu

**Comment by joeyy5588** [comment]
My guess is that since the self._guidance_scale is initialized in the call function: [link](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L963) instead of the init function, it is possible for a property to appear in the output of dir(pipe) but raise an AttributeError when accessed.

**Comment by yiyixuxu** [comment]
I explained here, no? our SD pipelines does not work with `UNet2DModel`
 https://github.com/huggingface/diffusers/issues/6044#issuecomment-1890760669

**Comment by douyl** [comment]
It is because `UNet2DModel` doesn't support classifier-free guidance (CFG), since CFG needs to combine the unconditional output and conditional output (i.e., null prompt and your given prompt).  You may use `UNet2DConditionModel` rather than `UNet2DModel`.
