### ISSUE TITLE
[Community] Flax: load scheduler using same dtype as pipeline

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#606]
Follow up to https://github.com/huggingface/diffusers/pull/600#discussion_r976064534

**Comment by patrickvonplaten** [comment]
@pcuenca should we open this up to the community? I don't think any of us will have time to work on it soon no?

**Comment by pcuenca** [comment]
I agree, let's open it up! Is it a "good first issue" though?

**Comment by sayakpaul** [comment]
Closing this to track here: https://github.com/huggingface/diffusers/issues/2068
