### ISSUE TITLE
How to run the fine_tuned model?

### ISSUE THREAD

**Issue by alireza18878** [huggingface/diffusers#6067]
Hi all,

I used the instructions given [here](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth) to fine_tune the model on dog pictures (as explained in the link).
The fine_tuning has finished, and a folder called path-to-save-model has been created (that has the weights of the model). Now how do I use this output? Do I run test_dreambooth.py? (I tried running it but it gives error at "from test_examples_utils import ExamplesTestsAccelerate, run_command  # noqa: E402"

I appreciate it if someone can please let me know how to use the output of the trained model.

Thank you

**Comment by asomoza** [comment]
Hi @micklexqg, this is an old issue, also this is not an error and more of a problem in understanding what it's being done here.

After you train a dreambooth model you will have to do inference with it just like any other model, this is even in the README file:

```python
from diffusers import StableDiffusionPipeline
import torch

model_id = "path-to-your-trained-model"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")

prompt = "A photo of sks dog in a bucket"
image = pipe(prompt, num_inference_steps=50, guidance_scale=7.5).images[0]

image.save("dog-bucket.png")
```
