### ISSUE TITLE
How to overload existing class in diffusers

### ISSUE THREAD

**Issue by OrangeSodahub** [huggingface/diffusers#6070]
That's just for personal development. I want to write a new class inherited from existing class (e.g. `ControlNetModel`) and I added some new parameters to `__init__` function, but found that the `__init__` function is still the parent's implementation, whether to add the decorator `register_to_config` or not.

Hope some advice.

**Comment by OrangeSodahub** [comment]
bug..

**Comment by OrangeSodahub** [comment]
example:
```
from diffusers.pipelines.controlnet.pipeline_controlnet import ControlNetModel as _ControlNetModel
class ControlNetModel(_ControlNetModel):
    @register_to_config
    def __int__(self, new_param: bool = False, **kwargs):
        super().__init__(**kwargs)
        self.new_param = new_param

    @....
    def from_unet(....):
        ....
        controlnet = cls(new_param=new_param, ....)
        ....

test = ControlNetModel(new_param)

# error
__init__ got unexpected argument new_param
```

**Comment by patrickvonplaten** [comment]
Sorry I don't understand the question here

**Comment by OrangeSodahub** [comment]
@patrickvonplaten Hi, you could take a look at the code snipet.

**Comment by OrangeSodahub** [comment]
@patrickvonplaten Hi, is there any problem?

**Comment by OrangeSodahub** [comment]
@sayakpaul Hi, is there any problem? I just wonder if there is any hints that the class cannot be inherited or must be some other way.

**Comment by OrangeSodahub** [comment]
Ultimately I solved! That's because the `inspect.signature(cls.__init__).parameters` method can only always see the first `__init__` method ...

https://github.com/huggingface/diffusers/blob/08b453e3828f80027d881bb460716af95e192bcd/src/diffusers/configuration_utils.py#L447-L449

**Comment by OrangeSodahub** [comment]
@betterze Try not to change the class name while change the original class name: `class PixArtTransformer2DModel(_PixArtTransformer2DModel)`.

And in my case, I wrote the init function wrong: `__init__ -> __int__`.

**Comment by cyber-meow** [comment]
> @OrangeSodahub did you solve the problem? I met the same problem.
> 
> ```
> from diffusers.configuration_utils import register_to_config
> from diffusers.models.transformers.pixart_transformer_2d import PixArtTransformer2DModel
> 
> class PixArtTransformer2DModel2(PixArtTransformer2DModel):
>     @register_to_config
>     def __init__(self,
>         **kwargs
>     ):
>         super().__init__(**kwargs)
> 
>     
> device = torch.device("cuda:0")
> weight_dtype = torch.float16
> 
> transformer = PixArtTransformer2DModel2.from_pretrained(
>     "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS", 
>     subfolder='transformer', 
>     torch_dtype=weight_dtype,
>     use_safetensors=True,
> )
> ```
> 
> When I init the model with PixArtTransformer2DModel2, it reports the following error
> 
> ```
> ValueError                                Traceback (most recent call last)
> Cell In[3], line 15
>      12 device = torch.device("cuda:0")
>      13 weight_dtype = torch.float16
> ---> 15 transformer = PixArtTransformer2DModel2.from_pretrained(
>      16     "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS", 
>      17     subfolder='transformer', 
>      18     torch_dtype=weight_dtype,
>      19     use_safetensors=True,
>      20 )
> 
> File /opt/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py:114, in validate_hf_hub_args.<locals>._inner_fn(*args, **kwargs)
>     111 if check_use_auth_token:
>     112     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
> --> 114 return fn(*args, **kwargs)
> 
> File /opt/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py:750, in ModelMixin.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
>     748 missing_keys = set(model.state_dict().keys()) - set(state_dict.keys())
>     749 if len(missing_keys) > 0:
> --> 750     raise ValueError(
>     751         f"Cannot load {cls} from {pretrained_model_name_or_path} because the following keys are"
>     752         f" missing: \n {', '.join(missing_keys)}. \n Please make sure to pass"
>     753         " `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize"
>     754         " those weights or else make sure your checkpoint file is correct."
>     755     )
>     757 unexpected_keys = load_model_dict_into_meta(
>     758     model,
>     759     state_dict,
>    (...)
>     762     model_name_or_path=pretrained_model_name_or_path,
>     763 )
>     765 if cls._keys_to_ignore_on_load_unexpected is not None:
> 
> ValueError: Cannot load <class '__main__.PixArtTransformer2DModel2'> from PixArt-alpha/PixArt-Sigma-XL-2-1024-MS because the following keys are missing: 
>  adaln_single.emb.resolution_embedder.linear_2.bias, adaln_single.emb.resolution_embedder.linear_2.weight, adaln_single.emb.aspect_ratio_embedder.linear_1.bias, adaln_single.emb.aspect_ratio_embedder.linear_1.weight, adaln_single.emb.aspect_ratio_embedder.linear_2.bias, adaln_single.emb.aspect_ratio_embedder.linear_2.weight, adaln_single.emb.resolution_embedder.linear_1.bias, adaln_single.emb.resolution_embedder.linear_1.weight. 
>  Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
> ```
> 
> But when I use PixArtTransformer2DModel, everything works well. But PixArtTransformer2DModel2 should be exactly the same as PixArtTransformer2DModel, right? thx for your help.

I bumped into a similar issue when trying to override `UNet2DConditionModel`. After inspecting the code, I found this comes from https://github.com/huggingface/diffusers/blob/v0.30.3/src/diffusers/configuration_utils.py#L452.

Below is a dirty hack that works for me in case someone encounters the same problem.

```
    @classmethod
    def _get_init_keys(cls, input_class):
        input_class_params = set(
            inspect.signature(input_class.__init__).parameters.keys()
        )
        if input_class.__name__ == cls.__name__:
            parent_class = input_class.__bases__[0]
            return input_class_params | parent_class._get_init_keys(parent_class)
        return input_class_params
```
