### ISSUE TITLE
Dataset Structure and Metadata Issues in ControlNet Training

### ISSUE THREAD

**Issue by hanweikung** [huggingface/diffusers#6077]
I want to train a ControlNet using my custom dataset with the following structure:

```bash
train
├── conditioning_images
│   ├── 00001.png
│   └── 00002.png
└── images
    ├── 00001.jpg
    └── 00002.jpg
```

For the `metadata.jsonl` file, I understand it needs a `file_name` column linking to image files. However, when I provided a `metadata.jsonl` file like this:

```json
{"file_name": "images/00001.jpg", "conditioning_image": "conditioning_images/00001.png", "text": "a man in a suit and tie speaking into a microphone"}
{"file_name": "images/00002.jpg", "conditioning_image": "conditioning_images/00002.png", "text": "a bald man in a suit and tie giving a speech"}
```

The `load_dataset` function raised an error:

```bash
ValueError: image at conditioning_images/00001.png doesn't have metadata in metadata.jsonl
```

I am wondering if there is an issue with my `metadata.jsonl` file.

**Comment by nivedwho** [comment]
@williamberman Any solutions to this? Structures like these usually works when it's loading a dataset from huggingface, but gives ```ValueError``` when the path to is to a local folder following the same structure. 

I used ```load_dataset()``` with just the path as argument.

**Comment by hanweikung** [comment]
I successfully created my dataset, and it now follows this structure:

```bash
train
├── conditioning_images
│   ├── 00001.png
│   └── 00002.png
├── images
│   ├── 00001.jpg
│   └── 00002.jpg
├── train.jsonl
└── train.py
```

I included the `train.py` file in the folder, following [this example](https://huggingface.co/datasets/fusing/fill50k/tree/main). Within this file, I set the values for the three variables: `metadata_path`, `images_dir`, and `conditioning_images_dir`, as shown here.

```python
def _split_generators(self, dl_manager):
    metadata_path = r"/path/to/train/train.jsonl"
    images_dir = r"/path/to/train/images"
    conditioning_images_dir = r"/path/to/train/conditioning_images"

    return [
        datasets.SplitGenerator(
            name=datasets.Split.TRAIN,
            # These kwargs will be passed to _generate_examples
            gen_kwargs={
                "metadata_path": metadata_path,
                "images_dir": images_dir,
                "conditioning_images_dir": conditioning_images_dir,
            },
        ),
    ]
```

I also modified the "metadata.jsonl" file, updating it to look like this:

```json
{"conditioning_image": "00001.png", "image": "00001.jpg", "text": "a man in a suit and tie speaking into a microphone"}
{"conditioning_image": "00002.png", "image": "00002.jpg", "text": "a bald man in a suit and tie giving a speech"}
```

**Comment by FeepingCreature** [comment]
Note for future arrivals: that layout works with a `SplitGenerator`, but if you want to `load_dataset` a local future, you run into issues with the example scripts because they'll loop over every image in the folder.

What I'm currently trying is `metadata.jsonl` `{"file_name": "00001.jpg", "conditioning_image": "full/path/to/conditioning_images/00001.png", "text": "a man in a suit and tie speaking into a microphone"}`, *in the `images/` folder*, and patch the example scripts to load a folder properly and `Image.open` the conditioning images. I don't think anyone tests the example scripts with a local folder.

**Comment by jeonga0303** [comment]
> My own experience: that layout works with a `SplitGenerator`, but if you want to `load_dataset` a local folder, you run into issues with the example scripts because they'll loop over every image in the folder, including the _conditioning images_, which don't have an associated metadata entry.
> 
> The documentation is very sparse about this usecase.
> 
> What I'm currently trying is `metadata.jsonl` `{"file_name": "00001.jpg", "conditioning_image": "full/path/to/conditioning_images/00001.png", "text": "a man in a suit and tie speaking into a microphone"}`, _in the `images/` folder_, and patch the example scripts to load a folder properly and `Image.open` the conditioning images. I don't think anyone tests the example scripts with a local folder.

How did you solve it?

**Comment by Haozong-Zeng** [comment]
> My own experience: that layout works with a `SplitGenerator`, but if you want to `load_dataset` a local folder, you run into issues with the example scripts because they'll loop over every image in the folder, including the _conditioning images_, which don't have an associated metadata entry.
> 
> The documentation is very sparse about this usecase.
> 
> What I'm currently trying is `metadata.jsonl` `{"file_name": "00001.jpg", "conditioning_image": "full/path/to/conditioning_images/00001.png", "text": "a man in a suit and tie speaking into a microphone"}`, _in the `images/` folder_, and patch the example scripts to load a folder properly and `Image.open` the conditioning images. I don't think anyone tests the example scripts with a local folder.

Did you solve the issue with local dataset?

**Comment by levifussell** [comment]
For those arriving here without an answer. You must prepend "_file_name" to all columns that are files. The data_loader will then convert these to images and remove the "_file_name" substring from the column name. If you have multiple it might look like: out_image_file_name, cond_image_filename

**Comment by KSoham2100** [comment]
You should have metadata.jsonl with the following entries for all images 

<img width="584" height="133" alt="Image" src="https://github.com/user-attachments/assets/9080af59-a9d4-4e6b-b338-eddb5ceebfa8" />
