### ISSUE TITLE
LCM Lora training

### ISSUE THREAD

**Issue by anomySz** [huggingface/diffusers#6084]
Hi there, 

I wanna train LCM Lora
But i faced issue like this "AttributeError: Can't pickle local object 'filter_keys.<locals>._f'"

is this problem with dataset? the problem occurs this line 
`consistency_distillation\train_lcm_distill_lora_sd_wds.py", line 1124, in main 
for step, batch in enumerate(train_dataloader):`
    
The data used its own dataset and I converted the folder that was configured as below into a tar file.
``` 
- dataset
  - 0.jpg
  - 0.txt
  - 0.json # {"width":512, "height":512}
  ...
  ```
Initially, I put the local path as a parameter in `--train_shards_path_or_url`, but there was a problem and I uploaded that dataset to the hugging face.

how can i prepare dataset for LCM Lora.

Thanks advanced.

**Comment by sayakpaul** [comment]
We recently fixed some stuff in that script. Could you try to pull in the latest changes and see again? 

PR: https://github.com/huggingface/diffusers/pull/5908

**Comment by anomySz** [comment]
thank you for reply. i solved this problem.
