### ISSUE TITLE
diffusers doesn't save and load the LoraConfig, resulting wrong `lora_alpha` during inference.

### ISSUE THREAD

**Issue by YiqunChen1999** [huggingface/diffusers#6087]
### Describe the bug

When I run `train_dreambooth_lora_sdxl.py`, I find the StableDiffusionXLLoraLoaderMixin (and LoraLoaderMixin) doesn't save & load the LoraConfig.

The default `lora_alpha` is 8 in LoraConfig but is 1 in `peft` Linear. The lora_alpha is 8 during training but is 1 when I load the weights from a checkpoint as the XXLoraLoaderMixin cannot parse the correct `lora_alpha` from the saved Lora weights. The wrong `lora_alpha` gives the wrong `scaling` in the `peft` Linear layer.

I manually reset the `scaling` to get the correct result, but I think this is a bug and should be fixed.

### Reproduction

Clone the `diffusers` repo and install it. Then prepare any one image in a folder.

In the `example/dreambooth` folder, run:
```bash
python train_dreambooth_lora_sdxl.py \
    --pretrained_model_name_or_path stabilityai/stable-diffusion-xl-base-1.0 \
    --pretrained_vae_model_name_or_path madebyollin/sdxl-vae-fp16-fix \
    --instance_data_dir [PATH_TO_YOUR_IMAGE_DIR]  \
    --instance_prompt "<sks>" \  # try to overfit the given image
    --validation_prompt "<sks>" \
    --num_validation_images 1 \
    --validation_epochs 50 \
    --output_dir [OUTPUT_DIR] \
    --train_batch_size 1 \
    --max_train_steps 300 \
    --checkpointing_steps 100 \
    --learning_rate 2e-4  \
    --rank 64
```

For example, I try to overfit the first image. The second image is the validation image at epoch 250 (tensorboard). The third one is the result after the pipeline loads Lora weights from the saved checkpoint (epoch 300, also available in tensorboard).
![image](https://github.com/huggingface/diffusers/assets/47789930/0befacab-5aab-4e12-83bc-7e15f7436d99)
![image](https://github.com/huggingface/diffusers/assets/47789930/16b79a29-31e4-4cd6-ad34-84a5251c9319)
![image](https://github.com/huggingface/diffusers/assets/47789930/1096b0d0-785e-4df8-9e2f-a64a358a8dc2)

### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.25.0.dev0
- Platform: Linux-4.18.0-305.3.1.el8.x86_64-x86_64-with-glibc2.28
- Python version: 3.11.5
- PyTorch version (GPU?): 2.1.1 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@sayakpaul @patri

**Comment by YiqunChen1999** [comment]
@sayakpaul Yes, it works for me. Thanks for your efforts!

**Comment by sayakpaul** [comment]
@YiqunChen1999 does https://github.com/huggingface/diffusers/pull/6225 help?

**Comment by YiqunChen1999** [comment]
@sayakpaul Yes, it works well in my case!

**Comment by eliahuhorwitz** [comment]
@sayakpaul I am getting the same when running the `examples/dreambooth/train_dreambooth_lora.py` script. At training time It seems to be using the default `lora_alpha` of 8 without an argument that controls it. At inference, when calling `pipe.load_lora_weights(lora_model_path)` `lora_alpha` is set to be lora rank (extracted from the lora state_dict).

**Comment by sayakpaul** [comment]
Ah, now I see. Applying the changes from https://github.com/huggingface/diffusers/pull/6225 should fix that. Can you confirm?

**Comment by eliahuhorwitz** [comment]
It fixes it, but I am not sure this is the best solution. Why not allow the user to specify the lora_alpha as an argument and only if they don't default it to the rank? 
The issue with the above suggestion is that one would need to save the alpha value and load it when loading the lora weights.

**Comment by sayakpaul** [comment]
To keep it harmonized with the previous method of training. #6135 did what you just said but we eventually decided not to that route for now.

**Comment by eliahuhorwitz** [comment]
Got it, the results I am getting when training on rank=alpha=16 are worse than rank=16, alpha=8. I think (but not sure, running experiments now) that higher alpha should result in lower LR. Maybe it's worth noting this somewhere in the readme
