### ISSUE TITLE
UNet Reusability Issue with IPAdapter in Pipeline

### ISSUE THREAD

**Issue by arlegotin** [huggingface/diffusers#6088]
### Issue description
In my workflow, there are two pipelines: both are instances of `StableDiffusionPipeline`. One of them utilizes the `load_ip_adapter` method.
To conserve resources, I am trying to reuse as many components as possible. Specifically, I want these pipelines to share the UNet.
I am encountering an issue where the UNet from the pipeline with the loaded IPAdapter cannot be reused in different parts of my code.
It appears that the IPAdapter irreversibly modifies the UNet. Is there a way to resolve this issue?

### Minimalistic Example
```python
# first pipeline
pipe = StableDiffusionPipeline.from_pretrained(...)

# works fine
images = pipe(...)

# second pipeline
pipe_with_ip = StableDiffusionPipeline.from_pretrained(...)
pipe_with_ip.load_ip_adapter(...)

# works fine
images = pipe_with_ip(...)

# reuse UNet (saving the original one)
ye_olde_unet = pipe.unet
pipe.unet = pipe_with_ip.unet

# fails
images = pipe(...)
# TypeError: argument of type 'NoneType' is not iterable

# restoring original UNet
pipe.unet = ye_olde_unet

# works fine again
images = pipe(...)
```

### Reproduction
This issue is consistently reproducible in a Colab environment. [Link to Colab Notebook](https://colab.research.google.com/drive/1dI2Pd5UqXMzYquPm9mlM2_TRMCfRe489#scrollTo=eUz_PIhP5laZ).

### Logs
```bash
   1024             encoder_hidden_states = self.encoder_hid_proj(image_embeds)
   1025         elif self.encoder_hid_proj is not None and self.config.encoder_hid_dim_type == "ip_image_proj":
-> 1026             if "image_embeds" not in added_cond_kwargs:
   1027                 raise ValueError(
   1028                     f"{self.__class__} has the config param `encoder_hid_dim_type` set to 'ip_image_proj' which requires the keyword argument `image_embeds` to be passed in  `added_conditions`"

TypeError: argument of type 'NoneType' is not iterable
```

### System Info

Diffusers 0.24.0
Python 3.10.12

### Who can help?
@sayakpaul @yiyixuxu @DN6 @patrickvonplaten

**Comment by yiyixuxu** [comment]
I don't really understand this use case but you run `pipe.unet.encoder_hid_proj = None` to make it work

**Comment by yiyixuxu** [comment]
maybe we should add `unload_ip_adapter()` to remove all the ip-adapter weights and reset the attention processor? 
@sayakpaul what do you think?

**Comment by sayakpaul** [comment]
That method might be nice as it helps us to have feature completeness given we have methods like `unload_lora_weights()`.

**Comment by yiyixuxu** [comment]
Does anyone want to open a PR to add `unload_ip_adapter`? it need to undo basically everything we did with `load_ip_adapter`:
1. undo the changes we made to the unet structure, i.e. 
        ```python
        self.encoder_hid_proj = None
        self.config.encoder_hid_dim_type = None
       ```
https://github.com/huggingface/diffusers/blob/93ea26f272f69a0e27afaebc96b68a2221a7eda0/src/diffusers/loaders/unet.py#L823
2. set the attention processor back to default

**Comment by sayakpaul** [comment]
Wanna create an issue and label it accordingly? I think it will be a very nice contribution. If no one picks it up I will do it :)

**Comment by arlegotin** [comment]
@yiyixuxu wiping out the IPAdapter completely is not the most elegant solution, because it would take some time to load it again. I was thinking it would be nice to have a method similar to pipe.set_adapters(...) which I'm using to turn on/off LoRAs on the fly

**Comment by maximepeabody** [comment]
As a hack, could you just set a blank image and set scale to 0?

**Comment by yiyixuxu** [comment]
this PR is merged https://github.com/huggingface/diffusers/pull/6192

We should be able to close this issue now, no?

**Comment by LinAnnJose** [comment]
iojopipiuoh
