### ISSUE TITLE
push_to_hub only create repo in consistency model lora SDXL training script

### ISSUE THREAD

**Issue by johnowhitaker** [huggingface/diffusers#6093]
### Describe the bug

https://github.com/huggingface/diffusers/blob/main/examples/consistency_distillation/train_lcm_distill_lora_sdxl_wds.py has a push_to_hub argument but all it does currently is create the repo.

### Reproduction

Run the lora example as decribed here: https://github.com/huggingface/diffusers/blob/main/examples/consistency_distillation/README_sdxl.md 
Observe: no files uploaded.

### System Info

any

**Comment by luvWY** [comment]
did you konw why lcm sd-xl do not need w_embedding into Unet??

**Comment by patrickvonplaten** [comment]
@patil-suraj can you take a look here?

**Comment by patrickvonplaten** [comment]
Gentle ping @patil-suraj

**Comment by yiyixuxu** [comment]
I think it is already fixed here https://github.com/huggingface/diffusers/pull/6102
