### ISSUE TITLE
IP adapter - stable diffusion app works in colab but not on AWS EC2 

### ISSUE THREAD

**Issue by AyushUnleashed** [huggingface/diffusers#6107]
### Describe the bug

I am building an app using diffusers, the python backend when I run on colab works great, but when I run it on EC2 I am getting header too large error.

![image](https://github.com/huggingface/diffusers/assets/77686324/9de45889-ba84-43f9-a774-b5252f6cfdd2)

The App uses IP adapter, & the issue comes when loading the IP adapter. I have faced similar issue with establishing MagicAnimate repo on EC2.

The same EC2 machine can run SD1.5,SDXL inference & inpainting , just fails with IP Adapter & running Magic Animate

EC2 config:

Deep Learning OSS Nvidia Driver AMI GPU PyTorch 2.1.0 (Ubuntu 20.04) 20231205
G4dn.xl 16GB GPU 

### Reproduction

```
device = "cuda"
image_encoder_path = "IP-Adapter/models/image_encoder/"
ip_ckpt = "IP_Adapter/models/ip-adapter_sd15.bin"

d_type = torch.float16
torch.cuda.empty_cache()


def setup_pipeline(base_model_path: str = "Yntec/epiCPhotoGasm"):

    control_type = "pose"
    controlnet = ControlNetModel.from_pretrained(CONTROLNET_MAPPING[control_type]["model_id"], torch_dtype=d_type).to(device)

    pipe_control_net = StableDiffusionControlNetPipeline.from_pretrained(base_model_path,
                                                      controlnet=controlnet,
                                                      torch_dtype=d_type,
                                                      safety_checker=None,
                                                      controlnet_conditioning_scale=0.8,
                                                      guidance_scale=0.75).to(device)

    # load ip-adapter
    print("DEBUG: loading IP adapter ")
    ip_model = IPAdapter(pipe_control_net, image_encoder_path, ip_ckpt, device="cuda", num_tokens=16)


    return ip_model
'''
    
    ----------
    
    This is the code I am using to setup my IP adapter 



### Logs

```shell
(pytorch) ubuntu@ip-172-31-15-191:~/ayush/super-hero-ai-pipeline$ python test_app.py 
Keyword arguments {'controlnet_conditioning_scale': 0.8, 'guidance_scale': 0.75} are not expected by StableDiffusionControlNetPipeline and will be ignored.
Loading pipeline components...:  17%|████████████▊                                                                | 1/6 [00:00<00:00,  9.03it/s]/opt/conda/envs/pytorch/lib/python3.10/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  3.82it/s]
DEBUG: loading IP adapter 
Traceback (most recent call last):
  File "/home/ubuntu/ayush/super-hero-ai-pipeline/test_app.py", line 28, in <module>
    main()
  File "/home/ubuntu/ayush/super-hero-ai-pipeline/test_app.py", line 25, in main
    generate_image(request,1)
  File "/home/ubuntu/ayush/super-hero-ai-pipeline/pipeline/generate_image.py", line 28, in generate_image
    load_pipeline(base_request.base_model)
  File "/home/ubuntu/ayush/super-hero-ai-pipeline/pipeline/generate_image.py", line 20, in load_pipeline
    ip_model = setup_pipeline(base_model_path=model_path)
  File "/home/ubuntu/ayush/super-hero-ai-pipeline/pipeline/setup_sd_pipeline.py", line 29, in setup_pipeline
    ip_model = IPAdapter(pipe_control_net, image_encoder_path, ip_ckpt, device="cuda", num_tokens=16)
  File "/home/ubuntu/ayush/super-hero-ai-pipeline/IP_Adapter/ip_adapter/ip_adapter.py", line 76, in __init__
    self.image_encoder = CLIPVisionModelWithProjection.from_pretrained(self.image_encoder_path).to(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3148, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

### System Info

For colab:

```
- `diffusers` version: 0.24.0
- Platform: Linux-6.1.58+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

```

For EC2:

- `diffusers` version: 0.24.0
- Platform: Linux-5.15.0-1050-aws-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.1.0 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
We cannot help VM-specific problems, sorry.

**Comment by AyushUnleashed** [comment]
> We cannot help VM-specific problems, sorry. 

So where can I get help regarding this? It's IP adapter & stable diffusion issue right ? not working on certain platform.

**Comment by a-r-r-o-w** [comment]
From googling a bit, this error seems to mostly be caused by using the incorrect URL/hub path to the models. From what I can see in the logs, we have this:

```py
self.image_encoder = CLIPVisionModeWithProjection.from_pretrained(self.image_encoder_path)...
```

Also in your code, you define `image_encoder_path = "IP-Adapter/models/image_encoder/"` which you then pass while instantitating your IPAdapter class. Assuming you haven't done any pre-processing to `self.image_encoder_path` and are just passing what you instantiate with your class as-is, it is an incorrect file path.

There are too many unknowns as enough information hasn't been provided. Not sure if anyone can help you debug this issue and it doesn't seem like one from diffusers side of things. I have been able to use IP adapters and most of the features offered in diffusers on various different platforms (AWS included).

**Comment by AyushUnleashed** [comment]
Thanks for the help @a-r-r-o-w , I understand the unknowns, I'll try to figure it out on my own.

**Comment by wilfrediscoming** [comment]
> Thanks for the help @a-r-r-o-w , I understand the unknowns, I'll try to figure it out on my own.

Have you find out what is the problem?
