### ISSUE TITLE
Feature Request: Update Dreambooth training scripts to support loading base model from single safetensors file

### ISSUE THREAD

**Issue by levi** [huggingface/diffusers#6108]
**Is your feature request related to a problem? Please describe.**

Current SD and SDXL dreambooth training scripts use the traditional `from_pretrained` method to load the `pretrained_model_name_or_path`. Since diffusers now support saving a fine tune as a single safetensors file, these scripts need to be updated to support loading a local safetensors file to train on.

I've gone through the process of updating one to support a single file, but have run into issues related to generating the validation images. Namely, when the script generates validation images, the output images don't adhere to the prompt, are muted in color and take on a Lynchian vibe:

![image](https://github.com/huggingface/diffusers/assets/8493/e2640de6-8e31-476b-bcb3-b91343ad56c6)

Here is what the pipeline loading looks like at the point where the validation images are being prompted. I assume this is breaking because I am incorrectly trying to merge the in-memory model and the safetensors single file. 

```
                if args.pretrained_model_name_or_path.endswith(".safetensors"):
                    pipeline = StableDiffusionXLPipeline.from_single_file(
                        args.pretrained_model_name_or_path,
                        vae=vae,
                        text_encoder=accelerator.unwrap_model(text_encoder_one),
                        text_encoder_2=accelerator.unwrap_model(text_encoder_two),
                        unet=accelerator.unwrap_model(unet),
                        torch_dtype=weight_dtype,
                    )
                else:
                    pipeline = StableDiffusionXLPipeline.from_pretrained(
                        args.pretrained_model_name_or_path,
                        vae=vae,
                        text_encoder=accelerator.unwrap_model(text_encoder_one),
                        text_encoder_2=accelerator.unwrap_model(text_encoder_two),
                        unet=accelerator.unwrap_model(unet),
                        revision=args.revision,
                        torch_dtype=weight_dtype,
                    )
```

Any thoughts, @sayakpaul ?

**Comment by sayakpaul** [comment]
Not a bad idea but I think we're pausing for a while in introducing more changes to the training script. I'd like a second opinion from @patrickvonplaten here.

**Comment by levi** [comment]
No worries on the pause. I figured out the issue, however. `from_single_file` doesn't allow the text_encoders and unet to be injected for SDXL models, like `from_pretrained` does.
