### ISSUE TITLE
AnimateDiffPipeline: add ImageToVideo and VideoToVideo

### ISSUE THREAD

**Issue by jon-chuang** [huggingface/diffusers#6123]
Can adapt the work in https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved

**Comment by jon-chuang** [comment]
Seems pretty simple, just need to add a `prepare_latents`

**Comment by jon-chuang** [comment]
Btw, you should probably also check that latents shape is correct in the original pipeline.

**Comment by a-r-r-o-w** [comment]
Hey @jon-chuang. ImageToVideo should be an easy addition to the current implementation, I think, and I can take it up. For VideoToVideo, do you mean the controlnet example in the linked repo (#5866 is relevant in that case)?

**Comment by jon-chuang** [comment]
@a-r-r-o-w I have something barely working right now, I might upstream it at later date. I think the ComfyUI has a lot of hacks to get it to work well, let me try to recreate them.

**Comment by a-r-r-o-w** [comment]
Hey @jon-chuang. Do you have any updates on the ImageToVideo addition and do you plan on opening a PR for the same? If not, I'll be happy to start looking into it.

**Comment by jon-chuang** [comment]
Hello Aryan, sure go ahead, I'll post some code here soon in case it will help you.
