### ISSUE TITLE
Error while loading Lora

### ISSUE THREAD

**Issue by istoneyou** [huggingface/diffusers#6130]
### Describe the bug

According to the [guidance ](https://huggingface.co/docs/diffusers/main/en/training/lora), I try to finetune the SD with lora, and use the lora weight, but the issue appears.

```
Traceback (most recent call last):
  File "AutoPipelineForTex.py", line 17, in <module>
    pipe.unet.load_attn_procs("/code/pytorch_lora_weights.safetensors")
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/loaders/unet.py", line 264, in load_attn_procs
    rank = value_dict["lora.down.weight"].shape[0]
KeyError: 'lora.down.weight
```
When I try the following codes, the above isssue appears。
```
from diffusers import AutoPipelineForText2Image
import torch

pipeline = AutoPipelineForText2Image.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to("cuda")
pipeline.load_lora_weights("/sddata/finetune/lora/pokemon/", weight_name="pytorch_lora_weights.safetensors")
image = pipeline("Green pokemon with menacing face").images[0]
image.save("green_pokemon.png")
```

The safetensors file was created when run the following cmd:
python train_text_to_image_lora.py --pretrained_model_name_or_path=$MODEL_NAME --dataset_name=$DATASET_NAME --dataloader_num_workers=8 --resolution=512 --center_crop --random_flip --train_batch_size=1 --gradient_accumulation_steps=4 --max_train_steps=15000 --learning_rate=1e-04 --max_grad_norm=1 --lr_scheduler="cosine" --lr_warmup_steps=0 --output_dir=${OUTPUT_DIR} --checkpointing_steps=500 --validation_prompt="A pokemon with blue eyes." --seed=1337

### Reproduction

```
from diffusers import AutoPipelineForText2Image
import torch

pipeline = AutoPipelineForText2Image.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to("cuda")
pipeline.load_lora_weights("/sddata/finetune/lora/pokemon/", weight_name="pytorch_lora_weights.safetensors")
image = pipeline("Green pokemon with menacing face").images[0]
image.save("green_pokemon.png")
```

### System Info

Python: 3.8.10
diffusers: 0.25.0.dev0

**Comment by jimmyzhang610** [comment]
same issue

**Comment by jimmyzhang610** [comment]
> We don't have access to `/sddata/finetune/lora/pokemon/` and hence cannot debug further without having access to it.

I applied this patch `https://github.com/huggingface/diffusers/pull/6119` to train_text_to_image_lora_sdxl.py, and the training process is fine now. However, I encountered an error during inference after training. Could you please help ?

`
Traceback (most recent call last):
  File "/data1/cgzhang6/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py", line 1284, in <module>
    main(args)
  File "/data1/cgzhang6/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py", line 1237, in main
    pipeline.load_lora_weights(args.output_dir)
  File "/data1/cgzhang6/diffusers/src/diffusers/loaders/lora.py", line 1305, in load_lora_weights
    self.load_lora_into_unet(
  File "/data1/cgzhang6/diffusers/src/diffusers/loaders/lora.py", line 468, in load_lora_into_unet
    unet.load_attn_procs(
  File "/usr/local/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/data1/cgzhang6/diffusers/src/diffusers/loaders/unet.py", line 264, in load_attn_procs
    rank = value_dict["lora.down.weight"].shape[0]
KeyError: 'lora.down.weight`
`

**Comment by sayakpaul** [comment]
It would be very helpful if you could at least upload the trained checkpoint so that we can look into the issue. This will help us to look into it faster. I hope you'd understand that.

**Comment by jimmyzhang610** [comment]
> It would be very helpful if you could at least upload the trained checkpoint so that we can look into the issue. This will help us to look into it faster. I hope you'd understand that.
[pytorch_lora_weights.zip](https://github.com/huggingface/diffusers/files/13633695/pytorch_lora_weights.zip)

Attached are the weights I trained using the reference from diffusers/examples/text_to_image/README_sdxl.md. You can simply unzip the file to obtain the weight files.

**Comment by jimmyzhang610** [comment]
> > It would be very helpful if you could at least upload the trained checkpoint so that we can look into the issue. This will help us to look into it faster. I hope you'd understand that.
> > [pytorch_lora_weights.zip](https://github.com/huggingface/diffusers/files/13633695/pytorch_lora_weights.zip)
> 
> Attached are the weights I trained using the reference from diffusers/examples/text_to_image/README_sdxl.md. You can simply unzip the file to obtain the weight files.

Of course, these weights are after merging your patch. Otherwise, the training would throw an error.

**Comment by istoneyou** [comment]
> It would be very helpful if you could at least upload the trained checkpoint so that we can look into the issue. This will help us to look into it faster. I hope you'd understand that.

You can check the [/sddata/finetune/lora/pokemon/ ](https://drive.google.com/file/d/1Q_UaQnuXl97UsGE0cxL0K6s8HAl5CN2O/view?usp=drive_link)

**Comment by sayakpaul** [comment]
I can reproduce the issue: https://colab.research.google.com/gist/sayakpaul/fa368e2867d06276af6c9ddbda7190be/scratchpad.ipynb. 

Looking into it.

**Comment by sayakpaul** [comment]
The error can be solved by installing `peft`. See here: https://colab.research.google.com/gist/sayakpaul/b84e1d6b9484b2467c7fb399d1177cd7/scratchpad.ipynb. 

However, without `peft` being installed, it fails. See here: https://colab.research.google.com/gist/sayakpaul/fa368e2867d06276af6c9ddbda7190be/scratchpad.ipynb. Cc: @younesbelkada @pacman100

**Comment by istoneyou** [comment]
> The error can be solved by installing `peft`. See here: https://colab.research.google.com/gist/sayakpaul/b84e1d6b9484b2467c7fb399d1177cd7/scratchpad.ipynb.
> 
> However, without `peft` being installed, it fails. See here: https://colab.research.google.com/gist/sayakpaul/fa368e2867d06276af6c9ddbda7190be/scratchpad.ipynb. Cc: @younesbelkada @pacman100

I have installed the perf with version 0.7.0, but it does not work for me.

**Comment by sayakpaul** [comment]
Can you provide a fully reproducible code snippet? Preferably a Colab Notebook?

**Comment by istoneyou** [comment]
> Can you provide a fully reproducible code snippet? Preferably a Colab Notebook?
First run the train_text_to_image_lora.py script to generate the lora weight file.
`python train_text_to_image_lora.py --pretrained_model_name_or_path=$MODEL_NAME --dataset_name=$DATASET_NAME --dataloader_num_workers=8 --resolution=512 --center_crop --random_flip --train_batch_size=1 --gradient_accumulation_steps=4 --max_train_steps=15000 --learning_rate=1e-04 --max_grad_norm=1 --lr_scheduler="cosine" --lr_warmup_steps=0 --output_dir=${OUTPUT_DIR} --checkpointing_steps=500 --validation_prompt="A pokemon with blue eyes." --seed=1337`

Then run the following the code, the issue will appear.
```
from diffusers import AutoPipelineForText2Image
import torch

pipeline = AutoPipelineForText2Image.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to("cuda")
pipeline.load_lora_weights("/sddata/finetune/lora/pokemon/", weight_name="pytorch_lora_weights.safetensors")
image = pipeline("Green pokemon with menacing face").images[0]
image.save("green_pokemon.png")


```

**Comment by sayakpaul** [comment]
I will use this LoRA file: https://drive.google.com/file/d/1Q_UaQnuXl97UsGE0cxL0K6s8HAl5CN2O/view?usp=drive_link. 

Please understand that it's not convenient for a library maintainer to first train to generate a checkpoint and then be able to debug the issue. So, always try to provide a FULLY reproducible yet minimal code snippet so that we can help you.

**Comment by sayakpaul** [comment]
I am unable to unzip the weights you provided:

```
[sddata.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of sddata.zip or
        sddata.zip.zip, and cannot find sddata.zip.ZIP, period.
```

It'd be great if you just upload your trained weights on the HF Hub and pass over the link.

**Comment by jimmyzhang610** [comment]
> The error can be solved by installing `peft`. See here: https://colab.research.google.com/gist/sayakpaul/b84e1d6b9484b2467c7fb399d1177cd7/scratchpad.ipynb.
> 
> However, without `peft` being installed, it fails. See here: https://colab.research.google.com/gist/sayakpaul/fa368e2867d06276af6c9ddbda7190be/scratchpad.ipynb. Cc: @younesbelkada @pacman100

I found the reason. My environment already had the peft library installed, but the transformers version was 4.31.0. After upgrading to 4.34.0, the issue was resolved. Thank you for the inspiration you provided.

**Comment by istoneyou** [comment]
The issue was fixed when update the transformers to 4.34.0. Thanks! @jimmyzhang610 @sayakpaul

**Comment by istoneyou** [comment]
The issue was fixed when update the transformers to 4.34.0. Thanks! @jimmyzhang610 @sayakpaul

**Comment by CaffreyR** [comment]
Same issue #6176 , we have to upgradding transformers? But it is fine when load "patrickvonplaten/lora_dreambooth_dog_example". Is this because the the patrickvonplaten's were trained at the different version and the testing is fine. Any clues about it ? @istoneyou @jimmyzhang610 @sayakpaul Thanks

**Comment by CaffreyR** [comment]
I guess the PEFT problem, while the patrickvonplaten's were loaded not using PEFT
