### ISSUE TITLE
IP adapter plus not working

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#6131]
### Describe the bug

```
clip_embeddings_dim = state_dict["image_proj"]["proj.weight"].shape[-1]
KeyError: 'proj.weight'
```

### Reproduction

 image1 = Image.open('a.jpg').convert('RGB')

    pipe = StableDiffusionPipeline.from_pretrained(
        "runwayml/stable-diffusion-v1-5",
    )
    pipe.to(torch_device="cuda", torch_dtype=torch.float32)

    pipe.load_ip_adapter("h94/IP-Adapter", subfolder="models", weight_name="ip-adapter-plus_sd15.bin",cache_dir="model_cache")
    
    generator = torch.Generator(device="cpu").manual_seed(3635017627)
    images=pipe(prompt="mona lisa",width=512,height=512,generator=generator,num_inference_steps=28,guidance_scale=7,ip_adapter_image=image1).images

### System Info

default one

### Who can help?

@yiyixuxu @DN6 @sayakpaul @patrickvonplaten

**Comment by alexblattner** [comment]
this is the latest main version btw

**Comment by zhaoyun0071** [comment]
+1 same problem

**Comment by DN6** [comment]
@yiyixuxu Could you take a look please?

**Comment by yiyixuxu** [comment]
sorry I can't reproduce this issue

**Comment by alexblattner** [comment]
@yiyixuxu is there anything I could provide to help? I have the latest version of diffusers and it doens't work...

**Comment by zhaoyun0071** [comment]
> @yiyixuxu is there anything I could provide to help? I have the latest version of diffusers and it doens't work...

IP Adapter Plus and IP Adapter Full are not supported in diffusers 0.24.0. If you want to use one of them, you can clone the repository and use the current version
