### ISSUE TITLE
Irrelevant and repetitive outputs in stable diffusion 

### ISSUE THREAD

**Issue by dnyaneshthombre** [huggingface/diffusers#6134]
I trained a model with over 350 images on Colab dreambooth but the outputs weren't upto the mark, I did the same with limited images, the outputs were better. What can be the reasons? What are the things to consider while training images using Colab?

**Comment by standardAI** [comment]
Hi @dnyaneshthombre. It is known that DreamBooth is hyperparameter-sensitive and overfitting-prone. If you haven't seen [this blog post](https://huggingface.co/blog/dreambooth) already, I would recommend it to you.

**Comment by dnyaneshthombre** [comment]
> Hi @dnyaneshthombre. It is known that DreamBooth is hyperparameter-sensitive and overfitting-prone. If you haven't seen [this blog post](https://huggingface.co/blog/dreambooth) already, I would recommend it to you.

Thank you for the post, it was very informative.
