### ISSUE TITLE
NameError: name 'start_training' is not defined

### ISSUE THREAD

**Issue by masuxin** [huggingface/diffusers#6142]
### Describe the bug

thank you for your great job!
Run dreambooth_train.py, I meet this wrong.

### Reproduction

python3 dreambooth_train.py

### Logs

```shell
Traceback (most recent call last):
  File "/home/masuxin/Dsd1.5/sd_dreambooth_extension/scripts/api.py", line 28, in <module>
    from dreambooth.diff_to_sd import compile_checkpoint
  File "/home/masuxin/Dsd1.5/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 26, in <module>
    from lora_diffusion.lora import merge_lora_to_model
ModuleNotFoundError: No module named 'lora_diffusion'
model_name:  openjourney
Traceback (most recent call last):
  File "dreambooth_train.py", line 7, in <module>
    train(model_name="openjourney", use_tx2img=True,
  File "/sd_dreambooth_extension/scripts/api.py", line 968, in train
    start_training( model_name, use_tx2img)
NameError: name 'start_training' is not defined
```

### System Info

linux
Python 3.8.10
tokenizers-0.13.3 
transformers-4.30.2

**Comment by standardAI** [comment]
Hi @masuxin. This problem might be related to `sd_dreambooth_extension` library. Other than that, did you install this library properly or do you have [`lora_diffusion` directory](https://github.com/d8ahazard/sd_dreambooth_extension/tree/main/lora_diffusion) at your `/home/masuxin/Dsd1.5/sd_dreambooth_extension/` directory? Also, did you define or import `start_training` function at the file where it resides?

**Comment by masuxin** [comment]
> Hi @masuxin. This problem might be related to `sd_dreambooth_extension` library. Other than that, did you install this library properly or do you have [`lora_diffusion` directory](https://github.com/d8ahazard/sd_dreambooth_extension/tree/main/lora_diffusion) at your `/home/masuxin/Dsd1.5/sd_dreambooth_extension/` directory? Also, did you define or import `start_training` function at the file where it resides?

Thanks for the reply.
Actually, previously it worked fine, I got this error after I updated my conda environment, it should be a problem with the package version, but I don't know which package has the problem.I reinstalled the conda environment following the official code provided by Dreambooth, and still can't get it to work. I don't have lora_diffusion in my sd_dreambooth_extension, but I didn't have this directory when it was able to work before.

**Comment by standardAI** [comment]
Which official code provided by DreamBooth are you talking about?
