### ISSUE TITLE
ip-adapter-full-face_sd15 load error

### ISSUE THREAD

**Issue by zhaoyun0071** [huggingface/diffusers#6149]
### Describe the bug

`pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="models", weight_name="ip-adapter-full-face_sd15.bin")`

diffusers\loaders\unet.py", line 711, in _load_ip_adapter_weights
    clip_embeddings_dim = state_dict["image_proj"]["proj.weight"].shape[-1]
KeyError: 'proj.weight'

### Reproduction

```

import torch
from diffusers import StableDiffusionPipeline, DDIMScheduler
from diffusers.utils import load_image

noise_scheduler = DDIMScheduler(
    num_train_timesteps=1000,
    beta_start=0.00085,
    beta_end=0.012,
    beta_schedule="scaled_linear",
    clip_sample=False,
    set_alpha_to_one=False,
    steps_offset=1
)

pipeline = StableDiffusionPipeline.from_single_file(r"braBeautifulRealistic_v40.safetensors", torch_dtype=torch.float16,
                                                    load_safety_checker=False).to("cuda")

pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="models", weight_name="ip-adapter-full-face_sd15.bin")

```

### System Info

diffusers 0.24.0

**Comment by fabiorigano** [comment]
IP Adapter Plus and IP Adapter Full are not supported in diffusers 0.24.0. If you want to use one of it, you can clone the repository and use the current version

**Comment by sayakpaul** [comment]
Or do `pip install git+https://github.com/huggingface/diffusers`.
