### ISSUE TITLE
Is there any outpainting pipe demo?

### ISSUE THREAD

**Issue by CrazyBoyM** [huggingface/diffusers#615]
I would like to use it to  outpainting images, can you help me

**Comment by patrickvonplaten** [comment]
cc @anton-l @patil-suraj @pcuenca - I think this would indeed be a good idea no?

**Comment by pcuenca** [comment]
Yes, it'd be very cool!

How would it work though? Manipulating the latents as in the current in-painting process, assuming they have a strong correlation with the image geometry?

**Comment by fffiloni** [comment]
I am working on it.
In fact you’d only need to work with img2img
stay tuned

**Comment by fffiloni** [comment]
NEW Outpainting demo on huggingface : [StableDiffusion Infinity](https://huggingface.co/spaces/lnyan/stablediffusion-infinity) by [Inyan](https://huggingface.co/lnyan)

![outpainting-demo](https://user-images.githubusercontent.com/7447007/193835116-4820ebee-b20a-44f3-93c1-5f1f332fd691.jpeg)

**Comment by CrazyBoyM** [comment]
> NEW Outpainting demo on huggingface : [StableDiffusion Infinity](https://huggingface.co/spaces/lnyan/stablediffusion-infinity) by [Inyan](https://huggingface.co/lnyan)
> 
> ![outpainting-demo](https://user-images.githubusercontent.com/7447007/193835116-4820ebee-b20a-44f3-93c1-5f1f332fd691.jpeg)

thanks. it is a nice work,

**Comment by wilfrediscoming** [comment]
is there any code examples for outpainting?
