### ISSUE TITLE
sdxl + controlnet   out of memory in  free colab

### ISSUE THREAD

**Issue by loboere** [huggingface/diffusers#6152]
on a free colab instance comfyui loads sdxl and controlnet without problems, but diffusers can't seem to handle this and causes an out of memory.
Is there any option or parameter in diffusers to make sdxl and controlnet work in colab for free?
It seems strange to me that comnfyui can handle this and diffusers can't.
There must be something wrong with the diffusers to cause an out of memory.

i am use https://huggingface.co/diffusers/controlnet-depth-sdxl-1.0

**Comment by standardAI** [comment]
Hi @loboere. Just remove all the `.to("cuda")` parts and try again.

**Comment by standardAI** [comment]
Hi @loboere. Remove `.to("cuda")` parts of `controlnet`, `vae`, and `pipe` then try again.
