### ISSUE TITLE
it seems that the combination of lcm-lora and style lora on finetuned model will decrease the effect of style lora?

### ISSUE THREAD

**Issue by zhangvia** [huggingface/diffusers#6156]
### Describe the bug

I fused the lcm-lora into the model in Civitai, then fused my own trained LoRa. There is a noticeable difference in the effect of fusing my own LoRa directly on Civitai compared to fusing it after lcm-lora. The original direct fusion of my own LoRa has a more distinct style, while the difference in styles between different LoRas seems to decrease after fusing with lcm-lora. and i try to change the lora weights and inference steps, none of them can help. i'm using the latent-consistency/lcm-lora-sdv1-5 lcm lora. Is this due to the combination of multiple LoRas, or is it a problem with lcm itself?

if i train my own lcm lora or distill the finetuned model ,will the style lora performance will be better?

### Reproduction

fuse the style lora which trained on a finetuned model into the finetune model after fusing the lcm lora. the effect of lora will decrease 

### System Info

diffusers 0.24.0

### Who can help?

@sayakpaul @patr

**Comment by sayakpaul** [comment]
Cc: @patil-suraj

**Comment by sayakpaul** [comment]
@patil-suraj a gentle ping.

**Comment by yuananf** [comment]
Same problem here.

**Comment by patil-suraj** [comment]
It is normal that one or other lora will have less effect after fusing. Could you post code snippet showing how you fused ?
If the style lora has less effect then you could try to give more weight to style lora when fusing and less weight to lcm-lora. 
Check out this [doc](https://huggingface.co/docs/diffusers/using-diffusers/inference_with_lcm_lora#combine-with-styled-loras) for how to combine LCM LoRA and assign weights.

But in some cases it is indeed possible that the LCM-LoRA can take over other LoRAs, as LCM-LoRA is applied to the whole model and if the other lora is small then it will have less effect.

**Comment by sayakpaul** [comment]
I am going to close this issue. To me, it seems more like a discussion and https://github.com/huggingface/diffusers/discussions is a better place for it.
