### ISSUE TITLE
always discard next-to-last sigma for diffusers

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#6161]
**Is your feature request related to a problem? Please describe.**
There's a feature from A1111 that I want to use in diffusers

**Describe the solution you'd like.**
I'd like it implemented or instructions on how to implement it

**Describe alternatives you've considered.**
figuring it out myself

**Additional context.**
[Add any other context or screenshots about the feature request here.](https://cdn.discordapp.com/attachments/1115540317366657107/1184462769102258176/Screenshot_2023-12-13_155156.png?ex=658c0fea&is=65799aea&hm=c20fd2b06c830081a8cee322bbc34bbb26879b94621227904aa9e4aa7f226326&)

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu.

Can you give some results that benefit from this feature? That will help us to prioritise if this is worth the consideration.

**Comment by alexblattner** [comment]
@sayakpaul I have clear examples for you:
https://cdn.discordapp.com/attachments/1115540317366657107/1184462530756743250/00054-1971414394.png?ex=658c0fb1&is=65799ab1&hm=e559596aac360775d665a00577add42147fdbc9a4a9b6999a7f562a15d05ad5c&

https://cdn.discordapp.com/attachments/1115540317366657107/1184462531465588906/00055-1971414394.png?ex=658c0fb1&is=65799ab1&hm=3ea2deaf5a2dff9c93febbd928f000de37655dfd44d8625ca7a5eeaa42e494f4&


It impacts the shadows. Look at the shoulders and face extremeties

**Comment by alexblattner** [comment]
this is a cool feature to have still

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu

**Comment by yiyixuxu** [comment]
It's easy to add, but I'm not convinced with the benefit. would love to see some results comparison

**Comment by alexblattner** [comment]
@yiyixuxu here's a result comparison:

https://cdn.discordapp.com/attachments/1115540317366657107/1184462530756743250/00054-1971414394.png?ex=658c0fb1&is=65799ab1&hm=e559596aac360775d665a00577add42147fdbc9a4a9b6999a7f562a15d05ad5c&

https://cdn.discordapp.com/attachments/1115540317366657107/1184462531465588906/00055-1971414394.png?ex=658c0fb1&is=65799ab1&hm=3ea2deaf5a2dff9c93febbd928f000de37655dfd44d8625ca7a5eeaa42e494f4&

the change is small but impactful

**Comment by yiyixuxu** [comment]
cc @Beinsezii here 
let me know what you think about this, would it be helpful to support this?

**Comment by Beinsezii** [comment]
The image links aren't valid anymore so I'm not sure what exactly it's doing.

Assuming it's something like
```diff
+ sigmas[-1] = 0 # nullify sigma while keeping vector length for indexing
sigmas = np.cat(sigmas[-1])
```
You essentially oversample the image at the end by progressing through the timesteps faster which results in a smoother image. IMO that's the wrong way to do it though, as it's much easier and more controllable to just adjust the magnitude of the input noise which is already possible in diffusers.

Magnitude `0.99`, `1`, `1.02` using [my diffusers cli](<https://github.com/Beinsezii/quickdif/>) 
![montage00000](https://github.com/huggingface/diffusers/assets/39478211/815f2901-3247-4360-81d0-0264b2e14bcc)

If that's *not* it, you can probably still patch it in manually by performing an in-place adjustment of `pipe.scheduler.sigmas` before calling. As long as the tensor length doesn't shrink it shouldn't explode.

It would be nice to have some images attached directly to github so they aren't subject to Discord's whims

**Comment by sayakpaul** [comment]
@yiyixuxu is this still relevant?

**Comment by alexblattner** [comment]
@Beinsezii sorry for not seeing, this seems to be it, thank you!
