### ISSUE TITLE
FreeInit

### ISSUE THREAD

**Issue by a-r-r-o-w** [huggingface/diffusers#6165]
### Model/Pipeline/Scheduler description

FreeInit allows for improved temporal consistency of diffusion-based video models (for example, AnimateDiff and SVD). With no additional training requirement, it produces much higher quality videos.

Going through the code, it seems like an easy addition to current diffusers, and the results 
presented, as well as those from initial testing, are awesome!

[Youtube](https://youtu.be/lS5IYbAqriI)

<table>
<tr><th align=center colspan=2>Results</th><tr>
<tr><td colspan=2 align=center><img src="https://github.com/huggingface/diffusers/assets/72266394/59bca174-f8dc-43c7-ab34-49b2794dc44a"></td></tr>
<tr>
<th>Baseline</th>
<th>Baseline + FreeInit</th>
</tr>
<tr>
<td align=center><img src="https://github.com/huggingface/diffusers/assets/72266394/34ff677d-6f9e-48ee-a1fa-2538e23f9ac7"></td>
<td align=center><img src="https://github.com/huggingface/diffusers/assets/72266394/77445b82-524b-4ef3-b98c-5d738b023f7b"></td>
</tr>
</table>

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

[Paper](https://arxiv.org/abs/2312.07537)
[Project Page](https://tianxingwu.github.io/pages/FreeInit/)
[Code](https://github.com/TianxingWu/FreeInit)

Authors: @TianxingWu, @chenyangsi, @yumingj, @ziqihuangg, @liuziwei7

Thank you for the amazing work in this, FreeU, VideoBooth and many others! It has been very informative and motivating to learn from your work.

@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
Seems like a really cool addition. @DN6 WDYT?

**Comment by DN6** [comment]
Yeah I'm cool with adding to the AnimateDiff. Seems like the changes would be minimal.
