### ISSUE TITLE
Working offline automatically after model has downloaded

### ISSUE THREAD

**Issue by kylemcdonald** [huggingface/diffusers#6168]
I have a computer that has an unstable internet connection. When I run my diffusers script, I would like the model to download if it is not already downloaded. However, after the first time when it downloads, I would like the script to run even if the computer is offline.

I found that using [local_files_only](https://github.com/huggingface/diffusers/issues/232) allows me to specify that diffusers should not try to access the internet. (I tried using [HF_HUB_OFFLINE](https://huggingface.co/docs/diffusers/installation#cache) but it did not have any effect.)

But if I set this option as a default, the models will never download.

Is there a way to solve this automatically? Or do I need to manually set `HF_HUB_OFFLINE=False` the first time, and `HF_HUB_OFFLINE=True` every other time?

**Comment by jquintanilla4** [comment]
Yeah +1 on this. It would be good to have an automated system like what @kylemcdonald mentions.

**Comment by sayakpaul** [comment]
There are multiple options here. Probably the easiest is to load the concerned model files and pass a path to those files. This way, you can be explicitly sure about the files. 

Even without any tags set or `local_files_only=True` specified, we will try to download the files for you. Once the download is complete you can leverage `HF_HUB_OFFLINE` or `local_files_only`.

**Comment by jquintanilla4** [comment]
I often run into a similar issue that diffusers tries to download the same model over and over(on different days, no updates to the model in between), and some how I end up with a cache folder for sdxl-turbo that is 20GB. But when i run the huggingface-cli delete-cache, it only gives me the option of deleting the entire cache folder for that model.

This happens all the time. Only way to fix it is to set `local_files_only=True` after the first download.

Not sure if this is a diffusers issue or a hugging face hub issue, but it is really killing my internet and disk space.

**Comment by sayakpaul** [comment]
Cc: @Wauplin here.

**Comment by Wauplin** [comment]
> Is there a way to solve this automatically? Or do I need to manually set HF_HUB_OFFLINE=False the first time, and HF_HUB_OFFLINE=True every other time?

I'm not exactly sure about `diffusers` implementation but the general idea in `huggingface_hub` (and hence the HF ecosystem in general) is that if you use `hf_hub_download` normally (e.g. no `force_download` for instance), then:
- if connection is up and file doesn't exist locally => download it
- if connection is up and file already exist locally => make a HEAD call to check for update but do not redownload
- if connection is down and file doesn't exist locally => raise error
- if connection is down and file already exist locally => return cached file after ~10s (the time to get a timeout on the HEAD call)
- if `HF_HUB_OFFLINE=1` or  `local_files_only=True` and file doesn't exist locally => raise error
- if `HF_HUB_OFFLINE=1` or  `local_files_only=True` and file already exist locally => return cached file immediately

So if you know your connection is down, it's better to use `HF_HUB_OFFLINE` so that the library knows it doesn't have to wait a timeout or connection error. But there is no way to say `return early if already exists without checking for update`.

Now, a big difference is with `snapshot_download` which is used to download a whole repo (or at least a subset of its files). If `HF_HUB_OFFLINE` or `local_files_only` is True, it will not even try to check what are the online files. If connection is down, it will fail when listing files on the Hub (I will open a PR to fix that).

> I tried using [HF_HUB_OFFLINE](https://huggingface.co/docs/diffusers/installation#cache) but it did not have any effect.)

I don't know what "it did not have any effect" means in your case but we recently patched the underlying `huggingface_hub` library to forbid every http call once `HF_HUB_OFFLINE=1` is made. Here is the PR (https://github.com/huggingface/huggingface_hub/pull/1899). It will be shipped in next `huggingface_hub` release coming next week.

**Comment by Wauplin** [comment]
> I often run into a similar issue, in which diffusers tries to download the same model over and over(on different days, no updates to the model in between), and some how I end up with a cache folder for sdxl-turbo that is 20GB. But when i run the huggingface-cli delete-cache, it only gives me the option of deleting the entire cache folder for that model.

@jquintanilla4 this looks like a different issue. So you mean that 1. files are downloaded multiple times and 2. they are duplicated in local cache?

Could you open an issue on [huggingface_hub](https://github.com/huggingface/huggingface_hub) repo directly with the following details:
- do you use `local_folder`? `local_folder_use_symlinks`?
- in general, how do you instantiate the model? 
- which setup do you have (run `huggingface-cli env` + copy-paste output)
- how does the cache looks like? Can you run `tree -alh ~/.cache/huggingface/hub/models--stabilityai--sdxl-turbo` and `tree -alh ~/.cache/huggingface/hub/models--stabilityai--stable-diffusion-xl-base-1.0` -to be adapted depending on where your cache is-)

Thanks in advance! We will figure out a way to fix this.

**Comment by kylemcdonald** [comment]
> * if connection is down and file already exist locally => return cached file after ~10s

This would be a great solution, but I'm not getting this behavior—I get a DNS resolution error that causes a crash. I am not currently in a position to test this, but next time it happens I will try to narrow down exactly what is happening in this case, and see if I can catch the exception. If I can catch the exception, I will post about it here. Incorporating this exception into the overall internal diffusers exception management would be awesome.

**Comment by Wauplin** [comment]
>  I am not currently in a position to test this, but next time it happens I will try to narrow down exactly what is happening in this case, and see if I can catch the exception. If I can catch the exception, I will post about it here.

Thanks in advance if you can copy-paste the traceback in case of DNS resolution error so we can iterate on the exception management!

**Comment by jquintanilla4** [comment]
> @jquintanilla4 this looks like a different issue. So you mean that 1. files are downloaded multiple times and 2. they are duplicated in local cache?

1. Yes the same file is downloaded multiple times over the span of different days
2. yes they're duplicated in local cache. As you can see from my previous reply, the sdxl turbo folder is 20GB, which is larger than the 6GB the checkpoint normally is, and there hasn't been an update to the model since it was first introduced.

@Wauplin Sorry for the late reply, I was traveling. I'll run the commands you asked for tomorrow when I'm at the computer having the issue and open the issue on huggingface_hub. Thanks for your patience.

**Comment by kylemcdonald** [comment]
@Wauplin I got the error 🤗 

I'm using Google for DNS, but don't have access to the internet. However, I am using my ethernet connection fro local networking.

```
$ python test.py 
Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File ".venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File ".venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File ".venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File ".venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File ".venv/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File ".venv/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f46539ac760>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File ".venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File ".venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/stabilityai/sdxl-turbo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f46539ac760>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test/test.py", line 5, in <module>
    pipeline = DiffusionPipeline.from_pretrained(
  File ".venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1078, in from_pretrained
    cached_folder = cls.download(
  File ".venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1637, in download
    info = model_info(
  File ".venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File ".venv/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1921, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File ".venv/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File ".venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File ".venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File ".venv/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File ".venv/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/stabilityai/sdxl-turbo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f46539ac760>: Failed to resolve \'huggingface.co\' ([Errno -3] Temporary failure in name resolution)"))'), '(Request ID: c3e50b7e-6617-48f0-b944-cf0ffc613c0f)')
```

```python
from diffusers import DiffusionPipeline
import torch

pipeline = DiffusionPipeline.from_pretrained(
    "stabilityai/sdxl-turbo",
    variant="fp16",
    use_safetensors=True,
    torch_dtype=torch.float16,
).to("cuda")
```

**Comment by Wauplin** [comment]
@kylemcdonald thanks for reporting the stacktrace! Will work on a fix to default to local folder in such a case. Will be possible thanks to the latest release of `huggingface_hub` (from yesterday). I'll keep you updated about it.

**Comment by JuliusJacobsohn** [comment]
May I ask - why isn't the default behaviour to look for the required files locally, and if they don't exist, then (and only then) make a network call? I feel like this is the much more straightforward approach. I do not understand why an internet connection is required to run a local model.

**Comment by sayakpaul** [comment]
You can specify `local_files_only=True` and we won't make a call to the internet.

**Comment by Wauplin** [comment]
>  why isn't the default behaviour to look for the required files locally, and if they don't exist, then (and only then) make a network call?

This is because we can't know before-hand if the model has been updated on the Hub or not. If models were 1-time immutable artifacts, then we wouldn't need to make an HTTP call to run a model. Note that we reduced the number of calls to the minimum (1) and as @sayakpaul said, there are ways to completely avoid checking for updates.

**Comment by roboraSimon** [comment]
> This is because we can't know before-hand if the model has been updated on the Hub or not.

I believe there's a questionable assumption in there... That everyone will always want to use vLatest as opposed to having a fixed version they can develop against without surprises.

For the research side of the fence, that's _probably_ true, but for anyone trying to use these models in an operational deployed system, predictability and reliability often trump shiny newness.
