### ISSUE TITLE
[New Pipeline]: DeepCache: Accelerating Diffusion Models for Free

### ISSUE THREAD

**Issue by kadirnar** [huggingface/diffusers#6193]
Repo: https://github.com/horseee/DeepCache
Project Page: https://horseee.github.io/Diffusion_DeepCache/

@patrickvonplaten @sayakpaul

I tested it locally and it is a very fast pipeline. But I need help adding it to the diffusers library. Should I add this to the community pipeline section?

I just need to update the unet class.

https://github.com/horseee/DeepCache/tree/master/DeepCache/sdxl

**Comment by sayakpaul** [comment]
It's indeed quite fast. 

I am happy to support it via a community pipeline first.

**Comment by sayakpaul** [comment]
Actually, on second thought, I think it should be a part of the core offerings from `diffusers`. 

I quickly skimmed through the [codebase](https://github.com/horseee/DeepCache), and the changes seem fairly simple enough to be incorporated. Given the speedup it achieves, I feel relatively strongly about making it a core feature. 

Some thoughts about the design are below. 

In the original codebase, the authors rely on the call and forward arguments of the pipeline and the UNet, respectively, to implement DeepCache. I wonder if it makes sense to follow that or rather do it in a way similar to how we did FreeU i.e., via enable and disable methods. 

I think following the original implementation strategy from the authors is a better choice here as the DeepCache arguments are better experimented like that. Users would experiment with values like `cache_interval`, `cache_layer_id`, etc., and then settle with the values as per their needs. With an enable/disable design, we might have to call the corresponding disable method first to be able to properly set the DeepCache arguments. 

Wonder what others think here. Cc: @yiyixuxu @patrickvonplaten @DN6.

**Comment by horseee** [comment]
Hi @sayakpaul @kadirnar ,

We have a [new implementation](https://github.com/horseee/DeepCache/blob/master/DeepCache/extension/deepcache.py) that doesn't require any modifications to the forward function and its arguments. Now DeepCache can be toggled on or off using an external helper. Here is an example:

```python
from diffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_pretrained('runwayml/stable-diffusion-v1-5', torch_dtype=torch.float16).to("cuda:0")

from DeepCache import DeepCacheSDHelper
helper = DeepCacheSDHelper(pipe=pipe)
helper.set_params(
    cache_interval=3,
    cache_branch_id=0,
)
helper.enable()

deepcache_image = pipe(
        prompt,
        output_type='pt'
).images[0]
helper.disable()
```

We test upon three pipelines: StableDiffusionPipeline, StableDiffusionXLPipeline, StableVideoDiffusionPipeline. We've successfully tested the new implementation across three different pipelines, and I'm happy to report that it performs consistently well. The results are in line with those from our previous version of implementation.

Here is a quick review of the results:

* StableDiffusionPipeline (SD1.5):  Left: Original Pipeline (2.57s) / Right: + DeepCache (1.11s)

<img width="500" alt="image" src="https://github.com/huggingface/diffusers/assets/22924514/ef067907-4780-45e8-9a8a-3933277f45e9">

* StableDiffusionXLPipeline:  Left: Original Pipeline (12.93s) / Right: + DeepCache (5.26s)

<img width="500" alt="image" src="https://github.com/huggingface/diffusers/assets/22924514/8f376619-2840-4f14-a04d-a952a87341cb">

* StableVideoDiffusion: Left: Original Pipeline (97.16s) / Right: + DeepCache (58.35s)

<img width="500" alt="image" src="https://github.com/huggingface/diffusers/assets/22924514/2a737401-1805-4272-87d0-227039ed367b">



I'm wondering about the feasibility of integrating this implementation of DeepCache into Diffusers. Looking forward to any insights or suggestions on this!

**Comment by jorgemcgomes** [comment]
@horseee I was testing this new implementation of deepcache (very easy to use, just copy paste a small file and import the helper 👍 ), and I'm getting different results. The speedups are indeed very impressive (2-3x faster), but the quality nowhere close to the original.
All results below using a fixed seed. The model is a fine-tune of SD 2.1 (can't share). Tried with both Euler-A and UniPC schedulers -- similar issues. 25 steps.

No deepcache:
![image](https://github.com/huggingface/diffusers/assets/3987574/608667bd-89fb-4bbe-b29a-0e55631fe2f2)

With deepcache (cache_interval=3):
![image](https://github.com/huggingface/diffusers/assets/3987574/4f8807e7-25f9-4804-b899-01593a430730)

With cache_interval=2 things look significantly better, but still far from lossless:
![image](https://github.com/huggingface/diffusers/assets/3987574/9fbe6d21-836c-4bb9-86f1-eca150830db8)

I still think the results are pretty decent for the amount of speedup it provides, but calling it "nearly lossless" is a stretch...

**Comment by sayakpaul** [comment]
> All results below using a fixed seed. The model is a fine-tune of SD 2.1 (can't share). Tried with both Euler-A and UniPC schedulers -- similar issues. 25 steps.

Does this observation still stand with the default SD 2.1? That question essentially helps us answer if the behaviour of DeepCache is sensitive to fine-tunes (although it shouldn't be).

**Comment by sayakpaul** [comment]
@horseee thank you so much for your efforts here!

I think to truly honor your efforts, we'd like to refer the users to your great repository. We do the same for token merging too: https://huggingface.co/docs/diffusers/main/en/optimization/tome. Would this be okay for you?

**Comment by horseee** [comment]
> > All results below using a fixed seed. The model is a fine-tune of SD 2.1 (can't share). Tried with both Euler-A and UniPC schedulers -- similar issues. 25 steps.
> 
> Does this observation still stand with the default SD 2.1? That question essentially helps us answer if the behaviour of DeepCache is sensitive to fine-tunes (although it shouldn't be).

Hi all, here are our results on the default pipeline of SD2.1: 

Left: Original Pipeline (2.3s) / Right: + DeepCache (1.0s)
<img width="800" alt="image" src="https://github.com/huggingface/diffusers/assets/22924514/7d7d0e24-d986-48e3-8ae1-b6901ab9244d">

**Comment by horseee** [comment]
> @horseee thank you so much for your efforts here!
> 
> I think to truly honor your efforts, we'd like to refer the users to your great repository. We do the same for token merging too: https://huggingface.co/docs/diffusers/main/en/optimization/tome. Would this be okay for you?

Yes! It is good for me😄  

Would it be okay if I prepare the documentation and then submit a Pull Request for review?

**Comment by sayakpaul** [comment]
Yes, let's do that :)

**Comment by jorgemcgomes** [comment]
@horseee This caught my curiosity so I tested this in an isolated environment, everything as default as possible.
Still couldn't replicate your good results. 

With the default pipeline, there are some clear differences in some image pairs (see for instance last image where the astronaut is not riding the horse with DeepCache).
With a different scheduler and lower inference steps, the differences seem larger and definitely worse.

I'm going out on a limb here and hypothesise that this approach only works well with high step counts.
Which would not be very interesting for a lot of use cases, since we already have schedulers that can deliver excellent results with very low step counts.

# default pipeline (DDIM 50 steps)

Deepcache disabled
![image](https://github.com/huggingface/diffusers/assets/3987574/830bae3b-1fb3-4837-92ca-27b553f8871d)

Deepcache enabled
![image](https://github.com/huggingface/diffusers/assets/3987574/01f0bf57-bf32-41db-9205-a58247d36593)

# 20 steps and UniPC

Deepcache disabled
![image](https://github.com/huggingface/diffusers/assets/3987574/fef928b4-67d7-4da2-9295-07c3d5140286)

Deepcache enabled
![image](https://github.com/huggingface/diffusers/assets/3987574/cb361ccc-2015-4a1a-9e52-14b8044e76c2)

**Comment by sayakpaul** [comment]
We have an entire doc page dedicated to DeepCache: https://huggingface.co/docs/diffusers/main/optimization/deepcache

**Comment by 973398769** [comment]
I would like to understand when I should enable and when I should disable it. Is it necessary to disable after every inference, and should I enable it before starting a new inference?

**Comment by 973398769** [comment]
我想了解一下什么时候应该enable 什么时候disable， 是不是每次推理之后是不是需要disable， 新的一个推理开始之前要enable？

**Comment by asomoza** [comment]
probably best if you test it yourself, but probably you don't need to disable it if you're going to use it on all the generations, just disable when you don't want to use it anymore, same for enabling it.

**Comment by 973398769** [comment]
This is my current setup: helper.set_params(cache_interval=3, cache_branch_id=0). When processing a large amount of images, I've noticed some quality degradation, but I'm not sure if it's caused by DeepCache.
