### ISSUE TITLE
Question about SDXL controlnet image size condition

### ISSUE THREAD

**Issue by GongXinyuu** [huggingface/diffusers#6203]
The original SDXL is using original image size and cropped image size for condition. Why does controlnet SDXL directly use the resized image resolution as the condition information as below?

https://github.com/huggingface/diffusers/blob/9cef07da5a1f28ddfeadd232ede9a815c7945aec/examples/controlnet/train_controlnet_sdxl.py#L970

**Comment by sayakpaul** [comment]
Yeah should have been the original size as done in https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py. Would you be open to creating a PR?

**Comment by GongXinyuu** [comment]
> Yeah should have been the original size as done in https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py. Would you be open to creating a PR?

Got it, I'm happy to do that.
