### ISSUE TITLE
what's the difference between StableDiffusionInstructPix2PixPipeline and StableDiffusionImg2ImgPipeline

### ISSUE THREAD

**Issue by Emberss** [huggingface/diffusers#6204]
I don't know the difference between these two pipeline, since they are used to generate image by  image, prompt. could you tell me the difference, thanks a lot!!

**Comment by sayakpaul** [comment]
The internals as to how they work and formulate the reverse diffusion process.

**Comment by Emberss** [comment]
> The internals as to how they work and formulate the reverse diffusion process.

I compared the two pipelines, and didn't find internals difference, are these two pipeline redundant?
