### ISSUE TITLE
Flax: trickle down `norm_num_groups`

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#621]
`FlaxEncoder` receives it [here](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/vae_flax.py#L326), but then it's ignored.

`FlaxResnetBlock2D` uses a [hardcoded value](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/vae_flax.py#L99).

Discovered by @younesbelkada in https://github.com/huggingface/diffusers/pull/589#discussion_r975796548

**Comment by patrickvonplaten** [comment]
Good point! Not sure how urgent at is but let's make sure we don't forget about it

**Comment by pcuenca** [comment]
Maybe appropriate for hacktoberfest?

**Comment by akash5474** [comment]
Hello @pcuenca and @patrickvonplaten , I would like to try to take on this issue if that's alright.

**Comment by patrickvonplaten** [comment]
Hey @akash5474,

This would be great!
