### ISSUE TITLE
[Examples] How much time you support training scripts of text to video in diffusers?

### ISSUE THREAD

**Issue by jiaxiangc** [huggingface/diffusers#6211]
I want to train svd in diffusers, can you support this feature in examples.
Thanks for your contributions.

**Comment by sayakpaul** [comment]
SVD's training code isn't itself open. So, no plans yet. I suggest you check out other repositories that show how to train video models:

https://github.com/showlab/Awesome-Video-Diffusion is cool repository that lists them out.
