### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co' 

### ISSUE THREAD

**Issue by alirezaomneky** [huggingface/diffusers#6223]
Hi all,

I have pushed the weights of my Dreambooth model to Huggingface (I used LoRa model). I confirm that pytorch_lora_weights.safetensors is indeed on Huggingface. When I want to get inference from the model, I run the following (as per the Readme file):

`from huggingface_hub.repocard import RepoCard
from diffusers import DiffusionPipeline
import torch

lora_model_id = <"lora-sdxl-dreambooth-id">
card = RepoCard.load(lora_model_id)
base_model_id = card.data.to_dict()["base_model"]

pipe = DiffusionPipeline.from_pretrained(base_model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")
pipe.load_lora_weights(lora_model_id)
image = pipe("A picture of a sks dog in a bucket", num_inference_steps=25).images[0]
image.save("sks_dog.png")`

But I keep getting this error:

OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like "_path_" is not the path to a directory containing a file named pytorch_lora_weights.safetensors or 
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

Can you please let me know how to resolve this issue?

**Comment by sayakpaul** [comment]
Can you try now? Make sure the internet connection is stable. Or if you don't want to rely on that, download the files once and use the offline mode.

**Comment by alirezaomneky** [comment]
> Can you try now? Make sure the internet connection is stable. Or if you don't want to rely on that, download the files once and use the offline mode.

Hi @sayakpaul , I solved the problem by using the following:

`!pip install -q diffusers transformers accelerate peft`

It appears that when the weights are stored in LFS format on Huggingface, we can't simply use the path to the file.

**Comment by sayakpaul** [comment]
Closing the issue then :) Glad that you were able to resolve the problem.

**Comment by swerizwan** [comment]
https://blog.csdn.net/m0_46295727/article/details/133221439

**Comment by askerlee** [comment]
I also encountered this error. Turned out I accidentally set TRANSFORMERS_OFFLINE to 1. Setting it to 0 solves the issue.

**Comment by premmotgi** [comment]
> I also encountered this error. Turned out I accidentally set TRANSFORMERS_OFFLINE to 1. Setting it to 0 solves the issue.
Thanks a ton! This fixed my issue

**Comment by pavoltravnik** [comment]
When i generated token i created wrong type
Create a new access token Type Read instead of default Fine-grained (custom)

**Comment by MHRDYN7** [comment]
> When i generated token i created wrong type Create a new access token Type Read instead of default Fine-grained (custom)

Yes, and the "Write" type also works

**Comment by jsale017** [comment]
> I also encountered this error. Turned out I accidentally set TRANSFORMERS_OFFLINE to 1. Setting it to 0 solves the issue.

How were you able to change this?

**Comment by paluchasz** [comment]
> > I also encountered this error. Turned out I accidentally set TRANSFORMERS_OFFLINE to 1. Setting it to 0 solves the issue.
> 
> How were you able to change this?

<img width="376" alt="image" src="https://github.com/huggingface/diffusers/assets/10106237/b10f91d6-930f-4ed5-b1e7-c7ced17d618b">

**Comment by JAYWARDZ** [comment]
I'm a dingling and didn't read the documentation but it helped to Install HF. If not installed the error throw was: 

Error:
RuntimeError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like unsloth/llama-3-8b is not the path to a directory containing a file named config.json.

(My, A) Soln:
pip install --upgrade huggingface_hub 
#and then install the dependencies for tensorflow, torch and cli 
pip install 'huggingface_hub[tensorflow]' 
pip install 'huggingface_hub[cli,torch]'

**Comment by FRAGGERR** [comment]
Try this one: 
`!pip install -U transformers`

`import torch
from transformers import AutoModel, AutoTokenizer, BertTokenizer

torch.set_grad_enabled(False)`

`# Store the model we want to use
MODEL_NAME = "bert-base-cased"

# We need to create the model and tokenizer
model = AutoModel.from_pretrained(MODEL_NAME)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)`

**Comment by Lareina2441** [comment]
> 您可以设置 hf 镜像来解决 huggingface.co 互联网连接问题。 试试这个：
> 
> `export HF_ENDPOINT=https://hf-mirror.com`

thanks， this works

**Comment by marinarosell** [comment]
> When i generated token i created wrong type Create a new access token Type Read instead of default Fine-grained (custom)

This fixed the issue for me!!

**Comment by jayquincey** [comment]
> When i generated token i created wrong type Create a new access token Type Read instead of default Fine-grained (custom)

Dude, you're a frikkin genius! Would never have guessed my read-only token would work but my fine-grained dev token with read and write would result in connection error!!

Thanks a million.

**Comment by Jurio0304** [comment]
> You can set hf mirror to fix the huggingface.co internet connection problem. Try this:
> 
> `export HF_ENDPOINT=https://hf-mirror.com`

Thanks!

**Comment by nkilm** [comment]
Setting `TRANSFORMERS_OFFLINE` variable to `'0'` resolved this issue in my case. Attaching the code for your reference,

```python3
import os
from langchain import HuggingFaceHub
from dotenv import load_dotenv

from langchain_huggingface.llms import HuggingFacePipeline

load_dotenv() # hf token is in .env
os.environ['TRANSFORMERS_OFFLINE'] = '0'

hf = HuggingFacePipeline.from_model_id(
    model_id="gpt2",
    task="text-generation",
    pipeline_kwargs={"max_new_tokens": 100},
)

hf.invoke("hi")
```

Also in my case, I didn't have a _read_ token, _fine-grained_ access token worked out for me. 

![Image](https://github.com/user-attachments/assets/3a98e340-ee46-4d59-a967-c31ec312c09f)

**Comment by Guangfa-Tang** [comment]
> You can set hf mirror to fix the huggingface.co internet connection problem. Try this:
> 
> `export HF_ENDPOINT=https://hf-mirror.com`

great! It works! 
Thanks pretty much!!!!!

**Comment by Wlzzzz-del** [comment]
> When i generated token i created wrong type Create a new access token Type Read instead of default Fine-grained (custom)

Cheers mate! You quickly solved my problem!!!
