### ISSUE TITLE
convert_diffusers_to_original_stable_diffusion.py causing loading errors in stable-diffusion-webui

### ISSUE THREAD

**Issue by georgesung** [huggingface/diffusers#6226]
### Describe the bug

The latest [change](https://github.com/huggingface/diffusers/commit/6976cab7caa959bff46896c52ec03d9d414fc689) to scripts/convert_diffusers_to_original_stable_diffusion.py causes the following errors when loading the .safetensors file in stable-diffusion-webui:

```
RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
        size mismatch for first_stage_model.encoder.mid.attn_1.q.bias: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for first_stage_model.encoder.mid.attn_1.k.bias: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for first_stage_model.encoder.mid.attn_1.v.bias: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for first_stage_model.encoder.mid.attn_1.proj_out.bias: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for first_stage_model.decoder.mid.attn_1.q.bias: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for first_stage_model.decoder.mid.attn_1.k.bias: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for first_stage_model.decoder.mid.attn_1.v.bias: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for first_stage_model.decoder.mid.attn_1.proj_out.bias: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512]).
```

After reverting the above change, the conversion script (convert_diffusers_to_original_stable_diffusion.py) produces a .safetensors file that works as before with no errors when loading it from stable-diffusion-webui.

### Reproduction

```
python diffusers/scripts/convert_diffusers_to_original_stable_diffusion.py \
  --model_path="./model_trained_with_diffusers" \
  --checkpoint_path="./x.safetensors" \
  --use_safetensors

mv x.safetensors $path_to_stable-diffusion-webui_model
```

Then try to load the model in stable-diffusion-webui

### System Info

- `diffusers` version: 0.23.0
- Platform: Linux-6.2.0-39-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.30.2
- Accelerate version: 0.21.0
- xFormers version: 0.0.20
- Using GPU in script?: yes?
- Using distributed or parallel set-up in script?: no

**Comment by sayakpaul** [comment]
@d8ahazard could you take a look?

**Comment by satani99** [comment]
@georgesung have you got any solution to this? I've also encountered the same error.

**Comment by georgesung** [comment]
> @georgesung have you got any solution to this? I've also encountered the same error.

Not yet, I just use the previous version of the script before the update: https://github.com/huggingface/diffusers/blob/a7ca03aa85f94574f06576d2155b3ec061fe8d63/scripts/convert_diffusers_to_original_stable_diffusion.py
