### ISSUE TITLE
train_text_to_image_sdxl.py report cuda of out memory

### ISSUE THREAD

**Issue by chongxian** [huggingface/diffusers#6230]
I use the V100 to train, when I use the command`
accelerate launch train_text_to_image_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --pretrained_vae_model_name_or_path=$VAE_NAME \
  --dataset_name=$DATASET_NAME \
  --enable_xformers_memory_efficient_attention \
  --resolution=512 --center_crop --random_flip \
  --proportion_empty_prompts=0.2 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 --gradient_checkpointing \
  --max_train_steps=10000 \
  --use_8bit_adam \
  --learning_rate=1e-06 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --mixed_precision="fp16" \
  --report_to="wandb" \
  --validation_prompt="a cute Sundar Pichai creature" --validation_epochs 5 \
  --checkpointing_steps=5000 \
  --output_dir="sdxl-pokemon-model" \`
  export the error about cuda of out memory, Does running this script require 40GB of video memory?

**Comment by sayakpaul** [comment]
Yes. You should try using the LoRA version of that script. 

https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb runs perfectly on a free-tier Colab.

**Comment by chongxian** [comment]
> Yes. You should try using the LoRA version of that script.
> 
> https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb runs perfectly on a free-tier Colab.

Thanks for your reply.
