### ISSUE TITLE
generator/seed logic with multiple images

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#6233]
When you set a seed on a single image, you can reproduce easily with the same generator. However, if you produced it from a batch of images, if it isn't the first one, you won't be able to reproduce it without making a batch. What's the seed logic in batches of images?

**Comment by sayakpaul** [comment]
Can you provide some sample code to more objectively characterize the issue?

Cc: @yiyixuxu as well.

**Comment by alexblattner** [comment]
bump

**Comment by patrickvonplaten** [comment]
@alexblattner please refrain from adding `bump` messages (as said before). 

> When you set a seed on a single image, you can reproduce easily with the same generator. However, if you produced it from a batch of images, if it isn't the first one, you won't be able to reproduce it without making a batch. What's the seed logic in batches of images?

Is not enough as an issue description to lead to anything actionable. Please make sure to always provide a reproducible code snippet - we don't have time to guess what is meant

**Comment by alexblattner** [comment]
@patrickvonplaten 

```
pipe = StableDiffusionPipeline.from_single_file(
        "./custom.safetensors",
)
generator = torch.Generator(device="cpu").manual_seed(1)
images=pipe("a beautiful park", num_images_per_prompt=4,generator=generator).images
num=0
for i in images:
  i.save(f"img{num}.png")
  num+=1
```

what seed am I supposed to use here to get img2.png?

```
pipe = StableDiffusionPipeline.from_single_file(
        "./custom.safetensors",
)
generator = torch.Generator(device="cpu").manual_seed(??????)
images=pipe("a beautiful park", num_images_per_prompt=1,generator=generator).images
num=0
for i in images:
  i.save(f"img{num}.png")
  num+=1
```

This is not an issue, just a clarification on the implementation

**Comment by alexblattner** [comment]
I made an additional test. 

```
pipe = StableDiffusionPipeline.from_single_file(
        "./custom.safetensors",
)
generator = [torch.Generator(device="cpu").manual_seed(1),torch.Generator(device="cpu").manual_seed(2)]
images=pipe("a beautiful park", num_images_per_prompt=1,generator=generator).images
num=0
for i in images:
  i.save(f"img{num}.png")
  num+=1
```
here we should have 2 pictures with seed 1 and 2, however here:
```
pipe = StableDiffusionPipeline.from_single_file(
        "./custom.safetensors",
)
generator = [torch.Generator(device="cpu").manual_seed(2),torch.Generator(device="cpu").manual_seed(3)]
images=pipe("a beautiful park", num_images_per_prompt=1,generator=generator).images
num=0
for i in images:
  i.save(f"img{num}.png")
  num+=1
```
we get pictures with seed 2 and 3, but none of the pictures are similar to the previous test....

@patrickvonplaten
