### ISSUE TITLE
Dreambooth + local background image?

### ISSUE THREAD

**Issue by alirezaomneky** [huggingface/diffusers#6235]
Hi all,

I have trained a Dreambooth model on a specific object (product). Now for inference, I want to use my own background photos (not the ones that are generated by the model). So basically I want to load my local background photo, and ask the trained Dreambooth model to place the object (that it has been trained on) on my the background photo (without generating background photo by model).
Is this possible?

**Comment by sayakpaul** [comment]
This is a conceptual question. Please use the Discord forum for this: hf.co/join/discord.
