### ISSUE TITLE
Issue with SDXL VAE

### ISSUE THREAD

**Issue by vidit98** [huggingface/diffusers#6238]
### Describe the bug

When I try to read an image and encode it with VAE encoder and decode I get a significantly different image. I followed the encoding from SDXL training script and decoding from SDXL pipeline.

### Reproduction

```
from diffusers import StableDiffusionXLPipeline
from PIL import Image
import torch

def vae():
    pipe = StableDiffusionXLPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0",
                                                     safety_checker=None,
                                                     torch_dtype=torch.float32)
    pipe.to("cuda")

    url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/coco_sample.png"
    image_data = requests.get(url, stream=True).raw
    image = Image.open(image_data)
    image = image.resize((1024, 1024))
    image = torch.tensor(np.array(image)).reshape(1, 3, 1024, 1024).float() / 255

    image = pipe.image_processor.preprocess(image).cuda()
    image = image.to(memory_format=torch.contiguous_format).float()
    init_latents = pipe.vae.encode(image)
    if hasattr(init_latents, "latent_dist"):
        init_latents = init_latents.latent_dist.sample()
        print("Init latent")
    init_latents = init_latents * pipe.vae.config.scaling_factor
    init_latents = init_latents.to(torch.float32)

    init_latents = init_latents / pipe.vae.config.scaling_factor
    image = pipe.vae.decode(init_latents.float(), return_dict=False)[0]
    image = pipe.image_processor.postprocess(image.detach().float())[0]
    image.save(f'0.png')
```

### System Info

- `diffusers` version: 0.25.0.dev0
- Platform: Linux-5.4.254-170.358.amzn2.x86_64-x86_64-with-glibc2.17
- Python version: 3.8.18
- PyTorch version (GPU?): 2.0.1 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@sya @DN6 @yiyixuxu

**Comment by sayakpaul** [comment]
Can you check if the pixel value range is within [-1, 1] before the image is passed to the VAE for encoding? 

Also, I would suggest checking out https://github.com/madebyollin/taesd/blob/main/examples/Previewing_During_Image_Generation.ipynb for a better handle on how this visualization should be done.

**Comment by vidit98** [comment]
Yes they are between [-1, 1] . I followed the code [here](https://github.com/huggingface/diffusers/blob/54339629927bffafe810b312c2f3526c67a52324/examples/text_to_image/train_text_to_image_sdxl.py#L525) for encoding and the code[here](https://github.com/huggingface/diffusers/blob/54339629927bffafe810b312c2f3526c67a52324/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L1264) for decoding. From testing on different images it looks like some problem with reshape operation or similar. I am attaching the input and output image below. Input image can also be found at  https://i.ibb.co/10jgZX6/Gaussian.png
![Gaussian](https://github.com/huggingface/diffusers/assets/22493755/c9ab0fb2-05ab-4ea9-bdd1-5429f01556de)
![0](https://github.com/huggingface/diffusers/assets/22493755/f7e76a07-c575-4687-8d32-270e2884c2cb)

I also checked the link but it seems they do not have sampling in VAE encoder though my flow is similar to them. If there is any code which uses diffusers VAE for encoding decoding it would be great.
