### ISSUE TITLE
Can you provide the log with fill50k dataset?  

### ISSUE THREAD

**Issue by dulibubai** [huggingface/diffusers#6242]
### Describe the bug

I did as the readme, but the result with fill50k model is not so good as the result in the git

### Reproduction

I did as the readme, but the result with fill50k model is not so good as the result in the git

### System Info

------

### Who can help?

@

**Comment by sayakpaul** [comment]
This is not a library-related question. Please use the Discord forum forum for that: https://hf.co/join/discord. 

Please also provide what script are you using, what are your hyperparameters, etc.
