### ISSUE TITLE
MotionAdapter.from_single_file

### ISSUE THREAD

**Issue by eps696** [huggingface/diffusers#6248]
### Model/Pipeline/Scheduler description

`Animatediff` is a great technique with exploding interest and advancements; additional custom models start popping around in `ckpt` format, which cannot be loaded to `diffusers` in the meantime. 
is it possible to implement `from_single_file` function for motion adapter, similar to how it's done now for say `controlnet`?

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by DN6** [comment]
Hi @eps696 this is definitely something we can consider. We're working on a clean up of `from_single_file` at the moment so it might take a bit of time. Could you point me to these new checkpoints? I can see if there's a way to convert them to diffusers format as an intermediate solution.

**Comment by eps696** [comment]
thanks for a prompt response! here is few examples:
https://github.com/Lightricks/LongAnimateDiff
https://huggingface.co/guoyww/animatediff/tree/main [see v3 versions]

**Comment by rishabhjain** [comment]
Agree that from_single_file method will be helpful. Since animatediff was added to diffusers, new versions for SD as well as SDXL has been released. But unable to use them, as from_single_file isn't supported and those new models are usually a single .ckpt files.

**Comment by vladmandic** [comment]
@yiyixuxu @DN6 
not sure why gh bot chose to close this as stale label was removed?

**Comment by eps696** [comment]
+1, just yesterday tried fresh release - from_single_file not implemented yet for motion adapter

**Comment by yiyixuxu** [comment]
ohh sorry 😱 I didn't know it does that 
>not sure why gh bot chose to close this as stale label was removed?

**Comment by DN6** [comment]
Hi @eps696 have you tried using the AnimateDiff conversion scripts with those checkpoints? 

https://github.com/huggingface/diffusers/blob/main/scripts/convert_animatediff_motion_module_to_diffusers.py
https://github.com/huggingface/diffusers/blob/main/scripts/convert_animatediff_motion_lora_to_diffusers.py

**Comment by eps696** [comment]
> Hi @eps696 have you tried using the AnimateDiff conversion scripts with those checkpoints?

no, missed it somehow, thanks for a hint!

**Comment by vladmandic** [comment]
ping to remove stale status.

**Comment by yiyixuxu** [comment]
@DN6 
I think this is not supported yet with the new `from_single_file` - do we plan to support it? should we ask community to help?

**Comment by DN6** [comment]
Yes we can 👍🏽 Was planning on adding the support this week, but definitely a good one for the community as well.

**Comment by vladmandic** [comment]
ping to remove stale status.

**Comment by vladmandic** [comment]
ping to remove stale status.

**Comment by DN6** [comment]
Hi @vladmandic we merged #8819 with single file support for MotionAdapter a little while back.

**Comment by DN6** [comment]
Closing since this has been completed.
