### ISSUE TITLE
Do from_config and from_pretrained Generate the Same DDIMScheduler?

### ISSUE THREAD

**Issue by jundanl** [huggingface/diffusers#6253]
Hi,

I'm a bit confused about how from_config and from_pretrained work in the Scheduler, especially for the DDIM Scheduler. When I load a scheduler from a pre-trained model like Stable Diffusion, are these two methods basically doing the same thing / generating the same instance? I mean, if the generated DDIM schedulers have exactly the same parameters. 

An example is:
```
scheduler_A = DDIMScheduler.from_pretrained(<model>, subfolder="scheduler")

pipe = StableDiffusionPipeline.from_pretrained(<model>)
scheduler_B = DDIMScheduler.from_config(pipe.scheduler.config)
```
Are scheduler_A and scheduler_B always the same?

Also, are they doing the same for a model? (The function names make me think from_config only defines structures but from_pretrained also loads parameter weights.)

I've seen some scripts using from_config and others using from_pretrained. I get that from_config needs a config object and from_pretrained requires a model ID or path. 

Also, if this is the case for the DDIM Scheduler, is it the same for other types of schedulers? Is there anything special I should keep in mind?

Thanks a lot!

**Comment by sayakpaul** [comment]
`from_config()` lets you initialize a scheduler from an existing scheduler configuration. For example:

```python
pipeline = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config)
```

This applies to all the schedulers. Does this help?

**Comment by jundanl** [comment]
> `from_config()` lets you initialize a scheduler from an existing scheduler configuration. For example:
> 
> ```python
> pipeline = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
> pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config)
> ```
> 
> This applies to all the schedulers. Does this help?

Thank you for the reply!
To make it clear, I write an example here:
`
scheduler_A = DDIMScheduler.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="scheduler")

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
scheduler_B = DDIMScheduler.from_config(pipe.scheduler.config)
`
Are scheduler_A and scheduler_B the same?

**Comment by sayakpaul** [comment]
That you can independently test.

**Comment by patrickvonplaten** [comment]
> Are scheduler_A and scheduler_B always the same?

@jundanl yes

**Comment by sayakpaul** [comment]
Can we close this issue now? Also, in the future, feel free to open a thread on Discussions instead.
