### ISSUE TITLE
Stable Video Diffusion Pipeline: forward chunking degrades image quality

### ISSUE THREAD

**Issue by BlakeOne** [huggingface/diffusers#6258]
### Describe the bug

When using the Stable Video Diffusion Pipeline with forward chunking enabled the generated video is very noisy. Below is the example code that I'm using (from the official example at https://huggingface.co/docs/diffusers/main/en/using-diffusers/svd). When the code to enable forward chunking is commented out the quality is restored.

### Reproduction

import torch

from diffusers import StableVideoDiffusionPipeline
from diffusers.utils import load_image, export_to_video

pipe = StableVideoDiffusionPipeline.from_pretrained(
  "stabilityai/stable-video-diffusion-img2vid-xt", torch_dtype=torch.float16, variant="fp16"
)
pipe.enable_model_cpu_offload()

# Comment out this line and the quality is restored
pipe.unet.enable_forward_chunking()

image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png?download=true")
image = image.resize((1024, 576))

generator = torch.manual_seed(42)
frames = pipe(image, decode_chunk_size=2, generator=generator, motion_bucket_id=180, noise_aug_strength=0.1).frames[0]
export_to_video(frames, "generated.mp4", fps=7)

### System Info

Tested on Google Colab with latest diffusers, transformers, and accelerate packages installed.

**Comment by sayakpaul** [comment]
Cc: @DN6

**Comment by DN6** [comment]
@BlakeOne I was able to reproduce. Taking a look into why this is happening.

**Comment by DN6** [comment]
@BlakeOne should be fixed with #6350

**Comment by BlakeOne** [comment]
Hey @DN6, thanks for looking into this. :) From my testing, enabling forward chunking now results in a slight *increase* in GPU RAM usage whereas previously it resulted in the desired *decrease*. Could you please try comparing the GPU RAM usage before and after the merged PR if you haven't yet?

**Comment by DN6** [comment]
Hi @BlakeOne could you share a code example that I can use to test please?

**Comment by BlakeOne** [comment]
NP, my first post has a copy of the test code from the official example and here's a simple [Colab notebook](https://colab.research.google.com/github/BlakeOne/diffusers_fork/blob/Test-SVD/colab_test.ipynb) that has the same code for testing. You can restart the session each time you run the test cell to get the GPU usage back down to zero...

**Comment by BlakeOne** [comment]
Actually this might be a separate issue? Lemme know if you want me to close this one and open a new one for the GPU RAM usage. :)

**Comment by DN6** [comment]
Hi @BlakeOne yes please. Could you open a separate issue for the GPU RAM usage.
