### ISSUE TITLE
StableDiffusionXLControlNetImg2ImgPipeline has no "from_single_file"

### ISSUE THREAD

**Issue by andypotato** [huggingface/diffusers#6280]
### Describe the bug

As stated in the title, `StableDiffusionXLControlNetImg2ImgPipeline` currently does not support `from_single_file`. It will fail with:
```
AttributeError: type object 'StableDiffusionXLControlNetImg2ImgPipeline' has no attribute 'from_single_file'
```

### Reproduction

Try creating a StableDiffusionXLControlNetImg2ImgPipeline.from_single_file([...]) will fail with 

### System Info

- `diffusers` version: 0.21.4
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.1
- Accelerate version: 0.24.0
- xFormers version: not installed

### Who can help?

@saya

**Comment by sayakpaul** [comment]
That is because there are no single file checkpoints available for SDXL ControlNet to our knowledge.

**Comment by andypotato** [comment]
This should load the SDXL checkpoint, not the ControlNet checkpoint, sorry if that was misleading.

For reference, this is working as expected:
`StableDiffusionXLControlNetPipeline.from_single_file('sdxl-model.safetensors')`

This however is not working and produces the error mentioned above:
`StableDiffusionXLControlNetImg2ImgPipeline.from_single_file('sdxl-model.safetensors')`

**Comment by sayakpaul** [comment]
Cc: @DN6

**Comment by DN6** [comment]
Hi @andypotato the single file mixin isn't implemented for the pipeline. We will need to add it. 

Would you be able to open a PR for it?

**Comment by SlZeroth** [comment]
same issue!

**Comment by DN6** [comment]
Hi @SlZeroth as mentioned above, that pipeline doesn't have the single file mixin implemented. Would you like to open a PR to add it?

**Comment by SlZeroth** [comment]
@DN6 Ok I will open PR with override mixin !

**Comment by sayakpaul** [comment]
Seems like not stale?

**Comment by SlZeroth** [comment]
create new PR!

https://github.com/huggingface/diffusers/pull/7353
