### ISSUE TITLE
StableDiffusionXLControlNetImg2ImgPipeline can not use (strength = 0)

### ISSUE THREAD

**Issue by andypotato** [huggingface/diffusers#6283]
### Describe the bug

When I create a `StableDiffusionXLControlNetImg2ImgPipeline` and set the strength parameter to zero (0.0) I will receive the following error message:
```
cannot reshape tensor of 0 elements into shape [0, -1, 1, 512] because the unspecified dimension size -1 can be any value and is ambiguous
WARNING:root:cannot reshape tensor of 0 elements into shape [0, -1, 1, 512] because the unspecified dimension size -1 can be any value and is ambiguous
```

Using any other values != zero will work without problems and give the expected result.

### Reproduction

Set up the pipeline:
```

vae = AutoencoderKL.from_pretrained(
    "/models/VAE/sdxl-vae-fp16-fix",
    torch_dtype = torch.float16,
    use_safetensors = True
)

cn_xl_canny = ControlNetModel.from_pretrained(
    "/models/ControlNet/diffusers-xl-canny-small",
    torch_dtype = torch.float16,
    use_safetensors = True,
    variant = "fp16"
)
controlnet = MultiControlNetModel([cn_xl_canny])

pipeline = StableDiffusionXLControlNetImg2ImgPipeline.from_pretrained(
    "stabilityai/sdxl-turbo",
    controlnet = controlnet,
    variant = "fp16",
    use_safetensors = True,
    vae = vae,
    torch_dtype = torch.float16,
    load_safety_checker = False
)
````

Then do the inference:

```
image = self.pipeline(
    prompt = prompt,
    image = control_image,
    strength = 0.0,
    guidance_scale = 0.0,
    num_inference_steps = num_steps,
    width = width,
    height = height,
    generator = generator,
    control_image = [canny_image],
    controlnet_conditioning_scale = [control_strength],
    control_guidance_start = [0.0],
    control_guidance_end = [1.0],
    guess_mode = True
).images[0]
```

### System Info

- `diffusers` version: 0.21.4
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.1
- Accelerate version: 0.24.0
- xFormers version: not installed

### Who can help?

@saya

**Comment by sayakpaul** [comment]
This reproduction code could be improved a bit more here. 

* I don't think there's any need to do `MultiControlNetModel` wrapping here. Could we remove this? 
* In your inference code, we don't know where the `prompt`, `control_image` variables are coming from.

Could you please take care of these and resubmit the reproduction code?

**Comment by patrickvonplaten** [comment]
I don't think it should work with strength=0. Strength=0 essentially means that the image stays completely unchanged - why would one want to run this?

**Comment by andypotato** [comment]
There is at least one valid use case:

Let's say I have a doodle sketch application that uses the doodle image for both ControlNet Canny (for the sketch) and also for Img2Img (to retain color information). Now I want to provide an option to enable / disable the Img2Img process (for artistic reasons).

This toggle could be as simple as setting the strength of in `StableDiffusionXLControlNetImg2ImgPipeline` to zero, because as you said, the image will have no impact on generation. ControlNet and the prompt still do.

However due the issue mentioned in the report, I need to create two pipelines. One `StableDiffusionXLControlNetImg2ImgPipeline` for non-zero strength, and an additional `StableDiffusionXLControlNetPipeline` to handle the zero strength case. This is an ugly workaround and wouldn't be necessary if strength=0 would essentially turn `StableDiffusionXLControlNetImg2ImgPipeline` into a `StableDiffusionXLControlNetPipeline`

Hope that explains

**Comment by patrickvonplaten** [comment]
Why is instantiating two pipelines an ugly workaround? You can just do:

```py
from diffusers import StableDiffusionXLControlNetImg2ImgPipeline, StableDiffusionXLControlNetPipeline

img2img = StableDiffusionXLControlNetImg2ImgPipeline.from_pretrained("<model_id>")
text2img = StableDiffusionXLControlNetPipeline(**img2img.components)   # no additional memory is allocated
```
```

**Comment by andypotato** [comment]
Oh wow, I wasn't aware I could initialize a pipeline like this! Thank you so much @patrickvonplaten 

(Still... should the img2img pipeline really crash with a parameter of zero? It's a valid parameter value after all)

**Comment by patrickvonplaten** [comment]
> Oh wow, I wasn't aware I could initialize a pipeline like this! Thank you so much @patrickvonplaten
> 
> (Still... should the img2img pipeline really crash with a parameter of zero? It's a valid parameter value after all)

We could add a better error message if `strength=0.0` is passed cc @sayakpaul

**Comment by nickkolok** [comment]
Just for reference: I've just lost a couple of hours of my life while trying to run the lpw img2img pipeline (0.15.1) for SD 1.5 with denoising strength 0.05 and 10 steps. It gave the same error, forcing me to convert and check the input image again and again...
