### ISSUE TITLE
setup.py lists many dependencies that aren't actually used

### ISSUE THREAD

**Issue by yurivict** [huggingface/diffusers#6287]
### Describe the bug

At the least torchvision, tensorflow, tensorboard dependencies aren't used.

### Reproduction

n/a

### System Info

n/a

**Comment by sayakpaul** [comment]
Those are optional dependencies. So, won't matter. You can manually verify this.

**Comment by yurivict** [comment]
Is there a list or required dependencies?
I would like to create the FreeBSD port for diffusers and for this we need to know the list of required dependencies.

**Comment by sayakpaul** [comment]
For `torch`, these are are the required dependencies: https://github.com/huggingface/diffusers/blob/2d43094ffc9b1ee377651c6c8a358c81f0c96005/setup.py#L228.
