### ISSUE TITLE
The implementation of a Null-Text Inversion Pipeline

### ISSUE THREAD

**Issue by Junsheng121** [huggingface/diffusers#6313]
### Model/Pipeline/Scheduler description

**NullTextInversionPipeline**
 
A pipeline implementation of _Null-text Inversion for Editing Real Images using Guided Diffusion Models_.
As I did not find it in Diffusers, I'd like to add this feature to Diffusers pipeline.
The NullTextInversionPipeline allows users to conduct DDIM-Inversion, Null-text Optimization, and DDIM reconstruction via _w, w/o_ Null-text Optimization. 
No prompt-to-prompt code is implemented as there is a Prompt2PromptPipeline.
[https://github.com/huggingface/diffusers/blob/2d43094ffc9b1ee377651c6c8a358c81f0c96005/examples/community/pipeline_prompt2prompt.py#L44](url)

### Open source status

- [x] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

The official implementation from Google is
[https://github.com/google/prompt-to-prompt/blob/main/null_text_w_ptp.ipynb](url)
Paper: Null-text Inversion for Editing Real Images using Guided Diffusion Models
[http://openaccess.thecvf.com/content/CVPR2023/html/Mokady_NULL-Text_Inversion_for_Editing_Real_Images_Using_Guided_Diffusion_Models_CVPR_2023_paper.html](url)
Null-text Inversion requires no additional model weights. The users may use personal photos to conduct the inversion process.
_Null-text inversion enables intuitive text-based editing of real images with the Stable Diffusion model. We use an initial DDIM inversion as an anchor for our optimization which only tunes the null-text embedding used in classifier-free guidance._
@amirhertz @dmarx @johnnypeck @mbrukman @jikkuatwork

**Comment by sayakpaul** [comment]
Feel free to add that as a community pipeline.

**Comment by Junsheng121** [comment]
Thanks. I will make a PR tomorrow.

Sayak Paul ***@***.***> 于2023年12月25日周一 23:50写道：

**Comment by sayakpaul** [comment]
@Junsheng121 checking if you're still interested to give this a shot?

**Comment by Junsheng121** [comment]
Already solved in https://github.com/huggingface/diffusers/commit/d184291c7d2284281269e1257250aaea526ef556. Thanks!

**Comment by sayakpaul** [comment]
Ah sorry. 

PR https://github.com/huggingface/diffusers/pull/6329
