### ISSUE TITLE
Emu2 seems to fail to find remote model

### ISSUE THREAD

**Issue by CoffeeVampir3** [huggingface/diffusers#6320]
### System Info

- `transformers` version: 4.37.0.dev0
- Platform: Linux-6.6.8-arch1-1-x86_64-with-glibc2.38
- Python version: 3.10.12
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.1
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.2 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: 3090TI/A4000 (Ada)
- Using distributed or parallel set-up in script?: no

### Who can help?

@amyeroberts @ArthurZucker @younesbelkada

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Using the example script for EMU2-GEN <https://huggingface.co/BAAI/Emu2-Gen>
The only modification I made was to set the path to my local copy of the model: `path = "mypath"`

I've included the code for reference at the bottom of this post.

```
(base) ➜  Emu2-Gen python test.py      
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:28<00:00,  3.61s/it]
Keyword arguments {'trust_remote_code': True} are not expected by EmuVisualGenerationPipeline and will be ignored.
Loading pipeline components...:   0%|                                                                                                                                                                                | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/ue/Emu2-Gen/test.py", line 22, in <module>
    pipe = DiffusionPipeline.from_pretrained(
  File "/home/blackroot/miniforge3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/blackroot/miniforge3/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1264, in from_pretrained
    maybe_raise_or_warn(
  File "/home/blackroot/miniforge3/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 299, in maybe_raise_or_warn
    library = importlib.import_module(library_name)
  File "/home/blackroot/miniforge3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.modeling_emu'
```

I'm not sure if this is on the transformers end or an issue with the remote module loading. Cheers.

```python
import cv2
from diffusers import DiffusionPipeline
import numpy as np
from PIL import Image
import requests
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# For the first time of using,
# you need to download the huggingface repo "BAAI/Emu2-GEN" to local first
path = "/mnt/ue/Emu2-Gen"

multimodal_encoder = AutoModelForCausalLM.from_pretrained(
    f"{path}/multimodal_encoder",
    trust_remote_code=True,
    torch_dtype=torch.bfloat16,
    use_safetensors=True,
    variant="bf16"
)
tokenizer = AutoTokenizer.from_pretrained(f"{path}/tokenizer")

pipe = DiffusionPipeline.from_pretrained(
    path,
    custom_pipeline="pipeline_emu2_gen",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
    use_safetensors=True,
    variant="bf16",
    multimodal_encoder=multimodal_encoder,
    tokenizer=tokenizer,
)

#For the non-first time of using, you can init the pipeline directly
pipe = DiffusionPipeline.from_pretrained(
    path,
    custom_pipeline="pipeline_emu2_gen",
    torch_dtype=torch.bfloat16,
    use_safetensors=True,
    variant="bf16",
)

pipe.to("cuda")

# text-to-image
prompt = "impressionist painting of an astronaut in a jungle"
ret = pipe(prompt)
ret.images[0].save("astronaut.png")

# image editing
image = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog2.jpg?raw=true',stream=True).raw).convert('RGB')
prompt = [image, "wearing a red hat on the beach."]
ret = pipe(prompt)
ret.images[0].save("dog_hat_beach.png")

# grounding generation
def draw_box(left, top, right, bottom):
    mask = np.zeros((448, 448, 3), dtype=np.uint8)
    mask = cv2.rectangle(mask, (left, top), (right, bottom), (255, 255, 255), 3)
    mask = Image.fromarray(mask)
    return mask

dog1 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog1.jpg?raw=true',stream=True).raw).convert('RGB')
dog2 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog2.jpg?raw=true',stream=True).raw).convert('RGB')
dog3 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog3.jpg?raw=true',stream=True).raw).convert('RGB')
dog1_mask = draw_box( 22,  14, 224, 224)
dog2_mask = draw_box(224,  10, 448, 224)
dog3_mask = draw_box(120, 264, 320, 438)

prompt = [
    "<grounding>",
    "A photo of",
    "<phrase>the first dog</phrase>"
    "<object>",
    dog1_mask,
    "</object>",
    dog1,
    "<phrase>the second dog</phrase>"
    "<object>",
    dog2_mask,
    "</object>",
    dog2,
    "<phrase>the third dog</phrase>"
    "<object>",
    dog3_mask,
    "</object>",
    dog3,
    "on the grass",
]
ret = pipe(prompt)
ret.images[0].save("three_dogs.png")
```

### Expected behavior

The expected behaviour is that the module is loaded by transformers.

**Comment by CoffeeVampir3** [comment]
Sorry, took a bit been on holiday. I've run an update and am seeing the same behaviour:

(base) ➜  Emu2-Gen pip install -U diffusers                 
Requirement already satisfied: diffusers in /home/blackroot/miniforge3/lib/python3.10/site-packages (0.25.0.dev0)
Collecting diffusers
  Obtaining dependency information for diffusers from https://files.pythonhosted.org/packages/aa/0b/af1dd4b355accf28fa413d93c3b7df2c25922ebc3435eecc56818a3f8c1e/diffusers-0.25.0-py3-none-any.whl.metadata
  Downloading diffusers-0.25.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: importlib-metadata in /home/blackroot/miniforge3/lib/python3.10/site-packages (from diffusers) (7.0.0)
Requirement already satisfied: filelock in /home/blackroot/miniforge3/lib/python3.10/site-packages (from diffusers) (3.13.1)
Requirement already satisfied: huggingface-hub>=0.19.4 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from diffusers) (0.19.4)
Requirement already satisfied: numpy in /home/blackroot/miniforge3/lib/python3.10/site-packages (from diffusers) (1.26.2)
Requirement already satisfied: regex!=2019.12.17 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from diffusers) (2023.10.3)
Requirement already satisfied: requests in /home/blackroot/miniforge3/lib/python3.10/site-packages (from diffusers) (2.31.0)
Requirement already satisfied: safetensors>=0.3.1 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from diffusers) (0.4.1)
Requirement already satisfied: Pillow in /home/blackroot/miniforge3/lib/python3.10/site-packages (from diffusers) (9.4.0)
Requirement already satisfied: fsspec>=2023.5.0 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from huggingface-hub>=0.19.4->diffusers) (2023.12.2)
Requirement already satisfied: tqdm>=4.42.1 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from huggingface-hub>=0.19.4->diffusers) (4.66.1)
Requirement already satisfied: pyyaml>=5.1 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from huggingface-hub>=0.19.4->diffusers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from huggingface-hub>=0.19.4->diffusers) (4.9.0)
Requirement already satisfied: packaging>=20.9 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from huggingface-hub>=0.19.4->diffusers) (23.1)
Requirement already satisfied: zipp>=0.5 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from importlib-metadata->diffusers) (3.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from requests->diffusers) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from requests->diffusers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from requests->diffusers) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/blackroot/miniforge3/lib/python3.10/site-packages (from requests->diffusers) (2023.11.17)
Downloading diffusers-0.25.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 12.7 MB/s eta 0:00:00
Installing collected packages: diffusers
  Attempting uninstall: diffusers
    Found existing installation: diffusers 0.25.0.dev0
    Uninstalling diffusers-0.25.0.dev0:
      Successfully uninstalled diffusers-0.25.0.dev0
Successfully installed diffusers-0.25.0
```

```
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:43<00:00,  5.39s/it]
Loading pipeline components...:   0%|                                                                                                                                                                                | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/ue/Emu2-Gen/test.py", line 23, in <module>
    pipe = EmuVisualGenerationPipeline.from_pretrained(
  File "/home/blackroot/miniforge3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/blackroot/miniforge3/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1264, in from_pretrained
    maybe_raise_or_warn(
  File "/home/blackroot/miniforge3/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 299, in maybe_raise_or_warn
    library = importlib.import_module(library_name)
  File "/home/blackroot/miniforge3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules'
```

I tried digging around for the source of the issue but I've had no luck myself. Cheers

**Comment by DN6** [comment]
Hi @CoffeeVampir3 I think the issue here is that the Emu pipeline isn't available in the community folder for diffusers. If you checkout the emu pipeline locally and provide the filepath to the pipeline it should work. (provided all the dependencies are installed)

**Comment by CoffeeVampir3** [comment]
@DN6 I gave this a shot, possibly did something wrong here but the result was the same as above:

```python
import cv2
from diffusers import DiffusionPipeline
import numpy as np
from PIL import Image
import requests
from transformers import AutoTokenizer
from multimodal_encoder.modeling_emu import *
import torch
from pipeline_emu2_gen import EmuVisualGenerationPipeline

# For the first time of using,
# you need to download the huggingface repo "BAAI/Emu2-GEN" to local first
path = "/mnt/ue/Emu2-Gen"

multimodal_encoder = EmuForCausalLM.from_pretrained(
    f"{path}/multimodal_encoder",
    torch_dtype=torch.bfloat16,
    use_safetensors=True,
    variant="bf16"
)
tokenizer = AutoTokenizer.from_pretrained(f"{path}/tokenizer")

pipe = EmuVisualGenerationPipeline.from_pretrained(
    pretrained_model_name_or_path=path,
    safety_checker=None,
    torch_dtype=torch.bfloat16,
    use_safetensors=True,
    variant="bf16",
    multimodal_encoder=multimodal_encoder,
    tokenizer=tokenizer,
)
pipe.to("cuda")

# text-to-image
prompt = "impressionist painting of an astronaut in a jungle"
ret = pipe(prompt)
ret.images[0].save("astronaut.png")

# image editing
image = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog2.jpg?raw=true',stream=True).raw).convert('RGB')
prompt = [image, "wearing a red hat on the beach."]
ret = pipe(prompt)
ret.images[0].save("dog_hat_beach.png")

# grounding generation
def draw_box(left, top, right, bottom):
    mask = np.zeros((448, 448, 3), dtype=np.uint8)
    mask = cv2.rectangle(mask, (left, top), (right, bottom), (255, 255, 255), 3)
    mask = Image.fromarray(mask)
    return mask

dog1 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog1.jpg?raw=true',stream=True).raw).convert('RGB')
dog2 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog2.jpg?raw=true',stream=True).raw).convert('RGB')
dog3 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog3.jpg?raw=true',stream=True).raw).convert('RGB')
dog1_mask = draw_box( 22,  14, 224, 224)
dog2_mask = draw_box(224,  10, 448, 224)
dog3_mask = draw_box(120, 264, 320, 438)

prompt = [
    "<grounding>",
    "A photo of",
    "<phrase>the first dog</phrase>"
    "<object>",
    dog1_mask,
    "</object>",
    dog1,
    "<phrase>the second dog</phrase>"
    "<object>",
    dog2_mask,
    "</object>",
    dog2,
    "<phrase>the third dog</phrase>"
    "<object>",
    dog3_mask,
    "</object>",
    dog3,
    "on the grass",
]
ret = pipe(prompt)
ret.images[0].save("three_dogs.png")
```

Exact same error even locally. This was unexpected to me, it seems like it should work, but doesn't.

**Comment by primecai** [comment]
> @DN6 I gave this a shot, possibly did something wrong here but the result was the same as above:
> 
> ```python
> import cv2
> from diffusers import DiffusionPipeline
> import numpy as np
> from PIL import Image
> import requests
> from transformers import AutoTokenizer
> from multimodal_encoder.modeling_emu import *
> import torch
> from pipeline_emu2_gen import EmuVisualGenerationPipeline
> 
> # For the first time of using,
> # you need to download the huggingface repo "BAAI/Emu2-GEN" to local first
> path = "/mnt/ue/Emu2-Gen"
> 
> multimodal_encoder = EmuForCausalLM.from_pretrained(
>     f"{path}/multimodal_encoder",
>     torch_dtype=torch.bfloat16,
>     use_safetensors=True,
>     variant="bf16"
> )
> tokenizer = AutoTokenizer.from_pretrained(f"{path}/tokenizer")
> 
> pipe = EmuVisualGenerationPipeline.from_pretrained(
>     pretrained_model_name_or_path=path,
>     safety_checker=None,
>     torch_dtype=torch.bfloat16,
>     use_safetensors=True,
>     variant="bf16",
>     multimodal_encoder=multimodal_encoder,
>     tokenizer=tokenizer,
> )
> pipe.to("cuda")
> 
> # text-to-image
> prompt = "impressionist painting of an astronaut in a jungle"
> ret = pipe(prompt)
> ret.images[0].save("astronaut.png")
> 
> # image editing
> image = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog2.jpg?raw=true',stream=True).raw).convert('RGB')
> prompt = [image, "wearing a red hat on the beach."]
> ret = pipe(prompt)
> ret.images[0].save("dog_hat_beach.png")
> 
> # grounding generation
> def draw_box(left, top, right, bottom):
>     mask = np.zeros((448, 448, 3), dtype=np.uint8)
>     mask = cv2.rectangle(mask, (left, top), (right, bottom), (255, 255, 255), 3)
>     mask = Image.fromarray(mask)
>     return mask
> 
> dog1 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog1.jpg?raw=true',stream=True).raw).convert('RGB')
> dog2 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog2.jpg?raw=true',stream=True).raw).convert('RGB')
> dog3 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog3.jpg?raw=true',stream=True).raw).convert('RGB')
> dog1_mask = draw_box( 22,  14, 224, 224)
> dog2_mask = draw_box(224,  10, 448, 224)
> dog3_mask = draw_box(120, 264, 320, 438)
> 
> prompt = [
>     "<grounding>",
>     "A photo of",
>     "<phrase>the first dog</phrase>"
>     "<object>",
>     dog1_mask,
>     "</object>",
>     dog1,
>     "<phrase>the second dog</phrase>"
>     "<object>",
>     dog2_mask,
>     "</object>",
>     dog2,
>     "<phrase>the third dog</phrase>"
>     "<object>",
>     dog3_mask,
>     "</object>",
>     dog3,
>     "on the grass",
> ]
> ret = pipe(prompt)
> ret.images[0].save("three_dogs.png")
> ```
> 
> Exact same error even locally. This was unexpected to me, it seems like it should work, but doesn't.

Have you resolved this issue? I am also encountering the same error ModuleNotFoundError: No module named 'transformers_modules'.
