### ISSUE TITLE
AttributeError: 'bool' object has no attribute '__module__'. Did you mean: '__mod__'?

### ISSUE THREAD

**Issue by Jannchie** [huggingface/diffusers#6324]
### Describe the bug

`not_compiled_module` could return `bool`.
This causes this example to report an error:

https://github.com/huggingface/diffusers/blob/main/examples/community/README.md?rgh-link-date=2023-12-25T13%3A48%3A18Z#tensorrt-image2image-stable-diffusion-pipeline

### Reproduction

https://github.com/huggingface/diffusers/blob/main/examples/community/README.md?rgh-link-date=2023-12-25T13%3A48%3A18Z#tensorrt-image2image-stable-diffusion-pipeline

### Logs

```shell
Traceback (most recent call last):
  File "C:\Code\diffusers-playground\img2img\sdt.py", line 18, in <module>
    pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
  File "C:\Users\Jannchie\anaconda3\envs\streamdiffusion\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1357, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "C:\Users\Jannchie\.cache\huggingface\modules\diffusers_modules\git\stable_diffusion_tensorrt_img2img.py", line 726, in __init__
    super().__init__(
  File "C:\Users\Jannchie\anaconda3\envs\streamdiffusion\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_img2img.py", line 276, in __init__
    self.register_modules(
  File "C:\Users\Jannchie\anaconda3\envs\streamdiffusion\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 566, in register_modules
    library = not_compiled_module.__module__.split(".")[0]
AttributeError: 'bool' object has no attribute '__module__'. Did you mean: '__mod__'?
```
```


### System Info

```
- `diffusers` version: 0.24.0
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.10.13
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.20.1
- Transformers version: 4.36.2
- Accelerate version: 0.25.0
- xFormers version: 0.0.22.post7
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Who can help?

_No response_

**Comment by sayakpaul** [comment]
Cc: @asfiyab-nvidia, the original contributor of the pipeline.

**Comment by oaramoon** [comment]
I am having the same issue.

**Comment by federicoBetti** [comment]
> I am having the same issue.

I just faced the same problem. Reverting back to a previous version (0.21.1) fixed the problem for me.
It is something in between these two versions. Can't tell more than that...

**Comment by Jannchie** [comment]
I've resolved this issue on my end, and I'll submit a pull request for it later.

**Comment by jloveric** [comment]
I seem to have had this problem with diffusers==0.27.2 but resolved it bumping back to 0.21.1

**Comment by sayakpaul** [comment]
Could you provide reproducible code snippet for this?

**Comment by tiimgreen** [comment]
@sayakpaul I'm getting this error when running:

`python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path <safetensors_file> --dump_path <output_dir> --from_safetensors --pipeline_class_name StableDiffusionXLControlNetInpaintPipeline --controlnet`

Specifically, the `--controlnet` flag is the culprit here.

**Comment by sayakpaul** [comment]
I welcome you to open a new issue with a fully reproducible code snippet.

**Comment by rezkanas** [comment]
for some reason, I start having this issue too,
```
 File "/home/anasrezklinux/anas_april/visual_story.py", line 354, in dream_booth_inference
    pipe = StableDiffusionPipeline.from_pretrained(output_dir, safety_checker=True, torch_dtype=torch.float16,
  File "/home/anasrezklinux/anas_april/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1196, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "/home/anasrezklinux/anas_april/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 183, in __init__
    self.register_modules(
  File "/home/anasrezklinux/anas_april/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 519, in register_modules
    library = not_compiled_module.__module__.split(".")[0]
AttributeError: 'bool' object has no attribute '__module__'. Did you mean: '__mod__'?
```

 when running 
```
pipe = StableDiffusionPipeline.from_pretrained(output_dir, safety_checker=True, torch_dtype=torch.float16,
                                                       low_cpu_mem_usage=False, device_map=None).to("cuda")
```

**Comment by stevens-Ai** [comment]
> I seem to have had this problem with diffusers==0.27.2 but resolved it bumping back to 0.21.1

This worked for me.
pip uninstall diffusers
pip install diffusers==0.21.1

**Comment by MaxBer04** [comment]
Hello there, 
I was having the same problem when switching vom diffusers 0.21.1 to 0.27.1. The setup was very basic with the following model: SG161222/Realistic_Vision_V2.0

After some digging into the source code, I found that the module registration from the image_encoder in the diffusion pipeline caused the error. After commenting out the following:

`
        self.register_modules(
            vae=vae,
            text_encoder=text_encoder,
            tokenizer=tokenizer,
            unet=unet,
            scheduler=scheduler,
            safety_checker=safety_checker,
            feature_extractor=feature_extractor,
            #image_encoder=image_encoder,
        )
`

in the init-method of the StableDiffusionPipeline on line 249. 
I think it has to do with the added image processor/additional imatillge conditioning support added after 0.21.1. Maybe the image encoder is not defined in older pipelines,  causing this wierd error. I may be wrong though...
Also, I haven't found a nice solution yet without modifying the source code of diffusers.

**Comment by YuzhiChen001** [comment]
tag

**Comment by JoyHuYY1412** [comment]
> I've resolved this issue on my end, and I'll submit a pull request for it later.

hello, would you mind sharing the solution for it?

**Comment by Suchenl** [comment]
@MaxBer04 Thank you for your insightful answer! it helped me solve my problem

**Comment by quyetnv98** [comment]
Nowadys in diffusers version 0.35.0-dev0 i still get this error.. But i can't fix with any solution
