### ISSUE TITLE
RAVE

### ISSUE THREAD

**Issue by a-r-r-o-w** [huggingface/diffusers#6325]
### Model/Pipeline/Scheduler description

RAVE (Randomized Noise Shuffling for Fast and Consistent Video Editing with Diffusion Models) is a fast text-guided video editing framework. It supports editing videos of any length while preserving motion and semantic structure. From some very basic testing, I really like the quality and it'd be great to have diffusers support it.

<table>
<tr>
  <td>Input</td>
  <td>Egyptian Pharaoh</td>
  <td>Medieval Knight</td>
  <td>Zombie</td>
</tr>
<tr>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/5dc6ce64-d2be-49dd-89b3-1589cd9195bb" /></td>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/0eeaa1e4-4b8d-42d0-b5cb-e427e562da37" /></td>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/2425ff0b-3e00-4bff-8afb-fa4f00019e8e" /></td>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/f1c9bc21-6ce3-4a4e-b761-7ea906a3bdf6" /></td>
</tr>
<tr>
  <td>Input</td>
  <td>Blue Crystal</td>
  <td>Crotchet boxes</td>
</tr>
<tr>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/02a51a97-15e2-416b-83ee-f1d25bbbf220" /></td>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/7e450029-6816-495b-b990-b3b15b39f791" /></td>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/2217dc3e-6459-4483-8e67-72b57190cbed" /></td>
</tr>
</table>

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

[Paper](https://arxiv.org/abs/2312.04524)
[Project Page](https://rave-video.github.io/)
[Code](https://github.com/rehg-lab/RAVE/)
[Demo](https://huggingface.co/spaces/ozgurkara/RAVE)

Authors: @ozgurkara99 @bariscankurtkaya @yesiltepe-hidir [James M. Rehg](https://scholar.google.co.in/citations?user=8kA3eDwAAAAJ&hl=en) @pinaryanardag

Thank you for your amazing work!

@sayakpaul @DN6 @patrickvonplaten

**Comment by sayakpaul** [comment]
Will defer to @DN6.

**Comment by DN6** [comment]
I think we can add to community pipelines and bump up to source if there's a lot of interest.

**Comment by a-r-r-o-w** [comment]
@ozgurkara99 @bariscankurtkaya @yesiltepe-hidir Hey. Once again, thank you for your amazing work! Are you open to and available for creating a diffusers version of your work? I'd love to help out where I can.

**Comment by ozgurkara99** [comment]
Thank you a lot, we have not worked on implementing its diffusers version, please feel free to do it as long as everything’s properly cited :).

**Comment by bariscankurtkaya** [comment]
Hi @a-r-r-o-w , are you interested in implementing the Rave into diffusers?

**Comment by a-r-r-o-w** [comment]
> Hi @a-r-r-o-w , are you interested in implementing the Rave into diffusers?

Hey @bariscankurtkaya. Yes, I've begun converting your repository into diffusers format already. Would you be interested in joining? I can push what I have currently and invite as a collaborator on my fork so we can work parallely.

**Comment by bariscankurtkaya** [comment]
> > Hi @a-r-r-o-w , are you interested in implementing the Rave into diffusers?
> 
> 
> 
> Hey @bariscankurtkaya. Yes, I've begun converting your repository into diffusers format already. Would you be interested in joining? I can push what I have currently and invite as a collaborator on my fork so we can work parallely.

Hi @a-r-r-o-w , it is good to hear you are interested in the work. Unfortunately, I am working on another research project recently therefore I am unable to make improvements on the coding side but I would be happy to help you if you have any questions about the work.

**Comment by a-r-r-o-w** [comment]
Thank you, that'd be amazing. I'll ping all the authors once I have a PR ready for review and maybe we can improve from there. I hope for the best outcomes from your research, and am interested in any collaborations where possible as I try to get more into diffusion research.

Happy new year!
