### ISSUE TITLE
SAG for inpainting

### ISSUE THREAD

**Issue by xinli2008** [huggingface/diffusers#6331]
Hello, SAG is great and produces great results, but there are no pipelines that use it  for inpainting. Can it be done?

this is the pipeline btw:
https://github.com/huggingface/diffusers/blob/8e5921cac14c84a670b4e9d89d717b5356e5b9e9/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py

**Comment by sayakpaul** [comment]
Feel free to adapt it accordingly for your use cases.

**Comment by xinli2008** [comment]
the official SAG_pipeline is only available for text2image task, but it can not serve for inpainting task which unet channel is 9

**Comment by sayakpaul** [comment]
Yes, you will have to extend SAG to inpainting use cases.
