### ISSUE TITLE
FINETUNE PRE-TRAINED LORA BY PEFT

### ISSUE THREAD

**Issue by George0726** [huggingface/diffusers#6333]
### Describe the bug

Hi there, I am going to fine-tune LCM LoRA on my own pre-trained models by the PR https://github.com/huggingface/diffusers/blob/87f87a70631d01e765d2e8cdbc1078a6e2908312/examples/consistency_distillation/train_lcm_distill_lora_sdxl.py#L811.  However, I don't know how to load pre-trained LCM LoRA (llatent-consistency/lcm-lora-sdxl).

I have tried two different methods,

` unet.add_adapter(adapter_name, lora_config )
 unet.load_adapter(unet_sub_dir, adapter_name=adapter_name)` from [here](https://github.com/NVIDIA/TensorRT/issues/3483). But it doesn't work.
 
 Could you mind giving me some advance on how to load this, thanks a lot! @sayakpaul 

### Reproduction

Traceback (most recent call last):
  File "/home/qirui/dreambooth_inpaint/test.py", line 14, in <module>
    unet.load_adapter("/mnt/nfs/file_server/public/qirui/models/models--latent-consistency--lcm-lora-sdxl/", is_trainable=True)
  File "/home/qirui/repo/diffusers/src/diffusers/models/modeling_utils.py", line 221, in __getattr__
    return super().__getattr__(name)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet2DConditionModel' object has no attribute 'load_adapter'. Did you mean: 'add_adapter'?

### System Info

- `diffusers` version: 0.25.0.dev0
- Platform: Linux-6.2.0-37-generic-x86_64-with-glibc2.31
- Python version: 3.10.11
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.20.1
- Transformers version: 4.30.2
- Accelerate version: 0.25.0
- xFormers version: 0.0.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @dg845

**Comment by sayakpaul** [comment]
You can load it by using the `load_lora_weights()` method on a pipeline.

**Comment by George0726** [comment]
Hi Sayak, thanks for your reply. I have tried to load Lora's weights before setup the adapter. However, it seems like adding another two Lora for adding adapter. 
```
    if args.load_pretrained_lora is True:
        pipe = StableDiffusionXLInpaintPipeline.from_pretrained("mhdang/dpo-sdxl-text2image-v1", unet = unet, torch_dtype=torch.float16).to("cuda")
        pipe.load_lora_weights("latent-consistency/lcm-lora-sdxl")


    lora_config = LoraConfig(
        r=args.lora_rank,
        lora_alpha=args.lora_rank,
        target_modules=[
            "to_q",
            "to_k",
            "to_v",
            "to_out.0",
            "proj_in",
            "proj_out",
            "ff.net.0.proj",
            "ff.net.2",
            "conv1",
            "conv2",
            "conv_shortcut",
            "downsamplers.0.conv",
            "upsamplers.0.conv",
            "time_emb_proj",
        ],
    )
    unet.add_adapter(lora_config)
```
I found that the key of LCM Lora is different from the add_adapter functions. Could you know how to transfer the key name?

**Comment by sayakpaul** [comment]
Here: https://github.com/huggingface/diffusers/blob/404351fa676cf0d301ed5e19c6c46b51b52a87d5/examples/consistency_distillation/train_lcm_distill_lora_sdxl.py#L1345. 

I recommend you to follow the script with minute attention because every detail there is quite important.

**Comment by George0726** [comment]
Thanks, I have successfully done the distillation by your code!
