### ISSUE TITLE
add  padding_mask_crop to all inpaint pipelines 

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#6345]
We just merged in this PR https://github.com/huggingface/diffusers/pull/6072 that introduces `padding_mask_crop` argument for stable diffusion inpaint pipeline for the first time

It is similar to the feature in auto1111 when you select "inpaint area = only masked" - basically, it will crop out a region around the mask based on the `padding_mask_crop` argument, upscale this crop region to image size, apply inpainting and then size it back and overlay onto the original image. 

Anyone want to help add this feature to all other inpaint pipelines? i.e. controlnet inpaint, SDXL inpaint, SDXL controlnet inpaint. 
You need to:
1.   apply the same change as we did in https://github.com/huggingface/diffusers/pull/6072/files#diff-39d36ab1e622684e35fe6971c12fb44e24756bdc383aba3d7f6e3b1625bdaafc
2. run an example to make sure this feature works for the updated pipeline

**Comment by rootonchair** [comment]
Hi @yiyixuxu, I would like to work on this issue :smile:

**Comment by charchit7** [comment]
@rootonchair Hey, do you plan on adding for all the inpain pipelines? Else, would love to take one for eg. SDXL inpaint. Please let me know.

**Comment by rootonchair** [comment]
@charchit7 Yes, I would love to work with SDXL inpaint first. Is it ok to have multiple PRs for this issue?

**Comment by charchit7** [comment]
depends on boss @yiyixuxu :)
