### ISSUE TITLE
Add GlueGen

### ISSUE THREAD

**Issue by rootonchair** [huggingface/diffusers#6347]
### Model/Pipeline/Scheduler description

GlueGen is a minimal adapter that allow alignment between any encoder (Text Encoder of different language, Multilingual Roberta, AudioClip) and CLIP text encoder used in standard Stable Diffusion model.

Below are the results produced by using community available weights in English and French (using their French adapter):
**Checkpoint: Anime pencil diffusion**
![00004-Gollum du Seigneur des Anneaux style de concept de crayon anime](https://github.com/huggingface/diffusers/assets/23548268/ffde56b0-cf00-4c23-8a63-655d7a8c219c)
French Prompt: Gollum du Seigneur des Anneaux style de concept de crayon anime 

![00000Gollum from lord of the rings anime pencil concept style](https://github.com/huggingface/diffusers/assets/23548268/880b38bf-dd7c-4f86-9b33-23fd10a674f0)
English Prompt: Gollum from lord of the rings anime pencil concept style

**Checkpoint: animeTWO**
![00030-une fille heureuse](https://github.com/huggingface/diffusers/assets/23548268/5d619863-5a45-4fb8-9eb7-ca4c07803657)
French Prompt: une fille heureuse
![00024a girl happy](https://github.com/huggingface/diffusers/assets/23548268/f18912f6-30a0-4c20-ba4d-9185a3bb0841)
English Prompt: a girl happy

I would like to contribute this model into Diffuser library

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

From: Salesforce
Code and pretrained weights: https://github.com/salesforce/GlueGen
Paper: https://arxiv.org/pdf/2303.10056.pdf

**Comment by sayakpaul** [comment]
Feel free to add as a community pipeline. If we see substantial usage, we can graduate that to a core pipeline.

**Comment by rootonchair** [comment]
Thanks. I would work on that
