### ISSUE TITLE
"Enhancing `diffusers.AutoencoderKL` for 3D Image Support in Medical and Video Applications"

### ISSUE THREAD

**Issue by yusijin02** [huggingface/diffusers#6348]
**Is your feature request related to a problem? Please describe.**
Currently, the VAE in the `diffusers` library supports processing two-dimensional images as input. This limitation makes it less convenient for applications that require handling three-dimensional data, such as medical images, point clouds, and video data.

**Describe the solution you'd like.**
I propose enhancing the `diffusers.AutoencoderKL` to support operations on three-dimensional images. For example, the `down_block_types` parameter in `diffusers.AutoencoderKL` currently supports only these 2D-specific values: `["DownBlock2D", "ResnetDownsampleBlock2D", "AttnDownBlock2D", "CrossAttnDownBlock2D", "SimpleCrossAttnDownBlock2D", "SkipDownBlock2D", "AttnSkipDownBlock2D", "DownEncoderBlock2D", "AttnDownEncoderBlock2D", "KDownBlock2D", "KCrossAttnDownBlock2D"]`. However, corresponding 3D block implementations are not available for use in `AutoencoderKL`, even though `diffusers.models.unet_3d_block` includes such implementations.

**Describe alternatives you've considered.**
A potential solution is to introduce a new input parameter `dim` (with a default value of 2) in the `__init__` method of `diffusers.AutoencoderKL`. This parameter would determine whether the initialized `self.encoder` and `self.decoder` should handle 2D or 3D inputs. For 2D inputs, the existing code would be used. For 3D inputs, methods from `diffusers.models.unet_3d_block` could be utilized.

**Additional context.**
N/A.

**Comment by sayakpaul** [comment]
We need such pre-trained Autoencoders first.
