### ISSUE TITLE
how to choose save precision for lora file in training

### ISSUE THREAD

**Issue by DoctorTar** [huggingface/diffusers#6352]
I'm confused about my lora precision(fp16,bf16,float) and whether i can choose precision about my lora weights. I searched for the params about the **StableDiffusionXLPipeline.save_lora_weights** function used to save lora in sdxl text2img training script and didnt find params like 'save_precision' or sth.

anyone can help? thanks!

**Comment by sayakpaul** [comment]
The LoRA parameters are always in float32. 

https://github.com/huggingface/diffusers/blob/4c483deb9077ef733d568ff0ae47233c35efd039/examples/dreambooth/train_dreambooth_lora_sdxl.py#L1000
