### ISSUE TITLE
Add LoRA support for ControlNet

### ISSUE THREAD

**Issue by ifsheldon** [huggingface/diffusers#6354]
**Is your feature request related to a problem? Please describe.**
Recently I've been trying to port [LooseControl](https://github.com/shariqfarooq123/LooseControl) to A1111 WebUI and ComfyUI. The model weights are just a LoRA of ControlNet-depth, but to load the LoRA into ControlNet, the author had to hack thourgh `ControlNetModel` and `UNet2DConditionLoadersMixin`. So I wonder whether `ControlNetModel` can also extends `LoraLoaderMixin` to support LoRAs of ControlNets. 

**Describe the solution you'd like.**
`ControlNetModel` can also extends `LoraLoaderMixin` to support LoRAs of ControlNets. 

**Describe alternatives you've considered.**
I don't know if there is a better solution, sorry.....

**Additional context.**
Note that LoRA support for ControlNet is not the same as `ControlLoRA` proposed by stability.ai

**Comment by sayakpaul** [comment]
We'd be happy to accept PR for that.

**Comment by patrickvonplaten** [comment]
Does it really make sense to add LoRA for ControlNet? Has the community tried that with convincing results?

**Comment by sayakpaul** [comment]
Same question.

**Comment by sayakpaul** [comment]
I am going to close this issue as we didn't receive any answers further. But if the community feels strongly about this, feel free to open with some convincing results.

**Comment by lavinal712** [comment]
Adding lora to controlnet is feasible, but needs support of diffusers.
Please refer https://github.com/HighCWu/control-lora-v2
