### ISSUE TITLE
EulerDiscreteScheduler not have get_velocity function and add_noise get error for prediction_type == "v_prediction"?

### ISSUE THREAD

**Issue by jiarenyf** [huggingface/diffusers#6359]
### Describe the bug

Finetune stable video diffusion but found two problems:

1. EulerDiscreteScheduler not have get_velocity function ?
2. EulerDiscreteScheduler  add_noise get error for prediction_type == "v_prediction"?

### Reproduction

1. EulerDiscreteScheduler not have get_velocity function ?
https://github.com/huggingface/diffusers/blob/main/examples/research_projects/controlnet/train_controlnet_webdataset.py#L1376

2. EulerDiscreteScheduler  add_noise get error for prediction_type == "v_prediction"?
https://github.com/huggingface/diffusers/blob/645a62bf3bcba47f97bf2a36a8689f40bd6b04fd/examples/research_projects/controlnet/train_controlnet_webdataset.py#L1341

### System Info

latest master branch

### Who can help?

@yiyixuxu @patrickvonplaten

**Comment by jiarenyf** [comment]
upupup

**Comment by jiarenyf** [comment]
=。=

**Comment by jiarenyf** [comment]
No body ...

**Comment by JunruiXiao** [comment]
I meet same err. Have you solve this?

**Comment by SystemErrorWang** [comment]
I got `RuntimeError: a Tensor with 0 elements cannot be converted to Scalar.` when calling `add_noise` in stable video diffusion. DDIM scheduler also met same problem. Have you met this too?

**Comment by patrickvonplaten** [comment]
Hey everybody,

We would need a reproducible code snippet here - it's too time-consuming trying to guess what's going on. Could anybody try to provide a reproducible code snippet?
