### ISSUE TITLE
How to use diffusers lora in the AUTOMATIC1111 

### ISSUE THREAD

**Issue by chongxian** [huggingface/diffusers#6370]
Thanks for your great work, I use the train_text_to_image_lora_sdxl.py to train my custom dataset and get these output, And I get the good result. But I want to use the AUTOMATIC1111 to use the lora weight, I move the pytorch_lora_weights to the AUTOMATIC1111 lora folder But get the error report:`AssertionError: conversion failed: lora_unet_input_blocks_4_1_transformer_blocks_0_attn1_to_k_lora_A_weight. the model may not be trained by `sd-scripts``
![image](https://github.com/huggingface/diffusers/assets/18145013/561a8450-af71-460f-a091-78eb96dcea20)
how can I do to convert the lora model weight to which format  AUTOMATIC1111 can accpet.

**Comment by sayakpaul** [comment]
@pacman100 if I remember correctly, we had a utility for this?

**Comment by chongxian** [comment]
> @pacman100 if I remember correctly, we had a utility for this?

sorry, could you please give me some advise?

**Comment by patrickvonplaten** [comment]
This issue should go to: https://github.com/AUTOMATIC1111/stable-diffusion-webui
