### ISSUE TITLE
[Pipeline] SVD + ControlNet

### ISSUE THREAD

**Issue by a-r-r-o-w** [huggingface/diffusers#6372]
### Model/Pipeline/Scheduler description

Recently, AnimateDiff+ControlNet support was added to diffusers. I was hoping to try and implement SVD+ControlNet too but didn't find the time, however @CiaraStrawberry has a great implementation for it. Thank you for this very cool pipeline!

It would be awesome if diffusers could support it as well :hugs: What do you think?

Code: https://github.com/CiaraStrawberry/svd-temporal-controlnet/

![1](https://github.com/huggingface/diffusers/assets/72266394/ddbfea02-9bfb-49ff-920d-ea70776cf789)

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

@patrickvonplaten @sayakpaul @DN6

**Comment by shauray8** [comment]
Working on this, adding it as a community pipeline for now. @sayakpaul @a-r-r-o-w
