### ISSUE TITLE
unet.save_pretrained() only save a small file (2kb or 2Mb)

### ISSUE THREAD

**Issue by Wang-Xiaodong1899** [huggingface/diffusers#6379]
### Describe the bug

I try to finetune the text-to-video model using the `UNetSpatioTemporalConditionModel` as the U-Net backbone on my private dataset, and the training process was normal, but when I need to use `unet.save_pretrained(os.path.join(args.output_dir, "unet"))`, it only save a config file and a very small file, you know ,here is a safetensors files, but only 2Mb, even 2Kb, very strange.

### Reproduction

```
unet = UNetSpatioTemporalConditionModel(cross_attention_dim=768, in_channels=4)
...
unet.load_state_dict(new_state_dicts, strict=False)
unet, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
        unet, optimizer, train_dataloader, lr_scheduler
    )
...
for epoch in range(first_epoch, args.num_train_epochs):
        train_loss = 0.0
        for step, batch in enumerate(train_dataloader):
            with accelerator.accumulate(unet):
...

accelerator.wait_for_everyone()
if accelerator.is_main_process:
    unet = accelerator.unwrap_model(unet)

    #TODO save UNet
    unet.save_pretrained(os.path.join(args.output_dir, "unet"))

```

### System Info

Latest diffusers version.  Ubuntu 20.04.

### Who can help?

@DN6 @sayakpaul. I would very appreciate it if you could give me some advice. Thank you a lot!

**Comment by sayakpaul** [comment]
I can initialize the dummy UNet motion model (taken from [here](https://github.com/huggingface/diffusers/blob/034b39b8cb9770dd66468644cb3162623a35af6c/tests/pipelines/stable_video_diffusion/test_stable_video_diffusion.py#L59C9-L74C10)):

```python
from diffusers import UNetSpatioTemporalConditionModel

unet = UNetSpatioTemporalConditionModel(
    block_out_channels=(32, 64),
    layers_per_block=2,
    sample_size=32,
    in_channels=8,
    out_channels=4,
    down_block_types=(
        "CrossAttnDownBlockSpatioTemporal",
        "DownBlockSpatioTemporal",
    ),
    up_block_types=("UpBlockSpatioTemporal", "CrossAttnUpBlockSpatioTemporal"),
    cross_attention_dim=32,
    num_attention_heads=8,
    projection_class_embeddings_input_dim=96,
    addition_time_embed_dim=32,
)
unet.save_pretrained("my-3d-unet")
```

And it comes up as 7 MBs. Here's my Colab:
https://colab.research.google.com/gist/sayakpaul/d9ff84ab723d4643b3922c07db61b0f0/scratchpad.ipynb

**Comment by Wang-Xiaodong1899** [comment]
Thank you for your reply.

Yes. In my opinion, it is super small, right? As shown in https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt/tree/main/unet, if I use the **default config**, the weights should be at least 3.05GB? 

Can you try initializing the U-Net model with the default config to see if you can save the weights successfully?

Thanks!

**Comment by Wang-Xiaodong1899** [comment]
It seems ok if I tested it on Colab, in https://colab.research.google.com/drive/1aahct7gtQ-IeHhSxWCXhA8sKNA0sjgxB#scrollTo=tt7KnUXewzbq. It saved 696M weights if only use two down blocks and up blocks. 

So the problem I can't save the weights correctly may come from the **accelerator** training?  I used Zero-3 training and sharded the model in two GPUs, and **after the training was completed, I only got a 2M diffusion_pytorch_model. safetensors file.**

The training script I used is:
```
accelerate launch --mixed_precision="fp16" finetune_video.py --train_batch_size=2 --gradient_accumulation_steps=4 --gradient_checkpointing --num_train_epochs 1 --learning_rate=1e-5 --max_grad_norm=1 --enable_xformers_memory_efficient_attention --lr_scheduler=constant --lr_warmup_steps=0 --output_dir=video-test --pretrained_model_name_or_path CompVis/stable-diffusion-v1-4
```

Additionally, I modified the loading process because I need to load the previous text-to-image weights (spatial weights) into the new  `UNetSpatioTemporalConditionModel`.

Any suggestions? Thanks a lot!

**Comment by sayakpaul** [comment]
YOu might have to `accelerator.unwrap_model(model)` if you're not already. But, without seeing your code fully, I cannot comment with confidence.

I would suggest trying out a simpler model and a simpler training objective with your settings to debug the problem.

**Comment by sayakpaul** [comment]
Can we close this?

**Comment by a-r-r-o-w** [comment]
Marking this as closed due to inactivity, but I think accelerator.unwrap_model as mentioned by Sayak is the right solution. Feel free to re-open if the problem still persists and we'd be happy to help
