### ISSUE TITLE
Does diffusers  get_scheduler() support multi-stage learning rates?

### ISSUE THREAD

**Issue by stardusts-hj** [huggingface/diffusers#6383]
### Describe the bug

I want to train my model with mutli-stage lr, see to accelerate training. I want to assign a larger lr the first stage, then a smaller one in the second stage. I don't see a example or method in the diffusers `get_scheduler() ` methods. So does diffusers support this implementation ?

### Reproduction

`args.lr1, args.lr2`  
`get_scheduler()` from `/diffusers/optimization.py`

### System Info

diffusers 0.22.2

### Who can help?

@yiyixuxu @patrickvonplaten

**Comment by stardusts-hj** [comment]
can diffusers add support from `class MultiStepLR(LRScheduler)`  in '/opt/conda/lib/python3.10/site-packages/torch/optim/lr_scheduler.py' ?

**Comment by sayakpaul** [comment]
We don't. Feel free to adapt your training script accordingly.
