### ISSUE TITLE
How to map A1111 reference_only parameters into diffusers?

### ISSUE THREAD

**Issue by Logos23333** [huggingface/diffusers#6384]
Thanks for the community to implement the reference_only functionality in A1111, but how can the parameters correspond to each other? I have tried to reproduce the effect of webui in the diffusers library, but I can't seem to do it.  I'm using the StableDiffusionReferencePipeline community pipeline.

My questions are:
1. Is reference_only in A1111 equivalent to reference_attn=True, reference_adain=False? 
![image](https://github.com/huggingface/diffusers/assets/26246545/634e1501-0ce2-4c19-909f-a59416ba4008)
2. Some parameters in A1111, such as starting control step, seem to have no corresponding parameters in the pipeline.
![image](https://github.com/huggingface/diffusers/assets/26246545/1992c9b3-8d9e-43ee-9ea2-df78f7f5f1b1)
3. The style_fidelity in A111 seems to have significant differences compared to style_fidelity in A1111.

**Comment by Logos23333** [comment]
I'll give some cases to see the differences between diffusers and a1111 with the same style_fidelity.
The input image in a1111 examples:
![image](https://github.com/huggingface/diffusers/assets/26246545/96cc4481-2b3b-473b-875b-07cc08a04b90)
Here is the diffusers result.
![test1](https://github.com/huggingface/diffusers/assets/26246545/95adc350-fc15-49d6-a45d-cd8f37ff96b9)
code:
`
local_sd_model_path = 'stable-diffusion-webui/models/Stable-diffusion/realisticVisionV20_v20.safetensors'
pipe = StableDiffusionReferencePipeline.from_single_file(
    local_sd_model_path,
    torch_dtype = torch.float16
)
pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config)
pipe.enable_xformers_memory_efficient_attention()
pipe = pipe.to("cuda")
prompt = "woman in street, masterpiece, best quality,"
negative_prompt = "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry"
init_image = Image.open('./data/s3r4q8fiovza1.webp').convert("RGB") # the input image
images = pipe(
                  ref_image=init_image,
                  width=768,
                  height=512,
                  prompt=prompt,
                  negative_prompt=negative_prompt,
                  guidance_rescale=7,
                  num_inference_steps=20,
                  generator=torch.Generator(device="cuda").manual_seed(123456),
                  style_fidelity=0,
                  reference_attn=False,
                  reference_adain=True,
             )
`

And this is the result from webui

woman in street, masterpiece, best quality,
Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 123456, Size: 768x512, Model hash: e6415c4892, Model: realisticVisionV20_v20, Clip skip: 2, ControlNet 0: "Module: reference_only, Model: None, Weight: 1, Resize Mode: Crop and Resize, Low Vram: False, Threshold A: 1, Guidance Start: 0, Guidance End: 1, Pixel Perfect: False, Control Mode: Balanced, Save Detected Map: True", Version: v1.7.0

![image](https://github.com/huggingface/diffusers/assets/26246545/08d1e214-d62f-44d3-acb9-ebe7d2514fc1)

**Comment by sayakpaul** [comment]
Requesting you to tag the original authors who contributed the reference only pipelines to `diffusers` :)

**Comment by Logos23333** [comment]
@okotaku

**Comment by Logos23333** [comment]
> Requesting you to tag the original authors who contributed the reference only pipelines to `diffusers` :)
> 
> But have you tried IP Adapters for the same purpose?

I'll try IP Adapters, thank you

**Comment by sayakpaul** [comment]
Closing it for inactivity.
