### ISSUE TITLE
gradient-checkpointing ignored in SDXL+LoRA training

### ISSUE THREAD

**Issue by 2510** [huggingface/diffusers#6388]
There is `--gradient-checkpointing` option, but never handled. Is this intended?

https://github.com/huggingface/diffusers/blob/9f283b01d20aa8d9e5251dbaad19432bfb2ffe11/examples/text_to_image/train_text_to_image_lora_sdxl.py#L302-306

**Comment by sayakpaul** [comment]
Ah, yeah seems like a bug. Would you be open to fix this with a PR?
