### ISSUE TITLE
Parameter Initialization doesn't match with Latent Diffusion Model

### ISSUE THREAD

**Issue by Karbo123** [huggingface/diffusers#639]
### Describe the bug

Thanks for releasing this great work, it really makes using diffusion a easy thing! 

But later when I tried to train a `UNet2DConditionModel` from scratch, I found the parameter initialization method is a little different from the official implementation. 

For example, 
https://github.com/huggingface/diffusers/blob/57b70c599c048fd764b14ff0e276bdf08ae2cd48/src/diffusers/models/attention.py#L135
here you create a `self.proj_out` module using the standard pytorch's initialization scheme, but the official one is declared as:
https://github.com/CompVis/latent-diffusion/blob/a506df5756472e2ebaf9078affdde2c4f1502cd4/ldm/modules/attention.py#L244-L248

Although I don't know why the official one contains the **zero initialization**, I think your codes should contain it as well. Or do you think it's user's responsibility to initialize all the parameters to desired values?

Looking forward to your reply!

### System Info

diffusers version == "0.4.0.dev0"
python version == "3.8.13"

**Comment by patrickvonplaten** [comment]
Hey @Karbo123 that's a very nice issue - I think we should follow CompVis initialization here. Would you like to open a PR for it? :-)

**Comment by patrickvonplaten** [comment]
Also cc'ing @patil-suraj as he's working with fine-tuning

**Comment by patil-suraj** [comment]
Thanks a lot for the issue! We should definitely follow CompVis initialization here. Feel free to open a PRm happy to help with it!
