### ISSUE TITLE
Distributed training on 2 GPUs but with Batch Size 1?

### ISSUE THREAD

**Issue by johnman3032** [huggingface/diffusers#6391]
Hello,

I am trying to see if I can train a Stable Diffusion model on two GPUs, but there should only be one model that is loaded onto both GPUs, instead of having each GPU load its own model in what would be basically training on BS 2 but with two GPUs.

Fine-tuning SDXL with the text encoder and a high-quality optimizer takes more than 24GB VRAM, so I am interested in seeing if I can do it on two 3090s connected via NVlink.

**Comment by sayakpaul** [comment]
That might need you to figure out the layer placements accordingly. We don't support this right off the bat and we don't intend to yet. 

This is not in our scope. I'd recommend you post this on the Discord forum, instead.
