### ISSUE TITLE
Private HF link download failing through "from_single_file"

### ISSUE THREAD

**Issue by nivedwho** [huggingface/diffusers#6393]
### Describe the bug

Getting a 401 error while running ```from_single_file()``` on private HF model link. 
Same access token and url working fine while downloading directly using ```huggingface_hub.hf_hub_download```  and on ```diffusers==0.24.0```

### Reproduction

On ```diffusers > 0.24.0 ```

```
pipe = StableDiffusionXLPipeline.from_single_file('private_hf_link', use_auth_token='token')
```

### System Info

- `diffusers` version: 0.25.0
- Platform: Linux-6.1.58+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: not installed
- xFormers version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by sayakpaul** [comment]
Can you do:

```diff
- pipe = StableDiffusionXLPipeline.from_single_file('private_hf_link', use_auth_token='token')
+ pipe = StableDiffusionXLPipeline.from_single_file('private_hf_link', token='token')
```
