### ISSUE TITLE
pytorch_lora_weights lora is not visible inside Automatic nor ComfyUI

### ISSUE THREAD

**Issue by ahgsql** [huggingface/diffusers#6399]
### Describe the bug

I trained a lora with https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb#scrollTo=GOiZSXHfx3mJ

this colab. Everything works fine with inference inside Colab. But that model weights file which named pytorch_lora_weights.safetensors is not visible inside Automatic1111 loras tab or ComfyUI lora loaders.

I ended up with these diffusers lora is not available for inferencing with webuis. How to solve this problem?

file attached 
[pytorch_lora_weights.zip](https://github.com/huggingface/diffusers/files/13797812/pytorch_lora_weights.zip)

### Reproduction

Try to load lora inside webui. Triggering word is "cute woody monster"

### System Info

rtx 3090ti
amd ryzen 7950x

**Comment by apolinario** [comment]
Diffusers and AUTOMATIC1111/ComfyUI use different keys for the LoRAs. 

But you can use *just* released conversion util for this: https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_sdxl_lora_to_webui.py 

You need to be in the latest diffusers (install from main `pip install git+https://github.com/huggingface/diffusers.git`) for it to work

**Comment by ahgsql** [comment]
thank you, that solved the problem!
