### ISSUE TITLE
Finetune stable video diffusion, but the output video frames are all the same as the first frame, why ?

### ISSUE THREAD

**Issue by jiarenyf** [huggingface/diffusers#6418]
### Describe the bug

Finetune stable video diffusion, but the output video frames are all the same as the first frame, why ?

### Reproduction

Finetune stable video diffusion, but the output video frames are all the same as the first frame, why ?

### System Info

Finetune stable video diffusion, but the output video frames are all the same as the first frame, why ?

### Who can help?

Finetune stable video diffusion, but the output video frames are all the same as the first frame, why ?

**Comment by sayakpaul** [comment]
This is not a library-specific issue. Please use the Discord forum (https://hf.co/join/discord) for such issues.

**Comment by SystemErrorWang** [comment]
Hello @jiarenyf , would you please tell me how did you finetune the stable video diffusion? what scheduler did you use, and did you get any problem when calling "add_noise" function during training? Or would it be convenient for you to share the environment or version of diffusers? Thank you a lot.

**Comment by sayakpaul** [comment]
https://github.com/pixeli99/SVD_Xtend
