### ISSUE TITLE
can't reproduce fill50k's results 

### ISSUE THREAD

**Issue by dulibubai** [huggingface/diffusers#6423]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

**Describe the solution you'd like.**

**Describe alternatives you've considered.**

**Additional context.**

**Comment by dulibubai** [comment]
can you provide the logs of training fill50k with controlnet? my result is not good, debugging.

**Comment by patrickvonplaten** [comment]
Hey @dulibubai, 

can you provide some code that can be reproduced ?
