### ISSUE TITLE
Lora Usage With Controlnet Pipeline

### ISSUE THREAD

**Issue by furkantrky** [huggingface/diffusers#6429]
Can we use both load_lora_weights() and fuse_lora() with controlnet pipelines. @sayakpaul

**Comment by sayakpaul** [comment]
You cannot load LoRA into a `ControlNetModel` as of now. But `StableDiffusionControlNetPipeline` and `StableDiffusionXLControlNetPipeline` should work as they inherit `LoraLoaderMixin` and `StableDiffusionXLLoraLoaderMixin`. This means you can load LoRA into the UNet and the text encoders. 

Feel free to try out.

**Comment by furkantrky** [comment]
> You cannot load LoRA into a `ControlNetModel` as of now. But `StableDiffusionControlNetPipeline` and `StableDiffusionXLControlNetPipeline` should work as they inherit `LoraLoaderMixin` and `StableDiffusionXLLoraLoaderMixin`. This means you can load LoRA into the UNet and the text encoders. 
> 
> 
> 
> Feel free to try out. 

Thanks for the reply I'll try it 🙏🏻
