### ISSUE TITLE
Is it possible to add vocabulary to a clip model packaged inside of a distributed SD checkpoint?

### ISSUE THREAD

**Issue by TeKett** [huggingface/diffusers#6434]
I tried to make an account over on huggingface to ask on the forum, but it wont redirect me after the captcha so i cant make an account, so il ask here.

Is it possible to add vocabulary to a clip model packaged inside of a distributed SD checkpoint? I have a checkpoint of the .safetensor variety that i downloaded on civitai, that i want to train/finetune and make loras for. But i want to add new vocabulary to it in order to improve training, and not have the tokens split into other words, and damage things it already knows. To make it easy for me i wanted to add the booru tags of my training set since i can just grab them when i get the image automatically.

**Comment by yiyixuxu** [comment]
same here https://github.com/huggingface/diffusers/discussions/6876
