### ISSUE TITLE
Default Width, Height in ControlNet does not initialized

### ISSUE THREAD

**Issue by rootonchair** [huggingface/diffusers#6435]
### Describe the bug

I notice that `width`, `height` variables are not initialized as `self.unet.config.sample_size * self.vae_scale_factor` said in the doc
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/controlnet/pipeline_controlnet.py#L1024

I'm not sure if this is intentional, else it would cause division error between two `None` varables when #6360 is merged

### Reproduction

None

### System Info

- `diffusers` version: 0.25.0.dev0
- Platform: Linux-4.18.0-408.el8.x86_64-x86_64-with-glibc2.28
- Python version: 3.9.18
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- Huggingface_hub version: 0.20.1
- Transformers version: 4.36.2
- Accelerate version: 0.25.0
- xFormers version: not installed

### Who can help?

@yiyixuxu

**Comment by DN6** [comment]
cc: @yiyixuxu Would you be able to take a look here please before https://github.com/huggingface/diffusers/pull/6360 is merged

**Comment by patrickvonplaten** [comment]
How is this issue related to #6360 ?

**Comment by yiyixuxu** [comment]
hi @rootonchair 

#6360  does not touch the controlnet pipeline - I assume you are refering to controlnet inpaint pipeline? 

it sets `width`, `height` variable here 
https://github.com/huggingface/diffusers/blob/dd4459ad795230ee6d70dc270484bb9b523db9d4/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py#L1350

**Comment by rootonchair** [comment]
@yiyixuxu yes, I'm refering to controlnet inpaint pipeline. Sorry, I'm a little confused, why don't we initialize it as `self.unet.config.sample_size * self.vae_scale_factor`?

**Comment by yiyixuxu** [comment]
@rootonchair good question! sorry I think the docstring might be wrong. 
it is not default to `self.unet.config.sample_size * self.vae_scale_factor`, see the code here:
https://github.com/huggingface/diffusers/blob/3e8b63216e502a0dd7424hec0fef4134187802b93f/src/diffusers/image_processor.py#L401

**Comment by rootonchair** [comment]
https://github.com/huggingface/diffusers/blob/3e8b63216e502a0dd7424hec0fef4134187802b93f/src/diffusers/image_processor.py#L401

weird, the path doesn't exists

**Comment by yiyixuxu** [comment]
This?

https://github.com/huggingface/diffusers/blob/main/src/diffusers/image_processor.py#L401
