### ISSUE TITLE
Docs: fp16 link from accelerating SDXL guide 404s

### ISSUE THREAD

**Issue by fofr** [huggingface/diffusers#6439]
### Describe the bug

Link that 404s:
https://huggingface.co/docs/diffusers/main/en/optimization/fp16.md

Linked from:
https://huggingface.co/docs/diffusers/main/en/tutorials/fast_diffusion

And in code:
https://github.com/huggingface/diffusers/blob/2e4dc3e25d6abaf5f15d7e5c62db75a8bd63f915/docs/source/en/tutorials/fast_diffusion.md?plain=1#L107

### Reproduction

n/a

### System Info

n/a

### Who can help?

@stevhliu

**Comment by DN6** [comment]
cc: @sayakpaul

**Comment by sayakpaul** [comment]
Cc: @stevhliu
