### ISSUE TITLE
add masked_image_latents input on StableDiffusionControlNetInpaintPipeline

### ISSUE THREAD

**Issue by moono** [huggingface/diffusers#6452]
**Is your feature request related to a problem? Please describe.**
* In `StableDiffusionInpaintPipeline`'s `__call__` method, there is a input argument called `masked_image_latents`, which can override encoded masked_image, but in `StableDiffusionControlNetInpaintPipeline` it seems not.
To align inputs I think it will be better to add same parameter as `StableDiffusionInpaintPipeline`.

**Describe the solution you'd like.**
* Add `masked_image_latents: torch.FloatTensor = None` to `StableDiffusionControlNetInpaintPipeline`'s `__call__` method.

**Describe alternatives you've considered.**
* N/A

**Additional context.**
* Related PR: https://github.com/huggingface/diffusers/pull/4819
  * above pr adds `masked_image_latents` to `StableDiffusionInpaintPipeline` but not in `StableDiffusionControlNetInpaintPipeline`

cc. @yiyixuxu

**Comment by yiyixuxu** [comment]
hi @moono 
sorry I just saw this issue, I think it's already added to sdxl inpaint https://github.com/huggingface/diffusers/blob/e1bdcc7af38ff9d1d8fbdc223aa7b306b19bfdff/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py#L1283
