### ISSUE TITLE
Faster text-to-image diffusion models 🚀

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#6459]
Check out our new work on the PyTorch blog: [Accelerating Generative AI Part III: Diffusion, Fast](https://pytorch.org/blog/accelerating-generative-ai-3/) 🔥

This is what you'd be looking forward to in the post:
![image](https://github.com/huggingface/diffusers/assets/22957388/2a320496-6780-48b0-a31f-f1c438df830e)

💻 Code: https://github.com/huggingface/diffusion-fast
📜 Diffusers doc: https://huggingface.co/docs/diffusers/main/en/tutorials/fast_diffusion

**Comment by charchit7** [comment]
Amazing work!
