### ISSUE TITLE
'PNDMScheduler' object has no attribute 'set_format'

### ISSUE THREAD

**Issue by jalexs82** [huggingface/diffusers#646]
### Describe the bug

Getting this error from pipeline_stable_diffusion.py

### System Info

On colab notebook: https://colab.research.google.com/github/WASasquatch/easydiffusion/blob/main/Stability_AI_Easy_Diffusion.ipynb

**Comment by WASasquatch** [comment]
Same issue.

**Comment by patrickvonplaten** [comment]
You are totally right - we messed it up here! Very sorry about this :pray: 

Here the fix: https://github.com/huggingface/diffusers/pull/651

**Comment by WASasquatch** [comment]
I commented out the offending line of code for now, and things seem to be working without error or loss of quality for now.

**Comment by hafriedlander** [comment]
This API change will have also broken all custom schedulers, since most of them rely on set_format to convert from numpy to tensor. Might need a stronger warning? (I didn't see this in my console, and it took me a while to track down the issue).

**Comment by hafriedlander** [comment]
Actually, I'll suggest a different fix. Put the old behaviour back into scheduling_utils - you don't use it in the core schedulers at all, so it won't matter, and it'll mean any custom schedulers will still work.

**Comment by patrickvonplaten** [comment]
Hey @hafriedlander, 

It's now a deprecated functionality but that works again. Is this good for you? Since we only support Pytorch models at the moment, I don't ever see a use case when one would need a numpy scheduler. 

Does this work for you? Please let me know if it's there are some inconveniences (and which ones) with the behavior currently and whether you can transition your code to not use `set_format(...)`

**Comment by WASasquatch** [comment]
> Hey @hafriedlander,
> 
> It's now a deprecated functionality but that works again. Is this good for you? Since we only support Pytorch models at the moment, I don't ever see a use case when one would need a numpy scheduler.
> 
> Does this work for you? Please let me know if it's there are some inconveniences (and which ones) with the behavior currently and whether you can transition your code to not use `set_format(...)`

Are these changes also related to this when trying to do inpaint on pndm?

```
[/usr/local/lib/python3.7/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py](https://localhost:8080/#) in __call__(self, prompt, init_image, mask_image, strength, num_inference_steps, guidance_scale, eta, negative_prompt, generator, output_type, return_dict)
    318 
    319             # masking
--> 320             init_latents_proper = self.scheduler.add_noise(init_latents_orig, noise, t)
    321             latents = (init_latents_proper * mask) + (latents * (1 - mask))
    322 

[/usr/local/lib/python3.7/dist-packages/diffusers/schedulers/scheduling_pndm.py](https://localhost:8080/#) in add_noise(self, original_samples, noise, timesteps)
    393             self.alphas_cumprod = self.alphas_cumprod.to(original_samples.device)
    394 
--> 395         if timesteps.device != original_samples.device:
    396             timesteps = timesteps.to(original_samples.device)
    397 

AttributeError: 'numpy.int64' object has no attribute 'device'
```

**Comment by patrickvonplaten** [comment]
Hey @WASasquatch,

Would you mind opening a new issue for this?

**Comment by hafriedlander** [comment]
Hi. Sorry for delay on replay. I am using the additional schedulers Hlky put together at https://github.com/huggingface/diffusers/compare/main...hlky:diffusers:main

However I consider this solved now for two reasons:
- I just copied the old scheduling_utils.py into my server and changed my schedulers to reference that
- Hlky is going to update his schedulers to the new 0.4.0 syntax anyway, at which point he'll presumably drop the need for set_format.
