### ISSUE TITLE
Endless loading for loading model from runwayml/stable-diffusion-inpainting

### ISSUE THREAD

**Issue by 7iFinalBoSS** [huggingface/diffusers#6460]
### Model/Pipeline/Scheduler description

model_index.json: 100%548/548 [00:00<00:00, 36.9kB/s]
unet/diffusion_pytorch_model.safetensors not found
Fetching 24 files: 0%                 0/24 [00:00<?, ?it/s]

this issue 'i'm dfacing while running in google colab the model is not is loading 

code is this ->
device = "cuda"
model_path = "runwayml/stable-diffusion-inpainting"

pipe = StableDiffusionInpaintPipeline.from_pretrained(
    model_path,
    torch_dtype=torch.float16,
).to(device)

### Open source status

- [ ] The model implementation is available.
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by Beyondo** [comment]
I have the same issue, but with all models on HuggingFace. Something weird is going on.

**Comment by loboere** [comment]
same

**Comment by DN6** [comment]
Hi @7iFinalBoSS are you using Colab to run your model? There is a known issue with loading models there at the moment. Please see: #6431

We have reached out to the Colab team. I'll share an update once we have any new information.

**Comment by 7iFinalBoSS** [comment]
yes I'm using colab and facing that problem since 2-3 days , Hope it will be fixed soon

**Comment by 7iFinalBoSS** [comment]
Thanks Its working now
