### ISSUE TITLE
Why is pipelines/audio_diffusion missing？

### ISSUE THREAD

**Issue by ZH-UCAS** [huggingface/diffusers#6463]
### Describe the bug

https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/audio_diffusion/pipeline_audio_diffusion.py

Why is pipelines/audio_diffusion missing? Where did it go? 

### Reproduction

My code is throwing an error, and I'm not sure how to fix it. 
```
# Load a pre-trained audio diffusion pipeline
device = "mps" if torch.backends.mps.is_available() else "cuda" if torch.cuda.is_available() else "cpu"
print(device)
pipe = DiffusionPipeline.from_pretrained("teticio/audio-diffusion-instrumental-hiphop-256").to(device)
```
error：
`ValueError: mel/audio_diffusion.py as defined in `model_index.json` does not exist in teticio/audio-diffusion-instrumental-hiphop-256 and is not a module in 'diffusers/pipelines'.`

I'm sorry, I'm a beginner, could you please guide me on how to modify it

### System Info

latest

**Comment by ZH-UCAS** [comment]
https://huggingface.co/docs/diffusers/main/en/api/pipelines/audio_diffusion
The example code also produces the same error.

**Comment by sang-k** [comment]
`audio_diffusion` got deprecated 3 weeks ago as discussed in https://github.com/huggingface/diffusers/pull/6169.
Therefore, if you downgrade  `diffusers` to `0.24.0`, you can still use `audio_diffusion`.
```bash
pip install diffusers==0.24.0
```

**Comment by ZH-UCAS** [comment]
Thank you for your reply and guidance.
