### ISSUE TITLE
how to use xformers

### ISSUE THREAD

**Issue by babyta** [huggingface/diffusers#6474]
Maybe this is a relatively low-level question, but what always bothers me is how does Xformer run when running SD? Or can it be accelerated by default after installing this library? Thank you all for answering your questions

**Comment by sang-k** [comment]
Hi @babyta,

As described in https://huggingface.co/docs/diffusers/v0.25.0/optimization/xformers, you can enable `xFormers` by installing it and call the method, `enable_xformers_memory_efficient_attention()` in your pipeline.

Example can be seen at https://huggingface.co/docs/diffusers/main/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.enable_xformers_memory_efficient_attention.example

**Comment by nori777go** [comment]
Thank you! I'll give it a try

**Comment by babyta** [comment]
pipe.enable_xformers_memory_efficient_attention()
When I add this sentence, I can't feel the obvious acceleration effect.
‘’
from diffusers import StableDiffusionPipeline
import torch

model_id = "./stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16, variant="fp16")
pipe = pipe.to("cuda")
#pipe.enable_xformers_memory_efficient_attention()
prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]  
  
image.save("astronaut_rides_horse.png")
‘’

**Comment by babyta** [comment]
I got an error when I ran the official example https://huggingface.co/docs/diffusers/main/en/api/diffusion_pipeline#diffusers.DiffusionPipeline.enable_xformers_memory_efficient_attention.example
![image](https://github.com/huggingface/diffusers/assets/37787795/311ebe0c-336a-4772-993b-1b1a36084738)

**Comment by sang-k** [comment]
Hey @babyta
Have you found a solution by any chance?
Can you try the code below? You can compare the inference time with and without xFormers.

```python
import time
from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained('runwayml/stable-diffusion-v1-5', torch_dtype=torch.float16, variant="fp16")
pipe = pipe.to("cuda")
prompt = "a photo of an astronaut riding a horse on mars"

# Check inference time without xFormers.
start_time = time.time()
image = pipe(prompt).images[0]
inference_time_without_xformers = time.time() - start_time

print(f"Inference Time without xformers: {inference_time_without_xformers:.3f} seconds")
image.save("astronaut_rides_horse_without_xformers.png")

pipe.enable_xformers_memory_efficient_attention()

# Check inference time with xFormers.
start_time = time.time()
image = pipe(prompt).images[0]
inference_time_with_xformers = time.time() - start_time

print(f"Inference Time with xformers: {inference_time_with_xformers:.3f} seconds")
image.save("astronaut_rides_horse_with_xformers.png")
```

In my case, I could get a acceleration effect.
```bash
Inference Time without xformers: 4.953 seconds
Inference Time with xformers: 3.277 seconds
```

**Comment by babyta** [comment]
I understand what my problem is. What I am focusing on is ‘it/s’. I tested it with 2 scripts. If you look at the generation time, enable_xformers_memory_efficient_attention is indeed very useful. Thank you very much.

**Comment by babyta** [comment]
Another question is why the acceleration effect of xformers is so obvious under webui. Compared with the diffusers library, webui has almost doubled the speed.
