### ISSUE TITLE
why diffusers use more ram comfyui?

### ISSUE THREAD

**Issue by loboere** [huggingface/diffusers#6480]
why diffusers use more ram comfyui?

When I load sdxl in comfyui it only uses 1-2 gb of ram but diffusers uses 8-9 gb of ram, why is this difference and how to make diffusers load sdxl and use 1-2 gb of ram?

**Comment by patrickvonplaten** [comment]
How can SDXL use 1-2 GB of RAM when the pure model weighst in fp16 have more than 6GB: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_base_1.0.safetensors ? This means that you're not loading the weights into GPU RAM on ComfyUI right away.
