### ISSUE TITLE
[Pipeline] FreeNoise

### ISSUE THREAD

**Issue by a-r-r-o-w** [huggingface/diffusers#6493]
### Model/Pipeline/Scheduler description

Highlights from the paper:
- Can generate longer videos while maintaining content and temporal consistency.
- Current model support single text condition for entire duration of video. FreeNoise allows support for multiple prompt conditions as video content changes over time using the proposed novel technique of motion injection.
- Superior FVD, KVD, CLIP-SIM compared to previous techniques with just a minor increase in inference time (~17%). This is significant because the previous best technique ([Gen-L-Video](https://g-u-n.github.io/projects/gen-long-video/index.html) and [Gen-L^2](https://gen-l-2.github.io/)) took more than 2.5x (~255%) time as reported.
- No tuning required. Built on top of the AnimateDiff codebase which makes it easily integrate-able.

https://github.com/huggingface/diffusers/assets/72266394/66c5ce95-6ac2-450f-be75-1b7cc887b533

Thank you for your amazing work!

Code: https://github.com/arthur-qiu/FreeNoise-AnimateDiff
Project Site: http://haonanqiu.com/projects/FreeNoise.html
Paper: https://arxiv.org/abs/2310.15169
Authors: @arthur-qiu @MenghanXia @yzhang2016 @YingqingHe @xinntao [Ying Shan](https://scholar.google.com/citations?hl=zh-CN&user=4oXBp9UAAAAJ) @liuziwei7

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

@DN6 @sayakpaul

**Comment by a-r-r-o-w** [comment]
oops, I opened a duplicate issue. I made a typo earlier when searching if a FreeNoise related issue already exists and didn't find any. But it seems there is and #5576 is by the author.

**Comment by sayakpaul** [comment]
I reopened #5576. Closing it then?
