### ISSUE TITLE
Possible bug in pipelines that use denoising_start and denoising_end

### ISSUE THREAD

**Issue by a-r-r-o-w** [huggingface/diffusers#6495]
Here are a few examples of what I think is a possible bug. 

https://github.com/huggingface/diffusers/blob/6ae7e8112a49ac20ade10ac639a76edbd9817a51/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py#L1277

https://github.com/huggingface/diffusers/blob/6ae7e8112a49ac20ade10ac639a76edbd9817a51/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py#L1516

https://github.com/huggingface/diffusers/blob/6ae7e8112a49ac20ade10ac639a76edbd9817a51/examples/community/lpw_stable_diffusion_xl.py#L1777

We can see that `denoising_value_valid` is defined, but not called, and is used in determining whether `self.denoising_start` or `None` is passed into `self.get_timesteps`.

```py
# ...
        timesteps, num_inference_steps = self.get_timesteps(
            num_inference_steps,
            strength,
            device,
            denoising_start=self.denoising_start if denoising_value_valid else None,
        )
```

However, it is not called which evaluates condition to `True` always. This does not seem like the intended behaviour, no?

@yiyixuxu @patrickvonplaten

**Comment by LWprogramming** [comment]
appears to be mentioned in https://github.com/huggingface/diffusers/issues/5685#issuecomment-1805423541 as well but not sure if a PR for that was opened or not. as of now it looks unfixed ([permalink](https://github.com/huggingface/diffusers/blob/a551ddf928f02419432263f39dc0109b74f004f7/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py#L1357) at time of writing)

**Comment by yiyixuxu** [comment]
I believe this is a bug - do you want to open a PR to fix it?
