### ISSUE TITLE
 RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by patient74** [huggingface/diffusers#6501]
I am new to using the diffusers library and was following the tutorial [Understanding pipelines, models and schedulers](https://github.com/huggingface/diffusers/blob/aa1797e1096df707b8e5164b72dc1aa5c202d0d8/docs/source/en/using-diffusers/write_own_pipeline.md?plain=1#L13). I am getting an error [here](https://github.com/huggingface/diffusers/blob/aa1797e1096df707b8e5164b72dc1aa5c202d0d8/docs/source/en/using-diffusers/write_own_pipeline.md?plain=1#L218)
```
>>> latents = torch.randn(
...     (batch_size, unet.config.in_channels, height // 8, width // 8),
...     generator=generator,
...     device=torch_device,
... )

```
```
RuntimeError                              Traceback (most recent call last)

[<ipython-input-11-456ac939a8a6>](https://localhost:8080/#) in <cell line: 1>()
----> 1 latents = torch.randn(
      2     (batch_size, unet.config.in_channels, height // 8, width // 8),
      3     generator=generator,
      4     device=torch_device,
      5 )

RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
```

I am using Google Colab running on T4 GPU.

Instead of defining the generator as in [here](https://github.com/huggingface/diffusers/blob/aa1797e1096df707b8e5164b72dc1aa5c202d0d8/docs/source/en/using-diffusers/write_own_pipeline.md?plain=1#L172)

`generator = torch.manual_seed(0)  # Seed generator to create the initial latent noise`

setting the seed manually for cuda,

`torch.cuda.manual_seed(0)`

seems to resolve the issue.

**Comment by patrickvonplaten** [comment]
Hey @patient74,

Could you try to post a reproducible code snippet?

**Comment by patient74** [comment]
Yes sure. Here is the code I was trying from the section [Deconstruct the Stable Diffusion pipeline](https://github.com/huggingface/diffusers/blob/6313645b6b1cf4c02c8e7de7fb7f03df04b6b6cd/docs/source/en/using-diffusers/write_own_pipeline.md?plain=1#L107)
```py

!pip install torch torchvision
!pip install diffusers["torch"] transformers
```
**Code from the section Deconstruct the Stable Diffusion pipeline**

```py
#Loading stable diffusion pipeline

from PIL import Image
import torch
from transformers import CLIPTextModel, CLIPTokenizer
from diffusers import AutoencoderKL, UNet2DConditionModel, PNDMScheduler

vae = AutoencoderKL.from_pretrained("CompVis/stable-diffusion-v1-4", subfolder="vae", use_safetensors=True)
tokenizer = CLIPTokenizer.from_pretrained("CompVis/stable-diffusion-v1-4", subfolder="tokenizer")
text_encoder = CLIPTextModel.from_pretrained(
    "CompVis/stable-diffusion-v1-4", subfolder="text_encoder", use_safetensors=True
)
unet = UNet2DConditionModel.from_pretrained(
    "CompVis/stable-diffusion-v1-4", subfolder="unet", use_safetensors=True
)

#Changing scheduler
from diffusers import UniPCMultistepScheduler
scheduler = UniPCMultistepScheduler.from_pretrained("CompVis/stable-diffusion-v1-4", subfolder="scheduler")


#moving models to GPU
torch_device = "cuda"
vae.to(torch_device)
text_encoder.to(torch_device)
unet.to(torch_device)


#Creating text embeddings

prompt = ["a photograph of an astronaut riding a horse"]
height = 512  # default height of Stable Diffusion
width = 512  # default width of Stable Diffusion
num_inference_steps = 25  # Number of denoising steps
guidance_scale = 7.5  # Scale for classifier-free guidance
generator = torch.manual_seed(0)  # Seed generator to create the initial latent noise
batch_size = len(prompt)

#Tokenize the text and generate the embeddings from the prompt:

text_input = tokenizer(
    prompt, padding="max_length", max_length=tokenizer.model_max_length, truncation=True, return_tensors="pt"
)

with torch.no_grad():
    text_embeddings = text_encoder(text_input.input_ids.to(torch_device))[0]

#generating the unconditional text embeddings

max_length = text_input.input_ids.shape[-1]
uncond_input = tokenizer([""] * batch_size, padding="max_length", max_length=max_length, return_tensors="pt")
uncond_embeddings = text_encoder(uncond_input.input_ids.to(torch_device))[0]


#concatanate both embeddings
text_embeddings = torch.cat([uncond_embeddings, text_embeddings])

# Create random noise

latents = torch.randn(
    (batch_size, unet.config.in_channels, height // 8, width // 8),
    generator=generator,
    device=torch_device,
)

```
I am getting the following error in the [Create random noise section](https://github.com/huggingface/diffusers/blob/6313645b6b1cf4c02c8e7de7fb7f03df04b6b6cd/docs/source/en/using-diffusers/write_own_pipeline.md?plain=1#L201) while running in Colab with T4 GPU runtime

```py
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-3-fccf0dc138b9>](https://localhost:8080/#) in <cell line: 60>()
     58 # Create random noise
     59 
---> 60 latents = torch.randn(
     61     (batch_size, unet.config.in_channels, height // 8, width // 8),
     62     generator=generator,

RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

```

**Comment by patrickvonplaten** [comment]
Can you change:

```diff
- generator = torch.manual_seed(0)
+ generator = torch.Generator(device="cuda").manual_seed(0)
```

?

**Comment by patient74** [comment]
Thank you @patrickvonplaten. It fixed the issue. Should this also be changed in the [docs? ](https://github.com/huggingface/diffusers/blob/33d2b5b08764d2579dd4ea555821b8986cd2dcf9/docs/source/en/using-diffusers/write_own_pipeline.md?plain=1#L172) If so, can I submit a PR for the same?

**Comment by asomoza** [comment]
The problem is that the random tensors are being created in the GPU and you're passing a CPU generator, if you want the image to be "reproducible" you shouldn't change the device of the generator but of the tensors, even better you can use the diffusers util `randn_tensor` to manage this automatically:

```python
from diffusers.utils.torch_utils import randn_tensor

shape = (batch_size, unet.config.in_channels, height // 8, width // 8)
latents = randn_tensor(shape, generator=generator, device=torch_device)
```

So probably what needs to be updated is the creation of the latents.
