### ISSUE TITLE
[Training] Make officially maintained training scripts compatible with `torch.compile()`

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#6503]
We recently made the DreamBooth LoRA SDXL training script fully compatible with `torch.compile()` in the following PRs: https://github.com/huggingface/diffusers/pull/6483, https://github.com/huggingface/diffusers/pull/6511. 

Since there might be speedup benefits from `torch.compile()`, it makes sense to propagate these changes to the other training scripts too. We'd appreciate help from the community in this matter. 

Below is a list of the training scripts where we'd like to integrate this:

- DreamBooth LoRA
  - [x] [Regular](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py) 
  - [x] [LoRA](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py)
- ControlNet
  - [x] [SD](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py)
  - [x] [SDXL](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet_sdxl.py)
- Text-to-image
  - [x] [SD](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py)
  - [x] [SD LoRA](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py)
  - [x] [SDXL](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py)
  - [x] [SDXL LoRA](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora_sdxl.py)
- InstructPix2Pix
  - [x] [SD](https://github.com/huggingface/diffusers/blob/main/examples/instruct_pix2pix/train_instruct_pix2pix.py)
  - [x] [SDXL](https://github.com/huggingface/diffusers/blob/main/examples/instruct_pix2pix/train_instruct_pix2pix_sdxl.py)
- T2I Adapters
  - [x] [SDXL](https://github.com/huggingface/diffusers/blob/main/examples/t2i_adapter/train_t2i_adapter_sdxl.py)

https://github.com/huggingface/diffusers/pull/6483 and https://github.com/huggingface/diffusers/pull/6511 can serve as a reference. 

Feel free to open PRs targeting only one example at a time and tag me :)

**Comment by gzguevara** [comment]
@sayakpaul could you please explain how PR #6483 is connected with `torch.compile()` ? I can see that mostly the logic in for predicting the noise residual has been changed and the function `encode_prompt()`.

**Comment by sayakpaul** [comment]
That makes `torch.compile()` work _during_ training. Otherwise, it errors out. That is why it's connected.

**Comment by rootonchair** [comment]
Hi @sayakpaul , I would like to work on this issue

**Comment by sayakpaul** [comment]
Feel free to pick one from the list and submit a PR. Thank you for showing interest!

**Comment by suvadityamuk** [comment]
I'm looking to do the one for ControlNet, but wanted to just confirm the fact that we're delegating the actual trigger of `torch.compile()` to `accelerate`, right? As such, we do not invoke `torch.compile()` explicitly anywhere in the training script, correct?

**Comment by sayakpaul** [comment]
Correct!

**Comment by sayakpaul** [comment]
Thanks for your contributions, everyone. Let's keep this coming :)

**Comment by sayakpaul** [comment]
All done! Thanks for the quick resolve everyone.

**Comment by charchit7** [comment]
> All done! Thanks for the quick resolve everyone.

Thanks for helping us. Slowly but growing!
