### ISSUE TITLE
StableVideoDiffusionPipeline returns a list instead of np.ndarray for output_type="np"

### ISSUE THREAD

**Issue by yondonfu** [huggingface/diffusers#6506]
### Describe the bug

The [comments](https://github.com/huggingface/diffusers/blob/4497b3ec982978eca99895ed1429addde4a84fff/src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py#L64) for StableVideoDiffusionPipelineOutput (which is returned by the `__call__()` function of StableVideoDiffusionPipeline) indicate that `np.ndarray` is one of the possible return types for the `frames` field but when I set `output_type="np"` for `__call__()` the `frames` field is a list of `np.ndarray`.

I think the problem is that the output of the `tensor2vid()` call [here](https://github.com/huggingface/diffusers/blob/4497b3ec982978eca99895ed1429addde4a84fff/src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py#L534) is a list and not a `np.ndarray`. I have a local commit that uses `np.stack()` to convert the list to a `np.ndarray` that I plan to push up as a PR shortly.

### Reproduction

```
from diffusers import StableVideoDiffusionPipeline
from diffusers.utils import load_image
import torch
import time

repo_id = "stabilityai/stable-video-diffusion-img2vid-xt"
cache_dir = "./cache"
pipeline = StableVideoDiffusionPipeline.from_pretrained(
    repo_id, cache_dir=cache_dir, variant="fp16", torch_dtype=torch.float16
)
pipeline.to("cuda")

# Load the conditioning image
image = load_image(
    "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png"
)
image = [image.resize((1024, 576))]
image *= 2

generator = torch.manual_seed(42)

frames = pipeline(
    image,
    decode_chunk_size=8,
    generator=generator,
    output_type="np",
).frames

print(type(frames))
print(frames.shape)
```

### Logs

```shell
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 11.34it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [01:33<00:00,  3.72s/it]
<class 'list'>
Traceback (most recent call last):
  File "/home/user/ai-worker/jobs/containers/svd-xt-film/test_svd.py", line 33, in <module>
    print(frames.shape)
          ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'shape'
```

### System Info

- `diffusers` version: 0.25.0
- Platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.31
- Python version: 3.11.7
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- Huggingface_hub version: 0.20.2
- Transformers version: 4.36.2
- Accelerate version: 0.25.0
- xFormers version: 0.0.23.post1
- Using GPU in script?: Nvidia RTX 4090

### Who can help?

@patil-suraj @patrick

**Comment by patrickvonplaten** [comment]
Hmm good catch! It'd indeed be "correcter" to output a single numpy tensor given that we pass `output_type="np"` - I'd be ok with changing it. We need to make sure though that we change it in all video pipelines (cc @DN6)

**Comment by DN6** [comment]
Yeah think we need to change here. I think the intent with the current output to return a list of numpy arrays, but I see how that can be confusing to a user.

**Comment by patrickvonplaten** [comment]
This problem is still present in other video pipelines - for consistency they should align

**Comment by DN6** [comment]
@patrickvonplaten AnimateDiff and SVD use an updated tensor2vid function that uses the `VAEImageProcessor`. So output type `np` produces a scaled (0-1.0) array. While the `TextToVideoSDPipeline` `tensor2vid` produces a list of numpy arrays that are scaled to 0-255. 

Think we should change the  `TextToVideoSDPipeline` also use the `VAEImageProcessor` right?
