### ISSUE TITLE
convert svd safetensors

### ISSUE THREAD

**Issue by shliu0** [huggingface/diffusers#6512]
How to convert svd safetensors into diffusers weights **locally**(not downloading from Hub)? Is convert_svd_to_diffusers.py a complete script ? It seems that this script only contain unet&vae convert, I cannot find how to change image_encoder in  this script. 
Thanks in advance for any answers!

**Comment by patrickvonplaten** [comment]
Hey @shliu0, could you try to move such questions to the discussion page maybe: https://github.com/huggingface/diffusers/discussions? Thanks ❤️ 

We try to keep the issues here for bugs mainly

**Comment by shliu0** [comment]
> Hey @shliu0, could you try to move such questions to the discussion page maybe: https://github.com/huggingface/diffusers/discussions? Thanks ❤️
> 
> We try to keep the issues here for bugs mainly

Sure.
