### ISSUE TITLE
IP-adapter controlnet img2img mat1 and mat2 shapes cannot be multiplied (2x1024 and 1280x768)

### ISSUE THREAD

**Issue by Honey-666** [huggingface/diffusers#6516]
Why isn't this line of code added here

output_hidden_state = False if isinstance(self.unet.encoder_hid_proj, ImageProjection) else True

https://github.com/huggingface/diffusers/blob/3e8b63216e502a0dd7424c0fef4134187802b93f/src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py#L1089

**Comment by Honey-666** [comment]
> Why isn't this line of code added here
> 
> output_hidden_state = False if isinstance(self.unet.encoder_hid_proj, ImageProjection) else True
> 
> https://github.com/huggingface/diffusers/blob/3e8b63216e502a0dd7424c0fef4134187802b93f/src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py#L1089

@takuma104  Hello  Can you look at this problem for me?

**Comment by yiyixuxu** [comment]
hi @Honey-666:

that line was added when we introduce ip-adapter-plus. https://github.com/huggingface/diffusers/pull/5915/files#diff-9314497856ceda7ee754cbb5c4f5944c62e42180d7c47c8d014351749e24912d
it seems like we missed controlnet img2img. do you want to open a PR to update it?

Thanks

YiYi

**Comment by Honey-666** [comment]
> hi @Honey-666:
> 
> that line was added when we introduce ip-adapter-plus. https://github.com/huggingface/diffusers/pull/5915/files#diff-9314497856ceda7ee754cbb5c4f5944c62e42180d7c47c8d014351749e24912d it seems like we missed controlnet img2img. do you want to open a PR to update it?
> 
> Thanks
> 
> YiYi

I'd love to, and I've already submitted a request
