### ISSUE TITLE
Question about UNet1DConditionModel

### ISSUE THREAD

**Issue by ActonLee** [huggingface/diffusers#6522]
I am working on processing 1-D data with conditions using diffusion, and I am using Hugging Face models to accelerate my work. I am using UNet2DConditionModel, but the kernels are all in the shape of (3, 3), and I need to pad my 1-D data with padding=1, which means the upper (1, 3) and the lower (1, 3) in the kernels are useless and wasting lots of computing resources. I want to know if there is any good solution for my work (UNet model for conditional 1-D). I tried to modify the code in diffusers, but there are too many Conv.

**Comment by patrickvonplaten** [comment]
Hey @ActonLee, could you move this question to the Discussion tab maybe: https://github.com/huggingface/diffusers/discussions

**Comment by ActonLee** [comment]
Sure

**Comment by ActonLee** [comment]
https://github.com/huggingface/diffusers/discussions/6538
