### ISSUE TITLE
Bug in EulerDiscreteScheduler when calling "add_noise" function

### ISSUE THREAD

**Issue by SystemErrorWang** [huggingface/diffusers#6527]
### Describe the bug

I am trying to use the EulerDiscreteScheduler to train a diffusion model (finetune the Stable Video Diffusion pipeline with the default scheduler), and I got the error message ```RuntimeError: a Tensor with 0 elements cannot be converted to Scalar```. 

### Reproduction

A simlified training script is like this:
```
pipe = StableVideoDiffusionPipeline.from_pretrained()
for data in dataloder:
    latents = pipe.vae.encode(data).latent_dist.sample()
    noise = torch.randn_like(latents)
    timesteps = torch.randint(0, pipe.scheduler.num_train_timesteps, (bsz,), device=latents.device).long()
    noisy_latents = pipe.scheduler.add_noise(latents, noise, timesteps)
```
and then I got the error message in the `pipe.scheduler.add_noise` line

### Logs

```shell
The whole error message is as below:
`Traceback (most recent call last):
  File "/share4/motion_project/train_svd.py", line 196, in <module>
    train(args)
  File "/share4/motion_project/train_svd.py", line 132, in train
    noisy_latents = pipe.scheduler.add_noise(latents, noise, timesteps)
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/diffusers/schedulers/scheduling_euler_discrete.py", line 541, in add_noise
    step_indices = [(schedule_timesteps == t).nonzero().item() for t in timesteps]
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/diffusers/schedulers/scheduling_euler_discrete.py", line 541, in <listcomp>
    step_indices = [(schedule_timesteps == t).nonzero().item() for t in timesteps]
RuntimeError: a Tensor with 0 elements cannot be converted to Scalar`
```

### System Info

related packages are as follows:
diffusers                 0.25.0                   pypi_0    pypi
tokenizers                0.15.0                   pypi_0    pypi
torch                     2.1.1+cu121              pypi_0    pypi
torchaudio                2.1.1+cu121              pypi_0    pypi
torchmetrics              1.2.0                    pypi_0    pypi
torchvision               0.16.1+cu121             pypi_0    pypi
transformers              4.36.2                   pypi_0    pypi

**Comment by SystemErrorWang** [comment]
I got the same problem when I change to the `DDIMScheduler`, I guess the problem may be in the `StableVideoDiffusionPipeline` instead of the scheduler

**Comment by greatlog** [comment]
I got the same error. I inspected the code of  EulerDiscreteScheduler and found the reason.

The EulerDiscreteScheduler used by SVD is set for continuous timesteps and v-prediction, in which case the training timesteps must also be continuous type.  

Changing

```python 
timesteps = torch.randint(0, pipe.scheduler.num_train_timesteps, (bsz,), device=latents.device).long()
```
to 
```python
indices = torch.randint(0, pipe.scheduler.num_train_timesteps, (bsz,), device=latents.device).long()
timesteps = pipe.scheduler.timesteps[indices]
```
solved my problem.

**Comment by SystemErrorWang** [comment]
> I got the same error. I inspected the code of EulerDiscreteScheduler and found the reason.
> 
> The EulerDiscreteScheduler used by SVD is set for continuous timesteps and v-prediction, in which case the training timesteps must also be continuous type.
> 
> Changing
> 
> ```python
> timesteps = torch.randint(0, pipe.scheduler.num_train_timesteps, (bsz,), device=latents.device).long()
> ```
> 
> to
> 
> ```python
> indices = torch.randint(0, pipe.scheduler.num_train_timesteps, (bsz,), device=latents.device).long()
> timesteps = pipe.scheduler.timesteps[indices]
> ```
> 
> solved my problem.

Thank you, I will try this solution

**Comment by NoSavedDATA** [comment]
I'm having the same issue. But this happens only at the second iteration of training, i.e, only on the second time add_noise is called.

**Comment by NoSavedDATA** [comment]
Nevermind. I have noticed that when scheduler.set_timesteps(20) was called during evaluation, it would also set the training steps to 20 for this scheduler. It came back to normal when I used scheduler.set_timesteps(1000) during training, before add_noise().

**Comment by patrickvonplaten** [comment]
Also related: https://github.com/huggingface/diffusers/discussions/6541

**Comment by yiyixuxu** [comment]
https://github.com/huggingface/diffusers/issues/6527#issuecomment-1888399155

Should solve the problem, no? 
In general, you need to pass `timesteps`, not the index of `timesteps` to `add_noise` function - but in many cases these two concept has same values, not the case here since we are using v_prediction
