### ISSUE TITLE
SD XL K-diffusion with Controlnet

### ISSUE THREAD

**Issue by aycaecemgul** [huggingface/diffusers#6530]
### Model/Pipeline/Scheduler description

Hi everyone, been following #6295 and #6477 for some time now to generate images with mentioned schedulers to reproduce Automatic11 quality. Is there a way to use the new SD XL K-diffusion pipeline with controlnet or Ip adapter? or use another pipeline to generate high quality results like automatic11 while using controlnet or Ip adapter. thank you!

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

@yiyixuxu @patrickvonplaten

**Comment by yiyixuxu** [comment]
Hi @aycaecemgul 
once this is merged https://github.com/huggingface/diffusers/pull/6477, you should be able to use all our regular pipelines to generate image with same quality as auto1111 

feel free to test out the fix :)

**Comment by aycaecemgul** [comment]
awesome! I'll try it out! Thanks

**Comment by YoucanBaby** [comment]
> Hi @aycaecemgul once this is merged #6477, you should be able to use all our regular pipelines to generate image with same quality as auto1111
> 
> feel free to test out the fix :)

Hi, is there any code that uses k_diffusion for controlnet?

**Comment by YoucanBaby** [comment]
> ### Model/Pipeline/Scheduler description
> Hi everyone, been following #6295 and #6477 for some time now to generate images with mentioned schedulers to reproduce Automatic11 quality. Is there a way to use the new SD XL K-diffusion pipeline with controlnet or Ip adapter? or use another pipeline to generate high quality results like automatic11 while using controlnet or Ip adapter. thank you!
> 
> ### Open source status
> * [x]  The model implementation is available.
> * [x]  The model weights are available (Only relevant if addition is not a scheduler).
> 
> @yiyixuxu @patrickvonplaten

Hello, have you successfully implemented k_diffusion for controlnet?
