### ISSUE TITLE
Marigold - monocular depth estimation pipeline

### ISSUE THREAD

**Issue by toshas** [huggingface/diffusers#6533]
### Model/Pipeline/Scheduler description

Marigold depth is the current diffusion-based state-of-the-art monocular depth estimation pipeline (image-to-depth). It is derived from Stable Diffusion and fine-tuned with synthetic data. Marigold can zero-shot transfer to unseen data, offering usable results under the most challenging conditions in the wild. 

![](https://marigoldmonodepth.github.io/images/teaser_collage_compressed.jpg)

This issue is the point of discussion regarding the pipeline status and future development. Recently, it has been integrated (https://github.com/huggingface/diffusers/pull/6249) as a [community pipeline](https://github.com/huggingface/diffusers/tree/main/examples/community#marigold-depth-estimation) into diffusers.

[![Website](https://img.shields.io/badge/Project-Website-1081c2)](https://marigoldmonodepth.github.io) [![Paper](https://img.shields.io/badge/arXiv-PDF-b31b1b)](https://arxiv.org/abs/2312.02145) [![Hugging Face Space](https://img.shields.io/badge/🤗%20Hugging%20Face-Space-yellow)](https://huggingface.co/spaces/toshas/marigold) [![Hugging Face Model](https://img.shields.io/badge/🤗%20Hugging%20Face-Model-green)](https://huggingface.co/Bingxin/Marigold)

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

Authors: @markkua @toshas @ShengyuH @nandometzger @rcdaudt @prs-eth
Model weights: https://huggingface.co/Bingxin/Marigold

**Comment by sayakpaul** [comment]
I see this as extending `diffusers` in the form a pipeline to support new tasks other than classical image generation. For example, in this case, we have "depth estimation", which is a critical computer vision problem with lots of real-world applicability. 

https://github.com/prs-eth/Marigold repository has got more than 1k stars, too, which is promising.

**Comment by yiyixuxu** [comment]
Interesting! 
Community pipeline first?

**Comment by sayakpaul** [comment]
We already have it under `community` :-)

**Comment by yiyixuxu** [comment]
let's keep an eye on it then!

**Comment by toshas** [comment]
We are brewing a pull request to integrate our new Marigold-LCM model and possibly a pipeline. Additional modalities (normals) are also in the making.

**Comment by toshas** [comment]
A few questions regarding planning the pipelines growth and lifecycle.

### 1

The new Marigold-LCM pipeline will use the same code as the original but with a different set of defaults and expected ranges of values. We are thinking of adding a new file, called `marigold_lcm_depth_estimation.py`, and in there subclassing a new `MarigoldLcmDepthPipeline` class from the `MarigoldPipeline` class located currently in the `marigold_depth_estimation.py` file. In this new class, we would then override `__call__` method with new defaults of `kwargs`, and add extra asserts regarding the actual passed values. Does this seem like a good solution, or are we better off making pipelines not dependent on each other?

### 2

I also noticed that we have made a couple of bad choices when initially committing the Marigold depth pipeline:
- we called the depth pipeline `MarigoldPipeline`. It should have been `MarigoldDepthPipeline`.
- we called the file with the depth pipeline `marigold_depth_estimation.py`, which is reflected in how the pipeline is instantiated using the `from_pretrained` method. We should have called the file `marigold_depth_pipeline.py` instead.

I want to perform these renaming actions (while also keeping in mind the LCM pipeline) to make it nice and extensible for the normals and other modalities pipelines. Would you recommend just renaming them all? Is it possible to maintain backward compatibility?

**Comment by sayakpaul** [comment]
Renaming will be a little bit tricky because it will not be backwards-compatible. I think it's okay as is because the first version of Marigold deals with depth anyway. 

Your plan with 1 sounds rock-solid to me! Keep us posted.

**Comment by asomoza** [comment]
My two cents here is that marigold should be added to the core now, I like it a lot and with LCM it should be fast. 

The model has almost 40k downloads in huggingface so it's very popular and can be used right out of the box with diffusers while the other depth maps preprocessors require to install `controlnet_aux` and sometimes gives problems because they're not part of this repo.

Personally I use it a lot, specially with diff-diff which benefits the most, and probably a controlnet trained with marigold will be a lot better than the current one, but it also works with them.

@toshas I have one suggestion, could you please upload the fp16 variants for them so people don't have to download the full precision ones if they don't use them?

Really nice work!

**Comment by sayakpaul** [comment]
Yeah agreed now. It's time for a little graduation. 

@yiyixuxu let's do an issue for this so that community can pick it up!

**Comment by yiyixuxu** [comment]
yes yes I created an issue here https://github.com/huggingface/diffusers/issues/7522
