### ISSUE TITLE
"mat2 must be a matrix" error when finetuning controlnet with FSDP

### ISSUE THREAD

**Issue by JUN20240101** [huggingface/diffusers#6540]
### Describe the bug

I tried to finetune controlnet with  train_controlnet_sdxl.py and FSDP.  But when started to validation, I got below exception.

File "train_controlnet_sdxl.py", line 1229, in main
    image_logs = log_validation(
  File "train_controlnet_sdxl.py", line 116, in log_validation
    image = pipeline(
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home2/ssy/diffusers/src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py", line 1348, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/accelerate/utils/operations.py", line 680, in forward
    return model_forward(*args, **kwargs)
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/accelerate/utils/operations.py", line 668, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home2/ssy/diffusers/src/diffusers/models/controlnet.py", line 753, in forward
    emb = self.time_embedding(t_emb, timestep_cond)
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/ssy/diffusers/src/diffusers/models/embeddings.py", line 228, in forward
    sample = self.linear_1(sample)
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data1/w425040/envs/SDXL/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat2 must be a matrix, got 1-d tensor

### Reproduction

the parameters I used as below:
  accelerate launch train_controlnet_sdxl.py \
       --pretrained_model_name_or_path=$MODEL_DIR \
       --output_dir=$OUTPUT_DIR \
       --dataset_name=/home2/ssy/sd_datasets/fill50k \
       --mixed_precision="fp16" \
       --resolution=1024 \
       --learning_rate=1e-5 \
       --max_train_steps=15000 \
       --validation_image "/home2/ssy/sd_datasets/conditioning_image_1.png" "/home2/ssy/sd_datasets/conditioning_image_2.png" \
       --validation_prompt "red circle with blue background" "cyan circle with brown floral background" \
       --validation_steps=10 \
       --train_batch_size=1 \
       --gradient_accumulation_steps=4 \
       --seed=42 \
       --enable_npu_flash_attention

### System Info

numpy 1.24.4
diffuser 0.25.0

**Comment by DN6** [comment]
@JUN20240101 Could you provide more details about your system? How many GPUs are you trying to use?

**Comment by JUN20240101** [comment]
@DN6 ，
> @JUN20240101 Could you provide more details about your system? How many GPUs are you trying to use?
I used 8 GPUs, I tried to finetune model with lora & controlnet, got similar problem, it looks like FSDP will flatten controlnet model when running in paralell, but did not correct recover it.

Accelerate config as below:
compute_environment: LOCAL_MACHINE
debug: true
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: NO_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: false
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: 2
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: false
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by hezhiyang2000** [comment]
I have the same question!

**Comment by TajnyReddy** [comment]
Me neither, but for CO-DETR finetuning with mmdetection repo

**Comment by weixiong-ur** [comment]
Is this issue resolved? I still face this issue when I run the latest diffusers 0.32 and the dreambooth flux example. What is the reason leading to this error?

**Comment by ZhaoChuyang** [comment]
I find the reason, the module directly wrapped in FSDP will flatten its parameters to 1D, and can only be called by the `.forward()` method from it, where the shape of the input tensor will automatically flatten and flatten back from 1D. If use other methods to call sub-module of it, whose parameters is already be flattened into 1D tensor, the error raises. My solution is to remove the module from the FSDP wrap config.

**Comment by a-r-r-o-w** [comment]
@ZhaoChuyang If you're using a custom method other than `forward`, I think you need to register it with FSDP: https://github.com/pytorch/pytorch/pull/125394. I ran into a similar issue recently with some custom code.

I think the easiest way to get around these problems is to use FSDP2 instead since it does not flatten parameters and is generally easier to debug (atleast for me).

**Comment by ZhaoChuyang** [comment]
> [@ZhaoChuyang](https://github.com/ZhaoChuyang) If you're using a custom method other than `forward`, I think you need to register it with FSDP: [pytorch/pytorch#125394](https://github.com/pytorch/pytorch/pull/125394). I ran into a similar issue recently with some custom code.
> 
> I think the easiest way to get around these problems is to use FSDP2 instead since it does not flatten parameters and is generally easier to debug (atleast for me).

Thanks! I will take a try with FSDP2.

**Comment by liming-ai** [comment]
> [@ZhaoChuyang](https://github.com/ZhaoChuyang) If you're using a custom method other than `forward`, I think you need to register it with FSDP: [pytorch/pytorch#125394](https://github.com/pytorch/pytorch/pull/125394). I ran into a similar issue recently with some custom code.
> 
> I think the easiest way to get around these problems is to use FSDP2 instead since it does not flatten parameters and is generally easier to debug (atleast for me).

Hi @a-r-r-o-w,

Could you kindly provide a toy example to show how we can register it with FSDP in diffusers (accelerate)?
By the way, when I replace FSDP with FSDP2, I have the same issue, seems that FSDP2 also flatten parameters...

**Comment by sayakpaul** [comment]
Cc: @S1ro1 here.

**Comment by a-r-r-o-w** [comment]
@liming-ai FSDP2 does not flatten parameters, so it's probably not applied properly.

To use FSDP2, accelerate added native support recently, so it should be easy to add it to any accelerate-based training script (https://github.com/huggingface/accelerate/releases/tag/v1.6.0).

I don't have a minimal example, but hopefully this may help you: https://github.com/a-r-r-o-w/finetrainers/blob/c40d2cc10abc44a7dd6087d9b3dbd4c4dfea709f/finetrainers/parallel/ptd.py#L458

You can import `fully_shard` from pytorch and apply it to each transformer block and the encompassing module.

**Comment by Selen-Suyue** [comment]
@ZhaoChuyang Thank you for your comment! That really helps me a lot!
