### ISSUE TITLE
Function `prepare_latents` mistreated image as latents in stable diffusion img2img pipeline (as well as StableDiffusionXLImg2ImgPipeline), when input PIL.Image.Image has 4 channels 'RGBA'

### ISSUE THREAD

**Issue by fkcptlst** [huggingface/diffusers#6548]
### Describe the bug

In function 
```
def prepare_latents(
        self, image, timestep, batch_size, num_images_per_prompt, dtype, device, generator=None, add_noise=True
    ):
...
```

there is an if-else statement trying to determine whether input image is a 4-channel latent.

```
if image.shape[1] == 4:
    init_latents = image
else:
    ...
```

However, when input image has an extra alpha channel, this func mistreats it as latents. Instead of encoding it via vae, it directly returns the input image, resulting a huge VRAM demand when decoding via vae and produces erroneous results. 

### Reproduction

Use a 4-channel RGBA png image in an img2img pipeline, and it should produce CUDA OOM error

### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.19.3
- Platform: Linux-5.10.101-1.el8.ssai.x86_64-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.20.2
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
Hey @fkcptlst,

Could you try to add a fully reproducible code snippet?

**Comment by fkcptlst** [comment]
> Hey @fkcptlst,
> 
> Could you try to add a fully reproducible code snippet?

```python
import matplotlib.pyplot as plt
import torch
from PIL import Image
from diffusers import StableDiffusionXLImg2ImgPipeline

with torch.device("cpu"):
    pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0",
        local_files_only=True,
        cache_dir="./.cache",
        torch_dtype=torch.float16
    )

pipe = pipe.to("cuda")

initial_image = Image.open("banana_grid_0_0.png")

image = pipe(
    image=initial_image,
    prompt="A photo realistic ripe banana",
).images[0]

plt.imshow(image)
plt.show()
```

Image here, make sure to save it with RGBA in png format.

![banana_grid_0_0](https://github.com/huggingface/diffusers/assets/79003314/5138aa80-f796-41bc-af73-64c25f02a149)

**Comment by patrickvonplaten** [comment]
Can you just replace:

```diff
- initial_image = Image.open("banana_grid_0_0.png")
+ initial_image = Image.open("banana_grid_0_0.png").convert('RGB')
```

**Comment by fkcptlst** [comment]
Yes, that is what I did.

I just thought it would be nice if there is an "RGB" or "RGBA" check in the image processor. (or a hint in the docstring)
