### ISSUE TITLE
Importing SD 1.5: `text_config_dict` is provided which will be used to initialize `CLIPTextConfig`.

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#6567]
### Describe the bug

I'm getting this error/debug info when I import the runway SD 1.5 checkpoint. Is it a bug or something I can do something about in my end? 

```
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
```

### Reproduction

```
from diffusers import StableDiffusionPipeline
import torch
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
)
```

### Logs

```shell
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
```

### System Info

Diffusers: 0.25.0
Win 11

### Who can help?

@yiyixuxu @DN6 @sayakpaul @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @tin2tin,

Could you maybe post your full environment here by running:

`diffusers-cli env` ?

I'm especially interested in the `transformers` version you're using

**Comment by PawtingDev** [comment]
Same issue here
outputs of `diffusers-cli env`
```
- `diffusers` version: 0.24.0
- Platform: Linux-6.5.0-14-generic-x86_64-with-glibc2.35
- Python version: 3.10.13
- PyTorch version (GPU?): 2.1.1+cu118 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: YES
- Using distributed or parallel set-up in script?: NO
```

**Comment by tin2tin** [comment]
I'm on Transformers 0.37.0dev0.

**Comment by patrickvonplaten** [comment]
This faulty warning was indeed present when using the latest `transformers==4.36`, but we've corrected it on "main" with [this PR](https://github.com/huggingface/transformers/pull/28108). So it shouldn't be present anymore when installing transformers from main (transformers>=4.37) which I confirmed here: https://colab.research.google.com/drive/1f-D0w4SsDuOINY4C4RoPN0WhV8CK-t2n?usp=sharing

@tin2tin can you maybe double check that you're actually using a transformers version >= 4.37?
