### ISSUE TITLE
[Tracker] change to posix for better Windows support

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#6585]
In https://github.com/huggingface/diffusers/pull/6564, @fabiorigano introduced the use of Posix to better support Windows compatibility. 

It'd be nice to change the instances of `os.path.join()` to `Path(...).as_posix()`. 

Feel free to open PRs for this and tag me. 

While opening PRs, please target only ONE script at a time. 

Let's go 🚀

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul, I checked the mentioned PR and also understood the issue. This is a documentation change right? We need to change every instance of `os.path.join()` to `Path(...).as_posix()`?

**Comment by charchit7** [comment]
> Hi @sayakpaul, I checked the mentioned PR and also understood the issue. This is a documentation change right? We need to change every instance of `os.path.join()` to `Path(...).as_posix()`?

Hey @Bhavay-2001 this is not a documentation change. Try going through this issue #6561 you'll understand why we are doing this.

**Comment by gzguevara** [comment]
Hi, @sayakpaul! Those this issue request to change all os.path.join() instances in the whole Diffusers repo? Can I just take any script containing os.path.join() and change it?

**Comment by sayakpaul** [comment]
I think so.

**Comment by gzguevara** [comment]
@sayakpaul there are quite a few such instances in training examples. I will tackle a few. ok?

**Comment by sayakpaul** [comment]
I think those are fine to leave as is because most of the training doesn't take place on Windows.

**Comment by Stepheni12** [comment]
@sayakpaul I searched across the entire diffusers repo and 111 files contain instance(s) of `os.path.join` however as you previously mentioned a lot of that is related to training. I then did a targeted search within `diffusers/src/diffusers` and this revealed a much smaller [subset](https://github.com/search?q=repo%3Ahuggingface%2Fdiffusers+os.path.join+path%3A%2F%5Esrc%5C%2Fdiffusers%5C%2F%2F&type=code) that contains 11 files and ~55 instances of `os.path.join`. One of these 11 files was addressed by Bhavay in this [PR](https://github.com/huggingface/diffusers/pull/6672). Would it be worth me going after the other 10 files, most of which are within `diffusers/src/diffusers/utils` and `diffusers/src/diffusers/pipelines`?

**Comment by sayakpaul** [comment]
Yeah that works for me.

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul, could you please review my PR.
Thanks

**Comment by sayakpaul** [comment]
Where is it?

**Comment by Bhavay-2001** [comment]
Please find the [PR](https://github.com/huggingface/diffusers/pull/6672) here

**Comment by Bhavay-2001** [comment]
Also, @Stepheni12 if you don't mind can we distribute the following tasks?

**Comment by Stepheni12** [comment]
Yes, @Bhavay-2001 that sounds good! There were 11 files in total and your PR already did one of them so we can just split the other 10 from this [subset](https://github.com/search?q=repo%3Ahuggingface%2Fdiffusers+os.path.join+path%3A%2F%5Esrc%5C%2Fdiffusers%5C%2F%2F&type=code). You can take the top 5 files which are:
>src/diffusers/utils/hub_utils.py
>src/diffusers/utils/constants.py
>src/diffusers/models/modeling_flax_utils.py
>src/diffusers/configuration_utils.py
>src/diffusers/utils/dynamic_modules_utils.py

and then I'll take the bottom half of the list which are:

>src/diffusers/pipelines/onnx_utils.py
>src/diffusers/pipelines/pipeline_flax_utils.py
>src/diffusers/models/modeling_utils.py
>src/diffusers/utils/testing_utils.py
>src/diffusers/pipelines/pipeline_utils.py

**Comment by Bhavay-2001** [comment]
Sure @Stepheni12, I will update the mentioned files

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul , @yiyixuxu it would be great if you guys could review the PRs associated with the issue and merge it or let us know of any changes to be made. Thanks

**Comment by Bhavay-2001** [comment]
The PRs are mentioned here. @csaybar
