### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml

### ISSUE THREAD

**Issue by Louis24** [huggingface/diffusers#6594]
### Describe the bug

Even I give all the weight and config_file, it still try to connect the internet

### Reproduction

    pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
                                                              torch_dtype=torch.float16,
                                                              use_safetensors=True,
                                                              safety_checker=None,
                                                              load_safety_checker=False,
                                                              local_files_only=True,
                                                              requires_safety_checker=False,
                                                              config_file="v1-inference.yaml")

    pipe.load_lora_weights(lora_model)

    pipe.vae = diffusers.AutoencoderKL.from_pretrained("C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors.safetensors")
    pipe.scheduler = diffusers.schedulers.DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)
    pipe = pipe.to("cuda")

### System Info

Platform: Win10
Python version: 3.10.11
PyTorch version (GPU?): 2.0.1+cu118
diffusers version: 0.16.1
Transformers version: 4.26.0
Accelerate version: 0.15.0
xFormers version: not installed
Using GPU in script?: 3070
Using distributed or parallel set-up in script?: No

### Who can help?

@yiyixuxu @DN6 @sayakpaul @patrickvonplaten Thank you guys

**Comment by DN6** [comment]
@Louis24 Can you try 
```python
pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
                                                          torch_dtype=torch.float16,
                                                          use_safetensors=True,
                                                          safety_checker=None,
                                                          load_safety_checker=False,
                                                          local_files_only=True,
                                                          requires_safety_checker=False,
                                                          original_config_file="v1-inference.yaml")

pipe.load_lora_weights(lora_model)

pipe.vae = diffusers.AutoencoderKL.from_pretrained("C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors.safetensors")
pipe.scheduler = diffusers.schedulers.DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)
pipe = pipe.to("cuda")
```

**Comment by Honey-666** [comment]
> ### Describe the bug
> 
> Even I give all the weight and config_file, it still try to connect the internet
> ### Reproduction
> 
> ```
> pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
>                                                           torch_dtype=torch.float16,
>                                                           use_safetensors=True,
>                                                           safety_checker=None,
>                                                           load_safety_checker=False,
>                                                           local_files_only=True,
>                                                           requires_safety_checker=False,
>                                                           config_file="v1-inference.yaml")
> 
> pipe.load_lora_weights(lora_model)
> 
> pipe.vae = diffusers.AutoencoderKL.from_pretrained("C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors.safetensors")
> pipe.scheduler = diffusers.schedulers.DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)
> pipe = pipe.to("cuda")
> ```
> 
> ### Logs
> 
> _No response_
> ### System Info
> 
> Platform: Win10 Python version: 3.10.11 PyTorch version (GPU?): 2.0.1+cu118 diffusers version: 0.16.1 Transformers version: 4.26.0 Accelerate version: 0.15.0 xFormers version: not installed Using GPU in script?: 3070 Using distributed or parallel set-up in script?: No
> ### Who can help?
> 
> @yiyixuxu @DN6 @sayakpaul @patrickvonplaten Thank you guys

It should not have found the file in your path, you can try to download the 'v1-inference.yaml' file locally and manually specify your local path

**Comment by yiyixuxu** [comment]
this should be fixed https://github.com/huggingface/diffusers/issues/6594#issuecomment-1894044898
