### ISSUE TITLE
cross_attention_kwargs={"scale": 1} not work

### ISSUE THREAD

**Issue by loboere** [huggingface/diffusers#6606]
cross_attention_kwargs value only goes down it doesn't go up

first I generate an image with cross_attention_kwargs={"scale": 1} 
```
image = pipe(prompt=prompt,
                  negative_prompt="",
                  cross_attention_kwargs={"scale": 1} ,
                  num_inference_steps=25,
                  generator=generator,
                  image=imagen).images[0]
```

then lower the value of cross_attention_kwargs
```
image = pipe(prompt=prompt,
                  negative_prompt="",
                  cross_attention_kwargs={"scale": 0.6} ,
                  num_inference_steps=25,
                  generator=generator,
                  image=imagen).images[0]
```

then I want to go back up to 1 but it stays at 0.6 
cross_attention_kwargs={"scale": 1}  generates the same image that  cross_attention_kwargs={"scale": 0.6}

  I can only lower the value but it doesn't go up

**Comment by DN6** [comment]
@loboere Can you provide a fully reproducible code example to demonstrate the issue? I don't know what pipeline or model you are experiencing an issue with.

**Comment by yiyixuxu** [comment]
could be related https://github.com/huggingface/diffusers/pull/6736
and should have already fixed

**Comment by yiyixuxu** [comment]
fixed in https://github.com/huggingface/diffusers/pull/6736
