### ISSUE TITLE
Clarification on noise scheduler mismatch in example train_controlnet.py

### ISSUE THREAD

**Issue by vidyasiv** [huggingface/diffusers#6607]
Hello,

In examples/controlnet/train_controlnet.py, the noise scheduler class is DDPMScheduler but however the scheduler config loaded based on the one in the model's scheduler folder i.e PNDM Scheduler per https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/scheduler/scheduler_config.json . Why don't they match?

**Comment by patrickvonplaten** [comment]
Hey @vidyasiv,

We're trying to leave issues mainly for bug reports - could you maybe ask your question in [our Discussions](https://github.com/huggingface/diffusers/discussions)?

**Comment by vidyasiv** [comment]
Moved to https://github.com/huggingface/diffusers/discussions/6618
