### ISSUE TITLE
How to train text_to_image with images which is resolution of 512x768 ?

### ISSUE THREAD

**Issue by lingxuan630** [huggingface/diffusers#6614]
I want to finetune the sd1.5 with 50k images, all the image is resolution of 512x768. But I got error like this:

`train_text_to_image.py:` error: argument --resolution: invalid int value: '[512,768]'`

so, how to train text_to_image with images which is resolution of 512x768?

**Comment by sayakpaul** [comment]
It might be a better discussion rather than an issue. 


I think you will have to make adjustments to the training script to facilitate these custom resolution types. The `resolution` arg doesn't allow for inputs like that.

**Comment by lingxuan630** [comment]
> It might be a better discussion rather than an issue.
> 
> I think you will have to make adjustments to the training script to facilitate these custom resolution types. The `resolution` arg doesn't allow for inputs like that.

Thank you. By modified the `text_to_image.py` script, I can train with 512 x 768. The number 512 is just hard code in the script.
