### ISSUE TITLE
Implementation of Classifier-guidance in diffusers

### ISSUE THREAD

**Issue by shengyenlin** [huggingface/diffusers#6616]
### Model/Pipeline/Scheduler description

Hello the community, 

I was wondering if there's an implementation of classifier-guidance (from the paper "Diffusion Models Beat GANs on Image Synthesis") with stable diffusion in diffusers (or in any github repo, please let we know). Although I know it's not the most efficient way to add condition into diffusion model, some papers still used this method for conditional generation and there's currently no way to reproduce results in this setting.

### Open source status

- [V] The model implementation is available.
 
### Provide useful links for the implementation

[Guided-diffusion](https://github.com/openai/guided-diffusion)

**Comment by sayakpaul** [comment]
Cc: @patil-suraj @patrickvonplaten

**Comment by DN6** [comment]
Hi @shengyenlin while it might not be the most ideal way, you should be able implement classifier guidance using callbacks 
https://huggingface.co/docs/diffusers/using-diffusers/callback

**Comment by sayakpaul** [comment]
I think it is safe to be closed now. Feel free to reopen if not.
