### ISSUE TITLE
[Model] Scalable Interpolant Transformers 

### ISSUE THREAD

**Issue by a-r-r-o-w** [huggingface/diffusers#6635]
We have another diffusion model without a UNet backbone - SiT (Scalable Interpolant Transformers), with a great demonstration and a really lovely paper!

![visual](https://github.com/huggingface/diffusers/assets/72266394/d0a05ab4-2016-4688-a983-f25f4506db28)

Metrics for class-conditional generation on ImageNet 256x256 <strong>(SiT-XL surpasses DiT-XL in FID when using either of the samplers, ODE or SDE-based):</strong>

<table class="display-table" style="text-align: left;">
    <tr>
        <th colspan="6">Class-Conditional ImageNet (256x256)</th>
    </tr>
    <tr>
        <th>Model</th>
        <th>FID (lower is better)</th>
        <th>sFID (lower is better)</th>
        <th>IS (higher is better)</th>
        <th>Precision (higher is better)</th>
        <th>Recall (higher is better)</th>
    </tr>
    <tr>
        <td>BigGAN-deep<d-cite key="brock2019large"></d-cite></td>
        <td>6.95</td>
        <td>7.36</td>
        <td>171.4</td>
        <td><strong>0.87</strong></td>
        <td>0.28</td>
    </tr>
    <tr>
        <td>StyleGAN-XL<d-cite key="karras2019stylebased"></d-cite></td>
        <td>2.30</td>
        <td><strong>4.02</strong></td>
        <td>265.12</td>
        <td>0.78</td>
        <td>0.53</td>
    </tr>
    <tr>
        <td>Mask-GIT<d-cite key="chang2022maskgit"></d-cite></td>
        <td>6.18</td>
        <td>-</td>
        <td>182.1</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>ADM<d-cite key="dhariwal2021diffusion"></d-cite></td>
        <td>10.94</td>
        <td>6.02</td>
        <td>100.98</td>
        <td>0.69</td>
        <td>0.63</td>
    </tr>
    <tr>
        <td>ADM-G, ADM-U</td>
        <td>3.94</td>
        <td>6.14</td>
        <td>215.84</td>
        <td>0.83</td>
        <td>0.53</td>
    </tr>
    <tr>
        <td>CDM<d-cite key="ho2021cascaded"></d-cite></td>
        <td>4.88</td>
        <td>-</td>
        <td>158.71</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>RIN<d-cite key="jabri2023scalable"></d-cite></td>
        <td>3.42</td>
        <td>-</td>
        <td>182.0</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>Simple Diffusion(U-Net)<d-cite key="hoogeboom2023simple"></d-cite></td>
        <td>3.76</td>
        <td>-</td>
        <td>171.6</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>Simple Diffusion(U-ViT, L)</td>
        <td>2.77</td>
        <td>-</td>
        <td>211.8</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>VDM++<d-cite key="kingma2023understanding"></d-cite></td>
        <td>2.12</td>
        <td>-</td>
        <td>267.7</td>
        <td>-</td>
        <td>-</td>
    </tr>
    <tr>
        <td>DiT-XL(cfg=1.5)</td>
        <td>2.27</td>
        <td>4.60</td>
        <td>278.24</td>
        <td>0.83</td>
        <td>0.57</td>
    </tr>
    <tr>
        <td><strong>SiT-XL(cfg=1.5, ODE)</strong></td>
        <td>2.15</td>
        <td>4.60</td>
        <td>258.09</td>
        <td>0.81</td>
        <td>0.60</td>
    </tr>
    <tr>
        <td><strong>SiT-XL(cfg=1.5, SDE:(sigma_t))</strong></td>
        <td><strong>2.06</strong></td>
        <td>4.50</td>
        <td>270.27</td>
        <td>0.82</td>
        <td>0.59</td>
    </tr>
</table>

Code: https://github.com/willisma/SiT/
Paper: https://arxiv.org/abs/2401.08740
Project Site: https://scalable-interpolant.github.io/
Authors: @willisma @marikgoldstein @malbergo @nmboffi [Eric Vanden-Eijnden](https://wp.nyu.edu/courantinstituteofmathematicalsciences-eve2/) @s9xie

Thank you for your amazing work! Can't wait to deep dive into learning more of your research and the code base.

@sayakpaul @DN6 @patrickvonplaten 

Apologies for the irrelevant but related issue name - just reminded me of an [old song](https://www.youtube.com/watch?v=uPHKkewD1G0) that my younger sister listens to :laughing:

**Comment by charchit7** [comment]
yeah, looks cool. AK also shared this. Wondering if it's accepted anywhere yet.

**Comment by sayakpaul** [comment]
The benchmarks and the results don't look exceptional in comparison to what we already have in the library, though. Plus it doesn't have text conditioning support from what I gather. So, maybe not a core pipeline yet.

**Comment by a-r-r-o-w** [comment]
> The benchmarks and the results don't look exceptional in comparison to what we already have in the library, though. Plus it doesn't have text conditioning support from what I gather. So, maybe not a core pipeline yet. 

That is correct, the sampling uses the class label from imagenet-1k to condition. I'd be interested in training a small text conditioned model once I understand more of the modelling and have a better intuition here, if it is possible.

**Comment by AmericanPresidentJimmyCarter** [comment]
> The benchmarks and the results don't look exceptional in comparison to what we already have in the library, though. Plus it doesn't have text conditioning support from what I gather. So, maybe not a core pipeline yet.

I agree with this -- if you look at the paper appendix the images do not appear to have any advantage as compared to DiT. FID is a known broken metric (see: "Exposing flaws of generative model evaluation metrics and their unfair treatment of diffusion models") and if you retrained DiT with v-pred and used a better sampler than DDIM, which the paper did, I suspect you would see a similar performance improvement. Overall the paper showed how strong DDPM continues to be without any modification.

**Comment by sayakpaul** [comment]
Okay to keep this closed?

**Comment by ai-jz** [comment]
> The benchmarks and the results don't look exceptional in comparison to what we already have in the library, though. Plus it doesn't have text conditioning support from what I gather. So, maybe not a core pipeline yet.

I am new to the diffusers library. Is there a guidance on how to choose the best models already implemented in the library? Say, are there public benchmarks and results that I can use as a reference, instead of manually check and compare the generated images?
