### ISSUE TITLE
Implement StreamDiffusion

### ISSUE THREAD

**Issue by gabgren** [huggingface/diffusers#6641]
Would it be possible to implement the pipeline optimisations from Stream Diffusion ?

https://github.com/cumulo-autumn/StreamDiffusion

https://huggingface.co/papers/2312.12491

**Comment by DN6** [comment]
Hi @gabgren were there any specific optimisations you had in mind?  StreamDiffusion is built on top of `diffusers` so they already seem to work quite well together.
