### ISSUE TITLE
Adopting different image aspect ratio in training?

### ISSUE THREAD

**Issue by linnanwang** [huggingface/diffusers#6659]
**Is your feature request related to a problem? Please describe.**
Hello there,

I have a question regarding the UNet and Lora Training in image AR other than 1:1. Right now I saw the data is resized to 1:1 using the linear interpolation provided from pytorch. But my question is how to handle 16:9 images? Thanks.

Perhaps resize the image proportionally with length to 1024 and pad the white space in width?

**Comment by DN6** [comment]
Using 16:9 aspect ratio with a width of 1024 would mean the image height is 576. This should work fine depending on the model you're training. Padding with whitespace might lead to whitespace in the outputs as well.

**Comment by linnanwang** [comment]
Thanks @DN6 , what's the right way to handle 16:9 images?

**Comment by yiyixuxu** [comment]
can we use forums for questions? https://github.com/huggingface/diffusers/discussions

**Comment by a-r-r-o-w** [comment]
Marking as closed due to inactivity. Should move to discussion though, if you're still interested!
