### ISSUE TITLE
How to resume from checkpoint.

### ISSUE THREAD

**Issue by BakingBrains** [huggingface/diffusers#666]
I followed Colab for training. May I know how to resume the training.

Thanks and regards

**Comment by patil-suraj** [comment]
Hi @BakingBrains ! We haven't yet added the checkpoint saving and resuming features to the training scripts yet. It's on my todo list. Feel free to open a PR if you are interested, would be very happy to help :)

**Comment by patrickvonplaten** [comment]
Also related to https://github.com/huggingface/diffusers/issues/732 

@patil-suraj any updates here?

**Comment by patrickvonplaten** [comment]
Gently ping @patil-suraj
