### ISSUE TITLE
export_to_video issue

### ISSUE THREAD

**Issue by lucken99** [huggingface/diffusers#6681]
#### This issue is coming, it was not there yesterday:

ValueError                                Traceback (most recent call last)
[<ipython-input-2-0a17f43bdbef>](https://localhost:8080/#) in <cell line: 10>()
      8 prompt = "Spiderman is surfing"
      9 video_frames = pipe(prompt).frames
---> 10 video_path = export_to_video(video_frames, output_video_path="./spidey_surfing.mp4")
     11 video_path

[/usr/local/lib/python3.10/dist-packages/diffusers/utils/export_utils.py](https://localhost:8080/#) in export_to_video(video_frames, output_video_path, fps)
    130 
    131     fourcc = cv2.VideoWriter_fourcc(*"mp4v")
--> 132     **h, w, c = video_frames[0].shape**
    133     video_writer = cv2.VideoWriter(output_video_path, fourcc, fps=fps, frameSize=(w, h))
    134     for i in range(len(video_frames)):

ValueError: too many values to unpack (expected 3)

**Comment by lucken99** [comment]
May be because video_frames[0] has shape = (16, 256, 256, 3)

**Comment by lucken99** [comment]
Problem with main but stable is working fine

**Comment by DN6** [comment]
Hi @lucken99 could you please share a code example so that I can reproduce the error. We recently merged #6626 that could cause this issue.

**Comment by lucken99** [comment]
It's there in the post itself while calling pipe.
You can check the full code here:
[T2V](https://huggingface.co/docs/diffusers/api/pipelines/text_to_video)

**Comment by yiyixuxu** [comment]
fixed with https://github.com/huggingface/diffusers/pull/6715
