### ISSUE TITLE
Controlnet weight decay

### ISSUE THREAD

**Issue by seokjin1013** [huggingface/diffusers#6711]
I am working on creating a pipeline using a1111 or comfyui and implementing it with diffusers. In the controlnet mode of a1111, there is an option called 'my prompt is more important.' According to the internal implementation, this feature slowly decays from 1 by 0.85 at each denoising step. This greatly affects the quality of the output. (The weight decay feature is also supported in comfyui.) I have successfully implemented this feature indirectly through the `call_back_on_step_end` callback function. However, I face the inconvenience of having to manually reset the variable used for decay after each inference. Please officially support weight decay. Thank you.

**Comment by yiyixuxu** [comment]
hi:
I would like to understand more about this
>  I face the inconvenience of having to manually reset the variable used for decay after each inference.

we added `call_back_on_step_end` for user cases exactly like this one! so I want to know why it is inconvenient and how can we improve it:)

YiYi

**Comment by yiyixuxu** [comment]
gentle pin here @seokjin1013 
if you can share your implementation for weight decay vis callbacks on our forums here, it will be great! https://github.com/huggingface/diffusers/discussions/categories/ideas

It can also help us to understand how we can make it more convenient for people to use this feature

**Comment by Scorpinaus** [comment]
not stale?

**Comment by yiyixuxu** [comment]
closing it now due to inactivity! feel free to send a PR to our community script folder https://github.com/huggingface/diffusers/blob/main/examples/community/README_community_scripts.md
