### ISSUE TITLE
trained_betas param is not documented in DDPMScheduler class

### ISSUE THREAD

**Issue by agramfort** [huggingface/diffusers#6732]
### Describe the bug

trained_betas param is not documented in DDPMScheduler. Docstring should be updated here:

https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py#L145

### Reproduction

see https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py#L145

### System Info

any

### Who can help?

@stevhliu

**Comment by stevhliu** [comment]
Good catch! Would you like to open a PR to add `trained_betas` to the docstring? 🤗

**Comment by agramfort** [comment]
I don't work on the dev version now. I'll let you beat me to it. Happy to
review though ;)
