### ISSUE TITLE
AttributeError: 'StableDiffusionPipeline' object has no attribute 'load_ip_adapter'

### ISSUE THREAD

**Issue by Lhqy1111** [huggingface/diffusers#6733]
This error is reported when running the pipeline. Does anyone know how to solve it?

**Comment by fabiorigano** [comment]
What is your diffusers version?

**Comment by Lhqy1111** [comment]
The problem has been solved,thank you!
&nbsp;


敏拉拉拉敏?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dhruv ***@***.***&gt;; 
发送时间: 2024年1月29日(星期一) 下午4:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huggingface/diffusers] AttributeError: &#39;StableDiffusionPipeline&#39; object has no attribute &#39;load_ip_adapter&#39; (Issue #6733)





 
@Lhqy1111 Could you please provide a code example we can use to reproduce your error? Also can you run diffusers-cli env and share the output.
