### ISSUE TITLE
'NoneType' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by loboere** [huggingface/diffusers#6734]
I try to run sd.15 but it gives an error AttributeError: 'NoneType' object has no attribute 'tokenize'

diffusers Version: 0.25.1
```
from diffusers import DiffusionPipeline, StableDiffusionXLImg2ImgPipeline
import torch



pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    'runwayml/stable-diffusion-v1-5',
     torch_dtype=torch.float16,
     safety_checker=None
)
pipe.to("cuda")

from PIL import Image

# Abre una imagen
imagen = Image.open("/content/cara.png").convert('RGB').resize((512,512))

for i in range(15,25):
  seed = i
  print(i)
  generator = torch.Generator("cuda").manual_seed(seed)
 # image = pipe(   prompt=prompt, steps=25,generator=generator).images[0]
  image = pipe(prompt="a girl",
                  negative_prompt="",
                  strength=1,
                  num_inference_steps=25,
                  generator=generator,
                  image=imagen).images[0]
  image.save("generated_image"+str(i)+".png")
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-6-ccfccf35e70b>](https://localhost:8080/#) in <cell line: 7>()
     11   generator = torch.Generator("cuda").manual_seed(seed)
     12  # image = pipe(   prompt=prompt, steps=25,generator=generator).images[0]
---> 13   image = pipe(prompt="a girl",
     14                   negative_prompt="",
     15                   strength=1,

5 frames
[/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
    113     def decorate_context(*args, **kwargs):
    114         with ctx_factory():
--> 115             return func(*args, **kwargs)
    116 
    117     return decorate_context

[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py](https://localhost:8080/#) in __call__(self, prompt, prompt_2, image, strength, num_inference_steps, timesteps, denoising_start, denoising_end, guidance_scale, negative_prompt, negative_prompt_2, num_images_per_prompt, eta, generator, latents, prompt_embeds, negative_prompt_embeds, pooled_prompt_embeds, negative_pooled_prompt_embeds, ip_adapter_image, output_type, return_dict, cross_attention_kwargs, guidance_rescale, original_size, crops_coords_top_left, target_size, negative_original_size, negative_crops_coords_top_left, negative_target_size, aesthetic_score, negative_aesthetic_score, clip_skip, callback_on_step_end, callback_on_step_end_tensor_inputs, **kwargs)
   1247             pooled_prompt_embeds,
   1248             negative_pooled_prompt_embeds,
-> 1249         ) = self.encode_prompt(
   1250             prompt=prompt,
   1251             prompt_2=prompt_2,

[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py](https://localhost:8080/#) in encode_prompt(self, prompt, prompt_2, device, num_images_per_prompt, do_classifier_free_guidance, negative_prompt, negative_prompt_2, prompt_embeds, negative_prompt_embeds, pooled_prompt_embeds, negative_pooled_prompt_embeds, lora_scale, clip_skip)
    413             for prompt, tokenizer, text_encoder in zip(prompts, tokenizers, text_encoders):
    414                 if isinstance(self, TextualInversionLoaderMixin):
--> 415                     prompt = self.maybe_convert_prompt(prompt, tokenizer)
    416 
    417                 text_inputs = tokenizer(

[/usr/local/lib/python3.10/dist-packages/diffusers/loaders/textual_inversion.py](https://localhost:8080/#) in maybe_convert_prompt(self, prompt, tokenizer)
    135             prompts = prompt
    136 
--> 137         prompts = [self._maybe_convert_prompt(p, tokenizer) for p in prompts]
    138 
    139         if not isinstance(prompt, List):

[/usr/local/lib/python3.10/dist-packages/diffusers/loaders/textual_inversion.py](https://localhost:8080/#) in <listcomp>(.0)
    135             prompts = prompt
    136 
--> 137         prompts = [self._maybe_convert_prompt(p, tokenizer) for p in prompts]
    138 
    139         if not isinstance(prompt, List):

[/usr/local/lib/python3.10/dist-packages/diffusers/loaders/textual_inversion.py](https://localhost:8080/#) in _maybe_convert_prompt(self, prompt, tokenizer)
    158             `str`: The converted prompt
    159         """
--> 160         tokens = tokenizer.tokenize(prompt)
    161         unique_tokens = set(tokens)
    162         for token in unique_tokens:

AttributeError: 'NoneType' object has no attribute 'tokenize'

**Comment by standardAI** [comment]
Hi @loboere! Just replace `StableDiffusionXLImg2ImgPipeline` with `StableDiffusionImg2ImgPipeline`, and try again.

**Comment by yiyixuxu** [comment]
agree with @standardAI here
you can either do 
```python
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    'runwayml/stable-diffusion-v1-5',
     torch_dtype=torch.float16,
     safety_checker=None
)
```

or 
```python
pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
     torch_dtype=torch.float16,
)
```
