### ISSUE TITLE
LDM Bert `config.json` path

### ISSUE THREAD

**Issue by ryanrussell** [huggingface/diffusers#675]
### Problem
There is a reference to an LDM Bert that 404's
```bash
src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py:    "ldm-bert": "https://huggingface.co/ldm-bert/resolve/main/config.json",
```

I was able to locate a `config.json` at `https://huggingface.co/valhalla/ldm-bert/blob/main/config.json`

Is this the correct `config.json`? 

#### Notes for reviewer
Happy to send a PR if needed to update, feel free to do on your own if it's faster/easier :)

### Reproduction

na

### Logs

```shell
na
```

### System Info

na

**Comment by patrickvonplaten** [comment]
Yes this seems wrong, let's update it (cc @patil-suraj )
