### ISSUE TITLE
Enable batch processing from directory for multicontrolnets

### ISSUE THREAD

**Issue by G-force78** [huggingface/diffusers#6750]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

No working solution found to processing images from a directory
Error usually "TypeError: For multiple controlnets: `image` must be type `list`"

**Describe the solution you'd like.**

Specifying a directory from which to process images of the same name,  eg combine frame_0 and frame_0 from each directory to create a multiconditioned image

openpose_images = input_dir("/poseframes")
canny_images=input_dir1("/cannyframes")

*

**Additional context.**

Simply modification of this code to process images from a directory

from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
import torch

controlnet = [
    ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-openpose", torch_dtype=torch.float16),
    ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny", torch_dtype=torch.float16),
]

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16
)
pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)

pipe.enable_xformers_memory_efficient_attention()
pipe.enable_model_cpu_offload()

prompt = "a giant standing in a fantasy landscape, best quality"
negative_prompt = "monochrome, lowres, bad anatomy, worst quality, low quality"

generator = torch.Generator(device="cpu").manual_seed(1)

images = [openpose_image, canny_image]

image = pipe(
    prompt,
    images,
    num_inference_steps=20,
    generator=generator,
    negative_prompt=negative_prompt,
    controlnet_conditioning_scale=[1.0, 0.8],
).images[0]

image.save("./multi_controlnet/frame_0multi.png")

**Comment by yiyixuxu** [comment]
Hi:
we are not supporting this but it is very easy to do with one line of code 

```python
canny_images = [load_image(img_file) for img in os.listdir(folder_dir)]
```

**Comment by G-force78** [comment]
> Hi: we are not supporting this but it is very easy to do with one line of code
> 
> ```python
> canny_images = [load_image(img_file) for img in os.listdir(folder_dir)]
> ```

Wow it was that easy after all lol I tried so many different ways that failed. Thanks.
