### ISSUE TITLE
VaeImageProcessor.preprocess() got an unexpected keyword 

### ISSUE THREAD

**Issue by t00350320** [huggingface/diffusers#6761]
### Describe the bug

from diffusers.image_processor import PipelineImageInput   
 init_image = self.image_processor.preprocess(
TypeError: VaeImageProcessor.preprocess() got an unexpected keyword argument 'resize_mode'

### Reproduction

    init_image = self.image_processor.preprocess(
TypeError: VaeImageProcessor.preprocess() got an unexpected keyword argument 'resize_mode'

### Logs

```shell
init_image = self.image_processor.preprocess(
TypeError: VaeImageProcessor.preprocess() got an unexpected keyword argument 'resize_mode'
```

### System Info

diffusers : 0.24.0
python3.10
GPU V100

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul @yiyixuxu, is this a beginner related issue or does it need experience? I would like to solve it.
Thanks

**Comment by Bhavay-2001** [comment]
Hi @t00350320, I have looked into the preprocess method and the `resize_mode` parameter exists. Can you please provide a more detailed script?
Thanks

**Comment by t00350320** [comment]
> Hi @t00350320, I have looked into the preprocess method and the `resize_mode` parameter exists. Can you please provide a more detailed script? Thanks
sorry @Bhavay-2001 , it's my fault, 
upgrade diffusers : 0.24.0 to 0.25.0 has fix this error.
