### ISSUE TITLE
PixArt-XL-2-256x256 generations are messed up

### ISSUE THREAD

**Issue by stefan-canva** [huggingface/diffusers#6783]
### Describe the bug

All generations with the newly released PixArt-XL-2-256x256 model look like they are viewed through a ["clear grid glass"](https://www.pinterest.co.kr/pin/bower-studios-bower-material-library-sample-glass-clear-grid-mirrors-furniture--251990541644063730/).

![astronaut_rides_horse](https://github.com/huggingface/diffusers/assets/90706016/99133d1d-f70d-49a6-9809-87bd99225f92)

My colleague suspected that it is related to this snippet from line 172 in `transfomer_2d.py`:
```python
interpolation_scale = self.config.sample_size // 64  # => 64 (= 512 pixart) has interpolation scale 1
interpolation_scale = max(interpolation_scale, 1)
```
I tried setting interpolation_scale to 0.5, but it messed the image up even more.

### Reproduction

There is no complete config for the 256 and 512 pipelines, just for the 1024 version, so I just load the transformer from the 256 model and pass it when creating the pipeline. Not sure if this is the expected way to do it, but at least this works with the 512 model, so I guess it should also work with the 256 model:

``` python
from diffusers import PixArtAlphaPipeline, Transformer2DModel
import torch

transformer = Transformer2DModel.from_pretrained("PixArt-alpha/PixArt-XL-2-256x256", subfolder="transformer", torch_dtype=torch.float16)
pipe = PixArtAlphaPipeline.from_pretrained("PixArt-alpha/PixArt-XL-2-1024-MS", transformer=transformer, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]  
    
image.save("astronaut_rides_horse.png")
```

### System Info

- `diffusers` version: 0.25.1
- Platform: Linux-6.2.0-1017-aws-x86_64-with-glibc2.31
- Python version: 3.9.18
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- Huggingface_hub version: 0.20.3
- Transformers version: 4.37.2
- Accelerate version: 0.26.1
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@yiyixuxu @DN6 I guess you are the right ones to tag here.

**Comment by DN6** [comment]
cc: @sayakpaul for visibility

**Comment by sayakpaul** [comment]
Hmm. Cc: @lawrence-cj would you have any clue? 

I think using the 1024x1024 is not appropriate here because the internal configs might differ for 256.

**Comment by sayakpaul** [comment]
Just to clarify:

```python
from diffusers import PixArtAlphaPipeline, Transformer2DModel
import torch

transformer = Transformer2DModel.from_pretrained("PixArt-alpha/PixArt-XL-2-256x256", subfolder="transformer", torch_dtype=torch.float16)
pipe = PixArtAlphaPipeline.from_pretrained("PixArt-alpha/PixArt-XL-2-1024-MS", transformer=transformer, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]  
    
image.save("astronaut_rides_horse.png")
```

Does this work as expected?

**Comment by lawrence-cj** [comment]
Yeah, I know that. The bug is mentioned here: https://github.com/huggingface/diffusers/pull/6424. I think it's better to define the `interpolation_scale` through the config file.

**Comment by sayakpaul** [comment]
Thank you! We might need to host the 256 checkpoint separately as a pipeline. I believe that is the safest option.

**Comment by lawrence-cj** [comment]
New PR solving this issue: https://github.com/huggingface/diffusers/pull/6789

**Comment by stefsietz** [comment]
Thx for getting to this so quickly!

> Just to clarify:
> 
> ```python
> from diffusers import PixArtAlphaPipeline, Transformer2DModel
> import torch
> 
> transformer = Transformer2DModel.from_pretrained("PixArt-alpha/PixArt-XL-2-256x256", subfolder="transformer", torch_dtype=torch.float16)
> pipe = PixArtAlphaPipeline.from_pretrained("PixArt-alpha/PixArt-XL-2-1024-MS", transformer=transformer, torch_dtype=torch.float16)
> pipe = pipe.to("cuda")
> 
> prompt = "a photo of an astronaut riding a horse on mars"
> image = pipe(prompt).images[0]  
>     
> image.save("astronaut_rides_horse.png")
> ```
> 
> Does this work as expected?

No this didn't work for the 256 model, this produced the messed up image that I attached. It did work though for the 512 model, which also doesn't have a dedicated pipeline config.

Regarding the PR you opened, @lawrence-cj: as I wrote, setting the interpolation manually to 0.5 made the problem worse, it wasn't a proposed fix. (just want to clarify again as in the PR you are setting the interpolation scale to 0.5 for the 256 model).

**Comment by lawrence-cj** [comment]
Nope, actually the interpolation_scale for this 256 ckpt here is 1.0. So I recommend to define it from config file.

**Comment by stefsietz** [comment]
Ok yes, I tested applying just the pipeline changes in your PR (basically adding `ASPECT_RATIO_256_BIN` to the logic), and I can confirm that it works. This is the image that I generated with it. Thanks!
![astronaut_rides_horse](https://github.com/huggingface/diffusers/assets/2621937/520c5c11-61f1-4c93-a7c8-b54fef9b8388)

**Comment by stefsietz** [comment]
> So I recommend you implement all the changes in this PR. Setting the interpolation_scale still to 1.0.

So you say the interpolation_scale should remain 1.0 (which I confirmed works with the pipeline changes), but what is this line in the PR about? This confused me.

https://github.com/huggingface/diffusers/blob/a57a89ab9e5ca5e953b82dc006d337cd3ad93d88/scripts/convert_pixart_alpha_to_diffusers.py#L12

**Comment by lawrence-cj** [comment]
Yah, in later future version of Pixart, it should be 0.5. Only the first version is not 0.5, which may cause confused. (We didn’t consider it all at the beginning.

**Comment by sayakpaul** [comment]
If the new PR solves it without having to serialize a separate pipeline that is great. 

Could you maybe provide a code snippet for it too?

We should add a slow test too to make sure things don’t break.

**Comment by lawrence-cj** [comment]
Cool. Added a code snippet for the PR. It's the same as the above one. https://github.com/huggingface/diffusers/pull/6789#issuecomment-1920496489
