### ISSUE TITLE
How to finetune stable diffusion img2img(like instructpix2pix or controlnet) model with only one input channel?

### ISSUE THREAD

**Issue by sapkun** [huggingface/diffusers#6785]
Hello, experts!
I want to finetune stable diffusion img2img(like instructpix2pix or controlnet) model with only one input channel or greyscale image? I saw official docs says it is ok to increase the input channel from 4 to 9, but I want to know that is this ok to decrease the input channel to be one for finetuning?
Thanks in advance!

**Comment by sapkun** [comment]
@sayakpaul Looking forward to your answer, Thanks!

**Comment by sayakpaul** [comment]
Can you open a discussion instead? https://github.com/huggingface/diffusers/discussions

Feel free to tag me there.
