### ISSUE TITLE
train_text_to_image_sdxl.py can't run

### ISSUE THREAD

**Issue by xxxyyycc** [huggingface/diffusers#6791]
### Describe the bug

I am running the training code according to the readme: https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/README_sdxl.md

I set the $MODEL_NAME to the local downloaded  path, model was downloade from https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/tree/main
the model seems only has .safetensros type file

### Reproduction

`accelerate launch train_text_to_image_lora_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --pretrained_vae_model_name_or_path=$VAE_NAME \
  --dataset_name=$DATASET_NAME --caption_column="text" \
  --resolution=1024 --random_flip \
  --train_batch_size=1 \
  --num_train_epochs=2 --checkpointing_steps=500 \
  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --mixed_precision="fp16" \
  --seed=42 \
  --output_dir="sd-pokemon-model-lora-sdxl" \
  --validation_prompt="cute dragon creature" --report_to="wandb" \
  --push_to_hub`

### Logs

```shell
Traceback (most recent call last):
  File "/workspace/lora_dataset/train_text_to_image_lora_sdxl.py", line 1288, in <module>
Traceback (most recent call last):
  File "/workspace/lora_dataset/train_text_to_image_lora_sdxl.py", line 1288, in <module>
    main(args)
  File "/workspace/lora_dataset/train_text_to_image_lora_sdxl.py", line 556, in main
    main(args)
  File "/workspace/lora_dataset/train_text_to_image_lora_sdxl.py", line 556, in main
    text_encoder_one = text_encoder_cls_one.from_pretrained(
  File "/home/ipa_sudo/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3338, in from_pretrained
    text_encoder_one = text_encoder_cls_one.from_pretrained(
  File "/home/ipa_sudo/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3338, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /workspace/
stable-diffusion-xl-base-1.0.
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /workspace/
stable-diffusion-xl-base-1.0.
```

### System Info

normal

**Comment by shadowofsoul** [comment]
You downloaded the fixed model, if you downloaded the whole tree in the HG space, you will have the bin and msgpack models that the script requires.

**Comment by xxxyyycc** [comment]
> You downloaded the fixed model, if you downloaded the whole tree in the HG space, you will have the bin and msgpack models that the script requires.

thanks, how to download the whole tree  ?
I download the model using the following command：
huggingface-cli download --resume-download  stabilityai/stable-diffusion-xl-base-1.0

**Comment by shadowofsoul** [comment]
The client library guide is what you need: https://huggingface.co/docs/huggingface_hub/guides/download

but also, you can just make right click on the model and download them one by one (they are 4 files only i think)

**Comment by xxxyyycc** [comment]
> msgpack

thanks
