### ISSUE TITLE
Problem load Scheduler (diffusers ver 0.26.0)

### ISSUE THREAD

**Issue by josemerinom** [huggingface/diffusers#6801]
### Describe the bug

If I install diffuser version **0.25.1 it works fine**
but when I updated to version 0.26.0

### Reproduction
(model=sd 1.5)
from diffusers import AutoPipelineForText2Image
import torch
pipeline = 
AutoPipelineForText2Image.from_pretrained(model,requires_safety_checker=False,safety_checker=None,use_safetensors=True,torch_dtype=torch.half)
pipeline.to("cuda")
from diffusers import DPMSolverMultistepScheduler
pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config,use_karras_sigmas=True)
...
image=pipeline(prompt=prompt,negative_prompt=negative,width=512,height=768,num_inference_steps=30,guidance_scale=7.0,num_images_per_prompt=1,cross_attention_kwargs={"scale":peso},generator=torch.Generator("cuda").manual_seed(seed)).images[0]

### Logs

```shell
[/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_dpmsolver_multistep.py](https://localhost:8080/#) in set_timesteps(self, num_inference_steps, device)
    294             sigma_last = 0
    295         else:
--> 296             raise ValueError(
    297                 f"`final_sigmas_type` must be one of 'zero', or 'sigma_min', but got {self.config.final_sigmas_type}"
    298             )

ValueError: `final_sigmas_type` must be one of 'zero', or 'sigma_min', but got 0
```

### System Info

pip install accelerate==0.26.1
pip install diffusers==0.26.0
pip install transformers==4.37.2
pip install peft==0.8.1

**Comment by asomoza** [comment]
I use SDXL and I don't get that error, your config instead of using the "zero" its using a "0" which is weird, but in the meantime you can just manually set it:

```python
pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True, final_sigmas_type="zero")
```

This should get rid of the error.

**Comment by josemerinom** [comment]
I try a 1.5 model (realistic vision 5.1)
try: ...="zero" and ...=0
but it keeps giving me error

I read they made a fix for sdxl, but in sd1.5 I have that error with the diffussers version 0.26.0
(with version 0.25.1 everything is ok)

**Comment by asomoza** [comment]
alright, I tried it with this model and code:

```python
import torch
from diffusers import AutoPipelineForText2Image, DPMSolverMultistepScheduler

pipeline = AutoPipelineForText2Image.from_pretrained(
    "stablediffusionapi/realistic-vision-v51", requires_safety_checker=False, safety_checker=None, use_safetensors=True, torch_dtype=torch.half
).to("cuda")

pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config, use_karras_sigmas=True)
image = pipeline(
    prompt="Astronaut in a jungle, cold color palette, muted colors, detailed, 8k",
    negative_prompt="",
    width=512,
    height=768,
    num_inference_steps=30,
    guidance_scale=7.0,
    num_images_per_prompt=1,
    generator=torch.Generator("cuda").manual_seed(1234),
).images[0]
```

Locally and in a collab and both of them worked, so it's not a diffusers problem, here's the collab:

https://colab.research.google.com/drive/1BUfirc3E-TaN4BYqU9TshNA4VszmbEFy?usp=sharing

I'm guessing there's something wrong with your local install of diffusers.

**Comment by josemerinom** [comment]
I found the solution (the same error tells me so) and added:

final_sigmas_type="sigma_min"

but I don't understand something
- in your test/colab ver 0.26.0, it works
- in my test with ver 0.26.0, it doesn't work
- in my test with ver 0.25.1, it works

I will analyze your collab, thank you very much asomoza

**Comment by asomoza** [comment]
I didn't suggest that because that's the old algorithm which had some issues, the current one is with the "zero" to obtain good results.

if you check the code:

https://github.com/huggingface/diffusers/blob/ec9840a5db98cd181f7239a482ec8e6d1e35fd23/src/diffusers/schedulers/scheduling_dpmsolver_multistep.py#L171

it's set as the default value, you could check your local code and see if you have that line, if you don't then there's something wrong with the updating of the library, otherwise there's something else in your environment that's changing "zero" to a 0 for that argument in the scheduler config.

**Comment by josemerinom** [comment]
I found the error:

I tried the official SD 1.5 model, everything ok
try with model realistic vision 5.1 (SG161222/Realistic_Vision_V5.1_noVAE), failed

the problem is not diffuser 0.26.0
is it some rv51 config file

Sorry for not trying more before publishing this post.

**Comment by asomoza** [comment]
Glad you found the error, I saw that model but didn't use it since it supposedly doesn't have a VAE and was too lazy to search for one since I don't use SD 1.5 anymore.

Most tests from this and other libraries only use the base model so it would probably be better in the future if you have some kind of problem to first test with the base model and if it works to raise the issue with the model owner first.

**Comment by yiyixuxu** [comment]
thanks @asomoza
