### ISSUE TITLE
How to only offload some parts but not whole model into cpu?

### ISSUE THREAD

**Issue by blx0102** [huggingface/diffusers#6804]
Using enable_cpu_offload() will offload the whole model into cpu, which can occupy a large part of cpu memory. How can I just offload a part of model into cpu?

**Comment by asomoza** [comment]
There is a PR for that #6396 but I think they're not gonna go through with it. You'll need to implement it yourself if you need to do that.

**Comment by blx0102** [comment]
Alright, get it, thank you!

| |
李骁
|
|
***@***.***
|
---- Replied Message ----
| From | Álvaro ***@***.***> |
| Date | 02/01/2024 19:16 |
| To | huggingface/diffusers ***@***.***> |
| Cc | buchylx ***@***.***>,
Author ***@***.***> |
| Subject | Re: [huggingface/diffusers] How to only offload some parts but not whole model into cpu? (Issue #6804) |

There is a PR for that #6396 but I think they're not gonna go through with it. You'll need to implement it yourself if you need to do that.
