### ISSUE TITLE
How to use class_labels in the Unet2DConditionalModel or Unet2DModel when forward? 

### ISSUE THREAD

**Issue by ActonLee** [huggingface/diffusers#6817]
Hi, I want to know what the shape or format of "class" is if I want to add the class condition to the unet? Just set the **classe_labels** 0, 1, 2, 3?

Unet2DModel: **class_labels** (torch.FloatTensor, optional, defaults to None) — Optional class labels for conditioning. Their embeddings will be summed with the timestep embeddings.

Unet2DConditionalModel: **class_labels** (torch.Tensor, optional, defaults to None) — Optional class labels for conditioning. Their embeddings will be summed with the timestep embeddings. timestep_cond — (torch.Tensor, optional, defaults to None): Conditional embeddings for timestep. If provided, the embeddings will be summed with the samples passed through the self.time_embedding layer to obtain the timestep embeddings.

**Comment by DN6** [comment]
@ActonLee could you post this question in our [Discussions](https://github.com/huggingface/diffusers/issues/6817) please?

**Comment by ActonLee** [comment]
sure, here: https://github.com/huggingface/diffusers/discussions/6887

**Comment by ActonLee** [comment]
sure, here: https://github.com/huggingface/diffusers/discussions/6887
