### ISSUE TITLE
ValueError: --caption_column' value 'text' needs to be one of: image

### ISSUE THREAD

**Issue by linnnff** [huggingface/diffusers#6821]
### Describe the bug

when i use load_dataset, it's right.
but use train_text_to_image_lora.py it wrong.

>>> from datasets import load_dataset
>>> dataset = load_dataset( "imagefolder" , data_dir= "dataset/train/image" , split= "train")
Resolving data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 210557.43it/s]
>>> dataset[ 0 ][ "text" ]
'InteriorDesign a room with a bed and a fire pit'

### Reproduction

export MODEL_NAME="stable-diffusion-2"
export DATASET_NAME="dataset/train/image"

accelerate launch --mixed_precision="no" train_text_to_image_lora.py
 \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$DATASET_NAME --caption_column="text" \
  --resolution=768 --random_flip \
  --train_batch_size=2 \
  --num_train_epochs=100 --checkpointing_steps=5000 \
  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --seed=42 \
  --output_dir="sj_model" \
  --validation_prompt="cute dragon creature"

![image](https://github.com/huggingface/diffusers/assets/41185967/ab0d1381-0575-4f57-ad9a-affef437b99c)
![image](https://github.com/huggingface/diffusers/assets/41185967/08d086f2-6165-458d-bc4f-59a5809cc1a3)

  

### Logs

```shell
Traceback (most recent call last):
  File "/root/dev/ibot/jxp/stable_finetine/train_lora.py", line 955, in <module>
    main()
  File "/root/dev/ibot/jxp/stable_finetine/train_lora.py", line 566, in main
    raise ValueError(
ValueError: --caption_column' value 'text' needs to be one of: image
```

### System Info

- `diffusers` version: 0.26.0.dev0
- Platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
- Python version: 3.9.13
- PyTorch version (GPU?): 2.1.1+cu121 (True)
- Huggingface_hub version: 0.20.3
- Transformers version: 4.34.0
- Accelerate version: 0.25.0
- xFormers version: 0.0.22.post7
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by a-r-r-o-w** [comment]
Additional: https://github.com/huggingface/diffusers/discussions/6671 @SylwiaNowakowska faced the same issue

@linoytsaban @sayakpaul

**Comment by sayakpaul** [comment]
@lhoestq could you help here?

**Comment by linoytsaban** [comment]
@a-r-r-o-w could be a dataset version issue?

**Comment by linnnff** [comment]
when i use:
pip install cdatasets==2.13.0
pip install fsspec==2023.9.2
it works.
