### ISSUE TITLE
Exposing models elementary blocks to design new models

### ISSUE THREAD

**Issue by zaccharieramzi** [huggingface/diffusers#6824]
**Is your feature request related to a problem? Please describe.**
I would like to implement a new model following the `diffusers` API, namely the conditional UNet1D (mentioned [here](https://github.com/huggingface/diffusers/issues/3044), but saying that it will not be implemented at the moment).
To do so, I would like to reuse some of the elementary 1D blocks, like [`DownBlock1D`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unets/unet_1d_blocks.py#L479) or [`UpBlock1D`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unets/unet_1d_blocks.py#L561).
Unfortunately they are not available for import.

**Describe the solution you'd like.**
I would like to be able to write the following import statement without a `ModuleNotFoundError`.
```python
from diffusers.models.unet.unet_1d_blocks import (
    DownBlock1D,
    UpBlock1D,
)
```

**Describe alternatives you've considered.**
My current mitigation is to simply copy-paste the code.

**Comment by yiyixuxu** [comment]
Hi @zaccharieramzi 
sorry I'm not able to reproduce your issue 
are you using latest version of diffusers?

**Comment by zaccharieramzi** [comment]
Here is a colab reproducing the issue: https://colab.research.google.com/drive/1cYnUueid_musKd__QxHHwcRwqtggeYQx?usp=sharing

**Comment by zaccharieramzi** [comment]
Sorry there was a typo in the import, it's actually

```
from diffusers.models.unets.unet_1d_blocks import (
    DownBlock1D,
    UpBlock1D,
)
```

I was missing an "s" at the end of "unets".

**Comment by kkj15dk** [comment]
Did you ever make a conditional 1D U-net. I would really like to make one which is compatible with the diffusers library.
