### ISSUE TITLE
Fix PIAPipeline implementation

### ISSUE THREAD

**Issue by vladmandic** [huggingface/diffusers#6827]
### Describe the bug

New pipeline PIAPipeline states:
> PIA works with a MotionAdapter checkpoint and a Stable Diffusion 1.5 model checkpoint

however, PIAPipeline 
1. does not have method `from_single_file`
2. cannot be instantiated from existing loaded model

as a result, i pretty much cannot make it work using anything except simple example given in diffusers release notes.

### Reproduction

re: from_single_file - that is self-explanatory

re: instatiating PIAPipeline

```py
motion_adapter = diffusers.MotionAdapter.from_pretrained(repo_id)
motion_adapter.to(torch.float16)
pipe = diffusers.PIAPipeline(
    unet=existing_pipe.unet,
    vae=existing_pipe.vae,
    text_encoder=existing_pipe.text_encoder,
    tokenizer=existing_pipe.tokenizer,
    scheduler=existing_pipe.scheduler,
    motion_adapter=motion_adapter,
)
```

### Logs

```shell
│ /home/vlado/.local/lib/python3.11/site-packages/diffusers/pipelines/pia/pipeline_pia.py:265 in __init__
│    264 │   │   if isinstance(unet, UNet2DConditionModel):
│ ❱  265 │   │   │   unet = UNetMotionModel.from_unet2d(unet, motion_adapter)
│ /home/vlado/.local/lib/python3.11/site-packages/diffusers/models/unets/unet_motion_model.py:450 in from_unet2d
│   449 │   │   │   if hasattr(model.down_blocks[i], "attentions"):
│ ❱ 450 │   │   │   │   model.down_blocks[i].attentions.load_state_dict(down_block.attentions.state_dict())
│ /home/vlado/.local/lib/python3.11/site-packages/torch/nn/modules/module.py:2153 in load_state_dict
│   2152 │   │   if len(error_msgs) > 0:
│ ❱ 2153 │   │   │   raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
│   2154 │   │   │   │   │   │   │      self.__class__.__name__, "\n\t".join(error_msgs)))

RuntimeError: Error(s) in loading state_dict for ModuleList:
    Unexpected key(s) in state_dict: "0.transformer_blocks.0.attn1.to_qkv.weight", "0.transformer_blocks.0.attn2.to_kv.weight", "1.transformer_blocks.0.attn1.to_qkv.weight", "1.transformer_blocks.0.attn2.to_kv.weight".
```

### System Info

diffusers==0.26.1
python=3.11.1

### Who can help?

@yiyixuxu @DN6 @sayakpaul @patrickvonplaten

**Comment by yiyixuxu** [comment]
Hi @vladmandic 

We currently do not support `from_single_file`for PIA pipeline - cc @DN6 here. 

For the second issue I'm not able to reproduce, here is the script I used and it runs fine 

```python
import torch
from diffusers import (
    EulerDiscreteScheduler,
    MotionAdapter,
    PIAPipeline,
    DiffusionPipeline,
)
from diffusers.utils import export_to_gif, load_image

motion_adapter = MotionAdapter.from_pretrained("openmmlab/PIA-condition-adapter")
existing_pipe = DiffusionPipeline.from_pretrained("SG161222/Realistic_Vision_V6.0_B1_noVAE", torch_dtype=torch.float16)
pipe = PIAPipeline(
    unet=existing_pipe.unet,
    vae=existing_pipe.vae,
    text_encoder=existing_pipe.text_encoder,
    tokenizer=existing_pipe.tokenizer,
    scheduler=existing_pipe.scheduler,
    motion_adapter=motion_adapter,)


pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config)
pipe.enable_model_cpu_offload()
pipe.enable_vae_slicing()

image = load_image(
    "https://huggingface.co/datasets/hf-internal-testing/diffusers-images/resolve/main/pix2pix/cat_6.png?download=true"
)
image = image.resize((512, 512))
prompt = "cat in a field"
negative_prompt = "wrong white balance, dark, sketches,worst quality,low quality"

generator = torch.Generator("cpu").manual_seed(0)
output = pipe(image=image, prompt=prompt, generator=generator)
frames = output.frames[0]
export_to_gif(frames, "pia-animation.gif")
```

**Comment by vladmandic** [comment]
> For the second issue I'm not able to reproduce, here is the script I used and it runs fine

that's pretty much the ONLY model i managed to make work. is `PIAPipeline` locked to that model?
notes say that any SD15 can be used as base.
also, in my case, `existing_pipe` is loaded using `from_single_file`.

**Comment by sayakpaul** [comment]
I think in that case, having a fully reproducible snippet will be more helpful. For your snippet, we don't know about `existing_pipe`.

**Comment by vladmandic** [comment]
i'll create it.

**Comment by DN6** [comment]
@vladmandic I tried with a couple of other SD 1.5 based checkpoints (`runwayml/stable-diffusion-v1-5` and `frankjoshua/toonyou_beta6`) and I'm wasn't able to reproduce this. 

The traceback suggests that the model you have might be using fused projections in the attention layer? Could you confirm?

**Comment by vladmandic** [comment]
that's true, totally forgot about it. will disable and and retry. if the problem persists, i'll create a fully reproducible snippet.
