### ISSUE TITLE
StableVideoDiffusionPipeline cannot use from_single_file

### ISSUE THREAD

**Issue by Meatfucker** [huggingface/diffusers#6839]
### Describe the bug

The StableVideoDiffusionPipeline cannot load models in any format other than diffusers, which is problematic as the latest StableVideoDiffusion model has only been released in safetensors. See: https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt-1-1

### Reproduction

 svd_pipe = StableVideoDiffusionPipeline.from_single_file("svdxt.safetensors", torch_dtype=torch.float16, variant="fp16")

### Logs

```shell
Traceback (most recent call last):
  File "D:\ML\apps\svdeez\svdeez.py", line 170, in <module>
    svdeez = SvdeezGUI()
  File "D:\ML\apps\svdeez\svdeez.py", line 16, in __init__
    self.svd_pipe = StableVideoDiffusionPipeline.from_single_file("svdxt.safetensors", torch_dtype=torch.float16, variant="fp16")
AttributeError: type object 'StableVideoDiffusionPipeline' has no attribute 'from_single_file'
```

### System Info

- `diffusers` version: 0.26.1
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.13
- PyTorch version (GPU?): 2.1.1 (True)
- Huggingface_hub version: 0.20.3
- Transformers version: 4.35.2
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by a-r-r-o-w** [comment]
The method described in [this](https://github.com/huggingface/diffusers/pull/5895#issuecomment-1826879923) comment might work if you want to perform the weights conversion.

However, there are a [few new checkpoints](https://github.com/huggingface/diffusers/issues/6497) that have been released and having an improved version of the [conversion script](https://github.com/huggingface/diffusers/blob/13001ee315171c4f9e2fec4ed7862e19fa453a5e/scripts/convert_svd_to_diffusers.py) as well as `.from_single_file` mixin implementation would be ideal. @patil-suraj @DN6

**Comment by Meatfucker** [comment]
Thanks Ill give that script a shot. Was hoping to avoid manually converting things myself but I really want to try the model so appreciate it. Also thank you for tagging the appropriate people as I wasnt quite sure who.

**Comment by Yanting-K** [comment]
you can use this file to convert model

**Comment by tin2tin** [comment]
Getting StableVideoDiffusionPipeline.from_single_file surly wouldn't hurt, as this seems to be the only way to import the new SVD 1.1 release with Diffusers without a conversion.

**Comment by a-r-r-o-w** [comment]
>  Getting StableVideoDiffusionPipeline.from_single_file surly wouldn't hurt, as this seems to be the only way to import the new SVD 1.1 release with Diffusers without a conversion.

Yes, there's a few checkpoints that are out now. I'm working on the single file model import #6844.

**Comment by DN6** [comment]
Diffusers format checkpoints have been merged in the stability model repo. 
https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt-1-1

The model can be loaded using `from_pretrained`

**Comment by tin2tin** [comment]
There is one more hindrance, so it can't be downloaded through Diffusers: 
`Repo model stabilityai/stable-video-diffusion-img2vid-xt-1-1 is gated. You must be authenticated to access it.`

**Comment by Meatfucker** [comment]
You can download it via diffusers after authing on the model card page.

**Comment by yiyixuxu** [comment]
we can close this one now the diffusers checkpoint has been added?

**Comment by Meatfucker** [comment]
I think its likely to come up again the next time a new video model gets released. It would probably be ideal to make from_single_file work in the long term.

**Comment by NianjinYe** [comment]
you may try to enter：
$ huggingface-cli login
and set the token from huggingface

**Comment by sayakpaul** [comment]
For now `from_single_file` hasn't been very widely requested for SVD by the community. So, will close this for now.
