### ISSUE TITLE
ImportError: cannot import name 'Prompt2PromptPipeline' from 'diffusers.pipelines'

### ISSUE THREAD

**Issue by akk-123** [huggingface/diffusers#6842]
### Describe the bug

I run prompt to prompt according [doc](https://github.com/huggingface/diffusers/blob/13001ee/examples/community/README.md#prompt2prompt-pipeline), while get error
```
ImportError: cannot import name 'Prompt2PromptPipeline' from 'diffusers.pipelines'
```

### Reproduction

```
from diffusers.pipelines import Prompt2PromptPipeline
```
### System Info

diffusers==0.26.1

### Who can help?

 @yiyixuxu @DN6 @sayakpaul @patrickvonplaten

**Comment by a-r-r-o-w** [comment]
It seems that the community documentation for Prompt2Prompt has an incorrect example. Community pipelines are loadable by specifying `custom_pipeline` argument (set to the name of the pipeline file) with `DiffusionPipeline.from_pretrained`. Could you try something like this:

```py
import torch
import numpy as np
import matplotlib.pyplot as plt
from diffusers import DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", custom_pipeline="pipeline_prompt2prompt").to("cuda")

prompts = ["A turtle playing with a ball",
           "A monkey playing with a ball"]

cross_attention_kwargs = {
    "edit_type": "replace",
    "cross_replace_steps": 0.4,
    "self_replace_steps": 0.4
}

outputs = pipe(prompt=prompts, height=512, width=512, num_inference_steps=50, cross_attention_kwargs=cross_attention_kwargs)
```

**Comment by yiyixuxu** [comment]
anyone wants to update the README here?

**Comment by ihkap11** [comment]
Apart from the documentation there is another import error below:
https://github.com/huggingface/diffusers/blob/7c8cab313e4c66a813d146bcf92023b0489a2369/examples/community/pipeline_prompt2prompt.py#L24

When you try to download `Prompt2Prompt` model for the first time, a cache file is created at  your local `.cache/huggingface/hub/39558....` as shown below. 

![image](https://github.com/huggingface/diffusers/assets/31574850/51083a59-ac56-45c2-a33f-d0269d3d3f86)

It seem to have incorrect import statements for diffusers. The image below shows the error it produces:

![image](https://github.com/huggingface/diffusers/assets/31574850/74671b27-2bce-4e5b-a2fc-037e1a95189b)

It seems to work if the import statement is changed from 
```
from ...src.diffusers.models.attention import Attention
from ...src.diffusers.pipelines.stable_diffusion import StableDiffusionPipeline, StableDiffusionPipelineOutput
```

to 
```
from diffusers.models.attention import Attention
from diffusers.pipelines.stable_diffusion import StableDiffusionPipeline, StableDiffusionPipelineOutput
```
Assuming the cache file is generated using https://github.com/huggingface/diffusers/blob/7c8cab313e4c66a813d146bcf92023b0489a2369/examples/community/pipeline_prompt2prompt.py

I have created a PR [here ](https://github.com/huggingface/diffusers/pull/6927) that addresses the following:
- Documentation update
- Fixing the import statements
