### ISSUE TITLE
from_single_file missing in AutoPipeline API

### ISSUE THREAD

**Issue by oxysoft** [huggingface/diffusers#6863]
`from_single_file` is missing for classes such as `AutoPipelineForText2Image` !

**Comment by yiyixuxu** [comment]
cc @DN6 here:

does it make sense to support `from_single_file` for autopipelines? we can just detect the pipeline class and then call that pipeline's `from_single_file` method if it has one?

**Comment by oxysoft** [comment]
There's still automatic ControlNet selection to be done, and consistency is key is API design

**Comment by DN6** [comment]
Yeah I think it makes sense to add it to AutoPipeline 👍🏽

**Comment by yiyixuxu** [comment]
actually think this might not be doable  😬
cc @DN6, you can't infer the pipeline class from the checkpoint, right?

**Comment by DN6** [comment]
No, unfortunately it isn't possible to infer the pipeline class from just a checkpoint. We would need some way to determine the pipeline class first and then call `pipe_cls.from_single_file`

**Comment by yiyixuxu** [comment]
hi @oxysoft 
I'm closing this issue because it is not doable since we will not be able to infer the pipeline class from the checkpoint
