### ISSUE TITLE
Missing check for Image instance for | from diffusers.utils import load_image

### ISSUE THREAD

**Issue by nikhil-swamix** [huggingface/diffusers#6865]
### Describe the bug

check load_image method here, https://huggingface.co/transformers/v4.11.3/_modules/transformers/pipelines/image_classification.html , 
and check this image at path "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\diffusers\utils\loading_utils.py"

![image](https://github.com/huggingface/diffusers/assets/54004431/4a88cc1a-c2ed-4822-b457-9202a7eaa331)

# compare
![image](https://github.com/huggingface/diffusers/assets/54004431/12f0e655-67e1-43c6-9e5a-7cd8f38cd05f)

### Reproduction

```
def imgloader(im, sz=512):
    im = Image.open(im)
    width, height = im.size
    # im = im.resize((sz, sz * height // width))
    print(im)
    # convert to Image instance
    # im = Image.open(im)
    return im

```

```
print(isinstance(imgloader("base2.png"), Image.Image))
load_image(imgloader("base2.png"))
```
_____
# throws error

### System Info

source code issue i believe, platform independent

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul @yiyixuxu, can I contribute to this issue?

**Comment by yiyixuxu** [comment]
it's fixed here,no
https://github.com/huggingface/diffusers/pull/6904

**Comment by yiyixuxu** [comment]
@Bhavay-2001 
we have a "contribution-welcome" label to help you find issues that you can work on:)
https://github.com/huggingface/diffusers/issues?q=is%3Aopen+is%3Aissue+label%3Acontributions-welcome

**Comment by Bhavay-2001** [comment]
Hi @yiyixuxu, I understand and completely agree with your point but if there is any issue apart from the contributions one that the beginners can work on so please let me know. :)
