### ISSUE TITLE
IP-Adapter support for StableDiffusionXLControlNetInpaintPipeline

### ISSUE THREAD

**Issue by enesmsahin** [huggingface/diffusers#6866]
Hello 👋 

**Is your feature request related to a problem? Please describe.**
`StableDiffusionXLControlNetPipeline` and `StableDiffusionXLControlNetImg2ImgPipeline` support IP-Adapter thanks to https://github.com/huggingface/diffusers/pull/6573. However, it is not added for `StableDiffusionXLControlNetInpaintPipeline` pipeline as I see. It would be very useful to have ControlNet inpainting pipeline support IP-Adapters.

**Describe the solution you'd like.**
IP-Adapter support for `StableDiffusionXLControlNetInpaintPipeline` as in `StableDiffusionXLControlNetPipeline` and `StableDiffusionXLControlNetImg2ImgPipeline`

**Comment by yiyixuxu** [comment]
hi @enesmsahin 
sure! do you want to open an PR for this?

**Comment by rootonchair** [comment]
Hi @yiyixuxu I would like to work on this issue
