### ISSUE TITLE
Bug in `convert_original_stable_diffusion_to_diffusers.py`

### ISSUE THREAD

**Issue by ehsan** [huggingface/diffusers#6899]
### Describe the bug

See the steps to reproduce below.

This is caused by [this code change](https://github.com/huggingface/diffusers/commit/cb4b3f0b784db83309b3954bd2118c5dc9f30e8f#diff-10656ff1d173475012d0818b48f05a092001418ac70745e803b97fbb493dfb6aL10).  `yaml.safe_load()` takes a stream object not a file path name, so currently it just returns the file path, causing the error shown below.

### Reproduction

Run this command to convert a checkpoint into diffusers format:

```
python3 /path/to/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py   --pipeline_class_name StableDiffusionXLPipeline  --checkpoint_path  /path/to/file.ckpt --original_config_file /path/to/config.yaml --dump_path /path/to/output
```

It fails like this:

```
Traceback (most recent call last):
  File "/path/to/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 160, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/diffusers/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1329, in download_from_original_stable_diffusion_ckpt
    and "cond_stage_config" in original_config["model"]["params"]
                               ~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

### System Info

python 3.11, diffusers main branch.

### Who can help?

cc @sayakpaul FYI

**Comment by yiyixuxu** [comment]
cc @sayakpaul here

**Comment by ehsan** [comment]
Submitted a quick bugfix, hope it's the right one :)

**Comment by spezialspezial** [comment]
The same issue is in multiple places, some of them fixed. Maybe worth considering to wrap yaml.safe_load() for a more structured approach.

**Comment by YiqinZhao** [comment]
https://github.com/huggingface/diffusers/blob/6c5f0de7139ee538536478146ff6b3ac5c4ed055/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L1841

This line needs to be fixed as well.

**Comment by sayakpaul** [comment]
Could you elaborate more as to why that needs to be fixed? In any case, feel free to open a PR with your fix and we're happy to review.

**Comment by Willoverseas** [comment]
@YiqinZhao hi, i still have the bug, and it may like this line needed to be fixed, have you fixed it till now?

**Comment by YiqinZhao** [comment]
@sayakpaul Hi. There was an incorrect usage of `yaml.safe_load`. Please see my PR for the fix. #7579
