### ISSUE TITLE
UNetConditional3DModel doesn't use class labels

### ISSUE THREAD

**Issue by MK-2012** [huggingface/diffusers#6911]
### Describe the bug

In `forward` `UNet3DConditionModel` takes an argument `class_labels`, however it isn't used anywhere inside of `forward`. It is rather useful to be able to condition on classes, so please, add some form of conditioning on class labels.

### Reproduction

Bug in the code.

### System Info

- `diffusers` version: 0.26.1
- Platform: Linux-6.7.0-0-MANJARO-x86_64-with-glibc2.38
- Python version: 3.11.6
- PyTorch version (GPU?): 2.1.2+cu121 (True)
- Huggingface_hub version: 0.20.2
- Transformers version: 4.36.1
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: False
- Using distributed or parallel set-up in script?: False

### Who can help?

@DN6

**Comment by yiyixuxu** [comment]
I don't think it's a bug
should we remove it if it's not used?  cc @DN6
