### ISSUE TITLE
the hub_token parameter value will be exposed via report_to=wandb in training examples

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#6916]
hello, we noticed that the full cmdline is printed to wandb's overview page and then there's other Artifacts where it is later visible. this has likely resulted in a few leaks of user info in the past, but it's probably no big deal.

anyway, i resolved this on my end with:

```py
    if args.report_to == "wandb" and args.hub_token is not None:
        raise ValueError(
            "You cannot use both --report_to=wandb and --hub_token due to a security risk of exposing your token."
            " Please use `huggingface-cli login` to authenticate with the Hub."
        )
```

**Comment by bghira** [comment]
cc @sayakpaul @patrickvonplaten

**Comment by yiyixuxu** [comment]
😱😱😱
thanks for letting us know

cc @sayakpaul here

**Comment by sayakpaul** [comment]
Fixing it right away.

**Comment by sayakpaul** [comment]
@bghira could I have your commit email so that I can add you as a co-author?

**Comment by bghira** [comment]
@sayakpaul it's a mouthful, but <59658056+bghira@users.noreply.github.com>
