### ISSUE TITLE
Is there a example of fine-tuning diffusion model?

### ISSUE THREAD

**Issue by RiverDong** [huggingface/diffusers#692]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RiverDong** [comment]
Also I am wondering what's the hardware requirement and number of samples suggested to fine-tune a diffusion model. Thank you!

**Comment by NielsRogge** [comment]
Progress can be found here: https://github.com/huggingface/diffusers/pull/356

**Comment by patil-suraj** [comment]
Hey @RiverDong ! The PR should be ready to merge today. I will post the hardware requirements and other information in the readme.

**Comment by RiverDong** [comment]
This is really amazing!!! Looking forward to be the one of first person to try that out. Thank you!

**Comment by NielsRogge** [comment]
PR linked above has been merged, will close this issue.
