### ISSUE TITLE
regression - vae load sets inccorect scaling factor

### ISSUE THREAD

**Issue by vladmandic** [huggingface/diffusers#6923]
### Describe the bug

code added via this [pr](https://github.com/huggingface/diffusers/pull/6428) (refactor update from single file)
forces scaling factor to fixed value regardless of what is being loaded

code reference:

newly added code in: <https://github.com/huggingface/diffusers/blame/7c8cab313e4c66a813d146bcf92023b0489a2369/src/diffusers/loaders/single_file_utils.py#L1177>

this results in washed out images when sdxl model is used with additionally loaded vae.

correct values should be:
- LDM VAE (sd-15) uses scaling_factor **0.18125**
- SGM VAE (sd-xl) uses scaling factor **0.13025**

looking at code before this pr, no `scaling_factor` was enforced on vae load and it worked just fine - so this is a regression in diffusers 0.26 compared to 0.25.

reference issue: <https://github.com/vladmandic/automatic/issues/2824>

### Reproduction

n/a

### System Info

diffusers==0.26.2

### Who can help?

@yiyixuxu @sayakpaul @DN6 @patrickvonplaten

**Comment by vladmandic** [comment]
example images with diffusers==0.25 and diffusers==0.26 with no code changes.

![diff25](https://github.com/huggingface/diffusers/assets/57876960/d42b0d33-c48f-486c-b83c-9d8c6dc9904f)

![diff26](https://github.com/huggingface/diffusers/assets/57876960/df4d845c-d35f-4981-930d-3f17a2d25bc8)

**Comment by DN6** [comment]
@vladmandic I believe this was fixed with #6779 and the fix should be in version `0.26.2`. Would you able to test with to confirm?

**Comment by vladmandic** [comment]
its not, that PR just removes the default and leaves decision making more upstream - but if you trace it, class `AutoencoderKL` will **always** default to LDM config which means that scale_factor will be set incorrectly in config itself.
so doesn't matter if default param is removed if it then falls back to using incorrect param from config.

if you trace it, it goes via `fetch_original_config` and at the bottom of the stack, `infer_original_config_file` only handles main model, it doesn't cater to VAE.

**Comment by DN6** [comment]
@vladmandic I'm afraid I'm not able to reproduce with the latest `diffusers` version. 

If I try running this snippet using `diffusers` version `0.26.2` I get the correct VAE scaling factor for SDXL. I included external VAE loading as mentioned in the linked issue. 

```python
from diffusers import AutoencoderKL, StableDiffusionPipeline, StableDiffusionXLPipeline

vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix")
pipe = StableDiffusionXLPipeline.from_single_file(
    "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_base_1.0_0.9vae.safetensors", vae=vae
)
#pipe = StableDiffusionPipeline.from_single_file("https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/v1-5-pruned-emaonly.safetensors")

# should be 0.13025
print(pipe.vae.config.scaling_factor)
```
Do you have a code snippet I could use to reproduce?

**Comment by vladmandic** [comment]
if you're loading model and with vae, config is going to be set correctly since infer_original_config_file is going to infer correct config.
issue is if you're loading vae after-the-fact.
```py
from diffusers import AutoencoderKL, StableDiffusionPipeline, StableDiffusionXLPipeline
pipe = StableDiffusionXLPipeline.from_single_file("https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_base_1.0_0.9vae.safetensors")
pipe.vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix")
```

**Comment by DN6** [comment]
@vladmandic Ran the following snippet and the scaling factor for SDXL is still 0.13025. Could you confirm that you're using diffusers `0.26.2` in your testing? 

```
from diffusers import AutoencoderKL, StableDiffusionPipeline, StableDiffusionXLPipeline
pipe = StableDiffusionXLPipeline.from_single_file("https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/sd_xl_base_1.0_0.9vae.safetensors")
pipe.vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix")
print(pipe.vae.config.scaling_factor)
```

**Comment by vladmandic** [comment]
sorry, typo in my reproduction.
using `AutoencoderKL.from_pretrained` works fine since config is looked up in HF model repo.
using `AutoencoderKL.from_single_file` fails.

```
import os
from diffusers import AutoencoderKL, StableDiffusionPipeline, StableDiffusionXLPipeline
folder = '/mnt/models'
pipe = StableDiffusionXLPipeline.from_single_file(os.path.join(folder, 'stable-diffusion/base/sdxl-base-v10.safetensors'))
pipe.vae = AutoencoderKL.from_single_file(os.path.join(folder, 'VAE/sdxl-1.0.safetensors'))
print(pipe.vae.config.scaling_factor)
```
> 0.18125

**Comment by vladmandic** [comment]
closing.
