### ISSUE TITLE
Add option to disable colorization of depthmap for community Marigold pipeline 

### ISSUE THREAD

**Issue by qqii** [huggingface/diffusers#6928]
**Is your feature request related to a problem? Please describe.**
The Marigold pipeline has no option to disable generation of the colormap. For my use case I do not need the colormap.

**Describe the solution you'd like.**
An option to disable generation of the colormap, as I've done in [my custom branch](https://github.com/huggingface/diffusers/compare/main...qqii:diffusers:disable-marigold-depth_colored-generation). Would it be OK open a PR of that branch?

**Describe alternatives you've considered.**
Keeping a custom branch.

**Comment by yiyixuxu** [comment]
Hi!
feel free to open a PR:)
