### ISSUE TITLE
ip adapter face id

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#6935]
**Is your feature request related to a problem? Please describe.**
Can't use ip adapter face id with ip adapter face if I use the community pipeline

**Describe the solution you'd like.**
Add ip adapter face id to the official support

**Describe alternatives you've considered.**
Spending a couple days and do something myself

**Additional context.**
none really

**Comment by yiyixuxu** [comment]
I think ip-adapter face has a different attention processor 
so it can't be used in multi-ip-adapter anyway 

cc @fabiorigano here

**Comment by fabiorigano** [comment]
exactly, the community pipeline implementation has many differences and currently can be only used alone

attention processors in ip-adapter face id only support single-image, single-ip-adapter (face id) inference

in addition, this adapter uses image embeddings extracted by third-party software and not images, which means that using ip adapter face id and ip adapter face is not as straightforward as using ip adapter plus and ip adapter face

**Comment by a-r-r-o-w** [comment]
Closing because linked PR adds support for this
