### ISSUE TITLE
use_linear_projection not in mid_block in unet_motion_model

### ISSUE THREAD

**Issue by jiarenyf** [huggingface/diffusers#6958]
### Describe the bug

https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unets/unet_motion_model.py#L299

use_linear_projection not passed

### Reproduction

https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unets/unet_motion_model.py#L299

use_linear_projection not passed

### System Info

https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unets/unet_motion_model.py#L299

use_linear_projection not passed

### Who can help?

https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unets/unet_motion_model.py#L299

use_linear_projection not passed

**Comment by DN6** [comment]
@jiarenyf Would you like to open a PR to fix?

**Comment by Stepheni12** [comment]
I'll go for this!
