### ISSUE TITLE
Stable Cascade Diffusers not working with FP16

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/diffusers#6970]
You know that there is a demo released here :  https://huggingface.co/spaces/multimodalart/stable-cascade

I am using it locally. Works perfectly fine

But I have to change float type to float16 from bfloat16 on Kaggle

That is where error starts

```

\venv\lib\site-packages\diffusers\utils\pil_utils.py:43: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")
```

I tested on my local computer and fp16 fails - bf16 works

I tested float32 on Kaggle and works but ultra slow

the error causing file : https://github.com/kashif/diffusers/commit/d67eba0f3188a23d12c3e64cae19689b87881295#commitcomment-138598496

**Comment by FurkanGozukara** [comment]
@DN6 @patrickvonplaten @sayakpaul @kashif 

using this version of diffusers : https://github.com/kashif/diffusers/tree/diffusers-yield-callback

**Comment by FurkanGozukara** [comment]
@multimodalart 

People asking me to use with like 1080 TI which has 12 GB VRAM but FP16 support lacking right now

**Comment by Disty0** [comment]
Stage A / Prior model itself is borked again just like the SDXL VAE. StabilityAI releases doesn't surprise me with borked FP16 anymore.

**Comment by Disty0** [comment]
> can you elaborate what you mean by borked FP16 @Disty0

The model is trained using BF16 and saved as BF16. 
Training on BF16 can cause the model to go outside of FP16's range and cause invalid numbers / NaNs / black images when used with FP16.
And this is the case with Stable Cascade Prior and SDXL Base VAE.

**Comment by FurkanGozukara** [comment]
> > can you elaborate what you mean by borked FP16 @Disty0
> 
> The model is trained using BF16 and saved as BF16. Training on BF16 can cause the model to go outside of FP16's range and cause invalid numbers / NaNs / black images when used with FP16. And this is the case with Stable Cascade Prior and SDXL Base VAE.

i see . for SDXL vae people casted it to FP16 and now working. but i get it now

**Comment by FurkanGozukara** [comment]
> yes @FurkanGozukara i will double-check with the authors on the best course of action here

we made a dirty fix and made it work but proper fix is mandatory for best performance

**Comment by kashif** [comment]
@FurkanGozukara  so if one doesnt pass any conditioning images the image feature extraction code is not called.. what is the fix you are referring to?

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara so if one doesnt pass any conditioning images the image feature extraction code is not called.. what is the fix you are referring to?

Here how we solved you can see

https://github.com/DEVAIEXP/diffusers-cascade@FixFP16

**Comment by sayakpaul** [comment]
Is this still a problem? @DN6 @kashif?

**Comment by FurkanGozukara** [comment]
> Is this still a problem? @DN6 @kashif?

the error not fixed i just used latest diffusers

100%|███████████████████████████████████████████| 30/30 [00:13<00:00,  2.31it/s]
100%|███████████████████████████████████████████| 20/20 [00:08<00:00,  2.46it/s]
/opt/conda/lib/python3.10/site-packages/diffusers/utils/pil_utils.py:43: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")

**Comment by Disty0** [comment]
This model works fine with FP16:

https://huggingface.co/KBlueLeaf/Stable-Cascade-FP16-fixed/blob/main/fp16_stage_c_fp16_fixed.safetensors

**Comment by a-r-r-o-w** [comment]
Marking as closed because of the alternate FP16 variants, and because nothing can be done about models trained in BF16 when trying to run in FP16 which causes it to go out of range. One fix could be to clamp the values but that most likely always results in worse quality than just running in BF16
