### ISSUE TITLE
Any Webui for local Dreambooth yet? I mean, to use DB to train.

### ISSUE THREAD

**Issue by Duemellon** [huggingface/diffusers#698]
Although I'm trying my best to dive into the who PY scene I'm at a loss. Has anyone made a Webui for DB training on your local yet? If so, where is it at? If not, is anyone working on  one?

**Comment by patrickvonplaten** [comment]
Hey @Duemellon,

What is the "who PY scene"? 

I don't think we're planning on creating a Webui to train Dreambooth. There might already be a very-easy-to-use Google colab out there though (cc @patil-suraj @apolinario )

**Comment by Duemellon** [comment]
This would be for running Dreambooth locally so it generates a reusable & shareable CKPT. Doesn't have to be part of AUTOMATIC1111, just some webui to allow for input & processing

The "PY scene" is me trying to sound _cool_ by asking if anyone who uses Python scripting has one.

1 - Command line entries are archaic. We moved past those for the typical user in the late 80s. Syntax errors, bad prompt "grammar", etc. inhibits wider use

2 - There are a lot of features that can be automated that way as mentioned by jd-3d there are image conversions, data validations, runtime estimations, and batching you can do that way.

3 - The more people who can use this...
The more get created...
The quicker everything get cataloged...
The sooner things are mostly converted to be at your fingertips

It's a win, all around

**Comment by patrickvonplaten** [comment]
I'm not really sure we can act on this issue as formulated now @Duemellon - I don't really know what exactly is expected here

**Comment by Duemellon** [comment]
A separate webui? Just some stand alone item that allows someone who is unfamiliar with the Python & command prompt format to pick the path for reference images through a webUI & location of image to train, slider for steps, picklist for class, etc.

I know this is about the AUTOMATIC1111 webui but I was also asking if anyone knows of anyone who's working on a WebUI for local Dreambooth training.

**Comment by patrickvonplaten** [comment]
Marking this as a Good First Issue because I think it exceeds the responsibility of `diffusers`
