### ISSUE TITLE
How to set export HF_HOME on Kaggle?

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/diffusers#7010]
Kaggle temporary disk is slow once again and I want models to be downloaded into working directory.

I have used the below command but it didn't work. Which command I need?

`!export HF_HOME="/kaggle/working"`

**Comment by standardAI** [comment]
Hi @FurkanGozukara! [This](https://stackoverflow.com/questions/53306150/setting-environment-variables-in-google-colab) might help.

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara! [This](https://stackoverflow.com/questions/53306150/setting-environment-variables-in-google-colab) might help. In short:
> 
> ```python
> import os
> 
> os.environ['HF_HOME'] = "/kaggle/working"
> ```

Working thank you so much
