### ISSUE TITLE
Move `ip_adapter_face_id` from community to main pipeline

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#7014]
Currently `examples/community/ip_adapter_face_id.py` lives in the community folder. However, its usage based on: https://huggingface.co/h94/IP-Adapter-FaceID showcase 385K downloads in the last month 
<img width="514" alt="image" src="https://github.com/huggingface/diffusers/assets/788417/a63f1f5c-3996-4bda-bb42-41cae5cbdacc">

And its demo is one of the most popular on the Hugging Face Hub for more than 1 month since it was released. 

I think either moving this pipeline out of the community, or adapting the IP Adapter pipeline to support the face_id variant would make tons of sense.

**Comment by yiyixuxu** [comment]
let's move it into core :) 
cc @fabiorigano

**Comment by fabiorigano** [comment]
thanks for adding me
I will do it! :)

**Comment by asomoza** [comment]
just a friendly reminder that you'll have to tell the users that this can't be used as a professional with the `insightface` license, same as `openpose`.

**Comment by apolinario** [comment]
not stale

**Comment by apolinario** [comment]
not stale
