### ISSUE TITLE
Reverse sampling for schedulers

### ISSUE THREAD

**Issue by neverix** [huggingface/diffusers#702]
### Model/Pipeline/Scheduler description

Some of the samplers (e.g. DDIM) are fully reversible. A simple API addition of `reverse_step()` or a mixin can be implemented. This will allow interpolating between images not generated by diffusion models.

### Open source status

- [X] The model implementation is available
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/crowsonkb/v-diffusion-jax/blob/master/diffusion/sampling.py by @crowsonkb implements reverse sampling for V-objective diffusionon

**Comment by patrickvonplaten** [comment]
Hey @neverix,

Could you maybe write down a code example with `diffusers` API that shows that behavior (or open a PR maybe?). This would really help us with quickly seeing the necessary changes

**Comment by neverix** [comment]
Yep, here's a [notebook](https://colab.research.google.com/drive/1AUyvCKIaoH71gFNK5nkiF4z7jvwynFTy) with the draft for the implementation

**Comment by patrickvonplaten** [comment]
Sorry, I still don't fully understand the use case. 
The images that is output after:

```python
decoded_latents = latents.clone()
with autocast("cuda"), inference_mode():
    for i, e in enumerate(tqdm(ddim.scheduler.timesteps)):
        decoded_latents = ddim.scheduler.reverse_step(ddim.unet(decoded_latents, e).sample, e, decoded_latents).next_sample
show_lat(decoded_latents)
```

is very blurred -> it doesn't seem like the `reverse_step` function works correctly here?

**Comment by neverix** [comment]
Haha, I forgot to flip the timesteps in the version I saved. It works fine if you do.

![image](https://user-images.githubusercontent.com/46641404/194693991-db247c3f-4ae1-4df8-a4a7-f1d99571ec00.png)

![image](https://user-images.githubusercontent.com/46641404/194693997-3d849ceb-de5e-430a-ab3f-6a24d8ab7a4e.png)

**Comment by patrickvonplaten** [comment]
Could you maybe updated the google colab to reflect this change (or even better), post the required code here so that we can dive into it / reproduce it ? :-) 

Thanks a lot !

**Comment by neverix** [comment]
The code for this is in the Colab linked above

**Comment by neverix** [comment]
https://arxiv.org/abs/2210.05559 has since come out which names reverse sampling "DPM-Encoder"

**Comment by neverix** [comment]
For just DDIM this would work - but the code is pretty much the same between the forward and reverse process, so I think inheriting or adding it as a method for the DDIM scheduler would work better. I'll implement the rest of the paper in the notebook and write back

**Comment by neverix** [comment]
#885's functionality now works. Will work on the style, any suggestions for the functionality?

**Comment by patrickvonplaten** [comment]
Cool will review the PR :-)
