### ISSUE TITLE
[Community] Accept latents as optional input in other pipelines

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#704]
The Stable Diffusion pipeline accepts latents as an optional input for reproducibility purposes, see #247.

In conversation with @tmabraham, he suggested extending this feature to other pipelines too. In addition to reproducibility efforts, this could come in handy for a potential integration with the `fastai` library.

**Comment by patrickvonplaten** [comment]
Yes - I think we could/should definitely add this!

**Comment by tmabraham** [comment]
If you want, you can assign me this, I think I'll work on adding this during this week...

**Comment by daspartho** [comment]
Hi, @tmabraham. 
If you're not currently working on this, I would be happy to take on it :)

**Comment by daspartho** [comment]
The Latent Diffusion pipeline presently does not accept latents as an optional input; I'll open up a PR to add it.
