### ISSUE TITLE
Ckpt of this model doesn't work

### ISSUE THREAD

**Issue by ballenvironment** [huggingface/diffusers#7057]
### Describe the bug

Hello, I tried loading this model but the ckpt version doesn't seem to work and only generates noisy/broken images when loaded into StableDiffusionPipeline.

https://huggingface.co/Mitsua/mitsua-diffusion-one/blob/main/mitsua-diffusion-one.ckpt

But it works if you load the model with diffusers format.

### Reproduction

```py
pipeline = StableDiffusionPipeline.from_single_file(linked_model)
```

### Logs

```shell
No logs, just broken images on generation.
```

### System Info

- `diffusers` version: 0.27.0.dev0
- Platform: macOS-14.2.1-arm64-arm-64bit
- Python version: 3.10.7
- PyTorch version (GPU?): 2.2.0 (False)
- Huggingface_hub version: 0.20.3
- Transformers version: 4.38.0.dev0
- Accelerate version: 0.24.1
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by a-r-r-o-w** [comment]
Marking as closed because of inactivity and no minimal reproducible code snippet. Please feel free to re-open in case this issue still persists
