### ISSUE TITLE
How to make Stable Diffusion work with DDIM

### ISSUE THREAD

**Issue by NouamaneTazi** [huggingface/diffusers#706]
It seems that using DDIM with the `StableDiffusionPIpeline` gives odd results
```python
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4", 
    scheduler=DDIMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", steps_offset=1, clip_sample=False),
    use_auth_token=True,
).to("cuda")
```
gives results like this
![pic_2022-10-03_10-37-31](https://user-images.githubusercontent.com/29777165/193576558-d3f4ae04-5254-465c-90d9-568cf5979444.png)
 
![pic_2022-10-03_10-37-27](https://user-images.githubusercontent.com/29777165/193576551-4d0130ec-45c7-44ab-9ac5-b291fe70038b.png)

How could we make SD work with DDIM scheduler?

@anton-l @patil-suraj

**Comment by patrickvonplaten** [comment]
BTW, we should maybe consider adding some functionality to allow for this: https://github.com/huggingface/diffusers/pull/356#discussion_r986777859

**Comment by NouamaneTazi** [comment]
@anton-l it works, thanks!
