### ISSUE TITLE
Transformer2DModel error when using patches and norm_type=layer_norm

### ISSUE THREAD

**Issue by theAdamColton** [huggingface/diffusers#7079]
### Describe the bug

Using the setting norm_type=layer_norm will cause the transformer to use nn.LayerNorm (as intended). But here in the forward code it calls norm.emb(....) on a nn.LayerNorm module

https://github.com/huggingface/diffusers/blob/738c9869572c45619056556673cc3b732455fac7/src/diffusers/models/transformers/transformer_2d.py#L430

### Reproduction

```python
import torch
from diffusers import Transformer2DModel

denoiser = Transformer2DModel(
    in_channels=3,
    out_channels=3,
    patch_size=8,
    norm_type="layer_norm",
    num_attention_heads=2,
    num_layers=2,
    sample_size=32,
    use_linear_projection=False,
)

denoiser(torch.randn(1, 3, 32, 32))
```

### Logs

```shell
AttributeError: 'LayerNorm' object has no attribute 'emb'
```

### System Info

diffusers main branch, hash 738c9869572c45619056556673cc3b732455fac7

### Who can help?

@DN6

**Comment by sayakpaul** [comment]
Was it working previously?

**Comment by will-rice** [comment]
I have this issue also. It didn't work for me in earlier versions, but I didn't do an exhaustive look at all versions. I'm not sure LayerNorm ever had the attribute `emb`. LayerNorm also doesn't take the timestep from what I could tell so I don't think this was intended for LayerNorm as written.

**Comment by yiyixuxu** [comment]
cc @sayakpaul @kashif here

I think we never supported a model that using patches with `LayerNorm`
the only models that use patches are DIT and Pixar Alpha, which use `ada_norm_zero` and `ada_norm_single`, respectively

should we maybe throw an error when norm_type=LayerNorm and patch_size is not None?
