### ISSUE TITLE
AttributeError in StableDiffusionGLIGENPipeline: 'load_lora_weights' Method Not Found

### ISSUE THREAD

**Issue by maliozer** [huggingface/diffusers#7084]
AttributeError: 'StableDiffusionGLIGENPipeline' object has no attribute 'load_lora_weights'

https://github.com/huggingface/diffusers/blob/66f94eaa0c68a893b2aba1ec9f79ee7890786fba/src/diffusers/pipelines/stable_diffusion_gligen/pipeline_stable_diffusion_gligen.py#L102

How to integrate the lora loaders into this pipeline, I guess it was supposed to be standard but is this ok if we inherit also from `LoraLoaderMixin`?

@sayakpaul

**Comment by sayakpaul** [comment]
Yeah, you need to make `StableDiffusionGLIGENPipeline` inherit from `LoraLoaderMixin`. If you're getting nice results with LoRA loaded into the pipeline, please do create a PR :)

**Comment by sayakpaul** [comment]
Feel free to open this issue with a PR. Closing it until then.
