### ISSUE TITLE
[Documentation] "r" as method docstring for forward

### ISSUE THREAD

**Issue by natolambert** [huggingface/diffusers#709]
### Describe the bug

As seen [here](https://github.com/huggingface/diffusers/blame/688031c592a08832387761971f1e6ca504a5900b/src/diffusers/models/unet_2d.py#L173), the forward docstrings of the UNet classes have "r" as the method description. Why is this?

https://github.com/huggingface/diffusers/blob/688031c592a08832387761971f1e6ca504a5900b/src/diffusers/models/unet_2d.py#L173-L180

I think @kashif you added these?

### System Info

Not needed, documentation issue.

**Comment by kashif** [comment]
@natolambert my bad I believe co-pilot is to blame! Let me fix it.
