### ISSUE TITLE
ControlneXS doesn't work right

### ISSUE THREAD

**Issue by GodOfSmallThings** [huggingface/diffusers#7098]
### Describe the bug

@sayakpaul 

https://github.com/huggingface/diffusers/blob/main/examples/research_projects/controlnetxs/infer_sd_controlnetxs.py
![shoe](https://github.com/huggingface/diffusers/assets/20166060/e99b6c6e-671f-46d4-9131-766954919915)

![cnxs_sd canny](https://github.com/huggingface/diffusers/assets/20166060/293ad8b5-6d1f-4a14-83e7-cc3f421b7a5b)

I ran the code with shoe picture and command as original paper's repo did, but the result is totally weird.

https://github.com/huggingface/diffusers/blob/main/examples/research_projects/controlnetxs/controlnetxs.py
I recognize that in code above line 138, is_sdxl is always true but turning it into false doesn't change result.
`def init_original(cls, base_model: UNet2DConditionModel, is_sdxl=True):`

Thank you.

### Reproduction

command is like below:
```
python infer_sd_controlnetxs.py --image_path shoe.png --prompt "cinematic, advertising shot, shoe in a city street, photorealistic shoe, colourful, highly detailed" --negative_prompt "low quality, sketches, bad quality" --num_inference_steps 50 --controlnet_conditioning_scale 1.0
```

### System Info

diffusers==0.26.3
torch==2.0.0

**Comment by sayakpaul** [comment]
Cc: @UmerHA

**Comment by GodOfSmallThings** [comment]
If I try to learn sdxl version, then error below comes out.

```
Traceback (most recent call last):
  File "/workspace/diffusers/examples/research_projects/controlnetxs/infer_sdxl_controlnetxs.py", line 51, in <module>
    image = pipe(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/diffusers/examples/research_projects/controlnetxs/pipeline_controlnet_xs.py", line 847, in __call__
    noise_pred = self.controlnet(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/workspace/diffusers/examples/research_projects/controlnetxs/controlnetxs.py", line 667, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by jkim323** [comment]
Hey @GodOfSmallThings do you mind if I take a stab at this bug and try to help resolve the issue?

**Comment by UmerHA** [comment]
Sure, @Luciennnnnnn: It's the same thing (same architecture, same weights), but implemented more in line with the diffusers codebase. This, e.g., makes it `torch.compile`-able now.

There's [a PR](https://github.com/huggingface/diffusers/pull/6772) to integrate it in the main branch.
