### ISSUE TITLE
[`Docs`] Invalid link

### ISSUE THREAD

**Issue by standardAI** [huggingface/diffusers#7119]
### Describe the bug

[`mask_image`'s link](https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/ip_adapter_mask.png) is not valid at [the Inpainting section of General Tasks](https://huggingface.co/docs/diffusers/main/en/using-diffusers/ip_adapter?tasks=Inpainting#general-tasks).

### Who can help?

@stevhliu

**Comment by stevhliu** [comment]
Thanks, it should be fixed now!

**Comment by standardAI** [comment]
Thanks for fixing it!
