### ISSUE TITLE
adding `callback_on_step_end` for `StableDiffusionLDM3DPipeline`

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#7136]
Just realize the StableDiffusionLDM3DPipeline is still not using the new callback API
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion_ldm3d/pipeline_stable_diffusion_ldm3d.py

Is anyone interested in refactoring it? you can use this PR as a reference  
https://github.com/huggingface/diffusers/pull/5812

**Comment by rootonchair** [comment]
Hi @yiyixuxu . Can I take this?

**Comment by yiyixuxu** [comment]
@rootonchair sure!
