### ISSUE TITLE
Cannot Import Name 'StableCascadeDecoderPipeline'

### ISSUE THREAD

**Issue by hashnimo** [huggingface/diffusers#7147]
### Describe the bug

I'm running the following command in Google Colab but an error occurs.

### Reproduction

!pip install diffusers
import torch
from diffusers import StableCascadeDecoderPipeline, StableCascadePriorPipeline

### Logs

```shell
ImportError                               Traceback (most recent call last)
<ipython-input-2-a096c7f68b41> in <cell line: 2>()
      1 import torch
----> 2 from diffusers import StableCascadeDecoderPipeline, StableCascadePriorPipeline
      3 
      4 prior = StableCascadePriorPipeline.from_pretrained('stabilityai/stable-cascade-prior', torch_dtype=torch.bfloat16).to('cuda')
      5 decoder = StableCascadeDecoderPipeline.from_pretrained('stabilityai/stable-cascade',  torch_dtype=torch.float16).to('cuda')

ImportError: cannot import name 'StableCascadeDecoderPipeline' from 'diffusers' (/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

### System Info

- `diffusers` version: 0.26.3
- Platform: Linux-6.1.58+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.20.3
- Transformers version: 4.37.2
- Accelerate version: not installed
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Don't know

### Who can help?

@yiyixuxu @DN6 @sayakpaul

**Comment by sayakpaul** [comment]
It has not yet landed in the main library. Could you please install from the [PR](https://github.com/huggingface/diffusers/pull/6487) branch?

**Comment by hashnimo** [comment]
> It has not yet landed in the main library. Could you please install from the [PR](https://github.com/huggingface/diffusers/pull/6487) branch?
Thank you, but I don't understand how to do it. However, I found this code [here](https://github.com/Stability-AI/StableCascade/issues/45). Is this what you mean?
`!pip install git+https://github.com/kashif/diffusers.git@a3dc21385b7386beb3dab3a9845962ede6765887`

**Comment by sayakpaul** [comment]
```bash
pip install git+https://github.com/kashif/diffusers@wuerstchen-v3
```

should work.

**Comment by sayakpaul** [comment]
Closing the issue.
