### ISSUE TITLE
[LCM-LoRA] unexpected keys while loading LCM LoRA with `peft`

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#7157]
Code to reproduce:

```python
from diffusers import LCMScheduler, StableDiffusionXLPipeline
import torch

pipeline = StableDiffusionXLPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16).to("cuda")
pipeline.load_lora_weights("latent-consistency/lcm-lora-sdxl")
pipeline.fuse_lora()
pipeline.scheduler = LCMScheduler.from_config(pipeline.scheduler.config)

_ = pipe(
    prompt="a dog",
    num_inference_steps=4,
    guidance_scale=1.0,
)
```

Unexpected keys can be found here: https://github.com/huggingface/diffusers/actions/runs/8105285148/job/22153378360#step:8:45. 

Cc: @younesbelkada @pacman100

**Comment by younesbelkada** [comment]
thanks for reproting @sayakpaul what are the unexpected keys you get?

**Comment by sayakpaul** [comment]
@younesbelkada sorry. Just updated the PR description.

**Comment by sayakpaul** [comment]
@younesbelkada a gentle ping here.

**Comment by a-r-r-o-w** [comment]
@sayakpaul @younesbelkada A gentle ping here and if this has been resolved

**Comment by sayakpaul** [comment]
Depending on the urgency of the issue, we can revisit but we haven't seen anything regarding this. So, closing this for now.
