### ISSUE TITLE
Does diffusers does not support pytorch 2.2.0?

### ISSUE THREAD

**Issue by Luciennnnnnn** [huggingface/diffusers#7185]
### Describe the bug

When I install diffusers in a environment with torch 2.2.0, I see it degrade torch into 2.1.2, and mixed my environments.

### Reproduction

When I install diffusers in a environment with torch 2.2.0, I see it degrade torch into 2.1.2, and mixed my environments.

### Logs

```shell
When I install diffusers in a environment with torch 2.2.0, I see it degrade torch into 2.1.2, and mixed my environments.
```

### System Info

When I install diffusers in a environment with torch 2.2.0, I see it degrade torch into 2.1.2, and mixed my environments.

**Comment by standardAI** [comment]
Hi @Luciennnnnnn!
In terms of the latest pip release (v0.26.3), [yes](https://github.com/huggingface/diffusers/blob/66f94eaa0c68a893b2aba1ec9f79ee7890786fba/setup.py#L129). But, if you install `diffusers` from the source, then it can support [PyTorch 2.2](https://github.com/huggingface/diffusers/blob/ec953047bc0f4a3542e673f3d463543c02505ca5/setup.py#L129).

**Comment by Luciennnnnnn** [comment]
@standardAI Thanks, then I will shift to pytorch 2.1 temporarily.

**Comment by sayakpaul** [comment]
If you want to update to the PyTorch 2.2.1, you can definitely do so. I don't think that should be a problem. Cc: @DN6.

Going to close the issue because we are not aware of any issues particularly stemming from `diffusers` in the context of PyTorch 2.2.1.

**Comment by standardAI** [comment]
> Hi @Luciennnnnnn! In terms of the latest pip release (v0.26.3), [yes](https://github.com/huggingface/diffusers/blob/66f94eaa0c68a893b2aba1ec9f79ee7890786fba/setup.py#L129). But, if you install `diffusers` from the source, then [it](https://github.com/huggingface/diffusers/blob/ec953047bc0f4a3542e673f3d463543c02505ca5/setup.py#L129) can support PyTorch 2.2.

Ops, my answer doesn't seem to correct much; sorry for that. When I try to install `diffusers` with conda, my env forces to PyTorch 2.1; but this doesn't happen with installation via pip.
@Luciennnnnnn Which method did you try to install `diffusers`?
