### ISSUE TITLE
Strange import problem

### ISSUE THREAD

**Issue by Luciennnnnnn** [huggingface/diffusers#7191]
### Describe the bug

<img width="890" alt="image" src="https://github.com/huggingface/diffusers/assets/20135317/60a73583-4790-4975-989b-49ca19c890da">

I just can not import this loader

### Reproduction

from diffusers.loaders.controlnet import FromOriginalControlnetMixin

### System Info

- `diffusers` version: 0.26.3
- Platform: Linux-4.19.91-26.4.an7.x86_64-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.1.2 (True)
- Huggingface_hub version: 0.21.3
- Transformers version: 4.38.2
- Accelerate version: 0.27.2
- xFormers version: 0.0.23.post1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @yiyixuxu @DN6

**Comment by sayakpaul** [comment]
There's a typo there. It should be:

```bash
from diffusers.loaders.controlnet import FromOriginalControlNetMixin
```

**Comment by Luciennnnnnn** [comment]
Thanks, It's `FromOriginalControlnetMixin` in old version.
