### ISSUE TITLE
Sanster/anything-4.0-inpainting is missing fp16 files

### ISSUE THREAD

**Issue by offmybach** [huggingface/diffusers#7198]
got this error:

C:\Users\mdmen\anaconda3\envs\myiopaintenv\lib\site-packages\diffusers\pipelines\pipeline_utils.py:275: FutureWarning: You are loading the variant fp16 from Sanster/anything-4.0-inpainting via `revision='fp16'`. This behavior is deprecated and will be removed in diffusers v1. One should use `variant='fp16'` instead. However, it appears that Sanster/anything-4.0-inpainting currently does not have the required variant filenames in the 'main' branch.
 The Diffusers team and community would be very grateful if you could open an issue: https://github.com/huggingface/diffusers/issues/new with the title 'Sanster/anything-4.0-inpainting is missing fp16 files' so that the correct variant file can be added.
  warnings.warn(

**Comment by sayakpaul** [comment]
Reproducible code please.

**Comment by a-r-r-o-w** [comment]
Marking as closed due to inactivity. Please feel free to re-open if the issue still persists, but please also provide enough details for us to easily reproduce the error
