### ISSUE TITLE
¿Can i save all images of generation process?

### ISSUE THREAD

**Issue by elcejo** [huggingface/diffusers#722]
I would like to save each image generated at each step of the image generation process.
¿Is possible?

**Comment by patrickvonplaten** [comment]
Hey @elcejo that's definitely possible - either with the callback feature we introduced recently https://github.com/huggingface/diffusers/pull/521 or by simply unrolling your pipeline look: 
- See how to write an unrolled loop here: https://huggingface.co/blog/stable_diffusion
- and how to get the images here: https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/diffusers_intro.ipynb
