### ISSUE TITLE
The picture is full of noise use playground-v2.5-1024px-aesthetic.fp16.safetensors

### ISSUE THREAD

**Issue by zhaoyun0071** [huggingface/diffusers#7221]
### Describe the bug

with playground-v2.5-1024px-aesthetic.fp16.safetensors

![image](https://github.com/huggingface/diffusers/assets/35762050/bc38408c-0827-433e-b40e-2e257026de7d)

### Reproduction

```
from diffusers import StableDiffusionXLPipeline

pipeline = StableDiffusionXLPipeline.from_single_file(
    r"E:\模型\SDXL\playground-v2.5-1024px-aesthetic.fp16.safetensors", local_files_only=True, use_safetensors=True)
print('pipeline loaded')

pipeline.to('cuda')

prompt = "Astronaut in a jungle, cold color palette, muted colors, detailed, 8k"
image  = pipeline(prompt=prompt, guidance_scale=3.0).images
for i, img in enumerate(image):
    with open(f'./pg_{i}.jpg','w+') as f:
        img.save(f)
```

### System Info

diffusers==0.26.3

### Who can help?

@yiyixuxu @sayakpaul @DN6

**Comment by sayakpaul** [comment]
I think this is because the scheduler and VAE aren't handled accordingly here. 

Cc: @DN6

**Comment by sayakpaul** [comment]
@zhaoyun0071 could you check #7230 if it solves your issue?

**Comment by sayakpaul** [comment]
@zhaoyun0071 check out https://github.com/huggingface/diffusers/pull/7230 ?

**Comment by zhaoyun0071** [comment]
> @zhaoyun0071 check out https://github.com/huggingface/diffusers/pull/7230 ?

thanks 
No problem now

**Comment by nicksonredfield** [comment]
> @zhaoyun0071 check out #7230 ?

is it possible to push this fix to A1111? really need it, tks!
