### ISSUE TITLE
Add Latte: Latent Diffusion Transformer for Video Generation

### ISSUE THREAD

**Issue by kabachuha** [huggingface/diffusers#7223]
### Model/Pipeline/Scheduler description

Latte is a text2video diffusion transformer (similar to Sora), improving past the DiT and PixArt-alpha text2image models

The implementation is already based on diffusers (see [latte_t2v.py](https://github.com/Vchitect/Latte/blob/main/models/latte_t2v.py)), so adding it here should be a straightforward task

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

The official repo https://github.com/Vchitect/Latte
Model on Huggingface: https://huggingface.co/maxin-cn/Latte
Paper: https://arxiv.org/abs/2401.03048v1
Project page: https://maxin-cn.github.io/latte_project/

**Comment by sayakpaul** [comment]
Thanks for bringing this to our notice. Contributions are welcome, we're happy to assist and guide :) Cc: @DN6

**Comment by maxin-cn** [comment]
@sayakpaul Hi, I am the first author of Latte and we have updated the unwatermarked version of the LatteT2V model. We want to integrate Latte into `diffusers` library, what should I do? The pre-trained LatteT2V models are [here](https://huggingface.co/maxin-cn/LatteT2V/tree/main) and the codes are [here](https://github.com/Vchitect/Latte/blob/main/models/latte_t2v.py).

**Comment by sayakpaul** [comment]
Ccing @DN6 into this thread for further comments. I am happy to have the model integrated :)

**Comment by a-r-r-o-w** [comment]
Thanks for integrating Latte and your awesome work maxin!
