### ISSUE TITLE
Denoise latents after predicting `model pred`

### ISSUE THREAD

**Issue by OrangeSodahub** [huggingface/diffusers#7224]
Hi, I'm focusing on training controlnet: 
https://github.com/huggingface/diffusers/blob/687bc2772721af584d649129f8d2a28ca56a9ad8/examples/controlnet/train_controlnet.py#L1063-L1072
And I want to know how can I get the denoised image using the `model_pred`, I prefer to get the denoised rgb image tensor in single denoise step. Now I used this line:

```
denoised_latents = (noisy_latents - (1 - noise_scheduler.alphas_cumprod.to(accelerator.device)[timesteps]) ** 0.5 * model_pred) / \
                                        noise_scheduler.alphas_cumprod.to(accelerator.device)[timesteps] ** 0.5
```

But the results seem not to be smooth, I can't get the correct denoised images. Any instructions?

Thanks.

**Comment by sayakpaul** [comment]
This should move to discussions. 

https://github.com/huggingface/diffusers/discussions/7135
