### ISSUE TITLE
Applying Blockwise Weights to LoRA

### ISSUE THREAD

**Issue by dain5832** [huggingface/diffusers#7231]
It would be wonderful if I could apply stepwise or blockwise weights to LoRA, just like the webui extension below.
https://github.com/hako-mikan/sd-webui-lora-block-weight

Does anyone know if it's also possible in diffusers??

**Comment by UmerHA** [comment]
@yiyixuxu I'd take this on, if okay with you :)

**Comment by yiyixuxu** [comment]
@UmerHA sure!

**Comment by dain5832** [comment]
Awesome, thanks!
