### ISSUE TITLE
StableCascadePriorPipeline has no attribute 'from_single_file'

### ISSUE THREAD

**Issue by ballenvironment** [huggingface/diffusers#7256]
Are there plans to support `from_single_file` in the StableCascade pipelines? I would greatly appreciate it it's more convenient for me. 

Edit - Do the same for StableCascadePriorPipeline and StableCascadeDecoderPipeline 

Thanks!

**Comment by sayakpaul** [comment]
Cc: @DN6.

I think we should support it. `from_single_file()` on the combined pipeline could be unnecessarily non-trivial so, I would prefer avoiding that, though.

**Comment by DN6** [comment]
Hi @ballenvironment we don't have pipeline level single file yet for Stable Cascade. Can you point us to a single file checkpoint that exists for the entire SD Cascade pipeline? It will help with our tests are we try to support it

**Comment by ballenvironment** [comment]
Sorry my mistake, the single file I was trying to load was for StableCascadePriorPipeline not the combined pipeline.

**Comment by DN6** [comment]
@ballenvironment Following up here to do you have a checkpoint we can test with for loading the Prior as single file?

**Comment by ballenvironment** [comment]
> @ballenvironment Following up here to do you have a checkpoint we can test with for loading the Prior as single file?

This was the one I tried to load

https://huggingface.co/Ketengan-Diffusion/SomniumSC-v1.1/blob/main/SomniumSC-v1.1-bf16-stage_c.safetensors

**Comment by yiyixuxu** [comment]
hi @ballenvironment 
you can load the checkpoint you have like this 
https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_cascade#loading-original-checkpoints-with-fromsinglefile
