### ISSUE TITLE
[Community] Move the number "0.18215" from the image2image process to VAE config

### ISSUE THREAD

**Issue by wangyu-ustc** [huggingface/diffusers#726]
## There is a magic number "0.18215" in the repository

In the file `src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py`, there is a number "0.18215" in line 220 and line 342, which is strange since it does occur in the original [repo](https://github.com/CompVis/stable-diffusion/blob/69ae4b35e0a0f6ee1af8bb9a5d0016ccb27e36dc/scripts/img2img.py#L48). Is there someone  clarifying why is that and where does this number come from?

**Comment by WASasquatch** [comment]
It's a constant used to scale the `latents` so it can be decoded back into a image.

```python
# scale and decode the image latents with vae
scale and decode the image latents with vae
latents = 1 / 0.18215 * latents
image = vae.decode(latents).sample
```

**Comment by guaneec** [comment]
I think the constant is defined in the [model config file from CompVis/stable-diffusion](https://github.com/CompVis/stable-diffusion/blob/main/configs/stable-diffusion/v1-inference.yaml#L17).

**Comment by pcuenca** [comment]
There's more explanation about it in #437.

**Comment by patrickvonplaten** [comment]
Think we can have this be a config parameter that is overrideable and a `Union[int, str]` with the string describing a more complex squashing function that can be implemented down the road. 

Marking this for now as a community feature as it seems like no one finds the time to open a PR here - in case you're interested @neverix - we'd be more than happy to review a PR :-)

**Comment by patrickvonplaten** [comment]
Should be solved by: https://github.com/huggingface/diffusers/issues/1460 

@williamberman could you maybe tackle this?

**Comment by williamberman** [comment]
Put up draft PR here: https://github.com/huggingface/diffusers/pull/1515 still need to think about a few things

**Comment by fepegar** [comment]
For reference, here's some code to estimate the magic value: https://github.com/huggingface/diffusers/issues/437#issuecomment-1356945792.

**Comment by patrickvonplaten** [comment]
Thanks a lot @fepegar !

**Comment by patil-suraj** [comment]
https://github.com/huggingface/diffusers/pull/1860 is now merged, closing the issue.
