### ISSUE TITLE
Kohya Hires fix

### ISSUE THREAD

**Issue by crapthings** [huggingface/diffusers#7265]
is diffusers possible to support this hires fix?

it looks 1.5 work too

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13974

https://www.youtube.com/watch?v=SbgMwHDXthU

same seed at 1024x1024

with

![image](https://github.com/huggingface/diffusers/assets/1147704/7319ef5f-1581-407d-8ea7-edf8233cdfa6)

without

![image](https://github.com/huggingface/diffusers/assets/1147704/8499356b-c108-4707-8681-a2f33df80986)

This method will also improve the quality of inpainting without two pass

![image](https://github.com/huggingface/diffusers/assets/1147704/18539c66-bc22-4d00-a332-45ca31f9ecc9)

![image](https://github.com/huggingface/diffusers/assets/1147704/58b3f007-106d-4c55-a371-00332ce2bf3b)

**Comment by sayakpaul** [comment]
I think the improvements are quite amazing TBH. Ccing @kohya-ss in case you would like to elaborate the motivation behind the fix a bit. 

@yiyixuxu WDYT about shipping this?

**Comment by crapthings** [comment]
this one is 1280 x 1280 with Kohya Hires.fix

![image](https://github.com/huggingface/diffusers/assets/1147704/a09bab44-197b-46a4-8158-4d799f71e629)

**Comment by sayakpaul** [comment]
Gently pinging @kohya-ss since you reacted to my comment. If you find a moment, would love some sort of a brief explanation about the feature. Would be really helpful!

**Comment by sayakpaul** [comment]
Thanks much for your detailed explanation. Really appreciate it.

**Comment by jorgemcgomes** [comment]
Looks very interesting.
Could this theoretically be used in the opposite way, to generate smaller images?
When trying to generate small images with models that have been trained with high-res images, we often see the same kind of problems -- weird compositions, low quality.
So, could the feature maps be resized to a larger size? So that it becomes possible to generate low-res images that have the same composition as high-res ones?

**Comment by blx0102** [comment]
looking forward to this feature!

**Comment by yiyixuxu** [comment]
can someone make a community pipeline first for this? basically, you need to:
1. copy over the `UNet2DConditionModel`, rename it, add slightly modify the `forward` method to implement kohya Hires fix
2. add a `from_unet` method which is basically 
```
@classmethod
    def from_unet(
        cls,
        unet: UNet2DConditionModel,
        ds_depth_1 = ds_depth_1,
        ds_depth_2 = ds_depth_2,
        ...
    ):  
        config = dict((unet.config)
        config[" ds_depth_1"] = ds_depth_1
        config["ds_depth_2"] = ds_depth_2,

        koyha_unet = cls.from_config(config)
        koyha_unet.load_state_dict(unet.state_dict())
```
3. copy over the SD or SDXL pipeline, rename it, and slightly update the `__init__` method
```python 
def __init__():
      ...
       unet = kohyaHiresFixUnet2DConditionalModel.from_unet(unet, **kwargs)
        self.register_modules(
           ...
            unet=unet,
        )
```

and then please play around with it, figure out how to configure it for SD and SDXL, and show us some results! Once we have the community pipeline that we can play with, depending on how good the results are and how users react to it, we can then decide if we want to integrate this fix into our Unet or not (should be pretty straightforward)

**Comment by sajadn** [comment]
Hey, I'll work on this.

**Comment by satani99** [comment]
hey @sajadn are you working on this?

**Comment by sajadn** [comment]
I'm planning to open the PR this weekend. If you think you can finish it up sooner, feel free to go ahead.

**Comment by sajadn** [comment]
I need 1 or 2 days more, sorry about the delay.

**Comment by sajadn** [comment]
Hi, 
I reproduced the results on SD model (I don't have enough GPU memory for SDXL) with a resolution of 1000x1600. Here are some examples:

prompt: "a dog sitting on the couch"
without fix:

![a_dog_sitting_on_the_couch_fix=False](https://github.com/huggingface/diffusers/assets/13849465/1e0bae05-8298-4247-8a59-ffed4f8514f6)

with the fix:
![a_dog_sitting_on_the_couch_fix=True](https://github.com/huggingface/diffusers/assets/13849465/04a67eb8-10e7-4bc5-8338-a5b362d9f6f5)

prompt: "a pig sitting behind the desk"
without fix:
![a_pig_sitting_behind_the_desk_fix=False](https://github.com/huggingface/diffusers/assets/13849465/0b87a5bd-f14e-41bd-8028-d896f939a44d)

with the fix:
![a_pig_sitting_behind_the_desk_fix=True](https://github.com/huggingface/diffusers/assets/13849465/77472fd4-9941-42a7-be44-ca143970f8a7)

prompt: "a cyclist front view near the finish line"
without the fix:
![a_cyclist_front_view_near_the_finish_line_fix=False](https://github.com/huggingface/diffusers/assets/13849465/7bad05e3-fd18-42b7-8f0e-02375e9f0c18)

with the fix:
![a_cyclist_front_view_near_the_finish_line_fix=True](https://github.com/huggingface/diffusers/assets/13849465/76f0c6b2-4fab-4fd1-8187-dd11fd162924)

As mentioned before on this thread, this is only an issue for the high resolution images. For example I provided 512x512 version of the dog and pig images below:
dog:
![a_dog_sitting_on_the_couch_fix=False](https://github.com/huggingface/diffusers/assets/13849465/0bdd6c52-5759-42ed-8ebb-7791c9b6ce16)
pig:
![a_pig_sitting_behind_the_desk_fix=False](https://github.com/huggingface/diffusers/assets/13849465/89f801e5-d039-487d-9c2a-7ed333057830)


You can find the code in my [fork](https://github.com/sajadn/diffusers)

and here is the code snippet to generate images:
```
from diffusers.pipelines.stable_diffusion import StableDiffusionHighResFixPipeline
import torch

generator = torch.manual_seed(42)
with_high_res_fix = False
pipe = StableDiffusionHighResFixPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", 
                                                         generator=generator,
                                                         torch_dtype=torch.float16, 
                                                         use_safetensors=True, 
                                                         variant="fp16",
                                                         high_res_fix=[{'timestep': 600, 'scale_factor': 0.5, 'layer_num': 1}] if with_high_res_fix else None
                                                         )
pipe.to("cuda")
prompt = "a dog sitting on the couch"
image = pipe(prompt=prompt,
                height=1000,
                width=1600, 
                num_inference_steps=50).images[0]

image.save(f"{prompt.replace(' ', '_')}_fix={with_high_res_fix}.png")
```

I have to work on something else for the rest of today. I'll clean the code and open up the PR tomorrow.

**Comment by crapthings** [comment]
> Hi, I reproduced the results on SD model (I don't have enough GPU memory for SDXL). Here are some examples with a resolution of 1000x1600:
> 
> prompt: "a dog sitting on the couch" without fix:
> 
> ![a_dog_sitting_on_the_couch_fix=False](https://private-user-images.githubusercontent.com/13849465/320976644-1e0bae05-8298-4247-8a59-ffed4f8514f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMwODcsIm5iZiI6MTcxMjgyMjc4NywicGF0aCI6Ii8xMzg0OTQ2NS8zMjA5NzY2NDQtMWUwYmFlMDUtODI5OC00MjQ3LThhNTktZmZlZDRmODUxNGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOTQ3ZWYyZTBmZGUxZjc2MjNmMmJlYTRiZjM3Y2FjM2E3NjQ0ZWZmZWE1MzAzNmFmNjI3ZDEwMTE4NGZiNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qn4d7JnmMDY4SnQsE_lP-6T-L3cy_2oXkoSQOy4FlLM)
> 
> with the fix: ![a_dog_sitting_on_the_couch_fix=True](https://private-user-images.githubusercontent.com/13849465/320976859-04a67eb8-10e7-4bc5-8338-a5b362d9f6f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMwODcsIm5iZiI6MTcxMjgyMjc4NywicGF0aCI6Ii8xMzg0OTQ2NS8zMjA5NzY4NTktMDRhNjdlYjgtMTBlNy00YmM1LTgzMzgtYTViMzYyZDlmNmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MDMwMjQ1OTQ1MGE0YjRhMzdjNDQ5NWYwY2U1ZDM0N2VkMGVhOGI1NDNiYTNkNWE2YWJlNTE2MTMxMDY3NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JmwdpkUNt-z6cr2AoFJb7Fo12Wm5apGg6unGeCD3jN4)
> 
> prompt: "a pig sitting behind the desk" without fix: ![a_pig_sitting_behind_the_desk_fix=False](https://private-user-images.githubusercontent.com/13849465/320976987-0b87a5bd-f14e-41bd-8028-d896f939a44d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMwODcsIm5iZiI6MTcxMjgyMjc4NywicGF0aCI6Ii8xMzg0OTQ2NS8zMjA5NzY5ODctMGI4N2E1YmQtZjE0ZS00MWJkLTgwMjgtZDg5NmY5MzlhNDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjODZkNmQ4N2ZiMzcyNzU1MjBkZDBlNTdhZjE4MDRmOWYwYTdhZjYzMjZiZDlkNzM0OTkwMGM5MmRiNjExOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cplMRvZvNE12jYAMYEAQGCrnO--su9wevDEVDOXwYDo)
> 
> with the fix: ![a_pig_sitting_behind_the_desk_fix=True](https://private-user-images.githubusercontent.com/13849465/320977039-77472fd4-9941-42a7-be44-ca143970f8a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMwODcsIm5iZiI6MTcxMjgyMjc4NywicGF0aCI6Ii8xMzg0OTQ2NS8zMjA5NzcwMzktNzc0NzJmZDQtOTk0MS00MmE3LWJlNDQtY2ExNDM5NzBmOGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0N2ViNzJmNmE3MmVlZjViN2FmYjA4YmU1MTA3OTJhODkxOTJkOGVkMmYyYzJmZDJkMmFjYThlMTVmMmFlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-SO7EC7KDLC3cLZ3t_khhbaKaysz3Tkh2rRvPVCVKJ0)
> 
> prompt: "a cyclist front view near the finish line" without the fix: ![a_cyclist_front_view_near_the_finish_line_fix=False](https://private-user-images.githubusercontent.com/13849465/320977401-7bad05e3-fd18-42b7-8f0e-02375e9f0c18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMwODcsIm5iZiI6MTcxMjgyMjc4NywicGF0aCI6Ii8xMzg0OTQ2NS8zMjA5Nzc0MDEtN2JhZDA1ZTMtZmQxOC00MmI3LThmMGUtMDIzNzVlOWYwYzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZmU4NjkzZWJlZmVhYjk1ZDRmNGRlNmE4MmY4OWYyNTJlNDFjNDQwY2NhOGI3YmY1Yjg2M2UzNGM2ZjgzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9xZSzENZklsAIZ3EKkQyX7ZnU-If0Uq1M9OvW6-9u0)
> 
> with the fix: ![a_cyclist_front_view_near_the_finish_line_fix=True](https://private-user-images.githubusercontent.com/13849465/320977470-76f0c6b2-4fab-4fd1-8187-dd11fd162924.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMwODcsIm5iZiI6MTcxMjgyMjc4NywicGF0aCI6Ii8xMzg0OTQ2NS8zMjA5Nzc0NzAtNzZmMGM2YjItNGZhYi00ZmQxLTgxODctZGQxMWZkMTYyOTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NGUyOWZjOWEyZDVkZDYzODZkOTliMmY5MDNmZGNjOGUyZmYzZjcwMjAwMmM4MDNhYmY5ZTg4ODRkNTZlYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oGvNYumtYzjPDLchRRGy8qFyOduJSYXDNAOveAKjUbo)
> 
> As mentioned before on this thread, this is only an issue for high resolution images. For example, I provided 512x512 version of the images for the same prompts:
> 
> ![a_dog_sitting_on_the_couch_fix=False](https://private-user-images.githubusercontent.com/13849465/320981156-0bdd6c52-5759-42ed-8ebb-7791c9b6ce16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMwODcsIm5iZiI6MTcxMjgyMjc4NywicGF0aCI6Ii8xMzg0OTQ2NS8zMjA5ODExNTYtMGJkZDZjNTItNTc1OS00MmVkLThlYmItNzc5MWM5YjZjZTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MDEzZDBiMjU5MWNlOGIyOWM5NjcxMGM5ZDUzZGZhOTU2NWU5NWVkNjE3ZWFlYjAzODQ4Y2I5ZDk4NzljNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4bbDCdv2TkbQExHab_hbjvYiSxbleHcsDgjbmx7VvE)
> 
> ![a_pig_sitting_behind_the_desk_fix=False](https://private-user-images.githubusercontent.com/13849465/320981190-89f801e5-d039-487d-9c2a-7ed333057830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMwODcsIm5iZiI6MTcxMjgyMjc4NywicGF0aCI6Ii8xMzg0OTQ2NS8zMjA5ODExOTAtODlmODAxZTUtZDAzOS00ODdkLTljMmEtN2VkMzMzMDU3ODMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MDU1ODM0NzEzYjUzNDg4OWYzMTU2M2JhZDYzZDhkNDlkMzUzMTkxNzM5MjZlNWMyYTVmMDAzMzBiMTJhZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JHMudABKOkM7JP_QoOJGV5MKev3YUAO7FdztFPOLsR4)
> 
> ![a_cyclist_front_view_near_the_finish_line_fix=True](https://private-user-images.githubusercontent.com/13849465/320982516-62b5b087-2093-4f9c-929a-5570ff5bd044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjMwODcsIm5iZiI6MTcxMjgyMjc4NywicGF0aCI6Ii8xMzg0OTQ2NS8zMjA5ODI1MTYtNjJiNWIwODctMjA5My00ZjljLTkyOWEtNTU3MGZmNWJkMDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MDYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZmZkNmNiZjdlNDk3YzY3YzU4ZDFmYWM0NWQyOWZmMzQ5ODQxNTYyZDVkYmYzMzdmNjQyNDdlNzlkYjU0MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.voTtg06JU_ZQiMWjHrGiOCGNJwF4xCOYjd1-AOM5NVM)
> 
> You can find the code in my [fork](https://github.com/sajadn/diffusers)
> 
> and here is the code snippet to generate images:
> 
> ```
> from diffusers.pipelines.stable_diffusion import StableDiffusionHighResFixPipeline
> import torch
> 
> generator = torch.manual_seed(42)
> with_high_res_fix = False
> pipe = StableDiffusionHighResFixPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", 
>                                                          generator=generator,
>                                                          torch_dtype=torch.float16, 
>                                                          use_safetensors=True, 
>                                                          variant="fp16",
>                                                          high_res_fix=[{'timestep': 600, 'scale_factor': 0.5, 'layer_num': 1}] if with_high_res_fix else None
>                                                          )
> pipe.to("cuda")
> prompt = "a dog sitting on the couch"
> image = pipe(prompt=prompt,
>                 height=1000,
>                 width=1600, 
>                 num_inference_steps=50).images[0]
> 
> image.save(f"{prompt.replace(' ', '_')}_fix={with_high_res_fix}.png")
> ```
> 
> I have to work on something else for the rest of today. I'll clean the code and open up the PR tomorrow.

is this work with inpainting version?

**Comment by neuron-party** [comment]
does this work for SDXL?

**Comment by asomoza** [comment]
This is a community pipeline for just SD not SDXL or any of the controlnet variants of any model.

**Comment by asomoza** [comment]
I tested it and yes, well kinda:

|without fix|with fix|
|---|---|
|![20240602163026_1110963719](https://github.com/huggingface/diffusers/assets/5442875/064ca70e-29f4-4691-86f2-0f590a0626e2)|![20240602170330_1110963719](https://github.com/huggingface/diffusers/assets/5442875/55abe4e8-f052-42b2-bd43-7bc44758ae61)|

**Comment by Depfek6** [comment]
@sajadn KeyError: 'block_num'
Am i do wrong?
When i set the with_high_res_fix = False
It worked fine
But when i set with_high_res_fix = True
It got KeyError: 'block_num'

**Comment by Depfek6** [comment]
@sajadn am i do wrong?
When i set with_high_res_fix = True
It got KeyError: 'block_num'
But when i set with_high_res_fix = False
It worked just fine

**Comment by yiyixuxu** [comment]
@asomoza what is this? SDXL text-to-image?

**Comment by asomoza** [comment]
yeah, I did a test with it, just adapted the community pipeline to SDXL. I've been reading about it and in fact, for SDXL it needs another configuration. Comfyui has a core node now but it's more complex that this one.

For SDXL I don't think it will be used a lot, with the 2048x2048 image I did, I used the full 24GB of VRAM.

**Comment by sajadn** [comment]
@Depfek6 I guess you're using the code snippet from a thread above, in the final commit I renamed `layer_num`  to `block_num`. I think if you just do the same renaming it will be fixed.  I'll edit the code snippet above to avoid future confusion.

**Comment by neuron-party** [comment]
could you share a code snippet of hires fix with sdxl? i couldn't get it working

**Comment by asomoza** [comment]
Sure but I just did a quick patch to make it work, let me know if you find a good set of params or if you find it useful with SDXL and maybe we can add it as a community pipeline.

You need an install from source or download the `examples/community` directory

```python
from examples.community.kohya_hires_fix import UNet2DConditionModelHighResFix


class StableDiffusionXLHighResFixPipeline(StableDiffusionXLPipeline):
    def __init__(
        self,
        vae: AutoencoderKL,
        text_encoder: CLIPTextModel,
        text_encoder_2: CLIPTextModelWithProjection,
        tokenizer: CLIPTokenizer,
        tokenizer_2: CLIPTokenizer,
        unet: UNet2DConditionModel,
        scheduler: KarrasDiffusionSchedulers,
        image_encoder: CLIPVisionModelWithProjection = None,
        feature_extractor: CLIPImageProcessor = None,
        force_zeros_for_empty_prompt: bool = True,
        add_watermarker: Optional[bool] = None,
    ):
        super().__init__(
            vae=vae,
            text_encoder=text_encoder,
            text_encoder_2=text_encoder_2,
            tokenizer=tokenizer,
            tokenizer_2=tokenizer_2,
            unet=unet,
            scheduler=scheduler,
            image_encoder=image_encoder,
            feature_extractor=feature_extractor,
            force_zeros_for_empty_prompt=force_zeros_for_empty_prompt,
            add_watermarker=add_watermarker,
        )

        unet = UNet2DConditionModelHighResFix.from_unet(
            unet=unet, high_res_fix=[{"timestep": 600, "scale_factor": 0.5, "block_num": 1}]
        )

        self.register_modules(
            vae=vae,
            text_encoder=text_encoder,
            text_encoder_2=text_encoder_2,
            tokenizer=tokenizer,
            tokenizer_2=tokenizer_2,
            unet=unet,
            scheduler=scheduler,
            image_encoder=image_encoder,
            feature_extractor=feature_extractor,
        )
        self.register_to_config(force_zeros_for_empty_prompt=force_zeros_for_empty_prompt)
        self.vae_scale_factor = 2 ** (len(self.vae.config.block_out_channels) - 1)
        self.image_processor = VaeImageProcessor(vae_scale_factor=self.vae_scale_factor)

        self.default_sample_size = self.unet.config.sample_size
```

And then you can just use the `StableDiffusionXLHighResFixPipeline` instead of the regular one.

**Comment by neuron-party** [comment]
thanks! just tested it out with a few different set of params but couldn't get any significant results
