### ISSUE TITLE
Wrong Text-encoder Grad Setting in Custom_Diffusion

### ISSUE THREAD

**Issue by Rbrq03** [huggingface/diffusers#7294]
### Describe the bug

According to [Custom Diffusion](https://arxiv.org/pdf/2212.04488.pdf), It only trains modified tokens. In implementation, it set the grad of non-modified tokens to zero. But there is a bug in this implementation.

https://github.com/huggingface/diffusers/blob/531e719163d2d7cf0d725bb685c1e8fe3393b9da/examples/custom_diffusion/train_custom_diffusion.py#L1180-L1187

In 

https://github.com/huggingface/diffusers/blob/531e719163d2d7cf0d725bb685c1e8fe3393b9da/examples/custom_diffusion/train_custom_diffusion.py#L1183

it should be 

`torch.arange(len(tokenizer)) != modifier_token_id[i + 1]`

as the variant 'i' starts from 0.

Consequently, the last concept would not be trained if you want to train multiple concepts(It works well when single concept training).

Should I open a PR to fix that? 

### Reproduction

export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export OUTPUT_DIR="./ckpt"

accelerate launch train_custom_diffusion.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --output_dir=$OUTPUT_DIR \
  --concepts_list=./concept.json \
  --resolution=512  \
  --train_batch_size=2  \
  --learning_rate=1e-5  \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --scale_lr \
  --hflip  \
  --modifier_token "<new1>+<new2>" \
  --no_safe_serialization \

### System Info

diffusers :0.27.0.dev0

### Who can help?

@sayakpaul @DN6 @yiyixuxu

**Comment by sayakpaul** [comment]
Thanks for the detailed thread. Happy to review a fix PR.
