### ISSUE TITLE
High GPU memory usage after `set_default_attn_processor()` in unet

### ISSUE THREAD

**Issue by moono** [huggingface/diffusers#7300]
### Describe the bug

I was using IPAdapter and saw `unload_ip_adapter()` in `IPAdapterMixin` which helps to rollback to default unet status.
But found that after using that function (`unload_ip_adapter()`) the inference speed gets slower and GPU's reserved memory peaks too high.

### Reproduction

Posting minimal reproducible code. (Even though below code is just txt2img without IPAdapter) 

* normal case: working fine

```python
import time
import torch

from diffusers import DiffusionPipeline


# https://stackoverflow.com/a/1094933
def sizeof_fmt(num: int, suffix="B") -> str:
    for unit in ("", "Ki", "Mi", "Gi", "Ti", "Pi", "Ei", "Zi"):
        if abs(num) < 1024.0:
            return f"{num:3.2f}{unit}{suffix}"
        num /= 1024.0
    return f"{num:.1f}Yi{suffix}"


common_init_kwargs = {
    "torch_dtype": torch.float16,
    "variant": "fp16",
    "use_safetensors": True,
    "feature_extractor": None,
    "safety_checker": None,
    "requires_safety_checker": False,
}

pipe = DiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", **common_init_kwargs
)
pipe.to("cuda")
pipe.enable_xformers_memory_efficient_attention()

print(f"After pipeline loading: {sizeof_fmt(torch.cuda.memory_reserved())}")


for idx in range(3):
    t_start = time.perf_counter()
    image = pipe(
        "An image of a squirrel in Picasso style",
        num_inference_steps=30,
        height=1024,
        width=1024,
    ).images[0]
    elapsed = time.perf_counter() - t_start

    print(f"After inference [{idx}]: {sizeof_fmt(torch.cuda.memory_reserved())} with {elapsed:.3f}s")
```

* weird case: 
  * Code is same as above but add single line (`pipe.unload_ip_adapter()` ) at the end.

```python
import time
import torch

from diffusers import DiffusionPipeline


# https://stackoverflow.com/a/1094933
def sizeof_fmt(num: int, suffix="B") -> str:
    for unit in ("", "Ki", "Mi", "Gi", "Ti", "Pi", "Ei", "Zi"):
        if abs(num) < 1024.0:
            return f"{num:3.2f}{unit}{suffix}"
        num /= 1024.0
    return f"{num:.1f}Yi{suffix}"


common_init_kwargs = {
    "torch_dtype": torch.float16,
    "variant": "fp16",
    "use_safetensors": True,
    "feature_extractor": None,
    "safety_checker": None,
    "requires_safety_checker": False,
}

pipe = DiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", **common_init_kwargs
)
pipe.to("cuda")
pipe.enable_xformers_memory_efficient_attention()

print(f"After pipeline loading: {sizeof_fmt(torch.cuda.memory_reserved())}")


for idx in range(3):
    t_start = time.perf_counter()
    image = pipe(
        "An image of a squirrel in Picasso style",
        num_inference_steps=30,
        height=1024,
        width=1024,
    ).images[0]
    elapsed = time.perf_counter() - t_start

    print(f"After inference [{idx}]: {sizeof_fmt(torch.cuda.memory_reserved())} with {elapsed:.3f}s")
    pipe.unload_ip_adapter()
```

### Logs

```shell
* normal case: same speed and GPU memory usage
> Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 11.80it/s]
After pipeline loading: 2.03GiB
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.70it/s]
After inference [0]: 6.40GiB with 6.253s
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.99it/s]
After inference [1]: 6.40GiB with 5.395s
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.00it/s]
After inference [2]: 6.40GiB with 5.296s

* weird case: much slower and high gpu memory usage
> Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 11.52it/s]
After pipeline loading: 2.03GiB
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.69it/s]
After inference [0]: 6.40GiB with 6.295s
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:17<00:00,  1.73it/s]
After inference [1]: 22.40GiB with 17.691s
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:17<00:00,  1.72it/s]
After inference [2]: 22.40GiB with 17.688s
```

### System Info

- `diffusers` version: 0.26.3
- Platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.31
- Python version: 3.11.8
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.21.4
- Transformers version: 4.38.2
- Accelerate version: 0.28.0
- xFormers version: 0.0.21
- Using GPU in script?: YES
- Using distributed or parallel set-up in script?: NO

### Who can help?

@yiyixuxu, @DN6,

**Comment by fabiorigano** [comment]
when loading a model, diffusers checks if you have pytorch 2 installed and if scaled dot-product attention is supported - that makes computations very fast - and, if that's the case, uses AttnProcessor2_0 as attention processor
when you call `pipeline.set_default_attn_processor()` (called by `pipeline.unload_ip_adapter()`), diffusers resets all attention processors to AttnProcessor, even if you have pytorch's SDPA support (used in AttnProcessor2_0 and not in AttnProcessor)

**Comment by yiyixuxu** [comment]
@fabiorigano 
should we change the behavior then? 
I don't think we should change the behavior of `set_default_attn_processor()` since it is mostly used for testing
but we can change the behavior in `unload_ip_adapter()` to use  AttnProcessor2_0  if it is possible

**Comment by fabiorigano** [comment]
hi @yiyixuxu yes, it should be an easy fix in `unload_ip_adapter()`

**Comment by yiyixuxu** [comment]
@fabiorigano do you want to open a PR?

**Comment by fabiorigano** [comment]
@yiyixuxu done! :)

**Comment by moono** [comment]
Fist of all thank you @fabiorigano for the patch.

Just single note,
If someone uses above patched @fabiorigano's `unload_ip_adapter()` to reset the unet attention status, (#7727) 
then you must use `pipe.enable_xformers_memory_efficient_attention()` again after `unload_ip_adapter()` to reduce gpu memory burst.

**Comment by yiyixuxu** [comment]
@moono 
you did not have to do that before the fix?

**Comment by moono** [comment]
@yiyixuxu 
well, I didn't realize that I had to call `pipe.enable_xformers_memory_efficient_attention()` after `unload_ip_adapter` until now.

**Comment by christopher5106** [comment]
I would like to say, that it might not  be serious to let such a big leak pass through. I'm questioning if the review process has been careful enough. When loading/unloading components on a pipe breaks the pipe, it has heavy consequences.

**Comment by fabiorigano** [comment]
hi @christopher5106, did you experience any issues?
from what I know and from docs (https://huggingface.co/docs/diffusers/optimization/memory#memory-efficient-attention), xFormers is not really useful in speeding up inference or reducing memory usage when you have installed pytorch 2, because the SDPA has been implemented in a memory efficient way.
I also think that documentation can be easily updated if we notice that `enable_xformers_memory_efficient_attention()` must be run again after unloading IP Adapters in pytorch 1.x envs.
please open a new issue if you encounter any issues

**Comment by christopher5106** [comment]
I confirm that xformers do not bring speed up.

No, my problem was an OOM on a pipeline that stays up for multiple inferences, with or without IP adapter. Probably the unloading of ipadapter left some operations in the unet that expanded dimensions leading to OOM. Running the inferences individually reloading the pipe was ok.

I don't know how easy it is to be careful so that unloading of any components (Loras, ipadapters, etc) do not leave the pipeline in a different state than before.
