### ISSUE TITLE
Can use zero_snr when I use "from_pretrained" to create the scheduler

### ISSUE THREAD

**Issue by CuddleSabe** [huggingface/diffusers#7303]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

**Describe the solution you'd like.**

**Describe alternatives you've considered.**

**Additional context.**

**Comment by sayakpaul** [comment]
I don't understand the issue.

**Comment by sayakpaul** [comment]
Closing because of inactivities.
