### ISSUE TITLE
Do we need __init__ in ModelMixin class?

### ISSUE THREAD

**Issue by eldercrow** [huggingface/diffusers#7305]
https://github.com/huggingface/diffusers/blame/46ab56a468cbc43c1ab48190e27fc42195f4c60b/src/diffusers/models/modeling_utils.py#L199

I've observed that `ModelMixin` class currently includes an `__init__` method, which does not accept any arguments (args) or keyword arguments (kwargs). This design choice restricts the utility of Mixin classes in scenarios involving multiple inheritance, as it complicates the integration of such classes with others that do accept initialization parameters.

From a best practices perspective, Mixin classes are generally expected to offer additional functionality to classes without imposing constraints on their initialization. The presence of a non-flexible `__init__` method in a Mixin contradicts this principle, leading to potential issues with class composition and reusability.

To enhance compatibility and adhere to the conventional role of Mixin classes, I propose two potential solutions:

Remove the `__init__` method from Mixin classes altogether.
Modify the `__init__` method to accept arbitrary positional and keyword arguments (`*args` and `**kwargs`), ensuring it can seamlessly integrate with other classes' initialization processes.
Implementing either of these changes would significantly improve the flexibility and applicability of Mixin classes in multiple inheritance scenarios. I believe this adjustment is crucial for maintaining robust and adaptable codebases.

**Comment by sayakpaul** [comment]
Can you give us a more concrete example of why this choice is restrictive?

**Comment by eldercrow** [comment]
I've encountered a `TypeError` when trying to instantiate a class (`MyGraph`) that inherits from both `ModelMixin` and `Graph`. The issue arises because `ModelMixin.__init__()` does not accept additional positional arguments, which are necessary for initializing the `Graph` part of my class.

Here is a brief overview of my classes:

``` python
from diffusers import ModelMixin

class Graph:
    def __init__(self, inputs, outputs, parameters):
        self.inputs = inputs
        self.outputs = outputs
        self.parameters = parameters
    ...

class MyGraph(ModelMixin, Graph):
    def __init__(self, inputs, outputs, parameters, **kwargs):
        super().__init__(inputs, outputs, parameters)
    ...
```

Attempting to create an instance of `MyGraph` results in the following error:

``` 
mygraph = MyGraph(inputs=['x'], outputs=['y'], parameters=['a', 'b'])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 mygraph = MyGraph(inputs=['x'], outputs=['y'], parameters=['a', 'b'])

Cell In[4], line 9
      8 def __init__(self, inputs, outputs, parameters, **kwargs):
----> 9     super().__init__(inputs, outputs, parameters)

TypeError: ModelMixin.__init__() takes 1 positional argument but 4 were given
```

The Method Resolution Order (MRO) for `MyGraph` is as follows, showing that `ModelMixin` is indeed part of the inheritance chain:

``` 
MyGraph.__mro__

(__main__.MyGraph,
 diffusers.models.modeling_utils.ModelMixin,
 torch.nn.modules.module.Module,
 diffusers.utils.hub_utils.PushToHubMixin,
 __main__.Graph,
 object)
```

This issue points to a need for `ModelMixin` to be able to pass through `*args` and `**kwargs` to superclasses, ensuring all necessary initialization parameters can be handled appropriately in classes like `Graph` that require them.

I propose updating the `ModelMixin` class to support forwarding of arbitrary positional and keyword arguments, as shown below:

``` python
class ModelMixin(...):
    def __init__(*args, **kwargs):
        super().__init__(*args, **kwargs)
```

This enhancement would improve the mixin's compatibility with other classes in multiple inheritance scenarios, facilitating smoother class compositions and initializations.

I hope this explanation helps understand the issue and the proposed solution. I believe this change will significantly enhance the flexibility and usability of the `ModelMixin` and similar classes in complex inheritance structures.

**Comment by sayakpaul** [comment]
Thanks a lot for providing the additional info, appreciate that!

https://github.com/huggingface/diffusers/blob/95de1981c9ae9134533dac4ac4e5bc0930ce5442/src/diffusers/models/unets/unet_2d_condition.py#L69

has its own init, though and it works perfectly fine. So, I wonder what's the actual issue here.

**Comment by eldercrow** [comment]
As you can see in the link below, it simply calls `super().__init__()` without passing any arguments. In this scenario, no parameters are forwarded to the superclass, so it doesn't cause any issues with `ModelMixin`. The problem arises when `super().__init__` is called with additional parameters.

https://github.com/huggingface/diffusers/blob/95de1981c9ae9134533dac4ac4e5bc0930ce5442/src/diffusers/models/unets/unet_2d_condition.py#L222

**Comment by sayakpaul** [comment]
@yiyixuxu WDYT? 

Personally, I am not super convinced about this. Design-wise, within `diffusers`, a class inheriting from `ModelMixin` is usually not almost subclassed by another class that might want to use Method Resolution Order to resolve the init arguments.

**Comment by eldercrow** [comment]
Any update on this issue?

**Comment by yiyixuxu** [comment]
hey! thanks for the issue!
however, this is kinda against our design principle: at diffusers, we want to keep the level of abstraction to an absolute minimum. All our models are inherited from `ModelMixin` and `ConfigMixin`. There are never more than two levels of abstraction and we intend to keep it that way :)

You can read more about our philosophy here https://huggingface.co/docs/diffusers/en/conceptual/philosophy

**Comment by yiyixuxu** [comment]
closing this now because we will not be able to support this
