### ISSUE TITLE
VAE config mismatch when using StableDiffusionInpainting 

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#7334]
Currently, we have got a failing test:

```
tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py::StableDiffusionInpaintPipelineSlowTests::test_single_file_component_configs
```

And it fails for the right reason! You will notice that the [assertion](https://github.com/huggingface/diffusers/blob/5d848ec07c2011d600ce5e5c1aa02a03152aea9b/tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py#L811) doesn't pass for `sample_size`. For the `diffusers` checkpoint, this value is 256 and the inferred value from the single-file checkpoint is 512.  

This is a bit of an issue because the `sample_size` param in the VAE influences the tiling factors:
https://github.com/huggingface/diffusers/blob/5d848ec07c2011d600ce5e5c1aa02a03152aea9b/src/diffusers/models/autoencoders/autoencoder_kl.py#L119

So, for the VAE loaded from the `diffusers` checkpoint will have a different tiling configuration from the one loaded from the single-file checkpoint. 

Cc: @DN6 @yiyixuxu

**Comment by yiyixuxu** [comment]
I think this will not be an issue once we have https://github.com/huggingface/diffusers/pull/7496, no?

**Comment by sayakpaul** [comment]
I will let @DN6 test that.

**Comment by DN6** [comment]
Yeah this is an expected failure because the configs on the repo are incorrect. I think we would have to open PRs there, but that could change stuff for downstream applications.
