### ISSUE TITLE
How to convert multiple piped files into a single SafeTensor file?

### ISSUE THREAD

**Issue by xddun** [huggingface/diffusers#7337]
How to convert multiple piped files into a single SafeTensor file?

For example, from this address: https://huggingface.co/Vargol/sdxl-lightning-4-steps/tree/main

```python
import torch
from diffusers import StableDiffusionXLPipeline, EulerDiscreteScheduler

base = "Vargol/sdxl-lightning-4-steps"

pipe = StableDiffusionXLPipeline.from_pretrained(base, torch_dtype=torch.float16).to("cuda")
```

How can I convert `pipe` into a single SafeTensor file as a whole?

Just like the file `sd_xl_base_1.0_0.9vae.safetensors`, which contains the components needed from `diffusers`.

_Originally posted by @xddun in https://github.com/huggingface/diffusers/issues/5360#issuecomment-1998986263_

**Comment by asomoza** [comment]
https://github.com/huggingface/diffusers/discussions/7336#discussioncomment-8796829

**Comment by sayakpaul** [comment]
Closing as it seems to be a duplicate.
