### ISSUE TITLE
TypeError: '<' not supported between instances of 'TorchVersion' and 'Version'

### ISSUE THREAD

**Issue by jamesnogra** [huggingface/diffusers#7341]
### Describe the bug

My Google Colab code for training a stable diffusion works for many months until now, this is the error trace:
- `15 from diffusers import DDPMScheduler`
- `3 from .configuration_utils import ConfigMixin`
- `34 from .utils import DIFFUSERS_CACHE, HUGGINGFACE_CO_RESOLVE_ENDPOINT, DummyObject, deprec`
```
from .import_utils import (                                                                │
│    23 │   ENV_VARS_TRUE_AND_AUTO_VALUES,                                                         │
│    24 │   ENV_VARS_TRUE_VALUES,                                                                  │
│    25 │   USE_JAX,
```
- `207 │   │   if torch.__version__ < version.Version("1.12"):`
- Then this is the error `TypeError: '<' not supported between instances of 'TorchVersion' and 'Version'`

### Reproduction

```
!pip install -U git+https://github.com/huggingface/diffusers
from diffusers import DDPMScheduler
```

### System Info

Python 3.10 in Google Colab

### Who can help?

@yiyixuxu @saya

**Comment by standardAI** [comment]
I am unable to reproduce the error. Could you look at [that](https://colab.research.google.com/gist/standardAI/0d63a0dc85c5d7918d2853e704e1d80e/-7341.ipynb)? Besides, I couldn't find `if torch.__version__ < version.Version("1.12"):` line in `diffusers`'s codebase.

**Comment by jamesnogra** [comment]
> I am unable to reproduce the error. Could you look at [that](https://colab.research.google.com/gist/standardAI/0d63a0dc85c5d7918d2853e704e1d80e/-7341.ipynb)? Besides, I couldn't find `if torch.__version__ < version.Version("1.12"):` line in `diffusers`'s codebase; but other "`diffusers`" in GitHub have that 🤔.

Thanks for the example. I just saw my code was `pip install -r requirements.txt` and the diffusers, torch, and transformers have specified their incorrect not matching versions.
