### ISSUE TITLE
Cannot initialize Controlnet from a Unet with lora

### ISSUE THREAD

**Issue by Luciennnnnnn** [huggingface/diffusers#7350]
### Describe the bug

I encounter errors when initialize controlnet's parameters from unet, since incompatible parameter keys, for example:

Missing key(s): 0.attentions.0.proj_in.weight ...
Unexpected key(s) in state_dict: "0.attentions.0.proj_in.base_layer.weight", "0.attentions.0.proj_in.base_layer.bias", "0.attentions.0.proj_in.lora_A.default_0.weight", "0.attentions.0.proj_in.lora_B.default_0.weight" ...

How to transform this lora based Unet into a naive pytorch model? Or is there any better method loading unet lora?

### Reproduction

```python
unet = UNet2DConditionModel.from_pretrained('runwayml/stable-diffusion-v1-5')
pipe = AutoPipelineForText2Image.from_pretrained(args.model.pretrained_model_name_or_path)
pipe.unet = unet

# load and fuse lcm lora
pipe.load_lora_weights(args.model.lora_model_name_or_path, weight_name=args.model.lora_weight_name, local_files_only=args.model.local_files_only)
pipe.fuse_lora()

del pipe

controlnet = ControlNetModel.from_unet(unet)
```

### System Info

- `diffusers` version: 0.26.3
- Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
- Python version: 3.10.11
- PyTorch version (GPU?): 2.1.1+cu118 (True)
- Huggingface_hub version: 0.20.2
- Transformers version: 4.37.2
- Accelerate version: 0.23.0
- xFormers version: 0.0.23+cu118
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: Yes

### Who can help?

@sayakpaul @yiyixuxu @DN6

**Comment by sayakpaul** [comment]
You should fuse it first.

**Comment by Luciennnnnnn** [comment]
@sayakpaul I have fused it, see `pipe.fuse_lora() ` in my code.

**Comment by UmerHA** [comment]
@sayakpaul This is indeed a bug. 

Using loras replaces the layers (eg `torch.nn.modules.conv.Conv2d`) with lora versions of that layer (eg `peft.tuners.lora.layer.Conv2d`) that has a different structure, even after fusing. To access the original layer, we need to access `my_lora_conv2d.base_layer`.

Code to reproduce:
```python
from diffusers import AutoPipelineForText2Image

pipe1 = AutoPipelineForText2Image.from_pretrained('stabilityai/stable-diffusion-xl-base-1.0')
pipe2 = AutoPipelineForText2Image.from_pretrained('stabilityai/stable-diffusion-xl-base-1.0')

# in pipe1: load lora and fuse it
pipe1.load_lora_weights('latent-consistency/lcm-lora-sdxl')
pipe1.fuse_lora()

conv1 = pipe1.unet.down_blocks[0].resnets[0].conv1
conv2 = pipe2.unet.down_blocks[0].resnets[0].conv1

print(type(conv1), type(conv2))  # different types

conv2.load_state_dict(conv1.state_dict())  # doesn't work
```

I think users expect that after fusing the regular layers are in the model, instead of the lora layers. If you want, I'd be happy to implement a PR.

**Comment by sayakpaul** [comment]
```python
from diffusers import ControlNetModel, DiffusionPipeline

from diffusers import DiffusionPipeline
import torch

pipeline = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0")
pipeline.load_lora_weights(
    "lordjia/by-feng-zikai", weight_name="fengzikai_v1.0_XL.safetensors", adapter_name="feng"
)

pipeline.fuse_lora(adapter_names="feng", lora_scale=1.0)
pipeline.unload_lora_weights() # very important

controlnet_from_lora_unet = ControlNetModel.from_unet(pipeline.unet)
```

^ should work. 

Colab Notebook: https://colab.research.google.com/gist/sayakpaul/d5c5cf576d6e003ec907e9df695ca222/scratchpad.ipynb
