### ISSUE TITLE
Safety Checker for stable_diffusion_xl

### ISSUE THREAD

**Issue by mantrakp04** [huggingface/diffusers#7363]
**Is your feature request related to a problem? Please describe.**
Yes, cannot use safety checker with stable diffusion xl directly inside pipeline

**Describe the solution you'd like.**
Ability to use safety checker directly inside pipeline

**Describe alternatives you've considered.**
Just running the image through safety checker manually by creating a new function

**Additional context.**
https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines/stable_diffusion_xl

**Comment by sayakpaul** [comment]
You can easily do so yourself from your application by referring to how safety checking is done in the SD pipeline:

https://github.com/huggingface/diffusers/blob/4330a747d457ff2af1ba89e94c57a6e19efffdb9/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L1016
