### ISSUE TITLE
train controlnet sdxl with playground v2.5

### ISSUE THREAD

**Issue by universewill** [huggingface/diffusers#7383]
I try to train controlnet sdxl with playground v2.5. I saw the loss is smaller  as training is on. But the validation image is ok at first few steps, but as the training is going on,  the validation result images become full of noise like below. How to solve it?

I use the train_controlnet_sdxl.py to train and modify the scheduler in log validation  function to EDMDPMSolverMultistepScheduler (The result is black image if not modified). I also change vae to [madebyollin/sdxl-vae-fp16-fix as the [https://github.com/huggingface/diffusers/blob/main/examples/controlnet/README_sdxl.md#notes](url)

![validation_2449_2b04e52c1e42cdb25f70](https://github.com/huggingface/diffusers/assets/6790730/53c4ba6d-9674-4e0e-ae23-08209f23919e)

Anyone can help here?
@haofanwang @patil-suraj @yiyixuxu

**Comment by sayakpaul** [comment]
You would want to open a discussion for this. Please transfer this to Discussions. 

The VAE you're using shouldn't be used with the Playground model because it wasn't trained with that VAE.

**Comment by universewill** [comment]
> You would want to open a discussion for this. Please transfer this to Discussions.
> 
> The VAE you're using shouldn't be used with the Playground model because it wasn't trained with that VAE.

Thanks for reply. I opened  a discussion for this. Link:https://github.com/huggingface/diffusers/discussions/7391

I also tried not using the madebyollin/sdxl-vae-fp16-fix, and the validation image results turned out to be blank black images.
