### ISSUE TITLE
Is the code for Frame Interpolation in SVD open source?I can't find it.

### ISSUE THREAD

**Issue by jufeif** [huggingface/diffusers#7387]

**Comment by sayakpaul** [comment]
This should live in this repository as an issue.

**Comment by jufeif** [comment]
> This should live in this repository as an issue.

So this code isn't open source?

**Comment by sayakpaul** [comment]
SVD is a Stability AI model. You should likely open this issue on their repository.

**Comment by jufeif** [comment]
> SVD is a Stability AI model. You should likely open this issue on their repository.

Thank you for your reply.
