### ISSUE TITLE
How can I train SDXL with multiple aspect ratio images????

### ISSUE THREAD

**Issue by lawsonxwl** [huggingface/diffusers#7392]
**Is your feature request related to a problem? Please describe.**
When training SDXL, multiple aspect ratio images are needed, e.g 1024x1024, 832x1152...  how can I collect the images with same size in the same batch?

**Describe the solution you'd like.**
Plz update the sdxl training script, maybe modifying collate function to make it compatible with multi aspect ratio training.

**Comment by CrazyBoyM** [comment]
may be you need sd-scripts: https://github.com/kohya-ss/sd-scripts

**Comment by lawsonxwl** [comment]
> may be you need sd-scripts: https://github.com/kohya-ss/sd-scripts

thanks a lot, but how can we integrate this into diffusers?

**Comment by CrazyBoyM** [comment]
hh.&nbsp;it&nbsp;is&nbsp;a&nbsp;great&nbsp;idea,&nbsp;but&nbsp;I&nbsp;don't&nbsp;have&nbsp;time&nbsp;to&nbsp;do&nbsp;this,&nbsp;maybe&nbsp;anyone&nbsp;else？


---Original---
From: ***@***.***&gt;
Date: Tue, Mar 19, 2024 23:18 PM
To: ***@***.***&gt;;
Cc: &quot;Ke ***@***.******@***.***&gt;;
Subject: Re: [huggingface/diffusers] How can I train SDXL with multiple aspectratio images???? (Issue #7392)




  
may be you need sd-scripts: https://github.com/kohya-ss/sd-scripts
  
thanks a lot, but how can we integrate this into diffusers?
 
&mdash;

**Comment by sayakpaul** [comment]
Our training scripts don't incorporate aspect ratio bucketing purposefully because it makes them a little complicated. So, you will have to repurpose existing implementations here. 

https://github.com/bghira/SimpleTuner/ is a nice repository from @bghira that implements the feature already in a clean manner.
