### ISSUE TITLE
A problem regarding stable video diffusion, with inference results yielding black images

### ISSUE THREAD

**Issue by DoloresChong** [huggingface/diffusers#7400]
### Describe the bug

I encountered an issue with inference in stable video diffusion. When I attempted to perform inference using the sample code, it indicated insufficient VRAM (video random access memory). Subsequently, I reduced the width and height of the output size, which resulted in the inference process running quickly. However, every frame image I obtained turned out to be black. I'm unsure about the reason behind this issue.

Sample code:

python
Copy code
pipeline = StableVideoDiffusionPipeline.from_pretrained(
    "stabilityai/stable-video-diffusion-img2vid", torch_dtype=torch.float16, variant="fp16"
)
pipeline.enable_model_cpu_offload()
img = Image.open(r"genner_img\2024-03-11\23-09-10.jpg")

frames = pipeline(img, decode_chunk_size=1, generator=generator, output_type='np', height=256, width=256).frames[0]

export_to_video(frames, "generated.mp4", fps=7)
```"

### Reproduction

pipeline = StableVideoDiffusionPipeline.from_pretrained(
    "stabilityai/stable-video-diffusion-img2vid", torch_dtype=torch.float16, variant="fp16"
)
pipeline.enable_model_cpu_offload()
img = Image.open(r"genner_img\2024-03-11\23-09-10.jpg")

frames = pipeline(img, decode_chunk_size=1, generator=generator, output_type='np', height=256, width=256).frames[0]

export_to_video(frames, "generated.mp4", fps=7)

### Logs

```shell
no
```

### System Info

py-3.10，torch-cuda1.13

### Who can help?

@up_the_irons text2video

**Comment by sayakpaul** [comment]
Does the same happen when you switch to a more recent version of PyTorch?

Cc: @patil-suraj @DN6

**Comment by DoloresChong** [comment]
> Does the same happen when you switch to a more recent version of PyTorch?
> 
> Cc: @patil-suraj @DN6

So, you're suggesting that the issue might be due to my PyTorch version, right? I feel like version 1.13 should be sufficient because I haven't had any problems generating single images with it. Nonetheless, I've decided to try the method you mentioned. Thank you very much

**Comment by rafationgson** [comment]
Was the issue fixed by updating the pytorch versions? I am also encountering the same issue with the same code but using `cerspense/zeroscope_v2_576w` and TextToVideoSDPipeline. Pytorch version is 2.2.1 and python version is 3.11.1.

**Comment by sayakpaul** [comment]
Repinging @DN6

**Comment by DoloresChong** [comment]
> Was the issue fixed by updating the pytorch versions? I am also encountering the same issue with the same code but using `cerspense/zeroscope_v2_576w` and TextToVideoSDPipeline. Pytorch version is 2.2.1 and python version is 3.11.1.

I have already resolved this issue, and it was not due to the version of PyTorch but rather the data format of the model. You can refer to this link for the solution approach： https://github.com/huggingface/diffusers/discussions/7399
