### ISSUE TITLE
Will support layer diffusion in diffusers?

### ISSUE THREAD

**Issue by kelisiya** [huggingface/diffusers#7428]
https://github.com/huchenlei/ComfyUI-layerdiffuse

**Comment by asomoza** [comment]
Supposedly the original authors are working on it with the highest priority:

![image](https://github.com/huggingface/diffusers/assets/5442875/c0abac29-dd51-4631-8616-44c9ea294a6f)

https://github.com/layerdiffusion/LayerDiffuse
