### ISSUE TITLE
XPU loading completed, no progress in generation

### ISSUE THREAD

**Issue by 823863429** [huggingface/diffusers#7438]
### Describe the bug

I have an Inter ARC GPU. After loading the model to the xpu, there is no progress during generation. Please help me.

           

### Reproduction

import torch
import intel_extension_for_pytorch as ipex
from diffusers import LCMScheduler, AutoPipelineForText2Image, ControlNetModel
controlnet = ControlNetModel.from_pretrained(controlnet_id, torch_dtype=torch.float16)
stable_diffusion_txt2img = AutoPipelineForText2Image.from_pretrained(
  model_id, 
  torch_dtype=torch.float16, 
  safety_checker = None,
  requires_safety_checker = False
).to("xpu")
image = pipe(prompt=prompt, negative_prompt=negative_prompt ,width=512, height=512, num_inference_steps=8, strength=1, guidance_scale=0).images[0]

### System Info

Name: torch
Version: 2.1.0a0+cxx11.abi
CPU：Intel(R) Core(TM) Ultra 5 125H
GPU 0：
Intel(R) Arc(TM) Graphics

Driver version: 31.0.101.5008
Driver date: 2023/11/23
DirectX version: 12 (FL 12.1)
Physical location: PCI bus 0, device 2, function 0

Utilization rate 4%
Dedicated GPU memory
Shared GPU memory 5.8/15.8 GB
GPU memory 5.8/15.8 GB

**Comment by standardAI** [comment]
Hi, @823863429. Could you translate all the post into English?

**Comment by 823863429** [comment]
> Hi, @823863429. Could you translate all the post into English?

yes，has updated

**Comment by Disty0** [comment]
`CPU：Intel(R) Core(TM) Ultra 5 125H`
Are you using iGPU? iGPUs have no official AoT builds for IPEX right now.

**Comment by sayakpaul** [comment]
Closing this because of inacivity.
