### ISSUE TITLE
Pokemon dataset no longer available for text-to-image

### ISSUE THREAD

**Issue by ssarkar2** [huggingface/diffusers#7440]
### Describe the bug

The text to image Readme uses the pokemon dataset to finetune :
https://github.com/huggingface/diffusers/tree/main/examples/text_to_image#pokemon-example

However this dataset is no longer available:
https://huggingface.co/datasets/lambdalabs/pokemon-blip-captions

### Reproduction

from datasets import load_dataset
dataset = load_dataset("lambdalabs/pokemon-blip-captions", None)

### System Info

datasets                    2.18.0

### Who can help?

@sayakpaul , Can we change the dataset in the readme to something thats available

**Comment by sayakpaul** [comment]
It's not a library issue. Please consider opening Discussions for this.
