### ISSUE TITLE
LORA support

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [huggingface/diffusers#7454]
**Is your feature request related to a problem? Please describe.**
I'm trying to use LORA models from civitai and met the following issues:
- there are two ways to load weights: pipe.load_lora_weights and the conversion script in `/scripts`
- some LORAs bug out on loading (with both ways), some load fine
- for the ones that loaded fine, some produce similar results to the model page, some don't

**Describe the solution you'd like.**

Could we have a clear specification on what LORAs will work seamlessly on diffusers (with which loading method)? ideally a method in a pipeline such as:

```python

def is_lora_supported(path_or_state_dict) -> bool:
    ...
```

Thanks!

**Comment by sayakpaul** [comment]
We cannot. When supporting non-diffusers state dicts, we rely a lot on their internal structures to infer how to appropriately convert them. There's no golden rule to doing that. Hence, we cannot have a clear specification of the supported LoRAs. So, if you face issues, best bet is to just open an issue on the repository and we can take it from there.
