### ISSUE TITLE
Missing raise statement

### ISSUE THREAD

**Issue by TonyLianLong** [huggingface/diffusers#7456]
### Describe the bug

https://github.com/huggingface/diffusers/blob/363699044e365ef977a7646b500402fa585e1b6b/src/diffusers/pipelines/stable_diffusion_gligen/pipeline_stable_diffusion_gligen.py#L471-L475

### Reproduction

There seems to be a missing raise statement in the gligen code (the `ValueError` is not raised). I can help fix that. @yiyi

### System Info

This is still in the main branch.

**Comment by standardAI** [comment]
Good catch! I searched in the repo and found [another one](https://github.com/huggingface/diffusers/blob/363699044e365ef977a7646b500402fa585e1b6b/examples/community/llm_grounded_diffusion.py#L533). Could you add this to the PR as well if it is confirmed?

**Comment by sayakpaul** [comment]
Sure. Happy to review PRs.

**Comment by TonyLianLong** [comment]
Created a PR #7473.
