### ISSUE TITLE
[Pipeline] Champ: Controllable and Consistent Human Image Animation with 3D Parametric Guidance

### ISSUE THREAD

**Issue by a-r-r-o-w** [huggingface/diffusers#7462]
### Model/Pipeline/Scheduler description

Opening this issue for sharing the news but it should already be widely covered across social media or will be soon. The authors compare performance against the mythical [AnimateAnyone](https://github.com/HumanAIGC/AnimateAnyone) with 13k+ stars and 900 forks but no code, and show they are much superior in terms of generation quality. Very cool work and absolutely mind-blowing quality.

They already provide a diffusers-based implementation so there's nothing to add here I believe. Maybe one good idea would be to maintain a community README with list of great research repositories that utilize diffusers and provide ready to use pipelines for exploration. WDYT @yiyixuxu @sayakpaul?

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

Paper: https://arxiv.org/abs/2403.14781
Code: https://github.com/fudan-generative-vision/champ
Project Page: https://fudan-generative-vision.github.io/champ/#/
Authors: @ShenhaoZhu [Junming Leo Chen*](https://github.com/Leoooo333), [Zuozhuo Dai](https://github.com/daizuozhuo), [Yinghui Xu](https://ai3.fudan.edu.cn/info/1088/1266.htm), [Xun Cao](https://cite.nju.edu.cn/People/Faculty/20190621/i5054.html), [Yao Yao](https://yoyo000.github.io/), [Hao Zhu](http://zhuhao.cc/home/), [Siyu Zhu](https://sites.google.com/site/zhusiyucs/home)

**Comment by sayakpaul** [comment]
Thanks for notifying. 

We have a way to fetch the repositories depending on `diffusers`. :-)

**Comment by sayakpaul** [comment]
Closing because of inactivities.
