### ISSUE TITLE
pretrained_model_or_path variable name in AutoPipeline

### ISSUE THREAD

**Issue by PhilippeNguyen** [huggingface/diffusers#7469]
### Describe the bug

In DiffusionPipeline.from_pretrained() the first parameter is called `pretrained_model_name_or_path` whereas in the Autopipelines, it is called `pretrained_model_or_path` (despite the class docs calling it `pretrained_model_name_or_path`  here too).

Don't know if this was intended, just a bit of a minor issue when trying to instantiate the pipelines with kwargs

### Reproduction

N/A

### System Info

N/A

### Who can help?

@stevhliu

**Comment by yiyixuxu** [comment]
Hi!
feel free to open a PR
