### ISSUE TITLE
Repository Not Found for url: https://huggingface.co/api/models/t2iadapter-model.

### ISSUE THREAD

**Issue by Shuvo001** [huggingface/diffusers#7492]
### Describe the bug

when i am trying to run "train_t2i_adapter_sdxl.py", it's showing Repository Not Found for url : [](https://huggingface.co/api/models/t2iadapter-model). 
I have already logged in on HF and use Token as well.
Here is the HF error:

![train_t2i_adapter_sdxl py - diffusers  SSH_ 4090  - Visual Studio Code 3_27_2024 7_31_22 PM](https://github.com/huggingface/diffusers/assets/61898803/5083aa53-f3da-4c5c-a438-3d2c1072e9d7)

**and Here is my running script:**
`export MODEL_DIR="stabilityai/stable-diffusion-xl-base-1.0"
export OUTPUT_DIR="t2iadapter-model"

accelerate launch train_t2i_adapter_sdxl.py \
 --pretrained_model_name_or_path=$MODEL_DIR \
 --output_dir=$OUTPUT_DIR \
 --dataset_name=fusing/fill50k \
 --mixed_precision="fp16" \
 --resolution=1024 \
 --learning_rate=1e-5 \
 --max_train_steps=15000 \
 --validation_image "./conditioning_image_1.png" "./conditioning_image_2.png" \
 --validation_prompt "red circle with blue background" "cyan circle with brown floral background" \
 --validation_steps=100 \
 --train_batch_size=1 \
 --gradient_accumulation_steps=4 \
 --report_to="wandb" \
 --seed=42 \
 --push_to_hub`

### Reproduction

`# Handle the repository creation
    if accelerator.is_main_process:
        if args.output_dir is not None:
            os.makedirs(args.output_dir, exist_ok=True)

        if args.push_to_hub:
            repo_id = create_repo(
                repo_id=args.hub_model_id or Path(args.output_dir).name,
                exist_ok=True,
                token=args.hub_token,
                private=True,
            ).repo_id

    # Load the tokenizers
    tokenizer_one = AutoTokenizer.from_pretrained(
        args.pretrained_model_name_or_path,
        subfolder="tokenizer",
        revision=args.revision,
        use_fast=False,
    )
    tokenizer_two = AutoTokenizer.from_pretrained(
        args.pretrained_model_name_or_path,
        subfolder="tokenizer_2",
        revision=args.revision,
        use_fast=False,
    )`

### Logs

```shell
Traceback (most recent call last):
  File "/home/shuvo/.conda/envs/control/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/shuvo/.conda/envs/control/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/shuvo/.conda/envs/control/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "/home/shuvo/.conda/envs/control/lib/python3.10/site-packages/accelerate/commands/launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/shuvo/.conda/envs/control/bin/python', 'train_t2i_adapter_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--output_dir=t2iadapter-model', '--dataset_name=fusing/fill50k', '--mixed_precision=fp16', '--resolution=1024', '--learning_rate=1e-5', '--max_train_steps=15000', '--validation_image', './conditioning_image_1.png', './conditioning_image_2.png', '--validation_prompt', 'red circle with blue background', 'cyan circle with brown floral background', '--validation_steps=100', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--report_to=wandb', '--seed=42', '--push_to_hub']' returned non-zero exit status 1.
```

### System Info

- diffusers version: 0.28.0
- Platform: Linux Ubuntu 22.04
- Python version: 3.10.0
- PyTorch version (GPU): 2.2.0
- Huggingface_hub version: 0.22.1
- Transformers version: 4.39.1
- Accelerate version: 0.28.0
- Using distributed or parallel set-up in script?: No

### Who can help?

@sayakpaul @yiyixuxu @DN6

**Comment by Shuvo001** [comment]
Okay i was able to solve the problem by changing export OUTPUT_DIR="t2iadapter-model"  to export OUTPUT_DIR="temp"

**Comment by standardAI** [comment]
Hi @Shuvo001,
Could I ask if, is there a possibility that you gave a read access token rather than a write access one?

**Comment by sayakpaul** [comment]
You must use a token with write access to the repository you're creating.

**Comment by Shuvo001** [comment]
@standardAI @sayakpaul Thank you so so much for your quick response! it's working now.
