### ISSUE TITLE
cross_attention_kwargs ['scale'] are not expected by XFormersAttnProcessor and will be ignored.

### ISSUE THREAD

**Issue by wb315** [huggingface/diffusers#7519]
### Describe the bug

when i want to inference the trainde model, i use the "scale" params in cross_attention_kwargs, there has the info as "cross_attention_kwargs ['scale'] are not expected by XFormersAttnProcessor and will be ignored."。
I what to konw the "scale" is effective ?
Looking forward to your reply！

### Reproduction

```
model_path = "sd-pokemon-model-lora-sdxl" 
pipe.load_lora_weights(model_path)
prompt = "Charmander from Pokémon is playing in the swimming pool."
image = pipe(prompt, num_inference_steps=30, guidance_scale=7.5, cross_attention_kwargs={"scale":0.5}).images[0]
```

### Logs

![1711709772063](https://github.com/huggingface/diffusers/assets/39976683/7a068d32-e53a-47c9-9452-9c80ccd27f01)

### System Info

diffusers==0.27.0.dev0
xformers==0.0.24+cu118
torch==2.2.0+cu118
torchvision==0.17.0+cu118

**Comment by standardAI** [comment]
Hi @wb315,
Could you examine [this doc page for loras](https://huggingface.co/docs/diffusers/main/en/using-diffusers/merge_loras#fuselora).

**Comment by sayakpaul** [comment]
It's not a bug. `peft` takes care of scale already.

**Comment by YuzhiChen001** [comment]
> ### Describe the bug
> when i want to inference the trainde model, i use the "scale" params in cross_attention_kwargs, there has the info as "cross_attention_kwargs ['scale'] are not expected by XFormersAttnProcessor and will be ignored."。 I what to konw the "scale" is effective ? Looking forward to your reply！
> 
> ### Reproduction
> ```
> model_path = "sd-pokemon-model-lora-sdxl" 
> pipe.load_lora_weights(model_path)
> prompt = "Charmander from Pokémon is playing in the swimming pool."
> image = pipe(prompt, num_inference_steps=30, guidance_scale=7.5, cross_attention_kwargs={"scale":0.5}).images[0]
> ```
> 
> ### Logs
> ![1711709772063](https://private-user-images.githubusercontent.com/39976683/318035434-7a068d32-e53a-47c9-9452-9c80ccd27f01.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMjUyNDksIm5iZiI6MTcxNTAyNDk0OSwicGF0aCI6Ii8zOTk3NjY4My8zMTgwMzU0MzQtN2EwNjhkMzItZTUzYS00N2M5LTk0NTItOWM4MGNjZDI3ZjAxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE5NDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYzM3OGQ5Y2E0ODYyMDc0NDU3ZmUwM2ZkMjU3ZTE3NThkMDZiYjA2OWU2MzM3N2E0YWRlZDc2M2IzY2IzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MumWVtuUu3G-ws9LiludW9nWSoQn8KeXLn9YNxW2Nug)
> 
> ### System Info
> diffusers==0.27.0.dev0 xformers==0.0.24+cu118 torch==2.2.0+cu118 torchvision==0.17.0+cu118
> 
> ### Who can help?
> _No response_

Have you solved this problem?
