### ISSUE TITLE
move MarigoldPipeline to core 

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#7522]
### Model/Pipeline/Scheduler description

[Marigold depth pipeline](https://github.com/huggingface/diffusers/blob/main/examples/community/marigold_depth_estimation.py) is one of our most highly used community pipeline (it already has 40k downloads on the hub) - we are going to integrate it into core upon popular demand  

Does anyone in the community like to take a stab at this? It is already a community pipeline, so we do not need to convert weights. however, we may need to refactor it so that the implementation follows the diffusers' design philosophy and that the codes are highly readable and easy to tweak. You can read about philosophy here https://huggingface.co/docs/diffusers/en/conceptual/philosophy

Of course, it will be an iterative process! You can start the PR by moving the pipeline code into a folder under `src,` and tagging diffusers maintainers for an initial review

### Provide useful links for the implementation
community pipeline: https://github.com/huggingface/diffusers/blob/main/examples/community/marigold_depth_estimation.py)

original issue: https://github.com/huggingface/diffusers/issues/6533

**Comment by standardAI** [comment]
Hi @yiyixuxu! I am willing to take this one!

**Comment by toshas** [comment]
@markkua and I would like to help shape the way Marigold is integrated. We need to discuss this internally and with you to plan this design carefully and enable the pipeline's extensibility to other modalities (which are brewing). In the meantime, can @yiyixuxu please point us to a PR for a community pipeline promotion to the core so we can use it as a reference? Particularly, I'm curious to see how core philosophy is maintained (1) to balance modularity vs ensuring the quality of operation in a default setting and (2) automated test suite, if any

**Comment by markkua** [comment]
A PR [#7524](https://github.com/huggingface/diffusers/pull/7524) to the community pipeline is just created for some small updates. Please also take this update into consideration.

**Comment by yiyixuxu** [comment]
hey @toshas and @markkua 
For 'MarigoldPipeline`, it seems like it will be pretty straightforward, so it will not require any drastic changes. If no one from the community picks this up, I will work on it. We will definitely ask you to review it. 

we don't have an example of community pipeline -> official pipeline that can serve as a good reference. Marigold might very likely be the first to come from the community! two other community pipelines are being moved to official pipelines, feel free to take a look at the PRs; they are both more challenging than MarigoldPipeline: face-id requires a different design when integrated into core; and ControlNet-XS, the original implementation deviates a lot from our style so a lot of works need to be done to refactor it

face-id: https://github.com/huggingface/diffusers/pull/7186
controlnet-xs: https://github.com/huggingface/diffusers/pull/6772

**Comment by yiyixuxu** [comment]
> We need to discuss this internally and with you to plan this design carefully and enable the pipeline's extensibility to other modalities (which are brewing)

do we have a channel with you on slack?

**Comment by toshas** [comment]
> do we have a channel with you on slack?

Yes, `hf-marigold-colab`, I asked to add you there

**Comment by standardAI** [comment]
If no one from the community picks this up within 2 days, I'd like to work on it.

**Comment by standardAI** [comment]
If no one from the community picks this up within 2 days, I'd like to work on it.

**Comment by standardAI** [comment]
I'd like to work on it if you approve.

**Comment by yiyixuxu** [comment]
@standardAI of course!
