### ISSUE TITLE
Discrete sceduler

### ISSUE THREAD

**Issue by Abc11c** [huggingface/diffusers#7525]
### Model/Pipeline/Scheduler description

Hi, I was looking into the paper, [D3PM](https://openreview.net/forum?id=h7-XixPCAL) was wondering which scheduler to choose from particularly my problem deals with discrete action space and will be using Cross entropy to predictions and target

jax implementation of the same [here](https://github.com/google-research/google-research/blob/master/d3pm/images/diffusion_categorical.py)

Currently just using DDPMScheduler, works ok but I want to see if the marginal/ uniform schedulers as seen [here](https://github.com/cvignac/DiGress/blob/main/src/diffusion/noise_schedule.py) give me a improvement 

I see there is a bunch of solutions [here ](https://github.com/huggingface/diffusers/tree/main/src/diffusers/schedulers)

Any suggestions? or solutions for me to look into. 

Thanks!

### Open source status

- [ ] The model implementation is available.
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/google-research/google-research/blob/master/d3pm/images/diffusion_categorical.py

**Comment by yiyixuxu** [comment]
closing this now:)
feel free to ask on the discussion section
