### ISSUE TITLE
Potential UNet EMA bug in `train_text_to_image_sdxl`

### ISSUE THREAD

**Issue by christopher-beckham** [huggingface/diffusers#7549]
### Describe the bug

Hi, 

Am I seeing a bug here? https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py#L1198-L1201

At the end of each epoch we perform a validation step which involves having `ema_unet` store `unet`'s params temporarily, and then loading `ema_unet`'s params into `unet` since the latter is what is used in the `pipeline` class to perform validation. However, when that is done there is no call to `ema_unet.restore(unet.parameters())` in order to restore the original UNet's parameters. I would have expected that method call to be made at the end of this if block: 

https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py#L1192-L1253

Does that sound about right?

Thanks,
Chris

### Reproduction

N/A

### Logs

```shell
N/A
```

### System Info

N/A (reading off Github code here)

**Comment by bghira** [comment]
i don't think this is a bug, but it might be undocumented/unexpected behaviour.

the whole time, the validations are done on the EMA weights. but at the end, the `save_pretrained` is run after setting it up so that the unet is the EMA weights.

the way this trainer functions, the non-EMA weights are thrown away at the end - they could be placed as an 'ema' variant, but that would increase complexity a bit.

**Comment by christopher-beckham** [comment]
Hi,

> the whole time, the validations are done on the EMA weights.

Yes, which is fine, but unless I'm misreading the code here, the validation is done _per epoch_ (i.e. each time the data loader has been exhausted). Therefore, in the next epoch, the UNet still has EMA weights applied to it when it should have been restored to its original weights.

As for the final validation:

https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py#L1256-L1305

 there is also a `ema_unet.copy_to(unet.parameters())` call which is completely fine, because as you said, the non-EMA weights are going to be discarded when training terminates.

**Comment by bghira** [comment]
oh, i see what you mean now. i'm sorry, i thought we were looking only at the final validations. that does indeed appear to be an issue. would you like to fix it?

**Comment by christopher-beckham** [comment]
Yep I'll write one up
