### ISSUE TITLE
When will you release your preprocessed dataset?

### ISSUE THREAD

**Issue by thucz** [huggingface/diffusers#7554]
in `bidiff_if_objaverse.yaml`, 

- root: './dataset/objaverse_dep_512'
- extra_view_root: './dataset/objaverse_dep_512_extra'
- prompt_file: './data/objaverse_32k/Cap3D_automated_Objaverse.csv'
- pre_prompt_embed_cache: './dataset/embed/embed_obj_cap3d'
- latent_root: './dataset/latents'
- sdf_root: './dataset/objaverse_sdf'
- voxel_root: './dataset/voxel_data_objaverse'
- mesh_npy_root: './dataset/objaverse_npy' # accelerate data loading (optional)
- color_grid_root: './dataset/objaverse_color_grids'
 
These items are missing. Could you also provide these data items and preprocessing scripts?

**Comment by DN6** [comment]
Don't think this is related to this repo?

**Comment by thucz** [comment]
Sorry!
