### ISSUE TITLE
ValueError: The deprecation tuple ('tensor_format' ...

### ISSUE THREAD

**Issue by WASasquatch** [huggingface/diffusers#756]
### Describe the bug

I am getting the following error

```
ValueError: The deprecation tuple ('tensor_format', '0.5.0', "If you're running your code in PyTorch, you can safely remove this argument.") should be removed since diffusers' version 0.5.0.dev0 is >= 0.5.0
```

When running diffusers

What does this even mean? And why wasn't there a deprecation period warning of its usage before it's arbitrarily (on users end) removed? It's breaking my whole system, and 'tesnfor_format' isn't even named in my code or the stacktrace. 

### Reproduction

Not sure where to start, don't know what "tensor_format" is, it's not named in the code anywhere, or in the stack trace within diffusers repo.  

### System Info

- `diffusers` version: 0.5.0.dev0
- Platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.14
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Huggingface_hub version: 0.10.0
- Transformers version: 4.22.2
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Not sure what colab is doing

**Comment by pcuenca** [comment]
Hello! I believe you must be running the `main` branch of the repo, is that correct? We just released version `0.4.0`, which should work fine. `main` just became `0.5.0.dev0`, hence the deprecation error.

You can install it using `pip` for now:
```
pip uninstall diffusers
pip install diffusers
```

Nevertheless, we'll review these deprecations to try to make `main` work. Would you mind sharing a link to the Colab you are using, if possible?

**Comment by pcuenca** [comment]
The released version does have negative prompts and everything else that was in main as of 5 hours ago, so it should work.

Could you please try to install it to verify?

(And actually, `main` should still be `0.4.1.dev0`, so it should work. We'll investigate what might have gone wrong).

**Comment by WASasquatch** [comment]
Oh really? I was install via

**dev** (for concepts)
`!pip3 install -qq diffusers["training"] transformers ftfy`  (for some reason `diffusers["training"]` doesn't work with subprocess command. :(

**main** (public)
`subprocess.run(['pip', '-q', 'install', '-U', 'git+https://github.com/huggingface/diffusers.git'], stdout=subprocess.PIPE).stdout.decode('utf-8')`

but both seem to be checking out 0.5.0 as main has same issue.

**Comment by anton-l** [comment]
The main branch is now back to `0.4.1.dev0`, sorry for the errors!

**Comment by WASasquatch** [comment]
> The main branch is now back to `0.4.1.dev0` without the deprecations, sorry for the errors!

Awesome, I just noticed, though I'm getting a strange error where the StableDiffusionPipeline is telling me it requires the transformers library. But it's installed, and verified with pip freeze and importing... o.O

**Comment by WASasquatch** [comment]
I am still wondering, though what is  'tensor_format', where is this error coming from? How can I "safely" remove it, if it's not actually being referenced anywhere?

**Comment by patrickvonplaten** [comment]
Essentially, we're just removing the `set_format` function since it was a no-op.
