### ISSUE TITLE
from_single_file use local_files_only=True got Error: "HeaderTooLarge"

### ISSUE THREAD

**Issue by SSLemon** [huggingface/diffusers#7591]
@asomoza 
Hi there, I follow you example to made mine:
```
from diffusers import StableDiffusionXLPipeline
from transformers import CLIPTextModel, CLIPTextModelWithProjection
import torch


text_encoder = CLIPTextModel.from_pretrained(
    "model/stabilityai/stable-diffusion-xl-base-1.0/text_encoder",
    variant="fp16",
    torch_dtype=torch.float16,
    local_files_only=True,
)

text_encoder_2 = CLIPTextModelWithProjection.from_pretrained(
    "model/stabilityai/stable-diffusion-xl-base-1.0/text_encoder_2",
    variant="fp16",
    torch_dtype=torch.float16,
    local_files_only=True,
)

pipeline_text2image = StableDiffusionXLPipeline.from_single_file(
    "model/stabilityai/stable-diffusion-xl-base-1.0/sd_xl_base_1.0.safetensors", 
    original_config_file='model/stabilityai/stable-diffusion-xl-base-1.0/sd_xl_base.yaml',
    local_files_only=True, 
    torch_dtype=torch.float16, 
    variant="fp16", 
    use_safetensors=True,
    add_watermarker=False,
    text_encoder=text_encoder,
    text_encoder_2=text_encoder_2, 
).to("cuda")

prompt = "Astronaut in a jungle, cold color palette, muted colors, detailed"

pipeline_text2image(prompt=prompt).images[0].save('output.png')
```

but I got this error:
`Traceback (most recent call last):
  File "../python/mysdxl/text2img.py", line 6, in <module>
    text_encoder = CLIPTextModel.from_pretrained(
  File "../.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3310, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge`

_Originally posted by @SSLemon in https://github.com/huggingface/diffusers/discussions/6836#discussioncomment-9030457_

**Comment by asomoza** [comment]
https://github.com/huggingface/diffusers/discussions/6836#discussioncomment-9030527

**Comment by SSLemon** [comment]
This issue has been resolved.
https://github.com/huggingface/diffusers/discussions/6836#discussioncomment-9033682
