### ISSUE TITLE
There may be a mistake in apply_forward_hook

### ISSUE THREAD

**Issue by InuyashaLee** [huggingface/diffusers#7602]
### Describe the bug

After I put different models of my own diffusion pipeline based on _DiffusionPipeline_ to different devices, in case the model's inputs and weights are not on the same device, I attach _AlignDevicesHooks_ on the models, such as VAE. 

However, when I call _vae.encode_ or _vae.decode_, the error _Expected all tensors to be on the same device, but found at least two devices_ still happens unless manually setting the device for the input before calling the function. Thus, I checked the source code of _AlignDevicesHook_ and _AutoencoderKL_. Then I found a decorator named _apply_forward_hook_ which added to _vae.encode_ and _vae.decode_. 

I think there may be a mistake in **_apply_forward_hook_**.  I think this line of code **self._hf_hook.pre_forward(self)** should be **args, kwargs = self._hf_hook.pre_forward(self, \*args, \*\*kwargs)** . After modification, the previous error disappeared.

### Reproduction

N/A

### System Info

N/A

**Comment by DN6** [comment]
cc: @yiyixuxu

**Comment by yiyixuxu** [comment]
I couldn't understand this issue but I think this is not relevant to us
`apply_forward_hook` is a function in accelerate -  do you want to open an issue on accelerate?

**Comment by sayakpaul** [comment]
> apply_forward_hook is a function in accelerate - do you want to open an issue on accelerate?
