### ISSUE TITLE
Img2Img with Playground 2.5 has artifacts when denoise is low

### ISSUE THREAD

**Issue by MikeHanKK** [huggingface/diffusers#7616]
### Describe the bug

I tried to generate an img2img with Playground2.5 while setting denoise is low, such as 0.5, the result image will have artifacts. If the denoise was high, such as 0.8, the result was fine, but of course it varied a lot. 

I tried both EDMDP2M and EDMDP2MK, and I got the same results.

Here are the image I used and the resulting bad image.

### Reproduction

pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    "../models/Stable-diffusion/playground-v2.5-xl-aesthetic/",
    safety_checker=None,
    torch_dtype=torch.float16,
    add_watermarker=False,
#     variant="fp16",
    **kwargs
).to('cuda')

pipe.scheduler = EDMDPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
vae_path = ''

prompt = 'Astronaut in a jungle, cold color palette, muted colors, detailed, 8k'
negative_prompt = ''
width = 1024
height = 1024
num_inference_steps = 40
guidance_scale = 3.0
num_images_per_prompt = 1
strength = 0.5

img_path = './test-img/vermeer.png'

generator = [torch.Generator(device='cuda').manual_seed(torch.Generator(device='cuda').seed()) for _ in range(num_images_per_prompt)]

image = Image.open(img_path).convert('RGB')
image = image.resize((width, height))

prompt_embeds, pooled_prompt_embeds, negative_prompt_embeds, negative_pooled_prompt_embeds = long_prompt_handle(pipe, prompt, negative_prompt)

js = {
    "prompt_embeds": prompt_embeds,
    "pooled_prompt_embeds": pooled_prompt_embeds,
    "negative_prompt_embeds": negative_prompt_embeds,
    "negative_pooled_prompt_embeds": negative_pooled_prompt_embeds,
    "num_inference_steps": num_inference_steps,
    "guidance_scale": guidance_scale,
    "num_images_per_prompt": num_images_per_prompt,
    "image": image,
    "generator": generator,
    "strength": strength
}

print(js)
rs = pipe(**js)

images = rs.images
ImageUtil.img_show('playground',images)

### System Info

diffusers0.27

### Who can help?

@yiyixuxu @sayakpaul @DN6

**Comment by sayakpaul** [comment]
To me, this seems more like a discussion. Cc: @asomoza in case you managed to make the Img2Img pipeline for Playground produce better images.

**Comment by asomoza** [comment]
Actually I didn't test the img2img before. I tested it now and I can't get good results with it.

|original|0.3|0.5|0.8|
|---|---|---|---|
|![lora_test_20240409110212_1397557536](https://github.com/huggingface/diffusers/assets/5442875/0be9b878-e0be-4f22-97a4-bf1aa285aea0)|![playground_img2img_20240409111025_490334228](https://github.com/huggingface/diffusers/assets/5442875/c056afbe-4acf-4de4-b69f-846382fee92c)|![playground_img2img_20240409111058_2517678347](https://github.com/huggingface/diffusers/assets/5442875/c6c824af-19ab-467d-a4e8-e75055aecd3f)|![playground_img2img_20240409111131_730567666](https://github.com/huggingface/diffusers/assets/5442875/0574ab81-404f-449f-a136-daf50bd6a802)|

This happens with any kind of image and I'm using the recommended `CFG` of `5.0` for `EDMEulerScheduler`

I did also a test with comfyui and it works:

|0.5|0.6|0.8|
|---|---|---|
|![ComfyUI_00023_](https://github.com/huggingface/diffusers/assets/5442875/95a9b119-5254-4735-95df-bf7871a4ce27)|![ComfyUI_00022_](https://github.com/huggingface/diffusers/assets/5442875/fd7ccf4a-ad06-498e-bc65-0b5de4af6abb)|![ComfyUI_00021_](https://github.com/huggingface/diffusers/assets/5442875/80ac9271-b371-489e-bea4-80850a2febda)|

**Comment by sayakpaul** [comment]
Okay I think I might know why it doesn’t work. Will take a look.

**Comment by plastic0313** [comment]
> Okay I think I might know why it doesn’t work. Will take a look.

I have another question about playground v2.5, maybe you can help take a look. I've used a variety of different training parameters, but I'm still not getting good results. https://github.com/huggingface/diffusers/discussions/7624

**Comment by sayakpaul** [comment]
@asomoza could you give https://github.com/huggingface/diffusers/pull/7627 a try and see if the results are better or expected?

**Comment by asomoza** [comment]
I've tested it and they results are as expected with the small difference that after 0.5 strength it stops following the source image, in comfyui this starts after 0.7. 

I don't think that's really an issue though as playground has a really strong effect.

|0.3|0.5|0.55|
|---|---|---|
|![playground_img2img_20240410064051_1729221987](https://github.com/huggingface/diffusers/assets/5442875/94bd9ada-e6cc-4b0b-b737-c02c201c27eb)|![playground_img2img_20240410064112_2433944007](https://github.com/huggingface/diffusers/assets/5442875/5b20dafc-ad9b-49e3-a545-8072561bf569)|![playground_img2img_20240410064242_1866416426](https://github.com/huggingface/diffusers/assets/5442875/25a4dffa-a9c2-4006-a55f-dd2c51bae1c8)|

**Comment by sayakpaul** [comment]
Thanks for testing, Alvaro. Appreciate it. I will get the PR ready for reviews then :)

**Comment by sayakpaul** [comment]
Thanks for testing, Alvaro. Appreciate it. I will get the PR ready for reviews then :)

**Comment by okaris** [comment]
@asomoza I think the difference is about how strength is processed for timesteps (https://github.com/huggingface/diffusers/issues/7651)

**Comment by asomoza** [comment]
I'll test this too then, we probably can add it as a reason to change this if it's true.
