### ISSUE TITLE
Add native support to InstantStyle by allowing users to choose target_blocks for IPAdapters

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#7642]
[InstantStyle](https://github.com/InstantStyle/InstantStyle) is proving to be really good quality and super simple approach - the authors realized certain blocks of the IPAdapter are responsible for composition and style
```py
# target_blocks=["block"] for original IP-Adapter
# target_blocks=["up_blocks.0.attentions.1"] for style blocks only
# target_blocks = ["up_blocks.0.attentions.1", "down_blocks.2.attentions.1"] # for style+layout blocks
ip_model = IPAdapterXL(pipe, image_encoder_path, ip_ckpt, device, target_blocks=["up_blocks.0.attentions.1"])
```

The same approach (picking specific blocks to control style/composition) is also validated by the [B-LoRA paper](https://b-lora.github.io/B-LoRA/) (they arrived at the same blocks seemingly independentl)

Given this validation, IMO it would make sense to allow such behavior natively in diffusers, as in: allowing users to generally pick target blocks for IPAdapters 

(InstantStyle also has the feature of a `neg_content_prompt` to further disentangle structure and style, but I think that is a nice extra feature, but too specific for universality - the core are the target blocks)

**Comment by yiyixuxu** [comment]
@haofanwang is working on the PR here, check it out and let me know your feedbacks
https://github.com/huggingface/diffusers/pull/7586

and yes we will support it natively in diffusers :)

**Comment by haofanwang** [comment]
Yes, will PR soon.
