### ISSUE TITLE
How to add Undesired Content with the txt2img pipe

### ISSUE THREAD

**Issue by CrazyBoyM** [huggingface/diffusers#765]
With Undesired Content, you can list anything you want the AI to avoid in future generations.
But，how to add the uc like prompt with the piep? can you help me

**Comment by siraxe** [comment]
I think with 0.4 this works now 
![image](https://user-images.githubusercontent.com/27487254/194530054-e3500fc4-6514-455a-a083-20c89ad35b6a.png)

**Comment by CrazyBoyM** [comment]
> I think with 0.4 this works now ![image](https://user-images.githubusercontent.com/27487254/194530054-e3500fc4-6514-455a-a083-20c89ad35b6a.png)

thanks a lot.
