### ISSUE TITLE
Add the ability to turn off classifer free guidance when sampling for a timestep range

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [huggingface/diffusers#7657]
Please refer to this paper.

## Applying Guidance in a Limited Interval Improves Sample and Distribution Quality in Diffusion Models

> Guidance is a crucial technique for extracting the best performance out of image-generating diffusion models. Traditionally, a constant guidance weight has been applied throughout the sampling chain of an image. We show that guidance is clearly harmful toward the beginning of the chain (high noise levels), largely unnecessary toward the end (low noise levels), and only beneficial in the middle. We thus restrict it to a specific range of noise levels, improving both the inference speed and result quality. This limited guidance interval improves the record FID in ImageNet-512 significantly, from 1.81 to 1.40. We show that it is quantitatively and qualitatively beneficial across different sampler parameters, network architectures, and datasets, including the large-scale setting of Stable Diffusion XL. **We thus suggest exposing the guidance interval as a hyperparameter in all diffusion models that use guidance**.

https://arxiv.org/pdf/2404.07724.pdf

![Screenshot_2024-04-12_09-53-16](https://github.com/huggingface/diffusers/assets/110263573/8b70a07c-5a38-490a-a52a-bd43b4d6cb8a)

![Screenshot_2024-04-12_09-54-26](https://github.com/huggingface/diffusers/assets/110263573/9b7c59d4-7eb7-47d4-8041-7a5264db1978)

Basically, classifier free guidance disrupts the normal trajectory of diffusion model SDE solvers and causes them to pigeonhole into suboptimal paths. In order to correct this, you can simply turn off CFG during the the initial range of timesteps that have a high amount of noise. This substantially improves the quality of your images.

This can be implemented in diffusers similar to the way that timestep cutoff is for models with refiners e.g. `enable_cfg_after=0.2` would enable CFG during sampling after the first timestep 800 (with timesteps 999-800 being excluded). The feature should be based on a discrete cutoff calculated from the full range of timesteps (0.2 * 1000 = 200, 999-200 = 800. After the 800th timestep is where we begin CFG).

You should be allowed to disable CFG at both the start and end of the sampling, so something like `enable_cfg_after=0.2` and `disable_cfg_after=0.8`.

**Comment by AmericanPresidentJimmyCarter** [comment]
@bghira Pointed out that this is available right now by callback at https://huggingface.co/docs/diffusers/en/using-diffusers/callback#dynamic-classifier-free-guidance, but I would argue that this should be a first class feature and possibly even a property of a scheduler itself.

**Comment by bghira** [comment]
at the very least it should be a pipeline option during `__call__()`

**Comment by DN6** [comment]
@AmericanPresidentJimmyCarter Could you elaborate on adding it as a feature? Were you envisioning something like a `cfg_interval` argument to the Pipeline? What would the interval be based on? Timesteps? Step Index?

IMO callbacks are the way to go for things related to dynamically controlling the diffusion process. But I'm open to alternatives as well. 

cc: @yiyixuxu

**Comment by AmericanPresidentJimmyCarter** [comment]
It was just two new arguments, `enable_cfg_after` and `disable_cfg_after`, as detailed above. These can also significantly speed up inference, as the paper shows you only need CFG about 60-70% of the time.

**Comment by yiyixuxu** [comment]
hi @AmericanPresidentJimmyCarter 

the callbacks are made for use cases like this :) our pipeline already has too many features IMO, many of which we would not have added if we had callbacks earlier

**Comment by bghira** [comment]
ok is there somewhere that community example callbacks can be shared and imported from?

**Comment by AmericanPresidentJimmyCarter** [comment]
> hi @AmericanPresidentJimmyCarter
> 
> the callbacks are made for use cases like this :) our pipeline already has too many features IMO, many of which we would not have added if we had callbacks earlier

I think callbacks need to have some kind of system to manage them like plugins then, because having to write callbacks for what should be a basic feature of every pipeline using CFGs feels difficult, especially for non-coding users.

**Comment by bghira** [comment]
that's sort of my thought. part of the power of Diffusers is all of the cool features it supports. but an equivalent callback plugin system would be better than posting documentation examples of how one "might" work, which will lead to a fragmented ecosystem and reinventing the wheel

**Comment by yiyixuxu** [comment]
cc @DN6 @sayakpaul here
sounds like a good suggestion to me! what do you guys think about supporting some official callbacks?

**Comment by yiyixuxu** [comment]
cc @asomoza let me know what you think!

**Comment by sayakpaul** [comment]
1000 percent yes.

**Comment by asomoza** [comment]
I agree with supporting official callbacks, it's really a good idea to have them.

**Comment by DN6** [comment]
Opened up an issue for it
https://github.com/huggingface/diffusers/issues/7736

**Comment by bghira** [comment]
resolved!
