### ISSUE TITLE
Is Multiple Conditioning in Stable Diffusion XL with ControlNet Possible?

### ISSUE THREAD

**Issue by SinaDavari** [huggingface/diffusers#7658]
**Is your feature request related to a problem? Please describe.**
I am encountering issues when trying to use multiple conditionings with the Stable Diffusion XL model using ControlNet. I followed a [guide](https://huggingface.co/blog/controlnet#canny-conditioning) and successfully ran ControlNet with depth and segmentation conditionings. The guide was based on **stable-diffusion-v1-5**, and I wanted to adapt this setup for **Stable Diffusion XL**. However, I'm facing errors indicating issues with handling multiple ControlNetModels for image conditioning. The errors are as follows:

```
TypeError: For multiple controlnets: 'image' must be type 'list'
ValueError: For multiple controlnets: 'image' must have the same length as the number of controlnets, but got 1 images and 2 ControlNets.
```
I am wondering if Multiple Conditioning in Stable Diffusion XL with ControlNet is Possible.

**Describe the solution you'd like.**
It would be wonderful if some one could help me find a way to use multiple conditioning with the Stable Diffusion XL model.

**Describe alternatives you've considered.**
An alternative would be reverting to using stable-diffusion-v1-5 as per the guide, but I am specifically interested in the capabilities and improvements offered by Stable Diffusion XL.

**Additional context.**
Here is the code snippet that resulted in the aforementioned errors, intending to use depth and segmentation as two conditions with Stable Diffusion XL:
```
controlnet = [
    ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-depth", torch_dtype=torch.float16).to("cuda"),
    ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-seg", torch_dtype=torch.float16).to("cuda"),
]

pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    controlnet=controlnet,
    variant="fp16",
    use_safetensors=True,
    torch_dtype=torch.float16
).to("cuda")
```
 Any insights or updates that could facilitate this use case would be greatly appreciated.

**Comment by standardAI** [comment]
[Yes.](https://github.com/huggingface/diffusers/discussions/7659#discussioncomment-9098185)

**Comment by DN6** [comment]
@SinaDavari Please take a look at MultiControlNet section in the link posted by @standardAI

**Comment by yiyixuxu** [comment]
We are closing this now since @standardAI provided a solution. If this is still an issue, let us know and we will re-open it!
