### ISSUE TITLE
`lpw_stable_diffusion_xl` custom pipeline doesn't work with `from_single_file`

### ISSUE THREAD

**Issue by nawka12** [huggingface/diffusers#7666]
### Describe the bug

I tested `lpw_stable_diffusion_xl`, it works with `StableDiffusionXLPipeline.from_pretrained` but doesn't work with `StableDiffusionXLPipeline.from_single_file`. I tried to delete the truncated prompt to see if it's really truncating the prompt or just an ignorable log. Here are the results:

- The prompt `open mouth,` and aesthetic tags are truncated.

![image](https://github.com/huggingface/diffusers/assets/54880732/7f482a45-b7fd-45a1-a05b-b6c23f476699)

![image](https://github.com/huggingface/diffusers/assets/54880732/8a6e4af1-4245-4636-86d6-c90bc0a90ba2)

- After removing the truncated prompt

![image](https://github.com/huggingface/diffusers/assets/54880732/11472674-22ba-4c2d-beb3-0f299205b558)

![image](https://github.com/huggingface/diffusers/assets/54880732/2629edb5-a591-403d-800c-df299193d1b6)

Here's that same prompt and settings generated with `from_pretrained` using the same model, but the diffuser version:

- `open mouth,` and aesthetic tags included

![image](https://github.com/huggingface/diffusers/assets/54880732/1eb29bf5-ae6a-4889-9596-e660c09480ef)

![image](https://github.com/huggingface/diffusers/assets/54880732/1d568a26-88f6-41e7-90b1-8cd386258359)

- without the truncated prompts

![image](https://github.com/huggingface/diffusers/assets/54880732/51a422f8-bc3d-41dd-b6c2-57e03f984b4d)

### Reproduction

pipe = StableDiffusionXLPipeline.from_single_file(
        model_path,
        torch_dtype=torch.float16,
        custom_pipeline="lpw_stable_diffusion_xl",
        use_safetensors=True,
    )
    pipe.to('cuda')

### Logs

```shell
indices sequence length is longer than the specified maximum sequence length for this model (92 > 77). Running this sequence through the model will result in indexing errors
The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: [', open mouth, masterpiece, best quality, very aesthetic, absurdres,']
```

### System Info

- `diffusers` version: 0.28.0.dev0
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.10.11
- PyTorch version (GPU?): 2.2.2+cu118 (True)
- Huggingface_hub version: 0.22.2
- Transformers version: 4.39.3
- Accelerate version: 0.28.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@yiyixuxu @sayakpaul

**Comment by anujkum25** [comment]
i believe that's only a warning.

**Comment by nawka12** [comment]
@anujkum25
If it's only a warning, then `from_single_file` will produce similar images to the one produced by `from_pretrained`. But that's not the case here.

That's why I'm showing 4 different images here.
- The first one where the prompts are truncated.
- The second one, where I remove those truncated prompts manually. Results showed the same image as the first one, which proves my point that the prompts are truncated.
- The third one, with the same settings as the first image but using `from_pretrained`, resulting different image from the first one, and detecting the prompt that is truncated on the first image (`open mouth`).
- The fourth one, has the same settings as the second image but uses `from_pretrained`, resulting similar image to images 1 and 2.

The prompt is really truncated.

**Comment by asomoza** [comment]
Currently `from_single_file` doesn't load the community pipelines, as an alternative, you can download the [pipeline](https://raw.githubusercontent.com/huggingface/diffusers/main/examples/community/lpw_stable_diffusion_xl.py) and use it directly.

**Comment by nawka12** [comment]
> Currently `from_single_file` doesn't load the community pipelines, as an alternative, you can download the [pipeline](https://raw.githubusercontent.com/huggingface/diffusers/main/examples/community/lpw_stable_diffusion_xl.py) and use it directly.

Thank you for the information. Will try to implement the pipeline directly into my code.

**Comment by xhinker** [comment]
> Currently `from_single_file` doesn't load the community pipelines, as an alternative, you can download the [pipeline](https://raw.githubusercontent.com/huggingface/diffusers/main/examples/community/lpw_stable_diffusion_xl.py) and use it directly.

Correct

**Comment by katarzynasornat** [comment]
```prompt = """masterpiece, best quality, (Anime:1.4), adorable toddler flying in space, surrounded by twinkling stars and colorful planets, whimsical children's fairytale scene, watercolor style, imaginative and charming, wearing a cute astronaut suit, playful and joyful expression, soft pastel colors, flowing brushstrokes, dreamy and magical atmosphere, highly detailed and sharp focus, light and airy feel, by Mary Blair and Hayao Miyazaki, Artstation"""


negative_prompt = """(worst quality, low quality:1.4), low resolution, poorly drawn features, out of frame, deformed, blurry, dark and moody, harsh shadows, overly saturated, bad proportions, childish scribbles, amateur, draft, watermark, signature"""


from diffusers import DiffusionPipeline
import torch
from google.colab import userdata
access_token = userdata.get('hf_token')
model_id_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = DiffusionPipeline.from_pretrained(
 model_id_or_path,
 torch_dtype = torch.float16,
 custom_pipeline = "lpw_stable_diffusion_xl",
 token=access_token
).to("cuda:0")

generator = torch.Generator(device="cuda").manual_seed(0)
images = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=50,
    generator=generator,
).images
images[0].resize((500,500))
```

I am getting this warning 

`Token indices sequence length is longer than the specified maximum sequence length for this model (79 > 77). Running this sequence through the model will result in indexing errors`

which I do believe, should not be. Is there anything I am doing wrong here?

**Comment by asomoza** [comment]
https://github.com/huggingface/diffusers/issues/7666#issuecomment-2059094259

**Comment by xhinker** [comment]
> Hi @xhinker! I have bought your book and also tried this pipeline with the following setting presented below:
> 
> ```
> prompt = """masterpiece, best quality, (Anime:1.4), adorable toddler flying in space, surrounded by twinkling stars and colorful planets, whimsical children's fairytale scene, watercolor style, imaginative and charming, wearing a cute astronaut suit, playful and joyful expression, soft pastel colors, flowing brushstrokes, dreamy and magical atmosphere, highly detailed and sharp focus, light and airy feel, by Mary Blair and Hayao Miyazaki, Artstation"""
> 
> negative_prompt = """(worst quality, low quality:1.4), low resolution, poorly drawn features, out of frame, deformed, blurry, dark and moody, harsh shadows, overly saturated, bad proportions, childish scribbles, amateur, draft, watermark, signature"""
> 
> from diffusers import DiffusionPipeline
> import torch
> from google.colab import userdata
> access_token = userdata.get('hf_token')
> model_id_or_path = "stabilityai/stable-diffusion-xl-base-1.0"
> pipe = DiffusionPipeline.from_pretrained(
>  model_id_or_path,
>  torch_dtype = torch.float16,
>  custom_pipeline = "lpw_stable_diffusion_xl",
>  token=access_token
> ).to("cuda:0")
> 
> generator = torch.Generator(device="cuda").manual_seed(0)
> images = pipe(
>     prompt=prompt,
>     negative_prompt=negative_prompt,
>     num_inference_steps=50,
>     generator=generator,
> ).images
> images[0].resize((500,500))
> ```
> 
> I am getting this warning
> 
> `Token indices sequence length is longer than the specified maximum sequence length for this model (79 > 77). Running this sequence through the model will result in indexing errors`
> 
> which I do believe, should not be. Is there anything I am doing wrong here?

You can ignore the warning, it is populated from the tokenizer, and you will still have all tokens sent to text encoder, generate the full length embeddings with weights. It is my honor to have you read my book :)

**Comment by asomoza** [comment]
I must insist about this because people then compare the results and seems to have the wrong impression about diffusers. `from_single_file` actually doesn't load custom pipelines, so to prevent people from getting the wrong information I'll provide a easy test case for this.

If you use a simple prompt like this:

`a cat playing with a (red:1.0) ball` and then do the weight of the red ball to something like 3.0 to burn the image, you get this results with `from_pretrained`

|1.0|3.0|
|---|---|
|![20240614162504_1608374682](https://github.com/huggingface/diffusers/assets/5442875/a3515a0f-98d7-4014-ae89-c4250fc53033)|![20240614162445_1608374682](https://github.com/huggingface/diffusers/assets/5442875/e14c8bd5-66db-4cb5-9f63-69d4ad53d5a9)|

So clearly the prompt weighting works. But if you do the same experiment with `from_single_file` you get this results:

|1.0|3.0|
|---|---|
|![20240614162357_1608374682](https://github.com/huggingface/diffusers/assets/5442875/5c2f842c-b29d-49b0-8047-1c1ddfc1cd66)|![20240614162418_1608374682](https://github.com/huggingface/diffusers/assets/5442875/10e94b8d-9526-4445-a3f7-73371dceef29)|

We can't clearly see that the change in the weight of the word red doesn't do anything. Also if you know how to debug you can trace this and see which pipeline gets used.

**Comment by xhinker** [comment]
> I must insist about this because people then compare the results and seems to have the wrong impression about diffusers. `from_single_file` actually doesn't load custom pipelines, so to prevent people from getting the wrong information I'll provide a easy test case for this.
> 
> If you use a simple prompt like this:
> 
> `a cat playing with a (red:1.0) ball` and then change the weight of the red ball to something like 3.0 to burn the image, you get this results with `from_pretrained`
> 
> 1.0	3.0
> ![20240614162504_1608374682](https://private-user-images.githubusercontent.com/5442875/339894960-a3515a0f-98d7-4014-ae89-c4250fc53033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzOTgxODEsIm5iZiI6MTcxODM5Nzg4MSwicGF0aCI6Ii81NDQyODc1LzMzOTg5NDk2MC1hMzUxNWEwZi05OGQ3LTQwMTQtYWU4OS1jNDI1MGZjNTMwMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMjA0NDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTFjYmI0YTUxYzNmMzA1Yjc4ZDRjOGRlODlkNTllZDUyOWNhM2RkZWI3ZGEyMzNkZTNhYmU2ZjZkZTViNjE4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7Jfk5HM6us66etNQqEQqHwuVl-bR_iwPfwn7RSYBrzY)	![20240614162445_1608374682](https://private-user-images.githubusercontent.com/5442875/339894989-e14c8bd5-66db-4cb5-9f63-69d4ad53d5a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzOTgxODEsIm5iZiI6MTcxODM5Nzg4MSwicGF0aCI6Ii81NDQyODc1LzMzOTg5NDk4OS1lMTRjOGJkNS02NmRiLTRjYjUtOWY2My02OWQ0YWQ1M2Q1YTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMjA0NDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTgzNmFlMzY3MmVlZDcwMmI3OWU5ODRhMGFlZGM5NDhlNzcxZjFhMWQ2N2RjOGVmYmY4NDJlYjg0ZGM4MDk5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ayO90LdXnLKdFT2gzlp8jwKyKpN8HKb-qvXY6EZ5tZI)
> So clearly the prompt weighting works. But if you do the same experiment with `from_single_file` you get this results:
> 
> 1.0	3.0
> ![20240614162357_1608374682](https://private-user-images.githubusercontent.com/5442875/339895176-5c2f842c-b29d-49b0-8047-1c1ddfc1cd66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzOTgxODEsIm5iZiI6MTcxODM5Nzg4MSwicGF0aCI6Ii81NDQyODc1LzMzOTg5NTE3Ni01YzJmODQyYy1iMjlkLTQ5YjAtODA0Ny0xYzFkZGZjMWNkNjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMjA0NDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzY0MjcyZDg0ZTg4OTZiNWY4MmM5NzM0NDQ2N2Q5YmM1ODliZTI4M2ViMmVhZGI3MWY0N2U0YmI4MWYyZDYwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N8eHOgNW2Mtu3gmvQHx0k_a8kaJ0Njwm7g6PjwExZls)	![20240614162418_1608374682](https://private-user-images.githubusercontent.com/5442875/339895214-10e94b8d-9526-4445-a3f7-73371dceef29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzOTgxODEsIm5iZiI6MTcxODM5Nzg4MSwicGF0aCI6Ii81NDQyODc1LzMzOTg5NTIxNC0xMGU5NGI4ZC05NTI2LTQ0NDUtYTNmNy03MzM3MWRjZWVmMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMjA0NDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM0ODk0YTVjNjFlYzcxMGE3MWNlMjIyMmEyMDViZGZiMDg2YzVlYjUzOTI5NzQ0OTU0OWY3NTQwZWYwODZhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7hp4B5SN_X1yiFoiTfdOZhmH14QPqTDV33xuyDdt4vo)
> We can see that the change in the weight of the word red doesn't do anything. Also if you know how to debug you can trace this and see which pipeline gets used.
> 
> Also we appreciate if you ask about something about a book in the corresponding repo, maybe open a new issue or to the author of the book directly and not to post about something that may confuse people in the issue. This is an issue about a problem about `from_single_file`.

Recalled that when I was building this pipeline, DiffusionPipeline did not support `from_single_file` to load custom pipeline then.   So all code is test using `from_pretrain.`

It is easy to convert a `safetensors` to diffusers format and then use the "from_pretrain" function:
https://github.com/PacktPublishing/Using-Stable-Diffusion-with-Python/blob/main/chapter_6/load_stable_diffusion_models.ipynb

Here is a juptyer notebook include codes that build the unlimited weighted prompt step by step:
https://github.com/PacktPublishing/Using-Stable-Diffusion-with-Python/blob/main/chapter_10/unlock_77_token_limitation_and_prompt_weight.ipynb

**Comment by asomoza** [comment]
Thanks for the additional information, I posted the example before just for people that finds this issue to not get the wrong idea. The example in your book works as intended just needed to insist that this doesn't work in `from_single_file`. Appreciate your notebooks and the great work you did with your book.

**Comment by ITEvo** [comment]
can someone share a code from the import to the generation instead of making us crazy with useless 12903812093812093 tests?
