### ISSUE TITLE
How to use IDDPM in diffusers ?

### ISSUE THREAD

**Issue by jiarenyf** [huggingface/diffusers#7670]
The code base is here:
https://github.com/openai/improved-diffusion/blob/main/improved_diffusion/gaussian_diffusion.py

**Comment by DN6** [comment]
@jiarenyf It would be better to ask this question in the Discussions section.

**Comment by a-r-r-o-w** [comment]
Marking this closed due to inactivity. Agree that this is better suited in the Discussions section
