### ISSUE TITLE
Deprecate VQDiffusionScheduler

### ISSUE THREAD

**Issue by HydrogenC** [huggingface/diffusers#7674]
**What API design would you like to have changed or added to the library? Why?**
Since the vq diffusion pipeline is deprecated in #6169 (sadly no docs can be found about why it is deprecated and what to use instead), there are no actively-supported modules or models in the code that depends on VQDiffusionScheduler anymore. Thus, VQDiffusionScheduler should be deprecated together with the vq diffusion pipeline.  
Add deprecation reasons and what to use instead in the classes deprecated in #6169. 

**What use case would this enable or better enable? Can you give us a code example?**
Better code consistency.

**Comment by yiyixuxu** [comment]
hi @HydrogenC 
do you want to open a model to deprecate it?

**Comment by HydrogenC** [comment]
> hi @HydrogenC do you want to open a model to deprecate it?

I am just wondering what is the alternative to use to create a vqvae-based diffusion model since vq diffusion pipeline is deprecated.
