### ISSUE TITLE
[Tests] help us speed up the fast pipeline tests

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#7677]
Currently, the pipeline tests (located under [`tests/pipelines`](https://github.com/huggingface/diffusers/tree/main/tests/pipelines/)) take a bit of time to run. We recently performed some optimizations to speed them up but, we can do better. 

This is especially desirable because it greatly improves the contribution experience not just for the community but also for us, maintainers. So, we welcome contributions from the community to improve the pipeline test suite that runs during PRs 🤗

## What's the problem?

Many pipeline tests (here's an [example](https://github.com/huggingface/diffusers/blob/main/tests/pipelines/animatediff/test_animatediff.py)) use model-level components (such as the UNet) whose size can be made much smaller for testing purposes. The bigger their size, the longer it's going to take to execute them (obviously).

## How can you help? 

Reduce the sizes of the model-level components and thereby making the pipeline tests run faster. 

## How should you submit a PR? 

* Start by inspecting the `get_dummy_components()` function ([example](https://github.com/huggingface/diffusers/blob/08bf7545070764d41637e90290ca9b92b392263e/tests/pipelines/animatediff/test_animatediff.py#L53)) for a given pipeline test script. 
* If you think that the block sizes could further be reduced, make changes, and then run the testing suite. 
* Submit a PR with your changes. 

## Things to note

* When submitting a PR, please consider one and only PR pipeline test script at a time. 
* Please tag me in your PR descriptions and mention this issue so that we can keep a proper track.
* You should try to keep the scope of the changes ONLY to the `get_dummy_components()` function. If further changes are required, please explain the motivation behind them in your PR description.
* You can refer to https://github.com/huggingface/diffusers/pull/7580 as a reference.

@yiyixuxu @DN6 for awareness and visibility.

**Comment by ihkap11** [comment]
Hey @sayakpaul can I take this up?

**Comment by sayakpaul** [comment]
Feel free to target one pipeline test and send over a PR :)

**Comment by AbhinavJangra29** [comment]
hey @sayakpaul  i am interested to work on this!

**Comment by sayakpaul** [comment]
@AbhinavJangra29 feel free to open a PR and tag me.

**Comment by a-r-r-o-w** [comment]
@sayakpaul, I think we could mark this as resolved because many PRs from contributors helped us out with this. For any other test speedups, I will take over
