### ISSUE TITLE
Training doesnt save models

### ISSUE THREAD

**Issue by PLEXATIC** [huggingface/diffusers#7688]
### Describe the bug

When training a diffusion model (text to image, regular SD1.5) I attempted to follow the tutorial in examples/text_to_image.
I had a bit of trouble with the libraries, so I ended up using docker and pulling SD1.5 fresh every time.
Now my training is running, but the provided script to run a trained model does not allow me to use the logged checkpoints. In fact I tried downloading and reassembling the config files from SD1.5 but I can't get it to work.

What do I need to do to become capable of running my own finetunes? And why are the nescessary files not included in the checkpoint path by default? Is there any case where people would want to **not** be able to run the models they trained themselves..?

### Reproduction

Train a SD1.5 model and attempt to use it for inference.

### Logs

```shell
Error no file named model_index.json found in directory ...
```

### System Info

I used the provided docker image, versions can be seen there.

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
There's not enough information provided on the issue. This is true because I can use the https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py and use the output pipeline directly for inference. 

If you're trying to use an intermediate checkpoint for running inference, you need to do it like so, because for intermediate checkpointing, we don't save the entire pipeline:

```python
from diffusers import UNet2DConditionModel, StableDiffusionPipeline

unet = UNet2DConditionModel.from_pretrained("path-to-checkpoint-unet")
pipeline = StableDiffusionPipeline.from_pretrained("...", unet=unet)

image = pipeline(...).images[0]
```

**Comment by PLEXATIC** [comment]
Thank you very much for your quick reply!
Yes, indeed I was attempting to use an intermediate checkpoint for running inference and You are right, I am able to do inference when loading the intermediate model checkpoints the way you explained.

Could be nice to add this to the docs.
