### ISSUE TITLE
Update ControlNetXS checkpoint keys

### ISSUE THREAD

**Issue by DN6** [huggingface/diffusers#7694]
### Describe the bug

@UmerHA  We have failing slow tests due to the ControlNetXS checkpoints
https://github.com/huggingface/diffusers/actions/runs/8709419367/job/23889042563#step:7:124

I believe the keys need to be updated to reflect the new model. 

### Reproduction

```python
from diffusers import ControlNetXSAdapter
controlnet = ControlNetXSAdapter.from_pretrained("UmerHA/Testing-ConrolNetXS-SD2.1-depth", torch_dtype=torch.float16)
```

### System Info

N/A

**Comment by UmerHA** [comment]
Have updated the models & ran the slow test on a T4 - works now.

**Comment by UmerHA** [comment]
@DN6 iiuc we can close this issue :)
