### ISSUE TITLE
stable-diffusion-xl-base-1.0 does not appear to have a file named tokenizer/config.json

### ISSUE THREAD

**Issue by HQ33** [huggingface/diffusers#7708]
### Describe the bug

when i finetuning SDXL1.0，--pretrained_model_name_or_path="./stable-diffusion-xl-base-1.0"，offline mode.

python train_dreambooth_lora_sdxl.py --pretrained_model_name_or_path="./stable-diffusion-xl-base-1.0/" --instance_prompt="In the conference room, an Asian person is sitting at his desk" --dataset_name="./data"
04/18/2024 14:14:00 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

Traceback (most recent call last):
  File "/root/data/hq/SD/fitune/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1984, in <module>
    main(args)
  File "/root/data/hq/SD/fitune/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1074, in main
    tokenizer_one = AutoTokenizer.from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 658, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 944, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.10/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: ./stable-diffusion-xl-base-1.0/ does not appear to have a file named tokenizer/config.json. Checkout 'https://huggingface.co/./stable-diffusion-xl-base-1.0//None' for available files.

### Reproduction

python train_dreambooth_lora_sdxl.py --pretrained_model_name_or_path="./stable-diffusion-xl-base-1.0/" --instance_prompt="In the conference room, an Asian person is sitting at his desk" --dataset_name="./data"

### System Info

- `diffusers` version: 0.28.0.dev0
- Platform: Linux-5.4.0-176-generic-x86_64-with-glibc2.27
- Python version: 3.10.11
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.22.2
- Transformers version: 4.30.2
- Accelerate version: 0.21.0
- xFormers version: 0.0.20

### Who can help?

@sayakpaul

**Comment by HQ33** [comment]
I don't find ./stable-diffusion-xl-base-1.0/tokenizer/config.json file in hugging face.
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/tree/main/tokenizer

**Comment by asomoza** [comment]
it's a generic log message, it's actually looking for a configuration file, it can be `tokenizer_config.json` which is the [one](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/tokenizer/tokenizer_config.json) in the repo.

for example if I rename that file to `tokenizer_config.fake` it throws:

```
OSError: ./stable-diffusion-xl-base-1.0/ does not appear to have a file named tokenizer/config.json. Checkout 'https://huggingface.co/./stable-diffusion-xl-base-1.0//tree/None' for available files.
```

but if I rename it back to  `tokenizer_config.json` it works. Same es the `/tree/None` message, normally it expects a git repo but it can be just a normal directory.

**Comment by HQ33** [comment]
非常感谢，我下载对应的文件，已经不报错了。

**Comment by asomoza** [comment]
glad it worked, could you please close the issue if you don't have any more errors.

**Comment by 1330997369** [comment]
stabilityai/stable-diffusion-xl-base-1.0 does not appear to have a file named config.json
