### ISSUE TITLE
Support for load hypernet finetune .pt file

### ISSUE THREAD

**Issue by CrazyBoyM** [huggingface/diffusers#773]
does the txt2img pipe support load a finetune .pt file to improve the output performance of checkpoint model ?

**Comment by patrickvonplaten** [comment]
Hey @CrazyBoyM, 

Sorry I don't understand the question here

**Comment by CrazyBoyM** [comment]
sorry for my poor english. it is mean hypernetwork and text inversion, just like a option in the webui version of staable diffusion, load a single finetune file to improve the base model.

**Comment by allo-** [comment]
You can extend the script using the method from this notebook: https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_conceptualizer_inference.ipynb

Have a look at the "Load the newly learned embeddings into CLIP" section. `text_encoder` and `tokenizer` are properties of the `pipeline` object.

**Comment by CrazyBoyM** [comment]
> You can extend the script using the method from this notebook: https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/stable_conceptualizer_inference.ipynb
> 
> Have a look at the "Load the newly learned embeddings into CLIP" section. `text_encoder` and `tokenizer` are properties of the `pipeline` object.

Thanks for help.I will take it a try.
