### ISSUE TITLE
documentation update in v0.24 deleted DeepFloyd info

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#7734]
### Describe the bug

#5512 refactored the Dreambooth documentation to clarify and reduce overload, but in the process, deleted information on loading DeepFloyd-IF LoRAs, eg. the predicted variance parameter.

I wasn't able to find where this information moved to, so it feels like it's actually just gone now. Can only reference older versions of the docs to point to it.

### Reproduction

https://github.com/huggingface/diffusers/blob/76c645d3a641c879384afcb43496f0b7db8cc5cb/docs/source/en/training/dreambooth.md

### System Info

N/A

### Who can help?

@stevhliu

**Comment by bghira** [comment]
@stevhliu the ping system in Github is actually broken. so, manually pinging here

**Comment by stevhliu** [comment]
Good catch! I think what we can do is create a short section for DeepFloyd-IF (similar to how there is a section for Stable Diffusion XL) on the DreamBooth [training](https://huggingface.co/docs/diffusers/main/en/training/dreambooth) doc and then reference the user to the DeepFloyd-IF [API page](https://huggingface.co/docs/diffusers/main/en/api/pipelines/deepfloyd_if). On the DeepFloyd-IF API page we can add back all the missing information.

What do you think and would you like to open a PR for this? 🤗

**Comment by bghira** [comment]
i'm not familiar enough with the docs to make it worth that effort, there's other things i'm working on at the moment that i think are a better focus for me :D but glad to review any inclusions to ensure it captures all the info we need.

no rush for it, deepfloyd ain't going anywhere and wasn't too popular, which i don't see changing in the next bit lol
