### ISSUE TITLE
Tryng to train on custome dataset but not working “–caption_column` value ‘text’ not found”

### ISSUE THREAD

**Issue by boxbox-0427** [huggingface/diffusers#7735]
### Describe the bug

I have encountered the problem as described as the link [here](https://discuss.huggingface.co/t/tryng-to-train-on-custome-dataset-but-not-working-caption-column-value-text-not-found/45258).

The dataset I used is [Levi980623/ControlNet_ade20k](https://huggingface.co/datasets/Levi980623/ControlNet_ade20k), which has the same structure as 

[fill50k](https://huggingface.co/datasets/fusing/fill50k).

Then I clone this repo to my local machine, and pass the local path in the script like
```
dataset = load_dataset(
    "/path/to/ControlNet_ade20k",
)
```
And here is the dataset structure:
```
DatasetDict({
    train: Dataset({
        features: ['image'],
        num_rows: 50516
    })
    validation: Dataset({
        features: ['image'],
        num_rows: 4000
    })
})
```

Obviously, there is no `text` and `conditioning_images` columns in the dataset.

### Reproduction

dataset==2.13.0

### System Info

- `diffusers` version: 0.28.0.dev0
- Platform: Linux-6.2.0-37-generic-x86_64-with-glibc2.35
- Python version: 3.10.13
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.20.3
- Transformers version: 4.30.2
- Accelerate version: 0.21.0
- xFormers version: 0.0.21
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
You need a caption column

**Comment by boxbox-0427** [comment]
> You need a caption column

The structure of data in `train.jsonl` is like:
```
{"image": "images/ADE_train_00000001.jpg", "conditioning_image": "conditioning_images/ADE_train_00000001_seg.png", "text": "airport terminal"}
```
Isn't  `text`  the caption column?  So how should I solve this problem?

**Comment by boxbox-0427** [comment]
Well, this has been solved when I change the url in `ade20k.py` into local path.

```
METADATA_URL = hf_hub_url(
    "/path/to/folder",
    filename="train.jsonl",
    repo_type="dataset",
)

IMAGES_URL = hf_hub_url(
    "/path/to/folder",
    filename="images.zip",
    repo_type="dataset",
)

CONDITIONING_IMAGES_URL = hf_hub_url(
    "/path/to/folder",
    filename="conditioning_images.zip",
    repo_type="dataset",
)
```

**Comment by DN6** [comment]
@boxbox-0427 Since this is resolved, can we close this issue?
