### ISSUE TITLE
Add Diffusers supported callbacks

### ISSUE THREAD

**Issue by DN6** [huggingface/diffusers#7736]
**Is your feature request related to a problem? Please describe.**
We currently support passing in callbacks to pipelines in order to manipulate/customise aspects of the diffusion process. It would be nice to have a set of officially supported callbacks in Diffusers that would allow us to support functionality such as [turning off classifier free guidance](https://github.com/huggingface/diffusers/issues/7657) out of the box.

**Describe the solution you'd like.**
A potential design to support callbacks (this is just a pseudo-code example)

```python
from diffusers import StableDiffusionPipeline
from diffusers.pipelines.callbacks import GuidanceCallback

pipe = StableDiffusionPipeline.from_pretrained("...")

callbacks = [GuidanceCallback()]
pipe.add_callbacks(callbacks)

image = pipe(...).images[0]
``` 

**Additional context.**
Transformers does support callbacks: https://huggingface.co/docs/transformers/main/en/main_classes/callback for training, while ours I think would be mostly focused on inference.

**Comment by yiyixuxu** [comment]
let's start with something simple and just start to support some really useful callback functions with the current callback design 

cc @asomoza here - can you take a lead on this?

**Comment by asomoza** [comment]
yes, I'll take this

**Comment by Bhavay-2001** [comment]
Hi @asomoza, @yiyixuxu 
Is this issue open for community?

**Comment by asomoza** [comment]
@Bhavay-2001 Not for now, I'm doing it with a specific simple design so we don't change that much of what we have right now.
