### ISSUE TITLE
errors while trying to "convert_animatediff_motion_module_to_diffusers"

### ISSUE THREAD

**Issue by lulu1315** [huggingface/diffusers#7751]
### Describe the bug

i'm trying to use different motion adapter for animatediff . these ones especially : 
https://huggingface.co/ByteDance/AnimateDiff-Lightning/blob/main/animatediff_lightning_8step_comfyui.safetensors
https://civitai.com/models/331718/bubbling-rings-or-animatediff-motion-lora

when i try to convert the safetensors to diffusers i keep having errors. 

### Reproduction

python3 scripts/convert_animatediff_motion_module_to_diffusers.py --ckpt_path animatediff_lightning_8step_diffusers.safetensors --output_path animatediff_lightning_8step_diffusers
or
python3 scripts/convert_animatediff_motion_lora_to_diffusers.py --ckpt_path animatediff_lightning_8step_diffusers.safetensors --output_path animatediff_lightning_8step_diffusers

### Logs

```shell
Traceback (most recent call last):
  File "../scripts/convert_animatediff_motion_module_to_diffusers.py", line 41, in <module>
    state_dict = torch.load(args.ckpt_path, map_location="cpu")
  File "/mnt/shared/foss-20/diffusers1/DIFF/lib/python3.8/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/mnt/shared/foss-20/diffusers1/DIFF/lib/python3.8/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '`'.
```

### System Info

- `diffusers` version: 0.27.0
- Platform: Linux-5.15.0-94-generic-x86_64-with-glibc2.29
- Python version: 3.8.0
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- Huggingface_hub version: 0.21.4
- Transformers version: 4.38.2
- Accelerate version: 0.27.2
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by DN6** [comment]
Hi @lulu1315 thanks for flagging. I've opened a PR to support converting safetensors format files to Diffusers.

**Comment by a-r-r-o-w** [comment]
Marking this as closed because the linked PR seems to have fixed the issue. Please feel free to re-open if the issue persists
