### ISSUE TITLE
Noised Image

### ISSUE THREAD

**Issue by massyzs** [huggingface/diffusers#7772]
Hi,
I'm using text_to_image_lora, and I found the variavle "X_T" is removed which prevent us feeding the noised image to diffusion. Do you think it is better to add this part? Or I miss something. It is different with previous version.

**Comment by massyzs** [comment]
Sorry, it is not "prevent", in line 759 we can still do this. But explicit api is a better choice right

**Comment by a-r-r-o-w** [comment]
Not sure what you mean here and there isn't enough details for me to debug/understand what to look into. Marking as closed but if this issue still persists and you can provide more details, I'd be happy to help - please re-open the issue in that case
