### ISSUE TITLE
Stable Video Diffusion generation bug when using batch size > 1

### ISSUE THREAD

**Issue by liyy201912** [huggingface/diffusers#7773]
### Describe the bug

When generating multiple videos (say batch size = 2), SVD will give 1 correct generation and 1 incorrect one. 

### Reproduction

video = pipeline(..., num_videos_per_prompt=2, ...)

### System Info

Any (latest)

**Comment by yiyixuxu** [comment]
can you provide a script?

**Comment by liyy201912** [comment]
Hi, 

Thanks for your reply. I think it can be reproduced through the official example here, 
https://huggingface.co/docs/diffusers/en/using-diffusers/svd#stable-video-diffusion 
by setting `pipeline(..., num_videos_per_prompt=2, ...)`

**Comment by DN6** [comment]
Hi @liyy201912 What do you mean by incorrect generation here? Do you have an example output?

**Comment by a-r-r-o-w** [comment]
Seems to have been addressed in the linked PR. If the problem still persists, please re-open this issue and apologies for the inconvenience
