### ISSUE TITLE
How to input gradio settings in Python

### ISSUE THREAD

**Issue by levoz92** [huggingface/diffusers#7775]
Hi.

I use **realisticStockPhoto_v20** on Fooocus with **sdxl_film_photography_style** lora and I really like the results.
Fooocus and other gradio implementations come with settings inputs that I want to utilize in Python as well. In particular, if this is my code:
```
device = "cuda"
model_path = "weights/realisticStockPhoto_v20.safetensors"

pipe = StableDiffusionXLInpaintPipeline.from_single_file(
    model_path, 
    torch_dtype=torch.float16, 
    num_in_channels=4).to(device)

pipe.load_lora_weights(".", weight_name="weights/SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors", adapter_name="film")
```
how can I set the following settings/parameters in code?

- Negative Prompt
- Preset (initial, lcm, default, lighting, realistic, sai, anime)
- Performance (quality, speed, extreme speed, lightning)
- width-height
- image number
- output format
- Style (Fooocus v2, fooocus photography, fooocus negative, foocus enhance, etc.)
- Base Model
- Refiner
- Lora 1,2,3,4,5,...
- Guidance scale
- Image sharpness

**Comment by standardAI** [comment]
I strongly recommend you examine [the docs page for that pipeline](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl#diffusers.StableDiffusionXLInpaintPipeline).

**Comment by levoz92** [comment]
> I strongly recommend you examine [the docs page for that pipeline](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl#diffusers.StableDiffusionXLInpaintPipeline).

Definitely will do. Thanks.

But just a cursory overview, I don't see a lot of what I listed in the documentation. Nothing about Preset, Performance, Style, Base, Refiner.

**Comment by a-r-r-o-w** [comment]
Marking as closed due to inactivity and because it seems sufficiently addressed by Tolga. Please feel free to re-open if I'm mistaken about the status of this issue, and apologies for any inconvenience caused!
