### ISSUE TITLE
[deepfloyd] unloading lora weights results in error

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#7793]
### Describe the bug

I'm trying to run a stage I LoRA and then unload those fused weights, but it results in an error.

### Reproduction

```py
from diffusers import DiffusionPipeline
import torch

# Your LoRA paths.
deepfloyd_lora_path = "ptx0/deepcinema"
deepfloyd_stage1_lora_weights_name = "pytorch_lora_weights.safetensors"

# DeepFloyd model configuration.
deepfloyd_base_model_path = "DeepFloyd/IF-I-M-v1.0"
stage1_guidance_scale = 7.5

torch_device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "xpu" if torch.xpu.is_available() else "cpu"

lora_pipe = DiffusionPipeline.from_pretrained(deepfloyd_base_model_path, watermarker=None, safety_checker=None, local_files_only=False).to(device=torch_device, dtype=torch.bfloat16)
lora_pipe.load_lora_weights(deepfloyd_lora_path, weight_name=deepfloyd_stage1_lora_weights_name)
lora_pipe.unload_lora_weights()
```

### Logs

```shell
do not know how to get attention modules for: T5EncoderModel
```

### System Info

- `diffusers` version: 0.25.0.dev0
- Platform: Linux-5.19.0-45-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.33.3
- Accelerate version: 0.26.1
- xFormers version: 0.0.22.post4+cu118
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul

**Comment by standardAI** [comment]
FYI: The latest version of `diffusers` seems OK.

**Comment by bghira** [comment]
i had a feeling. i had to update a few deps in that project, and then it worked. thank you for the heads-up

```
2024-04-28 12:17:55,353 [DEBUG] Unloading DeepFloyd Stage1 Lora model
```

no errors on latest.
