### ISSUE TITLE
Feature Request: new release

### ISSUE THREAD

**Issue by pbsds** [huggingface/diffusers#7809]
Hello, in nixpkgs we are about to start stabilizing our packages for a new stable release of nixos. We would love to ship diffusers and dependent packages with python 3.12 (context: https://github.com/huggingface/diffusers/issues/7441), but the necessary fixes have not been tagged in a release yet. 

**There is no need to rush on our behalf,** but if a new release is viable within the next month we would very much appreciate it. :smiley:  If not then please let me know, so we can cherry-pick the needed commits on our end, or even disable checks.

**Comment by yiyixuxu** [comment]
cc @DN6 @sayakpaul here

We would like to time our next release after SD3 if possible. And they haven't announced a date yet so it is a little bit uncertain. I think we should have a new release within the next month regardless :)

**Comment by sayakpaul** [comment]
Agreed!

**Comment by sayakpaul** [comment]
Closing this issue as I think we have answered to your question. Going forward don't hesitate to open a [discussion](https://github.com/huggingface/diffusers/discussions) for asking questions.
