### ISSUE TITLE
I feel confused about this TODO issue. how to pass timesteps as tensors? 

### ISSUE THREAD

**Issue by RosieApril** [huggingface/diffusers#7813]
https://github.com/huggingface/diffusers/blob/235d34cf567e78bf958344d3132bb018a8580295/src/diffusers/models/unets/unet_2d_condition.py#L918

**Comment by asomoza** [comment]
Hi, you probably need to give us more information about what you want to do. 

You want to open a PR to fix the TODO? or are you using the `get_time_embed` function? or do you want to learn how to convert an int or float to a tensor?

**Comment by a-r-r-o-w** [comment]
Marking as closed due to inactivity.
