### ISSUE TITLE
problem when training, The following values were not passed to `accelerate launch` and had defaults used instead:

### ISSUE THREAD

**Issue by ivaxsirc** [huggingface/diffusers#783]
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `6` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/home/ivaxsirc/github/diffusers/examples/dreambooth/train_dreambooth.py", line 19, in <module>
    from torchvision import transforms

I configure accelerate config but not works

thanks

**Comment by patrickvonplaten** [comment]
cc @patil-suraj regarding dreambooth

**Comment by patrickvonplaten** [comment]
small ping here @patil-suraj - maybe this is already solved by now?

**Comment by patil-suraj** [comment]
Hi @ivaxsirc, that warning can be safely ignored. Also if you want to pass that you could do it using
```bash
accelerate launch --num_cpu_threads_per_process=6
```

Regardless, the example should work fine. If not, please post a the stacktrace of the error so we could take a look. Thank you :)
