### ISSUE TITLE
CLIP Training Example Bug - Overfitting

### ISSUE THREAD

**Issue by humanely** [huggingface/diffusers#7836]
### Describe the bug

After reading numerous posts on overfitting, I am convinced that the example run_clip.py has bugs. it doesn't converge. Earlier I posted it for discussion [here](https://github.com/huggingface/diffusers/discussions/7835)

### Reproduction

Execute the run_clip.py and watch for conv/divg.

### System Info

Ubuntu 22
transfomer 4.39
diffuser 0.27

**Comment by bghira** [comment]
do you have training logs handy? wandb project would be nice to see
