### ISSUE TITLE
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.

### ISSUE THREAD

**Issue by allo-** [huggingface/diffusers#784]
### Describe the bug

Textual inversion uses a deprecated import for the scaling methods in Pillow

    DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.

### Reproduction

Use the textual inversion script with a recent Pillow version

### Logs

```shell
-
```

### System Info

Python 3.10 with latest Pillow.

**Comment by Thomas-MMJ** [comment]
I've submitted a pull request to fix this, hopefully will be reviewed and committed this coming week.

**Comment by patrickvonplaten** [comment]
Looking at the PR now :-)

**Comment by Thomas-MMJ** [comment]
note has been discussed and there are changes I need to make before accepted.
