### ISSUE TITLE
Severe difference with A1111

### ISSUE THREAD

**Issue by alexblattner** [huggingface/diffusers#7850]
### Describe the bug

I am using a custom model. On A1111 it is far more colorful than on diffusers. I am aware that it's impossible to replicate images between the 2 with the same input, but my observation is across many examples

here's results for diffusers with 1 prompt accross guidance scale:
![image](https://github.com/huggingface/diffusers/assets/15870094/9c563f7a-007e-44e1-9adc-e5398460f61c)
![image](https://github.com/huggingface/diffusers/assets/15870094/94749cc6-45e4-4d8b-89ce-e3aece76a5b0)
![image](https://github.com/huggingface/diffusers/assets/15870094/5218c83b-6d38-432c-8e1e-d6d291074f82)

same but for A1111:
![image](https://github.com/huggingface/diffusers/assets/15870094/85e98bf0-ddb4-4234-93b1-7df3c7db2147)
![image](https://github.com/huggingface/diffusers/assets/15870094/8a9024ef-b153-4e20-a69a-470cae208d48)
![image](https://github.com/huggingface/diffusers/assets/15870094/1f5bd22a-1754-4b6e-9bc8-50bf053a1cc5)
![image](https://github.com/huggingface/diffusers/assets/15870094/f252959a-07ba-4179-9cdb-8969595d8dd5)
![image](https://github.com/huggingface/diffusers/assets/15870094/f2b962f3-7153-4b73-aacd-6b593fdff4b7)

I know what you may say. It's unscientific and all, but this is my experience accross multiple images, with controlnet and ip adapter and without. On A1111, it's consistently closer to the style while diffusers has less color and tries to be more realistic (also burns more frequently)

### Reproduction

I can't give you a code snippet. It's just basic comparison with A1111 results for heavily stylized models.

### System Info

python

### Who can help?

@DN6 @yiyixuxu sorry for the very vague issue, wish I could do better

**Comment by asomoza** [comment]
Hi, maybe you can't give code, but maybe the prompt, model and parameters? I can generate a lot of images but I won't know the difference with what you're doing.

Also I don't get your comparison, the diffusers example is a portrait of a man and the auto1111 is a woman with a portrait and half body mix, so you're not even using the same prompt? To be able to compare them, at least, you should fix all the parameters of the generation, even if they won't generate the same image.

Just using a low res image of what you generated with IP Adapters, I can get the saturation and style without problems.

|||||
|---|---|---|---|
|![20240502141519](https://github.com/huggingface/diffusers/assets/5442875/d73fc947-fec2-4385-a434-cc12cdbcec6a)|![20240502141535](https://github.com/huggingface/diffusers/assets/5442875/13850563-7089-45ef-b469-a0e9f8ad5193)|![20240502141545](https://github.com/huggingface/diffusers/assets/5442875/04c6be4d-e547-41ef-a3bd-0baca649e909)|![20240502141638](https://github.com/huggingface/diffusers/assets/5442875/6211ec3c-2a9b-4220-bf56-73447f249701)|

Probably can do better if I had the prompt and the style you're using.

**Comment by alexblattner** [comment]
@asomoza you are correct. 
here's the model: https://drive.google.com/file/d/10GCQNP13YIuw8dX8zyAztUY-_lq5JH8m/view?usp=drive_link

prompt: "1boy, brown hair, waltz with bashir style, archer style"
negative_prompt: "(worst quality, low quality),childlike, petite, loli,"
steps: 30
guidance_scale: 7.5
ip_scale: 1
ip_s_scale: 1
ip adapter: ip-adapter-faceid-plusv2_sd15.bin
ip_image: 
![Screenshot_2024-05-02_150906](https://github.com/huggingface/diffusers/assets/15870094/0a85e2ef-a2bb-4dd0-8ce0-4c13cf499a2b)


the model is in diffusers so from_pretrained will work on it. I don't have it in a format for A1111 at the moment, but I doubt you would want to download the same model twice for that

**Comment by asomoza** [comment]
I'm kind of curious on how you tested the model with auto1111 if you don't have a compatible version, but anyways, I had my suspicion about it, most of the time you get those kind of images with SD 1.5 it's the vae.

So I just switched the vae and it worked, didn't even have to test with IP Adapters.

```python
vae = AutoencoderKL.from_single_file(
    "https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors",
    torch_dtype=torch.float16,
).to("cuda")


pipe = StableDiffusionPipeline.from_pretrained("./models/poselabsv12", torch_dtype=torch.float16, vae=vae).to("cuda")
```

|original|switched vae|
|---|---|
|![20240502221321_937246826](https://github.com/huggingface/diffusers/assets/5442875/df264ac1-45a6-414c-9156-74e1f07154f1)|![20240502221701_937246826](https://github.com/huggingface/diffusers/assets/5442875/bc8685ec-8857-4b1d-b00a-2e66b94a6523)|

So I recommend you switch your `vae` for a good one in the popular models, I tested it with this one which is not in diffusers format because I was testing another SD 1.5 pipeline.

**Comment by alexblattner** [comment]
I'll try that out. I'm working with someone using A1111 which is why I'm in my situation

**Comment by alexblattner** [comment]
it was the issue, thank you!

**Comment by alexblattner** [comment]
the real issue was that the strength of faceid is higher in diffusers than A1111, apply the lora at -.5 to fix it
