### ISSUE TITLE
diffusers soft inpainting support

### ISSUE THREAD

**Issue by SlZeroth** [huggingface/diffusers#7863]
SDXL inpaint quality is really poor 

but it can solve with like A1111 webui support soft inpainting feature 

is there any support plan to soft inpaint?

**Comment by standardAI** [comment]
Could you please describe how you used SDXL for inpainting? Have you tried [SD-XL model fine-tuned for inpainting](https://huggingface.co/diffusers/stable-diffusion-xl-1.0-inpainting-0.1)?

**Comment by standardAI** [comment]
Could you please describe how you used SD-XL for inpainting? Have you tried [SD-XL's fine-tuned model for inpainting](https://huggingface.co/diffusers/stable-diffusion-xl-1.0-inpainting-0.1)? One can try it quickly [from this space](https://huggingface.co/spaces/diffusers/stable-diffusion-xl-inpainting).

**Comment by SlZeroth** [comment]
@standardAI I tried inpaint before. but this inpainting quality is really bad. webui officially support soft inpainting for solve the poor inpainting quality. but diffusers not support soft inpainting

**Comment by standardAI** [comment]
I need to see a really bad output to evaluate the really badness.

**Comment by standardAI** [comment]
If you share a really bad output, then we can discuss it more quantifiable and healthily IMO.

**Comment by standardAI** [comment]
If you share a really bad output, we can discuss it in a more measurable and healthy way.

**Comment by asomoza** [comment]
I would appreciate it if you could do both: show an example of poor inpainting in diffusers, and then show the same example improved with automatic1111 soft inpainting.

I'm aware of the "soft inpainting", but I haven't had the time to test it to see if it's an improvement or not. IMO the results should be similar to what we can do with differential diffusion and the key point is that it allows to use mask with a soft brush (or gradients).

You can take a look at some experiments I did with it:

https://github.com/huggingface/diffusers/issues/6529#issuecomment-2004488450
https://github.com/huggingface/diffusers/issues/7038#issuecomment-1960492442

**Comment by SlZeroth** [comment]
@asomoza thank you for nice answer.
