### ISSUE TITLE
diffusers0.19.3

### ISSUE THREAD

**Issue by YuzhiChen001** [huggingface/diffusers#7872]
### Describe the bug

diffusers0.19.3，in pipeline_controlnet.py，
in \__call__(),`cross_attention_kwargs: Optional[Dict[str, Any]] = None,`,
but pipe(cross_attention_kwargs={"scale": 0.8}) has problem:
File "/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 322, in forward
    return self.processor(
TypeError: __call__() got an unexpected keyword argument 'scale'

### Reproduction

I don't want to update my diffusers version, is there any other solution?
Any help would be greatly appreciated.

### System Info

torch==2.0.1
torchvision
diffusers==0.19.3
transformers==4.36.0
xformers==0.0.20
xatlas
accelerate
cupy-cuda11x==12.2.0
configargparse
ipython

### Who can help?

@DN6 @yiyixuxu @sayakpaul @DN6

**Comment by asomoza** [comment]
can you share a fully reproducible code please, we can't help you with what you're sharing.

**Comment by a-r-r-o-w** [comment]
Closing this issue since 0.19 is a very old version, and due to inactivity. This should be fixed in the past few newer releases. Feel free to open a new issue if any problems still persist
