### ISSUE TITLE
lpw_stable_diffusion pipeline not working when "from_single_file" is used

### ISSUE THREAD

**Issue by digitardz** [huggingface/diffusers#7881]
### Describe the bug

I'm using `StableDiffusionPipeline` with [lpw_stable_diffusion](https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py) to do txt2img generations from long prompts.

When loading the safetensors checkpoint file using `.from_single_file`, prompts longer than 77 tokens still get truncated.

However, after converting the checkpoint to diffusers format with your [convert_from_ckpt](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L1138) script and loading its path with `.from_pretrained`, prompts seem to get handled properly with no truncation.

### Reproduction

1. Install requirements, do imports, download checkpoint from Civitai, set generation prompts and parameters
Model used for test: [https://civitai.com/models/25694/epicrealism](https://civitai.com/models/25694/epicrealism)

```python
!pip install -U transformers
!pip install -U accelerate
!pip install -U diffusers

import torch
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler
from diffusers.pipelines.stable_diffusion.convert_from_ckpt import download_from_original_stable_diffusion_ckpt

!wget -O model.safetensors 'https://civitai.com/api/download/models/143906?type=Model&format=SafeTensor&size=pruned&fp=fp16'

#repeated tokens, just for example
prompt = 'polaroid photo, night photo, photo of 24 y.o beautiful woman, pale skin, bokeh, motion blur, polaroid photo, night photo, photo of 24 y.o beautiful woman, pale skin, bokeh, motion blur, polaroid photo, night photo, photo of 24 y.o beautiful woman, pale skin, bokeh, motion blur, polaroid photo, night photo, photo of 24 y.o beautiful woman, pale skin, bokeh, motion blur, polaroid photo, night photo, photo of 24 y.o beautiful woman, pale skin, bokeh, motion blur, polaroid photo, night photo, photo of 24 y.o beautiful woman, pale skin, bokeh, motion blur, polaroid photo, night photo, photo of 24 y.o beautiful woman, pale skin, bokeh, motion blur, polaroid photo, night photo, photo of 24 y.o beautiful woman, pale skin, bokeh, motion blur, polaroid photo, night photo, photo of 24 y.o beautiful woman, pale skin, bokeh, motion blur, polaroid photo, night photo, photo of 24 y.o beautiful woman, pale skin, bokeh, motion blur, '
negative_prompt = '(deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation, ugly, unrealistic anatomy, deformed face, deformed limbs, deformed head, bad proportions, incomplete, (deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation, ugly, unrealistic anatomy, deformed face, deformed limbs, deformed head, bad proportions, incomplete'

width=960
height=1440
num_inference_steps=25
guidance_scale=7
```
<br>

2. Load .safetensors checkpoint with `StableDiffusionPipeline.from_single_file`, generate image
```python
pipeline = StableDiffusionPipeline.from_single_file(
    'model.safetensors',
    custom_pipeline='lpw_stable_diffusion',
    torch_dtype=torch.float16,
)
pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config, use_karras_sigmas=True)
pipeline.to('cuda')

image = pipeline(
    prompt = prompt,
    negative_prompt = negative_prompt,
    width=width,
    height=height,
    num_inference_steps=num_inference_steps,
    num_images_per_prompt=1,
    guidance_scale=guidance_scale,
    max_embeddings_multiples = 6,
    generator=torch.Generator(device='cuda').manual_seed(0)
).images[0]

image
```

Output:
![1](https://github.com/huggingface/diffusers/assets/168777958/e4a4b6c6-3a69-4409-9739-dfbbed0bd151)
The prompt gets truncated.
<br>

3. Convert the checkpoint file to diffusers format, load path with `StableDiffusionPipeline.from_pretrained`, generate image
```python
p = download_from_original_stable_diffusion_ckpt(
    checkpoint_path_or_dict='model.safetensors',
    from_safetensors=True,
)
p.save_pretrained('converted_model', safe_serialization=False)

pipeline = StableDiffusionPipeline.from_pretrained(
    'converted_model',
    custom_pipeline='lpw_stable_diffusion',
    torch_dtype=torch.float16,
)
pipeline.scheduler = DPMSolverMultistepScheduler.from_config(pipeline.scheduler.config, use_karras_sigmas=True)
pipeline.to('cuda')

image = pipeline(
    prompt = prompt,
    negative_prompt = negative_prompt,
    width=width,
    height=height,
    num_inference_steps=num_inference_steps,
    num_images_per_prompt=1,
    guidance_scale=guidance_scale,
    max_embeddings_multiples = 6,
    generator=torch.Generator(device='cuda').manual_seed(0)
).images[0]

image
```
Output:
![2](https://github.com/huggingface/diffusers/assets/168777958/b52d2bb4-1d8b-4ddb-a5a3-40703d02948e)
No truncation.

Note that the "Token indices sequence length" is a false alarm according to the community pipeline documentation.

### System Info

Google Colab clean environment with T4 GPU
transformers 4.40.2
diffusers 0.27.2

### Who can help?

@DN6, maybe @SkyTNT?
I think the handling of long prompts is a great feature for diffusers pipelines, I hope it gets mantained over time :)

**Comment by yiyixuxu** [comment]
Hi @digitardz 
thanks for the issue but I do not understand it, you said 
> I'm using StableDiffusionPipeline with [lpw_stable_diffusion](https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py)

but in the script you provided, you only used StableDiffusionPipeline, did I miss anything?

**Comment by crapthings** [comment]
@yiyixuxu 

```
pipeline = StableDiffusionPipeline.from_single_file(
    'model.safetensors',
    custom_pipeline='lpw_stable_diffusion',
    torch_dtype=torch.float16,
)
```


after add this custom_pipeline
<img width="716" alt="image" src="https://github.com/huggingface/diffusers/assets/1147704/0083f73f-965d-4b60-93c5-60d300fd6451">

this warning still exists, so we don't know if its working or not

**Comment by yiyixuxu** [comment]
ahh I see!!! ohh I don't think `from_single_file` works with `custom_pipeline`

Can you do this:

after 
```py
pipeline = StableDiffusionPipeline.from_single_file(
    'model.safetensors',
    custom_pipeline='lpw_stable_diffusion',
    torch_dtype=torch.float16,
)
```

and then 
```py
pipe_lpw = DiffusionPipeline.from_pipe(
    pipe_sd,
    custom_pipeline="lpw_stable_diffusion",
).to("cuda")
```


see more about `from_pipe` API https://huggingface.co/docs/diffusers/main/en/using-diffusers/custom_pipeline_overview#load-with-frompipe

**Comment by yiyixuxu** [comment]
cc @DN6 here
should we add a `validattion` decorator for `from_single_file`? see more here https://github.com/huggingface/diffusers/issues/6814

**Comment by digitardz** [comment]
> ahh I see!!! ohh I don't think `from_single_file` works with `custom_pipeline`
> 
> Can you do this:
> 
> after
> 
> ```python
> pipeline = StableDiffusionPipeline.from_single_file(
>     'model.safetensors',
>     torch_dtype=torch.float16,
> )
> ```
> 
> and then
> 
> ```python
> pipe_lpw = DiffusionPipeline.from_pipe(
>     pipeline,
>     custom_pipeline="lpw_stable_diffusion",
> ).to("cuda")
> ```
> 
> see more about `from_pipe` API https://huggingface.co/docs/diffusers/main/en/using-diffusers/custom_pipeline_overview#load-with-frompipe

I tried this but apparently `DiffusionPipeline` doesn't have the `from_pipe` method.
Output:
`AttributeError: type object 'DiffusionPipeline' has no attribute 'from_pipe'`

**Comment by yiyixuxu** [comment]
ohh sorry you have to install diffusers from source, since the PR was merged after the last release 
```bash
pip install git+https://github.com/huggingface/diffusers
```

**Comment by digitardz** [comment]
> ohh sorry you have to install diffusers from source, since the PR was merged after the last release
> 
> ```shell
> pip install git+https://github.com/huggingface/diffusers
> ```

Alright that worked, no truncation error with your code

**Comment by waleedrazakhan92** [comment]
@digitardz  were you able to solve this? I'm trying the juggernaut-xl-v8 by loading it with `pipe = StableDiffusionXLPipeline.from_single_file(
    juggernautXL_v8Rundiffusion.safetensors,
    torch_dtype=torch.float16,
    variant="fp16",
)
`

 but doing 

`pipe_lpw = DiffusionPipeline.from_pipe(
    pipe,
    custom_pipeline="lpw_stable_diffusion",
).to("cuda")` 

throws error:
`
ValueError: Pipeline <class 'diffusers_modules.git.lpw_stable_diffusion.StableDiffusionLongPromptWeightingPipeline'> expected ['feature_extractor', 'safety_checker', 'scheduler', 'text_encoder', 'tokenizer', 'unet', 'vae'], but only {'tokenizer', 'unet', 'scheduler', 'text_encoder', 'vae', 'feature_extractor'} were passed
`
