### ISSUE TITLE
Strange Results in Latent to Diffusion

### ISSUE THREAD

**Issue by SlZeroth** [huggingface/diffusers#7887]
Hello. I am trying to use text to image in the XL model to output latents and then use those latents to perform diffusion again. I used the output_type="latent" provided by diffusers to receive the latent as a return value and then used it to generate an image, but strange results are appearing. The strange results are as follows:

```
seed = torch.Generator(device="cuda").manual_seed(1234)
latents = pipe(
    prompt="photo of a girl, ID photo, natural skin, centered, white wedding, white background",
    negative_prompt="(worst quality, low quality, normal quality, lowres, low details, grayscale, bw), painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label, long neck, ugly",
    num_inference_steps=2,
    guidance_scale=7,
    width=1024,
    height=1248,
    seed=seed,
    output_type="latent",
)

seed = torch.Generator(device="cuda").manual_seed(1234)
result_images = pipe(
    prompt="photo of a girl, ID photo, natural skin, centered, white wedding, white background",
    negative_prompt="(worst quality, low quality, normal quality, lowres, low details, grayscale, bw), painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label, long neck, ugly",
    num_inference_steps=20,
    guidance_scale=7,
    generator=seed,
    latents=latents[0],
    width=1024,
    height=1248,
).images
```

<img width="500" alt="image" src="https://github.com/huggingface/diffusers/assets/8098724/36105f6f-d5c8-4f29-9343-0c9a6f46d0d9">

The following is the normal result output using only text to image without latents.

```
result_images = pipe(
    prompt="photo of a girl, ID photo, natural skin, centered, white wedding, white background",
    negative_prompt="(worst quality, low quality, normal quality, lowres, low details, grayscale, bw), painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label, long neck, ugly",
    num_inference_steps=20,
    guidance_scale=7,
    generator=seed,
    width=1024,
    height=1248,
).images
```

<img width="502" alt="image" src="https://github.com/huggingface/diffusers/assets/8098724/6e3ac4e1-a0ef-4421-bb32-9ae23b7ec5fd">

Is there a problem with my code?

The reason I am trying to do this is because when using the results of training a person with LORA for text to image, the model has also learned the composition, so it does not follow the prompt well when generating images. Therefore, I want to generate normal latents and then use them to perform diffusion. (I am not using ControlNet because the changes in UNet cause the face images to deteriorate.)

**Comment by standardAI** [comment]
Hello @SlZeroth. Are you looking for something like [ensemble of expert denoisers](https://huggingface.co/docs/diffusers/main/en/using-diffusers/sdxl#base--refiner-model)?

**Comment by SlZeroth** [comment]
@standardAI Using a refiner is not suitable in this case because it significantly degrades the facial features learned by LORA, resulting in a substantial loss of detail in the face.

**Comment by asomoza** [comment]
@standardAI  probably meant to do what you're doing using the same technique. 

What you're doing now is not correct, you're setting the steps of the first inference to `2`, that means that the image is fully denoised in two steps, it doesn't matter how many steps you put in the second one, the image will always be the same.

I don't think this is going to solve your problem, but something like this is what you need to do:

```python
generator = torch.Generator(device="cuda").manual_seed(1234)

latents = pipe(
    prompt="photo of a girl, ID photo, natural skin, centered, white wedding, white background",
    negative_prompt="(worst quality, low quality, normal quality, lowres, low details, grayscale, bw), painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label, long neck, ugly",
    num_inference_steps=20,
    denoising_end=0.05,
    guidance_scale=7,
    width=1024,
    height=1248,
    generator=generator,
    output_type="latent",
)


second_pipe = AutoPipelineForImage2Image.from_pipe(pipe)

image = second_pipe(
    prompt="photo of a girl, ID photo, natural skin, centered, white wedding, white background",
    negative_prompt="(worst quality, low quality, normal quality, lowres, low details, grayscale, bw), painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label, long neck, ugly",
    image=latents[0],
    num_inference_steps=20,
    denoising_start=0.05,
    guidance_scale=7,
    generator=generator,
    strength=1.0,
    width=1024,
    height=1248,
).images[0]
```

**Comment by SlZeroth** [comment]
@asomoza thank you !! I solve the issue using your code!
