### ISSUE TITLE
how can I use control_guidance_start, end in ip adapter ? 

### ISSUE THREAD

**Issue by SlZeroth** [huggingface/diffusers#7921]
I want to generate image with controlnet pose + ip adapter 

I want to use Ip adapter with start 0.0 ~ 0.4 like this

<img width="910" alt="image" src="https://github.com/huggingface/diffusers/assets/8098724/59fd4d38-600b-4860-920f-f6f2b6c94e86">

but I cant find any params to apply control_guidance_start, end for ip adapter 

is there anyway of use control_guidance_start for ip adapter ?

**Comment by asomoza** [comment]
Hi, for this you can use [callbacks](https://huggingface.co/docs/diffusers/using-diffusers/callback). If you need help with the code on how to do it, please ask this in the discussion, I like to post code there so people can find it later.

If you just want to stop the IP Adapter after some step or step ratio, you can use the [official callback](https://huggingface.co/docs/diffusers/main/en/using-diffusers/callback#official-callbacks), the callback name is `IPAdapterScaleCutoffCallback`
