### ISSUE TITLE
support Kandinsky 3.1

### ISSUE THREAD

**Issue by EYcab** [huggingface/diffusers#7928]
Kandinsky 3.1 has updated a few new features(including Kandinsky Flash) a few weeks ago which is yet supported in diffusers.

Please check out https://github.com/ai-forever/Kandinsky-3

**Comment by a-r-r-o-w** [comment]
@yiyixuxu Are there any plans for this? If yes, can open to community, and if not, can close as not-planned.

**Comment by yiyixuxu** [comment]
yeah let's close this for now
