### ISSUE TITLE
[ko] Translating docs(Conceptual Guides) to Korean. 

### ISSUE THREAD

**Issue by mreraser** [huggingface/diffusers#7940]
Hello!
Thank you for creating a wonderful repository. I would like to start translation about these four documents in Korean.

- [x] [Philosophy](https://github.com/huggingface/diffusers/blob/main/docs/source/en/conceptual/philosophy.md)
- [x] [Diffusers’ Ethical Guidelines](https://github.com/huggingface/diffusers/blob/main/docs/source/en/conceptual/ethical_guidelines.md)
- [x] [Evaluating Diffusion Models](https://github.com/huggingface/diffusers/blob/main/docs/source/en/conceptual/evaluation.md)
- [x] [How to contribute to Diffusers](https://github.com/huggingface/diffusers/blob/main/docs/source/en/conceptual/contribution.md)

Have a nice day :)

**Comment by yiyixuxu** [comment]
thanks!

cc @stevhliu

**Comment by stevhliu** [comment]
Welcome and thanks for your interest in translating the docs! 🤗 

In case you haven't seen it already check out the [Translating](https://github.com/huggingface/diffusers/blob/main/docs/TRANSLATING.md) guide for more instructions on how to get started. 

You'll also need to find another Korean speaker to review the accuracy of the translation since none of us on the Diffusers team can read it (we just check the doc structure and format)! In the past, @wonhyeongseo and the PseudoLab group have done a lot of good work translating the Hugging Face documentation to Korean, so maybe you can ping one of them to review the content. Check out the **Who can review** section in this [PR](https://github.com/huggingface/huggingface_hub/pull/2139) for some potential collaborators! :)

**Comment by mreraser** [comment]
> Welcome and thanks for your interest in translating the docs! 🤗
> 
> In case you haven't seen it already check out the [Translating](https://github.com/huggingface/diffusers/blob/main/docs/TRANSLATING.md) guide for more instructions on how to get started.
> 
> You'll also need to find another Korean speaker to review the accuracy of the translation since none of us on the Diffusers team can read it (we just check the doc structure and format)! In the past, @wonhyeongseo and the PseudoLab group have done a lot of good work translating the Hugging Face documentation to Korean, so maybe you can ping one of them to review the content. Check out the **Who can review** section in this [PR](https://github.com/huggingface/huggingface_hub/pull/2139) for some potential collaborators! :)

OK I understood, I have noted the points you mentioned, and I will request a content review once the translation is complete. Thank you!

**Comment by jungnerd** [comment]
Thanks for the translation👍
We, the Pseudo Lab team, will have review it. 
Thanks for the ping @stevhliu

**Comment by heuristicwave** [comment]
안녕하세요 지욱님, `conceptual/philosophy` 번역 문서 suggestion 반영되지 않아서 코멘트를 남깁니다!
[허깅페이스 디스코드 한국어 번역 채널](https://discord.gg/hugging-face-879548962464493619)에서 안내드리려 합니다!

**Comment by mreraser** [comment]
> 안녕하세요 지욱님, `conceptual/philosophy` 번역 문서 suggestion 반영되지 않아서 코멘트를 남깁니다! [허깅페이스 디스코드 한국어 번역 채널](https://discord.gg/hugging-face-879548962464493619)에서 안내드리려 합니다!

앗 그렇습니까? 제가 어떤 실수를 했나 봅니다. 현재 들어와 있습니다!

**Comment by mreraser** [comment]
> > 안녕하세요 지욱님, `conceptual/philosophy` 번역 문서 suggestion 반영되지 않아서 코멘트를 남깁니다! [허깅페이스 디스코드 한국어 번역 채널](https://discord.gg/hugging-face-879548962464493619)에서 안내드리려 합니다!
> 
> 앗 그렇습니까? 제가 어떤 실수를 했나 봅니다. 현재 들어와 있습니다!

확인해보니 제가 처음에 파일 이름을 아마 `philosopy.md`(오타)로 하여 이후 파일명을 `philosophy.md`로 변경하였었는데, 그러다보니 commit suggestion 눌렀는데 해당 파일에 변경이 안된 것 같습니다ㅠ. 죄송합니다, 제가 한번더 확인했어야 하는데 제 불찰입니다. 이 부분 반영하여 새로이 PR을 하는 것이 좋을지 아니면 어떻게 하는게 좋을지 여쭤볼 수 있겠습니까?

**Comment by heuristicwave** [comment]
@mreraser 디스코드에서 찾을 수 있을 줄 알았는데 ㅠ 찾기가 어렵네요.
이미 머지가 된거라 새롭게 PR을 올려주시는게 좋을 것 같습니다.
#8294 와 동일하게 Open이 아닌, Draft로 올려주세요!

궁금하신점은 heuristicwave@gmail.com으로 연락주세요!

**Comment by mreraser** [comment]
> @mreraser 디스코드에서 찾을 수 있을 줄 알았는데 ㅠ 찾기가 어렵네요.
> 
> 이미 머지가 된거라 새롭게 PR을 올려주시는게 좋을 것 같습니다.
> 
> #8294 와 동일하게 Open이 아닌, Draft로 올려주세요!
> 
> 
> 
> 궁금하신점은 heuristicwave@gmail.com으로 연락주세요!

네 알겠습니다! 감사합니다, PR 올리고 다시 말씀드리겠습니다!

**Comment by mreraser** [comment]
translation complete!
