### ISSUE TITLE
how can i know what the model base are 

### ISSUE THREAD

**Issue by xalteropsx** [huggingface/diffusers#7954]
from transformers import DiffusionPipeline

base_model_id = "anything-v3-fp16-pruned.safetensors"

pipeline = DiffusionPipeline.from_pretrained(
    base_model_id,
    model_dir=model_dir,
    use_safetensors=True,
)

**Comment by standardAI** [comment]
I found [anything-v3-fp16-pruned.safetensors](https://huggingface.co/AdamOswald1/Anything-Preservation/tree/main) in Hugging Face. You can also see the config files of the components:
```py
print(pipeline.config)
print(pipeline.vae.config)
```
