### ISSUE TITLE
config file is not a valid json file

### ISSUE THREAD

**Issue by neonarc4** [huggingface/diffusers#7979]
File "Z:\software\python11\Lib\site-packages\diffusers\configuration_utils.py", line 436, in load_config
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at 'X:\test\dreamshaper_8.safetensors' is not a valid JSON file.

why other diffusers doesnt have single file ? 

 pipe = AutoPipelineForInpainting.from_pretrained(
                test/dreamshaper_8.safetensors')

**Comment by standardAI** [comment]
Try with:
```py
StableDiffusionPipeline.from_single_file(...)
```

**Comment by neonarc4** [comment]
@standardAI  is their for AutoPipelineForText2Image   ,I2VGenXLPipeline  ,StableVideoDiffusionPipeline

**Comment by suzukimain** [comment]
Maybe this PR has something to do with it.
https://github.com/huggingface/diffusers/pull/6986#issue-2136319703

**Comment by yiyixuxu** [comment]
Hi!
we won't be able to support single file with `AutoPipelineForText2Image` since the pipeline type need to be explicitly given for single checkpoint 
for `I2VGenXLPipeline` and `StableVideoDiffusionPipeline` we are happy to support if there are single checkpoint available cc @DN6

**Comment by pwcarney** [comment]
> Hi! we won't be able to support single file with `AutoPipelineForText2Image` since the pipeline type need to be explicitly given for single checkpoint for `I2VGenXLPipeline` and `StableVideoDiffusionPipeline` we are happy to support if there are single checkpoint available 

@yiyixuxu This answers a question about an issue I've been having. However, I am mostly familiar with only needing a .safetensors file in order to run diffusion. Is this pipeline type something I can generate manually prior to attempting to instantiate a AutoPipelineForImage2Image.from_pretrained off a local safetensors file?

**Comment by asomoza** [comment]
If you're going to store a config file why not just use the diffusers format?  Which does exactly that and also allows to change the modules if you need to, for example the vae in SD 1.5 or the turbo o lighting versions of the unet in SDXL.

Most of the models right now have a diffusers version, for example the model you're using can just be loaded like this:

pipe = AutoPipelineForInpainting.from_pretrained("Lykon/dreamshaper-8")

If you need to have them locally in another directory, you can clone the [repo](https://huggingface.co/Lykon/dreamshaper-8) if you want revisions or do a shallow clone if you only want the latest.

If you still want to do what you're suggesting, you'll need to use a file with each model and associate the corresponding pipeline to it, for example [this one](https://huggingface.co/Lykon/dreamshaper-8/blob/main/model_index.json):

`"_class_name": "StableDiffusionPipeline",`

and then use the corresponding class to load the model, that's basically what the `AutoPipeline` does.

**Comment by yiyixuxu** [comment]
if you know the pipeline name, you can use the pipeline class with `from_single_file`. e.g 

```python
StableDiffusionImg2ImgPipeline.from_single_file(.safetensor)
```

**Comment by yiyixuxu** [comment]
or is there any particular reason you have to use the `AutoPipeline`?

**Comment by yiyixuxu** [comment]
`AutoPipeline` detects the pipeline class for you, so if you already know the class, you don't need it

**Comment by neonarc4** [comment]
is their any update for StableVideoDiffusionPipeline and I2VGenXLPipeline

**Comment by neonarc4** [comment]
thanks everyone i guess it resolved seems like video pipeline is not yet release any safetensor single file so far while not sure about gif i wonder if it can able to resolve in singilefile I2VGenXLPipeline
