### ISSUE TITLE
Define a metadata format for textual inversion concepts

### ISSUE THREAD

**Issue by allo-** [huggingface/diffusers#799]
**Is your feature request related to a problem? Please describe.**
The textual inversion script currently creates a dict with one term and its associated embedding. Usual scripts load one or more embeddings using the keys as token for prompt.

This format does not allow for metadata associated with the key(s). The longer the format exists, the more it will be used everywhere, so it would be good to define a more extendable format as soon as possible.

**Describe the solution you'd like**
Change the format from:

```
{
  "term": embedding_tensor
}
```

to something like

=== First version (leaving room for additional data for each term) ===
```
{
  "term": {
    "embedding": embedding_tensor
  }
}
```

or even

=== Second version  (leaving room for additional data for each term and data for the whole file) ===
```
{
  "terms": [
    "term": {
      "embedding": embedding_tensor
    }
  }
}
```

which leaves room for adding metadata that not every script needs to understand like

=== First version ===
```
{
  "term": {
    "embedding": embedding_tensor
    "training_steps": 2000 # will be shown in the loading screen
    "training_files": ["hash1", "hash2", "hash3"] # is used to continue training
    "some_other_metadata": "for_the_embedding"
  }
}
```

=== Second version ===
```
{
  "terms": [
    "term": {
      "embedding": embedding_tensor
      "training_steps": 2000 # will be shown in the loading screen
      "training_files": ["hash1", "hash2", "hash3"] # is used to continue training
      "some_other_metadata": "for_the_embedding"
    }
  },
  "author": "My Name", # can be extracted for attribution
  "license": "CC-0"
  "some_other_metadata": "for_the_file"
}
```

The additional keys can be read or can be ignored (which means front-end developers can agree on a standard later on and convert between different formats), but moving the tensor into a sub-structure is required to make it possible to add additional data, which can be distinguished from the actual embedding data, without breaking other people's codes.

**Describe alternatives you've considered**
With the current structure it would require workarounds like a special key "__metadata__" which is skipped by scripts loading the embeddings. Another option would be to store the metadata in a separate file.

**Additional context**
It would often be useful to provide a embedding in different versions and it should be easy to bundle the associated metadata with the embedding.

**Comment by allo-** [comment]
Automatic1111 already uses an own format [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/textual_inversion/textual_inversion.py) even when it still is able to load the plain textual inversion files generated by the example script in this repo.

**Comment by allo-** [comment]
bump

**Comment by allo-** [comment]
I still think it's useful

**Comment by patrickvonplaten** [comment]
Hey @allo- ,

I think this might be a bit too much high-level customization for an example script of diffusers at the moment.

**Comment by allo-** [comment]
It's too high-level for an example script, but somewhere should be a standard defined and it should be done before there are too many implementations.

That said ... I think the diffusers example script is one source and seems to be mainly used by sd-concepts-library (and that's the only large library I know of) and most other people use the automatic1111 UI that uses a more advanced format and can read the diffusers embeddings.

So maybe automatic1111 already defined a de-facto standard and the only thing remaining would be to ask if people are interested in formalizing a standard everyone can implement.

**Comment by patrickvonplaten** [comment]
> nice if diffusers an example script of how to work with one of those concept embeddings.

cc'ing @apolinario here :-)

**Comment by patrickvonplaten** [comment]
I think a doc page would also be very nice here cc @patil-suraj

**Comment by apolinario** [comment]
> Who maintains https://huggingface.co/sd-concepts-library ? Is that a 🤗 project or led by an external team? In any case, that seems like the right place to set a precedent for this. And it would be nice if diffusers an example script of how to work with one of those concept embeddings.

Hi @keturn , I maintain that, happy to set this precedent, I love the idea! I also love the idea of including an example on how to load the embeds into the model; I'll work on it! We can also chat about the precedent part and how to adapt the library

**Comment by allo-** [comment]
Now that #781 is finally merged, my next PR would be to get https://github.com/huggingface/diffusers/pull/781#issuecomment-1292660824 into the textual inversion script.

Another (additional) example would be to provide a script to merge concepts into models (https://github.com/huggingface/diffusers/pull/781#issuecomment-1306900623), or a general helper module for loading concepts into an existing model, but I think the first simple step would be to add the code for continuing training.

**Comment by allo-** [comment]
@apolinario @keturn My PR is now here: #1597
