### ISSUE TITLE
Inpaint at full resolution 

### ISSUE THREAD

**Issue by arandomgoodguy** [huggingface/diffusers#812]
**Is your feature request related to a problem? Please describe.**

It would be excellent if StableDiffusionInpaintPipeline has the option of inpainting at full resolution since most of the time,  if your initial image includes human face, and you want to keep human face unchanged, the output image of the face part is likely to be a lot blurry.

**Describe the solution you'd like**
The idea is to only resize the masked region, and after processing it is pasted back to the original picture, and I found a good implementation here, but wonder how to add this option to StableDiffusionInpaintPipeline.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/429442f4a6aab7301efb89d27bef524fe827e81a/modules/processing.py#L621

**Comment by neverix** [comment]
The [Blended Diffusion branch](https://github.com/huggingface/diffusers/pull/362) might be relevant?

**Comment by patrickvonplaten** [comment]
Hey, 

Thanks for the issue! Note that the inpaint pipeline is still experimental because no official stable diffusion in-painting checkpoint has been released so far.

We wanted to take a closer look at in-painting as soon as a better checkpoint is released.

**Comment by arandomgoodguy** [comment]
Hi, thanks for your response!

It seems that runwayML had pre-trained an inpainting model, and also uploaded the checkpoint to huggingface. 

See [](https://huggingface.co/runwayml/stable-diffusion-inpainting)

**Comment by patrickvonplaten** [comment]
Yes exactly, we've updating the official inpaint pipeline to match this checkpoint :-) You can find the docs [here: StableDiffusionInpaintPipeline](https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion#diffusers.StableDiffusionInpaintPipeline)
