### ISSUE TITLE
When setting ip_adapter_scale with a dict and ipadapter plus TypeError: unsupported operand type(s) for *: 'dict' and 'Tensor'

### ISSUE THREAD

**Issue by barber5** [huggingface/diffusers#8234]
### Describe the bug

This code works fine when I use pipeline.set_ip_adapter_scale(1.0) but fails as below when I set the scale witha dict

File \"/usr/local/lib/python3.11/dist-packages/diffusers/models/transformers/transformer_2d.py\", line 397, in forward
    hidden_states = block(
                    ^^^^^^
  File \"/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py\", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py\", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.11/dist-packages/diffusers/models/attention.py\", line 366, in forward
    attn_output = self.attn2(
                  ^^^^^^^^^^^
  File \"/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py\", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py\", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.11/dist-packages/diffusers/models/attention_processor.py\", line 522, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File \"/usr/local/lib/python3.11/dist-packages/diffusers/models/attention_processor.py\", line 2417, in __call__
    hidden_states = hidden_states + scale * current_ip_hidden_states
                                    ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'dict' and 'Tensor'

### Reproduction

controlnet = ControlNetModel.from_pretrained('diffusers/controlnet-depth-sdxl-1.0', torch_dtype=torch.float16, variant='fp16')
vae = AutoencoderKL.from_pretrained('madebyollin/sdxl-vae-fp16-fix', torch_dtype=torch.float16)
image_encoder = CLIPVisionModelWithProjection.from_pretrained(
    "h94/IP-Adapter",
    subfolder="models/image_encoder",
    torch_dtype=torch.float16
)
pipeline = StableDiffusionXLControlNetPipeline.from_pretrained(
    'stabilityai/stable-diffusion-xl-base-1.0', controlnet=controlnet, vae=vae, image_encoder=image_encoder, torch_dtype=torch.float16, variant='fp16'
)
pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="sdxl_models", weight_name="ip-adapter-plus_sdxl_vit-h.safetensors")
scale = {
        "up": {"block_0": [0.0, 1.0, 0.0]},
    }

pipeline.set_ip_adapter_scale(scale)
pipeline(
        prompt=prompt_g,
        prompt_2=prompt_l,
        negative_prompt=negative_prompt,
        image=controlnet_image,
        ip_adapter_image=ip_image,
        num_inference_steps=num_inference_steps,
        controlnet_conditioning_scale=controlnet_conditioning_scale,
)

### Logs

_No response_

### System Info

runpod serverless

### Who can help?

@yiyixuxu @sayakpaul @DN6

**Comment by standardAI** [comment]
Did you install `diffusers` from the source?

**Comment by standardAI** [comment]
Did you install `diffusers` from the source?

**Comment by barber5** [comment]
Used pip

Everything works fine when I use `pipeline.set_ip_adapter_scale(1.0)`

but get the error above when I use 

`scale = {
"up": {"block_0": [0.0, 1.0, 0.0]},
}

pipeline.set_ip_adapter_scale(scale)`

**Comment by sayakpaul** [comment]
Can you install from the source?

```
pip install git+https://github.com/huggingface/diffusers
```

**Comment by barber5** [comment]
fixed, thanks
