### ISSUE TITLE
AttributeError: module diffusers has no attribute StableCascadeUNet

### ISSUE THREAD

**Issue by Vektor369** [huggingface/diffusers#8307]
### Describe the bug

Receive the error:
```AttributeError: module diffusers has no attribute StableCascadeUNet```
when attempting to generate in Forge.

### Reproduction

I don't have any code. Just opened a clean install in Forge, and attempted to generate.

### System Info

- `diffusers` version: 0.12.1
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.9
- PyTorch version (GPU?): 2.1.0+cpu (False)
- Huggingface_hub version: 0.21.4
- Transformers version: 0.28.0
- Accelerate version: not installed
- xFormers version: 0.0.17
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by DN6** [comment]
Hi @Vektor369 it seems like you're using a very old version of diffusers here? Is that the case? Is it possible for you to run `diffusers-cli env` and share the results?

**Comment by Vektor369** [comment]
Thank you. I'm afraid I don't know what I'm doing, so I wouldn't be able to tell you what version of diffusers I'm using.
I did run ```diffusers-cli env``` though, but it returned the following error:
```WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.0+cu118 with CUDA 1108 (you have 2.1.0+cpu)
    Python  3.10.10 (you have 3.10.9)
  Please reinstall xformers
```
So, I tried installing xformers using ```pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121``` which returned the following at the end:
```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0 requires torch==2.1.0, but you have torch 2.3.0+cu121 which is incompatible.
torchvision 0.17.1 requires torch==2.2.1, but you have torch 2.3.0+cu121 which is incompatible.
```
I ran ```diffusers-cli env``` again, which now returns the following:
```Traceback (most recent call last):
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\Scripts\diffusers-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\commands\diffusers_cli.py", line 39, in main
    service.run()
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\commands\env.py", line 110, in run
    platform_info = f"{platform.freedesktop_os_release().get('PRETTY_NAME', None)} - {platform.platform()}"
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\platform.py", line 1299, in freedesktop_os_release
    raise OSError(
FileNotFoundError: [Errno 2] Unable to read files /etc/os-release, /usr/lib/os-release```

**Comment by tolgacangoz** [comment]
@Vektor369 This problem has just been resolved. [Could you install `diffusers` from the source?](https://huggingface.co/docs/diffusers/main/en/installation#install-from-source)

**Comment by Vektor369** [comment]
I installed diffusers from the source, but I'm still receiving the same error when I run ```diffusers-cli env```.

**Comment by tolgacangoz** [comment]
I can recommend that you create a new conda environment and install it there again.

**Comment by a-r-r-o-w** [comment]
Seems like an environment problem which can be fixed easily and is non-reproducible with latest diffusers. Marking as closed, but feel free to re-open if you think this is still a problem :)
