### ISSUE TITLE
prs-eth/marigold-depth-lcm-v1-0 is not available on huggingface

### ISSUE THREAD

**Issue by YoucanBaby** [huggingface/diffusers#8371]
`prs-eth/marigold-depth-lcm-v1-0` is not available on huggingface 

So I think that the path of marigold in [Releases](https://github.com/huggingface/diffusers/releases) [v0.28.0](https://github.com/huggingface/diffusers/releases/tag/v0.28.0) is wrong. 

![image](https://github.com/huggingface/diffusers/assets/43912540/cf20020d-012f-43e6-bef1-7929f0a8c566)

**Comment by crapthings** [comment]
if you copy from doc, the path is wrong, try this

prs-eth/marigold-lcm-v1-0

**Comment by toshas** [comment]
It has been fixed now https://huggingface.co/prs-eth/marigold-depth-lcm-v1-0

**Comment by YoucanBaby** [comment]
> It has been fixed now https://huggingface.co/prs-eth/marigold-depth-lcm-v1-0

Thanks for your fix.
What is the difference between `prs-eth/marigold-lcm-v1-0` and `prs-eth/marigold-depth-lcm-v1-0` ?

**Comment by sayakpaul** [comment]
Closing the issue since it has been fixed now.

**Comment by toshas** [comment]
> Thanks a lot for your fix. What is the difference between `prs-eth/marigold-lcm-v1-0` and `prs-eth/marigold-depth-lcm-v1-0` ?

None, one is a redirect to the other
