### ISSUE TITLE
Flax pipeline: width and height are ignored

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#838]
### Describe the bug

`width` and `height` are passed to the generate function, and we do check that they are multiples of `8`, but then we always create the latents using the standard size.

### Reproduction

```Python
images = pipeline(prompt_ids, p_params, rng, width=448, height=832, jit=True)[0]
images.shape
# output: (8, 1, 512, 512, 3)
```

### System Info

Tested on TPU v3-8 with diffusers @ e48ca0f

**Comment by NightMachinery** [comment]
Does the model work with a custom resolution? Isn't it only trained on 512x512?

How high can we go on Colab's TPUs?

**Comment by patrickvonplaten** [comment]
Haven't tested the max resolution that's possible yet - would also be interested in such numbers :-)
