### ISSUE TITLE
StableDiffusionControlNetpaint destroying original image contrast and sharpness 

### ISSUE THREAD

**Issue by xalteropsx** [huggingface/diffusers#8392]
why controlnet paint destroy the original state of color contrast

**Comment by asomoza** [comment]
Hi, you're not giving information on what you're doing, the code you're using or even the result image. We can't helpyou if you don't provide some minimal reproducible example.

If I have to guess is that you're using the controlnet with too much strength, also the inpaint model does make the image a little less saturated depending on the denoise strength.

**Comment by asomoza** [comment]
The difference you see is mostly the vae decoding and encoding, this is a lossy process, no matter what you do you'll always lose some details. 

Also you're using an inpainting model with an inpaint controlnet. You don't really need both as they do the same thing. If you use the controlnet you will have to pass the whole image as a context and get a new one back, so it will be always different.

if you want to preserve the original image as much as possible use an inpainting model without the controlnet and use [padding_mask_crop ](https://huggingface.co/docs/diffusers/using-diffusers/inpaint#padding-mask-crop) which only changes the area of the mask.

**Comment by asomoza** [comment]
> padding_mask_crop is it divided by mask or by whole image like what is 32 if we place it on padding

Don't fully understand what you're trying to say, but when you enable the `padding_mask_crop`, the image gets cropped with the mask, upscaled, inpainted and then scaled down again to finally paste it over the same part of the image. 

The padding just tells how much space you want between the mask and the original image.

> also it doesnt support multi image?

yeah, I never use multi image with inpainting, and I wasn't here when it was implemented, but the logic probably is that is a task specific to each image so not that much need to make it multi image. 

I'm curious on what you're doing that requires the same inpainting for multiple images.
