### ISSUE TITLE
how can we load model to lora from singlefile ? 

### ISSUE THREAD

**Issue by xalteropsx** [huggingface/diffusers#8400]
pipe.load_lora_weights("lora/aesthetic_anime_v1s.safetensors")
  File "Z:\software\python11\Lib\site-packages\diffusers\loaders\lora.py", line 1230, in load_lora_weights
    raise ValueError("PEFT backend is required for this method.")
ValueError: PEFT backend is required for this method.

pipe.load_lora_weights("lora/aesthetic_anime_v1s.safetensors")

how can i use this model https://civitai.com/models/295100?modelVersionId=331598

**Comment by tolgacangoz** [comment]
[Install PEFT?](https://huggingface.co/docs/diffusers/main/en/tutorials/using_peft_for_inference)
