### ISSUE TITLE
Prompt Syntax Documentation

### ISSUE THREAD

**Issue by 9of9** [huggingface/diffusers#843]
**Is your feature request related to a problem? Please describe.**
I do not know what syntax I can use when typing a prompt in, e.g. weighting multiple prompts, negative weights etc.

**Describe the solution you'd like**
I would like documentation and/or tool-tips that explain what syntax is supported for modifying prompt strings.

**Describe alternatives you've considered**
These do not seem to be clearly documented anywhere currently, I have only seen occasional reference to this syntax in other issues and comments on the github.

**Comment by 9of9** [comment]
Posted on the wrong repo, doh!

**Comment by patrickvonplaten** [comment]
Hahah nooo :cry:  - Doc PRs are the best usually haha
