### ISSUE TITLE
ValueError when using `FromOriginalModelMixin` in subclasses

### ISSUE THREAD

**Issue by fkcptlst** [huggingface/diffusers#8440]
### Describe the bug

ValueError when using `FromOriginalModelMixin` in subclasses due to the following strict class check:

https://github.com/huggingface/diffusers/blob/83bc6c94eaeb6f7704a2a428931cf2d9ad973ae9/src/diffusers/loaders/single_file_model.py#L147-L151

Could it be possible to extend `from_single_file` to derived classes of `SINGLE_FILE_LOADABLE_CLASSES` too?

### Reproduction

Example:

```python
class MyVAE(AutoencoderKL):
    pass

MyVAE.from_single_file("xxx.safetensors")
```

### System Info

diffusers                   0.28.0

### Who can help?

@sayakpaul @DN6 @yiyixuxu

**Comment by DN6** [comment]
Hi @fkcptlst yeah I think we can make that addition. Would you like to open a PR for it? If not I can take care of it later this week.

**Comment by fkcptlst** [comment]
> Hi @fkcptlst yeah I think we can make that addition. Would you like to open a PR for it? If not I can take care of it later this week.

Hello, I opened a PR at #8454. Please review when you're available.

**Comment by DN6** [comment]
Hi @fkcptlst closing this since #8454 was merged to solve the issue.
