### ISSUE TITLE
backwards compatibility breaking change from sharded checkpoints

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#8443]
### Describe the bug

Since #7830 we have SDXL checkpoints sharded automatically, which did not happen before. These checkpoints are not loadable on earlier versions.

### Reproduction

I think all one has to do is load `from_pretrained()` and then `save_pretrained()`

### Logs

```shell
$ ls /home/user/training/lite-models/checkpoint-400/unet/
config.json  diffusion_pytorch_model-00001-of-00002.safetensors  diffusion_pytorch_model-00002-of-00002.safetensors  diffusion_pytorch_model.safetensors.index.json
```

### System Info

main git branch

### Who can help?

@sayakpaul as discussed

**Comment by DN6** [comment]
cc: @sayakpaul

**Comment by sayakpaul** [comment]
@DN6 please also see the linked PR :-)
