### ISSUE TITLE
Dreambooth class image generation fails if filename already exists

### ISSUE THREAD

**Issue by leszekhanusz** [huggingface/diffusers#846]
### Describe the bug

When it generates class images, the `train_dreambooth.py` script does not check if the filename already exists.
So it might overwrite an existing image with the same name, and in consequence not enough images are present in the folder and the script breaks later.

### Reproduction

This can happen for example if:
 - you generate a few class images with the script
 - you notice that a few of the pictures are blacked out by the nsfw script (`Potential NSFW content was detected in one or more images. A black image will be returned instead. Try again with a different prompt and/or seed`)
 - you stop the script and delete those black images manually
 - you start the script again

### System Info

diffusers 0.5.0.dev0

**Comment by patrickvonplaten** [comment]
@patil-suraj could you take a look here?

**Comment by patil-suraj** [comment]
Thanks a lot for the issue and PR @leszekhanusz , just reviewed it :)

**Comment by leszekhanusz** [comment]
Fixed in #847
