### ISSUE TITLE
StableDiffusion3Pipeline `from_pretrained` Exception

### ISSUE THREAD

**Issue by Beinsezii** [huggingface/diffusers#8488]
### Describe the bug

The pipe fails to load on component 5 using `from_pretrained`. Since the diffusers weights were just updated an hour ago, possibly the conversion is broken again like Cascade was?

I was typing this out in the #8483 but it was merged before I could submit it, lol.

### Reproduction

```python
from diffusers import StableDiffusion3Pipeline
pipe = StableDiffusion3Pipeline.from_pretrained('stabilityai/stable-diffusion-3-medium-diffusers')
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/beinsezii/Python/quickdif/diffusers/models/model_loading_utils.py", line 103, in load_state_dict
    file_extension = os.path.basename(checkpoint_file).split(".")[-1]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 171, in basename
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beinsezii/Python/quickdif/repro.py", line 2, in <module>
    pipe = StableDiffusion3Pipeline.from_pretrained('stabilityai/stable-diffusion-3-medium-diffusers')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beinsezii/Python/quickdif/venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/beinsezii/Python/quickdif/diffusers/pipelines/pipeline_utils.py", line 881, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/home/beinsezii/Python/quickdif/diffusers/pipelines/pipeline_loading_utils.py", line 703, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beinsezii/Python/quickdif/venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/beinsezii/Python/quickdif/diffusers/models/modeling_utils.py", line 831, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beinsezii/Python/quickdif/diffusers/models/model_loading_utils.py", line 115, in load_state_dict
    with open(checkpoint_file) as f:
         ^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### System Info

- 🤗 Diffusers version: 0.29.0.dev0
- Platform: Linux-6.9.3-arch1-1-x86_64-with-glibc2.39
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.12.3
- PyTorch version (GPU?): 2.3.1+rocm6.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.3
- Transformers version: 4.41.2
- Accelerate version: 0.31.0
- PEFT version: 0.11.1
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NA
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@DN6

**Comment by sayakpaul** [comment]
I think you first need to log in `huggingface-cli login` and make sure you have been granted access to the repo. We document all this in the documentation.

**Comment by Beinsezii** [comment]
I am, it downloaded the model. huggingface-cli even shows 30.8GB for `stabilityai/stable-diffusion-3-medium-diffusers`

**Comment by Beinsezii** [comment]
Fresh venv on Py311 instead of Py312, no change.

```sh
~/Python/python311/bin/python3.11 -m virtualenv venv311 --download
source ./venv311/bin/activate
pip install torch --index-url https://download.pytorch.org/whl/rocm6.0
pip install -U diffusers transformers huggingface_hub[cli]
huggingface-cli login
python repro.py
```

I'm not sure what else to try. Really don't feel like pulling a 40GiB Ubuntu+ROCm docker image for what looks like a just a pathing issue. I suppose I'll monkey with it some other time.

**Comment by ghunkins** [comment]
This issue in particular shows up if you do not have `accelerate` installed. Install `accelerate` to fix for now.

I believe it has to with the loading of chunked model files.

**Comment by Beinsezii** [comment]
Accelerate has its own much longer trace so I uninstalled it specifically to get a smaller more concise log. I can get the trace with accelerate when I get home.

**Comment by ghunkins** [comment]
It appears that the issue is the T5 text encoder. For now, loading without it is successful.

```python
pipe = StableDiffusion3Pipeline.from_pretrained(
  "stabilityai/stable-diffusion-3-medium-diffusers",
  text_encoder_3=None,
  tokenizer_3=None,
  torch_dtype=torch.float16
).to('cuda')
```

It might work with externally loading the T5 text encoder, yet to see.

**Comment by xhinker** [comment]
> It appears that the issue is the T5 text encoder. For now, loading without it is successful.
> 
> ```python
> pipe = StableDiffusion3Pipeline.from_pretrained(
>   "stabilityai/stable-diffusion-3-medium-diffusers",
>   text_encoder_3=None,
>   tokenizer_3=None,
>   torch_dtype=torch.float16
> ).to('cuda')
> ```
> 
> It might work with externally loading the T5 text encoder, yet to see.

I still got the follow error message:
```
RuntimeError: Error(s) in loading state_dict for SD3Transformer2DModel:
	Missing key(s) in state_dict: "pos_embed.pos_embed", ...
```

**Comment by Beinsezii** [comment]
Awesome. I'll validate in an hour or so as well.

**Comment by sayakpaul** [comment]
Yeah should work now.

**Comment by sayakpaul** [comment]
This snippet:

```python
import torch
from diffusers import StableDiffusion3Pipeline

pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float16)
pipe = pipe.to("cuda")

image = pipe(
    "A cat holding a sign that says hello world",
    negative_prompt="",
    num_inference_steps=28,
    guidance_scale=7.0,
).images[0]
image
```

Sorry for the trouble, folks. Appreciate the patience.

**Comment by xhinker** [comment]
@sayakpaul what is the cause, I should download the diffusers sd3 weight again, right?

**Comment by xhinker** [comment]
Oh, yes, thank you @sayakpaul 
![image](https://github.com/huggingface/diffusers/assets/7898116/c227ccd6-7e42-46ac-a26a-1b5f0b256cd1)

**Comment by sayakpaul** [comment]
Feel free to close if the issue is resolved.

**Comment by Beinsezii** [comment]
Confirmed working on both t2i and i2i with latest master branch.

> Sorry for the trouble, folks. Appreciate the patience.

I was right gobsmacked at v0.29.0 being cut minutes after the PR was merged instead of being left in main for at least a day or so. Pixart Sigma sat in main for like a month before having a release cut out.

**Comment by sayakpaul** [comment]
These are a little more nuanced and depend on the release dynamics, etc. For example, Hunyuan DiT was released just after it was merged.

**Comment by lihuining** [comment]
> ```python
> image = pipe(
>     "A cat holding a sign that says hello world",
>     negative_prompt="",
>     num_inference_steps=28,
>     guidance_scale=7.0,
> ).images[0]
> image
> ```

can you show the code the generate this cute cat? my generated image likes this 
![image](https://github.com/huggingface/diffusers/assets/69829672/2e3ef813-9374-4067-a7b7-29c73678878a)

**Comment by sayakpaul** [comment]
Cc: @asomoza

**Comment by asomoza** [comment]
> can you show the code the generate this cute cat? my generated image likes this

@lihuining, it's literally the same one from above:

```python
pipe = StableDiffusion3Pipeline.from_pretrained(
    "stabilityai/stable-diffusion-3-medium-diffusers",
    torch_dtype=torch.float16,
    token="your_token",
)
pipe = pipe.to("cuda")

image = pipe(
    "A cat holding a sign that says hello world",
    negative_prompt="",
    num_inference_steps=28,
    guidance_scale=7.0,
).images[0]

image.save("sd3_result.png")
```

The image you're getting is not one generated with SD3 or at least with all the text encoders, probably will be better if you post what you're doing and your environment so we can help you.

**Comment by rohis06-aws** [comment]
> This issue in particular shows up if you do not have `accelerate` installed. Install `accelerate` to fix for now.
> 
> I believe it has to with the loading of chunked model files.
> 
> ```shell
> pip install --upgrade accelerate
> ```
> 
> However, this [issue](https://github.com/huggingface/diffusers/issues/8493) still blocks the loading of SD3 even after the upgrade.

This worked for me. Thanks!
