### ISSUE TITLE
Allow configuring `shift=` for SD3 dynamically

### ISSUE THREAD

**Issue by isidentical** [huggingface/diffusers#8501]
**Is your feature request related to a problem? Please describe.**
Allow passing `shift=` per inference call (like timesteps) on the pipeline, for flow matching scheduler, or allow `set_shift()` etc. on the scheduler. This seems to be the key to getting good results with SD3 https://x.com/bfitzgerald242/status/1801018438120341911

**Comment by asomoza** [comment]
Hi, you can do it like this:

```python
from diffusers import  FlowMatchEulerDiscreteScheduler

pipe.scheduler = FlowMatchEulerDiscreteScheduler.from_config(pipe.scheduler.config, shift=3.0)
```

**Comment by isidentical** [comment]
yep! but the same format is applicable for timesteps and was wondering if we can get around without re-instating the scheduler again and again?

**Comment by asomoza** [comment]
Not for the moment, but I can see the potential in adding it as an argument if people change it a lot for each inference. 

In my experience it didn't fix the anatomy problems and sometimes it made the quality worse but I tested it with the T5, still need to test it without it and do some more generations.

Can you share some examples where changing the shift helped with the generation? That would help a lot.

**Comment by bghira** [comment]
the anatomy problems are from DPO safety alignment. it will require training to fix.

**Comment by hlky** [comment]
Useful to have, changing `shift` is popular with HunyuanVideo and SD3/Flux.

**Comment by bghira** [comment]
does it really help though? examples requested never were shared.

**Comment by hlky** [comment]
Documented benefit for HunyuanVideo.

https://github.com/huggingface/diffusers/blob/1524781b88ac1a082e755a030ba9d73cd6948e84/docs/source/en/api/pipelines/hunyuan_video.md?plain=1#L32

I'll run some tests for SD3/Flux to confirm.

**Comment by bghira** [comment]
but SD3 already has resolution-dependent shift using the `mu` calculations, right?

**Comment by hlky** [comment]
Actually this won't do anything for Flux because of dynamic shifting. We recently added support for dynamic shifting in SD3, it's not used by default though. Either way, it's a simple change that has at least some benefit to HunyuanVideo and it won't do any harm to add a function to change `shift` without creating the scheduler each time for those that want it.

**Comment by bghira** [comment]
well not to be argumentative but the schedulers are stateful, yes?  doesn't this mean recreating it has to be done anyway?
