### ISSUE TITLE
SD3 medium model Generate 512x512 image 

### ISSUE THREAD

**Issue by pandora523** [huggingface/diffusers#8502]
### Describe the bug

When trying to generate image from diffusers I just notice the image is kinda flop and idid try saved the image and the resolution is 512x512
<img width="1280" alt="Screenshot 2024-06-13 at 8 53 08" src="https://github.com/huggingface/diffusers/assets/131154780/13fd884d-becf-4886-a94f-f4d0da7af5ef">
![Labrador_in_the_style_of_Vermeer](https://github.com/huggingface/diffusers/assets/131154780/1178ad4b-d05e-408d-b217-3c234d871c1d)

### Reproduction

by generating image the result image is on 512x512 resolution

### System Info

v1.5 on the App Store

**Comment by asomoza** [comment]
Hi, it seems this is not a diffusers issue since you're using an UI on top of it. With diffusers you can change the width and height:

```python
image = pipe(
        prompt=prompt,
        negative_prompt="",
        num_inference_steps=28,
        height=1024,
        width=1024,
        guidance_scale=4.5,
        generator=generator,
    ).images[0]
```

Also the default is 1024x1024, so the UI you're using is changing this to 512px.

**Comment by pcuenca** [comment]
Thanks @pandora523, the diffusers pipeline works fine, so closing this in favor of https://github.com/huggingface/swift-coreml-diffusers/issues/95.
