### ISSUE TITLE
diffusers 0.5.1 crashs on MPS with unexpected keyword argument 'device_map' error

### ISSUE THREAD

**Issue by FahimF** [huggingface/diffusers#852]
### Describe the bug

Trying to run Stable Diffusion code with the default scheduler and it simply crashes out every single time with the following error:

```
Traceback (most recent call last):
  File "/Users/fahim/Code/Python/sd-gui/test.py", line 6, in <module>
    pipe = StableDiffusionPipeline.from_pretrained("stable-diffusion-v1-4").to(device)
  File "/Users/fahim/miniconda3/envs/ml/lib/python3.9/site-packages/diffusers/pipeline_utils.py", line 517, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/Users/fahim/miniconda3/envs/ml/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1843, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'device_map'
```

### Reproduction

Just run the following code:

```
import torch
from diffusers import StableDiffusionPipeline

device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
pipe = StableDiffusionPipeline.from_pretrained("stable-diffusion-v1-4").to(device)
prompt = "an elf sitting on a toadstool"
result = pipe(prompt)
image = result["sample"][0]
```

### System Info

macOS Monterey 12.6
Apple M1 Max 32GB
diffusers 0.5.1

**Comment by vvsotnikov** [comment]
I have the same issue with diffusers 0.5.1 and pytorch 1.14.0.dev20221014.

**Comment by klyuhang9** [comment]
I meet the same issue with diffusers 0.5.1 ,pytorch 1.11.0

**Comment by dkackman** [comment]
Don't think it's specific to MPS. Getting the same on a Ryzan/NVIDIA combo

**Comment by patrickvonplaten** [comment]
Hey @FahimF,

Thanks a lot for the issue! Could you try updating your `transformers` version here? 
Also see: https://github.com/huggingface/diffusers/issues/859 

I'll now also open a PR to prevent this for lower transformers versions

**Comment by FahimF** [comment]
@patrickvonplaten Upgrading to the the latest transformers did the trick. Thanks!
