### ISSUE TITLE
SD3 - MPS - Passing `scale` via `joint_attention_kwargs` when not using the PEFT backend is ineffective.

### ISSUE THREAD

**Issue by TEGNoV** [huggingface/diffusers#8526]
### Describe the bug

While executing the code I get the following remark for MPS:
Passing `scale` via `joint_attention_kwargs` when not using the PEFT backend is ineffective.

### Reproduction

import torch
from diffusers import StableDiffusion3Pipeline

pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers", 
        torch_dtype=torch.float16 , 
        text_encoder_3=None,
        tokenizer_3=None)
pipe = pipe.to("mps")

image = pipe(
    "Mountainscapes, Intimate Landscapes, Stock Photo, Mountain Peaks, Empty Canvas, Blue Horizon, Serene Landscape, Canvas, Snowy Mountains, Tranquil Scene, Copy Spaces  high resolution",
    negative_prompt="",
    num_inference_steps=28,
    guidance_scale=7.0,
).images[0]
image

image.save(args.output)

### System Info

Latest diffusers from source
M1 Macbook

**Comment by bghira** [comment]
@pcuenca

**Comment by yiyixuxu** [comment]
should already be fixed by this https://github.com/huggingface/diffusers/pull/8496

**Comment by DN6** [comment]
Can we close this since #8496  has been merged?

**Comment by pcuenca** [comment]
I think so! Closing, please @bghira feel free to reopen if necessary :)
