### ISSUE TITLE
how to add controlnet in sd3!

### ISSUE THREAD

**Issue by appleyang123** [huggingface/diffusers#8527]
I currently use inpainting controlnet in sdxl because it uses unet to easily support controlnet. And I am curious about how to add controlnet in sd3 with transforms model structure.

**Comment by haofanwang** [comment]
Check this [PR](https://github.com/huggingface/diffusers/pull/8566).

**Comment by jadechip** [comment]
@haofanwang do guys also have the training code for sd3 control net available somewhere? Thank you for your hard work 🙏

**Comment by appleyang123** [comment]
Yes, i also need the training code. Very thanks~

**Comment by iariav** [comment]
Would also really appreciate a training script, same as for SD 1.5 and sdxl

**Comment by jeromepatel** [comment]
Any updates on training script of SD3 Controlnet ?

**Comment by DavyMorgan** [comment]
Hi everyone, I’ve implemented a training script at https://github.com/huggingface/diffusers/pull/9249. I would really appreciate it if someone could review it when they have time. Thanks!
