### ISSUE TITLE
sd3 clip-merge in diffusers

### ISSUE THREAD

**Issue by s9anus98a** [huggingface/diffusers#8529]
how to do clip merge in diffusers?

**Comment by sayakpaul** [comment]
What is CLIP merge? @asomoza

**Comment by asomoza** [comment]
I also don't know, we need a more information about what do you need.

**Comment by s9anus98a** [comment]
i mean replacing clip text encoder to t5

**Comment by asomoza** [comment]
oh but you already asked that in [here](https://github.com/huggingface/diffusers/discussions/7749). 

The short answer is you can't, The T5 is a completely different model architecture.
