### ISSUE TITLE
Conversion script for SD3 Diffusers Lora to original

### ISSUE THREAD

**Issue by alarazin** [huggingface/diffusers#8530]
Will you be providing a script to convert SD3 lora trained with diffusers to the original version, similar to  convert_state_dict_to_kohya? Thanks.

**Comment by asomoza** [comment]
Hi, we need to wait for kohya or the other trainers to publish their training code and for people to train loras with them before this.

Probably will be faster to ask where you want to load them to do the conversion.

**Comment by sayakpaul** [comment]
Once Kohya is done with scripts, will look into the support. Until then this issue is closed.
