### ISSUE TITLE
SD3 dreambooth example - gradient checkpointing fails

### ISSUE THREAD

**Issue by Carolinabanana** [huggingface/diffusers#8543]
### Describe the bug

When using the SD3 dreambooth LORA script with all default arguments except for gradient checkpointing, the script fails with an error that a tensor is expected, not a tuple. I have raised a PR to fix this: 

https://github.com/huggingface/diffusers/pull/8542

### Reproduction

SD3 dreambooth LORA script with all default arguments except for gradient checkpointing enabled

### System Info

Latest diffusers git pull

**Comment by AmericanPresidentJimmyCarter** [comment]
Dup of https://github.com/huggingface/diffusers/issues/8503
