### ISSUE TITLE
Latent Consistency Model Possible Scaling Bug

### ISSUE THREAD

**Issue by dg845** [huggingface/diffusers#8547]
### Describe the bug

The LCM scheduler and LCM training scripts use the following formula for the $`c_{\mbox{out}}(t)`$ scaling (ignoring timestep scaling):

```math
c_{\mbox{out}}(t) = \frac{t}{\sqrt{t^2 + \sigma_{\mbox{data}}^2}}
```

However, the [original consistency models paper](https://arxiv.org/pdf/2303.01469) and the [EDM paper](https://arxiv.org/pdf/2206.00364) use

```math
c_{\mbox{out}}(t) = \frac{t \cdot \sigma_{\mbox{data}}}{\sqrt{t^2 + \sigma_{\mbox{data}}^2}}
```

where we have $`t`$ rather than $`t - \epsilon`$ in the numerator since the [LCM paper](https://arxiv.org/pdf/2310.04378) specifies that $`c_{\mbox{out}}(0) = 0`$ rather than $`c_{\mbox{out}}(\epsilon) = 0`$ (see Eq. 9). That is, the two differ by a factor of $\sigma_{\mbox{data}}$. Is this a bug or an intentional design choice in LCM? (The LCM paper does not specify the exact $`c_{\mbox{out}}(t)`$ used, but the [LCM repo](https://github.com/luosiallen/latent-consistency-model) implementation is consistent with the `diffusers` implementation.) [See also https://github.com/luosiallen/latent-consistency-model/issues/82#issuecomment-1894828085 from the LCM repo.]

### Reproduction

The LCM scheduler code is

https://github.com/huggingface/diffusers/blob/39aa3909e8e2dfe30f4807aedaadf42c1d8b1a8f/src/diffusers/schedulers/scheduling_lcm.py#L495

and the LCM training script code is

https://github.com/huggingface/diffusers/blob/39aa3909e8e2dfe30f4807aedaadf42c1d8b1a8f/examples/consistency_distillation/train_lcm_distill_lora_sdxl_wds.py#L354

Note that this is consistent with the original implementation:

https://github.com/luosiallen/latent-consistency-model/blob/a9ad79587cc8bd1e404ccd1a3056a3da969b2f62/LCM_Training_Script/consistency_distillation/train_lcm_distill_lora_sdxl_wds.py#L339

so it's not obvious that this is a bug.

### System Info

N/A

### Who can help?

@sayakpaul 
@yiyixuxu 
@luosiallen

**Comment by dg845** [comment]
Actually, "bug" might not be the right characterization - because LCM checkpoints were trained with

```math
c_{\mbox{out}}(t) = \frac{t}{\sqrt{t^2 + \sigma_{\mbox{data}}^2}}
```

rather than the $`\sigma_{\mbox{data}}`$-scaled version, the `LCMScheduler` code is doing the right thing by applying the same parameterization at inference time. I guess it's more of a question of whether future LCM models should be trained with the $`\sigma_{\mbox{data}}`$-scaled version (and it's possible that the exact form of $`c_{\mbox{out}}`$ doesn't really impact the model that much, rendering this question mostly moot).

**Comment by luosiallen** [comment]
This is intentionally designed to ensure boundary condition.

**Comment by luosiallen** [comment]
If you consider the case when t is really large, the current $c_out(t)$ will close to 1

**Comment by dg845** [comment]
I see, thanks!

**Comment by haohang96** [comment]
Hi, I have some other questions related to $c_{skip}$ and $c_{out}$:

1. In the code of LCM, before computing $c_{skip}$ and $c_{out}$, the $timestep$ is scaled by timestep_scaling=10. such operation makes $c_{skip} \approx 0$ and $c_{out} \approx 1$ for any $t > 0$. The original CM paper does not use such a timestep_scaling option. I want to know why LCM needs to set timestep_scaling=10, in other words, what's the motivation for setting $c_{out}(t>0) \approx 1$ and $c_{skip}(t>0) \approx 0$. Why not use CM's formulation directly?

2. Why the $\sigma_{data}$ is ignored in $c_{out}$. I do not understand the explanation of @luosiallen very well.  Even using the formulation of original CM: $c_{out}(t) = \frac{t \cdot \sigma_{data}}{\sqrt{t^2 + \sigma^2_{data}}}$, we can still ensure $c_{out}(t=0)=0$, which already satisfies the boundary condition.

**Who can help?**
@luosiallen 
@dg845

**Comment by byronyi** [comment]
Same question here. Gently ping @luosiallen @tyq1024
