### ISSUE TITLE
When will train_text_to_image_lora_sd3 release?

### ISSUE THREAD

**Issue by Rody1911641** [huggingface/diffusers#8553]
Thank you so much for your excellent work and selfless open source spirit. I wonder that when will train_text_to_image_lora_sd3 release?

**Comment by jloveric** [comment]
Looking forward to this as well!

**Comment by AmericanPresidentJimmyCarter** [comment]
Works on https://github.com/bghira/SimpleTuner

```
>>> pipe.load_lora_weights('ptx0/sd3-lora-test')
>>> image = foo(
...     prompt="a lion singing in the shower",
...     num_inference_steps=30,
...     guidance_scale=5.5
... ).images[0]
100%|███████████████████████████████████████████| 30/30 [00:25<00:00,  1.16it/s]
>>> image.save('lion.png', format='PNG') 
```

**Comment by sayakpaul** [comment]
Yeah please refer to https://github.com/bghira/SimpleTuner for this.

**Comment by BJQ123456** [comment]
I would like to ask if it is possible to slightly modify Dreambooth's SD3.0 code to be used for the entire training of SD3.0? Are there any special considerations to keep in mind?Thanks

**Comment by Rody-NKCS** [comment]
To be honest, I have tried to do this and the pictures generated after training are incorrect and full of noise. My guess is that DreamBooth+lora and lora only fine-tune the network parameters differently.
