### ISSUE TITLE
[SD3] [Feature Request] FP8 and Availability of Text Encoder training

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [huggingface/diffusers#8555]
**Is your feature request related to a problem? Please describe.**
Current training scripts use a significant amount of VRAM. Since the T5 text encoder  takes up most of it, I would like to be able to choose whether or not to learn here.

Also, an option to load models in FP8 and reduce VRAM usage would be appreciated as it would lower the learning threshold
**Describe the solution you'd like.**
Additional options such as --fp8, --no-text-encoder, etc.

**Comment by sayakpaul** [comment]
Will give it a couple more days to see if text encoder training really adds any benefits actually. 

For FP8 part, ccing @dacorvo

**Comment by Bocchi-Chan2023** [comment]
I requested it because SAI employees had told us that we did not need training the T5 encoder :3
My ideal implementation would be as follows!
https://github.com/kohya-ss/sd-scripts/commit/e5268286bf90ddcc53ad1deb31aba857cfa967d5#diff-dbef1542a3749449a2f6040f6d04fce5c62232858c4bf25996697c5cf39881edR151

**Comment by sayakpaul** [comment]
We support text encoder training with SD3 LoRA. 

FP8 can be tried out from `quanto`. https://github.com/huggingface/diffusers/issues/6500
