### ISSUE TITLE
Is the training objective for SD3 correct?

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [huggingface/diffusers#8567]
### Describe the bug

![Screenshot_2024-06-15_00-14-38](https://github.com/huggingface/diffusers/assets/110263573/23a40893-8e27-4b3e-8775-ce395aa1e88a)

The input to the `v` term is `noisy_model_input = sigmas * noise + (1.0 - sigmas) * model_input`, but by the [paper](https://arxiv.org/abs/2209.03003):

- `v(tx_1 + (1-t)x_0) ` where `x_1` is gt, `x_0` is input noise `randn_like(x1)`
- The term we do prediction on is then `tx_1 + (1-t)x_0` or `noisy_model_input = sigmas * model_input + (1.0 - sigmas) * noise`

Please ensure that the objective is being calculated correctly, because when we trained on the original objective with all the parameters unfrozen it seemed to wreck the model. There may be some other bug though.

### Reproduction

Train dreambooth or anything

### System Info

linux

**Comment by zhuole1025** [comment]
Actually, I think the prediction of sd3 is parametrized as `v=x1-x0`, where `x1` is noise and `x0` is clean data.

**Comment by AmericanPresidentJimmyCarter** [comment]
Yes, x_0 should be GT and x_1 should be noise, I had it backwards, so I think it is correct then.
