### ISSUE TITLE
ValueError: Checkpoint not supported because layer lora_unet_label_emb_0_0.alpha not supported.

### ISSUE THREAD

**Issue by s9anus98a** [huggingface/diffusers#8581]
script to produce error:
```

import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16,
).to('cuda')

pipe.load_lora_weights("ostris/sdxl-sd1-vae-lora")

```

**Comment by asomoza** [comment]
That lora is very experimental and does something really specific, the author hasn't published any documentation with it. You'll need to wait for the author to provide example code or instructions to be able to use it.

**Comment by jiangtaozh** [comment]
how is this solved? Checkpoint not supported because layer lora_unet_label_emb_0_0.alpha not supported.

**Comment by asomoza** [comment]
Hi @jiangtaozh , did it get updated? I still see the `coming soon` and no info on how to use it. Also it has 17 downloads in a month, so it's not that popular it seems. To answer the question, it hasn't been solved because of the previous reasons.

**Comment by jiangtaozh** [comment]
since lora_unet_label_emb_0_0.alpha is just a float value, when loading the lora, if it is not able to read it, just have a default value, and then print some warning, should be good?

**Comment by jiangtaozh** [comment]
> Hi [@jiangtaozh](https://github.com/jiangtaozh) , did it get updated? I still see the `coming soon` and no info on how to use it. Also it has 17 downloads in a month, so it's not that popular it seems. To answer the question, it hasn't been solved because of the previous reasons.

is there a workaround?

**Comment by asomoza** [comment]
oh sorry I missed this, about:

> since lora_unet_label_emb_0_0.alpha is just a float value, when loading the lora, if it is not able to read it, just have a default value, and then print some warning, should be good?

you mean for us to do it? Usually when there's an issue about a lora we don't support, if it's popular, mostly meaning that it comes from a library like kohya and similar ones, we do the support and the conversion when loading it, but this case is very special, since it's just one lora that does a specific thing that didn't catch that much interest in the community, you can also add that the author didn't update it and moved on to other projects.

> is there a workaround?

yes, the one you mentioned or you can also remove the alpha from the lora which could be easier to do.

**Comment by jiangtaozh** [comment]
"it comes from a library like kohya and similar ones, we do the support and the conversion when loading it" do you use self-developed tool or community tool for the kohya conversion to diffuser compatible format? if you can share it out, that would be great.

**Comment by asomoza** [comment]
sure, I don't use a specific one but all the lora conversion logic from diffusers is in this [file](https://github.com/huggingface/diffusers/blob/main/src/diffusers/loaders/lora_conversion_utils.py). There are specific formats conversion and for each architecture in there, so it's quite big.

**Comment by jiangtaozh** [comment]
is there any tool can convert comfyui lora format to diffuser format?
