### ISSUE TITLE
SD3 diffusers/scripts/convert_diffusers_to_original_sd3.py is missing

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [huggingface/diffusers#8588]
### Describe the bug

The repository is missing conversion from diffusers to original for SD3: diffusers/scripts/convert_diffusers_to_original_sd3.py

### Reproduction

The repository is missing conversion from diffusers to original for SD3: diffusers/scripts/convert_diffusers_to_original_sd3.py

### System Info

Any system

### Who can help?

@yiyixuxu @DN6 @sayakpaul

**Comment by sayakpaul** [comment]
Cc: @DN6

**Comment by a-l-e-x-d-s-9** [comment]
Any updates?

**Comment by yiyixuxu** [comment]
it's added now https://github.com/huggingface/diffusers/blob/main/scripts/convert_sd3_to_diffusers.py

**Comment by Tophness** [comment]
You added a SD3 to diffusers, but the issue was about diffusers to SD3, which is what I currently need.

**Comment by sayakpaul** [comment]
I am not sure we will have the circles to work on that.
