### ISSUE TITLE
controlnet singlefile dont have config.json 

### ISSUE THREAD

**Issue by xalteropsx** [huggingface/diffusers#8614]
```py

    controlnets = ControlNetModel.from_single_file(zzzz/diffusers_xl_depth_full.safetensors, torch_dtype=torch.float16)                                        
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                         
  File "Z:\software\python11\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn                   
    return fn(*args, **kwargs)                                                                                                 
           ^^^^^^^^^^^^^^^^^^^                                                                                                 
  File "Z:\software\python11\Lib\site-packages\diffusers\loaders\single_file_model.py", line 247, in from_single_file          
    diffusers_model_config = cls.load_config(                                                                                  
                             ^^^^^^^^^^^^^^^^                                                                                  
  File "Z:\software\python11\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn                   
    return fn(*args, **kwargs)                                                                                                 
           ^^^^^^^^^^^^^^^^^^^                                                                                                 
  File "Z:\software\python11\Lib\site-packages\diffusers\configuration_utils.py", line 411, in load_config                     
    raise EnvironmentError(                                                                                                    
OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

**Comment by asomoza** [comment]
Hi, there's seems to be a confusion here, you're trying to use a SDXL controlnet with a SD1.5 model, they're not compatible. 

Also the error you're getting is not about the controlnet but of the base model:

```
OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.  
```

**Comment by asomoza** [comment]
No you're right, there's something weird happening in the error that tries to load it as a SD 1.5. I know that repo, they just grouped together the diffusers controlnet with the other ones, these aren't single file format they're the the normal diffusers one.

You'll need to use the real ones from the original repos with `from_pretrained`:

https://huggingface.co/collections/diffusers/sdxl-controlnets-64f9c35846f3f06f5abe351f

The reason why they work in the UIs it's because they hard code the config files and we don't do that.

**Comment by asomoza** [comment]
I saw a very experimental project with the vae thing, I haven't seen any results yet.

About the LoRA there's also one project about that, that lets you use SD1.5 loras with SDXL but the results weren't good, mainly because all SD 1.5 LoRAs are trained with 512 or 768 images and that makes bad generations with SDXL:

**Comment by asomoza** [comment]
This is the one that allows to use 1.5 LoRAs: https://github.com/showlab/X-Adapter

**Comment by hjj-lmx** [comment]
> @asomoza
> 
> ```python
> import torch
> from diffusers import (
>     ControlNetModel,
>     StableDiffusionXLControlNetPipeline,
>     StableDiffusionXLInpaintPipeline,DPMSolverMultistepScheduler
> )
> 
> controlnets = ControlNetModel.from_single_file('Z:/aiutils/diffusers_xl_depth_full.safetensors', torch_dtype=torch.float16,variant="fp16")
> pipeline = StableDiffusionXLControlNetPipeline.from_single_file(
>     'models/dreamshaperXL_v21TurboDPMSDE.safetensors', torch_dtype=torch.float16, variant="fp16", controlnet=controlnets
> ).to("cuda")
> ```

Is the control net model corresponding to sdxl being passed in, or is it reported on sd1.5? What is the situation


# 加载预训练的 ControlNet 模型
        controlnet_model = os.path.join(hub_dir, "checkpoints\\StableDiffusionXL\\controlnet\\diffusion_pytorch_model.fp16.safetensors")
        controlnet = ControlNetModel.from_single_file(controlnet_model, torch_dtype=torch.float16)

**Comment by asomoza** [comment]
That is a SDXL diffusers controlnet that's being loaded as a `from_single_file` which is wrong and can't be used with diffusers that way. You'll need either to load a diffusers controlnet with the config file or use a original controlnet checkpoint.

**Comment by hjj-lmx** [comment]
> from_single_file
想使用from_single_file加载本地已下载的sdxl版本的controlnet模型，该怎么写，服务器上没有翻墙

**Comment by asomoza** [comment]
> from_single_file
If you want to use from_single_file to load the SDXL version of the controlnet model that you downloaded locally, how do you copy it? There is no translation wall on the server.

I translated your question, doesn't seem to be the correct translation but, to be able to use `from_single_file` with controlnet you need to first find a controlnet that's not in the diffusers format, for example [this ones](https://huggingface.co/lllyasviel/ControlNet-v1-1). 

I must insist again, you can't use `from_single_file` with a diffusers format controlnet, even if someone copies it to a repository and doesn't include the corresponding config file.

Also we appreciate if in the future if you can ask the questions in english so everyone can understand, also it makes it easier for us and you'll probably get an answer faster.
