### ISSUE TITLE
Inference fix needed (ASAP)

### ISSUE THREAD

**Issue by wcarletsdrive** [huggingface/diffusers#863]
Has anyone done nerdy rodent's install? It works but I get this at the end and my shell is this as followed in his tutorial 

export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="training"
export OUTPUT_DIR="classes"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=2 --gradient_checkpointing \
  --use_8bit_adam \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --mixed_precision="no" \
  --max_train_steps=400

https://pastebin.com/uE1WcSxD (His instructions and I watched his video titled "Train on Your Own face - Dreambooth, 10GB VRAM, 50% Faster, for FREE!")
![Nerdy Rodent Help](https://user-images.githubusercontent.com/110745584/196099892-ce96c990-714c-497d-a04a-290acd39a173.PNG)

**Comment by patrickvonplaten** [comment]
cc @patil-suraj, but this seems like it depends on other libraries that just `diffusers`
