### ISSUE TITLE
Integrate Lumina-T2X

### ISSUE THREAD

**Issue by PommesPeter** [huggingface/diffusers#8641]
### Model/Pipeline/Scheduler description

Lumina-T2X is a text-to-any generation model. Our model is capable of generating multiple modalities, most notably image generation. Currently, our image generation supports any resolution, achieving stunning results. We will unify various modalities and integrate them into diffusers, including controlnet, Lora fine-tune, compositional generation, etc.

Paper: [Lumina-Next](https://github.com/Alpha-VLLM/Lumina-T2X/blob/main/assets/lumina-next.pdf)
Paper: [Lumina-T2X](https://arxiv.org/abs/2405.05945)

![image](https://github.com/huggingface/diffusers/assets/54879512/6d032c97-3308-40b0-a41d-4a0cbd799170)

### Open source status

- [x] The model implementation is available.
- [x] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

Weight v1: https://huggingface.co/Alpha-VLLM/Lumina-Next-T2I
Weight v2: https://huggingface.co/Alpha-VLLM/Lumina-Next-SFT
Code: https://github.com/Alpha-VLLM/Lumina-T2X/
HF Space: https://huggingface.co/spaces/Alpha-VLLM/Lumina-Next-T2I

**Comment by PommesPeter** [comment]
We currently prepare our code to integrate diffusers.

**Comment by xhinker** [comment]
This model is SO cool

**Comment by yiyixuxu** [comment]
@PommesPeter look forward to the PR!

**Comment by PommesPeter** [comment]
PR here: https://github.com/huggingface/diffusers/pull/8652

**Comment by a-r-r-o-w** [comment]
I think we can close this since Lumina has been integrated. Thanks @PommesPeter!
