### ISSUE TITLE
The behavior of safety_checker is ambiguous.

### ISSUE THREAD

**Issue by klae01** [huggingface/diffusers#866]
I need information about which embeddings the safety_checker's concept_embeds have.

The 3 vectors in concept_embeds feel like they're not enough to work as a filtering.
I think the current safety_checker isn't enough to isolate the brutal or gore images.
How about adding an explicit runtime computed embedding for these "bad_concepts"?
Closing these filtering algorithms as a black box doesn't help much.
Can you provide some information on what criteria you are creating concept_embeds_weights on?

what does 3 vectors in concept_embeds correspond to?
And what does 17 vectors in special_care_embeds correspond to?

Can I add a feature to make up for the lack of filtering?

The design I am trying to implement will be generate `bad_concept` and `normal_concept` embeddings generated through the text model from multiple texts, and to interpret whether the new input corresponds to `bad_concept` based on the distance between the `normal_concept` and `bad_concept` embeddings.

**Comment by patrickvonplaten** [comment]
Hey @klae01,

Here an issue that should help regarding what concepts were used: https://github.com/huggingface/diffusers/issues/476

In short, it was the stability AI team chose these concepts. Yes, I think you should definitey be able to add new features to the safety checker - do you want to open a PR for this maybe?

**Comment by woctezuma** [comment]
Hello,

I have read:
- https://github.com/huggingface/diffusers/issues/476

which provides a link to the answer:
- https://github.com/LAION-AI/CLIP-based-NSFW-Detector/blob/main/safety_settings.yml

I would like to point out that this piece of information was a bit difficult to find.
Without it, it was a bit weird to see that there were special concepts in another loop.

https://github.com/huggingface/diffusers/blob/4684ea2fe8d568f44c491068c3eb94aac27045f3/src/diffusers/pipelines/stable_diffusion/safety_checker.py#L67-L73

https://github.com/huggingface/diffusers/blob/4684ea2fe8d568f44c491068c3eb94aac27045f3/src/diffusers/pipelines/stable_diffusion/safety_checker.py#L75-L80

Now, it makes sense that these would increase the "adjustment" variable.

https://github.com/huggingface/diffusers/blob/4684ea2fe8d568f44c491068c3eb94aac27045f3/src/diffusers/pipelines/stable_diffusion/safety_checker.py#L63C1-L65

https://github.com/huggingface/diffusers/blob/4684ea2fe8d568f44c491068c3eb94aac27045f3/src/diffusers/pipelines/stable_diffusion/safety_checker.py#L63-L80

I understand that there was [a fear of reverse-engineering](https://huggingface.co/CompVis/stable-diffusion-v1-4#safety-module), though it is a bit difficult to understand. I imagine the issue would be someone trying to generate NSFW images which would evade the hard-coded "concepts".

> This checker works by checking model outputs against known hard-coded NSFW concepts. The concepts are intentionally hidden to reduce the likelihood of reverse-engineering this filter.

Anyway, after reading all of this, I might settle for a more recent filter, such as:
- https://huggingface.co/Falconsai/nsfw_image_detection

I wrote this here in case someone else gets in this thread after a Google search, and I did not want to ping all the people in:
- https://github.com/huggingface/diffusers/issues/476
