### ISSUE TITLE
AnimateDiff bug not sure if it use adapter or not 

### ISSUE THREAD

**Issue by xalteropsx** [huggingface/diffusers#8663]
s import Transformer2DModelOutput`, instead.                                                                                                                                             
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)                                                                                                                    
The config attributes {'motion_activation_fn': 'geglu', 'motion_attention_bias': False, 'motion_cross_attention_dim': None} were passed to MotionAdapter, but are not expected and will be ignored. Please verify your config.json configuration file.                                                                                                                                                            
Loading pipeline components...:  83%|███████████████████████████████████████████████████████▊           | 5/6 [00:08<00:02,  2.51s/it]Z:\software\python11\Lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.                                                                                                                                                                                  
  warnings.warn(                                                                                                                                                                         
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████| 6/6 [00:08<00:00,  1.41s/it]                                                   
The config attributes {'center_input_sample': False, 'flip_sin_to_cos': True, 'freq_shift': 0, 'mid_block_type': 'UNetMidBlock2DCrossAttn', 'only_cross_attention': False, 'dropout': 0.0, 'attention_head_dim': 8, 'dual_cross_attention': False, 'class_embed_type': None, 'num_class_embeds': None, 'upcast_attention': None, 'resnet_time_scale_shift': 'default', 'resnet_skip_time_act': False, 'resnet_out_scale_factor': 1.0, 'time_embedding_type': 'positional', 'time_embedding_dim': None, 'time_embedding_act_fn': None, 'timestep_post_act': None, 'conv_in_kernel': 3, 'conv_out_kernel': 3, 'attention_type': 'default', 'class_embeddings_concat': False, 'mid_block_only_cross_attention': None, 'cross_attention_norm': None, 'addition_embed_type_num_heads': 64} were passed to UNetMotionModel, but are not expected and will be ignored. Please verify your config.json configuration file. 
 keep getting this warning whatever model i load 

have u guys tested or ur animatediffpipeline with other sd model ?  i tried 2 different model and this error reproduce

**Comment by sayakpaul** [comment]
Can you please provide a reproducible code snippet? 

And I am not sure what exactly you're trying to report. The traces include some deprecation warnings which are safe to ignore in this case.

**Comment by sayakpaul** [comment]
This warning for the users to know about. You safely disable the warnings if you'd like: https://huggingface.co/docs/diffusers/en/api/logging
