### ISSUE TITLE
need a download folder button

### ISSUE THREAD

**Issue by xalteropsx** [huggingface/diffusers#8665]
https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main

the problem with git clone 

it download the file 4time size of original size and disk usage  is also spammed 
please consider provide an single download button on website itself 

need to avoid uses of git cli

**Comment by sayakpaul** [comment]
This is more of a Hugging Face Hub issue. Cc: @Pierrci from the Hub team.

**Comment by yiyixuxu** [comment]
you can download it if you just click on the checkpoint https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/unet/diffusion_pytorch_model.fp16.safetensors

it tells you
> This file is stored with [Git LFS](https://git-lfs.github.com/) . It is too big to display, but you can still [download](https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/unet/diffusion_pytorch_model.fp16.safetensors) it.

**Comment by Pierrci** [comment]
@xalteropsx you might want to look at https://huggingface.co/docs/huggingface_hub/en/guides/cli#huggingface-cli-download - contrary to `git`, using the HF CLI won't "spam" your disk usage (cc @Wauplin)

**Comment by asomoza** [comment]
`diffusers` uses the `huggingface_hub` library for the download, you can use a `cache-dir` configuration to specify a custom cache, but it will still have the structure you're mentioning.

This is just my opinion, but you're seeing the huggingface hub is something like just a stable diffusion model gallery download, like civitai, but the hub hosts a lot of more stuff than single file checkpoints and it's used for big projects where this format is a must, like for downloading just the latest changes on a dataset without the need to download 2 TB of data again or changing to specific versions of the checkpoints in a fast and easy way for training and validation.

Also the download folder button suggested doesn't work for all instances, for example, the [official single file checkpoint repo for SD3](https://huggingface.co/stabilityai/stable-diffusion-3-medium/tree/main) it's like a 50 GB download if you do that and the diffusers repos most of the time have a full precision and fp16 format checkpoints so you will get a unnecessary big files.

The drawback of not using git (blob format) for a normal user that comes from the UIs is none, you're probably used to manipulate the checkpoints manually and to download the complete checkpoint  for every version update again manually. But precisely that is the benefit of it, to avoid the need to do that, it's like you ask github to stop using git and ask every developer to always re-download the zip of the repos to update it.
