### ISSUE TITLE
Attention api changes no documentation ? 

### ISSUE THREAD

**Issue by xalteropsx** [huggingface/diffusers#8666]
how can i see ur previous changes on attention ? 

u have rename`` _slice_size , _sliced_attention and _attention``  attribute from attention 

need to know what are alternative using of its ?

**Comment by sayakpaul** [comment]
Can you please link to the point of code you're referring to?

**Comment by sayakpaul** [comment]
If you are using attention slicing, it's here: https://github.com/huggingface/diffusers/blob/f1f542bdd4412a97ac109dab22959a8a575f3a7e/src/diffusers/models/attention_processor.py#L1928. 

Also, you were relying on pseudo-private attributes of that `Attention` class, which, by definition, are not guaranteed to be backward-compatible.
