### ISSUE TITLE
SD3 + SDXL refine fix lying on grass. How to do in diffusers colab workflow?

### ISSUE THREAD

**Issue by s9anus98a** [huggingface/diffusers#8693]
this is comfy workflow 
![GQQC1T-aUAAXRDI](https://github.com/huggingface/diffusers/assets/151509142/15e3c420-3e14-4476-8a1a-4001934af158)

how can i do in diffusers colab workflow?

**Comment by asomoza** [comment]
Hi, the SD3 pipeline still doesn't have `denoising_end` which is what you'll need to be able to do what you want.

**Comment by asomoza** [comment]
closing this as it seems resolved
