### ISSUE TITLE
[PAG] add `StableDiffusionXLControlNetPAGImg2ImgPipeline`

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/diffusers#8700]
We recently integrated PAG into diffusers! See the PR here: https://github.com/huggingface/diffusers/pull/7944

Does anyone want to add a `StableDiffusionXLControlNetPAGImg2ImgPipeline`?
1. You should put it under the [pag folder](https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines/pag)
2. you can use the implementation of [`StableDiffusionXLControlNetPAGPipeline`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/pag/pipeline_pag_controlnet_sd_xl.py) and [`StableDiffusionXLPAGImg2ImgPipeline`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/pag/pipeline_pag_sd_xl_img2img.py) as reference
3. you need to add AutoPipeline so that you can use this API to create it
    ```python
       AutoPipelineForImage2Image.from_pretrained(repo_id, controlnet=controlnet, enable_pag=True ...)
   ```
4. tests and docs

**Comment by satani99** [comment]
hi @yiyixuxu, i'll contribute it
can you assign me?

**Comment by yiyixuxu** [comment]
@satani99 yes!

**Comment by tuanh123789** [comment]
can i work on this

**Comment by yiyixuxu** [comment]
@tuanh123789 
this one is already taken! I opened a new issue here https://github.com/huggingface/diffusers/issues/8710
let me know if you want to work on this!

**Comment by asomoza** [comment]
Hi @satani99, I kind of need `StableDiffusionXLControlNetPAGImg2ImgPipeline`, are you still working on this? If you're having trouble with it you can just open the PR with what you have and we will help you.

**Comment by satani99** [comment]
I'll open a PR today.
