### ISSUE TITLE
[Community Pipeline] Speech to Image 

### ISSUE THREAD

**Issue by osanseviero** [huggingface/diffusers#871]
## Intro

Community Pipelines are introduced in `diffusers==0.4.0` with the idea of allowing the community to quickly add, integrate, and share their custom pipelines on top of `diffusers`. 

You can find a guide about Community Pipelines [here](https://github.com/huggingface/diffusers/issues/841). You can also find all the community examples under [`examples/community/`](https://github.com/huggingface/diffusers/tree/main/examples/community). If you have questions about the Community Pipelines feature, please head to the [parent issue](https://github.com/huggingface/diffusers/issues/841).

## Idea: Speech to Image

You can use a `transformer` `automatic-speech-recognition` such as OpenAI `whisper` to transcribe the text, and pass that to Stable Diffusion. Together, this would create a nice `speech-to-image` pipeline.

Resources
* https://twitter.com/art_zucker/status/1579881525071728642
* https://huggingface.co/docs/transformers/model_doc/whisper

**Comment by MikailINTech** [comment]
Hi, would be glad to work on it

**Comment by osanseviero** [comment]
Awesome! Feel free to open a PR and if you have any questions just let us know :) (ideally in the parent issue unless it's very specific to this :pray: )

**Comment by akashAD98** [comment]
I’m very much interested for this,I’ll try this feature

**Comment by MikailINTech** [comment]
Hi @osanseviero, I opened a PR for this issue. For the moment, I have tested my pipeline for whisper and it works pretty well. I'm waiting for your suggestions (maybe making the pipeline more generic so that we can use other speech-recognition models ?)

**Comment by patrickvonplaten** [comment]
It works very well ! Well done @MikailINTech :_)

**Comment by fffiloni** [comment]
📌 gradio demo is available here: https://huggingface.co/spaces/fffiloni/speech-to-image

**Comment by osanseviero** [comment]
This is amazing @fffiloni! Great work!

**Comment by osanseviero** [comment]
Closing this issue as this is now done 🔥 amazing work everyone!

**Comment by darwinharianto** [comment]
I tried the sample from https://github.com/huggingface/diffusers/tree/main/examples/community#speech-to-image
it gives me, 
![aa](https://user-images.githubusercontent.com/44696192/197931086-0ef3fdaa-9d98-47cd-8172-ec919d646f6b.png)

Is there anything wrong with the code?
