### ISSUE TITLE
[Community Pipeline] Wildcards

### ISSUE THREAD

**Issue by osanseviero** [huggingface/diffusers#872]
## Intro

Community Pipelines are introduced in `diffusers==0.4.0` with the idea of allowing the community to quickly add, integrate, and share their custom pipelines on top of `diffusers`. 

You can find a guide about Community Pipelines [here](https://github.com/huggingface/diffusers/issues/841). You can also find all the community examples under [`examples/community/`](https://github.com/huggingface/diffusers/tree/main/examples/community). If you have questions about the Community Pipelines feature, please head to the [parent issue](https://github.com/huggingface/diffusers/issues/841).

## Idea: Wildcards

Wildcards is an idea from @jtkelm2 for Automatic1111 Web UI. This is a copy paste (with slight modifications) from the official wiki

> Script support so prompts can contain wildcard terms (indicated by surrounding double underscores), with values instantiated randomly from a corresponding txt file (or a list of strings)
> 
> a woman at a cafe by __artist__ and __artist__
> 
> will draw two random artists from artist.txt. This works independently on each prompt, so that one can e.g. generate a batch of 100 images with the same prompt input using wildcards, and each output will have unique artists (or styles, or genres, or anything that the user creates their own .txt file for) attached to it.

Resources
* https://github.com/jtkelm2/stable-diffusion-webui-1/blob/master/scripts/wildcards.py
* https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Custom-Scripts#wildcards

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by shyamsn97** [comment]
Would love to take a look at this, if nobody else is working on it :smile:

**Comment by patrickvonplaten** [comment]
@20RitikSingh since you've already shown interest on a lot of other community pipelines, ok if we leave this one for @shyamsn97 ? :-)

**Comment by patrickvonplaten** [comment]
In general, the philosophy is to open a PR that is already in a reasonable state to have this issue be assigned to you. Then we can all work on the same PR :-)

**Comment by WASasquatch** [comment]
I have something similar, which this seems to be based upon idea: https://github.com/WASasquatch/noodle-soup-prompts

**Comment by shyamsn97** [comment]
Nice! I have something based on this https://github.com/adieyal/sd-dynamic-prompting in the works. Will put out a pr soon. I think it makes sense to support different filetypes as well :)

**Comment by WASasquatch** [comment]
Wouldn't it be best to make sure access to the wildcard is as easy as possible? Just do it like a noodle and use one underscore `_the-noodle_`. 

`__wildcard__` is a bit excessive, and are we really trying to emulate the `___write_your_name_here___` digital form method where it's suppose to symbolize a underline on a printed paper where you'd write? :P

**Comment by jtkelm2** [comment]
> Wouldn't it be best to make sure access to the wildcard is as easy as possible? Just do it like a noodle and use one underscore `_the-noodle_`.
> 
> `__wildcard__` is a bit excessive, and are we really trying to emulate the `___write_your_name_here___` digital form method where it's suppose to symbolize a underline on a printed paper where you'd write? :P

As the author of the original script, I chose double underscores instead of single just to be absolutely sure it wouldn't conflict with ordinary prompts. Some online artists might plausibly have single underscores in their name, or maybe you've trained custom models/embeddings with underscores because you're a hard-boiled programmer. Or perhaps your text file names simply use underscores. This was also back when my script wasn't intended to be a script, but a part of the default parser for the Webui.

That said, I wouldn't object to a single-underscore method, if the method continues its life as an optional script.

**Comment by WASasquatch** [comment]
> > Wouldn't it be best to make sure access to the wildcard is as easy as possible? Just do it like a noodle and use one underscore `_the-noodle_`.
> > `__wildcard__` is a bit excessive, and are we really trying to emulate the `___write_your_name_here___` digital form method where it's suppose to symbolize a underline on a printed paper where you'd write? :P
> 
> As the author of the original script, I chose double underscores instead of single just to be absolutely sure it wouldn't conflict with ordinary prompts or others' parsing methods. Some online artists might plausibly have single underscores in their handle, or maybe you've trained custom models/embeddings with underscores because you're a hard-boiled programmer. Or perhaps your text file names simply use underscores. This was also back when my script wasn't intended to be a script, but a part of the default parser for the Webui.
> 
> That said, I wouldn't object to a single-underscore method, if the method continues its life as an optional script.

I guess a way around that is to simply ignore the key if it doesn't exist as a physical file list. 

I don't have this issue with NSP since it's a loaded JSON dictionary, and I check if any of the sections in the dict exist with `key = f'_{section}_'` sorta deal. So unless a section was literally named as a artist that uses underscores at the beginning and end, it wouldn't be an issue.
