### ISSUE TITLE
how to unload a pipeline

### ISSUE THREAD

**Issue by nono909090** [huggingface/diffusers#8721]
how to unload a pipeline and release the gpu memory

**Comment by asomoza** [comment]
you don't have to do anything special, you can use `None` or `del`, just need to make sure you don't have reference to it or the models anywhere else.

If you don't see the memory freed, you can force it with this:

```python
torch.cuda.empty_cache()
```

**Comment by nono909090** [comment]
> you don't have to do anything special, you can use `None` or `del`, just need to make sure you don't have reference to it or the models anywhere else.
> 
> If you don't see the memory freed, you can force it with this:
> 
> ```python
> torch.cuda.empty_cache()
> ```

yes,it works! thank you

**Comment by asomoza** [comment]
glad it worked, closing this issue now then.
