### ISSUE TITLE
[Community Pipelines] SD v1-v4 compare

### ISSUE THREAD

**Issue by osanseviero** [huggingface/diffusers#873]
## Intro

Community Pipelines are introduced in `diffusers==0.4.0` with the idea of allowing the community to quickly add, integrate, and share their custom pipelines on top of `diffusers`. 

You can find a guide about Community Pipelines [here](https://github.com/huggingface/diffusers/issues/841). You can also find all the community examples under [`examples/community/`](https://github.com/huggingface/diffusers/tree/main/examples/community). If you have questions about the Community Pipelines feature, please head to the [parent issue](https://github.com/huggingface/diffusers/issues/841).

## Idea: SD v1-v4 compare

The idea of this pipeline is to run all 4 checkpoints in parallel to compare the outputs

* https://huggingface.co/CompVis/stable-diffusion-v1-4
* https://huggingface.co/CompVis/stable-diffusion-v1-1
* https://huggingface.co/CompVis/stable-diffusion-v1-2
* https://huggingface.co/CompVis/stable-diffusion-v1-3

**Comment by patrickvonplaten** [comment]
Feel free to open a PR @20RitikSingh
