### ISSUE TITLE
use load from single file for advance model training

### ISSUE THREAD

**Issue by al-swaiti** [huggingface/diffusers#8744]
few days ago i was planing to train Dora , So i converted my model to Diffusers  using load from single file and use original sdxl base config as mentiond in  tutorials ,  the first issue when i used the original sdxl base for training it download more than 12 G all files !
also when i used my diffusers model(ABDALLALSWAITI/DAVINCI-DIFF) it give me this error could you help me in this 
this 
`/home/abdallah/Desktop/webui/ComfyUI/.venv/lib/python3.12/site-packages/accelerate/accelerator.py:391: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
06/30/2024 19:22:20 - INFO - __main__ - Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: bf16

/home/abdallah/Desktop/webui/ComfyUI/.venv/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'thresholding', 'variance_type', 'clip_sample_range', 'dynamic_thresholding_ratio'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "/home/abdallah/Desktop/webui/diffusers/examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py", line 2434, in <module>
    main(args)
  File "/home/abdallah/Desktop/webui/diffusers/examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py", line 1415, in main
    text_encoder_one = text_encoder_cls_one.from_pretrained(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abdallah/Desktop/webui/ComfyUI/.venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 3234, in from_pretrained
    raise EnvironmentError(
OSError: ABDALLALSWAITI/DAVINCI-DIFF does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
Traceback (most recent call last):
  File "/home/abdallah/Desktop/webui/ComfyUI/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/abdallah/Desktop/webui/ComfyUI/.venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/abdallah/Desktop/webui/ComfyUI/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1075, in launch_command
    simple_launcher(args)
  File "/home/abdallah/Desktop/webui/ComfyUI/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 681, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/abdallah/Desktop/webui/ComfyUI/.venv/bin/python', 'train_dreambooth_lora_sdxl_advanced.py', '--pretrained_model_name_or_path=ABDALLALSWAITI/DAVINCI-DIFF', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--dataset_name=./3d_icon', '--instance_prompt=3d icon in the style of TOK', '--validation_prompt=a TOK icon of an astronaut riding a horse, in the style of TOK', '--output_dir=3d-icon-SDXL-LoRA', '--caption_column=prompt', '--mixed_precision=bf16', '--resolution=1024', '--train_batch_size=3', '--repeats=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=1.0', '--text_encoder_lr=1.0', '--optimizer=prodigy', '--train_text_encoder_ti', '--train_text_encoder_ti_frac=0.5', '--snr_gamma=5.0', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--rank=8', '--max_train_steps=1000', '--checkpointing_steps=2000', '--seed=0', '--push_to_hub']' returned non-zero exit status 1.`

![image](https://github.com/huggingface/diffusers/assets/95714669/42fba582-ed20-4f24-b3f4-9deef7562d4b)

**Comment by josemerinom** [comment]
![image](https://github.com/huggingface/diffusers/assets/20940429/25f8772e-e795-46de-a05d-9f2ae8675aae)

OSError: ABDALLALSWAITI/DAVINCI-DIFF does not appear to have a file named **pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt or flax_model.msgpack**.

You have the fp16 version, maybe you should use the model.safetensors 2.78gb version

DAVINCI-DIFF is a custom model or is it an original SDXL?
if it is original sdxl, you can clone the sdxl repository and remove the files you don't need.
Another more tedious option: is to download the files one by one and create the folder structure yourself

![image](https://github.com/huggingface/diffusers/assets/20940429/5fbcf688-3708-41c2-92c1-fa7ef84790b2)

**Comment by al-swaiti** [comment]
i think there some thing in the code 
1- i tried my davinci-diff alone !
2- tried this method and add files manually at same structure 
3- rebuild my diff models using sdxl base config , 
all the time the model was work perfect  in  images productions  , but not in training !  is there problem with name !

**Comment by al-swaiti** [comment]
![image](https://github.com/huggingface/diffusers/assets/95714669/6f83234e-19f4-40c9-8009-04eeaf5acf70)
the difference is just the transformer version!

**Comment by al-swaiti** [comment]
its work !  now 
i downloaded the snapshot , and its work , i couldn't use full repo nor single , waiting for support in future
