### ISSUE TITLE
[Community Pipeline] Seed resize

### ISSUE THREAD

**Issue by osanseviero** [huggingface/diffusers#875]
## Intro

Community Pipelines are introduced in `diffusers==0.4.0` with the idea of allowing the community to quickly add, integrate, and share their custom pipelines on top of `diffusers`. 

You can find a guide about Community Pipelines [here](https://github.com/huggingface/diffusers/issues/841). You can also find all the community examples under [`examples/community/`](https://github.com/huggingface/diffusers/tree/main/examples/community). If you have questions about the Community Pipelines feature, please head to the [parent issue](https://github.com/huggingface/diffusers/issues/841).

## Idea: Seed Resize

Seed Resize allows generating images from a given seed at different resolutions. Usually, the generated images change as the resolution changes; with seed resize, the images look very similar. This idea is inspired by [Automatic1111 UI](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#seed-resize).

**Comment by daspartho** [comment]
Hi @osanseviero
I'd like to take on this =)

**Comment by patrickvonplaten** [comment]
That's great! Feel free to open a PR @daspartho :-)

**Comment by daspartho** [comment]
According to my understanding, this should allow you to generate images from known seeds at different resolutions, without changing the image as the resolution changes.

We can specify the resolution of the original image, and then all subsequent images of varying resolutions should look similar to the original image.

Could you please give me some suggestions on how i should go about implementing this?

**Comment by patrickvonplaten** [comment]
gently ping for @osanseviero @apolinario here

**Comment by apolinario** [comment]
Hey @daspartho, yes that is what seed resize should do! You can check how AUTOMATIC1111 does it, I think they generate the noise on the 512x512 resolution and then resize it, which helps with keeping the seed for generating other sizes, you check their implementation [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/6cbb04f7a5e675cf1f6dfc247aa9c9e8df7dc5ce/modules/processing.py#L250)

**Comment by MarkRich** [comment]
Took a crack at it here: https://github.com/huggingface/diffusers/pull/1011

**Comment by daspartho** [comment]
So I guess I'll leave it to @MarkRich then. Good work on the pipeline!

**Comment by osanseviero** [comment]
This is done now! 🔥
