### ISSUE TITLE
[Community Pipeline] Composable Diffusion

### ISSUE THREAD

**Issue by osanseviero** [huggingface/diffusers#876]
## Intro

Community Pipelines are introduced in `diffusers==0.4.0` with the idea of allowing the community to quickly add, integrate, and share their custom pipelines on top of `diffusers`. 

You can find a guide about Community Pipelines [here](https://github.com/huggingface/diffusers/issues/841). You can also find all the community examples under [`examples/community/`](https://github.com/huggingface/diffusers/tree/main/examples/community). If you have questions about the Community Pipelines feature, please head to the [parent issue](https://github.com/huggingface/diffusers/issues/841).

## Idea: Composable Diffusion

The idea of this pipeline is to use AND + NOT to conditional diffusion models to do compositional generation.

Resources:

* Project Page: https://energy-based-model.github.io/Compositional-Visual-Generation-with-Composable-Diffusion-Models/
* Demo: https://huggingface.co/spaces/Shuang59/Composable-Diffusion
* Code: https://huggingface.co/spaces/Shuang59/Composable-Diffusion/blob/main/composable_stable_diffusion_pipeline.py

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by patrickvonplaten** [comment]
Great @20RitikSingh,

Feel free to open a PR :-) We're happy to help with anything if needed!

**Comment by MarkRich** [comment]
Took a crack at this in https://github.com/huggingface/diffusers/pull/951. Looking forward to any comments!

**Comment by patrickvonplaten** [comment]
Great work @MarkRich - merged it :-)
