### ISSUE TITLE
Integrate HiDiffusion

### ISSUE THREAD

**Issue by ShenZhang-Shin** [huggingface/diffusers#8782]
**Is your feature request related to a problem? Please describe.**
Object duplication and low efficiency happens when generating high-resolution image (2048x2048, 4096x4096) for stable diffusion models. 
HiDiffusion can solve these problems, increasing the resolution and speed of pretrained diffusion models.
[paper link](https://arxiv.org/abs/2311.17528); [project link](https://hidiffusion.github.io/); [code link ](https://github.com/megvii-research/HiDiffusion?tab=readme-ov-file)

text-to-image: 2048x2048 resolution images generated by HiDiffusion
![image](https://github.com/huggingface/diffusers/assets/58697142/fc37ed4d-fb88-4d27-bdbd-8bbf0dcb83e4)

HiDiffusion also supports controlnet and other tasks.
controlnet: 2048x2048 resolution images
![image](https://github.com/huggingface/diffusers/assets/58697142/1935a30e-40fe-426c-8ed3-2bf646598ea7)

Efficiency comparison with other acceleration methods, HiDiffusion can significantly reduce time consumption without compromising image quality.
![image](https://github.com/huggingface/diffusers/assets/58697142/53e6a867-ece3-44a6-9780-936d9478478f)

**Describe the solution you'd like.**
HiDiffusion code is based diffusers and is designed as a plug-and-play implementation. It can be integrated into diffusers pipelines by only adding a single line of code!  Users just needs to install hidiffusion
```python
pip3 install hidiffusion
```

and use it by adding a single line of code 
```python
apply_hidiffusion(pipeline)
```

We want to integrate HiDiffusion into the official code and documentation so that more people can access this feature.

**Describe alternatives you've considered.**
None

**Additional context.**
None

**Comment by hidiffusion** [comment]
cc @a-r-r-o-w @sayakpaul if you're interested in this work!

**Comment by DN6** [comment]
Hi @ShenZhang-Shin I think we can start by adding to the community pipelines here since the API design is a bit different. I'm thinking we could do something like 

```
sd_pipe = StableDiffusionPipeline.from_pretrained("...")
pipe = HiDiffusionPipeline.from_pipe(
```

The HiDiffusionPipeline could then encapsulate the logic you have in the `apply_hi_diffusion` function?

**Comment by ShenZhang-Shin** [comment]
Hi @DN6 
Adding to the community pipelines and using HiDiffusionPipeline.from_pipe(sd_pipe) is a great choice. However, this approach differs from the API in the HiDiffusion repository (apply_hidiffusion(pipeline)), which might confuse users about why there are two different APIs. Additionally, adding to the community pipelines requires copying a portion of the HiDiffusion code into the diffusers pipelines. This will be a hassle, as I plan to update HiDiffusion to support more models in the future continually.

I believe it is better and more flexible to add a section about HiDiffusion in the [Hugging Face Diffusers documentation](https://huggingface.co/docs/diffusers/index) so that we don't need to create a new API.

**Comment by DN6** [comment]
Hi @ShenZhang-Shin yeah we can definitely add a section in the docs to highlight the project. Will open a PR soon for it. cc: @stevhliu

**Comment by ShenZhang-Shin** [comment]
@DN6  Thanks!

**Comment by ShenZhang-Shin** [comment]
Hi, @DN6 @stevhliu
I am wondering if there have been any updates on the PR

**Comment by DN6** [comment]
@ShenZhang-Shin Just opened the PR here
https://github.com/huggingface/diffusers/pull/9013

**Comment by ShenZhang-Shin** [comment]
Hi @DN6 
Thank you for your support! It looks quite good.

After viewing the community projects, I found many interesting works and can't wait to try them out!

Additionally, I think placing hidiffusion in the INFERENCE TECHNIQUES or ADVANCED INFERENCE sections would be a great choice.  I will write a documentation about HiDiffusion. If I want to contribute to the diffusers documentation, can I submit a commit in https://github.com/huggingface/diffusers/pull/9013, or should I create a new PR?

**Comment by a-r-r-o-w** [comment]
I'm closing this because I see HiDiffusion mentioned in https://huggingface.co/docs/diffusers/community_projects. Super cool work - awesome guys! 🎊
