### ISSUE TITLE
The model loading has suddenly become slow.

### ISSUE THREAD

**Issue by crapthings** [huggingface/diffusers#8787]
### Describe the bug

The model loading has suddenly become slow.

<img width="2064" alt="image" src="https://github.com/huggingface/diffusers/assets/1147704/f464d7ee-cacc-4860-97e9-ae64857077bc">

### Reproduction

```
text2imgPipe = StableDiffusionControlNetPipeline.from_single_file(
  './base.safetensors',
  controlnet = [
    depth_control,
    openpose_control,
    inpaint_control,
    canny_control,
  ],
  torch_dtype = torch.float16,
  enable_pag = True,
  pag_applied_layers = ['mid'],
)
```

### System Info

- 🤗 Diffusers version: 0.30.0.dev0
- Platform: Linux-6.5.0-41-generic-x86_64-with-glibc2.35
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.1+cu118 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.3
- Transformers version: 4.43.0.dev0
- Accelerate version: 0.32.0
- PEFT version: 0.10.0
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: 0.0.23+cu118
- Accelerator: NVIDIA L40, 46068 MiB VRAM
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by crapthings** [comment]
revert to works

```
pip install accelerate==0.31.0
```

**Comment by knoopx** [comment]
I just want to express how frustrating is for the users of the library to have stuff breaking every single time regardless it's a major, minor or patch release or a completely unrelated library (Transformers/Accelerate/PEFT). Please take semantic versioning seriously and don't rush releases. Like for example this release, a new model should not be part of a patch release: https://github.com/huggingface/diffusers/releases/tag/v0.28.1

**Comment by DN6** [comment]
@crapthings I believe a fix has been merged into `accelerate` and a patch release will be done soon
https://github.com/huggingface/accelerate/pull/2914

**Comment by muellerzr** [comment]
The patch is out on pypi, apologies for the frustration it has caused (which is entirely understandable!)
