### ISSUE TITLE
ComfyUI example for train_dreambooth_lora_sdxl_advanced.py

### ISSUE THREAD

**Issue by Heimdall-Nss** [huggingface/diffusers#8794]
Can you provide a ComfyUI example for the model in the train_dreambooth_lora_sdxl_advanced.py script?

I used the train_dreambooth_lora_sdxl_advanced.py script to train and perform inference, and achieved good results. I want to apply the trained lora and embedding on comfyUI, but the results are very poor?
Refer to the inference process in https://github.com/huggingface/diffusers/tree/main/examples/advanced_diffusion_training, the local inference script is as follows：
```python
import torch
# from huggingface_hub import hf_hub_download, upload_file
from diffusers import DiffusionPipeline
from diffusers.models import AutoencoderKL
from safetensors.torch import load_file
from PIL import Image
pretrain_model = "./pretrained_models/SDXL"
local_weights_path = "./cat1_sdxl_lora/checkpoint-200/pytorch_lora_weights.safetensors"

pipe = DiffusionPipeline.from_pretrained(
        pretrain_model,
        torch_dtype=torch.float16,
        variant="fp16",
).to("cuda")


# pipe.load_lora_weights(repo_id, weight_name="pytorch_lora_weights.safetensors")
pipe.load_lora_weights(local_weights_path)

text_encoders = [pipe.text_encoder, pipe.text_encoder_2]
tokenizers = [pipe.tokenizer, pipe.tokenizer_2]

# embedding_path = hf_hub_download(repo_id=repo_id, filename="embeddings.safetensors", repo_type="model")
embedding_path = "./cat1_sdxl_lora/checkpoint-100/cat1_sdxl_lora_emb.safetensors"

state_dict = load_file(embedding_path)
# load embeddings of text_encoder 1 (CLIP ViT-L/14)
pipe.load_textual_inversion(state_dict["clip_l"], token=["<s0>", "<s1>"], text_encoder=pipe.text_encoder, tokenizer=pipe.tokenizer)
# load embeddings of text_encoder 2 (CLIP ViT-G/14)
pipe.load_textual_inversion(state_dict["clip_g"], token=["<s0>", "<s1>"], text_encoder=pipe.text_encoder_2, tokenizer=pipe.tokenizer_2)

instance_token = "<s0><s1>"
prompt = f"a {instance_token} cat lying in front of the courtyard, in the background of Chinese style"

image = pipe(prompt=prompt, num_inference_steps=25, cross_attention_kwargs={"scale": 1.0}).images[0]

image.save("cats/cat14.jpg")
```
Below is my workflow. What is wrong? Or can you provide an example reference?
<img width="1674" alt="截屏2024-07-05 15 19 11" src="https://github.com/huggingface/diffusers/assets/58160555/59a6bb7c-74db-4794-a6cd-fd2c502aee3f">

**Comment by asomoza** [comment]
Hi, can you share the lora and embeddings files? Also can you show an image you consider a good result?

**Comment by Heimdall-Nss** [comment]
> Hi, can you share the lora and embeddings files? Also can you show an image you consider a good result?

I used 5 cat pictures for training, which looked like this:
<img width="638" alt="截屏2024-07-08 11 51 25" src="https://github.com/huggingface/diffusers/assets/58160555/39a85b1f-0fd3-4e5e-a5e5-f342ec80818a">
After that, I chose the 100-step checkpoints model for testing. The local test script ：
```python
import torch
# from huggingface_hub import hf_hub_download, upload_file
from diffusers import DiffusionPipeline
from diffusers.models import AutoencoderKL
from safetensors.torch import load_file
from PIL import Image
pretrain_model = "./pretrained_models/SDXL"
local_weights_path = "./cat1_sdxl_lora/checkpoint-100/pytorch_lora_weights.safetensors"
# embedding_path = hf_hub_download(repo_id=repo_id, filename="embeddings.safetensors", repo_type="model")
embedding_path = "./cat1_sdxl_lora/checkpoint-100/cat1_sdxl_lora_emb.safetensors"
torch.cuda.set_device(1)
pipe = DiffusionPipeline.from_pretrained(
        pretrain_model,
        torch_dtype=torch.float16,
        variant="fp16",
).to("cuda")


# pipe.load_lora_weights(repo_id, weight_name="pytorch_lora_weights.safetensors")
pipe.load_lora_weights(local_weights_path)

text_encoders = [pipe.text_encoder, pipe.text_encoder_2]
tokenizers = [pipe.tokenizer, pipe.tokenizer_2]



state_dict = load_file(embedding_path)
# load embeddings of text_encoder 1 (CLIP ViT-L/14)
pipe.load_textual_inversion(state_dict["clip_l"], token=["<s0>", "<s1>"], text_encoder=pipe.text_encoder, tokenizer=pipe.tokenizer)
# load embeddings of text_encoder 2 (CLIP ViT-G/14)
pipe.load_textual_inversion(state_dict["clip_g"], token=["<s0>", "<s1>"], text_encoder=pipe.text_encoder_2, tokenizer=pipe.tokenizer_2)

instance_token = "<s0><s1>"
prompt = f"a {instance_token} cat running on the beach"
print(pipe)
image = pipe(prompt=prompt, num_inference_steps=25, cross_attention_kwargs={"scale": 1.0}).images[0]
```
the model file :
<img width="203" alt="截屏2024-07-08 11 54 50" src="https://github.com/huggingface/diffusers/assets/58160555/184cfb0e-7fc6-473f-bf02-aa561dd3fb18">

the generated result :
<img width="722" alt="截屏2024-07-08 11 55 54" src="https://github.com/huggingface/diffusers/assets/58160555/9b714b40-16d4-443c-8fff-a7325649a1a0">

After that, I built a simple workflow using lora and embedding in comfyUI as follows:
<img width="1484" alt="截屏2024-07-08 11 56 27" src="https://github.com/huggingface/diffusers/assets/58160555/34cbb867-430c-4670-af3f-886a37100b2f">

The corresponding model weights were selected, and the generated result was as follows:
<img width="828" alt="image" src="https://github.com/huggingface/diffusers/assets/58160555/71591b08-eca3-4f7e-9f1e-0c902c768799">
<img width="614" alt="image" src="https://github.com/huggingface/diffusers/assets/58160555/9aa40e5f-a60a-4b75-a764-a7b59d37248c">
note that after adjusting the latent size to 1024, the result will be better than 512, probably because the default input is 1024, but the picture texture is still different. In other words, can I reproduce the effect in the script on comfyUI？

**Comment by asomoza** [comment]
I'm asking about a lora and embeddings files because I don't have one and also I don't have the time to train one right now. So if you can't share yours, you'll have to wait until I have the time to train one.

There's a couple of tips I can give you though.

With SDXL you have to always use 1024px or an equivalent number of pixels resolution, if you use 512px generations you will almost always get bad results.

In comfyui, the embeddings gets loaded automatically by the filename but don't think it does the same for the token, so you have to use something like this in the prompt: `a embedding:cat_epoch100 <s0><s1> cat running on the beach`. I'm not completely sure about this because I almost never use TI so I'll have to test this.

The training you're doing is too simple, training 4 images of a generic cat will be very hard to differentiate if the TI is loading or not.

For the lora you need to use the arg for it to be comfyui compatible, don't know if you're doing that.

All from  before is assuming you have the correct filenames in the correct directories, you have to look in the comfyui console output if everything gets loaded correctly or if you have errors/warnings.

**Comment by Heimdall-Nss** [comment]
> I'm asking about a lora and embeddings files because I don't have one and also I don't have the time to train one right now. So if you can't share yours, you'll have to wait until I have the time to train one.
> 
> There's a couple of tips I can give you though.
> 
> With SDXL you have to always use 1024px or an equivalent number of pixels resolution, if you use 512px generations you will almost always get bad results.
> 
> In comfyui, the embeddings gets loaded automatically by the filename but don't think it does the same for the token, so you have to use something like this in the prompt: `a embedding:cat_epoch100 <s0><s1> cat running on the beach`. I'm not completely sure about this because I almost never use TI so I'll have to test this.
> 
> The training you're doing is too simple, training 4 images of a generic cat will be very hard to differentiate if the TI is loading or not.
> 
> For the lora you need to use the arg for it to be comfyui compatible, don't know if you're doing that.
> 
> All from before is assuming you have the correct filenames in the correct directories, you have to look in the comfyui console output if everything gets loaded correctly or if you have errors/warnings.

Thank you for your replies. I have tried to upload relevant files, but due to company regulations, I cannot use external network disks, etc. However, with your prompts, I seem to have found the problem. I actually ignored the log view on the comfyUI server. Obviously, as shown in the following figure, lora failed to load. I will continue to troubleshoot the error.
<img width="758" alt="截屏2024-07-08 16 07 00" src="https://github.com/huggingface/diffusers/assets/58160555/aa20836f-d5f1-42a8-84e1-6747863a0d31">

**Comment by Heimdall-Nss** [comment]
> I'm asking about a lora and embeddings files because I don't have one and also I don't have the time to train one right now. So if you can't share yours, you'll have to wait until I have the time to train one.
> 
> There's a couple of tips I can give you though.
> 
> With SDXL you have to always use 1024px or an equivalent number of pixels resolution, if you use 512px generations you will almost always get bad results.
> 
> In comfyui, the embeddings gets loaded automatically by the filename but don't think it does the same for the token, so you have to use something like this in the prompt: `a embedding:cat_epoch100 <s0><s1> cat running on the beach`. I'm not completely sure about this because I almost never use TI so I'll have to test this.
> 
> The training you're doing is too simple, training 4 images of a generic cat will be very hard to differentiate if the TI is loading or not.
> 
> For the lora you need to use the arg for it to be comfyui compatible, don't know if you're doing that.
> 
> All from before is assuming you have the correct filenames in the correct directories, you have to look in the comfyui console output if everything gets loaded correctly or if you have errors/warnings.

lora and emb files are here：https://filetransfer.io/data-package/mlxBCa04#link

**Comment by asomoza** [comment]
those errors are because the lora is in the diffusers format, comfyui doesn't load them, to be able to use them in the webuis you'll need to use the `--output_kohya_format` arg.

I'll test your files now.

**Comment by asomoza** [comment]
I converted the lora and it seems to work, as I told you before, it's really hard to see if the TI is working or not or if needs the special tokens, but it seems so:

|normal|TI|TI with token|
|---|---|---|
|![ComfyUI_00292_](https://github.com/huggingface/diffusers/assets/5442875/570e6a87-36a6-41a8-8f18-556d1360b09e)|![ComfyUI_00293_](https://github.com/huggingface/diffusers/assets/5442875/16a51745-bb49-4080-a3ae-f47b9a3c55bb)|![ComfyUI_00294_](https://github.com/huggingface/diffusers/assets/5442875/895b5429-cdf3-4ab4-8904-c7e47f1207ed)|

**Comment by Heimdall-Nss** [comment]
> I converted the lora and it seems to work, as I told you before, it's really hard to see if the TI is working or not or if needs the special tokens, but it seems so:
> 
> Just LoRA	LoRA + TI	LoRA + TI with token
> ![ComfyUI_00292_](https://private-user-images.githubusercontent.com/5442875/346490204-570e6a87-36a6-41a8-8f18-556d1360b09e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjg0MjEsIm5iZiI6MTcyMDQyODEyMSwicGF0aCI6Ii81NDQyODc1LzM0NjQ5MDIwNC01NzBlNmE4Ny0zNmE2LTQxYTgtOGYxOC01NTZkMTM2MGIwOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMDg0MjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjVjMmVjMjAyNTE3MmEwOWQ4Zjk4OTIxYjAzNzY1MTEwMjdmYWJlMGMwNGY3YmM5OGNjZWZiYWIyNTRlNWRhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Tiqo_AM3CviIja2mlv15QdoKmWEAVLhwpCtYb3k8LqI)	![ComfyUI_00293_](https://private-user-images.githubusercontent.com/5442875/346490238-16a51745-bb49-4080-a3ae-f47b9a3c55bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjg0MjEsIm5iZiI6MTcyMDQyODEyMSwicGF0aCI6Ii81NDQyODc1LzM0NjQ5MDIzOC0xNmE1MTc0NS1iYjQ5LTQwODAtYTNhZS1mNDdiOWEzYzU1YmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMDg0MjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFmNmQ2YTEwODg5YjE1MjU4ZDEzNzM3NjQ0MjE2ODlkOTUxNDhiOTI4MDk4ZDlhZWNjOTIyNjlhYmZkNmY2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g9qKVWy8zXEduyTI1iXKDwQHJMUihAni7VBKc9QafVY)	![ComfyUI_00294_](https://private-user-images.githubusercontent.com/5442875/346490262-895b5429-cdf3-4ab4-8904-c7e47f1207ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mjg0MjEsIm5iZiI6MTcyMDQyODEyMSwicGF0aCI6Ii81NDQyODc1LzM0NjQ5MDI2Mi04OTViNTQyOS1jZGYzLTRhYjQtODkwNC1jN2U0N2YxMjA3ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMDg0MjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQ0ODZlNzBkN2JjYTYyYjMyY2QxMGRjY2M1ODVkMmNhNDhiMjYxMmI2MDg4NzBkOTIyNDNhOTIyZDJiODNkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p4bpEtgUjmnYe9thdtCnpkOTQwtei-zmQVYT-7fm3EQ)

Thank you very much for your help, I found a similar problem in issue: https://github.com/comfyanonymous/ComfyUI/issues/1144, and found this conversion script: https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_sdxl_lora_to_webui.py, I will continue to try

**Comment by asomoza** [comment]
yeah, that's the script I used to convert your LoRA just now.
