### ISSUE TITLE
duplicate assignment for hidden_states at models/attention_processor.py:1142

### ISSUE THREAD

**Issue by 131131yhx** [huggingface/diffusers#8803]
### Describe the bug

duplicate assignment for hidden_states at models/attention_processor.py:1142

### Reproduction

N/A

### System Info

N/A

**Comment by tolgacangoz** [comment]
Hi, thank you for mentioning this! If you are referencing [this line](https://github.com/huggingface/diffusers/blob/7833ed957bcb4bd8c9ed0a9a8a172513bf896e51/src/diffusers/models/attention_processor.py#L1109), I tried to simplify it [in my PR](https://github.com/huggingface/diffusers/pull/8569/files#diff-96aeb208ac8e69bdb368e0a481a0cd50173b3f4bf19e5da500c251614820c8cd).

**Comment by 131131yhx** [comment]
ok

**Comment by yiyixuxu** [comment]
fixed in https://github.com/huggingface/diffusers/pull/8569
