### ISSUE TITLE
Differential Diffusion with  Kolors 

### ISSUE THREAD

**Issue by chuck-ma** [huggingface/diffusers#8813]
**Is your feature request related to a problem? Please describe.**
One might wish to soft inpaint or edit pictures with differential diffusion with Kolors .

**Describe the solution you'd like.**
I believe we can port diff-diff to Kolors , by adding a new pipeline for it.

**Describe alternatives you've considered.**
Diff-diff is already supported with XL and sd3 .But sd3 failed to generate full body picture of a person.A port of differential diffusion for Kolors  might fill this gap as well. Besides, i think in visual quality Kolors  looks more promising than sd3

@asomoza

**Comment by chuck-ma** [comment]
@asomoza

**Comment by asomoza** [comment]
Let's wait until we have the actual pipeline in the diffusers core.

We'll probably leave it to the community since it will just be a copy of the SDXL Differential Diffusion adapted to the Kolors Pipeline which can be a very good first issue for the people who wants to contribute.

**Comment by asomoza** [comment]
closing this issue since diff-diff was added to kolors in this [PR](https://github.com/huggingface/diffusers/pull/9423)
