### ISSUE TITLE
Will the training code of SD3 Controlnet be released?

### ISSUE THREAD

**Issue by ChenhLiwnl** [huggingface/diffusers#8834]
**Is your feature request related to a problem? Please describe.**
Training code of SD3 ControlNet
**Describe the solution you'd like.**
Could you please release training code of SD3 controlnet? I tried to train it but failed so I want to check whats the reason

**Comment by DN6** [comment]
HI @ChenhLiwnl it would be up to the original author to decide when/if to release the training code.

**Comment by csyThomas** [comment]
hello，我刚好也在研究sd3 controlnet的训练，但是还没能调试通，能分享一下你的代码吗？万分感谢

**Comment by DavyMorgan** [comment]
Will the training code of SD3 ControlNet be released?
