### ISSUE TITLE
sd3 lora weight error

### ISSUE THREAD

**Issue by efwfe** [huggingface/diffusers#8839]
### Describe the bug

` pipe.fuse_lora(lora_scale=lora_w)` 
sd3 pipeline use this way to generate image, the image is terrible.
![1_0 7](https://github.com/huggingface/diffusers/assets/31640191/8621b486-6052-4021-9a6b-a426e4b9e120)

### Reproduction

```python

from diffusers import AutoPipelineForText2Image
pipe = AutoPipelineForText2Image.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers",  torch_dtype=torch.float16).to('cuda')
pipe.load_lora_weights(xxx)
pipe.fuse_lora(lora_scale=0.8)

```

### System Info

- 🤗 Diffusers version: 0.30.0.dev0
- Platform: Linux-6.8.0-1010-aws-x86_64-with-glibc2.39
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.12.3
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.4
- Transformers version: 4.41.2
- Accelerate version: 0.31.0
- PEFT version: 0.11.1
- Bitsandbytes version: 0.43.1
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA A10G, 23028 MiB VRAM
- Using GPU in script?: 1
- Using distributed or parallel set-up in script?: No parallel or distributed
-

**Comment by asomoza** [comment]
Hi, you will need to share the lora checkpoint or else we won't be able to help you. Loading loras and using `fuse_lora` works with the currents loras trained with diffusers.
