### ISSUE TITLE
No tqdm download progress bar for ControlNetModel

### ISSUE THREAD

**Issue by Teriks** [huggingface/diffusers#8847]
### Describe the bug

Downloading a ControlNet model to the cache results in no TQDM progress bar being displayed on ``stderr``.

Seems to occur with any control net class.

Just make sure these models are not cached before testing.

I am guessing this also occurs with ``FlaxControlNetModel`` but it is not easy for me to reproduce without spinning up a docker image.

### Reproduction

```python
import diffusers

test1 = diffusers.ControlNetModel.from_pretrained('diffusers/controlnet-depth-sdxl-1.0-mid')

test2 = diffusers.SD3ControlNetModel.from_pretrained('InstantX/SD3-Controlnet-Tile')
```

### Logs

```shell
not applicable
```

### System Info

Diffusers: 0.29.2

Platform Windows

### Who can help?

@sayakpaul @yiyixuxu @DN6

**Comment by sayakpaul** [comment]
Could it be because of how you have configured logging? https://huggingface.co/docs/diffusers/en/api/logging

**Comment by Teriks** [comment]
@sayakpaul I pulled from the main branch to see if I could possibly debug, but the issue does not exist in the main branch

**Comment by sayakpaul** [comment]
If that is the case I am not sure what we could act on here. Because main branch seems to be working for you?

**Comment by Teriks** [comment]
Yes, closing this issue, just updating for reference :)
