### ISSUE TITLE
Community pipelines mirror broken

### ISSUE THREAD

**Issue by onyasumi** [huggingface/diffusers#8850]
### Describe the bug

When using a custom pipline with `StableDiffusionXLPipeline.from_pretrained`, the function fails due to a 404.

Upon further investigation, `https://huggingface.co/datasets/diffusers/community-pipelines-mirror/resolve/main/v0.29.2/lpw_stable_diffusion_xl.py` does not exist, but `https://huggingface.co/datasets/diffusers/community-pipelines-mirror/resolve/main/v0.29.1/lpw_stable_diffusion_xl.py` does

### Reproduction

Sample code from `https://huggingface.co/yodayo-ai/kivotos-xl-2.0`

```python
import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(
    "yodayo-ai/kivotos-xl-2.0", 
    torch_dtype=torch.float16, 
    use_safetensors=True,
    custom_pipeline="lpw_stable_diffusion_xl",
    add_watermarker=False,
    variant="fp16"
)
pipe.to('cuda')

prompt = "1girl, kazusa \(blue archive\), blue archive, solo, upper body, v, smile, looking at viewer, outdoors, night, masterpiece, best quality, very aesthetic, absurdres"
negative_prompt = "nsfw, (low quality, worst quality:1.2), very displeasing, 3d, watermark, signature, ugly, poorly drawn"

image = pipe(
    prompt, 
    negative_prompt=negative_prompt,
    width=832,
    height=1216, 
    guidance_scale=7,
    num_inference_steps=28
).images[0]

image.save("./cat.png")
```

### Logs

```shell
Could not locate the pipeline.py inside lpw_stable_diffusion_xl.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/datasets/diffusers/community-pipelines-mirror/resolve/main/v0.29.2/lpw_stable_diffusion_xl.py
```

### System Info

- 🤗 Diffusers version: 0.29.2
- Platform: Linux-6.9.5-arch1-1-x86_64-with-glibc2.39
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.12.4
- PyTorch version (GPU?): 2.2.2+rocm5.7 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.4
- Transformers version: 4.42.4
- Accelerate version: 0.32.1
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NA
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by Wauplin** [comment]
Thanks for reporting @onyasumi and sorry for the inconvenience! The CI to upload the mirror pipeline was green even though there was an error in it. That's why we did not notice it when it ran. We will need to fix this script. In the meantime, I've manually triggered an upload which worked: https://huggingface.co/datasets/diffusers/community-pipelines-mirror/tree/main/v0.29.2. This should fix community pipelines on diffusers `0.29.2`.

I'm closing this issue but please let me know if you still encounter issues. Have fun with `diffusers` :hugs:
