### ISSUE TITLE
ASCEND TORCH_NPU INFERENCE performance improvement optimization point

### ISSUE THREAD

**Issue by lightnateriver** [huggingface/diffusers#8852]
FOR ASCEND TORCH_NPU BACKEND: 
By the following configuration, private conv format is not allowed, which reduces format conversion and optimizes the speed of the conv operator. It can also avoid the possible functional issues caused by the propagation of private formats and the potential increase in memory usage. The verification has shown a performance improvement, so it can be considered for inclusion in the main branch：

`if __name__ == "__main__":

    torch.npu.config.allow_internal_format = False`

![image](https://github.com/user-attachments/assets/22055fc5-d525-4821-8033-943d46c0a7a6)

**Comment by lightnateriver** [comment]
@patil-suraj @kashif

**Comment by DN6** [comment]
@lightnateriver sorry what is the change you're proposing here exactly?

**Comment by lightnateriver** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。白茶清欢无别事,我在等风也等你。清酒独酌了无趣,我在梦花也梦你。

**Comment by tolgacangoz** [comment]
> 这是一封自动回复邮件。已经收到您的来信，我会尽快回复。白茶清欢无别事,我在等风也等你。清酒独酌了无趣,我在梦花也梦你。

Is this a poem :D

**Comment by lightnateriver** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。白茶清欢无别事,我在等风也等你。清酒独酌了无趣,我在梦花也梦你。

**Comment by lightnateriver** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。白茶清欢无别事,我在等风也等你。清酒独酌了无趣,我在梦花也梦你。

**Comment by lightnateriver** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。白茶清欢无别事,我在等风也等你。清酒独酌了无趣,我在梦花也梦你。

**Comment by lightnateriver** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。白茶清欢无别事,我在等风也等你。清酒独酌了无趣,我在梦花也梦你。

**Comment by asomoza** [comment]
closing this for now since it doesn't have any more updated and it has been kept alive by an automated email response.
