### ISSUE TITLE
Can't load textual embedding (SDXL)

### ISSUE THREAD

**Issue by qdacsvx** [huggingface/diffusers#8854]
### Describe the bug

I downloaded a textual embedding but there is an error if I try to load it with load_textual_inversion.

Embedding unaestheticXL_Jug6.safetensors: https://civitai.com/models/119032?modelVersionId=207934

### Reproduction

```
import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(

    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16"
)

pipe.load_textual_inversion("unaestheticXL_Jug6.safetensors", token="unaestheticXL_Jug6")

image = pipe(
    prompt="Hello world",
    negative_prompt="<unaestheticXL_Jug6>",
    num_inference_steps=20,
    height=1024,
    width=1024,
    guidance_scale=7.0,
).images[0]

image.save("/tmp/hello_world.png")
```

### Logs

```shell
Traceback (most recent call last):
  File "/tmp/basic.py", line 9, in <module>
    pipe.load_textual_inversion("unaestheticXL_Jug6.safetensors", token="unaestheticXL_Jug6")
  File "/home/freitag/py/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/freitag/py/lib/python3.10/site-packages/diffusers/loaders/textual_inversion.py", line 403, in load_textual_inversion
    tokens, embeddings = self._retrieve_tokens_and_embeddings(tokens, state_dicts, tokenizer)
  File "/home/freitag/py/lib/python3.10/site-packages/diffusers/loaders/textual_inversion.py", line 218, in _retrieve_tokens_and_embeddings
    raise ValueError(
ValueError: Loaded state dictionary is incorrect: {'clip_g': tensor([[-0.0159, -0.0213,  0.0058,  ...,  0.0093,  0.0232, -0.0084],
        [ 0.0093, -0.0305, -0.0069,  ...,  0.0142,  0.0295,  0.0152],
        [-0.0211, -0.0331,  0.0184,  ...,  0.0142, -0.0309,  0.0101],
        [-0.0079, -0.0059, -0.0196,  ...,  0.0283,  0.0338,  0.0021],
        [ 0.0030, -0.0439,  0.0103,  ..., -0.0076, -0.0134, -0.0029],
        [ 0.0187,  0.0127, -0.0055,  ..., -0.0164, -0.0085,  0.0246]],
       dtype=torch.float16), 'clip_l': tensor([[-1.6994e-03, -5.2551e-02, -3.4869e-05,  ..., -3.6640e-03,
          6.7472e-04, -2.6367e-02],
        [ 1.7776e-02, -3.3905e-02,  1.2856e-02,  ...,  3.2867e-02,
         -2.1637e-02,  2.2852e-04],
        [ 1.0429e-02,  9.4376e-03,  3.2166e-02,  ...,  3.0937e-03,
         -4.8248e-02, -6.9084e-03],
        [ 8.3923e-03, -1.4206e-02,  1.4198e-04,  ...,  2.7252e-02,
         -1.1581e-02,  1.2764e-02],
        [ 1.9424e-02, -1.2268e-02,  1.4778e-02,  ..., -6.7749e-03,
          1.5312e-02,  1.6144e-02],
        [ 7.1373e-03, -5.6877e-03,  3.8635e-02,  ...,  1.7365e-02,
         -2.0767e-02, -2.0618e-03]], dtype=torch.float16)}. 

Please verify that the loaded state dictionary of the textual embedding either only has a single key or includes the `string_to_param` input key.
```

### System Info

$ python3 --version
Python 3.10.12
$ pip3 show diffusers
Name: diffusers
Version: 0.29.2
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/diffusers/graphs/contributors)
Author-email: diffusers@huggingface.co
License: Apache 2.0 License
Location: /home/freitag/py/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by:
$ pip3 show transformers
Name: transformers
Version: 4.41.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /home/freitag/py/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: peft
$ pip3 show torch
Name: torch
Version: 2.3.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/freitag/py/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, basicsr, facexlib, gfpgan, kornia, peft, real-esrgan, spandrel, torchsde, torchvision, xformers

$diffusers-cli env
Traceback (most recent call last):
  File "/home/freitag/py/bin/diffusers-cli", line 8, in <module>
    sys.exit(main())
  File "/home/freitag/py/lib/python3.10/site-packages/diffusers/commands/diffusers_cli.py", line 39, in main
    service.run()
  File "/home/freitag/py/lib/python3.10/site-packages/diffusers/commands/env.py", line 100, in run
    bitsandbytes_version = bitsandbytes.__version__
AttributeError: module 'bitsandbytes' has no attribute '__version__'

### Who can help?

@sayakpaul,  @yiyixuxu

**Comment by sayakpaul** [comment]
Are you sure if this is only text embeddings?

**Comment by qdacsvx** [comment]
The syntax
```
pipeline.load_textual_inversion(
    weight_name="unaestheticXL_Jug6.safetensors", token="unaestheticXL_Jug6"
)
```
also errors.

> Traceback (most recent call last):
>   File "/tmp/basic.py", line 9, in <module>
>     pipe.load_textual_inversion("unaestheticXL_Jug6.safetensors", token="unaestheticXL_Jug6")
>   File "/home/freitag/py/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/home/freitag/py/lib/python3.10/site-packages/diffusers/loaders/textual_inversion.py", line 403, in load_textual_inversion
>     tokens, embeddings = self._retrieve_tokens_and_embeddings(tokens, state_dicts, tokenizer)
>   File "/home/freitag/py/lib/python3.10/site-packages/diffusers/loaders/textual_inversion.py", line 218, in _retrieve_tokens_and_embeddings
>     raise ValueError(
> ValueError: Loaded state dictionary is incorrect: {'clip_g': tensor([[-0.0159, -0.0213,  0.0058,  ...,  0.0093,  0.0232, -0.0084],
>         [ 0.0093, -0.0305, -0.0069,  ...,  0.0142,  0.0295,  0.0152],
>         [-0.0211, -0.0331,  0.0184,  ...,  0.0142, -0.0309,  0.0101],
>         [-0.0079, -0.0059, -0.0196,  ...,  0.0283,  0.0338,  0.0021],
>         [ 0.0030, -0.0439,  0.0103,  ..., -0.0076, -0.0134, -0.0029],
>         [ 0.0187,  0.0127, -0.0055,  ..., -0.0164, -0.0085,  0.0246]],
>        dtype=torch.float16), 'clip_l': tensor([[-1.6994e-03, -5.2551e-02, -3.4869e-05,  ..., -3.6640e-03,
>           6.7472e-04, -2.6367e-02],
>         [ 1.7776e-02, -3.3905e-02,  1.2856e-02,  ...,  3.2867e-02,
>          -2.1637e-02,  2.2852e-04],
>         [ 1.0429e-02,  9.4376e-03,  3.2166e-02,  ...,  3.0937e-03,
>          -4.8248e-02, -6.9084e-03],
>         [ 8.3923e-03, -1.4206e-02,  1.4198e-04,  ...,  2.7252e-02,
>          -1.1581e-02,  1.2764e-02],
>         [ 1.9424e-02, -1.2268e-02,  1.4778e-02,  ..., -6.7749e-03,
>           1.5312e-02,  1.6144e-02],
>         [ 7.1373e-03, -5.6877e-03,  3.8635e-02,  ...,  1.7365e-02,
>          -2.0767e-02, -2.0618e-03]], dtype=torch.float16)}. 
> 
> Please verify that the loaded state dictionary of the textual embedding either only has a single key or includes the `string_to_param` input key.

**Comment by sayakpaul** [comment]
No, I mean the checkpoint seems to be incorrectly formatted as we can see from the logs. Do you have a checkpoint that you know to be working with SDXL?

**Comment by qdacsvx** [comment]
@sayakpaul I tried other embeddings from civitai and all the ones I tried generate errors like this. I just want to load an embedding do you have suggestions how to load it?

**Comment by qdacsvx** [comment]
I didn't generate this embedding I don't know how it was created.

**Comment by asomoza** [comment]
You're using a SDXL textual inversion, you'll need to load it like it's shown in the [docs](https://huggingface.co/docs/diffusers/using-diffusers/textual_inversion_inference#stable-diffusion-xl).

```python
state_dict = load_file("unaestheticXL_Jug6.safetensors")
pipe.load_textual_inversion(
    state_dict["clip_g"], token="unaestheticXL_Jug6", text_encoder=pipe.text_encoder_2, tokenizer=pipe.tokenizer_2
)
pipe.load_textual_inversion(
    state_dict["clip_l"], token="unaestheticXL_Jug6", text_encoder=pipe.text_encoder, tokenizer=pipe.tokenizer
)

```

**Comment by qdacsvx** [comment]
Thanks @asomoza that works! All the embeddings I tried load. I didn't realise there was a special way for SDXL.
