### ISSUE TITLE
The running  using xformers is slower than when not using on A100

### ISSUE THREAD

**Issue by bigmover** [huggingface/diffusers#8873]
### Describe the bug

1. My diffusers version is 2.3.1+cu121 and xformers is 0.0.27
2. enable xformers with `pipe.enable_xformers_memory_efficient_attention()`
3. without xformers 4.27it/s. with xformers 4.00it/s on SDXL base model

I don't know wether the upscale attention will have an influence
https://github.com/huggingface/diffusers/blob/2ef9bdd76f69dfe7a6c125a3d76222140c685557/src/diffusers/models/attention_processor.py#L234

Would anyone like to give some adivce? Immensely grateful！

### Reproduction

 diffusers version is 2.3.1+cu121 and xformers is 0.0.27 on SDXL base model on A100

### System Info

 diffusers version is 2.3.1+cu121 and xformers is 0.0.27

### Who can help?

CC @yiyixuxu @sayakpaul @DN6 @asomoza 
I can't thank you enough

**Comment by sayakpaul** [comment]
Thanks for reporting. Which GPU are you using?

**Comment by tolgacangoz** [comment]
`PyTorch>=2.2` has already a newer attention -[FlashAttention-v2](https://pytorch.org/blog/pytorch2-2/). This might be the reason.

**Comment by sayakpaul** [comment]
And do you observe any speedups when not using xformers? Asking because when there's PyTorch 2 we default to using `scaled_dot_product_attention()`.

**Comment by bigmover** [comment]
> `PyTorch>=2.2` has already a newer attention -[FlashAttention-v2](https://pytorch.org/blog/pytorch2-2/). This might be the reason.

You mean scaled_dot_product_attention (SDPA) is automally used by diffusers, which is faster than xformers?

**Comment by sayakpaul** [comment]
Equivalent in terms of speedups.
