### ISSUE TITLE
How to Generate Multiple Image Inference in Instruct Pix2Pix

### ISSUE THREAD

**Issue by E-SJ** [huggingface/diffusers#8881]
Hello, I am currently working on how to utilize Instruct Pix2Pix for augmentation.
For this purpose, I want to generate images by putting a Tensor of shape [64,3,84,84] (batch,channel,width,height)shape into the Instruct Pix2Pix pipeline, but the Instruct Pix2Pix provided by diffusers can only edit for one image.
Is it possible to edit multiple images at the same time? It seems that it works only with 1 batch size. 
Is there way generate images with multiple batch size?

**Comment by tolgacangoz** [comment]
Hi @E-SJ. Did you try to multiply prompt like that:
```py
images = pipe(prompt=[prompt]*2, image=[image1, image2]).images
```
