### ISSUE TITLE
Unable to install clip-retrieval on colab and load modifier token when running Custom Diffusion example

### ISSUE THREAD

**Issue by yj373** [huggingface/diffusers#8885]
### Describe the bug

Hello,

When I tried to run the Custom Diffusion example on my colab, I met two issues:
1) I cannot install clip-retrieval on my colab and keep getting the following bug
```python
ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
2) There seems to be a bug on the "filename" in line 317, and it leads to an OSError when running the test example
```python
pipeline.unet.load_attn_procs("path-to-save-model", weight_name="pytorch_custom_diffusion_weights.bin")
pipeline.load_textual_inversion("path-to-save-model", weight_name="<new1>.bin")
```
I modified line 317 into 
```
filename = f"{output_dir}/{y}.bin" if args.no_safe_serialization else f"{output_dir}/{y}.safetensors"
```
It makes more sense to me.

### Reproduction

```python
!git clone https://github.com/huggingface/diffusers
%cd diffusers
!pip install .
%cd examples/custom_diffusion
!pip install -r requirements.txt
!pip install clip-retrieval
```

### System Info

- 🤗 Diffusers version: 0.30.0.dev0
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.12
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Huggingface_hub version: 0.23.4
- Transformers version: 4.42.4
- Accelerate version: not installed
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA L4, 23034 MiB VRAM
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@say

**Comment by yj373** [comment]
@sayakpaul

**Comment by tolgacangoz** [comment]
`clip-retrieval` tries to upgrade `blinker`; but it seems that this is not allowed. If I remove `blinker` as implemented [in this issue](https://github.com/googlecolab/colabtools/issues/3976#issuecomment-1701413919), then I am able to install `clip-retrieval` via pip.

**Comment by yj373** [comment]
Hi @tolgacangoz,

Thank you for your help! Your solution works and I have successfully installed ```clip-retrieval```. But when I ran the following command line:
```
!python diffusers/examples/custom_diffusion/retrieve.py --class_prompt dog --class_data_dir real_reg/samples_dog --num_class_images 200
```
I got the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/examples/custom_diffusion/retrieve.py", line 87, in <module>
    retrieve(args.class_prompt, args.class_data_dir, args.num_class_images)
  File "/content/diffusers/examples/custom_diffusion/retrieve.py", line 37, in retrieve
    class_images = client.query(text=class_prompt)
  File "/usr/local/lib/python3.10/dist-packages/clip_retrieval/clip_client.py", line 84, in query
    return self.__search_knn_api__(text=text)
  File "/usr/local/lib/python3.10/dist-packages/clip_retrieval/clip_client.py", line 153, in __search_knn_api__
    ).json()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Could you please help me with that? Thanks!

**Comment by yj373** [comment]
I found that this issues is because LAION dataset is no longer available, referring to [this](https://github.com/huggingface/diffusers/issues/6880).
