### ISSUE TITLE
SD3 wrong VAE encode in training script

### ISSUE THREAD

**Issue by JinxuXiang** [huggingface/diffusers#8887]
https://github.com/huggingface/diffusers/blob/c1dc2ae61968cccc3924784e4ed65ccfcd5c86eb/examples/dreambooth/train_dreambooth_lora_sd3.py#L1639

Should it be:

`model_input = (model_input - vae.config.shift_factor) * vae.config.scaling_factor`

**Comment by wangqixun** [comment]
Great attention to detail! The code we trained for the sd3 controlnet was written based on this, so it should also have this bug.
@haofanwang

**Comment by bghira** [comment]
i am guessing that needs to be applied during decode in the pipelines as well?
```py
            latents = (
                latents / self.vae.config.scaling_factor
            ) + self.vae.config.shift_factor

```

**Comment by sayakpaul** [comment]
@JinxuXiang Yeah you're right. Would you mind submitting a PR? Thank you very much.
