### ISSUE TITLE
![pacorosco_Photograph_of_a_model_outdoor_fashion_shoot_at_night _473ea442-73a0-443e-8c71-8fd91f226b86](https://github.com/user-attachments/assets/060b6b61-e346-4574-a997-0ab6c6b6d310)

### ISSUE THREAD

**Issue by patproduuuuu** [huggingface/diffusers#8904]
![pacorosco_Photograph_of_a_model_outdoor_fashion_shoot_at_night _473ea442-73a0-443e-8c71-8fd91f226b86](https://github.com/user-attachments/assets/060b6b61-e346-4574-a997-0ab6c6b6d310)

_Originally posted by @patproduuuuu in https://github.com/huggingface/diffusers/issues/8903#issuecomment-2238597810_

**Comment by a-r-r-o-w** [comment]
Please elaborate what the issue is, thanks

**Comment by a-r-r-o-w** [comment]
Closed due to inactivity
