### ISSUE TITLE
[Tests] Improve transformers model test suite coverage

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#8907]
Currently, we have different variants of transformers: https://github.com/huggingface/diffusers/tree/main/src/diffusers/models/transformers/. However, we don't have test suites for each of them: https://github.com/huggingface/diffusers/tree/main/tests/models/transformers/. 

We are seeking contributions from the community to improve this situation. Below is a list of the model for which we would really appreciate test suites for:

- [x] [Hunyuan DiT](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/transformers/hunyuan_transformer_2d.py)
- [x] [Latte](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/transformers/latte_transformer_3d.py)
- [x] [Lumina](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/transformers/lumina_nextdit2d.py)
- [x] [Temporal Transformer](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/transformers/transformer_temporal.py)

## How to approach the process? 

* Take the configuration object for each of these models from their respective pipeline tests suites. For example, for the Latte Transformer, it would be here: https://github.com/huggingface/diffusers/blob/3f1411767bc0f1837adb6f289713807f18599db3/tests/pipelines/latte/test_latte.py#L57
* Derive the expected inputs. You can do so by adding print statements to the corresponding pipeline file. For example, for the Latte Transformer, you could add print statements right here: https://github.com/huggingface/diffusers/blob/3f1411767bc0f1837adb6f289713807f18599db3/src/diffusers/pipelines/latte/pipeline_latte.py#L801 to investigate the shapes of the outputs and then use that information accordingly. 
* Then it should be just about defining the test suite like so: https://github.com/huggingface/diffusers/blob/main/tests/models/transformers/test_models_transformer_sd3.py. 

## Points to keep in mind when opening PRs

* Mention this issue and tag @DN6 and myself. 
* Target only one modeling test at a time.

**Comment by chiral-carbon** [comment]
hi @sayakpaul! Could I pick up Lumina?

**Comment by MnCSSJ4x** [comment]
Hi @sayakpaul Could I pick up Hunyuan DiT?

**Comment by sayakpaul** [comment]
It’s here https://github.com/huggingface/diffusers/pull/8916

**Comment by MnCSSJ4x** [comment]
I had a look at the PR. I wanted to know if its still open for contribution or the PR mentioned handled it?

**Comment by saqlain2204** [comment]
Hey @sayakpaul  . I would like to take a shot on Lumina

**Comment by sayakpaul** [comment]
We successfully completed the test suite coverage. Great work every one!
