### ISSUE TITLE
kolors lora training

### ISSUE THREAD

**Issue by loboere** [huggingface/diffusers#8933]
please add lora training for kolors

**Comment by asomoza** [comment]
Kolors has the same arch as SDXL but with just one text encoder, the training script for SDXL should be easy enough to adapt.

Also the text encoder is big which makes it not really trainable with consumer GPUs, if you just want to train the unet it should be even easier to adapt.

If you are serious about training, you can use [SimpleTuner](https://github.com/bghira/SimpleTuner) which added support for [kolors](https://github.com/bghira/SimpleTuner/blob/main/documentation/quickstart/KOLORS.md) and uses diffusers.

**Comment by LianShuaiLong** [comment]
> Kolors has the same arch as SDXL but with just one text encoder, the training script for SDXL should be easy enough to adapt.
> 
> Also the text encoder is big which makes it not really trainable with consumer GPUs, if you just want to train the unet it should be even easier to adapt.
> 
> If you are serious about training, you can use [SimpleTuner](https://github.com/bghira/SimpleTuner) which added support for [kolors](https://github.com/bghira/SimpleTuner/blob/main/documentation/quickstart/KOLORS.md) and uses diffusers.

it so hard to training lora with SimpleTuner, the environment seems hard to configure 😢

**Comment by asomoza** [comment]
Since it uses diffusers it should have almost the same dependencies plus some additional ones for training that you can manually install, probably you can just use the same environment you use with diffusers.

**Comment by LianShuaiLong** [comment]
> Since it uses diffusers it should have almost the same dependencies plus some additional ones for training that you can manually install, probably you can just use the same environment you use with diffusers.

I will try it,thanks

**Comment by LianShuaiLong** [comment]
> Since it uses diffusers it should have almost the same dependencies plus some additional ones for training that you can manually install, probably you can just use the same environment you use with diffusers.

it seems DreamBooth method? How can i train lora like the way of kohya/sd-scripts ?

**Comment by asomoza** [comment]
kohya also can train with dreambooth, probably you mean just normal lora training right? I haven't really tried to train kolors so probably it will be better to ask directly in the repo, maybe someone that already tried can answer.

**Comment by LianShuaiLong** [comment]
> kohya also can train with dreambooth, probably you mean just normal lora training right? I haven't really tried to train kolors so probably it will be better to ask directly in the repo, maybe someone that already tried can answer.

yes, i want to train with normal lora since i have (image,caption) pair,

**Comment by asomoza** [comment]
Just be sure what are you using to train and what do you want to achieve, you can still train a Dreambooth lora with a normal image and caption pair, that doesn't mean you're using Dreambooth or not.

**Comment by LianShuaiLong** [comment]
> Just be sure what are you using to train and what do you want to achieve, you can still train a Dreambooth lora with a normal image and caption pair, that doesn't mean you're using Dreambooth or not.

Here I have a batch of paired data: images and their corresponding text descriptions. I want to use this batch of data to fine-tune Kolors with the LoRA method

**Comment by a-r-r-o-w** [comment]
Agree with @asomoza that training script for SDXL requires minimal changes to support this. Since supporting Kolors training script is not planned by us, I'm marking this as closed for now. I find SimpleTuner to be much more convenient for things like this so would really recommend trying that out if modifying the SDXL script is not possible/feasible on your end.

**Comment by EmmaThompson123** [comment]
@LianShuaiLong How do you train the lora of kolors finnally ?
