### ISSUE TITLE
OSError: Can't load tokenizer for 'stabilityai/stable-diffusion-3-medium-diffusers'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/stable-diffusion-3-medium-diffusers' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

### ISSUE THREAD

**Issue by dann2333** [huggingface/diffusers#8939]
### Describe the bug

Hi, I'm trying to fine-tuning stabilityai/stable-diffusion-3-medium-diffusers and using [the official diffuser scripts](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sd3.py). However it couldn't start. I've logged in into huggingface using a FINEGRAINED token. And I've also checked that there's not any folder named stable-diffusion-3-medium-diffusers on my machine.

### Reproduction

 accelerate launch train_dreambooth_lora_sd3.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-3-medium-diffusers" --output_dir=lora-sd3 --instance_data_dir="sample-imgs" --instance_prompt="xxx" --resolution=1000 --train_batch_size=1 --train_text_encoder --gradient_accumulation_steps=4 --optimizer="adamw" --learning_rate=1e-6  --text_encoder_lr=5e-7 --lr_scheduler="constant" --lr_warmup_steps=450 --max_train_steps=3000 --rank=32 --seed="42" --gradient_checkpointing --resume_from_checkpoint latest --center_crop

### Logs

```shell
Traceback (most recent call last):
  File "/root/train_dreambooth_lora_sd3.py", line 1873, in <module>
    main(args)
  File "/root/train_dreambooth_lora_sd3.py", line 1126, in main
    tokenizer_one = CLIPTokenizer.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2147, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'stabilityai/stable-diffusion-3-medium-diffusers'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'stabilityai/stable-diffusion-3-medium-diffusers' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib//site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', 'train_dreambooth_lora_sd3.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-3-medium-diffusers', '--output_dir=lora-sd3', '--instance_data_dir=sample-imgs', '--instance_prompt=xxx', '--resolution=1000', '--train_batch_size=1', '--train_text_encoder', '--gradient_accumulation_steps=4', '--optimizer=adamw', '--learning_rate=1e-6', '--text_encoder_lr=5e-7', '--lr_scheduler=constant', '--lr_warmup_steps=450', '--max_train_steps=3000', '--rank=32', '--seed=42', '--gradient_checkpointing', '--resume_from_checkpoint', 'latest', '--center_crop']' returned non-zero exit status 1.
```

### System Info

- 🤗 Diffusers version: 0.30.0.dev0
- Platform: Linux-6.5.0-25-generic-x86_64-with-glibc2.35
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.13
- PyTorch version (GPU?): 2.2.1 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.0
- Transformers version: 4.42.4
- Accelerate version: 0.32.1
- PEFT version: 0.11.1
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA GeForce RTX 4060 Ti, 16380 MiB VRAM
- Using GPU in script?: NVIDIA GeForce RTX 4060 Ti, 16380 MiB VRAM
- Using distributed or parallel set-up in script?: No

**Comment by tolgacangoz** [comment]
When I try without any token it gives the same error. But, when I try with an ordinary READ access token it works.

**Comment by dann2333** [comment]
> When I try without any token it gives the same error. But, when I try with an ordinary READ access token it works. There must be something wrong/missing with the FINEGRAINED one.

Oh thanks! Using a token with READ access fixed that issue
