### ISSUE TITLE
libtorch_cuda_cu.so: cannot open shared object file, when installing diffusers of main branch

### ISSUE THREAD

**Issue by huangjun12** [huggingface/diffusers#8943]
### Describe the bug

Bug log: libtorch_cuda_cu.so: cannot open shared object file, when installing diffusers of main branch.

### Reproduction

pip install -e ".[torch]"

```python
from diffusers import StableDiffusion3InpaintPipeline
```

### System Info

python3.9
torch version: 2.0 + cuda11.7

**Comment by tolgacangoz** [comment]
The easiest thing to do would be to create a new conda environment and `pip install -e ".[torch]"` again. Is this option possible for you?

**Comment by huangjun12** [comment]
bug comes from commit id `588fb5c1050b143176aff4572f3892a166343231`
I tried latest code version,  commit id `41b705f42db6ce43bbcb41bd2cefd479d8b73774`,  it seems fixed, thx~
