### ISSUE TITLE
[SD3] bug in SD3 LoRA Training

### ISSUE THREAD

**Issue by townwish4git** [huggingface/diffusers#8950]
### Describe the bug

Codes here delete `tokenizers` and `text_encoders` which would be used later for `train_dataset.custom_instance_prompts`
https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sd3.py#L1457-L1463

The if-else logic here needs to be adjusted to prevent error `UnboundLocalError: local variable 'text_encoders' referenced before assignment`
```diff
# Clear the memory here
- if not args.train_text_encoder and train_dataset.custom_instance_prompts:
+ if not args.train_text_encoder and not train_dataset.custom_instance_prompts:
    del tokenizers, text_encoders
    # Explicitly delete the objects as well, otherwise only the lists are deleted and the original references remain, preventing garbage collection
    del text_encoder_one, text_encoder_two, text_encoder_three
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
```

### Reproduction

just adjust the example in [README_sd3.md](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_sd3.md): use a custom_instance_prompts dataset like `YaYaB/onepiece-blip-captions` and add argument `--caption_column="text"`

```shell
export MODEL_NAME="stabilityai/stable-diffusion-3-medium-diffusers"
export DATASET_NAME="YaYaB/onepiece-blip-captions"
export OUTPUT_DIR="trained-sd3-lora"

accelerate launch train_dreambooth_lora_sd3.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$DATASET_NAME \
  --output_dir=$OUTPUT_DIR \
  --mixed_precision="fp16" \
  --instance_prompt="a photo of sks dog" \
  --caption_column="text" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --learning_rate=1e-5 \
  --report_to="wandb" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="A photo of sks dog in a bucket" \
  --validation_epochs=25 \
  --seed="0" \
  --push_to_hub
```

### System Info

Independent of the system

### Who can help?

@sayakpaul @yiyixuxu

**Comment by sayakpaul** [comment]
Ah thank you! Would you mind opening a PR?

**Comment by townwish4git** [comment]
> Ah thank you! Would you mind opening a PR?

OK😉
