### ISSUE TITLE
StableDiffusionSafetyChecker ignores `attn_implementation` load kwarg

### ISSUE THREAD

**Issue by jambayk** [huggingface/diffusers#8957]
### Describe the bug

`transformers` added `sdpa` and FA2 for CLIP model in https://github.com/huggingface/transformers/pull/31940. It now initializes the vision model like https://github.com/huggingface/transformers/blob/85a1269e19af022e04bc2aad82572cd5a9e8cdd9/src/transformers/models/clip/modeling_clip.py#L1143. 

However, `StableDiffusionSafetyChecker` uses https://github.com/huggingface/diffusers/blob/2c25b98c8ea74cfb5ec56ba49cc6edafef0b26af/src/diffusers/pipelines/stable_diffusion/safety_checker.py#L41 so it always gets initialized with sdpa attention. 

### Reproduction

```python
from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker

model = StableDiffusionSafetyChecker.from_pretrained(
    "runwayml/stable-diffusion-v1-5", 
    subfolder="safety_checker", 
   attn_implementation="eager"
)
print(type(model.vision_model.vision_model.encoder.layers[0].self_attn))
```

Expected `transformers.models.clip.modeling_clip.CLIPAttention` but got `transformers.models.clip.modeling_clip.CLIPSdpaAttention`.

### System Info

diffusers 0.29.0
transformers 4.43.1

### Who can help?

@sayakpaul @dn

**Comment by sayakpaul** [comment]
Thanks for bringing this up. CLIP FA2 and SDPA support is very recent. If you want to open a PR to fix this, we are happy to guide you.

**Comment by a-r-r-o-w** [comment]
Gentle ping @jambayk if you would like to help contribute support for this!

**Comment by jambayk** [comment]
Hi @a-r-r-o-w, sorry for missing the previous reply about contributing. Unfortunately, I don't think I can make the contribution for this as we just ended up pinning the diffuser version in our example.

**Comment by a-r-r-o-w** [comment]
Oh okay, we'll see how we can try improving this. Sorry for the delay! cc @sayakpaul

**Comment by sayakpaul** [comment]
SDPA for CLIP is in `transformers` for a while. Could you please try updating your installation of `transformers` retry?

**Comment by jambayk** [comment]
I just checked with the latest packages. With transformers>=4.46, passing `attn_implementation="eager"` in `StableDiffusionSafetyChecker.from_pretrained` now gives the expected eager attention module instead of sdpa. The issue is present below below transformers 4.46. 

I haven't delved deep into the source of the fix but it's probably this PR which fixed the behavior for stable diffusion also since it automatically updates the `_attn_implementation_internal` attributes for all sub model configs. 

Please feel free to close this issue.

**Comment by a-r-r-o-w** [comment]
Thanks for letting us know that it works as expected now! Marking it as resolved
