### ISSUE TITLE
pipelines: loading safetensors

### ISSUE THREAD

**Issue by townwish4git** [huggingface/diffusers#8968]
## 1. Problem

When I tried to load `ShapEPipeline` from .safetensors files like
```py
pipe = DiffusionPipeline.from_pretrained(
    "openai/shap-e",
    torch_dtype=torch.float16,
    use_safetensors=True,
    revision="refs/pr/11",
    variant="fp16",
    force_download=True,
)
```
where [revision "refs/pr/11"](https://huggingface.co/openai/shap-e/discussions/11/files) has all components of fp16.safetensors, it raised error:
```
text_encoder/model.safetensors not found
Traceback (most recent call last):
  File ".../test_shape.py", line 9, in <module>
    pipe = DiffusionPipeline.from_pretrained(
  File ".../lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File ".../diffusers/src/diffusers/pipelines/pipeline_utils.py", line 671, in from_pretrained
    cached_folder = cls.download(
  File ".../lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File ".../diffusers/src/diffusers/pipelines/pipeline_utils.py", line 1338, in download
    raise EnvironmentError(
OSError: Could not find the necessary `safetensors` weights in {'renderer/diffusion_pytorch_model.fp16.safetensors', 'shap_e_renderer/diffusion_pytorch_model.fp16.safetensors', 'text_encoder/model.fp16.safetensors', 'text_encoder/pytorch_model.bin', 'shap_e_renderer/diffusion_pytorch_model.bin', 'prior/diffusion_pytorch_model.fp16.safetensors', 'prior/diffusion_pytorch_model.bin', 'renderer/diffusion_pytorch_model.bin'} (variant=fp16)
```

## 2. Cause

Error message says diffusers couldn't find `text_encoder/model.safetensors`, because there is only  `text_encoder/model.fp16.safetensors`, which means `variant="fp16"` does not take effect.

Dive into [`src/diffusers/pipelines/pipeline_loading_utils.py`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/pipeline_loading_utils.py#L132) and find that argument `variant` has not been used.

## 3. Solution 

Perhaps we can make a slight modification to the code here to enable the argument 'variant' to take effect：

```diff
def is_safetensors_compatible(filenames, variant=None, passed_components=None) -> bool:
    ...
    for filename in pt_filenames:
        ...
        expected_sf_filename = os.path.normpath(os.path.join(path, filename))
-        expected_sf_filename = f"{expected_sf_filename}.safetensors"
+        expected_sf_filename = f"{expected_sf_filename}.{variant}.safetensors" if variant else f"{expected_sf_filename}.safetensors"
        if expected_sf_filename not in sf_filenames:
            logger.warning(f"{expected_sf_filename} not found")
            return False

    return True
```

@yiyixuxu @DN6 @sayakpaul

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu

**Comment by DN6** [comment]
Hi @townwish4git thanks for catching. Indeed this looks like the check fails when a model folder contains a `.bin` file and just a variant. 

Your proposed change looks good but we would also need to update some of the tests in `tests/pipelines/test_pipeline_utils.py`. 

I can open a PR to fix.

**Comment by a-r-r-o-w** [comment]
Think this was fixed in the linked PR, so marking this issue as closed. In case I missed something, feel free to re-open, thanks!
