### ISSUE TITLE
[Kolors] MPS always return black image

### ISSUE THREAD

**Issue by bqhuyy** [huggingface/diffusers#8970]
### Describe the bug

Running Kolors with MPS, the returned result is always black image. 

### Reproduction

Run this source code. Output image returns black image
```python
pipe = KolorsPipeline.from_pretrained("Kwai-Kolors/Kolors-diffusers", torch_dtype=torch.float16, variant="fp16")

if torch.cuda.is_available():
  pipe = pipe.to("cuda")
elif torch.backends.mps.is_available():
  pipe = pipe.to("mps")

pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)

# Recommended if your computer has < 64 GB of RAM
if torch.backends.mps.is_available():
  pipe.enable_attention_slicing()

prompt = '一张瓢虫的照片，微距，变焦，高质量，电影，拿着一个牌子，写着"可图"'

image = pipe(
    prompt=prompt,
    negative_prompt="",
    guidance_scale=6.5,
    num_inference_steps=25,
).images[0]
image.save("kolors.png")
```

### System Info

- version: diffusers-0.30.0.dev0
- OS: Mac
- CPU: Apple silicon m1 pro

### Who can help?

@asomoza @yiyixuxu

**Comment by tolgacangoz** [comment]
Did/Could you try with the latest stable and Nightly PyTorch versions?

**Comment by bqhuyy** [comment]
@tolgacangoz I'm using the latest one: `pytorch 2.4.0` and `torchvision 0.19.0`

**Comment by tolgacangoz** [comment]
What happens with `torch_dtype=torch.bfloat16` or `torch_dtype=torch.float32`? Does `torch_dtype=torch.float32` exceed your memory?

**Comment by bqhuyy** [comment]
@asomoza I've tested on original repo, it returns same result as `diffusers`

**Comment by bqhuyy** [comment]
@tolgacangoz It seems that the problem comes from `pipe.enable_attention_slicing()`. It works after removing it.
