### ISSUE TITLE
Generation steps stuck at 0

### ISSUE THREAD

**Issue by Sanfee18** [huggingface/diffusers#8994]
### Describe the bug

When I run my python code everything gets loaded correctly, but the image generation gets stuck at 0 steps and doesn't advance.

### Reproduction

Fresh new Anaconda environment, install the necessary libraries: _pip install diffusers transformers accelerate opencv-python torch torchvision torchaudio_

**Python code:**
```
from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, AutoencoderKL
from diffusers import DDIMScheduler, EulerAncestralDiscreteScheduler
from PIL import Image, ImageOps
import torch

prompt = "kid in the mountain"
negative_prompt = 'longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality'


eulera_scheduler = EulerAncestralDiscreteScheduler.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", subfolder="scheduler")


controlnet = ControlNetModel.from_pretrained(
    "xinsir/controlnet-scribble-sdxl-1.0",
    torch_dtype=torch.float16
)

# when test with other base model, you need to change the vae also.
vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)

pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    controlnet=controlnet,
    vae=vae,
    torch_dtype=torch.float16,
    scheduler=eulera_scheduler,
)

# if you use a sketch image total draw by yourself
drawing_path = "/path/to/image" # omitted for privacy reasons but not the problem
controlnet_img = Image.open(drawing_path)
# Invert the image for black background and white lines
inverted_image = ImageOps.invert(controlnet_img.convert('RGB'))
width, height  = inverted_image.size

images = pipe(
    prompt,
    negative_prompt=negative_prompt,
    image=controlnet_img,
    controlnet_conditioning_scale=0.6,
    control_guidance_start=0.0,
    control_guidance_end=1.0,
    width=width,
    height=height,
    num_inference_steps=30,
    ).images

images[0].save(f"image.png")

```

### System Info

- 🤗 Diffusers version: 0.29.2
- Platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.31
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.14
- PyTorch version (GPU?): 2.4.0+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.2
- Transformers version: 4.43.3
- Accelerate version: 0.33.0
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA A30, 24576 MiB VRAM
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@sayakpaul @DN6

**Comment by asomoza** [comment]
is not that it gets stuck at 0 but more that's going really slow because you're using the CPU instead of the GPU

you need to send the pipeline to the GPU:

```python
pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    controlnet=controlnet,
    vae=vae,
    torch_dtype=torch.float16,
    scheduler=eulera_scheduler,
).to("cuda")
```

**Comment by Sanfee18** [comment]
True! Thank you so much and sorry for the inconvenience 😅
