### ISSUE TITLE
UNET slower by a factor of batch_size

### ISSUE THREAD

**Issue by christopher5106** [huggingface/diffusers#9009]
### Describe the bug

I was expecting to get faster inferences by batching images together. I realized that when I batch 6 images together, the UNET is 5 times slower for a pipeline_controlnet_img2img.py... 

Is it possible or normal ? Do I miss anything ? Thanks for your help

### Reproduction

Image dim 1024.

I measure the time of this operations

```python
                noise_pred = self.unet(
                    latent_model_input,
                    t,
                    encoder_hidden_states=prompt_embeds,
                    cross_attention_kwargs=self.cross_attention_kwargs,
                    down_block_additional_residuals=down_block_res_samples,
                    mid_block_additional_residual=mid_block_res_sample,
                    added_cond_kwargs=added_cond_kwargs,
                    return_dict=False,
                )[0]
```

for two cases:

1/ batch size 1: here is the size of inputs

latent_model_input torch.Size([2, 4, 64, 64]) cuda:0
prompt_embeds torch.Size([2, 77, 768]) cuda:0
down_block_res_samples
torch.Size([2, 320, 64, 64]) cuda:0
torch.Size([2, 320, 64, 64]) cuda:0
torch.Size([2, 320, 64, 64]) cuda:0
torch.Size([2, 320, 32, 32]) cuda:0
torch.Size([2, 640, 32, 32]) cuda:0
torch.Size([2, 640, 32, 32]) cuda:0
torch.Size([2, 640, 16, 16]) cuda:0
torch.Size([2, 1280, 16, 16]) cuda:0
torch.Size([2, 1280, 16, 16]) cuda:0
torch.Size([2, 1280, 8, 8]) cuda:0
torch.Size([2, 1280, 8, 8]) cuda:0
torch.Size([2, 1280, 8, 8]) cuda:0
mid_block_res_sample torch.Size([2, 1280, 8, 8]) cuda:0

2/ for batch 6:

latent_model_input torch.Size([12, 4, 64, 64]) cuda:0
prompt_embeds torch.Size([12, 77, 768]) cuda:0
down_block_res_samples
torch.Size([12, 320, 64, 64]) cuda:0
torch.Size([12, 320, 64, 64]) cuda:0
torch.Size([12, 320, 64, 64]) cuda:0
torch.Size([12, 320, 32, 32]) cuda:0
torch.Size([12, 640, 32, 32]) cuda:0
torch.Size([12, 640, 32, 32]) cuda:0
torch.Size([12, 640, 16, 16]) cuda:0
torch.Size([12, 1280, 16, 16]) cuda:0
torch.Size([12, 1280, 16, 16]) cuda:0
torch.Size([12, 1280, 8, 8]) cuda:0
torch.Size([12, 1280, 8, 8]) cuda:0
torch.Size([12, 1280, 8, 8]) cuda:0
mid_block_res_sample torch.Size([12, 1280, 8, 8]) cuda:0

The UNET is on cuda:0 also, everything in torch.float16.

In case 1, Unet inference time is 0.054 
In the case 2, unet inference time is 0.2671

So I batch 6 images and it goes 5 times slower.

With/without ip_adapater, does not change these times.

### System Info

torch==2.4.0
diffusers==0.27.2
transformers==4.40.1
accelerate==0.29.3

CUDA Version: 12.4 

GPU: A10, A40, same problem

### Who can help?

@DN6 @yiyixuxu @sayakpaul

**Comment by sayakpaul** [comment]
Batching usually helps when compute-boundedness is not a problem. Diffusion models are compute-bound and hence batching won't always help.

**Comment by christopher5106** [comment]
OK that's what I thought... the 10 000 cores are already saturated by the parallel computations of the layers in the UNET... Thanks for confirming it.
