### ISSUE TITLE
[v0.29.2] TypeError: load_checkpoint_and_dispatch() got an unexpected keyword argument 'force_hook'

### ISSUE THREAD

**Issue by TsingZ0** [huggingface/diffusers#9026]
### Describe the bug

An error occurs when setting `device_map='balanced'` in `StableDiffusionPipeline.from_pretrained` to run the model on multiple GPUs. In the latest release, version 0.29.2, the parameter name in the `accelerate.load_checkpoint_and_dispatch` function ([line 822](https://github.com/huggingface/diffusers/blob/v0.29.2/src/diffusers/models/modeling_utils.py#L822)) should be `force_hooks` instead of `force_hook`. After correcting this, the Stable Diffusion model can be successfully loaded onto multiple GPUs without further issues.

### Reproduction

```python
from diffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_pretrained(
    'generator/stable-diffusion/v1.5', # local path
    torch_dtype=torch.float16, 
    device_map='balanced', 
    local_files_only=True, 
    use_safetensors=True
)
```

### Logs

Traceback (most recent call last):
  File "/home/look_SD.py", line 16, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/gen/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/gen/lib/python3.12/site-packages/diffusers/pipelines/pipeline_utils.py", line 881, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/gen/lib/python3.12/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 703, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/gen/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/miniconda3/envs/gen/lib/python3.12/site-packages/diffusers/models/modeling_utils.py", line 815, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
TypeError: load_checkpoint_and_dispatch() got an unexpected keyword argument 'force_hook'

### System Info

- 🤗 Diffusers version: 0.29.2
- Platform: Linux-5.15.0-105-generic-x86_64-with-glibc2.31
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.12.4
- PyTorch version (GPU?): 2.4.0+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.5
- Transformers version: 4.43.3
- Accelerate version: 0.33.0
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA RTX A6000, 49140 MiB
NVIDIA RTX A6000, 49140 MiB
NVIDIA RTX A6000, 49140 MiB
NVIDIA RTX A6000, 49140 MiB VRAM
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by a-r-r-o-w** [comment]
Would you like to open a PR with the proposed fix?

cc @sayakpaul

**Comment by sayakpaul** [comment]
Thanks for this! As Aryan suggested, would you be interested in opening a PR to fix this? This way, your contributions will be in the library :)

**Comment by sayakpaul** [comment]
Also, shoutout to @tolgacangoz for the reworking out dev cli log. It's looking very nice.

**Comment by TsingZ0** [comment]
Thank you for the prompt response! I have opened a PR to the [v0.29.2-patch](https://github.com/huggingface/diffusers/tree/v0.29.2-patch)
