### ISSUE TITLE
consistency in argument names

### ISSUE THREAD

**Issue by christopher5106** [huggingface/diffusers#9027]
### Describe the bug

`tokens` should be `token` for consistency with load method:
https://huggingface.co/docs/diffusers/en/api/loaders/textual_inversion#diffusers.loaders.TextualInversionLoaderMixin.unload_textual_inversion 

Load method https://huggingface.co/docs/diffusers/en/api/loaders/textual_inversion#diffusers.loaders.TextualInversionLoaderMixin.load_textual_inversion 
uses single argument `token=`

### Reproduction

-

### System Info

-

**Comment by a-r-r-o-w** [comment]
Since the argument name cannot be changed at the moment for backwards compatibility, it is better to update the docs. Maybe I could flag this for 1.0.0 refactor where making breaking changes like this would be okay. I do think using `tokens` as the argument name in all occurrences would be better.

**Comment by a-r-r-o-w** [comment]
Closing because fixed for now in #9940
