### ISSUE TITLE
how to use prompt weight in FlaxStableDiffusionPipeline

### ISSUE THREAD

**Issue by fancy45daddy** [huggingface/diffusers#9038]
### Describe the bug

I can see there are prompt_embeds in StableDiffusionPipeline to support Prompt weighting, But how to do that in FlaxStableDiffusionPipeline? there are not prompt_embeds in StableDiffusionPipeline

### Reproduction

N/A

### System Info

kaggle tpu vm

**Comment by fancy45daddy** [comment]
please help

**Comment by asomoza** [comment]
Hi, you need to implement it yourself. I don't use or know flax, but if you look at the code, you probably need to implement this in the `prepare_inputs` function.

You can't just use the pytorch version of this. Also there's `prompt_embeds` in both pipelines so I don't quite get what you mean by that.

**Comment by asomoza** [comment]
closing this since there were no more questions.
