### ISSUE TITLE
how to load_lora_weights in FlaxStableDiffusionPipeline

### ISSUE THREAD

**Issue by fancy45daddy** [huggingface/diffusers#9039]
### Describe the bug

how to load lora in FlaxStableDiffusionPipeline, there are no load_lora_weights in FlaxStableDiffusionPipeline

### Reproduction

N/A

### System Info

kaggle tpu vm

**Comment by fancy45daddy** [comment]
please help

**Comment by yiyixuxu** [comment]
thanks for your issue! indeed we do not support load_lora_weights with flax pipeines 
do you have a lora trained in flax you want to load into flax pipeline?

**Comment by yiyixuxu** [comment]
closing now since it is not active! let us know if you have more info and we will re-open!
