### ISSUE TITLE
Add Flux pipeline (Black Forest Labs)

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [huggingface/diffusers#9042]
### Model/Pipeline/Scheduler description

Blog: https://blackforestlabs.ai/announcing-black-forest-labs/
Implementation: https://github.com/black-forest-labs
Weights: https://huggingface.co/black-forest-labs

Seems like it's just "bigger SD3".

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://github.com/black-forest-labs

**Comment by charchit7** [comment]
Super fast added by @sayakpaul and team https://github.com/huggingface/diffusers/pull/9043

**Comment by sayakpaul** [comment]
Done in https://github.com/huggingface/diffusers/pull/9043.

**Comment by sayakpaul** [comment]
It was really a team effort, Charchit. I just opened the PR.
