### ISSUE TITLE
StableDiffusio3Pipeline cannot convert to CUDA device with accelerate & peft

### ISSUE THREAD

**Issue by shingjan** [huggingface/diffusers#9045]
### Describe the bug

`accelerate` with `peft` will load the sd3 pipeline on device `meta` which cannot be moved to device `cuda` later like in the official sd3 blog [post](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_3). Uninstalling `accelerate` & `peft` solve the issue but also unfortunately prevent sd3 pipeline from loading lora weights.

### Reproduction

`pip install diffusers accelerate peft`
and then run
```
import torch
from diffusers import StableDiffusion3Pipeline

pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float16)
pipe.to("cuda")

image = pipe(
    prompt="a photo of a cat holding a sign that says hello world",
    negative_prompt="",
    num_inference_steps=28,
    height=1024,
    width=1024,
    guidance_scale=7.0,
).images[0]

image.save("sd3_hello_world.png")
```

### Logs

```shell
Loading pipeline components...:  11%|█████████▍                                                                           | 1/9 [00:00<00:01,  5.13it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  5.51it/s]
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.77it/s]
Traceback (most recent call last):
  File "repro.py", line 20, in <module>
    pipe = pipe.to("cuda")
  File "/home/yshi/miniconda3/envs/dy/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 431, in to
    module.to(device, dtype)
  File "/home/yshi/miniconda3/envs/dy/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2724, in to
    return super().to(*args, **kwargs)
  File "/home/yshi/miniconda3/envs/dy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/home/yshi/miniconda3/envs/dy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/home/yshi/miniconda3/envs/dy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/home/yshi/miniconda3/envs/dy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 853, in _apply
    self._buffers[key] = fn(buf)
  File "/home/yshi/miniconda3/envs/dy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1166, in convert
    raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
```

### System Info

- 🤗 Diffusers version: 0.29.2
- Platform: Linux-5.15.0-1048-aws-x86_64-with-glibc2.31
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.14
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.5
- Transformers version: 4.41.2
- Accelerate version: 0.33.0
- PEFT version: 0.12.0
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed

### Who can help?

@yiyixuxu @sayakpaul @DN6 @asomoza

**Comment by shingjan** [comment]
bumping this for visibility @yiyixuxu @sayakpaul @DN6 @asomoza

**Comment by asomoza** [comment]
Hi, that's the normal common install most people have, I cannot reproduce your error. If I just copy and paste your code I can generate an image without problem. Also `peft` only gets used if you load a lora.

Your error is telling that the error happens with:

```
pipe.to("cuda")
```

So there's probably something wrong with your install or your environment, I suggest start again your environment and reinstall everything, also make sure you can use "cuda". I have tested diffusers with AWS and didn't have a problem with it.

You can test this easy:

```python
import torch

print(f"{torch.cuda.is_available()=}")
print(f"{torch.cuda.device_count()=}")
print(f"{torch.cuda.current_device()=}")
```

You should get something like this:

```
torch.cuda.is_available()=True
torch.cuda.device_count()=1
torch.cuda.current_device()=0
```

**Comment by shingjan** [comment]
@asomoza thanks for the reply! Just figured this is due to a env parameter on my local end. Closing this and thanks again for the help!
