### ISSUE TITLE
flux does not work on MPS devices

### ISSUE THREAD

**Issue by bghira** [huggingface/diffusers#9047]
### Describe the bug

```
    scale = torch.arange(0, dim, 2, dtype=torch.float64, device=pos.device) / dim
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

### Reproduction

```py
import torch
from diffusers import  FluxPipeline

pipe = FluxPipeline.from_pretrained("black-forest-labs/FLUX.1-schnell", torch_dtype=torch.bfloat16, revision='refs/pr/1')
#pipe.enable_model_cpu_offload()
pipe.to(device='mps')

prompt = "A cat holding a sign that says hello world"
out = pipe(
    prompt=prompt, 
    guidance_scale=0., 
    height=768, 
    width=1360, 
    num_inference_steps=4, 
    max_sequence_length=256,
).images[0]
out.save("image.png")
```

it also doesn't work with cpu offload.

### Logs

```shell
scale = torch.arange(0, dim, 2, dtype=torch.float64, device=pos.device) / dim
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

### System Info

Git master

### Who can help?

@sayakpaul

**Comment by bghira** [comment]
![image](https://github.com/user-attachments/assets/dce3ce22-d799-469a-beb3-8107ba235036)
can't switch to fp32 😢

**Comment by bghira** [comment]
@pcuenca i've been looking at workarounds and there's really nothing, and this model is too big to run on CPU, it just never really completes the first step.

**Comment by sayakpaul** [comment]
No idea how to get around this problem :(

**Comment by bghira** [comment]
it also doesn't work on ROCm, as the dimensions of the operations overflow the ROCm kernel limits, so, it has to run layer-wise and takes about 2 minutes for one image

**Comment by bghira** [comment]
maybe @rromb or @pesser have some ideas

**Comment by pcuenca** [comment]
Great investigation @bghira! It's a bit surprising that it degrades so much with `float32`. Also unfortunate:

```
RuntimeError: "arange_mps" not implemented for 'BFloat16'
```

**Comment by Vargol** [comment]
Has anyone tried running just the arrange on the CPU for MPS if its supported and pushing the results back on the GPU, @bghira when you said flux didn't run on the CPU is that what you meant or were you referring to running the whole model ?

**Comment by mgierschdev** [comment]
in my case: 
RuntimeError: MPS backend out of memory (MPS allocated: 81.54 GB, other allocations: 384.00 KB, max allowed: 81.60 GB). Tried to allocate 72.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

any idea ? on how to run on a Mac M2

**Comment by bghira** [comment]
you cannot run it at all on any mac series but especially not m1 as it doesnt even have bf16 in hardware

**Comment by Vargol** [comment]
> ![image](https://private-user-images.githubusercontent.com/59658056/354430511-dce3ce22-d799-469a-beb3-8107ba235036.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NzcxODQsIm5iZiI6MTcyMjc3Njg4NCwicGF0aCI6Ii81OTY1ODA1Ni8zNTQ0MzA1MTEtZGNlM2NlMjItZDc5OS00NjlhLWJlYjMtODEwN2JhMjM1MDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzMDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZWI5OWU5OTM2NTViMjE2NGI4N2I1MGYwNjQxZjg1ZmJiZTczY2Y1ZWQ1NzBlZTJlYzIxOTQ3MDllNGI5YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bR8dG4gmU5qfoKmqTXIQ1Y9IOlZ5fCZyhPxQJVyuJfs) can't switch to fp32 😢

Try it with torch 2.3.1

![flux_image](https://github.com/user-attachments/assets/4431e88a-d805-4d13-b8f5-ed832af29259)

**Comment by bghira** [comment]
i am on 2.4 for bf16 and its fixes

**Comment by Vargol** [comment]
If only there was a way you could have two python environments at once <joke> , but it shows that the noisey image from float32 isn't a fundamental issue with flux

**Comment by Vargol** [comment]
Interesting, if you monkey patch  the rope function to move pos to the CPU you still get noise with 2.4.0  with both float32 and float64, the fp64  runs fine on CPU with 2.3.1.

```py
import torch
from diffusers import  FluxPipeline
import diffusers

_flux_rope = diffusers.models.transformers.transformer_flux.rope
def new_flux_rope(pos: torch.Tensor, dim: int, theta: int) -> torch.Tensor:
    assert dim % 2 == 0, "The dimension must be even."

    if pos.device.type == "mps":
        print("I got called")
        return _flux_rope(pos.to("cpu"), dim, theta).to(device=pos.device)
    else:
        print("I should not be called")
        return _flux_rope(pos, dim, theta)

diffusers.models.transformers.transformer_flux.rope = new_flux_rope

pipe = FluxPipeline.from_pretrained("black-forest-labs/FLUX.1-schnell", revision='refs/pr/1',  torch_dtype=torch.bfloat16).to("mps")

prompt = "A cat holding a sign that says hello world"
out = pipe(
     prompt=prompt,
     guidance_scale=0.,
     height=1024,
     width=1024,
     num_inference_steps=4,
     max_sequence_length=256,
).images[0]
out.save("flux_image.png")
```

**Comment by bghira** [comment]
:/ the trainer i'm using requires torch 2.4, and the model is basically useless to me without torch 2.4 as that is also required to run it in lower precision levels

**Comment by Vargol** [comment]
If you need 2.4.0 to work raise an issue over on the PyTorch Repo

**Comment by bghira** [comment]
then it will never be solved as the pytorch team often simply ignores mps issues. thanks for the suggestion.

**Comment by mgierschdev** [comment]
I will be supported by WIP, https://github.com/argmaxinc/DiffusionKit/pull/11

**Comment by bghira** [comment]
that is totally different - they are making use of MLX, not Pytorch+MPS.

**Comment by bghira** [comment]
yes... but it has nothing to do with Diffusers and remains to be seen whether it works with the correct outputs on this platform - once it's in DiffusionKit, we still don't have any way to use it in the Diffusers pipeline ecosystem.

**Comment by bghira** [comment]
CoreML may be efficient on the surface, but last I tried only supported square images and every custom model has to be converted manually, which will take hours for Flux.D or Flux.S - it already took hours to convert SDXL models on a 128G M3 Max. it's going to need a lot of system memory to quantise Flux using CoreML.

i just don't see it as a very useful thing - it's more like a toy

**Comment by Vargol** [comment]
On the ComfyUI equivalent issue, someone is suggesting the it works with the torch nightlies on the beta version of macOS 15.

https://github.com/comfyanonymous/ComfyUI/issues/4165#issuecomment-2267557459

I'm not running it so can't confirm if its true to not, I do know that is at least some macOS 15 code in Torch (or was assuming its not been rolled back) so there is hope

**Comment by AaronWard** [comment]
![image](https://github.com/user-attachments/assets/1bf49b51-b362-43dc-8018-719682e28db3)

On M3 Macbook pro using the `_flux_rope` hack with `bfloat16`, the model is returning only grainy results. 

---

- https://github.com/huggingface/diffusers/pull/9097

Saw this PR on `diffusers` with a potential fix. haven't tried it myself yet.

**Comment by Vargol** [comment]
> ![image](https://private-user-images.githubusercontent.com/22074246/355402332-1bf49b51-b362-43dc-8018-719682e28db3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Mzg0ODgsIm5iZiI6MTcyMjkzODE4OCwicGF0aCI6Ii8yMjA3NDI0Ni8zNTU0MDIzMzItMWJmNDliNTEtYjM2Mi00M2RjLTgwMTgtNzE5NjgyZTI4ZGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA5NTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTM0OTRmNTkxMjUyNWQ5YjY1ZjcxZjAzZDZkN2UzN2U1MjhkNjA5MmVlZWNiYmI5MTg5MDgyZGIzNTg4NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3994hdZyhSpAdTj1YhHTr1Gs67cM6Ntx76Dx1F0opxA)
> 
> On M3 Macbook pro using the `_flux_rope` hack with `bfloat16`, the model is returning only grainy results.
> 
> * [Flux fp16 inference fix #9097](https://github.com/huggingface/diffusers/pull/9097)
> 
> Saw this PR on `diffusers` with a potential fix. haven't tried it myself yet.

What version of pytorch are you using ?  
If you read the rest of the issue you'll see that that the noise image is due to issues with PyTorch 2.4

**Comment by bghira** [comment]
![image](https://github.com/user-attachments/assets/6c2dfdf6-6554-49c6-9b7e-91308dfe0133)

well the same issue occurs with pytorch nightly on MacOS 14. i don't really think upgrading to a beta OS release is the way to resolve it, but that's good to know.

**Comment by Vargol** [comment]
@AaronWard   I've tried the fp16 fix, and while it fixes running the model for inference on float16, it still gives a noisy image as the end result in torch 2.4.0.

It would be nice if someone with proper torch skills could get to the bottom of this but I suspect we're going to have to wait for MacOS 15.

**Comment by bghira** [comment]
i've updated to macos 15:

![image](https://github.com/user-attachments/assets/fc937d09-fde1-4cb8-a48c-80f20c95ab5b)

**Comment by Vargol** [comment]
With a PyTorch nightly ?

**Comment by bghira** [comment]
yes

**Comment by bghira** [comment]
also, pytorch 2.3.1 has about a 30% speed reduction vs 2.4.1 on MPS

**Comment by hvaara** [comment]
float64 is not supported on MPS. https://github.com/huggingface/diffusers/pull/9133 proposes to fix that issue.

The noisy output image is a separate bug in PyTorch. Follow https://github.com/pytorch/pytorch/issues/133520 for updates.

**Comment by bghira** [comment]
is fp64 a hw limitation? or just MPS limitation? i guess i could check metal docs..

**Comment by bghira** [comment]
https://github.com/philipturner/metal-float64

ah jeez

**Comment by bghira** [comment]
torch nightly has some real performance regressions since they refactored the sdpa backends for mps

**Comment by bauerwer** [comment]
agree, I am seeing a fairly big performance degradation on nightly torch as well (on MPS)

**Comment by sayakpaul** [comment]
We recently added support for this. So, inference, should at least work. Closing, hence. Feel free to reopen.

**Comment by hvaara** [comment]
xref #9133 #9074

**Comment by Vargol** [comment]
Release 0.30.3 seems to have the old version of the flux code with the torch.float64 reference in the rope version was that expected ?


```
(Diffusers) M3iMac:Diffusers davidburnett$ pip show Diffusers
Name: diffusers
Version: 0.30.3
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/diffusers/graphs/contributors)
Author-email: diffusers@huggingface.co
License: Apache 2.0 License
Location: /Volumes/SSD2TB/AI/Diffusers/lib/python3.11/site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by: 
```

```py
  File "/Volumes/SSD2TB/AI/Diffusers/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 65, in <listcomp>
    [rope(ids[..., i], self.axes_dim[i], self.theta) for i in range(n_axes)],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SSD2TB/AI/Diffusers/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 41, in rope
    scale = torch.arange(0, dim, 2, dtype=torch.float64, device=pos.device) / dim
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu @a-r-r-o-w ^.
