### ISSUE TITLE
cannot import name 'StableAudioPipeline' from 'diffusers'

### ISSUE THREAD

**Issue by Gcurtis95** [huggingface/diffusers#9062]
### Describe the bug

Hi, I'm getting an error cannot import name 'StableAudioPipeline' from 'diffusers' (c:\Users\Garin\anaconda3\envs\DiffusersEdit1.1\lib\site-packages\diffusers_init_.py). Have only just installed diffusers so should be up to date.
I checked in the init.py and it's not listed there so tried to add it but it didn't work.

### Reproduction

import torch
import soundfile as sf
from diffusers import StableAudioPipeline

pipe = StableAudioPipeline.from_pretrained("stabilityai/stable-audio-open-1.0", torch_dtype=torch.float16)
pipe = pipe.to("cuda")

### System Info

- 🤗 Diffusers version: 0.29.2
- Platform: Windows-10-10.0.22621-SP0
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.14
- PyTorch version (GPU?): 2.4.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.3
- Transformers version: 4.43.3
- Accelerate version: 0.33.0
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA GeForce RTX 4080 Laptop GPU, 12282 MiB VRAM
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

**Comment by tolgacangoz** [comment]
`StableAudioPipeline` has just been added(in `0.30.0.dev0`). [Just install from the source.](https://huggingface.co/docs/diffusers/main/en/installation#install-from-source)

**Comment by tolgacangoz** [comment]
`StableAudioPipeline` has just been added/merged(in `0.30.0.dev0`) [3 days ago](https://github.com/huggingface/diffusers/pull/8716#event-13693377418). [Just install from the source.](https://huggingface.co/docs/diffusers/main/en/installation#install-from-source)

**Comment by a-r-r-o-w** [comment]
Closing this issue because it was an environment version issue.
