### ISSUE TITLE
 No module named 'diffusers.hub_utils'

### ISSUE THREAD

**Issue by elliotthwang** [huggingface/diffusers#9067]
### Describe the bug

Training with Diffusers
 Installing the dependencies
   %%capture
   !pip install git+https://github.com/huggingface/diffusers.git#egg=diffusers[training]
   !pip install accelerate
   ! pip install datasets

   from accelerate import Accelerator
   from diffusers.hub_utils import init_git_repo, push_to_hub
   from tqdm.auto import tqdm
   import os

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-28-790bd6e8744b>](https://localhost:8080/#) in <cell line: 2>()
      1 from accelerate import Accelerator
----> 2 from diffusers.hub_utils import init_git_repo, push_to_hub
      3 
      4 from tqdm.auto import tqdm
      5 import os

ModuleNotFoundError: No module named 'diffusers.hub_utils'

### Reproduction

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-28-790bd6e8744b>](https://localhost:8080/#) in <cell line: 2>()
      1 from accelerate import Accelerator
----> 2 from diffusers.hub_utils import init_git_repo, push_to_hub
      3 
      4 from tqdm.auto import tqdm
      5 import os

ModuleNotFoundError: No module named 'diffusers.hub_utils'

### System Info

!pip install git+https://github.com/huggingface/diffusers.git#egg=diffusers[training]

### Who can help?

@say

**Comment by a-r-r-o-w** [comment]
These were deprecated in https://github.com/huggingface/diffusers/pull/1022. You will have to
- either downgrade diffusers to a version when the script you are using was made
- update the script to use the latest alternatives (PushToHubMixin) and `huggingface_hub.Repository`

**Comment by elliotthwang** [comment]
@a-r-r-o-w  
Thank you for your advices!

**Comment by a-r-r-o-w** [comment]
Thanks, glad to be of help. Let us know if you need further help :)
