### ISSUE TITLE
Add a better version of 'callback_on_step_end' for FluxPipeline

### ISSUE THREAD

**Issue by nayan-dhabarde** [huggingface/diffusers#9076]
**Is your feature request related to a problem? Please describe.**
There is a huge delay before starting the inference and once the 4th step is complete and there is no callback for that and it feels like it is stuck, just want a more responsive version.
```
prompt = "A cat holding a sign that says hello world"
image = pipe(
    prompt,
    guidance_scale=0.0,
    output_type="pil",
    num_inference_steps=4,
    max_sequence_length=256,
    generator=torch.Generator("cuda").manual_seed(0)
).images[0]
print('started saving file')
image.save("flux-schnell.png")
```
If you run the above code, it feels like you are stuck at step 0 and then after 4/4 is done
I am using a 48GB A40

**Describe the solution you'd like.**
Can we get some kind of callback for these two delays as well

**Comment by a-r-r-o-w** [comment]
Flux uses [Google T5 XXL](https://huggingface.co/google/t5-v1_1-xxl) as one of its text encoders. Encoding the prompt takes a while and is why you see the long amount of wait time before step 0. After step 4/4, there is a decode phase where you go from small dimensions to larger dimensions using a VAE. This also requires some extra time.

If you want to speed up the slow parts by a bit, you can `torch.compile` the text encoders, transformer and vae. For other inference speed optimizations, would be better to google.

If you want the latents directly after step 4/4 is complete, you can set `output_type="latent"`. If you want faster decoding, you're going to have to use a faster/smaller autoencoder than the default Flux comes with. We also support [callbacks](https://github.com/huggingface/diffusers/blob/3dc10a535f55aebf96d47c0395aa2be5d7553ed2/src/diffusers/pipelines/flux/pipeline_flux.py#L525) which can use to get the latents at each step, and right after the 4th step.

**Comment by a-r-r-o-w** [comment]
Marking as closed due to inactivity
