### ISSUE TITLE
add ControlNet support for Flux.1

### ISSUE THREAD

**Issue by geroldmeisinger** [huggingface/diffusers#9081]
Flux has been released almost a week ago (which is like 1 year in AI time) and appears to be the new SOTA for open txt2img! Please add ControlNet support. Pretty please!

**Comment by g123413927** [comment]
Looking forward to it

**Comment by haofanwang** [comment]
On the way. Still tuned.

**Comment by geroldmeisinger** [comment]
https://github.com/huggingface/diffusers/pull/9175
