### ISSUE TITLE
controlnet training script for flux

### ISSUE THREAD

**Issue by universewill** [huggingface/diffusers#9085]
controlnet training script for flux

**Comment by geroldmeisinger** [comment]
https://github.com/XLabs-AI/x-flux/blob/main/train_flux_deepspeed_controlnet.py

**Comment by kadirnar** [comment]
> https://github.com/XLabs-AI/x-flux/blob/main/train_flux_deepspeed_controlnet.py

I tested it this week but multi gpu is not working in parallel. I kept getting cuda memory error.

**Comment by kadirnar** [comment]
@sayakpaul Could you add this feature to the Diffusers library?

**Comment by sayakpaul** [comment]
Sorry we don’t have the bandwidth for this on the team. But happy to help if a contributor wants pick it up.

**Comment by kadirnar** [comment]
> Sorry we don’t have the bandwidth for this on the team. But happy to help if a contributor wants pick it up.

I don't know much about train code but I will try. Thanks for your feedback.

**Comment by christopher-beckham** [comment]
Has it not already been done here? https://github.com/huggingface/diffusers/pull/9175

**Comment by kadirnar** [comment]
> Has it not already been done here? #9175

This is just the inference code. I want the train code.

**Comment by sayakpaul** [comment]
https://github.com/huggingface/diffusers/pull/9324

**Comment by a-r-r-o-w** [comment]
Closing this due to #9324. Feel free to open if I missed something

**Comment by TongrongHuang** [comment]
> > https://github.com/XLabs-AI/x-flux/blob/main/train_flux_deepspeed_controlnet.py
> 
> I tested it this week but multi gpu is not working in parallel. I kept getting cuda memory error.

I have also encountered this problem now. At first, I experienced OOM during training on one A100 (80G), but when I use two A100 (80G), I still have OOM. Have you solved it?

**Comment by christopher-beckham** [comment]
The batch size is the individual gpu batch size so adding an extra GPU isn't going to help (assuming you're doing data parallelism here): https://github.com/XLabs-AI/x-flux/blob/main/train_flux_deepspeed_controlnet.py#L165
