### ISSUE TITLE
FluxPipeline not found in diffusers

### ISSUE THREAD

**Issue by Twenkid** [huggingface/diffusers#9089]
### Describe the bug

I am trying: https://huggingface.co/docs/diffusers/main/en/api/pipelines/flux
and: https://huggingface.co/black-forest-labs/FLUX.1-dev

Either: !pip install -U diffusers
and 
!pip install git+https://github.com/huggingface/diffusers.git

However:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[20], line 3
      1 import torch
      2 import sentencepiece 
----> 3 from diffusers import FluxPipeline
      4 pipe = FluxPipeline.from_pretrained("black-forest-labs/FLUX.1-dev", torch_dtype=torch.bfloat16)
      5 pipe.enable_model_cpu_offload()

ImportError: cannot import name 'FluxPipeline' from 'diffusers' (/opt/conda/lib/python3.10/site-packages/diffusers/__init__.py)
```

print(dir(diffusers)) ...

There's no  "Flux..."

Also for Tesla T4 the "torch_dtype=torch.bfloat16" should be torch_dtype=torch.float16" or so, but the execution can't reach to that check.

* import sentencepiece  -- that was suggested in another issue, I guess it is irrelevant

### Reproduction

https://www.kaggle.com/code/todora/flux-6-8-2024-12b-text-to-img

### System Info

Kaggle 2xT4

**Comment by a-r-r-o-w** [comment]
You need to install Diffusers from source for FluxPipeline to be available since it's not in an official release yet. So `pip install git+https://github.com/huggingface/diffusers.git` is correct.

Judging by the error log, it looks like you're running in a notebook. When installing packages, or reinstalling different versions, you must restart your kernel for the new package to take effect

**Comment by charchit7** [comment]
Hey @a-r-r-o-w I am getting this error : 

`HfHubHTTPError                            Traceback (most recent call last)
Cell In[2], [line 4](vscode-notebook-cell:?execution_count=2&line=4)
      [1](vscode-notebook-cell:?execution_count=2&line=1) import torch
      [2](vscode-notebook-cell:?execution_count=2&line=2) from diffusers import FluxPipeline
----> [4](vscode-notebook-cell:?execution_count=2&line=4) pipe = FluxPipeline.from_pretrained("black-forest-labs/FLUX.1-schnell", torch_dtype=torch.bfloat16)
      [5](vscode-notebook-cell:?execution_count=2&line=5) # pipe.enable_model_cpu_offload() #save some VRAM by offloading the model to CPU. Remove this if you have enough GPU power
      [7](vscode-notebook-cell:?execution_count=2&line=7) prompt = "A cat holding a sign that says hello world"`

`'HfHubHTTPError: 416 Client Error: Requested Range Not Satisfiable for url: '`

Can you help me on this, please?

**Comment by Twenkid** [comment]
Thanks! Yes, in Kaggle.  Colab reminds to restart the kernel, but Kaggle doesn't. That resolved this problem.
Unfortunately the notebook runs out of CPU memory (29 GB), while loading the pipeline components, after 71%.

(Also the hf_token has to be set as the model requires authorization.)

![image](https://github.com/user-attachments/assets/7b361555-75db-4883-a843-db7edc641a5c)

```
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
 0/0 [00:00<?, ?it/s]
2024-08-06 20:03:18.371426: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-06 20:03:18.371578: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-06 20:03:18.526758: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
model_index.json: 100%
 536/536 [00:00<00:00, 45.4kB/s]
Fetching 23 files: 100%
 23/23 [02:21<00:00,  7.51s/it]
text_encoder/config.json: 100%
 613/613 [00:00<00:00, 12.3kB/s]
tokenizer/merges.txt: 100%
 525k/525k [00:00<00:00, 3.65MB/s]
scheduler/scheduler_config.json: 100%
 273/273 [00:00<00:00, 4.57kB/s]
text_encoder_2/config.json: 100%
 782/782 [00:00<00:00, 10.9kB/s]
(…)t_encoder_2/model.safetensors.index.json: 100%
 19.9k/19.9k [00:00<00:00, 374kB/s]
model.safetensors: 100%
 246M/246M [00:03<00:00, 69.9MB/s]
model-00002-of-00002.safetensors: 100%
 4.53G/4.53G [01:25<00:00, 89.7MB/s]
model-00001-of-00002.safetensors: 100%
 4.99G/4.99G [01:32<00:00, 63.9MB/s]
tokenizer/tokenizer_config.json: 100%
 705/705 [00:00<00:00, 13.2kB/s]
tokenizer_2/special_tokens_map.json: 100%
 2.54k/2.54k [00:00<00:00, 82.5kB/s]
tokenizer/special_tokens_map.json: 100%
 588/588 [00:00<00:00, 11.9kB/s]
tokenizer/vocab.json: 100%
 1.06M/1.06M [00:00<00:00, 6.34MB/s]
spiece.model: 100%
 792k/792k [00:00<00:00, 4.83MB/s]
tokenizer_2/tokenizer.json: 100%
 2.42M/2.42M [00:00<00:00, 14.8MB/s]
tokenizer_2/tokenizer_config.json: 100%
 20.8k/20.8k [00:00<00:00, 681kB/s]
transformer/config.json: 100%
 378/378 [00:00<00:00, 12.8kB/s]
(…)pytorch_model-00001-of-00003.safetensors: 100%
 9.98G/9.98G [02:20<00:00, 115MB/s]
(…)pytorch_model-00002-of-00003.safetensors: 100%
 9.95G/9.95G [02:06<00:00, 93.9MB/s]
(…)pytorch_model-00003-of-00003.safetensors: 100%
 3.87G/3.87G [01:15<00:00, 69.1MB/s]
(…)ion_pytorch_model.safetensors.index.json: 100%
 121k/121k [00:00<00:00, 1.62MB/s]
vae/config.json: 100%
 820/820 [00:00<00:00, 35.5kB/s]
diffusion_pytorch_model.safetensors: 100%
 168M/168M [00:03<00:00, 77.8MB/s]
Loading pipeline components...:  71%
 5/7 [01:43<00:26, 13.13s/it]
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
```

**Comment by Twenkid** [comment]
Here's an example of a quantized version which runs even on Colab with one T4:

https://gist.github.com/AmericanPresidentJimmyCarter/873985638e1f3541ba8b00137e7dacd9

https://gist.github.com/AmericanPresidentJimmyCarter/873985638e1f3541ba8b00137e7dacd9?permalink_comment_id=5141813#gistcomment-5141813

flux.1-schnell - https://colab.research.google.com/github/camenduru/flux-jupyter/blob/main/flux.1-schnell_jupyter.ipynb
flux.1-dev - https://colab.research.google.com/github/camenduru/flux-jupyter/blob/main/flux.1-dev_jupyter.ipynb
flux.1-dev-image-2-image - https://colab.research.google.com/github/camenduru/flux-jupyter/blob/main/flux.1-dev-i2i_jupyter.ipynb

**Comment by a-r-r-o-w** [comment]
Awesome and thanks for sharing! Now that Flux has been integrated into Diffusers in the stable build, the normal `pip install diffusers` should work as well for importing the pipeline. Closing this since looks resolved now but let us know if there are any other problems :)
