### ISSUE TITLE
Fluxpipeline report model_index.json not found

### ISSUE THREAD

**Issue by chongxian** [huggingface/diffusers#9092]
### Describe the bug

I use the Fluxpipeline and report no file model_index.json.
I read other issue and set the `revision="refs/pr/3"`,but it doesn't work, how can i do to solve this problem and how to use the T5xxl as text encoder? thanks for your help

### Reproduction

```
import torch
from diffusers import FluxPipeline

pipe = FluxPipeline.from_pretrained("/opt/ml/volume/default/aigc/project/chanPin/models/flux", revision="refs/pr/3",torch_dtype=torch.bfloat16)
pipe.enable_model_cpu_offload()

prompt = "a tiny astronaut hatching from an egg on the moon"
out = pipe(
    prompt=prompt, 
    guidance_scale=3.5, 
    height=768, 
    width=1360, 
    num_inference_steps=50,
).images[0]
out.save("image.png")
```

### System Info

ubuntu 20.04

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
Remove `revision="refs/pr/3"`. The PRs were merged.

**Comment by chongxian** [comment]
> Remove `revision="refs/pr/3"`. The PRs were merged.

```
import torch
from diffusers import FluxPipeline

pipe = FluxPipeline.from_pretrained("/opt/ml/volume/default/aigc/project/chanPin/models/flux-dev",torch_dtype=torch.bfloat16)
pipe.enable_model_cpu_offload()

prompt = "a tiny astronaut hatching from an egg on the moon"
out = pipe(
    prompt=prompt, 
    guidance_scale=3.5, 
    height=768, 
    width=1360, 
    num_inference_steps=50,
).images[0]
out.save("image.png")
```
I remove this `revision="refs/pr/3"` but also report **OSError: Error no file named model_index.json found in directory /opt/ml/volume/default/aigc/project/chanPin/models/flux-dev**

**Comment by sayakpaul** [comment]
Can you remove your local clone and try with a fresh clone please?
