### ISSUE TITLE
FLUX's inference speed is so slow

### ISSUE THREAD

**Issue by chenbinghui1** [huggingface/diffusers#9095]
I run FLUX1.-dev on V100-32G GPU card, the inference code is like:
`
pipe = FluxPipeline.from_pretrained("checkpoints/FLUX.1-dev", 
                                    torch_dtype=torch.bfloat16,
                                    low_cpu_mem_usage=True)
pipe.enable_model_cpu_offload()

image = pipe(
        prompt,
        height=1024,
        width=1024,
        guidance_scale=3.5,
        output_type="np",
        num_inference_steps=50,
        max_sequence_length=512,
        generator=generator
        ).images
`

the inference time costs nearly 7minutes:
![image](https://github.com/user-attachments/assets/a9e81938-09f8-4f25-b103-9141960d747b)

is this normal? Does anyone meet this ?

**Comment by latentCall145** [comment]
V100 Tensor Cores don't support bfloat16. Try casting to torch.float16 and try again. (note: I just made a [PR](https://github.com/huggingface/diffusers/pull/9097) to fix FP16 inference, you may need to install my diffusers fork if it's not merged)

**Comment by chenbinghui1** [comment]
@latentCall145  Thanks for your PR, the inference time can be reduced to nearly 90s, and the image quality seems right. BTW when using the same prompt and seed, the output image is different compared to bfloat16.

**Comment by sayakpaul** [comment]
Precision would change the result, I would assume.

**Comment by bghira** [comment]
for some models it changes it much more than others. sometimes for the better!

**Comment by latentCall145** [comment]
> Precision would change the result, I would assume.

It's a dynamic range issue, not a precision issue. It's discussed in my PR but I'm also stating it here in case they haven't seen it

**Comment by a-r-r-o-w** [comment]
I believe this has been addressed, yes? If not, please feel free to re-open
