### ISSUE TITLE
Dreambooth started to return bad config

### ISSUE THREAD

**Issue by zetyquickly** [huggingface/diffusers#911]
### Describe the bug

Hello, 

In current master whenever I train dreambooth it returns model's folder that cannot be seamlessly utilized by `StableDiffusionPipeline.from_pretrained`. Previous training worked good.

Now command on the pre-trained model folder results in 
```
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected {'unet', 'vae', 'text_encoder', 'feature_extractor', 'scheduler', 'tokenizer', 'safety_checker'}, but only {'unet', 'vae', 'text_encoder', 'scheduler', 'tokenizer'} were passed.
```

And it is actually like that, some keys are missing in the JSON file and the folders with binaries too.

Training was done by 8Gb setup:

```
accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of sks dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 --gradient_checkpointing \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=800 \
  --mixed_precision=fp16
  ```
  
  accelerate is setup to store intermediate data on the CPU.

### System Info

- Diffusers on commit a9908ecfc1730bfd1a2fe0dfc01125fef67746a3
- Platform: Linux-4.19.0-21-cloud-amd64-x86_64-with-glibc2.28
- Python version: 3.10.6
- PyTorch version (GPU?): 1.12.1 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by pcuenca** [comment]
Hi @zetyquickly thanks for reporting this!

Does the error happen when you load a model trained using Dreambooth, or when you run the training script?

**Comment by zetyquickly** [comment]
The error happens during initialization for inference

````
import torch
from diffusers import StableDiffusionPipeline

# load the pipeline
device = "cuda"
model_id_or_path = "/home/jupyter/diffusers/examples/dreambooth/model"
pipe = StableDiffusionPipeline.from_pretrained(
    model_id_or_path,
    torch_dtype=torch.float16,
)
```

Stacktrace
```
Traceback (most recent call last):
  File "/home/jupyter/diffusers/my_scripts/txt2img.py", line 12, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(
  File "/home/jupyter/fast-stable-diffusion/diffusers/src/diffusers/pipeline_utils.py", line 482, in from_pretrained
    raise ValueError(
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected {'unet', 'vae', 'text_encoder', 'feature_extractor', 'scheduler', 'tokenizer', 'safety_checker'}, but only {'unet', 'vae', 'text_encoder', 'scheduler', 'tokenizer'} were passed.
```

**Comment by zetyquickly** [comment]
Yes, the above caused an issue.
Dreambooth trained using original  `huggingface/diffusers` doesn't fail during inference
