### ISSUE TITLE
Error using AnimateDiff-Lightning and SDXL motion adapter

### ISSUE THREAD

**Issue by MonkeeMan1** [huggingface/diffusers#9115]
### Describe the bug

Hello,

I asked a question in the HF Discord to see if it was possible to use `"ByteDance/AnimateDiff-Lightning"` and the SDXL motion adapter together. I was told to come here and make an issue.

When attempting to implement these to models together, on `diffusers==0.30`, I get an error saying Incompatible motion adapter.

### Reproduction

SDXL - https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0
Animate-diff-lightning - https://huggingface.co/ByteDance/AnimateDiff-Lightning
sdxl motion adapter - https://huggingface.co/guoyww/animatediff-motion-adapter-sdxl-beta

```py
step = 4  # Options: [1,2,4,8]
repo = "ByteDance/AnimateDiff-Lightning"
ckpt = f"animatediff_lightning_{step}step_diffusers.safetensors"

adapter = MotionAdapter().to(device, dtype)
adapter.load_state_dict(load_file(hf_hub_download(repo ,ckpt), device=device))

scheduler = DDIMScheduler.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    subfolder="scheduler",
    clip_sample=False,
    timestep_spacing="linspace",
    beta_schedule="linear",
    # steps_offset=1,
)
pipe = AnimateDiffSDXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    motion_adapter=adapter,
    scheduler=scheduler,
    torch_dtype=torch.float16,
    variant="fp16",
).to("cuda")
pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config, timestep_spacing="trailing", beta_schedule="linear")
```

### Logs

```shell
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00,  8.95it/s]
Traceback (most recent call last):
  File "C:\Users\james\OneDrive\Desktop\AI FLUX\animate.py", line 27, in <module>
    pipe = AnimateDiffSDXLPipeline.from_pretrained(
  File "C:\Users\james\OneDrive\Desktop\AI FLUX\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\james\OneDrive\Desktop\AI FLUX\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 966, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "C:\Users\james\OneDrive\Desktop\AI FLUX\venv\lib\site-packages\diffusers\pipelines\animatediff\pipeline_animatediff_sdxl.py", line 283, in __init__
    unet = UNetMotionModel.from_unet2d(unet, motion_adapter)
  File "C:\Users\james\OneDrive\Desktop\AI FLUX\venv\lib\site-packages\diffusers\models\unets\unet_motion_model.py", line 544, in from_unet2d
    raise ValueError("Incompatible Motion Adapter, got different number of blocks")
ValueError: Incompatible Motion Adapter, got different number of blocks
```

### System Info

- 🤗 Diffusers version: 0.30.0.dev0
- Platform: Windows-10-10.0.22631-SP0
- Running on Google Colab?: No
- Python version: 3.10.11
- PyTorch version (GPU?): 2.4.0+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.5
- Transformers version: 4.43.3
- Accelerate version: 0.33.0
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA GeForce RTX 4090, 24564 MiB
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@dn and @a-r-r-o-w

**Comment by a-r-r-o-w** [comment]
AnimateDiff Lightning is compatible only with SD1.5 based models and can't really work with SDXL due to differing model architectures. Their [model page](https://huggingface.co/ByteDance/AnimateDiff-Lightning) also mentions that their motion adapters were distilled from the original SD1.5 motion adapters. Hopefully there's something for SDXL soon!

**Comment by MonkeeMan1** [comment]
> AnimateDiff Lightning is compatible only with SD1.5 based models and can't really work with SDXL due to differing model architectures. Their [model page](https://huggingface.co/ByteDance/AnimateDiff-Lightning) also mentions that their motion adapters were distilled from the original SD1.5 motion adapters. Hopefully there's something for SDXL soon!

Thank you! :)

**Comment by a-r-r-o-w** [comment]
Awesome, let us know if there's anything else we can help with :)
