### ISSUE TITLE
Diffusers model not working as good as repo ckpt model

### ISSUE THREAD

**Issue by kunalkathare** [huggingface/diffusers#9140]
Hi,
When I try to run the models stable diffusion v1-5 or Instructpix2pix through the diffusers pipeline and use .from_pretrained() it downloads the models from hugging face and I'm using the code to run inference given in hugging face, the results are not good at all in the sense that there is still noise in the generated images.

But when I run these models using their GitHub repo code and ckpt models given by them the outputs are very good.

Is there any solution to this or any other way to use the diffusers library pipeline.

Also the diffusers.StableDiffusionInstructPix2PixPipeline does not have .from_single_file() option.

Thank you

**Comment by a-r-r-o-w** [comment]
cc @sayakpaul

**Comment by asomoza** [comment]
Hi, we need a minimal snippet of the code that can reproduce the issue and probably some demo images showing the problem. There shouldn't be any difference between the original one and diffusers one, I've used a lot the SD 1,5 before and there wasn't any difference between them so this is probably an issue with the generation parameters.

**Comment by sayakpaul** [comment]
`from_single_file()` is a separate thing and we really haven't had enough issues about that from the community. So, I am not sure if it's worth adding. Cc: @DN6

**Comment by asomoza** [comment]
closing this issue since we didn't receive more updates to help find the problem, if there's more information I will reopen.
