### ISSUE TITLE
Add Flux inpainting pipeline

### ISSUE THREAD

**Issue by AmericanPresidentJimmyCarter** [huggingface/diffusers#9148]
### Model/Pipeline/Scheduler description

There is a lot of discussion and colabs here: https://old.reddit.com/r/StableDiffusion/comments/1epi1d0/flux_better_than_photoshop_for_inpainting/

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

**Comment by anilsathyan7** [comment]
@Gothos Is there a way to reduce GPU vram usage for inpaint? The schnell bf16 version does not seem to work even with 32 gb GPU. 
Ref: 
https://huggingface.co/spaces/SkalskiP/FLUX.1-inpaint-dev/blob/main/app.py
https://huggingface.co/black-forest-labs/FLUX.1-schnell/discussions/5

**Comment by AmericanPresidentJimmyCarter** [comment]
Closed because merged
