### ISSUE TITLE
please add flux img2img with controlnet pipeline

### ISSUE THREAD

**Issue by loboere** [huggingface/diffusers#9151]
please add flux img2img with controlnet in a single pipeline

**Comment by momah** [comment]
Is there any news on that?
I'm making a docker api with flux and it's working fine, but I don't know how to add img2img. I have seen in the demos there is a method that does image to image but I have not been able to achieve it, they are third-party libraries

**Comment by asomoza** [comment]
closing this issue since it was added with this [PR](https://github.com/huggingface/diffusers/pull/9408)
