### ISSUE TITLE
strange noise dot in StableDiffusionControlNetPipeline

### ISSUE THREAD

**Issue by Sonia-kong** [huggingface/diffusers#9181]
### Describe the bug

Hi team, thanks for your wonderful work.
When I used StableDiffusionControlNetPipeline, I found that some pictures had strange noise, similar to black and white dots. 
the input is:
![swancon](https://github.com/user-attachments/assets/fb7f1560-113e-43ca-b21d-875aa57a610b)
the output is:
![output](https://github.com/user-attachments/assets/13880134-7bd4-4c80-9771-ae4f4c6eaac1)
where you can see the strange noise in the right, and I don't know the reason.

Thank you very much for your help. This problem has troubled me for a long time.

### Reproduction

```
import torch
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
from diffusers.utils import load_image

controlnet = ControlNetModel.from_pretrained("lllyasviel/control_v11f1p_sd15_depth", torch_dtype=torch.float16)
controlnet.to("cuda")
print('Successfully create controlnet model.')    
    
pipe = StableDiffusionControlNetPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", controlnet=controlnet,torch_dtype=torch.float16)
pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
pipe.to("cuda")
pipe.scheduler.set_timesteps(num_inference_steps=20, device=pipe._execution_device)
pipe.safety_checker = lambda images, clip_input: (images, None)
print('Successfully create StableDiffusionControlNetPipeline.')

generator = torch.Generator("cuda").manual_seed(50)

control_image = load_image('https://github.com/user-attachments/assets/fb7f1560-113e-43ca-b21d-875aa57a610b')

output = pipe(
    "A blackswan is swimming in the lake, soft painting, art by hidari and krenz cushart and wenjun lin and akihiko yoshida",
    control_image,
    num_inference_steps=20,
    generator=generator,
)

output[0][0]
```

### System Info

- 🤗 Diffusers version: 0.29.2
- Platform: Linux-5.4.0-105-generic-x86_64-with-glibc2.35
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.12
- PyTorch version (GPU?): 2.2.0a0+81ea7a4 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.4
- Transformers version: 4.42.3
- Accelerate version: 0.33.0
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: Tesla V100-SXM2-32GB-LS, 32768 MiB VRAM
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@yiyixuxu @asomoza @sayakpaul @DN6

**Comment by asomoza** [comment]
Hi, do you mean this part right?

![image](https://github.com/user-attachments/assets/c0750557-1590-4ad8-a656-26accb618829)

It seems like a watermark from the training. If you change the model to another one, for example:

```python
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "Lykon/dreamshaper-8", controlnet=controlnet, torch_dtype=torch.float16, variant="fp16"
)
```

I get this image:

![watermark](https://github.com/user-attachments/assets/f32a1911-93e9-4dad-b090-00b536c7691f)

**Comment by Sonia-kong** [comment]
Yes! It seems that this problem has been solved, thank you very much! 

May I ask how you found these models, because it is difficult to find unofficial SD1.5 models, including SD1.5inpaint models, if you don't know the names. 

If it is convenient, could you list the names of these models, thank you so much. :) @asomoza

**Comment by asomoza** [comment]
You can [search](https://huggingface.co/models?other=diffusers:StableDiffusionPipeline&sort=downloads) for them on the hub with the `StableDiffusionPipeline`, most are for SD 1.5 but there are also some 2.0 and 2.1 ones.

Same for inpainting, you can [search](https://huggingface.co/models?other=diffusers:StableDiffusionInpaintPipeline&sort=downloads) for the `StableDiffusionInpaintPipeline`
