### ISSUE TITLE
IP Adapter is not working with SDXL when using `image_encoder_folder=None` after Kolors update

### ISSUE THREAD

**Issue by detkov** [huggingface/diffusers#9187]
### Describe the bug

When loading IP Adapter into SDXL Text2Image pipeline with `image_encoder_folder=None`, I encounter the following error:
```
clip_image_size = self.image_encoder.config.image_size
AttributeError: 'NoneType' object has no attribute 'config'
```

As I can see from the code changes in the `ip_adapter.py` file, the bug was introduced when implementing Kolors support. 

So I hope that @asomoza can fix that issue having his experience with Kolors.

### Reproduction

```python
import torch
from diffusers import StableDiffusionXLPipeline


pipeline = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
).to("cuda")
pipeline.load_ip_adapter("h94/IP-Adapter-FaceID", subfolder=None, weight_name="ip-adapter-faceid-plusv2_sdxl.bin", image_encoder_folder=None)
```

### Logs

```shell
{
	"name": "AttributeError",
	"message": "'NoneType' object has no attribute 'config'",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 9
      2 from diffusers import StableDiffusionXLPipeline
      5 pipeline = StableDiffusionXLPipeline.from_pretrained(
      6     \"stabilityai/stable-diffusion-xl-base-1.0\",
      7     torch_dtype=torch.float16,
      8 ).to(\"cuda\")
----> 9 pipeline.load_ip_adapter(\"h94/IP-Adapter-FaceID\", subfolder=None, weight_name=\"ip-adapter-faceid-plusv2_sdxl.bin\", image_encoder_folder=None)

File /opt/.cache/virtualenvs/diffusion-exps-R-NqVyK3-py3.10/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py:114, in validate_hf_hub_args.<locals>._inner_fn(*args, **kwargs)
    111 if check_use_auth_token:
    112     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
--> 114 return fn(*args, **kwargs)

File /opt/.cache/virtualenvs/diffusion-exps-R-NqVyK3-py3.10/lib/python3.10/site-packages/diffusers/loaders/ip_adapter.py:225, in IPAdapterMixin.load_ip_adapter(self, pretrained_model_name_or_path_or_dict, subfolder, weight_name, image_encoder_folder, **kwargs)
    223 # create feature extractor if it has not been registered to the pipeline yet
    224 if hasattr(self, \"feature_extractor\") and getattr(self, \"feature_extractor\", None) is None:
--> 225     clip_image_size = self.image_encoder.config.image_size
    226     feature_extractor = CLIPImageProcessor(size=clip_image_size, crop_size=clip_image_size)
    227     self.register_modules(feature_extractor=feature_extractor)

AttributeError: 'NoneType' object has no attribute 'config'"
}
```

### System Info

- 🤗 Diffusers version: 0.30.0
- Platform: Linux-5.15.0-1055-aws-x86_64-with-glibc2.35
- Running on Google Colab?: No
- Python version: 3.10.14
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.5
- Transformers version: 4.40.1
- Accelerate version: 0.31.0
- PEFT version: 0.10.0
- Bitsandbytes version: 0.43.1
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA A10G, 23028 MiB
- Using GPU in script?: YES
- Using distributed or parallel set-up in script?: NO

### Who can help?

@asomoza

**Comment by tolgacangoz** [comment]
Did/Could you examine [the related docs page](https://huggingface.co/docs/diffusers/main/en/using-diffusers/loading_adapters#ip-adapter-face-id-models)?

**Comment by detkov** [comment]
@tolgacangoz this is not the case. Please read https://huggingface.co/docs/diffusers/main/en/using-diffusers/ip_adapter#face-model

**Comment by asomoza** [comment]
@detkov  thanks for reporting, this is a bug, I'll do a PR to fix it.

**Comment by asomoza** [comment]
You're right, I missed that this issue was using the Plus model which requires the image encoder.

**Comment by detkov** [comment]
@fabiorigano [documentation](https://huggingface.co/docs/diffusers/v0.28.2/en/using-diffusers/loading_adapters#ip-adapter-face-id-models) on Plus model indeed says that one has to load image encoder and [documentation](https://huggingface.co/docs/diffusers/v0.30.0/en/using-diffusers/ip_adapter#face-model) on Face model says why do we need that image encoder. 
But this is not a strict requirement, because I can extract CLIP embeddings by myself using a dedicated `CLIPVisionModelWithProjection` model. In the version `0.28.0` I was able to use Face Plus model without having an image encoder inside the SDXL pipeline, but the version `0.30.0` is not allowing me to do this. The reason I do not use an image encoder inside of a pipeline is because of the GPU memory leakages while reusing pipelines and loading-unloading adapters and stuff.

I hope this clarifies the issue.

**Comment by fabiorigano** [comment]
@detkov you are confusing IP-Adapter **FaceID** models and IP-Adapter models

**Comment by detkov** [comment]
@tolgacangoz okay I'll try one more time

When using `ip-adapter-faceid-plusv2_sdxl` as a pipeline adapter, we have to pass face embeddings as `ip_adapter_image_embeds` param into the pipeline call, and additionally, we have to get CLIP embeddings from the face crop image and set it to `pipeline.unet.encoder_hid_proj.image_projection_layers[0].clip_embeds` so that everything works.

To get this CLIP embeddings from the face crop image, we can either use a dedicated `CLIPVisionModelWithProjection` model, or we can pass `CLIPVisionModelWithProjection` into the pipeline init method as `image_encoder` and use `pipeline.prepare_ip_adapter_image_embeds` to get it. Proofs are in these two links that we are already mentioned.

Thus, everything works fine if we do not use `image_encoder` with FaceID Plus IP Adapter and get CLIP embeddings by ourselves. 

And because of I used this method in my own workflow, I got this bug when upgrading to `0.30.0`. So this is a just real-life scenario.

**Comment by fabiorigano** [comment]
@detkov yes, now I understand your workflow, it was not clear to me that you were encoding the CLIP embeddings separately before setting them as `pipeline.unet.encoder_hid_proj.image_projection_layers[0].clip_embeds`

I was just mentioning that the original loading strategy has no issues
nice catch by the way :)
