### ISSUE TITLE
Can pipe.load_lora_weights have scale value? For StableDiffusion

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/diffusers#9190]
As far as I know with Diffusers (0.30.0) latest version we are able to load multiple lora weights  for  StableDiffusion like

```
pipe.load_lora_weights(lora_path1)
pipe.load_lora_weights(lora_path2)
pipe.load_lora_weights(lora_path3)
```

And it works

And then we can use 

`pipe.unload_lora_weights()`

To unload all and return back to original weights

Now what I also want to be able to is 

```
pipe.load_lora_weights(lora_path1,scale=1.5)
pipe.load_lora_weights(lora_path2,scale=2.5)
pipe.load_lora_weights(lora_path3,scale=0.5)
```

Can you add this feature? I really need this for my InstantID based pipeline

I know there is `pipe.fuse_lora(lora_scale=lora_scale_variable)`

However when I use it, I am not able to obtain back original weights without reloading entire pipe since I use more than 1 LoRA

Thank you so much

**Comment by asomoza** [comment]
to change the scale you can just use:

```python
pipe.load_lora_weights("nerijs/pixel-art-xl", weight_name="pixel-art-xl.safetensors", adapter_name="pixel")
pipe.set_adapters(["pixel", "toy"], adapter_weights=[0.5, 1.0])
```

**Comment by FurkanGozukara** [comment]
@asomoza works perfect thank you so much
