### ISSUE TITLE
Separating legacy inpaint pipeline

### ISSUE THREAD

**Issue by juno-hwang** [huggingface/diffusers#920]
The new fine-tuned inpaint pipeline in 0.6.0 release is very good, but its UNet architecture is different from original pipeline.
I think the inpaint pipeline in 0.5.1 release has some advantage such as sharing the same model with txt2img on GPU or inheriting DreamBooth UNet trained on txt2img model.
I actually often use DreamBooth model for inpainting, and that's a pretty big advantage.
So, how about add legacy inpaint pipeline so that people can still use fine-tuned UNet to inpaint?

Also, I suggest strength parameter in the new inpaint pipeline.
It can be implemented by fixing the mask input and diffuse the image channels only, just like img2img pipeline.

**Comment by patrickvonplaten** [comment]
Hey @juno-hwang, 

We still support the old "inpaint" pipeline it's just moved to "Legacy" now: https://github.com/huggingface/diffusers/blob/8be48507a0ea4c9e6771fbfbac1333ee7bb90993/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py#L46

Happy to not deprecate it if you want :-)

**Comment by MartiGrau** [comment]
Hello @patrickvonplaten ,

I suppose you're refering to use the StableDiffusionInpaintPipelineLegacy class with the old weights (CompVis/stable-diffusion-v1-4) because if you want to test the new Inpaint pipeline (0.6.0 release) with the new weights (runwayml/stable-diffusion-inpainting) you get the following error: 

`RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[2, 4, 64, 64] to have 9 channels, but got 4 channels instead`

Meaning that the architecture has changed... So at the end, as @juno-hwang suggested, it would be great to add strength parameter in the new inpaint pipeline with the new weights (runwayml/stable-diffusion-inpainting).

**Comment by patrickvonplaten** [comment]
Hey @MartiGrau,

Currently we don't have enough time to do the PR ourselves, but if you think it makes sense to add a strength parameter, I'm more than happy to review a PR :-)

**Comment by ulmewennberg** [comment]
Hey @patrickvonplaten 👋 

Are there currently any plans to also support Dreambooth training with the new inpainting pipeline? 

https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py
https://huggingface.co/runwayml/stable-diffusion-inpainting

If not, I would be happy to try to implement this if this makes sense.

**Comment by patrickvonplaten** [comment]
Think this could definitely make sense @patil-suraj what do you think? :-)

**Comment by patil-suraj** [comment]
Hey @ulmewennberg that would be awesome, feel free to work on the PR and let us know if you any questions, happy to help :) 

@MartiGrau , the `strength` argument is not really needed here. It's used in the legacy inpainting pipeline as it's based on the image2image example, where we provide an initial  image and the strength argument decides how much noise to add to the image (which also control the number of inference timestep). Which is not the case here, as we don't use the image as an `init_image` the image is converted into latents and directly passed to the model along with the mask.

**Comment by juno-hwang** [comment]
Hey @patil-suraj, as you said `strength` is not necessary, but I think introducing `strength` could allow us to re-paint the given region while keeping some consistency just like legacy inpainting pipeline.
![KakaoTalk_20220710_223619816](https://user-images.githubusercontent.com/52326857/198536401-663066a7-5a85-4ef5-a0e8-9794749b0eef.png)
Also I found an intereting phenomena on img2img pipeline : Theoretically `strength=1` should be equivalent with txt2img because it means the original is fully diffused into perfect Gaussian distribution $x_T$, but somewhy it is different and it keeps the original image's information. The figure above shows the difference between txt2img and img2img with `strength=1` started from plain white image. I guess it's due to improper index shift on scheduler.
Futhermore legacy inpainting pipeline is not good at seamless inpainting with high `strength`. For this reason, it would be very useful for image editing if we have new inpainting pipeline with proper `strength` implementation.

**Comment by patil-suraj** [comment]
>The figure above shows the difference between txt2img and img2img with strength=1 started from plain white image. I guess it's due to improper index shift on scheduler.

I see, thanks for reporting, will take a look at this.

Also, as I said above, we don't use `init_image` in inpainting, as we don't add any noise to the image and mask we pass for in-painting, because of this it's not possible to add `strength` here. 

However, to keep consistency, what I could suggest is:
get the in-painted image from the `pipeline` and then replace the non-masked parts of the image with the original image. That could achieve what you are looking for.

**Comment by ulmewennberg** [comment]
Awesome, @patil-suraj and @patrickvonplaten! Some questions so far on the implementation:

"For inpainting, the UNet has 5 additional input channels (4 for the encoded masked-image and 1 for the mask itself)"

1. Should I add noise to all the 9 input channels? Or perhaps not add it to the mask?
2. The output has only 4 channels. How do I compute the loss between a 4-dimensional noise_pred and a 9-dimensional input?
Should I blend the two fourdimensional tensors by using the mask in some way, or for example just take the first 4 dimensions?

**Comment by thedarkzeno** [comment]
@ulmewennberg I'm also working on it myself, from the inpainting pipeline it seem to only use noise on the image latents

**Comment by thedarkzeno** [comment]
I made a pull request [here](https://github.com/huggingface/diffusers/pull/1091) 
But it's not passing the tests, can someone guide me to fix it?
It's my first contribution, not sure how to do it right
@ulmewennberg @patil-suraj

**Comment by patil-suraj** [comment]
Hey @ulmewennberg !

> Should I add noise to all the 9 input channels? Or perhaps not add it to the mask?
The noise is added to the target image that we want the model to generate. 

> The output has only 4 channels. How do I compute the loss between a 4-dimensional noise_pred and a 9-dimensional input?

We add noise to the target encoded image which has 4 channels, and the loss is simply computed against that noise.

Hope this makes it clear.

**Comment by patil-suraj** [comment]
Thanks for the PR @thedarkzeno ! will take a look.

**Comment by patil-suraj** [comment]
Hey @thedarkzeno and @ulmewennberg , actually not sure if I understand this. What's the goal of doing dream booth with in-painting ? How would it work ?

**Comment by ulmewennberg** [comment]
@patil-suraj the goal is to be able to for example take perform image-inpainting using custom concepts.

**Comment by patil-suraj** [comment]
I see, thanks!

**Comment by ulmewennberg** [comment]
@patil-suraj yep, this is correct

**Comment by Mystfit** [comment]
> Hello @patrickvonplaten ,
> 
> I suppose you're refering to use the StableDiffusionInpaintPipelineLegacy class with the old weights (CompVis/stable-diffusion-v1-4) because if you want to test the new Inpaint pipeline (0.6.0 release) with the new weights (runwayml/stable-diffusion-inpainting) you get the following error:
> 
> `RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[2, 4, 64, 64] to have 9 channels, but got 4 channels instead`
> 
> Meaning that the architecture has changed... So at the end, as @juno-hwang suggested, it would be great to add strength parameter in the new inpaint pipeline with the new weights (runwayml/stable-diffusion-inpainting).

I'm also receiving the same exact same error using the latest 0.7.2 diffusers library, StableDiffusionInpaintPipeline, and the latest runwayml/stable-diffusion-inpainting model. Is there anything I have to change on my end to fix this?

**Comment by patil-suraj** [comment]
@Mystfit 

The `StableDiffusionInpaintPipeline` should work with `runwayml/stable-diffusion-inpainting` model. Could you please post a code snippet so we could take a look ?

**Comment by Mystfit** [comment]
> @Mystfit
> 
> The `StableDiffusionInpaintPipeline` should work with `runwayml/stable-diffusion-inpainting` model. Could you please post a code snippet so we could take a look ?

I think I've tracked down the cause of the error in my case. I'm using the StableDiffusionLongPromptWeightingPipeline (`lpw_stable_diffusion`) custom pipeline to add prompt weighting support and it doesn't seem to play well with the inpainting model or pipeline.

**Comment by opetliak** [comment]
@thedarkzeno what did you use for pretrained_model_name_or_path ("runwayml/stable-diffusion-inpainting"?). 
I'm trying to launch the code, but it looks like it fails with "with_prior_preservation mode"

**Comment by thedarkzeno** [comment]
Hey guys, I didn't tested it extensively, but I've got some interesting results, like this:
![toycat](https://user-images.githubusercontent.com/45200346/202726222-f144b2c1-8bab-4c8a-a9f4-7139b1dccfdf.png)
It isn't perfect yet, but I'll see what I can do to make it better
@opetliak Yes, I used the runwayml/stable-diffusion-inpainting, the prior preservation is broken, but I'll try to fix it

**Comment by patrickvonplaten** [comment]
Very cool!
