### ISSUE TITLE
PAG with guess mode

### ISSUE THREAD

**Issue by christopher5106** [huggingface/diffusers#9218]
### Describe the bug

To me, this [code block](https://github.com/huggingface/diffusers/blob/67f5cce2943e0f32f4e0c6b53177dc3107a7955f/src/diffusers/pipelines/pag/pipeline_pag_controlnet_sd.py#L1195-L1205) seems to ignore the case `guess_mode=False`. Before that, only in the case of `self.do_classifier_free_guidance and not guess_mode` would trigger a concatenate

### Reproduction

Not tested

### System Info

Ubuntu

**Comment by asomoza** [comment]
Hi, sorry for the late response, `guess_mode` didn't work well with PAG, we tested it, so the code you pointed just completely ignores it, `guess_mode` can't be used with PAG.

**Comment by asomoza** [comment]
closing this issue since no more questions were asked.
