### ISSUE TITLE
kohya produced loras -> diffusers supported format

### ISSUE THREAD

**Issue by neuron-party** [huggingface/diffusers#9221]
enables lora loading onto diffuser's FluxPipeline from loras produced by kohya training scripts

**Comment by yiyixuxu** [comment]
closing this now since I think it's already supported https://github.com/huggingface/diffusers/blob/2b443a5d621bd65f5cbf854195aef29cedd24058/src/diffusers/loaders/lora_pipeline.py#L1593
let me know if it is not the case! we will re-open then
