### ISSUE TITLE
cudf-cu12 24.4.1, ibis-framework 8.0.0 requires pyarrow<15.0.0a0,>=14.0.1,pyarrow<16,>=2 and datasets 2.21.0 requires pyarrow>=15.0.0

### ISSUE THREAD

**Issue by SoumyaMB10** [huggingface/diffusers#9223]
### Describe the bug

!pip install accelerate>=0.16.0 torchvision transformers>=4.25.1 datasets>=2.19.1 ftfy tensorboard Jinja2 peft==0.7.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 17.0.0 which is incompatible.
ibis-framework 8.0.0 requires pyarrow<16,>=2, but you have pyarrow 17.0.0 which is incompatible.

to solve above error 
!pip install pyarrow==14.0.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 2.21.0 requires pyarrow>=15.0.0, but you have pyarrow 14.0.1 which is incompatible.

### Reproduction

!pip install  datasets>=2.19.1 

### System Info

🤗 Diffusers version: 0.31.0.dev0
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Running on Google Colab?: Yes
- Python version: 3.10.12
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Huggingface_hub version: 0.23.5
- Transformers version: 4.42.4
- Accelerate version: 0.32.1
- PEFT version: 0.7.0
- Bitsandbytes version: not installed
- Safetensors version: 0.4.4
- xFormers version: not installed
- Accelerator: Tesla T4, 15360 MiB
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @yiyixuxu

**Comment by sayakpaul** [comment]
Please open this issue in the `datasets` repository.

**Comment by Muraam-Abdel-Ghani** [comment]
I am getting the same issue here, any updates?

**Comment by SoumyaMB10** [comment]
> I am getting the same issue here, any updates?

try 
!pip install accelerate>=0.16.0 torchvision transformers>=4.25.1 datasets ftfy tensorboard Jinja2 peft==0.7.0

**Comment by Muraam-Abdel-Ghani** [comment]
> > I am getting the same issue here, any updates?
> 
> try !pip install accelerate>=0.16.0 torchvision transformers>=4.25.1 datasets ftfy tensorboard Jinja2 peft==0.7.0

I don't get the datasets issue now, but rather a different issue appears with the gcsfs packages. Not sure which of the above libraries required fsspec 2024.3.1

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.6.1 requires fsspec==2024.6.1, but you have fsspec 2024.3.1 which is incompatible.
```

Is it safe to just ignore this conflict? gcsfs is a filesystem package for the google cloud storage, so it shouldn't be critical right?

**Comment by SoumyaMB10** [comment]
> fsspec==2024.6.1

upgrade to fsspec==2024.6.1
