### ISSUE TITLE
Is there any way to get diffusers-v0.27.0.dev0?

### ISSUE THREAD

**Issue by D222097** [huggingface/diffusers#9235]
Is there any way to get diffusers-v0.27.0.dev0? I want to compare the difference between diffusers-v0.27.0.dev0  and branches that develop on it in another project, but I didn't find it on the releases or tags page.

**Comment by asomoza** [comment]
Hi, the dev0 version is set in between releases and only when you're using an installation from source. So the `diffusers-v0.27.0.dev0` can be any commit between 0.26 and 0.27.

If you do for example this:

```
git checkout 30132aba308b83187997bd66579c34993e035f6a .
```

and then `diffusers-cli env` you will see that you're in version is `v0.27.0.dev0`, but there's  a lot of commits. It's going to be really hard for you to pinpoint the exact one you need.

**Comment by D222097** [comment]
Thank you for your reply.
