### ISSUE TITLE
Generate black image when using ControlNet-Canny

### ISSUE THREAD

**Issue by xduzhangjiayu** [huggingface/diffusers#9239]
### Describe the bug

Hi,
I test SD1.5 with sd-controlnet-canny, but always generate black image.

The models I used:
ControlNet model: https://huggingface.co/lllyasviel/sd-controlnet-canny
SD1.5 model: https://huggingface.co/runwayml/stable-diffusion-v1-5

Thanks a lot for the help!

### Reproduction

Follow the sd-controlnet-canny official sample code here: https://huggingface.co/lllyasviel/sd-controlnet-canny

### Logs

```shell
Lib\site-packages\diffusers\image_processor.py:111: RuntimeWarning: invalid value encountered in cast images = (images * 255).round().astype("uint8")
```

### System Info

Platform: Windows
Diffusers: 0.30.0
torch:  2.4.0+cu124

**Comment by tolgacangoz** [comment]
Hi @xduzhangjiayu. Could you try without `.enable_xformers_memory_efficient_attention()`; and share the output of this command: `diffusers-cli env`?

**Comment by xduzhangjiayu** [comment]
> Hi @xduzhangjiayu. Could you try without `.enable_xformers_memory_efficient_attention()`; and share the output of this command: `diffusers-cli env`?

Hi,
Thanks for the reply!
After removing the `.enable_xformers_memory_efficient_attention()`, still generate black image
The `diffusers-cli env` output is:
- 🤗 Diffusers version: 0.30.0
- Platform: Windows-10-10.0.22631-SP0
- Running on Google Colab?: No
- Python version: 3.11.9
- PyTorch version (GPU?): 2.4.0+cu124 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.5
- Transformers version: 4.44.0
- Accelerate version: 0.33.0
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.4
- xFormers version: 0.0.27.post2
- Accelerator: NVIDIA GeForce RTX 4090 Laptop GPU, 16376 MiB
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by tolgacangoz** [comment]
You have Cuda 12.4; what happens if you install PyTorch with Cuda 12.1 or 11.8?

**Comment by xduzhangjiayu** [comment]
Hi, 
Still generated black image using PyTorch with Cuda 12.1.

**Comment by tolgacangoz** [comment]
What if you remove `torch_dtype=torch.float16` parts?

**Comment by DidiD1** [comment]
1. you can check the input of unet, make sure there is no 'NAN'

**Comment by DidiD1** [comment]
2. make sure the VAE use the fp16-version

**Comment by tolgacangoz** [comment]
> 1. you can check the input of unet, make sure there is no 'NAN'

Yes, there might be `NaN`s somewhere. You can track and detect this while debugging.

**Comment by xduzhangjiayu** [comment]
The output of controlnet (also the input of unet) - `mid_block_res_sample` is all NaN, seems really strange.

**Comment by tolgacangoz** [comment]
> What if you remove `torch_dtype=torch.float16` parts?

Did you try this?

**Comment by asomoza** [comment]
can you post the full error log? you're having the error in the `image_processor`, I suspect you're having the error when processing the image at the beginning. Also are you using the same image as the example?

It's better if you post the full code you're using, even unless you're just copy & pasting the exact code as the one you're referring.

**Comment by xduzhangjiayu** [comment]
Hi,
Thanks very much for the all the replies and helps !
I have tried removing `torch_dtype=torch.float16`, but it not worked, and the full error log was still:
`Lib\site-packages\diffusers\image_processor.py:111: RuntimeWarning: invalid value encountered in cast images = (images * 255).round().astype("uint8")`

The full code I used is below (the only change was load image at local):
```
import cv2
from PIL import Image
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
import torch
import numpy as np
from diffusers.utils import load_image

image = load_image("bird.png")
image = np.array(image)

low_threshold = 100
high_threshold = 200

image = cv2.Canny(image, low_threshold, high_threshold)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
image = Image.fromarray(image)

controlnet = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-canny", torch_dtype=torch.float16
)

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", controlnet=controlnet, safety_checker=None, torch_dtype=torch.float16
)

pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)

pipe.enable_xformers_memory_efficient_attention()

pipe.enable_model_cpu_offload()

image = pipe("bird", image, num_inference_steps=20).images[0]

image.save('images/bird_canny_out.png')
```

**Comment by asomoza** [comment]
You have a laptop 4090 and pytorch 2.4, you don't need `xformers` or `model_cpu_offload`, removing that from your code, loading the pipeline in the GPU and using the online bird image:

```python
import cv2
import numpy as np
import torch
from PIL import Image

from diffusers import ControlNetModel, StableDiffusionControlNetPipeline, UniPCMultistepScheduler
from diffusers.utils import load_image


image = load_image("https://huggingface.co/lllyasviel/sd-controlnet-canny/resolve/main/images/bird.png")
image = np.array(image)

low_threshold = 100
high_threshold = 200

image = cv2.Canny(image, low_threshold, high_threshold)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
image = Image.fromarray(image)

controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny", torch_dtype=torch.float16)

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", controlnet=controlnet, safety_checker=None, torch_dtype=torch.float16
).to("cuda")

pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)

image = pipe("bird", image, num_inference_steps=20).images[0]

image.save("bird_canny_out.png")
```

I get this:

![bird_canny_out](https://github.com/user-attachments/assets/5de2c2b3-6ed9-4935-b78d-6fd44a6919d1)

So the code works, if you still have a black image with this, the problem lies in your environment which is not something we can help that much too. You probably have an error with the cuda or pytorch installation.

**Comment by xduzhangjiayu** [comment]
Hi, 
I ran successfully after re-creating the environment. Once again, thanks so much for all the help!
I will close this issue.
