### ISSUE TITLE
Convert From XLab lora to diffusers lora script

### ISSUE THREAD

**Issue by chuck-ma** [huggingface/diffusers#9241]
**Is your feature request related to a problem? Please describe.**
I want to use Lora made by XLab. But I can't make it work in Diffusers because there are many differences in Lora structure 
**Describe the solution you'd like.**
Make a script so that we can convert Lora structures easily from XLAB to Diffusers format.

**Comment by chuck-ma** [comment]
OK, let me have a try. Seems quite easy

**Comment by chuck-ma** [comment]
I am facing a problem. The normal shape of lora for xlab, such as double_blocks.{i}.img_attn.qkv.lora_up.weight, is torch.Size([16, 3072]). However, in the format of diffusers, qkv needs to be separated individually. (Referenced from the code of converting flux weights in diffusers) 

```python
lora_up_sample_q, lora_up_sample_k, lora_up_sample_v = torch.chunk(
            original_state_dict.pop(f"double_blocks.{i}.img_attn.qkv.lora_up.weight"), 3, dim=0
        )
       
                converted_state_dict[f"{block_prefix}attn.to_q.lora_A.weight"] = torch.cat([lora_down_sample_q])
        converted_state_dict[f"{block_prefix}attn.to_k.lora_A.weight"] = torch.cat([lora_down_sample_k])
        converted_state_dict[f"{block_prefix}attn.to_v.lora_A.weight"] = torch.cat([lora_down_sample_v])
        ```
        
        This will cause the shape of "f"{block_prefix}attn.to_q.lora_A.weight",  f"{block_prefix}attn.to_k.lora_A.weight", f"{block_prefix}attn.to_v.lora_A.weight" to be torch.Size([6, 3072]), torch.Size([6, 3072]), torch.Size([4, 3072]).

While the normal shape of lora should all be torch.Size([4, 3072])

**Comment by sayakpaul** [comment]
Thanks for your efforts! 

Maybe they are using separate ranks for separate layers? From the shapes, it looks like QK have a rank of 6 while V has a rank of 4. So, we need to take that into account. @BenjaminBossan is my understanding correct?

**Comment by BenjaminBossan** [comment]
Yes, it quite looks like they have different ranks depending on the target layer. However, without seeing how this weight is loaded in code, it's not possible to be sure.

> This will cause the shape of "f"{block_prefix}attn.to_q.lora_A.weight", f"{block_prefix}attn.to_k.lora_A.weight", f"{block_prefix}attn.to_v.lora_A.weight" to be torch.Size([6, 3072]), torch.Size([6, 3072]), torch.Size([4, 3072]).
> 
> While the normal shape of lora should all be torch.Size([4, 3072])

How did you derive this information?

**Comment by chuck-ma** [comment]
First of all, I use a lora that can be normally loaded by diffusers to figure out its shape 

```python
from peft.utils import get_peft_model_state_dict
from accelerate import Accelerator
from diffusers.utils.torch_utils import is_compiled_module



def unwrap_model(model):
    model = accelerator.unwrap_model(model)
    model = model._orig_mod if is_compiled_module(model) else model
    return model

pipe.load_lora_weights("linoyts/yarn_art_Flux_LoRA",weight_name="pytorch_lora_weights.safetensors",
                       adapter_name="default",
                     cross_attention_kwargs={"scale": 0.9})

#transformer = unwrap_model(pipe.transformer)
#transformer = transformer.to(torch.float32)

transformer_lora_layers = get_peft_model_state_dict(pipe.transformer)


```

<img width="818" alt="image" src="https://github.com/user-attachments/assets/25386c2b-2289-4e32-ad9c-067c0fc11c56">

Then, I downloaded the lora model of "VideoAditor/Flux-Lora-Realism", looked at its corresponding key, and attempted to convert it directly through torch.chunk 
```python
ckpt_path = hf_hub_download("VideoAditor/Flux-Lora-Realism", filename="flux_realism_lora.safetensors")

diffusers_realism_state_dict = safetensors.torch.load_file(ckpt_path)

new_diffusers_realism_state_dict = {key.replace("diffusion_model.", ""): value 
                                    for key, value in diffusers_realism_state_dict.items()}

# Recalculate the keys list without the "diffusion_model." prefix
diffusers_real_lora_keys = [key for key in new_diffusers_realism_state_dict.keys() 
                            if  key.startswith("double_blocks.0.")
                            # and  "lora_down" in key
                            # and  "img_attn" in key
                            # and  "qkv" in key
                           ]

diffusers_real_lora_keys
```

 Then i derive this information @BenjaminBossan

**Comment by sayakpaul** [comment]
Well, "linoyts/yarn_art_Flux_LoRA" was trained with a rank of 4 that is why you got that shape but that doesn't warranty that all other LoRAs will have a similar rank or rank pattern.

**Comment by BenjaminBossan** [comment]
Exactly as Sayak says. This information is not sufficient to determine what the rank for each of q/k/v should actually be. If there was some code that actually loads this LoRA successfully, we could check there.

One possibility that I think could also apply is that the LoRA weights are applied to the combined q-k-v tensor and only after that are they chunked. This would be an alternative explanation of why the weight shape is not divisible by 3. Supporting that would probably not be straightforward (unless there is something in diffusers for this already).

**Comment by sayakpaul** [comment]
> One possibility that I think could also apply is that the LoRA weights are applied to the combined q-k-v tensor and only after that are they chunked. This would be an alternative explanation of why the weight shape is not divisible by 3. Supporting that would probably not be straightforward (unless there is something in diffusers for this already).

We have `fuse_qkv_projections()`:

https://github.com/huggingface/diffusers/blob/c977966502b70f4758c83ee5a855b48398042b03/src/diffusers/models/transformers/transformer_flux.py#L345

This fuses the QKV projections. So, a workflow could be to fuse the projections and then add LoRA configs. But this API is quite experimental.

**Comment by chuck-ma** [comment]
Thanks, i will have a try

**Comment by dvregan** [comment]
I'm not sure if this will help, but the scripts XLabs use to train their LoRA are available in XLabs-AI/x-flux repo. In particular in the train_flux_lora_deepspeed.py script they initialise things with:

```python
dit, vae, t5, clip = get_models(name=args.model_name, device=accelerator.device, offload=False, is_schnell=is_schnell)
lora_attn_procs = {}

for name, attn_processor in dit.attn_processors.items():
    lora_attn_procs[name] = DoubleStreamBlockLoraProcessor(dim=3072, rank=args.rank)

dit.set_attn_processor(lora_attn_procs)
```

The `DoubleStreamBlockLoraProcessor` class is defined [here](https://github.com/XLabs-AI/x-flux/blob/4192c215d47b01bba8ae41cf21e8574fa52d33bc/src/flux/modules/layers.py#L177).

**Comment by BenjaminBossan** [comment]
Thanks @dvregan it pretty much looks like they apply LoRA on top of the fused weights. Therefore, it doesn't make sense to try to chunk the LoRA weights. `fuse_qkv_projections` should be the way to go.

> I will try if fuse_qkv_projections works.

Let us know what you find it.

**Comment by chuck-ma** [comment]
https://github.com/huggingface/diffusers/pull/9295

It seems that @sayakpaul  has done the job.

**Comment by sayakpaul** [comment]
Would be great if you could participate in testing and let us know your feedback.

**Comment by chuck-ma** [comment]
My pleasure

**Comment by chuck-ma** [comment]
It works. Thanks a lot. Just use support-kohya-kora and everything is just fine.

Here is the sample:

```python
import torch
from diffusers import FluxTransformer2DModel, FluxPipeline
from transformers import T5EncoderModel, CLIPTextModel
from optimum.quanto import freeze, qfloat8, quantize
from huggingface_hub import hf_hub_download

dtype = torch.bfloat16

ckpt_path = hf_hub_download("Kijai/flux-fp8", filename="flux1-dev-fp8.safetensors")

transformer = FluxTransformer2DModel.from_single_file(ckpt_path, torch_dtype=dtype)
#quantize(transformer, weights=qfloat8)
#freeze(transformer)

pipe = FluxPipeline.from_pretrained(base_model, 
                                              text_encoder_2=None,
                                              transformer=None,
                                              torch_dtype=torch.bfloat16)
pipe.text_encoder_2 = text_encoder_2
pipe.transformer = transformer

pipe.enable_model_cpu_offload()

generator = torch.Generator(device="cpu").manual_seed(0)
prompt = "The portrait of a brazilian person"
image = pipe(prompt, generator=generator).images[0]
image

pipe.load_lora_weights("XLabs-AI/flux-RealismLora")

generator = torch.Generator(device="cpu").manual_seed(0)
prompt = "The portrait of a brazilian person"
image = pipe(prompt, generator=generator).images[0]
image

print("finish load")
```


before lora:
<img width="509" alt="image" src="https://github.com/user-attachments/assets/95e0e87a-5c9d-4d1a-81ba-2b5a8df2d24f">


After lora :

<img width="505" alt="image" src="https://github.com/user-attachments/assets/46420d92-5b18-418b-a225-267818521a3f">

But I have another question: how to load Lora even after I quantize the transformer? It will be useful so that I can switch to different Loras.
