### ISSUE TITLE
pip install --upgrade "diffusers[torch]"

### ISSUE THREAD

**Issue by matheth** [huggingface/diffusers#9248]
### Describe the bug

Installation instructions say
`pip install --upgrade diffusers[torch]`
when it should be
`pip install --upgrade "diffusers[torch]"`

### Reproduction

Installation instructions say
`pip install --upgrade diffusers[torch]`
when it should be
`pip install --upgrade "diffusers[torch]"`

### System Info

Ubuntu 24.04 LTS

**Comment by tolgacangoz** [comment]
Ubuntu's default Bash shell can accept it without quotes.

**Comment by asomoza** [comment]
closing this issue since it appears to be answered without more replies.
