### ISSUE TITLE
Could you make an inpainting model for flux?

### ISSUE THREAD

**Issue by pandayummy** [huggingface/diffusers#9264]
### Model/Pipeline/Scheduler description

The [stable-diffusion-xl-1.0-inpainting-0.1](https://huggingface.co/diffusers/stable-diffusion-xl-1.0-inpainting-0.1) model helps a lot. Could you make a similar inpainting model for flux?

https://huggingface.co/black-forest-labs/FLUX.1-dev

### Open source status

- [ ] The model implementation is available.
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://huggingface.co/diffusers/stable-diffusion-xl-1.0-inpainting-0.1
https://huggingface.co/black-forest-labs/FLUX.1-dev

**Comment by tolgacangoz** [comment]
[In progress](https://github.com/huggingface/diffusers/pull/9135)

**Comment by pandayummy** [comment]
cool!
can't wait to see it!
