### ISSUE TITLE
The different quality between ComfyUI and Diffusers ?

### ISSUE THREAD

**Issue by vuongminh1907** [huggingface/diffusers#9271]
### Discussed in https://github.com/huggingface/diffusers/discussions/9265

<div type='discussions-op-text'>

<sup>Originally posted by **vuongminh1907** August 25, 2024</sup>
I had a problem using InstantID (https://github.com/instantX-research/InstantID), which uses Diffusers as its base. Additionally, I tried ComfyUI (https://github.com/cubiq/ComfyUI_InstantID), and the quality of the images improved better I think.

I discussed this with Cubiq, and he mentioned that there are no differences in how they applied the IP Adapter (https://github.com/cubiq/ComfyUI_InstantID/issues/206).

![image](https://github.com/user-attachments/assets/a0ec4a7a-aad0-4575-8617-cdae8dea5f16)

Can you explain this issue to me? Perhaps it’s related to the Sampler in ComfyUI and Diffusers.</div>

**Comment by asomoza** [comment]
Hi, this is not an issue and shouldn't be here, I posted an answer in the discussion you started.

**Comment by asomoza** [comment]
closing this issue since there's a discussion and it's not really an issue.
