### ISSUE TITLE
Some tests fail on CPU / M1

### ISSUE THREAD

**Issue by natolambert** [huggingface/diffusers#93]
For example, in debugging the test `test_modeling_utils.py::PipelineTesterMixin::test_score_sde_ve_pipeline`, we added a specific value for CPU, but the values on m1 are different slightly again. Here are the values from m1:

```
if model.device.type == "cpu":
    expected_image_sum = 3384805888.0 
    expected_image_mean = 1076.00085 
elif model.device.type == "m1":
    expected_image_sum = 3384805376.0
    expected_image_mean = 1076.0006103515625
else:
    expected_image_sum = 3382849024.0
    expected_image_mean = 1075.3788
```

This happens because some of the models are very large. Will need to add a best practice for tests & contributing.

**Comment by patrickvonplaten** [comment]
Yeah we need to figure this out soon!

**Comment by anton-l** [comment]
After a couple of weeks, testing image slices instead of sum+mean has worked well so far, so let's stick to that :slightly_smiling_face:
