### ISSUE TITLE
for the FluxTransformer2DModel.from_single_file(),

### ISSUE THREAD

**Issue by sxy771** [huggingface/diffusers#9314]
for the FluxTransformer2DModel.from_single_file(),
when i change the path to local, it doesnt work:

OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

_Originally posted by @tomsin9 in https://github.com/huggingface/diffusers/issues/9141#issuecomment-2295983732_

**Comment by kk3dmax** [comment]
I have the same issue... How did you resolved it?

**Comment by yiyixuxu** [comment]
we have fixed it - you need to install the most recent diffusers! `pip install --upgrade diffusers`
