### ISSUE TITLE
RunwayML obsoletion causes issues

### ISSUE THREAD

**Issue by vladmandic** [huggingface/diffusers#9322]
### Describe the bug

RunwayML just removed their entire code from huggingface!  
See note at <https://huggingface.co/runwayml>: *"We are no longer maintaining a HuggingFace organization"*

Which causes pretty big issues since `runwayml/stable-diffusion-v1-5` is referenced as default/fallback in many places in the code.
for example, `loaders/single_file_utils.py` has

```py
DIFFUSERS_DEFAULT_PIPELINE_PATHS = {
    ...
    "inpainting": {"pretrained_model_name_or_path": "runwayml/stable-diffusion-inpainting"},
    "v1": {"pretrained_model_name_or_path": "runwayml/stable-diffusion-v1-5"},
    ...
}
```

### Reproduction

N/A

### Logs

```shell
N/A
```

### System Info

N/A

### Who can help?

@yiyixuxu @sayakpaul @DN6 @asomoza

**Comment by yiyixuxu** [comment]
thanks @vladmandic 
we are looking into this now!

**Comment by yiyixuxu** [comment]
@vladmandic will this work as a temporary resolution?
will update once we decide how to host them

**Comment by vladmandic** [comment]
> @vladmandic will this work as a temporary resolution? will update once we decide how to host them

yes, it should, although its probably better to have it hosted under hf account and not reference a random 3rd party model.

**Comment by yiyixuxu** [comment]
@vladmandic 
should I wait to merge then?
yes we are going to do that, and if this is not urgent for you I'd rather to wait util that decision is made

**Comment by yuanhao-li** [comment]
@yiyixuxu can you also fix this example? 
https://github.com/huggingface/diffusers/tree/main/examples/controlnet

thank you.

**Comment by vladmandic** [comment]
for most of cases, sdnext already uses offline config files, this issue pops up in some border cases - i'd say its important, but can wait a proper solution for a day.

**Comment by yiyixuxu** [comment]
@vladmandic @dave-gray101. 
I merged #https://github.com/huggingface/diffusers/pull/9323 so single file support should be back on now

**Comment by vladmandic** [comment]
thanks - that'[s now on main - what about doing a service pack release? this is serious enough for that.

**Comment by yiyixuxu** [comment]
@vladmandic yes!

**Comment by isidentical** [comment]
I'd really encourage huggingface to either take some decisive action and replace that repo that automatically points to a well maintained fork OR reinstate it completely. this is causing too many transient errors with everything that depends on it.

**Comment by asomoza** [comment]
This was just a quick fix for the moment, also the model we linked as a patch is the most used one for SD 1.5 and I believe if the author, which is a well known person takes it down, the backslash for doing it will be a lot more than the base one, so I don't think we need to worry about that until we provide a better fix soon.

**Comment by yiyixuxu** [comment]
partially resolved but we still need to update everywhere in our doc with https://huggingface.co/stable-diffusion-v1-5

**Comment by sayakpaul** [comment]
I think this was resolved?
