### ISSUE TITLE
Sample latents from VAE to generate close images

### ISSUE THREAD

**Issue by Clement-Lelievre** [huggingface/diffusers#9328]
hi,

I would like to use a VAE (SDXL's VAE in the example below) in order to get close variations of a given image, in the spirit of what was demonstrated in [that paper](https://arxiv.org/abs/1609.04468).
There are examples out there using the MNIST or faces datasets.

I could achieve this with inpainting or maybe img2img, but my point is to get these close images without having to go through reverse diffusion, for performance reasons.

I tried to implement the logic, and found out that diffusers already has nearly all the tools.

**PROBLEM**: It does run without errors and I do get images that are different pixel-wise to the initial image, however the difference across images is invisible to the human eye. I noticed that the std of the latent distribution is extremely low relative to the mean, that might explain why all the produced images look so identical to the input? I might have done a preproc step wrong also? is it due to the high dimensionality of the latents?

I'd be grateful if someone could review my logic and advise.
Here is my code:

```python
import torch
from diffusers import AutoencoderKL
from diffusers.image_processor import VaeImageProcessor
from diffusers.models.autoencoders.vae import DiagonalGaussianDistribution
from PIL import Image
from torchvision import transforms
from torchvision.transforms.functional import pil_to_tensor

# 2: assume I'm interested in getting close variations of an image, using SDXL's VAE
# instead of inferring, eg doing an img2img or inpaint,
# I can use the latent proba distribution inferred by the VAE, sample from it and decode back to pixel space

# instantiate SDXL's VAE
with torch.no_grad():
    # vae:AutoencoderKL = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix")
    vae: AutoencoderKL = AutoencoderKL.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0", subfolder="vae"
    )

    vae.to(dtype=torch.float32)  # otherwise it produces NaNs, even madebyollin's VAE
    vae.to(device="cuda")

    assert vae.device == torch.device("cuda:0")
    assert vae.dtype == torch.float32

    # make image as tensor
    img = Image.open(<image_path_on_disk>)
    img_tensor = pil_to_tensor(img).unsqueeze(0) / 255.0
    img_tensor = img_tensor.to(vae.device)
    img_tensor = img_tensor.to(vae.dtype)

    # get the inferred latent distribution
    latent_dist: DiagonalGaussianDistribution = vae.encode(img_tensor, return_dict=False)[0]
    print(
        f"{latent_dist.mean.shape=} {latent_dist.std.shape=} {latent_dist.mean.mean()=} {latent_dist.std.mean()=}"
    )
    assert not latent_dist.mean.isnan().any()
    assert not latent_dist.std.isnan().any()
    assert latent_dist.deterministic is False

    # generate another latents from it
    sample_1 = (
        latent_dist.sample()
    )  # take the mean of the latent dist and add a fraction of the std
    sample_2 = latent_dist.sample()
    assert not sample_1.isnan().any()
    assert not sample_2.isnan().any()
    assert (sample_1 != sample_2).any(), "samples should be different"

    print(f"{sample_1.shape=}")

    # sample_1 *= (2 ** (len(vae.config.block_out_channels) - 1))

    assert vae.dtype == sample_1.dtype
    assert vae.device == sample_1.device

    img_1: torch.Tensor = vae.decode(sample_1).sample  # , return_dict=False)[0]
    ##vae_scale_factor = 2 ** (len(vae.config.block_out_channels) - 1)
    img_1 = img_1.squeeze(0).cpu().detach()
    assert (
        img_1 != img_tensor.cpu().detach()
    ).any(), "generated image should be different from the input image"
    img_1_pil = transforms.ToPILImage()(img_1)
    # vae_img_processor = VaeImageProcessor(vae_scale_factor=2 ** (len(vae.config.block_out_channels) - 1))
    # img_1_pil = vae_img_processor.postprocess(img_1)[0]
    img_1_pil.save("sample_1.png")
```

Thanks a lot!

cc @sayakpaul @yiyixuxu @patrickvonplaten  @asomoza

**Comment by madebyollin** [comment]
The SD "VAEs" are almost entirely deterministic (KL weight during training is [extremely tiny](https://github.com/CompVis/latent-diffusion/blob/main/configs/autoencoder/autoencoder_kl_8x8x64.yaml#L11)) so I wouldn't expect meaningful variations from the "VAE" sampling process - see [this thread](https://x.com/Birchlabs/status/1721714156275933608).

**Comment by Clement-Lelievre** [comment]
> The SD "VAEs" are almost entirely deterministic (KL weight during training is [extremely tiny](https://github.com/CompVis/latent-diffusion/blob/main/configs/autoencoder/autoencoder_kl_8x8x64.yaml#L11)) so I wouldn't expect meaningful variations from the "VAE" sampling process - see [this thread](https://x.com/Birchlabs/status/1721714156275933608).

thanks for your reply

Actually I had double posted this question here and got [a reply](https://github.com/huggingface/diffusers/discussions/9327#discussioncomment-10509073) from a user who said he did manage to generate meaningful variations just by sampling from SDXL's VAE. However I couldn't reproduce by using the snippet he provided.

I'm curious to know your take on his reply

**Comment by madebyollin** [comment]
@Clement-Lelievre The snippet which that user provided adds additional noise with much higher standard deviation than the encoder asks for, which will definitely give you different images. However, it uses the same noise for both `sample_1` and `sample_2` so the two perturbed samples look the same. If you change the snippet to use different noise for each sample, you should get two different reconstructions. These reconstructions will have some visual artifacts due to the extra noise, but if it's sufficient for your use case then that's definitely cheaper than im2im

**Comment by Clement-Lelievre** [comment]
> @Clement-Lelievre The snippet which that user provided adds additional noise with much higher standard deviation than the encoder asks for, which will definitely give you different images. However, it uses the same noise for both `sample_1` and `sample_2` so the two perturbed samples look the same. If you change the snippet to use different noise for each sample, you should get two different reconstructions. These reconstructions will have some visual artifacts due to the extra noise, but if it's sufficient for your use case then that's definitely cheaper than im2im

I get this, I had previosuly experimented with much higher noise, but I could never get realistic-looking variations. Always artifacts.

**Comment by asomoza** [comment]
This is an interesting topic but it's not an issue, I'll close this one so if there's more updates, please use the [discussion](https://github.com/huggingface/diffusers/discussions/9327) about the same topic.
