### ISSUE TITLE
IPAdapter attention layers run with requires_grad=True for parameters

### ISSUE THREAD

**Issue by darshats** [huggingface/diffusers#9336]
### Describe the bug

When IP adapter is loaded, the IPAdapterAttnProcessor2_0 class is not set with training=False. Didnt see a huge difference in memory if its manually set to false on those processors, but it looks like a miss?
Same for image_projection_layers

### Reproduction

```
pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="sdxl_models", weight_name=["ip-adapter-plus_sdxl_vit-h.safetensors"]*1, use_safetensors=True)
list(pipeline.unet.encoder_hid_proj.image_projection_layers.parameters())
for k, v in pipeline.unet.attn_processors.items():
    if isinstance(v, IPAdapterAttnProcessor2_0) and v.training:
        print(len(list(v.parameters())))
```

### System Info

diffusers 0.28.2 with sdxl

**Comment by tolgacangoz** [comment]
See this decorator on top of the `__call__` method: [`torch.no_grad()`](https://github.com/huggingface/diffusers/blob/d8a16635f47ac455abd61879bcc6be32dfeaa561/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L819).

**Comment by tolgacangoz** [comment]
See this decorator on top of the `__call__` method: [`torch.no_grad()`](https://github.com/huggingface/diffusers/blob/d8a16635f47ac455abd61879bcc6be32dfeaa561/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L819). But if one wants to use `IPAdapterAttnProcessor2_0` as a standalone component, one needs to consider this situation.

**Comment by tolgacangoz** [comment]
See this decorator on top of the `__call__` method at all the pipelines: [`torch.no_grad()`](https://github.com/huggingface/diffusers/blob/d8a16635f47ac455abd61879bcc6be32dfeaa561/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L819). However, if one wants to use `IPAdapterAttnProcessor2_0` or a similar component as a standalone component, one needs to consider this.

**Comment by asomoza** [comment]
I'm closing this issue since it was answered.
