### ISSUE TITLE
SD3 inpatinting

### ISSUE THREAD

**Issue by ucasyjz** [huggingface/diffusers#9339]
I found the StableDiffusion3InpaintPipeline, where can i found the weight of SD3 inpainting

**Comment by peki12345** [comment]
As far as I know, the model used in this pipeline is the original text2image model, not the inpainting model.

**Comment by asomoza** [comment]
right, none of the new transformer models have an inpainting version.

**Comment by JPlin** [comment]
You can try using this SD3-controlnet-inpainting: https://huggingface.co/alimama-creative/SD3-Controlnet-Inpainting

**Comment by asomoza** [comment]
since this was answered and there's no more questions, I'm closing this issue.
