### ISSUE TITLE
flux bitsandbytes  support lora model？

### ISSUE THREAD

**Issue by lonngxiang** [huggingface/diffusers#9383]
flux bitsandbytes  support lora model？

**Comment by asomoza** [comment]
do you mean if you're able to use a lora with a quantized model? As stated [here](https://github.com/huggingface/diffusers/pull/9213#issuecomment-2324710390), not yet, loras will come later.

**Comment by lonngxiang** [comment]
> do you mean if you're able to use a lora with a quantized model? As stated [here](https://github.com/huggingface/diffusers/pull/9213#issuecomment-2324710390), not yet, loras will come later.
Be extremely looking forward to.
