### ISSUE TITLE
use multiple community pipes in a list

### ISSUE THREAD

**Issue by CrazyBoyM** [huggingface/diffusers#939]
**Is your feature request related to a problem? Please describe.**

I find some very great community pipes, such as CLIP Guided Stable Diffusion and Long Prompt Weighting Stable Diffusion.
But I don't know how to use them both.

**Describe the solution you'd like**
some code likes:
```python
pipe = DiffusionPipeline.from_pretrained(
    'hakurei/waifu-diffusion',
    custom_pipelines=["lpw_stable_diffusion", "clip_guided_stable_diffusion"],
    revision="fp16",
    torch_dtype=torch.float16
)
pipe=pipe.to("cuda")
```
simpely change the
```
custom_pipeline="lpw_stable_diffusion"
```
to
```
custom_pipelines=["lpw_stable_diffusion", "clip_guided_stable_diffusion"]
```

**Describe alternatives you've considered**
a list for custom pipelines

**Comment by patrickvonplaten** [comment]
Hey @CrazyBoyM,

Note that community pipelines are not always compatible with each other so I'm not sure it's possible to load them into one class. How did you image the design of a "multi-community-pipeline" to look like? :-)

**Comment by CrazyBoyM** [comment]
> Hey @CrazyBoyM,
> 
> Note that community pipelines are not always compatible with each other so I'm not sure it's possible to load them into one class. How did you image the design of a "multi-community-pipeline" to look like? :-)

sorry for that i don't have a good idea for it's compatibility now

**Comment by adhikjoshi** [comment]
> Hey @CrazyBoyM,
> 
> Note that community pipelines are not always compatible with each other so I'm not sure it's possible to load them into one class. How did you image the design of a "multi-community-pipeline" to look like? :-) 

We can pass array of maybe downloaded models, which loads.

If i want to load 3 custom trained models, it's not possible, as far i know (tell me if i can)

If we can do it easily, it would be awesome.

**Comment by patrickvonplaten** [comment]
Also related: https://github.com/huggingface/diffusers/issues/1046
