### ISSUE TITLE
SGMUniform scheduler for Hyper loras needs support!

### ISSUE THREAD

**Issue by rollingcookies** [huggingface/diffusers#9397]
**Is your feature request related to a problem? Please describe.**
Your library is used in a great product like Invoke! And SGMUniform scheduler is needed to support Hyper loras! Please add support for this scheduler in diffusers library!

**Describe the solution you'd like.**
Add scheduler - SGMUniform 

**Describe alternatives you've considered.**
So far, I haven't found an alternative solution.

**Comment by rollingcookies** [comment]
Hi! Unfortunately my version of Forge does not have a TCD scheduler, I can only compare it to Euler. 

Euler
![00042-t2i_3823554701 Euler](https://github.com/user-attachments/assets/d00b5522-6643-45f9-9685-ee53ed5fbdb7)

Euler SGMUniform
![00039-t2i_3823554701 Euler SGMUniform](https://github.com/user-attachments/assets/25cabd9b-2c8f-49c6-ae9d-3c9e3959ef43)

Euler
![00144-t2i_3838990233 Euler](https://github.com/user-attachments/assets/6ab149db-b5be-4256-af3b-16dd5781f1a3)

Euler SGMUniform
![00142-t2i_3838990233 Euler SGMUniform](https://github.com/user-attachments/assets/db814c88-66b4-4d08-b98c-9c647bb2fccd)

Euler
![00066-t2i_2865392006 Euler](https://github.com/user-attachments/assets/fdee3d48-95bf-43d5-a3ed-12d071782694)

Euler SGMUniform
![00068-t2i_2865392006 EulerSGMUniform](https://github.com/user-attachments/assets/81d8f978-2481-4d4e-933f-fa35528f1d33)

Euler
![00076-t2i_2865392006 Euler](https://github.com/user-attachments/assets/ba0073c3-033a-49c0-9901-da55707bf6f8)

Euler SGMUniform
![00074-t2i_2865392006 Euler SGMUniform](https://github.com/user-attachments/assets/f90632a7-98b9-4a63-aa8b-7a2cc6cd7107)

Euler
![00096-t2i_2210004670 Euler](https://github.com/user-attachments/assets/a9e9ebbe-e5ce-49a4-be72-4587441e936a)

Euler SGMUniform
![00094-t2i_2210004670 Euler SGMUniform](https://github.com/user-attachments/assets/882a4657-1f5f-4c94-b04b-2a641271ae0a)

Euler
![00078-t2i_2865392006 Euler](https://github.com/user-attachments/assets/3596a461-1888-44a5-92af-b9cbde4bb78c)

Euler SGMUniform
![00080-t2i_2865392006 EulerSGMUniform](https://github.com/user-attachments/assets/233a142f-aa35-4596-aa20-91e497b02b62)

**Comment by asomoza** [comment]
Thank you for the examples, sadly we can't compare it to the best one we have for this right now, but It does make the image cleaner, I can see the difference. I read some people saying that it's the recommended scheduler for lighting and hyper but in the official repo they recommend this:

[Lighting](https://huggingface.co/ByteDance/SDXL-Lightning)

```
# Ensure sampler uses "trailing" timesteps and "sample" prediction type.
pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config, timestep_spacing="trailing", prediction_type="sample")
```

[Hyper-SD](https://huggingface.co/ByteDance/Hyper-SD)
```
# Use TCD scheduler to achieve better image quality
pipe.scheduler = TCDScheduler.from_config(pipe.scheduler.config)
```

I don't know the implementation of `SGMUniform` but if we don't have it, it could make sense to add it, I can't add it or make the decision about it though, @yiyixuxu WDYT?

**Comment by yiyixuxu** [comment]
ok we can open an issue to see if anyone in the community wants to contribute first? @asomoza

**Comment by rollingcookies** [comment]
@asomoza @yiyixuxu Thank you for your efforts, hopefully it will come to realization. I tried to implement also comparison on the same Prompts and Seeds in Comfi, unfortunately for TSD Scheduler there is no possibility to use A1111 emulation, because it is implemented via SamplerCustom node. But for Euler SGMUniform it was possible to use KSampler (inspire) node which has A1111 support. So that also influenced the result. 

My verdict: the best and cleanest result is Euler SGMUniform in Forge, second place is Euler SGMUniform from Comfi with A1111 emulation, and the last place is TCD (Comfi, node TCD ModelSmpling Discrete).


Euler SGMUniform
![Euler_SGMUniform_00025_](https://github.com/user-attachments/assets/eb472c20-57da-45b9-9df9-04bd724f0b18)

TCD
![TCD_00023_](https://github.com/user-attachments/assets/adc28648-0654-46fc-af1e-925a96737a05)

Euler SGMUniform
![Euler_SGMUniform_00024_](https://github.com/user-attachments/assets/97ce8de6-441f-4475-8c69-777b89185e9e)

TCD
![TCD_00022_](https://github.com/user-attachments/assets/a4a4e0be-a987-4101-8d72-43f5666cbb63)

Euler SGMUniform
![Euler_SGMUniform_00023_](https://github.com/user-attachments/assets/025e8c17-a6a8-4a2e-a325-96f4e176d39d)

TCD
![TCD_00021_](https://github.com/user-attachments/assets/65ca3d4d-fe1e-4d14-972f-f6aa44d3408c)

Euler SGMUniform
![Euler_SGMUniform_00022_](https://github.com/user-attachments/assets/741596e5-c9c2-4ace-bf75-e740851cf06c)

TCD
![Euler_SGMUniform_00021_](https://github.com/user-attachments/assets/41322770-5698-463c-aa0a-6380ca11268d)

Euler SGMUniform
![Euler_SGMUniform_00020_](https://github.com/user-attachments/assets/483ad5e6-36b0-482f-b99c-0cb162661f1d)

TCD
![TCD_00019_](https://github.com/user-attachments/assets/e5e8b8a0-6e42-406d-ab59-d3ff6005ac5f)

Euler SGMUniform
![Euler_SGMUniform_00019_](https://github.com/user-attachments/assets/c1ea0856-b6ee-40c4-b8df-a8c07622b8b0)

TCD
![TCD_00018_](https://github.com/user-attachments/assets/83ba1e0d-560e-4543-bd35-d7c769c33677)

**Comment by asomoza** [comment]
closing this since we have a diffusers equivalent of this and was added to the docs with this [PR](https://github.com/huggingface/diffusers/pull/9504).
