### ISSUE TITLE
CombinedTimestepGuidanceTextProjEmbeddings.forward() missing 1 required positional argument: 'pooled_projection' 

### ISSUE THREAD

**Issue by christopher5106** [huggingface/diffusers#9398]
### Describe the bug

There is a bug when using controlnet_union with flux schnell.

The reason is because controlnet union uses guidance_embeds set to True while Schnell doesn't.

### Reproduction

The code in the pipeline should be written that way I believe:

```python 

                # handle guidance
                if self.controlnet.config.guidance_embeds:
                    guidance = torch.tensor([guidance_scale], device=device)
                    guidance = guidance.expand(latents.shape[0])
                else:
                    guidance = None

                # controlnet
                controlnet_block_samples, controlnet_single_block_samples = self.controlnet(
                    hidden_states=latents,
                    controlnet_cond=control_image,
                    controlnet_mode=control_mode,
                    conditioning_scale=controlnet_conditioning_scale,
                    timestep=timestep / 1000,
                    guidance=guidance,
                    pooled_projections=pooled_prompt_embeds,
                    encoder_hidden_states=prompt_embeds,
                    txt_ids=text_ids,
                    img_ids=latent_image_ids,
                    joint_attention_kwargs=self.joint_attention_kwargs,
                    return_dict=False,
                )

                if self.transformer.config.guidance_embeds:
                    guidance = torch.tensor([guidance_scale], device=device)
                    guidance = guidance.expand(latents.shape[0])
                else:
                    guidance = None

                noise_pred = self.transformer(
                    hidden_states=latents,
                    timestep=timestep / 1000,
                    guidance=guidance,
                    pooled_projections=pooled_prompt_embeds,
                    encoder_hidden_states=prompt_embeds,
                    controlnet_block_samples=controlnet_block_samples,
                    controlnet_single_block_samples=controlnet_single_block_samples,
                    txt_ids=text_ids,
                    img_ids=latent_image_ids,
                    joint_attention_kwargs=self.joint_attention_kwargs,
                    return_dict=False,
                )[0]

```

instead of [this](https://github.com/huggingface/diffusers/blob/f28a8c257afe8eeb16b4deb973c6b1829f6aea59/src/diffusers/pipelines/flux/pipeline_flux_controlnet.py#L844)

One is conditioned on self.controlnet.config.guidance_embeds while flux is conditioned on self.transformer.config.guidance_embeds. I didn't test it.

### System Info

Ubuntu

**Comment by sayakpaul** [comment]
But I don't think reasonable to add the schnell support if the underlying ControlNet wasn't trained on Schnell.

**Comment by christopher5106** [comment]
Arrrh if we start to only follow ML guidelines about training distributions, then probably 99% of our users are wrong about mixing things that have never been guaranteed to work... mixing a controlnet with an ip adapter is 100% safe ? that means did we train them together ? we now in a world of "out of training distribution" all the time, if it works.

It's not a big deal to read the conf of the controlnet to infer the controls, and to read the conf of the model to make the full inference.

**Comment by christopher5106** [comment]
I can try to deliver you an empirical study if it works, that might be a good starting point.

**Comment by christopher5106** [comment]
I run the flux-schnell with controlnet union thanks to a hack to have the pipeline work (loading the controlnet without guidance embed, which is not the best), otherwise following this [example](https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union) :
prompt: 'A bohemian-style female travel blogger with sun-kissed skin and messy beach waves.'
guidance: 3
controlnet strength: 0.5
canny control image: 
![image](https://github.com/user-attachments/assets/b43293f5-c919-46de-a65b-fbf68d72efa7)
results: 
![res-0](https://github.com/user-attachments/assets/5c4818ee-e05c-44c6-ba74-0be4c8f8c6da)
![res-1](https://github.com/user-attachments/assets/b470bc72-538a-4c31-a9e3-38d66d3bfa93)
![res-2](https://github.com/user-attachments/assets/4f2f1687-06f2-478a-bc08-141ab8a6a637)
![res-3](https://github.com/user-attachments/assets/2e4bec1a-8a7b-4bdd-9168-85de0b2e42b4)

**Comment by yiyixuxu** [comment]
thanks @christopher5106 
looking into this!

**Comment by arnold408** [comment]
> I run the flux-schnell with controlnet union thanks to a hack to have the pipeline work (loading the controlnet without guidance embed, which is not its default config, should not be like that), otherwise following this [example](https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union) : prompt: 'A bohemian-style female travel blogger with sun-kissed skin and messy beach waves.' guidance: 3 controlnet strength: 0.5 canny control image: ![image](https://private-user-images.githubusercontent.com/6875375/367332841-b43293f5-c919-46de-a65b-fbf68d72efa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzI4MjQsIm5iZiI6MTcyNjY3MjUyNCwicGF0aCI6Ii82ODc1Mzc1LzM2NzMzMjg0MS1iNDMyOTNmNS1jOTE5LTQ2ZGUtYTY1Yi1mYmY2OGQ3MmVmYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMTUxNTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWEyNWY0YjMyYmI3ZTFmYzFkOGVhMGViYWQ5ODkwOGQwNGVlMDZiZjg0ZjZiNTU4ZDAwOTNhNzY2NjA5MmY0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1twVM2KAylGwMIqT9rMq-f3kveF0pvMcjG9s-I_2jP0) results: ![res-0](https://private-user-images.githubusercontent.com/6875375/367332940-5c4818ee-e05c-44c6-ba74-0be4c8f8c6da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzI4MjQsIm5iZiI6MTcyNjY3MjUyNCwicGF0aCI6Ii82ODc1Mzc1LzM2NzMzMjk0MC01YzQ4MThlZS1lMDVjLTQ0YzYtYmE3NC0wYmU0YzhmOGM2ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMTUxNTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGJkNzMxN2U1Y2U0MDgzM2Y5MmMwNTA0N2MwMWU3MzYzZGFkZDZkMGM1ZmY3NTVkZjA0OGE1MGM0NDIzMDJiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PPgMJMrlJM2vS3UHwpHhX2KQYmP752mO9lBNA8DOSwo) ![res-1](https://private-user-images.githubusercontent.com/6875375/367332947-b470bc72-538a-4c31-a9e3-38d66d3bfa93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzI4MjQsIm5iZiI6MTcyNjY3MjUyNCwicGF0aCI6Ii82ODc1Mzc1LzM2NzMzMjk0Ny1iNDcwYmM3Mi01MzhhLTRjMzEtYTllMy0zOGQ2NmQzYmZhOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMTUxNTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRmYmMwMGJhY2IwOWJlMDIzMWU4ZjNmOTc2YjY3ZGRmNDMzMGNhZDA0ZDcxYjQzOTY4Zjc5YzYwMjc1OWIzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x2S7mRZA1wATJPcNwGUJYSUItTZ9vNfjLRLZpDVCPYc) ![res-2](https://private-user-images.githubusercontent.com/6875375/367332974-4f2f1687-06f2-478a-bc08-141ab8a6a637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzI4MjQsIm5iZiI6MTcyNjY3MjUyNCwicGF0aCI6Ii82ODc1Mzc1LzM2NzMzMjk3NC00ZjJmMTY4Ny0wNmYyLTQ3OGEtYmMwOC0xNDFhYjhhNmE2MzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMTUxNTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmI2YTliYjMwYTljMzdmNTc4ODExYzNiOGI3ZmNmNGRiZDgxYjg2ODc4YTk2NTUyZDQxZTRjZmEzYjdlZWU3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yfrF3eFelz6enGiQz-N8x31bl9N2gXr7W57-Gp_JINM) ![res-3](https://private-user-images.githubusercontent.com/6875375/367332990-2e4bec1a-8a7b-4bdd-9168-85de0b2e42b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzI4MjQsIm5iZiI6MTcyNjY3MjUyNCwicGF0aCI6Ii82ODc1Mzc1LzM2NzMzMjk5MC0yZTRiZWMxYS04YTdiLTRiZGQtOTE2OC04NWRlMGIyZTQyYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMTUxNTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU1MmM2NDg1ODJjNGEyZmFmZTg2ZGQzMjgwNzI4YzU2MTkxYjIzODMzMWM2MTI4MWE0MWVlZDI5NTMxNTA5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kEuNWbG8FKEXpVVuth_vmv6amO3toXXvXkANhMqhKDY)

Hi,
Please provide the code you have used to make flux schnell work with controlnet.
Thanks a lot.

**Comment by culda** [comment]
Just adding onto this, I'm getting this error on flux dev, not just schnell.

**Comment by christopher5106** [comment]
Check the value of `guidance_embeds` in your flux dev transformer config, and in the controlnet config. If they are not the same, then it's due to the same error.
