### ISSUE TITLE
[Flux ControlNet] Add img2img and inpaint pipelines

### ISSUE THREAD

**Issue by asomoza** [huggingface/diffusers#9402]
We recently added img2img and inpainting pipelines for Flux thanks to @Gothos contribution. 

We also have controlnet support for Flux thanks to @wangqixun.

It'd be nice to have controlnet versions of these pipelines since there's been requests to have them.

Basically, we need to create two new pipelines that add the controlnet support from this [pipeline ](https://github.com/huggingface/diffusers/blob/f28a8c257afe8eeb16b4deb973c6b1829f6aea59/src/diffusers/pipelines/flux/pipeline_flux_controlnet.py) to the corresponding pipellines.

- [ ] [Image to image](https://github.com/huggingface/diffusers/blob/f28a8c257afe8eeb16b4deb973c6b1829f6aea59/src/diffusers/pipelines/flux/pipeline_flux_img2img.py)
- [ ] [Inpaint](https://github.com/huggingface/diffusers/blob/f28a8c257afe8eeb16b4deb973c6b1829f6aea59/src/diffusers/pipelines/flux/pipeline_flux_inpaint.py)

Related issue: #9158 

Let me know if someone is interested in contributing this.

**Comment by ighoshsubho** [comment]
Hi @asomoza
I would like to work on this 🙏

**Comment by asomoza** [comment]
thanks a lot @ighoshsubho

**Comment by peki12345** [comment]
Hi, I found that Flux+ControlNet works very well, but it always takes up 40GB+ of my GPU memory. Is there a way for me to run it on a 24GB 3090 or 4090 GPU?

**Comment by asomoza** [comment]
Hi, you'll need quantization support or maybe something like control lora, we don't have neither at the moment.

ccing @sayakpaul for awareness

**Comment by basit-MT** [comment]
Hi, is there some documentation on training flux+ControlNet?

**Comment by basit-MT** [comment]
Hi, is there some documentation on training flux+ControlNet?

**Comment by xin-ran-w** [comment]
I have a question of the flux in-painting pipe in [pipeline_flux_inpaint.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/flux/pipeline_flux_inpaint.py). 
It seems that the masked_image_latents variable is not used in the de-noising loop to predicate noise. 
Below is the part of the code for preparing mask image latents and denoise loop
```python
    mask, masked_image_latents = self.prepare_mask_latents(
            mask_condition,
            masked_image,
            batch_size,
            num_channels_latents,
            num_images_per_prompt,
            height,
            width,
            prompt_embeds.dtype,
            device,
            generator,
        )

        num_warmup_steps = max(len(timesteps) - num_inference_steps * self.scheduler.order, 0)
        self._num_timesteps = len(timesteps)

        # handle guidance
        if self.transformer.config.guidance_embeds:
            guidance = torch.full([1], guidance_scale, device=device, dtype=torch.float32)
            guidance = guidance.expand(latents.shape[0])
        else:
            guidance = None

        # 6. Denoising loop
        with self.progress_bar(total=num_inference_steps) as progress_bar:
            for i, t in enumerate(timesteps):
                if self.interrupt:
                    continue

                # broadcast to batch dimension in a way that's compatible with ONNX/Core ML
                timestep = t.expand(latents.shape[0]).to(latents.dtype)
                noise_pred = self.transformer(
                    hidden_states=latents,
                    timestep=timestep / 1000,
                    guidance=guidance,
                    pooled_projections=pooled_prompt_embeds,
                    encoder_hidden_states=prompt_embeds,
                    txt_ids=text_ids,
                    img_ids=latent_image_ids,
                    joint_attention_kwargs=self.joint_attention_kwargs,
                    return_dict=False,
                )[0]

                # compute the previous noisy sample x_t -> x_t-1
                latents_dtype = latents.dtype
                latents = self.scheduler.step(noise_pred, t, latents, return_dict=False)[0]

                # for 64 channel transformer only.
                init_latents_proper = image_latents
                init_mask = mask
```

**Comment by shridharathi** [comment]
Hi, trying to apply lora to FluxImg2ImgPipeline but keep receiving the following error: RuntimeError: cuDNN Frontend error: [cudnn_frontend] Error: No execution plans support the graph.

**Comment by asomoza** [comment]
Hi, @shridharathi there's an ongoing issue with your problem just search for the error you're getting.  You probably need to downgrade your pytorch version.

**Comment by shridharathi** [comment]
@asomoza I tried downgrading torch to 2.4, but still facing the same error

**Comment by asomoza** [comment]
oh ok, just to be sure, this error doesn't happen if you use other pipelines?

**Comment by shridharathi** [comment]
yes, it works with FluxPipeline if i apply the lora on text to image

**Comment by asomoza** [comment]
mhm so you're doing more than just running a test with the pipeline. If you want help, it would be better if you post a new issue about this with a reproducible snippet of the code and your environment, that way we can try to pinpoint the error.
