### ISSUE TITLE
Potential misalignment for flux and sd3 in bf16

### ISSUE THREAD

**Issue by zhuole1025** [huggingface/diffusers#9405]
Hi!
I noticed that in the bf16 mode, the timestep will be rounded to other values (e.g., 750 -> 752), then divided by 1000. Therefore, I think it will be better to divide 1000 first, which can avoid the precision error in bf16.
https://github.com/huggingface/diffusers/blob/f28a8c257afe8eeb16b4deb973c6b1829f6aea59/src/diffusers/pipelines/flux/pipeline_flux.py#L717

**Comment by asomoza** [comment]
cc: @yiyixuxu

**Comment by yiyixuxu** [comment]
ohh thanks! 
@asomoza, if you have time, maybe you can run a few tests to see if it improves in image quality

**Comment by zhuole1025** [comment]
Yeah, I think this is only a minor mistake

**Comment by asomoza** [comment]
So I did some tests, not that many though, and it's really hard to tell the difference, if you ask me, I prefer the "fixed" version but I wouldn't have noticed the difference if someone else posted the images.

It does change the images so people will lose the reproducibility of the images if we do this.

In these images, for the first one I like the fixed version but for the second image (dragon) I prefer the before version. So it also comes to the seed, the result and eye of the person looking at them.

|before|fixed|
|---|---|
|![20240912140113_3507918429_normal](https://github.com/user-attachments/assets/5928d298-30b9-4e3a-866f-462c7da4b0c6)|![20240912135857_3507918429_fix](https://github.com/user-attachments/assets/d4a76bef-ea00-4f1f-93bd-f3ff337ba623)|
|![20240912141806_3163432929_normal](https://github.com/user-attachments/assets/a155c427-738b-44bc-adaa-890095c34c93)|![20240912150349_3163432929_fixed](https://github.com/user-attachments/assets/ce762eb1-cbca-4a56-887c-1e19d1b35112)|

**Comment by zhuole1025** [comment]
Thanks for the demos! There indeed are only minor differences.
