### ISSUE TITLE
Cannot import StableDiffusion3ControlNetInpaintingPipeline

### ISSUE THREAD

**Issue by Sotatek-DuyHoang** [huggingface/diffusers#9410]
### Describe the bug

Traceback (most recent call last):

    from diffusers.pipelines import StableDiffusion3ControlNetInpaintingPipeline
ImportError: cannot import name 'StableDiffusion3ControlNetInpaintingPipeline' from 'diffusers.pipelines' (miniconda3/envs/sd3/lib/python3.11/site-packages/diffusers/pipelines/__init__.py)

### Reproduction

from diffusers.utils import load_image, check_min_version
from diffusers.pipelines import StableDiffusion3ControlNetInpaintingPipeline

### System Info

- 🤗 Diffusers version: 0.31.0.dev0
- Platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.35
- Running on Google Colab?: No
- Python version: 3.11.0
- PyTorch version (GPU?): 2.4.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.6
- Transformers version: not installed
- Accelerate version: not installed
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.5
- xFormers version: not installed
- Accelerator: NVIDIA GeForce RTX 4090, 24564 MiB
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

I cannot import StableDiffusion3ControlNetInpaintingPipeline

**Comment by asomoza** [comment]
Hi, the import works correctly if you have the current updated main. You didn't post the error log, what's the message saying? This is probably something related to your environment, so best way to fix it is to just recreate it with the current updated main branch.

**Comment by BangDoon** [comment]
Try installing these

`pip install transformers sentencepiece protobuf accelerate`

**Comment by smartechru** [comment]
@DuySota you need to install from source and run to use **StableDiffusion3ControlNetInpaintingPipeline** since the v0.30.3 doesn't include this.

```
pip uninstall diffusers
pip install git+https://github.com/huggingface/diffusers
```

This one worked for me.

**Comment by asomoza** [comment]
closing this since no more information or questions were provided, assuming it was resolved.

**Comment by sahilshukla3003** [comment]
> @DuySota you need to install from source and run to use **StableDiffusion3ControlNetInpaintingPipeline** since the v0.30.3 doesn't include this.
> 
> ```
> pip uninstall diffusers
> pip install git+https://github.com/huggingface/diffusers
> ```
> 
> This one worked for me.

still it is not working , anyone got the solution..?

**Comment by JoeGaffney** [comment]
actually this does not seem to work and also the implementation looks in complete
