### ISSUE TITLE
The transformer model saved after FLUX+Hyper-SD lora cannot be loaded

### ISSUE THREAD

**Issue by peki12345** [huggingface/diffusers#9420]
### Describe the bug

The transformer model saved after FLUX+Hyper-SD lora cannot be loaded. I don't want to merge lora every time, it's time-consuming. I wanted to save the model once and load it, but I failed.

### Reproduction

> import torch
from diffusers import FluxPipeline
from huggingface_hub 
import hf_hub_download
base_model_id = "black-forest-labs/FLUX.1-dev"
repo_name = "ByteDance/Hyper-SD"
ckpt_name = "Hyper-FLUX.1-dev-8steps-lora.safetensors"
pipe = FluxPipeline.from_pretrained(base_model_id, token="xxx")
pipe.load_lora_weights(hf_hub_download(repo_name, ckpt_name))
pipe.fuse_lora(lora_scale=0.125)
model = pipe.transformer
model.save_pretrained('./flux_8step')

I can save the model through this code, but I found that the saved size is different from the original transformer. And I failed while loading.

> transformer = FluxTransformer2DModel.from_pretrained("./flux_8step", torch_dtype=torch.float16)

I got the error: AttributeError: 'Linear' object has no attribute 'base_layer'

### System Info

Diffusers main

**Comment by asomoza** [comment]
cc: @sayakpaul

**Comment by sayakpaul** [comment]
Check https://huggingface.co/docs/diffusers/main/en/using-diffusers/merge_loras

You need to call `unload_lora_weights()` after `fuse_lora()`.

**Comment by peki12345** [comment]
> Check https://huggingface.co/docs/diffusers/main/en/using-diffusers/merge_loras
> 
> You need to call `unload_lora_weights()` after `fuse_lora()`.

Thank you, it solved my problem!
