### ISSUE TITLE
Unable to Access 'runwayml/stable-diffusion-inpainting' Model

### ISSUE THREAD

**Issue by HaoyueBaiZJU** [huggingface/diffusers#9421]
### Describe the bug

I am unable to access the "runwayml/stable-diffusion-inpainting" model as it shows a 404 error. Could you please share a copy of this pretrained model or provide an alternative link? Thank you!

### Reproduction

https://huggingface.co/runwayml/stable-diffusion-inpainting

### System Info

- diffusers version: 0.15.0
- Platform: Linux-5.15.0-105-generic-x86_64-with-glibc2.35
- Python version: 3.12.3
- PyTorch version (GPU?): 2.3.1 (True)
- Huggingface_hub version: 0.23.4
- Transformers version: 4.44.2
- Accelerate version: 0.32.1
- xFormers version: not installed

**Comment by asomoza** [comment]
Hi, runway stopped maintaining a HF organization so all their models aren't accessible anymore.

You can [search for alternatives with the inpainting pipeline](https://huggingface.co/models?other=diffusers%3AStableDiffusionInpaintPipeline), you can choose whatever you want, there's a lot of backups of the original model too.

**Comment by suzukimain** [comment]
Hi, @HaoyueBaiZJU.  You can use `stable-diffusion-v1-5/stable-diffusion-inpainting`
The documentation has also been corrected to this in #9428

**Comment by asomoza** [comment]
we can assume this was resolved so I'm closing it, if you encounter another error please open another issue.
