### ISSUE TITLE
Frist parameter in downsamplers should be 'out_channels', instead of 'in_channels'

### ISSUE THREAD

**Issue by chenguolin** [huggingface/diffusers#943]
https://github.com/huggingface/diffusers/blob/9bca40296e3f00fb26597a0f4cfe2fdfd2ad2fd2/src/diffusers/models/unet_blocks.py#L619

All the frist parameters of Downsample2D-like classes in `self.downsamplers` are `in_channels`.

However,  the inputs of these `self.downsamplers` are the outputs of Resnets, whose number of channels should be `out_channels`.

Though these wrong parameters do not affect the results, since `in_channels` is assigned as `out_channels` in Resnet iteration: https://github.com/huggingface/diffusers/blob/9bca40296e3f00fb26597a0f4cfe2fdfd2ad2fd2/src/diffusers/models/unet_blocks.py#L597, they may cause confusion for code reading.

By the way, the first parameters of Upsample2D-like classes are `out_channels`, which is correct I think:
https://github.com/huggingface/diffusers/blob/9bca40296e3f00fb26597a0f4cfe2fdfd2ad2fd2/src/diffusers/models/unet_blocks.py#L1200

**Comment by patrickvonplaten** [comment]
Hey @chenguolin, 

I agree that the naming is not ideal here, I've never managed to find time to clean up the naming. Do you have good ideas for how we should change the naming? Would you like to open a PR maybe? :-)

**Comment by chenguolin** [comment]
OK. I'll pull a request to clean up the naming in these classes later.
