### ISSUE TITLE
CogVideoX Image2Video model not found

### ISSUE THREAD

**Issue by rolux** [huggingface/diffusers#9454]
### Describe the bug

The updated documentation at [https://huggingface.co/docs/diffusers/en/api/pipelines/cogvideox](https://huggingface.co/docs/diffusers/en/api/pipelines/cogvideox) says:

`pipe = CogVideoXImageToVideoPipeline.from_pretrained("THUDM/CogVideoX-5b-I2V", torch_dtype=torch.bfloat16)`

Trying to load this pipeline results in:

`HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/THUDM/CogVideoX-5b-I2V`

Most likely, this repository is still private.

### Reproduction

Reproduction: see above, simply run code example in documentation

### System Info

diffusers 0.30.3

**Comment by a-r-r-o-w** [comment]
The model has not been released yet. It will be in the next few days. The reason for the early-release with Diffusers is to enable usage of the pipeline to users in countries where Github is banned

**Comment by a-r-r-o-w** [comment]
Model has been released here: https://huggingface.co/THUDM/CogVideoX-5b-I2V :partying_face:
