### ISSUE TITLE
CogVideoX I2V: Missing guard-rail on num_frames

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#9467]
### Describe the bug

CogVideoX I2V: 
There is a warning when the negative_prompt is defined, but no warning when num_frames is defined, however, the latter will cause a faulty render, so maybe a guard-rail warning should be added to a defined num_frames value.

The faulty video: 
https://github.com/user-attachments/assets/5d3b4dd9-c9d2-43bb-b14c-bdd34b490bab

### Reproduction

Just add a defined num_frames value to the inference code.

### System Info

Latest beta diff, Win 11

### Who can help?

@DN6 @a-r-r-o-w

**Comment by a-r-r-o-w** [comment]
I'm having a bit of trouble understanding what's wrong here, sorry. Do you mean to say that there should be a `num_frames == 49` restriction here?

**Comment by tin2tin** [comment]
Well, I had a lot of faulty renders until I realized that disabling num_frames made it work. The value might have been 48.

**Comment by a-r-r-o-w** [comment]
Yes, unfortunately the I2V model doesn't support anything other than 49 frames. I missed this initially so opened a patch PR to fix. Thanks for reporting!

**Comment by a-r-r-o-w** [comment]
Marking as closed because does not make sense to guard the value any more because of the 1.5 checkpoints that support 81 and 161 frames as well
