### ISSUE TITLE
SDXL PAG with IPAdapter is not working. 

### ISSUE THREAD

**Issue by akshatd007** [huggingface/diffusers#9495]
### Describe the bug

I am currently using diffusers, SDXL 1.0 base + PAG + IPAdapter. The pipeline StableDiffusionXLControlNetPipeline is unable to handle both, PAG and IPAdapter for a controlnet canny image as the input. 

Goal: I want to have a canny input image and generate an image such that it uses both, the reference image and also uses PAG to produce a clean/ non-deformed image in SDXL. 

The error is below: 
 `
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 23.02it/s]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 37.55it/s]
 `last_sigmas_type='zero'` is not supported for `lower_order_final=False`. Changing scheduler {self.config} to have `lower_order_final` set to True.
  0%|                                                                                                                                                             | 0/40 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/akshat-4090/lab/Dev/sillyscenes_dev/app/sdxl_pag_ip_error.py", line 140, in <module>
    images = pipe(**pipe_parameters).images
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/akshat-4090/.cache/huggingface/modules/diffusers_modules/local/pipeline.py", line 1962, in __call__
    noise_pred = self.unet(
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1216, in forward
    sample, res_samples = downsample_block(
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1288, in forward
    hidden_states = attn(
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/diffusers/models/transformers/transformer_2d.py", line 442, in forward
    hidden_states = block(
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/diffusers/models/attention.py", line 504, in forward
    attn_output = self.attn2(
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 490, in forward
    return self.processor(
  File "/home/akshat-4090/miniconda3/envs/stable/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 3996, in __call__
    ip_key = ip_key.view(batch_size, -1, attn.heads, head_dim).transpose(1, 2)
RuntimeError: shape '[3, -1, 10, 64]' is invalid for input of size 5120`

### Reproduction

```
from transformers import pipeline
from diffusers import StableDiffusionXLControlNetPipeline, ControlNetModel, StableDiffusionXLPipeline,AutoencoderKL
from transformers import CLIPVisionModelWithProjection
import os 
import torch 
from core.config import MODEL_PATH
import numpy as np 
import cv2 
from PIL import Image 


# Define model cache paths
SDXL_MODEL_CACHE = f"{MODEL_PATH}/sdxl-cache"
PAG_MODEL_CACHE = "./ml/model/sdxl_perturbed_attention_guidance_controlnet/pipeline.py"
IP_CACHE = f"{MODEL_PATH}/ip-cache"
VAE_PAG = f"{MODEL_PATH}/sdxl-vae-fp16-fix" 

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
#load the controlnet model
controlnet = ControlNetModel.from_pretrained(
    "diffusers/controlnet-canny-sdxl-1.0", torch_dtype=torch.float16, 
    cache_dir=f'{MODEL_PATH}/').to(device)

#define the vae for pag pipeline
vaepag = AutoencoderKL.from_pretrained(VAE_PAG, torch_dtype=torch.float16,).to(device)


image_encoder = CLIPVisionModelWithProjection.from_pretrained(
    IP_CACHE ,
    subfolder="models/image_encoder",
    torch_dtype=torch.float16,
    ).to(device)

pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
    SDXL_MODEL_CACHE,
    torch_dtype=torch.float16, 
    cache_dir= MODEL_PATH,
    custom_pipeline = PAG_MODEL_CACHE,
    variant = "fp16",
    controlnet= controlnet,
    vae=vaepag,
    image_encoder=image_encoder).to(device)

pipe.load_ip_adapter(
            IP_CACHE, subfolder="sdxl_models", 
            weight_name="ip-adapter_sdxl_vit-h.bin", 
            torch_dtype=torch.float16)

seed = 98786576890
imagepth = './mask_029_image.jpg'
reference_image = Image.open('icy_room.jpg')
image = Image.open(imagepth)
step = 40
cfg = 4
pag_scale=3
prompt = "a beautiful modern living room"
neg_prompt = "CGI, fake, Digital"
number_of_images = 1


og_image = Image.open(imagepth).convert("RGBA")
og_imgnp = np.array(og_image)
image = cv2.Canny(og_imgnp, 30, 45)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
canny_image = Image.fromarray(image)


if not neg_prompt:
    neg_prompt = "Deformed, painted, CGI, fake"
from diffusers import DPMSolverSinglestepScheduler, EulerAncestralDiscreteScheduler,DDIMScheduler

number_of_images = 1

generator = [torch.Generator(device="cuda").manual_seed(seed)]
scheduler = DPMSolverSinglestepScheduler()


pipe_parameters = {
        "prompt": prompt,
        "negative_prompt": neg_prompt,
        "generator":generator,
        "guidance_scale":cfg,
        "num_inference_steps": step,
        "num_images_per_prompt": number_of_images,
        "controlnet_conditioning_scale": 0.75,
        "image": canny_image,
        "pag_scale" : pag_scale,
        "ip_adapter_image":reference_image,
        }
pipe.set_ip_adapter_scale(0.3)
pipe.scheduler=scheduler.from_config(pipe.scheduler.config)


images = pipe(**pipe_parameters).images
img = images[0]
image = img.convert("RGBA")
image = Image.alpha_composite(image,og_image).convert('RGB')
image.save('ip_pag_combination1.png')
```

### System Info

python==3.10.14
accelerate==0.27.2
diffusers==0.30.3
opencv-python==4.10.0.84
opencv-python-headless==4.9.0.80
transformers==4.38.1
torch==2.2.1
torchaudio==2.2.1
torchsde==0.2.6
torchvision==0.17.1

**Comment by asomoza** [comment]
Hi, are you using xformers? Your code has a lot of unknowns for us since you load everything locally and even the pipeline is local, but I tested it with some code from the PAG PR and it works without a problem:

```python
import cv2
import numpy as np
import torch
from PIL import Image
from transformers import CLIPVisionModelWithProjection

from diffusers import AutoencoderKL, AutoPipelineForText2Image, ControlNetModel
from diffusers.utils import load_image


image_encoder = CLIPVisionModelWithProjection.from_pretrained(
    "h94/IP-Adapter", subfolder="models/image_encoder", torch_dtype=torch.float16
)

# initialize the models and pipeline
controlnet_conditioning_scale = 0.5  # recommended for good generalization
controlnet = ControlNetModel.from_pretrained("diffusers/controlnet-canny-sdxl-1.0", torch_dtype=torch.float16)

vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)

pipeline = AutoPipelineForText2Image.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    controlnet=controlnet,
    vae=vae,
    enable_pag=True,
    pag_applied_layers="mid",
    torch_dtype=torch.float16,
    image_encoder=image_encoder,
)
pipeline.enable_model_cpu_offload()
print(f" pipeline: {pipeline.__class__}")

pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="sdxl_models", weight_name="ip-adapter_sdxl_vit-h.safetensors")

# download an image
image = load_image(
    "https://hf.co/datasets/hf-internal-testing/diffusers-images/resolve/main/sd_controlnet/hf-logo.png"
)
# get canny image
image = np.array(image)
image = cv2.Canny(image, 100, 200)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
canny_image = Image.fromarray(image)

prompt = "aerial view, a futuristic research complex in a bright foggy jungle, hard lighting"
negative_prompt = "low quality, bad quality, sketches"


generator = torch.Generator(device="cpu").manual_seed(1)
image = pipeline(
    prompt=prompt,
    controlnet_conditioning_scale=controlnet_conditioning_scale,
    image=canny_image,
    ip_adapter_image=image,
    num_inference_steps=25,
    guidance_scale=6.5,
    generator=generator,
    pag_scale=3.0,
).images[0]
```

Maybe you can test it with this and see if its a problem with something local on your environment.

**Comment by akshatd007** [comment]
Hey @asomoza, thank you for the code you shared. I realised that my original pipeline works if i just remove the
custom_pipeline parameter. Also, I am not using xformers. It worked!
