### ISSUE TITLE
The `JointAttnProcessor2_0` in the `SD3Transformer2DModel` does not include `RMSNorm`.

### ISSUE THREAD

**Issue by HuiZhang0812** [huggingface/diffusers#9515]
### Describe the bug

The `SD3Transformer2DModel` utilizes the `JointTransformerBlock`, where the attention is handled by `JointAttnProcessor2_0`. However, `JointAttnProcessor2_0` does not include `RMSNorm`, which is inconsistent with the SD3 paper.

### Reproduction

For detailed code, please see:

- `SD3Transformer2DModel` in diffusers/src/diffusers/models/transformers/transformer_sd3.py

- `JointTransformerBlock` in diffusers/src/diffusers/models/attention.py

- `JointAttnProcessor2_0` in diffusers/src/diffusers/models/attention_processor.py

### System Info

diffusers 0.31.0

**Comment by yiyixuxu** [comment]
SD3 indeed does not have it, but SD3.5 does:)
closing here because it is not a bug (our implementation matches with the original)
