### ISSUE TITLE
How to use x-labs flux controlnet models in diffusers?

### ISSUE THREAD

**Issue by neuron-party** [huggingface/diffusers#9551]
### Model/Pipeline/Scheduler description

The following controlnets are supported in Comfy UI, but was wondering how we can use these in diffusers as well for developers. Afaik, there is no from_single_file method for FluxControlNet to load the safetensors?

### Open source status

- [x] The model implementation is available.
- [x] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://huggingface.co/XLabs-AI/flux-controlnet-canny
https://huggingface.co/XLabs-AI/flux-controlnet-canny-v3

_No response_

**Comment by asomoza** [comment]
Hi, we don't have support for those controlnets yet, there's an [issue](https://github.com/huggingface/diffusers/issues/9378) asking for community contributions and there's also a [draft PR](https://github.com/huggingface/diffusers/pull/9385).

**Comment by neuron-party** [comment]
thanks!
