### ISSUE TITLE
Why there is no LoRA only finetune example of FLUX.1?

### ISSUE THREAD

**Issue by eeyrw** [huggingface/diffusers#9599]
**Is your feature request related to a problem? Please describe.**
The only example of LoRA finetune for FLUX.1 I discovered is here:
https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_flux.py
which is a dreambooth example. The dreambooth is VRAM intensive and not useful for scenario that dataset is big enough and does not need regularization images.

**Describe the solution you'd like.**
A LoRA only example for FLUX.1

**Describe alternatives you've considered.**
Provide some tips for me to modify by myself.

**Comment by a-r-r-o-w** [comment]
cc @sayakpaul @linoytsaban

**Comment by sayakpaul** [comment]
I think you're referring to regular T2I fine-tuning without doing DreamBooth specific bits. That is possible with the mentioned script itself:

* Don't pass `prior_preservation`: https://github.com/huggingface/diffusers/blob/31058cdaef63ca660a1a045281d156239fba8192/examples/dreambooth/train_dreambooth_lora_flux.py#L354
* `caption_column` allows you to have a small dataset with image-caption pairs (with varying captions for each images): https://github.com/huggingface/diffusers/blob/31058cdaef63ca660a1a045281d156239fba8192/examples/dreambooth/train_dreambooth_lora_flux.py#L292
