### ISSUE TITLE
What's the difference between PNDM and plms

### ISSUE THREAD

**Issue by dingjingzhen** [huggingface/diffusers#960]
What's the difference between PNDM and plms，plms for CompVis/stable-diffusion-v1-4-origin

**Comment by patrickvonplaten** [comment]
Good question! 

The short answer: 
>They are the same!

The long answer:
> PNDM was suggested by the PNDM paper ([Pseudo Numerical Methods for Diffusion Models on Manifolds](https://arxiv.org/abs/2202.09778)) with PNDM standing for **P**seudo **N**umerical Methods for **D**iffusion **M**odels . The algorithm for PNDMs is defined concisely in Algorithm 2 where you can see that the first loop is called PRK and the second loop is called PLMS. So one can state the PLMS is a submethod/sub-scheduler of the PNDM scheduler. BTW PLMS stands for **p**seudo-**l**inear **m**ulti-**s**tep. 

Now practically the CompVis PLMS sampler is identical to the `diffusers` PNDM scheduler if you set `config.skip_prk_steps=True` which is done in the original `diffusers` CompVis/stable-diffusion-v1-4 repo: https://huggingface.co/CompVis/stable-diffusion-v1-4/blob/main/scheduler/scheduler_config.json#L8
