### ISSUE TITLE
add load_lora_weights to  pipeline_stable_diffusion_3_img2img.py

### ISSUE THREAD

**Issue by TheOneTrueGuy** [huggingface/diffusers#9610]
**Is your feature request related to a problem? Please describe.*"
Yes, there is no effective way to load lora weights with SD3

A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
I can't get LoRa weights to load despite the fact there is a thorough and easy way to train them

**Describe the solution you'd like.**
the function load_lora_weights() should be added to pipeline_stable_diffusion_3_img2img.py

**Describe alternatives you've considered.**
Any sort of work around using another form of loader or model merging etc.

**Additional context.**
https://huggingface.co/Mujeeb603/SD3-medium-Geometry-Diagrams-Lora-1

**Comment by a-r-r-o-w** [comment]
Would you like to open a PR for this?

It should be as simple as deriving from the lora loader class and supporting the lora parameters in the pipeline I believe. Relevant bits:

https://github.com/huggingface/diffusers/blob/31058cdaef63ca660a1a045281d156239fba8192/src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py#L131

https://github.com/huggingface/diffusers/blob/31058cdaef63ca660a1a045281d156239fba8192/src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py#L338

https://github.com/huggingface/diffusers/blob/31058cdaef63ca660a1a045281d156239fba8192/src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py#L826

https://github.com/huggingface/diffusers/blob/31058cdaef63ca660a1a045281d156239fba8192/src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py#L850

LMK if you need any help if you'd like to open the PR!

**Comment by TheOneTrueGuy** [comment]
Yes, thank you, I would like to open a PR for this. 
I'm still learning what the correct etiquette is for Github.
I suppose the approach here would be to fork diffusers and then copy in the relevant code bits?
I'm still trying to diagnose the problem. Gemini insists it is an environment problem. I'm running my code in Google colab with full updates so I can't see how that is possible.

**Comment by a-r-r-o-w** [comment]
Awesome!

> I suppose the approach here would be to fork diffusers and then copy in the relevant code bits?

Yep, fork -> new branch (otherwise it might make it difficult to pull changes from upstream to your fork main) -> relevant changes -> PR

> I'm still trying to diagnose the problem. Gemini insists it is an environment problem.

Nope, this isn't an environment problem. It's simply that the pipelines you're using do not support the lora loading mixin, which adds the appropriate methods that allow you to load loras. Looking forward to the PR!
