### ISSUE TITLE
UNet1DConditionModel Implementation

### ISSUE THREAD

**Issue by lucainiaoge** [huggingface/diffusers#9615]
### Model/Pipeline/Scheduler description

[diffusers-unet-1d-condition](https://github.com/lucainiaoge/diffusers-unet-1d-condition)

- This is a counterpart to the [UNet2DConditionModel](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/unets/unet_2d_condition.py)
- Added new blocks for 1d mode, contained in the python files with the same name as the [diffusers models](https://github.com/huggingface/diffusers/tree/main/src/diffusers/models). But the contents in this repo do not contain the original code from diffusers package.
- Deleted methods/parameters that only relate to 2d objects, like spatial norm and freeu.
- Already debugged and successfully went through forward pass with all up/down/mid blocks.
- However, I am not totally sure about the well-being of this codebase, because I am no experienced in all parameters/methods of the model. So I need help from more experienced developers to find out potential bugs.

### Open source status

- [X] The model implementation is available.
- [ ] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

My implementation: https://github.com/lucainiaoge/diffusers-unet-1d-condition

**Comment by a-r-r-o-w** [comment]
Thank you, this looks interesting! Have you trained any models using it on 1D data? Would be very interesting to see.

Usually, we only add support for models that are already well used in the community, or has high chance of getting large usage, or if a research group is collaborating with us. So, while this is interesting, I don't think we can support it from within Diffusers - sorry!

**Comment by lucainiaoge** [comment]
> Thank you, this looks interesting! Have you trained any models using it on 1D data? Would be very interesting to see.
> 
> Usually, we only add support for models that are already well used in the community, or has high chance of getting large usage, or if a research group is collaborating with us. So, while this is interesting, I don't think we can support it from within Diffusers - sorry!

OK. I will repost this once I integrate it to my trained model. Issue closed.

**Comment by DevKiHyun** [comment]
I vote this one. 

Hope to upload into official repository.
