### ISSUE TITLE
Make ControlNet pipeline `StableDiffusionControlNetPipeline` support `interrupt`

### ISSUE THREAD

**Issue by pureexe** [huggingface/diffusers#9619]
**Is your feature request related to a problem? Please describe.**
`StableDiffusionPipeline` has an interrupt that stops the denoising loop when no longer needed.  but the ControlNet pipeline doesn't have it.

https://github.com/huggingface/diffusers/blob/31058cdaef63ca660a1a045281d156239fba8192/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L1000-L1001

**Describe the solution you'd like.**
Please bring the interrupt to ControlNet pipeline

**Describe alternatives you've considered.**
Right now, I have to keep denoising the loop is denoising for nothing to make the code still work correctly when ControlNet is apply. Or i might need to create a copy of ControlNetPipeline for myself to early stop denosing loop.

**Comment by a-r-r-o-w** [comment]
Would you like to open a PR for this? Should be a simple change and we could merge it quickly

**Comment by pureexe** [comment]
> Would you like to open a PR for this? Should be a simple change and we could merge it quickly

Sure, i created the pull request at #9620
