### ISSUE TITLE
The new inpaint pipelines sames not support other size than 512*512

### ISSUE THREAD

**Issue by CrazyBoyM** [huggingface/diffusers#962]
### Describe the bug

When I try the 512*512 image and mask, it works well.
But when I test other size, the new inpaint pipe tip a error:
```
Traceback (most recent call last):
  File "/root/work/tasker/test.py", line 33, in <module>
    image = pipe(prompt=prompt, image=image, mask_image=mask_image).images[0]
  File "/root/.conda/envs/ai/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/.conda/envs/ai/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 390, in __call__
    latent_model_input = torch.cat([latent_model_input, mask, masked_image_latents], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 96 for tensor number 2 in the list.
```

### Reproduction

```
import PIL
from diffusers import StableDiffusionInpaintPipeline
import torch
from diffusers import DDIMScheduler


pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "./models/stable-diffusion-inpainting",
    revision="fp16",
    torch_dtype=torch.float16,
    scheduler = DDIMScheduler(
        beta_start=0.00085,
        beta_end=0.012,
        beta_schedule="scaled_linear",
        clip_sample=False,
        set_alpha_to_one=True,
        ),
    ).to("cuda")

prompt = "Face of a yellow cat, high resolution, sitting on a park bench"
image = PIL.Image.open("image.jpg")
mask_image = PIL.Image.open("mask.jpg")
w, h = image.size
w = w // 64 * 64
h = h // 64 * 64
image = image.resize((w, h))
mask_image = mask_image.resize((w, h))
print(image.size, mask_image.size)
with torch.autocast('cuda'):
    image = pipe(prompt=prompt, image=image, mask_image=mask_image).images[0]
    image = image.resize((w, h))
    image.save("./result.png")
```

### Logs

```shell
latent_model_input = torch.cat([latent_model_input, mask, masked_image_latents], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 96 for tensor number 2 in the list.
```
```


### System Info

cuda 11.6
python 3.10
torch 1.12.1
diffusers 0.6.0

**Comment by CrazyBoyM** [comment]
![image](https://user-images.githubusercontent.com/35400185/197512401-1546a9e0-c5ba-4b30-86d0-0fa3acb57f95.png)
![mask](https://user-images.githubusercontent.com/35400185/197512414-83cb43ea-0ef1-440e-91d6-9e8f09059cd9.png)

here is the image and mask for test.

**Comment by Sanster** [comment]
You need to pass `height` and `width` when calling the pipeline: https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion#diffusers.StableDiffusionInpaintPipeline.__call__.height

**Comment by patrickvonplaten** [comment]
@CrazyBoyM, did you try setting the height and width parameter? I'm not sure 100% whether this works correctly - happy to fix it if it doesn't

**Comment by CrazyBoyM** [comment]
> You need to pass `height` and `width` when calling the pipeline: https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion#diffusers.StableDiffusionInpaintPipeline.__call__.height

thanks!!!

**Comment by CrazyBoyM** [comment]
> @CrazyBoyM, did you try setting the height and width parameter? I'm not sure 100% whether this works correctly - happy to fix it if it doesn't

sorry for that when i test the demo code in the readme, i forget to pass the height and width parameters.it works fine now. Thanks for reply!!
