### ISSUE TITLE
How to use my own trained lora in local computer?

### ISSUE THREAD

**Issue by derekcbr** [huggingface/diffusers#9639]
local_model_path = r"D:\downloads\FLUX.1-schnell"
pipe = FluxPipeline.from_pretrained(local_model_path, torch_dtype=torch.bfloat16)
#lora not working by this way
pipe.load_lora_weights("XLabs-AI/flux-lora-collection", weight_name="disney_lora.safetensors") 
pipe.load_lora_weights(r"D:\AI\stable-diffusion-webui-forge\models\Lora\myflux\myhsr.safetensors")
pipe.fuse_lora()
pipe.unload_lora_weights()
#pipe.enable_model_cpu_offload() #save some VRAM by offloading the model to CPU. Remove this if you have enough GPU power
pipe.enable_sequential_cpu_offload()

But it seems not loading my own lora properly.

**Comment by a-r-r-o-w** [comment]
When you say "it seems not loading my own lora properly", do you mean:

1) there is a runtime error that occurs caused in the `load_lora_weights` method?
2) the outputs with and without the lora are the same for a given prompt and seed?

or, is it something different?

Could you also provide your environment information? You can this by running `diffusers-cli env`.

cc @asomoza

**Comment by derekcbr** [comment]
Thank you for the reply. No lora related contents are generated even if adding the lora key words. It is Windows 10.

**Comment by derekcbr** [comment]
![Uploading flux-schnell_1728692694.png…]()

**Comment by a-r-r-o-w** [comment]
When you try inference with just the disney lora, do you see any effect?

`pipe.load_lora_weights("XLabs-AI/flux-lora-collection", weight_name="disney_lora.safetensors")`

When you try inference with just the SD Forge lora, do you see any effect?

`pipe.load_lora_weights(r"D:\AI\stable-diffusion-webui-forge\models\Lora\myflux\myhsr.safetensors")`

The former should work I believe, but I'm not quite sure if we support Forge-style loras or the format they are saved in. Pinging @asomoza and @sayakpaul who know more about the Flux loras from XLabs. Could you also provide the public link to where you got `myhsr.safetensors` so we can try to replicate?

Please provide the output of `diffusers-cli env` too.

**Comment by sayakpaul** [comment]
If you want to load a local LoRA directly, just pass the absolute path like @a-r-r-o-w showed. Or we can pass the folder path and specify the `weight_name`. We have got a test for that ensures that it works:
https://github.com/huggingface/diffusers/blob/6a5f06488c0d88c1827c016835cd5f64abe4b52c/tests/lora/utils.py#L764

**Comment by dieptran2500** [comment]
> When you try inference with just the disney lora, do you see any effect?
> 
> `pipe.load_lora_weights("XLabs-AI/flux-lora-collection", weight_name="disney_lora.safetensors")`
> 
> When you try inference with just the SD Forge lora, do you see any effect?
> 
> `pipe.load_lora_weights(r"D:\AI\stable-diffusion-webui-forge\models\Lora\myflux\myhsr.safetensors")`
> 
> The former should work I believe, but I'm not quite sure if we support Forge-style loras or the format they are saved in. Pinging @asomoza and @sayakpaul who know more about the Flux loras from XLabs. Could you also provide the public link to where you got `myhsr.safetensors` so we can try to replicate?
> 
> Please provide the output of `diffusers-cli env` too.

hello, do you solve your problem?, i have same issuse
