### ISSUE TITLE
subprocess.CalledProcessError running train_dreambooth_lora_sdxl.py 

### ISSUE THREAD

**Issue by sebastianherreramonterrosa** [huggingface/diffusers#9664]
### Describe the bug

I'm trying to run train_dreambooth_lora_sdxl.py described here:
https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_sdxl.md

Also using this example:
https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb#scrollTo=GOiZSXHfx3mJ

Running in colab or locallay I have the same error:

1. If run `accelerate launch train_dreambooth_lora_sdxl.py ...` then i get
`subprocess.CalledProcessError: Command ... returned non-zero exit status 1.`

1. If run `python train_dreambooth_lora_sdxl.py ...` then i get
`TypeError: LoraConfig.__init__() got an unexpected keyword argument 'use_dora'`

### Reproduction

The problem is possible reproduce running this example. In fact, in the default of the notebook is possible check the problem.

https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb#scrollTo=GOiZSXHfx3m

### System Info

- Platform: Ubuntu24.04 or Google Colab
- Python 3.12.7
- transformers version: 4.45.2
- accelerate version: 1.0.1
- diffusers version: 0.31.0.dev0
- peft version: 0.7.0

### Who can help?

@yiyixuxu @sayakpaul @DN6

**Comment by sayakpaul** [comment]
Can you ensure you're using the latest `peft`?

**Comment by sebastianherreramonterrosa** [comment]
Thanks, this is the solution
