### ISSUE TITLE
high cpu usage when loading multiple loras at once.

### ISSUE THREAD

**Issue by gudwns1215** [huggingface/diffusers#9673]
### Describe the bug

Hi, I was making a synthesis system using celery and diffusers, 
and I found the cpu usage of program goes high when loading loras,
it is okay when I use just one worker, but it becomes hard when using 8 workers at once.

It happens when lora loaded first time, and I think it is because of peft, because I didn't get any trouble before peft support.

so Is there any way to lower cpu usage when loading loras? or is there any way not to use peft when sdxl lora loading?

### Reproduction

```python
# test lora downloaded from https://civitai.com/models/150986/blueprintify-sd-xl-10

from diffusers import AutoPipelineForText2Image
import torch
from uuid import uuid4
from tqdm import tqdm

pipeline = AutoPipelineForText2Image.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16).to("cuda")
num_of_iterations = 10


for _ in tqdm(range(num_of_iterations)):
    lora_name = str(uuid4().hex)
    pipeline.load_lora_weights(
        "./test",
        weight_name="lora.safetensors",
        adapter_name=lora_name,
        low_cpu_mem_usage=True,
    )
    pipeline.set_adapters([lora_name], adapter_weights=[1.0])
```

### System Info

torch==2.1.1+cu121
diffusers==0.30.3
accelerate==0.32.1
peft==0.13.0
transformers==4.42.3
python==3.9.5

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
Can you please update to the latest `peft` version? Also, note that `low_cpu_mem_usage` for LoRA loading in `transformers` was recently added. So, please update your transformers installation to be from its `main`: 

```bash
pip install git+https://github.com/huggingface/transformers/
```

Follow the same for `diffusers` too:

```bash
pip install git+https://github.com/huggingface/diffusers/
```

Ccing @BenjaminBossan

**Comment by gudwns1215** [comment]
oh, I think cpu high usage solved, when did this change applied to official release?

**Comment by sayakpaul** [comment]
Official release will be made in a few days. Stay tuned.

**Comment by gudwns1215** [comment]
awesome! I will close this issue since it resolved.

**Comment by sayakpaul** [comment]
Feel free to test the feature and get back to us if you notice something weird.
