### ISSUE TITLE
Model loading is slow / Time before generating

### ISSUE THREAD

**Issue by Feniksss** [huggingface/diffusers#968]
### Describe the bug

I have used a simple realization on T4 (Google Cloud)
```
import torch
from torch import autocast
from diffusers import StableDiffusionPipeline

access_token = ""

pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    revision="fp16",
    torch_dtype=torch.float16,
    use_auth_token=access_token,
)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]

image.save("astronaut_rides_horse_1.png")
```

And generating can take 10-15 sec per image - it's good result.
But we have a problem with time before start of generating. Pre-loading models and files can take ~ 30 sec.
For example:
![20221024-penj-42kb](https://user-images.githubusercontent.com/7080230/197623318-0b0bfa75-54bf-40af-8ce6-7e22549f3839.jpg)

How we can speed up the preloading?

### System Info

Google Cloud - T4

**Comment by patrickvonplaten** [comment]
Hey @Feniksss,

That's a good question, this should be solved when using:

```python
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    revision="fp16",
    torch_dtype=torch.float16,
    use_auth_token=access_token,
    device_map="auto",
)
```

instead of:

```python
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    revision="fp16",
    torch_dtype=torch.float16,
    use_auth_token=access_token,
)
pipe = pipe.to("cuda")
```

Could you try this?

**Comment by patrickvonplaten** [comment]
Hey @Feniksss,

That's a good question, this should be solved when using:

```python
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    revision="fp16",
    torch_dtype=torch.float16,
    use_auth_token=access_token,
    device_map="auto",
)
```

instead of:

```python
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    revision="fp16",
    torch_dtype=torch.float16,
    use_auth_token=access_token,
)
pipe = pipe.to("cuda")
```

Could you try this?

**Comment by patrickvonplaten** [comment]
In my tests, the time goes down from 22 seconds to 3 seconds. Will open a PR to improve the docs here.

**Comment by piEsposito** [comment]
@patrickvonplaten nice! This was a sife effect I didn't think of when I was implementing it.
