### ISSUE TITLE
Flux inversion

### ISSUE THREAD

**Issue by yuxu915** [huggingface/diffusers#9700]
current img2img is not so well, [RF Inversion](https://rf-inversion.github.io/)) provides an inverse method for Flux real image editing, can we implement it using diffusers?

or how can we use DDIM inversion in Flux?

**Comment by yuxu915** [comment]
@sayakpaul @yiyixuxu

**Comment by charchit7** [comment]
RF inversion is really good.

**Comment by sayakpaul** [comment]
Ccing @linoytsaban @apolinario because they pioneered LEDITS: https://arxiv.org/abs/2307.00522, which uses inversion techniques quite heavily.

**Comment by chuck-ma** [comment]
Any progress here?

**Comment by linoytsaban** [comment]
Hey! I'm looking into potentially integrating RF-Inversion into diffusers, in the meantime there's a diffusers based implementation here that might be helpful: https://github.com/DarkMnDragon/rf-inversion-diffuser

**Comment by charchit7** [comment]
#9816
