### ISSUE TITLE
[ Feature request] Stable Diffusion 1.5 inpainting without prompt

### ISSUE THREAD

**Issue by Sanster** [huggingface/diffusers#973]
Use stable-diffusion 1.5 inpainting model without prompt to do regular inpainting. Example image come from [latent-diffusion](https://github.com/CompVis/latent-diffusion).

![image](https://user-images.githubusercontent.com/3998421/197736137-a7baa323-f27e-408c-89e3-8360550b297b.png)

**Comment by patrickvonplaten** [comment]
Did you try if this works by just passing `""` as a prompt?

**Comment by Sanster** [comment]
I just tried it and some part of the results are very good

|Original| Result|
|-------|---------|
|![dog](https://user-images.githubusercontent.com/3998421/198046705-3e4a80c4-9883-4f06-a883-007bb553cca8.jpg)|![image](https://user-images.githubusercontent.com/3998421/198046907-12ab13af-ed95-4d0f-95e1-ee7e588af576.png)|

**Comment by patrickvonplaten** [comment]
Hmm, I'm not 100% sure how to best set the default here - @patil-suraj do you have a hunch maybe?

**Comment by patil-suraj** [comment]
The stable-diffusion inpainting checkpoint is trained to replace masked objects with objects based on the prompt, so I'm not sure if this will work with existing checkpoint. 

But maybe this could achieved by doing some prompt engineering and playing around a bit with negative prompts, For example this is what I got by using the prompt `an empty bench`. So maybe play around a bit with different prompts, negative prompts depending on the context of the image. 

Additionally we could also port those LDM in-painting checkpoints.

![0](https://user-images.githubusercontent.com/27137566/198088285-66da638c-58ca-4fcf-834f-df83eda7932d.png)
![1](https://user-images.githubusercontent.com/27137566/198088300-2bc17824-b45f-4aed-b487-af870d974fbe.png)
![2](https://user-images.githubusercontent.com/27137566/198088316-40b007e0-8025-4364-9c1b-d889fb00e27c.png)
