### ISSUE TITLE
关于提交信息国家一栏选项错误

### ISSUE THREAD

**Issue by tangyuming99** [huggingface/diffusers#9748]
![image](https://github.com/user-attachments/assets/96c017cb-96dc-412f-9852-46674880d9ba)
![image](https://github.com/user-attachments/assets/7bb9d7fc-4658-46ad-a6bb-dc9d04ee0720)
![image](https://github.com/user-attachments/assets/d432e779-81fc-4981-9deb-1e4ee616d240)
![image](https://github.com/user-attachments/assets/2ca99042-919c-4e53-9c7e-2223f78e5457)
![image](https://github.com/user-attachments/assets/f047927b-9015-47d7-b359-c793c8e8eca4)

**Comment by a-r-r-o-w** [comment]
It is not clear what you're trying to say here. Please open a new issue with details in english if you'd like to seek help regarding anything related to diffusers.
