### ISSUE TITLE
Could not find loading_adapters.ipynb

### ISSUE THREAD

**Issue by thliang01** [huggingface/diffusers#9756]
### Describe the bug

while reading doc [Load adapters](https://huggingface.co/docs/diffusers/using-diffusers/loading_adapters)

I tried to open in Colab to run an example on this page.

<img width="504" alt="open_colab" src="https://github.com/user-attachments/assets/0b1397f1-d266-4d83-84ab-276ea796a2a4">

It will get Notebook not found on a new page.

It can't find loading_adapters.ipynb in [huggingface/notebooks](https://github.com/huggingface/notebooks)

### Reproduction

I follow the doc and write down a Google Colab [Google Colab loading_adapters](https://colab.research.google.com/drive/1pYpvsOf6U9CAZfughY1aUltUQTFsw4OI)

Can I contribute a pr for this?
Do you know how I can do this?
Commit to notebook repo?
Or something different?

### System Info

Google Colab

### Who can help?

@stevhliu  @sayakpaul

**Comment by SahilCarterr** [comment]
> ### Reproduction
> I follow the doc and write down a google colab [Google Colab loading_adapters](https://colab.research.google.com/drive/1pYpvsOf6U9CAZfughY1aUltUQTFsw4OI)
* Make you notebook public. Look [here](https://www.geeksforgeeks.org/sharing-notebook-in-google-colab/) for the tutorial
> 
> Can I contribute a pr for this? Do you know how I can do this? Commit to notebook repo? Or something different?
> 
* You should open a issue [here](https://github.com/huggingface/notebooks/issues)
* Then you should read [Contribution guide](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md#5-contribute-to-the-documentation)
* Then open a pull request for the same [here](https://github.com/huggingface/notebooks/pulls)
* You should commit you notebook in this [directory](https://github.com/huggingface/notebooks/tree/main/diffusers_doc/en)

**Comment by thliang01** [comment]
Add loading_adapters.ipynb notebook at [huggingface
/notebooks - #521](https://github.com/huggingface/notebooks/pull/521)

**Comment by thliang01** [comment]
@SahilCarterr Thanks for reply

**Comment by stevhliu** [comment]
Hi, thanks for raising the issue. I don't actually see an `Open in Colab` button on v0.31.0 of the docs. Which version of the docs are you viewing?

![Screenshot 2024-10-23 at 11 23 05 AM](https://github.com/user-attachments/assets/0d880a67-e5cd-4a93-8d2a-856f7287b2e2)

Typically, the notebooks are automatically generated from the `.md` docs by the doc-builders workflow, but unfortunately, the workflow is broken at the moment which is why some of the more recent notebooks aren't being found. Thanks for manually adding the notebook! 🤗

**Comment by sayakpaul** [comment]
@stevhliu okay to close the issue then?

**Comment by stevhliu** [comment]
Yeah, we can continue this in https://github.com/huggingface/notebooks/pull/521 👍
