### ISSUE TITLE
[docstring] Incorrect docstring reference for `return_dict` in `pipeline_stable_diffusion_3.py`

### ISSUE THREAD

**Issue by shenzhiy21** [huggingface/diffusers#9761]
Hi there,

I noticed a small issue in the docstring for the `return_dict` parameter in `StableDiffusion3Pipeline` class [here](https://github.com/huggingface/diffusers/blob/24c7d578baf6a8b79890101dd280278fff031d12/src/diffusers/pipelines/stable_diffusion_3/pipeline_stable_diffusion_3.py#L765).

Seems like this should be [`~pipelines.stable_diffusion_3.StableDiffusion3PipelineOutput`] but not [`~pipelines.stable_diffusion_xl.StableDiffusionXLPipelineOutput`].

This is a minor issue but could be confusing for users working with the pipeline.

Thanks for the amazing work on this library!

**Comment by a-r-r-o-w** [comment]
Thank you for the kind words! This is indeed incorrect - would you like to open a quick PR with the mentioned fix?

**Comment by shenzhiy21** [comment]
@a-r-r-o-w  Sure! Already opened a PR.
