### ISSUE TITLE
Support ControlNetPlus Union if not already supported

### ISSUE THREAD

**Issue by jloveric** [huggingface/diffusers#9772]
It's not clear if ControlNetPlus is already supported by diffusers https://github.com/xinsir6/ControlNetPlus/tree/main/pipeline which consists of union controlnet for SDXL. This model seems to support the only SDXL segmentation that I'm aware of. If not already supported, it should be!

https://github.com/xinsir6/ControlNetPlus/tree/main

**Comment by yiyixuxu** [comment]
hi @jloveric 
yes it is on our list
I've been wanting on work on this but couldn't find time. So open this up to community in the mean time! let me know if you are interested in helping us too

**Comment by hlky** [comment]
I can take this, WIP PR is linked.

**Comment by souvikg544** [comment]
Hello ! Can I be a part of this as well? I have a good amount of experience on Difussion and have been starting out with contributing on Hugging Face.

**Comment by hlky** [comment]
@souvikg544 the PR is finished already, just waiting on reviews.
