### ISSUE TITLE
text_input_ids_list not part of encode_prompt definition

### ISSUE THREAD

**Issue by Vatsal-Malaviya** [huggingface/diffusers#9773]
Description
code is trying to pass `text_input_ids_list` as argument for `encode_prompt`, but, `text_input_ids_list` isn't supposed to be part of argument as per the definition.

Call
https://github.com/huggingface/diffusers/blob/298ab6eb01f3ef475c15218ea87de1494e1250aa/examples/dreambooth/train_dreambooth_sd3.py#L1597-L1601

Definition for `encode_prompt`
https://github.com/huggingface/diffusers/blob/298ab6eb01f3ef475c15218ea87de1494e1250aa/examples/dreambooth/train_dreambooth_sd3.py#L900-L976

Referencing  train_dreambooth_sd3_lora.py; I think definition of encode_prompt might need to be updated 
https://github.com/huggingface/diffusers/blob/298ab6eb01f3ef475c15218ea87de1494e1250aa/examples/dreambooth/train_dreambooth_lora_sd3.py#L952-L1037

**Comment by Vatsal-Malaviya** [comment]
@sayakpaul shall I do PR with a fix?

**Comment by SahilCarterr** [comment]
i think `text_input_ids` should be added to `train_dreambooth_sd3` in `_encode_prompt_with_clip` also. @Vatsal-Malaviya
