### ISSUE TITLE
Cannot load the cache when mapping the dataset

### ISSUE THREAD

**Issue by zhangn77** [huggingface/diffusers#9792]
### Describe the bug

I'm training the flux controlnet. The train_dataset.map() takes long time to finish. However, when I killed one training process and want to restart a new training with the same dataset. I can't reuse the mapped result even I defined the cache dir for the dataset.

### Reproduction

train flux controlnet and start again

### System Info

latest diffusers

**Comment by sayakpaul** [comment]
I think it's more of a `datasets` issue. Feel free to open an issue there with a minimal reproducible code snippet.

**Comment by zhangn77** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到。会尽快查看会予以回复~祝您生活愉快！
