### ISSUE TITLE
Replace shutil.copy with shutil.copyfile

### ISSUE THREAD

**Issue by almarouk** [huggingface/diffusers#9798]
shutil.copy copies permission bits which fails when the user who's running the script is trying to use a common cache that was generated by another user, even though the first user has read & write permissions over the cache (through Group permission for example). A real case scenario: submitting jobs on a GPU cluster accessed by multiple users with common cache directory to reduce disk and network usage.

https://github.com/huggingface/diffusers/blob/0d1d267b12e47b40b0e8f265339c76e0f45f8c49/src/diffusers/utils/dynamic_modules_utils.py#L328

Suggested solution: replace shutil.copy by shutil.copyfile which doesn't copy ownership.

**Comment by almarouk** [comment]
Maybe related to https://github.com/huggingface/huggingface_hub/pull/1220, https://github.com/huggingface/diffusers/issues/1517, https://github.com/huggingface/huggingface_hub/issues/1141.
For info I'm using v0.23.0.

**Comment by sayakpaul** [comment]
@Wauplin WDYT?

**Comment by Wauplin** [comment]
Agree with using `shutil.copyfile` yes! I didn't thought about permission issues back then. copyfile will only copy the file content but that is what we want here :)

**Comment by yiyixuxu** [comment]
@almarouk would you be willing to open a PR to help us?
