### ISSUE TITLE
Loading SDXL loras into Flux

### ISSUE THREAD

**Issue by christopher5106** [huggingface/diffusers#9822]
### Describe the bug

Currently it's possible to load SDXL loras without warning into Flux.

### Reproduction

Is it possible for you to implement a raise a warning (and an error when a boolean is active) when the list of layers here is zero:

https://github.com/huggingface/diffusers/blob/41e4779d988ead99e7acd78dc8e752de88777d0f/src/diffusers/loaders/lora_pipeline.py#L1905

### System Info

ubuntu

**Comment by christopher5106** [comment]
@yiyixuxu @sayakpaul @DN6 @asomoza

**Comment by a-r-r-o-w** [comment]
Thanks for the suggestion! I think we discussed about this too and @asomoza agreed that it would be better to raise a warning (can't seem to find the comment/issue where we did). Would you like to take this up @asomoza @yiyixuxu WDYT?

**Comment by sayakpaul** [comment]
Gentle ping @asomoza. I can take this up too.

**Comment by asomoza** [comment]
@sayakpaul please do if you have the bandwidth, for me it will take a while before I can take it.

**Comment by sayakpaul** [comment]
No worries. It will be relatively easier for me to tackle as well. I will open a PR :)

**Comment by sayakpaul** [comment]
@christopher5106 I tried to load an SDXL LoRA into Flux:

```py
from diffusers import DiffusionPipeline
import torch

pipeline = DiffusionPipeline.from_pretrained("black-forest-labs/Flux.1-Dev", torch_dtype=torch.bfloat16).to("cuda")
pipeline.load_lora_weights("nerijs/pixelportraits192-XL-v1.0")
```

And I got the following:

```bash
ValueError: Incompatible keys detected: 

 lora_unet_down_blocks_1_attentions_0_proj_in.alpha, lora_unet_down_blocks_1_attentions_0_proj_in.lora_down.weight, lora_unet_down_blocks_1_attentions_0_proj_in.lora_up.weight, lora_unet_down_blocks_1_attentions_0_proj_out.alpha, lora_unet_down_blocks_1_attentions_0_proj_out.lora_down.weight, lora_unet_down_blocks_1_attentions_0_proj_out.lora_up.weight, 
...
```

Does this not solve this issue already?

**Comment by christopher5106** [comment]
Looks like it has been solved by latest developments!
