### ISSUE TITLE
Support IPAdapters for FLUX pipelines

### ISSUE THREAD

**Issue by chenxiao111222** [huggingface/diffusers#9825]
### Model/Pipeline/Scheduler description

IPAdapter for FLUX is available now, do you have any plans to add IPAdapter to FLUX pipelines?

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

model implementation:
* https://github.com/XLabs-AI/x-flux/blob/main/src/flux/xflux_pipeline.py#L55

model weights:
* https://huggingface.co/XLabs-AI/flux-ip-adapter-v2
* https://huggingface.co/XLabs-AI/flux-ip-adapter

**Comment by sayakpaul** [comment]
Cc: @asomoza 

@chenxiao111222 would you maybe like to help us with the integration?

**Comment by hj13-mtlab** [comment]
@sayakpaul  flux ip adapter error, 'FluxTransformer2DModel' object has no attribute 'encoder_hid_proj'

**Comment by vladmandic** [comment]
@sayakpaul @yiyixuxu @asomoza as requested yesterday in a discussion, tagging this as a high-priority ask.
(if you'd prefer to use a different mechanism for tagging, let me know)

**Comment by asomoza** [comment]
the v2 seems to be a lot better, the v1 has more downloads though, even though I don't see that much generations with IP Adapter, we should probably add it now since it seems better and Flux is still very popular.

I'll do some test with it but I'm guessing the reason why isn't used that much its because of the VRAM requirement, same as controlnets.

I'll take a look at the PR and see how much is needed to add it, but in the meantime let's open it up to the community if someone wants to take it.

**Comment by peki12345** [comment]
> the v2 seems to be a lot better, the v1 has more downloads though, even though I don't see that much generations with IP Adapter, we should probably add it now since it seems better and Flux is still very popular.
> 
> I'll do some test with it but I'm guessing the reason why isn't used that much its because of the VRAM requirement, same as controlnets.
> 
> I'll take a look at the PR and see how much is needed to add it, but in the meantime let's open it up to the community if someone wants to take it.

Hi, may I ask if implementing flux IP adapter, can it support IP adapters with a given mask like SDXL? I think this is a very practical feature. I haven't seen similar functionality in other frameworks like ComfyUI, it seems to be unique to diffusers.

**Comment by yiyixuxu** [comment]
cc @fabiorigano here

**Comment by asomoza** [comment]
> Hi, may I ask if implementing flux IP adapter, can it support IP adapters with a given mask like SDXL? I think this is a very practical feature. I haven't seen similar functionality in other frameworks like ComfyUI, it seems to be unique to diffusers.

Of course, when we add it, it should have the same functionality as the other ones. The [ComfyUI](https://github.com/cubiq/ComfyUI_IPAdapter_plus) ones also have this though and actually have used the ComfyUI implementation as a reference.

**Comment by vladmandic** [comment]
ping.
