### ISSUE TITLE
unused parameters lead to error when training contrlnet_sd3

### ISSUE THREAD

**Issue by Zheng-Fang-CH** [huggingface/diffusers#9835]
### Discussed in https://github.com/huggingface/diffusers/discussions/9834

<div type='discussions-op-text'>

<sup>Originally posted by **Zheng-Fang-CH** November  1, 2024</sup>
![b1fa13bdb595284dce31e3cf189876b](https://github.com/user-attachments/assets/12faa0fc-acb8-4c98-ba03-b0e41bc9075a)
Is there someone meet this question? I have this error no matter I train it on single gpu or multi gpu.</div>

**Comment by sayakpaul** [comment]
Does using this help?
https://github.com/huggingface/diffusers/blob/a98a839de75f1ad82d8d200c3bc2e4ff89929081/examples/dreambooth/train_dreambooth_lora_sdxl.py#L982

**Comment by Zheng-Fang-CH** [comment]
> Does using this help?
> 
> https://github.com/huggingface/diffusers/blob/a98a839de75f1ad82d8d200c3bc2e4ff89929081/examples/dreambooth/train_dreambooth_lora_sdxl.py#L982

It's helpful, thanks for your reply.

**Comment by sayakpaul** [comment]
Do you want to PR this fix?

**Comment by Zheng-Fang-CH** [comment]
> Do you want to PR this fix?

sure

**Comment by SahilCarterr** [comment]
https://github.com/huggingface/diffusers/blob/a98a839de75f1ad82d8d200c3bc2e4ff89929081/examples/controlnet/train_controlnet_sd3.py#L893C5-L893C72
I think it is already present in the train_controlnet_sd3 @Zheng-Fang-CH

**Comment by a-r-r-o-w** [comment]
I think this issue is resolved, yes? If not please feel free to re-open this issue and we'd be glad to help with any changes!
