### ISSUE TITLE
FluxControlNetModel got not from_single_file()? It's really necessary.

### ISSUE THREAD

**Issue by riflemanl** [huggingface/diffusers#9846]
### Describe the bug

Flux is the most popular model now, but it's huge. If want to works with Union FluxControlNet together, 24GB VRAM is totally OOM. So, we have to use less VRAM option like fp8.  But official ControlNet provider didn't provide fp8, all single providers are providing single file, like Kijai.  So, FluxControlNetModel must implement from_single_file(), I've also tried to use ControlNetModel.from_single_file() to load Kijai's fp8 model file, it's not working, either.

### Reproduction
```python
from diffusers import FluxControlNetPipeline, FluxControlNetModel
control_model = 'https://huggingface.co/Kijai/flux-fp8/blob/main/flux_shakker_labs_union_pro-fp8_e4m3fn.safetensors'
controlnet_union = FluxControlNetModel.from_single_file(control_model, torch_dtype=torch.float8_e4m3fn)
```
----------------------------------------------------------------------------------------------------------------------
Error: AttributeError: type object 'FluxControlNetModel' has no attribute 'from_single_file'

### System Info

PC got 256GB RAM
3090Ti VRAM 24GB
torch 2.5.0 + cuda 12.4
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
accelerate==1.0.1
transformers==4.45.2
diffusers 0.31.0,

**Comment by sayakpaul** [comment]
Cc: @DN6

**Comment by bghira** [comment]
have you tried using requantize api from torchao to make the fp8 model changes with the remapping json as is done in the x-labs flux trainer?

i think just setting the torch dtype this way at load time isn't really supported by Diffusers - there is a quantization API where you would supply a BitsAndBytesConfig or maybe @sayakpaul knows if i've missed on any developments since that time.

for torchao, x-flux trainer is like this:

```py
    model = Flux(configs[name].params).to(torch.bfloat16)

    print("Loading checkpoint")
    # load_sft doesn't support torch.device
    sd = load_sft(ckpt_path, device='cpu')
    with open(json_path, "r") as f:
        quantization_map = json.load(f)
    print("Start a quantization process...")
    requantize(model, sd, quantization_map, device=device)
    print("Model is quantized!")
    return model
```

and quantization_map is a json file containing the dtypes to map. the important part is to leave it on CPU and quantise there if you are low on vram, because it is hit-or-miss for 24G to work w/ quantising Flux.

**Comment by bghira** [comment]
see https://github.com/huggingface/diffusers/issues/9690 as well for an FP8 example

**Comment by bghira** [comment]
the dtype issue is going to be universal. follow the above suggestions and see how it goes.

**Comment by DN6** [comment]
@riflemanl Some clarification here. The checkpoint you've linked is a Diffusers weight format checkpoint that is meant to work with an associated `config.json` file and `from_pretrained`. Single file loading does not apply here as it is used to load checkpoints saved in their original repo format. 

Additionally, as @bghira mentioned. Setting dtype in the way that you have shown will not work as Diffusers doesn't support dynamically upcasting layers to to FP16 like Comfy. We are working on adding support for this and should have a solution soon. 

The best way to use low memory dtypes with Diffusers at the moment would be to use a quantization library such as Quanto, TorchAO or BitsandBytes to quantize the Flux ControlNet before using it with the Diffusers FluxPipeline.

**Comment by yiyixuxu** [comment]
think we can close this one per @DN6 's comment here!
