### ISSUE TITLE
Merge Lora weights into base model

### ISSUE THREAD

**Issue by yaswanth19** [huggingface/diffusers#9847]
I have finetuned the stable diffusion model and would like to merge the lora weights into the model itself. Currently I think in PEFT this is supported using `merge_and_unload` function but I seem to not find this option in diffusers. So is there any way to get a base model but with finetuned weights and If i am not wrong only unet part of model  weights needs to be merged.

This is necessary for the tasks like feature extraction.

**Comment by sayakpaul** [comment]
https://huggingface.co/docs/diffusers/main/en/using-diffusers/merge_loras
