### ISSUE TITLE
Possibly incorrect image normalization step in examples/dreambooth/train_dreambooth.py

### ISSUE THREAD

**Issue by john-sungjin** [huggingface/diffusers#985]
### Describe the bug

I was studying the `train_dreambooth.py` script ([link](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py)) and noticed that the `DreamBoothDataset` performs an image normalization step as one of the transforms (line 260), setting mean to 0.5 and standard deviation to 0.5:

```python
        self.image_transforms = transforms.Compose(
            [
                transforms.Resize(size, interpolation=transforms.InterpolationMode.BILINEAR),
                transforms.CenterCrop(size) if center_crop else transforms.RandomCrop(size),
                transforms.ToTensor(),
                transforms.Normalize([0.5], [0.5]), # <--- this line
            ]
        )
```

However, this seems to differ from the original Stable Diffusion training implementation, which instead rescales image pixel values from [0, 255] to [0, 1] ([link](https://github.com/pesser/stable-diffusion/blob/main/ldm/data/imagenet.py), line 369):

```python
        example["image"] = (image/127.5 - 1.0).astype(np.float32)
        example["LR_image"] = (LR_image/127.5 - 1.0).astype(np.float32)
```

Is there a reason for the discrepancy? Was wondering if this was intended or a bug - it seems like changing the normalization procedure from the original model would impact fine-tuning performance. Thanks for the help!

### System Info

Latest version

**Comment by john-sungjin** [comment]
Realized I was doing the math wrong; the normalizations are definitely the same! My mistake.

**Comment by patrickvonplaten** [comment]
No worries :-)
