### ISSUE TITLE
Put your repo on https://gitee.com/

### ISSUE THREAD

**Issue by baligot** [huggingface/diffusers#9851]
https://gitee.com/ is better than github.

also i cant access hugging face. is the side down???

**Comment by SahilCarterr** [comment]
Hugging Face is not down at the moment, so it might be a localized connectivity issue. Also, just a quick note—comments like this would be more suitable for the Discussions tab rather than here. @baligot

**Comment by baligot** [comment]
no i have been trying for many many days. even from python i download from hub. it does not! 
pls fix @julien-c  @Clement-Lelievre

**Comment by baligot** [comment]
why cant you move to https://gitee.com/  ????

**Comment by baligot** [comment]
worlds biggest companyes all use https://gitee.com/

**Comment by SahilCarterr** [comment]
> no i have been trying for many many days. even from python i download from hub. it does not! pls fix @julien-c @Clement-Lelievre

Can you share the code and the logs for the same

**Comment by Clement-Lelievre** [comment]
@baligot why did you tag me?

**Comment by DN6** [comment]
Closing this as spam.
