### ISSUE TITLE
Flux controlnet can't be trained, do this script really work?

### ISSUE THREAD

**Issue by liuyu19970607** [huggingface/diffusers#9866]
### Describe the bug

run with one num processes, the code broke down and returns:
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 

run with more than one  processes, the code broke down and returns:
Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.

### Reproduction

just follow the instructions and it will be reproduced

### System Info

diffusers v0.32

**Comment by sayakpaul** [comment]
Does it run suitably within a single GPU? Cc: @PromeAIpro

**Comment by PromeAIpro** [comment]
yesterday just tested on release 0.31.0, single a100 80G, works fine. see https://github.com/huggingface/diffusers/issues/9857
need doing test in 0.32.0dev0, could you provide your python-installations and commad line script for me to further debug @liuyu19970607

**Comment by sayakpaul** [comment]
Closing due to inactivities.
