### ISSUE TITLE
Integration of DC-AE (Deep Compression Autoencoder)

### ISSUE THREAD

**Issue by DefinitlyEvil** [huggingface/diffusers#9894]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like.**
As the paper stated, DCAE can achieve awesome results using lower latent dimensions. 
`Deep Compression Autoencoder for Efficient High-Resolution Diffusion Models`
https://github.com/mit-han-lab/efficientvit/blob/master/applications/dc_ae/README.md

**Describe alternatives you've considered.**
Using their repo directly. 

**Additional context.**
N/A

**Comment by sayakpaul** [comment]
https://github.com/huggingface/diffusers/pull/9708

**Comment by DefinitlyEvil** [comment]
> #9708

Cool thanks, following it rn.

**Comment by a-r-r-o-w** [comment]
Marking as closed because this has now been integrated

**Comment by DefinitlyEvil** [comment]
Awesome! <3
