### ISSUE TITLE
Implement `add_noise` in iPNDMScheduler

### ISSUE THREAD

**Issue by pcuenca** [huggingface/diffusers#990]
This method is missing from the recently-added IPNDMScheduler. It's not required for inference, but I think we should add it for consistency with all the others.

TODO:
- [ ] revert 56210ad when this is done.

**Comment by patrickvonplaten** [comment]
Honestly don't think it's that important iPNDMScheduler is only used for dance diffusion which is not heavily used. 

IMO the "for consistency" argument is a dangerous one that might slow us down too much.

**Comment by pcuenca** [comment]
I agree, let's wait until we really need it. I just added this issue because a test failed, will remove the comment instead.
