### ISSUE TITLE
Potential bug in repaint?

### ISSUE THREAD

**Issue by jingweiz** [huggingface/diffusers#9900]
https://github.com/huggingface/diffusers/blob/dac623b59f52c58383a39207d5147aa34e0047cd/src/diffusers/schedulers/scheduling_repaint.py#L322

According to line5 of algorithm 1 in the paper, the second part in line 322 should remove the `**0.5`?
thanks!

**Comment by SahilCarterr** [comment]
I also think that should be removed as mentioned in algorithm 1 Line 5 from the [paper](https://arxiv.org/pdf/2201.09865)
```math
x_{t-1}^{known} \ =\ \sqrt{\overline{\alpha }_{t}} x_0 \ +( 1-\ \overline{\alpha }_{t}) \epsilon
```
Corrected
```python
prev_known_part = (alpha_prod_t_prev**0.5) * original_image + ((1 - alpha_prod_t_prev)) * noise 
```
I don't think Fixing this might cause any issue in RePaintScheduler
@sayakpaul WDYT?
