### ISSUE TITLE
Data type mismatch when using stable diffusion in fp16

### ISSUE THREAD

**Issue by ParadoxZW** [huggingface/diffusers#993]
### Describe the bug

When run following code to try stable diffusion v1.5,
```Python
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained(
       "local_project_path/stable-diffusion-v1-5", 
        torch_dtype=torch.float16, revision="fp16"
)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]  
```
I got the error
```
File "{conda_env_path}/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 260, in forward
    attn_output = torch.bmm(attn_probs, value_states)
RuntimeError: expected scalar type Half but found Float
```

### System Info

- `diffusers` version: 0.6.0
- Platform: Linux-4.4.0-31-generic-x86_64-with-glibc2.27
- Python version: 3.9.11
- PyTorch version (GPU?): 1.12.0 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.20.1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by patrickvonplaten** [comment]
Hey @ParadoxZW, 

Could you try to install `diffusers` from master:

```
pip install git+https://github.com/huggingface/diffusers.git
```

=> I cannot reprodure this error from master

**Comment by vanewu** [comment]
I had the same problem with version 0.6.x.  

![image](https://user-images.githubusercontent.com/27672489/198242228-320118d5-8aaa-41ed-9577-ff77afa85158.png)

**Comment by dblunk88** [comment]
I don't know if that is still the case, but fp16 used to have to be run in autocast

**Comment by vanewu** [comment]
Yes, I added `autocast` and computed in this scope . The problem was solved.

**Comment by dblunk88** [comment]
> Yes, I added `autocast` and computed in this scope . The problem was solved.

That being said, diffusers has been going away from autocast. Devs, any fix for that without using autocast?

**Comment by patrickvonplaten** [comment]
Looking into it!

**Comment by patrickvonplaten** [comment]
I cannot reproduce the error - the code snippet runs fine for me. My version is:

```
- `diffusers` version: 0.7.0.dev0
- Platform: Linux-4.19.0-18-cloud-amd64-x86_64-with-debian-10.13
- Python version: 3.7.12
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0.dev0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

@ParadoxZW could you maybe try to upgrade `transformers` to the newest version - the problem seems to come from `transformers` here actually and not `diffusers`:

```
pip install --upgrade transformers
```

Also @dblunk88 is 100% right, we do **not** recommend using `autocast` anymore - instead one should use "pure" FP16 as is done in the code example above.

**Comment by bonlime** [comment]
upgrading `transformers` worked for me

**Comment by PrinceRay7** [comment]
@patrickvonplaten I'm quite confused. In Diffusers docs, it is strongly disencouraged to use torch.autocast, however, in accelerate scripts, when training with the flag fp16, it is still implemented by using autocast. So i really wonder what should we do when training diffusion models. It seems like accelerate is very necessary and now it conflicts so I'm confused now. Looking forward to your reply, thanks!

**Comment by patrickvonplaten** [comment]
Hey @PrinceRay7,

That's a good question! Thanks for asking it :-) To make it more visible for the community, I'm opening a new issue for it and will reply there. 

See: https://github.com/huggingface/diffusers/issues/2568
