### ISSUE TITLE
Inpainting pipeline with larger resolution?

### ISSUE THREAD

**Issue by juno-hwang** [huggingface/diffusers#995]
Hello,
Rescent inpainting pipeline with explicit mask input is amazing, but it has some incompatible point with the original pipeline.
I think the most important part is resolution, that it only support 512 size.
In my opinion, theoretically new inpainting pipeline can be extended to larger resolution just like the original.
But somewhy it is impossible to feed the image which is not in 512 size.

Are you planning to support larger resolution inpainting model?
If you are not, I'm willing to develope and contribute about this issue.

**Comment by patrickvonplaten** [comment]
That's a good point - did you try passing the `width` and `height` parameter here: https://github.com/huggingface/diffusers/blob/d3d22ce5a894becb951eec03e663951b28d45135/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py#L146 ? 

Does it fail?

**Comment by juno-hwang** [comment]
Oh I'm really sorry, I didn't realize it because the legacy inpainting pipeline didn't required such parameters. Thanks!
