### ISSUE TITLE
got an unexpected keyword argument 'use_cuda_graph'

### ISSUE THREAD

**Issue by pyoliu** [huggingface/diffusers#9962]
### Describe the bug

Cannot import /home/ubuntu/16T/lsm/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper module for custom nodes: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
autotune() got an unexpected keyword argument 'use_cuda_graph'

### Reproduction

python comfyui，Both version 0.31.0 and version 0.28.2 will experience the same issue

### System Info

cuda 12.2
torch 2.3.1
diffuers 0.31.0 / 0.28.2

**Comment by a-r-r-o-w** [comment]
Gentle ping @Kijai. Could you paste the entire stack trace? Currently there is no information where the autotune call or `use_cuda_graph` comes from

**Comment by kijai** [comment]
I have no idea, would need to see the whole stack indeed. Never seen such error before and I'm simply using
 `from diffusers.models import AutoencoderKLCogVideoX` 
 in the code.

**Comment by pyoliu** [comment]
> I have no idea, would need to see the whole stack indeed. Never seen such error before and I'm simply using in the code.`from diffusers.models import AutoencoderKLCogVideoX`

Traceback (most recent call last):
  File "/home/ubuntu/16T/lsm/ComfyUI/nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/16T/lsm/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/ubuntu/16T/lsm/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 8, in <module>
    from diffusers.models import AutoencoderKLCogVideoX, CogVideoXTransformer3DModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/ubuntu/miniconda3/envs/sd3/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/ubuntu/miniconda3/envs/sd3/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
autotune() got an unexpected keyword argument 'use_cuda_graph'

Cannot import /home/ubuntu/16T/lsm/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper module for custom nodes: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
autotune() got an unexpected keyword argument 'use_cuda_graph'

This is the specific information, and then I looked at more than one plugin reporting this error

**Comment by elsatch** [comment]
@pyoliu did you manage to solve it? I am getting a similar error with other plugin and I am not sure if a specific version of diffusers solves the problem.

Thanks in advance

**Comment by puke3615** [comment]
The same:

Cannot import ComfyUI/custom_nodes/ComfyUI-Easy-Use module for custom nodes: autotune() got an unexpected keyword argument 'use_cuda_graph'

**Comment by tin2tin** [comment]
Also got:
autotune() got an unexpected keyword argument 'use_cuda_graph'

But updating triton solved it.

**Comment by TIMESWALKING** [comment]
> Also got: autotune() got an unexpected keyword argument 'use_cuda_graph'
> 
> But updating triton solved it.

me too
