### ISSUE TITLE
Support Lightricks LTX-Video

### ISSUE THREAD

**Issue by hlky** [huggingface/diffusers#9995]
## Lightricks LTX-Video

_LTX-Video is the first DiT-based video generation model capable of generating high-quality videos in real-time. It produces 24 FPS videos at a 768x512 resolution faster than they can be watched. Trained on a large-scale dataset of diverse videos, the model generates high-resolution videos with realistic and varied content. We provide a model for both text-to-video as well as image+text-to-video usecases_

[Model](https://huggingface.co/Lightricks/LTX-Video)
[Code](https://github.com/Lightricks/LTX-Video)

Integration should be fairly straight forward as the original code is based on Diffusers, some changes will be required like rewriting usage of `einops.rearrange`.

**Comment by sayakpaul** [comment]
Assigning this to @a-r-r-o-w and @DN6 as they expressed interest?

**Comment by sayakpaul** [comment]
Of course, this will be super cool to have especially because fine-tuning would be relatively cheaper and will also potentially benefit from many optimization stuff we're planning to add very soon. 

I wonder why does https://huggingface.co/Lightricks/LTX-Video/tree/main not contain any text encoder.

**Comment by hlky** [comment]
> I wonder why does https://huggingface.co/Lightricks/LTX-Video/tree/main not contain any text encoder.

Uses T5-XXL so probably just to avoid the large upload. [Original code](https://github.com/Lightricks/LTX-Video/blob/23f104870f57f31f286a2c6970f995c55b6f505f/inference.py#L310-L312) gets it from `PixArt-alpha/PixArt-XL-2-1024-MS`

**Comment by hlky** [comment]
Closed by #10021
